### PR TITLE
fix: do not escape HTML special chars for an invite's welcomeNote

### PR DESCRIPTION
**Pull request by akinwale**
### Details
This removes the escape operation performed on the welcomeNote.

### Fixed Issues
$ https://github.com/Expensify/App/issues/20081
PROPOSAL: https://github.com/Expensify/App/issues/20081#issuecomment-1588398016

### Tests
1. Launch the app
2. Navigate to Settings > Workspaces
3. Select any Workspace or create a new one
4. Select Members
5. Click on Invite
6. Select a user with a contact number (user who has contact number as primary contact) and click Next. The contact number should be able to receive SMS / text messages
7. Use the default invite message, or write any message containing an apostrophe. Eg: "This is test's message".
8. Click on Invite
9. Verify that the text message received by the contact number contains the actual apostrophes in the invite message, and not escaped HTML sequences.

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as tests.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

20081-web

</details>

<details>
<summary>Mobile Web - Chrome</summary>

20081-android-chrome

</details>

<details>
<summary>Mobile Web - Safari</summary>

20081-ios-safari

</details>

<details>
<summary>Desktop</summary>

20081-desktop

</details>

<details>
<summary>iOS</summary>

20081-ios-native

</details>

<details>
<summary>Android</summary>

20081-android-native

</details>

### CODE REVIEW

**Comment by cristipaval** [comment]
@akinwale Did you manage to test this? I haven't changed the backend yet, and after the first glance, we might not need to do any changes there.

@0xmiroslav Could you also please test this with the other characters that are supposed to be escaped in an HTML string? Let's test all of them for both email and SMS.

**Comment by akinwale** [comment]
> @akinwale Did you manage to test this? I haven't changed the backend yet, and after the first glance, we might not need to do any changes there.

@cristipaval Yes, I did with both an email and SMS recipient. I can include screenshots of the received messages if required.

> @0xmiroslav @akinwale Could you also please test this with the other characters that are supposed to be escaped in an HTML string? Let's test all of them for both email and SMS.

Based on [the documentation for the escape method](https://underscorejs.org/#escape), that means we'll test with these characters:
`&`, `<`, `>`, `"`, ```, and `'`.

**Comment by akinwale** [comment]
@cristipaval @0xmiroslav

Ran the following tests.

### Test 1
It appears that HTML tags are being stripped out by the backend for both emails and SMS (anything between the `<` and `>`characters inclusive) as can be observed from the message in the email and SMS screenshots attached. Also, for only the SMS, backticks were converted to single quotes / apostrophes.

**Invite message**
invite_message_1

**SMS received (last message in thread)**
screenshot

**Email received**
screenshot

### Test 2
For the SMS message, backticks were converted to single quotes. All other characters appear to display fine here.

**Invite message**
invite_message_2

**SMS received (last message in thread)**
screenshot

**Email received**
screenshot

**Comment by cristipaval** [comment]
Thanks a lot for your testing @akinwale.
I'll close this PR though, please see [this](https://github.com/Expensify/App/issues/20081#issuecomment-1614747997) for more info.

**Comment by cristipaval** [comment]
I reopened this after some internal discussions. We want this solution. I'll add a HOLD on this PR because we need a [Web-PR](https://github.com/Expensify/Web-Expensify/pull/38012) deployed before merging this one.

**Comment by cristipaval** [comment]
FYI: We're close to get the [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/38012) merged.

**Comment by cristipaval** [comment]
This is off hold. @akinwale Could you please merge latest main into this branch and make it ready for @0xmiroslav to test?

**Comment by akinwale** [comment]
> 

@cristipaval Done!

**Comment by akinwale** [comment]
@0xmiroslav This is ready for review. Thanks.

**Comment by akinwale** [comment]
> Workspace invite message not received from SMS. @akinwale did you test?

@0xmiroslav Yes, I did, and I received the SMS messages as expected, as well as the email.
Perhaps it could be due to mobile provider delivery delays or issues.

**Comment by cristipaval** [comment]
> Workspace invite message not received from SMS. @akinwale did you test?

Wait, I think we limited Twilio to some countries only in staging. @0xmiroslav  Could you please try in dev?

**Comment by cristipaval** [comment]
> > Could you please try in dev?
> 
> You mean api point to production?

Sorry, I'm stupid... you don't have access to dev backend.
@0xmiroslav @akinwale Could you both tell me what country codes your phone numbers have?

**Comment by akinwale** [comment]
> > > Could you please try in dev?
> > 
> > 
> > You mean api point to production?
> 
> Sorry, I'm stupid... you don't have access to dev backend. @0xmiroslav @akinwale Could you both tell me what country codes your phone numbers have?

@cristipaval US country code for mine.

**Comment by cristipaval** [comment]
That's why it works for you, @akinwale 👍

**Comment by cristipaval** [comment]
I can do the sms screenshot for you, @0xmiroslav

**Review by 0xmiroslav — APPROVED** [review]
@cristipaval all yours

**Review by cristipaval — APPROVED** [review]

**Comment by Pluto0104** [comment]
Hi, guys. did you test on Web browser? It seems that this causes a regression. @akinwale @0xmiroslav @cristipaval please see https://github.com/Expensify/App/issues/27290

**Comment by pradeepmdk** [comment]
@Pluto0104 I think this bug does not create a regression there. here they are fixing just remove the _.escape keyword.

**Pull request merged**
