### PR TITLE
fix Locale Picker and small picker styles

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

1. Removed API call.
2. Fixed the Picker style so that it shows a blue border while focused.
3. Fixed picker style on Firefox browsers. https://expensify.slack.com/archives/C01GTK53T8Q/p1629962984011400

### Fixed Issues

$ https://github.com/Expensify/App/issues/4513

### Tests | QA Steps
1. Open the login page & sign in with some account.
2. Sign out of the app.
3. Switch a language.
4. Language should change.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

locale-wd

#### Mobile Web

locale-m

#### Android

locale-a

### CODE REVIEW

**Review by Beamanator — COMMENTED** [review]
Removed API call.
- 👍 looks great, no extra, useless API calls
Fixed the Picker style so that it shows a blue border while focused.
- 👍 confirmed on web
Fixed picker style on Firefox browsers. https://expensify.slack.com/archives/C01GTK53T8Q/p1629962984011400
- 👍 looking good on Preferences page & elsewhere! Still looks good on other browsers too

A few code comments though

**Review by Beamanator — APPROVED** [review]
LGTM 👍

**Comment by shawnborton** [comment]
@parasharrajat just double checking here - what does the picker look like when it is not active? It seems like the styles are still a little off - I think when the picker is active, the border color should change instead of an additional blue border being added. Let me know if that makes sense.

**Comment by parasharrajat** [comment]
When picker is not active it shows gray border like other input in app. There are two borders arround the picker. I changed the colour or outer border but didn't know that there were two  borders. So In a follow up I will remove the inner border.

**Pull request merged**
