### PR TITLE
feat: Provide education/confirmation before creating workspaces in New Workspace flows

### PR DESCRIPTION
**Pull request by Krishna2323**
### Explanation of Change
- Problem: When users attempting to submit expenses are inadvertently led to create workspaces, it causes confusion about how to submit an expense to their boss, leading to frustration and a poor user experience.
- This PR adds a workspace confirmation page which will be shown before a workspace is created. Workspace confirmation page will have avatar picker, name input and currency selector, users can now choose custom avatar, workspace name and currency before creating a workspace.

### Fixed Issues
$ https://github.com/Expensify/App/issues/51504
PROPOSAL: https://github.com/Expensify/App/issues/51504#issuecomment-2445925882

### Tests
1. Go to workspace lists page > Click on `Create workspace` 
2. Verify RHP is opened with avatar selector, name input and currency selector.
3. Select any avatar > Enter custom name > Select a different currency
4. Click confirm 
5. Verify workspace is created with the selected avatar, name and currency.
6. Repeat Step 1 to 4 with default avatar
7. Verify workspace is created with the default avatar, name and currency.
8. Repeat Step 1 to 4 with default currency 
9. Verify workspace is created with the selected avatar, name and default currency.
10. Click on `Create workspace` > Enter any custom name
11. Verify default avatar uses the first character of the name.
12. Log out and login with a new account > Complete onboarding
13. Open FAB > Select `New workspace` > Verify RHP is opened with avatar selector, name input and currency selector.
14. Select any avatar > Enter custom name > Select a different currency
15. Click confirm 
16. Verify workspace is created with the selected avatar, name and currency.
17. Delete the single workspace from workspace list page 
18. On workspace list page click `New Workspace` button 
19. Verify RHP is opened with avatar selector, name input and currency selector.
20. Select any avatar > Enter custom name > Select a different currency
21. Click confirm 
22. Verify workspace is created with the selected avatar, name and currency.

- [x] Verify that no errors appear in the JS console

### Offline tests
1. Go to workspace lists page > Click on `Create workspace` 
2. Verify RHP is opened with avatar selector, name input and currency selector.
3. Select any avatar > Enter custom name > Select a different currency
4. Click confirm 
5. Verify workspace is created with the selected avatar, name and currency.
6. Repeat Step 1 to 4 with default avatar
7. Verify workspace is created with the default avatar, name and currency.
8. Repeat Step 1 to 4 with default currency 
9. Verify workspace is created with the selected avatar, name and default currency.
10. Click on `Create workspace` > Enter any custom name
11. Verify default avatar uses the first character of the name.
12. Log out and login with a new account > Complete onboarding
13. Open FAB > Select `New workspace` > Verify RHP is opened with avatar selector, name input and currency selector.
14. Select any avatar > Enter custom name > Select a different currency
15. Click confirm 
16. Verify workspace is created with the selected avatar, name and currency.
17. Delete the single workspace from workspace list page 
18. On workspace list page click `New Workspace` button 
19. Verify RHP is opened with avatar selector, name input and currency selector.
20. Select any avatar > Enter custom name > Select a different currency
21. Click confirm 
22. Verify workspace is created with the selected avatar, name and currency.

### QA Steps
1. Go to workspace lists page > Click on `Create workspace` 
2. Verify RHP is opened with avatar selector, name input and currency selector.
3. Select any avatar > Enter custom name > Select a different currency
4. Click confirm 
5. Verify workspace is created with the selected avatar, name and currency.
6. Repeat Step 1 to 4 with default avatar
7. Verify workspace is created with the default avatar, name and currency.
8. Repeat Step 1 to 4 with default currency 
9. Verify workspace is created with the selected avatar, name and default currency.
10. Click on `Create workspace` > Enter any custom name
11. Verify default avatar uses the first character of the name.
12. Log out and login with a new account > Complete onboarding
13. Open FAB > Select `New workspace` > Verify RHP is opened with avatar selector, name input and currency selector.
14. Select any avatar > Enter custom name > Select a different currency
15. Click confirm 
16. Verify workspace is created with the selected avatar, name and currency.
17. Delete the single workspace from workspace list page 
18. On workspace list page click `New Workspace` button 
19. Verify RHP is opened with avatar selector, name input and currency selector.
20. Select any avatar > Enter custom name > Select a different currency
21. Click confirm 
22. Verify workspace is created with the selected avatar, name and currency.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/43a33876-97a8-4566-bcc4-3c9e67e24b56

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/380f3369-e467-421c-b2ba-70712bb9d6c9

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/eebdc027-5683-4218-945a-a6eac4da8830

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/a8e9fb52-63b1-4868-a19c-c27cd18af908

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/357c0bb6-b651-4636-9796-33b33e2cde57

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/68bbccce-abf7-47e2-ac8f-f517ba58a5f3

</details>

### CODE REVIEW

**Comment by dubielzyk-expensify** [comment]
Let me know when this is ready to review from a design standpoint?

**Comment by grgia** [comment]
Pulling locally to test the flow

**Review by allgandalf — CHANGES_REQUESTED** [review]
@Krishna2323 overall LGTM, minor comments. Also please do the following:

1. Merge main
2. There is also a way to create workspace from track expense have you tested if that works expected  ?

**Review by allgandalf — COMMENTED** [review]
Alright this looks great!! thanks for all the work here @Krishna2323 .

> Let me know when this is ready to review from a design standpoint?

@dubielzyk-expensify @Expensify/design this is ready for your review.  I will approve this PR after design team approves, The latest builds are [here](https://github.com/Expensify/App/pull/52164#issuecomment-2511860931).

Also A very nitpick, Should we also make the profile icon scrollable ? currently on small screens only the input fields are scrollable:


https://github.com/user-attachments/assets/cd141067-02fe-46cf-9214-f62d8f2020ab

**Comment by grgia** [comment]
> Also A very nitpick, Should we also make the profile icon scrollable ? currently on small screens only the input fields are scrollable:

@allgandalf nice catch! Instinctively I want to say yes, curious what @dubielzyk-expensify will say 😁 

Either way NAB

**Comment by shawnborton** [comment]
Yes, the entire view should be scrollable.

**Comment by shawnborton** [comment]
It looks like the top text doesn't match the mock, which uses our textSupporting color. Here is the mock:
image

**Comment by shawnborton** [comment]
@jamesdeanexpensify are you cool with the double hyphen? Why not use an em dash instead?
CleanShot 2024-12-03 at 08 20 47@2x

**Comment by dannymcclain** [comment]
>are you cool with the double hyphen?

I will not rest until the double hyphen is no more 😆

**Comment by jamesdeanexpensify** [comment]
Em dash for sure!

**Comment by shawnborton** [comment]
> please verify the em dash and description text color:

Looks good to me.

However, the green button should be docked to the bottom of the view right?

**Comment by dannymcclain** [comment]
>please verify the em dash

This is the **most** nit picky possible thing, but I think when using em dashes, typically you don't include spaces on either side 🤓 (I don't feel super strongly, just being a nerd)

>However, the green button should be docked to the bottom of the view right?

Yeah I would think it would be docked to the bottom as well—our classic footer button.

**Comment by jamesdeanexpensify** [comment]
I would actually keep spaces on either side of the em dash just for some breathing room. We can say it's "our style" hehe.

**Comment by dubielzyk-expensify** [comment]
The padding below the button looks very big to me? 
CleanShot 2024-12-05 at 09 54 28@2x

Let's make sure we're using the same component and positioning as all our other footer button screens (Profile settings etc)

**Comment by shawnborton** [comment]
Cool, I'll run another test build for us.

**Comment by shawnborton** [comment]
The test builds look good to me. 

On iOS, the green Save button is sitting slightly below the keyboard but that's probably okay since the content is technically long enough to make a scrollable page. I guess we could switch up the style to force the green button to be always attached to the bottom of the view? 
CleanShot 2024-12-05 at 15 31 18@2x

**Comment by dannymcclain** [comment]
>I guess we could switch up the style to force the green button to be always attached to the bottom of the view?

I don't think I feel super strongly either way.

**Comment by shawnborton** [comment]
I think we can just leave this as-is, let's get this merged first and we can always follow up if we feel that it's necessary to change.

**Review by allgandalf — APPROVED** [review]
great work and collaboration here from everyone 🚀 , lets get this one shipped

**Review by grgia — APPROVED** [review]
Great work on this!

**Comment by luacmartins** [comment]
Thanks! For a list of all blockers caused by this PR, please see the revert [here](https://github.com/Expensify/App/pull/52164)

**Pull request merged**
