### PR TITLE
Position tolltip in appropriate place

### PR DESCRIPTION
**Pull request by sobitneupane**
### Details

Solves the issue of tooltip positioning. The issue is occurring in Web and Desktop App. I have tested on Web and would like to request reviewer to double check on Desktop App as I don't have access to macOS. Thanks.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7481

### Tests

- Create an account using a very long email address. 
- Create two other accounts with short first names
- From a fourth account, create a group chat will all three accounts from the previous two steps.
- Send a message in the group chat.
- Open the search page and search for the group chat.
- Hover over the long email address

### QA Steps

- Create an account using a very long email address. 
- Create two other accounts with short first names
- From a fourth account, create a group chat will all three accounts from the previous two steps.
- Send a message in the group chat.
- Open the search page and search for the group chat.
- Hover over the long email address

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

Screenshot from 2022-02-04 14-07-44
Screenshot from 2022-02-04 14-07-40
Screenshot from 2022-02-04 14-07-30
Screenshot from 2022-02-04 14-07-25
Screenshot from 2022-02-04 14-07-14
Screenshot from 2022-02-04 14-07-06
Screenshot from 2022-02-04 14-07-01
Screenshot from 2022-02-04 14-06-54
Screenshot from 2022-02-04 14-06-40

### CODE REVIEW

**Comment by rushatgabhane** [comment]
> would like to request reviewer to double check on Desktop App as I don't have access to macOS

@sobitneupane That's alright for this PR I've added screenshot for desktop. 

But FYI, tests on all platforms will be mandatory for any future PRs.
So I suggest that you get access to MacOS with the help of [this document](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms), VMs, Macbook air etc.

image
Screen Shot 2022-02-04 at 2 35 52 PM

**Comment by rushatgabhane** [comment]
@sobitneupane One last thing, can you please modify the tests and qa to be more aligned with the issue?
Use the original issue for reference. Cheers.

**Comment by sobitneupane** [comment]
> @sobitneupane One last thing, can you please modify the tests and qa to be more aligned with the issue? Use the original issue for reference. Cheers.

Updated.

**Review by rushatgabhane — APPROVED** [review]
LGTM! 🎉 Tests well on web (chrome and safari xD) and desktop.
Tested mobile for any crashes.

cc: @mountiny

**Review by mountiny — APPROVED** [review]
Nice job everyone! Thank you!

**Pull request merged**
