### PR TITLE
Update E-common

### PR DESCRIPTION
**Pull request by parasharrajat**
@Beamanator Please review.

### Fixed Issues

Fixes Following issues
 #4188
 Expensify/App#4066
 Expensify/App#4169
 
#### 1
 1. Open e.cash in Web
 2. Navigate to a conversation that has some messages
 3. In a message that only contains text, use the copy function. For web, hover over the message and a menu should appear
 4. Paste the message in a text box (Should be tested on Windows Web). NO emptty lines should appended and prepended.
 
#### 2 
 1. Navigate to a conversation that has some messages.
 2. Edit a message that contains &. & should be shown as & not `&amp;`.
 
#### 3 
 1. Navigate to a conversation that has some messages.
 2. Paste the Text from MAC Note.app to the composer. No css should be pasted including other metadata.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by Beamanator** [comment]
Hmm I copied some basic text from the Notes app and didn't see css or metadata, but I did see a bunch of preceding empty lines - I think this passes since the empty lines also exists in the staging app

Screen Shot 2021-08-02 at 1 27 30 PM

**Review by Beamanator — APPROVED** [review]
Looks solid! 👍

**Comment by parasharrajat** [comment]
so that whitespace seems a different issue. I will look into it separately.

**Comment by Beamanator** [comment]
Merging since there's no code change here, and changing expensify-common hash tested well 👍

**Pull request merged**
