### PR TITLE
Fix/make emojis larger in other contexts

### PR DESCRIPTION
**Pull request by josemak25**
### Details

This solution covers several related scenarios:
#### Action Performed:
Add an emoji with other plain text characters in a message in the composer.

#### Expected Result:
The emoji should be larger (19pt) compared to the default size for text (15pt) in the composer. The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji (like the right-hand-side of https://github.com/Expensify/App/issues/4114#issuecomment-1078143131.

> ***Solution does not cover this case as handling emojis inside the input is a bit tricky***

#### Action Performed:
Send a message with emojis and text.

#### Expected Result:
The emoji should be larger (19pt) compared to the default size for text (15pt) in the chat history. The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji (like the right-hand-side of https://github.com/Expensify/App/issues/4114#issuecomment-1078143131

> ***Solution covers this case***

#### Action Performed
Draft a message (of any length) with only an emoji.

#### Expected Result:
The emoji should appear very large (27pt) in the composer.

> ***Solution does not cover this case as handling emojis inside the input is a bit tricky***

#### Action Performed
Send a message (of any length) with only emoji.

#### Expected Result:
The emoji should appear very large (27pt) in the report history.

> ***Solution covers this case***

#### Action Performed
Go to `Settings` -> Profile and add emoji(s) to your last name 😎

#### Expected Result:
The emoji should appear larger (19pt) than the rest of the text (15pt) in the text input. The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji (like the right-hand-side of https://github.com/Expensify/App/issues/4114#issuecomment-1078143131

> ***Solution does not cover this case as handling emojis inside the input is a bit tricky***

#### Action Performed
1. Go to `Settings` -> `Profile` and add emoji(s) to your last name 😎.
2. Save your profile.
3. Open the `Settings` RHP and look at your name:

#### Expected Result:
The emoji should appear larger (21pt) than the rest of the text (17pt) in the text input. The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji (like the right-hand-side of https://github.com/Expensify/App/issues/4114#issuecomment-1078143131

> <span style="color:green">***Solution covers this case***</span>

#### Action Performed

1. Go to `Settings` -> `Profile` and add emoji(s) to your last name 😎.
2. Save your profile.
3. Open a chat with another user and send them a message. Take a look at your message in the report history.

#### Expected Result:
The emoji should appear larger (19pt) than the rest of the test (15pt). The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji (like the right-hand-side of https://github.com/Expensify/App/issues/4114#issuecomment-1078143131

> ***Solution covers this case***

### Fixed Issues

$ https://github.com/Expensify/App/issues/4114

### Tests

   1. The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji
   2. Draft a message (of any length) with only emoji the emoji should appear very large (27pt) in the composer.
   3. Go to Settings -> Profile and add emoji(s)[😎] to your last name or first name and save your profile. now open the settings RHP and look at your name, the emoji appear to be bigger in size than the text.
- [x] Verify that no errors appear in the JS console

### QA Steps

   1. The emoji and text should appear vertically centered with respect to each other, such that the baseline of the emoji is below the plain text and the middle of the text vertically aligns with the middle of the emoji
   2. Draft a message (of any length) with only emoji the emoji should appear very large (27pt) in the composer.
   3. Go to Settings -> Profile and add emoji(s)[😎] to your last name or first name and save your profile. now open the settings RHP and look at your name, the emoji appear to be bigger in size than the text.
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Chrome Web</summary>

https://user-images.githubusercontent.com/33870502/220120140-d5943671-4816-48cd-9903-4b499880cdb5.mov

</details>

<details>
<summary>Safari Web</summary>

https://user-images.githubusercontent.com/33870502/220120214-f953ddb4-a1df-494d-a05f-098fa96175d9.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/33870502/220120634-a78792d9-27ec-4d9d-ad5c-8c95b7e2c8e3.mov
</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/33870502/220120341-43cb24bd-d9e8-4535-b357-30aec4cdb7da.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/33870502/220121807-0ad21fb6-4e5a-45c8-907a-25bfa71fc54b.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/33870502/220120814-7283f403-0857-4ec3-83aa-1bcb0ab19658.mp4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/33870502/220120774-a75321f3-51e2-49ab-8535-175e1843e6b9.mov

</details>

### CODE REVIEW

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Unfortunately, commits are still unsigned on this. https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Let us know if you need any help on this.

**Review by parasharrajat — CHANGES_REQUESTED** [review]
@josemak25 Can you please update the Details section on the PR indicating which scenarios have you solved in this PR and which are not?

you can find all needed scenarios on https://github.com/Expensify/App/issues/4114#issue-946385786

**Comment by josemak25** [comment]
> @josemak25 Can you please update the Details section on the PR indicating which scenarios have you solved in this PR and which are not?
> 
> you can find all needed scenarios on [#4114 (comment)](https://github.com/Expensify/App/issues/4114#issue-946385786)

The requested changes has been added please confirm if it's okay

**Comment by roryabraham** [comment]
@josemak25 this PR includes a lot of commits that it should not. Let's once more create a fresh PR with just the commits and changes that are relevant to this issue. This time, please make sure that all your commits are signed before creating the pull request. You can set up automatic commit signing so you don't have to think about it.

**Comment by josemak25** [comment]
> @josemak25 this PR includes a lot of commits that it should not. Let's once more create a fresh PR with just the commits and changes that are relevant to this issue. This time, please make sure that all your commits are signed before creating the pull request. You can set up automatic commit signing so you don't have to think about it going forward

@roryabraham here is the new PR as requested https://github.com/Expensify/App/pull/15611

**Pull request closed without merging**
