### PR TITLE
Add log on bootsplash hide success

### PR DESCRIPTION
**Pull request by zoontek**
### Details

Following https://github.com/Expensify/App/issues/5620

As some users still stucks on the splash screen, this PR add a log on `hide` promise resolve to determine if:
- The promise is resolved immediately, then the splash screen is initialized after that.
- The promise stays forever in pending state and is never resolved (the task is added to the queue but never removed).

### Fixed Issues

$ https://github.com/Expensify/App/issues/5620

(This does not fix it, just add more logs)

### Tests

1. Start the app
2. Check the logs
3. `[BootSplash] hiding succeeded` will appear if the splash screen fade

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by kidroca** [comment]
If we're adding more logs, adding the current app state, could help as well: https://github.com/Expensify/App/issues/5620#issuecomment-999472321

**Comment by kidroca** [comment]
> As some users still stucks on the splash screen, this PR add a log on `hide` promise resolve to determine if:
> 
> * The promise is resolved immediately, then the splash screen is initialized after that.
> * The promise stays forever in pending state and is never resolved (the task is added to the queue but never removed).

Seeing the logs how would you differentiate whether the promise was resolved immediately or after 3 sec. 
All the timestamps in the log are from the same second `14:08:37` even though we use `setTimeout` with 30 sec. I think it's the time they were received on the server

I mean we can only see whether the promise resolved or not

**Comment by zoontek** [comment]
@kidroca Yes, that's what I want to check (the promise might not resolve if it's added to the queue but never played)

**Comment by NikkiWines** [comment]
@zoontek sorry for the delay on this one - do we still need this now that we've merged your other PR bumping the version?

**Comment by zoontek** [comment]
@NikkiWines We might if the issue persists (again, it's only suppositions). Let's keep this unmerged for now

**Comment by NikkiWines** [comment]
Closing this as the main issue has been resolved 🎉

**Pull request closed without merging**
