### PR TITLE
Add webpack bundle analyzer to help minimize JS bundle size

### PR DESCRIPTION
**Pull request by marcaaron**
cc @AndrewGable @Julesssss @tgolen 

### Details

This tool is incredible. 

Separately, it would be interesting to maybe integrate this somehow so that we are pinged when the bundle size increases by a certain amount with a generated image. For now, just want to add it to `devDependencies`.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/153830

### Tests
1. `npm i`
2. Run `npm run analyze-packages`
3. Verify you see the output in your browser that looks like this
Screen Shot 2021-02-08 at 9 46 21 AM
4. Run `npm run build` and verify you do not see the output and the script terminates after building.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by tgolen** [comment]
Rather than the test steps that you have which require manually changing the code and running a script, could it instead be a separate npm script like `npm run analyze_packages` (or something) and not require any manual code changes by passing a custom argument to webpack?

**Comment by marcaaron** [comment]
>could it instead be a separate npm script like npm run analyze_packages (or something) and not require any manual code changes by passing a custom argument to webpack?

Ooh that's a good idea. Maybe this dev feature would be less "hidden" in the code then and might be something you can stumble upon when testing out the different npm scripts.

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
Awesome tool. Can see why Moment was worth killing!

It would be interesting to experiment with the `generateStatsFile` option to generate a file we could check for large increases as a GH Action.

**Comment by tgolen** [comment]
That's a cool idea, Jules!

**Comment by AndrewGable** [comment]
Is there a way we could run this for clients other than web? Does the speed of boot time effect those clients similarly to web?

**Comment by marcaaron** [comment]
@AndrewGable Oh hmm good thought. I guess in theory I'd expect the metro bundler to work similar to webpack, but hadn't thought about it much. There is this package which we could also add -> https://github.com/IjzerenHein/react-native-bundle-visualizer

>Does the speed of boot time effect those clients similarly to web?

I'd have to dig to get a more solid answer to that question since I'm admittedly less familiar with how JS works when it doesn't run inside node or a browser. My _guess_ would be that having a smaller bundle will mean a smaller app bundle size overall for downloading. And likely would mean less JS to load into memory and parse when the app boots.

More info here but I haven't dug super deeply into the suggestions here yet -> https://reactnative.dev/docs/ram-bundles-inline-requires

**Comment by tgolen** [comment]
My guess is that this would be specific to web because I think all other
platforms bundle the JS in with the application so that it doesn't need to
be downloaded on demand like it does for web. I think there are typically
two big performance bottlenecks when it comes to the JS bundle size:

1. Downloading the JS bundle
2. The JS engine evaluating the code before running it

Decreasing the bundle size will improve both of those bottlenecks, but I
think that the first bottleneck only applies to web. The second bottleneck
doesn't have very much overhead, but I think it would still exist for every
platform. The second bottleneck definitely has a point of diminishing
returns and I don't think it's something we need to be too concerned about
at this point.

**Review by madmax330 — APPROVED** [review]

**Pull request merged**
