### PR TITLE
Fix/26470: Input focus is not working while coming from ws

### PR DESCRIPTION
**Pull request by DylanDylann**
### Details

Input focus is not working properly while coming from directly from WS
### Fixed Issues

$ https://github.com/Expensify/App/issues/26470
PROPOSAL: https://github.com/Expensify/App/issues/26470#issuecomment-1707723170

### Tests

1. go to any chat
2. send some messages
3. observe focus is working fine
4. no go to any workspace(create if not have -(Profile setting->workspace))
5. then select three dots which is top most right
6. go to #announce
7. write some text
8. observe the focus
- [x] Verify that no errors appear in the JS console

### QA Steps

1. go to any chat
2. send some messages
3. observe focus is working fine
4. no go to any workspace(create if not have -(Profile setting->workspace))
5. then select three dots which is top most right
6. go to #announce
7. write some text
8. observe the focus
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

[Screencast from 12-09-2023 14:47:09.webm](https://github.com/Expensify/App/assets/141406735/9af6e49f-dd75-41fc-877b-761957a15116)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/141406735/7f089139-88c4-47ce-a79e-b98e2742a8bb

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/141406735/d68d6c93-011d-47be-9bbf-7bc55a3ab020

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/141406735/454dc6ca-3d30-4e4b-b08f-791342a78dc0

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/141406735/42783961-df71-4c77-8172-7720c906ae64

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/141406735/01a09fa1-0eb1-4f8a-8a75-a80713cce156

</details>

### CODE REVIEW

**Comment by DylanDylann** [comment]
@sobitneupane Please help review this PR

**Review by sobitneupane — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://github.com/Expensify/App/assets/25876548/545efb4c-2248-4731-908a-4b180e1b00a9
</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://github.com/Expensify/App/assets/25876548/50717508-c374-4417-af73-6fbdddaa4a24


</details>

<details>
<summary>Mobile Web - Safari</summary>



https://github.com/Expensify/App/assets/25876548/0a09ed09-6846-46ed-aa8a-475ecc0369d3

</details>

<details>
<summary>Desktop</summary>



https://github.com/Expensify/App/assets/25876548/444bb099-db7f-4b52-8aba-fddc5eefc8a2

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/25876548/72f54c79-573e-4608-bb37-3a0aa909c905

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/25876548/ae7ceb2c-b83b-4793-8129-a2b95f139907

</details>

**Review by sobitneupane — COMMENTED** [review]
While testing I found some unusual behavior in small screen device, the composer text input focuses sometime and mostly it doesn't focus. It doesn't look related to this PR.

**Comment by DylanDylann** [comment]
> While testing I found some unusual behavior in small screen device, the composer text input focuses sometime and mostly it doesn't focus. It doesn't look related to this PR.

Currently, We are using this condition to check if we auto focus on composer or not: 
https://github.com/Expensify/App/blob/1e33428d3dcb968f501c3d5309b95898fb5bdb8c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L114
- With the mobile device, the ```shouldAutoFocus``` is just true if the report is empty

**Comment by DylanDylann** [comment]
Bump @sobitneupane

**Comment by DylanDylann** [comment]
@Beamanator Please help check this PR

**Comment by sobitneupane** [comment]
@Beamanator Is it expected to autofocus empty chats (in this case #admins and #announce) in small screen device?

**Comment by DylanDylann** [comment]
@sobitneupane FYI https://github.com/Expensify/App/blob/1e33428d3dcb968f501c3d5309b95898fb5bdb8c/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L427-L429

**Comment by sobitneupane** [comment]
@DylanDylann In that case, we should not open keyboard on native platforms even after the modal closes. Let's handle the issue.

**Comment by DylanDylann** [comment]
> @DylanDylann In that case, we should not open keyboard on native platforms even after the modal closes. Let's handle the issue.

Which case? Please give me more detail

**Comment by sobitneupane** [comment]
> // We want to focus or refocus the input when a modal has been closed or the underlying screen is refocused. 
 // We avoid doing this on native platforms since the software keyboard popping 
 // open creates a jarring and broken UX.
 
 We want to avoid focusing the input when a modal has been closed in native platforms but if you go through the attached [screen recordings](https://github.com/Expensify/App/pull/27219#pullrequestreview-1624169155), you can notice that we are focusing input on native as well which is not expected according to above comment.

**Comment by DylanDylann** [comment]
> > // We want to focus or refocus the input when a modal has been closed or the underlying screen is refocused.
> > // We avoid doing this on native platforms since the software keyboard popping
> > // open creates a jarring and broken UX.
> 
> We want to avoid focusing the input when a modal has been closed in native platforms but if you go through the attached [screen recordings](https://github.com/Expensify/App/pull/27219#pullrequestreview-1624169155), you can notice that we are focusing input on native as well which is not expected according to the above comment.

So you mean that in the native device, we will avoid the composer focusing when the modal is closed regardless the report is empty or not, right?

**Comment by sobitneupane** [comment]
Do we focus empty chats when user navigate to it from LHN in native platforms? If yes, I believe it should focus. Else, it shouldn't. I am not sure what is the expected behavior. So, waiting for confirmation from @Beamanator on [this](https://github.com/Expensify/App/pull/27219#issuecomment-1719751905).

**Comment by DylanDylann** [comment]
> Do we focus empty chats when user navigate to it from LHN in native platforms? If yes, I believe it should focus. Else, it shouldn't. I am not sure what is the expected behavior. So, waiting for confirmation from @Beamanator on [this](https://github.com/Expensify/App/pull/27219#issuecomment-1719751905).

@Beamanator please help confirm

**Comment by DylanDylann** [comment]
@Beamanator  bump

**Comment by Beamanator** [comment]
shit, sorry for the delay - will review today 🙏

**Comment by Beamanator** [comment]
Looks like the main question is:

> @Beamanator Is it expected to autofocus empty chats (in this case #admins and #announce) in small screen device?

Good question, let's go with what we have today - on my iOS device any time I open a chat report (#admins, #announce, group chat, 1:1, room, etc) I DO NOT see autofocusing chats, so I think we should not autofocus empty chats either, yeah?

I do see when you START a brand new chat, we auto-focus the input on iOS, but opening empty #admins / #announce rooms does NOT auto-focus inputs

**Comment by DylanDylann** [comment]
@Beamanator @sobitneupane Currently, this issue is fixed by https://github.com/Expensify/App/pull/27317. With this fix[https://github.com/Expensify/App/pull/27317](url), modal.isVisible is also set to false before go to #admin/#announce report

**Comment by DylanDylann** [comment]
BUMP @Beamanator

**Comment by sobitneupane** [comment]
@DylanDylann Let's merge it with main and retest to see if we get the expected output.

**Comment by DylanDylann** [comment]
> @DylanDylann ~Let's merge it with main and retest to see if we get the expected output.~
> 
> Oh I see. So, this PR won't be required any longer, right?

yeb

**Comment by DylanDylann** [comment]
@Beamanator BUMP

**Comment by Beamanator** [comment]
@DylanDylann please add more in your messages than BUMP - what exactly do you want me to look at? @sobitneupane already responded to your tags, what do you think is next? Please help push this along without just saying "BUMP @Beamanator". I'd recommend you try to understand that this PR is a very small change to a very niche flow that is not nearly as high priority as other things going on in this company. I'm not purposefully ignoring your bumps, I'm working hard on other tasks that I believe are higher priority, so I get back to this when I can. This is all I'm going to say about this matter, but feel free to reach out if you have questions / concerns.

@sobitneupane are we planning to close this PR?

**Comment by sobitneupane** [comment]
I'll verify whether the problem has been resolved in the main branch, and if it is, we can proceed to close this pull request.

**Comment by DylanDylann** [comment]
> please add more in your messages than BUMP - what exactly do you want me to look at? @sobitneupane already responded to your tags, what do you think is next? Please help push this along without just saying "BUMP @Beamanator". I'd recommend you try to understand that this PR is a very small change to a very niche flow that is not nearly as high priority as other things going on in this company. I'm not purposefully ignoring your bumps, I'm working hard on other tasks that I believe are higher priority, so I get back to this when I can. This is all I'm going to say about this matter, but feel free to reach out if you have questions / concerns.

Thanks for your remainder, I noted that

**Comment by sobitneupane** [comment]
Keyboard doesn't open in android when we access #admins or #announce room through the workspace. It is quite different issue. So, I think we can close this PR.


### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/25876548/cbc8fe28-e8df-4607-9e5c-a39880736fb9

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/25876548/5e49eb06-08b0-452d-a0b5-00c95beda631


</details>

<details>
<summary>Mobile Web - Safari</summary>



https://github.com/Expensify/App/assets/25876548/b8a593f1-772a-4943-bb25-19d2ee2df795


</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/25876548/1dee3e3f-9a1a-4971-bbab-df6be1a22126


</details>



<details>
<summary>Android</summary>



https://github.com/Expensify/App/assets/25876548/c531ec99-73aa-4bdc-8df2-16c73218e73c


</details>

**Comment by DylanDylann** [comment]
@sobitneupane Can I close this PR?

**Comment by sobitneupane** [comment]
Yes @DylanDylann. You can close the PR.

**Pull request closed without merging**
