### PR TITLE
Optimize the first rendering of the report main view and the report actions view

### PR DESCRIPTION
**Pull request by tgolen**
This fixes https://github.com/Expensify/ReactNativeChat/issues/443 I hope. I wasn't able to reproduce the problem locally, so maybe one of you are able to?

This PR adds an HOC which will allow a component to render a collection in batches. In the case of the report main view, the batches are based off of first the visible reports, then 5 seconds later, the rest of the reports. On the report actions view, the first batch is 100 comments, then 5 seconds later, the rest of the comments.

# Tests
1. From a cold boot of the app, sign in, and search with the chatpicker
1. Verify it is very very fast to do so

### CODE REVIEW

**Review by marcaaron — CHANGES_REQUESTED** [review]
Thanks for taking a crack at this @tgolen. It took me a while to wrap my head around how `withBatchedRendering` works, but I appreciate what you’ve done here so far.

Now, my instinct is that this HOC may point to a deeper problem somewhere else in the code. And I wonder if we really need it at all. However, I haven’t investigated performance issues yet so I won't share any wild guesses right now. And I won't block this solution if it's the glue that gets us from A to B.

I did spot a few problems that we should address and had a few suggestions for how to improve things.

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Review by marcaaron — DISMISSED** [review]

**Review by roryabraham — CHANGES_REQUESTED** [review]
Overall looks good, just the one DRY comment for `getDisplayName` for now - the other is NAB and more just a question.

**Review by roryabraham — DISMISSED** [review]
Changing this to an approval, but I'll let @chiragsalian have a look too.

**Review by chiragsalian — DISMISSED** [review]
Looks great to me and works really well on web and mobile too. Left two minor comments. Approved anyway since they are mostly NABs.

**Review by chiragsalian — APPROVED** [review]
LGTM :+1:

**Pull request closed without merging**
