### PR TITLE
[No QA] Rename master to main in E.cash

### PR DESCRIPTION
**Pull request by roryabraham**
cc @rafecolton because we'll want to merge this right after you rename `master` to `main` in E.cash to prevent broken deploys.

### Details
Renames the `master` branch to `main` in all our E.cash documentation and CI/CD Github Workflows.

### Fixed Issues
Fixes (partial) https://github.com/Expensify/Expensify/issues/158454

### Tests
Marked as No QA because we'll know if it doesn't work because deploys will break.

1) Rename `master` branch to `main` in Expensify.cash repo
2) Merge this PR
3) Monitor, make sure deploys are happening normally.

### Tested On

n/a - Test on github

### CODE REVIEW

**Review by nickmurray47 — DISMISSED** [review]
lgtm

**Review by johnmlee101 — DISMISSED** [review]
Looking good!

**Review by AndrewGable — DISMISSED** [review]
Looks good, feel free to merge when off hold.

**Comment by rafecolton** [comment]
cc @justinpersaud since it looks like you are assigned to the rename issue (https://github.com/Expensify/Expensify/issues/158705)

**Comment by roryabraham** [comment]
Had to make some minor updates after merging master. Hoping to get this done today

**Review by johnmlee101 — APPROVED** [review]

**Pull request merged**
