### PR TITLE
Fix icon color for saved search popup menu

### PR DESCRIPTION
**Pull request by jaydamani**
### Details

The icon color inside three dot menu for saved search are incorrect.

### Fixed Issues

$ https://github.com/Expensify/App/issues/49440
PROPOSAL: https://github.com/Expensify/App/issues/49440#issuecomment-2361883274

### Tests

1. Go to search tab
2. Click on three dot menu on right side of a saved search
3. Verify the default icon color is grey
4. Hover or click one of the item in the menu
5. Verify the color on hover/click is green

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Go to search tab
3. Create a saved search if not present
4. If on mobile devices, click grey button on top for list of saved searches
5. Click on three dot menu on right side of a saved search
6. Verify the default icon color is grey
7. Hover or click one of the item in the menu
8. Verify the color on hover/click is green
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Screenshot_1726911113

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot_1726911747

</details>

<details>
<summary>iOS: Native</summary>

Simulator Screenshot - iPhone 16 - 2024-09-21 at 11 59 02

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Simulator Screenshot - iPhone 16 - 2024-09-21 at 12 03 22

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Screenshot 2024-09-21 at 08 26 58

</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2024-09-21 at 12 09 07

</details>

### CODE REVIEW

**Review by ishpaul777 — APPROVED** [review]
LGTM!

**Review by D-01576 — APPROVED** [review]

**Comment by dubielzyk-expensify** [comment]
This issue is actually not entirely correct. Cause our default colors on popup is that the icon is green:
CleanShot 2024-09-23 at 15 40 07@2x

But for the Search LHN we've changed the icon color to be green on active and grey on inactive.

I kinda think we should do one of two things here:
1. Not do anything as the popover is different to the LHN bottom sheet
2. Change the default icon color to be grey across the app (which we've spoken about before anyways).

I don't think we should treat this as an exception, but keen to hear what @Expensify/design things. cc @luacmartins

**Comment by jaydamani** [comment]
@dubielzyk-expensify option 2 seems like a better choice but if it affects in too many places and we go for option 1, I think it should be still changed for mobile/narrow screens. It is not like a popup there, so it seems inconsistent on mobile devices. (the below screenshot is with changes from this PR)

image

**Comment by dubielzyk-expensify** [comment]
Yeah. I think if we did 1 and 2 we'd just do it as a separate follow-up. I'm not totally against creating a specific override here, but it just feels a bit off. Let's hear what @dannymcclain thinks.

**Comment by dannymcclain** [comment]
Ok I think this is my perspective:
The LHN items are different than the popover/menu items. All LHN items currently work this way: Gray icon for static, Green icon for active. You can see them working that way in Settings. So I could definitely see going with Jon's Option 1.

BUT I am a bit torn because I do prefer the update (Option 2) 😅 but am a little concerned about how many places an update like that would touch. ...Although we've been talking about making that change for a looooooong time now.

I do agree with Jon that we should not treat this as exception though. Can we get any insight into the level of effort/scariness for pursuing Option 2?

**Comment by dannymcclain** [comment]
🫣 We were talking about ALL of them 🫣

Although your comment does make me wonder if there's a phased/stepped approach we could potentially take (like start with menu items, then go through our "regular" option rows, and then tackle any stragglers, etc).

But yeah, initially I think Jon and I were talking about all of them everywhere.

**Comment by dannymcclain** [comment]
Whoa that's awesome. Let's have some peeps take a look!

**Comment by dubielzyk-expensify** [comment]
We'll have to do an audit cause I've already found 2 place where it doesn't replace the icon color: 
CleanShot 2024-09-24 at 09 52 41@2x
CleanShot 2024-09-24 at 09 53 17@2x

But that being said, I kinda wanna do this. Cause either we do it now-ish or we start having this half n half of Search being the outlier and the rest being different.

Keen to hear if @trjExpensify or @JmillsExpensify have any thoughts. 

Also we can always revert this change later if we hate it, but I kinda dig it 😄

**Comment by trjExpensify** [comment]
I'm not super passionate, but I'm not really following the issue with what's in prod today based on the current status quo? 

The rows in the search popover looks the same as other popovers to me?

image

image

**Comment by jaydamani** [comment]
> We'll have to do an audit cause I've already found 2 place where it doesn't replace the icon color: 

Agreed, there will be a few places with some specific exception but since this does not break any functionality I also think they can be fixed as we find them.

Also, I investigated the places mentioned above and they have an issue on staging as well. They do not change color when hovered even on staging.
> CleanShot 2024-09-24 at 09 52 41@2x 

This does not change color because [table](https://github.com/Expensify/App/blob/main/assets/images/table.svg) icon is hardcoded as green. This can be fixed by editing the svg and removing the hardcoded color.

image

> CleanShot 2024-09-24 at 09 53 17@2x

The color for this place is hardcoded [here](https://github.com/Expensify/App/blob/4841f44e2070ddd800ce3170cb0d8133287f3f96/src/pages/settings/Security/SecuritySettingsPage.tsx#L191).
Similar issue exists for "Subscription > Request early cancellation". It is also hardcoded [here](https://github.com/Expensify/App/blob/4841f44e2070ddd800ce3170cb0d8133287f3f96/src/pages/settings/Subscription/CardSection/RequestEarlyCancellationMenuItem/index.tsx#L19)

**Comment by dannymcclain** [comment]
>there will be a few places with some specific exception but since this does not break any functionality I also think they can be fixed as we find them.

This is exactly my thinking as well. And fixing the ones that don't get the color change automatically isn't a super complicated/hard thing. I think most will just be removing the hardcoded color values like you point out.

**Comment by JmillsExpensify** [comment]
Yeah, I for pushing this PR forward. I think what we're going here is a good start at cleaning things up.

**Comment by trjExpensify** [comment]
>The "issue" really becomes more pronounced on mobile where our LHN items and menu items become conflated and look almost the same but not quite the same.

Yeah, sorry. I'm just getting tripped up by the terms "fix" and "incorrect" etc. What's in prod is consistent with other popover menus throughout the app today, right? They're not "incorrect" like the parent issue suggests in that regard, we just want to change them, and make that change everywhere yeah?

**Comment by dubielzyk-expensify** [comment]
> They're not "incorrect" like the parent issue suggests in that regard, we just want to change them, and make that change everywhere yeah?

Yeah I agree with this. This issue isn't true cause the original post is what's consistent with the rest of the mocks, but not with the Figma mocks.

But I agree with the steps outlined by @ishpaul777 above. You okay with that @JmillsExpensify and @trjExpensify ?

**Comment by trjExpensify** [comment]
Cool yeah, thanks for clarifying. That was turning me around, haha. I'm down for the change, let's make sure we do the follow-up step #2 though!

**Comment by luacmartins** [comment]
Ok, sounds like a plan. @jaydamani can you update the PR to invert the isPaneMenu logic, e.g. how we have done [here](https://github.com/Expensify/App/pull/49616)

**Review by luacmartins — CHANGES_REQUESTED** [review]
@jaydamani please address the comments above

**Comment by jaydamani** [comment]
@luacmartins working on it

**Comment by jaydamani** [comment]
Updated below places that had hardcoded colors. All of them now change colors on hover:

- Workspace settings > Expensify Card > select any card > Deactivate card
- Workspace settings > Workflow > Add approval workflow
- Workspace settings > Workflow > select any non default workflow > Delete
- Security settings > Add copilot
- Subscription > Request early cancellation
- Table icon in three dot menu inside workspace settings.
Note: For table icon, the color was hardcoded with `fill` attribute for path in table.svg. Removing the fill breaks the image so instead fill is set as inherit

Let me know if any of them should be reverted.

Also, I am not sure what should be the best steps for QA. Should we instruct them to roam around in app and find incorrect/old icons or just ask them to verify the above mentioned places where we explicitly made some changes.

**Comment by luacmartins** [comment]
Gonna run an adhoc build. @dubielzyk-expensify @dannymcclain could you test the build to make sure the colors are correct?

**Comment by dubielzyk-expensify** [comment]
Looked everywhere and couldn't find any faults. Looking great! 👏 Would love @dannymcclain 's eyes on it as a double check before we go ahead, but I think this is good

**Review by luacmartins — APPROVED** [review]

**Comment by luacmartins** [comment]
>Would love @dannymcclain 's eyes on it as a double check before we go ahead, but I think this is good

Thanks for testing. In this case, I'll go ahead and merge this to avoid any conflicts in the meantime. @dannymcclain let me know if you find anything weird and we can address it in a follow up.

**Comment by dannymcclain** [comment]
Totally fine with y'all merging without my review—this is a pretty "low-stakes" update in that we're not really going to break anything here. Sorry I didn't get a chance to check it out yesterday! I will keep my eyes peeled for miscolored icons, but I'm stoked we're finally pushing this through!

**Comment by roryabraham** [comment]
This appears to have caused a regression: https://github.com/Expensify/App/issues/49885

**Comment by luacmartins** [comment]
Thanks! Fix merged

**Pull request merged**
