### PR TITLE
[No QA] Deploy help site with GH Pages built-in Jekyll

### PR DESCRIPTION
**Pull request by roryabraham**
On HOLD because in order for this to work we'll need to change our GitHub Pages publishing directory to `main`.

### Details
This is solution D, discussed in slack [here](https://expensify.slack.com/archives/C02QSAC6BJ8/p1657131166750999).

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/216746

### Tests
1. Merge this PR
1. Verify that the help site immediately deploys on GH pages.

### CODE REVIEW

**Comment by roryabraham** [comment]
cc @marcochavezf @AndrewGable

**Review by AndrewGable — APPROVED** [review]

**Review by marcochavezf — APPROVED** [review]
Tested locally and the help site looks good

**Review by Justicea83 — APPROVED** [review]
Changes look good!

**Comment by roryabraham** [comment]
Going to merge + test

**Comment by roryabraham** [comment]
https://github.com/Expensify/App/actions/runs/2631188164

**Comment by roryabraham** [comment]
So the build happened, but not everything is working as expected:

image

There is a good likelihood that the cause for this problem is described in [this comment](https://github.com/Expensify/Expensify/issues/216746#issuecomment-1173132144)

**Pull request merged**
