### PR TITLE
Fix/29812: Same page has different error text color for different errors

### PR DESCRIPTION
**Pull request by Victor-Nyagudi**
### Details

Errors in Expensify are shown in red text, but the error shown when trying to create a distance request without adding waypoints has a red dot accompanied by light-greyish green text (the color of success messages when accompanied by a green dot).

This PR restores the red color to the error text. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/29812
PROPOSAL: https://github.com/Expensify/App/issues/29812#issuecomment-1768115351

### Tests

1. Log into a test account.
2. Click the green circle with a "+" sign in it at the bottom left of the screen. 
3. Select "Request money" from the modal that appears. 
4. If you're on Mac Chrome, Mac Safari, or the Mac desktop app and the app/browser is at least half the width of the screen, a panel will appear on the right side. If on mobile, a modal this panel/modal will fill the screen. Click on the "Distance" tab. 
5. Click on the large, green pill button at the bottom of the panel/modal that says "Next".
6. Verify a red dot appears above the button in step 5 with red text to its right that says "Please enter at least two waypoints".
7. Tap on the left facing caret/arrow at the top of the modal next to the words "Request money" to go back/close the panel/modal.
8. Click on the avatar at the top left of the screen and then click on "Profile" in the panel/modal that appears. 
9. Click on  "Contact method" and then click on the green pill button at the bottom that says "New contact method".
10. Enter a valid email e.g. another test account you have access to, and then click on the green pill button at the bottom that says "Add". You'll be redirected to the previous screen. 
11. Click on the email you just added. It should have a green dot next to it. 
12. Verify a green dot with light-greyish green text to its right saying "Please enter the magic code sent to [the email you entered in Step 10]" is shown below the header with the Step 10 email and left facing caret/arrow. 

- [x] Verify that no errors appear in the JS console

### Offline tests

After logging into an account while online, turn off the wifi/internet connection and perform steps 2 through 6 in the "Tests" section above. You can also force offline by clicking on the avatar at the top left of the screen -> preferences -> toggle offline. 

You can add a contact method while offline, but you won't be able to click it (step 11) to navigate to the screen with the green dot and light-greyish green text. 

### QA Steps

Same as above in the "Tests" section. 

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

expensify-fixed-error-text-color-iOS-native

</details>

<details>
<summary>iOS: mWeb Safari</summary>

expensify-fixed-error-text-color-iOS-web

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

expensify-fixed-error-text-color-mac-chrome

expensify-fixed-error-text-color-mac-safari

</details>

<details>
<summary>MacOS: Desktop</summary>

expensify-fixed-error-text-color-mac-desktop

</details>

### CODE REVIEW

**Comment by Victor-Nyagudi** [comment]
It appears this bug occurs in other places too like when you try uploading an image over 6MB as your avatar.

<details>

<summary>Image upload error before changes</summary>

expensify-incorrect-image-upload-text-error-color

</details>

Same thing if you input the wrong magic link numbers when trying to add another contact method. 

<details>

<summary>Contact method error before changes</summary>

expensify-contact-method-incorrect-error-text

</details>

In addition, trying to unlink a login method with account errors (tried but not sure how to reproduce this one) or if it's detected you committed domain fraud (I prefer to stay out of jail, so I won't try reproducing this), the error shows up in the wrong text color.

https://github.com/Expensify/App/blob/38d647e174acb502e2fae1494faf1c0d9d59e792/src/pages/signin/UnlinkLoginForm.js#L73-L79

https://github.com/Expensify/App/blob/38d647e174acb502e2fae1494faf1c0d9d59e792/src/pages/settings/Wallet/ExpensifyCardPage.js#L89-L96

The changes in this PR will address those cases. Here's a sample.

<details>

<summary>Image upload error after changes</summary>

expensify-image-upload-error-red-text

</details>

However, during my testing, I stumbled on this other error that doesn't show red text if you deny location permissions when adding a start position to a distance request i.e. click on FAB -> Request money -> Distance -> Click start -> Select "Use your location" from dropdown when input is focused-> deny location permission

<details>

<summary>Denied location permission error</summary>

expensify-denied-location-incorrect-error-text

</details>

The current changes won't apply because this particular error is rendered using `LocationErrorMessage`, not `DotIndicatorMessage`.

https://github.com/Expensify/App/blob/2d6e8ef0655c1ab75a5dc3f1c1ca14607e094262/src/components/LocationErrorMessage/BaseLocationErrorMessage.js#L43-L52

The text there is styled using `styles.offlineFeedback.text`, similar to [the text in `DotIndicatorMessage`](https://github.com/Expensify/App/blob/2d6e8ef0655c1ab75a5dc3f1c1ca14607e094262/src/components/DotIndicatorMessage.js#L70-L75), except the color isn't set back to red.

I figured I'd ask first before making any changes other than the ones agreed upon in my proposal.

Should we opt to fix the denied permission error in this PR, we could potentially create a helper method like `getFormErrorColor()` in `StyleUtils` that returns the `{color: styles.formError.color}` style and apply it in both `DotIndicatorMessage` and `BaseLocationErrorMessage`.

Let me know your thoughts on this.

**Comment by Victor-Nyagudi** [comment]
I'm yet to find other places where the error text color is light greyish-green isn't of red.

**Comment by Victor-Nyagudi** [comment]
Friendly bump @thesahindia for a review.

**Comment by Victor-Nyagudi** [comment]
I'm on it.

**Comment by Victor-Nyagudi** [comment]
All yours, @thesahindia.

Tests well too. 

expensify-fixed-denied-permission-error

**Comment by Victor-Nyagudi** [comment]
I've fixed the conflicts, but the linter has detected a prettier diff from the import alias PR that just got merged. 

Running `npm run prettier` doesn't fix it. 

How to proceed, @thesahindia?

**Comment by Victor-Nyagudi** [comment]
@thesahindia All conflicts have been resolved. 

We're good to move forward.

**Review by thesahindia — APPROVED** [review]
LGTM!

**Review by bondydaa — APPROVED** [review]

**Pull request merged**
