### PR TITLE
Fix emoji’s are cut in half when in Edit message mode

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

The emoji is enlarged when the composer only contains emoji, but we didn't increase the line height for edit composer.

### Fixed Issues

$ https://github.com/Expensify/App/issues/42530
PROPOSAL: https://github.com/Expensify/App/issues/42530#issuecomment-2128381197

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

1. Open any chat
2. Send an emoji only message
3. Long-press/right-click on the message and choose Edit message
4. Verify the emoji isn't cut in half
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/50919443/1f8fd2c3-3e94-4e1c-8b62-078f3b70dd0c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/50919443/3bb59c85-a95c-4c91-bde0-741f5a7e4966

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/50919443/3b569ddb-9e2d-4f13-b346-d6adc86b9e31

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/50919443/296b62ab-c998-4009-91d4-e5cf8a072c7c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/50919443/40b16162-931d-481b-8e9b-c2cb3d1dee70

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/50919443/8e6f929f-16ae-4564-8279-aadc836490f0

</details>

### CODE REVIEW

**Comment by dubielzyk-expensify** [comment]
Looks close to me, but what's going on here? 
CleanShot 2024-05-27 at 16 12 55@2x

The X button isn't centered in the compose bar like it is before you edit which is what we want

**Comment by shawnborton** [comment]
Also, it seems like this has some overlap with @kbieganowski's [PR over here](https://github.com/Expensify/App/pull/40692)?

**Comment by shawnborton** [comment]
Even in normal compose mode, adding just one emoji shouldn't cause the composer to grow like this:
CleanShot 2024-05-27 at 08 47 28@2x

**Comment by kbieganowski** [comment]
> Also, it seems like this has some overlap with @kbieganowski's [PR over here](https://github.com/Expensify/App/pull/40692)?

Thanks for pointing this out @shawnborton! Can confirm that this is not an issue in PR you mentioned:

https://github.com/Expensify/App/assets/26638539/415755e7-f6cf-4975-9917-e48e9e0078a8


https://github.com/Expensify/App/assets/26638539/e91520fc-68de-49f8-9772-d190e2b180ff

**Comment by bernhardoj** [comment]
> The X button isn't centered in the compose bar like it is before you edit which is what we'd like to happen

The X button is always aligned to the bottom for edit composer

image

> Even in normal compose mode, adding just one emoji shouldn't cause the composer to grow like this:

The bigger font size and line height increase the composer's height. It happens on prod too btw.

> Also, it seems like this has some overlap with @kbieganowski's https://github.com/Expensify/App/pull/40692?

Yeah, there is an overlap there.

**Review by Ollyws — APPROVED** [review]
LGTM.

**Comment by shawnborton** [comment]
Even the cursor appears centered :) 
CleanShot 2024-05-28 at 17 46 50@2x

**Comment by bernhardoj** [comment]
We can't do that on iOS, otherwise it will be cut in half. Maybe we should apply the increased line-height for native only?

**Comment by shawnborton** [comment]
I think whatever the solution is, ideally it doesn't increase the composer height anywhere. Can you think of other approaches? 

Also just to confirm, the increased emoji line height already exists on production, right? So I mean one approach could be to just get this PR wrapped up so that the Edit behavior is the same as the compose behavior, and then we can fix the emoji line height in the other PR that is being worked on for emojis [here](https://github.com/Expensify/App/pull/40692).

**Comment by bernhardoj** [comment]
Yeah, it already exists in production. https://github.com/Expensify/App/pull/40692 reduce the composer padding (not sure if it's the best way, but I can't think of other approaches) so the height will be normal as I pointed out in my previous comment [here](https://github.com/Expensify/App/pull/42615#issuecomment-2135572014), so we can wrap this PR.

Btw, I just refactored the code to reduce the conflict with https://github.com/Expensify/App/pull/40692

**Comment by shawnborton** [comment]
Sounds good, thank you!

**Review by Ollyws — APPROVED** [review]
Still tests well.

**Review by rlinoz — APPROVED** [review]

**Pull request merged**
