### PR TITLE
Bump Onyx version to fix resetting default values

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
cc @Julesssss 

### Fixed Issues

Fixes https://github.com/Expensify/Expensify/issues/164467

### Tests
1. Log into E.cash
2. Wait for all network requests to finish
3. Log out
4. Verify the following default keys can be seen in storage

```js
{
    session: {loading: false, shouldShowComposeInput: true},
    account: {error: "", success: "", loading: false}
    network: {isOffline: false},
    iou: {loading: false},
}
```

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by Julesssss — APPROVED** [review]

**Review by Julesssss — CHANGES_REQUESTED** [review]
Tests well, but would you mind merging main so that we can include the new IOU keys introduced by IOU Details Modal. Thanks!

**Comment by marcaaron** [comment]
Updated

**Review by Julesssss — DISMISSED** [review]

**Comment by Julesssss** [comment]
Confirmed that the original IOU error is fixed, give us a bump when the conflict is resolved 👍

**Review by MonilBhavsar — DISMISSED** [review]

**Comment by MonilBhavsar** [comment]
Tested, works well!

**Comment by marcaaron** [comment]
Updated

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
@marcaaron I'm heading out soon, but feel free to merge when the iOS tests complete

**Comment by isagoico** [comment]
@marcaaron Any QA steps for this one?

**Comment by marcaaron** [comment]
Ah woops sorry. None besides testing logging in and out and verifying that the data looks correct in the `localStorage`

I tested on staging and everything looks OK to me.

Screen Shot 2021-05-21 at 8 07 30 AM

**Pull request merged**
