### PR TITLE
Update Onyx version to improve handling of defaultKeyStates

### PR DESCRIPTION
**Pull request by marcaaron**
### Details

cc @kidroca updating the Onyx version to incorporate the latest changes regarding `defaultKeyStates`

**Notes:** 

There are two changes included in this PR under one sha

- `defaultKeyStates` PR - I ran some basic user timing tests around boot time and when the side bar first loads, but didn't notice anything worthy of reporting as far as performance improvements. We are viewing this as a pre-requisite to future improvements that should have a greater impact.
- The second PR for preventing unnecessary writes adds about 250ms to chat switching on Android release builds 🎉 

### Fixed Issues (Related)
https://github.com/Expensify/App/issues/2667

### QA Steps
- Make sure the app initialize and runs OK
- No specific test steps other than basic regressions and look out for errors when the app boots

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
This is failing one of our tests. Going to put this back into draft while I check it out.

**Comment by marcaaron** [comment]
Test is fixed. We've also merged another PR into `react-native-onyx` so going to bump this again in a bit.

**Comment by marcaaron** [comment]
Just updated it again to include the latest changes and seeing some improvements with chat switches on Android. Should be ready for review now.

**Review by Jag96 — APPROVED** [review]
LGTM

**Pull request merged**
