### PR TITLE
Revert "[navigation-refactor] Fix browser history for complex navigation actions"

### PR DESCRIPTION
**Pull request by mountiny**
Reverts Expensify/App#24165

### CODE REVIEW

**Comment by shubham1206agra** [comment]
This is happening due to multiple race conditions between `window.history` methods and the `onStateChange` method execution. Due to which, multiple `window.history.go(-1)` calls were made, and #25527 occurs

**Comment by shubham1206agra** [comment]
> This is happening due to multiple race conditions between `window.history` methods and the `onStateChange` method execution. Due to which, multiple `window.history.go(-1)` calls were made, and #25527 occurs

I have fixed this issue. Can I put the patch PR?

**Comment by mountiny** [comment]
https://25572.pr-testing.expensify.com/

**Comment by hayata-suenaga** [comment]
@mountiny are you gonna revert the revert?

**Comment by mountiny** [comment]
@hayata-suenaga not sure what you mean, I have created this revert branch to make sure if it would fix the issues but I have confirmed the issues linked to the Pr still prevailed so it was not the root cause. No need to revert

**Comment by hayata-suenaga** [comment]
@mountiny I have an issue that was being held for [the original PR](https://github.com/Expensify/App/pull/24165). Since you reverted the original PR (but confirmed that it was not the root cause of an issue), I was wondering if you're planning to bring back the original PR by reverting this revert PR.

**Comment by mountiny** [comment]
Probably some miscommunication, the PR was **not** reverted. This Revert PR has not been merged so the original PR is still there

**Comment by hayata-suenaga** [comment]
ahh can't believe I missed this big red sign 😓 thank you for much for the clarification 🙇 

Screenshot 2023-08-22 at 1 19 13 PM

**Comment by mountiny** [comment]
So not only Big Green buttons but also big red signs :trollface:

**Pull request closed without merging**
