### PR TITLE
[NoQA] fix links for Expensify Help site

### PR DESCRIPTION
**Pull request by marcochavezf**
### Details
This PR fixes the links for the new Expensify Help (where the back button is not working as expected [here](https://help.expensify.com/articles/request-money/SmartScan)).

### Fixed Issues
N/A

### Tests
0. (you need ruby and bundler installed to do this, more info [here](https://github.com/Expensify/App/tree/main/docs#pre-requisites))
1. Run:

    ```bash
    cd docs
    bundle install
    bundle exec jekyll serve
    ```
2. Navigate to http://localhost:4000/articles/request-money/SmartScan and click on the `Back` button, it should redirect to the hub page (upper level)

Screen Shot 2022-07-14 at 15 10 08

3. Click on the `Home` button and verify it redirects you to the Homepage (currently it's an empty page) instead of the "Coming soon" page.

Screen Shot 2022-07-14 at 15 10 18

### CODE REVIEW

**Review by johnmlee101 — APPROVED** [review]

**Comment by johnmlee101** [comment]
Why can't this be QA'd?

**Comment by marcochavezf** [comment]
> Why can't this be QA'd?

Ah the site is still in an "alpha" version and we're going to still do more changes, but this fix is required for us to internally begin to upload content. So I think it won't make sense to use QA since we're going to be testing the site internally until we have more content :)

**Comment by marcochavezf** [comment]
Merging it

**Comment by johnmlee101** [comment]
I don't necessarily agree. As long as one of the QA testers can jump into the site and click the links I think its fine to have it go through the QA process since its not being cherry-picked.

**Pull request merged**
