### PR TITLE
Fix fonts

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
cc @Luke9389 Fixes font paths

### Fixed Issues
$ https://expensify.slack.com/archives/C07J32337/p1670008137700449
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests
1. Checkout this branch and run `npm i`
1. Open the App
2. Verify that the fonts are `ExpensifyNeue`

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as tests

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

web

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screenshot 2022-12-02 at 12 31 35 PM

</details>

<details>
<summary>Mobile Web - Safari</summary>

safari

</details>

<details>
<summary>Desktop</summary>

desktop

</details>

<details>
<summary>iOS</summary>

ios

</details>

<details>
<summary>Android</summary>

Screenshot 2022-12-02 at 12 40 17 PM

</details>

### CODE REVIEW

**Comment by roryabraham** [comment]
Weird, because [this line](https://github.com/Expensify/App/blob/7f1544d9a9303bdd0b8c7f5bb75e275970cb78a6/config/webpack/webpack.common.js#L97) moves the assets to the root of the site bundled by webpack.

**Comment by Luke9389** [comment]
Yep, that's what's confusing me too @roryabraham

**Comment by roryabraham** [comment]
Also this worked for me locally before, so we should probably do:

1. Local webpack staging build with `npm run build-staging`
1. Storybook dev testing with `npm run storybook`. We forgot this in the last PR.
1. Local storybook production build with `npm run storybook-build`

and make sure it's working in all those environments. It seems like the build failure we were seeing was in the storybook build, which we also forgot to test in the previous PR. Maybe there's a problem in the [storybook webpack config](https://github.com/Expensify/App/blob/main/.storybook/webpack.config.js).

**Comment by Luke9389** [comment]
@luacmartins is away so I'm going to hop onto this issue.

**Comment by Luke9389** [comment]
I tested this PR on web and it works, but I've also undone the change and that works too...

Does that make any sense to you @roryabraham?

**Comment by Luke9389** [comment]
I think this is coming from storybooks webpack config. Should we just remove the font from storybook to fix the errors right now and then add it to storybook later?

**Comment by roryabraham** [comment]
Pretty sure we are looking in the wrong place and need to fix this in the CSP:

image

**Comment by roryabraham** [comment]
I think this is the PR we'll need to fix web fonts on staging and production: https://github.com/Expensify/Cloudflare-Workers/pull/44

It sounds like storybook might be having a separate problem, but the CSP issue is the most important rn because it fixes a deploy blocker

**Comment by luacmartins** [comment]
Closing in favor of https://github.com/Expensify/Cloudflare-Workers/pull/44

**Pull request closed without merging**
