### PR TITLE
Fix ellipsis in DisplayNames - 2

### PR DESCRIPTION
**Pull request by CamilaRivera**
### Details

Add `display: inline-block` in web to make ellipsis work.

### Fixed Issues

$ https://github.com/Expensify/App/issues/6913

### Tests | QA Steps

1. Open app
2. Create a group with multiple contacts
3. Check LHN for the group with multiple contacts, it should show an ellipsis if the names don't fit
4. Create a contact with a long email to check it also shows an ellipsis at the end
5. Check in the search page the same behavior as LHN 

Expected result: You should see the ellipsis for all cases above.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

image

#### Mobile Web
Chrome Android 

Screen Shot 2022-01-03 at 7 18 09 PM
Screen Shot 2022-01-03 at 7 17 52 PM
Screen Shot 2022-01-03 at 7 17 30 PM

Safari IOS

Screen Shot 2022-01-03 at 7 47 52 PM
Screen Shot 2022-01-03 at 7 47 46 PM
Screen Shot 2022-01-03 at 7 47 42 PM

#### Desktop

Screen Shot 2022-01-03 at 7 30 23 PM
Screen Shot 2022-01-03 at 7 30 17 PM
Screen Shot 2022-01-03 at 7 30 11 PM

#### iOS

Screen Shot 2022-01-03 at 7 45 21 PM
Screen Shot 2022-01-03 at 7 45 14 PM
Screen Shot 2022-01-03 at 7 45 08 PM

#### Android

Screenshot_20220103-193913
Screenshot_20220103-193922
Screenshot_20220103-193931

### CODE REVIEW

**Comment by parasharrajat** [comment]
@CamilaRivera Let's find the real cause why this is not working natively. Why RN-web is using multiline styles.

**Comment by Beamanator** [comment]
Also since you tested on mobile web & desktop would you please provide some screenshots? :D (also for ios and android if you're able to test there)

**Comment by CamilaRivera** [comment]
> @CamilaRivera Let's find the real cause why this is not working natively. Why RN-web is using multiline styles.

Not sure what you mean about "multiline styles", but this is what I found: 

The base requirements for the ellipsis, according to this [SO](https://stackoverflow.com/a/17783233/15608445), are:

```css
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
```

and a constrained width. We are missing this last part because of the `display: -webkit-box` currently being set.  Haven't found why that is set like that.

**Comment by CamilaRivera** [comment]
> Also since you tested on mobile web & desktop would you please provide some screenshots? :D (also for ios and android if you're able to test there)

@Beamanator Updated the description with screenshots

**Comment by parasharrajat** [comment]
I meant the same thing `display: -webkit-box` is multiline styles. So Now I would wait before merging this and request you to do some analysis on finding the root cause. If we are not able to determine then we can proceed with this approach which is a hacky solution.

This problem is coming due to the recent upgrade of RN-web. But is this a bug with RN-web or an issue in our repo?

**Comment by parasharrajat** [comment]
Here is the issue with RN-web https://github.com/necolas/react-native-web/issues/2186. Let's wait for the solution

**Comment by parasharrajat** [comment]
I have submitted a fix for RN-web https://github.com/necolas/react-native-web/pull/2193 which should be merged soon and then this issue will be fixed.

**Comment by Beamanator** [comment]
Closing since the fix was made in react-native-web (our fork, for now)

**Pull request closed without merging**
