### PR TITLE
Error message shown out of place in VBA flow

### PR DESCRIPTION
**Pull request by thienlnam**
### Fixed Issues

$ https://github.com/Expensify/App/issues/4916#

### Tests / QA
1. Created workspace on freePlan beta
2. Selected `Get Started` in the Expensify Card tab of the Workspace
3. Entered test bank account credentials in [3 of this SO](https://stackoverflow.com/c/expensify/questions/342/525#525)
4. When asking for your name, enter an invalid date of birth that doesn't get caught by front-end validation (like 2020-05-05)
4. Arrived at Validate Step to enter validation amounts, and make sure you don't see a verify your name and date of birth message

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

Screen Shot 2021-08-31 at 4 46 03 PM

### CODE REVIEW

**Comment by thienlnam** [comment]
Putting on hold for now until I can test this once the validate step works again

**Comment by aldo-expensify** [comment]
> Putting on hold for now until I can test this once the validate step works again

I was able to test this locally using the credentials in [2 of this SO](https://stackoverflow.com/c/expensify/questions/342/525#525) (not 3)

**Comment by aldo-expensify** [comment]
I think your are right about the problem being that we don't clear the error state properly.

When the error comes from the back end (no field highlighted, only growl), the fix doesn't seem to work:

https://user-images.githubusercontent.com/87341702/131585148-dc948619-0699-4d65-a6b6-d487015ed209.mov

When the error is from a validation in the front end (field highlighted + growl), there is doesn't stay because we clear it immediately on the input change [here](https://github.com/Expensify/App/blob/2919b884743e06aec2a9bdfe7caeb8cfc11c9ed9/src/pages/ReimbursementAccount/IdentityForm.js#L96-L102) 

https://user-images.githubusercontent.com/87341702/131585234-9387fc4e-c8b0-4881-8e3e-3d60350d06af.mov

**Comment by thienlnam** [comment]
Did you test on my branch? I was testing with the second credentials and had success (going to give it another test now)

**Comment by thienlnam** [comment]
Just kidding, I didn't trigger the API call, back to the drawing board

**Comment by thienlnam** [comment]
@aldo-expensify Thanks for the initial review - ready for another one (I tested it correctly this time)

**Comment by aldo-expensify** [comment]
Tested again, now it worked.

Just two comments:

1. I saw this error in the console, which I guess is related to displaying the error `''`:

Screen Shot 2021-08-31 at 4 51 12 PM

This is related to the problem described [here](https://github.com/Expensify/App/blob/main/STYLE.md#important-note), a way to fix that is by doing this change in ValidationStep.js:

```
                            {errorMessage && (
                                <Text style={[styles.mb5, styles.textDanger]}>
                                    {errorMessage}
                                </Text>
                            )}
```
for
```
                            {Boolean(errorMessage) && (
                                <Text style={[styles.mb5, styles.textDanger]}>
                                    {errorMessage}
                                </Text>
                            )}
```

2. There is already a function in BankAccounts.js to clear the errors: `hideBankAccountErrors`

**Comment by thienlnam** [comment]
Good catch, I ended up using the !_.isEmpty conditional

**Review by aldo-expensify — APPROVED** [review]
Tested in web, looks good to me! Waiting on tests to finish before merging..

**Comment by isagoico** [comment]
@thienlnam hello! I think this may have to be internal QA, we're unable to trigger the "get started" flow and get the validation numbers for last step.

**Comment by aldo-expensify** [comment]
> @thienlnam hello! I think this may have to be internal QA, we're unable to trigger the "get started" flow and get the validation numbers for last step.

Hey @isagoico , I think you don't need those numbers to test this PR, you just have to get to that view and see that no error message lingered from the previous steps:

https://user-images.githubusercontent.com/87341702/131585148-dc948619-0699-4d65-a6b6-d487015ed209.mov

**Comment by isagoico** [comment]
I _think_ I found a new issue here. After following the steps to enter a pending account I got a empty validation page 🤔 
image

**Comment by isagoico** [comment]
Ok ignore this 🔝 It happened because I already had an account with that user. Retested on a new account and it was a pass 🎉 

image

**Pull request merged**
