### PR TITLE
Remove timezone migration

### PR DESCRIPTION
**Pull request by NikkiWines**
### Details

Removes a migration that was causing issues in the following PR: https://github.com/Expensify/Expensify.cash/pull/2040
### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com/Expensify/Expensify.cash/pull/2040#issuecomment-808354538

### Tests/QA 
1. Log into E.cash 
2. Open the JS console navigate to Application, select Local Storage, and search for `myPersonalDetails`
3. Manually modify your timezone in your `myPersonalDetails` so that it's a string like so 
**OLD**
```JSON
"timezone": {
  "automatic": true,
  "selected": "America/Los_Angeles"
}
```

**NEW**
```JSON
"timezone": "America/Los_Angeles"
``` 
4. Refresh the page and confirm you don't see any errors in the JS console and the page loads as anticipated. 

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots
N/A no UI changes

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
Okay, LGTM. This PR is essentially just a revert of https://github.com/Expensify/Expensify.cash/pull/2040/files

**Comment by NikkiWines** [comment]
For some reason I am unable to record my screen at the moment but I can confirm that this works on staging

**Comment by NikkiWines** [comment]
Got screen recording working 🎉 

https://user-images.githubusercontent.com/16747822/112695575-96442980-8e41-11eb-8fe6-63612651e826.mov

**Comment by isagoico** [comment]
Nice! Need me to test it on my side too?

**Comment by NikkiWines** [comment]
Can't hurt 😅  I'd rather be safe than sorry here

**Comment by isagoico** [comment]
Oh no 😟 
image

```
app-6abeeedf7b640e20646e.bundle.js:57 Uncaught TypeError: Cannot read property 'login' of null
    at Zs (app-6abeeedf7b640e20646e.bundle.js:85)
    at n.value (app-6abeeedf7b640e20646e.bundle.js:85)
    at ve.onKeyDown (app-6abeeedf7b640e20646e.bundle.js:1)
    at Object.s (app-6abeeedf7b640e20646e.bundle.js:57)
    at f (app-6abeeedf7b640e20646e.bundle.js:57)
    at app-6abeeedf7b640e20646e.bundle.js:57
    at b (app-6abeeedf7b640e20646e.bundle.js:57)
    at at (app-6abeeedf7b640e20646e.bundle.js:57)
    at ot (app-6abeeedf7b640e20646e.bundle.js:57)
    at st (app-6abeeedf7b640e20646e.bundle.js:57)
```

**Comment by roryabraham** [comment]
@isagoico While that's not good, it looks to me like you're using the production website

**Comment by isagoico** [comment]
Yep I think the production "set up password" link is broken. I also updated on the staging results for this one here https://github.com/Expensify/Expensify.cash/pull/2040#issuecomment-808552770

**Pull request merged**
