### PR TITLE
[Feat] Add Image loading indicator

### PR DESCRIPTION
**Pull request by mdneyazahmad**
### Details

Display an `ActivityIndicator` when image is being loaded in the chat.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7584

### Tests

1. Open a chat with images, or upload an image.
2. Verify that an `ActivityIndicator` appears when image is being downloaded.
- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. “toggleReport” and not “onIconClick”)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct english, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct english and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY
- [x] I verified any variables that can be defined as constants (ie. in CONST.js) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] Any internal methods are bound to “this” properly so there are no scoping issues
    - [x] Any internal methods bound to “this” are necessary to be bound
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose and it is
    - [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn’t already exist
    - [x] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function
(i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)

#### PR Reviewer Checklist
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. “toggleReport” and not “onIconClick”).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct english, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct english and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] Any internal methods are bound to “this” properly so there are no scoping issues
    - [ ] Any internal methods bound to “this” are necessary to be bound
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function
(i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)

### QA Steps

1. Open a chat with images, or upload an image.
2. Verify that an `ActivityIndicator` appears when image is being downloaded.
3. Verify that it never stuck in loading state.
- [x] Verify that no errors appear in the JS console

#### Web

https://user-images.githubusercontent.com/77761491/158813190-82ccd9c0-bd5a-4ec7-adf3-3e35be1cc806.mp4

#### Mobile Web

https://user-images.githubusercontent.com/77761491/158931407-717e5575-48a1-4eb4-85c5-05a87291964d.mp4

#### Desktop

https://user-images.githubusercontent.com/77761491/158812303-7dd7b55f-aca9-4bd4-8c64-86b3a11f33d9.mp4

#### iOS

https://user-images.githubusercontent.com/77761491/158812437-eed37ae2-ac83-4abc-bdb9-01d286031db2.mp4

#### Android

https://user-images.githubusercontent.com/77761491/158812505-274b6900-1508-41f5-9a23-3832a74d0334.mp4

### CODE REVIEW

**Review by rushatgabhane — APPROVED** [review]
@mountiny LGTM! 🎉 Works well on all platforms.

- [x]  I verified the correct issue is linked in the ### Fixed Issues section above
- [x]  I verified testing steps are clear and they cover the changes made in this PR
  - [x]  I verified the steps for local testing are in the Tests section
  - [x]  I verified the steps for Staging and/or Production testing are in the QA steps section
  - [x]  I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
  - [x]  I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
  - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. “toggleReport” and not “onIconClick”).
  - [x]  I verified that comments were added to code that is not self explanatory
  - [x]  I verified that any new or modified comments were clear, correct english, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
  - [x]  I verified any copy / text shown in the product was added in all src/languages/* files
  - [x]  I verified any copy / text that was added to the app is correct english and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
  - [x]  I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
  - [x]  I verified the JSDocs style guidelines (in [STYLE.md](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [x] If a new component is created I verified that 
  - [x]  A similar component doesn't exist in the codebase
  - [x]  All props are defined accurately and each prop has a /** comment above it */
  - [x]  Any functional components have the displayName property
  - [x]  The file is named correctly
  - [x]  The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
  - [x]  The only data being stored in the state is data necessary for rendering and nothing else
  - [x]  Any internal methods are bound to “this” properly so there are no scoping issues
  - [x]  Any internal methods bound to “this” are necessary to be bound
  - [x]  All JSX used for rendering exists in the render method
  - [x]  The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
 - [x]  If a new CSS style is added I verified that:
    - [x]  A similar style doesn’t already exist
    - [x]  The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function
    - [x] (i.e. StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)

**Review by mountiny — COMMENTED** [review]
@rushatgabhane Thanks! Just asking, did you make sure that this regression we had previously has not been happening again? https://github.com/Expensify/App/issues/7900

You have probably not encountered it, but just want to make sure 😅

**Comment by rushatgabhane** [comment]
@mountiny Attaching images on iOS simulator doesn't work for me, so I ran the app on my old iPad.
I didn't encounter the regression we were facing. Thanks for asking :)

**Comment by mdneyazahmad** [comment]
ios simulator (15.x) does not let me upload too. However, it does in safari.

**Comment by rushatgabhane** [comment]
@mdneyazahmad you're missing recording for web

**Comment by mdneyazahmad** [comment]
My bad it was removed be me mistake. Just updating it.

**Comment by mdneyazahmad** [comment]
Done @rushatgabhane

**Review by mountiny — APPROVED** [review]
@mdneyazahmad @rushatgabhane Thank you very much for your work on this one. 

It is a handy feature, great job! Let's hope nothing will backfire this time 🍀

**Comment by mdneyazahmad** [comment]
I found one performance related issue in my pr. `onLoadEnd={() => this.setState({isLoading: false})};` This inline function causes the component to re-render when `isLoading` changes. As a result the component keeps rendering `Image` component. As `ImageWithSizeCalculation` is a `PureComponent` it stops re-render but it still render twice.

We can fix this issue by extracting `onLoadEnd` from inline to a class method. And also I am not more confident with `isLoading: true` in the initial state. I would like to make this further changes.  Tested on all platform works fine.

```diff
         this.state = {
-            isLoading: true,
+            isLoading: false,
         };

+        this.imageLoadingStart = this.imageLoadingStart.bind(this);
+        this.imageLoadingEnd = this.imageLoadingEnd.bind(this);
     }

+    imageLoadingStart() {
+        this.setState({isLoading: true});
+    }
+
+    imageLoadingEnd() {
+        this.setState({isLoading: false});
+    }

-                    onLoadEnd={() => this.setState({isLoading: false})}
+                    onLoadStart={this.imageLoadingStart}
+                    onLoadEnd={this.imageLoadingEnd}
```

cc: @mountiny @rushatgabhane

**Comment by rushatgabhane** [comment]
> isLoading: false

@mdneyazahmad I remember giving this a try before, and it didn't work (got a perpetual spinner).

**Comment by mdneyazahmad** [comment]
@rushatgabhane Exactly this is the issue and this is due to inline function on `onLoadEnd`.

**Comment by mdneyazahmad** [comment]
Could you please test with https://github.com/Expensify/App/pull/8203#issuecomment-1072944196 and make sure it solves that issue?

**Comment by mountiny** [comment]
@rushatgabhane @mdneyazahmad I have created a revert of this PR just to make sure it does not get to Staging, will you be please able to update https://github.com/Expensify/App/pull/8238 to include these changes?

Let's really focus on this so there are no hiccups again, otherwise, we should just get back to the drawing board instead of going back and forth.

**Comment by mountiny** [comment]
This PR has been reverted, let's update the PR you have mentioned 🙇

**Pull request merged**
