### PR TITLE
Fix infinite spinner when signing into an account after signing out

### LINKED ISSUE #3488: Web/mWeb- Sign in - Endless loading spinner appears when re login
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Able to log in to the account without any issue

## Actual Result:
Infinite loading spinner appears on tapping "continue" after entering the email
## Action Performed:
1. Go to https://staging.expensify.cash/
2. Log in with any account
3. Log out
4. Log in again with same account or different account
## Workaround:
Unknown

## Platform:

 Web ✔️
 iOS
 Android 
 Desktop App
 Mobile Web ✔️

**Version Number:** 
1.0.66-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/121415171-6f23d100-c935-11eb-9f7d-4b83af2584e2.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by alex-mechler**
cc @Julesssss @marcaaron 

### Details
Moves the `DeleteLogin` call to be before we clear the auth token, ensuring that we do not make a network request without an auth token.

** This does introduce a new bug, where we drop the user into `/r/` after signing in and out. We have [decided that this should not block the release.](https://github.com/Expensify/Expensify.cash/issues/3488#issuecomment-859746128) **

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/3488

### Tests / QA Steps
1. Sign into an account
2. Sign out of the account
3. _Verify_ you can sign into a different account
    - you will be dropped into `/r/`, and not a chat. This is a different issue which we have decided to live with for now to not block release

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android 

#### Web
image

#### Mobile Web
image

#### Desktop
image

#### iOS
image

#### Android
image

### CODE REVIEW

**Comment by alex-mechler** [comment]
Ready for review, [follow up issue here](https://github.com/Expensify/Expensify/issues/167034). @marcaaron This solves a deploy blocker, so a quick review would be great if you can!

**Review by marcaaron — APPROVED** [review]

**Comment by aliabbasmalik8** [comment]
This issue still produces on the latest main branch.
**VIDEO:** http://recordit.co/vO2GdLgryh

**Comment by alex-mechler** [comment]
@aliabbasmalik8 Did you `npm i`? there was a change that had to be made in onyx that fixed that behavior

**Comment by aliabbasmalik8** [comment]
Okay, Got it. let me check

**Comment by aliabbasmalik8** [comment]
@alex-mechler No, it did not produce after run `npm i`.

**Comment by roryabraham** [comment]
I am going to manually CP this to staging. P.S. if you want to CP a PR to staging the easiest/default way of doing that is by adding the `CP Staging` label _before_ it's merged 😁

**Comment by isagoico** [comment]
@roryabraham Not sure why this PR was added to the staging checklist again. Looks like it was already deployed to production.

**Pull request merged**
