### PR TITLE
[23304] Update tasks status color.

### PR DESCRIPTION
**Pull request by DanutGavrus**
### Details
Task status used to be a link in the past, but it's not anymore. Updated it's color from a blue link color to a gray color.

### Fixed Issues
$ https://github.com/Expensify/App/issues/23304
PROPOSAL: https://github.com/Expensify/App/issues/23304#issuecomment-1644523224

### Tests
Same as QA Steps.

- [X] Verify that no errors appear in the JS console

### Offline tests
Same as QA Steps.

### QA Steps
1. Create a task with any title, description and asignee;
2. Mark it as done -> reopen it -> close it;
3. Verify that "completed task", "reopened task" & "canceled task" messages are gray.

- [X] Verify that no errors appear in the JS console

### PR Author Checklist
- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>
<details>
<summary>Mobile Web - Chrome</summary>

</details>
<details>
<summary>Mobile Web - Safari</summary>

</details>
<details>
<summary>Desktop</summary>

</details>
<details>
<summary>iOS</summary>

</details>
<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by shawnborton** [comment]
The entire system message should use the textSupporting color. The task title should not appear in the regular text color. Can you please update? cc @JmillsExpensify @trjExpensify

**Comment by shawnborton** [comment]
Correct. But where it says "Test Title" here, those are in the wrong color:
image

**Comment by DanutGavrus** [comment]
Hmm, I didn't modify that part. From what I know, it was not discussed in the issue/proposal, but it's very easy to update if needed.

> The entire system message ...

"Test Title" is the actual title which I've gave to the task. Should I leave its color as it was, or to update it?

**Comment by DanutGavrus** [comment]
I don't know if any system message uses that style. My understanding is almost the same. The only difference is that I understood that only the *task's status* is part of the `system message`, while the *task title* would not be part of the `system message` as it's user input and does not come from the system. Comments in the issue also referenced the blue text.  

Let me know if I misunderstood and should update.

**Comment by DanutGavrus** [comment]
> the entire system message should use the text supporting color. So let's update it to use that.  

So, you're saying that the task's title is considered a system message?

**Comment by shawnborton** [comment]
Yes, we are showing the title within the system message itself.

**Comment by DanutGavrus** [comment]
> this should be a shared component that all system messages use  

There's this existing component: [InlineSystemMessage](https://github.com/Expensify/App/blob/main/src/components/InlineSystemMessage.js), which uses:
https://github.com/Expensify/App/blob/dc3270005e924e49a890028bd4b3ef094a939227/src/styles/styles.js#L3152-L3157

Don't know if the `font` is a good fit for this, and also don't think that the `marginLeft` is desired here, but I think we can pass some `style props` in order to add/override what we need.

I think I have to wait for @ArekChr & @dangrous feedback in order to know if it's ok to implement it like that.

**Comment by ArekChr** [comment]
> Also, this should be a shared component that all system messages use. Is there a way to dry this up to make sure we're using the same, consistent system message component everywhere?

We can achieve this by combining `styles.chatItemMessage` and `styles.colorMuted` into a single style or creating a custom Text component that utilizes both styles. Based on what I see in the codebase, it seems unlikely to create text wrappers everywhere, as it consistently uses styles directly.

**Comment by shawnborton** [comment]
I'm not so much talking about styles, I'm also talking about the code here. I would imagine we will use system messages in many other situations, not just tasks.

**Comment by shawnborton** [comment]
@JmillsExpensify do you mind chiming in here? Where else do we currently use system messages?

**Comment by ArekChr** [comment]
> > this should be a shared component that all system messages use
> 
> There's this existing component: [InlineSystemMessage](https://github.com/Expensify/App/blob/main/src/components/InlineSystemMessage.js), which uses:
> 
> https://github.com/Expensify/App/blob/dc3270005e924e49a890028bd4b3ef094a939227/src/styles/styles.js#L3152-L3157
> 
> Don't know if the `font` is a good fit for this, and also don't think that the `marginLeft` is desired here, but I think we can pass some `style props` in order to add/override what we need, or to create a new component: `SystemMessage`.
> 
> I think I have to wait for @ArekChr & @dangrous feedback in order to know if it's ok to implement it like that.

This style is used for inline system errors, has different font size and margins

image

**Comment by DanutGavrus** [comment]
@ArekChr 
> This style is used for inline system errors, has different font size and margins

I think we may make it more customizable as to receive and apply only the `style(s)` received through `props`(for the parent `View` & for the `Text`) , and also to display the icon based on a boolean. 

Or, we may create a new component in a similar manner.

**Comment by shawnborton** [comment]
Sorry to clarify, this system message is different from the inlineSystemError messages. Let's ignore that as it relates to this particular project. 

Here is an example of where we'd use system messages elsewhere, in a different project:
image


The point being, let's not duplicate the work and have multiple ways in the code to render a system message. It's a shared style that will be used all over the platform, not just for tasks. 

But that being said, I can see where that is something we should tackle elsewhere, and this issue should just be about updating the color. 

cc @jasperhuangg @thienlnam - can you comment on the idea of drying this up for future use?

**Comment by ArekChr** [comment]
@shawnborton, what do you think about adding a ":" as a separator between the message and the task name?

like here:
Zrzut ekranu 2023-07-31 o 15 23 05

**Comment by shawnborton** [comment]
Web screenshot looks good. No need to add the `:` - we can leave the message as-is.

**Comment by DanutGavrus** [comment]
@shawnborton 
Ok, thank you!

@ArekChr 
I will proceed to update the other screenshots soon, and make code changes when & if you require. Thanks!

**Comment by DanutGavrus** [comment]
> But that being said, I can see where that is something we should tackle elsewhere, and this issue should just be about updating the color.
cc @jasperhuangg @thienlnam - can you comment on the idea of drying this up for future use?

If refactoring the current component as to make it customizable through props will be desired, I'm available to make that PR for no bounty/payment afterwards.

**Comment by JmillsExpensify** [comment]
@shawnborton sorry for the delay! We already use system messages on `expense` reports. I agree with everything you said above around textSupporting, that's what it's supposed to be, it's just for some reason this isn't the case on Tasks. I'm not sure why. Example on `expense` reports below. 

Screenshot 2023-07-31 at 23 32 07

**Comment by JmillsExpensify** [comment]
Also very minor but important point. All system messages begin with a lowercase letter, not a capitalized one.

**Comment by ArekChr** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>



</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by shawnborton** [comment]
Screenshots look good, thanks!

**Review by ArekChr — APPROVED** [review]
LGTM!

**Comment by DanutGavrus** [comment]
@dangrous I'm rechecking the changes on all platforms and updating the Screenshots now. Please wait before merging, I want to make sure all is good! Thanks!

**Comment by DanutGavrus** [comment]
Done updating my screenshots too, sorry for the delay!

@dangrous all good now!

**Review by dangrous — APPROVED** [review]
Lovely!

**Pull request merged**
