### PR TITLE
fix/14314: Timezone changes to some 1st option in the list while pressing the enter key

### PR DESCRIPTION
**Pull request by tienifr**
### Details

- Fix the missing focus style (it should have background color)
- When going to the options list, initially focus on the item that was selected before, and make it visible in the list

### Fixed Issues

$ https://github.com/Expensify/App/issues/14314   
$ https://github.com/Expensify/App/issues/14314#issuecomment-1398626471

### Tests

1. Login with any account
2. Go to Settings -> Profile and click on timezone
3. Change timezone to some other regions and go back
4. Again click on timezone
5. Verify that the timezone selected before is visible in the list, and have the focus style (background color)
6. Hit the enter key
7. Verify that the timezone remains the same as was selected before and does not change to any arbitrary region

- [x] Verify that no errors appear in the JS console

### Offline tests

1. Turn the network off
2. Repeat the steps in `Tests`

### QA Steps

1. Login with any account
2. Go to Settings -> Profile and click on timezone
3. Change timezone to some other regions and go back
4. Again click on timezone
5. Verify that the timezone selected before is visible in the list, and have the focus style (background color)
6. Hit the enter key
7. Verify that the timezone remains the same as was selected before and does not change to any arbitrary region

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/113963320/214080463-043e4633-4187-43a4-9b8c-615227093dad.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/113963320/214080876-b8cd6da8-cb33-4391-802a-c7e2b0f9982c.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/113963320/214081066-c1720e13-5781-4610-993b-4571d56f16b0.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/113963320/214081432-93b76410-87c1-4794-b9a1-013f9ec0616c.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/113963320/214087918-bbbdf15f-68da-4798-9b0e-4c875535689e.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/113963320/214089174-1d6d2339-112f-4e59-9de7-0e6c657ce2c9.mp4

</details>

### CODE REVIEW

**Comment by tienifr** [comment]
@rushatgabhane You mean that we need to add a regression test for [this issue](https://github.com/Expensify/App/issues/14781)

**Comment by tienifr** [comment]
# Regression Test Proposal

**Bug**: Invite new members - Users is highlighted after selecting

**Proposed Test Steps**:

- Open the app
- Open Workspace and go to the invite member page
- Select some members
- Verify that selected members aren't highlighted

Do we :+1: or :-1: 

Video (Regression Test):
https://user-images.githubusercontent.com/113963320/217418140-3cb8ccba-cdf6-4c41-b674-cd51628590af.mov

**Comment by tienifr** [comment]
@thienlnam @rushatgabhane 

# Regression Test Proposal

**Bug**: Timezone changes to some 1st option in the list while pressing the enter key

**Proposed Test Steps**:

1. Go to Profile and click on timezone
2. Change timezone to some other regions and go back
3. Again click on timezone and now hit the enter key
4. Notice that timezone changes to some other region on pressing the enter key

Do we :+1: or :-1: 

Video (Regression Test):

https://user-images.githubusercontent.com/113963320/218412461-8bdb09e8-9d6b-46a4-b470-1e9e5fc6c2c3.mp4

**Comment by tienifr** [comment]
@thienlnam @rushatgabhane I added regression tests for both issues https://github.com/Expensify/App/issues/14314 and https://github.com/Expensify/App/issues/14781. Please help to check again

**Comment by tienifr** [comment]
@rushatgabhane Please help to check again

**Review by rushatgabhane — COMMENTED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/29673073/220697691-94e155dc-9b2c-4e62-b5e4-b098634855db.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://user-images.githubusercontent.com/29673073/220713130-579f24db-8850-47ab-a70b-a10f39f40d5c.mp4


</details>

<details>
<summary>Mobile Web - Safari</summary>


https://user-images.githubusercontent.com/29673073/220710262-22807044-29d0-4a61-aea2-1834912703ea.mp4



</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/29673073/220701481-a98b09a4-61b4-4ead-b3b1-be08f03c4771.mp4



</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/29673073/220699801-26c8b4e1-4f3a-48a0-8fe8-2fa8fe0ea059.mp4




</details>

<details>
<summary>Android</summary>


https://user-images.githubusercontent.com/29673073/220708395-1e91cdd0-b7f0-4b1b-8c35-800572d70fd2.mp4



</details>

**Comment by thienlnam** [comment]
Taking over review from Andre - @rushatgabhane please let me know when you complete reviewer steps!

**Review by rushatgabhane — APPROVED** [review]
@thienlnam LGTM!

**Review by thienlnam — APPROVED** [review]
Awesome, thanks!

**Comment by thienlnam** [comment]
Merging since this was already approved before

**Comment by priyeshshah11** [comment]
> # Regression Test Proposal
> **Bug**: Invite new members - Users is highlighted after selecting
> 
> **Proposed Test Steps**:
> 
> * Open the app
> * Open Workspace and go to the invite member page
> * Select some members
> * Verify that selected members aren't highlighted
> 
> Do we 👍 or 👎
> 
> Video (Regression Test):

Hi @tienifr just checking, was this tested on iOS as well? Context [here](https://github.com/priyeshshah11/App/commit/eec304385fa3158054ff8651dad0d0d735b08f5c#r102161201)

**Comment by tienifr** [comment]
@priyeshshah11 yes, my PR works well on iOS

**Pull request merged**
