### PR TITLE
fix: optimistic iou report date not matching

### PR DESCRIPTION
**Pull request by jaimebuildsthings**
### Details
The "New Messages" button is incorrectly displayed when creating an IOU, caused by a date discrepancy between the report and the sorted actions and the following expression: https://github.com/Expensify/App/blob/665a8adfdb3239667270b5d23c12287894763d7d/src/pages/home/report/ReportActionsList.tsx#L191

### Fixed Issues

$ https://github.com/Expensify/App/issues/38848
PROPOSAL: https://github.com/Expensify/App/issues/38848#issuecomment-2019213759

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Go to https://dev.new.expensify.com/
2. Log in
3. Navigate to account with a long conversation history
4. Send a message
5. Create IOU
6. Verify no "New Message" button shows up

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/12721875/746ed312-9f87-422e-bebe-117ff08dec05

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/12721875/11c16158-da66-45d4-ab93-d2a07b330b9c

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/12721875/7ca1c053-2c5f-4d53-8629-cf311eaaef1e

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/12721875/8705427c-c6bf-4c47-8a32-f9ab99523935

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/12721875/4ece5d6a-15c1-4eb5-bd66-02565ca50a24

https://github.com/Expensify/App/assets/12721875/622f9764-3917-425d-aae4-c141bfd9b09e

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/12721875/d21885d9-98f5-4c03-a603-89e275c5db68

</details>

### CODE REVIEW

**Comment by cleverjam** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rushatgabhane** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
@cleverjam the issue is still reproducible. Please merge latest `main` to reproduce the issue


https://github.com/Expensify/App/assets/29673073/02068cdc-ef26-4453-aa82-b6e22a0b3132

**Comment by cleverjam** [comment]
@rushatgabhane There is a bit of a discrepancy here:

1. When there is no existing money request, a new one gets created and added as the most recent report action, my change ensures that the time of this new report action matches the `report.lastVisibleActionCreated` as proposed in #38848 
2. On the other hand, when there is an existing money request, the latest report action does not change. Instead an older action gets updated (the existing money request), in other words, the most recent action creation date will not match the `report.lastVisibleActionCreated` and will trigger the "New message" button.

I believe the issue scope was on IOU creation and not on IOU update, however there are several ways we can proceed here, but I need guidance.

1. We can chose to keep the `report.lastVisibleActionCreated` as is when a money request does not create a new action (because existing one gets updated). But this only work until the `/api/RequestMoney` response comes in and the optimistic report's value gets updated, to prevent this there needs to be a service change.
2. We can add even more logic in the [ReportActionsList.tsx](https://github.com/Expensify/App/blob/665a8adfdb3239667270b5d23c12287894763d7d/src/pages/home/report/ReportActionsList.tsx#L191) render, to match the `lastVisibleActionCreated` with any of the sorted report actions, if the date matches any action then set `hasNewestReportAction` to `true` preventing the button from showing, we can memo and only look if the date does not match the most recent action but this will still impact perf.

Please advise on how to proceed

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
@cleverjam okayy let's get this sorted. I noticed that on `staging` this issue doesn't occur anymore. Could you please confirm?

https://github.com/Expensify/App/assets/29673073/956a8ee3-6c76-4c98-8331-206092665435

**Comment by cleverjam** [comment]
@rushatgabhane I can still reproduce in staging when requesting money from another user, it seems your screen capture you are requesting in a workspace...

**Comment by cleverjam** [comment]
@rushatgabhane I have updated my PR, the optimistic report's `lastVisibleActionCreated` still points to the most recent visible action whether the iou request is new or there is an existing IOU and the new requests gets added to that.

However, when `/api/RequestMoney` is resolved the `lastVisibleActionCreated` is updated to whatever the updated IOU created date is, that will cause the new button to show up.... I mitigated this by looking at the sorted report actions to see if any previous action matches this date. Without updates to the BE I don't think I can make this any better

**Comment by rushatgabhane** [comment]
@cleverjam thank you i agree

**Comment by cleverjam** [comment]
> @cleverjam thank you i agree
> 
> I don't have much of a clue. Let's discuss this on slack? I'll attach a link soon

@rushatgabhane any updates?

**Comment by rushatgabhane** [comment]
> existing IOU and the new requests gets added to that.
However, when /api/RequestMoney is resolved the lastVisibleActionCreated is updated to whatever the updated IOU created date is, that will cause the new button to show up.... I mitigated this by looking at the sorted report actions to see if any previous action matches this date.

@cleverjam I don't think this is a good idea because the messages are paginated. We don't have all the messages on frontend.

**Comment by rushatgabhane** [comment]
We'll need help with backend on it. 


@yuwenmemon we need your help on https://github.com/Expensify/App/pull/39665#issuecomment-2048748791

**Comment by yuwenmemon** [comment]
@rushatgabhane what kind of back end change were you envisoning?

**Comment by cleverjam** [comment]
@yuwenmemon sorry about the delayed response, in essence the issue is that the report's 'lastVisibleActionCreated' does not match the most recent action in the money request response.

This occurs when a new request is added to an existing one.

Note: I am responding on GH Mobile app and can add more detail if needed once I am at my desk.

**Comment by yuwenmemon** [comment]
Gotcha :+1: I can take a look! Feel free to add more detail though, always welcome 😄

**Comment by cleverjam** [comment]
@yuwenmemon Yes! 😄 

The reason why I believe the backend needs to be updated is because I was able to fix the issue (until BE update comes in) by updating the optimistic report [here](https://github.com/Expensify/App/pull/39665/files#diff-9c07b44e092fd3d975806649be46d76b75a377c16e32ed86597b630a84c290d0R455).

The change prevents the optimist report from merging a new `lastVisibleActionCreated` value when we are **not** creating a new request (there is an existing request which we will add the new amount into).

When testing this change we get no "New message" button during the time `/api/RequestMoney` is pending, and as soon as the updated report comes back from BE the message pops up. 

I was able to fully test this by adding [this code](https://github.com/Expensify/App/pull/39665/files#diff-42d45a343b031265784f22ea27e4502b3c1968e492b1fc83154414b584d59217R204) in the report list, basically looking in the report action list we have for the new `lastVisibleActionCreated` and as it turns out, that creation time is assigned to the existing money request (which is not the most recent report action)

I apologize if my assumption is incorrect here, perhaps there are other things I can do in the FE to fix the issue? this is my first contribution to this project and I am still learning its ways.

**Comment by cleverjam** [comment]
@yuwenmemon did you get a chance to look into this?

**Comment by yuwenmemon** [comment]
Ah jeez, sorry I did not! Assigned myself so I don't forget about this.

**Comment by cleverjam** [comment]
no problem, just checking, let me know if any of this doesn't make sense or needs to be reconsidered in the FE, thanks!

**Comment by yuwenmemon** [comment]
Closing as per: https://github.com/Expensify/App/issues/38848#issuecomment-2289835521

**Pull request closed without merging**
