### PR TITLE
[Fix] mWeb - Chat - Device keyboard does not auto appear when editing a message

### PR DESCRIPTION
**Pull request by BartoszGrajdek**
### Fixed Issues

$ https://github.com/Expensify/App/issues/39263

### Tests

1. Send a message
2. Try editing the message
3. Make sure that the keyboard appears on mWeb
- [x] Verify that no errors appear in the JS console

### QA Steps

Same as above
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/41169160/5e49487b-71a5-4d8c-ba25-b7a299825dc4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/41169160/6cb42492-8ef6-4ae4-aa85-8bf3ba64d1ce

</details>

### CODE REVIEW

**Comment by BartoszGrajdek** [comment]
cc @shubham1206agra @c3024 @thienlnam

**Comment by jayeshmangwani** [comment]
Reviewing... 🚀

**Comment by jayeshmangwani** [comment]
@BartoszGrajdek Not sure why but I am testing the change on my side and its not working for me, I have pulled your branch and merge latest main , installed node_modules, but yet i am facing the same issue in mWeb safari

https://github.com/Expensify/App/assets/35371050/2615ed22-7012-48d3-bb84-4239e6e1ae0e

**Comment by BartoszGrajdek** [comment]
Hmm that's weird - and how does this work for you on android? 🤔 @jayeshmangwani

**Comment by jayeshmangwani** [comment]
Yes Android works fine for me

**Comment by jayeshmangwani** [comment]
https://github.com/Expensify/App/assets/35371050/218e8557-1bc1-4fa9-82ef-e93a836712de

@BartoszGrajdek Android mWeb works fine, keyboard opens on edit

**Comment by BartoszGrajdek** [comment]
I'll check why it's not working on iOS in that case, give me a moment 👀

**Comment by BartoszGrajdek** [comment]
And does the keyboard open in the main composer when you open a chat on iOS?

**Comment by BartoszGrajdek** [comment]
@thienlnam could we create an adhoc just for web here? I'd like to run it on a real device

**Comment by thienlnam** [comment]
Kicked off the adhoc build

**Comment by BartoszGrajdek** [comment]
Sometimes these bugs related to keyboard are caused by simulators, so that's why I want to check if this may be the reason

**Comment by jayeshmangwani** [comment]
Note: I have tested the production version of the mWEB in real iOS device, and keyboard does not open in it too. please check, on edit if keyboard opens on the real device on your side or not.

@BartoszGrajdek @thienlnam

**Comment by BartoszGrajdek** [comment]
Only after I click once again directly into the edit composer does it open - tested on prod using real device

**Comment by BartoszGrajdek** [comment]
If that's the case I wouldn't even consider this bug we're trying to fix a blocker @thienlnam

**Comment by jayeshmangwani** [comment]
For me, iOS mweb Production and Staging works same way,
But For Android mWeb, in Production the keyboard will be appeared when edit , but in staging keyboard is not appeared on edit ,
So I think we here in this PR, trying to fix the Android mWeb inconsistency between staging and prod, 
What's next for this PR @thienlnam @BartoszGrajdek ?

**Comment by thienlnam** [comment]
Since it already partially functions like that on production, we don't have to handle this with immediate urgency anymore. However, let's continue as planned in this PR making sure that this solves the issue where editing a message opens the keyboard on both mWeb for Android and iOS

**Comment by thienlnam** [comment]
Also, it looks like the adhoc build failed - not sure why but I'll try to re-run it

**Comment by BartoszGrajdek** [comment]
It's not working on a real device as well - I'm not sure why it's fixed only on my simulator 🤯

**Comment by jayeshmangwani** [comment]
There is an old issue that is related to safari mWeb input https://github.com/Expensify/App/issues/10414, and it has more context, so should we proceed with a fix on the Android mWeb on this PR, or should we wait? @thienlnam @BartoszGrajdek

**Comment by thienlnam** [comment]
Let's wait for the other issue - since this isn't fixed with these current changes

**Pull request closed without merging**
