### PR TITLE
Refactor the rest of the code to remove Ion.get()

### PR DESCRIPTION
**Pull request by tgolen**
This final refactoring does quite a few things:

1. It removes all traces of `Ion.get()` and `Ion.multiGet()`
1. It simplifies the Ion connection config to remove `loader`, `loaderParams`, `path`, `defaultValue`, and `addAsCollection`
1. It adds a lot to the readme to help clarify the code philosophy
1. It initializes all Ion connections with the data already in Ion as part of the `connect()` process
1. It adds local timezone support!
1. Simplifies a lot of the promise chains

# Tests
Need to regression test everything. Make sure to sign out and sign in!

### CODE REVIEW

**Review by cead22 — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]
Overall, tons of great improvements here! Really love the simplification of the Ion options. I left a suggestion for how we might be able to simplify Ion even more. And many comments about the README changes.

**Review by marcaaron — CHANGES_REQUESTED** [review]
I might be holding something wrong but when I try to log in it's not possible and I just have an empty session in storage.

Screenshot 1319
Screenshot 1318

Logging in works fine on `master`.

**Repro steps**
1. Clear storage
1. Attempt to login with this branch
1. 💥

**Review by tgolen — COMMENTED** [review]
Thanks, Marc! I've updated the code to address your new round of comments. I'm having trouble testing it due to an infinite loop somewhere (I think Carlos is fixing it).

**Review by marcaaron — COMMENTED** [review]
Went through and resolved a lot of the comments I had + responded to a few more.

**Review by marcaaron — DISMISSED** [review]
Ok here are the tests I performed. Overall working good. But I couldn't repro either of these on the `master` branch.

**Unable to sign in without first refreshing sign in page**
1. Clear local storage
2. Sign in with Expensify login
3. Unable to sign in
4. Refresh page
5. Now able to sign in

Once we are logged in leaving comments works well

1. Sign out
2. Sign in
3. Everything seems ok

But one weird thing that I noticed is that signing out does not unsubscribe you from Pusher. I think maybe it should? But was unsure if there would be any bad effects from that. I tested on `master` and nothing bad happens (even though yes we are still subscribed there as well) then tested on this branch and ran into problems:

1. Sign out as person A
2. Leave a comment from another user on a report as person B
3. Sign in as person A
4. Observed the following errors (see below) and unresponsive app
5. Refresh page and everything works fine again

Screenshot 1329
Screenshot 1330
Screenshot 1332

The Pusher issue seems pretty edge case + we just need to unsubscribe, but I think we should fix the sign in bug.

**Review by cead22 — APPROVED** [review]

**Pull request merged**
