### PR TITLE
[NO QA]Manually update staging to use new GPG key in cherry pick workflow

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
Due to the way the deploy process works, we do not update the staging branch once the checklists are running, however we do update the GitHub workflow code on merge. This has caused a discrepancy in the workflow code and the GPG key on staging. This will update the key and code to match on staging, allowing us to test following these steps: https://github.com/Expensify/Expensify/issues/190171

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/190171#issuecomment-1003165197

### Tests
1. Merge this PR
2. Verify the staging branch has the new GPG key
3. Cherry pick https://github.com/Expensify/App/pull/6951

### QA Steps
N/A

### CODE REVIEW

**Review by aldo-expensify — APPROVED** [review]

**Comment by aldo-expensify** [comment]
GPG key has been updated in staging:

Screen Shot 2021-12-30 at 5 59 33 PM

**Comment by aldo-expensify** [comment]
How do Cherry pick fix: room page layout #6951? Do you manually create a new PR  from branch `parasharrajat:room-page` to `stating`?

**Comment by AndrewGable** [comment]
@aldo-expensify mobile deployers can run a manual cherry pick here: https://github.com/Expensify/App/actions/workflows/cherryPick.yml

Screen Shot 2021-12-30 at 2 13 05 PM


I've kicked one off!

**Comment by aldo-expensify** [comment]
Thanks!

**Comment by aldo-expensify** [comment]
It died, right? 😆

**Comment by AndrewGable** [comment]
It did die, but I forgot to delete the branch `AndrewGable-cherry-pick-staging-6951` where it previously failed, so I deleted it. Then on re-run it worked! https://github.com/Expensify/App/actions/runs/1638813496

Yes, can you resolve the conflicts and merge the PR?

**Pull request merged**
