### PR TITLE
Update guidelines on bugs not happening in production

### PR DESCRIPTION
**Pull request by iwiznia**
Context https://expensify.slack.com/archives/C02NK2DQWUX/p1640209639081000

This is just a process change, no need to QA or test.

### CODE REVIEW

**Comment by mallenexpensify** [comment]
@iwiznia . Line 49
> and add the `DeployBlockerCash` label.

I don't think contributors are able to add labels in issues, so we likely want to update this, maybe to "leave a comment in the issue - "This might be a deploy blocker"" (or.. similar)

**Comment by iwiznia** [comment]
Bump @danieldoglas

**Review by danieldoglas — APPROVED** [review]
LGTM

**Comment by mallenexpensify** [comment]
@iwiznia can you drop a comment in #expensify-open-source that includes details on this update and also include this update too? https://github.com/Expensify/App/pull/6968#issuecomment-1004487051

**Comment by iwiznia** [comment]
I think it is not needed, GH shows to every contributor that the file was updated and tells you to check it out.

**Pull request merged**
