### PR TITLE
Fix the toggle button text style

### PR DESCRIPTION
**Pull request by hayata-suenaga**
### Details

@shawnborton [realized](https://github.com/Expensify/Expensify/issues/387834#issuecomment-2070856003) that the text style next to the toggle button is wrong on Categories and Tags settings screens. This PR fixes the style.

This PR also changes the word `spend` in the UI copy to `expenses`

Screenshot 2024-04-24 at 9 10 43 PM
Screenshot 2024-04-24 at 9 12 14 PM
Screenshot 2024-04-24 at 9 11 35 PM
Screenshot 2024-04-24 at 9 11 45 PM
Screenshot 2024-04-24 at 9 26 28 PM
Screenshot 2024-04-24 at 9 26 34 PM
 Screenshot 2024-04-24 at 9 27 00 PM
Screenshot 2024-04-24 at 9 26 57 PM

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/387834
PROPOSAL: N/A

### Tests / QA Steps

1. Go to the workspace settings page
2. Go to Categories page and click `Settings` button
3. Check the text next to the toggle button. Refer to the screenshots above.

1 Go to the workspace settings page
2 Go to Tags page and click Settings button
3 Verify that the text next to the toggle button is not muted.

### Offline tests
N/A

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
_Tested on the Chrome browser. Please see the screenshots in the PR description_
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by rojiphil** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by rojiphil — COMMENTED** [review]
@hayata-suenaga I think we missed fixing the muted text for `Tags` settings. Did we?

**Comment by hayata-suenaga** [comment]
> @hayata-suenaga I think we missed fixing the muted text for Tags settings. Did we?
forgot to push the last commit. now it's up to date 😓

**Review by rojiphil — APPROVED** [review]
@hayata-suenaga  Few small updates in PR author checklist for your consideration:
1) The linked issue does not seem to be correct. 
2) It would be good to add a test case for `tags` settings too. Something like this:
Steps:
	1	Go to the `workspace` settings page
	2	Go to `Tags` page and click `Settings` button
	3	Verify that the text next to the toggle button is not muted.

Otherwise LGTM. And tests well too.

**Comment by hayata-suenaga** [comment]
@rojiphil thank you for the review 🙇 

> The linked issue does not seem to be correct.
The linked issue is actually correct, I just didn't link [the specific comment](https://github.com/Expensify/Expensify/issues/387834#issuecomment-2070856003) that is relevant to this PR 🙇 

> It would be good to add a test case for tags settings too. Something like this:
Steps:
1 Go to the workspace settings page
2 Go to Tags page and click Settings button
3 Verify that the text next to the toggle button is not muted.

good idea! I added these to the test steps 😄

**Review by nkuoch — DISMISSED** [review]

**Comment by rojiphil** [comment]
@hayata-suenaga There are conflicts in the branch

**Comment by hayata-suenaga** [comment]
I think the issue was fixed on the main branch. @rojiphil could you check if the issues have been fixed? 🙇

**Comment by rojiphil** [comment]
> I think the issue was fixed on the main branch. @rojiphil could you check if the issues have been fixed? 🙇

@hayata-suenaga I think the issue is not fixed completely yet.

Two observations as seen in the attached test video
1. The text still shows muted for `Tags` settings. 
2. The text is `bold` for `Categories` settings. Do you think this is intentional?

https://github.com/Expensify/App/assets/3004659/412740dc-3f75-46e0-ba7d-e2c7958b62a1

**Comment by hayata-suenaga** [comment]
> The text is bold for Categories settings. Do you think this is intentional?

I don't believe that is intentional. @shawnborton for double confirmation.

@shawnborton, the text next to the button shouldn't be bold like the one below, right?

Screenshot 2024-04-29 at 8 24 36 PM

**Comment by shawnborton** [comment]
Correct, that text should not be bold and should just be our regular weight font at 15px size (normal size).

**Comment by nkuoch** [comment]
🤔 
image

**Comment by hayata-suenaga** [comment]
> 🤔

There was a change that uses different component for toggle. So after merging made my changes obsolete.

so I'm working on achieving the same thing with the changed component

**Comment by hayata-suenaga** [comment]
Does this look okay @shawnborton ?

Screenshot 2024-05-01 at 4 04 06 PM
Screenshot 2024-05-01 at 4 07 54 PM

**Comment by hayata-suenaga** [comment]
confirming translation -> https://expensify.slack.com/archives/C21FRDWCV/p1714605765597709

**Comment by shawnborton** [comment]
Looks pretty good! For this screenshot:
image

How far away is the hint text from the stuff above? Is that a global component we're using? In Figma, I think we have the hint text at 4px below the label + toggle: 
CleanShot 2024-05-01 at 20 44 53@2x

CleanShot 2024-05-01 at 20 44 58@2x

**Review by rojiphil — COMMENTED** [review]
@hayata-suenaga  The changes look good on `Categories` settings. 
But we missed bringing the earlier changes to `Tags` settings as the text is still muted.
Also, I think we should change `spend` to `expenses` in `tags` just like in `categories`.

https://github.com/Expensify/App/assets/3004659/569c9a5f-cd24-41c5-8780-4de87ca32e8e

**Comment by shawnborton** [comment]
> But we missed bringing the earlier changes to Tags settings as the text is still muted.

Good catch, let's fix that!

**Comment by rojiphil** [comment]
@hayata-suenaga Gentle bump on the fix [here](https://github.com/Expensify/App/pull/40950#issuecomment-2090313565)

**Comment by hayata-suenaga** [comment]
@shawnborton, sorry for the late response for [your question here](https://github.com/Expensify/App/pull/40950#issuecomment-2089347458)

Screenshot 2024-05-10 at 7 43 08 PM

The distance between the Switch component and subtext is 16px as shown in the above screenshot. The reason for this is that because I'm using the same component with the same configuration as the one used in the Advanced Connection configuration screen as shown below).

Screenshot 2024-05-10 at 7 41 36 PM

The distance between the Switch and the subtexts on the Advanced Configuration screen is also 4px on Figma. But as seen in the above screenshot, it's actually 16px in the production app.

Which one should I use, 16px or 4px? Should we use the same distance or should we use different values for these different contexts?

Screenshot 2024-05-10 at 8 02 47 PM

**Comment by shawnborton** [comment]
It should actually be 4px in Figma:
CleanShot 2024-05-12 at 22 25 26@2x

And ideally we can make it 4px in product too. I recently worked on this same thing with @teneeto over here: https://github.com/Expensify/App/pull/40718

**Comment by hayata-suenaga** [comment]
@shawnborton, thank you for your confirmation 😄 I adjusted my PR accordingly. Could you check the screenshots below when you have time? 🙇 

Before (16px between the Switch and the subtext)
Screenshot 2024-05-13 at 7 49 55 AM

After (4px)
Screenshot 2024-05-13 at 7 49 31 AM

Screenshot 2024-05-13 at 8 16 48 AM

**Comment by shawnborton** [comment]
Looks good to me, thanks!

**Review by nkuoch — APPROVED** [review]

**Comment by hayata-suenaga** [comment]
@rojiphil, could you do the final check and approve the PR is everything looks good? 😄

**Review by rojiphil — APPROVED** [review]
Looks super good to merge. And tests well too. I have updated the checklist with the latest test videos. Thanks.

**Pull request merged**
