### PR TITLE
fix: 26657 Another error message for a short time when opening archived chat from search bar

### PR DESCRIPTION
**Pull request by tienifr**
### Fixed Issues

$ https://github.com/Expensify/App/issues/26657
PROPOSAL: https://github.com/Expensify/App/issues/26657#issuecomment-1714973164

### Tests

1. Open app
2. Click on search icon and find any archived workspace that has some messages in it so that it should be loaded for a short time.
3. If there's no archived workspace that is not loaded before, sign out and sign in again
4. Verify that the skeleton is shown at the bottom where the reason for the chat being archived will show until the message is loaded

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open app
2. Click on search icon and find any archived workspace that has some messages in it so that it should be loaded for a short time.
3. If there's no archived workspace that is not loaded before, sign out and sign in again
4. Verify that the skeleton is shown at the bottom where the reason for the chat being archived will show until the message is loaded

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/113963320/ef47bed7-2ed6-4e53-89bd-e7d1bea697c3

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/113963320/26e2e06c-29b7-4398-bba4-0dff53e6e282

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/113963320/4ea41cac-f286-437b-a9cc-8b123a9129c5

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/113963320/0107210f-ff2c-4050-88e6-a59437f2f76f

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/113963320/c8f9e147-0549-49dc-9fb7-4d9d79d5621b

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/113963320/c8f9e147-0549-49dc-9fb7-4d9d79d5621b

</details>

### CODE REVIEW

**Comment by jjcoffee** [comment]
@tienifr Please can you update the last step to clarify that we're verifying that a skeleton is showing at the bottom where the reason for the chat being archived will show? Thanks!

**Comment by jjcoffee** [comment]
@robertjchen Should we get some design eyes on the look of the skeleton at this stage?

**Comment by jjcoffee** [comment]
@tienifr Also another test step to help reproducing is to sign out if you're already signed in - I wasn't able to get the skeleton to show otherwise! Could you add that?

**Comment by robertjchen** [comment]
@jjcoffee That would be great! Is there a visual screenshot for Design to evaluate/tweak, or would we need them to design something entirely new specifically for this?

**Comment by jjcoffee** [comment]
@robertjchen Sure here's a screengrab from one of the videos:

image

**Comment by jjcoffee** [comment]
Hey @shawnborton or @dannymcclain we need some design eyes on a new skeleton we're adding for displaying the reason why a chat is archived. See still screenshot [here](https://github.com/Expensify/App/pull/27420#issuecomment-1720934931). Thanks!

**Comment by dannymcclain** [comment]
I think this is fine. IMO it feels a tad heavier than necessary but it totally works, and it's not something that I'm _super_ passionate/concerned about. @shawnborton can weigh in too if he has strong feels.

**Comment by shawnborton** [comment]
Can we see what it looks like if we have the reason box but no skeleton line in it? I feel like we might be fine if it's just the highlighted box at the bottom.

**Comment by shawnborton** [comment]
Ah sorry, I meant just no skeleton line within the box at the bottom. But we'd still use skeletons above it right?

**Comment by shawnborton** [comment]
Ah no, apologies. I meant in this screen here:
image

Keep the message skeletons, but in the archived reason box, remove the skeleton line and just use the box BG.

**Comment by shawnborton** [comment]
Okay, yeah, I think I prefer that more though because in this screenshot here, the single skeleton line in the archived reason box feels like it's out of place compared to the other lines above it:
image

So I think not having it might feel more subtle. cc @Expensify/design for thoughts though, as I don't feel strongly.

**Comment by shawnborton** [comment]
Can you get me a side-by-side comparison,  where one screenshot has the skeleton in the archive box and the other does not? Basically this screenshot, but no skeleton in the archive reason box. Thanks!
image

**Comment by shawnborton** [comment]
Okay cool, I don't feel too strongly here. I guess the line version makes more sense. Curious if @Expensify/design has any strong opinions here, what do you think?

**Comment by dannymcclain** [comment]
What if we just made that bottom box have the same color/gradient effect as the avatar and message skeleton? I feel like we could just use that as our "skeleton style" for everything. I don't see a strong reason for it to be different. But I also don't feel super super strongly.

**Comment by shawnborton** [comment]
Oh nice, I like that idea!

**Comment by jjcoffee** [comment]
@tienifr I think we can go with @dannymcclain's [suggestion](https://github.com/Expensify/App/pull/27420#issuecomment-1736657185)?

**Comment by dannymcclain** [comment]
@tienifr That bottom box doesn't look like it's matching the same color as the avatar/message skeleton. The concept is right though, we just want ALL of the skeleton UI elements to share the same color/gradient effect.

**Comment by dannymcclain** [comment]
Hmm, it's not looking the same to me by eye or when I sample the hex codes. Maybe something unexpected it happening?
ghost-color-compare

**Comment by shawnborton** [comment]
Nice, that's feelin' better for sure!

**Comment by dannymcclain** [comment]
Yeah lookin' good!

**Comment by jjcoffee** [comment]
@tienifr Yes, thanks for the bump - reviewing today!

**Review by jjcoffee — APPROVED** [review]
LGTM!

**Review by robertjchen — APPROVED** [review]
Looks great!

**Comment by amyevans** [comment]
👋 This PR was reverted here: https://github.com/Expensify/App/pull/29106

**Pull request merged**
