### PR TITLE
[HOLD] Revert "RN 0.75 upgrade"

### PR DESCRIPTION
**Pull request by situchan**
Reverts Expensify/App#45289

### CODE REVIEW

**Comment by mountiny** [comment]
@situchan Lets try to fix all the issues in staging to avoid this revert

**Comment by situchan** [comment]
I am stuck in android build so no way to test android in PRs I am assigned (without reverting RN upgrade locally).

image

Looks like many people also facing build issues in native https://github.com/Expensify/App/pull/48105#issuecomment-2313147166

**Comment by mountiny** [comment]
Please use this thread to resolve any build issues https://expensify.slack.com/archives/C01GTK53T8Q/p1724842994690509

**Comment by situchan** [comment]
Both android and iOS builds are now successful

**Pull request closed without merging**
