### PR TITLE
Update react-native-onyx with the latest version

### LINKED ISSUE #2762: Improvements to `Onyx.get`
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem: 
- Each time a component “connects” to Onyx we read that data from disk before returning it to `withOnyx`. 
- When multiple components ask for the same key at the same time (e.g. during init | switching chats) the key is requested multiple times from storage
- This causes a lot of unnecessary traffic through the native bridge and adds unnecessary CPU / memory usage
- Confirmed with the following manual benchmarks: https://github.com/Expensify/react-native-onyx/issues/63#issuecomment-832002373

## Solution:
This was widely discussed in the following places and it was decided to go with the cache solution: 
- Improvements for Onyx: https://github.com/Expensify/react-native-onyx/issues/63
- Benchmark Onyx: https://github.com/Expensify/react-native-onyx/issues/65
- Latest slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1620065578311900

###  Prevent unnecessary reads from disk
When a request is made to retrieve something from disk capture the task that would resolve with the read data, as more calls for the same key arrive, instead of making a separate call for the same thing redirect the reads to be resolved from the already pending task. This way only one round trip would ever happen for a given key. As soon as the data for the first call is available - all calls are resolved at once.

### Cache and lazy loading
As data is read from file, keep a reference/pointer to the data in memory in a cache dictionary
Fill the cache lazily - only after a key was requested and read from file
Remove cache entries after the last connection for the given key is disconnected

---

### Additional Work
✔️ Should we implement any benchmarks / metering?

The general principle I like to apply for a benchmark is through method decoration like the same here: https://github.com/Expensify/react-native-onyx/issues/65#issuecomment-821027845

1. Create a metrics capturing function that tracks call and response information
    - call start/end time
    - call execution time
    - arguments for the call
    - tag returned objects so we can see how much of them are still in memory (Or just tag the `cache` map since it should pretty much hold the same information - thought this is only possible after the update that adds cache...)
2. Use a ENV variable (let's say `ONYX_BENCHMARK`) to apply the metring function through decoration to a list of Onyx methods
    - in order to work the methods in the list need to return a promise or have a callback that is triggered when the call is over
    - e.g. the base methods like `get`, `set`, `merge` would pretty much work out of the box
3. Use the same ENV var from above to expose a `readCollectMetrics` and `resetMetrics` as an Onyx method
    - you will be able to further aggregate data like: how much calls were there for `get` with the a specific `key`
    - this can also include information about how much data is currently in cache, after the update is made

---

## Expected Result:
Onyx does not try to retrieve data that is already available in memory

## Actual Result:
Onyx will always ask data from AsyncStorage

## Action Performed:
N/A

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Affected Platforms:
-[x] Web
-[x] iOS
-[x] Android
-[x] Desktop App
-[x] Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by kidroca**
@marcaaron @Jag96 @roryabraham 

### Details

Update E.cash to use the react-native-onyx with with in memory cache

### Fixed Issues

Fixes #2762

### Tests

This update affects the app as a whole. It should become faster and more responsive
There is a known issue where selecting a chat might seem to hang for a bit, details here: https://github.com/Expensify/react-native-onyx/pull/76#issuecomment-853789066

There are no specific steps to do otherwise, the entire app should be tested

### QA Steps

Same as above

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/12156624/121177761-78923800-c866-11eb-9c98-9da9f992598a.mp4

#### Mobile Web

https://user-images.githubusercontent.com/12156624/121179792-c871fe80-c868-11eb-8b77-6ca825a3e482.mov

#### Desktop

https://user-images.githubusercontent.com/12156624/121180744-dbd19980-c869-11eb-8b48-4f4bd0b3bc09.mp4

#### iOS

https://user-images.githubusercontent.com/12156624/121180156-31f20d00-c869-11eb-80a7-71f976151907.mov

#### Android

https://user-images.githubusercontent.com/12156624/121181091-4edb1000-c86a-11eb-8e61-9fb1c648f4c9.mp4

### CODE REVIEW

**Comment by kidroca** [comment]
Stumbled on some problems while testing, but I don't think they are related to the cache changes

### IOUs showing `0.00` [all platforms]
After a fresh install and login all my IOUs we're displaying `0.00`
After refresh they will display the correct amount

https://user-images.githubusercontent.com/12156624/121181858-21db2d00-c86b-11eb-8d31-4c1874541ff8.mp4
- initial value is 0.00
- after clicking "View Details" the value is fixed
- pressing on the badge while it reads `0.00` results in exception
   - the badge in the header inside a chat
   - as well as the badge for a conversation in the LHN

A similar issue happens if someone else made an IOU with me while I'm using the app - the new IOU will appear in LHN with a value of `0.00` it's fixed only after "View Details" or restarting the app

### Request Money does not allow to type a note [mWeb
For some reason the field immediately loses focus

https://user-images.githubusercontent.com/12156624/121182651-fdcc1b80-c86b-11eb-8abd-45800cb145c8.mov

---

Are any of these problems known?

**Comment by kidroca** [comment]
Maybe we should first merge the changes here and update this PR: https://github.com/Expensify/react-native-onyx/pull/79
Or we can open a follow-up

**Comment by kidroca** [comment]
I found out what's causing the  _"IOUs showing `0.00`"_ here: https://github.com/Expensify/react-native-onyx/pull/79#issuecomment-856833531

I'm working on a fix

**Comment by mountiny** [comment]
Great that you found it! I assume we shall wait for that bug to be fixed before merging this. I will try to test it out locally in case any other problem comes up.

**Comment by kidroca** [comment]
I've pushed the fix to the other PR, and verified it's working:

https://user-images.githubusercontent.com/12156624/121215069-59a49d80-c888-11eb-9f07-2901929c2ae2.mov

**Comment by marcaaron** [comment]
Merged so you can update the sha here again with `ebde257d2ebd6f72fe56af6ee3f4630d47c16dc5`

**Comment by kidroca** [comment]
Updated with the latest Onyx version

**Review by Jag96 — APPROVED** [review]
LGTM and tests well ✅ 

I can see that the issue on mobile web where the reason textbox isn't working is present on both production and staging, so I don't think this is related to this PR (posted in slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1623193138110700))

**Comment by trjExpensify** [comment]
Marking this as a deploy blocker, so it's correctly reflected [here](https://github.com/Expensify/Expensify.cash/issues/3450). Thank you both @kidroca and @Julesssss for getting PRs up to fix the IOU regressions today!

**Comment by Julesssss** [comment]
We've closed the linked issues, so marking this as resolved in the deploy checklist.

**Pull request merged**
