### PR TITLE
Fix: IOU - Final review modal design

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

Please find the details here https://github.com/Expensify/App/issues/3952#issuecomment-902211642

### Fixed Issues

$ https://github.com/Expensify/App/issues/3952

### Tests | QA Steps

1. Log in to new.expensify.com on the mobile web on Android device
2. Tap on FAB
3. Tap on Request money
4. Set an amount and continue
5. On user search, click on any user with the keyboard open.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

Updating shortly...

#### Web | Desktop

iou-w

#### Mobile Web

iou-m
iou-mi

#### iOS

iou-i

#### Android

iou-a

### CODE REVIEW

**Review by Luke9389 — APPROVED** [review]
Looking good. I'll stop back here when you've tested with screenshots. Nice job 👍

**Comment by parasharrajat** [comment]
All set @Luke9389

**Comment by Luke9389** [comment]
Nailed it, thanks man 👍

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

**Pull request merged**
