### PR TITLE
[No QA] Ensure bundle version strings are compatible before auto-merging CP PR

### PR DESCRIPTION
**Pull request by Jag96**
@AndrewGable @roryabraham will you please review this?

### Details
This PR updates our CP workflow to ensure that auto-merge PRs won't merge if the bundleVersion string and shortBundleVersion strings aren't compatible. This PR is a revert of https://github.com/Expensify/App/pull/6350, which reverted the initial PR here: https://github.com/Expensify/App/pull/6199.

Compatible bundle version strings: `1.1.1` and `1.1.1.0`
Incompatible bundle version strings: `1.1.1` and `1.1.0.0`

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/178225

### Tests
To test this we'll merge this PR and then CP a dummy change to ensure that there are no CP flow regressions. I also tested this in another public repo [here](https://github.com/Andrew-Test-Org/Public-Test-Repo/pull/59) to confirm everything worked as expected w/ GH actions on an ubuntu box (see [these action runs](https://github.com/Andrew-Test-Org/Public-Test-Repo/actions/workflows/checkBuildVersions.yml))

### QA Steps
None

### Tested On
N/A

### CODE REVIEW

**Comment by AndrewGable** [comment]
So while I agree with this logic: 

> Compatible bundle version strings: 1.1.1 and 1.1.1.0
> Incompatible bundle version strings: 1.1.1 and 1.1.0.0

I thought the issue was we submitted a 1.1.1, it gets approved, then we submit another 1.1.1 when we need to submit a 1.1.2? Is that wrong?

**Comment by Jag96** [comment]
> I thought the issue was we submitted a 1.1.1, it gets approved, then we submit another 1.1.1 when we need to submit a 1.1.2? Is that wrong?

I think you're referring to [this comment](https://github.com/Expensify/Expensify/issues/178225#issuecomment-924404234) which was moved to https://github.com/Expensify/Expensify/issues/178492. The issue we're fixing here is detailed in https://github.com/Expensify/Expensify/issues/178225#issuecomment-960253428, basically the part of the script that is supposed to bump the info.plist version from 1.1.1 to 1.1.2 doesn't happen, but the rest of the workflow continues.

**Comment by AndrewGable** [comment]
Got it- Makes sense!

**Review by AndrewGable — APPROVED** [review]

**Review by nkuoch — APPROVED** [review]

**Review by roryabraham — APPROVED** [review]

**Comment by Jag96** [comment]
Looks like this didn't cause any regressions in https://github.com/Expensify/App/runs/4550113235?check_suite_focus=true 🎉 

image

**Pull request merged**
