### PR TITLE
Make preferences page scrollable

### PR DESCRIPTION
**Pull request by kakajann**
### Details
Makes the preferences page scrollable

### Fixed Issues

$ https://github.com/Expensify/App/issues/6487

### QA Steps

1. Rotate the phone landscape mode
2. Go to the preferences page
2. Try to scroll

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

https://user-images.githubusercontent.com/11542415/143507754-85a1df3b-cca8-4131-8ad9-0fe0fbc811b0.mov

### CODE REVIEW

**Review by parasharrajat — APPROVED** [review]
LGTM.
All yours @Jag96

**Review by parasharrajat — CHANGES_REQUESTED** [review]
@kakajann Please sign your commits so that this can be merged.

**Review by Jag96 — CHANGES_REQUESTED** [review]
Looks like [this commit](https://github.com/Expensify/App/pull/6589/commits/a5880f9ef48e7c39a1b71909f9e306e218e2f63e) still isn't signed, you can try rebasing to sign the commits or just open a new PR if that doesn't work

**Comment by kakajann** [comment]
#6601

**Pull request closed without merging**
