### PR TITLE
Get native versions resynced with package.json

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
I manually updated the version number from package.json without running `react-native-version`, so the version number in the native platforms got out-of-sync. The native platforms were on 1.0.1-420 and package.json was on 1.0.1-422. To fix it, I just ran `react-native-version` twice.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/153656

### Tests
Must test by merging 🙃😬

### CODE REVIEW

**Review by tgolen — DISMISSED** [review]
Looks like this has conflicts now.

**Comment by AndrewGable** [comment]
I think this might have self resolved and no changes are required, but I'll let @roryabraham confirm.

**Comment by roryabraham** [comment]
I don't think this self-resolved. Looks like the versionCode in the native layers is still 2 versions behind `package.json`. Maybe that wasn't the cause of the failure, but we should get these synced up again. I'll resolve the merge conflicts in this PR.

**Comment by roryabraham** [comment]
Okay, updated

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
