### PR TITLE
fix: Stories rendering issues

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7187

### Tests | QA Steps
1. Go to staging.new.expensify.com/docs/index.html
    and verify that you can see the storybook docs with the themes matching the screenshots below.
2. Canvas / Header/ Default
3. Canvas / ButtonWithDropdwn/ Fefault
4. Canvas/ MenuItem/ Default
5. Repeat step 2-4 for Docs tab
 6. Go to HeaderWithCloseButton

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

image508579.png)

### CODE REVIEW

**Comment by mountiny** [comment]
Is this ready for a review?

**Comment by parasharrajat** [comment]
Yeah, Stories only work on the Web. So only a screenshot of the Web is attached.

**Comment by mountiny** [comment]
Yeah yeah, I see you did not run `npm install` to get the new design and Expensify logo in the Storybook :)

**Comment by parasharrajat** [comment]
Let me run the` npm install ` first.

**Comment by parasharrajat** [comment]
I checked the storybook local server and I don't see any error. 
image

Please tell me if you are using something else.

**Comment by mountiny** [comment]
@parasharrajat nono I am using the same. That is odd.

**Comment by parasharrajat** [comment]
An interesting fact is I can't find these strings in our codebase. :smiley:

**Comment by mountiny** [comment]
Yeah, I said that before too which makes me think it must be from Storybook. Well, let's try this on staging then 😄 Thank you for working on this!

**Review by mountiny — APPROVED** [review]

**Comment by kavimuru** [comment]
@parasharrajat  PR is failing. Still we see console errors. Able to reproduce this bug #7187
chrome_DnwJhUVZLL
7

**Comment by parasharrajat** [comment]
These are cors and security errors. It does not break the Storybook in any way. You can see that headers are rendered correctly on the Canvas. 
It is about the deployment and configuration of the Storybook so it should be handled on the backend. To me, it does not matter much but I will leave this to @mountiny to decide. 
image

**Comment by mountiny** [comment]
Yes, that is true. These errors are cors related and not sure if there is anything simple we can do about this. These errors are not reproducible in the local dev environment.

@kavimuru I think we will have to accept these particular errors will be around for Storybook for a while. Would you be able to reflect it in your QA steps, please? They always refer `Content Security Policy` or `CSP`.

Can you also label this as passing the QA? It has resolved the other issues and Rajat can't do much about this particular type of errors.

**Pull request merged**
