### PR TITLE
feat: Expense Tracking in the Workspace Chat

### PR DESCRIPTION
**Pull request by paultsimura**
### Details
This PR enables tracking expenses within the Workspace money reports.

### Fixed Issues

$ https://github.com/Expensify/App/issues/38971
PROPOSAL: N/A

### Tests

Same as QA

### Offline tests

Same as QA

### QA Steps

1. Go to your own policy expense chat where you don't have an active expense report
2. Click "+" -> Track expense -> proceed with amount of $10
3. Verify a Report Preview was created with title "{user} spent: $10"
4. Open the Expense report
5. Verify the total shows $10
6. Click "+" -> Request money -> proceed with $5
7. Verify the total now shows a separation:
   - Total: $15
   - Out-of-pocket spend: $5
   - Company spend: $10
8. Click "+" -> Track expense -> proceed with amount of $5
9. Verify the total now shows a separation:
   - Total: $20
   - Out-of-pocket spend: $5
   - Company spend: $15
10. Click "Submit"
11. Click "Approve"
12. Verify a message 
13. Verify the settlement button now says "Pay $5 ..."
14. Click "Pay elsewhere"
15. Verify it says "Paid $5 ..."
   
### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/12595293/f357dc70-ccab-4b62-8852-cef03bd3a9ca

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/12595293/25890b7f-9be7-4deb-a6f4-376f56404a47

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/12595293/dda1bc89-38de-44e4-97c3-ae6ba4e07654

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/12595293/2367b740-eecb-4f84-a288-0158d61f971d

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/12595293/703a2d3b-eceb-48c9-82d1-e93948bd06af

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/12595293/7e70ca50-cd64-4002-bfc8-2574fa1f8164

</details>

### CODE REVIEW

**Comment by dannymcclain** [comment]
Hmm, I'm really curious for the other designer's thoughts on these.

>First – there is no visual difference between the tracking expense (1st) and the actual money request (2nd) – do we want to change it?

For this one, I could maybe see editing the `Cash` line or maybe just adding a dot separator and appending something there to make it more clear? I'm not sure.

>Is there any design for what we should show in such cases (when there are reimbursable and non-reimbursable requests combined)?

This one has me kinda stumped. I don't know that we want to change the preview behavior or create a custom preview for tracked expenses, so I'm not sure if there's a good solution for this.

@Expensify/design any ideas?

**Comment by shawnborton** [comment]
> First – there is no visual difference between the tracking expense (1st) and the actual money request (2nd) – do we want to change it?

Correct - whether you track a personal expense or send someone a money request, they are both just expenses under the hood and they would look the same at the expense level. 

> Do I understand correctly that adding a Tracking Expense inside an Expense Report should increase the Total and Company spend, but not the Out-of-pocket spend?

I don't understand why we are handling it this way. If you add an expense to a report, it just increases the total. The "Company spend" vs "Out of pocket spend" is just a nicer way of saying "Is this expense reimburseable or not?" 

Unless I am missing something. Did the GH issue or design doc specify otherwise?

> When there are no other money requests, only a tracking one, it will look like this (showing only Total), are we ok with this?

Yes. We already have existing patterns for what expenses look like when they are added to a workspace, so we just follow what we currently have. 

@thienlnam can you also chime in here? Seems like maybe there is some misunderstanding going on.

**Comment by shawnborton** [comment]
Hmm did the user take any action to trigger that state? Like did the user mark the report as Paid? If so, then yes.

**Comment by shawnborton** [comment]
Cool, then I think what you have is correct. We shouldn't really view these as "special" transactions, we should try to treat them like any other expense as best we can.

**Comment by shawnborton** [comment]
> Should I see a GBR indicator on LHN for track expenses on workspace?

Good question - perhaps bring to Slack for discussion? I feel like if there is no action to take, there shouldn't be a green brick road dot. And I think this should be consistent everywhere, not just the personal tracking case. cc @JmillsExpensify @puneetlath for thoughts

**Comment by thienlnam** [comment]
Yeah, the changes for deleting a tracked expense should be fixed and live now.

Also, to clarify the current issues that need to be updated on the BE:
- Prevent GBR from showing on workspace chat
- Returned total on a deleted request https://github.com/Expensify/App/pull/39239#issuecomment-2028159067
- Returned total on approving a money request https://expensify.slack.com/archives/C01GTK53T8Q/p1711993297064759?thread_ts=1711645376.852749&cid=C01GTK53T8Q

Is there anything else?

**Comment by thienlnam** [comment]
I'll pull this branch and take a look

**Comment by thienlnam** [comment]
https://github.com/Expensify/App/assets/30609178/fc7c173c-5d8c-49a2-a25f-61d55e8875fc
Hmm it seems to work fine for me

**Comment by thienlnam** [comment]
Yeah I agree we shouldn't find a workaround from the FE side. However, it doesn't seem like a blocker so we can proceed here and then once the BE is fixed it should just work

**Review by shubham1206agra — APPROVED** [review]
LGTM!

**Review by thienlnam — APPROVED** [review]
Great - thanks!

**Comment by MonilBhavsar** [comment]
We seem to have a regression here https://github.com/Expensify/App/issues/40067. If anyone can please take a look cc @paultsimura @shubham1206agra @thienlnam

**Pull request merged**
