### PR TITLE
[CP Staging] Bump `react-native-live-markdown` to 0.1.82

### PR DESCRIPTION
**Pull request by BartoszGrajdek**
### Details

This PR bumps the version of live markdown

### Fixed Issues

$ https://github.com/Expensify/App/issues/41696
$ https://github.com/Expensify/App/issues/39255
$ https://github.com/Expensify/App/issues/42160
$ https://github.com/Expensify/App/issues/17767
$ https://github.com/Expensify/App/issues/14445
$ https://github.com/Expensify/App/issues/15640
$ https://github.com/Expensify/App/issues/41137
$ https://github.com/Expensify/App/issues/41567
$ https://github.com/Expensify/App/issues/42523
$ https://github.com/Expensify/App/issues/41078

### Tests

The best course of action would be to go through each of the issues added above and verify if just the changes in react-native-live-markdown were needed to fix them. If so you can test if they are not happening anymore. Here's a list of some of the issues & testing steps:

2. https://github.com/Expensify/App/issues/41078
Check if only valid phone number mentions are allowed
3. https://github.com/Expensify/App/issues/42523
Check if you are able to type in the composer on android mWeb
4. https://github.com/Expensify/App/issues/41567
Check if you are able to scroll task description input
5. https://github.com/Expensify/App/issues/41137
Check if pasting on android mWeb
6. https://github.com/Expensify/App/issues/17767
Paste text from issue desc and check if it's displayed properly
7. https://github.com/Expensify/App/issues/39255
Check if you are able to undo copy pasted text
8. https://github.com/Expensify/App/issues/41696
Check if markdown is treating `>test` and `> test` differently (the second one should be a quote, the first one just plain text)

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/41169160/5e3f2da5-6746-4371-b691-d3db41fa7049

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/41169160/3bb52893-8249-453c-9ad4-446d4ea7dcee

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/41169160/2d674b78-22b0-4fa4-8984-e4fcfeb3289b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/41169160/f15ddef9-d7b4-4e91-bd46-34a590069ac7

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/41169160/83684ebf-5d4a-48f4-b4e2-0a152eee7474

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/41169160/60c2d9df-1a6a-44d7-953f-18a941cd708a

</details>

### CODE REVIEW

**Comment by BartoszGrajdek** [comment]
cc @luacmartins

**Comment by BartoszGrajdek** [comment]
cc @tomekzaw @SzymczakJ

**Review by luacmartins — APPROVED** [review]

**Comment by tomekzaw** [comment]
> https://github.com/Expensify/App/pull/43255#issuecomment-2154906692

Actually, this wasn't supposed to be fixed, I think it's in the PR description by mistake. Thanks for pointing this out.

**Comment by luacmartins** [comment]
Thanks @ishpaul777. It seems like https://github.com/Expensify/App/issues/41597 shouldn't be fixed in this PR, so I removed it from the OP. As for https://github.com/Expensify/App/issues/41137, that's no longer a blocker, so I think we can merge this and continue to work on a solution for https://github.com/Expensify/App/issues/41137

**Review by ishpaul777 — APPROVED** [review]

**Comment by kavimuru** [comment]
1. [Live Markdown treats > space and >nospace equally](https://github.com/Expensify/App/issues/41696) Failing in mweb , desktop and native apps

https://platform.utest.com/services/links/v1/internal/51620598?.mp4
https://platform.applause.com/services/links/v1/external/f916461c07391fd466e658254fcfb563574b41b84e21b539481ccd655dfeb380
https://platform.utest.com/services/links/v1/internal/51620643?.mp4
https://platform.applause.com/services/links/v1/external/78183abdc52fcd999d20dbe7c331e946b519afcab806a6d18b0b8f384b5def44

2. [[$500] Unable to undo copy and pasted text](https://github.com/Expensify/App/issues/39255) - Failing in web

https://platform.applause.com/services/links/v1/external/c0c9dbe667126f8e96131d8f41281532421f41efd3242c21a9ff54f5bf240040

3. Found a blocker [Chat - Emoji gets inserted in front of entered text](https://github.com/Expensify/App/issues/43312) when validating (https://github.com/Expensify/App/issues/14445)

4. [mWeb - Chat-Pasting text in compose box makes page moves up and down](https://github.com/Expensify/App/issues/41137) failing in mweb https://platform.utest.com/services/links/v1/internal/51618911?.mp4

5. [App crashes after pressing R in metro bundler on iOS simulator](https://github.com/Expensify/App/issues/42160) can't be retested in staging

**Comment by fabOnReact** [comment]
#### Expensify Composer (When moving to another line, the word and emoji are close to each other):

All tests for Issue https://github.com/Expensify/App/issues/14445 are successfull.

The difference of baseline is 1.15 (barely noticeable), maximumLineHeight 20, maximumFontLineHeight 17.69

| Before    | After |
| ----------- | ----------- |
|       |        |

| Before    | After |
| ----------- | ----------- |
|       |        |

The result below is achieved after setting [textInputCompose.lineHeight: 40](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/styles/index.ts#L2080).
- baseLineOffset is 11.15
- maximumLineHeight is 40
- maximumFontLineHeight is 17.69

| Before    | After |
| ----------- | ----------- |
|       |        |

| Before    | After |
| ----------- | ----------- |
|       |        |

| Before    | After |
| ----------- | ----------- |
|       |        |

Issue https://github.com/Expensify/App/issues/14445 requires also Meta team to merge PR https://github.com/facebook/react-native/pull/44614.

**Pull request merged**
