### PR TITLE
Feature: Render markdown in thread header

### PR DESCRIPTION
**Pull request by tienifr**
### Details

Expected outcome for thread name in LHN:
- Only the first line of the message should display on the thread title with no trailing space

Expected outcome for thread header:
- Only the first line of the message should display on the thread title with no trailing space
- Markdown, if in a thread title, should display as markdown
   - Heading markdown should display as text only (no formatting)
   - Code fence should display as inline code

### Fixed Issues

$ https://github.com/Expensify/App/issues/22832
PROPOSAL: https://github.com/Expensify/App/issues/22832#issuecomment-1652795468

### Tests

1. Login with any account
2. Go to any report
3. Send a message with multiline code fence (3 backticks markdown)
4. Reply in thread
5. Verify that thread header displays as the expected outcome
====
6. Repeat step 2-5 with all supported markdowns: # Heading, `Inline code`, [Link](url), Email, **Bold**, _Italic_, ~Strikethrough~, > Quote, Mention user, Mention here.
7. Back to LHN, verify that thread's report name displays as expected outcome

- [x] Verify that no errors appear in the JS console

### Offline tests

NA

### QA Steps

Expected outcome for thread header:
- Only the first line of the message should display on the thread title with no trailing space
- Markdown, if in a thread title, should display as markdown
   - Heading markdown should display as text only (no formatting)
   - Code fence should display as inline code

1. Login with any account
2. Go to any report
3. Send a message with multiline code fence (3 backticks markdown)
4. Reply in thread
5. Verify that thread header displays as the expected outcome
====
6. Repeat step 2-5 with all supported markdowns: # Heading, `Inline code`, [Link](url), Email, **Bold**, _Italic_, ~Strikethrough~, > Quote, Mention user, Mention here.
7. Back to LHN, verify that thread's report name displays as expected outcome

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

image

image

image

image

image

image

image

image

image

image

image

</details>

<details>
<summary>Mobile Web - Chrome</summary>

image

image

image

image

image

image

image

image

image

image

image

</details>

<details>
<summary>Mobile Web - Safari</summary>

simulator_screenshot_F77EC10F-4E88-409D-B463-54E68068443B
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 38 45
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 38 48
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 38 55
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 38 59
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 02
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 05
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 08
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 12
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 20
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 23
Simulator Screenshot - iPhone 15 Pro Max - 2023-10-13 at 16 39 26

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

simulator_screenshot_2EE60272-34FA-4BD7-93F4-0F2F4D6AD35F
simulator_screenshot_1A3F69EF-B8BE-471E-A145-DB020AC22074
simulator_screenshot_1C204730-8EB9-4ACE-986E-55F23C8C9DEC
simulator_screenshot_164799CE-6E7D-4A74-A839-7641FFA40801
simulator_screenshot_F690579A-2491-4164-81A0-2469A9B38706
simulator_screenshot_20C353EA-AD08-4D88-BDD8-648167C98086
simulator_screenshot_CE2CEB81-9D43-4BA2-9415-8601CFBF245A
simulator_screenshot_1B40B9CE-F8E4-4C4C-971A-71445C815B17
simulator_screenshot_C68C2C2F-08D7-43BC-B837-711F29781F47
simulator_screenshot_709D6775-CB18-4D8B-899A-C0BE35FFC261
simulator_screenshot_2A776E94-2851-4BCE-89D9-AECE5647280F
simulator_screenshot_DE5371FA-5C92-4599-BEFC-DB62EF716E48

</details>

<details>
<summary>Android</summary>

Screenshot_1697185621
Screenshot_1697188475
Screenshot_1697188485
Screenshot_1697188532
Screenshot_1697188537
Screenshot_1697188541
Screenshot_1697188545
Screenshot_1697188550
Screenshot_1697188575
Screenshot_1697188580
Screenshot_1697188584
Screenshot_1697188589

</details>

### CODE REVIEW

**Comment by sobitneupane** [comment]
@tienifr Any update?

**Review by sobitneupane — COMMENTED** [review]
I am yet to review all the cases. But initial tests are quite promising. Thanks for the work @tienifr

The header still overflows. 

https://github.com/Expensify/App/assets/25876548/9de62cd2-816b-4e7b-88ea-be967f1e557b

Screenshot 2023-08-23 at 16 30 02

**Review by sobitneupane — COMMENTED** [review]
@tienifr Since we are only using first line in the header, should we do the same in LHN as well? What do you think?

**Comment by sobitneupane** [comment]
image

**Comment by sobitneupane** [comment]
Sorry for the delay @tienifr. I will probably get to this PR before the weekend. In the meantime, could you please verify that my concerns have been addressed?

https://github.com/Expensify/App/pull/24574#pullrequestreview-1591278303
https://github.com/Expensify/App/pull/24574#pullrequestreview-1591279877
https://github.com/Expensify/App/pull/24574#issuecomment-1689735209

**Comment by sobitneupane** [comment]
@tienifr I am sorry for the delay. 

For LHN, I was saying we should show single line but looks like you have added markdown. I think we should revert it back but we should show only text present in heading.

We are showing normal text in header instead of markdown. Can you please check at your end? 

I will continuously work on this. I will be OOO from Monday (for a week). I want to get it merged before that.

Screenshot 2023-10-12 at 17 16 31

Thank you for your work @tienifr

**Comment by sobitneupane** [comment]
> Does this rule apply globally for threads, for example to report name in Onyx and report title in report details modal? Or is it just for displaying?

Let's keep it just displaying in LHN for now. We can work it on other PR if we decide to otherwise.

**Review by sobitneupane — COMMENTED** [review]
1. Found an issue. When we send a normal text with special characters like `<`  or `&`, we show entity name instead of those character.
Screenshot 2023-10-31 at 18 39 06

**Comment by sobitneupane** [comment]
On native device (IOS and android), quotes are not displayed as expected in the header.
Screenshot 2023-10-31 at 19 08 58

**Review by sobitneupane — COMMENTED** [review]
### Screenshots/Videos
<details>
<summary>Android: Native</summary>


Screenshot 2023-10-31 at 19 51 50
Screenshot 2023-10-31 at 19 51 57
Screenshot 2023-10-31 at 19 52 10
Screenshot 2023-10-31 at 19 52 18
Screenshot 2023-10-31 at 19 52 28
Screenshot 2023-10-31 at 19 52 36
Screenshot 2023-10-31 at 19 52 43
Screenshot 2023-10-31 at 19 52 51
Screenshot 2023-10-31 at 19 53 04

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot 2023-10-31 at 19 01 09
Screenshot 2023-10-31 at 19 01 27
Screenshot 2023-10-31 at 19 00 35
Screenshot 2023-10-31 at 19 00 05
</details>

<details>
<summary>iOS: Native</summary>

Screenshot 2023-10-31 at 19 51 25
Screenshot 2023-10-31 at 19 13 09
Screenshot 2023-10-31 at 19 13 42
Screenshot 2023-10-31 at 19 44 21
Screenshot 2023-10-31 at 19 48 44
Screenshot 2023-10-31 at 19 50 24
Screenshot 2023-10-31 at 19 51 07
Screenshot 2023-10-31 at 18 48 42

Screenshot 2023-10-31 at 18 50 28
</details>
<details>
<summary>iOS: mWeb Safari</summary>

Screenshot 2023-10-31 at 18 53 21
Screenshot 2023-10-31 at 18 53 32
Screenshot 2023-10-31 at 18 53 41
Screenshot 2023-10-31 at 18 53 56
Screenshot 2023-10-31 at 18 54 07
Screenshot 2023-10-31 at 18 54 18
Screenshot 2023-10-31 at 18 54 42
Screenshot 2023-10-31 at 18 54 58

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>
Screenshot 2023-10-31 at 18 12 43
Screenshot 2023-10-31 at 18 05 28
Screenshot 2023-10-31 at 18 05 51
Screenshot 2023-10-31 at 18 06 07
Screenshot 2023-10-31 at 18 07 57
Screenshot 2023-10-31 at 18 09 11
Screenshot 2023-10-31 at 18 10 02
Screenshot 2023-10-31 at 18 10 31
Screenshot 2023-10-31 at 18 11 18
Screenshot 2023-10-31 at 18 11 33

</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by sobitneupane** [comment]
Messages with markdown keeps flickering on IOS and Android.

https://github.com/Expensify/App/assets/25876548/32e7f800-d2f3-4ee7-9a2d-bb1e9f5b70fa

Header with markdown in not bold in Android and IOS where as in Web and mWeb all headers appear bold.

**Comment by sobitneupane** [comment]
@tienifr Any update?

**Comment by sobitneupane** [comment]
@tienifr Let's get this fixed asap.

**Comment by sobitneupane** [comment]
Thanks for the update @tienifr. I will prioritize this PR and will review it asap. In the mean time, can you please thoroughly test it in your end as well. There are around 70 commits. And we are likely to have issues in Native applications.

**Comment by sobitneupane** [comment]
Thanks for the update @tienifr.

I am testing the PR now. It tested well in web. I am planning not to block the PR for minor issues. We can deal with the minor issues separately in another PR.

**Review by sobitneupane — COMMENTED** [review]
### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/25876548/c928b5c4-0a86-4d8e-868f-bd5d1bce5f8e


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/25876548/f29f6579-67b4-4b61-99d5-a87f31f6c45d

</details>
<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/25876548/0e36439f-88db-4c87-b375-183e63edf2fb


</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/25876548/6e36f64a-8497-4b7c-bd8e-54c068c22425

</details>

**Comment by sobitneupane** [comment]
@tienifr I found some issues in android native:
1. Quotes with large text
2. Inline codes with large text
3. Inline code followed by text

https://github.com/Expensify/App/assets/25876548/07c51faf-431b-4775-a797-1fddcaff3a75

**Comment by sobitneupane** [comment]
There are some minor issues in Web like truncating quotes with large text, etc. which can be dealt later on.

**Comment by sobitneupane** [comment]
@tienifr Any update?

**Comment by sobitneupane** [comment]
@tienifr Let's focus on this issue. Can you please update where you are stuck now?

**Comment by sobitneupane** [comment]
What can we do to get this PR merged? We can open follow up PR for some implementations if it doesn't break anything.

**Comment by sobitneupane** [comment]
Any update @tienifr ?

**Comment by sobitneupane** [comment]
> I'm still blocking on these issues https://github.com/Expensify/App/pull/24574#issuecomment-1991044985 where blockquote does not work properly. I found the root cause but no optimal solution had been found. If we want merging ASAP, I think we should exclude blockquote from thread-title and resolve in future PRs.

@tienifr Yup. That sounds like a good idea. Please test it thoroughly at your end, update the screen recordings and let me know.

**Comment by shawnborton** [comment]
Let us know when there are updated screenshots to review, thanks!

**Comment by shawnborton** [comment]
Actually... I'm kind of curious why we are even doing this in the first place. Going to head to the original issue to discuss.

**Comment by shawnborton** [comment]
Can you update them with the latest? They seem quite dated:
CleanShot 2024-05-24 at 16 15 57@2x

Either way, we are discussing in Slack and I think it might have been a mistake to allow for the markdown to appear in the report headers, especially with no clean way of truncating things. 

So let's pause for a moment until we get clarification from @JmillsExpensify, but I think we should keep the report headers as just our normal app text style.

**Comment by shawnborton** [comment]
What's the latest here? Can we just close this one?

**Comment by shawnborton** [comment]
Friendly bump @tienifr and @sobitneupane - what's the status with this one?

**Comment by sobitneupane** [comment]
@shawnborton Looks like we don't want to make the change introduced by this PR. So, I think we are good to close this out.

**Pull request closed without merging**
