### PR TITLE
Fix copy to clipboard in long emails

### PR DESCRIPTION
**Pull request by luacmartins**
cc @chiragsalian 

### Details
Also fixed an issue with the space below display name and `Email` or `Phone`, as well as copy to clipboard being shown on user's display name. See screenshot below:

Screen Shot 2021-07-20 at 10 40 50 AM

### Fixed Issues
$ https://github.com/Expensify/App/issues/4076

### Tests
1. Open a chat with a user that has a long email address, e.g. applausetester+0118mn@applause.expensifail.com
2. Tap on user's avatar to open their details page
3. Verify that the copy to clipboard icon is visible

### QA Steps
Steps above.

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

#### Web

https://user-images.githubusercontent.com/22219519/126380578-f7c8d96a-634a-42c3-b98c-c7ae9631a8d0.mov

#### Mobile Web

https://user-images.githubusercontent.com/22219519/126380595-22ab60b6-9847-47bd-89c7-8ec4e11eecda.mov

#### Desktop

https://user-images.githubusercontent.com/22219519/126380612-ad8aebce-d93e-4e92-a1e4-875da69b8bf8.mov

#### iOS

https://user-images.githubusercontent.com/22219519/126380626-3c94d409-93ed-4699-a0a4-1376e2d16d7f.mov

#### Android

https://user-images.githubusercontent.com/22219519/126380646-094217c2-9bdf-481f-8f49-9a608c91decb.mov

### CODE REVIEW

**Comment by parasharrajat** [comment]
The whole point of using absolute position was that its presence should not affect the layout of the original component.

If we want to remove this feature from the Phone number under the Avatar then it's fine. Otherwise, it would push the phone number under the avatar towards the left.

To fix this just inline the Name and Apply right padding= width of an icon button.

**Comment by luacmartins** [comment]
The feature was removed from the phone number under the avatar.

**Review by sketchydroide — APPROVED** [review]
LGTM

**Comment by mananjadhav** [comment]
I am tagging this PR to highlight an issue fixed [here](https://github.com/Expensify/App/issues/16683). All conditions in ternary expressions or left-hand operands on conditional renders, should be boolean. This PR is one of the PRs that uses conditional render with string operands, hence I am tagging it here for the contributors to check. 

We've also updated the item in the checklist with this [PR](https://github.com/Expensify/App/pull/18069) to avoid this issue in the future.

**Pull request merged**
