### PR TITLE
Update payments page to use Expensify logo for Expensify Card

### PR DESCRIPTION
**Pull request by puneetlath**
### Details

Updates the icon used in the payments section of the app for the Expensify Card. For other cards, we're using the logo of the issuer. In this case, since Expensify is the issuer, the logo being used is the Expensify logo. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/5215

### Tests

1. Go to Settings > Payments in an account that has an Expensify Card assigned and is also importing other cards
2. Look at the list of Payment methods
3. Make sure the Expensify Card is showing the Expensify logo 
4. Make sure all other logos are showing as expected

### QA Steps

1. Go to Settings > Payments in an account that has an Expensify Card assigned and is also importing other cards
2. Look at the list of Payment methods
3. Make sure the Expensify Card is showing the Expensify logo 
4. Make sure all other logos are showing as expected

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

image

#### Mobile Web

image

#### Desktop

image

#### iOS

Screen Shot 2021-09-14 at 12 49 06 PM

#### Android

image

### CODE REVIEW

**Comment by iwiznia** [comment]
Should I review this? Asking because it's WIP

**Comment by puneetlath** [comment]
Not yet! I guess PR's automatically get assigned our in this repo, even though I hadn't assigned puller bear yet. I'll ping you when it's no longer WIP.

**Comment by puneetlath** [comment]
@iwiznia it's ready for your review now!

**Review by iwiznia — APPROVED** [review]

**Comment by mvtglobally** [comment]
@puneetlath @iwiznia what account can we use to validate this PR? 
We are unable to see needed details with Applausecard account

**Comment by puneetlath** [comment]
You can use any account that has an Expensify Card assigned to it and log into new.expensify.com and view the Payments page.

**Comment by isagoico** [comment]
@puneetlath I checked on our testing account that has an active Expensify Card and it's not visible in the payments Page. 
tester@applausecard.expensifail.com (Credentials in 1Password) 

image

**Comment by puneetlath** [comment]
Ah, it looks like this PR made my PR obsolete: https://github.com/Expensify/App/pull/5212

**Comment by isagoico** [comment]
Oh, how should we proceed here then? Should I create a separate issue about the card not appearing?

**Comment by puneetlath** [comment]
We can go ahead and let this go to production, it won't hurt anything. And I'll submit a follow-up PR to clean up the logic given that the change made here is no longer needed.

**Pull request merged**
