### PR TITLE
fix issue 6326: Chat - Magnifying glass displayed anywhere

### PR DESCRIPTION
**Pull request by railway17**
### Details
- Because `cursor: zoom-in` style was assigned to the ancient of the `Image` component, this cursor was displayed out of the image area.
To resolve it, I reassign this style to image (Actually, I assigned it to `Pressable` component because the `Image` component is wrapped by it).
- While reassigning this style, I had to keep the center alignment of the image in the modal.
For center alignment, I calculated the offset based on modal size and image size.
- When the image is expanded, it was using scaled width and height. I have kept this code like below
```
   if (isZoomed) {
        return {
            height: `${(imgHeight * zoomScale)}px`,
            width: `${(imgWidth * zoomScale)}px`,
        };
    }
```

### Fixed Issues
$ [GH_LINK](https://github.com/Expensify/App/issues/6326)

### Tests

1. Send the image to someone.
2. Click the image thumbnail in the chatbox.
3. Modal is open to display the image.
4. Image is center aligned.
5. Check the cursor while hovering around the image.
6. Check the zoom in and zoom out functionality.

### QA Steps
1. Send the image to someone.
2. Click the image thumbnail in the chatbox.
3. Check the center alignment of an image in the modal.
5. Check the cursor while hovering around the image.
6. Check the zoom in and zoom out functionality.

### Tested On
This issue is just a hovering issue, don't need to check for mobile platforms.
- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web
[web fix video](https://drive.google.com/file/d/1DKGHBaSYwr4MJgAk6yMwJYj9P7_M264L/view?usp=sharing)

#### Desktop
[desktop fix video](https://drive.google.com/file/d/1KzE5WtSgUj6ivmeVJvhPfkw_U-UqRxyi/view?usp=sharing)

### CODE REVIEW

**Comment by railway17** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by deetergp — CHANGES_REQUESTED** [review]
The code looks good and tests well when the image is zoomed out, but once the image is zoomed in, the magnifying glass goes back to appearing everywhere. Can you update the zoomed in behavior to match the zoomed out?

https://user-images.githubusercontent.com/766197/143146103-3f39e62c-f50f-4644-9a97-cdfa30cd533d.mp4

**Comment by railway17** [comment]
image
As I mentioned in 3) of the pull request detail, I kept the width and height when it is zoomed ((it is original code) because I thought you want this size.
But I got it you need the same feature even though the image is zoomed.
I will fix it and update you shortly

**Comment by deetergp** [comment]
Fair, though it didn't really make sense till I saw it in action — after seeing it, I think it makes more sense to have it behave the same.

> I will fix it and update you shortly

Thanks!

**Comment by railway17** [comment]
@deetergp 
Please review new commits.
I calculated the `zoomScale` again by using `Math.min` instead of `Math.max` based on modal size.
I am attaching my testing video again.

[- new web fix](https://drive.google.com/file/d/1606qt3vg2E-xy4PMdZ9w0s4lyWaE0l2e/view?usp=sharing)
[- new desktop fix](https://drive.google.com/file/d/1ltWQ4Fw8x61oxoUYwJRqWRHXq_Zf3qrI/view?usp=sharing)

**Review by deetergp — APPROVED** [review]
Looks good and tests well. Thanks!

**Comment by ogumen** [comment]
The accessibility issue found in this PR:
1. No keyboard alternative is provided for zoom-in / zoom-out functionality - failure of WCAG SC 2.1.1

https://user-images.githubusercontent.com/88733897/144065413-42868933-65c3-4dfb-b2cf-18a784f83f24.mp4

**Comment by railway17** [comment]
> The accessibility issue found in this PR:
> 
> 1. No keyboard alternative is provided for zoom-in / zoom-out functionality - failure of WCAG SC 2.1.1
> 
>  No.keyboard.alternative.provided.to.zoom-in.functionality.mp4

Was there any keyboard functionality before I've changed before?
Because I am the first contributor and didn't report for keyboard function, I didn't consider it.

**Comment by ogumen** [comment]
> > The accessibility issue found in this PR:
> > 
> > 1. No keyboard alternative is provided for zoom-in / zoom-out functionality - failure of WCAG SC 2.1.1
> > 
> > No.keyboard.alternative.provided.to.zoom-in.functionality.mp4
> 
> Was there any keyboard functionality before I've changed before? Because I am the first contributor and didn't report for keyboard function, I didn't consider it.

@railway17 no, there was no keyboard alternative provided for zoom-in functionality before the latest changes. Tagging @roryabraham for an input on accessibility issues, but I think they are not deploy blockers for any issue.

**Comment by railway17** [comment]
> The accessibility issue found in this PR:
> 
> 1. No keyboard alternative is provided for zoom-in / zoom-out functionality - failure of WCAG SC 2.1.1
> 
>  No.keyboard.alternative.provided.to.zoom-in.functionality.mp4

Sorry, but I didn't understand your issue.
What does mean keyboard alternative?
What are the current results and the expected result?

**Comment by roryabraham** [comment]
@railway17 We're piloting an in-sprint accessibility testing program to improve the UI/UX of our app as it is consumed by users with various forms of impairments. This program is still in its infancy, and we don't need to address accessibility issues at this time. @ogumen (and their team) test PRs and post issues found to gain familiarity with our process and application, and to provide educational opportunities for us as engineers to be able to identify and fix these accessibility issues.

Thanks @ogumen! I'll create a follow-up issue to address this shortcoming. Quick question before I do: our zoom-in functionality zooms into different areas on the image depending on where you click on it (i.e cursor position). How do you recommend we implement that sort of functionality with a keyboard alternative?

**Comment by railway17** [comment]
> @railway17 We're piloting an in-sprint accessibility testing program to improve the UI/UX of our app as it is consumed by users with various forms of impairments. This program is still in its infancy, and we don't need to address accessibility issues at this time. @ogumen (and their team) test PRs and post issues found to gain familiarity with our process and application, and to provide educational opportunities for us as engineers to be able to identify and fix these accessibility issues.
> 
> Thanks @ogumen! I'll create a follow-up issue to address this shortcoming. Quick question before I do: our zoom-in functionality zooms into different areas on the image depending on where you click on it (i.e cursor position). How do you recommend we implement that sort of functionality with a keyboard alternative?

Ok, I got it.

@ogumen 
Please take a look [issue report](https://github.com/expensify/App/issues/6326) for this pull request if you like to see it.
Maybe, it will help you to notice what you have to test at this moment.

**Comment by ogumen** [comment]
> @railway17 We're piloting an in-sprint accessibility testing program to improve the UI/UX of our app as it is consumed by users with various forms of impairments. This program is still in its infancy, and we don't need to address accessibility issues at this time. @ogumen (and their team) test PRs and post issues found to gain familiarity with our process and application, and to provide educational opportunities for us as engineers to be able to identify and fix these accessibility issues.
> 
> Thanks @ogumen! I'll create a follow-up issue to address this shortcoming. Quick question before I do: our zoom-in functionality zooms into different areas on the image depending on where you click on it (i.e cursor position). How do you recommend we implement that sort of functionality with a keyboard alternative?

Thank you @roryabraham. As of now after hovering over and clicking on the image in the Attachment dialog, a portion of the image is zoomed in, and user can move over the other parts of the image using arrow keys (this is great!). My recommendation is to provide a toggle button which will zoom in / zoom out the image once activated (the same functionality as the magnifying glass icon does on click).
As a side note, the left and up edge of the enlarged image attachment are cut off (it is a functional issue, just thought it might be useful).
Screenshot (3461)
Screenshot (3460)

**Pull request merged**
