### PR TITLE
Bump react-native-live-markdown to newest version and remove/rename patches 

### PR DESCRIPTION
**Pull request by MrRefactor**
### Details

Bumping `react-native-live-markdown` to newest version in order to remove patches for `react-native` `0.75` support. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/37374
PROPOSAL:

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

 * [Red spell check line is shown frequently in composer when typing](https://github.com/Expensify/App/issues/48662) in version `0.1.133` - [PR](https://github.com/Expensify/react-native-live-markdown/pull/470)
  Test steps:
 
 1. Open any chat
 2. Start typing any sentence
 3. Verify if the red spell check line isn't shown while still typing a word
 4. Verify if the red spell check line is being added correctly
 
 * [Voice recognition doesn't work on mobile web on Android in the message compose](https://github.com/Expensify/App/issues/44394) input in version `0.1.130` - [PR](https://github.com/Expensify/react-native-live-markdown/pull/468)
   Test steps:
 
 1. Open any chat
 2. Start inserting text using voice recognition
 3. Verify the input content. Check if it wasn't doubled and if it's correct

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    -  [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Review by tomekzaw — COMMENTED** [review]
The PR looks good. Can we also remove `@expensify+react-native-live-markdown+0.1.129+001+hybrid-app.patch`? I believe this change has not been upstreamed to `react-native-live-markdown` yet.

**Comment by Skalakid** [comment]
Hi, I see that you will be bumping the `react-native-live-markdown` version to `0.1.135` after merging this [PR](https://github.com/Expensify/react-native-live-markdown/pull/476) in the library. This will be a bigger version jump and contain my fixes for 2 issues in E/App. Can we please add QA steps to this PR so my bug fixes will also be tested?

Here are the issues that I fixed and your bump will contain them:
- [Red spell check line is shown frequently in composer when typing](https://github.com/Expensify/App/issues/48662) in version `0.1.133` - [PR](https://github.com/Expensify/react-native-live-markdown/pull/470)
Test steps:
1. Open any chat
2. Start typing any sentence
3. Verify if the red spell check line isn't shown while still typing a word
4. Verify if the red spell check line is being added correctly

- [Voice recognition doesn't work on mobile web on Android in the message compose](https://github.com/Expensify/App/issues/44394) input in version `0.1.130` - [PR](https://github.com/Expensify/react-native-live-markdown/pull/468)
Test steps:
1. Open any chat
2. Start inserting text using voice recognition
3. Verify the input content. Check if it wasn't doubled and if it's correct

**Comment by MrRefactor** [comment]
@Skalakid sure thing, updated

**Comment by MrRefactor** [comment]
@shubham1206agra hey, PR is ready to be reviewed. 
cc: @Skalakid

**Comment by VickyStash** [comment]
@MrRefactor could you please update the lib to the latest version, so [these fixes](https://github.com/Expensify/App/pull/47547#issuecomment-2346003752) are included 🙏
cc @parasharrajat

**Comment by MrRefactor** [comment]
@mountiny can we go ahead with that PR?

**Review by tomekzaw — APPROVED** [review]
Thanks for bumping!

**Comment by mountiny** [comment]
@VickyStash @MrRefactor We should test the fixes from the library are working in the App on this PR, were all of them tested across platforms?

**Comment by mountiny** [comment]
Started a thread [here](https://expensify.slack.com/archives/C05LX9D6E07/p1726172674757349) to talk about this one

**Comment by MrRefactor** [comment]
@ZhenjaHorbach resolved conflicts

**Comment by tomekzaw** [comment]
@ZhenjaHorbach Thanks for reviewing

>On Android
>The height changes in 2 stages
>As a result
>For a short period of time first line is cut off

This is unfortunately an issue in React Native (all `TextInput` components suffer from this very problem). Since `MarkdownTextInput` extends `TextInput`, the behavior is propagated. The root cause of this problem is that the content of the text input is updated on the UI thread but the height of the component (and the layout of the rest of the components) needs to be calculated by Yoga and mounted separately after a commit on the JS thread. So this needs to be addressed separately.

Also, this behavior on Android has nothing to do with https://github.com/Expensify/react-native-live-markdown/pull/474 since this was an iOS-only changes.

**Comment by tomekzaw** [comment]
@ZhenjaHorbach No worries! I'm glad you found the height jump issue on Android – I wish we could address that in the future as well.

**Comment by MrRefactor** [comment]
@VickyStash could you look at that emoji behaviour?

**Comment by VickyStash** [comment]
> @VickyStash could you look at that emoji behaviour?

It's hard for me to say right away what's wrong here and I'm not sure I'll have enough time today to dig more into it. (I'll be OOO next week). Though I think the current version looks better than jumping/emojis cutting off on the main.
cc @tomekzaw

**Comment by tomekzaw** [comment]
@ZhenjaHorbach Thanks for finding the regression with emoji in https://github.com/Expensify/App/pull/48626#issuecomment-2348807054. This indeed looks like an incorrect behavior.

I'd like to suggest merging this PR as it is now (since it fixes 5+ issues) and reporting this behavior as a separate issue so it can be fixed incrementally.

**Review by ZhenjaHorbach — APPROVED** [review]

**Review by roryabraham — APPROVED** [review]

**Comment by mountiny** [comment]
Thanks for thorough testing @ZhenjaHorbach

**Pull request merged**
