### PR TITLE
fix: Search Page Order

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/6627
$ https://github.com/Expensify/App/issues/5699

### Tests | QA Steps
1. Open Search Page.
2. Search for some user name that does not start with #.
3. Search results should be in the following order:
1. 1: 1 chat.
2. group Chat.
3. Room.

4. Order will change based on the resemblance between search value and search result. e.g. If the search value matches the room name, the room name would be above. etc.
---

  1. In an account that has at least 1 workspace
  2. Open search
  3. Search for #announce room
  4. Delete a character and write it again
  5. room name should not duplicate

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

https://user-images.githubusercontent.com/24370807/148835203-1b98d6a0-704c-493a-b0fb-72e8e83cf149.mp4

#### Mobile Web

image

#### Android

image

### CODE REVIEW

**Comment by roryabraham** [comment]
Sorry for the delay here. Reviewing now...

**Review by roryabraham — COMMENTED** [review]
Looks good – my only suggestion is that we should order rooms so that any `(deleted)` rooms appear _after_ open rooms.

**Comment by roryabraham** [comment]
We can do that pretty easily by replacing [this line](https://github.com/Expensify/App/pull/6971/files#diff-733528d957ae6a80eb863637fa5d54278c89c6121998f3574fa8c0aba935daebR388) with:

```javascript
let orderedReports = lodashOrderBy(reports, sortProperty, sortDirection);
orderedReports = _.sortBy(orderedReports, report => ReportUtils.isArchivedRoom(report));
```

**Comment by parasharrajat** [comment]
Thanks for the suggestion. Let's do this as well. But I can't see which lines you are referring to. Maybe tell me the line number.
I tried replacing the https://github.com/Expensify/App/blob/b5d2e8b10f9fa10e9fdd3cfb95b5580220c0c5d5/src/libs/OptionsListUtils.js#L386 with your code snippet but that does work. I will check the code.

**Comment by parasharrajat** [comment]
@roryabraham  Updated.

**Review by roryabraham — APPROVED** [review]

**Comment by kavimuru** [comment]
@parasharrajat Issue #5699 is still reproduced. This PR is failing.

 Screen Shot 2022-01-15 at 2 52 03 PM

**Comment by parasharrajat** [comment]
@kavimuru Could you please follow these steps for me and let me the results?
1. Open first announce room. 
2. Save the id from URL and send one message to it. 
3. Go back to some other chat but not any of these rooms. 
4. Search for # announce and then open the second one. 
4. Note the id and tell me if you see the same message again.

**Comment by parasharrajat** [comment]
@mvtglobally Any luck above?

**Comment by kavimuru** [comment]
@parasharrajat  Sorry for the delay. Issue #5699 is not reproduced anymore. I followed these steps and not seeing the same message.

1. Open first announce room.
2. Save the id from URL and send one message to it.
3. Go back to some other chat but not any of these rooms.
4. Search for # announce and then open the second one.
5. Note the id and tell me if you see the same message again.

https://user-images.githubusercontent.com/43996225/150138901-45bb239b-87e0-474d-a2b9-7753c5f5e2fa.mp4

**Comment by parasharrajat** [comment]
Thanks for looking into this @kavimuru. Based on these, I can say that these are two rooms with the same name. I saw the same results but as the message is not visible on other room it means that they are different.

**Comment by jasperhuangg** [comment]
Hey! I know this is from a while back, but it looks like this PR is somewhat related to [this bug](https://github.com/Expensify/App/issues/12900). In addition to updating the indexOffset for that new section that you added, we also need to update the indexOffset for the `usersToInvite` section. The PR with that fix is [here](https://github.com/Expensify/App/pull/12906).

**Pull request merged**
