### PR TITLE
Add tap to focus and fix orientation

### PR DESCRIPTION
**Pull request by janicduplessis**
### Details

This adds tap to focus on iOS and Android for the scan receipt camera. It also adds a focus indicator to have some feedback of the focus, I made it similar to the IG camera.

Note that this only affects native iOS and Android. As far as I know browser apis have no way to control camera focus.

### Fixed Issues

$ https://github.com/Expensify/App/issues/34898
PROPOSAL: N/A

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Log in to an account
2. In the + menu tap Request money
3. You can now tap on the camera preview to focus different areas

___

Orientation fix:
1. on iOS, rotate the phone to landscape
2. Verify the UI does not rotate
3. Verify the camera also does not rotate
4. Take a picture
5. verify the picture is taken in portrait mode

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/2677334/e2e6ced7-b4bd-4343-8432-8bd5b25ee3f8

</details>

<details>
<summary>Android: mWeb Chrome</summary>

N/A

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/2677334/33d31603-7671-462d-aa5e-a599b505f399

</details>

<details>
<summary>iOS: mWeb Safari</summary>

N/A

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

N/A

</details>

<details>
<summary>MacOS: Desktop</summary>

N/A

</details>

### CODE REVIEW

**Comment by janicduplessis** [comment]
Hey @ishpaul777! Not sure if there is an easier way, but what I did is use my own developer account to sign the app and run it on device. You can do it with the following changes:

- Open the app in xcode
- Go to Signing and Capabilities then in the section called Signing (DebugDevelopment and ReleaseDevelopment)

image

- Check enable automatically singing
- Pick your personal team
- Change the bundle identifier to something unique like `com.yourname.expensify.chat.dev` 

image

- Go to the NotificationService target and repeat the last 3 steps

image

- Go back to NewExpensify target and scroll down
- Remove Associated Domains, Communication Notifications, Push Notifications and Sign In With Apple capabilities

Then it should build, you might need to authorize your dev account on your phone, it should tell you how to when you run the  app the first time.

**Comment by janicduplessis** [comment]
I added the steps in the PR description, lmk if it is clear.

**Comment by mountiny** [comment]
@ishpaul777 added test steps for the orientation fix

**Comment by mountiny** [comment]
@ishpaul777 this is the issue in main currently:

https://github.com/Expensify/App/assets/36083550/56fc8cda-04ca-4f9a-8479-585cdf032d1d


The problem seems to be not really a landscape/ portrait but if the phone is laying flat or standing, then the angle changes 🤔 

Honestly in your video it seems fine, can you also test laying the phone flat and then straighten it up?

**Comment by mountiny** [comment]
Even the picture was taken correctly I think

**Comment by mountiny** [comment]
Yeah sorry it's hard to explain so I included the video :D

**Comment by mountiny** [comment]
Thanks! Sounds like we can do the checklist now, thanks for a quick turn around

**Comment by janicduplessis** [comment]
@mountiny I completely forgot about the orientation fix, thanks!

**Comment by janicduplessis** [comment]
I will look into the warning

**Comment by mountiny** [comment]
Any updates on the warning?

**Comment by janicduplessis** [comment]
I checked with Marc, the author of vision camera and seems to also think the warning is harmless and can just be ignored. I will verify that later today and add code to just ignore it.

**Comment by mountiny** [comment]
@ishpaul777 can you please finish the review now? The reassure tests are known, unrelated

**Review by ishpaul777 — APPROVED** [review]
Looks good :shipit:

**Review by mountiny — APPROVED** [review]
Really nice, thank you!!!

**Comment by mountiny** [comment]
Knwown reassure failure that is resolved on main

**Comment by mountiny** [comment]
@janicduplessis this seems not to be working for me on iOS, should be in prod already, can you test?


https://github.com/Expensify/App/assets/36083550/83f82c41-ab46-4dcc-85c2-61bae517307c

**Comment by mountiny** [comment]
> New iphones usually have one that is better at very close pictures so maybe we could allow it to be used.

Interesting. We need to do something about this for sure as its been couple of people who tried and did not find it working.

How can we achieve it to behave "same" as the built-in camera focus?

**Comment by mrousavy** [comment]
I believe we could use the [`setPrimaryConstituentDeviceSwitchingBehavior(_:restrictedSwitchingBehaviorConditions:)`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/3875310-setprimaryconstituentdeviceswitc) API from AVFoundation to have it automatically zoom out to the ultra-wide-angle-camera (aka "macro-lens") when something is too close to focus on?

**Comment by mrousavy** [comment]
This is not part of VisionCamera V3 or V2 yet. @janicduplessis wanna just try adding that to the `AVCaptureDevice` setup code and see if that does anything?

Effectively under the hood this should only switch to the ultra-wide-angle-camera when something is too close to focus on, while still staying at the same zoom factor.

Without this API, we can only zoom out to switch to the ultra-wide, technically not achieving the same behaviour

**Comment by mrousavy** [comment]
I heard about this in [this Apple Developer Forums post](https://forums.developer.apple.com/forums/thread/709243), and I think the way the iOS stock Camera achieves it is by 

1. zooming "out" to the ultra-wide camera (in VisionCamera terms; `zoom={device.minZoom}`)
2. locking the device to stay at the ultra-wide camera and prevent it from switching over to the other cameras ([`setPrimaryConstituentDeviceSwitchingBehavior(.locked, ...)`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/3875310-setprimaryconstituentdeviceswitc))
3. setting the zoom back to it's value what it was before step 1

I am not sure how that'll work on the implementation though as we need to await until the Camera switches over to the ultra-wide before we lock the switching behaviour. 

As an alternative, we can just always use the ultra-wide angle which has a closer `minFocusDistance`, but that probably looks weird to users, no?

**Comment by janicduplessis** [comment]
@mrousavy The api you are suggesting would make it so it only changes to ultra-wide if the thing is too close to focus, instead of switching automatically like when using `dual-wide-camera`?

**Comment by mrousavy** [comment]
Yea kinda, I think this is how the "Macro Mode" in the stock iOS camera works (the little flower icon at the bottom left if you are close to a subject).

If we use the `dual-wide-camera` then the user can manually zoom out to achieve the same behaviour. If that's fine, that would take 5 seconds to implement, whereas the other API could take a few hours.

**Comment by janicduplessis** [comment]
When I tested last time using tap to focus or getting really close would cause it to change automatically from what I remember.

**Comment by janicduplessis** [comment]
I think this might be a good solution for now, and we can look at more complex solutions if we still have issues.

**Comment by mountiny** [comment]
Interesting, I would say we need to optimize for receipt scanning in this case so that is usually taking picture from close distance so if its hard to make the focus work for all proximities of the object from camera, we should ideally do the macro case first

**Comment by janicduplessis** [comment]
I can try allowing both extra-wide and wide cameras and we can test if that works well. If we are not satisfied we can explore more advanced apis @mrousavy mentionned.

**Comment by mrousavy** [comment]
> When I tested last time using tap to focus or getting really close would cause it to change automatically from what I remember.

Oh well then that's even better! AVFoundation positively surprising, as always

**Pull request merged**
