### PR TITLE
[CP Staging] Fix document upload on Android

### PR DESCRIPTION
**Pull request by kidroca**
@mountiny 

### Details

Add `file://` scheme prefix to attachment files (when it's missing)
Related to: https://github.com/Expensify/App/pull/4908#issuecomment-1013968846

RN Document picker does not add a URI scheme for the file uri on Android. This seems to work ok for showing the document in previews, but instantly fails File upload when `file://` is missing

Checked on iOS and there we do have a `file://` prefix
So the logic that adds the prefix is conditional
Maybe we should try to address this on RN document picker's repo - this PR would remove the deploy blocker in the meantime

### Fixed Issues

$ https://github.com/Expensify/App/issues/7267

### Tests

- [ ] Verify that no errors appear in the JS console
- [ ] Add a Document attachment in Android (verify it gets uploaded)
- [ ] Add a Document attachment in iOS (verify it gets uploaded)
- [ ] Add a Document attachment on other platforms (verify it gets uploaded)

### QA Steps

Same as above

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/12156624/149757142-b7beb8de-c4dc-46bb-b3e3-65a072cdfc3d.mp4

#### Mobile Web

https://user-images.githubusercontent.com/12156624/149758955-0ddcf6ff-d9f0-46c0-8c2d-c7661667adec.mov

#### Desktop

https://user-images.githubusercontent.com/12156624/149758544-e45cee5b-2582-4987-bde3-b2823ceef7cf.mov

#### iOS

https://user-images.githubusercontent.com/12156624/149754955-b9012998-e7b1-4ce8-be58-f9e0c327c04d.mov

#### Android

https://user-images.githubusercontent.com/12156624/149754871-620c812c-38ca-4307-8d4b-9883c1f70935.mp4

### CODE REVIEW

**Review by mountiny — APPROVED** [review]
Great! Thank you for fixing this deploy blocker. I agree this would be better to fix in the RN Attachment picker.

**Comment by kidroca** [comment]
> Great! Thank you for fixing this deploy blocker. I agree this would be better to fix in the RN Attachment picker.

I've opened an issue here: https://github.com/rnmods/react-native-document-picker/issues/526
I guess it would be OK if we can open a PR about it

**Comment by mountiny** [comment]
Thank you for following up with the issue. It would be great if the fix could be implemented in the package itself. Would you be able to also create the PR? Do you need me to create a separate issue in our repo so you could be paid for it or can you just add time spent on that to this issue?

**Comment by kidroca** [comment]
> Thank you for following up with the issue. It would be great if the fix could be implemented in the package itself. Would you be able to also create the PR? Do you need me to create a separate issue in our repo so you could be paid for it or can you just add time spent on that to this issue?

You're welcome 

I've identified the cause https://github.com/rnmods/react-native-document-picker/issues/526#issuecomment-1014777947 and I can submit a PR 
I can time track it and log it under https://github.com/Expensify/App/issues/7267 
Can you add me there (but remove the deploy blocker label)?

**Comment by mountiny** [comment]
Done @kidroca! Thank you!

**Pull request merged**
