### PR TITLE
Add inline images preview to the Live Markdown Input on the web

### PR DESCRIPTION
**Pull request by Skalakid**
### Details

This PR bumps the version of the `react-native-live-markdown` to the latest and enables the inline image previews inside the input on the web

Screenshot 2024-09-16 at 11 56 32

### Fixed Issues

$ https://github.com/Expensify/App/issues/40181#issue-2240640829
$ https://github.com/Expensify/App/issues/48797

PROPOSAL:

#### Inline image preview

1. Open any chat room / page with Live Markdown input
2. Enter inline image markdown. For example:
```
*test* ![demo image](https://picsum.photos/id/1067/200/300)_test_ 
```
3. Verify the behavior of the input with image preview inside
4. Verify the loading indicator styling and layout before the image loads
5. Verify the size and aspect ratio of the image preview
6. Verify other cases where image can break the input

#### https://github.com/Expensify/App/issues/48797
 
1. Initiate a DM with any user
2. Compose a message
3. Place the cursor in the middle of the composed message
4. Press the Delete button on the keyboard

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as Tests
### QA Steps

Same as Tests
- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

web only feature
</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/24182271-ea8e-40b4-ab58-f2eab5975555

</details>

<details>
<summary>iOS: Native</summary>

web only feature
</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/30bddba0-127f-4ae5-82e3-bc5e22dca8fb

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/3983f59a-9186-4da7-875b-30eb7c765253

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/97dd34cb-239e-4ce8-9265-2e94df02fd67

</details>

### CODE REVIEW

**Comment by hungvu193** [comment]
Taking a look 👀

**Comment by hungvu193** [comment]
@Skalakid  I still can reproduce the mentioned box issue on mWeb

https://github.com/user-attachments/assets/49c8c33f-0c71-4a55-8ea3-2890fcf0db06

**Comment by hungvu193** [comment]
I still can reproduce this issue:
https://github.com/Expensify/App/issues/49973


https://github.com/user-attachments/assets/cb182fff-d18b-4cda-a541-eae52841e760

<br />


Also if we send an image with a text, we can edit it and a broken image preview will be shown. Do you think we should fix it here as well?


https://github.com/user-attachments/assets/cd7b67fb-b1cf-48e9-8708-1b7e11212c82

**Comment by Skalakid** [comment]
@hungvu193, can you please check if you pulled the latest changes on my branch and delete `node_modules` before npm i, please? If it doesn't help please give me test steps how to reproduce the first issue

**Comment by Skalakid** [comment]
@hungvu193 The second issue you reported is more complex since the image preview isn't displayed because the auth token is missing. It's pretty problematic, and we should think about how to solve this problem safely without exposing any token

**Comment by hungvu193** [comment]
> @hungvu193, can you please check if you pulled the latest changes on my branch and delete `node_modules` before `npm i`, please? If it doesn't help please give me test steps how to reproduce the first issue

I think that's caches issue, I removed the `node_modules` and run `npm ci` and this issue's gone 🤦

**Comment by hungvu193** [comment]
All good!

@thienlnam Can you add build label and ask QA to verify this PR?

**Comment by Skalakid** [comment]
@hungvu193 I just fixed the issue with image previews that require auth token

**Comment by hungvu193** [comment]
Please ignore this PR @ishpaul777

**Comment by hungvu193** [comment]
@Skalakid I think the recent changes from selection logic breaks shortcut key, now when I press command + A to select all, the cursor will move to the first character of the line:

https://github.com/user-attachments/assets/498a78a9-e1a3-4a7d-9460-8cfe7be7160c

**Comment by hungvu193** [comment]
another way to reproduce it, type a letter and double click to select it, you can notice that you can select that letter.

**Comment by Skalakid** [comment]
@hungvu193 fixed!

**Comment by hungvu193** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



https://github.com/user-attachments/assets/f83e816d-ea56-43dd-b238-0cd8563ef085

https://github.com/user-attachments/assets/95b6eea0-82cc-42e9-8029-bf7012956a0b





</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/1b083534-67d8-4204-b457-1f996649fe8c


https://github.com/user-attachments/assets/63987777-9e69-493a-9c05-9ede0370403b



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/1fd04c3d-c64a-4d50-be0f-e0d48b990e67


</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/31933cef-4a93-4d03-ae1b-1ed6ac6d0fa1



</details>

**Review by hungvu193 — APPROVED** [review]

**Comment by hungvu193** [comment]
Please add build label and ask QA team to verify it. Ty 🙇

**Review by rafecolton — COMMENTED** [review]
Confirmed forward delete works as expected in this branch. Somehow it's even worse in main - it now jumps the cursor to the end of the line 🙈

So if we can't get this merged soon or it gets reverted again, please let's do a small PR to just fix forward delete so we don't delay that further 🙏

**Comment by thienlnam** [comment]
Okay thanks, will request one more QA review so we can try to get ahead of any blockers

**Comment by thienlnam** [comment]
Timing works out great since I'm also the deployer this week 😄

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Task –Task description content with exceeded character limit flashes if tap on fix the errors


**Version Number:** 9.0.44-8
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Tap on +/ Assign task
5. Enter task title
6. Enter description longer than 1000 characters and tap Next
7. When focus is gone tap on fix the errors link

## Expected Result:
Task description content not flashes

## Actual Result:
Task description content flashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/e5ee7077-09d4-44bc-a30a-2d7e47ea28cc



</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Task - & is displayed as &amp; in task conversation created


**Version Number:** 9.0.44-8
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Go to https://50047.pr-testing.expensify.com/home
2. Open self DM
3. Enter [] @[jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
&
4. Send the message

## Expected Result:
& must not be displayed as &amp; in task conversation created

## Actual Result:
& is displayed as &amp; in task conversation created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/8f66000c-4857-4653-889e-5a6973a44712



</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by IuliiaHerets** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Chat - Infinite loading when trying to reproduce video after sending it to chat


**Version Number:** 9.0.44-8
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Open the staging.new.expensify.com website.
2. Open any chat.
3. Click on the "+" button.
4. Click on "Add Attachment"
5. Select a video to upload to chat.
6. Click on "Send"
7. Once the video is sent to chat, wait a few seconds and click on it to reproduce it.
8. Verify the video is reproduced smoothly.

## Expected Result:
After sending a video to chat, the user should be able to reproduce it by clicking on play on the preview.

## Actual Result:
After uploading a video to chat, waiting a few seconds and clicking on play to reproduce it, the video loads infinitely.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b136e3ce-d18d-4199-9164-a15de1bb3283

</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by Skalakid** [comment]
@hungvu193 @thienlnam [Task - & is displayed as & in task conversation created](https://github.com/Expensify/App/pull/50047#issuecomment-2397912302) and [Chat - Infinite loading when trying to reproduce video after sending it to chat](https://github.com/Expensify/App/pull/50047#issuecomment-2399085863) issues can also be reproduced on the latest main. The [Task –Task description content with exceeded character limit flashes if tap on fix the errors](https://github.com/Expensify/App/pull/50047#issuecomment-2397912302) issue is connected to https://github.com/Expensify/App/issues/45885#issuecomment-2397583811 since the input is scrolling element into view after clicking the "Fix" button. It's a pretty small bug, and we can handle it in the separate Live Markdown library bump

**Comment by hungvu193** [comment]
Agree with you 💯

**Comment by thienlnam** [comment]
Yup I agree, I think QA is still running through regression testing though so let's see if anything else comes up that is worth fixing

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Image preview reloads when deleting line and returning to the previous line with image preview


**Version Number:** 9.0.44-8
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Go to https://50047.pr-testing.expensify.com/
2. Go to DM
3. Type anything in the composer
4. Attach an image and send it
5. Right click on the message > Edit comment
6. Press SHIFT+Enter to create a new line after the link
7. Delete the link to return to previous line

## Expected Result:
The image preview will not reload when deleting the line and returning to the previous line with image preview

## Actual Result:
The image preview reloads when deleting the line and returning to the previous line with image preview

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3476f204-b5ec-45fa-b07a-8c2cda392b79

</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by Skalakid** [comment]
Thank you for reporting t[he Image preview reloads when deleting the line and returning to the previous line with the image preview issue](https://github.com/Expensify/App/pull/50047#issuecomment-2402624592). [Here](https://github.com/Expensify/react-native-live-markdown/pull/516), I created the fix for it. However, I think it's a pretty low-priority bug, and we can add this fix to the E/App in a separate PR with a library bump

**Comment by thienlnam** [comment]
Given that nothing major has come up, going to ship this today - and hopefully if anything comes up on the weekend that proves to be a blocker we can address it

**Review by thienlnam — APPROVED** [review]

**Pull request merged**
