### PR TITLE
Aligned header

### PR DESCRIPTION
**Pull request by mateusbra**
### Details

Style fix for settings subpages miss-aligned headers on IOS and Android
### Fixed Issues

$ [#7491](https://github.com/Expensify/App/issues/7491)

### Tests | QA Steps

1. Login in New Dot
2. Go to Settings
3. Check header title is vertically centered on all pages where there is a header. E.g. Settings pages. 
4. Note: that it should not affect the header where the subtitle is also visible. e.g. Attachment modal.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

Chrome:
image
Safari:
Captura de Tela 2022-02-01 às 18 39 43

#### Mobile Web
Android chrome mWeb:

image
IOS safari mWeb:
Captura de Tela 2022-02-01 às 19 11 07

#### Desktop

Captura de Tela 2022-02-01 às 18 22 38

#### iOS

Captura de Tela 2022-02-01 às 14 19 58
#### Android

image

### CODE REVIEW

**Review by mountiny — COMMENTED** [review]
@mateusbra Could you please also add a screenshot for Safari iOS in the mobile Web category? Not a big deal but the styles sometimes get screwed for mobile safari.

**Comment by mateusbra** [comment]
@mountiny sure!

**Comment by mateusbra** [comment]
@mountiny PR updated with Safari IOS on Web Screenshots

**Review by parasharrajat — APPROVED** [review]
LGTM.

Please change the test steps: 
 ~3. Observe that all the subpages are aligned~ 
 
 3. Check header title is vertically centered on all pages where there is a header. E.g. Settings pages. 
 4. Note: that it should not affect the header where the subtitle is also visible. e.g. Attachment modal.
 
 cc: @mountiny 
:ribbon: :eyes: :ribbon:  C+ reviewed

**Review by mountiny — APPROVED** [review]

**Comment by mountiny** [comment]
@mateusbra Thank you for working on this! 🙇 and @parasharrajat for a review!

**Comment by mountiny** [comment]
@mateusbra For future PRs, please, make sure the linked issue is written using the following format:
```
$ https://github.com/Expensify/App/issues/7491
```

What you have there now is:
```
$ [#7491](https://github.com/Expensify/App/issues/7491)
```

We have automation in place, which requires this format to work properly (for example the issue has not been updated with a date when we should pay you). Thank you for keeping your eye on this in future!

**Comment by mateusbra** [comment]
@mountiny sure! Sorry for that. I'll ensure future PR's will follow the correct format 😅

**Comment by mountiny** [comment]
No problem at all! 🙇

**Pull request merged**
