### PR TITLE
desktop title bar customization

### LINKED ISSUE #1503: Update desktop app title bar style
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___
Upwork posting: https://www.upwork.com/jobs/~0156d292c1f9d2ed43

**Platform - version:**  
Mac Desktop app 

**Current:**
Right now this is what the title bar looks like on the mac electron app. 
image

**New:**
This is what we want it to look like: 

image

**Notes/Photos/Videos:** 
Notice that the button color is only shown when hovered. 

Not Hovered | Hovered
----- | -----
image | image

### PR DESCRIPTION
**Pull request by ilijaprzeski**
### Reviewer
@puneetlath 

### Details
Mac Desktop App titlebar custom

### Fixed Issues
Fixes [Update desktop app title bar style #1503](https://github.com/Expensify/Expensify.cash/issues/1503)

### CODE REVIEW

**Comment by shawnborton** [comment]
For padding from the top (to provide space for the buttons), could we try 12px? Let us know how that looks and we can go from there.

**Comment by ilijaprzeski** [comment]
Just I added 12px padding on the top of desktop app, but desktop environment is not working now, so this will not be applied.
If desktop env works, that will be applied.

**Comment by shawnborton** [comment]
Are you able to share any screenshots of your progress, or do you mean that you are unable to get the desktop app to work locally?

**Comment by ilijaprzeski** [comment]
Home
Modal
Signin

**Comment by shawnborton** [comment]
It doesn't look like the extra padding is being applied in those screenshots.

**Comment by ilijaprzeski** [comment]
As you can see in first 2 images, windows control buttons are too clear to header of home screen. That's why src/components/HeaderGap/index.desktop.js is not applied to the app in desktop environment.

**Comment by ilijaprzeski** [comment]
This is normal screen when everything works well.
Home

**Comment by shawnborton** [comment]
Could we also see what it looks like if a modal is launched? So for example, can you click on your profile picture for one test, and for another test can you open an image attachment on a chat message?

**Comment by ilijaprzeski** [comment]
Modal window
Screen Shot 2021-02-22 at 6 07 49 PM

**Comment by shawnborton** [comment]
Great, could I also see an image attachment?

**Comment by ilijaprzeski** [comment]
Screen Shot 2021-02-22 at 6 40 46 PM

**Comment by shawnborton** [comment]
So it sounds like you are just blocked on the [issue you made here](https://github.com/Expensify/Expensify.cash/issues/1537), correct?

**Comment by ilijaprzeski** [comment]
No, that is correct screenshot. Have any problem in the screen?

**Comment by shawnborton** [comment]
The screenshots look good to me, but I wasn't sure if the other issue you created was a bug you encountered while trying to implement this solution.

**Comment by ilijaprzeski** [comment]
No, it can't be.
So, I confirmed it on original version.

**Comment by shawnborton** [comment]
Cc @roryabraham and @AndrewGable in case you have more thoughts on this.

**Comment by marcaaron** [comment]
x-posting workaround here for visibility @ilijaprzeski https://github.com/Expensify/Expensify.cash/issues/1537#issuecomment-783575142

**Comment by ilijaprzeski** [comment]
Just I updated this PR. Please check it.

**Comment by roryabraham** [comment]
Please hold for a few minutes, I think I know how to fix the platform issue.

**Comment by roryabraham** [comment]
Right [here](https://github.com/Expensify/Expensify.cash/blob/b9d7a0dd31ccae8bd90e0443858414801da3d623/config/webpack/webpack.common.js#L125) is our webpack configration line which tells webpack which file extension to consider the module's index, and according to [this SO](https://stackoverflow.com/questions/41810258/multiple-webpack-builds-based-on-file-extension) it looks like it searches for an `index` file with the extensions matching the ones provided in this array _in the order in which they appear in the array_.

So can we first try to fix this by just changing this:

```
extensions: ['.web.js', '.js', '.jsx', (platform === 'web') ? '.website.js' : '.desktop.js'],
```

To this:

```
extensions: ['.web.js', (platform === 'web') ? '.website.js' : '.desktop.js', '.js', '.jsx'],
```

I think that will make webpack look for `index.desktop.js` or `index.website.js` before looking for `index.js`.

**Comment by ilijaprzeski** [comment]
Ok, thanks for your suggestion. so what should I do? Should I restore PR to before one?

**Comment by ilijaprzeski** [comment]
Just I also confirmed that worked well.

**Comment by roryabraham** [comment]
Yeah, I would just revert your last commit and make the 1-line change in the webpack configuration.

**Comment by ilijaprzeski** [comment]
Ok, thanks

**Comment by ilijaprzeski** [comment]
So, what should I do?

**Comment by ilijaprzeski** [comment]
Hello, @roryabraham 
So I no need to update this PR?

**Comment by roryabraham** [comment]
Webpack changes look good, but I'm not a primary reviewer of this PR so I'll let somewhen else take it from here.

**Comment by ilijaprzeski** [comment]
Updated

**Comment by AndrewGable** [comment]
recheck

**Review by timszot — APPROVED** [review]
LGTM

**Comment by botify** [comment]
@timszot looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Comment by timszot** [comment]
Merged with skipped check per: https://github.com/Expensify/Expensify.cash/pull/1533#issuecomment-783732879

**Pull request merged**
