### PR TITLE
Fix: navigate to LHN after onboarding

### PR DESCRIPTION
**Pull request by mkzie2**
### Explanation of Change

Fix: navigate to LHN after onboarding
### Fixed Issues

$ https://github.com/Expensify/App/issues/52420
PROPOSAL: https://github.com/Expensify/App/issues/52420#issuecomment-2479636755

### Tests

1. Resize window to small screen width if we're in Web/Desktop
2. Sign in with a new account
3. Complete the onboarding flow
4. Verify that we always navigate to LHN after completing the onboarding
- [x] Verify that no errors appear in the JS console

### Offline tests

Same
### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."
1. Resize window to small screen width if we're in Web/Desktop
2. Sign in with a new account
3. Complete the onboarding flow
4. Verify that we always navigate to LHN after completing the onboarding
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/e537a1a2-b600-45ea-a2f5-46c900b4a0b9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/910fc3d9-424c-4a22-9af8-8c56ad7c5b82

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/b760c44f-5f4b-42e7-bdf3-446d9e11763a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/658ca520-9acb-48e8-9903-7b1bf67a84bf

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/97814486-0e8d-4886-a52d-e68f41ae0c37

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/93e93217-b83a-49ed-8b60-249b681a89d7

</details>

### CODE REVIEW

**Comment by mollfpr** [comment]
@mkzie2 The app still navigates to the concierge chat on the web or desktop. The step to reproduce:
1. Open the app full size
2. Create a new account
3. When the onboarding flow shows up, resize to phone size
4. Complete the onboarding

https://github.com/user-attachments/assets/662bf515-5741-404a-aa7c-8968d2ee6a27


https://github.com/user-attachments/assets/a8ec503c-f644-409f-b4ee-5d108700ee62




It didn't happened if we already resized the screen before creating a new account like in your video.





https://github.com/user-attachments/assets/e667b5d7-e4d1-4f85-b400-21d736b9711d

**Comment by mkzie2** [comment]
@mollfpr I don't think this is a bug because when we resize the window, the screen behind the onboarding is the concierge chat.

https://github.com/user-attachments/assets/fb40db77-d494-48a2-86ee-af7bfa39ede7

**Comment by mollfpr** [comment]
@mkzie2 Yeah, it doesn't look like a bug but it doesn't look consistent. @MitchExpensify Do you considered [this](https://github.com/Expensify/App/pull/53239#issuecomment-2520683876) an issue?

**Comment by MitchExpensify** [comment]
I don't think users resizing is an issue because its an edge case but we do want everyone to land in LHN instead of Concierge if they don't resize

**Comment by mkzie2** [comment]
@mollfpr We're good now.

**Review by mollfpr — APPROVED** [review]
LGTM 👍

**Review by MariaHCD — APPROVED** [review]

**Comment by MariaHCD** [comment]
@mkzie2 @mollfpr we have two workflows failing on main after this PR was merged, could you please take a look?

- https://github.com/Expensify/App/issues/54193
- https://github.com/Expensify/App/issues/54194

**Comment by mollfpr** [comment]
@MariaHCD Looking 👀

**Comment by MariaHCD** [comment]
Thanks! If we're not able to fix it within the next hour or so, we can revert this PR and start a new one. I don't want to block the App deploy 🤔

**Comment by mollfpr** [comment]
@MariaHCD I think it's safe to revert the PR since we need to add back the `route` both failing because of it.

**Comment by MariaHCD** [comment]
Okay, thanks. Will spin up the revert PR.

**Comment by MariaHCD** [comment]
Revert PR: https://github.com/Expensify/App/pull/54198

**Comment by kavimuru** [comment]
Still failing with original bug https://github.com/Expensify/App/issues/52420 in web 

https://platform.applause.com/services/links/v1/external/c520cc4f3f23148426c4f40355298c897a7fefc1587de026d5e0ff71db21d7be

**Comment by MariaHCD** [comment]
> Still failing with original bug https://github.com/Expensify/App/issues/52420 in web

The fix was reverted.

And is being worked on in a new PR here: https://github.com/Expensify/App/pull/54200

So the bug will still persist for now until the new PR is merged and deployed.

**Pull request merged**
