### PR TITLE
[E.cash] - Updated Lodash Dependency to Fix Vulnerability

### PR DESCRIPTION
**Pull request by Luke9389**
This PR is on [HOLD] pending the deployment of [this PR](https://github.com/Expensify/react-native-onyx/pull/53).

cc @tgolen 

### Details
<Explanation of the change or anything fishy that is going on>

Rather than using individual packages for each lodash method, we are using the main lodash package and selectively loading the methods we need (using this handy syntax: `lodash/orderby`)

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com/Expensify/Expensify/issues/157894

### Tests

Our testing method for this is admittedly a bit primitive; comb the site looking for errors/broken stuff.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by Luke9389** [comment]
Testing on all platforms now. So far web & mobile web are clear

**Comment by Luke9389** [comment]
All 5 platforms seem stable. I tried to hit all the pages that were using lodash.

**Comment by tgolen** [comment]
Let's maybe hold this so that you can include the onyx upgrade in it too?

**Comment by roryabraham** [comment]
Looks like this change made in Onyx:

image

Is [already available](https://github.com/Expensify/Expensify.cash/blob/master/package.json#L72) in Expensify.cash. I'm going hold [this other PR](https://github.com/Expensify/Expensify.cash/pull/2020) on this one.

**Comment by Luke9389** [comment]
Yea, I updated Onyx on monday before I was OOO today. Retesting this now

**Comment by Luke9389** [comment]
Retested on all 5 and it's lookin good. We need to be clever about when this gets merged. It'd be bad if another PR using the wrong lodash package got merged right before this one. For this reason, I think it's best to reassign the reviewer role to someone in my time-zone, so we can be sure to merge this at the right moment. @tgolen or @roryabraham Would either of you be willing to swap in for @Gonals and become the reviewer of this PR?

**Review by tgolen — APPROVED** [review]

**Comment by tgolen** [comment]
Yeah, I don't mind reviewing and merging this. It looks fine!

**Pull request merged**
