### PR TITLE
Update MentionUserRenderer.js for issue 26016

### PR DESCRIPTION
**Pull request by nikhildewoolkar**
Fixed Issues
https://github.com/Expensify/App/issues/26016
https://github.com/Expensify/App/issues/26016

Tests
Open the app
Open any report
Write '@' to trigger mentions
Select any one mention, make any letter of mention as capital and send
Hover on mention to observe that tooltip doesn't display the right display name and avatar
For same mention as step 4 or select different mention and capitalize all letters and send
Observe that now it is not displayed as mention

IMG-20231212-WA0003

### CODE REVIEW

**Comment by nikhildewoolkar** [comment]
kindly review the PR

**Comment by nikhildewoolkar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sobitneupane** [comment]
@nikhildewoolkar You need to fill up the PR Author Checklist. You were supposed to fill up the template that was generated while creating PR. We won't be able to merge PR without this test passing.

Screenshot 2023-12-14 at 08 07 48

**Comment by sobitneupane** [comment]
@nikhildewoolkar Bump on [this](https://github.com/Expensify/App/pull/32933#issuecomment-1855007723). Let's wrap this PR asap.

**Comment by nikhildewoolkar** [comment]
https://github.com/Expensify/App/pull/33539
@sobitneupane  @rushatgabhane 
Kindly review PR.
Screenshots added below in comments section of PR. Screenshots not applicable for mobile application

**Pull request closed without merging**
