### PR TITLE
fix: Remaining pages for workspace

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

Follow up https://github.com/Expensify/App/pull/6543
### Fixed Issues

$ https://github.com/Expensify/App/issues/6496

### Tests | QA Steps
Same as preceding PR.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Android

https://user-images.githubusercontent.com/24370807/144223270-4ff0800a-0ab4-42d5-8e2a-aefa181a7534.mp4

### CODE REVIEW

**Comment by parasharrajat** [comment]
@Gonals Please review...

**Review by thienlnam — APPROVED** [review]

**Comment by parasharrajat** [comment]
@thienlnam I don't know why E2E test failed but we should be good to merge here.

**Comment by thienlnam** [comment]
Hmm, are E2E tests failing on other PRs? If not then I don't think we should merge this.  Going to re-run the test to see if it was just a flakey test

**Comment by parasharrajat** [comment]
We are good.. @thienlnam

**Comment by mvtglobally** [comment]
@parasharrajat Do we need to do any additional QA for this PR on top of QA for  #6543?
if yes, can you share steps?

**Comment by marcaaron** [comment]
I think this PR is possible breaking the VBA flow -> https://github.com/Expensify/App/issues/6620

Did a `git bisect` and it led me here.

**Pull request merged**
