### PR TITLE
[No QA] Cleanup Authentication error handling

### PR DESCRIPTION
**Pull request by marcaaron**
### Details

More cleanup for the Network code. The code should work the same as before and no new behavior is being added.

**Summary of Changes**

- Move the error handling in `Authenticate()` to a util so we don't have to throw an `Error` inside `API.Authenticate()`
- When we run out of retries in the main queue we are resolving the promise with a special client side jsonCode which can be handled in the `.then()` of an API command
- We account for this change in `reauthenticate()`
- Then fix up some API method usages where a `.catch()` was implemented as they were previously handling a `CONST.ERROR.API_OFFLINE` and now need to handle a `CONST.JSON_CODE.UNABLE_TO_RETRY`.
- Some automated tests were also fixed to reflect the new changes

### Fixed Issues

$ https://github.com/Expensify/App/issues/8864

### Tests

No specific QA other than to make sure reauthentication flows are working. 

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist
<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps

No specific QA other than to make sure reauthentication flows are working. 

- [ ] Verify that no errors appear in the JS console

### Screenshots
❌

### CODE REVIEW

**Review by robertjchen — DISMISSED** [review]
Looks solid!

**Comment by marcaaron** [comment]
Ah shucks I got conflicts. Fixed now 🙇

**Comment by marcaaron** [comment]
cc @Luke9389 able to give this a quick look?

**Review by Luke9389 — APPROVED** [review]
Nice, this looks great.

**Comment by marcaaron** [comment]
@aldo-expensify Nice catch. I think returning the response could work and would just mean we would continue and set the same error to account again? But why is the call to `createTemporaryLogin()` failing? That sounds like a different bug... Do you want to fix this or should I create a follow up PR here?

**Comment by aldo-expensify** [comment]
> That sounds like a different bug...

Yeah, I think this wasn't working properly before your changes... so we can treat it separately.

> But why is the call to createTemporaryLogin() failing?

I was trying to reproduce the infinite spinner + error this user is getting here: https://github.com/Expensify/Expensify/issues/202627 and noticed that we get similar symptoms with an expired short lived auth token

I got the expired token by reusing the URL that takes you to New Dot. While this is a weird case, I think we should fix it and probably kick the user to the login screen. Do you agree with taking the user to the login screen? or are we handling expired sessions some other ways?

> Do you want to fix this or should I create a follow up PR here?

I'm somewhat concern about the user not being able to use NewDot for a long time now, but I cannot tell yet if this would fix the problem for the user or not. I'm ok with trying to find a solution if your plate is full, and if I find out that this is not related to the problem the user is having, I can even leave it for external contributors.

**Comment by marcaaron** [comment]
>While this is a weird case, I think we should fix it and probably kick the user to the login screen. Do you agree with taking the user to the login screen? or are we handling expired sessions some other ways?

Hmm I'm not sure if I agree because I'm not sure if I understand what is happening. What are the reproduction steps?

If the short lived token is expired I think one of two things would be true...

- They are logged in already as the correct user
    - Short lived token isn't needed because we already have an active session and stored credentials. So why are we logging them in at all.

- They are not logged in at all
    - In this case... they wouldn't need to be "logged out" or brought to the login screen. If we can log them in, but can't create a temporary login that sounds like a bug.

- They are logged in as a different user
    - If this is true then we should sign them out then sign them back in with the short lived token and then we are back to the previous scenario ☝️ 

cc @neil-marcellini who has looked into these flows a ton and might have better context.

**Comment by marcaaron** [comment]
>I'm ok with trying to find a solution if your plate is full, and if I find out that this is not related to the problem the user is having, I can even leave it for external contributors.

For now, I will just patch this so the behavior is the same at least and not throw any errors.
I do not think this is a good issue for contributors since it's difficult to test the OldDot > NewDot transition.

**Pull request merged**
