### PR TITLE
Add document picking support to mobile

### PR DESCRIPTION
**Pull request by Julesssss**
CC @Jag96 

Add ability to add document attachments to chats on mobile. This already exists for web and desktop, but mobile users were only able to upload images. 
- Uses [DocumentPicker library](https://github.com/rnmods/react-native-document-picker) for native file selection
- Renames our existing ImagePicker class to AttachmentPicker
- Builds custom 'Add document' option into existing lists 

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/142733

### Tests

**1)** Take Photo
- Press attachment button, then 'Take photo'
- The temporary attachment spinner should display
- Photo should be uploaded as an attachment

**2)** Upload photo from gallery
- Press attachment button, then 'Choose from gallery'
- The temporary attachment spinner should display
- Photo should be uploaded as an attachment

**3)** 
- Press attachment button, then 'Choose Document'
- Select a file for upload (.pdf, .csv, ect)
- File should be uploaded as an attachment

**4)**
- Press attachment button, press cancel button
- The temporary attachment spinner should **not** display

**5)**
- Press attachment button, press 'Choose Document' button
- Press cancel on the modal that pops up
- The temporary attachment spinner should **not** display

**6)**
- Revoke camera permission (or completely reinstall)
- Press attachment button, press 'Take Photo' button
- Deny permission
- The temporary attachment spinner should **not** display

### Screenshots

Simulator Screen Shot - iPhone 11 - 2020-10-23 at 11 23 02
Simulator Screen Shot - iPhone 11 - 2020-10-23 at 12 11 11

**Android**
Screenshot_1603450582
Screenshot_1603451295

### CODE REVIEW

**Review by Jag96 — COMMENTED** [review]
I like the idea of moving the Document picker inside the newly renamed AttachmentPicker. Left a couple of comments but looks good so far.

**Review by Jag96 — COMMENTED** [review]
Looking good, just a couple of questions/recommendations

**Review by stitesExpensify — DISMISSED** [review]
LGTM

**Review by Jag96 — DISMISSED** [review]
LGTM, just a nab

**Review by Jag96 — APPROVED** [review]
LGTM, good stuff!

**Pull request merged**
