### PR TITLE
[HOLD merge of main PR] [Wave8] Top Bar Search - Search Input and clickable Logo with arrow down icon

### PR DESCRIPTION
**Pull request by MaciejSWM**
Note to C+: I had problems with running the app in Android Chrome. Please test yourself if everything is correct.

### Details

This PR implements first part of the components needed for Wave8 Ideal Nav.

These are the components implemented:
image
On mouse hover:
image
Storybook for Search component:
image
Storybook for SubscriptAvatar:
image

This is the relevant part in Figma I used as the base:
https://www.figma.com/file/Xv3yHJooZcxRGkXbAcTZD5/%23ideal-nav-(Ideal-Nav)?type=design&node-id=576-250584&mode=design&t=elsCHwrw0dccJ2kn-4

### Fixed Issues

$ https://github.com/Expensify/App/issues/31766
PROPOSAL: 

### Tests

- Verify that no errors appear in the JS console
- Open Storybook, look for Search component
- Open Storybook, look for SubscriptAvatar component
- Open the App, see if the top left part of the left hand panel looks like in the Figma. Validate that:
  - Pressing Search Input opens the search modal
  - Pressing the avatar on the right opens the settings
  - Pressing the Expensify logo does nothing - will be implemented in it's own time

### Offline tests

- Same as QA

### QA Steps

- Verify that no errors appear in the JS console
- Open the App, see if the top left part of the left hand panel looks like in the Figma. Validate that:
  - Pressing Search Input opens the search modal
  - Pressing the avatar on the right opens the settings
  - Pressing the Expensify logo does nothing - will be implemented in it's own time

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/85628901/b9109576-9398-489d-ab03-784870e1aa11

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Problems with running

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/85628901/4c57e18e-5950-43c7-8870-2dcfd131b6cf

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/85628901/84cf3c33-49ca-4b34-b795-a2bff0126519

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/85628901/f7c83b9e-3070-471f-8837-e95c1f37ad20

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/85628901/4291b2ea-125e-4ddf-9d3e-bc878ce73ce6

</details>

### CODE REVIEW

**Comment by hayata-suenaga** [comment]
@MaciejSWM when you click the Expensify icon on the left side of the search bar, nothing happens yet right?

**Comment by MaciejSWM** [comment]
> Btw, did you try this and still failed?
> 
> https://127.0.0.1:8082/ after running `adb reverse tcp:8082 tcp:8082`

Yes, tried this and was still getting `structuredClone is not defined`, even on main. I've seen someone having the same issue but no solution was found at that time.

> @MaciejSWM when you click the Expensify icon on the left side of the search bar, nothing happens yet right?

Yes - it's just the component itself so far, nothing happens on onPress

**Comment by mountiny** [comment]
@MaciejSWM Sorry just to clarify, we should not be merging the design changes to the App yet in live components. We should just create new components which we can then plug into the App to change once we have more bits and pieces of the doc and design ready.

**Comment by MaciejSWM** [comment]
I know @mountiny. Any suggestions on how to approach this so that nobody merges it beforehand?

**Comment by hayata-suenaga** [comment]
for the new components, we can merge as long as we don't use the new component

however, if you have modified existing components in this PR, we have to wait until the navigation stuff is complete.

@mountiny, but in this case, I think it's fine to merge this beforehand because this wont' change the functionality. Maybe we can discuss this in the design doc rollout plan?

**Comment by mountiny** [comment]
I dont know.. this is changing how to top search bar looks and I thin kwe should roll out the design changes all in one go to.

I think we should update this PR to only add new components which are not used and we can just put them in use later.

I have added HOLD so without removing it cant be accidentally merged

**Comment by hayata-suenaga** [comment]
@aimane-chnaif please hold the review of this PR until @MaciejSWM makes a new PR (as stated above)

**Comment by MaciejSWM** [comment]
@hayata-suenaga @aimane-chnaif @mountiny Search component extracted into a separate PR: https://github.com/Expensify/App/pull/32439

**Comment by trjExpensify** [comment]
What's going on here? Does this PR need to still be on hold?

**Comment by mountiny** [comment]
I think this PR yes, or at least merging to main, we can merge it to the feature branch

**Comment by hayata-suenaga** [comment]
Changed the title to make it more clear what we're holding on. As discussed here, the feature branch might be created in the SWM's fork, so I won't put the branch number to the HOLD prefix of the title.

**Comment by MaciejSWM** [comment]
Will be part of ideal-nav-merge branch

**Pull request closed without merging**
