### PR TITLE
Add loading indicator

### PR DESCRIPTION
**Pull request by alex-mechler**
@roryabraham will you review please?

cc: @marcaaron 

# Fixed issues
$ https://github.com/Expensify/Expensify/issues/141725

## Tests / QA
1. Attempt to sign in with a login that will not work
1. _Verify_ that you get a loading indicator
1. After the signin attempt has finished, _verify_ that you receive an error message
1. Attempt to sign in with valid credentials.
1. _Verify_ the error message disappears, and that you get a loading indicator
1. _Verify_ you are signed in
1. Sign out
1. Turn off your local nginx
1. Attempt to sign in
1. _Verify_ the loading indicator stops, and you get the following error
image

## Screenshots
IOS
image

Android
image

Web
image

Desktop
image

### CODE REVIEW

**Review by roryabraham — CHANGES_REQUESTED** [review]
Code looks good, but in the case that there is no network connection (i.e: [this](https://github.com/Expensify/ReactNativeChat/blob/master/src/lib/Network.js#L48) is thrown), it will display a loading indicator indefinitely, and no network connection error message.

**Review by marcaaron — CHANGES_REQUESTED** [review]
LGTM just left a few minor comments

**Review by roryabraham — APPROVED** [review]
Looks good to me

**Review by marcaaron — APPROVED** [review]
LGTM

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
