### PR TITLE
fix: Add trim to searchValue in OptionsUtils

### PR DESCRIPTION
**Pull request by mananjadhav**
### Details

- Added `trim()` for `OptionsUtils` so that leading/trailing spaces can be ignored when making the search calls.

### Fixed Issues

$ https://github.com/Expensify/App/issues/6907

### Tests
1. Tested the search with leading/trailing spaces for the input
2. Ensured the input doesn't change automatically

### QA Steps
1. Click the Profile image to open settings
2. Navigate to any Workspaces
3. Go to Members >Manage Members
4. Invite any email with leading/trailing spaces
5. Ensure the search shows the result.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

web-options-space-trim

**New Email Search**
web-new-email-options-search

#### Mobile Web

mweb-options-space-trim

#### Desktop

desktop-options-space-trim

#### iOS

ios-options-space-trim

#### Android

android-options-space-trim

### CODE REVIEW

**Review by mountiny — CHANGES_REQUESTED** [review]
@mananjadhav Thank you very much for the PR! I have one request, would you be able to show a screenshot/video, with a new email searched? Email the user has never been in touch and maybe does not even exist (I think that was the case in the original proposal)

**Comment by mananjadhav** [comment]
@mountiny Updated in the PR body web screenshot.

**Review by mountiny — APPROVED** [review]
@mananjadhav Thank you! Nice job on this issue:)

**Review by parasharrajat — COMMENTED** [review]
:ribbon: :eyes: :ribbon:  C+ reviewed

**Pull request merged**
