### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by spamalotmucho**
### Details
THIS IS A TEST! Please don't merge 👍 

### Fixed Issues
$ https://github.com/Expensify/App/issues/6564

### Tests
None, it's just a test!

### QA Steps
None, it's just a test!

### Tested On
N/A

### Screenshots
N/A

### CODE REVIEW

**Comment by Beamanator** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by spamalotmucho** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by spamalotmucho** [comment]
recheck

**Comment by Beamanator** [comment]
Thanks for being test dummies @luacmartins and @parasharrajat - That time you were assigned when the PR went from draft to ready for review, now we'll try when I request `Pullerbear` as a reviewer

**Comment by Beamanator** [comment]
Sick! Worked again!

**Pull request closed without merging**
