### PR TITLE
Use `VERSION_CODE` instead of `VERSION`

### LINKED ISSUE #2918: Android Production Deploys are failing
Keeping this issue internal since this requires Google Play access to confirm the builds show up in the internal track
cc @Expensify/mobile-deployers 

## Expected Result:
Android deploys such as [this one](https://github.com/Expensify/Expensify.cash/commit/66421d9a5c3bd916c9d454638b45c4c25f0eea00/checks) should succeed

## Actual Result:
Android deploys are failing with the following error message:
`Track 'internal' doesn't have any releases`

## Action Performed:
This happens during the `Run Fastlane` step of the [Build and Deploy Android 
 action](https://github.com/Expensify/Expensify.cash/commit/66421d9a5c3bd916c9d454638b45c4c25f0eea00/checks)

## Platform:
Where is this issue occurring?
- Android

For the run mentioned above, we see `[22:53:31]: Found '1001004400' version codes in track 'internal'` in the logs, and in the google play console we see that the 1.0.44-0 release is in the Internal Testing track, but for some reason fastlane still doesn't see the release.

Potentiall related: https://github.com/fastlane/fastlane/issues/18497

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
Changes the ENV variable to the correct name `VERSION_CODE` in the platform deploy workflow.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2918

### Tests
1. Run a production Android deploy
2. Verify the version_code is not `0`

### CODE REVIEW

**Review by roryabraham — COMMENTED** [review]
Just noticed that in the iOS production lane we're expecting a `VERSION` input, but in Android we're expecting `VERSION_CODE`. Maybe we should change the ruby code instead of the GH workflow so that the inputs match better between iOS and Android?

**Comment by AndrewGable** [comment]
👍 - That works! I will make that change.

**Review by Jag96 — APPROVED** [review]
LGTM

**Review by roryabraham — APPROVED** [review]
Cool, let's see if this works!

**Pull request merged**
