### PR TITLE
Treat IOU debts as pinned reports in the LHN

### PR DESCRIPTION
**Pull request by Jag96**
### Details
This PR updates the LHN to show IOUs the user owes at the top of the LHN with pinned reports.

### Fixed Issues

$ https://github.com/Expensify/Expensify.cash/issues/3389

### Tests/QA
1. Sign into account A and send some requests to other users for different amounts
2. Sign into account B and send a request to account A so that account A owes account B
3. Sign into account C and send a request to account A *larger than the amount in step 2* so that account A owes account C
4. In account A, change the Priority Mode (click user profile image -> preferences -> priority mode) to #focus, confirm that after navigating back to the LHN all reports are shown in alphabetical order, and unpinned IOU debt reports are still shown in the LHN
5. Change the Priority Mode back to Recent Mode, confirm that after navigating back to the LHN the pinned reports are at the top, followed by the debts in order from highest to lowest amount owed, followed by other chats
6. Hit the search icon, confirm that the results are still shown in recent order, and not in order of pinned reports or debts.
7. Hit the green plus button and select a new chat, confirm that the results still show the recent chats in order of recently viewed, ~and the contacts below are listed in alphabetical order.~

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web/Desktop/Mobile Web
| #focus | Recent |
|---|---|
| image | image |

#### iOS/Android
| #focus | Recent |
|---|---|
| image | image |

### CODE REVIEW

**Comment by Jag96** [comment]
Converting to draft while I fix/update tests

**Comment by Jag96** [comment]
Updated tests and screenshots, this is ready for review!

**Comment by Jag96** [comment]
@johnmlee101 friendly bump!

**Review by johnmlee101 — APPROVED** [review]
Looks great!

**Comment by kavimuru** [comment]
## New Chat - List of the Contacts area is not organized in alphabetical order
## Expected Result: 
 Per the step 7 of the PR, Contacts listed must be in alphabetical order
## Actual Result:
Contacts are not in alphabetical order
## Actions Performed:
1. Open e.cash in Web
2. Click the green plus button and select a new chat
3. Scroll down to the Contacts area
## Platform:
iOS ✔️
mWeb ✔️
Android ✔️
Web ✔️
Desktop ✔️
## Build:
1.0.78-0
## Notes/Images/Video:

https://user-images.githubusercontent.com/43996225/125950188-64044034-45c0-472a-9dd3-e5caa2167dac.mp4

Bug5153398_image__4_

**Comment by isagoico** [comment]
Looks like step 7 is failing **but** the same issue is reproducible in production. @Jag96 Should I open a separate issue for this or do you want to address this on this PR?

**Comment by Jag96** [comment]
Ah, I just added that step since that was what I was seeing when I tested on my account. Scrolling all the way down on production though, I see that all the contacts aren't all in alphabetical order, and looking back at the code it seems this isn't being done explicitly, so I think we can leave this alone for now (not an issue). Thanks for the double-check!

**Pull request merged**
