### PR TITLE
[No QA] Fix directory error on node run web

### PR DESCRIPTION
**Pull request by candidia**
### Details
This makes config/webpack/CustomVersionFilePlugin.js ensure all of version.js's parent directories exist before creating it.

### Fixed Issues
$ https://github.com/Expensify/App/issues/7011

### Tests

1. Make a fresh copy of the repo
2. Install node & npm: `brew install node`
3. Install watchman: `brew install watchman`
4. Install dependencies: `npm install`
5. Run `npm run web`

- [X] Verify that no errors appear in the JS console

### QA Steps
I think simply deploying this to staging should validate it worked if staging has a fresh copy of the repo each time.

- [X] Verify that no errors appear in the JS console

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

### Screenshots
N/A, this is dev bug

#### Web
N/A

#### Mobile Web
N/A

#### Desktop
N/A

#### iOS
N/A

#### Android
N/A

### CODE REVIEW

**Comment by CSFlorin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by CSFlorin** [comment]
recheck

**Comment by rushatgabhane** [comment]
Hi @CSFlorin, can you please change your title to something like - **[No QA]** Fix directory error on node run web. Thanks!

**Review by rushatgabhane — APPROVED** [review]
LGTM! 🎉

cc: @Jag96

**Review by Jag96 — APPROVED** [review]

**Pull request merged**
