### PR TITLE
Rename expensify button

### PR DESCRIPTION
**Pull request by mateusbra**
### Details

Rename component `ExpensifyButton` to `Button`
### Fixed Issues

$ https://github.com/Expensify/App/issues/6760

### Tests

1. Run the app and see that Buttons continue working.
### QA Steps

1. Run the app and see that Buttons continue working.
### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web

Captura de Tela 2021-12-15 às 19 12 45
#### Mobile Web

WhatsApp Image 2021-12-15 at 19 14 37
#### Desktop

Captura de Tela 2021-12-15 às 19 01 16

### CODE REVIEW

**Review by parasharrajat — APPROVED** [review]
LGTM. Please create separate PR for each milestone. Thanks.

cC: @puneetlath .

**Review by puneetlath — COMMENTED** [review]
Looks good to me as well. However, can you test on the mobile apps as well for completeness. Once you do, I'll merge. Thanks!

**Comment by mateusbra** [comment]
Tested in Android and IOS apps and it worked fine on both:
**Android**
WhatsApp Image 2021-12-17 at 12 59 42
**IOS**
Simulator Screen Shot - iPhone 12 - 2021-12-17 at 14 02 29

**Review by puneetlath — APPROVED** [review]
Thank you!

**Pull request merged**
