### PR TITLE
Move ExistingOwners view into new component. Reuse confirm modal.

### PR DESCRIPTION
**Pull request by marcaaron**
cc @aldo-expensify @jasperhuangg 

### Details
Just moving some things around so that our error handling is easier to follow.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/176349

### Tests
1. Follow steps here to get the modal to appear https://stackoverflow.com/c/expensify/questions/10740/10741
2. Verified this modal appears

3. Pressed "Got it" and verified it went away
4. Make it appear again
5. Press the link and verify the modal closes and we navigate to the "Company Information" step.

### QA Steps
1. Create a policy and add User A and User B
1. Create bank account in open state with User A (via OldDot or via the `/bank-account` flow in NewDot)
1. Attempt to create bank account as User B in NewDot via the `/bank-account` flow
2. Verified this modal appears
3. Press "Got it" and verify it goes away
4. Make it appear again (add the same account)
5. Press the hyperlink and verify the modal closes and we navigate to the "Company Information" step.

**Note:** This cannot be QA'd on native platforms yet as the Plaid staging credentials do not work in NewDot yet.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
@joelbettner do you happen to know much about what an "existing copy" is or when we'd show this? 
I couldn't figure out how to surface this error organically.

**Review by aldo-expensify — DISMISSED** [review]
~~Looks good.~~

Found a problem, see comment below.

**Comment by aldo-expensify** [comment]
If you click the blue link in the modal, it takes you to the Company step, but the modal stays there and the error changes to the generic error -> the modal should hide.

On a side note: the blue link is taking the user to the company step, is this correct? (This behaviour was here from before this PR)

**Comment by marcaaron** [comment]
>On a side note and out of the scope of this PR: the blue link is taking the user to the company step, is this correct?

I'll look into this today thanks!

**Comment by marcaaron** [comment]
>the blue link is taking the user to the company step, is this correct

AFAIK this is correct. We handle the link the same way in OldDot.

**Comment by marcaaron** [comment]
OK, fixed the issue with the modal not closing. Still unsure exactly how to trigger the existing copies warning in staging.

**Comment by marcaaron** [comment]
Ok figured this out and added a SO post [here](https://stackoverflow.com/c/expensify/questions/10740)

**Review by aldo-expensify — APPROVED** [review]
Looks good. Tested in Android and web.

**Comment by isagoico** [comment]
@marcaaron Hello! This PR was a pass in web. We were unable to verify this on Android because of this issue https://github.com/Expensify/App/issues/5075. Are we good to check it off?

**Pull request merged**
