### PR TITLE
Unescape the backend strings for IOU

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/6159

### Tests | QA Steps

1. Open staging.new.expensify.com
2. Login with existing account
3. Tap + button
4. Select Split Bills
5. Select contact with double-quote in the name
6. Tap Request
7. Open the chat with that IOU request and observe their name.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

image

### CODE REVIEW

**Comment by parasharrajat** [comment]
Gentle Bump @puneetlath .

**Comment by parasharrajat** [comment]
@puneetlath Awaiting your review...

**Comment by puneetlath** [comment]
@parasharrajat we have a merge hold right now, so won't be able to merge until next week or a little longer, but I'll review soon!

**Comment by parasharrajat** [comment]
Maybe you can add the hold label on the issue @puneetlath. Thanks.

**Comment by mallenexpensify** [comment]
Removed Company Offsite HOLD, feel free to merge @puneetlath

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
