### PR TITLE
Skintone Emoji Border Radius and Size

### PR DESCRIPTION
**Pull request by mananjadhav**
@stitesExpensify Can you please review this?

### Details
- Added `borderRadius` to Skin tone Emoji
- Aligned skin tone picker with rest of the emojis

### Fixed Issues

$ https://github.com/Expensify/App/issues/5247

### Tests
1. Checked Emoji Skintones on all platforms
2. Verified the default highlighted skintone

### QA Steps

**Emoji Size**
1. Go to EmojiPicker
2. Hover over any Emoji
3. Click on Choose Skintone and hover over any skintone
4. Verify size is same for both of them.

**Emoji Retention**
1. Open EmojiPicker
2. Click on "Change default skin tone"
3. Choose one of the skin tones.
4. Click on the "Change default skin tone" again
5. Verify the selected skin tone in step 3, is highlighted by default.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screenshot 2021-09-15 at 12 29 16 AM

**Updated**
web-skintone-list-alignment
web-skintone-picker-alignment

#### Mobile Web

mweb-skintone-picker-alignment
mweb-skintone-list-alignment

#### Desktop

image

**Updated**

desktop-skintone-picker-alignment
desktop-skintone-list-alignment

#### iOS

ios-skintone-picker-alignment
ios-skintone-list-alignment png

#### Android

android-skintone-picker-alignment
android-skintone-list-alignment

### CODE REVIEW

**Comment by shawnborton** [comment]
Can we make it so that the buttons on this screenshot are perfectly aligned? It seems like the bottom row is shifted over to the left a bit:
image

**Comment by mananjadhav** [comment]
@shawnborton does this work?

image

image

**Comment by shawnborton** [comment]
Looks great, but perhaps in the default state we can align the ✋ icon to the left edge of the emojis above as well?
image

**Comment by marcaaron** [comment]
Taking myself off this review as it's related to https://github.com/Expensify/App/issues/4323 also tagging in @puneetlath

**Comment by mananjadhav** [comment]
Done.

image

**Comment by kadiealexander** [comment]
Hi @mananjadhav, I've placed this issue on hold as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1631754482374800), as we are prioritising issues related to a feature release scheduled for 9/24. As an apology for the delay, we will add a $100 bonus as a thank you for waiting.

**Comment by puneetlath** [comment]
@mananjadhav the changes look good to me, but can you add updated screenshots from all platforms to your original comment? Then I can go ahead and approve.

**Comment by mananjadhav** [comment]
@puneetlath @stitesExpensify I would like to request a review again. I have done some cleanup of the code when fixing issues for all mobile devices.

**Comment by stitesExpensify** [comment]
Hi @mananjadhav I can give you a review, but this is currently on hold due to internal prioritization so it cannot be merged https://github.com/Expensify/App/issues/5247#issuecomment-920501918

**Comment by stitesExpensify** [comment]
Also, are the screenshots in the PR description current? Or are they from a previous iteration of the code?

**Comment by mananjadhav** [comment]
For Web and Desktop I’ve tagged Updated. 

For the rest we weren’t solving earlier so it didn’t have. Now I’ve updated for all screenshots

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
