### PR TITLE
fix/14954: "Email" title is displayed on the detail page instead of "Phone number" after creating a chat with an invalid number

### PR DESCRIPTION
**Pull request by tienifr**
### Details
When the user type in the phone number on the new chat search, the isValidPhone filter is using the original text that was typed in. However, the isSMSLogin condition that was used to select "Email" or "Phone number" label is using the phone number with added country code. This inconsistency is the root cause of the issue

### Fixed Issues

$ https://github.com/Expensify/App/issues/14954
$ https://github.com/Expensify/App/issues/14954#issuecomment-1426940665

### Tests

1. Click on :green-plus-button: > New chat
2. Enter an invalid phone number and press enter key
3. Verify that there are no options displayed
4. Enter a valid phone number and press enter key
5. Verify that the contact title in the detail page should be "Phone number"

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Click on :green-plus-button: > New chat
2. Enter an invalid phone number and press enter key
3. Verify that there are no options displayed
4. Enter a valid phone number and press enter key
5. Verify that the contact title in the detail page should be "Phone number"

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/113963320/218646124-c7d13407-11c7-4d9b-b72f-075a9980f762.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/113963320/218646232-4a743105-4172-4fd6-8e15-1d085334fb66.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/113963320/218646143-6cdd9188-3613-4ad2-8ed9-329b774205b3.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/113963320/218646153-c9c501b1-f044-4447-9949-ffb7662423ae.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/113963320/218647172-61a1db86-4732-4fb6-96b1-e0a25728b535.mp4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/113963320/218651805-f844861b-35ae-492f-80e9-f0c0fc76d899.mp4

</details>

### CODE REVIEW

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
I've reviewed the PR. I'll test on all platforms tonight.

**Comment by cead22** [comment]
> * [x]  I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)

Can you share how this was done? Does your test cover all the flows that call `getOptions`? If not, can you test them all please?

**Comment by tienifr** [comment]
@cead22 the getOptions function is being used in 3 places: getSearchOptions in SearchPage, getNewChatOptions in NewChatPage, getMemberInviteOptions in WorkspaceInvitePage. I just tested and saw that it works correctly in all places

**Comment by mananjadhav** [comment]
@robertjchen I was wondering if we could get the regression test suite from the QA team here so that we can ensure we cover everything? I am a bit concerned as getOptions is used at multiple places and moving the code shouldn't impact any other search operation?

@tienifr Are you fine that we run the regression test suite to ensure things are working as expected for other areas.

**Comment by tienifr** [comment]
I agree with @mananjadhav, we should run the regression test to ensure that it works correctly in all places

**Comment by robertjchen** [comment]
@mananjadhav Thanks for pointing this out- additional testing with such refactors are always good!

However, I'm not 100% familiar with the `regression test suite from the QA team`? My understanding is the same as @tienifr , where the usual QA process also includes a regression test. Is there an example where we've employed more in-depth regression testing for other PRs- would love to know about this myself 🙏

**Comment by mananjadhav** [comment]
@robertjchen We had done that [here](https://github.com/Expensify/App/pull/7846#issuecomment-1230024273). @roryabraham Had shared the list of test rail cases maintained internally for the component my PR was touching and then we tested each test rail case. I hope this helps.

**Comment by robertjchen** [comment]
Got it- agreed that it would be great! I might have to defer to @roryabraham on the process behind employing the same testing here, as I'm not sure if this involves granting access or finding QA resources.

**Comment by cead22** [comment]
These are the tests I see we have for the chat switcher

image

And here are the steps for each

image
image
image
image
image
image

**Review by cead22 — APPROVED** [review]

**Comment by cead22** [comment]
Code looks good. @mananjadhav please fill out the reviewer checklist when you get a chance

**Comment by mananjadhav** [comment]
Thanks @cead22. Testing this out. @tienifr Can you also test the given regression suite?

**Comment by tienifr** [comment]
1. Chat switcher

https://user-images.githubusercontent.com/113963320/219604920-e6799209-5efc-442f-8b7f-806133acc001.mp4

3. New chat/New group search

https://user-images.githubusercontent.com/113963320/219607074-3d625145-456d-40c9-828c-f0bc266ab934.mp4

4. Request/Send/Split bill

https://user-images.githubusercontent.com/113963320/219607734-b8f5d5bf-7c37-4b0b-b6a2-63a43bc152d0.mp4

5. Arrow navigation

https://user-images.githubusercontent.com/113963320/219611282-2373379b-2cfb-4e68-8cd0-5eed11f6a6fb.mp4


6. Navigate to Concierge link

https://user-images.githubusercontent.com/113963320/219611422-99cc7666-8861-4fe0-a252-825d0c2f53e3.mp4


7. Navigate to IOU link

https://user-images.githubusercontent.com/113963320/219613938-71f28238-93c4-4cc8-8ebe-39aebf27735c.mp4

**Comment by tienifr** [comment]
@mananjadhav Can u help review my tests? Thanks

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/3069065/219744810-3db45c5d-55fa-46bc-8719-a78ffd565549.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/3069065/219745967-b5a83a67-caca-478b-b878-0880e2c1bf47.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>


https://user-images.githubusercontent.com/3069065/219747462-efe13cfc-d073-4d95-a5d4-d8bd1bda42b4.mov

https://user-images.githubusercontent.com/3069065/219747678-842288b3-bc66-4f52-91a4-5fdb69493842.mov


https://user-images.githubusercontent.com/3069065/219748062-e3baa034-d760-4e7a-b941-68c1f4a18904.mov



https://user-images.githubusercontent.com/3069065/219747495-5eb31769-870e-48c6-a6fe-ffcd0cd934ec.mov

https://user-images.githubusercontent.com/3069065/219746340-965df8ca-0a96-421b-9984-697373be434b.mov

</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by cead22** [comment]
Thanks! @mananjadhav your desktop video doesn't show the full test, so I created a new one
https://user-images.githubusercontent.com/165133/219793352-7c294a59-bf67-4622-9371-094f68ae4e24.mov

**Comment by deetergp** [comment]
Just a heads up that the code to append country codes should also have been applied go `Loginutils.getHeaderMessage`. Not doing so led to [this issue](https://github.com/Expensify/App/issues/15547) being created.

**Pull request merged**
