### PR TITLE
show current user in members

### PR DESCRIPTION
**Pull request by thesahindia**
### Details

Made the current user show up in members page

### Fixed Issues

$ https://github.com/Expensify/App/issues/7624

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open app
2. Create a room or go to announce/admins room
3. Verify it shows you in members
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/83179295/153755429-f8b2031e-b174-406e-b284-a1cd670d2592.mov

#### Mobile Web

https://user-images.githubusercontent.com/83179295/153755431-01c7eb18-437f-4de2-9aec-58feddbb2b9e.mov

#### iOS

https://user-images.githubusercontent.com/83179295/153755432-3bf3d8c3-9048-4fff-b302-5f12ffa0a203.mov

#### Android

https://user-images.githubusercontent.com/83179295/153755430-184dbb35-710d-45bd-ae2e-f44ff470cb97.mov

### CODE REVIEW

**Comment by rushatgabhane** [comment]
@thesahindia you should merge `main` into your branch, so that you can test desktop. Thank you for adding desktop screenshot.

**Review by rushatgabhane — APPROVED** [review]
@puneetlath LGTM! Tests well on all platforms (inc desktop)

**Comment by thesahindia** [comment]
@rushatgabhane, I tried running desktop after merging main but I am still seeing the white screen.

**Comment by rushatgabhane** [comment]
That's weird, try deleting .env files.

**Review by puneetlath — APPROVED** [review]

**Comment by puneetlath** [comment]
Tested and it works for me on Desktop as well.

**Comment by SumitDiyora** [comment]
**Issue 1 -**

**Title** - [High]: Chrome+Jaws : Screen reader: Role not defined for "back" control.
**Actual** - Role is not defined for the "back (<)". interactive element. This made it difficult for screen reader users to access the functionality associated with it. Additionally, the label is not defined for the mentioned interactive element in the source code of the page.
**Expected** - When a role is defined appropriately for the interactive element, the screen reader user will interact with the element effectively.
**WCAG failure** - 4.1.2, 2.5.3
**Reproducible in staging?** - Yes
**Version Number:** - v1.1.39-3
**Platforms** - Web, Desktop, Mobile-web, iOS
**Suggested Fix** - Ensure that all the page functionality is available for all users irrespective of the device being used.
Apply the following changes:
- Specify role="button" for the 'div' element containing the "back (<)" control.
- Provide aria-label value such as "back" for the 'div' element containing the "back (<)" control.

**Note** - Due to installation of build not able to check on 'Android'.

Role not defined for back interactive element

**Issue 2 -**

**Title** - [High]: Chrome+Jaws : Non Modal dialog inaccessible fro screen reader user.
**Actual** - Non-modal dialog (that becomes available on clicking "Members" interactive elements) gets dynamically added on the screen. The keyboard focus does not move to the beginning of the non-modal dialog. Screen reader users are not aware of the non-modal dialog. In fact, blind users are not informed that a non-modal dialog is displayed on the screen, and they have no means to distinguish between the non-modal dialog content and the content of the screen behind it.
**Expected** - Non-modal dialog should be accessible for keyboard only and screen reader user.
**WCAG failure** - 2.1.1
**Reproducible in staging?** - Yes
**Version Number:** - v1.1.39-3
**Platforms** - Web, Desktop, Mobile-web, iOS
**Suggested Fix** - 
Apply the following changes:
• In the page source code, move the non-modal dialog content immediately after the link that triggers it. 
• When the non-modal dialog is displayed, set the keyboard focus to the beginning of its content (tabindex="-1" can be used for this purpose).
• Add the text “pop-up content starts” and “pop-up content ends” at the beginning and at the end of the non-modal dialog content to assist blind users. Position this text off-screen via CSS.

**Note** - Due to installation of build not able to check on 'Android'.

https://user-images.githubusercontent.com/98817464/157303368-389cced2-68a7-44be-b37f-9752de91236f.mp4

**Pull request merged**
