### PR TITLE
Use currentBalance instead of availableBalance

### PR DESCRIPTION
**Pull request by madmax330**
### Details

We're showing the wrong balance to the user. The `currentBalance` is the one we want the user to see. `availableBalance` is used on the backend to decide wether or not to authorize transactions.

cc @parasharrajat 

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/173152
$ https://github.com/Expensify/Expensify/issues/173151

### Tests

- Log into an account with a wallet
- Insert a queued reimbursement with the creditBankAccountID the wallet of the account you are logged in with
- Make sure that you see the balance updated. 
- Check that available balance is 0 by running this snippet:
```
API.get({returnValueList: 'userWallet'}).done(({userWallet}) => {
            console.log(userWallet);
        }).fail((e) => {
            console.log(e);
        });
```

### QA Steps

- Request money from someone
- Have them pay the IOU via bank account, not debit card
- Make sure you see your balance change right after they paid the IOU

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

Screen Shot 2021-09-06 at 10 04 48 PM
Screen Shot 2021-09-06 at 10 04 53 PM
Screen Shot 2021-09-06 at 10 05 22 PM

### CODE REVIEW

**Comment by madmax330** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by parasharrajat** [comment]
Ok. Thanks for making a clear distinction. I am working on one of the PR's which deal with this so I will update that.

**Review by Dal-Papa — DISMISSED** [review]
Code LGTM

**Comment by madmax330** [comment]
Updated, only tested on web since there's not actually a UI change.

**Review by Dal-Papa — APPROVED** [review]

**Review by stitesExpensify — APPROVED** [review]

**Comment by stitesExpensify** [comment]
You stole [my PR](https://github.com/Expensify/App/pull/5033)! lol jk. Updated your description to include that other issue and merged :+1:

**Comment by isagoico** [comment]
@madmax330 Hello! is this testable by us? we tried by adding a fully verified account but the payment option doesn't appear.

**Comment by madmax330** [comment]
No I put the internalQA label, but apparently it doesn't work the same here as it does for the web app. Sorry, we'll test this internally.

**Comment by roryabraham** [comment]
Hey y'all, any update on the internal QA here? This is the last item on the checklist blocking a prod deploy.

**Comment by yuwenmemon** [comment]
Looks like @Jag96 and @kevinksullivan are doing the internal QA for this.

**Comment by madmax330** [comment]
No it's @joekaufmanexpensify  and Kevin. Should be good to check off her soon

**Comment by yuwenmemon** [comment]
🤦‍♂️ lol Sorry!

**Comment by madmax330** [comment]
Hence the importance of the Ionatan rule 😆

**Comment by kevinksullivan** [comment]
QA successful on staging - balance changed after paying an IOU.

**Pull request merged**
