### PR TITLE
[HybridApp] Add explanation modal

### PR DESCRIPTION
**Pull request by mateuuszzzzz**
### Details

OldDot part of this PR: https://github.com/Expensify/Mobile-Expensify/pull/12779

### Fixed Issues

$ https://github.com/Expensify/App/issues/37860
PROPOSAL:

### Tests
One remark before tests:
Branch of this PR was created on [our fork](https://github.com/software-mansion-labs/expensify-app-fork).
This means it's impossible to switch to this branch in HybridApp's react-native submodule.
One need to remove `react-native` submodule folder and then clone our fork.
`git clone {ssh/https repo url} react-native`

For OldDot repository one need to switch to this branch [set-explanation-modal-key-in-od](https://github.com/Expensify/Mobile-Expensify/tree/set-explanation-modal-key-in-od)

**It can be tested only on HybridApp**
- Create fresh account (make sure it's not native app, it can be desktop or web)
- Finish or skip onboarding flow.
- Open HybridApp (OldDot) and go to NewDot.
- After opening NewDot one should see Explanation modal. (if onboarding is not finished then after closing explanation modal, onboarding modal should appear)
- Go back to Expensify Classic.
- Kill the app.
- Open once again and go to NewDot.
- Verify that explanation modal opens only once. (in this step it should not open)

### Offline tests

-

### QA Steps

Same as tests

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos

NOTE: All videos were recorded with a trigger from the troubleshooting section. On videos, I included the old onboarding flow after dismissing the explanation modal. Once stage 1 is ready it will be changed to a new onboarding flow.
Especially, those videos don't include full HybridApp flow.

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/60450261/9c779458-644a-4fed-82d9-45488174bd86

</details>

<details>
<summary>Android: mWeb Chrome</summary>
-
</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/60450261/1139a59f-2889-4198-93fd-da41936ae271

</details>

<details>
<summary>iOS: mWeb Safari</summary>
-
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>
-
</details>

<details>
<summary>MacOS: Desktop</summary>
-
</details>

### CODE REVIEW

**Comment by mateuuszzzzz** [comment]
Translations:
English:
`Getting paid is as easy as sending a message.`
`To switch back to Expensify Classic, just tap your profile picture > Go to Expensify Classic.`
Spanish:
`Solicitar y enviar dinero es tan fácil como enviar un mensaje. La nueva era de los gastos ha llegado.`
`Para volver a Expensify Classic, simplemente toca tu foto de perfil > Ir a Expensify Classic.`

**Comment by Santhosh-Sellavel** [comment]
Conflicts again

**Comment by Santhosh-Sellavel** [comment]
Bump @mateuuszzzzz

**Comment by mateuuszzzzz** [comment]
> Bump @mateuuszzzzz

@Santhosh-Sellavel  I resolved conflicts

**Comment by Santhosh-Sellavel** [comment]
@mateuuszzzzz 
#### New Login Case
Onboarding not complete
> When onboarding is not complete: additionally one should be navigated to the onboarding flow.

This case fails

https://github.com/Expensify/App/assets/85645967/129c0b59-1107-4e7d-8047-34819f737f99

#### While window is resized content is not responsive
Unable to scroll, not fit properly

https://github.com/Expensify/App/assets/85645967/08aa841f-e08f-47de-9378-7bb5a079dfe9

**Comment by mateuuszzzzz** [comment]
> @mateuuszzzzz 
> 
> #### New Login Case
> 
> Onboarding not complete
> 
> > When onboarding is not complete: additionally one should be navigated to the onboarding flow.
> 
> 
> 
> This case fails
> 
> 
> 
> https://github.com/Expensify/App/assets/85645967/129c0b59-1107-4e7d-8047-34819f737f99
> 
> 
> 
> #### While window is resized content is not responsive
> 
> Unable to scroll, not fit properly
> 
> 
> 
> https://github.com/Expensify/App/assets/85645967/08aa841f-e08f-47de-9378-7bb5a079dfe9
> 
> 
> 
> 

This looks like regressions introduced after merging main. I will investigate it.

**Comment by Santhosh-Sellavel** [comment]
@mateuuszzzzz bump!

**Comment by mateuuszzzzz** [comment]
> @mateuuszzzzz bump!

I'm on it

**Comment by mateuuszzzzz** [comment]
I added `NVP_SEEN_NEW_USER_MODAL`. For now it simply changes state locally. I will adjust it once BE is ready.

**Comment by AndrewGable** [comment]
Happy to review when ready

**Comment by mateuuszzzzz** [comment]
I adjusted most of the logic in the PR. Remaining things to finish it are types specifications

**Review by AndrewGable — COMMENTED** [review]
Looking good!

**Comment by mateuuszzzzz** [comment]
One important remark. Due to poor transitions we have very weird behaviour on Android. Navigation behaves a bit different than it should (see video for Android native). I can't do much about it in this PR.

I want to fix it in oncoming improved transitions PR where I will delegate handling HybridApp onboarding flow to "HybridApp middleware". This should guarantee us that navigation on Android works correctly.

**Comment by AndrewGable** [comment]
> Perhaps we should close this PR since more complete version is https://github.com/Expensify/App/pull/44471 cc: @AndrewGable

I kinda think we should keep this one separate and just merge `main` into https://github.com/Expensify/App/pull/44471 once this is merged

**Review by AndrewGable — DISMISSED** [review]
Looking really good! I will do checklist soon.

**Comment by AndrewGable** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by AndrewGable** [comment]
Conflicts, but code looks good to me! 

Simulator 2024-06-26 at 14 29 36

**Review by AndrewGable — DISMISSED** [review]

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
