### PR TITLE
Shiny up the request call page

### PR DESCRIPTION
**Pull request by roryabraham**
cc @trjExpensify 

### Details
- Updates the request call page to match OldDot
- Removes the extra information about call scheduling, to be addressed further in [this issue](https://github.com/Expensify/Expensify/issues/179284).

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/179276

### Tests / QA Steps.
1. Open the chat with concierge
1. Click on the call button
1. Verify that the request call modal opens and appears as it does in screenshots below.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Desktop
image

### CODE REVIEW

**Comment by roryabraham** [comment]
Also cc @Expensify/design in case anyone with a keen eye has time for a quick review.

**Comment by shawnborton** [comment]
Looks pretty good to me! 

One question though about iOS: it looks like there is a border on top of the content and that the top status bar area is a different color. Is that a new iOS 15 thing? Is there any way to get a clean white bleed without a border up to the top edge of the device like we used to have?
image

**Comment by shawnborton** [comment]
Looks like Android has this same problem where the top status bar is not a clean bleed with the page. Is that normal?
image

**Comment by roryabraham** [comment]
@shawnborton Let me see what I can do to fix that!

**Comment by roryabraham** [comment]
> One question though about iOS: it looks like there is a border on top of the content and that the top status bar area is a different color. Is that a new iOS 15 thing? Is there any way to get a clean white bleed without a border up to the top edge of the device like we used to have?

So I retested and didn't see this border on the iOS native app:



But I _do_ see it on iOS 15 Safari:



However, I think this problem did exist before, it just didn't look wrong because the search bar was on top:



I looked into this a tiny bit, and it seems like it's an issue that just hasn't been addressed in iOS Safari 15 yet AFAIK. The status bar/everything in the browser outside of the website is prettymuch out of our control in Safari.

**Comment by shawnborton** [comment]
Got it - all of that sounds good to me, thanks for the thorough investigation!

**Review by joelbettner — APPROVED** [review]
Looks great! Glad we can be more concise and have everything in the subtitle.

Are there plans in the future to give an estimate for when the user will receive a call?

**Comment by roryabraham** [comment]
> Are there plans in the future to give an estimate for when the user will receive a call?

Yep! There's an issue for that [here](https://github.com/Expensify/Expensify/issues/179284)!

**Pull request merged**
