### PR TITLE
Add Android production deploy lane

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
Adds Android production deploy lane, which will allow us to move a version from internal testing to production via GitHub actions.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/155198

### Tests
I tested this locally and it did not throw any errors, we will need to test this further when we wire everything together.

```
andrew ➜ Expensify.cash VERSION=1000001492
andrew ➜ Expensify.cash bundle exec fastlane android production
[✔] 🚀
[15:44:18]: ---------------------------
[15:44:18]: --- Step: opt_out_usage ---
[15:44:18]: ---------------------------
[15:44:18]: Disabled upload of used actions
[15:44:18]: Driving the lane 'android production' 🚀
[15:44:18]: ---------------------------------------------
[15:44:18]: --- Step: google_play_track_version_codes ---
[15:44:18]: ---------------------------------------------
[15:44:19]: Found '1000001492' version codes in track 'internal'
[15:44:19]: ----------------------------------
[15:44:19]: --- Step: upload_to_play_store ---
[15:44:19]: ----------------------------------

+---------------------------------+-----------------------------------------+
|                        Summary for supply 2.176.0                         |
+---------------------------------+-----------------------------------------+
| package_name                    | com.expensify.chat                      |
| json_key                        | ./android/app/android-fastlane-json-ke  |
|                                 | y.json                                  |
| track                           | internal                                |
| track_promote_to                | production                              |
| rollout                         | 1.0                                     |
| skip_upload_apk                 | true                                    |
| skip_upload_aab                 | true                                    |
| skip_upload_metadata            | true                                    |
| skip_upload_changelogs          | true                                    |
| skip_upload_images              | true                                    |
| skip_upload_screenshots         | true                                    |
| release_status                  | completed                               |
| validate_only                   | false                                   |
| check_superseded_tracks         | false                                   |
| timeout                         | 300                                     |
| deactivate_on_promote           | true                                    |
| ack_bundle_installation_warning | false                                   |
+---------------------------------+-----------------------------------------+

[15:44:21]: Uploading all changes to Google Play...
[15:44:23]: Successfully finished the upload to Google Play

+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 1    | opt_out_usage            | 0           |
| 2    | google_play_track_versi  | 1           |
|      | on_codes                 |             |
| 3    | upload_to_play_store     | 3           |
+------+--------------------------+-------------+

[15:44:23]: fastlane.tools finished successfully 🎉
```

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
This LGTM but it might be good to get a second Mobile-Deployer like @Jag96 to take a look.

**Comment by Jag96** [comment]
Conflicts from https://github.com/Expensify/Expensify.cash/pull/1643

**Comment by AndrewGable** [comment]
Just tested this once more and I believe it's working as expected:

```
andrew ➜ Expensify.cash VERSION=1.0.2-7
andrew ➜ Expensify.cash bundle exec fastlane android production
[✔] 🚀
[12:39:37]: ---------------------------
[12:39:37]: --- Step: opt_out_usage ---
[12:39:37]: ---------------------------
[12:39:37]: Disabled upload of used actions
[12:39:37]: Driving the lane 'android production' 🚀
[12:39:37]: ---------------------------------------------
[12:39:37]: --- Step: google_play_track_version_codes ---
[12:39:37]: ---------------------------------------------
[12:39:39]: Found '1000001495' version codes in track 'internal'
[12:39:39]: ----------------------------------
[12:39:39]: --- Step: upload_to_play_store ---
[12:39:39]: ----------------------------------

+---------------------------------+-----------------------------------------+
|                        Summary for supply 2.176.0                         |
+---------------------------------+-----------------------------------------+
| package_name                    | com.expensify.chat                      |
| json_key                        | ./android/app/android-fastlane-json-ke  |
|                                 | y.json                                  |
| track                           | internal                                |
| track_promote_to                | production                              |
| rollout                         | 1.0                                     |
| skip_upload_apk                 | true                                    |
| skip_upload_aab                 | true                                    |
| skip_upload_metadata            | true                                    |
| skip_upload_changelogs          | true                                    |
| skip_upload_images              | true                                    |
| skip_upload_screenshots         | true                                    |
| release_status                  | completed                               |
| validate_only                   | false                                   |
| check_superseded_tracks         | false                                   |
| timeout                         | 300                                     |
| deactivate_on_promote           | true                                    |
| ack_bundle_installation_warning | false                                   |
+---------------------------------+-----------------------------------------+

[12:39:41]: Uploading all changes to Google Play...
[12:39:45]: Successfully finished the upload to Google Play

+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 1    | opt_out_usage            | 0           |
| 2    | google_play_track_versi  | 1           |
|      | on_codes                 |             |
| 3    | upload_to_play_store     | 5           |
+------+--------------------------+-------------+

[12:39:45]: fastlane.tools finished successfully 🎉
```

Checked the dashboard and `1.0.2-7` is in review for full rollout to production:

Screen Shot 2021-03-08 at 12 41 21 PM

**Review by Jag96 — APPROVED** [review]
LGTM

**Pull request merged**
