### PR TITLE
Fix emoji picker hover

### PR DESCRIPTION
**Pull request by mollfpr**
### Details

Adding props to handle when the cursor is hovering out to set the highlighted index to none of the emoji items.

### Fixed Issues

$ https://github.com/Expensify/App/issues/10865

### Tests

1. Go to staging.new.expensify.com
2. Open a report
3. Click on emoji icon on composer
4. Type arrow
5. Try to hover on emojis and observe the style applied to emoji in the corner.
6. Verify that on hovering out, none of the items is highlighted.

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

### QA Steps

1. Go to staging.new.expensify.com
2. Open a report
3. Click on emoji icon on composer
4. Type arrow
5. Try to hover on emojis and observe the style applied to emoji in the corner.
6. Verify that on hovering out, none of the items is highlighted.

- [x] Verify that no errors appear in the JS console

#### Web

https://user-images.githubusercontent.com/25520267/191019382-249ed22b-adfc-4af4-a6f4-6388224e7085.mov

#### Mobile Web

https://user-images.githubusercontent.com/25520267/191019618-85dccfad-4360-42d4-9262-999dd041a106.mov

https://user-images.githubusercontent.com/25520267/191805981-5289fe84-36c8-4b9a-9f7e-ef94fb480d7a.mov

#### Desktop

https://user-images.githubusercontent.com/25520267/191019414-07260068-1a7d-4c1c-8519-92302da6a927.mov

#### iOS

https://user-images.githubusercontent.com/25520267/191019523-5b450d7b-51b4-4c51-a9b7-2893308d9cbf.mov

#### Android

https://user-images.githubusercontent.com/25520267/191805851-a72bb6ec-e7f9-4db9-85b0-86731207103b.mp4

### CODE REVIEW

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
@mollfpr the cursor is in the emoji's boundary but it's hover style isn't activated.
Can we fix this?

https://user-images.githubusercontent.com/29673073/190902320-5860380b-016a-4f6f-b98a-0049db26f9c9.mov

**Comment by mollfpr** [comment]
@rushatgabhane I’ll take a look on that.

**Comment by mollfpr** [comment]
> the cursor is in the emoji's boundary but it's hover style isn't activated.

This issue occurred because there's a padding style on the button and because of that the hoverable component will be active after the padding.

Also, we don't have any gap between the `EmojiPickerMenuItem` so the hover in / hovers out will not call in an order. Sometimes hover in will call first when moving the cursor to another item and call hover out after that and make the highlighted state not `-1` while it should bet has the index from the emoji.

I ended up using the hoverable component callback and because of this, we don't need to manage highlighted state in `EmojiPickerMenu` and avoid the race problem of `EmojiPickerMenuItem`. After that apply the hover style to the `Text` emoji.

```diff
diff --git a/src/components/EmojiPicker/EmojiPickerMenuItem.js b/src/components/EmojiPicker/EmojiPickerMenuItem.js
index baa9d9fdf..77f1af52b 100644
--- a/src/components/EmojiPicker/EmojiPickerMenuItem.js
+++ b/src/components/EmojiPicker/EmojiPickerMenuItem.js
@@ -25,23 +25,25 @@ const propTypes = {
 };

 const EmojiPickerMenuItem = props => (
-    <Pressable
-        onPress={() => props.onPress(props.emoji)}
-        style={({
-            pressed,
-        }) => ([
-            styles.p1,
-            StyleUtils.getButtonBackgroundColorStyle(getButtonState(false, pressed)),
-            props.isHighlighted ? styles.emojiItemHighlighted : {},
-            styles.emojiItem,
-        ])}
-    >
-        <Hoverable onHoverIn={props.onHoverIn} onHoverOut={props.onHoverOut}>
-            <Text style={[styles.emojiText]}>
-                {props.emoji}
-            </Text>
-        </Hoverable>
-    </Pressable>
+    <Hoverable containerStyles={[styles.emojiItem, styles.alignSelfCenter]}>
+        {hovered => (
+            <Pressable
+                onPress={() => props.onPress(props.emoji)}
+                style={({
+                    pressed,
+                }) => ([
+                    styles.pv1,
+                    StyleUtils.getButtonBackgroundColorStyle(getButtonState(false, pressed)),
+                    hovered ? styles.emojiItemHighlighted : {},
+                    {borderRadius: 8},
+                ])}
+            >
+                <Text style={[styles.emojiText]}>
+                    {props.emoji}
+                </Text>
+            </Pressable>
+        )}
+    </Hoverable>

 );
 EmojiPickerMenuItem.propTypes = propTypes;
```

**Web**

https://user-images.githubusercontent.com/25520267/190922235-913362cd-0a54-4004-b311-9d76cb84ee74.mov

**iOS**

https://user-images.githubusercontent.com/25520267/190922259-634e647c-bf50-4157-822b-415dd7f44591.mov

cc @rushatgabhane @puneetlath

**Comment by rushatgabhane** [comment]
@mollfpr seems like a better solution. Let's do it!

**Comment by mollfpr** [comment]
> we don't need to manage highlighted state in EmojiPickerMenu and avoid the race problem of EmojiPickerMenuItem
I'm wrong about this, highlighted state is also used to highlight an emoji when using the arrow keyboard.

So we have a problem when using the `Hoverable` component when the `onHoverIn` from the next emoji is called before `onHoverOut` from the current emoji when moving around the cursor from right to left. This is because, on the `Hoverable` component, the callback hover props are called after `setState` is complete for `this.state.isHovered`.

Creating a gap between the emoji to make the cursor a blur for a millisecond is work but makes the highlight hover style not run smoothly.

In this case, we not using the interaction state from the `Hoverable` component. We can use the props `onHoverIn` and `onHoverOut` from the pressable component.

`Hoverable` is used to solve the problem with hover on nested `Pressable` https://github.com/necolas/react-native-web/issues/1875. We not have nested `Pressable` and we are not using the interaction state, so I think it's a good reason to replace the `Hoverable` usage.

```diff
diff --git a/src/components/EmojiPicker/EmojiPickerMenuItem.js b/src/components/EmojiPicker/EmojiPickerMenuItem.js
index baa9d9fdf..929930efe 100644
--- a/src/components/EmojiPicker/EmojiPickerMenuItem.js
+++ b/src/components/EmojiPicker/EmojiPickerMenuItem.js
@@ -4,7 +4,6 @@ import {Pressable} from 'react-native';
 import styles from '../../styles/styles';
 import * as StyleUtils from '../../styles/StyleUtils';
 import getButtonState from '../../libs/getButtonState';
-import Hoverable from '../Hoverable';
 import Text from '../Text';

 const propTypes = {
@@ -27,20 +26,20 @@ const propTypes = {
 const EmojiPickerMenuItem = props => (
     <Pressable
         onPress={() => props.onPress(props.emoji)}
+        onHoverIn={props.onHoverIn}
+        onHoverOut={props.onHoverOut}
         style={({
             pressed,
         }) => ([
-            styles.p1,
+            styles.pv1,
             StyleUtils.getButtonBackgroundColorStyle(getButtonState(false, pressed)),
             props.isHighlighted ? styles.emojiItemHighlighted : {},
             styles.emojiItem,
         ])}
     >
-        <Hoverable onHoverIn={props.onHoverIn} onHoverOut={props.onHoverOut}>
-            <Text style={[styles.emojiText]}>
-                {props.emoji}
-            </Text>
-        </Hoverable>
+        <Text style={[styles.emojiText]}>
+            {props.emoji}
+        </Text>
     </Pressable>

 );
```

**Web**

https://user-images.githubusercontent.com/25520267/191019382-249ed22b-adfc-4af4-a6f4-6388224e7085.mov

**mWeb/Safari**


https://user-images.githubusercontent.com/25520267/191019618-85dccfad-4360-42d4-9262-999dd041a106.mov



**Desktop**

https://user-images.githubusercontent.com/25520267/191019414-07260068-1a7d-4c1c-8519-92302da6a927.mov

**iOS**


https://user-images.githubusercontent.com/25520267/191019523-5b450d7b-51b4-4c51-a9b7-2893308d9cbf.mov


cc @rushatgabhane @puneetlath

**Comment by mollfpr** [comment]
The problem that I mention is this.

https://user-images.githubusercontent.com/25520267/191020013-4b4e29f0-7da2-461a-b1f5-dd6ed9adf76f.mov

As you can see in the video, the log second `hovered in` is called before the first `hovered out` emoji. Instead, we need the callback on hover in/out immediately without waiting for the `setState` to be complete.

**Comment by puneetlath** [comment]
Just to make sure I understand @mollfpr. You are suggesting that we use a `Pressable` component instead of `Hoverable` and we use `onHoverOut` and `onHoverIn` in that `Pressable` component. Is that correct?

**Comment by mollfpr** [comment]
@puneetlath Yes.

**Comment by puneetlath** [comment]
That seems fine to me. @rushatgabhane any concerns?

**Comment by mollfpr** [comment]
Updated video and commit

cc @rushatgabhane @puneetlath

**Comment by puneetlath** [comment]
@rushatgabhane please give it a review when you have a chance. Thanks!

**Comment by mollfpr** [comment]
@rushatgabhane I just push the fix for the above issue. Please check, thanks!

**Comment by mollfpr** [comment]
@rushatgabhane I just try the above issue on staging and the issue is already there. Can you confirm this?

**Comment by mollfpr** [comment]
Bump @rushatgabhane 👆

**Review by rushatgabhane — APPROVED** [review]
@puneetlath LGTM!


<details>
<summary><h4>PR Reviewer Checklist</h4>

</summary>

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

**Comment by puneetlath** [comment]
Have we reported the bug in #expensify-open-source?

**Review by puneetlath — APPROVED** [review]

**Comment by mollfpr** [comment]
@puneetlath Is this mergeable?

**Comment by puneetlath** [comment]
Yep! Just wanted to make sure the bug had been reported before merging.

**Pull request merged**
