### PR TITLE
Password Error message Translation on Language change

### PR DESCRIPTION
**Pull request by mananjadhav**
@Jag96  Can you please review this?

### Details
- Changed error translation on language change
- Also added `onBlur` to the forms
- Hide API error if formError exists

### Fixed Issues

$ #4663 

### Tests
1. Checked error messages translation on changing the language after the error is shown
2. Ensure that error hides if the value is entered and textinput is blurred

### QA Steps
1. Go to the Login Form, press the button and the error is shown
2. After that if the language is changed, then the translation for the password should also be changed

This has to be tested for LoginForm as well as PasswordForm

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/3069065/131161002-8b8e6295-d164-4eab-8443-66e11dcc25a3.mp4
https://user-images.githubusercontent.com/3069065/131161028-b7838053-9e1a-49b6-a92b-39931c55c6c4.mp4

#### Mobile Web
https://user-images.githubusercontent.com/3069065/131161480-d7740257-a2ec-474a-a1c6-7ecfdbb11d8d.mp4
https://user-images.githubusercontent.com/3069065/131161519-9d5d35e6-d41b-436e-ae2b-e62ce202c3c7.mp4

#### Desktop
https://user-images.githubusercontent.com/3069065/131161556-e09b9c9f-dc50-45f6-a86b-3d27dc478a38.mp4
https://user-images.githubusercontent.com/3069065/131161563-5c2a0277-714c-473c-985d-9ff8de724ef3.mp4

#### iOS
https://user-images.githubusercontent.com/3069065/131163340-d6da9bef-def5-4005-bb06-313ac3f9ab6d.mp4
https://user-images.githubusercontent.com/3069065/131163367-6ceffb31-f3d5-46d6-a693-e1192693ee53.mp4

#### Android
https://user-images.githubusercontent.com/3069065/131163437-40bfd47e-5b54-4a79-9d94-0f6a47c44719.mp4
https://user-images.githubusercontent.com/3069065/131163469-a44dbf84-1a5f-4abb-832b-15ae0b5abebc.mp4

### CODE REVIEW

**Review by Jag96 — CHANGES_REQUESTED** [review]
> Update: I've added a fix for the same and pushed it. Attached are the videos for the same. Should we be tracking it outside this PR scope?

Good find! I think it's fine to keep this in this PR if it resolves the issue on all platforms since it's fairly straightforward. If it turns out to be a more complicated issue during testing or if it has other side effects we can move it to its own issue.

**Review by Jag96 — APPROVED** [review]
LGTM, works well!

**Comment by roryabraham** [comment]
Looks like this might've been involved with a [deploy blocker](https://github.com/Expensify/App/issues/4958)

**Comment by roryabraham** [comment]
I do notice for sure that [errors from the API](https://github.com/Expensify/App/blob/17f49e59f3ba30dc36c4af3e54ec2696113067d6/src/pages/signin/LoginForm.js#L96-L98) signin method are not translated.

**Comment by Jag96** [comment]
> I do notice for sure that errors from the API signin method are not translated.

This was not part of the change or requirements for this one, translating errors from the API will have to be a separate issue.

**Comment by mananjadhav** [comment]
@roryabraham I saw the marked issue was unrelated to this one and resolved. Let me know if you still need help.

**Comment by roryabraham** [comment]
Thanks @mananjadhav, this PR didn't cause any regressions, so all good here 👍

**Pull request merged**
