### PR TITLE
#5875 - Make dropdown arrows clickable

### PR DESCRIPTION
**Pull request by elemdos**
### Fixed Issues

$ https://github.com/Expensify/App/issues/5875

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/39444813/144056992-b927f17b-e1f0-4dfd-9314-3623a3e18921.mov

#### Mobile Web
https://user-images.githubusercontent.com/39444813/145066810-0c6ff8e0-81d4-4102-8f91-9d22b9aab568.mov

#### Desktop
https://user-images.githubusercontent.com/39444813/144057394-26ad37cd-5a2c-4efc-bd24-e9f19bf0b972.mov

#### iOS
https://user-images.githubusercontent.com/39444813/145055770-ce51406c-d424-41ce-bf99-91d26c8f8741.mov

#### Android
https://user-images.githubusercontent.com/39444813/146194359-f0802809-8532-40a2-b90f-25a3d77138da.mov

### CODE REVIEW

**Comment by chiragsalian** [comment]
Could you update your `Fixed Issues` section to include the github issue link that you are fixing. Normally you should place the Github issue URL there before putting the PR for review so that the reviewers of your proposal get automatically assigned to review the PR.

**Comment by chiragsalian** [comment]
Also, you'll need to have tests / QA steps in your description explaining how we and QA team should be testing your PR.
Additionally, I've tested this flow on the latest master branch and on production but the dropdown arrows are perfectly clickable. Was this resolved elsewhere at some point and is this is a non-issue anymore?

**Comment by mateomorris** [comment]
Ah yeah sorry about that, forgot to include the issue link. 

And yeah now that you mention it, it looks like this issue was fixed [here](https://github.com/Expensify/App/commit/b3e32bde7f974ab32b520e4eed0e19970c102bc7) shortly after I got accepted for the job. `pointer-events` is a better option to make the arrow unclickable compared to `z-index` (which was used instead), but probably not enough to go through the effort of a change. What do you think @chiragsalian?

**Comment by chiragsalian** [comment]
Yeah, I don't feel like any more effort needs to be made here. I think we should just go ahead and close out this PR and issue and work on other important tasks.

Thanks for the effort Mateo. I guess this one reason why we state in the [contributor guidelines](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request) that providing daily updates is important. This way you and everyone else can test the PR daily against dev and production to notice changes immediately.

**Pull request closed without merging**
