### PR TITLE
chore: update task preview UI

### PR DESCRIPTION
**Pull request by dominictb**
### Fixed Issues

$ https://github.com/Expensify/App/issues/48409
PROPOSAL: https://github.com/Expensify/App/issues/48409#issuecomment-2325564454

### Tests

1. Sign-up on NewDot with a new account
2. Choose an onboarding intent (i.e "Get paid back by my employer")
3. Complete the onboarding steps
4. Navigate to the Concierge DM to view the onboarding tasks created

Verify that: all assigned task previews should
- Not include a mention
- Use only the avatar of the assigned user instead
- Clicking on the task preview row (incl. the avatar) will navigate to the task, not the profile.

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Sign-up on NewDot with a new account
2. Choose an onboarding intent (i.e "Get paid back by my employer")
3. Complete the onboarding steps
4. Navigate to the Concierge DM to view the onboarding tasks created

Verify that: all assigned task previews should
- Not include a mention
- Use only the avatar of the assigned user instead
- Clicking on the task preview row (incl. the avatar) will navigate to the task, not the profile.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Screenshot 2024-09-04 at 19 35 59
</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot 2024-09-04 at 19 36 42
</details>

<details>
<summary>iOS: Native</summary>

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-04 at 19 37 53
</details>

<details>
<summary>iOS: mWeb Safari</summary>

Simulator Screenshot - iPhone 15 Pro Max - 2024-09-04 at 19 38 38
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Screenshot 2024-09-04 at 19 35 15
</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2024-09-04 at 19 35 15

</details>

### CODE REVIEW

**Comment by dannymcclain** [comment]
Screenshots are looking good so far. cc'ing @Expensify/design because this is a decently significant visual change to the product and I want them to be able to review too if they want.

**Review by dukenv0307 — APPROVED** [review]

**Comment by shawnborton** [comment]
Small nitpick but I wonder if we should be reusing the same exact avatar size as the thread indicator? Just to try to reduce the amount of sizes we have on the screen for the same kind of thing.

**Comment by dannymcclain** [comment]
@shawnborton Ah snap, not a bad idea at all!!

Here's a mock comparing thread indicator (28px), your proposed task avatar size (28px), and the original task avatar size (24px).
image

**Comment by shawnborton** [comment]
Dope, thanks for laying it out like that! I like going with 28px as well, I like that it's a size we're using in other places as well. Let's see what @dubielzyk-expensify thinks too!

**Comment by dubielzyk-expensify** [comment]
Great call. Dig it. Just on the completed task look. We don't want any sort of strikethrough on the avatar right? Or fade of the avatar? A part of me kinda wishes there was some visual indication that the task is done on the avatar too. But maybe it's just better to leave it for now?

image

Probably just do nothing, right?

**Comment by trjExpensify** [comment]
Yeah, I think it looks too much like offline pending delete tbh.

**Comment by shawnborton** [comment]
Yeah, I think the `Nothin'` version feels the most correct to me

**Comment by shawnborton** [comment]
If we're all really feeling the fade version, then I think it's totally okay if we do it personally.

**Comment by shawnborton** [comment]
I can see where it looks a bit like pending delete but pending delete should look even more faded out, right?

**Comment by dannymcclain** [comment]
>If we're all really feeling the fade version, then I think it's totally okay if we do it personally.

`#send-it`

>I can see where it looks a bit like pending delete but pending delete should look even more faded out, right?

Yeah I think the whole entire row/message would be faded. I think it would probably be fine.

**Review by blimpich — DISMISSED** [review]

**Comment by trjExpensify** [comment]
Not gunna' fight it. Fifty Shades of Fade™️

**Comment by dubielzyk-expensify** [comment]
Let's do `0.5` or `50%` :)

**Comment by trjExpensify** [comment]
>It should just use our textSupporting color and it shouldn't have reduced opacity. I think only the avatar would have reduced opacity. Is that what you were thinking Danny?

I hope so otherwise it does look exactly like pending delete... 🙈🏃‍♂️

**Comment by dannymcclain** [comment]
Haha yes Shawn and Tom are absolutely right. _Only_ the avatar should get reduced opacity when it's done. It looks like in your screenshot the whole row is getting reduced opacity which is not what we want here (as that is the pending offline pattern as Tom pointed out).

So checkmark and text should be full opacity, just the avatar should be reduced to 50% opacity.

CleanShot 2024-09-06 at 08 25 33@2x

**Comment by shawnborton** [comment]
Sounds correct to me.

**Comment by dubielzyk-expensify** [comment]
> Just to confirm here:
The checkbox and the text won't be faded off
The avatar will be faded off
The text will be strikethrough

Exactly!

**Comment by shawnborton** [comment]
That looks better!

**Comment by dubielzyk-expensify** [comment]
Looks great 🥲

**Comment by trjExpensify** [comment]
Great stuff, let's get this thing merged!

**Comment by dannymcclain** [comment]
Looking good!

@Expensify/design seeing these tasks with the bigger avatar... I'm starting to wonder if we should just use our default size checkbox (20px) instead of the smaller one we're currently using (16px).

Here are some side-by-sides (Current 16px on the left, 20px on the right):

image

image

> [!NOTE]
> If we want to make a change like this, I would propose it being a follow-up and _not_ getting in the way of merging this avatar change.

**Comment by shawnborton** [comment]
Super down to standardize on the... standard size of 20px here!

**Review by blimpich — APPROVED** [review]

**Pull request merged**
