### PR TITLE
Update LoginFormNarrow.js

### PR DESCRIPTION
**Pull request by stephanieelliott**
Corrected small dumb typo reported by a user: corrected Github to GitHub. 

<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
<Explanation of the change or anything fishy that is going on>

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com/Expensify/Expensify/issues/149077

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by flodnv — APPROVED** [review]
@marcaaron what's the process here -- should this still be tested on all platforms before merging?

**Review by flodnv — CHANGES_REQUESTED** [review]
Actually I'm confused why this is going into the `Steph-fixtypo` branch 😕

**Comment by marcaaron** [comment]
Change looks pretty straightforward so I would say it probably doesn't need to be tested at all. 🤷

**Comment by marcaaron** [comment]
@stephanieelliott looks good but you need to follow the instructions in [this comment](https://github.com/Expensify/Expensify.cash/pull/1350#issuecomment-768751042) before we can merge

**Comment by flodnv** [comment]
Alright. It seems the CLA Assistant is saying @stephanieelliott needs to sign the CLA ? 😕

**Comment by stephanieelliott** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by marcaaron** [comment]
recheck

**Review by flodnv — APPROVED** [review]

**Comment by marcaaron** [comment]
Not sure why this E2E test keeps failing. We may need to merge `master`.

**Pull request merged**
