### PR TITLE
Add modal for existing owners error

### PR DESCRIPTION
**Pull request by jasperhuangg**
### Details
Previously, `setupWithdrawalAccount` would silently error when a user tried to add a withdrawal bank account that we already assigned an owner to. 

This PR adds some text similar to [the text in Web-Secure](https://github.com/Expensify/Web-Secure/blob/2f20e1b0b13b2d09081ecf0986a64a8af4a0a67f/site/app/dialogs/reimbursementAccount/existingCopiesWarning.jsx#L3-L49).

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/169896

### Tests
1. Paste this code block [here](https://github.com/Expensify/App/blob/3ea4b275d6fa885e631a69d6335bc80a46e4f955/src/libs/actions/BankAccounts.js#L600). This'll simulate the server returning with an existingOwners error:
    ```js
    return new Promise(resolve => resolve({existingOwners: ['patrick@expensify.com', 'spongebob@expensify.com', 'sandy@expensify.com']})).then((response) => {
        const existingOwnersList = response.existingOwners.reduce((ownersStr, owner, i, ownersArr) => {
            let separator = ',\n';
            if (i === 0) {
                separator = '\n';
            } else if (i === ownersArr.length - 1) {
                separator = ' and\n';
            }
            return `${ownersStr}${separator}${owner}`;
        }, '');
        Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {loading: false, error: CONST.BANK_ACCOUNT.ERROR.EXISTING_OWNERS, existingOwnersList});
    });
    ```
2. Navigate to the add bank account flow for a workspace. 
3. Verify that you're unable to add the account since the bank account already has an existing owner, and verify that the error step displays (see screenshots).

### QA
1. Create a new workspace and click "Get Started".
2. Add a bank account manually following the steps [here](https://stackoverflow.com/c/expensify/questions/342).
3. In a different account, follow steps 1 and 2.
4. Verify that you're unable to add the account since the bank account already has an existing owner, and verify that the error step displays (see screenshots).

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

#### Web
Screen Shot 2021-07-20 at 5 40 26 PM

#### Desktop
Screen Shot 2021-07-20 at 5 40 43 PM

#### Mobile-Web
Screen Shot 2021-07-20 at 5 41 35 PM

#### iOS
Screen Shot 2021-07-20 at 5 40 54 PM

### CODE REVIEW

**Comment by shawnborton** [comment]
Maybe we don't need that extra padding around the inner message?

**Comment by jasperhuangg** [comment]
@shawnborton Removed the padding, let me know if there's anything else that catches your eye!

**Review by shawnborton — DISMISSED** [review]

**Review by luacmartins — APPROVED** [review]
LGTM!

**Comment by isagoico** [comment]
@jasperhuangg While testing this, I noticed only 2 of the current users of the Bank account are displayed. I wanted to verify if there are any limits to how many users are displayed in the modal. For the account I just tried it has a LOT of active owners, that's why I found it weird that only 2 were displayed. 

image

**Comment by jasperhuangg** [comment]
@isagoico I'm honestly not too sure about this. The code in this PR simply handles displaying the modal with information that was already retrieved from the API. I'll reach out to @marcaaron and ask about this.

**Comment by isagoico** [comment]
Oh sure, the we could open a separate issue for this and check the PR off since the modal is correctly displayed right?

**Comment by roryabraham** [comment]
I'm going to check this off on the checklist and run the production deploy. @isagoico Can you create a follow-up issue please? 🙏

**Comment by marcaaron** [comment]
>For the account I just tried it has a LOT of active owners, that's why I found it weird that only 2 were displayed.

I honestly also have no idea about this but it sounds like something we should have followed up on.

**Pull request merged**
