### PR TITLE
Fix - Reduce the haptic feedback vibration to a short bip

### PR DESCRIPTION
**Pull request by rushatgabhane**
cc: @Jag96 Creating a draft PR. Looking forward for your feedback!
### Details

This PR removes `react-native-unimodules` and `expo-haptics` as they aren't required anymore.

Now that my PR is merged into `react-native-haptic-feedback`, we can use it directly instead of Expensify's fork.

Use the lib [`junina-de/react-native-haptic-feedback`](https://github.com/junina-de/react-native-haptic-feedback) for haptic feedback.

#### Android
Create a new file: components/PressableWithSecondaryInteraction/index.android.js
Call `ReactNativeHapticFeedback.trigger('effectHeavyClick');` for a long press.
#### iOS
Create a new file: components/PressableWithSecondaryInteraction/index.ios.js
Call `ReactNativeHapticFeedback.trigger('selection');` for a long press.
### Fixed Issues

$ https://github.com/Expensify/App/issues/4355

### Tests / QA

1. Navigate to a conversation on mobile (iOS, Android).
2. Long press on a message.
3. Verify that the haptic feeback is same as slack's long press on a message.

### Tested On
- [x] iOS
- [x] Android

### Screenshots
Not Applicable

### CODE REVIEW

**Comment by rushatgabhane** [comment]
All checks have passed!

**Review by Julesssss — CHANGES_REQUESTED** [review]
I'm getting a crash on Android 8.1:

```
Error when loading lib: dlopen failed: library "libjsc.so" not found lib hash: eae0e884bac6a338b8c53618b45e2515 search path is /data/app/com.expensify.chat-4zdOjJAUwAHOSjq0TXDQ8Q==/lib/arm64
2021-10-26 11:36:08.075 16636-16636/com.expensify.chat W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
2021-10-26 11:36:08.076 16636-16636/com.expensify.chat W/System.err:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:384)
2021-10-26 11:36:08.077 16636-16636/com.expensify.chat W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
2021-10-26 11:36:08.077 16636-16636/com.expensify.chat W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:50)
2021-10-26 11:36:08.077 16636-16636/com.expensify.chat W/System.err:     at com.facebook.soloader.ApplicationSoSource.loadLibrary(ApplicationSoSource.java:89)
```

device-2021-10-26-114021

**Review by Jag96 — COMMENTED** [review]
Tested on my physical iPhone and the 500ms matches slack exactly 👍

**Review by Julesssss — APPROVED** [review]
Tests well on Android, the vibration pattern matches slack.

I requested one minor change, but once that's done I think we're good to merge 👍

**Review by Julesssss — CHANGES_REQUESTED** [review]
Nnoticed a few small things to change

**Review by Julesssss — APPROVED** [review]
Confirmed the vibration pattern matches on Android.

**Review by Jag96 — APPROVED** [review]
LGTM, great work on this!

**Pull request merged**
