### PR TITLE
Remove default payment method for paypal

### PR DESCRIPTION
**Pull request by mdneyazahmad**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7518

### Tests

1. Goto settings -> Payments -> Paypal
2. Click on a already added paypal method
3. Verify that there is no set default payment button for it
- [x] Verify that no errors appear in the JS console

### QA Steps

1. Goto settings -> Payments -> Paypal
2. Click on a already added paypal method
3. Verify that there is no set default payment button for it
4.  Verify that other payment method can be selected as default method
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

web

#### Mobile Web

mweb

#### Desktop

desktop

#### iOS

ios

#### Android

android

### CODE REVIEW

**Review by rushatgabhane — APPROVED** [review]
@puneetlath LGTM! 🎉️ and tests well on all platforms.

**Comment by puneetlath** [comment]
@mdneyazahmad let's add to the QA steps to make sure that other payment methods can still be removed.

**Review by puneetlath — APPROVED** [review]

**Comment by mdneyazahmad** [comment]
@puneetlath updated the steps

**Comment by SumitDiyora** [comment]
**Issue 1 -**

**Title**- [Medium]: Chrome+Jaws: Screen reader: Role is not defined for Paypal A/c.
**Actual** - When focus lands on the Paypal A/c, screen reader is reading "Paypal.me testetstes(A/c name)", not read the role for the A/c.
**Expected** - Role should be define as a 'button' for the paypal a/c and screen reader should read like "Paypal.me testetstes".
**WCAG failure -** 4.1.2
**Reproducible in staging?**: - Yes
**Version Number:** - v1.1.39-3
**Platforms** - Web, Desktop, Mobile-web, iOS

**Note** - Due to installation of build not able to check on 'Android'.

https://user-images.githubusercontent.com/98817464/157312433-ad0baf44-4fec-42fb-b1b5-16c8a8553a6f.mp4

**Issue 2-**

**Title**- [Medium]: Chrome+Jaws: Keyboard Navigation: Order is not sequential on 'Delete dialogue'
**Actual** - After opening the dialogue first focus lands on the Cancel control then it's moved to delete control.
**Expected** - Focus should first land on the 'Delete' control then should land on the 'Cancel'.
**WCAG failure** - 2.4.3
**Reproducible in staging?**: - Yes
**Version Number**: - v1.1.39-3
**Platforms** - Web, Desktop

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/98817464/157313551-ac3cf7de-4238-4d2d-b83d-041aef34035d.mp4

**Issue 3 -**

**Title**- [Medium]: Chrome +Jaws : Screen reader : Role is not defined for 'Delete' control.
**Actual** - When focus lands on the Delete control, screen reader is reading "Delete", not read the role.
**Expected** - Role should be define as 'button' and screen reader should read like "Delete button".
**WCAG failure** - 4.1.2
**Reproducible in staging?**: - Yes
**Version Number:** - v1.1.39-3
**Platforms** - Web, Mobile-web, iOS

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/98817464/157314617-44a71c98-559e-4938-bcba-15d1528f93c9.mp4

**Issue 4 -**

**Title**- [Medium]: Chrome +Jaws : Screen reader : Screen reader is not reading the Dialogue information.
**Actual** - After select the delete control, screen reader is reading "Cancel", not read the 'Are you sure...".
**Expected** - Screen reader should read like "Are you sure that you want to delete this account?, cancel button".
**WCAG failure** - 1.3.1
**Reproducible in staging?:** - Yes
**Version Number:** - v1.1.39-3
**Platforms** - Web

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/98817464/157315896-17c7fade-1469-42be-b12d-619d91d41b23.mp4

**Pull request merged**
