### PR TITLE
Add priority mode setting to Onyx

### PR DESCRIPTION
**Pull request by marcaaron**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
This is a prep PR and will be next passed to someone else to set up the UI for the setting described in the linked issue. 

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/153252

### Tests
1. There are no real QA steps just make sure the app is still building.
2. Check localStorage and verify the new onyx key exists
Screen Shot 2021-02-10 at 10 10 17 AM

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Review by tgolen — APPROVED** [review]

**Comment by quinthar** [comment]
I'm not quite following -- what is the "priorityMode"?

**Comment by marcaaron** [comment]
NVP for the sidebar priority settings. I thought maybe `gsd` mode might apply to other things so didn't want to get too specific. Can change it up if there's a better name for this to use.

**Comment by quinthar** [comment]
Why is it called "priority"?  Maye "viewMode" or "sortMode"?

**Comment by marcaaron** [comment]
Thought priority made sense because we are prioritizing things. But we can go with whatever you like and I'll add it to the next issue.

**Comment by quinthar** [comment]
What are we calling the setting externally; how is it presented to the user?

**Comment by marcaaron** [comment]
@quinthar This is still being discussed in the issue if you wanna leave any thoughts there -> https://github.com/Expensify/Expensify/issues/153252#issuecomment-777376502

**Pull request merged**
