### PR TITLE
Cross-platform Live-Update JS

### PR DESCRIPTION
**Pull request by roryabraham**
@tgolen @AndrewGable  Will you please review this?

cc @quinthar 

### Fixes issues:
~~https://github.com/Expensify/ReactNativeChat/issues/256~~
~~https://github.com/Expensify/ReactNativeChat/issues/257~~

$ https://github.com/Expensify/Expensify/issues/141663

### Main Details:
- Introduces a JS utility which periodically checks for updates executes platform-specific update code if there is a network connection.
    - On web, it will also check for updates (and optionally refresh) when the page is minimized/hidden. That allows us to silently update, reducing interruptions for the user.
- Each platform must provide it's own platform-specific instructions on how to update.
    - On web (`index.js`), this is a simple refresh
    - On electron (`main.js`), we can use `autoupdater.checkForUpdatesAndNotify`
    - iOS/Android as-yet TBD
- Writes a version file to the web server during production builds

### Bonus/Cleanup:
- Creates a `download` and `isOnline` network utility
- Create a `getDisplayName` utility for components (useful in HOC's)

### CODE REVIEW

**Review by tgolen — CHANGES_REQUESTED** [review]
I know it's only a WIP, so I'll just comment on some high-level stuff at this point.

You did this right with `index.native.js` being the no-op 👍  so you are good there.

I'm actually thinking at this point that this should NOT be an HOC, and let me give you my reasoning:
1. Most of the stuff that is being done in the HOC is normally what would be done inside of an Action (making XHRs, setting and getting things from Ion, etc.)
1. By not having this logic in an Action, it's breaking away from the data flow of an app (be sure to read the first three points of the "philosophy" on the [readme](https://github.com/Expensify/ReactNativeChat#philosophy))

Here is what I would suggest.

1. Make this just a normal component, not a HOC, with a no-op for native.
1. Render it in `HeaderView.js` (because that is more than likely where we will tell the user to refresh)
1. Rename it to something like `<RefreshAppSuggestor />` (hahaha, maybe not the best name)
1. Create `lib/actions/AppVisibility.js` that exports an `init()` method, which is called from `componentDidMount` of `RefreshAppSuggestor`.
1. The action will set a value in Ion for `app_shouldRefresh` (initially set to false)
1. Now listen for visibility changes on the window, and setup polling mechanism for checking the hash in the file
1. Whenever the hash changes, set `app_shouldRefresh` to true in Ion (if document is not visible, then just refresh right there)
1. Connect `RefreshAppSuggestor` to Ion using the `withIon` HOC.
1. When `app_shouldRefresh` is true (this will be in the `state` of `RefreshAppSuggestor`), display the message to the user to refresh

I hope that makes sense!

**Review by tgolen — CHANGES_REQUESTED** [review]
OK, thanks for your reasoning about the HOC. I think it's a bit strange to have a HOC that's only applied to a single component, and in that case, I think I would prefer the functionality to just be placed directly into the component. Otherwise, it's just abstracting functionality to a different component with no value.

**Review by marcaaron — COMMENTED** [review]
This is maybe outside the scope of your efforts here (which are really great!) but I think wherever possible we should try to come up with a simple solutions for now that do not depend on `Ion` unless it has some relevance to React.

Here's what I'd propose...

1. Continue to use Ion to store the version hash
1. Move the logic from the HOC into a simple JS module (use the `.js/.native.js` extensions)
1. Export an `init` method (and a noop one for mobile version)
1. Think about what actually need to go in `Ion` and what doesn't - I'm pretty sure it's just the version hash at this point. Everything else can be contained in just one file.

**Review by marcaaron — CHANGES_REQUESTED** [review]
Left a lot of small comments (mostly style/RNC questions) but some big ones. The biggest questions I have are...

- What else needs to be done here? (API command looks empty)
- Are we going to save the version after we fetch it from the API? I noticed a few places where we're probably passing `undefined`

**Review by tgolen — COMMENTED** [review]
@roryabraham I wanted to answer a couple of the questions you posted in your last comment.

> In dev, the dist folder is deleted with every hot-reload, so that's why we have to manually create the file

I think we should just disable the refreshing when we are doing local development. The webpack hot module loading will take care of everything we need, so I don't think it's necessary to do anything with the version file in local development.

> It would be pretty easy to create a download utility in Network.js

Yep, I think this is fine. We eventually want to split out `Network.js` into a separate `API.js` so that `Network.js` would then be just a utility module instead of doing business logic (I think @cead22 is working on that).

**Review by tgolen — COMMENTED** [review]
I like this!

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
