### PR TITLE
fix multiline textInput height on app

### PR DESCRIPTION
**Pull request by thesahindia**
### Details

Fixed the increasing height of multiline textInput on close account page.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7738

### Tests

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I verified the PR has a small number of commits behind `main`
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [ ] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I added comments when the code was not self explanatory
    - [ ] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [ ] I followed proper naming convention for platform-specific files (if applicable)
    - [ ] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
    - [ ] I followed the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs))
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I corroborated the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If I created a new component I verified that a similar component doesn't exist in the codebase

#### PR Reviewer Checklist
- [ ] I verified the PR has a small number of commits behind `main`
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [ ] If a new component is created I verified that a similar component doesn't exist in the codebase

### QA Steps

1. Navigate to settings>security>close account
2. Add multiline text to fill the textInput so that it becomes scrollable
3. Check the height of the textInput stays the same
- [x] Verify that no errors appear in the JS console

#### Web

Screenshot 2022-03-07 at 12 40 01 AM

#### Mobile Web

Screenshot 2022-03-07 at 12 24 55 AM

#### Desktop

Screenshot 2022-03-07 at 12 20 27 AM

#### iOS

https://user-images.githubusercontent.com/83179295/156938355-7759c1da-d6c7-47fa-a0f7-07c75f3700fe.mov

#### Android

https://user-images.githubusercontent.com/83179295/156938322-4ba223b3-bfd0-4313-8454-5fd45418cdb9.mov

### CODE REVIEW

**Comment by rushatgabhane** [comment]
#### PR Reviewer Checklist
* [ ]  I verified the PR has a small number of commits behind `main`
* [ ]  I verified the correct issue is linked in the `### Fixed Issues` section above
* [ ]  I verified testing steps are clear and they cover the changes made in this PR
  
  * [ ]  I verified the testing environment is mentioned in the test steps
* [ ]  I verified testing steps cover success & fail scenarios (if applicable)
* [ ]  I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
* [ ]  I verified tests pass on **all platforms** & I tested again on:
  
  * [ ]  iOS / native
  * [ ]  Android / native
  * [ ]  iOS / Safari
  * [ ]  Android / Chrome
  * [ ]  MacOS / Chrome
  * [ ]  MacOS / Desktop
* [ ]  I verified there are no console errors related to changes in this PR
* [ ]  I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
  
  * [ ]  I verified comments were added when the code was not self explanatory
  * [ ]  I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
  * [ ]  I verified proper naming convention for platform-specific files was followed (if applicable)
  * [ ]  I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
  * [ ]  I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
* [ ]  I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
* [ ]  I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
* [ ]  I verified the UI performance was not affected (the performance is the same than `main` branch)
* [ ]  If a new component is created I verified that a similar component doesn't exist in the codebase

**Comment by rushatgabhane** [comment]
> Check the height of the textInput stays the same

@thesahindia could you please add a step before this which explains what can change height of the textinput?

**Review by rushatgabhane — APPROVED** [review]
@deetergp LGTM!

**Review by deetergp — APPROVED** [review]
LGTM 👍

**Pull request merged**
