### PR TITLE
Updating the CONTRIBUTING.md file to include #expensify-bugs guidance

### PR DESCRIPTION
**Pull request by michaelhaxhiu**
cc @JmillsExpensify @mallenexpensify 

### Details

- Updated all guidance to embody the new world of Bug vs New Feature
- Re-worked the `Ask Questions` header to be `Slack Channels`
- Added guidance on #expensify-bug channel throughout
- Cleaned up verbiage in some areas as I went through this, mainly for the sake of clarity

### Fixed Issues
https://github.com/Expensify/Expensify/issues/240113

### CODE REVIEW

**Comment by michaelhaxhiu** [comment]
Hold on this please - need to get other changes ready before this is deployed to the production file.

**Comment by Julesssss** [comment]
Sure, just ping me when it's ready for review 👍

**Review by dylanexpensify — COMMENTED** [review]
Line 28: For discussing the difference of use-case behind each room, it isn't clear if _discussing_ issues around bugs would be in the bug channel or the open source channel since it says it's only for reporting.

Line 49: A job may be fixing a bug or working on a new feature. (take it or leave it, I just think that sounds better)

Line 55: is the identifying bug payment only if they propose a solution? I thought not. Also, "If the bug or feature is fixed by a PR that is not associated with your proposal, the contributor is not eligible for compensation unless they can find the PR that fixed it and prove their porposal preceded the one associated with the PR." to "If the bug or feature is fixed by a PR that is not associated with your proposal, then you will not be eligible for the associated compensation unless you can find the PR that fixed it and that yours preceded that one."

**Comment by michaelhaxhiu** [comment]
@dylanexpensify 

>Line 28: For discussing the difference of use-case behind each room, it isn't clear if discussing issues around bugs would be in the bug channel or the open source channel since it says it's only for reporting.

Fixed!

>Line 49: A job may be fixing a bug or working on a new feature. (take it or leave it, I just think that sounds better)

Updated!


>Line 55: is the identifying bug payment only if they propose a solution? I thought not. Also, "If the bug or feature is fixed by a PR that is not associated with your proposal, the contributor is not eligible for compensation unless they can find the PR that fixed it and prove their porposal preceded the one associated with the PR." to "If the bug or feature is fixed by a PR that is not associated with your proposal, then you will not be eligible for the associated compensation unless you can find the PR that fixed it and that yours preceded that one."

`Line 55: is the identifying bug payment only if they propose a solution?` -- what do you mean @dylanexpensify? Can you expand this a little more?

`If the bug or feature is fixed by a PR that is not associated with your proposal, then you will not be eligible for the associated compensation unless you can find the PR that fixed it and that yours preceded that one.`

Added!

**Comment by dylanexpensify** [comment]
Ah yeah, so line 55 basically makes it seem like you have to report the bug and propose a solution to get the reporting bonus, but to my knowledge I thought they could just report the bug and get the bonus and not need to provide a potential solution!

**Review by nathanmetcalf — APPROVED** [review]

**Comment by michaelhaxhiu** [comment]
Thanks for no scoping this PR @nathanmetcalf 🎯.

**Comment by Julesssss** [comment]
@michaelhaxhiu is this still on hold?

**Review by Julesssss — APPROVED** [review]

**Comment by michaelhaxhiu** [comment]
Yes still on hold while Slack support gives us hell 🔥

**Comment by michaelhaxhiu** [comment]
Let's do this thing now, just got unblocked and ready to proceed.

**Comment by michaelhaxhiu** [comment]
It's live

**Pull request merged**
