### PR TITLE
Remove unneded SSH key

### PR DESCRIPTION
**Pull request by AndrewGable**
@Jag96 - Please review

### Details
Now that all our dependencies are open source we no longer need an ssh key to install npm packages.

### Fixed Issues
N/A

### Tests
1. Verify GitHub actions pass

### CODE REVIEW

**Comment by AndrewGable** [comment]
@rafecolton - Can you delete the `SSH_PRIVATE_KEY` secret once this is merged? Thanks!

**Comment by rafecolton** [comment]
Sure thing

**Review by rafecolton — APPROVED** [review]

**Comment by rafecolton** [comment]
Secret deleted

**Comment by AndrewGable** [comment]
🙏 Thank you!

**Pull request merged**
