### PR TITLE
fix arrow focus priority when multiple arrow listeners are subscribed

### PR DESCRIPTION
**Pull request by azimgd**
### Details

Fixes keyboard arrow navigation in the list if open "new chat". Keyboard arrow listeners priority was reset to highest value.

Key priority was initially lowered (to 1), to disable arrow up / down events from triggering when KeyboardShortcutsModal is open. https://github.com/Expensify/App/pull/18425 has updated event subscription approach to event lifecycle hence we need to reset it back to highest priority when new modal is opened.

### Fixed Issues

$ https://github.com/Expensify/App/issues/18516
PROPOSAL: https://github.com/Expensify/App/issues/18516

### Tests

- [x] Verify that no errors appear in the JS console

1. Click on "+" FAB menu icon
2. Click on "New chat"
3. Press CMD+K
4. Press up/down arrows keys in the keyboard to navigate in the chat list

---

1. Go to a chat
2. Type something
3. Press "SHIFT + ENTER"
4. Verify that a new line was added
5. Verify that you can move the cursor up and down by pressing arrow and down keys

---

1. Open "Create Group" modal by pressing CMD+SHIFT+K
2. Open "Keyboard shortcuts" modal by pressing CMD+J
3. Pressing Enter should first close "Keyboard shortcuts" modal, pressing enter again should select members on "Create Group" list
4. Open "Send Money" modal
5. Open "Keyboard shortcuts" modal by pressing CMD+J
6. Pressing Enter should first close "Keyboard shortcuts" modal, pressing enter again submit form on "Send Money" modal

### Offline tests

Same as tests.

### QA Steps

- [x] Verify that no errors appear in the JS console

Same as tests.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by Beamanator** [comment]
@azimgd thanks for the quick fix! However we want to make sure this doesn't break the other related PRs:
- https://github.com/Expensify/App/pull/18425
- https://github.com/Expensify/App/pull/18273

So can you make sure to test that those still work, and add the tests from those PRs here? 🙏

**Comment by Beamanator** [comment]
@mollfpr tagging you in as C+ since I know you're available now & we want to get this deploy blocker fixed quick 👍

**Comment by mollfpr** [comment]
@azimgd I found another issue related to `Enter` key pressed on the new group chat selection is submitting the form. I remember this issue was already resolved in your PR previously, but it's raised again.

Step:
1. Open search page with command or click on the search icon
2. Open new group chat page with command CMD+Shift+K
3. Press enter

It's not selecting the option.

https://user-images.githubusercontent.com/25520267/236844394-95d61331-2d20-4b0a-99fb-0f9a928cc0a3.mov

**Comment by azimgd** [comment]
@mollfpr could you have a look again please.

**Comment by mollfpr** [comment]
It's fixing the previous issue and the OP issue, but I'm able to use the arrow key in the new group chat page and can't close the keyboard shortcut modal after refreshing the page.

https://user-images.githubusercontent.com/25520267/236847888-0d289e78-31cb-474e-875b-dbbbfe9af043.mov

**Comment by azimgd** [comment]
That only happens if you refresh the page, correct?

**Comment by Beamanator** [comment]
> I suggest that we don't persist the state of visibility for KeyboardShortcutsModal hence refreshing will not show it, which makes most sense for me.

This makes the most sense to me, but I'll try to check in with people who implemented that

**Comment by aldo-expensify** [comment]
> I suggest that we don't persist the state of visibility for `KeyboardShortcutsModal` hence refreshing will not show it, which makes most sense for me.

Removing that state from Onyx makes sense to me. I don't know why we would like to keep it open if the user refresh the page.
This is the PR that added this modal: https://github.com/Expensify/App/pull/6833

@roryabraham , do you know why we put the state `ONYXKEYS.IS_SHORTCUTS_MODAL_OPEN` in Onyx and not in a local state of the component? (just asking you because you are assigned to this [issue](https://github.com/Expensify/App/issues/6660))

**Comment by Beamanator** [comment]
Boom we're in agreement that the modal's visibility doesn't need to persist 💪

**Comment by aldo-expensify** [comment]
Moved the commits to this PR: https://github.com/Expensify/App/pull/18599 so we can continue. cc @mollfpr we will need your review there :)

**Pull request closed without merging**
