### PR TITLE
Fixed no result found after selecting a address from the drop-down menu

### PR DESCRIPTION
**Pull request by shubham1206agra**
### Fixed Issues

$ https://github.com/Expensify/App/issues/25595
PROPOSAL: https://github.com/Expensify/App/issues/25595#issuecomment-1686678383

### Tests

1. Navigate to Settings > Wallet > Add a debit card.
2. Click "Billing address" and start typing any address.
3. Choose an address from the available options.
4. Click "Billing address" again once an address is selected.

- [x] Verify that no errors appear in the JS console
- [x] Verify that once we start typing, we get a loading indicator (or Cargando in Spanish) in step 2
- [x] Verify that after selecting `Billing address` again in step 4, we don't see any `No result found`.

### QA Steps

Same as `Tests`

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/58412969/c22738c6-203a-4184-8e9c-dfcdb477a02c

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/58412969/52b79b98-9375-4940-9af7-737bf0f18c00

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/58412969/c9d93469-0e2b-4182-b8d4-cf1f6e2158ed

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/58412969/8c63fb3a-67b6-47de-aa00-a8b1c6a50a0a

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/58412969/f5d25f89-8ade-4937-92b6-7fdbdb6b6ad4

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/58412969/b16a995f-8046-499f-9b20-546e6e606bb7

</details>

### CODE REVIEW

**Comment by shubham1206agra** [comment]
Unable to test this due to a bug in Android DEV on connecting Plaid

**Comment by shubham1206agra** [comment]
@mananjadhav Can you review this today?

**Comment by mananjadhav** [comment]
@shubham1206agra Apologies I was away for the weekend. I did test, and the Test steps work fine, but this particular case doesn't. 

When I start searching or type only one letter, it momentarily shows `No results found`, before loading the results.

https://github.com/Expensify/App/assets/3069065/8ecda2cc-1c3e-4a67-92bd-8674f6506e1a

I tried figuring out an easy fix but I can't see how. Can you fix it? I am now wondering if @Pujan92's solution of fixing it in the lib would be needed. Will wait for your fix before testing again.

**Comment by shubham1206agra** [comment]
> @shubham1206agra Apologies I was away for the weekend. I did test, and the Test steps work fine, but this particular case doesn't.
> 
> When I start searching or type only one letter, it momentarily shows `No results found`, before loading the results.
> no-results-found.mov
> 
> I tried figuring out an easy fix but I can't see how. Can you fix it? I am now wondering if @Pujan92's solution of fixing it in the lib would be needed. Will wait for your fix before testing again.

@mananjadhav This issue is due to the synchronous nature of API calls in lib. I also checked that @Pujan92's solution did not work for the above issue. I think we should do nothing about this as this may introduce regression in other areas, and it's a minor issue.

**Comment by shubham1206agra** [comment]
@mananjadhav ?

**Comment by mananjadhav** [comment]
@AndrewGable Can you please check this [case](https://github.com/Expensify/App/pull/27035#issuecomment-1713059493) and confirm if this is fine?

**Comment by AndrewGable** [comment]
Does this happen on the existing build?

**Comment by mananjadhav** [comment]
Yes it does @AndrewGable

**Comment by AndrewGable** [comment]
It would be really nice to fix this, how complex would the solution be?

**Comment by shubham1206agra** [comment]
> It would be really nice to fix this, how complex would the solution be?

It will require patching upstream, with not so sure solution. I think we should directly open upstream PR for this as patching locally might create some problems.

**Comment by mananjadhav** [comment]
@AndrewGable Our current approach won't work, and then we'll have to fix it upstream. I won't say it is complex, the idea is to expose the props while the API is being fetched.

**Comment by AndrewGable** [comment]
We have our own fork so fixing upstream seems like just as easy to fix it the "right" way as this PR. I am happy to help make sure it is deployed correctly, etc.

**Comment by shubham1206agra** [comment]
@mananjadhav Please decide in that case, and if upstream changes are needed, please create a fork so that I can work on that.

**Comment by shubham1206agra** [comment]
Btw we need to fix this issue in short
https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/751

**Comment by mananjadhav** [comment]
Yes @shubham1206agra but the fix will be pushed in this [repo](https://github.com/Expensify/react-native-google-places-autocomplete)

**Comment by shubham1206agra** [comment]
I am gonna close this one and reopen another PR when upstream changes are made

**Comment by shubham1206agra** [comment]
I am gonna reopen this PR. Looks like you also need these changes too!

**Comment by shubham1206agra** [comment]
Please review this PR https://github.com/Expensify/react-native-google-places-autocomplete/pull/7

**Comment by shubham1206agra** [comment]
@mananjadhav You can start testing this PR

**Comment by shubham1206agra** [comment]
@mananjadhav ?

**Comment by shubham1206agra** [comment]
@mananjadhav Are you on leave right now?

**Comment by mananjadhav** [comment]
I was, but I am available now. @shubham1206agra Can you resolve conflicts so that I can finish this today.

**Comment by AndrewGable** [comment]
@mananjadhav - I can review once you are done testing 👍

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
@shubham1206agra The code change is fine, but the Test steps look incomplete.
1. We need to mention what is expected now. For example, `No results found` shouldn't show up. It should now show/not show `Loading` based on the typing/search behavior.
2. We should also mention the spanish translation for Loading in the Test steps.

Also I would recommend keep QA steps as a separate section as per the template. You can copy the tests or mention `same as Test steps`.

**Comment by shubham1206agra** [comment]
> @shubham1206agra The code change is fine, but the Test steps look incomplete.
> 
>     1. We need to mention what is expected now. For example, `No results found` shouldn't show up. It should now show/not show `Loading` based on the typing/search behavior.
> 

Ok I will update this

>     2. We should also mention the spanish translation for Loading in the Test steps.
> 

I didn't get this. Can you help me here?

> 
> Also I would recommend keep QA steps as a separate section as per the template. You can copy the tests or mention `same as Test steps`.

Ok

**Comment by mananjadhav** [comment]
@shubham1206agra I found one minor UI issue. The loader resets when you keep typing/deleting characters. This shows the loading icon keeps jumping.

**Steps to reproduce**
1.  On the address field, keep typing the characters OR
2. Type a very long string and then keep deleting the characters one by one
3. Notice the loader resets (essentially meaning, keeps reloading).

https://github.com/Expensify/App/assets/3069065/d4c9d8ea-88c6-4357-9da9-e7e0df758f7f

**Comment by shubham1206agra** [comment]
Should I remove the loader?

**Comment by mananjadhav** [comment]
@shawnborton Do we want a loader here? or we can keep a text only `Loading...` for this one?

**Comment by mananjadhav** [comment]
> 2. We should also mention the spanish translation for Loading in the Test steps.

What I meant is add a test step that when the language is Spanish it should show `Cargando`

**Comment by shubham1206agra** [comment]
Meanwhile, I will try to fix this if I can

**Comment by shubham1206agra** [comment]
> > 2. We should also mention the spanish translation for Loading in the Test steps.
> 
> What I meant is add a test step that when the language is Spanish it should show `Cargando`

I have updated the Tests

**Comment by shubham1206agra** [comment]
I found another bug which fixed the loader

**Comment by shawnborton** [comment]
I feel like we can get rid of the text and only use the loading spinner, but we should vertically and horizontally center the spinner. cc @Expensify/design

**Comment by shubham1206agra** [comment]
I will wait on https://github.com/FaridSafi/react-native-google-places-autocomplete/pull/913 to be merged

**Comment by mananjadhav** [comment]
@shubham1206agra Did you get a chance to look at @shawnborton's comment? I think we want the wrapper to be equal to the width of the input (or the list items). No text and only spinner.

**Comment by shubham1206agra** [comment]
I thought @shawnborton is verifying this with Design team. 
@shawnborton What should be the ideal UI?
Can you clarify?

**Comment by shawnborton** [comment]
I think we're all good to move forward with just vertically and horizontally centering the loading spinner, no need for a text label.

**Comment by shubham1206agra** [comment]
@mananjadhav Please complete the checklist now

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/3069065/5ff04b4f-10f1-4d0f-bc69-7944cdd4a337

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/3069065/3bdffcfb-5a78-4368-ab47-573efb25b7bf

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/3069065/b542d8e7-11c8-4f73-874d-41e03197342e

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/3069065/e953ea59-d6b5-4621-8c08-dab26cd418a4

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/3069065/98d67463-687c-4cac-891d-a2a3111e38c5

</details>



------

Thanks @shubham1206agra for the changes. This looks better. Thank you for taking this to the finish line. @AndrewGable All  yours.

**Comment by mananjadhav** [comment]
@shubham1206agra 

Okay I noticed one thing on Android, intermittently, I got two console errors. Can you please check

Screenshot 2023-10-04 at 12 12 38 AM

Screenshot 2023-10-04 at 12 12 24 AM

**Comment by shubham1206agra** [comment]
> @shubham1206agra 
> 
> Okay I noticed one thing intermittently, I got two console errors. Can you please check. I think we're only left with this.
> 
> Screenshot 2023-10-04 at 12 12 38 AM
> 
> Screenshot 2023-10-04 at 12 12 24 AM
> 

This is another bug with the library
Can we create a separate ticket for the same?
Cause this is not really related to this

**Comment by mananjadhav** [comment]
Yeah not directly related to the change here, but good to fix. I'll let @AndrewGable decide.  All good from my side.

🎀 👀 🎀 C+ reviewed.

**Review by AndrewGable — APPROVED** [review]

**Comment by AndrewGable** [comment]
Tests were still running I guess, not emergency.

**Comment by shubham1206agra** [comment]
@AndrewGable Can you create an issue for this?
https://github.com/Expensify/App/pull/27035#issuecomment-1745527145

**Comment by AndrewGable** [comment]
I'd report these via #expensify-bugs Slack channel

**Pull request merged**
