### PR TITLE
Update CLA assistant to check for newlines/spaces

### PR DESCRIPTION
**Pull request by Jag96**
cc @AndrewGable 

### Details
This PR updates the CLA assistant to include https://github.com/cla-assistant/github-action/pull/69 and includes the changes from https://github.com/cla-assistant/github-action/issues/57#issuecomment-764472530.

### Tests
I've removed myself from the CLA json, will test in comments.

### CODE REVIEW

**Comment by Jag96** [comment]
recheck

**Comment by Jag96** [comment]
recheckcla

**Comment by Jag96** [comment]
recheckcla

**Comment by Jag96** [comment]
recheckcla

**Comment by Jag96** [comment]
recheckcla

**Comment by Jag96** [comment]
recheck

**Comment by Jag96** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jag96** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jag96** [comment]
recheck

**Review by AndrewGable — APPROVED** [review]

**Comment by AndrewGable** [comment]
Looks great! Thank you

**Pull request merged**
