### PR TITLE
Send isViaExpensifyCash param for two API commands

### PR DESCRIPTION
**Pull request by AndrewGable**
@stitesExpensify - Please review
cc @tgolen 

### Details
Web PR: https://github.com/Expensify/Web-Expensify/pull/29961

Sends required parameter to API commands `GetAccountStatus` and `User_SignUp`

### Fixed Issues
Fixes 2FA not working for Expensify users on login via mobile clients

### Tests
Must checkout https://github.com/Expensify/Web-Expensify/pull/29961 first!
On each platform (**especially iOS/Android**):
1. Delete app
2. Install fresh version of app
3. Sign in with an account via 2FA
4. Verify you see no errors

### CODE REVIEW

**Review by stitesExpensify — APPROVED** [review]

**Review by tgolen — COMMENTED** [review]
Thanks for this change! Makes sense in retrospect. I wonder though if we should be using a parameter more like `referer: 'expensify.cash'` and add it to every request? That could be pretty scalable and easier to work with down the road. We already use `Request::getReferer()` in web-e in a few places so I think this would make the API layer more consistent. Thoughts?

**Comment by stitesExpensify** [comment]
That makes sense to me that we would just add it to every request. We did this because we were just looking at what the requests were currently sending and Android was pretty much useless haha

**Comment by AndrewGable** [comment]
So I have struggled with this in the past, but I thought there was some security built into `fetch` that didn't allow the `referer` header to be sent? e.g. https://javascript.info/fetch-api#referrer-referrerpolicy This is getting into CORS territory which I still don't totally understand. Does this mean we need to tweak the `referrerPolicy` sent to the client from our API, then we'd be able to send the `referer` http header?

**Comment by tgolen** [comment]
Sorry, I didn't mean we set the `referer` in the header (that would be akin to spoofing the header which is probably what `fetch` has issues with). I meant to just set `referer` in the body of the request. That should work fine with web-e since it's just referencing `$_REQUEST['referer']`.

**Comment by AndrewGable** [comment]
Ah that makes total sense! 👍

**Comment by AndrewGable** [comment]
Issue for myself here: https://github.com/Expensify/Expensify/issues/149347

**Pull request merged**
