### PR TITLE
Comment box resizing after writing multiline comment

### PR DESCRIPTION
**Pull request by sketchydroide**
The comment box was not being resized after a message was written and sent.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/143303

### Tests (Mobile, Web and Desktop)
1. Write a multiline comment on any chat
1. Verify that the comment box is Cleared and the size returns to the 1 line default size at the same time.

### CODE REVIEW

**Review by madmax330 — DISMISSED** [review]
LGTM all yours @AndrewGable

**Review by AndrewGable — DISMISSED** [review]
Tests well! Added @marcaaron as a final reviewer to double check some JS stuff that I don't know as well.

**Review by marcaaron — CHANGES_REQUESTED** [review]
Hmm I don't really like how we are adding an instance method to `TextInputFocusable`. This is something that I have tried _really_ hard to get people to stop doing.

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Review by marcaaron — APPROVED** [review]
LGTM

**Pull request merged**
