### PR TITLE
Upgrade react-native-document-picker to 5.1.0

### LINKED ISSUE #3543: [HOLD for payment 21 June]  iOS - Attachment picker flickers and unable to select for choose document
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Attachment picker displayed and user able to select attachment

## Actual Result:
Attachment picker flickers and unable to choose any document

## Action Performed:
1. Launch the app and login
2. Choose any chat from LHN
3. Tap the + > Add Attachment > Choose Document

## Workaround:
Unknown 

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.67-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/44479856/121675329-8e486d00-cab3-11eb-8eda-cd51930f48a6.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by roryabraham**
cc @marcaaron @cead22 

### Details
Not sure why, but this does seem to resolve the issue for me.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/3543

### Tests / QA Steps
1. Hit the `+`, then select `Upload Attachment`
2. Then choose `Choose Document`
3. Verify that the document picker opens and that you can choose and upload a document.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web
image

image

#### Desktop
image

#### iOS
image

image

image

#### Android
image

image

### CODE REVIEW

**Comment by roryabraham** [comment]
All three of my reviewers are likely out for the day, and I'd like to get this reviewed and merged ASAP because it resolves a deploy blocker.

**Comment by marcaaron** [comment]
Testing now @roryabraham

**Review by cead22 — APPROVED** [review]

**Review by marcaaron — APPROVED** [review]
Wasn't able to repro on the following:

Simulator (iPhone 12/iOS 14.5)
Android (Galaxy S8 - physical)
iPad mini 2 (iOS 12.5.1 - physical)

:shipit: ❓

**Comment by roryabraham** [comment]
:shipit:

**Comment by Julesssss** [comment]
Thanks for prioritising this!

**Pull request merged**
