### PR TITLE
Do not select participant in IOU confirmation list

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
Prevents the `focusedIndex` being set to 0 when the `IOUConfimationList` component updates

### Fixed Issues
$ https://github.com/Expensify/App/issues/14441

### Tests
1. Open the App in 2 sessions logged in to the same account
2. In session A, navigate to `+ > Request money/Send money > Enter Amount > Select participant > Confirmation page`
3. In session B, navigate to `Settings > Preferences` and change the selected language
4. In session A, verify that the selected participant is not highlighted

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as tests.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/22219519/214184633-def17180-5c98-46f0-9406-64c495a56fc9.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/22219519/214184678-c4dedbf0-4e79-416b-b759-bcae358e5d86.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/22219519/214184704-05a668f8-83f8-4fe6-8bff-22156762adfb.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/22219519/214184719-c213b765-5633-4db5-a943-433b3f6f46a5.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/22219519/214184723-85d2f417-8f7d-48fc-aa54-30fd273de8f6.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/22219519/214184730-e3e88c56-16ff-409e-9663-fc6f7fe7caa6.mov

</details>

### CODE REVIEW

**Comment by luacmartins** [comment]
@parasharrajat if it helps, the only place that passes the `shouldTextInputAppearBelowOptions` prop is the `IOUConfirmationList` page, so this shouldn't affect any other pages.

**Comment by luacmartins** [comment]
`newOptions` shows all available options in the page, whereas `selectedOptions` only shows the option we "selected" in cases where we can select multiple participants like in Group chat or Split bill.

So in the context of the` IOUConfirmPage` it will be the same for `SplitBill` since we can select multiple participants, but for other flows e.g. `Request money` selected participants will be an empty array since we can't "select" multiple participants.

You can see them in the images below:

Split bill
Screenshot 2023-01-25 at 1 22 21 PM

Request money
Screenshot 2023-01-25 at 1 21 39 PM

**Comment by aldo-expensify** [comment]
@luacmartins the change works and seems somewhat consistent with what we do with the index in this other line:


I don't fully understand why this code makes sense, can you add a comment explaining?

Did you consider another option like "disable highlights if the options are disabled"? In this case, you can't click on the options, they are just there for display, prop `isDisabled` is set to `true`. I think it could make sense and be more intuitive just to disable the highlights:


```js
                optionIsFocused={!this.props.disableFocusOptions
                    && !this.props.isDisabled
                    && !section.isDisabled
                    && this.props.focusedIndex === (index + section.indexOffset)}
```

in https://github.com/Expensify/App/blob/066018af885bd1acb9e350972d5160de79a2ca4a/src/components/OptionsList/BaseOptionsList.js#L158-L170


Or another options is to pass `disableFocusOptions` as `true` for this usage.

**Comment by luacmartins** [comment]
>Did you consider another option like "disable highlights if the options are disabled"?

Funny you asked, because that was the first solution that I tried and it works! However, I felt like it was kind of a workaround to me since what caused the issue was focusing on that option in the first place instead of having the input focused by default. I don't feel strongly though, so I can use the disable the highlights if the option is disabled approach if we think that's more intuitive.

**Comment by luacmartins** [comment]
Updated with the "disable highlight if option is disabled" solution!

**Comment by aldo-expensify** [comment]
> > Did you consider another option like "disable highlights if the options are disabled"?
> 
> Funny you asked, because that was the first solution that I tried and it works! However, I felt like it was kind of a workaround to me since what caused the issue was focusing on that option in the first place instead of having the input focused by default. I don't feel strongly though, so I can use the disable the highlights if the option is disabled approach if we think that's more intuitive.

Was the initial solution to change the focus index to `1` in this case, since that is the position of the input if it was in the option list? Was the focus index = 0 making it highlight?

**Review by aldo-expensify — APPROVED** [review]

**Comment by luacmartins** [comment]
>Was the initial solution to change the focus index to 1, since that is the index of the input if it was in the option list? Was the focus index = 0 making it highlight incorrectly?

Yea, this was it. I agree with what you said above and I don't feel strongly about any particular solution here and I also agree that disabling the focus highlight is more intuitive so let's go with that! As always, thanks for the review!

**Comment by luacmartins** [comment]
Bump @parasharrajat!

**Comment by luacmartins** [comment]
@parasharrajat we changed the solution and are now just disabling focus if the input is disabled.

**Comment by aldo-expensify** [comment]
Ping @parasharrajat

**Comment by luacmartins** [comment]
Here's what I think that does:

1. We can pass the `shouldTextInputAppearBelowOptions` to [render a TextInput](https://github.com/Expensify/App/blob/93854081336980a19b02138a271fead29b37e5d9/src/components/OptionsSelector/BaseOptionsSelector.js#L279-L298) component below the options list.
2. If we pass that prop, we set the `focusedIndex` to `allOptions.length` so that the TextInput is focused, instead of the first option in the OptionsList

We only seem to have that logic as a default for the state though. When we change languages and the component re-renders, we hit [this logic](https://github.com/Expensify/App/blob/93854081336980a19b02138a271fead29b37e5d9/src/components/OptionsSelector/BaseOptionsSelector.js#L104) instead, which does not account for the `shouldTextInputAppearBelowOptions` prop and sets the `focusedIndex` to 0

**Comment by luacmartins** [comment]
We do it [here](https://github.com/Expensify/App/blob/5937ed9fc12455b7f81007e1c495af46193e8e02/src/components/OptionsSelector/BaseOptionsSelector.js#L87-L95), because we also pass `autoFocus` along with `shouldTextInputAppearBelowOptions`.

**Comment by luacmartins** [comment]
Correct! It just prevents the option from being focused, since we focus the TextInput instead.

**Review by parasharrajat — APPROVED** [review]
LGTM. Fixes the issue.

## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

cc: @aldo-expensify 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by luacmartins** [comment]
Haha I think that's what my first solution tried to address, but TBH I think we should get rid of the `shouldTextInputAppearBelowOptions` altogether since it's confusing and just disable focusing on the OptionsList. I'll leave that for another PR though. Thanks for the reviews!

**Pull request merged**
