### PR TITLE
Styling on storybook sidebar in mWeb is broken

### PR DESCRIPTION
**Pull request by mollfpr**
### Details

1. Add a CSS to change sidebar background
2. Add `../assets/css` to serve staticly
3. Call `fonts.css` from `../assets/css` to make font work

### Fixed Issues

$ https://github.com/Expensify/App/issues/7842

### Tests

1. Run storybook and verify the font base is `GTAmericaExp-Regular`
2. Open storybook from mobile web and click sidebar navigation, verify the background is changed and the texts are visible

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I verified the PR has a small number of commits behind `main`
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests & veryfy they passed on:
    - [ ] iOS / native
    - [ ] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [ ] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I added comments when the code was not self explanatory
    - [x] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [x] I followed proper naming convention for platform-specific files (if applicable)
    - [x] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
    - [x] I followed the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs))
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I corroborated the UI performance was not affected (the performance is the same than `main` branch)
- [x] If I created a new component I verified that a similar component doesn't exist in the codebase

#### PR Reviewer Checklist
- [x] I verified the PR has a small number of commits behind `main`
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the testing environment is mentioned in the test steps
- [x] I verified testing steps cover success & fail scenarios (if applicable)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [ ] MacOS / Desktop
- [x] I verified there are no console errors related to changes in this PR
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified comments were added when the code was not self explanatory
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [x] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [x] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified the UI performance was not affected (the performance is the same than `main` branch)
- [x] If a new component is created I verified that a similar component doesn't exist in the codebase

### QA Steps

1. Go to https://staging.new.expensify.com/docs/index.html and verify the font base is `GTAmericaExp-Regular` (and not something obviously different like `Times New Roman`)
2. Go to https://staging.new.expensify.com/docs/index.html from mobile web and click sidebar navigation, verify the background is changed and the texts are visible

- [x] Verify that no errors appear in the JS console

#### Safari
Screen Shot 2022-03-08 at 16 33 34

#### Chrome
Screen Shot 2022-03-08 at 16 23 47

#### Mobile Web

Screen Shot 2022-03-08 at 16 23 59

### CODE REVIEW

**Comment by roryabraham** [comment]
@mollfpr I updated your QA steps a bit. Since QA happens in our staging environment, it doesn't really make sense to "Run storybook". Storybook is hosted at `/docs/index.html`, so I added a link to clarify that.

**Comment by mollfpr** [comment]
@roryabraham thank you for clearing things up!

**Review by roryabraham — DISMISSED** [review]
Looks good and tests well! :shipit:

**Comment by roryabraham** [comment]
Whoops, I can't merge this because we require all git commits to be signed. This is pretty easy to do and there's lots of documentation out there for how to set up commit signing. Once you have commit signing working, you can retroactively sign all these commits by:

1. `git rebase -i HEAD~2`
1. For each commit, enter this in vim: `:%substitute/^pick/reword/` then save and quit.
1. Force-push your changes in this PR.

**Comment by roryabraham** [comment]
Here is one set of instructions you could follow: https://webdevstudios.com/2020/05/26/retroactively-sign-git-commits/

**Comment by mollfpr** [comment]
@roryabraham Done!

**Review by roryabraham — DISMISSED** [review]

**Comment by mollfpr** [comment]
@roryabraham Sorry I rebase the commit again. Turn out my gitconfig that signingkey not setup properly.

**Review by roryabraham — APPROVED** [review]

**Comment by mollfpr** [comment]
Updates link to test

**Pull request merged**
