### PR TITLE
Fix: Add payment method blink after interacting with buttons

### PR DESCRIPTION
**Pull request by hungvu193**
Fix:  Web - Payments - "Add payment method" blinks after interacting with buttons

### Fixed Issues

$ https://github.com/Expensify/App/issues/12438
PROPOSAL: https://github.com/Expensify/App/issues/12438#issuecomment-1316812764

### Tests
1. Open Profile, choose Payment, add a new payment method if you don't have one.
2. Press on any payment method (ie: Paypal), an Delete modal will show, press `Delete`
3. Verify that the payment method doesn't blink when you press `Delete`

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open Profile, choose Payment, add a new payment method if you don't have one.
2. Press on any payment method (ie: Paypal), an Delete modal will show, press `Delete`
3. Verify that the payment method doesn't blink when you press `Delete`

- [x] Verify that no errors appear in the JS console

#### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

#### Web

https://user-images.githubusercontent.com/16502320/202494474-2a93ce86-a6e1-403b-9fc3-9b708280e52a.mov

#### Mobile Web - Chrome

https://user-images.githubusercontent.com/16502320/202494777-c9a7e94d-a7df-48d8-8afc-3db5ef771ba3.mov

#### Mobile Web - Safari

https://user-images.githubusercontent.com/16502320/202495348-31632cfc-88f8-44eb-aa80-b8774880a5cd.mov

#### Desktop

https://user-images.githubusercontent.com/16502320/202495975-96599d3e-bfbd-4283-9734-e4b540b77826.mov

#### iOS

https://user-images.githubusercontent.com/16502320/202495582-96b151cd-d01b-4c2c-940f-6cfc587da369.mov

#### Android

https://user-images.githubusercontent.com/16502320/202495867-e68c7b97-a545-42a5-b3a8-deb376dcb6d6.mov

### CODE REVIEW

**Review by marcochavezf — DISMISSED** [review]
The code LGTM, I was able to only test on web atm (having issues with my machine).

https://user-images.githubusercontent.com/6829422/202592235-6ab0496c-6434-47d5-82fe-947a52d3a6de.mov

@sobitneupane could you also test it? For some reason, the PullerBear is not assigning reviewers 🤔

**Review by sobitneupane — COMMENTED** [review]
Found a bug while testing on IOS. When canceling/closing Delete Account popover, prior content appears for a while before closing the popover.


https://user-images.githubusercontent.com/25876548/202633309-3b223a65-cd93-458e-b22a-0acfb9c133d4.mov

**Comment by hungvu193** [comment]
> Found a bug while testing on IOS. When canceling/closing Delete Account popover, prior content appears for a while before closing the popover.

Nice catch, I think the problem came from the way I setState `shouldShowDefaultDeleteMenu` and `showDeleteContent` together. I can fix this by using InteractionManager. I will update it soon.

**Comment by hungvu193** [comment]
Updated my PR:

https://user-images.githubusercontent.com/16502320/202663854-f2cdac70-20c3-4bf7-9990-df6ece9649d3.mov

**Review by sobitneupane — COMMENTED** [review]
I notice some delay on closing/canceling the Modal. At first the focus on the selected payment method goes off, and after few moment the modal closes. Can we get rid of it as well.

https://user-images.githubusercontent.com/25876548/202718079-f85df5f5-f2d1-4e0c-8503-84698665da6f.mov

**Comment by hungvu193** [comment]
@sobitneupane It actually happened on a lot of modal in our application, I don't think it's in scope of this PR.

**Comment by sobitneupane** [comment]
>  It actually happened on a lot of modal in our application, I don't think it's in scope of this PR.

@hungvu193 I think this PR is creating this particular issue.

**Comment by hungvu193** [comment]
I don't think so,  here's the code running on main branch (you can see the modal blink) before I added anything. You can see it even more delay because it's using 2 modal.

https://user-images.githubusercontent.com/16502320/202724055-1759d6a2-5757-4192-9520-bfed1e964f04.mov

**Comment by sobitneupane** [comment]
I don't see much delay when the second modal closes in the video. 

And this PR is to solve those blinking issues.

**Comment by hungvu193** [comment]
> And this PR is to solve those blinking issues.

This exactly what I mean here, you can compare this video (in my PR) with my previous video  I posted on main branch.
I believe It has the same performance, you can see it even smoother than origin one. 

https://user-images.githubusercontent.com/16502320/202729661-fd60220a-6f5a-4ffb-a673-6c714429ff02.mov

**Comment by hungvu193** [comment]
cc @marcochavezf  thoughts on this

**Comment by sobitneupane** [comment]
It looks smooth in the video you attached.

But in my end, it is pretty slow and clearly noticeable.
> https://user-images.githubusercontent.com/25876548/202718079-f85df5f5-f2d1-4e0c-8503-84698665da6f.mov

**Comment by hungvu193** [comment]
> It looks smooth in the video you attached.
> 
> But in my end, it is pretty slow and clearly noticeable.

can you also try to run it on main branch too? I think it depends on your computer RAM and CPU too.
Please let me know your result. If it's the same then I think it's out of scope. Otherwise I'm happy to do much as I can.

**Comment by sobitneupane** [comment]
> can you also try to run it on main branch too

Oh yes. I can reproduce it on main as well. 

I would like to have feedback from @marcochavezf as [this issue](https://github.com/Expensify/App/pull/12824#pullrequestreview-1185547699) is reproducible on my simulator both on main and this PR. Might be machine limitation on my end.

Also, I will test it on real device tomorrow NPT time.

**Comment by marcochavezf** [comment]
Hi guys, thanks for the collaboration on fixing this issue!

>I would like to have feedback from @marcochavezf as https://github.com/Expensify/App/pull/12824#pullrequestreview-1185547699 is reproducible on my simulator both on main and this PR. Might be machine limitation on my end.

I haven't tested on my simulator too, but if that issue is happening on `main` then I think it's ok to keep it out of scope for this PR as @hungvu193 stated. Also, afaik the modal performance will be improved in this [PR](https://github.com/Expensify/App/pull/12369/files), so let's focus on the blinking issue and test again the modal when that PR is merged :)

**Review by sobitneupane — COMMENTED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for expected offline behavior are in the `Offline steps` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

### Screenshots


#### Web


https://user-images.githubusercontent.com/25876548/202860534-d4b1dd2b-e8c4-4318-b294-94a6314577d2.mov



#### Mobile Web - Chrome


https://user-images.githubusercontent.com/25876548/202860557-48601a8c-6dd1-45cd-b606-bcff0aa55caa.mov


#### Mobile Web - Safari


https://user-images.githubusercontent.com/25876548/202860713-645ea5b8-37b6-433a-888c-a44b366a2436.mp4



#### Desktop


https://user-images.githubusercontent.com/25876548/202860546-d04dcbf9-09dd-40cf-a774-b46ff62a9e1a.mov


#### iOS


https://user-images.githubusercontent.com/25876548/202860671-0cf0194b-627c-4b9e-9a5e-595aed9b2903.mp4


#### Android


https://user-images.githubusercontent.com/25876548/202860626-f77f3aa0-d97e-40ab-b888-e754d66ab8ef.mov

**Review by sobitneupane — COMMENTED** [review]
@marcochavezf Changes look good and test well.
🎀👀🎀 C+ reviewed

**Review by marcochavezf — APPROVED** [review]
LGTM, thank you guys!

**Comment by marcochavezf** [comment]
Tests already passed

**Pull request merged**
