### PR TITLE
Fix/38814: Distance - Unable to save second distance edit offline

### PR DESCRIPTION
**Pull request by DylanDylann**
### Details

This fixes a regression introduced in [PR](https://github.com/Expensify/App/pull/35302), which was a solution for https://github.com/Expensify/App/issues/34610

### Fixed Issues

$ https://github.com/Expensify/App/issues/38814
PROPOSAL: NA

### Tests

1. Go to workspace chat.
2. Create a distance request with three waypoints.
3. Go to request details page.
4. Go offline.
5. Click Distance.
6. Edit a waypoint
7. Repeat Step 5 and 6.
8. Verify that the user can save the second distance edit.

### Offline tests

Same above
### QA Steps

Same above
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/141406735/9ac62332-7105-441d-af0f-d9d1e7d83408

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/141406735/8af2763e-fe0c-431b-a192-417365f7cb22

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/141406735/324ebfc4-570f-44f5-887d-eb13636cee23

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/141406735/b31b0570-418c-459e-b4c3-025e092cda58

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/141406735/cc8bea40-fd7e-4d06-8263-d0af7113b2b9

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/141406735/e78750c5-5a8b-4c69-bc30-eef0dceefdcd

</details>

### CODE REVIEW

**Comment by DylanDylann** [comment]
Small change

**Comment by cubuspl42** [comment]
"Tests" block is outdated

**Comment by DylanDylann** [comment]
@cubuspl42 Updated

**Comment by DylanDylann** [comment]
@cubuspl42 Any update here

**Comment by cubuspl42** [comment]
I'm testing right now.

**Comment by cubuspl42** [comment]
Tested on this PR feature branch + `main` merged-in. This is on a fresh full Android build.

https://github.com/Expensify/App/assets/2590174/4390b3fb-773a-421b-bfd5-f975013548f5

The handles for dragging waypoints don't render, and there's a crash after attempting to drag them a few times.

While I don't _think_ this is related, I believe that this is good enough reason to double-check this. You didn't include videos from other platforms than Web.

Please...
- Merge`main`
- Test this on all platforms and provide screenshots/videos

**Comment by cubuspl42** [comment]
Please fill the "Details" section, something like "This fixes a regression introduced in PR #{id}, which intended to fix issue #{issue-id}. This allows efficient navigation.

In general, never leave "Details" empty.

**Comment by cubuspl42** [comment]
Can you reproduce the issue I mentioned? If so, did you find out if it's unrelated (i.e. occurring on `main` too)?

**Comment by DylanDylann** [comment]
I can't reproduce your bug. If you still can reproduce please help to detail the step

**Comment by DylanDylann** [comment]
@cubuspl42 I think we should focus on the original bug, If you see a bug that isn't related to this one, we can create a new bug to avoid block this PR

**Comment by DylanDylann** [comment]
@cubuspl42 Ohh, I just reproduced your bug, let's me check

**Comment by DylanDylann** [comment]
It seems it isn't related to our PR

**Comment by DylanDylann** [comment]
@cubuspl42 I uploaded videos. On the Android and IOS native we have another bug: Can't drag waypoint. But I checked this bug and saw that it isn't related to this PR. We can create another issue to fix this

https://github.com/Expensify/App/assets/141406735/b0086c1a-b0b0-4878-a624-559f5c365eb0

**Comment by cubuspl42** [comment]
> it isn't related to this PR

Neither this one, nor the [original one](https://github.com/Expensify/App/pull/35302), right?

> We can create another issue to fix this

...unless there already is one. It would be good to know its ID, we might consider holding on it.

**Comment by DylanDylann** [comment]
@cubuspl42 We can report this bug on Slack channel. This fix is very simple and I think we don't need to hold this issue

**Comment by DylanDylann** [comment]
> Neither this one, nor the https://github.com/Expensify/App/pull/35302, right?

I am not sure

**Comment by cubuspl42** [comment]
> We can report this bug on Slack channel

Go for it :)

> This fix is very simple and I think we don't need to hold this issue

You wrote "Blocked by another bug", classifying two platforms as untested 🙁 We should pick, we can't go with "not holding" and "blocked by another bug" at the same time

**Comment by DylanDylann** [comment]
@cubuspl42  I see another way to test this PR. I am updating videos for Android and IOS

https://github.com/Expensify/App/assets/141406735/324ebfc4-570f-44f5-887d-eb13636cee23

**Comment by DylanDylann** [comment]
@cubuspl42 Updated videos

**Comment by cubuspl42** [comment]
We have a ridiculous problem.

We need to change...

```
[...], which intended to fix https://github.com/Expensify/App/issues/34610
```

...to...

```
[...], which was a solution for https://github.com/Expensify/App/issues/34610
```

...or anything else that won't match [this pattern](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by DylanDylann** [comment]
@cubuspl42 updated

**Comment by cubuspl42** [comment]
It worked: 

image

(there was a link here before)

**Comment by DylanDylann** [comment]
@cubuspl42 Is there any problem? It is small change, we should speed up it

**Comment by cubuspl42** [comment]
No problem with this one. I spent some time on another issue in my queue.

**Comment by cubuspl42** [comment]
[I reported this on `#expensify-bugs`](https://expensify.slack.com/archives/C049HHMV9SM/p1712065680115269). I don't think there's much benefit of rushing with this PR, if the app just crashes on two crucial platforms in this flow. I'd assume that the other feature is a deploy blocker anyway.

**Comment by cubuspl42** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/2590174/93ebf030-4eb3-4294-9982-0a2506d9086f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/2590174/aae3e8ec-8890-4670-84dd-f04a46848585

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/2590174/a076e8f4-88db-40f3-970a-691c71eec933

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/2590174/8e4944bc-cc55-485e-839a-932281a0a3d8

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/2590174/d9eb613d-2f7a-4fbc-9b82-4da60563321d

</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by jakub-trzebiatowski — APPROVED** [review]

**Comment by cubuspl42** [comment]
@srikarparsi 

Originally, the testing steps involved re-ordering the waypoints. It triggered a crash, which is also observable on `main`.

We considered two options:
- Holding on the discovered issue
- Working it around / finding another way to test this PR

I suggested going with the first, but @DylanDylann strongly recommends the second option. I don't want to force my way, as I can see the benefits of both paths, so I approved. I'll leave the decision about the final approval to you.

**Comment by srikarparsi** [comment]
Hi, I am okay with merging because I think we can all agree that the root causes aren't related.

**Review by srikarparsi — APPROVED** [review]
lgtm

**Pull request merged**
