### PR TITLE
[No QA] Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by greg-schroeder**
Adjusting guidelines to match new payment amounts for bug reporting

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/308678

Can you confirm this looks ok @thienlnam?

### CODE REVIEW

**Review by thienlnam — APPROVED** [review]

**Comment by thienlnam** [comment]
These current changes look good, but is another spot we mention the price right? Or maybe we only mention the reporting bonus?

**Comment by greg-schroeder** [comment]
@thienlnam I went through and tried to find another place we mentioned it but I couldn't. We reference $1k in the C+ article but not just as a random example, it's not stating that's what the baseline is.

**Comment by thienlnam** [comment]
Yeah sounds good - I'm going to test something to see if it can catch stuff

**Comment by thienlnam** [comment]
Okay looks good - after feeding some files to ChatGPT it seems like those are the main mentions of the price.

In `HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md` it mentions 

... C+ are compensated the same price as the contributor for reviewing proposals and the associated PR. (ie. if a job is listed at $1000, that’s how much the C+ will make if they review both the proposals and PR).  If regressions are found that should have* been caught after the PR has ...

But I think that's fine as is

**Comment by thienlnam** [comment]
@greg-schroeder Can you sign the CLA by adding this in a comment?

`I have read the CLA Document and I hereby sign the CLA`

**Comment by greg-schroeder** [comment]
> Okay looks good - after feeding some files to ChatGPT it seems like those are the main mentions of the price.
> 
> In HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md it mentions
> 
> ... C+ are compensated the same price as the contributor for reviewing proposals and the associated PR. (ie. if a job is listed at $1000, that’s how much the C+ will make if they review both the proposals and PR). If regressions are found that should have* been caught after the PR has ...
> 
> But I think that's fine as is

Yeah I referenced that [here](https://github.com/Expensify/App/pull/26379#issuecomment-1701862073), I think it's fine.

**Comment by greg-schroeder** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by puneetlath — APPROVED** [review]

**Comment by puneetlath** [comment]
Documentation update only, so checklists weren't relevant.

**Pull request merged**
