### PR TITLE
test: use version from Onyx PR (OOM handling)

### PR DESCRIPTION
**Pull request by kirillzyusko**
### Fixed Issues

$
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by lanitochka17** [comment]
###  Video - Video loads infinitely

**IS THE ISSUE REPRODUCIBLE IN PRODUCTION:** Yes

## Expected Result:
The video plays successfully

## Actual Result:
The video loads infinitely

## ACTION PERFORMED:
1. Go to https://37917.pr-testing.expensify.com/
2. Go to any chat.
3. Upload a video.
4. Play the video.

## Workaround:
Unknown

## Notes/Photos/Videos:


https://github.com/Expensify/Web-Expensify/assets/78819774/dcd563b2-f7ba-478d-960e-ffffbd68b6a2

**Comment by kirillzyusko** [comment]
@lanitochka17 but the issue is reproducible in production as well?.. If yes, then I think the problem is not produced by my changes 😅

**Comment by kirillzyusko** [comment]
@lanitochka17 I pulled latest changes from onyx repository and updated a version from this PR - would you mind to trigger a new build and check again if the problem persist?

Again want to ask you about whether it's PR specific problem or the problem is reproducible in `main` branch as well.

@tgolen also tagging you for better visibility 👀

**Comment by lanitochka17** [comment]
Issue is still reproducible 


https://github.com/Expensify/App/assets/78819774/ad317c19-cf0b-4762-9497-a216466437c1

**Comment by kirillzyusko** [comment]
@lanitochka17 I have several questions:
1. Did you trigger a fresh build? I don't see any new comments about new build availability 🤔 
2. Does the issue reproducible in production? Or was ever reproducible in production?

**Comment by lanitochka17** [comment]
@kirillzyusko There has not yet been an announcement for a new special assembly for us.
Issue not reproducible in stg and prod


https://github.com/Expensify/App/assets/78819774/53c79b73-de00-4cca-bb9a-60013a729830

**Comment by mountiny** [comment]
@kirillzyusko kicked off new build based on your comment https://github.com/Expensify/App/actions/runs/8266551319

**Comment by kirillzyusko** [comment]
@lanitochka17 can you please test again? 🙏

**Comment by lanitochka17** [comment]
@kirillzyusko By following the link provided I can still reproduce the  issue


https://github.com/Expensify/App/assets/78819774/d6aca27e-7e18-4bcc-977c-29e9cfce152b

**Comment by kirillzyusko** [comment]
@lanitochka17 @tgolen I think this issue not because of the new version of onyx. I tested web version from this PR (it doesn't contain these changes) https://github.com/Expensify/App/pull/37891#issuecomment-1992727297 and the issue also present. I'm getting (I removed `encryptedAuthToken` from URL form security point of view):

```bash
Refused to load media from 'https://staging.expensify.com/chat-attachments/1322710446990230970/w_b88b5234a18ca5d81400f494233196928ad18cca.mov?encryptedAuthToken=...' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.
```

So I think the error happens because of pr-preview URL and it's not because of my changes 😅

**Comment by mountiny** [comment]
Beware that on web, the ad-hoc build might require fresh restart/ clearing cache as its served from the same URL. Using incognito mode is adviced

**Comment by kirillzyusko** [comment]
> Beware that on web, the ad-hoc build might require fresh restart/ clearing cache as its served from the same URL. Using incognito mode is adviced

@mountiny good point! I've double checked incognito mode and it has the same problem on the other branch (so it makes me thinking that the problem is not related to changes in this PR).

**Comment by kirillzyusko** [comment]
@tgolen Am I right in thinking that this PR is not causing any regressions? If yes, then can we merge an original PR in `react-native-onyx` repository?

**Comment by tgolen** [comment]
It appears that way so far. I am not sure if they are done testing it though. I can reach out to them and ask.

**Comment by kirillzyusko** [comment]
> It appears that way so far. I am not sure if they are done testing it though. I can reach out to them and ask.

That would be amazing 🙌

**Comment by tgolen** [comment]
They said they have about 20% of testing left to go and will try to get it prioritized around the regular deploys to get it wrapped up.

**Comment by kbecciv** [comment]
###  Thread - Unavailable workspace displayed in header

**IS THE ISSUE REPRODUCIBLE IN PRODUCTION:** NO

## Expected Result:
Only the user's avatar is displayed in the header

## Actual Result:
"Unavailable workspace" is displayed next to the avatar in the header and in LHN

## ACTION PERFORMED:
1. Open the app and log in
2. Open any report and send a message
3. Start a thread

## Workaround:
Unknown

## Notes/Photos/Videos:


https://github.com/Expensify/App/assets/93399543/04b02c67-5dbd-4413-b9b6-e6ed6b400fb5

**Comment by kbecciv** [comment]
Below issue could be the same root cause of https://github.com/Expensify/App/pull/37917#issuecomment-1988428160, but would like to double check.

###  Chat - "Hmm... it's not here" error when open chat link in new tab

**IS THE ISSUE REPRODUCIBLE IN PRODUCTION/Staging:** NO

## Expected Result:
Chat conversation should open and no error page should appear

## Actual Result:
"Hmm... it's not here" error when open chat link in new tab

## ACTION PERFORMED:
1. Click on the green + button and select the "Start Chat" option.
2. Search for a user that you don't have any messages with and open the chat
3. Don't send any message
4. Copy the 'reportID'
5, Paste the 'reportID' on another tab and press Enter

## Workaround:
Unknown

## Notes/Photos/Videos:


https://github.com/Expensify/App/assets/93399543/6bac6baa-1688-459b-8694-3e60684b035e

**Comment by kirillzyusko** [comment]
> Below issue could be the same root cause of https://github.com/Expensify/App/pull/37917#issuecomment-1988428160, but would like to double check.

Yes, I think you're right. I also tested another PR without these changes and there is the same problem - I see error page straight after pressing an "enter" button in a new tab (I think this could be due to additional `37917.pr-testing` prefix for host - but anyway I think this problem is not because of the changes made in this PR.

**Comment by kirillzyusko** [comment]
> Thread - Unavailable workspace displayed in header

@kbecciv I can confirm, that issue existed. But it looks like it was added in `main` branch and also the issue not coming from this PR. I rebased my changes to latest `main` branch and the issue has gone (I pushed my changes).

@tgolen can you please trigger a new build so that QA can verify and confirm/refute my words? 👀

**Comment by tgolen** [comment]
Sure thing. I've just not triggered a new build.

**Comment by kirillzyusko** [comment]
@mountiny I think we are not going to merge this PR - I just assembled my branch from Onyx repository and in this PR we simply want to test the code before merging my PR into Onyx `main` branch. When merge happens, then we'll close this PR I believe 👀

**Comment by mountiny** [comment]
Ah I did not check, thanks for clarifying

**Comment by kirillzyusko** [comment]
@tgolen just wanted to check a status of this PR - are we waiting for another round of testing? 👀

**Comment by kirillzyusko** [comment]
> I will ask @kirillzyusko have you resolved all the known issues?

@mountiny yes, some of issues were solved just by a rebase and some of them can not be resolved (due to different URL - CORS policy).

May I know the status of testing? 👀

**Comment by kirillzyusko** [comment]
I'm closing this PR since my changes were merged into onyx and were released. The only remaining thing is bump onyx, but it's made in different PR.

**Pull request closed without merging**
