### PR TITLE
[CP Staging] Fix task description is double parsed when updating the task title

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

When we update the title, we also parse the task description which shouldn't happen because it's already parsed. This PR make sure to parse it only when editing the description.

### Fixed Issues

$ https://github.com/Expensify/App/issues/42225
$ https://github.com/Expensify/App/issues/42263
$ https://github.com/Expensify/App/issues/39496
PROPOSAL:

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

1. Create a new task with a description that contains markdown (bold, italic, emoji, etc.)
2. Open the task report
3. Verify the task description is rendered as a markdown
4. Edit the task title
5. Verify the task description stays the same
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/50919443/c91397d8-2079-4cf9-843c-8283e9ab0d06

https://github.com/Expensify/App/assets/50919443/4cd3e070-bc48-4f68-a05a-7729e86f015f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/50919443/da391e09-b9ae-4356-80e3-c862a8c2774d

https://github.com/Expensify/App/assets/50919443/91b59d3e-bec7-4d73-8f2d-b96544eb234f

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/50919443/7c59b810-7e4c-4d6c-bee4-418e607645c4

https://github.com/Expensify/App/assets/50919443/aa72ec19-6bf5-4cfe-bb66-9716ebef01df

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/50919443/cca6dead-3159-4a6d-b621-8e7fdb0db397

https://github.com/Expensify/App/assets/50919443/4043f4e4-cd8e-4b56-b481-2d605890f119

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/50919443/57499382-bf25-4d98-b43f-74e4714b931a

https://github.com/Expensify/App/assets/50919443/6852141b-00e0-478b-875d-ebd0da0f0116

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/50919443/4eafd41f-d04c-42b6-8f69-57c681b929a2

https://github.com/Expensify/App/assets/50919443/3c4bde69-f62e-4329-b476-201f8a096083

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
@abdulrahuman5196 we have another regression. It's my bad that I didn't carefully see that updating the title would parse the task description again. I fix it by making sure we parse it only when editing the description.

**Comment by Beamanator** [comment]
Bumped @abdulrahuman5196 🙏

**Comment by abdulrahuman5196** [comment]
checking now

**Comment by bernhardoj** [comment]
FYI, the ts error is unrelated and being handled [here](https://www.github.com/Expensify/App/pull/42256)

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours. @Beamanator 

🎀 👀 🎀
C+ Reviewed

**Review by Beamanator — APPROVED** [review]
LGTM - doesn't have anything to do with the type errors, and since this fixes 2 blockers I'm ok moving forward with this

**Comment by Beamanator** [comment]
Not emergency, we know the type error exists and it's being fixed in https://github.com/Expensify/App/issues/42253

**Comment by Beamanator** [comment]
Requesting CP

**Comment by Beamanator** [comment]
@bernhardoj @abdulrahuman5196 either of you available to test this on staging? 🙏

**Comment by bernhardoj** [comment]
@Beamanator Fixed on staging

https://github.com/Expensify/App/assets/50919443/ddf75ff9-90cc-4fd0-a061-e5c612072cb8

**Comment by Beamanator** [comment]
Thanks very much @bernhardoj !

**Pull request merged**
