### PR TITLE
Change "Beneficial Owners" to "Additional Information" in VBA flow

### PR DESCRIPTION
**Pull request by mountiny**
### Details

Mostly just updating a copy and aligning design with other views in a page.

For more context, see linked issue.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/176730

### QA Steps

1. Create a workspace
2. Select Get Started
3. Enter information using [test credentials ](https://stackoverflow.com/c/expensify/questions/342) from (2)
4. Make sure the Panel header and subheader look like on screenshot below.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

image

### CODE REVIEW

**Review by luacmartins — COMMENTED** [review]
Code LGTM!

I think we are missing the bank account credentials link in the OP. Could you please include that as well as screenshots of the new panel?

**Comment by mountiny** [comment]
@luacmartins You are too fast Carlos, had to hop on two syncs haha

Updating right now!

**Review by luacmartins — APPROVED** [review]
Thanks for the update 😄  LGTM!

**Comment by mountiny** [comment]
@luacmartins Thank you very much for your review! I have added the QA link and I have also included a screenshot. 

Since it is just a copy update essentially I believe we do not need to check other platforms.

**Pull request merged**
