### PR TITLE
Image Web/Desktop: Add support for http headers

### PR DESCRIPTION
**Pull request by kidroca**
Note: This PR was previously reverted (see PR #35636 for reference). Our objective now is to identify an issue that manifests only post-deployment. We should be able to use the `pr-testing` link to detect any problems in loading/rendering images 

### Details

This PR refactors the `Image` component, aligning the web/desktop and native implementations for better consistency and maintainability.

#### **Changes:**

1. **Introduced `BaseImage` Component:** 
    - File Location: `src/components/Image/BaseImage.tsx`
    - This new component acts as a bridge between the native and web implementations. 
    - For the `onLoad` event, it ensures that both web and native platforms have the same signature.

2. **Native Implementation Update:** 
    - File Location: `src/components/Image/BaseImage.native.tsx`
    - The native side uses `expo-image`, with a slight adjustment for the `onLoad` prop, to make it's interface uniform.

3. **Unified Image Component for Web/Desktop and Native:**
    - File Location: `src/components/Image/index.js`
    - The main `Image` component has been refactored to use the new `BaseImage`.
    - This change streamlines the authToken inclusion process in the image source, ensuring it works seamlessly across both platforms.

4. **Removed Redundant Native Specific Implementation:** 
    - File Location: `src/components/Image/index.native.js`
    - With the new unified approach, the native-specific implementation has become redundant and has been removed.

5. **Patch for `react-native-web`**
   - File Location: `patches/react-native-web+0.19.9+005+image-header-support.patch`
   - Implemented a custom patch for the official react-native-web version 0.19.9, incorporating changes from PR [#2442](https://github.com/necolas/react-native-web/pull/2442). This patch adds support for Image with HTTP headers, which was previously missing in our current version.

### Fixed Issues

$ https://github.com/Expensify/App/issues/12603
PROPOSAL: N/A

#### Verify the Image component works on all platforms
1. Launch the application and navigate to a report containing multiple attachments.
2. Scroll through the report, ensuring that all attachments are loading successfully without any errors or delay.
3. Click on an attachment to open its preview.
   - Confirm that the preview displays the image correctly.
   - Ensure the download button is present and functional; downloading the image should work as expected.
4. Open your browser's developer tools or the equivalent network monitoring tool for the platform you are testing on.
   - Monitor the network requests for image attachments.
   - Verify that the requests contain the `X-Chat-Attachment-Token` header.
5. Test the image caching functionality:
   - Keep the application open for more than 2 hours.
   - Observe that the images remain loaded and are not re-fetched.
   - Logout from the application and then log back in.
   - Navigate to the same report with attachments.
   - Images that were previously loaded should display instantly, indicating they are loaded from the cache.
   - Confirm that the behavior remains consistent even if the `X-Chat-Attachment-Token` value changes.
6. Verify Attachment Opening for Scanned Receipts in Payment Requests
   - Create a payment request using "Request money"
   - Scan or upload a receipt during the request process.
   - Once the receipt is uploaded and the request is sent, attempt to open the receipt by tapping on the receipt image.
   - Confirm that the receipt opens correctly in the attachment view.

### Offline tests

1. Make sure you have viewed some reports with attachments while online.
2. Disconnect from the internet or turn on airplane mode to simulate an offline state.
3. Navigate to a report with attachments that were previously loaded.
   - Verify that these images still render correctly, even without an internet connection.
4. Navigate to a report with attachments that were NOT previously loaded.
   - The attachments should appear in an infinite loading state, indicating they cannot be fetched without an internet connection.

### QA Steps

1. Open the staging environment of the application.
2. Navigate to various reports that contain different types of attachments.
3. Ensure that all attachments load successfully without any visual artifacts or errors.
4. Click on any attachment to initiate the attachment preview.
   - Confirm that the preview opens, displaying the attachment correctly.
   - Locate the download button and click on it. Verify that the image is downloaded to your device or computer as expected.
5. Verify Attachment Opening for Scanned Receipts in Payment Requests
   - Create a payment request using "Request money"
   - Scan or upload a receipt during the request process.
   - Once the receipt is uploaded and the request is sent, attempt to open the receipt by tapping on the receipt image.
   - Confirm that the receipt opens correctly in the attachment view.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

image

</details>

<details>
<summary>Android: mWeb Chrome</summary>

image

</details>

<details>
<summary>iOS: Native</summary>

Screenshot 2024-01-15 at 16 32 43

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Screenshot 2024-02-15 at 10 07 25

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/12156624/2566a909-fd0b-4af1-a357-504981b54e94

Screenshot 2024-02-15 at 9 43 15

</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2024-02-15 at 9 58 09

</details>

### CODE REVIEW

**Comment by Beamanator** [comment]
Creating adhoc build soon 👍

**Comment by kidroca** [comment]
@aimane-chnaif, @francoisl, @Beamanator 

I couldn't recreate the problem that led to reverting the previous PR, following these steps: https://github.com/Expensify/App/pull/35636#issuecomment-1922941224

Furthermore, until the receipt image is uploaded and processed we're supplying the local file blob to represent the receipt image
image

This means the browser can release the local blob resource when it's no longer used, though I wasn't able to reproduce this either, but technically if you refresh, or better yet close the app window and open it again this local blob might be released to conserve resources 

I have a working theory that since it takes some time to process a receipt, once the receipt result is ready the backend provides the remote attachment address, at that point the user happened to be offline and the remote image couldn't load 
I see that in such cases we currently show an offline image placeholder 
image

Or perhaps the issue @francoisl encountered is an unrelated, intermittent bug that manifests independently of the image update changes.

**Comment by francoisl** [comment]
Not sure if it helps, but here's what I'm seeing from https://36560.pr-testing.expensify.com/

- The image has a `blob:https://` `src`, even after reloading the app, and even after the receipt is finished processing in the backend
- While offline, switching back and forth to a chat that has the `blob:` image replaces it with the offline placeholder - even though I can still refresh the `blob:` image in a separate tab, which seems to indicate that the browser did not release the blob

https://github.com/Expensify/App/assets/2229301/42bd981f-c286-47d6-829f-31b40916ec2d

**Comment by kidroca** [comment]
I believe I've identified the issue—the preflight response isn't being cached, resulting in its repeated execution with each image render. While the images themselves are cached, the browser is forced to reinitiate the preflight check due to the absence of caching headers. These headers are crucial as they instruct the browser on whether and how long to cache the preflight request.

Consequently, in offline scenarios, the browser is unable to perform the preflight request, leading to a failure in loading all images.

Here are some visuals to illustrate the point:

- **Image caching example** (Notice how the GET response for the image is cached):
Image caching example

- **Preflight request missing caching headers**:
Preflight request missing caching headers

To fix the issue in offline usage, and omit doing preflight request for cached items we should add some cache to the preflight response as well (this is a backend task)

**Comment by cubuspl42** [comment]
Conflicts ⚔️

**Comment by trjExpensify** [comment]
>To fix the issue in offline usage, and omit doing preflight request for cached items we should add some cache to the preflight response as well (this is a backend task)

@Beamanator are you going to take this on, or perhaps @justinpersaud, as you've been helping out on resolving some backend issues related to this?

**Comment by justinpersaud** [comment]
@kidroca I just deployed a change to enable caching of preflight requests if you'd like to test again and report back.

**Comment by kidroca** [comment]
> @kidroca I just deployed a change to enable caching of preflight requests if you'd like to test again and report back.

It doesn't seem possible to use the current PR review environment: https://36560.pr-testing.expensify.com/

image


I've pushed updates to sync with `main` and resolve conflicts, so we need to re-run the adhoc build: https://github.com/Expensify/App/pull/36560#issuecomment-1945658149

**Comment by amyevans** [comment]
This got built, however the workflow failed on the `Post a GitHub comment with app download links for testing` step, so I'm going to just post them manually:
* [Android](https://ad-hoc-expensify-cash.s3.amazonaws.com/android/https%3A//github.com/Expensify/App/pull/36560/index.html)
* [iOS](https://ad-hoc-expensify-cash.s3.amazonaws.com/ios/https%3A//github.com/Expensify/App/pull/36560/index.html)
* [Desktop](https://ad-hoc-expensify-cash.s3.amazonaws.com/desktop/36560/NewExpensify.dmg)
* [Web](https://36560.pr-testing.expensify.com/)

**Comment by kidroca** [comment]
@amyevans, thank you for your assistance. However, it appears that this PR was still significantly out of sync with `main`, leading us to encounter the "Update Requested" screen again on the review environment: https://36560.pr-testing.expensify.com/.

I've just re-synced with `main`. Could you please trigger another ad-hoc build? 🥺

**Comment by Beamanator** [comment]
Sorry y'all, I just got back from vacay 🙏  I just triggered another adhoc build 👍

**Comment by kidroca** [comment]
Hello @Beamanator,

I noticed that the Web build and deploy process was successful: https://github.com/Expensify/App/actions/runs/8264151190/job/22607147679. However, there seems to be an issue, as the review environment still displays the "Update Requested" screen. This could either be because the build isn't using the latest code, or there might be a build issue. Upon inspecting the details, I observed that App's version in the network calls is `1.4.42-0`, which is incorrect. After pulling the remote branch, I confirmed that the version should be `1.4.51-3`. Therefore, it appears something is not functioning as expected with the ad hoc build process.

image

Could you investigate, or confirm you have the same issue on this review env: https://36560.pr-testing.expensify.com/

**Comment by Beamanator** [comment]
Same here 🤔  I'm able to sign in and I see `appversion: 1.4.51-3`

**Comment by kidroca** [comment]
> Same here 🤔 I'm able to sign in and I see `appversion: 1.4.51-3`

Thank you for checking, everyone. It appears to have been a caching issue, as switching to a different browser resolved the problem for me. I can no longer reproduce the issue with thumbnail images when offline, nor the issue with failed receipt OCRs. I've confirmed that the preflight requests are now cached for 24 hours, which means they are entirely skipped in CORS checks.

✔️ The PR is now ready for review. It has already been reviewed and approved in previous iterations, but it's worth taking another look since I introduced some changes while resolving conflicts with the recent conversion of the Image to TypeScript.

**Comment by Beamanator** [comment]
Amazing, thanks so much @kidroca 🙏  @aimane-chnaif can you please do another full review before we move forward with this guy?

**Review by aimane-chnaif — APPROVED** [review]

**Review by Beamanator — APPROVED** [review]
This looks great to me, Hoping this is the last time we have to merge this 🙏

**Pull request merged**
