### PR TITLE
[No QA] Post deploy announcements in slack

### PR DESCRIPTION
**Pull request by luacmartins**
cc @roryabraham will you please take a look?

### Details
Posts an announcement in the `#announce` Slack channel after app is deployed to staging and production.

### Fixed Issues
$ https://github.com/Expensify/App/issues/4727

### Tests
1. Make sure that the `StagingDeployCash` is not locked.
2. Lock the `StagingDeployCash`, then verify that the resulting staging deploy is announced in `#announce`.
3. Merge a PR with the `CP Staging` label, then verify that the resulting staging deploy is announced in `#announce`.
4. Once the deploy checklist is complete and we close it out, verify that the resulting prod deploy is announced in `#announce`.

### QA Steps
None.

### Tested On
N/A GitHub only!

### CODE REVIEW

**Review by roryabraham — COMMENTED** [review]
Should we also post prod deploys in #expensify-open-source?

**Review by Julesssss — DISMISSED** [review]
Hi @luacmartins, I'm unsure how to test this without causing havoc with the current release. Should we merge and use internal testing to verify against the next official release and CP?

**Comment by luacmartins** [comment]
Updated! Added the step to post prod deploys to `#expensify-open-source`.

> Hi @luacmartins, I'm unsure how to test this without causing havoc with the current release. Should we merge and use internal testing to verify against the next official release and CP?

@Julesssss I think that might be the only way.

**Review by Julesssss — APPROVED** [review]
Could do with some more emoji

**Review by roryabraham — APPROVED** [review]
LGTM, but I agree with @Julesssss that it's lacking in emoji.

Live-testing changes like this always requires some patience and persistence. You don't necessarily have follow the testing instructions to the T in order to verify it works, just remember to verify it when CPs / staging deploys / prod deploys happen.

**Comment by Julesssss** [comment]
> You don't necessarily have follow the testing instructions to the T in order to verify it works, just remember to verify it when CPs / staging deploys / prod deploys happen.

Good points, will keep an eye out for this. Merging now.

**Comment by luacmartins** [comment]
Seems to be working!

**Pull request merged**
