### PR TITLE
Add inline images preview to the Live Markdown Input on the web

### PR DESCRIPTION
**Pull request by Skalakid**
### Details

This PR bumps the version of the `react-native-live-markdown` to the latest and enables the inline image previews inside the input on the web

Screenshot 2024-09-16 at 11 56 32

### Fixed Issues

$ https://github.com/Expensify/App/issues/40181#issue-2240640829
$ https://github.com/Expensify/App/issues/48797

PROPOSAL:

#### Inline image preview

1. Open any chat room / page with Live Markdown input
2. Enter inline image markdown. For example:
```
*test* ![demo image](https://picsum.photos/id/1067/200/300)_test_ 
```
3. Verify the behavior of the input with image preview inside
4. Verify the loading indicator styling and layout before the image loads
5. Verify the size and aspect ratio of the image preview
6. Verify other cases where image can break the input

#### https://github.com/Expensify/App/issues/48797
 
1. Initiate a DM with any user
2. Compose a message
3. Place the cursor in the middle of the composed message
4. Press the Delete button on the keyboard

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as Tests
### QA Steps

Same as Tests
- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>
web only feature
<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/742e3511-abd8-4506-b129-560584bc93e4

</details>

<details>
<summary>iOS: Native</summary>

web only feature
</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/3b8178cd-47de-4bda-999b-4582d54d30fd

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/7c064876-7505-480e-9c8f-a18031a98f20

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/77241e41-15e1-4811-9c39-c62b8d4a66e8

</details>

### CODE REVIEW

**Comment by shawnborton** [comment]
Do we need to use `[image preview]`? Wouldn't just using `[image]` be easier?

**Comment by Skalakid** [comment]
> Do we need to use [image preview]? Wouldn't just using [image] be easier?

I used `image preview` only as an example; you can type whatever you want there

**Comment by Skalakid** [comment]
> It seems like the height of the image jumps a bit when we load it... any ideas what's happening there? It goes from this:

It's because I'm changing the source URL of the image, and the browser is loading it once again since it can be completely different image. While loading we are rendering the loading indicator that has `20px` of height. THe image loads pretty quick so loading indicator disappears instantly and that why we have a layout jump.

Also, on the screen shots that you posted I'm changing the URL variables (width and height) to get the image with different resolution, it's also the reason of the jump

**Comment by Skalakid** [comment]
@mountiny, can we get an adhoc build for testing so we can all easily verify how inline images behave in action, please?

**Comment by shawnborton** [comment]
Hmm I keep getting a broken image when I try this with the adhoc build, I've tried multiple URLs too:

CleanShot 2024-09-16 at 15 11 26@2x

**Comment by hungvu193** [comment]
just tried the adbuild and I got the same issue with @shawnborton 

Screenshot 2024-09-16 at 20 43 05

Here's the logs:

Screenshot 2024-09-16 at 20 44 06

**Comment by hungvu193** [comment]
It's working with Dev, so I assume that we will need to wait for BE to deploy to make it work with Staging, just like videos, we will need to whitelist these URL right? 😄 

Screenshot 2024-09-16 at 21 31 47

**Comment by hungvu193** [comment]
@Skalakid  Can we add a debounce or wait until the user ends their inputting before another preview?

https://github.com/user-attachments/assets/42370fa9-b935-4601-b271-9bc8c71244b0

**Comment by Skalakid** [comment]
@hannojg I've added a debounce for inline image previews :D

**Comment by hungvu193** [comment]
> @hungvu193 I've added a debounce for inline image previews :D

Awesome!. It's working! 🎉 .

I've found this bug, if you added multiple inline images at the same time, when you edit that message, the first image won't show up.

https://github.com/user-attachments/assets/4b33c9c3-c5e4-454e-a75b-f851070a891c

**Comment by Skalakid** [comment]
@hungvu193 Hello, I fixed the problem with multiple image loading. Also, I've updated the PR description and added test steps for https://github.com/Expensify/App/issues/48797 since the latest library bump includes their changes. Please verify this during testing

**Comment by hungvu193** [comment]
Thanks @Skalakid, the bug I mentioned above is fixed 🎉 . 

Do we also support offline patterns for this feature? If yes, I think we still have 2 issues:
1. If the user tries to add an inline image offline, the broken image will show and the preview image won't reload or show even when we're back online.
2. While in step 1, turn on the internet connection and edit the URL or enter any character to make the composer re-render, now the image will take the full space of the composer.


https://github.com/user-attachments/assets/e01dbfd1-b0ed-41b9-83e6-b082e7217acb

**Comment by hungvu193** [comment]
Another issue, I think that it will need advice from @Expensify/design team.
If we send an invalid inline image (the URL is broken), an empty placeholder will appear, if we click on it, a loading spinner will show infinitely. I think we should display a placeholder for broken image instead. Any thoughts?

https://github.com/user-attachments/assets/85fe3467-d6dd-4c70-98cb-947f8bb3bc49

**Comment by Skalakid** [comment]
> Another issue, I think that it will need advice from @Expensify/design team. If we send an invalid inline image (the URL is broken), an empty placeholder will appear, if we click on it, a loading spinner will show infinitely. I think we should display a placeholder for broken image instead. Any thoughts?
> 
>  Screen.Recording.2024-09-18.at.17.39.50.mov

cc @dubielzyk-expensify @shawnborton @dannymcclain

**Comment by Skalakid** [comment]
>1. If the user tries to add an inline image offline, the broken image will show and the preview image won't reload or show even when we're back online.
>2. While in step 1, turn on the internet connection and edit the URL or enter any character to make the composer re-render, now the image will take the full space of the composer.

Hi @hungvu193, thanks for reporting these issues. I think we should treat both of them as bugs. I've started preparing the fix for them. However, a couple of new problems appeared. I will continue working on it tomorrow

**Comment by shawnborton** [comment]
I like the idea of using a custom broken image icon for the placeholder. I think we already have a good placeholder for things like deleted images or images that won't quite load, right? So we could reuse that pattern and swap the icon out.

**Review by rafecolton — COMMENTED** [review]
This PR merges the react-native-live-markdown change that fixes https://github.com/Expensify/App/issues/48797. I downloaded and tested the branch and can confirm it includes the fix for that issue 👍

**Comment by Skalakid** [comment]
Hi, I prepared the PR with the fixes for image loading when the app is reconnecting. Also, I've fixed async image loading: https://github.com/Expensify/react-native-live-markdown/pull/500

**Comment by Skalakid** [comment]
Hello @hungvu193, I bumped the library, so the issues that you've reported should be fixed 😄

**Comment by hungvu193** [comment]
Thanks for your quick work 🚀 let me test it

**Comment by Skalakid** [comment]
> Another issue, I think that it will need advice from @Expensify/design team.
If we send an invalid inline image (the URL is broken), an empty placeholder will appear, if we click on it, a loading spinner will show infinitely. I think we should display a placeholder for broken image instead. Any thoughts?

I think that we should fix this issue in a separate PR, since it's more connected to E/App itself and how attachments are being displayed.

**Comment by hungvu193** [comment]
@Skalakid It worked 🚀 . I've wondered if we should add a loading spinner when we're back online? What's your thought?


https://github.com/user-attachments/assets/f9a45548-603d-49dd-b30f-80c44b1e1914

**Comment by Skalakid** [comment]
@hungvu193 Hmm, I'm not sure. I think it's a tiny detail for now, and we can add it in other PR that will bump the library

**Comment by hungvu193** [comment]
> @hungvu193 Hmm, I'm not sure. I think it's a tiny detail for now, and we can add it in other PR that will bump the library

Agreed 😄 This LGTM, I'll complete the checklist

**Comment by hungvu193** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/1b083534-67d8-4204-b457-1f996649fe8c



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/1fd04c3d-c64a-4d50-be0f-e0d48b990e67


</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/31933cef-4a93-4d03-ae1b-1ed6ac6d0fa1



</details>

**Review by hungvu193 — APPROVED** [review]

**Comment by rafecolton** [comment]
Requesting a review from Jack too since he is working on the markdown preview feature. I will do a review for both that and the forward delete issue.

**Comment by thienlnam** [comment]
Woo! Nice work getting it here - changes look good but since this is a big bump this might be good to have tested by QA as well

**Comment by thienlnam** [comment]
Just generated a new build of the latest, and will have applause run through some tests for the composer

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Mark down - Image preview in the composer loads infinitely when opened in thread


**Version Number:** 9.0.6-2
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

1. Go to https://49250.pr-testing.expensify.com/
2. Go to DM
3. Type anything in the composer
4. Click + > Add attachment
5. Select a photo and send it
6. Right click on the message > Reply in thread
7. Right click on the message in thread > Edit message


## Expected Result:
The image preview in the composer will not load infiniftely

## Actual Result:
The image preview in the composer loads infinitely when opened in thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5cc2011b-9cc4-4308-be21-258d70eea814


</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## mWeb - Task - Description entered is not shown in task preview


**Version Number:** 9.0.39-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

1. Go to https://49250.pr-testing.expensify.com/home
2. Tap on a chat
3. Tap plus icon -- assign task
4. Enter title and description
5. Tap next

## Expected Result:
Description entered must be shown in task preview

## Actual Result:
Description entered is not shown in task preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4c5bfd1-4fb9-4106-998c-930c4c574f31


</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## mWeb - Room - The text saved in private notes section is not shown


**Version Number:** 9.0.39-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

1. Go to https://49250.pr-testing.expensify.com/home
2. Open a group chat
3. Tap private notes
4. Enter a text and save it
5. Tap private notes section again

## Expected Result:
The text saved in private notes section must be shown

## Actual Result:
The text saved in private notes section is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1dffa928-b667-441d-851f-3e6369ab3be6

</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## mWeb - Composer - Text cursor appears behind the first letter after tapping keyboard spacebar


**Version Number:** 9.0.39-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

Precondition:
- Keyboard is Samsung keyboard
1. Go to https://49250.pr-testing.expensify.com/

2. Go to DM
3. Type a word and do not select any word from the suggestion (make sure the typed word still has underline)
4. Tap keyboard spacebar

## Expected Result:
The text cursor will be at the end of the word

## Actual Result:
The text cursor appears behind the first letter after tapping keyboard spacebar

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/2c4e0e40-06b0-40e5-aa66-cab18bae4bb5


</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Web - Compose box - Emojis entered from OS-built emojis are rendered as small emojis


**Version Number:** 9.0.39-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

Precondition:
1. Sign in to https://49250.pr-testing.expensify.com/
2. Navigate to a conversation
3. While focusing on compose box, enter emojis from OS-build emojis

## Expected Result:
Emojis have big size in compose box and the send button works

## Actual Result:
Emojis are rendered in small size and send button is disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/587baa04-14f0-463d-a5b0-0011bea86f3c

</details> 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>

**Comment by dubielzyk-expensify** [comment]
Tested this locally with the branch and it's looking awesome! At least the inline image side of it. I'll leave the rest to testing, but from a visual perspective this is good to go 👍

**Review by dubielzyk-expensify — DISMISSED** [review]

**Comment by hungvu193** [comment]
[This bug](https://github.com/Expensify/App/pull/49250#issuecomment-2368851657) from QA is interesting.
I assume that we won't let user edit their message if they attach image right?

**Comment by hungvu193** [comment]
[This bug](https://github.com/Expensify/App/pull/49250#issuecomment-2369308556) is being handled [here](https://github.com/Expensify/App/issues/4114)

**Comment by mvtglobally** [comment]
QA regression has been completed

**Comment by Skalakid** [comment]
Hello, thanks for the QA regression tests, I'm back at the office and I will investigate them

**Comment by Skalakid** [comment]
@lanitochka17 I wasn't able to reproduce the following issues:

- [mWeb - Task - Description entered is not shown in task preview](https://github.com/Expensify/App/pull/49250#issuecomment-2368907990)

https://github.com/user-attachments/assets/f9ab18e8-b588-44c3-ac3f-b713dd033573

- [mWeb - Room - The text saved in private notes section is not shown](https://github.com/Expensify/App/pull/49250#issuecomment-2368968438)

https://github.com/user-attachments/assets/96fc29c9-0291-4676-b426-ef834b375170

**Comment by Skalakid** [comment]
@lanitochka17 Oh, okay, everything happens on Samsung devices.. I will continue the investigation tomorrow

**Comment by Skalakid** [comment]
Hello, [here](https://github.com/Expensify/react-native-live-markdown/pull/506) I created the PR with the fixes for the issues reported above

**Comment by Skalakid** [comment]
@hungvu193 @lanitochka17 The PR has been merged, so all reported bugs have been fixed :D Please verify it, and let's merge this feature into E/App

**Comment by hungvu193** [comment]
Thanks @Skalakid, I can verify that all the bugs above are fixed!

Just found a small bug, but I think we can address it in a follow-up PR. If we add the room description as an inline image, while clicking the image the RHP won't show up.

https://github.com/user-attachments/assets/500fc7f3-caa5-45a8-a306-441db10f0160


All yours @thienlnam

**Review by thienlnam — APPROVED** [review]
Thanks for sticking with this! Let's send it 🚀

**Comment by hungvu193** [comment]
@thienlnam can you create an issue for these issues?
https://github.com/Expensify/App/pull/49250#issuecomment-2363993179 and https://github.com/Expensify/App/pull/49250#issuecomment-2382888496

**Comment by thienlnam** [comment]
We ended up reverting this PR to fix some other blockers - unfortunately, I think it will be tough to get this through without causing any issues. Let's see what we can address from the latest batch of reported issues and make sure we address any critical issues. Anything smaller that comes up we can probably address later and I'll denote that to the App deployer next time we merge this

**Comment by rafecolton** [comment]
Given that, can we merge a separate update that only updates the markdown library, so we can deploy the fix to https://github.com/Expensify/App/issues/48797?

**Comment by mjasikowski** [comment]
@Skalakid just confirming that this has caused 49983, we'll need - we'll need to review composer scrolling with the new update

**Comment by VickyStash** [comment]
Also, this one caused this issue: https://github.com/Expensify/App/issues/49973

**Pull request merged**
