### PR TITLE
Revert "Merge pull request #6738 from azimgd/fix-reverted-list"

### PR DESCRIPTION
**Pull request by alex-mechler**
This reverts commit 1c80150632c684174270c019b7439854318471a4, reversing
changes made to 7b0752d5f973003ae7b51f8c466513626b3619c6.

cc @azimgd 

### Details
This inverted flatlist fix broke iOS and Android views with a few amount of messages

### Fixed Issues
$ https://github.com/Expensify/App/issues/6792

### Tests
1. Launch the app
1. Log in
1. Tap on Fab menu and Tap on New Room
1. Create a Room
1. Send some messages
1. _Verify_ they appear at the bottom

### QA Steps
1. Launch the app
1. Log in
1. Tap on Fab menu and Tap on New Room
1. Create a Room
1. Send some messages
1. _Verify_ they appear at the bottom

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

### Screenshots
image

### CODE REVIEW

**Review by Julesssss — APPROVED** [review]
Approving so that we can resolve the deploy blocker

**Comment by azimgd** [comment]
@alex-mechler @Julesssss Can we prioritize the fix https://github.com/Expensify/App/pull/6798 instead ?

cc @thienlnam

**Comment by Julesssss** [comment]
@azimgd ah, thanks for pointing that out. I'll review it once I have a moment.

**Comment by alex-mechler** [comment]
Yup, we can do that instead! Thanks for working on a fix for this so quick!

**Pull request closed without merging**
