### PR TITLE
Live Markdown Preview for web

### PR DESCRIPTION
**Pull request by Skalakid**
This PR adds Live Markdown Preview feature for web using @expensify/react-native-live-markdown library. Previously Markdown Input was added only for native devices in https://github.com/Expensify/App/pull/34292.
### Fixed Issues

$ https://github.com/Expensify/App/issues/27977
PROPOSAL:

### Tests

Testing Replacement Rules

Code Fence:
Type: ```your text```
Expected: Text appears in a separate block formatted as code.

Inline Code Block:
Type: ``your text``
Expected: Text appears inline, formatted as code.

Email Link:
Type: test@email.com
Expected: Email address turns into a clickable mailto link.

URL Link:
Type: `https://github.com/Expensify/App/pull/34292`
Expected: Displays `https://github.com/Expensify/App/pull/34292` styled as web link (it shouldn't be clickable).

Italics
Type: _your text_
Expected: Text appears in italics.

Bold Text:
Type: *your text*
Expected: Text appears in bold.

Strikethrough Text:
Type: ~your text~
Expected: Text appears with a strikethrough.

Block Quote:
Type: > your text
Expected: Text appears as a block quote.

Heading:
Type: # Your Heading
Expected: Text appears as a large, bold heading.

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as Tests
### QA Steps

Same as Tests
- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by thienlnam** [comment]
Adding @c3024 here since he did the original review for live markdown mobile

**Comment by thienlnam** [comment]
Thanks for the PR @Skalakid, could you also copy the tests from https://github.com/Expensify/App/pull/34292 into the QA steps of the issue description so our quality assurance team can test this as well once it's deployed?

**Comment by shubham1206agra** [comment]
@Skalakid The Cursor after using mention is wrong (it doesn't update to the correct position).

**Comment by Skalakid** [comment]
@shubham1206agra I just fixed the bug with cursor positioning, it should have the correct position now

**Comment by c3024** [comment]
There is a styling warning thrown if the composer is resized with text in it.

`Warning: Removing a style property during rerender (overflowY) when a conflicting property is set (overflow) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
    at div
    at eval (webpack-internal:///./node_modules/@expensify/react-native-live-markdown/lib/module/MarkdownTextInput.web.js:80:3)
    at Composer (webpack-internal:///./src/components/Composer/index.tsx:83:20)`
    
    

https://github.com/Expensify/App/assets/102477862/f8fee1b6-f82f-4fba-ada8-8cd5fc05b19d

**Comment by shubham1206agra** [comment]
> @shubham1206agra I just fixed the bug with cursor positioning, it should have the correct position now

@Skalakid This is still not fixed for me :(.

**Comment by Skalakid** [comment]
@shubham1206agra are you testing on adhoc build? If no, try to remove `node_modules` and reinstall dependencies with `npm i`

https://github.com/Expensify/App/assets/39538890/7458984a-8dfe-41de-bdf9-d6acf198f4e8

**Comment by shubham1206agra** [comment]
@Skalakid This was on ad-hoc build only. Try using keys for selection.

**Comment by Skalakid** [comment]
@shubham1206agra can you record a video with bug reproduction, please? It will be easier to fix it

**Comment by shubham1206agra** [comment]
> @shubham1206agra can you record a video with bug reproduction, please? It will be easier to fix it

This is fixed now. An old ad-hoc build was used to test it again at that time accidentally.

**Comment by thienlnam** [comment]
Looks like we're really close - I'm going to generate one last ad hoc to ensure there's no breaking items but looks like we may even be able to merge today?

**Comment by c3024** [comment]
https://github.com/Expensify/App/assets/102477862/557d60b0-9add-4efe-a74c-f58e740b6263


https://github.com/Expensify/App/assets/102477862/9bef0389-efd7-41e5-acec-d8df280b2f4d


https://github.com/Expensify/App/assets/102477862/4013ae4c-f2af-41c1-808b-0dc0c921be70

Testing well :shipit:

**Review by thienlnam — APPROVED** [review]
Thanks, this is working great for me as well! Going to send it 🚀

**Comment by shubham1206agra** [comment]
Sorry for the late response here, but this text seems to break Markdown
```
lol > lol
```

More specifically these characters `&'"<>`.

@Skalakid Can you issue a fix to this in a follow-up PR now?

**Comment by robertKozik** [comment]
Hi @shubham1206agra I'll create the followup PR fir this issue - it will be inside `expensify-common` repo as it is parsing issue. I'll let you know when it'll be ready

**Comment by shubham1206agra** [comment]
@Skalakid @robertKozik One more thing I noticed. Copy-pasting anything multiline is inserting extra lines in between text.

**Comment by c3024** [comment]
> Copy-pasting anything multiline is inserting extra lines in between text.

I noticed this as well but this issue was on `main` even before merging this PR.

**Comment by shubham1206agra** [comment]
Interesting. It was not on staging.

**Comment by c3024** [comment]
Extra text breaks are added on staging as well. 🤔 


https://github.com/Expensify/App/assets/102477862/2868996f-96a3-4dee-ad3b-86ac7986a9a2

**Comment by shubham1206agra** [comment]
This PR is adding more lines :)
Staging:
Screenshot 2024-02-08 at 5 45 19 PM

This PR
Screenshot 2024-02-08 at 5 45 45 PM

**Comment by robertKozik** [comment]
> Sorry for the late response here, but this text inside code blocks seems to break Markdown
> 
> ```
> lol > lol
> ```
> 
> More specifically these characters `&'"<>`.
> 
> @Skalakid Can you issue a fix to this in a follow-up PR now?

@shubham1206agra  Follow up on this one - https://github.com/Expensify/expensify-common/pull/644

**Comment by situchan** [comment]
BUG (Critical): Macbook keyboard glitch on each key input in composer


https://github.com/Expensify/App/assets/108292595/4e5bed16-8893-4e40-b8e0-575f536d1973

**Comment by thienlnam** [comment]
@situchan Could you give us more details about the mac that you're experiencing this bug on? https://github.com/Expensify/App/pull/35837#issuecomment-1934868267

Model / OSX version / Browser

**Comment by situchan** [comment]
> @situchan Could you give us more details about the mac that you're experiencing this bug on? [#35837 (comment)](https://github.com/Expensify/App/pull/35837#issuecomment-1934868267)
> 
> Model / OSX version / Browser

Macbook Pro 2019 / Sonoma 14.0 / Chrome

**Pull request merged**
