### PR TITLE
Split finishReleaseCycle into two jobs

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
The `finishReleaseCycle` workflow previously only had on job which ran on `ubuntu`. However, the `bumpVersion` action relies on the macOS utility `PListBuddy`, so [it failed](https://github.com/Expensify/Expensify.cash/runs/2144100874?check_suite_focus=true). Furthermore, the `repo-sync/pull-request` action _only_ works on `ubuntu`. So this PR splits the `finishReleaseCycle` workflow into two jobs: one that runs ubuntu and another macOS.

### Fixes
Failed workflow run: https://github.com/Expensify/Expensify.cash/runs/2144100874?check_suite_focus=true

### Tests
To test this workflow, we'll need to:

1) Merge this PR
2) Close an E.cash issue labeled `StagingDeployCash`

We'll then expect that:

- [ ] An automerge PR is created from staging -> production
- [ ] A new `BUILD` version is created off master.
- [ ] An automerge PR for that new version is created w/ master as the base. Only the version files should be updated in that PR, and it should be merged.
- [ ] Tags should be pushed, and a staging deploy should happen
- [ ] A new StagingDeployCash should be triggered.

### CODE REVIEW

**Comment by roryabraham** [comment]
Note that both of these jobs will run asynchronously. I think that's fine and they don't need to be run sequentially in this case, but buddy-check.

**Review by AndrewGable — APPROVED** [review]

**Comment by AndrewGable** [comment]
I think this looks good, modeled off of the other workflow well. Skipping e2e to get this tested ASAP.

**Comment by botify** [comment]
@AndrewGable looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Comment by roryabraham** [comment]
Testing:

finishReleaseCycle workflow run: https://github.com/Expensify/Expensify.cash/actions/runs/666214402
automerge PR staging -> prod: https://github.com/Expensify/Expensify.cash/pull/1881 (was merged)
new StagingDeployCash: https://github.com/Expensify/Expensify.cash/issues/1883
new version PR against master: https://github.com/Expensify/Expensify.cash/pull/1882 (was merged)
New version staging deploy happened: 
image


- [x] An automerge PR is created from staging -> production
- [x] A new `BUILD` version is created off master.
- [x] An automerge PR for that new version is created w/ master as the base. Only the version files should be updated in that PR, and it should be merged.
- [x] Tags should be pushed, and a staging deploy should happen
- [x] A new StagingDeployCash should be triggered.

**Comment by AndrewGable** [comment]
🥳

**Pull request merged**
