### PR TITLE
[HOLD Web-Expensify #31129] PR template updated to work well with AwaitingPayment functionality

### PR DESCRIPTION
**Pull request by mountiny**
### Details

This PR is updating a pull request template to reflect needs of new webhook functionality introduced in Expensify/Web-Expensify#31129. We need to avoid using native keywords such as fixes for the issues so we do not close the external issues upon merging the PR, but we keep them open for the 7 days regression period.

cc @roryabraham

### Tests

No tests

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by Beamanator — DISMISSED** [review]
I like 👍

Are you sure we have to wait for Web-E#31129 to be merged before this one? If we merge this now, the only change is that issues won't be auto-closed when PRs are merged, right? I don't think that's a huge problem for now :D But I'm definitely happy to wait for the other PR to get merged first 👍

**Comment by mountiny** [comment]
Yes, you are right! I had this discussion about merging or not merging [here](https://expensify.slack.com/archives/C03TQ48KC/p1623860188425900) with Rafe. I would wait closer to the time the other PR will be merged as it might take couple more days and then it will also take some time before it gets to production. So I would wait for that yet.

**Comment by roryabraham** [comment]
I know we talked about this already, but I later realized that other repos (such as Web-E) use `$` as a special character to mark linked issues instead of `Fixes`. Maybe we want to follow that same pattern here for consistency?

**Comment by mountiny** [comment]
Updated!

**Review by roryabraham — APPROVED** [review]

**Review by Beamanator — APPROVED** [review]

**Comment by Beamanator** [comment]
Oof I got merge-happy, and remembered @mountiny recommended we don't merge until Web-Expensify PR#31129 is merged / closer to being merged! Shall we revert?

**Comment by mountiny** [comment]
That is a good question. I do not think it is necessary to revert but now for all the PRs created using this template the linked issues wont be automatically closed, so maybe we should let someone know.

I will try to push the other PR since it should be ready for a review!

**Comment by Beamanator** [comment]
I'll mention it in a slack channel or two :D

**Pull request merged**
