### PR TITLE
Bank account load animation issue #4696

### PR DESCRIPTION
**Pull request by Santhosh-Sellavel**
### Details
Update position of the animated gif added a new header to close the view.
Android Gif Animation was broken, update fresco version to fix it.

### Fixed Issues
$ #4696 

### Tests &QA Steps
1. Open New Expensify
2. Click "+"
3. Click "Create Workspace"
4. Click "Get Started"
5. Bank loading animation view will open

Fixes added to Bank loading animation view :
1. Added a new header with the title `One Moment`with the close button.
2. Animated image position will be moved to top-docked
3. ` One moment...` under animated image was remove to avoid redundancy

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/85645967/130668904-f704c4ef-ad94-4075-8fc0-cc0345956cdc.mov

#### Mobile Web
https://user-images.githubusercontent.com/85645967/130668951-2160c0fb-4ed5-420b-a26b-0916f5765809.mov

#### Desktop
https://user-images.githubusercontent.com/85645967/130668963-9ab921b7-5ad1-4c89-96db-66edc1a81d10.mov

#### iOS
https://user-images.githubusercontent.com/85645967/130668934-fc15c89a-11ef-49bb-a4de-4fa495a45503.mp4

#### Android
https://user-images.githubusercontent.com/85645967/130674431-b007c57c-9104-4017-8ff3-0ee0713853c9.mov

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
@Jag96 this is ready for review!

**Review by Jag96 — COMMENTED** [review]
This is looking good, I'm just having trouble getting this to run on Android. I'm seeing this error when booting the app:

```
LOG  Running "NewExpensify" with {"rootTag":1}
WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at sendDataToConnection (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:131284:46)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:131333:40)
    at tryCallOne (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:31831:16)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:31932:27)
    at apply (native)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:32372:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:32260:17)
    at _callImmediatesPass (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:32299:17)
    at callImmediates (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:32516:33)
    at __callImmediates (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:6152:35)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:5931:34)
    at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:6135:15)
    at flushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:5930:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.expensify.chat&modulesOnly=false&runModule=true:5923:33)
```

It seems to be working fine in the PR description gif, @Santhosh-Sellavel are you seeing the same thing? I have no issue running it on `main`, if you aren't seeing the issue I can ask in slack to see if anybody else can reproduce.

**Review by Jag96 — CHANGES_REQUESTED** [review]
> I facing this issue for few days because the simulator time is not updating properly when I manually update time in settings it works fine. I can reproduce the error across all branches.

@Santhosh-Sellavel can you merge main into your branch and update? I did an `npx react-native-clean-project` and that fixed the issue I encountered yesterday. I am now seeing the following issue on the CompanyStep, however, which seems to be fixed on main:

image

Once it's updated I'll fully test the VBA flow to confirm all the screens look good, thanks for bearing with me on this one!

**Review by Jag96 — APPROVED** [review]
LGTM!

**Pull request merged**
