### PR TITLE
save checkbox value to draft and button text updation

### PR DESCRIPTION
**Pull request by Pujan92**
### Details
Enable the saving draft option for the checkbox in the first step of the Connect bank account flow.
Update the button text to Continue for the first step of the Manual Bank Account Setup flow.

### Fixed Issues

$ https://github.com/Expensify/App/issues/13616   
PROPOSAL: https://github.com/Expensify/App/issues/13616#issuecomment-1366317946

### Tests

1. Select any workspace
2. Select connect bank account option
3. Click on the checkbox on the first step and go back
4. Again go to bank account option and observe the checkbox which needs to be checked
5. Verify the button text to Continue on the first step

- [X] Verify that no errors appear in the JS console

### QA Steps

1. Select any workspace
2. Select connect bank account option
3. Click on the checkbox on the first step and go back
4. Again go to bank account option and observe the checkbox which needs to be checked
5. Verify the button text to Continue on the first step

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/14358475/210451358-95b2534c-34e4-4731-b96f-f3f3a7d30093.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

mChrome

</details>

<details>
<summary>Mobile Web - Safari</summary>

mSafari

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/14358475/210451448-0da39a12-d492-4273-b3a7-6414857ec3ab.mov

</details>

<details>
<summary>iOS</summary>

Uploading ioos.mp4…

</details>

<details>
<summary>Android</summary>

[anddd.webm](https://user-images.githubusercontent.com/14358475/210452050-f85278d1-a4e2-4e56-b6a1-2edf7c832264.webm)

</details>

### CODE REVIEW

**Review by sobitneupane — COMMENTED** [review]
@Pujan92 Can you please add Tests, Offline tests and QA steps?

**Comment by Pujan92** [comment]
> @Pujan92 Can you please add Tests, Offline tests and QA steps?

Sorry, forgot to write it. Just updated.

**Comment by sobitneupane** [comment]
### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/25876548/210606769-c8c78414-929a-4397-98cb-e3d404e642df.mov


</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/25876548/210606712-390eddce-b3ae-40be-a71a-aded7ac2d770.mov


</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/25876548/210606855-c168b0b5-ddb1-4d6d-a7c5-04c06d757475.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/25876548/210608392-69bb2516-b985-4f39-b1c0-d815e2334e12.mov


</details>

**Review by sobitneupane — COMMENTED** [review]
I believe we also want to update "Save & continue" to "Continue" in following places as well:

https://github.com/Expensify/App/blob/034a6f0fcc142b81802a2c21114392833f050671/src/pages/ReimbursementAccount/BankAccountPlaidStep.js#L82

https://github.com/Expensify/App/blob/034a6f0fcc142b81802a2c21114392833f050671/src/pages/ReimbursementAccount/ReimbursementAccountForm.js#L63

But I am not sure if we want to change "Save & continue" button to "Continue" at all. Raised [here](https://expensify.slack.com/archives/C049HHMV9SM/p1672853571696859?thread_ts=1671493070.462859&cid=C049HHMV9SM).

cc: @francoisl

**Comment by Pujan92** [comment]
> But I am not sure if we want to change "Save & continue" button to "Continue" at all. Raised [here](https://expensify.slack.com/archives/C049HHMV9SM/p1672853571696859?thread_ts=1671493070.462859&cid=C049HHMV9SM).

Thanks @sobitneupane for raising this and it seems "Save & Continue" need not be changed to "Continue".

**Comment by francoisl** [comment]
Thanks for the quick PR! Looks good to me, but holding on approving for a second - asked a [clarification question in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1672871757021019?thread_ts=1671493070.462859&cid=C049HHMV9SM) here about the `Continue` button for the first step of the manual flow.

**Comment by Pujan92** [comment]
Based on the slack discussion applied the button change only for the first step of the Connect Manually flow and updated the same in the PR description.

**Review by francoisl — APPROVED** [review]

**Pull request merged**
