### PR TITLE
Fix infinite plaid spinner when coming online and other add payment method weirdness

### PR DESCRIPTION
**Pull request by ctkochan22**
@Expensify/pullerbear 

### Details
Addressing the infinite spinner that happens when going back online when adding a Personal Bank Account.

On top of this, we are going to remove disabling this button when loading personal payment methods

### Fixed Issues
$ https://github.com/Expensify/App/issues/14575

### Tests
Same as QA

### Offline tests
Included in QA

### QA Steps
1. Create an account on new dot
2. Go to Account Settings -> Payments
3. Click "Add Payment Method" so the menu option will come up, **then go offline**
4. Click and choose "Bank Account"
5. You should see a full page blocker
6. Go back online, and verify that Plaid kicks off properly

Example down in screen shots section

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://recordit.co/efD6c9iL8O

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://recordit.co/AEkSMN9OV6

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://recordit.co/9N64VhCCd8

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/12980144/216723688-a833e10b-6c36-4fa5-8996-4436e8517b93.mp4

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Review by sobitneupane — COMMENTED** [review]
Though I already have a Paypal account added, If I am offline Add Payment Method contains Paypal.me and I am allowed to add Paypal account. (When I am online Add Payment Method does not contain Paypal.me if I already have a Paypal account added.)
 
 My previous Paypal account gets replaced by newly added Paypal account when I go back online.


https://user-images.githubusercontent.com/25876548/216808581-9b0b52c7-1c8b-45da-bae2-2c15a52d65f0.mov

**Comment by ctkochan22** [comment]
> Though I already have a Paypal account added, If I am offline Add Payment Method contains Paypal.me and I am allowed to add Paypal account.

That seems like a possible bug for sure. However, can you open another PR? It doesn't seem related to adding a bank account and kicking off plaid from offline

**Comment by ctkochan22** [comment]
@sobitneupane

**Comment by ctkochan22** [comment]
@sobitneupane will you be able to test this PR please?

**Comment by sobitneupane** [comment]
@ctkochan22 Add payment method button used to be disabled when offline. So, https://github.com/Expensify/App/pull/14827#pullrequestreview-1284163438 issue was not existent before. But we are enabling Add payment method even when offline with this PR.

**Comment by sobitneupane** [comment]
### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/25876548/217162302-18dd1393-0549-4c04-8415-1f62ef9593ce.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/25876548/217163610-ab225833-5b90-48a4-aa46-0d716950eea0.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/25876548/217166304-3468a203-193a-48c8-9490-3e892a8c66f0.MP4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/25876548/217162855-1401cf6d-8ac0-4975-b2a5-2a3eb04184e6.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/25876548/217166340-e075ec69-74d8-436f-9142-0b5e33bd62b4.MP4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/25876548/217164860-17c9899f-ec97-48c0-bb06-f6c3ed7fb527.mov

</details>

**Comment by sobitneupane** [comment]
I am not sure if [this](https://github.com/Expensify/App/pull/14827#pullrequestreview-1284163438) is something we want to handle. If we consider it as an issue, we can either handle it in this PR or create another github issue to deal with it.

**Comment by ctkochan22** [comment]
Sorry @sobitneupane , circling back now. Had to hop onto an issue that required immediate attention. Looking now

**Comment by ctkochan22** [comment]
I think we should create another github for how we handle paypal offline separate from this PR.

**Comment by ctkochan22** [comment]
I don't think its a breaking bug, but I'm going to bring it up in slack and get some buy in. I think we should simply handle paypal like any other form. 

Meaning, we'll have to change a good amount of its behavior

**Comment by ctkochan22** [comment]
I may reel back this PR. Fix the spinner first

**Comment by ctkochan22** [comment]
SO I'm going to re-introduce the offline disabling of the AddPaymentsMethod button, and just remove the isLoadingPaymentMethod condition. So it'll only be disabled for when the user is offline, not when payment methods are loading

**Comment by ctkochan22** [comment]
@sobitneupane I updated the PR and tests in the description. Can you test please?

**Comment by sobitneupane** [comment]
@ctkochan22 I can still reproduce [this issue](https://github.com/Expensify/App/pull/14827#pullrequestreview-1284163438). Though I will have very short duration to do so.

Steps to Reproduce:
1. Login to Expensify
2. Go offline
3. Go to Settings > Payments
4. Go online and press "Add Payment method"
5. Press on PayPal.me and add a PayPal account


https://user-images.githubusercontent.com/25876548/219600287-8558d8ee-a16e-44a8-93a8-7c0c60bf042b.mov

In my opinion, we should not consider https://github.com/Expensify/App/issues/14681 as a bug but as an intentional behavior.

**Comment by ctkochan22** [comment]
@sobitneupane I can do this on main as well. So it shouldn't block this PR. I'll create a new GH bug for it. 

Also great find!

**Comment by ctkochan22** [comment]
Oh no you're right, it specific to this PR because I removed the loading. Lets roll back that chance and I'll bring it up in slack how we want to approach it

**Comment by ctkochan22** [comment]
Updated

**Comment by sobitneupane** [comment]
@ctkochan22 I think we should remove https://github.com/Expensify/App/issues/14681 from Fixed issues in PR body because this PR will not solve https://github.com/Expensify/App/issues/14681 issue.

**Review by sobitneupane — COMMENTED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/25876548/220015329-6a8da396-824e-432a-acbe-a61ccf95db76.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/25876548/220015348-07624012-6ca6-42cb-b688-afa2e70d26e2.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/25876548/220017391-12af3a8a-0d9d-4392-9ee7-72325202ef05.MP4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/25876548/220015552-aeda2c19-d2e8-414a-9f1a-e7ef1c6d66ba.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/25876548/220017436-4fc5d751-e21d-4016-bea3-e369104ab6ec.MP4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/25876548/220016923-c0bf16ec-4289-478f-928e-046ca69618e6.mov

</details>

**Review by sobitneupane — APPROVED** [review]

**Comment by ctkochan22** [comment]
I agree thanks

**Comment by ctkochan22** [comment]
@alex-mechler Ready for your review!

**Review by alex-mechler — APPROVED** [review]

**Comment by alex-mechler** [comment]
There was a canceled job that had timed out, reruning that to verify it passes before merging

**Pull request merged**
