### PR TITLE
Update expensify-common dependency

### PR DESCRIPTION
**Pull request by cristipaval**
### Details
This PR addresses 2 issues, that's why there are 2 sets of testing steps.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/238874
$ https://github.com/Expensify/App/issues/12511

#### Tests for handling custom subject messages
1.  Run the app
2. Open any chat and send a custom subject message like following:
    `# Test how h1 looks`
    `H1 tags now should have text of size 17px and bottom margin o size 8px`
3. Check the style of the custom subject to have text of size 17px and bottom margin of size 8px
#### Tests for markdown links with trailing spaces
Run `npm run clean` and `npm install` to get the latest markdown changes on dev.
1. Sign in with any account
2. Go to any chat
3. Paste in a markdown link with trailing spaces in the title e.x `[  test  ](https://www.expensify.com/)`
4. Verify that the link message is exactly "test" and is blue and underlined.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x]  I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

#### Web
web

#### Mobile Web - Chrome
android chrome

#### Mobile Web - Safari
ios safari

#### Desktop
desktop

#### iOS
ios native

#### Android
android native

#### Web

https://user-images.githubusercontent.com/26260477/201993666-fece3e21-619a-42ab-8804-e448b727743f.mov

#### Mobile Web - Chrome

https://user-images.githubusercontent.com/26260477/201993719-68f493a0-4eb4-475a-8f09-040dd036550c.mov

#### Mobile Web - Safari

https://user-images.githubusercontent.com/26260477/201993768-e0f643b8-1c4a-4216-8b40-14468d142ba3.mp4

#### Desktop

https://user-images.githubusercontent.com/26260477/201993851-976102ef-85ca-4bdf-95fd-467a903a6c6a.mov

#### iOS

https://user-images.githubusercontent.com/26260477/201993885-74e03ca6-a4aa-4d4c-962c-d1f6c5860f59.mp4

#### Android

https://user-images.githubusercontent.com/26260477/201993913-5da50ac6-d829-4545-a2f2-94b4054c0f2b.mov

### CODE REVIEW

**Comment by neil-marcellini** [comment]
Hey @cristipaval. I'm working on [this issue](https://github.com/Expensify/App/issues/12511) and we recently made some changes to expensify-common as well. Would you please add my issue to the fixed issues section and test these steps as well?

1. Sign in with any account
2. Go to any chat
3. Paste in a markdown link with trailing spaces in the title e.x `[  test  ](https://www.expensify.com/)`
4. Verify that the link message is exactly "test" and is blue and underlined.

**Comment by cristipaval** [comment]
> Hey @cristipaval. I'm working on [this issue](https://github.com/Expensify/App/issues/12511) and we recently made some changes to expensify-common as well. Would you please add my issue to the fixed issues section and test these steps as well?
> 
> 1. Sign in with any account
> 2. Go to any chat
> 3. Paste in a markdown link with trailing spaces in the title e.x `[  test  ](https://www.expensify.com/)`
> 4. Verify that the link message is exactly "test" and is blue and underlined.

Hey @neil-marcellini! Sure, the testing steps and the fixed issues sections are now updated. Feel free to add screenshots for your tests.

**Comment by neil-marcellini** [comment]
@cristipaval Thanks! I added screen recordings for the trailing space tests. Also please merge main to fix the conflicts.

**Comment by cristipaval** [comment]
Ready for review.

**Comment by Santhosh-Sellavel** [comment]
Will get to this tomorrow!

**Comment by Santhosh-Sellavel** [comment]
Ah sorry, I couldn't able to get this sooner!

**Comment by Santhosh-Sellavel** [comment]
Testing now!

**Comment by Santhosh-Sellavel** [comment]
Bug: An extra line was added above. 

Only the text below was sent, after sent try edit the text look there is extra line above
```
# Test how h1 looks
H1 tags now should have text of size 17px and bottom margin o size 8px
```

Uploading Screen Recording 2022-11-19 at 3.38.45 PM.mov…

**Comment by Santhosh-Sellavel** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>



</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by Santhosh-Sellavel** [comment]
@cristipaval 

Tests pass. But a doubt are we adding support for using one `#` only to just support h1, not for `##` to support `h2`?

[This](https://github.com/Expensify/App/pull/12720#issuecomment-1320851283) happens on staging also.

cc: @marcochavezf

**Review by Santhosh-Sellavel — COMMENTED** [review]
Tests pass, just need some clarification [here](https://github.com/Expensify/App/pull/12720#issuecomment-1320856206)  other wise looks good!

**Comment by cristipaval** [comment]
> @cristipaval
> 
> Tests pass. But a doubt are we adding support for using one `#` only to just support h1, not for `##` to support `h2`?
> 
> [This](https://github.com/Expensify/App/pull/12720#issuecomment-1320851283) happens on staging also, so mostly this should not blocking, but I'll wait for your answer before approving thanks!
> 
> cc: @marcochavezf

Hey @Santhosh-Sellavel ! Thanks for reviewing! No, we don't have support for `##` yet. We only support `#` (`h1`) for now because we use it for sending custom subject messages (which internally have special behaviour but you can't test it. It was tested internally).

**Comment by Santhosh-Sellavel** [comment]
Then We are good here!

**Review by Santhosh-Sellavel — APPROVED** [review]
Looks good, tests well
Over to you @marcochavezf!

**Review by marcochavezf — APPROVED** [review]

**Comment by Santhosh-Sellavel** [comment]
@cristipaval / @neil-marcellini / @marcochavezf  Can you assign a BZ here to track payment for PR review?

**Comment by neil-marcellini** [comment]
The BZ member assigned to the issue will pay you, which is @abekkala.

**Comment by abekkala** [comment]
@neil-marcellini 
> The BZ member assigned to the issue will pay you, which is @abekkala.

Was Santosh's review for GH 12511? I did payouts for that one last week but didn't see him assigned to the issue that I'm assigned to? Can I confirm what his Review payout is for? 
I was unaware that he needed a review payout for that issue as he wasn't assigned. So I need some clarification if his review payout is for that issue (12511) or if he is getting paid out via a different issue?

**Comment by Santhosh-Sellavel** [comment]
cc: @neil-marcellini @cristipaval 

> @neil-marcellini
> 
> > The BZ member assigned to the issue will pay you, which is @abekkala.
> 
> Was Santosh's review for GH 12511? I did payouts for that one last week but didn't see him assigned to the issue that I'm assigned to? Can I confirm what his Review payout is for? I was unaware that he needed a review payout for that issue as he wasn't assigned. So I need some clarification if his review payout is for that issue (12511) or if he is getting paid out via a different issue?

**Comment by neil-marcellini** [comment]
@abekkala C+ reviewers are automatically assigned to every App PR and they get paid for their review. There's no requirement for them to be assigned to the issue. In this case @Santhosh-Sellavel  should be paid for reviewing this PR, and any other PRs that he reviewed in relation to https://github.com/Expensify/App/issues/12511. Of course, he's only paid once per PR.

I had a hard time finding this process in our documentation, so please start a Slack conversation in #bug-zero about adding this to our guidelines.

**Comment by abekkala** [comment]
PR review has been Paid! 🎉

**Pull request merged**
