### PR TITLE
Convert line-breaks to spaces in LHN message preview

### LINKED ISSUE #2965: LHN - Message preview doesn't treat new line as space
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Message preview should display a space if there is a new line in the message. 

## Actual Result:
Message preview doesn't treat new line as space

## Action Performed:
1. Navigate to a conversation
2. Send this message
```
Cool
Test
Of
New line
```
3. Check the message preview in the LHN

## Workaround:
No need, visual issue. 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.47-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @puneetlath https://expensify.slack.com/archives/C01GTK53T8Q/p1621222051218200

> LHN doesn’t treat new line as a space. Notice how in the LHN image there is no space between “Hello!” and the sentence before it. But in the actual message, it is on its own line. We should treat that new line as a space when showing the text in the LHN.

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

Fixes #2965

### Tests / QA Steps
1. Navigate to a conversation
2. Send this message
```
Cool
Test
Of
New line
```
3. Check the message preview in the LHN.
4. There should be a space between newlines text in the preview.
5. Multiple new lines should only add one space.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/24370807/119172088-17efb680-ba83-11eb-80f1-da2db87bc7b2.mp4

### CODE REVIEW

**Comment by parasharrajat** [comment]
Blocker: We also need to modify the backend so that it convert <Br> to spaces while sending data from Pusher & API

**Comment by parasharrajat** [comment]
Bumping here so that blocker can be resolved. Thanks.

**Comment by parasharrajat** [comment]
@deetergp Have you got a chance to review it? And could you please tag the right guy for backend blocker. Thanks

**Comment by deetergp** [comment]
Hey @parasharrajat 👋 Been a bit swamped with other stuff, but getting up to speed on this. I'm pretty sure the answer to this is "no" but do you know whether there was a GH made for the back end portion of this? If there is, then I don't want to step on someone else's toes, but if one hasn't been made, I will put one together and probably just do the work myself. Thanks!

**Comment by deetergp** [comment]
@parasharrajat Can you explain why backend changes are needed?

**Comment by parasharrajat** [comment]
Yes. @deetergp. When we save the report using the Report_AddComment we send all the html and this ali returns a response back which includes text as well. I saw that this text is different from what we have send. Also, other user with receive the Pusher event with the message payload that also contains the text. Let me know if I am missing something here.

**Review by deetergp — APPROVED** [review]
The blocking back-end portion has been merged, un-blocking this one. We're good to go! 🎉

**Comment by isagoico** [comment]
@parasharrajat @deetergp 
We found this issue in Android and iOS apps

## 2 spaces are displayed in LHN for a line break

## Expected result
Only 1 space should be displayed for a line break

## Actual result
2 spaces are displayed for a line break 

## Action Performed 
1. Navigate to a conversation
2. Send this message
```
Cool
Test
Of
New line
```
3. Check the message preview in the LHN.

## Platform

iOS ✔️ 
Android ✔️ 

**Images/Notes/Video**

image

**Comment by isagoico** [comment]
Will open a separate issue for the above 🔝 Following Rory's comment here https://github.com/Expensify/Expensify.cash/pull/3059#issuecomment-853345313

**Pull request merged**
