### PR TITLE
Fixed tooltip pointer in left/right-aligned tooltips

### PR DESCRIPTION
**Pull request by mananjadhav**
@iwiznia  Can you please review this fix?

### Details
- Added fix to the broken pointer of the tooltip.

### Fixed Issues

$ #4499 

### Tests
1. Tested the right aligned `tooltip`

### QA Steps
1. Go to Homepage
2. Click on the Avatar to open Settings Screen
3. Check the Close(X) button  for its alignment and UI

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web
web 2
web

#### Desktop
desktop

### CODE REVIEW

**Review by iwiznia — DISMISSED** [review]

**Comment by iwiznia** [comment]
Wait, that does not look good, does it?
First, it has a weird shape on the top right, no?
image

Second, it does not seem to be positioned correctly, it's kind of far away, no?

**Comment by mananjadhav** [comment]
> Wait, that does not look good, does it?
> First, it has a weird shape on the top right, no?
> image
> 
Yeah, let me check by giving a little borderRadius than 0.

> Second, it does not seem to be positioned correctly, it's kind of far away, no?

Spacing is similar to other tooltips.

**Comment by iwiznia** [comment]
> Spacing is similar to other tooltips.

Oh ok, just in case I am tagging @Expensify/design to check it looks good

**Comment by mananjadhav** [comment]
@iwiznia Updated screenshots:

zoomed-view-tooltip
web-view
desktop-view

**Comment by iwiznia** [comment]
It still looks a bit weird, but not really sure, let's wait for design to chime in.

**Comment by shawnborton** [comment]
That still doesn't look right. You should move the pointed part of the tooltip inwards, like this:
image

**Comment by shawnborton** [comment]
cc @roryabraham on this one as I think you built the tooltip system?

**Comment by mananjadhav** [comment]
@shawnborton How does this look?

image

**Comment by shawnborton** [comment]
Hmm for some reason it doesn't look the same as the screenshot I posted. It seems like the pointed part is not as tall?

**Comment by shawnborton** [comment]
That makes sense to me, good catch on that.

**Comment by shawnborton** [comment]
Though I guess in theory, the close button should have a margin right of 20?

**Comment by mananjadhav** [comment]
> Though I guess in theory, the close button should have a margin right of 20?

Well, the pin icon has a margin of 20. Screenshot with marginRight: 20

image

Let me know which one is preferable.

**Comment by shawnborton** [comment]
20 is my vote!

**Comment by mananjadhav** [comment]
> @mananjadhav There's also the `shiftHorizontal` or `shiftVertical` props of the tooltip if you feel the need ...

Thanks, @roryabraham I did check but for some reason, the pointer and the tooltip text don't align. Is there any example where it is used?

For now, our close issue got solved because of different padding. But would want to see how it works.

**Review by iwiznia — APPROVED** [review]

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

**Pull request merged**
