### PR TITLE
Use the same logic to get the money request amount for LHN last message and report preview

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

LHN last message and report preview amount have different logic to get the amount.

LHN last message uses ReportUtils.getMoneyRequestReimbursableTotal, but the report preview uses ReportUtils.getMoneyRequestSpendBreakdown

### Fixed Issues

$ https://github.com/Expensify/App/issues/34064
PROPOSAL: https://github.com/Expensify/App/issues/34064#issuecomment-1879576434

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

1. Open a policy expense chat
2. Create a new scan money request with a valid receipt
3. Wait until the scan completes
4. Verify the amount shown in the report/IOU preview is the same as the amount written in the LHN last message.
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/50919443/dc8707c2-58f5-45cb-b555-31a72f6fc7f8

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/50919443/bbb5dfd6-3c63-4d63-827b-0479f1c38f26

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/50919443/9ba4cca7-465f-4d0e-a2f3-6e9d8de93356

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/50919443/118793de-9fa8-43e2-a2f4-350f9b8fb404

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/50919443/32199d3c-2612-4907-9aa2-c4064a3116c4

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/50919443/2e1d728c-7f31-48b4-b7b6-fd74e5aac851

</details>

### CODE REVIEW

**Comment by cubuspl42** [comment]
That's a clean little change! Are the other uses of `getMoneyRequestReimbursableTotal` fine?

**Comment by cubuspl42** [comment]
> Create a new scan money request with a valid receipt

Will any valid receipt? Isn't there some condition that triggered the different values to appear in the first place?

**Comment by bernhardoj** [comment]
> Will any valid receipt do? Isn't there some condition that triggered the different values to appear in the first place?

Yes, any valid receipt will do but the Pusher is already fixed (the last time I tested), so there is no way to trigger the different value anymore.

> Are the other uses of getMoneyRequestReimbursableTotal fine?

Most likely not. That's what I thought too about other usages of `getMoneyRequestReimbursableTotal`. I think it would make sense to replace all `getMoneyRequestReimbursableTotal` with `getMoneyRequestSpendBreakdown`, but I'm not sure.

**Comment by cubuspl42** [comment]
Please check each of the usages of `getMoneyRequestReimbursableTotal` and ensure that they do not contribute to the issue [as it is currently described](https://github.com/Expensify/App/issues/34064#issue-2068010973). If any of them do, we definitely have to fix them.

**Comment by bernhardoj** [comment]
> Please check each of the usages of getMoneyRequestReimbursableTotal and ensure that they do not contribute to the issue

The problem is that the Pusher already sends the correct data, so we actually have no real way to check it, except if we have a repro step to create a money request that will have the same amount of `nonReimbursableTotal` (positive) and `total` (negative). This is true for our last message case here too.

Btw, here are the remaining cases of `getMoneyRequestReimbursableTotal` usages.
1. [SidebarUtils #1](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/libs/SidebarUtils.ts#L202) - unused, can be removed
2. [SidebarUtils #2](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/libs/SidebarUtils.ts#L461) - unused, can be removed
3. [OptionstListUtils](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/libs/OptionsListUtils.js#L571) - unused, can be removed
4. [MoneyReportHeader](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/components/MoneyReportHeader.tsx#L55)
5. [ReportUtils.getMoneyRequestReportName](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/libs/ReportUtils.ts#L1904)
6. [ReportUtils.getIOUReportActionMessage](https://github.com/Expensify/App/blob/b542031ff0fd0cf094f775dd1ad307bb3c86eb90/src/libs/ReportUtils.ts#L2747)

For MoneyReportHeader and ReportUtils.getMoneyRequestReportName, we can see that it has the same problem from the OP video of the issue (around 0:32)

Screenshot 2024-01-22 at 19 40 54

I think we can optimistically replace all `getMoneyRequestReimbursableTotal` with `getMoneyRequestSpendBreakdown` (just like we did with last message) and remove the unused ones. What do you think?

**Comment by bernhardoj** [comment]
> We can conclude from this that fixing that fragment just lies in the scope of the issue we're supposed to fix.

We can definitely include it in the scope.

> Do I understand correctly that you have the necessary repro steps for case no. 4, but don't have for cases 5 and 6?

Nope, I don't have it for all cases.

**Comment by bernhardoj** [comment]
All cases (4, 5, 6, and last message) require this:

> a repro step to create a money request that will have the same amount of nonReimbursableTotal (positive) and total (negative).

so we can see the difference (between `getMoneyRequestSpendBreakdown` and `getMoneyRequestReimbursableTotal`) in our PR. 

So, I think the first step is, can you ask internally for the repro steps?

**Comment by bernhardoj** [comment]
> do your QA Steps fail on main and succeed on the PR branch?

It succeeds on both the main and this PR.

I just remembered that perhaps we can use the step from the [PR](https://github.com/Expensify/App/pull/29566) that implements `getMoneyRequestSpendBreakdown`.
image

It manually alters the report though.

**Comment by cubuspl42** [comment]
We're getting somewhere!

> It succeeds on both the main and this PR.

It's **not good**.

Does this step from ["Actions Performed"](https://github.com/Expensify/App/issues/34064#issue-2068010973) help in any way?

> Create a scan request with a receipt which has **different currency from the workspace default currency**

**Comment by cubuspl42** [comment]
I'm sorry; I understood we need to adjust the frontend to utilize the backend fix. I think we should switch the discussion back to the issue.

**Pull request closed without merging**
