### PR TITLE
Remove extra margin from close account button

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7378

### Tests | QA Steps
1. Open the app
2. Navigate to Settings>Security>Close Account
3. Check Close Button

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Mobile Web | Desktop

image

### CODE REVIEW

**Comment by parasharrajat** [comment]
cc: @Julesssss let me know if you are waiting for the rest of the screenshots. Otherwise it's ready.

**Comment by Julesssss** [comment]
Oh sorry, I completely missed this one.

**Comment by parasharrajat** [comment]
cc: @Julesssss This is ready for merge.

**Comment by parasharrajat** [comment]
@Julesssss I think this can be merged.

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
Yep. Sorry, I lost the issue again.

**Pull request merged**
