### PR TITLE
fix: clicking spacebar leaves highlight focus on emoji in emoji picker

### PR DESCRIPTION
**Pull request by payal-lathidadiya**
### Details
This fixes issue in emoji picker, wherein clicking on spacebar leaves selected/highlight focus on emoji. Removes highlight style for web and desktop since pressing on the emoji is expected to close the popup

### Fixed Issues
$ https://github.com/Expensify/App/issues/21806
PROPOSAL: https://github.com/Expensify/App/issues/21806#issuecomment-1613401727

### Tests

1. Open expensify on chrome web/desktop
2. Go to any chat
3. Open Emoji picker from composer
4. Use tab/arrow key to navigate in emoji list
5. While focus is on any emoji, click on spacebar from keyboard
6. Verify that it shouldn't leave highlight focus on emoji and cursor should move to search input. 

- [X] Verify that no errors appear in the JS console

### Offline tests
Same as above 

### QA Steps
Same as above 
- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/130229379/c4fbdca8-e4ff-4e65-83e9-91b2848e4c24

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/130229379/76cf7003-b62b-4d23-ac11-daa7dcd9ff02

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/130229379/a8cf87dc-f6da-4b54-945e-21ee9ce7a08d

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/130229379/886b95cb-162e-4cbc-b237-2419b97694a7

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/130229379/62e54f65-0535-4294-96c6-3cd368b13c3e

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/130229379/2c888e15-57ff-4905-824c-774cb7b36fd9

</details>

### CODE REVIEW

**Review by Julesssss — DISMISSED** [review]

**Comment by abdulrahuman5196** [comment]
@payal-lathidadiya Offline tests is also "Same as tests" since this is expected to work offline as well

**Comment by payal-lathidadiya** [comment]
> @payal-lathidadiya Offline tests is also "Same as tests" since this is expected to work offline as well

Yeah correct, it's same as test steps above.

**Comment by abdulrahuman5196** [comment]
> > @payal-lathidadiya Offline tests is also "Same as tests" since this is expected to work offline as well
> 
> Yeah correct, it's same as test steps above.

Could you update the same in author's checklist?

**Comment by abdulrahuman5196** [comment]
@Julesssss It seems we have an issue of this implementation in case of mobile devices. This approved change is removing a press feedback kind of mechanism in current behaviour.

With this PR.

https://github.com/Expensify/App/assets/46707890/47c25900-4d6f-45b5-92f6-b1be4a306ddc

Current Production behaviour.

https://github.com/Expensify/App/assets/46707890/94c2681e-7d03-454f-8e26-d9825a3862f3

**Comment by payal-lathidadiya** [comment]
> 
> Could you update the same in author's checklist?

@abdulrahuman5196 updated. thanks

**Comment by payal-lathidadiya** [comment]
> It seems we have an issue of this implementation in case of mobile devices. This approved change is removing a press feedback kind of mechanism in current behaviour.

@abdulrahuman5196 
yeah, I can see that now it won't show highlight when selected since we've removed style applied when pressed.

I'm just wondering if we should to show it since selecting emoji is going to close the picker.

Not sure if we should compare UX/behavior with other messaging apps/tools. as checked, slack doesn't show press feedback with emoji selection.

**Comment by Julesssss** [comment]
> I'm just wondering if we should to show it since selecting emoji is going to close the picker.

I would expect a native Android View to highlight when pressed, even if the modal is closed. We'll need to resolve this.

**Comment by payal-lathidadiya** [comment]
> > I'm just wondering if we should to show it since selecting emoji is going to close the picker.
> 
> I would expect a native Android View to highlight when pressed, even if the modal is closed. We'll need to resolve this.

Sure @Julesssss, I'll look into possible solution.

Do you think we should apply current solution only except native app? since original issue is only around desktop and web where we support keyboard interaction for navigating in emoji list.

Or do you have any other thoughts or input here.

**Comment by Julesssss** [comment]
We try to avoid any platform specific logic, but yeah using alternate components/files per platform with specific files is okay (for example .android)

**Comment by abdulrahuman5196** [comment]
I am not sure that will work out. Since we would still face this issue in mobile web.

**Comment by payal-lathidadiya** [comment]
> I am not sure that will work out. Since we would still face this issue in mobile web.

@Julesssss @abdulrahuman5196 
I just tried and tested by creating separate emoji picker component file for native platfroms i.e. `.native.js` and keeping existing background style for press event. It seems to be working as expected.

For mobile web, we can use our browser API i.e. `Browser.isMobile()` to keep those style to get applied for mobile web browsers.

What do you think about this approach and solution?

If looks good, I can push new updates.

**Comment by Julesssss** [comment]
@payal-lathidadiya that sounds reasonable to me 👍

**Comment by abdulrahuman5196** [comment]
@payal-lathidadiya I think we can also use `isSmallScreenWidth` prop to solve this. Could you kindly try this?

**Comment by Julesssss** [comment]
> I think we can also use isSmallScreenWidth prop to solve this. Could you kindly try this?

I don't like this solution as it is not directly associated with the client platform (r resized desktop web client would still have the bug)

**Comment by abdulrahuman5196** [comment]
>r resized desktop web client would still have the bug

I had the same doubt, but I am unable to check the same currently. So I am suggesting it just as an another option to try out to solve this issue.

**Comment by payal-lathidadiya** [comment]
Here we go! 
I've pushed new updates to fix observed issues on native and mobile platform.

Also, updated PR with fresh screen recording post testing of new updates

**Comment by payal-lathidadiya** [comment]
@abdulrahuman5196 bump for review

**Comment by abdulrahuman5196** [comment]
Will work on review today

**Review by Julesssss — APPROVED** [review]
👍

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>





https://github.com/Expensify/App/assets/46707890/7bbb9295-047b-4ac6-942a-cd5e5f4e20f3



</details>

<details>
<summary>Mobile Web - Chrome</summary>





https://github.com/Expensify/App/assets/46707890/9c53932f-dba0-4a72-91ba-468fcca6abeb


</details>

<details>
<summary>Mobile Web - Safari</summary>






https://github.com/Expensify/App/assets/46707890/2872777d-9876-40d5-843c-965cf08bbb27



</details>

<details>
<summary>Desktop</summary>





https://github.com/Expensify/App/assets/46707890/c39d516f-f6ce-4235-8764-75b8b8415dd0



</details>

<details>
<summary>iOS</summary>






https://github.com/Expensify/App/assets/46707890/8bdef482-7f04-4852-b181-496719669dc0

</details>

<details>
<summary>Android</summary>





https://github.com/Expensify/App/assets/46707890/10fb2acb-d8b0-47d4-a652-67c32d8b87e5



</details>

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours. @Julesssss Good to merge.

🎀 👀 🎀
C+ Reviewed

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
Tests well

**Pull request merged**
