### PR TITLE
removed Navigation.closeDrawer(); to fix 6908.

### PR DESCRIPTION
**Pull request by hiteshagja**
@mountiny @parasharrajat 

### Details
Removed Navigation.closeDrawser(); from navigateToConciergeChat() method to properly navigate to Concierge report.

### Fixed Issues
$ https://github.com/Expensify/App/issues/6908

### Tests
1. Login app
2. Goto any report but not Concierge
3. Goto Settings => About => click/tap on "Report a bug"

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I made sure to pull `main` before submitting my PR for review
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I ran the tests & they passed on **all platforms**
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](../PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I added comments when the code was not self explanatory
    - [x] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [x] I followed proper naming convention for platform-specific files (if applicable)
    - [x] I followed style guidelines (in [`Styling.md`](../STYLING.md)) for all style edits I made
- [x] I followed the guidelines as stated in the [Review Guidelines](../PR_REVIEW_GUIDELINES.md)

#### PR Reviewer Checklist
- [ ] I verified the Author pulled `main` before submitting the PR
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I verified tests pass on **all platforms** & I tested again on all platforms
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](../PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](../STYLING.md) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](../PR_REVIEW_GUIDELINES.md)

### QA Steps
Check all the steps in all the platforms

Scenario 1
1. Login app
2. Goto any report but not Concierge
3. Goto Settings => About => click/tap on "Report a bug"

Scenario 2
1. Login app
2. Goto any report but not Concierge
3. Write some text in message input box and send message
4. Goto another report
5. Goto Settings => About => click/tap on "Report a bug"

Scenario 3
1. Login app
2. Goto any report but not Concierge
3. Goto Settings => About => click/tap on "Report a bug"
4. Search any report and choose one

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/5493716/155571291-fb5f46b7-208e-4a2b-857b-c40f22f0f736.mp4

#### Desktop

https://user-images.githubusercontent.com/5493716/155571470-bedb0c54-6bd9-41eb-9cee-010428edf14d.mp4

#### iOS

https://user-images.githubusercontent.com/5493716/155571509-a378fe4a-f313-4da7-afec-2a86c3c8faa7.mp4

#### Android

https://user-images.githubusercontent.com/5493716/155571548-20cb399c-718d-4026-b3ab-0cf1996c7f04.mp4

### CODE REVIEW

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Please fix issue link . 
image


1. Mention to check this on all platforms in QA steps.

**Review by mountiny — COMMENTED** [review]
Please, make sure you always link the issues like: `$ https://github.com/Expensify/App/issues/6908`. I have fixed it for you, for now, it is needed for our integration pipeline. Thank you very much for keeping an eye on this for the future!

**Comment by mountiny** [comment]
Oh, @parasharrajat missed that 😅

**Comment by hiteshagja** [comment]
> Please, make sure you always link the issues like: `$ https://github.com/Expensify/App/issues/6908`. I have fixed it for you, for now, it is needed for our integration pipeline. Thank you very much for keeping an eye on this for the future!

its' my bad. 

Thank you !!

**Comment by hiteshagja** [comment]
> Please fix issue link . image
> 
> 1. Mention to check this on all platforms in QA steps.

@parasharrajat mentioned. 

Thanks

**Comment by parasharrajat** [comment]
image
:roll_eyes:

**Comment by mountiny** [comment]
I fixed it @thesahindia 😅 look at the history of the body and use the version I put in.

**Comment by thesahindia** [comment]
> I fixed it @thesahindia 😅 look at the history of the body and use the version I put in.

Oops I guess it was for @hiteshagja

**Comment by mountiny** [comment]
@thesahindia ooops sorry about this! Yes, @hiteshagja was supposed to be tagged :)

**Comment by parasharrajat** [comment]
I still see that 
image

@mountiny Could you please do that and we can merge the PR? Changes are good.

**Review by parasharrajat — APPROVED** [review]
LGTM... only the PR description needs to be fixed

cc: @mountiny 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Review by mountiny — APPROVED** [review]
Thank you @parasharrajat.

@hiteshagja remember the linking format for future, thank you:)

**Pull request merged**
