### PR TITLE
Completely remove getBetas and User_GetBetas

### PR DESCRIPTION
**Pull request by yuwenmemon**
@luacmartins please review

HOLD ON MERGING UNTIL https://github.com/Expensify/App/pull/9934 IS DEPLOYED.

### Details
Completely remove User_GetBetas from E/App. We'll want to be sure to re-test this once 

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/213881

### Tests
1. Login via an expensifail.com account, make sure that you can see the #expensifail.com domain room.
1. Login via a vanilla Gmail account, make sure that you cannot see any default rooms (make sure you have not created a workspace, but have created a policy on OldDot that you are a member of)

### CODE REVIEW

**Review by luacmartins — DISMISSED** [review]

**Review by aldo-expensify — DISMISSED** [review]

**Comment by luacmartins** [comment]
@yuwenmemon just a heads up! We'll likely remove User_getBetas from that timer before AuthenticateUser is implemented, so we should be good to merge this once https://github.com/Expensify/App/pull/9934 is merged!

**Comment by luacmartins** [comment]
@yuwenmemon https://github.com/Expensify/App/pull/9934 is merged!

**Comment by yuwenmemon** [comment]
@luacmartins Feel free to re-review!

**Review by luacmartins — APPROVED** [review]

**Comment by kavimuru** [comment]
@yuwenmemon  We don't see #[expensifail.com](http://expensifail.com/) domain room when login with expensifail account. We logged this issue and it was closed as internal QA https://github.com/Expensify/App/issues/9923#issuecomment-1187900636. Can you please confirm?
Screenshot (415)

**Pull request merged**
