### PR TITLE
Fix currency rate at reimburse expenses page

### PR DESCRIPTION
**Pull request by mateusbra**
### Details

PR fixing https://github.com/Expensify/App/issues/7780 , fix currency rate at reimburse expenses page.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7780

### Tests | QA Steps

For example:
1. Go to any Workspace
2. Click Reimburse expenses
3. Check your rate currency(within rate placeholder's text input)
4. Go back to Workspace menu
5. In the section "General settings" change on another currency
6. Go back to Workspace menu
7. Back to "Reimburse expenses" and verify that the rate is displayed in the currency you selected on item 5.

#### Contributor (PR Author) Checklist
- [x] I made sure to pull `main` before submitting my PR for review
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I ran the tests & they passed on **all platforms**
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I added comments when the code was not self explanatory
    - [x] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [x] I followed proper naming convention for platform-specific files (if applicable)
    - [x] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

#### PR Reviewer Checklist
- [ ] I verified the Author pulled `main` before submitting the PR
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I verified tests pass on **all platforms** & I tested again on all platforms
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/56851391/155587663-aae26795-39d7-412b-bd5b-1714839f4177.mp4

#### Mobile Web

https://user-images.githubusercontent.com/56851391/156064215-043ffc2c-aa75-4efc-8481-1b2156aabb7d.mp4

#### Desktop

https://user-images.githubusercontent.com/56851391/156081466-400c80a9-e0b4-4fb5-b5f4-4edff707dd44.mp4

#### iOS

https://user-images.githubusercontent.com/56851391/156072131-ef3fdb85-423a-4c05-884f-8a78144f9c52.mp4

#### Android

https://user-images.githubusercontent.com/56851391/156073943-0cf35293-b25d-4e6a-8c68-a4471679599c.mp4

### CODE REVIEW

**Comment by rushatgabhane** [comment]
#### PR Reviewer Checklist
- [ ] I verified the Author pulled `main` before submitting the PR
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I verified tests pass on **all platforms** & I tested again on all platforms
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

**Comment by rushatgabhane** [comment]
@mateusbra I think it's a good idea to explain in tests how to "check rate"
And.. we need to go back, to navigate to General Settings.

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
@mateusbra I think it's a good idea to explain in tests how to "check rate"
And that we need to go back, to navigate to General Settings.

**Comment by mateusbra** [comment]
@rushatgabhane tests section changed

**Comment by rushatgabhane** [comment]
Thanks!

@puneetlath LGTM! 🎉

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
