### PR TITLE
[IS-3218] Fixed cursor issue

### PR DESCRIPTION
**Pull request by aliabbasmalik8**
### Fixed Issues

Fixes https://github.com/Expensify/Expensify.cash/pull/3434#issuecomment-857834677

### QA Steps
1. Launch the app and log in
2. Hover over an owned message and click on the edit comment option in the menu
3. Start editing the message

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

**VIDEO:** https://recordit.co/QidiIvauZB 
#### Desktop

**VIDEO:** http://recordit.co/pyTfs5cFT9 
#### iOS

https://user-images.githubusercontent.com/31027036/121502441-2e1bd300-c9ae-11eb-8f1f-c2784d806197.mov

#### Android

https://user-images.githubusercontent.com/31027036/121499213-2c044500-c9ab-11eb-97cd-64034386e055.mp4

### CODE REVIEW

**Comment by Julesssss** [comment]
@aliabbasmalik8 can you please add tests for this PR please?

**Review by Julesssss — APPROVED** [review]
Tests well for me on Android (the platform that the crash occurred on)

**Comment by Julesssss** [comment]
All yours @Dal-Papa

**Review by Dal-Papa — APPROVED** [review]

**Comment by kavimuru** [comment]
## Tapping on Edit Message scrolls down to the bottom to the compose box

## Expected result:
User stays in the same position and is able to edit the message

## Actual result:
Tapping on Edit scrolls down the page to the compose box

## Actions Performed:
1. Launch the app and log in
2. Hover over a sent message and click on the edit comment option in the menu
3. Start editing the message

## Platform:
iOS 
mWeb 
Android ✔️

## Build:
1.0.67-0

## Notes/Images/Video:

https://user-images.githubusercontent.com/43996225/121611132-92c64480-ca25-11eb-8aaa-8c5204107ff7.mp4

**Comment by aliabbasmalik8** [comment]
@kavimuru 
I believe [this issue](https://github.com/Expensify/Expensify.cash/pull/3510#issuecomment-859161837) not due to my PR and not relate to my working issue.
it's a new issue and I tested it on android without my commits and still produce.

and it's due to when the keyboard opens then messages scroll to the bottom.
would like to fix it but want not to relate [this issue](https://github.com/Expensify/Expensify.cash/pull/3510#issuecomment-859161837) to my current work
Thanks

**Comment by isagoico** [comment]
Separate issue here https://github.com/Expensify/Expensify.cash/issues/3545

**Comment by Julesssss** [comment]
Yeah, this seems to be caused by another issue. I tested this branch in isolation and can't reproduce.

**Comment by Julesssss** [comment]
@isagoico should we remove the deployBlocker label, as it's being handled on that linked issue?

**Comment by isagoico** [comment]
Oh woops yeah, I think we should remove if the linked issue has the label already. Thanks @Julesssss 🙇‍♀️

**Pull request merged**
