### PR TITLE
Fix inverted list by applying forked version of react-native-web

### PR DESCRIPTION
**Pull request by azimgd**
I used a patched version of react-native-web with fixes for copying text into the buffer in reversed order; 

React native change: https://github.com/Expensify/react-native-web/pull/3

### Details
I have removed flatlist inversion (by inverted=true prop) which used [transform: translate] css hack and instead adding flatlist array items in reverse order [unshift instead of push]; It also reverses ScrollView event response received from browser [e.nativeEvent.configOffset *= -1];

### Fixed Issues

https://github.com/Expensify/App/issues/3381

### Tests

1. run `npm install` which will patch react-native-web package
2. `npm run web` 
3. load a chat with 200 messages
4. scrolling up and down (with debugger enabled) works fine
5. copying text into buffer preserves order

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web
https://user-images.githubusercontent.com/4882133/128644572-72213a37-820b-4465-9a2c-1eb4f3666510.mov

### CODE REVIEW

**Comment by azimgd** [comment]
@thienlnam ready for review. First https://github.com/Expensify/react-native-web/pull/3 needs to be merged.

**Comment by azimgd** [comment]
@parasharrajat @PrashantMangukiya @kidroca 

Based on your previous reports I would appreciate if you could take a look at this PR.

**Comment by azimgd** [comment]
Fixes https://github.com/Expensify/App/issues/6436 https://github.com/Expensify/App/issues/6425

**Review by kidroca — COMMENTED** [review]
We already decided against having to build this in the `postinstall` hook
It would be much better to use a prebuilt hash from our fork

Build once use the same bundle everywhere vs making everyone build it themselves

cc @thienlnam

**Comment by azimgd** [comment]
@kidroca could you link the thread with discussion here

**Comment by thienlnam** [comment]
Here's the slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1636047163494200

**Comment by thienlnam** [comment]
As discussed in the thread, going to allow this for now so we can have QA test these changes and create another issue to have it fixed.

Going to test this locally before approving / merging

**Review by thienlnam — APPROVED** [review]
Tests well for me locally

**Comment by thienlnam** [comment]
Linked the issue to update how we apply it https://github.com/Expensify/App/issues/6763

For now, this can move along and we can have QA test the changes to the virtualized list

**Comment by alex-mechler** [comment]
Reverting to solve a deploy blocker https://github.com/Expensify/App/issues/6792

**Pull request merged**
