### PR TITLE
Update react-navigation to latest versions

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
There is a bug in the react navigation library that has already been fixed and we just need to update.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/178594

### Tests

1. `npm i && npm run web`
2. Sign out of NewDot
2. Sign up for a new account in OldDot on a mobile web (small width on Chrome or iPhone user agent in safari or iOS simulator)
3. Tap the first link
4. Verify you are brought to the workspace page
5. Verify you do not see a white screen

### QA Steps
1. Sign out of NewDot
2. Sign up for a new account in OldDot on a mobile web (use actual device)
3. Tap the first link
4. Verify you are brought to the workspace page
5. Verify you do not see a white screen
6. Repeat 10+ times to verify the white screen can't happen

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]

**Review by luacmartins — APPROVED** [review]

**Review by aldo-expensify — APPROVED** [review]

**Comment by aldo-expensify** [comment]
Tested on dev, seems to work fine

**Comment by aldo-expensify** [comment]
Are we waiting for the E2E iOS tests to merge?

**Comment by roryabraham** [comment]
Yep, since we updated dependencies we should let E2E finish

**Comment by roryabraham** [comment]
Okay, E2E tests passed and the workflow run seems to be stuck on [complete job](https://github.com/Expensify/App/runs/3704325115). So I'm going to merge this.

**Comment by isagoico** [comment]
@marcaaron Will this be tested internally? We tried testing this on our side and there's only 1 option displayed for public domain accounts (gmail) and we're unable to use the applause.expensifail domain because it asks us to verify the account first 
image

**Comment by roryabraham** [comment]
@isagoico we tested this pretty thoroughly on staging, so feel free to check it off on the checklist. In the near future, we'll probably add testing for this flow to the regression suite.

**Pull request merged**
