### PR TITLE
Fix tooltip doesn't show after closing the emoji picker

### PR DESCRIPTION
**Pull request by bernhardoj**
### Fixed Issues

$ https://github.com/Expensify/App/issues/33683
$ https://github.com/Expensify/App/issues/31155
PROPOSAL:

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

Web/Desktop
1. Open status page (Settings > Profile > Status)
2. Hover over the emoji picker button
3. Verify a tooltip is shown
4. Press the emoji picker button
5. Verify the tooltip is hidden
6. Press again to close the emoji picker
7. Verify the tooltip is shown back

Web/Desktop
1. Open any chat
2. Open the emoji picker
3. Resize the browser/desktop window to small and back to large
4. Verify the emoji picker position is still shown on top of the emoji picker button

Android/iOS/mWeb
No tooltip
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/50919443/ee3d92a9-10b8-4bc6-9c68-e46bdb503be4

https://github.com/Expensify/App/assets/50919443/b6b4fb94-e894-4967-b324-6cdc62315bac

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/50919443/967037ab-5f71-4315-bc59-3ce6765a5e2e

https://github.com/Expensify/App/assets/50919443/0bc4d787-6469-4c14-9e82-1317472838ac

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
The tooltip uses `PopoverAnchorTooltip` that will hide the tooltip if the popover is currently showing. However, even after the popover is closed, the popover `isOpen` state is still true, so the tooltip stays hidden.

https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/Tooltip/PopoverAnchorTooltip.tsx#L11-L23

The reason is that, when we close the popover, the `anchorRef` object reference is not the same as the `activePopoverRef.current.anchorRef` object reference, so we return early. (notice it uses !== to compare the reference)
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/PopoverProvider/index.tsx#L15-L26

Why is it different?
`getEmojiPopoverAnchor` will return either the local ref or the ref of the element (the button). 
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/EmojiPicker/EmojiPicker.js#L47

When we show the emoji picker, the popover provider will store the ref of the element.

When we try to close the emoji picker, we immediately clear the ref, so `getEmojiPopoverAnchor` will return the local ref now.
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/EmojiPicker/EmojiPicker.js#L85-L91

And because of that, `PopoverWithoutOverlay` will call `closePopover/close` with the local ref.
https://github.com/Expensify/App/blob/573f6b7005d67e5f8ec83e2efa64fb8d3b9902d2/src/components/PopoverWithoutOverlay/index.tsx#L55-L59

So, local ref object !== emoji picker button ref object.

I think we can consider this one as not a regression, but rather discovering a hidden bug. The real issue here is that we pass a different ref to `closePopover`. This doesn't happen before because we compare the ref object reference, but still in the previous code, we have a different ref value.

In the previous code, when we show the emoji picker, the popover will store the ref as:
`{current: buttonElement}`

And when we close the emoji picker, we pass `{current: null}` to `closePopover`.

Notice the ref value is already different, but it still works because the object reference is the same.

The solution is to avoid the ref being updated before the popover is completely hidden.

**Comment by shubham1206agra** [comment]
@bernhardoj There's seems to be a problem with your approach

### Current

https://github.com/Expensify/App/assets/58412969/4d8cb677-36fc-4c34-99dc-7115580a5742

### This PR

https://github.com/Expensify/App/assets/58412969/fa4337b0-28fb-46ba-8639-2a44d7e0e4f5

### Mine approach in https://github.com/Expensify/App/issues/33683#issuecomment-1870799648

https://github.com/Expensify/App/assets/58412969/df34be38-562d-4210-a85b-c297d6a7394f

This approach (i.e., the current logic for hiding the modal) was added to https://github.com/Expensify/App/pull/7580.

**Comment by shubham1206agra** [comment]
> I think we can consider this one as not a regression, but rather discovering a hidden bug.

I strongly believe this is a regression, but its a easy to miss bug as you are not testing this behavior at all in the first place. (If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App)

**Comment by bernhardoj** [comment]
Thanks for catching that. I didn't realize `onModalHide` will be called when the popover changes from PopoverWithoutOverlay to Modal.

I have pushed a new fix (which is still based on my previous fix because it fixes the root cause of the issue).

**Comment by shubham1206agra** [comment]
@bernhardoj I believe you need to fix reassure test too

**Comment by bernhardoj** [comment]
@shubham1206agra it fails on `main` too

**Comment by bernhardoj** [comment]
Checking

**Comment by bernhardoj** [comment]
I don't know how long the delay in https://github.com/Expensify/App/issues/33873, but did feel the delay a little bit (~ 1s), so I tried switching my branch to the previous PR branch and the delay is gone, so the issue is not from our PR.

I reverting one by one commits and the delay is gone when reverting this one https://github.com/Expensify/App/pull/32551.

**Comment by bernhardoj** [comment]
Unrelated, already happens before the PR.

**Comment by bernhardoj** [comment]
@aimane-chnaif don't forget to check this one

**Comment by bernhardoj** [comment]
Thanks for catching that. I think I forgot to restest it after addressing this [issue](https://github.com/Expensify/App/pull/33690#issuecomment-1872461096).

The `onModalHide` here is undefined
https://github.com/Expensify/App/blob/6a6b5fcf607adf672dcceca921ba0c9078677be5/src/components/EmojiPicker/EmojiPickerButtonDropdown.js#L39

We can have a default props for it, but to be very safe, I think it's better to check whether the hide callback is not undefined before calling it.

**Review by aimane-chnaif — APPROVED** [review]

**Review by neil-marcellini — APPROVED** [review]
Looks good. Can we also included tests and QA for resizing, and upload a video of that before merging?

**Comment by bernhardoj** [comment]
@neil-marcellini added

**Review by neil-marcellini — APPROVED** [review]
Great thanks!

**Pull request merged**
