### PR TITLE
make workspace message scrollable

### PR DESCRIPTION
**Pull request by thesahindia**
### Details

Made the message box scrollable 
Made the box fit atleast 3 lines comfortably.
### Fixed Issues

$ https://github.com/Expensify/App/issues/6594

### QA Steps

1. Go to any Workspace
2. Go to Manage members
3. Tap invite member
4. Add text in "add a personal message" box 
5. Scroll inside message box
### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/83179295/145576842-ccf50ba2-404d-4188-879e-dbcfd7f1e293.mp4

#### Mobile Web

https://user-images.githubusercontent.com/83179295/145576874-b80d1170-4dc4-4b15-9ab4-1029e27500af.mp4

#### Desktop

https://user-images.githubusercontent.com/83179295/145576791-c0ec8c87-08a6-4fbd-8aca-3e5186b4e7a8.mp4

#### iOS

https://user-images.githubusercontent.com/83179295/145576757-1d020a71-1055-4f9e-b79c-26b8e019006f.mp4

#### Android

https://user-images.githubusercontent.com/83179295/145576706-cabba0f4-bf08-4398-a8b6-ffc5935f9ebf.mp4

### CODE REVIEW

**Comment by parasharrajat** [comment]
Looks like the label and Value gap is little much on IOS. Could you please look into that?
Also, I am expecting to see a video testing of various pages for each platform to make sure there are no regressions. I am not able to remember why height:100% was added. Thanks

**Comment by thesahindia** [comment]
> Looks like the label and Value gap is little much on IOS. Could you please look into that? 

@parasharrajat, Looking into that problem.. but it's not a regression from this pr as even with `height:100%` it's still the same.

-> without any changes
Screenshot 2021-12-10 at 4 08 13 PM

Also, will add the testing videos of remaining platforms soon.

**Comment by parasharrajat** [comment]
Thanks for the videos @thesahindia. Ok, I have found the reason why height:100% was added here. When the input is auto-filled, it is used to cover the whole area including the border. Thus highlighted border was getting hidden.  Could you please test it and show me a clip/screenshot of that working fine?

**Comment by thesahindia** [comment]
@parasharrajat, It's working fine. 
Here's a screenshot -
Screenshot 2021-12-12 at 9 17 52 PM

**Review by parasharrajat — APPROVED** [review]
LGTM. Thanks for your patience. 

cc: @chiragsalian

**Review by chiragsalian — APPROVED** [review]
LGTM

**Pull request merged**
