### PR TITLE
Add Jest unit tests and Detox end to end tests

### PR DESCRIPTION
**Pull request by AndrewGable**
@tgolen @marcaaron - Will you please review? 

Adds test two frameworks to RNC repo, [`jest`](https://jestjs.io/en/) unit tests and [`detox`](https://github.com/wix/Detox) e2e tests. While the tests are sparse at the moment, I hope they enable the ability to add future tests that will grow into a valuable addition.

### CODE REVIEW

**Review by tgolen — DISMISSED** [review]

**Review by marcaaron — DISMISSED** [review]
Looks awesome!!

**Review by sketchydroide — DISMISSED** [review]
LGTM
In all honesty this is hard to understand, but from I could understand it looks good.

**Review by marcaaron — APPROVED** [review]
Looks great!

**Review by sketchydroide — COMMENTED** [review]
LGTM

**Pull request merged**
