### PR TITLE
Disable save button after saving self-select pronoun with a sapce

### PR DESCRIPTION
**Pull request by sobitneupane**
### Details

After saving self-select pronoun with space, the Save button was not disabled. The issue is fixed by making proper change in the variable that determines whether the button should be disabled or not.
### Fixed Issues

$ https://github.com/Expensify/App/issues/7147

### Tests

- [ ] Go to Profile
- [ ] Select "Self-select" in Preferred pronouns field.
- [ ] Enter preferred pronoun with space at the end.
- [ ] Click Save button.

### QA Steps

- [ ] Go to Profile
- [ ] Select "Self-select" in Preferred pronouns field.
- [ ] Enter preferred pronoun with space at the end.
- [ ] Click Save button.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

#### Web

Screenshot from 2022-01-14 13-55-03

#### Mobile Web

Screenshot_20220114-140753_Chrome

#### Android

Screenshot_20220114-135917_New Expensify

### CODE REVIEW

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Looks good. Could you please update the line 164 as well. 
```js
 const [hasFirstNameError, hasLastNameError, hasPronounError] = ValidationUtils.doesFailCharacterLimit(50, [this.state.firstName.trim(), this.state.lastName.trim(), this.state.pronouns.trim()]);
```

**Comment by sobitneupane** [comment]
> Looks good. Could you please update the line 164 as well.
> 
> ```js
>  const [hasFirstNameError, hasLastNameError, hasPronounError] = ValidationUtils.doesFailCharacterLimit(50, [this.state.firstName.trim(), this.state.lastName.trim(), this.state.pronouns.trim()]);
> ```

@parasharrajat Updated.

**Review by parasharrajat — APPROVED** [review]
LGTM.

cc: @Luke9389 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Review by Luke9389 — APPROVED** [review]
Thanks @parasharrajat & @sobitneupane!

**Pull request merged**
