### PR TITLE
Fix MulitpleAvatars alignment

### PR DESCRIPTION
**Pull request by DrLoopFall**
### Details
Replace `left` with `margin-left` for positioning `MultipleAvatars`, which removes the need for calculating the `width`, removing the issues caused by the wrong calculation of the `width`.

### Fixed Issues

$ https://github.com/Expensify/App/issues/22632
PROPOSAL: https://github.com/Expensify/App/issues/22632#issuecomment-1631418875

#### Case 1:  Workspace icons are aligned to the left #22632

1. Open settings.
2. Create 5 or more Workspaces if needed.
3. Check the avatars in the Workspaces menu item.
4. Verify if the avatars are properly aligned.

#### Case 2: Avatars group on final screen moves to the left if admin invites more 8 users #22685

1. Go to the existing or create a new workspace.
2. Go to Workspace > Members.
3. Click / Tap 'Invite'.
4. Select more than 8 users.
5. Click 'Next'.
6. Verify if the avatars are properly center aligned.

#### Case 3: Split bill icons are aligned to the left #22993

1. Split bill with 8 users.
2. Check the icons on the split bill report.
3. Verify if the avatars are properly aligned.  

#### Case 4:  Multiple avatars in group

1. Create a group of five or more.
2. Verify if the avatars are properly aligned.

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

#### Case 1:  Workspace icons are aligned to the left #22632

1. Open settings.
2. Create 5 or more Workspaces if needed.
3. Check the avatars in the Workspaces menu item.
4. Verify if the avatars are properly aligned.

#### Case 2: Avatars group on final screen moves to the left if admin invites more 8 users #22685

1. Go to the existing or create a new workspace.
2. Go to Workspace > Members.
3. Click / Tap 'Invite'.
4. Select more than 8 users.
5. Click 'Next'.
6. Verify if the avatars are properly center aligned.

#### Case 3: Split bill icons are aligned to the left #22993

1. Split bill with 8 users.
2. Check the icons on the split bill report.
3. Verify if the avatars are properly aligned.  

#### Case 4:  Multiple avatars in group

1. Create a group of five or more.
2. Verify if the avatars are properly aligned.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

**Case 1**
Screenshot 2023-07-25 at 11 17 43 PM

**Case 2**
Screenshot 2023-07-26 at 3 43 50 PM

**Case 3 & 4**
Screenshot 2023-07-26 at 3 37 55 PM

</details>

<details>
<summary>Mobile Web - Chrome</summary>

**Case 1**
Screenshot_1690306356

**Case 2**
Screenshot_1690371982

**Case 3 & 4**
Screenshot_1690371925

</details>

<details>
<summary>Mobile Web - Safari</summary>

**Case 1**
Simulator Screenshot - iPhone 14 - 2023-07-25 at 23 13 08

**Case 2**
Simulator Screenshot - iPhone 14 - 2023-07-26 at 17 08 33

**Case 3 & 4**
Simulator Screenshot - iPhone 14 - 2023-07-26 at 17 07 30

</details>

<details>
<summary>Desktop</summary>

**Case 1**
Screenshot 2023-07-25 at 11 23 48 PM

**Case 2**
Screenshot 2023-07-26 at 4 42 56 PM

**Case 3 & 4**
Screenshot 2023-07-26 at 4 40 44 PM

</details>

<details>
<summary>iOS</summary>

**Case 1**
Simulator Screenshot - iPhone 14 - 2023-07-25 at 23 07 40

**Case 2**
Simulator Screenshot - iPhone 14 - 2023-07-26 at 17 05 13

**Case 3 & 4**
Simulator Screenshot - iPhone 14 - 2023-07-26 at 16 45 47

</details>

<details>
<summary>Android</summary>

**Case 1**
Screenshot_1690306030

**Case 2**
Screenshot_1690372556

**Case 3 & 4**
Screenshot_1690372485

</details>

### CODE REVIEW

**Review by sobitneupane — COMMENTED** [review]
@DrLoopFall Can you please add other test cases as well. We are making use of MultipleAvatars with shouldStackHorizontally true in many places. We should verify that it's working fine in all those places.

**Comment by DrLoopFall** [comment]
@sobitneupane I've added tests for other cases with relevant screenshots, please check it.

**Review by sobitneupane — COMMENTED** [review]
### Screenshots/Videos
<details>
<summary>Web</summary>

Screenshot 2023-07-27 at 14 09 16
Screenshot 2023-07-27 at 14 09 45
Screenshot 2023-07-27 at 14 10 11


Screenshot 2023-07-27 at 14 10 31
Screenshot 2023-07-27 at 14 10 56
Screenshot 2023-07-27 at 14 11 13
Screenshot 2023-07-27 at 14 11 51
Screenshot 2023-07-27 at 14 12 13
Screenshot 2023-07-27 at 14 12 42
Screenshot 2023-07-27 at 14 27 25
Screenshot 2023-07-27 at 14 28 58


</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>


Screenshot 2023-07-27 at 14 23 04
Screenshot 2023-07-27 at 14 23 15

Screenshot 2023-07-27 at 14 23 30
Screenshot 2023-07-27 at 14 24 05
Screenshot 2023-07-27 at 14 24 26

Screenshot 2023-07-27 at 14 27 49

</details>

<details>
<summary>Desktop</summary>
Screenshot 2023-07-27 at 14 25 11
Screenshot 2023-07-27 at 14 25 28
Screenshot 2023-07-27 at 14 25 44
Screenshot 2023-07-27 at 14 25 55
Screenshot 2023-07-27 at 14 26 07
Screenshot 2023-07-27 at 14 26 44
Screenshot 2023-07-27 at 14 27 12

</details>

<details>
<summary>iOS</summary>

simulator_screenshot_5CFF535A-9568-4B5C-A8BC-58225C43C013

simulator_screenshot_899F8204-8606-43A6-9B23-E165BF0F8EBB
Screenshot 2023-07-27 at 14 20 25
Screenshot 2023-07-27 at 14 20 40
Screenshot 2023-07-27 at 14 20 59
Screenshot 2023-07-27 at 14 21 39


Screenshot 2023-07-27 at 14 28 07
Screenshot 2023-07-27 at 14 29 27


</details>

<details>
<summary>Android</summary>
Screenshot 2023-07-27 at 14 14 16
Screenshot 2023-07-27 at 14 14 58
Screenshot 2023-07-27 at 14 16 34

Screenshot 2023-07-27 at 14 16 53
Screenshot 2023-07-27 at 14 17 20
Screenshot 2023-07-27 at 14 17 51
Screenshot 2023-07-27 at 14 18 33
Screenshot 2023-07-27 at 14 29 20



</details>

**Review by sobitneupane — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

**Review by Li357 — APPROVED** [review]
LGTM, thanks for addressing the root cause and slimming the code!

**Pull request merged**
