### PR TITLE
Enable comma-dangle ESLint rule

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
This enables the ESLint rule to enforce our written style guide rule that multiline objects and arrays should always have a trailing comma. 

### Fixed Issues
https://github.com/Expensify/Expensify/issues/149302

### Tests
1. Run `npm run lint` on a file with a multiline object, correctly formatted with trailing commas.
2. Remove the trailing comma from any multiline object or array
3. Then run `npm run lint`, and observe the desired lint error appear.
4. Run `./node_modules/.bin/eslint --fix 'src/**/*.js'`, and see that trailing commas are added to automatically resolve the new lint errors.

### Tested On

**Note:** This was simply tested in the IDE, and affects non-critical code style changes.

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots
No UI changes.

### CODE REVIEW

**Comment by marcaaron** [comment]
@roryabraham might be easier to just merge this with style failing and then have people fix these when they touch the files

**Comment by roryabraham** [comment]
> might be easier to just merge this with style failing and then have people fix these when they touch the files

only reason I didn't want to do this is because the lint errors will show up on everyone's PRs

**Review by marcaaron — DISMISSED** [review]

**Comment by marcaaron** [comment]
There is an empty file I think maybe this was not merged correctly or what exactly is happening here?

Screen Shot 2021-01-04 at 11 50 01 AM

**Comment by marcaaron** [comment]
>only reason I didn't want to do this is because the lint errors will show up on everyone's PRs

Ok that's fine. Personally, I think it's just better to have people fix their PRs and we'll get to the comma dangle when we get to them vs. give everyone with an open PR conflicts by merging this, but it's NAB.

**Comment by roryabraham** [comment]
Removed the empty file. It's not present on master

**Review by marcaaron — APPROVED** [review]

**Review by marcaaron — APPROVED** [review]

**Pull request merged**
