### PR TITLE
Add encrypted App Store Connect API json file and use for fastlane upload

### PR DESCRIPTION
**Pull request by timszot**
### Details
<Explanation of the change or anything fishy that is going on>
Adds an encrypted json file that contains the App Store Connect API key for fastlane to use when uploading the build per https://github.com/Expensify/Expensify/issues/151900#issuecomment-772111266

Don't want to auto-close the issue as there is still more work for Mobile-Expensify
Reference https://github.com/Expensify/Expensify/issues/151900

### Tests
None. We'll test this once it's merged and see if the build succeeds.

### CODE REVIEW

**Review by AndrewGable — COMMENTED** [review]
Should we remove this line? https://github.com/Expensify/Expensify.cash/pull/1395/files#diff-fc40e39603744467ec4d9d7cb6c3bd67756ec09c037d03f3655904fc1c6bcfdaR52

**Comment by timszot** [comment]
> Should we remove this line?

I don't think that link is working.... It's not pointing me to a specific line when I click it.

**Comment by AndrewGable** [comment]
```yml
- name: Run Fastlane
    run: bundle exec fastlane ios beta
    env:  
----->  FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
```

`FASTLANE_PASSWORD` since we have to use API key now?

**Comment by timszot** [comment]
Updated

**Review by AndrewGable — APPROVED** [review]

**Review by chiragsalian — APPROVED** [review]

**Comment by timszot** [comment]
Self merging since it's all approved.

**Pull request merged**
