### PR TITLE
Fix : Chat moves up a bit when new message is received

### PR DESCRIPTION
**Pull request by ahmdshrif**
### Details

* fix Chat moves up a bit when new message is received for ios 

### Fixed Issues

$ https://github.com/Expensify/App/issues/7145

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open a room and scroll to earlier message (fastly)
2. Stay on specific message (to read it or something)
3. Send new message to that room
4. Verify that chat view is not moving around when new message is received

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/21364901/149676476-0f649c70-ebe4-4b28-af9b-c2048a52e082.mov

#### Mobile Web

https://user-images.githubusercontent.com/21364901/149676384-8a6bc7ee-9f00-4df0-825b-054b28da6d9d.mp4

#### Desktop

https://user-images.githubusercontent.com/21364901/149676613-cebc7ed1-e137-4559-9c83-eec8d7d51594.mov

#### iOS

https://user-images.githubusercontent.com/21364901/149667812-8a6e9aad-22b9-42c2-b836-04b1c219a77f.mov

### CODE REVIEW

**Review by mountiny — COMMENTED** [review]
Looks good to me! Good find here @ahmdshrif:)

I will wait for Rushat to test this and approve it before going ahead.

**Comment by rushatgabhane** [comment]
I'm testing for regressions. Meanwhile, @ahmdshrif please add screenshots for all platforms. Thanks a lot! 😃

**Comment by ahmdshrif** [comment]
@rushatgabhane  I have already included a video for all platforms except android since it still has the issue.

**Comment by rushatgabhane** [comment]
@mountiny  LGTM! Couldn't find any regressions.

**Review by rushatgabhane — DISMISSED** [review]
@mountiny Looks good to me too! Couldn't find any regressions.

**Review by mountiny — DISMISSED** [review]
Nice! Thank you very much @rushatgabhane and @ahmdshrif!

:shipit:

**Comment by mountiny** [comment]
Yikes, I cant merge this as your commit is not signed it seems @ahmdshrif :/

Would you be able to follow these instructions and I guess force push to this branch to sign the commit. https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request

Thank you!

**Comment by ahmdshrif** [comment]
@mountiny  ok, I signed it and delete the not-signed commit.

**Review by mountiny — DISMISSED** [review]
Thank you @ahmdshrif!

**Review by rushatgabhane — DISMISSED** [review]

**Comment by ahmdshrif** [comment]
sorry for that again. but my commit was signed but was not verified so I again push force verified sign commit and that dismiss your reviews. 
@mountiny  @rushatgabhane

**Review by rushatgabhane — APPROVED** [review]

**Comment by mountiny** [comment]
Thank you!

**Review by mountiny — APPROVED** [review]

**Comment by mountiny** [comment]
Test passed so going ahead and merging.

**Comment by kbecciv** [comment]
@ahmdshrif @rushatgabhane @r8 The issue is reproduced during Regression. Reopening the issue https://github.com/Expensify/App/issues/7145

https://user-images.githubusercontent.com/93399543/150171440-e31ae6ad-8c33-4408-a3ee-8fca5b37fdb9.mp4

**Comment by ahmdshrif** [comment]
@kbecciv think the issue is defined on android and ios only.

> ## Platform:
> Where is this issue occurring?
> 
> * iOS
> * Android
> 
> **Version Number:** 1.1.27-0 **Reproducible in staging?:** Y **Reproducible in production?:** Y **Logs:** https://stackoverflow.com/c/expensify/questions/4856 **Notes/Photos/Videos:** Any additional supporting documentation
> 
>  RPReplay_Final1641962371.MP4 
> **Expensify/Expensify Issue URL:** **Issue reported by:** @K4tsuki **Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1641188993370400

**Comment by rushatgabhane** [comment]
@ahmdshrif mWeb was working before. Not it isn't. Let's find why this is happening

**Comment by rushatgabhane** [comment]
Alright, this issue is happening on Safari only. 
It is happening on main too.

**Comment by ahmdshrif** [comment]
Yes i test it on mobile (not safari) work 

Uploading Screen_Recording_20220119-194225_Samsung Internet.mp4 …

**Comment by rushatgabhane** [comment]
@ahmdshrif any ideas how to fix this?

**Comment by mountiny** [comment]
Yeah, we have missed that case to test, maybe we should explicitly state it in the PR checklist too. Would you be able to look into the safari issue @ahmdshrif, please?

**Comment by ahmdshrif** [comment]
@mountiny  @rushatgabhane 
I try to debug this but do not have a solution for now. it looks like the `flatlist` for web use something not supported on safari. 

I test it with and without my code. it's happened on safari in both cases.

**Comment by mountiny** [comment]
Alright, that is a shame safari is causing such problems for us. I guess we will need to follow up with this later on if there is not a clear solution for this.

**Comment by mountiny** [comment]
Ok, I have created a follow-up issue, since I would say this has not been clearly stated before and we should not hold the payment of the linked issue on this regression. This is an edge case that will require additional treatment. https://github.com/Expensify/App/issues/7334

**Comment by rushatgabhane** [comment]
Thanks!

**Comment by ahmdshrif** [comment]
thanks, mountiny  rushatgabhane

**Pull request merged**
