### PR TITLE
Upgrade Gradle Distribution to 6.8

### PR DESCRIPTION
**Pull request by dylmye**
### Details
When trying to build the app for Android 11, the following issue occurs:

> Error:Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

This fix, identified in [this stackoverflow answer](https://stackoverflow.com/a/60850178), resolves the error.

The [latest version of Gradle](https://gradle.org/releases/) at the time of writing is 6.7.1. I'm not fully sure how gradle versions and Android compatibility are connected so I've just gone with the version that people have agreed works.

### Fixed Issues
n/a

### Tests
* Tested on Windows 10 with Android 11 (API level 30) emulator + system image. Android app builds successfully.

This change does not affect any other platforms as it is android-specific.

Java version printout:
```
java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

### Tested On

- [x] Android

### Screenshots
n/a

### CODE REVIEW

**Comment by dylmye** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dylmye** [comment]
recheck

**Comment by dylmye** [comment]
Updated

**Comment by sketchydroide** [comment]
CCing @Julesssss as he knows more about this than me. In principle this seems ok. But would prefer to ask someone with more Android to give it a look as well.

**Comment by Julesssss** [comment]
My only comment would be that we should take this opportunity to update both Gradle and the Gradle plugin to the latest version now. But given the context of blocking development this also seems fine.

Any thoughts @AndrewGable ?

**Comment by AndrewGable** [comment]
I agree that we should just update both to latest 👍

**Comment by sketchydroide** [comment]
Ok seems like we have an agreement then. @dylmye can you please update both Gradle and the Gradle plugin to the latest version.
Thanks

**Comment by Julesssss** [comment]
Thanks for this @dylmye, let us know if you have any questions!

**Comment by dylmye** [comment]
I just need to test this (having some issue with my virtualisation/SVM), but I upgraded to Gradle 6.8. According to [this page](https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle), the plugin version to use is 4.1.0. Dependency [react-native-config has been updated](https://github.com/luggit/react-native-config/pull/512) to enable support for plugin 4.1.0.

**Comment by dylmye** [comment]
Confirmed working on my setup, please can anyone else clone this branch and confirm it's working for them?

image

**Comment by dylmye** [comment]
bump

**Review by AndrewGable — APPROVED** [review]
Looks great, thanks! I will let @sketchydroide merge.

**Review by sketchydroide — APPROVED** [review]
LGTM

**Pull request merged**
