### PR TITLE
Update getPullRequestsMergedBetween to run pre-set string command

### PR DESCRIPTION
**Pull request by Jag96**
@roryabraham will you please review this
cc @AndrewGable 

### Details
This PR attempts to fix an issue where when a CP happens, the `toRef` is set to an empty string, even though it is being logged out properly beforehand. Came up with this approach after looking at [this SO](https://stackoverflow.com/questions/37331797/can-i-pass-a-variable-in-javascript-to-a-child-process-exec-command) and seeing that our other usages of `execSync` only set variables that are separated by spaces, so perhaps there is an issue in this case. I also added a log line that will spit out the command to ensure that the string is what we expect it to be.

### Fixed Issues

Related to https://github.com/Expensify/Expensify/issues/168349, possibly a fix 🤞 

### Tests
1. Merge this PR
2. With a staging deploy checklist open, CP a new PR
3. Confirm that the deploy checklist issue description isn't updated with PRs that aren't on staging

I ran tests locally to confirm that the function still works as expected:

image

### QA Steps
None

### Screenshots
N/A

### CODE REVIEW

**Comment by aldo-expensify** [comment]
@Jag96 from what I see, and I think this what you wanted to achieve, this is logging some extra stuff and not changing the return of the function. But unfortunately due to my lack of experience in the area, I don't know how to test this! Feel free to remove me and find someone else that can give you a better input about this if you need :)

**Review by roryabraham — APPROVED** [review]
Definitely worth a shot! Let's test this on the next checklist by CPing it as soon as the checklist is locked.

**Comment by roryabraham** [comment]
cc @isagoico because I know you'll be more stoked about this than anyone if it works.

**Review by aldo-expensify — APPROVED** [review]
I ran the test local test and confirmed that it is working. I'll let the merge to you guys because I'm not familiarized enough with the process to test it in staging.

**Comment by Jag96** [comment]
For context, we're holding off on merging this until we have a fresh checklist to confirm the issue is fixed. Putting this on HOLD for now

**Comment by Jag96** [comment]
Going to CP this to Staging before the prod deploy

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
