### PR TITLE
Close AddressSearch results on blur

### PR DESCRIPTION
**Pull request by aldo-expensify**
### Details

- Remove `keepResultsAfterBlur` prop from `GooglePlacesAutocomplete` so it closes on blur
- Pass down `event` to `onBlur` and `onFocus` in `BaseExpensiTextInput`. `GooglePlacesAutocomplete` will pass an `onBlur` callback that checks if the focus is changing to a result on blur. If we don't pass the `event` parameter, it fails to check that and closes the results list too soon.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/181023

### Tests / QA

1. Sign in to New Dot with a new account
2. Create a new workspace
3. Connect a new bank account
    Routing number: 123123123
    Account Number: 1111222233331111
4. Hit enter, you should get to the Company Information page
5. Start typing a `Company address`, you should see some suggested addresses appearing.
6. Don't click any, click another field.
7. The list of suggested addresses should disappear (close on blur).
8. Start typing again in the `Company address` field and select one of the results
9. The result list should disappear and the `Company address` should have the value of the selected result.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/87341702/137223293-4f05242f-82e2-47cb-8982-ea0461057f12.mov

### CODE REVIEW

**Comment by aldo-expensify** [comment]
Should I put `CP-Label` in this?

**Review by Luke9389 — COMMENTED** [review]
Would you be sure to test this on the date picker as well? We pass an onFocus prop there and I just want to double-check that it works still.

**Comment by aldo-expensify** [comment]
> Nice! It looks like this fixes the gray bar under the field too right?

hmm not exactly.. the gray bar appear less now because we close the results on blur, but you will still see it if you do:

1. type something in `Company address`
2. select result
3. click the `Company address` field again (focus)

The gray bar will be there because it is focused and there are no results

**Comment by Luke9389** [comment]
But it's good that the gray bar is showing far less often!

**Comment by aldo-expensify** [comment]
> K, I'm testing on android rigtht now. Wanna do iOS?

sure!

**Comment by aldo-expensify** [comment]
There is this ugly bug when we reload the page during the `Company step`:


https://user-images.githubusercontent.com/87341702/137230266-e6c60a2c-34f4-47b6-9e45-7b50b1b91a72.mov

but I think that was there from before and we should make a different GH issue for it. I would think it is probably related to how we store/read the draft? info.

**Review by Luke9389 — APPROVED** [review]

**Pull request merged**
