### PR TITLE
Mobile Selection Mode

### PR DESCRIPTION
**Pull request by filip-solecki**
### Details

This PR add new Selection Mode on small devices on a few pages listed in the main issue. It is already implemented on the Search page but has to be refactored to add possibility to use it in tho whole app. 
### Fixed Issues

$ https://github.com/Expensify/App/issues/45451
PROPOSAL:

### Tests

<details>
<summary>Workspace Members</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Members (as an admin)
4. Add a few members if you are alone
5. Long press on some item
6. Chose "Select"
7. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Distance Rates</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Distance Rates (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few distance rates if there is only one rate
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Categories</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Categories (as an admin)
4. Turn it on in `More features` if not enabled
5. Long press on some item
6. Chose "Select"
7. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace multi level Tags</summary>
1. Log in to OD
2. Go to Workspace settings
3. Go to Tags and enable it if not enabled
4. Enable `People must tag expenses` and `Use multiple level of tags`
5. Import some multi level Tags (eh. [this](https://github.com/Expensify/App/files/15195760/Independent%2Bwithout%2BGL%2Bcodes%2Bformat.csv) )
6. Go to ND
7. Go to the same Workspace and Tags page
8. You should not be able to select any Tag on main page
9. Go to Tag details
10. You'll see Tags inside 
11. Long press on some item
12. Chose "Select"
13. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace single level Tags</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Tags (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few Tags 
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Taxes</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Taxes (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few tax rates
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Report Fields</summary>
1. Change `canUseReportFieldsFeature` in `permissions.ts` to return true
2. Log in to the app
3. Go to existing Workspace or create new
4. Go to Report Fields (as an admin)
5. Turn it on in `More features` if not enabled
6. Add a few items
7. Long press on some item
8. Chose "Select"
9. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Report Fields - Add list type report</summary>
1. Change `canUseReportFieldsFeature` in `permissions.ts` to return true
2. Log in to the app
3. Go to existing Workspace or create new
4. Go to Report Fields (as an admin)
5. Turn it on in `More features` if not enabled
6. Click "Add field"
7. Fill required fields
8. Chose "List" type 
9. Chose "List values"
10. Add a few items
11. Long press on some item
12. Chose "Select"
13. Select and unselect options and test some bulk action
</details>

<details>
<summary>Group chat -> Members</summary>
1. Log in to the app
2. Go to existing group chat (if you don't have any go to point 3 otherwise go to point 6)
3. Click `+` button
4. Chose `Start chat`
5. Add a few people to the chat
6. Go to chat details
7. Go to members
8. Long press on some item
9. Chose "Select"
11. Select and unselect options and test some bulk action
</details>

<details>
<summary>Search</summary>
1. Log in to the app (use account with existing transactions or create a few new)
2. Go to Search Tab (from bottom tab)
3. Use small screen width or mobile device
4. Long press some item 
5. Chose "Select" option
6. Select and unselect options and do some bulk action
</details>

- [x] Verify that no errors appear in the JS console

### QA Steps

<details>
<summary>Workspace Members</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Members (as an admin)
4. Add a few members if you are alone
5. Long press on some item
6. Chose "Select"
7. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Distance Rates</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Distance Rates (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few distance rates if there is only one rate
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Categories</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Categories (as an admin)
4. Turn it on in `More features` if not enabled
5. Long press on some item
6. Chose "Select"
7. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace multi level Tags</summary>
1. Log in to OD
2. Go to Workspace settings
3. Go to Tags and enable it if not enabled
4. Enable `People must tag expenses` and `Use multiple level of tags`
5. Import some multi level Tags (eh. [this](https://github.com/Expensify/App/files/15195760/Independent%2Bwithout%2BGL%2Bcodes%2Bformat.csv) )
6. Go to ND
7. Go to the same Workspace and Tags page
8. You should not be able to select any Tag on main page
9. Go to Tag details
10. You'll see Tags inside 
12. Long press on some item
13. Chose "Select"
14. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace single level Tags</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Tags (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few Tags 
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Taxes</summary>
1. Log in to the app
2. Go to existing Workspace or create new
3. Go to Taxes (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few tax rates
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Report Fields</summary>
1. Log in to the app with an account that has Report Fields beta enabled
2. Go to existing Workspace or create new
3. Go to Report Fields (as an admin)
4. Turn it on in `More features` if not enabled
5. Add a few items
6. Long press on some item
7. Chose "Select"
8. Select and unselect options and test some bulk action
</details>

<details>
<summary>Workspace Report Fields - Add list type report</summary>
1. Use an account that has Report Fields beta enabled
2. Log in to the app
3. Go to existing Workspace or create new
4. Go to Report Fields (as an admin)
5. Turn it on in `More features` if not enabled
6. Click "Add field"
7. Fill required fields
8. Chose "List" type 
9. Chose "List values"
10. Add a few items
11. Long press on some item
12. Chose "Select"
13. Select and unselect options and test some bulk action
</details>

<details>
<summary>Group chat -> Members</summary>
1. Log in to the app
2. Go to existing group chat (if you don't have any go to point 3 otherwise go to point 6)
3. Click `+` button
4. Chose `Start chat`
5. Add a few people to the chat
6. Go to chat details
7. Go to members
8. Long press on some item
9. Chose "Select"
10. Select and unselect options and test some bulk action
</details>

<details>
<summary>Search</summary>
1. Log in to the app (use account with existing transactions or create a few new)
2. Go to Search Tab (from bottom tab)
3. Use small screen width or mobile device
4. Long press some item 
5. Chose "Select" option
6. Select and unselect options and do some bulk action
</details>

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Workspace Members</summary>

https://github.com/user-attachments/assets/1cefb2ce-cc60-4e7e-9a32-f3b89ce2d84b

</details>

<details>
<summary>Workspace Distance Rates</summary>

https://github.com/user-attachments/assets/9055414a-6493-4521-93e1-95416af3d8a6

</details>

<details>
<summary>Workspace Categories</summary>

https://github.com/user-attachments/assets/497c863b-6224-41d9-8e3b-9a421a353e08

</details>

<details>
<summary>Workspace multi level Tags</summary>

https://github.com/user-attachments/assets/70e87b30-7a25-401b-8356-672b4d572e62

</details>

<details>
<summary>Workspace single level Tags</summary>

https://github.com/user-attachments/assets/84a7b2b0-5219-4e44-83f3-9323144ba9ed

</details>

<details>
<summary>Workspace Taxes</summary>

https://github.com/user-attachments/assets/8c8c1588-59b2-4892-b078-838c3360883a

</details>

<details>
<summary>Workspace Report Fields</summary>

https://github.com/user-attachments/assets/6ffa6acb-f925-4a84-9077-2a9d838b1fd2

</details>

<details>
<summary>Group chat -> Members</summary>
[Android_Group-members.webm](https://github.com/user-attachments/assets/cf3aafbf-baf2-4f5a-973e-17de9ff96ab4)

</details>

<details>
<summary>Search</summary>
[Android_Web_Search.webm](https://github.com/user-attachments/assets/a709d5e7-2cfb-4796-b724-231c2d5eb644)

</details>

### CODE REVIEW

**Review by zfurtak — APPROVED** [review]
LGTM 🎉

**Comment by filip-solecki** [comment]
@ikevin127 it's all yours!

**Comment by ikevin127** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by ikevin127** [comment]
@filip-solecki Completed the checklist, overall functionality looks great - good job on this one!

⚠️ **However, while testing I found 3 issues. Here they are in the order I found them:**
1. * [ ] **New mobile selection mode is missing in Report Fields > [+] Add field > Type: List > List values**

      **Note:** Happens on all platforms (native and mWeb).
      
      <details>
      <summary>Video</summary>
      
      https://github.com/user-attachments/assets/f7cb0140-0bac-401a-8695-1adeea2b0541
      
      </details>

2. * [ ] **Search - Select UI Glitch: ✅ Remains in card after going back from Select multiple**

      **Note:** Happens on all platforms (native and mWeb).
      
      <details>
      <summary>Video</summary>
      
      https://github.com/user-attachments/assets/f44cc9a3-bfa6-478d-a91f-f2677967721d
      
      </details>

3. * [ ] **Selected items modal backdrop non-existent on mWeb**

      **Note:** Happens **only** on mWeb - both Android / iOS - Chrome and Safari.
      
      <details>
      <summary>Video</summary>
      
      https://github.com/user-attachments/assets/e623c737-2ea0-4fcc-a8a2-20d7d0377cfa
      
      </details>

##

Based on the https://github.com/Expensify/App/issues/45451 issue, I think these 3 issues should be addressed here as they seem to be part of the scope. Once the issues are addressed and conflicts are solved I'll re-test to confirm they are fixed then will **Approve** if everything looks good.

**Comment by filip-solecki** [comment]
Ok, working on merge changes right now, there were a lot of changes since yesterday

**Comment by filip-solecki** [comment]
Issue number 2 seems to be easy fix and probably caused by my changes btw

**Comment by filip-solecki** [comment]
I will fix bug number 2 in [this issue](https://github.com/Expensify/App/issues/44916) - it will be much easier there when we merge small and large screen selected states into one i SearchContext

**Comment by filip-solecki** [comment]
I've added mobile selection mode to add report field list type page 
cc @ikevin127

**Review by ikevin127 — APPROVED** [review]
Thanks for addressing the issues! LGTM 🎉 

##

**Summary on the found issues from https://github.com/Expensify/App/pull/46096#issuecomment-2251584206:**
* [x] ~~**1. New mobile selection mode is missing in Report Fields > [+] Add field > Type: List > List values**~~
- ✅ fixed by commit https://github.com/Expensify/App/pull/46096/commits/b4a81a36630a98d3ae0e56009496e67b741d3061

* [x] ~~**2. Search - Select UI Glitch: ✅ Remains in card after going back from Select multiple**~~

- ✅ confirmed in [#46096 (comment)](https://github.com/Expensify/App/pull/46096#issuecomment-2252290483), and will be addressed in a follow-up task (https://github.com/Expensify/App/issues/44916)

* [x] ~~**3. Selected items modal backdrop non-existent on mWeb**~~

- ✅ NAB, confirmed in [#46096 (comment)](https://github.com/Expensify/App/pull/46096#issuecomment-2252097059) as only reproducible in local dev due to StrictMode, meaning it won't be present once deployed on staging / production

**Comment by ikevin127** [comment]
cc @jasperhuangg

**Comment by filip-solecki** [comment]
Resolved, @jasperhuangg all yours!

**Review by jasperhuangg — DISMISSED** [review]

**Comment by jasperhuangg** [comment]
@filip-solecki sorry, merge conflicts :/

**Comment by filip-solecki** [comment]
@jasperhuangg - resolved

**Comment by filip-solecki** [comment]
@ikevin127 Please check my latest commit - I decided to move turning on selection mode logic to `SelectionListWithModal` to avoid recreating this logic in every component

**Review by jasperhuangg — APPROVED** [review]

**Comment by ikevin127** [comment]
LGTM - Ready to Merge 🚀

cc @jasperhuangg

**Comment by ikevin127** [comment]
@filip-solecki I decided to do a double-check again and I noticed an issue on the Search page:
- once entered in select mode, as long as there's at least 1 item selected -> we cannot go back (exit select mode) using [< Select multiple] button
- the go back [< Select multiple] button only works as expected if no items are selected (checked), see video below

This happens with StrictMode **off** as well, so it's not because of StrictMode. It also happens on all platforms (mWeb and Native). **Note:** It's possible that this happened after the push of commit https://github.com/Expensify/App/pull/46096/commits/7a0e5a669d7bf793a8957b3e3c7b796e01a23f51.

@jasperhuangg Maybe there's still time to push a follow-up fix before this gets deployed and the regression is reported.

| iOS | iOS-mWeb |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/e35c05f5-99de-4c75-a30f-f40462d253eb"> | <video src="https://github.com/user-attachments/assets/c800b309-577d-4f30-ad9c-ec1d0daa04c4"> |

**Comment by filip-solecki** [comment]
Hmm, for sure it is fixed in [this PR](https://github.com/Expensify/App/pull/46096#issuecomment-2259337837) and imo it's better to focus on that PR and merge it quickly as fixing it in this PR might be a little bit tricky, WDYT?

**Comment by ikevin127** [comment]
@filip-solecki Not sure what PR you are referencing - the issue I just found was found after this PR was merged by checking-out this PRs branch.

As I referenced in my previous comment: the issue wasn't present before your latest commit https://github.com/Expensify/App/commit/7a0e5a669d7bf793a8957b3e3c7b796e01a23f51 so I'm assuming that's where things went south.

I just wanted to double-check with you and let people know - maybe we can fix the issue before this PR is deployed to staging and a regression will for sure arise.

**Comment by filip-solecki** [comment]
Sorry, pasted bad link - I mean [this PR](https://github.com/Expensify/App/pull/46406)

**Comment by filip-solecki** [comment]
I've asked @rushatgabhane for prioritizing review on mentioned PR to avoid regression here

**Comment by jasperhuangg** [comment]
@rezkiy37 Thanks for investigating! Looks like we're aware of that and will address that in the the fix PR: https://github.com/Expensify/App/pull/46698#issuecomment-2273981101

**Comment by ikevin127** [comment]
Issue was fixed in PR https://github.com/Expensify/App/pull/46698, commit https://github.com/Expensify/App/pull/46698/commits/6e6edea522fe1ff901a6ddacee20aaf52d1e09a7, here's the [proof](https://github.com/Expensify/App/pull/46698#issuecomment-2282767940). Next, we're looking at merging the PR 🚀

**Comment by jayeshmangwani** [comment]
Coming from this Issue https://github.com/Expensify/App/issues/46619, we missed to disabling the dropdown button on mobile devices when no data is selected we fixed it in this [PR](https://github.com/Expensify/App/pull/46679) , more context for the solution on this Proposal https://github.com/Expensify/App/issues/46619#issuecomment-2261596872

**Comment by getusha** [comment]
Coming from https://github.com/Expensify/App/issues/46620, we missed disabling a selection on disabled selection items on mobile devices.

**Pull request merged**
