### PR TITLE
Add teamdot check to SideBarUtils.js

### PR DESCRIPTION
**Pull request by alex-mechler**
@tgolen will you review please? 

### Details
While you were working on https://github.com/Expensify/App/pull/10800, we added another bypass to the beta in https://github.com/Expensify/App/pull/10855. As a result, SideBarUtils didn't have this check. This PR adds the extra bypass check to SideBarUtils as well

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/229968

### Tests
1. (Dev) turned off all forced betas
2. Signed into an account that was not on the beta, but had an assigned guide
3. _Verified_ I saw the #admins room in the sidebar
image
- [ ] Verify that no errors appear in the JS console

### QA Steps
1. On OldDot, from a public domain account (gmail.com for example), create a new corporate policy
2. Navigate to NewDot and sign in to the same account
3. _Verify_ you see the #admins room in the side bar 
image
- [ ] Verify that no errors appear in the JS console

### CODE REVIEW

**Review by marcochavezf — APPROVED** [review]
LGTM

**Comment by alex-mechler** [comment]
Adding the CP label, guides are running into this in prod https://expensify.slack.com/archives/C036S0BVAHH/p1663955934830269

**Comment by alex-mechler** [comment]
Going to self merge this. Tim is OOO today, and guides are running into this, impacting their workflow.

**Comment by alex-mechler** [comment]
See above, guides were running into this, impacting 121 assignments

**Comment by marcochavezf** [comment]
The checklist was not completed because we wanted to hotfix this asap https://github.com/Expensify/App/pull/11244#issuecomment-1256528753

**Pull request merged**
