### PR TITLE
Remove unnecessary style causing bug in android

### PR DESCRIPTION
**Pull request by aldo-expensify**
cc: @pecanoro  @marcaaron @jasperhuangg CC you guys because you have a good idea of what was going on.

### Details
I labeled this `CP Staging` because it is fixing the following regression: https://github.com/Expensify/App/issues/4730#issuecomment-904268814

The style `errorOutline` was unnecessary and was causing an unwanted behaviour in Android.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4730

### Tests/QA
1. Navigate to `<baseURL>/bank-account/company`.
2. Input invalid data for the following fields and try to submit the form. Verify that red outlines AND growl messages occur.
    - Empty password
    - Invalid address street
    - Invalid address zip code
    - Invalid website URL
    - Invalid company tax ID
    - Invalid industry code
    - Invalid incorporation date

Make sure that in Android the value of the input with error doesn't disappear .

Expected to look like this:

Screen Shot 2021-08-24 at 1 31 52 PM

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [x] Android

### CODE REVIEW

**Review by pecanoro — DISMISSED** [review]

**Review by luacmartins — DISMISSED** [review]
Tests well and code LGTM!

**Comment by luacmartins** [comment]
@aldo-expensify Feel free to self-merge once tests pass.

**Comment by marcaaron** [comment]
>The style errorOutline was unnecessary and was causing an unwanted behaviour in Android.

I get that it was unnecessary since it looks like we wrapped the `TextInput` in a `View` that already has an outline... 

https://github.com/Expensify/App/blob/eb73fd3e727d7adc7fe5cc2e20b39587fb4ac3e7/src/components/ExpensiTextInput/BaseExpensiTextInput.js#L136

But is there some explanation for why this should make the element value completely disappear? 🤯

**Comment by aldo-expensify** [comment]
@marcaaron I don't have good explanation for it, but what I found is:

- The text content didn't really disappear, it was there but out of view. The input of is scrollable and if you scroll you eventually can see the text, but the space available for the text is very small:

https://user-images.githubusercontent.com/87341702/130698811-b848c7be-959f-47c3-8917-a84e065c4d0d.mov


- In Android we have to make the padding 0 (see `styles.expensiTextInputAndroid`). If use we a small padding value, i.e. 4:

```
    expensiTextInputAndroid: left => ({
        padding: 4,
        left,
    }),
```
The space for the input text becomes smaller and we get some scrolling:

https://user-images.githubusercontent.com/87341702/130698503-057f6093-0184-46f1-8ad9-97411771aef2.mov

- If we remove the `padding: 0` completely from `styles.expensiTextInputAndroid`, the input value is not visible anymore (too much padding?).

I don't know why, but adding the style `errorOutline` to the TextInput seems to somehow mess up this in a similar way as adding padding messes it up. Maybe when we add the `borderColor` Android does something with the padding? 🤷  I just found that this fixed it by trial an error, removing and putting back things.

**Comment by aldo-expensify** [comment]
Update: had to resolve conflict and commit again.

**Review by luacmartins — APPROVED** [review]

**Comment by isagoico** [comment]
@aldo-expensify Can this be tested on your side? We're currently unable to navigate to `/bank-account/company` in Android or iOS bc we don't have access to the current URL in the app.

**Comment by aldo-expensify** [comment]
> @aldo-expensify Can this be tested on your side? We're currently unable to navigate to `/bank-account/company` in Android or iOS bc we don't have access to the current URL in the app.

Sure, I'm waiting on the (PR)[https://github.com/Expensify/App/pull/4814] to be approved and merged.

**Pull request merged**
