### PR TITLE
Move Search to a RightDockedModal

### LINKED ISSUE #1448: Move Search to the RightDockedModal
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

view the job on upwork [here](https://www.upwork.com/jobs/~019f6dc14b35d73bb0).

**Platform - version:**  
current

Currently, clicking the search icon changes the functionality of the Left Hand Nav in order to show search results. We've recently introduced a right-docked modal which would be a better fit for search functionality. We're leaving the search icon in the same place as it is today (on the left), but we're going to engage the right-docked modal to show the search bar and search results when the icon is clicked. This implementation is similar to `NewChatPage` and `NewGroupPage` navigation wise.

**Action Performed (reproducible steps):**
1. Click the search icon
2. Search for a user using the search bar

**Expected Result:**
1. The search bar and results should utilize `RightDockedModal`
Note: ensure we grey out the main page content, as we do for the other pages in the `RightDockedModal`

**Actual Result:**
1. The search bar and results utilize the Left Hand Nav

**Notes/Photos/Videos:** 
107490413-2546fc00-6b8a-11eb-9020-0dc65d5e49b8

### PR DESCRIPTION
**Pull request by lucas-neuhaus-dev**
@marcaaron 

### Details
Change the search from a sidebar component to a `RightDockedModal` component.
As a result, got rid of everything related to `ChatSwitcher`, since the Sidebar no longer has it.

#### Problem I am seeing (not new, but important to point out)

I have been seeing that warning
```
Warning: Can't perform a React state update on an unmounted component (...)
```
since the first issues I have worked on, and it can be seen on the console every now and then when clicking `New Chat` or `New Group`. For the search, it seems to be consistently showing up every first time a contact is selected from the search list.

I find it a hard warning to debug since the message is not very specific, but I am going to give it a try.

### Fixed Issues
Fixes #1448 

### Tests
1. Click on the Magnifying glass icon in the sidebar;
2. If on small screens, check if the `SearchPage` covers all the screen. If on large screens, check if the `SearchPage` is a modal that animates from the right, just as the `NewChatPage` and `NewGroupPage` do;
3. Verify that when selecting a contact, the selected report chat opens up, closing the `SearchPage`;
4. Verify if the modal closes either by clicking anywhere outside of it, or by pressing `ESC`, or by pressing / clicking on the `X` button on the top right;
5. **Edit (adding)** Also, verify that the other keyboard actions work accordingly (`UP` / `DOWN` arrow keys to change selection, `ENTER` to perform the selection.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
web

#### Mobile Web
mobile web

#### Desktop
desktop

#### iOS
ios

#### Android
android

### CODE REVIEW

**Comment by lucas-neuhaus-dev** [comment]
Realized I left some styles that are not used anymore, deleted them.

Renamed 3 styles to fit better the schema we have now:
| Before | After |
| --- | --- |
| `chatSwitcherItemAvatarNameWrapper` | `optionItemAvatarNameWrapper` |
| `chatSwitcherDisplayName` | `optionDisplayName` |
| `chatSwitcherLogin` | `optionAlternateText` |

**Comment by shawnborton** [comment]
Tested and it's looks great, thanks Lucas!

One thing I noticed with Android is that there is a lot of space at the top of the modal area. I vaguely remember talking about this somewhere else at one point... so perhaps it's not related to this PR and something we can address elsewhere?

Chats | Search
----- | -----
image | image

**Comment by lucas-neuhaus-dev** [comment]
You are correct, I did mention this bug on the [new group page PR](https://github.com/Expensify/Expensify.cash/pull/1392).
It is a problem with android (from my digging it says not all Android devices, but all that I tested had this problem) and React Native's Modal.
At that time we decided to move forward since it wasn't really related and there were a bunch of things to do. 
I left some reference links there, I'm going to take a look again, maybe it's simple and I can fit in this PR (or create a new one).

**Comment by shawnborton** [comment]
Ah okay, thanks for the additional context. If it's an existing bug, no need to address it in this PR - let's use a separate PR for that.

**Comment by lucas-neuhaus-dev** [comment]
It seems like it was as easy as adding one line of code. Going to fix it here and now if that is not a problem.
Tested on all platforms and found no regressions.

Important to point out that this problem was happening in all places with full height modals. It fixed that Attachment modal on Android as well.

| Chats | Search |
| --- | --- |
| chat | search |

**Comment by shawnborton** [comment]
Nice, that's great news!

**Comment by sketchydroide** [comment]
The PR looks good to me, but would love to another pair o eyes, @marcaaron  or @roryabraham

**Review by sketchydroide — APPROVED** [review]
LGTM

**Review by marcaaron — APPROVED** [review]
Looks great to me! Love the clean up here.

**Pull request merged**
