### PR TITLE
[TS migration] Migrate 'SignInDesktop' page

### PR DESCRIPTION
**Pull request by brunovjk**
### Details

**[TS migration] Migrate 'SignInDesktop' page, files:**
> [src/pages/signin/DesktopRedirectPage.js](https://github.com/Expensify/App/blob/main/src/pages/signin/DesktopRedirectPage.js)
> [src/pages/signin/GoogleSignInDesktopPage/index.website.js](https://github.com/Expensify/App/blob/main/src/pages/signin/GoogleSignInDesktopPage/index.website.js)
> [src/pages/signin/GoogleSignInDesktopPage/index.js](https://github.com/Expensify/App/blob/main/src/pages/signin/GoogleSignInDesktopPage/index.js)
> [src/pages/signin/DesktopSignInRedirectPage/index.website.js](https://github.com/Expensify/App/blob/main/src/pages/signin/DesktopSignInRedirectPage/index.website.js)
> [src/pages/signin/DesktopSignInRedirectPage/index.js](https://github.com/Expensify/App/blob/main/src/pages/signin/DesktopSignInRedirectPage/index.js)
> [src/pages/signin/AppleSignInDesktopPage/index.website.js](https://github.com/Expensify/App/blob/main/src/pages/signin/AppleSignInDesktopPage/index.website.js)
> [src/pages/signin/AppleSignInDesktopPage/index.js](https://github.com/Expensify/App/blob/main/src/pages/signin/AppleSignInDesktopPage/index.js)

### Fixed Issues

$ https://github.com/Expensify/App/issues/31988
PROPOSAL: N/A

### Tests

Pre-condition:
1. Render the web Sign In with Google button in Development. [APPLE_GOOGLE_SIGNIN.md#render-the-web-sign-in-with-google-button-in-development](https://github.com/Expensify/App/blob/main/contributingGuides/APPLE_GOOGLE_SIGNIN.md#render-the-web-sign-in-with-google-button-in-development)
2. Update [`newExpensifyURL`](https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/CONFIG.ts#L14) so we can use `https://dev.new.expensify.com:8083` in place of `https://new.expensify.com/`
3. Start Dektop App (`npm run desktop`) at :8082.
4. Start Web App (`npm run web`) at :8083.
5. Manually login with any google account to the Web App (`dev.new.expensify.com:8083`). Don't use the Google Sign Button, it won't work.
6.  Update the webpack.dev.js config to change `host` from `dev.new.expensify.com` to `localhost` and server type from `https` to `http`. [APPLE_GOOGLE_SIGNIN.md#hostport-requirements](https://github.com/Expensify/App/blob/main/contributingGuides/APPLE_GOOGLE_SIGNIN.md#hostport-requirements)

Steps to test:
1. Go to the Desktop App and click on the Google SignIn button.
2. Verify that you have been redirected to `.../sign-in-with-google` and the URL automatically updates to `.../desktop-signin-redirect`.
3. Click on `Try Again` to be redirected to the Desktop App.
4. Verify that we are logged into DesktopApp with the same account we used in `Pre-condition Step 5`.
5. Logout in the DektopApp.
6. In the Desktop App click on the Apple SignIn button.
7. Verify that you have been redirected to `.../sign-in-with-apple` and the URL automatically updates to `.../desktop-signin-redirect`.
- [x] Verify that no errors appear in the JS console

### Offline tests

N/A
### QA Steps

Google SignIn
1. Sign out of Desktop and Web apps
2. Go to the Desktop app and click on the Google SignIn button.
3. Verify that you have been redirected to the URL `.../sign-in-with-google` in the browser
4. Login with a Google Account and verify that URL automatically updates to `.../desktop-signin-redirect`.
5. Verify that it is directed to Desktop app. (If there is a prompt to open on Desktop app click on the prompt to redirect to Desktop app)
6. Verify that we are logged into Desktop app with the same account logged in at Step 4

Apple Signin
1. Sign out of Desktop and Web apps
2. Go to the Desktop app and click on the Apple SignIn button.
3. Verify that you have been redirected to the URL `.../sign-in-with-apple` in the browser
4. Login with an Apple Account and verify that URL automatically updates to `.../desktop-signin-redirect`.
5. Verify that it is directed to Desktop app. (If there is a prompt to open on Desktop app click on the prompt to redirect to Desktop app)
6. Verify that we are logged into Desktop app with the same account logged in at Step 4

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

N/A
</details>

<details>
<summary>Android: mWeb Chrome</summary>

N/A
</details>

<details>
<summary>iOS: Native</summary>

N/A
</details>

<details>
<summary>iOS: mWeb Safari</summary>

N/A
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

N/A
</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/95647348/7a7ab7e8-d6c7-4de3-b3e3-525c8a304c8a

</details>

### CODE REVIEW

**Comment by brunovjk** [comment]
Please, I need help to test this migration. I'm still not clear what the steps are, to test and [ensure all sign in on all platforms works fine](https://expensify.slack.com/archives/C01GTK53T8Q/p1706617138803219?thread_ts=1706613191.987329&cid=C01GTK53T8Q).

**Comment by brunovjk** [comment]
I still haven't managed to enable SSO options on my local dev.

**Comment by brunovjk** [comment]
Currently working on Steps test and POCs

**Comment by c3024** [comment]
@brunovjk Sorry, could not respond to your earlier pings. I've been checking other PRs. I'll check and get back in a few hours.

**Comment by c3024** [comment]
I think visiting these routes

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/ROUTES.ts#L50-L52

and checking if they are working as expected with nothing broken and no new console warnings and errors should do.

You might want to modify this line for dekstop prompt in dev environment.

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/DeeplinkWrapper/index.website.tsx#L65

**Comment by brunovjk** [comment]
Thank you @c3024 I saw your message before, still working on those tests. This PR will be ready for review soon. At the latest by the end of this week 02/09, but I believe sooner.

**Comment by brunovjk** [comment]
@c3024 The PR is ready for review.

**Comment by c3024** [comment]
In the pre-condition, at this step

> Login with any google account to the Web App (dev.new.expensify.com:8083)

I am not able to login with a Google account on web. I am getting a blank white screen.

https://github.com/Expensify/App/assets/102477862/5b688cf7-2e37-4230-a832-ad4928061b15

I followed all the preceding steps in the pre-condition. Could you help me with this? @brunovjk

**Comment by brunovjk** [comment]
@c3024 Thanks for the review. My bad, I didn't make it so clear, that in step 5 I logged in with a Google account not through the GoogleSignIn Button, but I entered the account manually, sorry about that. During the tests I did, I tested several 'Step test Path', none led to accurate reproduction, but none had a failure or error in relation to migration. Actually I'm not very happy with these steps, I'll redo/improve it and let you know.

**Review by blazejkustra — APPROVED** [review]

**Comment by brunovjk** [comment]
Hello @blazejkustra were you able to test using the steps I provided? Thank you: D

**Comment by brunovjk** [comment]
Hello @blazejkustra were you able to test using the steps I provided? Thank you :D

**Comment by blazejkustra** [comment]
No, I only reviewed typescript-wise @brunovjk 😄

**Comment by brunovjk** [comment]
Nice, thank you. I agree, the TS migration is looking good. I will keep working on those steps today, I believe it is important for the QA team.

**Comment by c3024** [comment]
I think the test steps cover well enough to verify the changes made.

**Review by c3024 — APPROVED** [review]
LGTM

**Review by c3024 — APPROVED** [review]
:shipit:

**Review by youssef-lr — APPROVED** [review]
LGTM

**Comment by kavimuru** [comment]
@youssef-lr @c3024  Could you help with "Precondition" part for the QA team?

**Comment by c3024** [comment]
My bad @kavimuru . The QA steps do not require the pre-condition because the buttons are already rendered. Please follow the following steps.

## QA steps
### Google SignIn
1. Sign out of Desktop and Web apps
2. Go to the Desktop app and click on the Google SignIn button.
3. Verify that you have been redirected to the URL `.../sign-in-with-google` in the browser
4. Login with a Google Account and verify that URL automatically updates to `.../desktop-signin-redirect`.
5. Verify that it is directed to Desktop app. (If there is a prompt to open on Desktop app click on the prompt to redirect to Desktop app)
6. Verify that we are logged into Desktop app with the same account logged in at Step 4

### Apple Signin
1. Sign out of Desktop and Web apps
2. Go to the Desktop app and click on the Apple SignIn button.
3. Verify that you have been redirected to the URL `.../sign-in-with-apple` in the browser
4. Login with an Apple Account and verify that URL automatically updates to `.../desktop-signin-redirect`.
5. Verify that it is directed to Desktop app. (If there is a prompt to open on Desktop app click on the prompt to redirect to Desktop app)
6. Verify that we are logged into Desktop app with the same account logged in at Step 4

**Comment by c3024** [comment]
Please suggest any corrections if required here https://github.com/Expensify/App/pull/35406#issuecomment-1943896890.

@brunovjk

**Comment by brunovjk** [comment]
True, we don't need pre-conditioning for QA tests, I hadn't realized that. @c3024 should I edit the PR 'Details' with [these QA steps](https://github.com/Expensify/App/pull/35406#issuecomment-1943896890)? They look good to me.

**Comment by brunovjk** [comment]
Done :)

**Pull request merged**
