### PR TITLE
Update Terms and Fees step to match latest requirements

### PR DESCRIPTION
**Pull request by Jag96**
cc @shawnborton for design 👀 

### Details
This PR updates the styles for the Terms and Fees step of the VBA flow based on the mockups in https://github.com/Expensify/Expensify/issues/167278#issuecomment-982972716.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/167278

### Tests
The easiest way to get to the Terms Page without going through the entire OnFido flow is to update the following lines locally:

1. Undo [this change](https://github.com/Expensify/App/pull/3879/commits/a1b6d5b4690057cbe786aa68fe416062d931318d#diff-239d10d81e0cd799a3aa5ae1c9f951c5cc10c75d1924e1efe3473f97dd09e93fR35) which makes the default step the terms page
2. Undo [this change](https://github.com/Expensify/App/pull/3879/commits/a1b6d5b4690057cbe786aa68fe416062d931318d#diff-9b9fee594bc95324fa21caa02ac4d6d9692ce460c56587ff9aea35893fb3dde2R117) which will let you navigate to the terms page by tapping on the `+` button and selecting `New Chat`
3. Confirm the design matches the updated layout in https://github.com/Expensify/Expensify/issues/167278#issuecomment-982972716

### QA Steps
No QA

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

| Mobile | Web |
|---|---|
| image | image |
| image | image |

### CODE REVIEW

**Review by MonilBhavsar — COMMENTED** [review]
Looks good.
Not affected by this PR, but I think we should update the error message

Screenshot 2021-12-06 at 5 36 10 PM

**Comment by shawnborton** [comment]
Looking pretty good! I forget where we landed with this general UX discussion, but should we actually move the green button to be at the very bottom of the disclosure text instead of being fixed to the bottom of the viewport? I think that makes sense given that you basically need to scroll all the way to the bottom and tap on the checkboxes before moving forward. Thoughts on that?

**Comment by Jag96** [comment]
> Not affected by this PR, but I think we should update the error message

Good find, I'll have a look

> I forget where we landed with this general UX discussion, but should we actually move the green button to be at the very bottom of the disclosure text instead of being fixed to the bottom of the viewport?

Yes, I'll update!

**Comment by Jag96** [comment]
Fixed the error message and button and added some spacing under the button as well, screenshots have been updated!

**Review by shawnborton — APPROVED** [review]

**Review by MonilBhavsar — APPROVED** [review]
Thanks!

**Pull request merged**
