### PR TITLE
Fix focus loss after message deletion in edit mode

### PR DESCRIPTION
**Pull request by Shahidullah-Muffakir**
### Details

This PR fixes a problem where deleting a message while editing causes the text input area (composer) to lose focus. The issue was caused by a mistake in how a callback function was assigned, which led to unexpected behavior. The solution is to call the runAndResetCallback function directly to make sure it works correctly and resets as needed. Also, I corrected some typos in the references to onConfirmDeleteModal to avoid any future errors.

### Fixed Issues

$https://github.com/Expensify/App/issues/45472
PROPOSAL:https://github.com/Expensify/App/issues/45472#issuecomment-2336825317

### Tests

1. Start the ND Desktop App or go to staging.new.expensify.com and log in with any account.
2. Open any chat and send a message.
3. Press the Arrow Up key, then use Ctrl + A (or Cmd + A) to select all text, followed by the 'Delete' key.
4. Press 'Enter' to confirm the deletion.
5. Ensure that the focus remains on the composer field after deletion.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as tests.

### QA Steps

same as tests.
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
### Screenshots/Videos
<details>
<summary>Android: Native</summary>

This feature is only supported on the desktop app and web.
</details>

<details>
<summary>Android: mWeb Chrome</summary>

This feature is only supported on the desktop app and web.
</details>

<details>
<summary>iOS: Native</summary>

This feature is only supported on the desktop app and web..
</details>

<details>
<summary>iOS: mWeb Safari</summary>

This feature is only supported on the desktop app and web.
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/5a554987-318e-43aa-8cc0-a8aecead41d2

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/4f634df9-0a63-4656-93b0-4923fd118ad1

</details>

### CODE REVIEW

**Comment by Shahidullah-Muffakir** [comment]
@brunovjk, It seems the linting error in **`PopoverReportActionContextMenu.tsx`** is unrelated to the changes made in this PR, as I haven't modified that file. The error is related to the use of the deprecated **substr()** method. Would you like me to address this issue in this PR, or should it be handled separately? Thank you.

https://github.com/Expensify/App/blob/c666296588dd7628d14b1e7d6b8e2602537a97e7/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L228

**Comment by brunovjk** [comment]
> @brunovjk, It seems the linting error in **`PopoverReportActionContextMenu.tsx`** is unrelated to the changes made in this PR, as I haven't modified that file. The error is related to the use of the deprecated **substr()** method. Would you like me to address this issue in this PR, or should it be handled separately? Thank you.
> 
> https://github.com/Expensify/App/blob/c666296588dd7628d14b1e7d6b8e2602537a97e7/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.tsx#L228

Good work so far @Shahidullah-Muffakir. Good question, I'll ask on Slack about it and get back to you. Thanks.

**Comment by Shahidullah-Muffakir** [comment]
@brunovjk, my bad about the earlier message. I got it wrong. The linting error is actually in the same file where we made our PR changes.
The problem is with the substr() method, which is old and not recommended anymore. We can fix it pretty easily by changing substr to slice.
Want me to go ahead and make this change in our current PR? Let me know what you think.

**Comment by brunovjk** [comment]
Great @Shahidullah-Muffakir! I'm waiting for someone to comment on Slack, if nothing happens by Monday, please feel free to make the necessary updates and then we'll hand it over to an internal reviewer. What do you think? Thanks.

**Comment by Shahidullah-Muffakir** [comment]
@brunovjk, Sounds good to me. We'll wait until Monday for any comments on Slack. Thank you!

**Comment by brunovjk** [comment]
@Shahidullah-Muffakir Do you also see a delay to focus the composer? Thanks.
Desktop:

https://github.com/user-attachments/assets/9cffba0a-72aa-481a-945d-89b4c956e97e


Chorme:

https://github.com/user-attachments/assets/7a55bf68-3566-4e90-94cc-e2e686a63509

In `native` it doesn't:

https://github.com/user-attachments/assets/ca4980fc-9fb5-42f9-b7f3-b9a0ab89cf60


**I wonder if in native it should Focus after deleting a message**, according to the issue [_"Web/Desktop - Chat - Focus is lost ..."_](https://github.com/Expensify/App/issues/45472)  no, what do you think @youssef-lr? Thank you.

**Comment by Shahidullah-Muffakir** [comment]
@brunovjk, Yes, I see the same delay in focusing the composer. It seems like the delay might be caused by the time it takes to process the message deletion request. I believe this line of code could be the reason for the delay:

https://github.com/Expensify/App/blob/9160fa585c26d3312fd6d6fbd69d334e66cb373d/src/pages/home/report/ReportActionItemMessageEdit.tsx#L297

Not sure if there’s much we can do about this, Thank you.

**Comment by brunovjk** [comment]
@Shahidullah-Muffakir Let's move forward and resolve this lint issue, okay? 
_"This feature is only supported on the desktop app and web"_ Are you sure about this? I think so too, but I'd like to confirm before moving forward.

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir Let's move forward and resolve this lint issue, okay? _"This feature is only supported on the desktop app and web"_ Are you sure about this? I think so too, but I'd like to confirm before moving forward.

@brunovjk, Sure, I'll take care of the lint issue.

As for the native apps, the issue description (https://github.com/Expensify/App/issues/45472) mentions pressing the **Up Arrow Key** to edit a message. Since that's not possible on mobile apps, that's why I said it's only supported on desktop and web.

However, on mobile, if we edit a comment by tapping on it, clear the text, and confirm the deletion through the modal, the input is refocused as expected. I tested this, and it works fine on mobile.

https://github.com/user-attachments/assets/abf37763-0a40-459b-b6e9-350f39fa3f74

**Comment by Shahidullah-Muffakir** [comment]
@brunovjk I’ve fixed the linting issue. Thank you.

**Comment by brunovjk** [comment]
The changes seem good to me @Shahidullah-Muffakir, but I'm still unsure about the expected behavior on different platforms. I tested on Web and Desktop and apart from the small delay it seems good to me:

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/dc820ae0-113d-4e80-8eee-1a1694a74e9a


</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/16b798f4-f33d-4513-80fe-5bd474923542


</details>

On emulators, both web and native, the composer is not focused after deleting a comment, but even when editing (which is not the focus of this PR) the composer is not focused as well.

<details>
<summary>Android: Native</summary>



https://github.com/user-attachments/assets/f9a5abcf-d306-4c9b-bdf8-63c39bd31300


</details>

<details>
<summary>Android: mWeb Chrome</summary>



https://github.com/user-attachments/assets/8e707c7c-f1b4-4533-9a4b-2d2079958a45


</details>

<details>
<summary>iOS: Native</summary>



https://github.com/user-attachments/assets/ec7f297a-6a79-41f8-88be-68ab72ad3294


</details>

With that, @youssef-lr Do you confirm that the main composer should be focused when deleting messages only on web/desktop? I didn't find any reported issue about the main composer not being focused when editing either. **Can you confirm the expected behavior of "focus main composer" on all platforms after deleting a message?** Thank you very much.

**Comment by youssef-lr** [comment]
> Can you confirm the expected behavior of "focus main composer" on different platforms after deleting a message?

I think it's the same behavior on every platform.

**Comment by brunovjk** [comment]
@Shahidullah-Muffakir Following @youssef-lr s [comment](https://github.com/Expensify/App/pull/49538#issuecomment-2385784370), do you think we can update the behavior? At first glance it seems a bit out of scope, I'm not sure, but if that's the case we can try an increase in compensation (not guaranteed). Let me know what you think and your findings. Thanks.

**Comment by Shahidullah-Muffakir** [comment]
Hi @youssef-lr and @brunovjk,

I'm not sure if it's necessary to focus on the input field in the native apps. Based on a discussion I found in our Slack channel, the reason we don't focus the composer in native apps is that it would trigger the keyboard to open, which takes up half the screen. This isn't ideal for the user experience. We don't want to assume the user wants to start typing immediately, and the sudden appearance of the keyboard can feel jarring.

Links to the slack discussions: https://expensify.slack.com/archives/C01GTK53T8Q/p1696528231560429

and here: https://expensify.slack.com/archives/C01GTK53T8Q/p1617206989251400?thread_ts=1617201995.245400&cid=C01GTK53T8Q

Also, since the original issue only mentions desktop, this could be why the focus behavior is different there.
Thank you.

**Comment by brunovjk** [comment]
Great @Shahidullah-Muffakir! This is the investigation we needed, good work!! Thank you.

**Review by brunovjk — APPROVED** [review]
Great @Shahidullah-Muffakir! This is the investigation we needed, good work!! Thank you.

I just retested it and everything looks good to me :D [Do you agree](https://github.com/Expensify/App/pull/49538#issuecomment-2387986339) @youssef-lr?

**Review by youssef-lr — APPROVED** [review]
LGTM!

**Pull request merged**
