### PR TITLE
exclude reports in LHN that has no report type

### PR DESCRIPTION
**Pull request by rojiphil**
@abdulrahuman5196  @chiragsalian 

### Details

The original proposal considered checking for report `type`. However, this resulted in unit test failure which was analyzed [here](https://github.com/Expensify/App/pull/29155#issuecomment-1755897185). 

The alternate solution is to consider `participantAccountIDs` from where we gather personal details like avatars. However, as this seems like a hacky work, it was decided not to pursue this path.

This PR makes the following changes to the code:
1) Additionally check for undefined report `type` to decide if this report must be considered for visibility in the LHN options list. The changes are made in `shouldReportBeInOptionList`
2) Further, we update the failing unit tests by including report `type`. The changes are in `OptionsListUtilsTest.js` and `UnreadIndicatorsTest.js`

### Fixed Issues
$ https://github.com/Expensify/App/issues/27878
PROPOSAL: https://github.com/Expensify/App/issues/27878#issuecomment-1729436030

### Tests

1. Sign-in as User A in Expensify App.
2. Sign-in as User B in another Expensify App. (Note: User B should be such that user A should not have a chat history with user B)
3. Click on FAB in User B’s app and send Money Request.
4. Observe the LHN in User A
Expected Behaviour: Verify that IOU Report in LHN of user A should arrive with proper display of avatar and user name
i.e. There should not be a brief time during which avatar and user name is not displayed.

- [x] Verify that no errors appear in the JS console

### Offline tests

There are no offline tests as this use case requires interaction between two apps and, hence, requires to be online.

### QA Steps

Same as Steps for Tests Section.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos

<details>
<summary>Web-Chrome</summary>

https://github.com/Expensify/App/assets/3004659/8a39a076-7b8d-485c-9779-bd968af7d2b9

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/3004659/489b8077-ac58-4691-865c-608220750948

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/3004659/2287e2ea-4b40-4eee-87ee-7a3b002d1528

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/3004659/2237d3ec-c74e-4c26-b693-a67d133f4087

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/3004659/69c2c970-d566-49cc-bb03-7abcc027d7ca

</details>

<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/3004659/92a10cc5-747c-4846-a031-95ce014ab5ea

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/3004659/9acd6011-1dae-4d58-ba03-81638971e500

</details>

### CODE REVIEW

**Comment by rojiphil** [comment]
@abdulrahuman5196 
Using report `type` as per original proposal resulted in jest unit test failure. 
So, instead of using `type`, I propose using `participantAccountIDs` which looks like an even better option considering that we derive personal details from this variable. The jest unit tests are successful here. Also, this fixes the problem we have.
Kindly review the PR and let me know if there are changes required.

**Comment by abdulrahuman5196** [comment]
@rojiphil what unit test is failing as per original post?

**Comment by abdulrahuman5196** [comment]
@rojiphil Why where the UTs failing? Could you provide information that?

**Comment by rojiphil** [comment]
> @rojiphil Why where the UTs failing? Could you provide information that?

@abdulrahuman5196 
That's an interesting question. I quickly jumped on to find an alternate solution. 
I will check and get back.

**Comment by rojiphil** [comment]
@abdulrahuman5196 
Based on the UT test failures, I think, there are cases where `type` may not be sent but `participantAccountIDs` are sent. 
So, it looks like using `participantAccountIDs` to check is the better thing to do. 
What are your thoughts?

**Comment by abdulrahuman5196** [comment]
>So, it looks like using participantAccountIDs to check is the better thing to do.

@chiragsalian Could you kindly confirm if its fine to check for `participantAccountIDs`, or we should stick with type ?

**Comment by chiragsalian** [comment]
I think its fine to update this to check for `participantAccountIDs`.
But do we always have `participantAccountIDs` for reports? I'm just wondering for an optimistically created report do we always set `participantAccountIDs` now? Because if not then we would have to update optimistically created reports too as necessary.

**Comment by rojiphil** [comment]
> But do we always have `participantAccountIDs` for reports? I'm just wondering for an optimistically created report do we always set `participantAccountIDs` now? Because if not then we would have to update optimistically created reports too as necessary.

@chiragsalian 
That's a good question. This needs to be looked into. I will check and get back.

**Comment by rojiphil** [comment]
> I think its fine to update this to check for `participantAccountIDs`.
> But do we always have `participantAccountIDs` for reports? I'm just wondering for an optimistically created report do we always set `participantAccountIDs` now? Because if not then we would have to update optimistically created reports too as necessary.

@chiragsalian @abdulrahuman5196 
Currently, we have four types of chat as seen [here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/CONST.ts#L565C1-L570C11)

`ParticipantAccountIDs` is assigned optimistically in three of the report types (i.e)
1) `chat` : [assigned here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/libs/ReportUtils.js#L2603)
2) `iou` : [assigned here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/libs/ReportUtils.js#L2117)
3) `task` : [assigned here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/libs/ReportUtils.js#L2818)

However, for `expense` report type, `ParticipantAccountIDs` is not optimistically set as [seen here](https://github.com/Expensify/App/blob/502df9bc99accb7ac82b703d1105d18d34fe880f/src/libs/ReportUtils.js#L2150C1-L2166C7). We can add `participantAccountIDs: []` to `buildOptimisticExpenseReport` as well to keep regression at bay.

**Comment by rojiphil** [comment]
@abdulrahuman5196

I have added `participantAccountIDs: []` to `buildOptimisticExpenseReport` and have verified that it works. 
Also, I have attached a test video for this in the PR description.
Kindly review.

**Comment by abdulrahuman5196** [comment]
> I think its fine to update this to check for `participantAccountIDs`. But do we always have `participantAccountIDs` for reports? I'm just wondering for an optimistically created report do we always set `participantAccountIDs` now? Because if not then we would have to update optimistically created reports too as necessary.

@chiragsalian Logically I am not sure if this is correct, because we can have a task without assignee meaning it won't have `participantAccountIDs`(although we get/set empty `[]` now in the object so it should work fine). And in the failing UTs I don't think the `type` is intentionally left out, it could be that the `type` was missed during implementation and we haven't checked/updated since then. Even I can see commits adding `type` field to UTs https://github.com/Expensify/App/commit/ff1d770ce166583fc400ca10540f3e4cfccd8dce

I think `type` would be better and we can update UTs as well on the same. It would be better if you could confirm again which is more reliable from backend/logical perspective. Is it `type` field or `participantAccountIDs` field?

**Comment by rojiphil** [comment]
> I have added `participantAccountIDs: []` to `buildOptimisticExpenseReport` and have verified that it works.

@abdulrahuman5196 @chiragsalian 
Also, I wanted to mention one observation that I noticed while executing the following steps:
1. Go Offline
2. In a workspace, create an expense report by manually requesting money
3. Notice the console window

I noticed this console error (related to accountID) before adding `participantAccountIDs` to `buildOptimisticExpenseReport`
However, after adding `participantAccountIDs` to `buildOptimisticExpenseReport`, the console error disappears.
I haven't researched this but it looks like adding `participantAccountIDs` have resolved this.

Screenshot 2023-10-11 at 10 51 14 PM

**Comment by chiragsalian** [comment]
Ah poop i was hoping that reports always had participants but i forgot about report-type tasks. I thought this would be a quick answer. I'm not a fan of adding `participantAccountIDs: []` just to make the functionality work.

When in doubt i usually check what the backend has and try to make the front end work with values that is usually more expected.
Checking against a much smaller sample set than production
```
sqlite> select count(reportID) from reports where reportID NOT IN (SELECT reportID from reportNameValuePairs where name = 'type');
count(reportID)
---------------
0
```
This means that all reports have type in the backend. So the front end tests should be updated to consider them if we want it to closely match the backend.

```
sqlite> select count(reportID) from reports where reportID NOT IN (SELECT reportID from sharedReports);
count(reportID)
---------------
128
```
This tells us there are a number of reports not shared with others which can possibly result in `participantAccountIDs: []` values. (there are exceptions like owners etc)

So yeah i think checking for `type` is the better approach moving forward. If there is any API request not providing report type then we should update it because the backend has this information. Finally, we should update the tests as necessary to account for report type too.

**Comment by rojiphil** [comment]
> So yeah i think checking for `type` is the better approach moving forward. If there is any API request not providing report type then we should update it because the backend has this information. Finally, we should update the tests as necessary to account for report type too.

@abdulrahuman5196 @chiragsalian 
Ok. So, we have a consensus on this. 
I will revert the code and make the necessary changes to align with this.

**Comment by rojiphil** [comment]
@abdulrahuman5196 
The required changes are made and the PR description is updated accordingly.
Works well too.
Over to you for review.

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>




https://github.com/Expensify/App/assets/46707890/8553d6cb-4100-4da8-af08-e0b9db227444


</details>

<details>
<summary>Mobile Web - Chrome</summary>





https://github.com/Expensify/App/assets/46707890/977e26e6-72ec-4889-9e88-f2dcc83c56ff


</details>

<details>
<summary>Mobile Web - Safari</summary>






https://github.com/Expensify/App/assets/46707890/55f87e76-26c9-4968-928d-7dc5ca0649b3


</details>

<details>
<summary>Desktop</summary>







https://github.com/Expensify/App/assets/46707890/d5c0e4e5-70ec-49a2-9d87-149b4b68f101




</details>

<details>
<summary>iOS</summary>





https://github.com/Expensify/App/assets/46707890/c525647d-03de-491e-8230-af092beedbe6


</details>

<details>
<summary>Android</summary>





https://github.com/Expensify/App/assets/46707890/9dc84e7a-d683-43fd-96e6-81b13b21a10a


</details>

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours. @chiragsalian 

🎀 👀 🎀
C+ Reviewed

**Comment by rojiphil** [comment]
> Changes looks good and works well. Reviewers checklist is also complete.
> 
> All yours. @chiragsalian
> 
> 🎀 👀 🎀 C+ Reviewed

@chiragsalian 
Gentle bump on review here.

**Review by chiragsalian — APPROVED** [review]
LGTM

**Pull request merged**
