### PR TITLE
IOU - Autofocus 'What's it for?' text box in details page

### PR DESCRIPTION
**Pull request by rushatgabhane**
### Details

Added `autoFocus` prop to `TextInput` 

I didn't encounter any bugs that were mentioned in [this comment](https://github.com/Expensify/App/issues/4215#issuecomment-887097671).
### Fixed Issues

$ #4215 

### Tests / QA
1. Sign in to New Expensify
2. Request money to any user
3. Enter amount and go next.
4. Verify that 'What's it for?' text box is focused. 
5. Verify that the keyboard pops up for mobile devices.
### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

Screen Shot 2021-07-28 at 2 30 38 AM

#### Desktop

Screen Shot 2021-07-28 at 2 52 50 AM

#### iOS

Screen Shot 2021-07-28 at 11 20 21 AM

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
LGTM, I didn't see any react-navigation bugs either 👍

**Comment by shawnborton** [comment]
Just want to confirm - does the keyboard launch on all devices when this field is autofocused? I think it should, but the screenshots make it seem like it might not be the case.

**Comment by rushatgabhane** [comment]
> Just want to confirm - does the keyboard launch on all devices when this field is autofocused? I think it should, but the screenshots make it seem like it might not be the case.

Yes they do, just not in the simulator.

**Comment by shawnborton** [comment]
Sounds good, thanks for confirming!

**Comment by roryabraham** [comment]
Yes, I confirmed that too. @rushatgabhane Just in case you weren't aware, to make the software keyboard work in an iOS simulator you can go to `I/O` -> `Keyboard` -> `Toggle Software Keyboard` or just `CMD + K` and it will start behaving more like a physical device. I don't know why it doesn't do that by default.

**Comment by rushatgabhane** [comment]
> I don't know why it doesn't do that by default.

Too bad we can't raise an issue on their repo 😆

**Pull request merged**
