### PR TITLE
Correctly highlight chats in the chat switcher if they are unread

### PR DESCRIPTION
**Pull request by Gonals**
<Assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

While we were correctly highlighting report-type chats with unread comments in the chat Switcher, we were not doing the same with user chats. This should fix that.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/143652

### Tests
- Open two different instances of Nativa chat and log in with two different accounts (You can open one in incognito mode, for example).
- Open a chat with someone else in Account 1
- Send a message from Account 2 to Account 1. You should get the notification and see the chat highlighted in the LHN. Do not open it.
- Go to chat Switcher and start searching for Account 2. When it shows up, it should do so highlighted:
Screen Shot 2020-11-19 at 1 02 51 PM

### CODE REVIEW

**Review by chiragsalian — COMMENTED** [review]
LGTM and works well, you have a couple of jsx warnings that would be nice to address though.

**Review by nickmurray47 — DISMISSED** [review]
LGTM!

**Review by chiragsalian — DISMISSED** [review]
LGTM unfortunately there is some merge conflict now.

**Review by chiragsalian — DISMISSED** [review]
LGTM, nick's comment should be addressed though

**Review by chiragsalian — APPROVED** [review]
LGTM

**Review by nickmurray47 — APPROVED** [review]

**Pull request merged**
