### PR TITLE
Fix ActiveClientManager doesn't track the currently active tab well and needs improved

### PR DESCRIPTION
**Pull request by Skakruk**
### Fixed Issues

$ https://github.com/Expensify/App/issues/40044
PROPOSAL: https://github.com/Expensify/App/issues/40044#issuecomment-2049242184

### Tests
The easiest way to track if app client is a leader is to check the login page.

#### Client receives leading status:
1. Open the login page as an unauthenticated user in Tab A
2. Right-click on the tab and select Duplicate
3. Switch to Tab A before Tab B is fully loaded
4. Check that `Another login page is open.` text appears instead of the login form
5. Right-click on Tab B while it's in the background and select Close
6. Check that `Another login page is open.` disappears and the normal login form is shown.

#### Client correctly receives leading status on tab change:
1. Open the login page as an unauthenticated user in Tab A
2. Right-click on the tab and select Duplicate
3. Wait until app is fully loaded
4. The login form is displayed
5. Switch to Tab A
6. The login form is displayed

### Offline tests
Not applicable. 

### QA Steps
The easiest way to track if app client is a leader is to check the login page.

#### Client receives leading status:
1. Open the login page as an unauthenticated user in Tab A
2. Right-click on the tab and select Duplicate
3. Switch to Tab A before Tab B is fully loaded
4. Check that `Another login page is open.` text appears instead of the login form
5. Right-click on Tab B while it's in the background and select Close
6. Check that `Another login page is open.` disappears and the normal login form is shown.

#### Client correctly receives leading status on tab change:
1. Open the login page as an unauthenticated user in Tab A
2. Right-click on the tab and select Duplicate
3. Wait until app is fully loaded
4. The login form is displayed
5. Switch to Tab A
6. The login form is displayed

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Not applicable

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Not applicable

</details>

<details>
<summary>iOS: Native</summary>

Not applicable

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Not applicable

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/1768919/0a344ea9-ca56-47bf-81af-b5e5e78e2a44

</details>

<details>
<summary>MacOS: Desktop</summary>

Not applicable

</details>

### CODE REVIEW

**Comment by Skakruk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Skakruk** [comment]
recheck

**Comment by Skakruk** [comment]
recheck

**Comment by DylanDylann** [comment]
@allroundexperts Will you take over this one?

**Comment by allroundexperts** [comment]
Yes. Not sure why I wasn't assigned here. @tgolen can you assign this to me? Thanks!

@Skakruk Can you please complete the CLA?

**Comment by Skakruk** [comment]
@allroundexperts I did, bot has changed the comment text, but the job is still in a failed state. Not sure how to fix it. Tried the `recheck` command too a few times.

**Comment by Skakruk** [comment]
Fixed linting

**Comment by allroundexperts** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by allroundexperts** [comment]
Hi @Skakruk!
The solution you applied here is quite different from what you proposed ie:
```
window.addEventListener("beforeunload",  () => {
        activeClients = activeClients.filter((id) => id !== clientID);
        ActiveClients.setActiveClients(activeClients);
    });
```

Can you please explain why the above was not sufficient?

**Comment by allroundexperts** [comment]
Also, using `storage` event would degrade the performance of the app for sure. Can't we just stick to your original proposal?

**Comment by Skakruk** [comment]
@allroundexperts sure, here is my thoughts:

First, I implemented as I described in the proposal, and everything was working. But I dug deeper in docs and found out that using event `beforeunload` is not recommended. It makes page ineligible for bfcache and it should be used only conditionally (e.g. when we need to notify a user of an unfinished job on the form). https://web.dev/articles/bfcache#beforeunload-caution

The recommended events are `visibilitychange` and `pagehide`. The first one is called on every time the tab goes background and the second is when the tab is closed. So I went with the second one.

But since those event callbacks are sync, it's not guaranteed that that transaction to IDB will finish in time (in almost all tries it didn't). `Onyx.set` and `Onyx.subscription` worked fine, but no change to persistent storage. 

So I had to manage it is some way, that the closing tab will communicate with the left ones and notify them of client being destroyed in sync way.

There are a couple of ways to archive it:
 1. Broadcast Channel API - which is a fairly new API, but already implemented in all browsers https://caniuse.com/broadcastchannel
 2. Using localStorage and `storage` event - old-fashioned style of communication between tabs.
 3. Use https://www.npmjs.com/package/broadcast-channel - which utilizes both of them, depending on browser support.
 
I went with localStorage option since it's working in all browsers.

I can go with Broadcast Channel API, but I couldn't find any drawbacks of using `storage` event (maybe I'm missing some).

**Comment by allroundexperts** [comment]
Hi @Skakruk!
In my opinion, we should use `onunload` since it is much more simpler and less complex. The complexity which gets added due to the `storage` listener is not worth it. @tgolen Can you please weigh in here?

**Comment by Skakruk** [comment]
@allroundexperts `onunload` event is deprecated and is not recommended for use https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event https://developer.chrome.com/docs/web-platform/deprecating-unload

**Comment by allroundexperts** [comment]
@Skakruk I do get that. But I'm not fully onboard with the solution you implemented. I feel like its too complex. Waiting to see what @tgolen thinks.

**Comment by Skakruk** [comment]
@tgolen 
> Are you saying that this code never executes before the visibilitychange and pagehide events have ran their callbacks?

Onyx does its job correctly, but it does not save changes to IndexedDB, since those calls are async.

> I kind of think that we should just go back to this for now. Until there is a specific problem with that approach

I'm afraid that using `beforeunload` event might affect the overall performance of the application as it prevents usage of [bfcache](https://web.dev/articles/bfcache).

**Comment by tgolen** [comment]
> might affect the overall performance of the application as it prevents usage of [bfcache](https://web.dev/articles/bfcache).

Have you confirmed this is an actual problem?

**Comment by Skakruk** [comment]
@tgolen I rechecked and could not observe the issues described in [article about bfcache](https://web.dev/articles/bfcache).

So I reverting the implementation to the basic one.

**Review by tgolen — APPROVED** [review]
Wonderful, thanks for confirming that! This looks good.

**Review by allroundexperts — APPROVED** [review]
Looks good to me as well!

**Comment by kbecciv** [comment]
This PR is failing because of issue #1234 

The issue is reproducible in: Web - only check for now

https://github.com/Expensify/App/assets/93399543/e1e3750c-72a2-4515-87fa-90f9c05714a1

**Pull request merged**
