### PR TITLE
Add safety net for timezone in DateUtils

### PR DESCRIPTION
**Pull request by kidroca**
### Details

Handle the cases where `timezone` is used before the Onyx connection has provided a value
or when the value lacks timezone
Handle response errors in the `API.Get` in `AuthScreens`

### Fixed Issues

$ https://github.com/Expensify/App/issues/5305

### Tests

1. Log out
2. Log in
3. Refresh the page
4. You should not be stuck in a white screen after following these steps

Test that there are no regressions regarding locale assignment
1. Go to settings -> Preferences
2. Pick a different locale 
3. Refresh the app
4. There should be no regressions

### QA Steps

Same as above

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/12156624/133676577-654786e6-7055-4165-9bc0-9b2b158021ad.mp4

#### Mobile Web

https://user-images.githubusercontent.com/12156624/133677314-57bc851d-34f2-4af7-b486-f188a8808cb7.mp4

#### Android

https://user-images.githubusercontent.com/12156624/133677034-95714294-ba25-437b-b167-66474fbe47c9.mp4

### CODE REVIEW

**Comment by kidroca** [comment]
I'm not able to test iOS and Desktop ATM, I can try them later
Will post Android and mWeb (form Android) in a bit

**Review by luacmartins — APPROVED** [review]
LGTM and tested well! Adding desktop and iOS recordings here for reference.

### Desktop

https://user-images.githubusercontent.com/22219519/133687330-6f5f6dff-cbe2-482d-a479-2be8d7a667bd.mov

### iOS

https://user-images.githubusercontent.com/22219519/133687354-6f0112be-6262-412d-be15-365e493501ed.mov

**Comment by luacmartins** [comment]
Merging to fix a deploy blocker! Sorry @Gonals!

**Comment by isagoico** [comment]
Tested this PR and it was a pass. @AndrewGable not sure if you want to check on your side to double check.

**Comment by AndrewGable** [comment]
I can login with no white screens 👍

**Pull request merged**
