### PR TITLE
Fix cursor issue in room name input

### PR DESCRIPTION
**Pull request by sobitneupane**
### Details

Fix the issue "When user inputs a space in middle of room name, cursor moves to the end"

### Fixed Issues

$ https://github.com/Expensify/App/issues/7471

### Tests

1. Create new room
2. Enter room name
3. Add space in middle of the room name

### QA Steps

1. Create new room
2. Enter room name
3. Add space in middle of the room name

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/25876548/153271608-47ac7210-1b1e-46df-b2fc-335011a34bb0.mov

#### Mobile Web

https://user-images.githubusercontent.com/25876548/153272750-cddbdd77-8bd5-4456-b977-9ca6d3b119f6.mov

#### Desktop

https://user-images.githubusercontent.com/25876548/153270674-d589cf44-59c6-452e-967c-74bceea48cf1.mov

#### iOS

https://user-images.githubusercontent.com/25876548/153274953-1f4c8a3e-df68-4f4c-81a8-ea2f59056cf4.mov

#### Android

https://user-images.githubusercontent.com/25876548/153272925-740170dc-d1fd-404d-801a-e038ae2b76dd.mov

### CODE REVIEW

**Review by rushatgabhane — DISMISSED** [review]
@luacmartins LGTM, tests well on all platforms!

**Review by luacmartins — COMMENTED** [review]
Left a small comment.

**Review by luacmartins — APPROVED** [review]
LGTM! Thanks for the changes!

**Comment by Stutikuls** [comment]
**Issue 1 -**

**Title**- [Medium] Chrome +Jaws : Form field 'Room name' is not associated with their visible label.
**Actual** - The 'Room value' field is not announced with their visible labels.
Screen reader only read the value of the Room name, not reading the Label 'Room name' along with the value.
**Expected** -The visible label of a form field is programmatically associated with its form field so that assistive technology announces the label with the form field.
Screen reader should read like "Abc  room name editable text box".
**WCAG failure** - 1.3.1
**Reproducible in staging?**: - Yes
**Version Number**: - v1.1.39-3
**Platforms** - Web (Chrome + Jaws)

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/156990129-04a1ec45-7c8f-4937-9570-b0dfcb95fa27.mp4

**Issue 2 -**

**Title**- [Medium] Chrome +Jaws : 'Room Name' text edit field is not marked as required and announced.
**Actual** - The fields 'Room name' text field is required to be filled but is not announced as required and no visual "*" sign for required field.
Screen reader only read the value of the Room name, not reading the Label 'Room name' along with the value.
**Expected** -If the form element is required, it should be announced as such for the screen reader users and visual "*" sign for required field should be there. Screen reader should read like "Abc  room name editable text box".
**WCAG failure** - 1.3.1
**Reproducible in staging?**: - Yes
**Version Number**: - v1.1.39-3
**Platforms** - Web (Chrome + Jaws), Desktop (MAC), iOS(Voiceover), Mobile - web(Safari + Voiceover)

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/156990162-e324cea1-9dea-4ba6-9dcf-bb0bcebc15da.mp4

**Issue 3 -** 

**Title**-[High] Chrome + Jaws: Screen reader : Error message is not announced by the screen reader.
**Actual** - Screen reader does not announce any inline error message appear below to text boxes.
**Expected** - Inline error message should be conveyed to the users as soon as it appear on the fields so that user can resolve the error.
**WCAG failure** - 3.3.1
**Reproducible in staging?**: - Yes
**Version Number**: - v1.1.39-3
**Platforms** - Web(Chrome + Jaws), Desktop(MAC), Mobile-web (Safari + Voiceover)

**Note** - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/156995082-741e708a-da64-47d5-8577-bac7ad43a4de.mp4

**Comment by rushatgabhane** [comment]
@Stutikuls Thanks, I'd suggest that you post this on slack.

https://github.com/Expensify/App/blob/d4ed740be06862eb4ea31fa831de9416f7ed0a55/CONTRIBUTING.md#asking-questions

**Comment by ogumen** [comment]
> @Stutikuls Thanks, I'd suggest that you report this bug on **slack** because this bug doesn't seem to be related to this PR
> 
> https://github.com/Expensify/App/blob/d4ed740be06862eb4ea31fa831de9416f7ed0a55/CONTRIBUTING.md#asking-questions

Hi @rushatgabhane, the accessibility team is working on in-sprint testing for the PRs, the issues mentioned by Stuti are all related to the described flow. We were told to mention all accessibility issues we find in a comment to the corresponding PR.

**Comment by rushatgabhane** [comment]
Thanks, I wasn't aware of that. I'll take care of this

**Pull request merged**
