### PR TITLE
Fix: No notification on web if window is not active

### PR DESCRIPTION
**Pull request by tienifr**
### Details

Desktop shows the notification but web does not when we focus on the tab then open another app to blur the window. That is caused by different implementations of `Visibility.isVisible()` function across platforms. This PR fixes the issue.

### Fixed Issues

$ https://github.com/Expensify/App/issues/17242
PROPOSAL: https://github.com/Expensify/App/issues/17242#issuecomment-1507879211

### Tests

1. Login with account A on **Web**
2. Go to any chat with account B
3. Open any other app so that the browser window gets defocused
4. Login with account B on another device
5. Send message from that device to account A
6. Verify that the account A's device receives new message notification

- [x] Verify that no errors appear in the JS console

### Offline tests

Same above

### QA Steps

1. Login with account A on **Web**
2. Go to any chat with account B
3. Open any other app so that the browser window gets defocused
4. Login with account B on another device
5. Send message from that device to account A
6. Verify that the account A's device receives new message notification

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

[Screencast from 17-04-2023 15:59:02.webm](https://user-images.githubusercontent.com/113963320/232437134-5600a501-06f5-4b3e-8498-f51488a3734a.webm)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by tienifr** [comment]
Note: This only happens on Web so I only included Web screenshot. Please let me know if there were ways to enable notification on mWeb. What do you think if I didn't included other platforms' screenshots?

**Review by luacmartins — APPROVED** [review]

**Comment by luacmartins** [comment]
@Santhosh-Sellavel all yours!

**Comment by tienifr** [comment]
@Santhosh-Sellavel Just a friendly reminder in case you missed this.

**Review by luacmartins — COMMENTED** [review]
@tienifr I'm having issues testing these changes. I'm only getting notifications when the browser is minimized, but nothing comes up when I have it open and the window is unfocused. Am I doing something wrong?

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel Just a friendly reminder in case you missed this.

@tienifr 
Sorry we discussed this internally and forgot to leave a comment here, everything perfectly works fine for me on the staging itself and I'm not sure what we are trying to do here.

cc: @luacmartins

**Comment by tienifr** [comment]
@luacmartins I still can produce it, can you describe your context in detail?

[Screencast from 19-04-2023 15:33:18.webm](https://user-images.githubusercontent.com/113963320/233017521-afdcb6c2-1ac8-4877-922d-19bef6b328ab.webm)

**Comment by tienifr** [comment]
@Santhosh-Sellavel I **didn't get notified when the window is unfocused**/not active. Reproduced on Staging.

[Screencast from 19-04-2023 15:37:53.webm](https://user-images.githubusercontent.com/113963320/233018812-1cfddce4-23b9-4ada-ada3-edda7b879351.webm)

**Comment by Santhosh-Sellavel** [comment]
Alright, I got to reproduce the issue now, but the issue is not the same as it was described slightly differently.

We receive notifications even when the window is not active. We don't show when the same chat is active for which the notifications are received receiving the notification is

**Comment by Santhosh-Sellavel** [comment]
@tienifr Doesn't it affect mWeb also?

**Comment by tienifr** [comment]
> We receive notifications even when the window is not active. We don't show when the same chat is active

Absolutely! We don't show when that chat is opened and the window is active, to be more concise.

**Comment by luacmartins** [comment]
Supposedly you can enable notifications on Chrome mWeb, but I couldn't get it to work 😕 

Screenshot_1681921185

**Comment by tienifr** [comment]
@luacmartins Thanks! I already tried but it yielded no result. In Chrome mobile (Android & iOS), we can't manually add allowed sites for notifications. Instead, the site must ask for permission first. While it's different on Computer where we can manually add or remove any site.

Reference: https://support.google.com/chrome/answer/3220216?hl=en&co=GENIE.Platform%3DAndroid&oco=1

**Comment by Santhosh-Sellavel** [comment]
Alright if the notification is itself not working on mWeb it's a different problem, can you create a new tracking issue for that @luacmartins? And let's move forward here

**Comment by Julesssss** [comment]
> Are we asking for permission to show notifications on mWeb?

Pretty sure mWeb is completely unsupported for now

**Review by Santhosh-Sellavel — APPROVED** [review]
LGTM, tests well!

**Comment by luacmartins** [comment]
@Julesssss is mWeb notification covered anywhere in the notifications project? do we already have an issue for it?

**Comment by Julesssss** [comment]
@cead22 no, it's not something we care about

**Comment by cristipaval** [comment]
FYI: this PR introduced [this regression](https://expensify.slack.com/archives/C049HHMV9SM/p1682429757156649).

**Comment by Santhosh-Sellavel** [comment]
@cristipaval I'm confused how this cause a regression

**Comment by cristipaval** [comment]
@tienifr @Santhosh-Sellavel @luacmartins  I am reverting this PR since automatic authentication with the magic link is a very important feature.

**Comment by cristipaval** [comment]
> @cristipaval I'm confused about how this causes a regression, can you explain please with a bit more context thanks!

@Santhosh-Sellavel Please see follow [here](https://github.com/Expensify/App/pull/17970#issue-1683464026) this link to the Slack conversation with more context.

**Pull request merged**
