### PR TITLE
Revert "fix: Taxes - App allows deleted tax rate to be selected as currency default in offline mode."

### PR DESCRIPTION
**Pull request by iwiznia**
Reverts Expensify/App#42620

Caused https://github.com/Expensify/App/issues/42918#issuecomment-2143031145

cc @Krishna2323

### CODE REVIEW

**Comment by iwiznia** [comment]
We don't _need_ it but seems like the simplest option. You can work on re-sending the PR with the needed changes without us having to decide between blocking a deploy or deploying "broken" code or having to do a CP to staging.
As for the answer, I think you'll find it in the issue that was open due to it.

**Comment by iwiznia** [comment]
Oh wait, I guess we will have to CP the code either way (or deploy the broken code). Anyway, we can close this revert if the PR you send is ready to go in the next deploy.

**Comment by iwiznia** [comment]
> k, can you pls confirm this https://github.com/Expensify/App/pull/42620#issuecomment-2142356780 for me?


I think you'll find the answer to it in the issue that was open here https://github.com/Expensify/App/issues/42918

**Comment by MonilBhavsar** [comment]
Followup PR https://github.com/Expensify/App/pull/42974 is made, so I think we can close this. Thanks @Krishna2323!

**Comment by youssef-lr** [comment]
Can we close this?

**Comment by youssef-lr** [comment]
I think we can close 😀

**Pull request closed without merging**
