### PR TITLE
fix: Attachment - Press enter fullscreen mode in video player by Tab

### PR DESCRIPTION
**Pull request by nkdengineer**
### Fixed Issues

$ https://github.com/Expensify/App/issues/44379
PROPOSAL: https://github.com/Expensify/App/issues/44379#issuecomment-2196669019

### Tests

1. Open the app
2. Go to any conversation
3. Click "+" and choose Add Attachment
4. Choose any available video
5. Press the Tab on the video player to fullscreen
6. Press enter
7. Verify that: Only the video player is fullscreen; the app keeps its original size
Note: It won't work on native Android because [here](https://github.com/Expensify/App/pull/45379#issuecomment-2259618702)
- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open the app
2. Go to any conversation
3. Click "+" and choose Add Attachment
4. Choose any available video
5. Press the Tab on the video player to fullscreen
6. Press enter
7. Verify that: Only the video player is fullscreen; the app keeps its original size
Note: It won't work on native Android because [here](https://github.com/Expensify/App/pull/45379#issuecomment-2259618702)
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/d375efd9-e5b9-4919-b40b-243628f6d391

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/0a7c3dd5-9fad-4e87-a194-082178afce87

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/68cd30f6-4bb9-4ae3-af10-082039f88bb7

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/fe9b98e3-1787-4fb0-944a-0d4ea5464908

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/32d20e59-fcf6-4549-902c-d1e8779b993d

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/18f88852-18f0-45e2-bba6-4afab5c6c295

</details>

### CODE REVIEW

**Comment by getusha** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



https://github.com/user-attachments/assets/e2689061-44b3-491c-9f1f-b127f35a0942

</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/eca55be1-8034-4049-98b2-a24fff002273

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/2d5e3c34-37ec-4587-8c5f-797591fda14d

</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/21fa9736-7ff0-45bb-b4b0-b0dd8834ff3c

</details>

**Comment by getusha** [comment]
@nkdengineer i can reproduce this on android native

**Comment by getusha** [comment]
friendly bump @nkdengineer

**Comment by nkdengineer** [comment]
Checking this now.

**Comment by nkdengineer** [comment]
@getusha Sorry for the delay
I have some problems with building android
I don't think it's a bug [here](https://github.com/Expensify/App/pull/45379#issuecomment-2230575571)
On native, when you press enter it means you press the send button

**Comment by getusha** [comment]
>On native, when you press enter it means you press the send button

Isn't that the beahvior on every platform? when there is another element focused it shouldn't send.

**Comment by nkdengineer** [comment]
I'll update today

**Comment by nkdengineer** [comment]
Still investigating to find the reason

**Comment by nkdengineer** [comment]
@getusha It's a weird behavior in Android simulator that we can use the tab key to focus on an element. On native, we cannot detect the focus element [here](https://github.com/Expensify/App/blob/881c5482facc08af709f047025c863ad67b6d5b3/src/components/ActiveElementRoleProvider/index.native.tsx#L11), and then `onPress` can be triggered because `shouldDisableEnterShortcut` is `false` [here](https://github.com/Expensify/App/blob/881c5482facc08af709f047025c863ad67b6d5b3/src/components/Button/index.tsx#L137). 


We can't reproduce this in the real device so I don't think it's a bug.

**Comment by nkdengineer** [comment]
@getusha Friendly bump.

**Review by getusha — APPROVED** [review]

**Comment by getusha** [comment]
@nkdengineer could you add a note on the PR description stating this doesn't apply for Android native?

**Comment by nkdengineer** [comment]
@getusha i updated

**Comment by MonilBhavsar** [comment]
So, is this issue/limitation only on android simulator, and not on real device? Did we confirm it?

**Comment by nkdengineer** [comment]
@MonilBhavsar Yes, the we don't have the tab key in the real device. To ensure can you run an adhoc build then I can test again in the real device.

**Comment by MonilBhavsar** [comment]
Thanks for clarifying. That's a good idea. Let's test it.

**Comment by MonilBhavsar** [comment]
Let's merge main? I can retry then

**Comment by nkdengineer** [comment]
@MonilBhavsar Merged main.

**Comment by nkdengineer** [comment]
@MonilBhavsar The Android and IOS builds have failed.

**Comment by MonilBhavsar** [comment]
Error in gemfile. Not sure why though. I have started a new build

**Comment by nkdengineer** [comment]
@getusha Do you have an external keyboard to test with the real device?

**Comment by MonilBhavsar** [comment]
@getusha ^

**Comment by getusha** [comment]
> @getusha Do you have an external keyboard to test with the real device?

I don't have one currently, but I'll try to get it. :)

**Comment by nkdengineer** [comment]
@getusha friendly bump

**Comment by MonilBhavsar** [comment]
Any update here?

**Comment by getusha** [comment]
> Any update here?

Lost my android phone this week, i'll update on monday 😄

**Comment by getusha** [comment]
Tested with external keyboard and i can reproduce this issue & i can use `Tab` to focus elements.

https://github.com/user-attachments/assets/74a7ca88-03b1-40a5-966c-e2b403cddf5d

**Comment by MonilBhavsar** [comment]
you mean you can still reproduce issue on this branch? cc @nkdengineer

**Comment by getusha** [comment]
> you mean you can still reproduce issue on this branch? cc @nkdengineer

Yes, on android native with external keyboard

**Comment by nkdengineer** [comment]
I will check again.

**Comment by nkdengineer** [comment]
@getusha I checked again and here is my opinion:

1. This bug also happens on the latest main. Let's see the video when I focus on the back button via Tab key (The button is lighter) and press enter key the attachment is also sent. So we should fix it as a separate issue to not block the current issue.


https://github.com/user-attachments/assets/3bccf3ec-c977-4423-b889-098f7d68020f

2. I don't feed strong that we need to fix this case since it's barely edge case since we use external keyboard for Android app.

cc @MonilBhavsar What do you think?

**Comment by nkdengineer** [comment]
@getusha Any thoughts on my comment above

**Comment by getusha** [comment]
>This bug also happens on the latest main.

@nkdengineer yes, that's what we are trying to fix.

>I don't feed strong that we need to fix this case since it's barely edge case since we use external keyboard for Android app.

@MonilBhavsar what do you think? i'd say we fix this

**Comment by nkdengineer** [comment]
> @nkdengineer yes, that's what we are trying to fix.

@getusha I mean it's another bug. Let's see the video here, the bug doesn't happen on the web if we focus on the back button and press enter

https://github.com/user-attachments/assets/44886710-73cb-4eaa-ab07-5e3d6154860b

**Comment by MonilBhavsar** [comment]
> what do you think? i'd say we fix this

If I am understanding it correctly, the bug we're trying to fix is fixed for all platforms except android when using external keyboard, and we're thinking to leave that since it's an edge case? Isn't the root cause similar?

**Comment by nkdengineer** [comment]
> Isn't the root cause similar?

@MonilBhavsar Yeah the bug in Android happens when we use the tab key to focus on any button in the attachment modal not only the control video button.

And this bug doesn't happen when we focus on the back button in this screen on web like video that I shared above.

**Comment by MonilBhavsar** [comment]
Okay, so seems like the the cause is same, but the newly reported issue while testing only happens on Android while we focus on back button? If so I think we should fix it here as they are nearly similar issues. If you're thinking other way, please let me know

**Comment by nkdengineer** [comment]
Will check tomorrow

**Comment by nkdengineer** [comment]
Still investigating

**Comment by nkdengineer** [comment]
@MonilBhavsar After testing for many places in the App, the Android bug happens in the Modal component, other components don't face this bug. See the video here the cancel button is focused but the event of the delete button is triggered when we press on enter key. I can't find the RCA as to why this only happens in the Modal component.

https://github.com/user-attachments/assets/7dcef20e-7b11-449c-8ade-9649f62fb15a

**Comment by nkdengineer** [comment]
@MonilBhavsar Any thoughts on this?

**Comment by MonilBhavsar** [comment]
> See the video here the cancel button is focused but the event of the delete button is triggered when we press on enter key.

That's the correct expected behavior, no?

**Comment by MonilBhavsar** [comment]
Could you please describe the bug. I am not getting it, sorry.
I think if button is focussed and enter is pressed, we should trigger the event

**Comment by MonilBhavsar** [comment]
Ah, I see. Thanks for explaining. Not easy to figure out from video 😅 
Does this happen on main and for all modals? To be honest, this sounds very similar to the issue we're actually fixing

**Comment by nkdengineer** [comment]
> Does this happen on main and for all modals?

@MonilBhavsar Yes, it happens on the main. Currently, the bug that we're fixing in this PR is resolved except for the Android native. But it's an Android bug that happens in other places on the latest main of the App with different RCA. So I think we should ignore this here.

**Comment by MonilBhavsar** [comment]
> But it's an Android bug that happens in other places on the latest main of the App with different RCA. So I think we should ignore this here.

Okay and that does happen when using external hardware keyboard on android device. Is that right?

**Comment by nkdengineer** [comment]
> Okay and that does happen when using external hardware keyboard on android device. Is that right?

@MonilBhavsar Yes that happens when we use the tab key with external keyboard.

**Comment by MonilBhavsar** [comment]
Okay cool! I think very less people would actually use external keyboard with android device and since it happens on all modals, it's fine to descope it cc @getusha

**Review by getusha — APPROVED** [review]
It would have been great to fix this on Android, since we're trying to address the same issue on other platforms.

**Review by MonilBhavsar — APPROVED** [review]

**Pull request merged**
