### PR TITLE
[HOLD] fix: improve mobile's inline code block font and alignment

### PR DESCRIPTION
**Pull request by fabioh8010**
### Details

Made some changes in mobile's inline code block to have a scalable font just like the other texts and not cut emojis, and improved some stylings to make the code block more aligned with the text. This is a temporary solution until I have a proper fix to the react-native issue that is the root cause of this misalignment problem.

### Fixed Issues

$ https://github.com/Expensify/App/issues/8132
PROPOSAL: https://github.com/Expensify/App/issues/8132#issuecomment-1432933388

### Tests

1. Go to any chat
2. Send a message that contains inline code blocks and emojis e.g. ```Lorem ipsum `dolor 🚀` sit amet, con`s``e`ctetur `adipiscing elit, sed do eiusmod tempor incididunt` ut labore et dolore `magna` ali`q`u`a`. 🚀```
3. Verify if the inline code blocks are properly aligned with the normal text and if emojis are not being cut.
4. Increase the system or browser font size (if applicable). It should also increase the inline code block font properly.

### Offline tests

This feature doesn't change or is impacted by offline mode.

### QA Steps

Same as above.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/20051562/220730114-87b56218-f024-4867-94e2-035d8f6ef51c.mov

https://user-images.githubusercontent.com/20051562/220730349-ec22ecda-d99a-4391-a0ec-640b73be2a61.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/20051562/220730712-7947b916-b8d1-4957-addc-9f5bc11698db.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/20051562/220730766-e3973343-0023-4fb0-9e3b-fb3a8d464429.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/20051562/220730811-137a13af-9627-454a-8a10-5a26e0c61a90.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/20051562/220731998-296affde-5526-498e-833b-b86c0ba26855.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/20051562/220732425-9fefe3b5-79c5-4f5c-94d4-726c7430a789.mov

</details>

### CODE REVIEW

**Review by Santhosh-Sellavel — COMMENTED** [review]
@stitesExpensify 

Code Looks good, but I will like to test it a bit more extensively so I would test it over the weekend.

**Comment by stitesExpensify** [comment]
Hi @Santhosh-Sellavel did you get a chance to test this weekend like you planned?

**Comment by Santhosh-Sellavel** [comment]
Sorry didn't able to test extensively as I planned, caught occupied with other items and will update you by today or tomorrow.

**Comment by Santhosh-Sellavel** [comment]
Alignment is weird on iOS, line spacing for a code block

### Now
Screenshot 2023-03-03 at 12 49 46 AM

### Before
Screenshot 2023-03-03 at 12 53 39 AM

**Comment by fabioh8010** [comment]
Hi @Santhosh-Sellavel, I will take a look on this today.

**Comment by fabioh8010** [comment]
Hi @Santhosh-Sellavel !

Tweaking a little bit with the positioning in iOS, what do you think about this?

```diff
diff --git a/src/styles/codeStyles/index.ios.js b/src/styles/codeStyles/index.ios.js
index a387609040..0dfd3babfc 100644
--- a/src/styles/codeStyles/index.ios.js
+++ b/src/styles/codeStyles/index.ios.js
@@ -7,7 +7,7 @@ const codeWordWrapper = {
 
 const codeWordStyle = {
     position: 'relative',
-    top: 2.5,
+    top: 3.5,
 };
 
 const codeTextStyle = {
```

Screenshot 2023-03-07 at 14 21 56

Screenshot 2023-03-07 at 14 24 46

As stated before, this is a workaround so the alignment won't be perfect until I get a proper fix for this on native side. We canso also explore what was proposed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1677360137423139?thread_ts=1676991093.760849&cid=C01GTK53T8Q).

**Comment by Santhosh-Sellavel** [comment]
@stitesExpensify Can we have a check with design or lets proceed?

**Comment by stitesExpensify** [comment]
@fabioh8010 can you create a before and after so that we can tag design and have them pick between them?

**Comment by fabioh8010** [comment]
Sure @stitesExpensify , I'm OOO at the moment but I'll return on Tuesday and provide some examples to present to the design team!

**Comment by fabioh8010** [comment]
Hi @stitesExpensify @Santhosh-Sellavel , today I came across this [PR](https://github.com/Expensify/react-native/pull/43) while helping a team member with testing and we noticed that that PR could help us solving this back tick issue properly, without workarounds. The idea here would be using this new prop `textCodeBlock` to stylise the code blocks instead of using a `View`, thus avoiding the misalignment problem we currently have.

What do you think? Is it worth waiting for that PR and internal RN update to be available for us in order to proceed with a proper fix on my PR?

**Comment by fabioh8010** [comment]
@stitesExpensify @Santhosh-Sellavel Did you have opportunity to read my last comment?

**Comment by Santhosh-Sellavel** [comment]
I've read already It makes sense to wait here cc: @stitesExpensify

**Comment by stitesExpensify** [comment]
I agree that it makes sense to wait. Not using a workaround seems worth it to me!

**Comment by fabioh8010** [comment]
**Update:** The [old PR](https://github.com/Expensify/react-native/pull/43) was closed, and now a [new one](https://github.com/facebook/react-native/pull/37397) is being prepared to fix those related issues.

**Comment by stitesExpensify** [comment]
Since there hasn't been movement on that PR in ~6 months, should we close this PR for now?

**Comment by fabioh8010** [comment]
@stitesExpensify I think yes, we can open later if necessary.

**Pull request closed without merging**
