### PR TITLE
Create connect-ANZ.md

### PR DESCRIPTION
**Pull request by bfitzexpensify**
Adding an article to ExpensifyHelp from https://github.com/Expensify/Expensify/issues/309819 following the instructions from https://stackoverflowteams.com/c/expensify/questions/15135

### Fixed Issues
https://github.com/Expensify/Expensify/issues/309819

### CODE REVIEW

**Comment by bfitzexpensify** [comment]
OK, comments removed @rushatgabhane

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
@bfitzexpensify could you please rename the file from `connect-ANZ.md` to `Connect-ANZ.md`. Capitalize the `C`

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
We need to rename the file to `Connect-ANZ.md` 

1. Go to https://github.com/Expensify/App/blob/bfitzexpensify-patch-4/docs/articles/expensify-classic/bank-accounts-and-credit-cards/connect-ANZ.md
2. click edit
3. change `connect-ANZ.md` -> `Connect-ANZ.md`
image

**Comment by hayata-suenaga** [comment]
Same question as this one: https://github.com/Expensify/App/pull/28397#issuecomment-1744184332

**Comment by bfitzexpensify** [comment]
When I try to change the file name, I get this:

image

Do I need to just create a new file with that correct title?

**Review by rushatgabhane — APPROVED** [review]
@hayata-suenaga LGTM!

**Review by arosiclair — APPROVED** [review]

**Review by hayata-suenaga — APPROVED** [review]

**Comment by hayata-suenaga** [comment]
> Do I need to just create a new file with that correct title?
I guess we don't need the file anymore 🤔

**Pull request merged**
