### PR TITLE
delete money request with no trace if only changelogs exist

### PR DESCRIPTION
**Pull request by rojiphil**
@allroundexperts  @rlinoz

### Details

This PR implements the following changes:
1) During deletion of Money Request, the decision to delete the Transaction Thread report is made based on the `childVisibleAction` count instead of the last visible action’s message. As the `childVisibleActionCount` does not include MODIFIEDEXPENSE actions (i.e. changelogs), the Transaction Thread report will, henceforth, be deleted when there are only changelogs in the Transaction Thread
2) Add optimistic data with incremented `childVisibleActionCount` for task creation in offline scenarios. In offline scenarios, task creation will, thus, ensure that `reply` count is correctly displayed in the parent action of the IOU report.
3) Add optimistic data with decremented `childVisibleActionCount` for task cancellation in offline scenarios. In offline scenarios, task cancellation will, thus, ensure that `reply` count is correctly displayed in the parent action of the IOU report. 

### Fixed Issues
$ https://github.com/Expensify/App/issues/30219
PROPOSAL: https://github.com/Expensify/App/issues/30219#issuecomment-1823189501

### Tests

**Test 1: Delete Money Request with no trace when only changelogs are present**
Precondition: There must be no prior unsettled money request. 
1. Click `Request Money` via 1:1 chat’s FAB 
2. For  `Manual` request, enter the amount and generate a money request.
3. Click on `Report Preview` to open the IOU Report
4. Click on `Money Request Preview` to open the Transaction Thread
5. Click on the `Description` and enter any description and update the value. Verify that the changelog is generated for the updated description.
6. Click on 3dots menu and delete the money request.

**Expected Result**: The Transaction Thread report must be deleted, navigate back to the Chat Report and the Report Preview must also be removed

**Test 2: Task creation in offline scenarios must update the `reply count` correctly in parent report action**
1. Click `Request Money` via 1:1 chat’s FAB 
2. For  `Manual` request, enter the amount and generate a money request.
3. Click on `Report Preview` to open the IOU Report
4. Click on `Money Request Preview` to open the Transaction Thread
5. Go Offline
6. Click on `Assign Task` via 1:1 chat FAB and create a new task.
7. Go back to the IOU Report 

**Expected Result**: The Money Request preview should show a `Reply` count of 1 due to the newly created task.

**Test 3:  When offline, cancelling the task does not update the reply count in IOU Report.**
1. Click Request Money via 1:1 chat’s FAB
2. For Manual request, enter the amount and generate a money request.
3. Click on Report Preview to open the IOU Report
4. Click on Money Request Preview in IOU Report to open the Transaction Thread
5. Click on Assign Task via 1:1 chat FAB and create a new task. Go to IOU Report and verify that Money Request Preview shows reply count of 1.
6. Go Offline and go back to Task Report.
7. Click on 3dot menu and cancel the task
8. Navigate to the parent IOU Report

**Expected Result**: There should not be any reply count in the Money Request action of IOU Report as the task is cancelled.

- [ ] Verify that no errors appear in the JS console

### Offline tests

Same as the Steps for Tests Section.

### QA Steps

Same as the Steps for Tests Section.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>
<details>
<summary>Test 01</summary>

https://github.com/Expensify/App/assets/3004659/d1590a03-2343-4300-a6b3-8171dd1be9db

</details>
<details>
<summary>Test 02-03</summary>

https://github.com/Expensify/App/assets/3004659/b760c011-258e-4481-86c1-d73cc2608851

</details>
</details>

<details>
<summary>Desktop</summary>
<details>
<summary>Test 01</summary>

https://github.com/Expensify/App/assets/3004659/4826808a-752b-4c0c-a573-08ecad3f3be8

</details>
<details>
<summary>Test 02-03</summary>

https://github.com/Expensify/App/assets/3004659/3e178d5a-11f1-435d-8a16-3e4136227fce

</details>

</details>

<details>
<summary>iOS</summary>
<details>
<summary>Test 01</summary>

https://github.com/Expensify/App/assets/3004659/a9e38e94-982d-4bb0-9a2e-1d4d64042471

</details>
<details>
<summary>Test 02-03</summary>

https://github.com/Expensify/App/assets/3004659/385a9ef8-1227-4312-8e7d-ec3439b1d249

</details>
</details>

<details>
<summary>Android</summary>
<details>
<summary>Test 01</summary>

https://github.com/Expensify/App/assets/3004659/3ecedc38-a351-41b1-b790-4f774864f389

</details>
<details>
<summary>Test 02-03</summary>

https://github.com/Expensify/App/assets/3004659/14020c9a-70ff-4401-9704-d6afe5d761f4

</details>
</details>

<details>
<summary>Mobile Web - Chrome</summary>
<details>
<summary>Test 01</summary>

https://github.com/Expensify/App/assets/3004659/da77a709-9db7-4102-b7b0-83967f89ce03

</details>
<details>
<summary>Test 02-03</summary>

https://github.com/Expensify/App/assets/3004659/2be0e02f-8c73-40d1-b741-d26b42937d9c

</details>
</details>

<details>
<summary>Mobile Web - Safari</summary>
<details>
<summary>Test 01</summary>

https://github.com/Expensify/App/assets/3004659/f93f51a1-33a2-4ace-96b0-02b8d5cfca3a

</details>
<details>
<summary>Test 02-03</summary>

https://github.com/Expensify/App/assets/3004659/8ebdb4ba-8b4d-4cd4-b6cb-fedd3af7ab68

</details>
</details>

### CODE REVIEW

**Comment by rojiphil** [comment]
### Issue:
### Please re-state the problem that we are trying to solve in this issue.

**Problem** : When offline, cancelling the task does not update the reply count in IOU Report.

**Steps**:
	1	Click Request Money via 1:1 chat’s FAB
	2	For Manual request, enter the amount and generate a money request.
	3	Click on Report Preview to open the IOU Report
	4	Click on Money Request Preview in IOU Report to open the Transaction Thread
	5	Click on Assign Task via 1:1 chat FAB and create a new task. Go to IOU Report and verify that Money Request Preview shows reply count of 1.
	6	Go Offline and go back to Task Report.
	7	Click on 3dot menu and cancel the task
	8	Navigate to the parent IOU Report

**Expected Result**: There should not be any reply count in the Money Request action of IOU Report as the task is cancelled.

<details>
<summary>Issue Video</summary>

https://github.com/Expensify/App/assets/3004659/3ccbcbb7-ea02-4f3b-a472-3f0653198086

</details>

### What is the root cause of that problem?

We are not decrementing the `childVisibleActionCount` as we are doing it for normal comments [here](https://github.com/Expensify/App/blob/3ed43fff9aaa2814693094d5e95e6ba113822e69/src/libs/actions/Report.ts#L1169C1-L1180C6)

### What changes do you think we should make in order to solve the problem?

We need to decrement the `childVisibleActionCount` as follows [here](https://github.com/Expensify/App/blob/3ed43fff9aaa2814693094d5e95e6ba113822e69/src/libs/actions/Task.js#L774C1-L774C1)


    // Update optimistic data for parent report action if the report is a child report and the task report has no visible child
    const childVisibleActionCount = lodashGet(parentReportAction, 'childVisibleActionCount', 0);
    if (childVisibleActionCount === 0) {
        const optimisticParentReportData = ReportUtils.getOptimisticDataForParentReportAction(
            parentReport.reportID,
            parentReport.lastVisibleActionCreated || '',
            CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
        );
        if (isNotEmptyObject(optimisticParentReportData)) {
            optimisticData.push(optimisticParentReportData);
        }
    }

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment]
@allroundexperts 
PR is ready for review.

**Comment by allroundexperts** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by rojiphil** [comment]
@allroundexperts 
Just noticed that this PR will also resolve MEDIUM priority issue [here](https://github.com/Expensify/App/issues/31630) in vip-vsb 
Looking forward to your PR review.

**Comment by mallenexpensify** [comment]
@allroundexperts please review, it looks like it's been two weeks.

**Comment by rojiphil** [comment]
@allroundexperts 
Can you please prioritize on review here?

**Comment by allroundexperts** [comment]
Yep. I'll finish this up today.

**Review by allroundexperts — APPROVED** [review]
Tests well!

Apologies for the delay. I was OoO last week.

**Review by rlinoz — APPROVED** [review]

**Pull request merged**
