### PR TITLE
Fix receipt image blink when opening it the first time

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

The receipt image blinks when we open it the first time because the size is not ready yet and we scale it really big.

### Fixed Issues

$ https://github.com/Expensify/App/issues/33625
PROPOSAL: https://github.com/Expensify/App/issues/33625#issuecomment-1870170835

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

1. Create a new scan request to any user
2. Press the IOU preview twice to open the transaction thread
3. Press the receipt image to open the image preview
4. Verify the image shows without any blink
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/50919443/dad56236-52a7-43d4-9c63-809c228e1ecf

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/50919443/cba1b78d-877c-47b2-8d9b-4a8fb1de81de

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/50919443/36868a80-2b8f-4281-9878-3edbdff69a69

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/50919443/de2efc5c-65b8-4f11-83ee-71d3c9d25920

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/50919443/e2abc46b-8889-4ded-9a99-c255ac08d258

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/50919443/08e05517-bfc1-4684-923c-25adf9168c6a

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
@Ollyws please review when you get the chance 🙇

**Comment by bernhardoj** [comment]
Hmm, somehow after this [PR](https://github.com/Expensify/App/pull/33745) is merged, the image `onLoad` is called thrice. First with a smaller size and the second (and third) one with a bigger size. If I tried reverting it locally, everything back to normal

Here is the size comparison before and after the above-linked PR.

Before (no issue):
Screenshot 2024-01-09 at 13 35 27

After (has issue):
Screenshot 2024-01-09 at 13 36 01

(the number after the content size object is the zoom scale)

If we try to calculate the width/height * zoom scale, we actually get a size that fits the screen. The problem here is that the scale size is animated but the image size is not.

So, when we get the new image size, the image is still scaled with the previous zoom scale for a brief moment. In our case, when the image size becomes {height: 5148, width: 2376}, it is still scaled with 0.22031172000665591 instead of 0.14028395846577663.

To overcome this new behavior, I'm thinking of a new solution:
First, we will create a new debounced function of `setImageLoaded` state (in Lightbox.js).

```
const debouncedSetImageLoaded = useDebounce(
    useCallback((loaded) => {
        console.log('load ended')
        setImageLoaded(loaded)
    }, []),
    500,
    { maxWait: 1000 }
)
```

Then, in `onLoadEnd`, instead of calling `setImageLoaded`, we call `debouncedSetImageLoaded`. Next, we apply the opacity style directly to the Image component. If `isImageLoaded` is false, we set the opacity to 0.
```
{opacity: isImageLoaded ? 1 : 0}
```

And we can remove the opacity style from MultiGestureCanvas. With this solution, the image will be shown when the last `onLoadEnd` callback is called. I use maxWait in case there is a bug where the `onLoadEnd` is called infinitely.

It works fine so far on my end, can you please test this and let me know whether we should proceed with this new solution or not?

_Why do I debounce the onLoadEnd and not onLoad?_
The 2nd onLoad will be called only after the image gets the size from the 1st onLoad. So, even if we debounce `onLoad`, it will be called 3 times. But from my testing, the blink is gone even though the `onLoad` is called 3 times and maybe it is because each size update is delayed.

**Comment by bernhardoj** [comment]
@Ollyws let me know your thoughts for the above finding!

**Comment by bernhardoj** [comment]
@Ollyws I'm afraid there is nothing much we can do as this is most likely the issue with expo-image which is actually already out of scope from the initial issue.

**Comment by bernhardoj** [comment]
@Ollyws updated. Please check

**Comment by bernhardoj** [comment]
Yes, that's expected if we use debounce. The image will be delayed at least 500ms (debounce wait time) or a maximum of 1s (max wait). So far, 500ms is a safe value to prevent the multiple onLoad with different sizes being called.

One idea to improve it is to have a ref called `hasCache`.

```
const hasCache = useRef(!!cachedDimensions.get(source))
```

This will indicate whether the image size has been cached or not. If not yet, we will debounce it, otherwise we won't debounce it. 

```
onLoadEnd={() => {
    if (!hasCache.current) {
        debouncedSetImageLoaded(true)
        return;
    }
    setImageLoaded(true)
}}
```

What do you think?

**Comment by bernhardoj** [comment]
The reassure is unrelated. It fails on the search page. Happens on `main`.

**Comment by bernhardoj** [comment]
The second issue doesn't seems reproducible anymore on latest main for me. Can you check that too? You can log the `contentSize` here
https://github.com/Expensify/App/blob/668df99bfa6bad36978622e9c5685db70077f56b/src/components/Lightbox/index.tsx#L111-L117

**Comment by bernhardoj** [comment]
@Ollyws bump

**Comment by bernhardoj** [comment]
@Ollyws yes, I retested a few times and the original solution still work.

Please check.

**Review by Ollyws — APPROVED** [review]
LGTM.

**Review by marcochavezf — APPROVED** [review]
LGTM, thanks guys!

**Pull request merged**
