### PR TITLE
Remove SidebarBottom

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
Clean up step related to the addition of the Settings page which is now accessible via the avatar.

### Fixed Issues
❌ 

### Tests
1. Verify the app links and sign out text + display name is not present in the Left Hand Navigation

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by Luke9389** [comment]
Seems pretty straightforward. I'll test on each platform though just in case.

**Comment by marcaaron** [comment]
Thanks @Luke9389 I'm testing on iOS and Android now

**Comment by Luke9389** [comment]
Man, mobile development is usually a pretty error-ridden process for me, and this time–shockingly–turned out to be smooth sailin'. Looks good on all platforms. Nice work! This app is really comin' together.

**Review by Luke9389 — APPROVED** [review]
Tested on all platforms 👍

**Comment by Luke9389** [comment]
Will merge after conflicts are resolved. They looked trivial but I didn't want to touch it (wasn't sure if it's bad form to resolve conflicts on behalf of the PR author).

**Comment by marcaaron** [comment]
Thanks fixed now.

**Pull request merged**
