### PR TITLE
Sort Distance Rates on IOURequestsStepDistanceRate.tsx

### PR DESCRIPTION
**Pull request by ChavdaSachin**
### Fixed Issues

$ https://github.com/Expensify/App/issues/50304
PROPOSAL: https://github.com/Expensify/App/issues/50304#issuecomment-2395514652

### Tests

Same as QA tests

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA tests.

### QA Steps

Note: This is a beta feature, so enable canUseP2PDistanceRequests beta before proceeding.
1. Go to workspace settings > Distance rates
2. Add a few distance rates
3. Go to workspace chat.
4. Click + > Submit expense > Distance.
5. Enter waypoints > Next.
6. Click Rate on confirmation page.
7. Notice Distance rates are sorted based on rate values.
8. Go to Troubleshoot > Clear cache and restart 
9. Select Reset and refresh
10. Repeat steps 3-6.
11. Notice Distance rates are sorted based on rate values.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/389a81f7-491a-4198-97f1-beb43a252b01

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/1112c9e3-c133-4613-bd1e-024ef7cc029f

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/3ec4e1f7-8b05-4b18-a936-5815c8d1f6c4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/3c50c321-9a35-4f7d-a4c3-1b8463c621be

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/63bd7e2b-7ef7-4777-8fc9-f047428a0580

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/d7e38420-9c20-4999-9c02-7fba941dad1b

</details>

### CODE REVIEW

**Comment by ChavdaSachin** [comment]
We have an additional concern here,

Names produced for Distance rates are not up to the mark, 
- Add few distance rates.
- delete one of the distance rate from the list.
- Add a new distance rate.
Go to IOURequest Distance Rate step. notice Names produces for the rates lacks consistent naming logic.

From birds eye view - this function here needs improvement.
https://github.com/Expensify/App/blob/1535588058820e6830b5d0427e1f013ad45f5a87/src/libs/PolicyDistanceRatesUtils.ts#L42-L45

Which causes visual inconsistency, see
Screenshot 2024-10-14 at 5 32 29 PM

What should be our next step here?
Should we take care of naming as part of this PR?

cc. @paultsimura @madmax330

**Comment by ChavdaSachin** [comment]
Alright I will proceed with the checklist then...

**Comment by ChavdaSachin** [comment]
And about useOnyx migration?
check is failing here https://github.com/Expensify/App/actions/runs/11327065310/job/31497336590?pr=50721

**Comment by ChavdaSachin** [comment]
IMO we should have a separate PR for migration.
Today I merged a PR where we decided to handle ONYX migration as separate PR.

**Comment by ChavdaSachin** [comment]
https://github.com/Expensify/App/pull/50142/files#diff-7b1d9dac2fdc5c08e5f62ae430056029ab25f103fa19bd77688286f188ec3507
This PR looks almost finished, so rather then copying let's wait for the pr to merge with main. shouldn't take long...

**Comment by ChavdaSachin** [comment]
Done

**Review by paultsimura — APPROVED** [review]
LGTM ✔️

**Review by madmax330 — APPROVED** [review]

**Pull request merged**
