### PR TITLE
Fix waypoints removal

### PR DESCRIPTION
**Pull request by paultsimura**
### Details

Fix the bug when it was impossible to remove a waypoint when editing a Distance request.

### Fixed Issues

$ https://github.com/Expensify/App/issues/34686
PROPOSAL: https://github.com/Expensify/App/issues/34686#issuecomment-1896980125

### Tests

Same as QA

### Offline tests

Same as QA

### QA Steps

1. Create a distance request with 3 waypoints
2. Navigate to the distance request details
3. Disable the internet connection
4. Click on the distance field to edit
5. Click on a waypoint
6. Click on the 3 dot menu > Delete waypoint
7. Hit Save
8. Go back online
- [ ] Verify the distance & amount are updated
- [ ] Verify the waypoint was deleted successfully

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/12595293/4cfe4ad5-93af-487c-8567-36f9d46b83cc

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/12595293/8be92ad0-bf88-4a21-9fcf-d37fe1d5d78e

</details>

### CODE REVIEW

**Comment by paultsimura** [comment]
@alitoshmatov there are some complications on the Onyx side. Asked in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1706359180399219?thread_ts=1705484273.717249&cid=C01GTK53T8Q

**Comment by paultsimura** [comment]
Hey @tgolen, I think I'm facing the  **Onyx race condition** once again – would appreciate your closer look 🙏 

I'm attaching a screen recording with every network call expanded and checked key-by-key, you can see that in all the operations after the first OpenReport, the transaction has either 2 waypoints or 3 (with the last one explicitly set to `null`, which you implemented).

https://github.com/Expensify/App/assets/12595293/2b8207fb-b895-402c-81c8-c30bb9e53796

The steps to reproduce are:
1. Create a Distance request
2. Visit it once (so it's loaded into Onyx)
3. Move back to the parent Expense report
4. Go offline
5. Open the created Distance request (this is important so that we load the `OpenReport` call into the queue)
6. Remove a waypoint and save the result
7. Go online

I suspect there is a race condition between the `merge` and `mergecollection` operations once they are batched when coming online: the `mergecollection`, even though it comes first chronologically, overwrites the `merge` operations that come later.

We saw a similar faulty behavior here: https://github.com/Expensify/App/issues/33544#issuecomment-1868286445 (the fix was a kinda workaround), and here: https://github.com/Expensify/App/issues/28737 (this one was supposed to fix this very issue, but it remains, apparently).

cc: @Julesssss as you were handling the original Onyx out-of-order issue.

**Comment by tgolen** [comment]
Do you think it's an issue with the App's API queue, or internal to Onyx? Can we isolate the bug and create a unit test in `react-native-onyx` that demonstrates the bug and allows us to fix it?

**Comment by paultsimura** [comment]
> Do you think it's an issue with the App's API queue, or internal to Onyx?

I tried batching 2 Onyx operations (`mergecollection` + `merge`) in one call using a browser console like this:
```js
Promise.all([
    Onyx.mergeCollection('transactions_', {
        'transactions_4605945495455879570': {
            comment: {
                waypoints: {
                    waypoint0: "a",
                    waypoint1: "b",
                    waypoint2: "c",
                },
            },
        }
    }),
    Onyx.merge(`transactions_4605945495455879570`, {
        comment: {
            waypoints: {
                waypoint0: "a",
                waypoint1: "c",
                waypoint2: null,
            },
        },
    })
]);
```

This way, the data gets processed in the correct order.
So I would say it might be more related to the App's API queue, but I cannot speak with 100% confidence – I'm not that familiar with how Onyx works under the hood, unfortunately.

**Comment by tgolen** [comment]
Could you try that same kind of test from the console using Onyx.update()
with both a mergeCollection and a merge in that same order and see if you
get the same or a different result?

**Comment by tgolen** [comment]
You could also try two calls to Onyx.update(). The first with a
mergeCollection and the second with a merge. That will probably be more
accurate with how the updates are applied to Onyx in the network layer.

**Comment by paultsimura** [comment]
```js
```

**Comment by paultsimura** [comment]
Both options work correctly (this and with both updates in one call):

```js
Onyx.update([{
    "onyxMethod": "mergecollection",
    "key": "transactions_",
    "value": {
        "transactions_4605945495455879570": {
            comment: {
                waypoints: {
                    waypoint0: "a",
                    waypoint1: "b",
                    waypoint2: "c",
                },
            },
        }
    }
}]);
Onyx.update([{
    "onyxMethod": "merge",
    "key": "transactions_4605945495455879570",
    "value": {
        comment: {
            waypoints: {
                waypoint0: "a",
                waypoint1: "c",
                waypoint2: null,
            },
        },
    }
}]);
```

**Comment by tgolen** [comment]
Well, that's sure interesting. I guess the next step would be to add some debugging inside Onyx to see what order they are being applied in during the network requests. 

You could start here:
https://github.com/Expensify/react-native-onyx/blob/main/lib/Onyx.js#L1477-L1519

and follow the instructions [here](https://github.com/Expensify/react-native-onyx?tab=readme-ov-file#development) for an easy way to build/debug it.

**Comment by paultsimura** [comment]
@tgolen thanks for your guidance on this.
I found eventually that we **do have** the race condition of how these events are being processed. 

I've added logs here to track when we build the promise for each operation:
https://github.com/Expensify/react-native-onyx/blob/8cca556b08bf858c17a7d4f5ddd2879ac3f456d4/lib/Onyx.js#L1497-L1515

And here to track when each promise is resolved:
https://github.com/Expensify/react-native-onyx/blob/63b07a3c9f82b9b5be5782c96dff9e1138ac1821/lib/storage/providers/IDBKeyVal.ts#L18-L39

You can see on the recording that we enqueue the promises correctly, but the `merge` ones get resolved before the `mergeCollection`:

https://github.com/Expensify/App/assets/12595293/afdeb3ab-6b74-46a5-b505-237d415c66ca

**Comment by tgolen** [comment]
Oh awesome! Way to dig into that. @hannojg could you take a look at this and see if you can provide any guidance? I think it was you that added this originally.

**Comment by hannojg** [comment]
Hey, sorry, but I have never worked on that code 😄

**Pull request closed without merging**
