### PR TITLE
Add auth token to image URL

### PR DESCRIPTION
**Pull request by roryabraham**
I think we just missed a couple places where the image url needs an auth token. Not 100% clear on the cause/effect, but the result was that we were getting weird image formatting where all images were using the default image size (square). Anyways, this seems to fix it 🤷🏼‍♂️

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/146484

### Tests
1) Upload a tall image and a wide image into chat.
2) Make sure the thumbnail preview for each is not square.
3) Click on each, and make sure it scales appropriately (does not become a square) and is not cropped at all.

### Tested on:

- [x] Web
- [x] Desktop
- [x] iOS
- [ ] Android
- [ ] Mobile Web

### Screenshots

image

image

image

### CODE REVIEW

**Review by marcaaron — DISMISSED** [review]
Wooo! Nice catch @roryabraham 🙇‍♂️

**Review by thienlnam — CHANGES_REQUESTED** [review]
Looks good, just question about maybe using state values so we don't have multiple constants

**Review by timszot — DISMISSED** [review]
No additional comments from me, leaving this to the other reviewers and keeping an eye on this to learn more.

**Review by thienlnam — CHANGES_REQUESTED** [review]

**Review by thienlnam — DISMISSED** [review]
Thank you!!

**Review by marcaaron — CHANGES_REQUESTED** [review]

**Review by thienlnam — DISMISSED** [review]

**Review by marcaaron — DISMISSED** [review]

**Review by marcaaron — APPROVED** [review]

**Pull request merged**
