### PR TITLE
[No QA] Don't Overwrite Storybook docs directory when deploying

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
This should work 🤞 

### Fixed Issues
No Issue. But follow up to https://github.com/Expensify/Expensify/issues/164021

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Review by roryabraham — APPROVED** [review]
Let's give this a go!

**Pull request merged**
