### PR TITLE
Fix: reset the wallet balance when transfer is successful

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7626

### Tests | QA Steps
1. Go to Settings->Payment -> Transfer balance page.
2. Select the Mode and account.
3. Click Transfer balance. 
4. Confirm that you are taken back to the Payments Page, a confirmation modal is shown and the wallet balance is set to 0.

#### To test locally
1. Apply this patch 
```Diff
diff --git a/src/libs/actions/PaymentMethods.js b/src/libs/actions/PaymentMethods.js
index fd9fa25be..59bff94b8 100644
--- a/src/libs/actions/PaymentMethods.js
+++ b/src/libs/actions/PaymentMethods.js
@@ -194,6 +194,10 @@ function transferWalletBalance(paymentMethod) {
         [paymentMethodIDKey]: paymentMethod.methodID,
     };
     Onyx.merge(ONYXKEYS.WALLET_TRANSFER, {loading: true});
+    Onyx.merge(ONYXKEYS.USER_WALLET, {currentBalance: 0});
+    Onyx.merge(ONYXKEYS.WALLET_TRANSFER, {shouldShowConfirmModal: true, loading: false});
+    Navigation.navigate(ROUTES.SETTINGS_PAYMENTS);
+    return;
 
     API.TransferWalletBalance(parameters)
         .then((response) => {
diff --git a/src/libs/actions/Wallet.js b/src/libs/actions/Wallet.js
index adb53b3e2..e25ef174c 100644
--- a/src/libs/actions/Wallet.js
+++ b/src/libs/actions/Wallet.js
@@ -178,7 +178,7 @@ function fetchUserWallet() {
                 return;
             }
 
-            Onyx.merge(ONYXKEYS.USER_WALLET, response.userWallet);
+            Onyx.merge(ONYXKEYS.USER_WALLET, {...response.userWallet, currentBalance: 12345});
         });
 }
 ```
 2. Go directly to http://localhost:8080/settings/payments/transfer-balance
 3. Follow the previous testing/QA steps.

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

https://user-images.githubusercontent.com/24370807/153726673-c1247b53-6658-49c3-a3f2-2b7aa0c4d468.mp4

#### Mobile Web

https://user-images.githubusercontent.com/24370807/153726604-8621e770-c49b-4424-be62-2454cdd63e2d.mp4

### CODE REVIEW

**Comment by NikkiWines** [comment]
@parasharrajat please include steps for how to get a non-zero balance as well so that this can be tested using a fresh account

**Comment by parasharrajat** [comment]
@NikkiWines I have added the testing steps.

**Comment by NikkiWines** [comment]
> @NikkiWines I have added the testing steps

Thank you! 

> I don't know the way to load the wallet.

No worries, I would just add a step 1 for QA steps that they should log into an account with a non-zero wallet balance.

**Comment by NikkiWines** [comment]
> Please let me know if You want me to attach clips for those tests.

If possible, I do think it's good to attach clips of the tests for mweb, android, ios

**Review by NikkiWines — COMMENTED** [review]
Works well! Just missing some screenshots, will approve once those are added

**Comment by parasharrajat** [comment]
I have added the test clips for web| Desktop| Mobile web. I can't open the transfer page directly on Android| IOS due to KYCWall. But I think they are not needed. The change is small and clear.

**Review by NikkiWines — APPROVED** [review]
👍

**Comment by mvtglobally** [comment]
@NikkiWines  We are not able to QA Transfer Balance functionality due ty KYC wall. Can you validate this internally?

**Comment by NikkiWines** [comment]
Asking @joekaufmanexpensify since it looks like his account is the one being used in the video shown in the issue

**Comment by joekaufmanexpensify** [comment]
My balance was already transferred, but sent Nikki $1 to validate that this works when attempting a balance transfer.

**Comment by NikkiWines** [comment]
Confirms the fix works as anticipated 🎉  Ty @joekaufmanexpensify for the help! 

https://user-images.githubusercontent.com/16747822/154164905-d79b7eac-f058-4e36-a9c4-73c967943165.mov

**Pull request merged**
