### PR TITLE
[No QA] Only post to slack when job was successful

### PR DESCRIPTION
**Pull request by tgolen**
### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/183630

### Tests
The next time there is a deploy failure, we can verify there was no success message posted

### QA Steps
None

cc @roryabraham

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
LGTM

**Review by aldo-expensify — APPROVED** [review]
Looks good to me.

NAB: just a doubt, there is no message on slack on failure, right?

**Comment by tgolen** [comment]
@aldo-expensify There is a message for the failure, yeah. It's higher up in the file: https://github.com/Expensify/App/blob/300decb609729b1a62d0b1ab08d80d44a8fc8048/.github/workflows/platformDeploy.yml#L350-L372

**Comment by aldo-expensify** [comment]
> @aldo-expensify There is a message for the failure, yeah. It's higher up in the file:

Cool, I missed it!, thanks

**Comment by yuwenmemon** [comment]
> NAB: just a doubt, there is no message on slack on failure, right?

I didn't see this show up when the successful message was displayed:
https://expensify.slack.com/archives/C07J32337/p1635813884219300

Are we sure the fail message posts in #deployer?

**Comment by tgolen** [comment]
> Are we sure the fail message posts in #deployer?

Well, according to that action, the fail message posts to #announce.

**Pull request merged**
