### PR TITLE
Add isStagingDeployLockedTest for GitHub action

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
We wanted to add some tests to the GitHub action, so this adds one as a framework for new actions. We need to confirm this all works on the GitHub workflows as well since there is some logic changes.

### Fixed Issues
Fixes headaches in the future hopefully

### Tests
1. Make sure unit tests pass
2. Create a staging deploy issue
3. Lock it
4. Merge another PR
5. Verify it leaves the correct comment saying the PR will be deployed in the future

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
Thanks, this is awesome!

**Review by francoisl — APPROVED** [review]

**Comment by AndrewGable** [comment]
Ok so actions are running so slow I was able to test this within it's own PR. Tests pass!

**Comment by AndrewGable** [comment]
Ohh snap, no they didn't pass because I forgot to rebuild the actions 😬 - I will do that in https://github.com/Expensify/Expensify.cash/pull/1784

**Comment by AndrewGable** [comment]
Ok confirmed this works with this test 👉  https://github.com/Expensify/Expensify.cash/pull/1784#issuecomment-799811044

**Pull request merged**
