### PR TITLE
[No QA] Upgrade react native CLI to 6.2.0

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Fixes a local build error I'm seeing on Android: https://expensify.slack.com/archives/C01GTK53T8Q/p1641859243262700

**Note:** I followed the custom upgrade instructions [here](https://github.com/react-native-community/cli#updating-the-cli).
**Note:** I had to manually install fbjs https://github.com/wonday/react-native-pdf/pull/592

### Fixed Issues
$ n/a

### Tests
1. Run `rm -rf node_modules`
1. Run `npm i`
1. Run `react-native start --reset-cache`
1. Run the app on all platforms – verify that they build and run successfully.

- [x] Verify that no (new) errors appear in the JS console

### QA Steps
None.

### Tested On

- [x] Web
- [ ] ~~Mobile Web~~ This is the same build as web, the client makes no difference wrt to the CLI
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Desktop
image

### CODE REVIEW

**Comment by roryabraham** [comment]
Tagging in @Jag96 for another review because we chatted about this 1:1

**Comment by roryabraham** [comment]
Curious why there is a diff in the compiled GitHub actions? I am too. I'm not sure I have a 100% crystal clear understanding of exactly what happened here, but my hand-wavy explanation is:

1. The old version of the CLI came bundled with https://www.npmjs.com/package/fbjs as a peer dependency. The new version does not, so upgrading implicitly removed that code from our `node_modules`.
    - Note: As a result, I had to add it explicitly because it was needed by `react-native-pdf`, which doesn't properly list it as a peer dependency, and instead just acknowledges the peer dependency as a requirement in the README installation instructions: https://github.com/wonday/react-native-pdf/pull/592
1. Anyways, one of the dependencies used in our GitHub Actions must have somehow been wrapped up with the `fbjs` module such that `ncc` was including `fbjs` (or some subset thereof) in the compiled GitHub Actions output. But now that `fbjs` is included as its own separate dependency, `ncc` knows that it's not imported by our GitHub Actions. So all that code is no longer in the compiled `ncc` output.

**Review by Jag96 — COMMENTED** [review]
I've got a Podfile.lock diff but the changes look unrelated, just confirming that there wasn't anything that had to be pushed there.

The GH actions diff is interesting, I built the actions locally and confirmed there isn't a diff so not sure what the cause is. 

> Anyways, one of the dependencies used in our GitHub Actions must have somehow been wrapped up with the fbjs module such that ncc was including fbjs (or some subset thereof) in the compiled GitHub Actions output. But now that fbjs is included as its own separate dependency, ncc knows that it's not imported by our GitHub Actions. So all that code is no longer in the compiled ncc output.

👍 Idk if there's a better way to confirm that, but I'm not sure we need to.

**Review by neil-marcellini — APPROVED** [review]
I followed the test steps and got it running on all platforms. Thanks for doing the upgrade.

**Comment by kidroca** [comment]
- Hey just so you know `fbjs` was not a problem before because it was a part of the old `"@react-native-community/cli": "4.13.1"`
- @roryabraham I've opened an issue regarding `fbjs` beeing a peer dep some time ago: https://github.com/wonday/react-native-pdf/issues/610

Regarding `"@react-native-community/cli": "6.2.0"` - we don't need it in `dependencies` - it's a transitive dependenciesm meaning it's listed in `react-native`'s `dependencies` and is installed along `react-native`

We can remove it from `package.json` following this migration guide: https://github.com/react-native-community/cli#updating-the-cli
1. find all the @react-native-community/cli prefixed entries in package-lock.json and remove them
2. run `npm install` 

---

Finally,

We do use `@react-native-community/cli-tools` for development purposes:

https://github.com/Expensify/App/blob/7e50a8d04d58f732db69e127b60515702700bd63/config/checkMetroBundlerPort.js#L1

It should be listed in our `dev-dependencies`

**Pull request merged**
