### PR TITLE
Migrate index.native.js to function component

### PR DESCRIPTION
**Pull request by kadiealexander**
### Fixed Issues

$ https://github.com/Expensify/App/issues/16187
PROPOSAL: 

### Tests

1. Upload a password-protected PDF to an Expensify chat
2. Open the PDF
3. Click to enter the password
4. Enter the correct password
5. Verify the PDF appears
6. Close the PDF
7. Open the PDF
8. Click to enter the password
9. Enter an incorrect password
10. Verify that an incorrect password error occurs

- [x] Verify that no errors appear in the JS console

### Offline tests

If you go offline once the PDF is uploaded, you should be able to still complete the steps above. 

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/59587260/fdca4dc1-3f09-4e50-a18b-ea241b5c191d

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/pull/24615#issuecomment-1797941582

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/59587260/1dfbed07-b661-46b4-9892-5362a9b7d22a

</details>

<details>

<summary>Desktop</summary>

https://github.com/Expensify/App/assets/59587260/0bff4df1-8299-443d-9b09-ebe8920c0a53

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/59587260/7d98cb69-cb43-4ce0-8033-863111466886

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/pull/24615#issuecomment-1797941582

</details>

### CODE REVIEW

**Comment by kadiealexander** [comment]
@0xmiroslav @puneetlath I'd love your thoughts on this! When testing this, I get stuck in a "invalid password" loop even though I know my PDF password is valid. I don't get any console errors or anything to help me debug, it just declines my password every time. Could either of you take a look and see what might be causing this? 🙏 I'm at a loss!

**Comment by kadiealexander** [comment]
@0xmiroslav I'm still getting the "wrong password" error when using your PDF:

image

Are you also testing on iOS?

**Comment by kadiealexander** [comment]
Yup, works fine on main!

image

**Comment by kadiealexander** [comment]
@Puneetlath @0xmiroslav any thoughts on what might be causing this issue? Puneet, could you please try testing my branch and see if you run into the same issue?

**Review by 0xmiroslav — CHANGES_REQUESTED** [review]

**Comment by kadiealexander** [comment]
@0xmiroslav I've addressed the comments you left, could you please review again?

**Comment by kadiealexander** [comment]
@0xmiroslav bump for review please!!

**Review by 0xmiroslav — CHANGES_REQUESTED** [review]
Convert HOC to hook:
- `withWindowDimensions` > `useWindowDimensions`
- `withKeyboardState` > `useKeyboardState`
- `withLocalize` > `useLocalize`
- `withThemeStyles` > `useThemeStyles`

**Comment by kadiealexander** [comment]
@0xmiroslav I've addressed your comments, please review again when you get a chance.

**Comment by kadiealexander** [comment]
@0xmiroslav bump!

**Comment by kadiealexander** [comment]
@0xmiroslav could you please check this one again?

**Comment by kadiealexander** [comment]
@0xmiroslav could you please take another look? :)

**Comment by kadiealexander** [comment]
@0xmiroslav bump!

**Comment by kadiealexander** [comment]
Thanks @0xmiroslav, hopefully this one is the ticket!

**Comment by kadiealexander** [comment]
@0xmiroslav I'm getting a notification saying it's already up to date. Any other ideas for fixing the error?

image

**Comment by kadiealexander** [comment]
@0xmiroslav please review, hopefully for the last time!

**Review by 0xmiroslav — APPROVED** [review]
Looks good except [these propTypes console warnings](https://github.com/Expensify/App/pull/24615#issuecomment-1899819812).
As they're dev only error, not blocker.

**Review by MonilBhavsar — COMMENTED** [review]
Working limited time this week. I'll be back to this shortly

**Comment by mallenexpensify** [comment]
https://github.com/Expensify/App/issues/16187
@Santhosh-Sellavel reassigned the above, please review the PR.

**Comment by Santhosh-Sellavel** [comment]
@kadiealexander

Console errors in the recording below are introduced in this PR can you fix them please, thanks!
https://github.com/Expensify/App/assets/85645967/2bb9d0ac-f18b-4ec8-a686-c3984dc990c7

**Review by Santhosh-Sellavel — CHANGES_REQUESTED** [review]
Check this out https://github.com/Expensify/App/pull/24615#issuecomment-1908773289!

**Comment by Santhosh-Sellavel** [comment]
Any update @kadiealexander

**Comment by kadiealexander** [comment]
Hey @Santhosh-Sellavel, I think it's best if I remove withThemeStyles alongside [this PR](https://github.com/Expensify/App/pull/31281) as opposed to including them in this PR. What are your thoughts on this?

**Comment by Santhosh-Sellavel** [comment]
> Hey @Santhosh-Sellavel, I think it's best if I remove withThemeStyles alongside [this PR](https://github.com/Expensify/App/pull/31281) as opposed to including them in this PR. What are your thoughts on this?

Somehow this got missed from my radar, yeah I agree we can merge this. Sorry I missed the fact that props are still required in web platforms
we need to ensure the errors are [resolved](https://github.com/Expensify/App/pull/24615#issuecomment-1908773289) in  https://github.com/Expensify/App/pull/31281

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
