### PR TITLE
code block styling fixed

### LINKED ISSUE #4005: [Hold for payment Aug 23rd] InlineCode block is trimmed on Android
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performe
1. Open any conversation on E.cash on Mobile App.
2. Send following message.
```
This is a big message which includes `inline code block`. An inline code block can be `two lines long and we have to make sure that it is shown correctly`. 
```

## Expected Result:
The code block is trimmed and not visible correctly.

## Actual Result:
Describe what actually happened

Code block should be visible correctly.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
None.

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android :heavy_check_mark: 
 Desktop App
 Mobile Web

**Version Number:** Latest
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
code-issue

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ Fixes #4005

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [x] Android

#### Android

fix-code

### CODE REVIEW

**Comment by parasharrajat** [comment]
LOL. Closing it and opening a new one. Sorry for the ping.

**Comment by roryabraham** [comment]
😂 "@parasharrajat wants to merge 10000 commits"

**Comment by marcaaron** [comment]
that's one way to win the GitHub game 🙄

**Comment by iwiznia** [comment]
NO TEST NO QA CP TO PROD! :trollface:

**Pull request closed without merging**
