### PR TITLE
Update appstore profile

### PR DESCRIPTION
**Pull request by Jag96**
@marcaaron will you please review this? cc @AndrewGable @roryabraham 

### Details
This PR updates the appstore provisioning profile using the directions listed [here](https://docs.github.com/en/actions/reference/encrypted-secrets#limits-for-secrets).

### Fixed Issues
Fixes broken iOS deploy coming from [slack](https://expensify.slack.com/archives/C03V9A4TB/p1616689543188700)

### Tests
1. I downloaded the appstore profile from developer.apple.com and double-clicked it
2. Opened Xcode and confirmed that under `Signing`, there were no warnings about the profile such as 
```
error: Provisioning profile "chat_expensify_appstore" doesn't support the Associated Domains capability
```

### CODE REVIEW

**Review by AndrewGable — APPROVED** [review]

**Review by marcaaron — APPROVED** [review]
Thanks for helping with this !

**Comment by marcaaron** [comment]
Not sure if there is anything to test here, but LGTM.

**Review by sketchydroide — COMMENTED** [review]
LGTM to

**Comment by isagoico** [comment]
@Jag96 Hello! This PR looks like internal QA. If so, can you let me know when it's QA'd in staging so I can check it off the deploy list? Thanks in advance!

**Comment by Jag96** [comment]
This is good to check off!

**Pull request merged**
