### PR TITLE
Ensure only latest bank account shows default badge

### PR DESCRIPTION
**Pull request by Shahidullah-Muffakir**
### Details

Updated logic to ensure only the latest added bank account is marked as default, preventing two accounts from being shown as default without needing a page refresh.
### Fixed Issues

$ https://github.com/Expensify/App/issues/50829
PROPOSAL: https://github.com/Expensify/App/issues/50829#issuecomment-2415543267

### Tests

1. Log in to the account that has no bank accounts.
2. Navigate to Settings > Wallet and click on Add Bank Account > Personal Bank Account.
3. On the Plaid modal, search and select Wells Fargo bank, enter credentials (e.g., user_good / pass_good), and complete the process.
4. Verify that the added bank account is not marked as the default(because we are not showing default badge if there is only one bank account)
5. Repeat the process to add a second bank account by selecting Chase bank.
6. Verify that only the newly added bank account is marked as default, and the previous account does not show the default badge.
7. Refresh the page and confirm that the correct default account is still displayed.

- [x] Verify that no errors appear in the JS console

### Offline tests

This feature requires an active internet connection.
### QA Steps

1. Log in to the account that has no bank accounts.
2. Navigate to Settings > Wallet and click on Add Bank Account > Personal Bank Account.
3. On the Plaid modal, search and select Wells Fargo bank, enter credentials (e.g., user_good / pass_good), and complete the process.
4. Verify that the added bank account is not marked as the default(because we are not showing default badge if there is only one bank account)
5. Repeat the process to add a second bank account by selecting Chase bank.
6. Verify that only the newly added bank account is marked as default, and the previous account does not show the default badge.
7. Refresh the page and confirm that the correct default account is still displayed.
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/2c71d641-5245-4f70-aac4-d00dfbb9d331

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/1a17f34a-c45c-4ca6-b55f-8b33cca7514c

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/f7ac06bc-17e7-4612-aab5-6daf112c1ff8

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/700224f9-51a7-4aa1-9e5d-ea902b296cf1

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/9c1bc70d-2197-4ed2-a290-cbd583f1e583

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/034b8f0d-f802-4b9a-abcb-553ccd8101b8

</details>

### CODE REVIEW

**Comment by Shahidullah-Muffakir** [comment]
@thesahindia, I tested now, I could add the 2nd account.  
It seems we need to test it with different banks, one time CHASE bank and for the 2nd account with WELLS FARGO.
Thank you.

**Comment by Shahidullah-Muffakir** [comment]
> `created` should be the date the bank account was added into the DB... so it should reflect the order the accounts were added. If those accounts are the testing plaid accounts there might be some weirdness with the `created` dates since they're re-used regularly 🤔

Thanks for explaining! If the created date is the date the bank account was added to the database, then that should work fine for what we need. I also think that the issue might be because of the test accounts. I noticed that when I re-added the same test account, it showed the correct created date as today’s date and time. So, it seems like the old dates we’re seeing could be because these test accounts.

**Comment by Shahidullah-Muffakir** [comment]
I noticed something during testing:

1. I added a Chase Bank account (“Plaid Checking”).
2. Then, I added another account, WELLS FARGO (“Plaid Saving”).
3. I deleted the Chase Bank account from Step 1.
4. I re-added the Chase Bank account from Step 1.

When I re-added the account in Step 4, I saw that it kept the original created date from Step 1, rather than updating to the current date. It seems like we aren’t updating the created date if a user re-adds a deleted payment method.

@NikkiWines , do we update the created date for real payment methods in production when a user re-adds a deleted method, or is this just an issue with test accounts? If we can confirm this, I think we will be good to proceed with our PR.

@thesahindia  , based on this, we can test our approach by using a new user account. If we add two accounts with a new user, the most recently added should correctly show as the default.

Thank you.

**Comment by NikkiWines** [comment]
> @NikkiWines , do we update the created date for real payment methods in production when a user re-adds a deleted method, or is this just an issue with test accounts? If we can confirm this, I think we will be good to proceed with our PR.

Sorry for the delay, I can confirm that when re-adding a deleted account, the original `created` is used - it's not updated to reflect the most recent time the account was added.

**Comment by Shahidullah-Muffakir** [comment]
> > @NikkiWines , do we update the created date for real payment methods in production when a user re-adds a deleted method, or is this just an issue with test accounts? If we can confirm this, I think we will be good to proceed with our PR.
> 
> Sorry for the delay, I can confirm that when re-adding a deleted account, the original `created` is used - it's not updated to reflect the most recent time the account was added (for both test and non-test accounts)

Thanks for confirming! Considering this, our current approach won’t work as expected. We’ll need to find another solution, maybe we can store the ID of the latest payment method in Onyx and use that ID to determine which account shows the default badge.

**Comment by Shahidullah-Muffakir** [comment]
> @Shahidullah-Muffakir, any progress on the new solution?

@thesahindia, will push the changes in few hours.

**Comment by Shahidullah-Muffakir** [comment]
@thesahindia Changes are complete. Let me know if anything else is needed, Thank you.

**Review by thesahindia — APPROVED** [review]
Tests well!

**Review by NikkiWines — CHANGES_REQUESTED** [review]
Sorry to do this, since I know there's been a fair amount of back and forth on this issue already... But after doing some digging, I think we actually need to set the `default` badge according to the `bankAccountID` saved in `userWallet.walletLinkedAccountID`, as that's the value we reference on the backend to determine the default account. 

Additionally, some bankAccounts are not added via plaid, so relying on that value may b unreliable. 

Sorry!! Let me know if that doesn't make sense

**Comment by Shahidullah-Muffakir** [comment]
> Sorry to do this, since I know there's been a fair amount of back and forth on this issue already... But after doing some digging, I think we actually need to set the `default` badge according to the `bankAccountID` saved in `userWallet.walletLinkedAccountID`, as that's the value we reference on the backend to determine the default account.
> 
> Additionally, some bankAccounts are not added via plaid, so relying on that value may b unreliable.
> 
> Sorry!! Let me know if that doesn't make sense

No issue, I’ll make the update. Thanks for explaining! We’ll use `bankAccountID || fundID` since that’s what’s stored in walletLinkedAccountID here: https://github.com/Expensify/App/blob/3023d6016ef59d3fc8f0190f48597c41e95d3a55/src/libs/actions/PaymentMethods.ts#L110

**Comment by Shahidullah-Muffakir** [comment]
> Sorry to do this, since I know there's been a fair amount of back and forth on this issue already... But after doing some digging, I think we actually need to set the `default` badge according to the `bankAccountID` saved in `userWallet.walletLinkedAccountID`, as that's the value we reference on the backend to determine the default account.
> 
> Additionally, some bankAccounts are not added via plaid, so relying on that value may b unreliable.
> 
> Sorry!! Let me know if that doesn't make sense

@NikkiWines ,  Just to confirm, should the key be named `LATEST_ADDED_WALLET_LINKED_ACCOUNT_ID,` or do you prefer something else? Thanks!
 ```
 /** The ID of the latest added wallet linked account */
    LATEST_ADDED_WALLET_LINKED_ACCOUNT_ID: 'latestAddedWalletLinkedAccountID',
```

**Comment by NikkiWines** [comment]
I think you could just use `walletLinkedAccountID` which is what we use elsewhere in the product, but you shouldn't need a new onyx key for this. You should be able to get the value from the `USER_WALLET` onyx key.

**Comment by Shahidullah-Muffakir** [comment]
> I think you could just use `walletLinkedAccountID` which is what we use elsewhere in the product, but you shouldn't need a new onyx key for this. You should be able to get the value from the `USER_WALLET` onyx key.


Currently, when we add a new payment method with `addPersonalBankAccount`, the `userWallet.walletLinkedAccountID` is not updated. `walletLinkedAccountID` only gets updated in two cases: 
1. when a user manually sets a payment method as default by clicking **'Make default payment method,'** 
2. or when the `OpenPaymentsPage` API runs (only triggered when the Wallet page opens).
Screenshot 2024-11-13 at 5 19 41 AM




Given the current issue, relying on these alone won’t work.



So, considering this, we have a couple of options:
1. When we add a new payment method via `addPersonalBankAccount`, the backend could save `userWallet.walletLinkedAccountID `as the latest added account if isDefault is true. This would be similar to how `OpenPaymentsPage` returns `userWallet.walletLinkedAccountID` . Then, we could use this to show the default.
 we will still need to add the same changes, as I added in the last approach in the `shouldShowDefaultBadge` function.
2. Alternatively, a more straightforward approach would be to call the `OpenPaymentsPage` endpoint right after a user adds a new payment method. Since OpenPaymentsPage returns only one isDefault true.
We need to add `bankAccountList` in deps array of this useEffect:
https://github.com/Expensify/App/blob/7256ad6eef046be3345e0b260252f6ec47fc4203/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L267-L272

**Comment by Shahidullah-Muffakir** [comment]
> Additionally, some bankAccounts are not added via plaid, so relying on that value may b unreliable.
> 
When I click on 'Add Bank Account,' it directly opens the Plaid modal, and I couldn’t find any other way to add a bank account. Could you clarify how bank accounts might be added without Plaid. Thank you.

**Comment by NikkiWines** [comment]
> Currently, when we add a new payment method with addPersonalBankAccount, the userWallet.walletLinkedAccountID is not updated. walletLinkedAccountID only gets updated in two cases:

Oh, hmm. We do update it on the backend but the onyx key isn't appropriately updated currently. I can push up a change that will fix that. 

> When I click on 'Add Bank Account,' it directly opens the Plaid modal, and I couldn’t find any other way to add a bank account. Could you clarify how bank accounts might be added without Plaid. Thank you.

Users can add personal bank accouns without plaid via Expensify Classic. 

image

**Comment by Shahidullah-Muffakir** [comment]
> Oh, hmm. We do update it on the backend but the onyx key isn't appropriately updated currently. I can push up a change that will fix that.

Okay, that sounds great, this change should work then. Thanks

> Users can add personal bank accouns without plaid via Expensify Classic.
> 
 Got it, thanks for clarifying.

**Comment by NikkiWines** [comment]
PR is up to resolve this, I'll update here when it's live but for now you can proceed as though we'll use the `walletLinkedAccountID` from the USER_WALLET key to determine the default

**Comment by NikkiWines** [comment]
Backend PR has been merged, should be on production by thursday

**Comment by Shahidullah-Muffakir** [comment]
> Backend PR has been merged, should be on production by thursday

Thank you! I’ll test it with the backend changes on Thursday and push the updates afterward.

**Comment by Shahidullah-Muffakir** [comment]
I added changes to use `userWallet.walletLinkedAccountID`. 
Not sure if the failing test is related, as it seems unrelated to the changes made.

**Comment by NikkiWines** [comment]
Hmm yeah the failing test does seem unrelated, try merging main again @Shahidullah-Muffakir?

**Comment by Shahidullah-Muffakir** [comment]
> Hmm yeah the failing test does seem unrelated, try merging main again @Shahidullah-Muffakir?

@NikkiWines, Thank you, Merging main fixed the issue.

**Comment by NikkiWines** [comment]
Backend changes are live! You should be getting the updated `walletLinkedAccountID` now

**Comment by Shahidullah-Muffakir** [comment]
Yes, I tested it with the new backend changes, and it’s working well. Thanks.

**Review by NikkiWines — APPROVED** [review]
Looks great, thanks for the perserverence here 🙇

**Pull request merged**
