### PR TITLE
Fix typos in automerge and finishReleaseCycle workflows

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Fixes typos in workflow that have caused our automerge PRs to fail, for example: https://github.com/Expensify/Expensify.cash/runs/2143260738?check_suite_focus=true

### CODE REVIEW

**Review by AndrewGable — APPROVED** [review]

**Review by AndrewGable — APPROVED** [review]

**Comment by botify** [comment]
@AndrewGable looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Comment by AndrewGable** [comment]
Merging to fix deploys!

**Comment by roryabraham** [comment]
- First preDeploy: https://github.com/Expensify/Expensify.cash/actions/runs/665933255
- PR against master: https://github.com/Expensify/Expensify.cash/pull/1867
- Automerge master: https://github.com/Expensify/Expensify.cash/actions/runs/665935855
- Second preDeploy: https://github.com/Expensify/Expensify.cash/actions/runs/665938192
- PR against staging: Not created b/c one was already open

**Comment by roryabraham** [comment]
There were other problems, but fortunately this PR served it's purpose in repairing the automerge workflow

**Pull request merged**
