### PR TITLE
[CP Staging] Revert "Remove `withNavigationFallback.js` HOC"

### PR DESCRIPTION
**Pull request by tienifr**
### Details

Restore the `withNavigationFallback` to avoid app crashing. Straight revert of PR https://github.com/Expensify/App/pull/29449.

### Fixed Issues

$ https://github.com/Expensify/App/issues/29839
PROPOSAL: https://github.com/Expensify/App/issues/29839#issuecomment-1767530246

### Tests

1. Login in ND
2. Go to any chat
3. Send any message
4. Hold message >> Delete message
5. Verify that message is deleted and user can continue use app

- [x] Verify that no errors appear in the JS console

### Offline tests

NA

### QA Steps

1. Login in ND
2. Go to any chat
3. Send any message
4. Hold message >> Delete message
5. Verify that message is deleted and user can continue use app

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/113963320/9babdc06-e94e-4752-8c6b-04777545b7cb

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/113963320/9f8d3bc3-19c6-4fb9-a3ec-02c58665ff1b

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/113963320/1dc3a188-fc48-47c5-88ad-cb634d94323f

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/113963320/c39cd12e-370a-4dbc-82f8-1ba394004760

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/113963320/6c056dca-5566-4ab5-9c8d-c5e4e079b42c

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/113963320/cb93bed0-1c28-4839-9bca-2824c1008325

</details>

### CODE REVIEW

**Review by Julesssss — APPROVED** [review]

**Review by Julesssss — COMMENTED** [review]
Hmm, this is not quite a straight revert due to [these](https://github.com/Expensify/App/pull/29449/files#diff-3401552ecd81836fbf3b40788fa80901ec80b064b37a99c75ead8cf1e38384deL4-R4) and [these](https://github.com/Expensify/App/pull/29449/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L119-R119) changes. Are they necessary?

**Comment by Julesssss** [comment]
Alright, thanks let me find someone for the C+ review 👍

**Review by rushatgabhane — COMMENTED** [review]
Revert looks clean to me

**Review by rushatgabhane — CHANGES_REQUESTED** [review]
@tienifr i can't delete the message on web

1. tap and hold
2. delete


```
Uncaught TypeError: Cannot read properties of undefined (reading '3708590258034326363')
    at eval (ReportActionsUtils.js:387:85)
    at Array.forEach (<anonymous>)
    at Module.getLastVisibleAction (ReportActionsUtils.js:386:1)
    at Module.getLastVisibleMessage (ReportUtils.js:1211:27)
    at Module.deleteReportComment (Report.js:990:33)
    at Object.eval [as onConfirm] (PopoverReportActionContextMenu.js:249:7)
    at Object.onConfirm [as onPress] (ConfirmModal.js:85:1)
```
https://github.com/Expensify/App/assets/29673073/18cbbd27-06b4-4e7f-8159-8b2f2fd5841e

**Comment by youssef-lr** [comment]
@rushatgabhane since it's late for you @situchan will be completing the checklist

**Comment by situchan** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



https://github.com/Expensify/App/assets/108292595/d546be7f-b9e4-482a-bcd6-594b53189926


</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/108292595/b4b89856-d12e-4f3c-ba26-2cfdf2d6260f



</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/108292595/4203b2b3-476f-45a1-bb47-02dda33ec562



</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/assets/108292595/b2826058-16c7-4321-b0d7-59c0764abde7



</details>

<details>
<summary>iOS</summary>



https://github.com/Expensify/App/assets/108292595/32418b8e-3540-4e74-a68e-118287b59b43


</details>

<details>
<summary>Android</summary>


https://github.com/Expensify/App/assets/108292595/5ddf6772-adaa-4b80-951b-802768939232



</details>

**Review by situchan — APPROVED** [review]

**Comment by youssef-lr** [comment]
@tienifr what do you think about this bug @situchan encountered [here](https://expensify.slack.com/archives/C049HHMV9SM/p1697654861618629?thread_ts=1697653662.720699&cid=C049HHMV9SM)? also cc @kacper-mikolajczak I see you encountered this bug before [here](https://github.com/Expensify/App/issues/16161#issuecomment-1747364108)

**Comment by situchan** [comment]
> It did not throw any error or crashed the app but **the comment was not deleted until I switched to another report and came back**

This seems like another deploy blocker with different root cause

**Comment by youssef-lr** [comment]
>Yes, I was able to reproduce the resizing issue. Having looked at the errors, I thought it's not related to this PR.

Yeah my guess as well, I think we have another PR causing this issue. So I'm gonna go ahead and merge this one, thanks everyone!

**Comment by youssef-lr** [comment]
sounds good @tienifr, also, this [PR](https://github.com/Expensify/App/pull/29052) just got deployed yesterday, @kacper-mikolajczak ran into this [issue](https://github.com/Expensify/App/pull/29844#issuecomment-1769163247) while working on it, could it be what's causing that bug on staging?

**Comment by youssef-lr** [comment]
Yeah I know. I think we also need to figure out the resizing issue.

**Comment by situchan** [comment]
> Hmm so strange. I can't reproduce it (i.e. the delete by popover menu issue) anymore on the latest `main` after we merged this. Thanks for your patience @youssef-lr !

I suspect #29784 (merged 15 min ago) might have fixed this as it's the only one related to popover merged within 1 hr.
I was able to reproduce 1 hr ago on this branch merged with latest main locally.

**Comment by situchan** [comment]
@rushatgabhane I can delete message successfully on staging (both from context menu and from mini context menu)


https://github.com/Expensify/App/assets/108292595/be59743d-b893-433c-a5ac-a8aa07325a73


https://github.com/Expensify/App/assets/108292595/ef7059b3-8968-4ae4-be66-4242ddd093fa

**Comment by youssef-lr** [comment]
@situchan @tienifr the resizing error has made it to production, can we confirm if this [PR](https://github.com/Expensify/App/pull/29052) is the culprit? just a guess as Kacper encountered this error while working on the PR

**Comment by youssef-lr** [comment]
OK I can confirm that reverting that PR fixes the issue for me locally

**Comment by kacper-mikolajczak** [comment]
Looking into it now 🔧

**Comment by youssef-lr** [comment]
Thanks @kacper-mikolajczak!

**Pull request merged**
