### PR TITLE
[CP-stag] Get CompanyAddress field to autofill and show errors

### PR DESCRIPTION
**Pull request by Luke9389**
## Details

This PR fixes several things about the Address Picker. 

This component uses a 3rd party package to populate the dropdown list for addresses. After _quite a lot_ of wrestling we decided to just make `AddressSearch` a functional component because that seems to fix our problems immediately. 

## Fixed Issues

$ https://github.com/Expensify/App/issues/5794
$ https://github.com/Expensify/Expensify/issues/181023

### Error reporting

1) Sign in to New Dot with a new account
2) Create a new workspace
3) Connect a new bank account
4) Routing number: 123123123 
    Account Number: 1111222233331111
5) Hit enter. When you're on the Company Information page, immediately hit enter. 
6) Verify that you see the error under the Company Address field and that the border of that field turns red.

### Autofill

1) Sign in to New Dot (new account is fine)
2) Create a new workspace
3) Connect a new bank account
4) Routing number: 123123123
     Account Number: 1111222233331111
5) Input valid information on all fields in the Company Information step (doesn't need to be real info)
6) 
    a) _Variant 1:_ Refresh the page
    b) _Variant 2:_ Hit Submit. When you're on Step 3 (Personal Information) click the back arrow to go back to Step 2 (Company Informaion)
7) Notice that all the fields are auto-filled, including the Company Address. 

## Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [x] iOS
- [x] Android

#### iOS

Screen Shot 2021-10-13 at 3 12 50 PM
Screen Shot 2021-10-13 at 3 14 03 PM

#### Android

Screen Shot 2021-10-13 at 3 27 53 PM

### CODE REVIEW

**Comment by Luke9389** [comment]
Putting this on WIP until I've tested on all platforms

**Comment by trjExpensify** [comment]
Can we add the `CP Staging` label to this, so we can get it into the launch.

**Review by robertjchen — APPROVED** [review]
Nice! 👍

**Comment by kevinksullivan** [comment]
@isagoico that is a typo, company address should be auto-filled. Can we check this one off?

**Comment by Luke9389** [comment]
Yup my bad. That was copy pasta from the issue I made for this 😬

**Pull request merged**
