### PR TITLE
[HOLD] [Travel] Create Trip Details for newDot

### PR DESCRIPTION
**Pull request by cdOut**
HELD on https://github.com/Expensify/Expensify/issues/416688

### Details

Add a new Trip Details page for displaying information about a trip room and itinerary.

### Fixed Issues

$ https://github.com/Expensify/App/issues/37823
PROPOSAL:

### Tests

1. Go to oldDot - staging.expensify.com
2. Go to travel
3. Book a flight, rail, car and hotel.
4. Go to newDot and go to the trip room.
5. Press on the trip summary fields and confirm that you see the correct Trip Details page (for now this is not using the figma version due to there not being backends that would send the proper data, for the current design please refer to the screenshots below).

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

### Hotel:

HOTEL

### Flight:

FLIGHT

</details>

### CODE REVIEW

**Comment by cdOut** [comment]
I'll be fixing this today, I'll cc you after it's done.

**Comment by shawnborton** [comment]
And please let @Expensify/design know when this is ready for more testing too, thanks!

**Comment by cdOut** [comment]
@shubham1206agra due to the lack of backends and the deadline getting very close we've decided to make a fallback-simplified version, as per [this conversation](https://swmansion.slack.com/archives/C05S5EV2JTX/p1721062807563259).

PR ready to be checked, merged with latest main.

**Comment by cdOut** [comment]
Yes, I'll supply them here in a moment.

**Comment by cdOut** [comment]
@shubham1206agra I've added screenshots for the details page for hotels and flight.

**Comment by shawnborton** [comment]
cc @Expensify/design for any feedback too... some of this stuff feels a little "new" compared to the rest of the design system, as we're balancing the styles we used in the preview card vs having styles that appear in a read-only fashion, almost like a read-only push-row. 

Is there any way to test this out myself too? How can I generate these trips locally?

**Comment by dannymcclain** [comment]
Hmm yeah I see what you mean. I guess I'm kind of wondering why we don't just follow more of our established patterns?

For example:
- Why does the header use NewKansas instead of our regular "Page Header" text style?
- Why not use styles that are more exactly like our read-only push rows for the details? (Looks like the text in these is bold?)

Not sure there is anything terribly wrong with what I'm seeing in the screenshots, but some of the styles do feel like a bit of a departure (without any meaningful reason that I can see).

**Comment by cdOut** [comment]
I agree with the header, it's clearly incorrect and I'll change its styling to fit our other designs. However when it comes to the read-only details, this is exactly how it was designed in [figma](https://www.figma.com/design/rOyUSHbLLyp64emz6WeoPW/Travel?node-id=308-32633&t=ExHsBzXa5QVN1daY-4).

image

**Comment by shawnborton** [comment]
> However when it comes to the read-only details, this is exactly how it was designed in [figma](https://www.figma.com/design/rOyUSHbLLyp64emz6WeoPW/Travel?node-id=308-32633&t=ExHsBzXa5QVN1daY-4).

Totally, we're just discussing that maybe what we designed isn't the best solution for the sake of consistency. Let me whip up some alternatives quickly.

**Comment by dannymcclain** [comment]
>Totally, we're just discussing that maybe what we designed isn't the best solution for the sake of consistency.

💯. Sorry if my feedback came across as something _wrong_ with the PR—I was more so just calling those things out to make sure we consider our other design patterns!

**Comment by shawnborton** [comment]
@cdOut do you have any examples of how we handle flights with multiple legs?

**Comment by cdOut** [comment]
No no, that one's on me, I must've also came off across wrong. Please let me know once you guys have came up with a different design so I can implement it!

In the meantime I've reworked the code since it forced a different styling for the header whilst using an icon for it, the styles for the text there look exactly as in the designs.

@shawnborton I do not have any examples and I'm not sure if we've considered that one, I was basing the changes entirely on the figma files. @shubham1206agra Could you generate a flight with multiple legs so we could see what data we get for it and how it looks in the `TripDetailsView`?

**Comment by shawnborton** [comment]
@cdOut I'm working on suggesting some design updates to this, thanks for your patience! In the meantime, do you have examples of what we would show for a hotel, rental car, and train?

**Comment by cdOut** [comment]
@shawnborton I don't have the access to the more detailed info that we'll receive here from the backend, I'd have to ask @stitesExpensify what kinda info we'd be sending through here for hotels, cars and train rides.

I only have access to the very basic info we're currently getting from the backend, let me know if you still want to see those or should we supply the more detailed ones.

**Comment by shawnborton** [comment]
Started a conversation [here](https://expensify.slack.com/archives/C05S5EV2JTX/p1721737498827189)

**Comment by cdOut** [comment]
@shubham1206agra not yet, Ted had sent Shawn all the possible values we can send over from the backend and he's still working on the final mocks for this page, after which we'll also have to wait for the backend to implement sending those selected values through to `Reservation`.

After I get the final design mocks from Shawn I'll let you know and add those here for you to check while we wait for the backend to close it up.

**Comment by shawnborton** [comment]
@twisterdotcom any update on your end for this one? Would love to have "final" mocks to share so we can get this one over the finish line. Thanks!

**Comment by twisterdotcom** [comment]
I started trying to figure this out for say `Flight`. In [our test data](https://github.com/Expensify/Auth/blob/main/test/test/data/spotnana_flight_pnr.json), (also [here](https://github.com/user-attachments/files/16516571/spotnana_flight_pnr.json)) we have a whole PNR. Within that PNR, we actually have 3 legs:

DEN > YVR on 2024-04-19
YVR > SIN on 2024-04-20
SIN > SFO on 2024-04-30

I'm not actually too sure how we'll be splitting these up now we're trying to split up individually charged tickets @stitesExpensify? But I've done the data just for DEN > YVR in Figma here: https://www.figma.com/design/rOyUSHbLLyp64emz6WeoPW/Travel?node-id=1043-15037&t=31fIWT97dRBsu4yZ-0

Is this the kind of thing you need anyway?
image

I can do this for the rest of them.

**Comment by shawnborton** [comment]
Oh dang, that is super helpful and doing that for all of them would be very appreciated. 

I was thinking of the step before that though, where I just want your confirmation on what kind of information we should show on these screens first, and then we can map it all out to the exact data names.

**Comment by twisterdotcom** [comment]
Ah nice, okay, I can do a few tables then to start and you maybe figure out what a better design might be for each of these. As you see, I added another separator in the flight details to fit the _duration - plane type - flight class_ and maybe that's not the best way to display it.

One Q though reviewing the flight data which is the hardest to consider I think, but perhaps will also be relevant to Rail eventually given it too can have "legs", how are we determining what to show here?
image

I think we should be splitting it into "legs" which the payload has (this one has two, one for DEN > SIN (via YVR) and one for SIN > DEN (via SFO)), in which case, this should show `airPnr.legs[0].flights[0].origin and airPnr.legs[0].flights[last].destination` (however we calculate "last"). In which case too, we will need a way of showing layovers and likely layover time, so here's ALL the useful information but, it's a lot even for a flight with just one layover to consider fitting into a single screen.

Required:

|JSON Path|Description|Comment
|---------|-----------|-----------|
|`airPnr.legs[0].flights[0].origin`|Origin Airport Code (`DEN`)|
|`additionalMetadata.airportInfo[2].cityName`|Origin City Name (`Denver`)|
|`airPnr.legs[0].flights[0].destination`|Layover Airport Code (`YVR`)|
|`airPnr.legs[0].flights[0].arrivalDateTime.iso8601` to `airPnr.legs[0].flights[1].departureDateTime.iso8601`|Layover Time (`9h 56m`)|
|`airPnr.legs[0].flights[airPnr.legs[0].flights.length - 1].destination`|Destination Airport Code (`SIN`)|
|`additionalMetadata.airportInfo[1].cityName`|Destination City Name (`Singapore`)|
|`travelers[0].user.name.family1` + `family2`|Passenger Name (`Brandon Stites`)|
|`travelers[0].user.email`|Passenger Email (`spotnanauser@spotnanauser.com`)|
|`airPnr.legs[0].flights[0].operating.airlineCode` + `num`|Flight 1 Number (`UA2432`)|
|`airPnr.legs[0].flights[0].cabin`|Flight 1 Cabin Class (`Economy`)|
|`airPnr.legs[0].flights[0].departureDateTime.iso8601`|Flight 1 Departure Date and Time (`Apr 19, 12:03 PM`)|
|`airPnr.legs[0].flights[0].departureGate.terminal`|Flight 1 Departure Terminal (`Terminal B`)|
|`airPnr.legs[0].flights[0].vendorConfirmationNumber`|Flight 1 Record Locator (`ADJXCZ`)|
|`airPnr.travelerInfos[0].booking.seats[0].number`|Flight 1 Seat Number (`7F`)|
|`airPnr.legs[0].flights[0].duration.iso8601`|Flight 1 Duration (`PT3H6M`)|
|`airPnr.legs[0].flights[1].cabin`|Flight 2 Cabin Class (`Business`)|
|`airPnr.legs[0].flights[1].arrivalDateTime.iso8601`|Flight 2 Arrival Date and Time (`Apr 21, 7:10 AM`)|
|`additionalMetadata.airportInfo[1].airportName`|Flight 2 Arrival Airport Name (`Singapore Changi Airport`)|
|`airPnr.legs[0].flights[1].arrivalGate.terminal`|Flight 2 Arrival Terminal (`Terminal 2`)|
|`airPnr.legs[0].flights[1].vendorConfirmationNumber`|Flight 2 Record Locator (`4YGEMD`)|
|`airPnr.travelerInfos[0].booking.seats[1].number`|Flight 2 Seat Number (`3G`)|
|`airPnr.legs[0].flights[1].duration.iso8601`|Flight 2 Duration (`PT16H5M`)|


Optional if design likes it:

|JSON Path|Description|Comment
|---------|-----------|-----------|
|`additionalMetadata.airportInfo[0].cityName`|Layover City Name (`Vancouver`)| We really can get away with just showing `YVR` and the layover time I think |
|`airPnr.legs[0].flights[0].equipment.name`|Flight 1 Aircraft Type (`Airbus A319`)|
|`airPnr.legs[0].flights[0].arrivalDateTime.iso8601`|Flight 1 Arrival Date and Time (`Apr 19, 2:09 PM`)|
|`additionalMetadata.airportInfo[0].airportName`|Flight 1 Arrival Airport Name (`Vancouver International Airport`)|
|`airPnr.legs[0].flights[0].arrivalGate.terminal`|Flight 1 Arrival Terminal (`Main Terminal`)| Perhaps these are useful if you need to know if you're changing Terminal? |
|`airPnr.legs[0].flights[1].departureGate.terminal`|Flight 2 Departure Terminal (`Main Terminal`)|
|`airPnr.legs[0].flights[0].co2EmissionDetail.emissionValue`|Flight 1 Carbon Emission (`0.26708 tonnes`)| Carbon stuff people seem to vibe off, so could be a nice design flare? |
|`airPnr.legs[0].flights[1].operating.airlineCode` + `num`|Flight 2 Number (`AC19`)|
|`airPnr.legs[0].flights[1].equipment.name`|Flight 2 Aircraft Type (`Boeing 787-9`)|
|`airPnr.legs[0].flights[1].departureDateTime.iso8601`|Flight 2 Departure Date and Time (`Apr 20, 12:05 AM`)| Again, maybe we don't need this if we just show layover time? |
|`airPnr.legs[0].flights[1].co2EmissionDetail.emissionValue`|Flight 2 Carbon Emission (`1.4545 tonnes`)|
|`airPnr.legs[0].fareOffers[0].baggagePolicy.checkedIn[0].description`|Baggage Policy (Checked Bags: `2 checked bags, 70 lbs each`)|
|`airPnr.legs[0].fareOffers[0].baggagePolicy.carryOn[0].description`|Baggage Policy (Carry-On: `1 carry-on bag`)|

**Comment by shawnborton** [comment]
> One Q though reviewing the flight data which is the hardest to consider I think, but perhaps will also be relevant to Rail eventually given it too can have "legs", how are we determining what to show here?

I had previously asked about this and my understanding was that we'd show the separate legs as part of the summary in the trip room, so that when you click into each one of them, you only need the specific details for that leg. Let me know if that makes sense and if that's your understanding as well as for how we should display/handle this.

**Comment by twisterdotcom** [comment]
>my understanding was that we'd show the separate legs as part of the summary in the trip room, so that when you click into each one of them, you only need the specific details for that leg

This sounds good to me, no need for us to say "non-stop" anywhere, we can just list it all. Do you think it's worth ever highlighting what the layover time is, given we'll just always show them as separate rows?

Also, should we ever try to differentiate the _journeys_. Let's say you don't book a hotel as a separator, the only differentiator would be the dates, which I suppose is fine?

What are your thoughts otherwise on including the other things: Aircraft Type, Carbon Emission, Checked Bags, Carry-On

**Comment by shawnborton** [comment]
> Do you think it's worth ever highlighting what the layover time is, given we'll just always show them as separate rows?

That's a great point, I wonder if we should reference the other legs within the detailed view so it's more clear that the flights are connected? 

> Also, should we ever try to differentiate the journeys. Let's say you don't book a hotel as a separator, the only differentiator would be the dates, which I suppose is fine?

I'm not quite following, can you restate that one? 

> What are your thoughts otherwise on including the other things: Aircraft Type, Carbon Emission, Checked Bags, Carry-On

Super down with that.

**Comment by twisterdotcom** [comment]
>I'm not quite following, can you restate that one?

I'm saying here, in the data we have for the legs, they are separated in the payload into:

Journey 1:
DEN > YVR
YVR > SIN

Journey 2:
SIN > SFO
SFO > DEN

But I'm saying, if there's no hotel in between, we would just see:

DEN > YVR
YVR > SIN
SIN > SFO
SFO > DEN

And if all we have are small dates written in grey, it might not be clear what the journeys are and the legs within those journeys without a separator. Kind of related to your thought that:

>if we should reference the other legs within the detailed view so it's more clear that the flights are connected?

I wonder if we could have something at the bottom of the view that's something like:

> 🏃 Only a 1h 3m layover until your [next flight to SIN](linkToOpenNextFlight). (Remember to change terminals!)

OR

> 🚕 You've arrived! Why not get an [Uber](https://help.expensify.com/articles/expensify-classic/connections/Uber) to your hotel.

Either than, or we just show very simple informative language:

>1h 3m layover until UA1234 to SIN

OR

>Singapore is your final destination for this leg

**Comment by shawnborton** [comment]
That all makes sense, but just to clarify, are you saying that within the context of the trip room itself, or are you saying we should show all of that on the details view? 

Also, do you have any good screenshots of what Spotnana shows for all of these scenarios? I wonder if we can use that as inspiration as well.

**Comment by twisterdotcom** [comment]
I actually think what we have in the trip room header is fine by itself. I think let's just focus on the RHP for the leg details and see what we can get in there and make that look like.

**Comment by shawnborton** [comment]
Okay looks like we landed here:
CleanShot 2024-08-14 at 09 07 07@2x

Where we add the layover information at the top of the details view if the flight had a layover before it, and we're using some HRs to better separate some of the sections within the page as well.

**Comment by cdOut** [comment]
cc: @twisterdotcom @stitesExpensify

Now that we've settled on a design, could someone start working on sending all the additional info required for those pages through to the frontend side?

Please keep me updated on the progress. In the meantime, I'll incorporate any changes made since the previous designs using mock data. Thanks!

**Comment by shawnborton** [comment]
What's the latest on this one?

**Comment by cdOut** [comment]
> What's the latest on this one?

As per the comment left by me above, I'm still waiting on the data from backend - without it I cannot push this PR further. I'll bump on the latest thread about this one on slack and hopefully we'll get it moving.

**Comment by shawnborton** [comment]
Looks like the linked issue was closed/merged, does that mean we should pick this one back up?

**Comment by stitesExpensify** [comment]
We are currently focusing fully on OldDot travel, so this is still on hold for now

**Comment by mountiny** [comment]
This will be worked on by SWM in a new PR once this is a priority again

**Pull request closed without merging**
