### PR TITLE
Order by most recent along with report icons

### PR DESCRIPTION
**Pull request by chiragsalian**
~HOLD for Web-E [PR](https://github.com/Expensify/Web-Expensify/pull/29599) to go live.~
~HOLD for Web-E [PR](https://github.com/Expensify/Web-Expensify/pull/29707) to go live~
HOLD for Web-E [PR](https://github.com/Expensify/Web-Expensify/pull/29768) to go live.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/145238

### Tests
1. Pull in this web-E [PR](https://github.com/Expensify/Web-Expensify/pull/29599).
1. Open expensify chat. Click through a few of your reports. Remember the order of reports you clicked through if possible.
image
3. Click on the search bar. Confirm you see your reports sorted in the same order.
image
4. Confirm 1:1 DMs show up with Add button and group DMs don't have add button.
1. Click on a name and confirm that report opens up.
1. Click search again and type out a name. This is not sorted by last visited but we confirm that nothing is broken here.
1. Select a name or add to group chat and confirm nothing is broken.
1. Confirm in the LHN, recently visited chats or while chat searching that any user that has an icon shows their icons.
image

### Screenshots
Pinned chats (the only difference is that icons now show up here as well)
image

Pinned chats mobile
image

Empty chat search showing recently visited chats - web
image

Empty chat search showing recently visited chats - mobile
image

Searching for a person - web
image

Searching for a person - mobile
image

### CODE REVIEW

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]
Lots of questions 😅

**Review by marcaaron — COMMENTED** [review]
Wow! Looking real good! 

@chiragsalian, sorry I've been out for a bit and I am having laptop issues I won't be able to test this for a bit. My laptop died completely and I'm still recovering / waiting for a replacement to arrive.

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]
LGTM. Left some NABs and thoughts.

While testing I found a few issues:

- Deleting last text character in search box closes the switcher and causes the input to lose focus
- Default avatars are not being used for search results despite existing.
Screen Shot 2020-12-08 at 9 35 28 AM

- Some chat links are linking to `r/undefined` (does not affect ability to create chat) and weirdly these ones DO have the default avatars

**Review by tgolen — CHANGES_REQUESTED** [review]
OK, I know these are some pretty verbose comments, but I wanted to be sure I was providing the full context around my suggestions.

**Review by marcaaron — DISMISSED** [review]
LGTM and tests well. Just left one minor comment, but I don't think it's a blocker

**Review by tgolen — DISMISSED** [review]
Cool, this looks good. We worked through a bug with some default avatars not showing. I tested this on web and iOS and it works well. @marcaaron all yours.

**Review by marcaaron — APPROVED** [review]

**Pull request merged**
