### PR TITLE
[No QA] Deploy help site to GitHub Pages

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Deploys the Expensify Help site to GitHub Pages

_Note:_ Links, styles, and scripts on the site will not work until we [configure a custom domain](https://github.com/Expensify/Expensify/issues/216752). More details in [this comment](https://github.com/Expensify/Expensify/issues/216746#issuecomment-1173132144).

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/216746

### Tests
1. Merge this PR
1. The site should deploy on GitHub Pages.
1. _Note:_ [action-gh-pages warns](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token) that the first deployment with the `github.token` may fail. I didn't observe that in the test repo, but it may happen.

### CODE REVIEW

**Comment by roryabraham** [comment]
I branched off of marco-addNewHelpSite to create this PR. Once https://github.com/Expensify/App/pull/9519 is merged and I merge main into this branch, the diff and number of commits will look a lot more reasonable.

**Comment by roryabraham** [comment]
This is ready for review but I'd prefer to wait until I'm not OOO to merge/live-test

**Review by marcochavezf — APPROVED** [review]
Awesome, big fan of using dart-sass, and thanks for addressing all these changes that will enable us to use it for the help site @roryabraham!

**Comment by roryabraham** [comment]
Let's test this out!

**Comment by roryabraham** [comment]
This was passing tests.

**Comment by roryabraham** [comment]
One thing I'm noticing is that HelpDot PRs have the potential to trigger unnecessary NewDot PRs. It won't happen now because the checklist is locked, but it's something we should clean up in a follow-up

**Comment by roryabraham** [comment]
HelpDot deploy running here: https://github.com/Expensify/App/runs/7204996726?check_suite_focus=true

**Comment by roryabraham** [comment]
Weird, the community action didn't work with the ref we used in this PR: 

image

I had only previously tested it with a tag, which goes against our GitHub Actions security guidelines for this repo.

**Comment by roryabraham** [comment]
Another thing I'm noticing is that there's no slack alert if this workflow fails.

**Comment by roryabraham** [comment]
First follow-up: https://github.com/Expensify/App/pull/9721

**Comment by roryabraham** [comment]
Ruby cache worked so the second deploy was super-duper quick 🎉

**Comment by roryabraham** [comment]
Second follow-up: https://github.com/Expensify/App/pull/9722

**Pull request merged**
