### PR TITLE
Reduce imageHeight to windowHeight if greater

### PR DESCRIPTION
**Pull request by sobitneupane**
### Details

Reduce height of image to height of window if it is greater than window's height.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7012

### Tests

- Send a large image
- Open attachment to see if image height fits within the window

### QA Steps

- Send a large image
- Open attachment to see if image height fits within the window

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

#### Web

Screenshot from 2022-01-25 14-21-45

#### Mobile Web

Screenshot_20220125-142126_Chrome

#### Android

Screenshot_20220125-145141_New Expensify

### CODE REVIEW

**Comment by parasharrajat** [comment]
@sobitneupane Please add screenshots for other platforms.

**Comment by sobitneupane** [comment]
> @sobitneupane Please add screenshots for other platforms.

I have added for Web and mWeb. I don't have accessibility of macOS and IOS.

**Comment by parasharrajat** [comment]
Ok, I tested the changes. But now when we zoom the image it does not take the full width of the screen. 
image

**Comment by sobitneupane** [comment]
> Ok, I tested the changes. But now when we zoom the image it does not take the full width of the screen.

It is because we have used 2 as scale to zoomin for doubleClick. It can be zoomed further using pinch-to-zoom.

**Comment by deetergp** [comment]
Overall the PR looks good and I greatly appreciate the comments explaining the "why" of each bit of logic. Thanks! You've got some merge conflicts you need to resolve, but once that's done it will be good to go, IMO!

**Review by parasharrajat — DISMISSED** [review]
LGTM: 

cc: @deetergp 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Review by deetergp — APPROVED** [review]

**Pull request merged**
