### PR TITLE
Theme switching: Going Live! (Add preferences menu entry for ThemePage)

### PR DESCRIPTION
**Pull request by chrispader**
@grgia 

### Fixed Issues

$ https://github.com/Expensify/App/issues/21670
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests

- [x] Verify that no errors appear in the JS console

1. Go to settings -> Preferences
2. Make sure there's a menu entry "Theme"
3. Click on it
4. Make sure you're redirected to a new "Theme" page
5. Change theme and make sure the setting is changing the color theme accordingly

### Offline tests

Not needed.

### QA Steps

No QA

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos

See https://github.com/Expensify/App/pull/21666

<details>
<summary>Web</summary>

Screenshot 2023-07-04 at 13 17 23
Screenshot 2023-07-04 at 13 17 26

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screenshot_20230704_133156_Chrome

Screenshot_20230704_133234_Chrome

</details>

<details>
<summary>Mobile Web - Safari</summary>

Simulator Screen Shot - iPhone 14 Pro (16 2) - 2023-07-04 at 13 24 23
Simulator Screen Shot - iPhone 14 Pro (16 2) - 2023-07-04 at 13 24 25

</details>

<details>
<summary>Desktop</summary>

Screenshot 2023-07-04 at 13 19 38
Screenshot 2023-07-04 at 13 19 40

</details>

<details>
<summary>iOS</summary>

Simulator Screen Shot - iPhone 14 Pro (16 2) - 2023-07-05 at 12 28 41
Simulator Screen Shot - iPhone 14 Pro (16 2) - 2023-07-05 at 12 30 21

</details>

<details>
<summary>Android</summary>

Screenshot_20230704_140321_New Expensify
Screenshot_20230704_140326_New Expensify

</details>

### CODE REVIEW

**Comment by chrispader** [comment]
@thesahindia please ignore you're mention, @grgia is gonna review this

**Comment by grgia** [comment]
Adding Hold, since we will not be merging this until we go live

**Comment by grgia** [comment]
Commenting for Melvin, still on hold

**Comment by grgia** [comment]
@chrispader we'll need to merge , we'll need to merge main since there's been an update to the translate hook. I temporarily made the changes in this commit so design can QA but I'll remove it before we merge so we can QA all the settings in this PR. 
https://github.com/Expensify/App/pull/32512/commits/2230d21056914311b87e9a5b33800014d6d46f17



Also, what are your thoughts on the drawer animation here? It feels a little jagged with the rerendering, but Im not sure if there's much we can do with push to page here


https://github.com/Expensify/App/assets/38015950/68aa3307-facd-4379-baa5-76b7158b40bb

**Comment by chrispader** [comment]
> @chrispader we'll need to merge main since there's been an update to the translate hook.

done 👍

**Comment by chrispader** [comment]
> Also, what are your thoughts on the drawer animation here? It feels a little jagged with the rerendering, but Im not sure if there's much we can do with push to page here

I don't think there's much we can do here either. Probably due to the rendering of the lottie animation. i can take a look into this by time.

**Comment by grgia** [comment]
@chrispader yeah the jaggedness matches changing priority mode, so I think it's fine. Personally, I think the fix is actually not navigating back to preferences on button click for the settings that rerender large parts of the app

**Comment by grgia** [comment]
@chrispader for tests, here's some paths to get started:

**Anonymous User**
Here we are testing:
✅ **Sign in Page is Dark for all users**
✅ **Theme matches device settings for anonymous users**
- Ensure Sign In Page is Dark, Navigate to a report anonymously, ensure that theme matches OS
- Repeat this with OS set to Light, Dark, Auto

**Brand New User**
Here we are testing:
✅ **Theme is automatically set to System**
- Set OS theme to Dark
- Create a new account, ensure that the theme setting in preferences is set to System and is Dark Mode.
- Log out, set OS theme to Light
- Create a new account, ensure that the theme setting in preferences is set to System and is Light Mode.

**Logged in User**
Here we are testing:
✅ **Theme can be changed**
✅ **Theme is remembered after logging out and logging back in**
✅ **Theme preference is synced across devices*
- Go to preferences -> theme
- Set theme to Dark, ensure theme is changed to dark.
- Log out and log back in, ensure theme remains dark.
- Log into another device, ensure theme remains dark. 
- Repeat steps with Light setting.
- Repeat steps with System setting. Here you will ensure that theme matches device OS theme. Change device OS theme between Dark and Light and ensure that the theme changes to match.

**Comment by chrispader** [comment]
@grgia the current default theme is `dark`: https://github.com/Expensify/App/blob/b0268fab8826bb964ad4c8450c342c27e23d0d50/src/CONST.ts#L699C12-L699C12

Should we change this to `system`?

**Review by grgia — CHANGES_REQUESTED** [review]
looks like in places where we do `themes[CONST.THEME.DEFAULT];` system isnt working

**Comment by grgia** [comment]
retrying desktop ^

**Comment by grgia** [comment]
hmmm clicking on the button isnt working 

https://github.com/Expensify/App/assets/38015950/1c46557a-31af-433c-baba-f18af917b051

**Comment by grgia** [comment]
Rebuilding

**Comment by grgia** [comment]
PS I cancelled that build ^

**Comment by grgia** [comment]
@chrispader if you merge main it should fix lint

**Comment by grgia** [comment]
**QA**

## Brand New User
Here we are testing:
✅ Theme is automatically set to System

Set OS theme to Dark
Create a new account, and ensure that the theme setting in preferences is set to System and is Dark Mode.

https://github.com/Expensify/App/assets/38015950/57ab39b8-bfae-410b-ad63-b3a75d16d7b8




Log out, set OS theme to Light
Create a new account, and ensure that the theme setting in preferences is set to System and is Light Mode.

https://github.com/Expensify/App/assets/38015950/6aed1b8a-2037-4fa7-b3e5-563ada6cbbec

**Comment by grgia** [comment]
image

I get this warning on IOS when switching themes

**Comment by chrispader** [comment]
> I get this warning on IOS when switching themes 

not sure if this is related, doesn't seem so.

can check tmrw!

**Comment by grgia** [comment]
Looked into that kind of error and I don't think it's related either, looks like a react navigation bug

**Comment by grgia** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by grgia** [comment]
waiting on the test build for android bc my local android still will not build 🙃🤖

**Review by grgia — APPROVED** [review]
🕺 🎊 LGTM 🎊 🕺

**Pull request merged**
