### PR TITLE
Update README.md with more Xcode instructions

### PR DESCRIPTION
**Pull request by carlosmiceli**
### Details
Updated with instructions for Xcode that would have saved me a lot of time!

### CODE REVIEW

**Comment by carlosmiceli** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by carlosmiceli** [comment]
recheck

**Comment by carlosmiceli** [comment]
Hey @blimpich, GH suggested you as a reviewer so I figured I'd bring you in. I wanted to make a small improvement that would have helped me a lot to see in the Readme, but apparently the process here is different to get the PR approved. Did I do something wrong or should I do something different for this suggested change? Thanks in advance for your help!

**Review by blimpich — APPROVED** [review]

**Comment by blimpich** [comment]
Not an emergency, just a README change

**Comment by carlosmiceli** [comment]
@blimpich Perrrfect, thanks for the explanation too!

**Pull request merged**
