### PR TITLE
add growl for updating/removing avatar as well

### PR DESCRIPTION
**Pull request by aman-atg**
### Details

https://github.com/Expensify/App/issues/4417#issuecomment-893312415
### Fixed Issues

$ https://github.com/Expensify/App/issues/4417

### Tests || QA Steps

1. Login to newDot
2. Go to settings
3. Select Profile
4. Update or Remove your profile picture
5. Growl will appear

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS ( Can't select images on emulator due to https://github.com/react-native-image-picker/react-native-image-picker/issues/1541 )
- [x] Android

#### Web

https://user-images.githubusercontent.com/28243942/131554216-c6ba8ba0-dcf7-4c12-871e-da8a69fcf7df.mov

#### Mobile Web

https://user-images.githubusercontent.com/28243942/131554247-3640b087-65be-4374-9ffd-ecaec7fc3458.mov

#### Desktop

https://user-images.githubusercontent.com/28243942/131554284-0edc0fb6-f49d-4fa1-9285-3607f67e435b.mov

#### iOS

https://user-images.githubusercontent.com/28243942/131554312-a88f19ea-5913-48fd-884d-a0667d90dbb3.mov

#### Android

https://user-images.githubusercontent.com/28243942/131554334-3dcf3d2b-076e-47fa-b508-e7ba72b416fe.mov

### CODE REVIEW

**Comment by mallenexpensify** [comment]
@johnmlee101 is this waiting on your review?

**Comment by johnmlee101** [comment]
Sorry! This slipped through the cracks. On it now

**Review by johnmlee101 — APPROVED** [review]
LGTM!

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-16.  :confetti_ball:

**Pull request merged**
