### PR TITLE
Issue-6239

### PR DESCRIPTION
**Pull request by marktoman**
### Fixed Issues

$ https://github.com/Expensify/App/issues/6239

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by mountiny** [comment]
@marktoman Hi! thanks for doing this, I have just uploaded a PR for this. Sorry for not letting you know sooner. https://github.com/Expensify/App/pull/6240

**Comment by marktoman** [comment]
@mountiny I have fixed the only place where we touch `unreadActionCount`.

**Comment by mountiny** [comment]
@marktoman In general, it is contributors responsibility to fix regressions which stem from their PR, so I really appreciate you have gone ahead, but since the fix was quite straightforward I have submitted the PR. 

I will close this PR in favour of the other one.

**Comment by mountiny** [comment]
@marktoman ALso notice sometimes the package-lock.json goes wild. See the diff of this file 😅

**Comment by marktoman** [comment]
@mountiny OK, thank you. Ah, I see. :)

**Comment by marktoman** [comment]
@mountiny Out of interest, I have tested `Object.entries` and `_.values`. The first does not produce nulls, which is the behavior I was used to. You learn every day :)

**Comment by mountiny** [comment]
@marktoman Interesting. It is true I am not sure what is the reason we got `null` in there in a first place (just the first report) after signing out. Any ideas 🤔

**Comment by marktoman** [comment]
@mountiny
I can have multiple reports that are null (see below), but what is weird is that when I add a slightly expensive calculation (`JSON.stringify` or summing a number) I do not get any nulls over ~20 attempts. Otherwise, switching a contact, typing, deleting and signing out is pretty much guaranteed to have them. I think this suggests some kind of race condition.

```
{report_82679573: null, report_82407519: null, report_82275133: null, report_83141298: null, report_82679326: null, …}
report_82275133: null
report_82407519: null
report_82679294: null
report_82679326: null
report_82679573: null
report_82795751: {reportID: 82795751, reportName: 'Exp3', chatType: '', ownerEmail: '__fake__', policyID: '_FAKE_', …}
report_83141297: {reportID: 83141297, reportName: '#announce', chatType: 'policyAnnounce', ownerEmail: '__fake__', policyID: '4B93D85B5FFDAFC8', …}
report_83141298: null
```

**Comment by mountiny** [comment]
@marktoman Thanks for looking into this. Let's keep an eye on this one if we can see any problems stemming out of this.

**Comment by marktoman** [comment]
@mountiny Just one thing I have to get of my chest. If `Object.entries` is the standard, then the underscore behavior is nonstandard. As such, I think it should be mentioned in the guide, especially given there is no mention about it in the [underscore docs](https://underscorejs.org/#values).

**Comment by mountiny** [comment]
@marktoman I will have a look into that, hopefully next week! Thank you!

**Comment by marktoman** [comment]
@mountiny Thank you for noticing it was caused by my PR. I will certainly pay more attention to slack screenshots next time!

**Comment by mountiny** [comment]
@marktoman This happens all the time, don't worry about it, it is usually our job to find what caused the problem and then contributor should help with fixing it. But this time it was fast to fix so I just went ahead.

**Pull request closed without merging**
