### PR TITLE
Setup deep links for iOS / Android

### PR DESCRIPTION
**Pull request by marcaaron**
cc @AndrewGable @Jag96 

~~Not sure if we need to do anything else here I think the last step is to just add the capability here?~~ ✅  Thanks Andrew!

Screen Shot 2021-03-24 at 10 04 24 AM

### Details
Sets up deep links / universal links for the iOS app. Will do Android next.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/146908

### Tests
**Local Test**

**iOS**
1. Build and run the iOS app
2. Log in
3. In terminal run `xcrun simctl openurl booted expensify-cash://settings`
4. Verify the iOS app opens and you are brought to the settings page

**Android**
1. Build and run the Android app
2. Log in
3. In terminal run `npx uri-scheme open expensify-cash://settings --android`
4. Verify you are asked if you want to open the link in Expensify.cash and say yes
5. Verify the Settings page opens.

**Production Test**
1. Verify `https://expensify.cash/apple-app-site-association` leads to a JSON file
2. Tap a link to `https://expensify.cash/settings` and verify it opens in the mobile app

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Review by Jag96 — CHANGES_REQUESTED** [review]
iOS worked fine for me! On Android, however, I got no response on the emulator when running `npx uri-scheme open expensify-cash://settings --android`

I saw the following output in the terminal
```
npx: installed 1 in 1.055s
› Android: Attempting to open URI "expensify-cash://settings" in emulator
```

But no response in the Android app. I tried running the command while the app was backgrounded as well as open.

**Comment by marcaaron** [comment]
Thanks for catching that @Jag96/ Updated this with some more intent filter guys. Having one per combination of scheme + host seems to have fixed this issue.

**Review by Jag96 — APPROVED** [review]
That worked! LGTM

**Comment by roryabraham** [comment]
Whoops! This PR is causing iOS builds to fail https://github.com/Expensify/Expensify.cash/runs/2189376685?check_suite_focus=true

**Comment by isagoico** [comment]
@marcaaron Hello! This PR looks like internal QA. If so, can you let me know when it's QA'd in staging so I can check it off the deploy list? Thanks in advance!

**Comment by marcaaron** [comment]
This PR can be tested actually!

1. Install iOS and Android app betas
2. Log into the app
3. Email a link to https://staging.expensify.cash/settings
4. Accept that you want to open the link in the app
5. Get navigated to the settings screen

I just tested this on Android. iOS may need to wait for changes here -> https://github.com/Expensify/Expensify/issues/154510#issuecomment-807705014

**Comment by marcaaron** [comment]
Alright so quick heads up here..

This did not pass on the latest iOS TestFlight build. I also can't think of any reason why it wouldn't be working. But it doesn't seem to be causing any issues for the TestFlight build so probably not a blocker.

**Comment by isagoico** [comment]
I got the same behaviour as you in the iOS app, a mWeb page was opened instead of the App. Android app was a pass tho 🎉 Let me know if I should open a separate issue about the iOS behaviour.

**Comment by AndrewGable** [comment]
FYI - I don't think iOS has been deployed yet

**Comment by isagoico** [comment]
Should we check this off the list if Android was a pass? We could check iOS once it's out.

**Comment by AndrewGable** [comment]
Yes, let's check it off ✅

**Pull request merged**
