### PR TITLE
Update the password label in Plaid VBA flow

### PR DESCRIPTION
**Pull request by mountiny**
### Details

See the issue for more context.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/173525
$ https://github.com/Expensify/App/issues/4548

### Tests

How to test it locally: [SO here](https://stackoverflow.com/c/expensify/questions/342).

Follow the `Log Into Your Bank` flow in `Add Bank Account`, login in through Plaid, select `Plaid Saving` and make sure the password field says `Enter Expensify password` if English is selected as your language.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots

image

### CODE REVIEW

**Comment by shawnborton** [comment]
Chiming in here quickly - it looks like the select menu is missing a small label above the value:
image

**Comment by mountiny** [comment]
@shawnborton You are right! I have raised the issue in [here](https://expensify.slack.com/archives/C020EPP9B9A/p1628618439036500?thread_ts=1628615061.030700&channel=C020EPP9B9A&message_ts=1628618439.036500), but that was a wrong place probably.

The thing is that there was no label originally. What label would you propose for this select, or should I ask in #product?

**Comment by shawnborton** [comment]
I think it could simply say "Account" or "Choose account" - looks like @roryabraham also [reported this](https://expensify.slack.com/archives/C01GTK53T8Q/p1628645830194700).

**Comment by mountiny** [comment]
@Jag96 For context for anyone else coming across this in future, I have asked in Slack [here](https://expensify.slack.com/archives/C020EPP9B9A/p1628640174079600) and we decided to use `Account` as a label. It can be easily changed in future if it would be a problem.

image

I have updated the copy and added the label, should be ready for a review!

**Review by Jag96 — APPROVED** [review]
LGTM 👍

**Pull request merged**
