### PR TITLE
Clear store when redirecting to sign in, and don't let the user into the app if CreateLogin fails

### PR DESCRIPTION
**Pull request by cead22**
@marcaaron @stitesExpensify please review
cc @AndrewGable @tgolen 

- Fixes https://github.com/Expensify/Expensify/issues/141696
- Fixes https://github.com/Expensify/Expensify/issues/141695

**Note** the commit https://github.com/Expensify/ReactNativeChat/pull/557/commits/881228c06f9db6bc97a38dc6461d203ecb0bd5cd which I pushed and reverted intentionally, has a slightly different solution: when authenticate succeeds, instead of not letting the user into the app if create login fails, we let the user in knowing that re-authentication will fail, but the user can start using the app, and will be signed out when we try to re-authenticate. The commit if pretty small, so I wanted to share it in case we prefer that solution, but we can also handle that in a separate PR if we feel that's the way to go

# Tests
### 1) Tested hardcoding an error in api.php for Authenticate, tried signing in, confirmed proper error message shows up
```diff

Expensidev/Web-Expensify (master) $ git diff
diff --git a/api.php b/api.php
index 7ff4a5611d..27cca55640 100755
--- a/api.php
+++ b/api.php
@@ -2078,6 +2078,7 @@ try {
         }
         UserAPI::changePrimaryLogin($authToken, $login, $_REQUEST['password'] ?? '');
     } elseif ($command == 'Authenticate') {
+        // throw new ExpError('E5219A50-8EB3-4C1A-BB87-4FAABAE0F063', 'Error authenticating!!', '', [], false);
         Maintenance::blockWithJSONResponse();
         $partnerName = $_REQUEST['partnerName'] ?? null;
         $partnerPassword = $_REQUEST['partnerPassword'] ?? null;
```
image

### 2) Tested hardcoding an error in api.php for CreateLogin, tried signing in, confirmed proper error message shows up
```diff
@@ -2383,7 +2384,8 @@ try {
     } elseif ($command === 'MergeAccountWithSAML') {
         $response = UserAPI::mergeAccountWithSAML($authToken, $_REQUEST['validateCode'] ?? '');
     } elseif ($command === 'CreateLogin') {
-        $response = Auth::createLogin($authToken, $_REQUEST['partnerName'] ?? '', $_REQUEST['partnerPassword'] ?? '', $_REQUEST['partnerUserID'] ?? '', $_REQUEST['partnerUserSecret'] ?? '');
+        // $response = Auth::createLogin($authToken, $_REQUEST['partnerName'] ?? '', $_REQUEST['partnerPassword'] ?? '', $_REQUEST['partnerUserID'] ?? '', $_REQUEST['partnerUserSecret'] ?? '');
+        throw new ExpError('E5219A50-8EB3-4C1A-BB87-4FAABAE0F063', 'Error creating login', '', [], false);
     } elseif ($command === 'TwoFactorAuth_Validate') {
         if (!BetaManager::isInBeta($email, BetaManager::BETA_TWO_FACTOR_AUTH)) {
             throw new ExpError('E5219A50-8EB3-4C1A-BB87-4FAABAE0F063', 'Action not permitted', '', [], false);
```
image

### 3) I updated auth tokens to expire after 15s
```diff
diff --git a/auth/lib/AuthToken.cpp b/auth/lib/AuthToken.cpp
index 3bdb32a4a..781de493f 100644
--- a/auth/lib/AuthToken.cpp
+++ b/auth/lib/AuthToken.cpp
@@ -907,7 +907,7 @@ string AuthToken::create(int64_t accountID, int64_t partnerID, const bool isVali
     authToken["accountID"] = to_string(accountID);
     authToken["partnerID"] = to_string(partnerID);
     authToken["issued"] = to_string(STimeNow());
-    authToken["expires"] = to_string(STimeNow() + expires);
+    authToken["expires"] = to_string(STimeNow() + 15 * STIME_US_PER_S);
     authToken["type"] = typeStrings[type];
 
     if (requestingAccountID != 0) {
```
- Signed in successfully
- Posted a comment
- Waited 15s
- Posted another comment
- Confirmed re-authentication worked 
- Confirmed comment posted after re-authentication
- Refreshed
- Confirmed the last comment was shown

### Extra) on that commit I mentioned in the **Note** above
- Signed in successfully
- Confirmed warning was logged saying that we failed to create a login and that re-authentication will fail
- Waited 15s
- Posted another comment
- Confirmed re-authentication didn't work and I was signed out 
- **Note** when doing this, I got into a network request loop

### CODE REVIEW

**Review by marcaaron — CHANGES_REQUESTED** [review]
LGTM, left a few questions / NABs. The main change that I'm requesting here is that we consider not catching errors for `queueRequest()` usages or explain how they are possible if it does in fact work.

**Review by stitesExpensify — COMMENTED** [review]
Marc had good comments, but the meat and potatoes LGTM :+1:

**Review by marcaaron — APPROVED** [review]
Ok lgtm all your @stitesExpensify

**Review by stitesExpensify — APPROVED** [review]
LGTM! Yay for cleaning up

**Pull request merged**
