### PR TITLE
Show day of the week when other user is in a different date

### PR DESCRIPTION
**Pull request by rdjuric**
### Details

Modifies our `ParticipantLocalTime` to also show the day of the week when the other user is in a different day.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4118

### Tests

1. Open any chat
2. Change your timezone so that you're one day ahead or one day behind the other user
3. Above the composer you should see the day of the week that the other user is in
### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/53711423/127076626-13b16006-37c7-40ab-8ba3-c441d47fb9a2.mov

#### Mobile Web

mWeb

#### Desktop

https://user-images.githubusercontent.com/53711423/127076633-98b4ab0a-2782-42eb-94f9-013d5d6c6784.mov

#### iOS

https://user-images.githubusercontent.com/53711423/127076637-e79249e9-170d-4cf3-9ddf-9d29f1a328ec.mp4

#### Android

android

### CODE REVIEW

**Review by Dal-Papa — APPROVED** [review]

**Comment by isagoico** [comment]
## Day of the week is not displayed

## Action Performed 
1. Log in to New Expensify in Android / iOS or Desktop 
2. Change your timezone so that you're one day ahead or one day behind the other user
3. Above the composer you should see the day of the week that the other user is in

## Expected Result
Day of the week is displayed along with the current time of the user

## Actual result
Day of the week is not displayed with the current time of the user. 

## Platform 

iOS ✔️ 
Android ✔️ 
Desktop ✔️ 


**Notes/images/video**

image

**Comment by rdjuric** [comment]
Hi @isagoico! I couldn't reproduce it on staging (see image). Can you give me more details, like the Timezone the testers were in?

Just to make sure: the day difference is calculated based on the timezones of the account, and not in relation to the time of the device/computer. In the screenshot, looks like one user is at 3:25 AM and the other at 7:21 AM. I can't be sure but looks like they might have been in the same day of the week.

Screen Shot 2021-07-29 at 4 14 43 PM

**Comment by isagoico** [comment]
@rdjuric this is only reproducible on mobile apps and in desktop. Web is a pass for this PR.

**Comment by rdjuric** [comment]
Thanks for the clarification, @isagoico! I still can't reproduce it anywhere
Screen Shot 2021-07-29 at 5 55 01 PM

**Comment by isagoico** [comment]
Weird 🤔 I'm not able to reproduce the issue anymore on Android or iOS but I'm still able to repro on Desktop 🤯 
I checked with the same account in dekstop as in iOS and Android so it _should_ be working there too. 
image


image

**Comment by rdjuric** [comment]
Yes! It's specially weird since the Desktop has the same code as the Web 🤯

I'll keep looking for a way to reproduce this.

**Comment by isagoico** [comment]
mmm I did just update the desktop app and it's still showing build 1.0.81-2 instead of 1.0.81-3 so I think that's the main issue. I'll ask in contributor channel if anyone has been able to download build 1.0.81-3 in desktop.

**Comment by isagoico** [comment]
Retest was a pass! Checking this one off the list

**Pull request merged**
