### PR TITLE
Code Block Formatting Bug

### PR DESCRIPTION
**Pull request by ronlaniado**
### Details
I have fixed the bug where text in code blocks breaks words and symbols. It will now no longer do so. 

### Fixed Issues
[https://github.com/Expensify/Expensify.cash/issues/993](Issue 993)

### Tests
For example:
1. Sign into the Expensify.cash app
2. Start a chat with some other user
3. Use three backticks (```) follows by a newline (Shift+Enter) to add a block of long code, ending if with another newline (Shift+Enter) and three more backticks (```).
4. See the output of the message is formatted correctly

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Desktop
Screen Shot 2020-12-30 at 12 18 45 PM

#### iOS
Screen Shot 2020-12-30 at 12 16 22 PM

### CODE REVIEW

**Comment by ronlaniado** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ronlaniado** [comment]
I just noticed that there are a lot of stylistic changes made due to prettier. I can fix this to match the required style that Expensify needs. For any code reviewers so far, the changes I have made can be found in the addAction function in lines ~450-500

**Comment by ronlaniado** [comment]
recheck

**Comment by ronlaniado** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by ronlaniado** [comment]
recheck

**Comment by TomatoToaster** [comment]
Hey @ronlaniado, thanks for taking a stab at this one! We decided to go with a different solution since it addressed the root cause of the problem in our expensify-common library: https://github.com/Expensify/expensify-common/pull/316.

**Pull request closed without merging**
