### PR TITLE
fix: message highlight issue & mini context-menu issue

### PR DESCRIPTION
**Pull request by parasharrajat**
@jasperhuangg Please review.

### Details

https://github.com/Expensify/App/issues/5197#issuecomment-917113461
https://github.com/Expensify/App/issues/5250#issuecomment-919356200
### Fixed Issues

$ https://github.com/Expensify/App/issues/5197
$ https://github.com/Expensify/App/issues/5250

### Tests | QA Steps

1. Open any chat.
2. Right-click on any message. When Context Menu is open, no mini menu is shown.
3. Now move to the empty area on the same message, right-click on that empty area(which is not covered by the context menu).
4. Click anywhere on the app. Context Menu should close.
5. Now hover back on the same message. The mini menu **should** be shown again.

---
 1. Long press/click over any chat item,
 2. Chat options like Copy to Clipboard or Mark as Unread. will be shown.
 3. Choose any one of the options mentioned above.
 4. Hover the cursor on another message.
 5. Previous message **should not** be highlighted anymore.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

https://user-images.githubusercontent.com/24370807/133478084-a476e34e-4f9b-45ad-830d-c4ad74400b80.mp4

#### Mobile Web

https://user-images.githubusercontent.com/24370807/133487236-9d28efd3-a646-49ae-870f-b768848b6fe0.mp4

#### Android

https://user-images.githubusercontent.com/24370807/133480956-80b9da2d-7aa2-46cd-9174-1c1b5187d731.mp4

### CODE REVIEW

**Comment by luacmartins** [comment]
It seems that there is still some sort of race condition between the callbacks. When trying to right click through multiple messages in a short period of time, we can still get in some weird state. It's a bit of an edge case, but it would be nice to fix it.

https://user-images.githubusercontent.com/22219519/133495918-84c9adad-6b46-4e18-9242-7a7ab4a82c70.mov

**Comment by parasharrajat** [comment]
Sure, let me check this.

**Comment by kadiealexander** [comment]
Hi @parasharrajat, I've placed this issue on hold as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1631754482374800), as we are prioritising issues related to a feature release scheduled for 9/24. As an apology for the delay, we will add a $100 bonus as a thank you for waiting.

**Comment by parasharrajat** [comment]
@luacmartins I have handled three types of possible race conditions now. It is performing better.
1. When onHide callback was getting overridden, if a new context menu was opening.
2. When onHide callback (called after user has done some action) was getting overridden, if a new context menu was opening.
3. When the Previous instance of the menu is supposed to close with a delay(If happens when user click either copy to clipboard or mark unread), but it was closing the new instance if user opened a new context menu.

**Comment by luacmartins** [comment]
This is a tricky one. I'm still seeing the race condition. I'm not too sure how to solve those though. Do you have any more ideas?

https://user-images.githubusercontent.com/22219519/133801029-c99aa454-38c6-4740-9ffe-70c801bb6faa.mov

**Comment by parasharrajat** [comment]
Hmm. Interesting! I specifically checked all callbacks and applied for the fix. I am not facing any with the new changes. But it does not mean that there are none. I will check again.

**Comment by jasperhuangg** [comment]
@parasharrajat Let me know when you're done fixing that race condition, or if you need some help investigating!

**Comment by parasharrajat** [comment]
@jasperhuangg Yeah, I need your help to confirm if race conditions are still happening on this PR. I don't see them anymore. Maybe my computer is processing too fast.

**Review by jasperhuangg — APPROVED** [review]
Tests well on all platforms!

**Comment by luacmartins** [comment]
Hmm I thought this PR was on `n6-hold` and we should not merge it. Is that not the case?

**Pull request merged**
