### PR TITLE
add 404 page to Help Site

### PR DESCRIPTION
**Pull request by marcochavezf**
cc @michelle-thompson 

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/216920

### Tests

0. (you need ruby and bundler installed to do this, more info [here](https://github.com/Expensify/App/tree/main/docs#pre-requisites))
1. Run:

    ```bash
    cd docs
    bundle install
    bundle exec jekyll serve
    ```
2. Navigate http://localhost:4000/blabla (a non-existent page) and verify the 404 page is displayed

### QA Steps

Follow step 2 from the Test section

#### Web

127 0 0 1_4000_blabla

### CODE REVIEW

**Comment by michelle-thompson** [comment]
Looks good to me!

**Review by techievivek — APPROVED** [review]
Looks good to me, just tested this locally and it works like charm.

**Comment by mvtglobally** [comment]
@marcochavezf @techievivek Can you validate this internally or update the QA steps for Staging so we can run it

**Comment by marcochavezf** [comment]
Oops I forgot to update the QA tests with the correct URL, but it's working fine on the production env (https://help.expensify.com/):

Screen Shot 2022-08-16 at 18 21 59

**Pull request merged**
