### PR TITLE
Center loading indicator

### PR DESCRIPTION
**Pull request by varshamb**
### Details

Loading indicator was not in the center of container on page `addPersonalBankAccountPage` and `BankAccountStep` .
We made it center using `styles.flex1`.
### Fixed Issues

$ https://github.com/Expensify/App/issues/10362

#### Steps for adding Payment method in addPersonalBankAccountPage:

1. Go to settings > Payments > Add payment method
2. Click on bank account
3. Verify that the loading spinner is centered vertically.

#### Steps for BankAccountStep in Workplace:

1. Settings > Workspace > Connect Bank Account
2. Click on Connect Online with Plaid
3. Verify that the loading spinner is centered vertically.

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>

#### Steps for adding Payment method in addPersonalBankAccountPage:

1. Login to valid account
2. Go to settings > Payments > Add payment method
4. Click on bank account

#### Steps for BankAccountStep in Workplace:

1. Login to valid account
2. Settings > Workspace > Connect Bank Account
3. Click on Connect Online with Plaid

- [X] Verify that no errors appear in the JS console

#### Web

addPersonalBankAccountPage:

image

BankAccountStep:

image

#### Mobile Web

addPersonalBankAccountPage:

https://user-images.githubusercontent.com/111683206/188496209-04af85a6-fb3b-45db-82ff-ae4d5a7abe5f.mp4

BankAccountStep:

https://user-images.githubusercontent.com/111683206/189186888-71d56095-3d87-4de8-ba9c-73b8aefac93c.mp4

#### Desktop

addPersonalBankAccountPage:

image

BankAccountStep:

image

#### iOS

addPersonalBankAccountPage:

https://user-images.githubusercontent.com/111683206/188496437-ef65a10c-4429-45a4-b3c2-174c7b2ae2f5.mp4

BankAccountStep:

https://user-images.githubusercontent.com/111683206/188940433-2ee1d00e-ccc6-4de8-a80d-6e83f50e5fcb.mp4

#### Android

addPersonalBankAccountPage:

WhatsApp Image 2022-09-05 at 23 10 28

BankAccountStep:

WhatsApp Image 2022-09-07 at 22 37 47

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
> Also, the same issue could occur when adding a bank account via workspace. It should be handled there too!

Can you handle this also!

**Comment by varshamb** [comment]
> > Also, the same issue could occur when adding a bank account via workspace. It should be handled there too!
> 
> Can you handle this also!

Yes sure, please suggest the page for adding a bank account via workspace. I am not getting an option to add a bank account in my workspace.

**Comment by Santhosh-Sellavel** [comment]
Find usages of AddPlaidAccount @varshamb

**Comment by varshamb** [comment]
@Santhosh-Sellavel Done.

**Comment by jasperhuangg** [comment]
> @Santhosh-Sellavel Done.

@varshamb Do you mind updating the screenshots to include both the updated views? Thanks!

**Comment by Santhosh-Sellavel** [comment]
@varshamb Still web & desktop videos are not updated,  can you update them properly?

**Comment by Santhosh-Sellavel** [comment]
Take this [PR](https://github.com/Expensify/App/pull/10742) as an example, nothing from the app screen is cut off.

**Comment by varshamb** [comment]
@Santhosh-Sellavel Is it really needed to update those screen shots, we used `styles.flex1` on both pages, the screens which I have attached are slightly cropped from the bottom.

cc: @jasperhuangg

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel Is it really needed to update those screen shots, we used `styles.flex1` on both pages, the screens which I have attached are slightly cropped from the bottom.
> 
> cc: @jasperhuangg

Actually, that's what @jasperhuangg has asked [here](https://github.com/Expensify/App/pull/10823#issuecomment-1240570670) to update.

> @varshamb
> Thanks! Looks like a few of your screenshots are slightly cut-off and don't display the indicator as centered. I'm checking out your PR now and verifying that everything looks good on my end, **but please update those screenshots so that they display the loading indicator as centered vertically/horizontally, since that's what the issue calls for.**

At least the RHN should be completely visible to ensure it's working fine on both platforms!

**Comment by varshamb** [comment]
@Santhosh-Sellavel updated.

**Comment by Santhosh-Sellavel** [comment]
<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

**Comment by Santhosh-Sellavel** [comment]
@varshamb 

Thanks for updating, mostly looks good just a couple more things.

Can you update the test steps for workspace  flow too?

#### Workspace Add Bank
Settings -> Workspace -> Connect Bank Account

**Comment by varshamb** [comment]
@Santhosh-Sellavel Thanks for your inputs.
Both the 'Tests' & 'QA Tests' has been updated.

**Review by jasperhuangg — APPROVED** [review]

**Review by Santhosh-Sellavel — APPROVED** [review]

**Comment by Santhosh-Sellavel** [comment]
@jasperhuangg LGTM

**Review by Santhosh-Sellavel — APPROVED** [review]

**Comment by francoisl** [comment]
🚀 [Cherry-picked](https://github.com/Expensify/App/actions/runs/3055939937) to staging by @francoisl in version: 1.2.0-3 🚀

 platform | result 
 ---|--- 
🤖 android 🤖|success ✅ 
🖥 desktop 🖥|success ✅
🍎 iOS 🍎| success ✅ 
🕸 web 🕸|success ✅

@Expensify/applauseleads please QA this PR and check it off on the [deploy checklist](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3AStagingDeployCash) if it passes.


---

Note: we had a conflict on the `staging` branch which ended up needing to be manually fixed, so this PR doesn't automatically appear in the diff between production and staging - so I'm manually adding the note that it was CPed to staging here.

**Pull request merged**
