### PR TITLE
fix: User avatar and email does not show when using Submit

### PR DESCRIPTION
**Pull request by nkdengineer**
### Fixed Issues

$ https://github.com/Expensify/App/issues/44295
PROPOSAL: https://github.com/Expensify/App/issues/44295#issuecomment-2195111222

### Tests

1. Global Create > Track Expense
2. Input the amount, description > Track
3. This will take you to your DM
4. Select Submit it to someone in the actionable whispers
5. Input the new user email
6. Submit it to them
7. Verify that: The avatar and email of the user you've submitted an expense to shows in the new transaction comment

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Global Create > Track Expense
2. Input the amount, description > Track
3. This will take you to your DM
4. Select Submit it to someone in the actionable whispers
5. Input the new user email
6. Submit it to them
7. Verify that: The avatar and email of the user you've submitted an expense to shows in the new transaction comment
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/fb5335a7-460c-4b32-a085-ffdd0bff2f77

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/984941ae-6290-4b56-a46a-f78b95eb8002

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/09907068-b464-4036-bcf9-42bac2834406

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/d20b5b83-f092-4973-900b-0acabd5610d4

</details>

### CODE REVIEW

**Comment by nkdengineer** [comment]
@shubham1206agra I'm still working fine, please check again

https://github.com/user-attachments/assets/415558e3-fd13-4066-a922-0660a0bf88d2

**Comment by nkdengineer** [comment]
@shubham1206agra please add more detailed steps and video so that I can follow your issue

**Comment by nkdengineer** [comment]
@shubham1206agra maybe the problem happens when in strict mode, you can turn it off [here](https://github.com/Expensify/App/blob/be3ebb0931b5bfd5a20354f17f2b7661aada4bb8/src/CONFIG.ts#L99)

**Comment by nkdengineer** [comment]
@shubham1206agra I can reproduce it now, I will investigate and update tomorrow.

**Comment by nkdengineer** [comment]
@shubham1206agra I missed checking out this branch yesterday then I can reproduce this bug. I tried many times again but can reproduce now. Sorry for the confusion.

**Comment by nkdengineer** [comment]
@grgia Can you please add a build here? I need to re-test in the real device to confirm this bug still happens or not.

**Comment by nkdengineer** [comment]
@shubham1206agra Let's wait for a build here and we can re-test again if it still happens.

**Comment by grgia** [comment]
Triggered a test build @nkdengineer !

**Comment by nkdengineer** [comment]
@grgia Unnecessary, the build is failing on all platforms.

**Comment by grgia** [comment]
@nkdengineer it triggered two builds by accident and I cancelled the first, second is still building!

**Comment by nkdengineer** [comment]
Thanks.

**Comment by nkdengineer** [comment]
@shubham1206agra Found the RCA when testing in the build web, `ConvertTrackedExpenseToRequest` API BE returns only the personal details of the current user, and the `participant` also only has the current user. If we open another report and go back, `OpenReport` API is called and then the necessary is returned.

I'm not sure why I can't reproduce locally on my side. Maybe on my side `OpenReport` API is called immediately after `ConvertTrackedExpenseToRequest` is called.

Screenshot 2024-07-30 at 17 11 57

**Comment by grgia** [comment]
@shubham1206agra @nkdengineer 
> API BE returns only the personal details of the current user, and the participant also only has the current user.

Could you remind me the expected behavior here

**Comment by nkdengineer** [comment]
@grgia the expected behavior here is. For `ConvertTrackedExpenseToRequest` API, BE should

1. `personalDetailsList`, return the personal details of the user that is `payerEmail` in the param of the API

2. `report` (invoice report),  return the correct `participants` that contain the `payerEmail` user. Current this API returns `participant` only has the current user

**Comment by grgia** [comment]
@nkdengineer @shubham1206agra Let me take a look at the BE this afternoon, please let me know if there are any specific steps I need to consider

**Comment by grgia** [comment]
I also see the call to OpenReport after in Dev @nkdengineer but not in the adhoc test as well

**Comment by grgia** [comment]
Either way I can update `ConvertTrackedExpenseToRequest` to send both participants, I have a PR up [here](https://github.com/Expensify/Auth/pull/11854)  (internal repo)

**Comment by nkdengineer** [comment]
@grgia Got it. We should return the data correctly as I mentioned here https://github.com/Expensify/App/pull/45393#issuecomment-2258124000 to prevent loading show in header before `OpenReport` API is complete or it's not called.

**Comment by grgia** [comment]
I verified locally that the linked PR will send the necessary detail. It's in review now and I'll keep you updated

**Comment by muttmuure** [comment]
@nkdengineer are you unblocked now? The linked Auth PR is on production

**Comment by nkdengineer** [comment]
@muttmuure Thanks for your update, let me test again.

**Comment by nkdengineer** [comment]
@shubham1206agra I tested in the ad-hoc build again and the bug is fixed after the BE changes. Can you please double-check with your local again, thanks.

**Comment by nkdengineer** [comment]
@shubham1206agra Merged main.

**Review by shubham1206agra — APPROVED** [review]

**Review by grgia — APPROVED** [review]

**Pull request merged**
