### PR TITLE
Fix Placeholders not vertically centered in text inputs

### PR DESCRIPTION
**Pull request by PrashantMangukiya**
Corrected Placeholders not vertically centered in text inputs. @chiragsalian kindly review pull request, please message me if any information missing from my side.  I closed previous pull request #4823 because I forgot to sign commit with gpg.

### Details
Basically when there is no focus it shows ExpensiTextInputLabel.js component. We need to update top value for expensiTextInputLabel style within src/styles/styles.js file. i.e. change top: 14 to top: 16 as under:

    expensiTextInputLabel: {
	...
        top: 16,
	...
    },

So now we moved inactive label default position 2 pt down, So to keep the active label (i.e. when focused) at the same position we have to set ACTIVE_LABEL_TRANSLATE_Y = -12 (at present it is -10) within src/components/ExpensiTextInput/BaseExpensiTextInput.js  (line 12)

### Fixed Issues
$ https://github.com/Expensify/App/issues/4675

### Tests
1. Run app on any platform
2. Check  text input placeholder on Login screen, now it will show text input placeholder vertically centered when no input text.
3. For after login screen, Text input with no value will show placeholder vertically centered where text input used.

### QA Steps
1. Login screen text input. When there is no focus on text input, placeholder shows vertically centered now. (previously it was vertically off centered)
2. After login any text input.  When there is no focus on text input, placeholder shows vertically centered now. (previously it was vertically off centered)

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
4675-Web

#### Mobile Web
4675-mobileWeb

#### Desktop
macOsDesktop

#### iOS
4675-iOS

#### Android
4675-Android7

### CODE REVIEW

**Comment by PrashantMangukiya** [comment]
Hi, @cead22, As soon as you get time kindly review my pull request 4874. This is my first pull request, if so anything missing then please message me. I will provide needed information as soon as possible. Thank you.

**Comment by cead22** [comment]
@PrashantMangukiya code looks good, but please include screenshots showing active text inputs and their labels like you did in the other PR for completeness

**Comment by PrashantMangukiya** [comment]
Hi @cead22  Attached is screenshots having text input value. 

#### Web
4675-Web-Input

4675-Web-Input-inner

#### Mobile Web
4675-MobileWeb-Input

#### Desktop
4675-macOsDesktop-inner

#### iOS
4675-IOS-Input

#### Android
4675-Android7-2


4675-Android-3

**Review by cead22 — APPROVED** [review]

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-10.  :confetti_ball:

**Pull request merged**
