### PR TITLE
Blur login page input only when transitioned to magic link page

### PR DESCRIPTION
**Pull request by huzaifa-99**
### Fixed Issues

$ https://github.com/Expensify/App/issues/13044
PROPOSAL: https://github.com/Expensify/App/issues/13044#issuecomment-1329560350

### Tests

**Test with an existing account**
1. Go to login page
2. Enter Email
3. Click Continue (You should be redirected to Password Screen)
5. Verify that the keyboard does not close and there is no jerk effect

**Test with a new account**
1. Go to login page
2. Enter email that is not yet registered
3. Click Continue (You should be redirected to Magic Link Screen)
4. Verify that the keyboard should dismiss 

**Test keyboard dismiss**
1. Go to login page
2. Click on the input field (the virtual keyboard should open)
3. Click outside the input field other than the continue button (the virtual keyboard should dismiss)

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

**Test with an existing account**
1. Go to login page
2. Enter Email
3. Click Continue (You should be redirected to Password Screen)
4. Verify that the keyboard does not close and there is no jerk effect

**Test with a new account**
1. Go to login page
2. Enter email that is not yet registered
3. Click Continue (You should be redirected to Magic Link Screen)
4. Verify that the keyboard should dismiss 

**Test keyboard dismiss**
1. Go to login page
2. Click on the input field (the virtual keyboard should open)
3. Click outside the input field other than the continue button (the virtual keyboard should dismiss)

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Safari
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

#### Safari
https://user-images.githubusercontent.com/68777211/205229435-dc55c5e1-0e94-4a26-904d-6a74b738f70f.mp4

#### Chrome
https://user-images.githubusercontent.com/68777211/205229448-dc489b0c-2d3a-4e71-8ae9-b9800a9d0d30.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/68777211/205229502-cb8b2aa4-8496-4eba-abcc-895463408955.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/68777211/205229553-0b810705-0bf8-404f-96af-14437033ae4d.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/68777211/205229565-7fb9472a-c25d-4b8b-a162-74d891a5511f.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/68777211/205229585-654315bc-f331-4f75-b1f9-dffc14429379.mp4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/68777211/204353695-599f3061-2e0c-4072-a84c-98a894011f57.mp4

</details>

### CODE REVIEW

**Review by rushatgabhane — APPROVED** [review]
## Reviewer Checklist

@pecanoro LGTM!

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.


### Screenshots/Videos
<details>
<summary>Web</summary>


https://user-images.githubusercontent.com/29673073/205240956-9f60ee46-c7c5-48ea-8b53-ebeb5b06e567.mov


</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://user-images.githubusercontent.com/29673073/205240336-c42d55f8-3b60-4240-a0a5-d021df62ccc3.mov


</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/29673073/205240310-c428f932-aa78-4292-9a1a-edbb034ce5c5.mov


</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/29673073/205238616-577de75f-e643-4fc5-bf61-db2610fe733c.mov

</details>

<details>
<summary>iOS</summary>





https://user-images.githubusercontent.com/29673073/205238288-7f9bfd2c-f0c0-4409-bd71-e608d8d38240.mov


</details>

<details>
<summary>Android</summary>


https://user-images.githubusercontent.com/29673073/205238115-d6f50673-66b0-479a-ba92-1c74b380d130.mov


</details>

**Comment by tgolen** [comment]
@huzaifa-99 Can you also please add to your tests to be sure that tapping outside of the email or password form allows the keyboard to be dismissed? We need to ensure that behavior doesn't regress at all.

I just tested it out, and it looks like tapping outside of the inputs to blur them still works, so that's good 👍 

However, while testing it, I found that the original issue is still there if:
- You press [Enter]
- You press the [Return] button on the soft keyboard

It only appears to me like the issue is solved if you tap on the Continue button. I see that the original issue only mentions tapping on the Continue button, but should we also cover these other cases?

**Comment by pecanoro** [comment]
> You press [Enter]

What do you mean by pressing Enter? On a physical keyboard?

> You press the [Return] button on the soft keyboard.

I was able to reproduce what Tim mentioned when pressing the keyboard button for `Return`, it closes the keyboard. However, this seems like the native behavior of the keyboard because it does the same in many other apps on my phone. Just guessing though, maybe I'm totally wrong.

I am asuming the Return button you mention is this one:

Monosnap App 2022-12-05 12-20-26

**Comment by tgolen** [comment]
> What do you mean by pressing Enter? On a physical keyboard?

Yeah, a physical keyboard. This is easy to do when testing an emulator. Granted, it won't happen much in the real world except on tablets. However, since behavior is the same as the "return button" I thought it was worth mentioning.

> I am asuming the Return button you mention is this one:

Yep, exactly.

**Comment by pecanoro** [comment]
I honestly think it's native behavior, as I mentioned, I tried with other apps and it closes it every single time even when it makes sense to leave it open. @tgolen do you think we should look into it or can we move forward with merging it as it is right now.

**Comment by tgolen** [comment]
Yeah, I also agree that it's native behavior. I mostly bring it up so that we can all agree that in some cases, we just won't be able to avoid it, and that's probably OK.

**Review by pecanoro — APPROVED** [review]

**Pull request merged**
