### PR TITLE
Change tooltiptext of avatar in LHN to Settings

### PR DESCRIPTION
**Pull request by sobitneupane**
### Details

Change the tooltiptext of avatar from displayName to Settings
This issue is occurring in web and desktop app. I have tested only for web. **So, I would like to request reviewer to double check in desktop.**

### Fixed Issues

$ https://github.com/Expensify/App/issues/6911

### Tests

1. Hovered on avatar near to the search icon at the top of LHN

### QA Steps

1. Open app in desktop or Open web app
2. Hover on avatar near to the search icon at the top of LHN

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

Screenshot from 2022-01-02 14-05-07

### CODE REVIEW

**Comment by sobitneupane** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by parasharrajat — APPROVED** [review]
LGTM. I am not asking for the remaining screenshots as this is a minor change and I know it will work. 

cc: @Beamanator 
:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by Beamanator** [comment]
I just ran the workflows, I assume tests will pass 👍

**Review by Beamanator — APPROVED** [review]
Nice work 💪 Will merge once tests pass

**Pull request merged**
