### PR TITLE
Trim long workspace name

### PR DESCRIPTION
**Pull request by akshayasalvi**
@Julesssss Can you please review this?

### Details
- Trimmed workspace name when its too long

### Fixed Issues

$ #4747 

### Tests
1. Test on WorkspaceSidebar
2. Tested on Home Sidebar

### QA Steps
1. Create an account with a very long email
2. Create a new workspace
3. Then visit the workspace and verify that it doesn't get trimmed outside the container.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screenshot 2021-08-25 at 11 17 34 PM
Screenshot 2021-08-25 at 11 01 01 PM

#### Mobile Web
Screenshot 2021-08-25 at 11 36 02 PM
Screenshot 2021-08-25 at 11 35 55 PM

#### Desktop
Screenshot 2021-08-25 at 11 38 02 PM
Screenshot 2021-08-25 at 11 37 48 PM

#### iOS
Screenshot 2021-08-25 at 11 46 04 PM
Screenshot 2021-08-25 at 11 46 17 PM

#### Android
Screenshot 2021-08-26 at 12 05 52 AM
Screenshot 2021-08-26 at 12 05 26 AM

### CODE REVIEW

**Review by aldo-expensify — APPROVED** [review]
Looks fine, tested in web / android.

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

**Comment by mallenexpensify** [comment]
@akshayasalvi when creating new PRs, can you please include the full link to the GH issue and not just the issue number? 
`$ https://github.com/Expensify/App/issues/4747` instead of

**Comment by akshayasalvi** [comment]
Okay noted. Will do.

**Pull request merged**
