### PR TITLE
feat: address remaining design inconsistencies for distance requests

### PR DESCRIPTION
**Pull request by akinwale**
### Details
Updates the margin and padding styles for distance and money requests.

### Fixed Issues
$ https://github.com/Expensify/App/issues/27052
PROPOSAL: https://github.com/Expensify/App/issues/27052#issuecomment-1712142719

### Tests
1. Launch Expensify, and open the global create menu.
2. Select Request money and select Distance if it is not yet active.
3. Add Start and End waypoints, and click Next.
4. Verify the margins and spacing on the request confirmation page. 

- [x] Verify that no errors appear in the JS console

### Offline tests
Same as tests.

### QA Steps
Same as tests.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

27052-web

</details>

<details>
<summary>Mobile Web - Chrome</summary>

27052-android-chrome

</details>

<details>
<summary>Mobile Web - Safari</summary>

27052-ios-safari-1

</details>

<details>
<summary>Desktop</summary>

27052-desktop

</details>

<details>
<summary>iOS</summary>

27052-ios-native

</details>

<details>
<summary>Android</summary>

27052-android-native

</details>

### CODE REVIEW

**Comment by akinwale** [comment]
@situchan I added a 16px top margin for the Request button at the bottom of the confirmation page, since there was very little spacing after removing the bottom margins from the push-to-page rows. This is what it looks like on iOS Safari where it's noticeable.

27052-ios-safari-2

cc @shawnborton @dannymcclain

**Comment by shawnborton** [comment]
I think we want just 8px above the bottom-docked buttons?

**Comment by akinwale** [comment]
> I think we want just 8px above the bottom-docked buttons?

@shawnborton Here's what it looks like with 8px.

27052-ios-safari-3

**Comment by shawnborton** [comment]
Awesome, can you show what it looks like when the form might overlap below the bottom-docked button?

**Comment by akinwale** [comment]
> Awesome, can you show what it looks like when the form might overlap below the bottom-docked button?

Sorry, I'm not quite sure what the form overlapping below means. Do you mean the form going all the way beyond the viewport to the bottom of the screen? Here are a couple of screenshots (one with categories and tags enabled to occupy more vertical space, and the other without).

27052-ios-safari-5

27052-ios-safari-4

**Comment by shawnborton** [comment]
Nice, yeah I think that looks good, although for these kinds of flows, do we want the green button to always be docked to the bottom of the viewport? And then all of the content would scroll behind it?

**Comment by akinwale** [comment]
> Nice, yeah I think that looks good, although for these kinds of flows, do we want the green button to always be docked to the bottom of the viewport? And then all of the content would scroll behind it?

I wasn't a part of the discussions concerning this, but I remember from the distance request issues I've worked on, after a few iterations, we settled for the button to start docked at the bottom, but should be scrollable along with the main content, if the content ever got up to that point.

**Comment by shawnborton** [comment]
Okay that makes sense to me, just tested other create flows and they do the same. Thanks for confirming. I say what you have looks good to me.

**Review by dannymcclain — DISMISSED** [review]
Looking good

**Comment by akinwale** [comment]
@situchan bump on review.

**Comment by situchan** [comment]
Code looks good. I will test in a few hrs

**Comment by akinwale** [comment]
@situchan bump. Hoping we can get this done and merged before the 3-day limit as today is already the 3rd day. Thanks.

**Comment by situchan** [comment]
- [x] Each push-to-page row has margin-bottom: 8px - let’s get rid of that so it’s a bit more compact and matches existing styles
- [x] the map image itself has a bunch of vertical margin (20px) and thus it feels quite far away from the push row below it which also has vertical margin. Let’s make the vertical margin on the map image something like 8px or 12px
- [x] The “To” field above the workspace has a height of 32px. Let’s remove the height and just have some margin-top, but no need for margin below as the workspace row (avatar + name) already has vertical margin. This change should be applied everywhere we have a “To” row
- [x] Let’s make the map preview image use the same border radius as other receipt previews, which I think is 16px

**Comment by situchan** [comment]
I feel space between Category and Billable is smaller. @shawnborton what do you think?

https://github.com/Expensify/App/assets/108292595/2f3a10b4-d9f5-47f7-a7d1-d9dd8c7497e0

**Review by situchan — COMMENTED** [review]
Let's add `styles.mt2` to Billable View here:
https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/components/MoneyRequestConfirmationList.js#L546

**Comment by akinwale** [comment]
> Let's add `styles.mt2` to Billable View here:
> 
> https://github.com/Expensify/App/blob/cf9ad20a4545ec01b16f88f9c1a53a7488ca1b44/src/components/MoneyRequestConfirmationList.js#L546

Done.

**Comment by situchan** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

web


https://github.com/Expensify/App/assets/108292595/0a680741-d72a-4437-94b4-3485ab5916f5



</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/108292595/1d2c8a6e-ab5e-4b2f-8f26-6e916cfac741



</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/108292595/43bf8da2-b32b-46ef-ac96-d7c52717e97a



</details>

<details>
<summary>Desktop</summary>

desktop


</details>

<details>
<summary>iOS</summary>


ios



</details>

<details>
<summary>Android</summary>


https://github.com/Expensify/App/assets/108292595/6c8be6ce-a8c6-4c55-8107-fccb6aed659b



</details>

**Review by situchan — APPROVED** [review]
:shipit:

**Comment by shawnborton** [comment]
> I feel space between Category and Billable is smaller. @shawnborton what do you think?

Yeah, I think we maybe need to give the billable row some vertical margin to make it feel like it has the same height as all of the other push rows. Can we make it so that the billable row is basically the same width/height as every row above it, and the content (label + toggle) is vertically centered within that area? 

cc @Expensify/design

**Comment by situchan** [comment]
> > I feel space between Category and Billable is smaller. @shawnborton what do you think?
> 
> Yeah, I think we maybe need to give the billable row some vertical margin to make it feel like it has the same height as all of the other push rows. Can we make it so that the billable row is basically the same width/height as every row above it, and the content (label + toggle) is vertically centered within that area?
> 
> cc @Expensify/design

Agree, but maybe we can do that as follow-up to apply same height to all switch views by making a new common component.

Screenshot 2023-09-28 at 9 23 39 AM
Screenshot 2023-09-28 at 9 24 59 AM
Screenshot 2023-09-28 at 9 26 22 AM

**Comment by shawnborton** [comment]
I suppose we could but we need to at least fix it here right?

**Comment by situchan** [comment]
> I suppose we could but we need to at least fix it here right?

yes

**Comment by situchan** [comment]
@akinwale let's do that on this page only for now

**Comment by akinwale** [comment]
> @akinwale let's do that on this page only for now

Pushed a new commit. Modified the styles to make it the same height as the push-to-page rows.

**Comment by situchan** [comment]
Looks good. @joelbettner all yours!


https://github.com/Expensify/App/assets/108292595/897095f5-298a-482b-908e-0f8e565db08b

**Review by joelbettner — APPROVED** [review]

**Pull request merged**
