### PR TITLE
[NO-QA] Bump Onyx commit to fix IOU regression

### PR DESCRIPTION
**Pull request by Julesssss**
CC @marcaaron 

### Details
Bumps Onyx after [this regression fix PR](https://github.com/Expensify/react-native-onyx/pull/81)

### Fixed Issues
N/A

### Tests
N/A -- the feature was [tested here](https://github.com/Expensify/react-native-onyx/pull/81)

### QA Steps
N/A

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
eslint is failing (probably because it's broken on `main` - also... what? how?)

**Comment by Julesssss** [comment]
Yeah, that's expected. The initial issue was triggered by an unlucky conflict. This lint exists on main currently. Fixing now.

**Comment by Julesssss** [comment]
Here's the original explanation: https://github.com/Expensify/Expensify.cash/pull/3401#issuecomment-857714870

(I am getting confused with all these fixes)

**Comment by Julesssss** [comment]
My PR here fixes the regression and the lint error: https://github.com/Expensify/Expensify.cash/pull/3481

**Comment by Julesssss** [comment]
Okay. The PR which fixes a lint which slipped into main due to a conflict has been merged. I updated this PR, so the tests will pass this time.

**Comment by Julesssss** [comment]
Ready for review: @sketchydroide @marcaaron

**Review by alex-mechler — APPROVED** [review]

**Pull request merged**
