### PR TITLE
Fix menu item padding

### PR DESCRIPTION
**Pull request by cristipaval**
### Details
Removes the extra inner padding when MenuItem has no left icon.

### Fixed Issues
$ https://github.com/Expensify/App/issues/14745

### Tests and QA Steps
1. Go to Settings -> Profile and verify that the left margin is 20px
2. Go to Settings -> Preferences and verify that the left margin is 20px
3. Go to Settings -> Profile -> Timezone and verify that the left margin is 20px
4. Test that all other pages with menu items look as expected

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/18078393/216983554-b5f6552b-1b00-45dc-89a9-9c171d7f27c4.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/18078393/216983580-670d4182-5ef4-450f-9fef-79bbdb0a5e14.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/18078393/216983606-1149fe6f-e3ce-4405-8816-834614caa80c.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/18078393/216983635-2892728f-bb9d-4639-9e9f-5d26e2112d93.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/18078393/216983656-34656022-6d54-4ed1-8dc1-bb2dffd4a667.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/18078393/216983703-dd482516-c441-4ea7-b30f-105011648a56.mov

</details>

### CODE REVIEW

**Comment by cristipaval** [comment]
yeah, I think we better wait for @shawnborton to confirm it looks as expected. He is ooo today, so I think he will review it tomorrow the earliest.

**Review by neil-marcellini — COMMENTED** [review]
I feel like the alignment with the back button in the header was better on the profile page before. The timezone page does look like an improvement.

Profile this branch
image

Profile staging.
image

**Comment by shawnborton** [comment]
This looks good to me. I agree that the top back arrow feels a bit strange, but let's solve that in a different PR as that's been that way for a long time. The goal of this PR is to undo the left padding regression that was added, and I think it solves that.

**Review by shawnborton — DISMISSED** [review]

**Comment by cristipaval** [comment]
Thank you @shawnborton !

All on you @aimane-chnaif and @neil-marcellini

**Comment by shawnborton** [comment]
This is what we'd like to see ideally:
image


Basically 20px padding from left and right edges of the frame. 

So maybe we can follow up and have the left arrow use a smaller bounding box. I think we can adjust the hitbox area around it to make sure it's still easily tappable though.

**Comment by neil-marcellini** [comment]
> This is what we'd like to see ideally:

Why don't we fix it now? It doesn't seem that hard.

**Comment by shawnborton** [comment]
That works for me.

**Comment by cristipaval** [comment]
Feedback addressed.

**Comment by shawnborton** [comment]
I quite like it actually!

**Comment by shawnborton** [comment]
But I am curious if the "X" button is wrapped in any kind of bigger box, and how close that is to the right side. 

Same with the ">" carets on the rows - how close are they to the right edge? 

Just want to make sure we get perfect spacing like this:
image

**Comment by cristipaval** [comment]
Sorry, I was ooo yesterday. I'll take care of this one today.

**Comment by cristipaval** [comment]
Hey @shawnborton, please have a look at the screenshots below:
Screenshot 2023-02-17 at 18 42 34
Screenshot 2023-02-17 at 18 42 54
Screenshot 2023-02-17 at 18 46 22

As you can see, all icons are rendered in 40px squares. The thing is that when back button is present, the paddingLeft set on the header is 8px, but the paddingRight is 20px. The same settings are on the right icons on menu items. I think you want me to make them look symmetrical and set paddingRight to 8px when there is an icon, right?

**Comment by shawnborton** [comment]
So I think if we want these to look identical, we'd just keep the icons at 20x20 for the back arrow in the page header, the x in in the page header, as well as the right arrow (or new window icon) in the option row:
image


Now the main concern there is that 20x20 isn't a huge hit area for mobile, but I believe we can extend the hit box to be outside of the 20x20 frame right?

Let me know if that makes sense!

**Comment by cristipaval** [comment]
@shawnborton yes, the icons are 20x20, and they are rendered in 40x40 boxes which handle the tap events.

> The thing is that when back button is present, the paddingLeft set on the header is 8px, but the paddingRight is 20px. The same settings are applied to the right icons on menu items.

These paddings are set related the boxes which surround the icons.

**Comment by shawnborton** [comment]
Yeah, I am suggesting that we remove the 40x40 box but instead use the hitSlop property to give us some extra tappable area: https://reactnative.dev/docs/pressable#hitslop

**Comment by cristipaval** [comment]
oh wow, love it, thanks!

**Comment by cristipaval** [comment]
Looks like it doesn't work and after doing some research it looks like `hitSlop` works only to the extent that it doesn't interfere with other components. In our case, the `Pressable` component is wrapped by `Tooltip` component which has no space left available for the `hitSlop` property to work. I think we should stick with the current implementation which sets 40px size to the Pressable component and set padding outside it. cc @shawnborton

**Comment by shawnborton** [comment]
Hmm yeah, the more I think about this the more I think we don't want to get too wild with a refactor. Otherwise we'd need to change the page titles, option rows, and now push to edit fields. So yeah, maybe we should just stick to what you [have here](https://github.com/Expensify/App/pull/14855#issuecomment-1425233946)

**Comment by cristipaval** [comment]
Had a 1:1 chat with @shawnborton and as he mentioned in the previous comment, we want to merge the PR as it is and then we can take a more holistic look at how the various components all line up with each other.

@aimane-chnaif Could you please review this again?

**Review by neil-marcellini — DISMISSED** [review]
Based on the latest discussion I'm happy with this. It looks like menu items that lead with an icon will be over-indented now. I also noticed that on the security page. It's not a huge deal and we can fix it later I suppose. If this PR is linked as the source of regressions we should make it clear that the over-indent is expected and not a regression.

image
image

**Comment by shawnborton** [comment]
Cool, yeah this is intended. For example, look at the About us page and you will see the same 20px horizontal padding in the view, and the same kind of icon alignment elsewhere: 
image

**Comment by cristipaval** [comment]
On you, @aimane-chnaif

**Comment by neil-marcellini** [comment]
@aimane-chnaif when will you be able to review this?

**Comment by neil-marcellini** [comment]
@aimane-chnaif I think you can review without pulling from main since there are no merge conflicts. You could also pull main into the branch yourself if you want.

**Comment by cristipaval** [comment]
> This should be fixed here? personal details

Yes it might be related as I changed the padding in `MenuItem`
Did you merge the main branch?

**Review by aimane-chnaif — APPROVED** [review]

**Review by neil-marcellini — APPROVED** [review]
Looks great, time to merge!

**Comment by esh-g** [comment]
I think I found a regression. The phone number is not inline with e-mail in contact methods
https://expensify.slack.com/archives/C049HHMV9SM/p1677573548049769

Screenshot 2023-02-28 at 2 32 41 PM

**Comment by neil-marcellini** [comment]
Resolved here https://expensify.slack.com/archives/C049HHMV9SM/p1677577184977659?thread_ts=1677573548.049769&cid=C049HHMV9SM

**Pull request merged**
