### PR TITLE
[No QA] Fix broken ExpensifyText

### PR DESCRIPTION
**Pull request by marcaaron**
### Fixed Issues
https://github.com/Expensify/App/pull/6819#issuecomment-1004482601

### Tests
1. Build web app JS verify it works OK

### QA Steps
No QA

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by Jag96 — APPROVED** [review]

**Comment by parasharrajat** [comment]
@mountiny  Can we please merge this as this is holding some PRs.

**Comment by mountiny** [comment]
@parasharrajat Let me have a look.

**Review by Julesssss — APPROVED** [review]
Checks are passing and Web builds work as expected for me. Holding merge as I believe @mountiny is also reviewing.

**Review by mountiny — APPROVED** [review]
I was mainly looking through internal discussion of the failing deploys yesterday. I think Joe and Francois will look into the problems later today, and the only reason this was not merged last night was probably the E2E tests still running at the EOD.

**Comment by anthony-hull** [comment]
thanks for the fast response 👍

**Pull request merged**
