### PR TITLE
Fix: Long display name not being wrapped

### PR DESCRIPTION
**Pull request by rdjuric**
### Details

Fixes an issue where our display name wasn't respecting the size of it's container. 

### Fixed Issues

#3172 

### Tests

1. Wrote a long display name (first+last name, or email)
2. It was trimmed correctly on the chat and on the IOU details modal
### QA Steps

1. Choose a long display name (first+last name, or email)
2. It should be trimmed correctly on the chat and on the IOU details modal

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/53711423/124042762-f36eee80-d9df-11eb-80f8-b11877de815b.mov

#### Mobile Web

https://user-images.githubusercontent.com/53711423/124042766-f5d14880-d9df-11eb-93fe-4a820a2f9c1f.mp4

#### Desktop

https://user-images.githubusercontent.com/53711423/124042770-f8cc3900-d9df-11eb-96b5-d6a976206a61.mov

#### iOS

https://user-images.githubusercontent.com/53711423/124042779-fbc72980-d9df-11eb-827b-e3633ead5bc4.mp4

#### Android

https://user-images.githubusercontent.com/53711423/124042787-fff34700-d9df-11eb-9338-3a23191d2428.mp4

### CODE REVIEW

**Review by Luke9389 — COMMENTED** [review]
Ok after thinking about this, I'm not sure if this is the best result. It works great, and your testing shows that, but I'm worried that if we ever want to use a `ReportActionItemFragment` with `fragment.type = TEXT` in a different context, we might be bummed about being restricted to one line. 

@marcaaron, do you think this is pre-optimizing? Should we cross that bridge if/when we get to it, or do you think this concern is worth addressing now?

**Comment by marcaaron** [comment]
Yeah I agree @Luke9389. This solution will most likely go out of date as soon as we start adding other kinds of report actions to NewDot. Maybe better to pass this in as a prop to `ReportActionItemFragment` for now and then conditionally set the single line. Then apply it here where we are building the "person" text:

https://github.com/Expensify/Expensify.cash/blob/b330b3da015703a0e3ceacfb3c946bf565019752/src/pages/home/report/ReportActionItemSingle.js#L67-L75

**Comment by rdjuric** [comment]
@Luke9389  @marcaaron It's a good point! We would be restricting too much the use cases of our `TEXT` fragment. 

This commit keeps the `containerStyle` in our `ToolTip` (we still don't want the content of our `TEXT` to go beyond the container), and changes the numberOfLines to be a conditional. 

I thought it might be better to make the `isSingleLine` boolean a property of the fragment object instead of a prop of our `ReportActionItemFragment`, since it's only really relevant for our `TEXT` and doesn't change the behavior of our component.

**Comment by Luke9389** [comment]
OK, these changes look good @rdjuric 👍

Just want to double-check, did you test the most recent commits on each platform? (I know it's a hassle but regressions have been sprouting up a lot lately).

**Comment by rdjuric** [comment]
@Luke9389 
Yes! Updated the PR with videos testing the most recent commit on all platforms.

**Review by Luke9389 — APPROVED** [review]
Awesome! Thanks! 👍

**Comment by parasharrajat** [comment]
Just found an regression https://expensify.slack.com/archives/C01GTK53T8Q/p1625174167354500

**Comment by rdjuric** [comment]
Thanks, @parasharrajat. Looking at it now.

**Comment by roryabraham** [comment]
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.

**Pull request merged**
