### PR TITLE
Added translations for "edited" label in chats

### PR DESCRIPTION
**Pull request by akshayasalvi**
@Julesssss PR for the review.

### Details
Add translation for "(edited)" label

### Fixed Issues

$ #4518 

### Tests
- Tested by switching the language for edited messages
- Tested for Links (HTML content)

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
english-web
web

#### Mobile Web
mobile-web

#### Desktop
desktop

#### iOS
ios

#### Android
android

### CODE REVIEW

**Comment by akshayasalvi** [comment]
@Julesssss  I found that the same label is hardcoded in `BaseHTMLEngineProvider` as well. I've fixed it there too.

But I need a little help here. How should I pass `withLocalizePropTypes` to the `EditRenderer`?

Options:
1. I leave it as per what I've done right now
2. I create a named component and then passed `propTypes`. But in this what would be the other `propTypes` for the renderer component?

**Comment by Julesssss** [comment]
Hi @akshayasalvi, I'm not sure about this. I asked in our open source slack channel here for some help. Please feel free to add your own comments, or to follow along [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1629717401127100)

**Comment by akshayasalvi** [comment]
Hi @Julesssss,
I am unable to access the link and I don't have a slack account. I've found two more functions in `src/libs/translate`. I feel `translateLocal` might help in this case. I've tested and it works. Can we use that?


image

**Comment by Julesssss** [comment]
Hi @akshayasalvi, `transalateLocal` seems to be a valid solution here. I would suggest joining our Slack channel for better communication and updates about new jobs, ect.

**Comment by akshayasalvi** [comment]
Thank you. Then any other changes from my side?

I'll try to join the channel. How do I join it?

**Comment by Julesssss** [comment]
Instructions are [here](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#asking-questions). I'll review the PR now.

**Review by Julesssss — CHANGES_REQUESTED** [review]
One issue: I noticed that the HTML `edited` does not update when changing language. Perhaps this is due to `translateLocal`... If you are stuck here I think we should continue the discussion I started in the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1629717401127100)

Screenshot 2021-08-24 at 12 35 18

**Comment by akshayasalvi** [comment]
Ohh yeah, that's right. It doesn't change.

**Comment by akshayasalvi** [comment]
@Julesssss I have sent the request to join slack.

I've checked and my previous solution of adding `withLocalize` to `EditedRenderer` is working fine. Should we think on those lines?

**Comment by Julesssss** [comment]
> I've checked and my previous solution of adding withLocalize to EditedRenderer is working fine.

Yeah, I think that's fine. I was a bit worried about the performance hit from adding a new subscription to a Commonly used component, but [apparently it is fine](https://expensify.slack.com/archives/C01GTK53T8Q/p1629901935268700?thread_ts=1629717401.127100&cid=C01GTK53T8Q) 👍

**Comment by akshayasalvi** [comment]
PR updated

**Review by Julesssss — DISMISSED** [review]
LGTM, just need to make the fix @aldo-expensify suggested

**Review by aldo-expensify — APPROVED** [review]
Looks good to me, I leave it to you @Julesssss

**Review by Julesssss — APPROVED** [review]

**Pull request merged**
