### PR TITLE
Check for app updates every 8 hours

### PR DESCRIPTION
**Pull request by neil-marcellini**
### Details

Rather than checking for app updates once per hour after the initial check, check once every 8 hours.
### Fixed Issues

$ https://github.com/Expensify/App/issues/7643

### Tests

1. Comment out [this line](https://github.com/Expensify/App/blob/ed4886dc808bdad8c539fc02d4190a6e77211811/desktop/main.js#L332) so that you get update notifications on your dev environment
2. `npm run desktop`
3. Sign in to the local desktop app
4. Sign in to the production desktop app
5. Keep both apps open for 8 hours.
6. When update notifications pop up for the desktop app hourly, make sure they they don't pop up for the local app.

- [ ] Verify that no errors appear in the JS console

### QA Steps

1. Sign in to the desktop staging app
2.  Sign in to the production desktop app
3. Keep both apps open for 8 hours.
4. When update notifications pop up for the desktop app hourly, make sure they they don't pop up for the staging version.

- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by neil-marcellini** [comment]
I haven't actually tested this yet, but I'm pretty sure it will work since it's a simple change. Tomorrow I will test this and add screenshots to be proper.

**Review by mountiny — APPROVED** [review]
I am not sure how much value testing this change thoroughly would bring. The logic is pretty simple here. LGTM!

**Comment by mountiny** [comment]
Oh, that is a good point, I have overlooked that during a review @neil-marcellini

**Comment by neil-marcellini** [comment]
What would be the benefit to checking more often, but notifying only every 8 hours?

**Comment by flodnv** [comment]
To clarify, does the app check on startup?

**Comment by neil-marcellini** [comment]
Yes it checks on startup. When [init is called](https://github.com/Expensify/App/blob/8c5b412466beaadc27a28a08cbf584cae7286529/src/libs/checkForUpdates.js#L14) on the electron updater it checks for updates [here](https://github.com/Expensify/App/blob/2cf52100ad2d341c7e1dcc2e246461fc41d30833/desktop/main.js#L110). The behavior is similar for web.

**Comment by flodnv** [comment]
I think it's probably fine although it feels a bit weird to knowingly introduce an "improvement" that means that most of our user base will be on an older version for several hours at a time. Perhaps it's ok though.

**Pull request merged**
