### PR TITLE
[No QA] Apply engineering label to deploy blockers, not demolition

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Coming from [this (long) thread](https://expensify.slack.com/archives/C011W8BJ9L6/p1620738367042800).

### Fixed Issues
n/a

### Tests
1. Merge this PR.
2. Create a new issue labelled `DeployBlockerCash`.
3. Verify that the following labels are automatically applied: `Hourly`, `Engineering`.
4. Verify that (allowing for a few minutes' delay), an engineer is auto-assigned the issue.

### QA Steps
None.

### Tested On

Live-testing only 🤪

### CODE REVIEW

**Review by iwiznia — DISMISSED** [review]

**Review by rafecolton — DISMISSED** [review]

**Comment by roryabraham** [comment]
Sorry, I added another quick fix in this PR to fix [this failed workflow run](https://github.com/Expensify/Expensify.cash/actions/runs/851151025)

**Review by rafecolton — APPROVED** [review]

**Review by Luke9389 — APPROVED** [review]
love it

**Comment by roryabraham** [comment]
Okay, going to merge this and test it out

**Comment by roryabraham** [comment]
Okay, this worked! I'm going to adjust the Slack comment so it doesn't ping everyone in the channel for a deploy blocker

**Pull request merged**
