### PR TITLE
Add edit icon

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/5326

### Tests | QA Steps
1. Open NewDot on Web or Desktop.
2. Go to any existing Workspace from the Settings page.
3. Edit icon should be visible on the LeftSidebar over Workspace Avatar.
4. Clicking should take you to edit.
5. Hovering on the pencil icon will show a tooltip saying `Edit workspace`.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### Screenshots

image

### CODE REVIEW

**Comment by parasharrajat** [comment]
@mountiny I have added a tooltip as well. This PR is ready.

Adding a tooltip to this icon was not straightforward and it was left out in the issue which was supposed to add that. (please read till the end https://github.com/Expensify/App/issues/4499#issuecomment-905409385 to know more).

I would to request to submit another PR to add tooltips to other parts of the app that were left deliberately due to the Tooltip component's limitation. I have added the code to uplift the limitation which is additional work for this job.

It would be a way of getting compensation for the additional work as well as fixing that problem and not just a bonus.

Let me know what do you think about this?

**Comment by mountiny** [comment]
@parasharrajat I like that idea. To recap, you have fixed the problem with positioning tooltips over elements which are absolutely positioned? The new issue would be to add the tooltips to all the elements left out due to this limitation?

If so, feel free to create a new issue for this and propose a solution there. You can ping me here and I can triage it as I already have a context for it. 

Would you consider including this idea from Shawn in your new issue too https://github.com/Expensify/App/issues/4499#issuecomment-900413457? Or do you reckon that would be more substantial/complicated change?

**Comment by parasharrajat** [comment]
You are correct with first paragraph.

I see, Shawn's Idea is amazing. I would love to invest some time into it. I have a generic plan on How we can do that  Let me try that and see if that works.

**Review by mountiny — APPROVED** [review]
Great job on this one! Code looks good to me 🚀

**Pull request merged**
