### PR TITLE
Fix multiple open report call when report screen is mounted

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

We call OpenReport in both ReportScreen and ReportActionsView. This PR fix it.

### Fixed Issues

$ https://github.com/Expensify/App/issues/39673
PROPOSAL: https://github.com/Expensify/App/issues/39673#issuecomment-2041127917

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

Web/Desktop
1. Open developer tools
2. Switch to the Network tab
3. Sign out and sign in
4. Wait until the app load completes
5. In the network tab, verify there is only 1 OpenReport call

Android/iOS/mWeb
1. Open developer tools (not available in Android/iOS)
2. Switch to the Network tab
3. Open any report
4. In the network tab, verify there is only 1 OpenReport call
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/50919443/ce20e7b8-0c3f-4a91-b6a9-64864d35a5b5

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/50919443/b88c02a4-b2d4-4ebe-bb46-b296bf174698

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/50919443/02303f74-4283-4ba7-a0fb-c92105c31281

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/50919443/a027758b-a8ca-46a0-b2a1-fba1236499fa

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/50919443/90b3119a-d3a1-4e60-8792-708896565261

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/50919443/8f9ca721-e1e0-4965-aaf7-3ee64ac9a1d9

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
On a small screen, logging in won't call OpenReport since there is no report screen mounted which is different with a large screen. So, I only test opening some reports and verify the OpenReport call is still only called once.

> I still saw some reports not making OpenReport API call with the mentioned changes 

@abdulrahuman5196 can you tell me how to reproduce this? so I can take a look. Thanks!

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
> On a small screen, logging in won't call OpenReport since there is no report screen mounted which is different with a large screen. So, I only test opening some reports and verify the OpenReport call is still only called once.
> 
> > I still saw some reports not making OpenReport API call with the mentioned changes
> 
> @abdulrahuman5196 can you tell me how to reproduce this? so I can take a look. Thanks!

I didn't see this issue yesterday. Will again and approve if no other issues.

**Comment by abdulrahuman5196** [comment]
https://github.com/Expensify/App/assets/46707890/84d0192f-eb9b-4c22-b01b-aaf75ec9ba61


For some reports I am still seeing OpenReport being called twice after fresh signin. I suspect reports with partial skeleton loading is still calling OpenReport twice. Could you check on this @bernhardoj ?

**Comment by bernhardoj** [comment]
Looks like it's coming from this temporary code
https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/pages/home/report/ReportActionsView.tsx#L394-L410

From your video, I can see at least 2 satisfied conditions,
`newestReportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.REPORT_PREVIEW`
and
`!hasCreatedAction`

I think we can ignore it for now since it's a temporary code and the author already commented that it will be removed in the future.

**Comment by abdulrahuman5196** [comment]
> Looks like it's coming from this temporary code
> 
> https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/pages/home/report/ReportActionsView.tsx#L394-L410
> 
> From your video, I can see at least 2 satisfied conditions, `newestReportAction?.actionName === CONST.REPORT.ACTIONS.TYPE.REPORT_PREVIEW` and `!hasCreatedAction`
> 
> I think we can ignore it for now since it's a temporary code and the author already commented that it will be removed in the future.
> 
> _Btw, idk how to reproduce it_

Got it. Verified and seems its the cause.

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours. @flodnv 

🎀 👀 🎀
C+ Reviewed

**Review by flodnv — APPROVED** [review]

**Comment by kbecciv** [comment]
This PR is failing because of issue https://github.com/Expensify/App/issues/39673

The issue is tested in: Web and Desktop


https://github.com/Expensify/App/assets/93399543/ba55297d-ac58-4a7a-8895-090262fc7262

https://github.com/Expensify/App/assets/93399543/bee69c89-3eb7-4f3a-8177-7c096940776f

**Pull request merged**
