### PR TITLE
[No QA] Fix missing app icon for iPad

### PR DESCRIPTION
**Pull request by shawnborton**
@roryabraham 

### Details
This provides the missing iPad icon.

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes GH_LINK

### Tests
N/A

### QA Steps
image

### CODE REVIEW

**Comment by roryabraham** [comment]
Hey @AndrewGable, this PR is meant to fix [this deploy failure](https://github.com/Expensify/Expensify.cash/runs/2446268794?check_suite_focus=true), do you have any experience with this type of failure / any guidance on how to test locally?

**Review by joelbettner — APPROVED** [review]

**Review by roryabraham — APPROVED** [review]
Seems fine to me, and we can always just try it and see if it fails again 🙃

**Comment by roryabraham** [comment]
Okay, let's just try this and hope it works 🤞🏼

**Comment by AndrewGable** [comment]
@shawnborton - I am not sure the `@3x` is required. It's throwing a warning now saying it's unassigned/unused. Would you mind making a follow up PR? Thanks!

Screen Shot 2021-04-27 at 11 20 28 AM

**Comment by shawnborton** [comment]
Can do. The @3x image was already there so we would have been getting this warning for quite some time now is my guess.

**Comment by AndrewGable** [comment]
Looks like it deployed OK! Main error was fixed 🎉

**Comment by roryabraham** [comment]
@AndrewGable great news! We found another race condition 😭😭😭🤮

Here's what I _think_ happened:

1) The `StagingDeployCash` was locked, then immediately after this PR was merged
2) The `StagingDeployCash` deploy (`1.0.32-0`) began first, but included the changes from this PR (I think that's good, because it got to keep the last-minute changes from this PR). This happened because this PR was merged to main while the action's runner was starting up and it hadn't checked out the repo yet.
3) The `preDeploy` from this workflow then found that the `StagingDeployCash` was locked, so it skipped the deploy (`1.0.31-5`). Also good.
4) However, because the `StagingDeployCash` was locked, it commented on the PR saying that it wasn't going to be deployed, but it was already in the process of being deployed in `1.0.32-0`.

Ultimately nothing too bad happened here, it's just that this comment was a lie:

image

**Comment by AndrewGable** [comment]
Will your future version PR fix this one?

**Comment by roryabraham** [comment]
I don't think so actually.

**Pull request merged**
