### PR TITLE
Fix: portion of text shown when changing IOU value

### PR DESCRIPTION
**Pull request by neg-0**
### Details

The change made from issue https://github.com/Expensify/App/issues/8158 added an additional width of 2 pixels to the Text component used to autoGrow the RNTextInput in BaseTextInput. The value of RNTextInput is changed prior to the Text component resizing, which shows a partial number. The proposed change is to remove the extra 2 pixels applied to the Text component that's being used to implement autoGrow in the BaseInputText component. The original intent of this padding was to fix issue https://github.com/Expensify/App/issues/8158 but it seems that the root cause has been resolved and the extra padding is no longer necessary.

### Fixed Issues

$ https://github.com/Expensify/App/issues/26628
PROPOSAL: https://github.com/Expensify/App/issues/26628#issuecomment-1718308555

### Tests

1. Click the FAB and select Request Money
2. Select Manual
3. Type any amount
4. Notice that as the amount changes, there is no rendering error near the final number

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

1. Click the FAB and select Request Money
2. Select Manual
3. Type any amount
4. Notice that as the amount changes, there is no rendering error near the final number

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/1709513/ed1bbebf-971a-45f1-a4a8-630932a54a58

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/1709513/e08bb162-6698-4580-9e45-5cbc33656702

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/1709513/0c627806-07fe-425a-9de4-c2e72c3c77f3

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/1709513/c4e7f014-4304-483a-9f35-76333b8013e1

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/1709513/062072d9-14fb-4d41-a8ce-006a1f4016b6

</details>

<details>
<summary>Android</summary>

[Android.webm](https://github.com/Expensify/App/assets/1709513/b24e2e68-8708-4e06-a87f-ed30968c98e6)

</details>

### CODE REVIEW

**Comment by neg-0** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by neg-0** [comment]
@ArekChr I accidentally included a merge with this PR. If that's going to cause any issues please let me know and I will resubmit. I apologize for that!

**Comment by ArekChr** [comment]
@neg-0 I found regression was found during testing. Some wider numbers are truncated, e.g. 4 or 8, 9. Could you fix that? Thanks!

Zrzut ekranu 2023-09-18 o 11 18 37

**Comment by neg-0** [comment]
@ArekChr Good catch. It seems like the mWeb and Native versions are handling the text sizes differently. This was in fact what #8158 aimed to fix. I'm looking into a solution now.

**Comment by neg-0** [comment]
@ArekChr Ok, I got a working solution!



The reason why portions of numbers are being cut off is due to the layout width of the Text component not accounting for a cursor or any potential changes in the value. It only outputs the width of the current text value. The previous change added 2 pixels to prevent cutting off numbers due to the cursor. However, it does not give enough room for an additional number in the event that the value changes. This "squeeze" is what causes the text to shift to the left upon adding a new number because the value tries to justify itself to always show the cursor (which is typically on the right side of the screen).

First change: I reimplemented the change that I removed in ```BaseTextInput.js```, except I actually changed the pixel count from 2 to 32. This gives all text changes adequate room to breathe.

Screenshot 2023-09-19 at 12 10 02 AM

With this change in place, the text will now overflow to the right upon change instead of shifting everything to the left. I believe this is much more appealing.

https://github.com/Expensify/App/assets/1709513/56392058-7b77-45e6-9b9a-16c4b747dadd

https://github.com/Expensify/App/assets/1709513/6365fb69-6211-4081-86ef-9045e9be8873

Now, this extra width shifts everything to the left because the centering style tries to center the entire component hierarchy. To counteract this, in the ```styles.js``` file I added a 32px margin to the left side of the currency icon. This adds the proper amount of spacing and properly centers the components.

Screenshot 2023-09-19 at 12 22 53 AM

This results in proper centering of the currency symbol and amount.

https://github.com/Expensify/App/assets/1709513/12f22745-6281-46bf-86af-cfaadb1c258b

With the changes, I don't see any rendering issues in other parts of the app that use ```BaseInputText.js``` and I've pushed this new commit. Please review and let me know if you see any further issues. Thank you

**Comment by ArekChr** [comment]
@neg-0 These extra shifts happen on the web, iOS, and Android when typing numbers.
on iOS, it looks like it happens randomly
on Android, it occurs like on every text change 
The web is more performant, but this is still noticeable. Looks like any number makes this shift.


https://github.com/Expensify/App/assets/24796318/ffe54b34-606e-47b6-a0da-0d96636f896c

**Comment by neg-0** [comment]
@ArekChr Yes, this is due to the nature of resizing the width of RNTextInput using the onLayout of another component. This is the issue of synchronization between the two elements that I mentioned in the initial posting. This delay was previously masked by the smaller width of the RNTextInput driven by the onLayout function of Text. However, this is what introduced the issues in #26628. React-native does not support automatic sizing of TextInput components so this additional Text component was created to render the text off-screen and get its width accordingly. There's a slight delay with this process which results in the popping you see there.

I'm looking into additional refactoring of the ```BaseInputText.js``` component to mitigate this, but without substantial changes that delay will always be present. Please advise how you'd like to move forward.

Thank you!

**Comment by neg-0** [comment]
I'm currently working on a refactor for the BaseTextInput component that should resolve this issue completely.

**Comment by neg-0** [comment]
@ArekChr I was not able to refactor BaseTextInput in a way that fixed the synchronization issue.

I propose that we only add the additional 2-pixel width to Safari browsers. This will properly account for the cursor width issue we saw before that cuts off the left side of text on Safari browsers. It will also prevent the portion of text showing when repeatedly typing the same number, fixing issue #26628

Here is the modified code:
Screenshot 2023-09-20 at 11 14 59 PM

<details>
<summary>Result on MacOS Chrome (with 0 additional width):</summary>
https://github.com/Expensify/App/assets/1709513/ba41479e-0222-416d-823a-986b7921b065
</details>

<details>
<summary>Result on MacOS Safari (with 2 additional width):</summary>
https://github.com/Expensify/App/assets/1709513/3f6c3534-23c2-4171-b578-d4005048e8ca
</details>

<details>
<summary>Result on iOS Safari (with 2 additional width):</summary>
https://github.com/Expensify/App/assets/1709513/0670d42d-32c0-4076-9e14-ad634469c712
</details>

<details>
<summary>Result on Desktop (with 0 additional width):</summary>
https://github.com/Expensify/App/assets/1709513/63af9184-5cdc-438f-b519-d733a1793e80
</details>

<details>
<summary>Result on iOS Native (with 0 additional width):</summary>
https://github.com/Expensify/App/assets/1709513/419bc293-b728-4015-a124-1dad1cb893a3
</details>

<details>
<summary>Result on Android Native (with 0 additional width):</summary>
https://github.com/Expensify/App/assets/1709513/fd4da897-a902-4655-828c-1f452e4d1aa3
</details>

**Comment by ArekChr** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



https://github.com/Expensify/App/assets/24796318/b18983c6-0dd7-410a-a83c-41523bea15f3


</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://github.com/Expensify/App/assets/24796318/d7104164-11bc-43b7-85b1-ea6ab480137f


</details>

<details>
<summary>Mobile Web - Safari</summary>



https://github.com/Expensify/App/assets/24796318/971d5455-0a13-4c71-b2ca-7c29c823a62d


</details>

<details>
<summary>Desktop</summary>



https://github.com/Expensify/App/assets/24796318/3e4a3f42-6b96-47c5-99cd-cf43d7570f89


</details>

<details>
<summary>iOS</summary>



https://github.com/Expensify/App/assets/24796318/c7305758-a706-4638-84d4-381ef974dbd4


</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/24796318/274b5539-1c26-46e5-b81a-0752b651e1a6




</details>

**Comment by ArekChr** [comment]
@neg-0 It works for me, I think in future, we should consider refactoring, and simplifying this input by removing width and height logic in onLayout event.

**Review by ArekChr — APPROVED** [review]

**Comment by neg-0** [comment]
@ArekChr Thanks for the review. Agreed. It's too bad react-native doesn't support this out of the box. I tried several methods of refactoring to make this look cleaner but all had unwanted side effects.

**Review by mountiny — DISMISSED** [review]
Not great to see the browser specific code but I agree this is a good UX improvement to pursue so going ahead

**Comment by mountiny** [comment]
Lint is failing @neg-0

**Comment by neg-0** [comment]
@mountiny Sorry about that. Ran Prettier and committed the code diff.

**Comment by neg-0** [comment]
@ArekChr @mountiny can we please rerun the pipeline? Thank you.

**Review by mountiny — APPROVED** [review]
:shipit:

**Pull request merged**
