### PR TITLE
[HOLD E/E #311912] Fix/25680: Assignee does not show on Confirm task page

### PR DESCRIPTION
**Pull request by DylanDylann**
### Details

Assignee does not show on Confirm task page because we don't have their personal details yet
### Fixed Issues
 
$ https://github.com/Expensify/App/issues/25680
PROPOSAL: https://github.com/Expensify/App/issues/25680#issuecomment-1688477898

### Tests

1. Click on FAB icon and select new chat
2. Enter email and create a new chat
3. Click on FAB icon and select assign a task
4. Enter title and click on Next button
5. Click on assignee and search for user with whom you created new chat
6. Select that user
7. Verify that assignee should show on Confirm task page

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Click on FAB icon and select new chat
2. Enter email and create a new chat
3. Click on FAB icon and select assign a task
4. Enter title and click on Next button
5. Click on assignee and search for user with whom you created new chat
6. Select that user
7. Verify that assignee should show on Confirm task page

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

[Screencast from 23-08-2023 18:23:29.webm](https://github.com/Expensify/App/assets/141406735/5e9e5199-5eea-4aff-9fa8-dfc211d60324)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/141406735/3a37d41c-b65f-46ca-94bd-3e8bb467054c

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/141406735/8dad80b0-011a-46ba-85ae-97487f5901ed

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/141406735/64d75778-d6fd-450a-ab84-e964f12664fa

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/141406735/78391e8e-374d-4f9b-a7f2-18bf4d2a4eda

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by DylanDylann** [comment]
@rushatgabhane updated! Please help check my PR

**Comment by DylanDylann** [comment]
Screenshot 2023-08-24 at 17 35 19

@rushatgabhane @mountiny Now we can't search for new users in the assignee modal. If it is intentional, the original issue couldn't reproduce

**Comment by DylanDylann** [comment]
@rushatgabhane  please help review my PR, thanks!

**Comment by DylanDylann** [comment]
@rushatgabhane merged latest main into my branch

**Comment by DylanDylann** [comment]
> @DylanDylann for some reason im stuck on the report loading screen when I run this branch. Do you experience the same?
> 
> image

no. It is fine from my side

**Comment by mountiny** [comment]
@DylanDylann I think we can revert that cc @marcaaron @thienlnam 

@DylanDylann Will your solution work even after signing out and signing back in when the other user exists but they have display name set (in that case the personal details returned wont have login/email)

**Comment by mountiny** [comment]
> Click on assignee and search for user with whom you created new chat

this user, do they have display name set up?

**Comment by mountiny** [comment]
can you try with the dispaly name set, then you wont have the email locally available

**Comment by DylanDylann** [comment]
> can you try with the dispaly name set, then you wont have the email locally available

here is my screen record, folow these steps: 
1. Set display name for user B
2. Login with user A
3. Click on FAB icon and select new chat
4. Enter email and create a new chat
5. Click on FAB icon and select assign a task
6. Enter title and click on Next button
7. Click on assignee and search for user with whom you created new chat
8. Select that user
9. Verify that assignee should show on Confirm task page
[Screencast from 26-08-2023 08:04:05.webm](https://github.com/Expensify/App/assets/141406735/42508dd2-fa5a-4461-a386-67f9e628f02d)

**Comment by DylanDylann** [comment]
@mountiny Currently it works properly on the main branch. I don't know what change makes it work

**Comment by DylanDylann** [comment]
@mountiny Bump 
cc @rushatgabhane

**Comment by mountiny** [comment]
@rushatgabhane could you come back to this one please?

**Comment by DylanDylann** [comment]
> @DylanDylann [#25806 (comment)](https://github.com/Expensify/App/pull/25806#issuecomment-1694011588) well it seems like creating a new user through this flow is not supported in BE if I understood this correctly, @rushatgabhane to confirm

@rushatgabhane please help confirm it. Thanks

**Comment by DylanDylann** [comment]
@mountiny  Bump
cc @rushatgabhane

**Comment by mountiny** [comment]
Sorry i am mainly busy with the deliverables for the conferences now, we will come back to this later as it seems a bit more intertwined

**Comment by thienlnam** [comment]
This should still allow optimistic assignees that you haven't chatted with before, but will still fail on contacts that don't exist at all - this is kind of how it was before which is fine

**Comment by DylanDylann** [comment]
@thienlnam @mountiny @rushatgabhane So should we revert [this PR](https://github.com/Expensify/App/pull/25806#issuecomment-1694011588) ?

**Comment by marcaaron** [comment]
Let's verify whether reverting it reintroduces the deploy blocker it was created to resolve?

**Comment by marcaaron** [comment]
>this is kind of how it was before which is fine

Yes, fine, except the part about the app crashing when you try to do it and they don't exist - that was introduced and is not fine 😄

**Comment by DylanDylann** [comment]
@mountiny @marcaaron @thienlnam  [This PR](https://github.com/Expensify/App/pull/25806), we don't allow users to assign to assignees that you haven't chatted with before and don't exist at all. But as the comment from @thienlnam 

> This should still allow optimistic assignees that you haven't chatted with before, but will still fail on contacts that don't exist at all - this is kind of how it was before which is fine

we only don't allow users to assign to assignees who don't exist at all.

So, I think we should revert [this PR](https://github.com/Expensify/App/pull/25806) and create another PR to fix [this issue](https://github.com/Expensify/App/issues/25688) as the correct expected.

Please correct me if I am wrong

**Comment by mountiny** [comment]
Ok, yeah I think the expected behaviour and the easiest for now until this is updated across stack is just to allow assinging people you have in the personalDetails

@thienlnam @marcaaron do you agree?

**Comment by thienlnam** [comment]
> Yes, fine, except the part about the app crashing when you try to do it and they don't exist - that was introduced and is not fine 😄

Yeah indeed, though a recent PR introduced that regression not the original PR that allowed this
I'm kind of agreeing with Vit here on doing nothing and closing this PR here as it's not really a priority. 

I have a follow up issue to handle assignees that don't exist yet in the BE. We can just address this after that follow up issue is done

**Comment by marcaaron** [comment]
>we should revert https://github.com/Expensify/App/pull/25806 and create another PR to fix https://github.com/Expensify/App/issues/25688 as the correct expected

fwiw, the order of operations here sounds wrong. The change we made was small so just "revert" and fix it in the same PR.

**Comment by DylanDylann** [comment]
@thienlnam  @mountiny 
> I have a follow up issue to handle assignees that don't exist yet in the BE. We can just address this after that follow up issue is done

So we should hold this PR until the BE change is done

**Comment by mountiny** [comment]
@thienlnam could you put this on hold for the backend PR you got in works?

**Pull request closed without merging**
