### PR TITLE
chore(bump-e-common): Updated expensify-common ref hash

### LINKED ISSUE #4229: Hyperlink markdown doesn't work if the ] is preceded by an (
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a conversation
2. Send this message 
` [Yo (click here to see a cool cat)](https://c8.alamy.com/compes/ha11pc/cookie-cat-con-sombrero-de-cowboy-y-sun-glass-ha11pc.jpg)`
3. Check the message in the history

## Expected Result:
The link should be hyperlinked even if there is a ) before the ].

## Actual Result:
Link is not hyperlinked. Checked on Github and it gets hyperlinked correctly so this seems like an issue. 
**Important**: Same happens for other punctuation marks. 

Example 
[Yo (click here to see a cool cat)](https://c8.alamy.com/compes/ha11pc/cookie-cat-con-sombrero-de-cowboy-y-sun-glass-ha11pc.jpg)

## Workaround:
User can send the link without the formatting

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

**Version Number:** 1.0.80-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

____ 
From @mallenexpensify https://expensify.slack.com/archives/C01GTK53T8Q/p1627271189249400 
> Markdown doesn't work when ] is preceded by )

### PR DESCRIPTION
**Pull request by mananjadhav**
@AndrewGable Can you review this PR?

### Details
- Merges hyperlink changes from expensify-common to the App

### Fixed Issues

$ Fixes [App/4229](https://github.com/Expensify/App/issues/4229)

### QA Steps

1. Type `[Yo (click here to see a cool cat)](https://c8.alamy.com/compes/ha11pc/cookie-cat-con-sombrero-de-cowboy-y-sun-glass-ha11pc.jpg)` (without `)
2. Verify it hyperlinks correctly

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/3069065/127357607-b09cc0f1-6e6c-4b0d-9d1a-6e53df0e3eec.mp4

#### Mobile Web
https://user-images.githubusercontent.com/3069065/127372250-daec48b7-855b-4965-b11b-7cffddc227cf.mp4

#### Desktop
https://user-images.githubusercontent.com/3069065/127357442-98d02450-cdf1-45d1-8cea-0bf6f136d99b.mp4

#### iOS
https://user-images.githubusercontent.com/3069065/127385748-6e297267-fa5c-47e2-8851-5b0fa654c545.mp4

#### Android
https://user-images.githubusercontent.com/3069065/127372048-5dbce2a9-172b-4252-98d2-6f0945f65ffe.mp4

### CODE REVIEW

**Comment by mananjadhav** [comment]
@AndrewGable  Can you review this PR. Hopefully, this should pass all the checks.

**Comment by AndrewGable** [comment]
So unfortunately I am seeing a weird bug on this PR now, it's only running one check from my end. Not the tests & lint 😞

**Comment by mananjadhav** [comment]
Ohh just saw the count! Something wrong at my end?

**Comment by mananjadhav** [comment]
Github actions not working. Closing this PR.

**Comment by mananjadhav** [comment]
Received a notification from GitHub for this. Temp error from github.

image

**Pull request closed without merging**
