### PR TITLE
Fix Search Page Slow Issue (CMD+K) - 2nd, 3rd solution

### PR DESCRIPTION
**Pull request by Looxor**
### Details

1. src/pages/SearchPage.js
- added conditional render using didScreenTransitionEnd

### Fixed Issues

$ https://github.com/Expensify/Expensify.cash/issues/3601

### Tests

1. While using e.cash use the cmd+k command
2. Type on the search field

### QA Steps

1. While using e.cash use the cmd+k command
2. Type on the search field

### Tested On

- [ ] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Desktop

https://user-images.githubusercontent.com/1319853/123469737-bb3c6a00-d5f3-11eb-8c55-bd98276cd43d.mp4

#### Android

I have read the CLA Document and I hereby sign the CLA.

### CODE REVIEW

**Comment by nickmurray47** [comment]
@Looxor I added a Work In Progress label until we get a demo account that we can test this PR with and so we don't merge this PR until we've fully tested yet.

**Comment by timszot** [comment]
@nickmurray47 @Looxor I tested this with my account! Here's a summary of what I found.

I used the dev tools performance profiler to test the `CMD +K` shortcut followed by typing a name (I used `tim` since that has multiple results in my account). I didn't notice any regression of performance when using this branch as a build source. I didn't notice an increase in any performance either... but I think this is safe to merge.

**Review by timszot — DISMISSED** [review]

**Comment by nickmurray47** [comment]
Ok, I still think we should hold off on merging until we can definitely say that the PR does increase performance for the search page. @Looxor I also notice that this PR is pretty different from your original proposal of potentially cutting down on the number of renders. Can you include some details on why this change would improve performance?

I'm wondering for testing if we can include some kind of performance metric to quantify this. I will also work on getting you your own testing account. Thoughts?

**Comment by Looxor** [comment]
@nickmurray47, Thank you for your attention.

Regarding multiple rendering, I think that it's better to decrease multiple rendering, but as you mentioned before, it makes some regression issues. At the moment, I realized that it is related to too many components, and I tried to find other ways.

Regarding didScreenTransitionEnd, I found a more effective way to display an ActivityIndicator.
It was more effective to use the conditional rendering than using "visible" variable because a former way does not require to render any blank component if not necessary.

Thank you,

**Comment by nickmurray47** [comment]
@Looxor I also saw you posted in our open-source channel https://expensify.slack.com/archives/C01GTK53T8Q/p1625851107062100. Did you still need help mocking additional users?

**Comment by Looxor** [comment]
@nickmurray47 ,
And I want to continue to integrate 1st solution of mine, but stopped due to the regression problem.
Can you please provide me a demo user (and password) so that I can check the regression problem as you mentioned?

**Comment by Looxor** [comment]
@nickmurray47 , Yes, I still need them.

**Comment by nickmurray47** [comment]
Ok, @isagoico do you have a production QA account (expensifail) with a ton of chats on it that you could lend to an external contributor?

**Comment by isagoico** [comment]
@nickmurray47 Sure! You can try with `applausetester+ig@applause.expensifail.com / 123456Hola` and let me know if that one has enough chats, If it doesn't have enough I can try and find another one.

**Comment by nickmurray47** [comment]
Thank you @isagoico!

**Comment by Looxor** [comment]
@isagoico , Thank you so much. It works well.

**Comment by Looxor** [comment]
Regarding 3rd solution,

I just pushed the 3rd solution.

Looking up a component FullScreenLoadingIndicator, I noticed that there is a difference between "adjusting with height:100%" and "adjusting with {top: 0, bottom: 0}".

But, I also agree on that "adjusting with {left: 0, right: 0, top: 0, bottom: 0}" is a better solution than "width/height: 100%".
ex: https://codepen.io/wizardzines/pen/abNXEVy
article: https://stackoverflow.com/questions/15972192/css-positioning-to-fill-container-width-vs-left-right

So, I left the original code and put some additional code for our CMD+K case.
And I believe that the solution is working fast than before.

@timszot , @nickmurray47 ,
Could you all please check this carefully?

Thank you.

**Comment by parasharrajat** [comment]
Leaving my thoughts here. Looking at the changes here, I am uncertain of any performance gain here. Once again, I would request you to pull Marc in for review as he is mostly looking into performance-related issues.

**Comment by Looxor** [comment]
> Leaving my thoughts here. Looking at the changes, I am uncertain of any performance gain here. I would request you to pull Marc in for review as he is mostly looking into performance-related issues.

@parasharrajat 

I made 2 screenshots for you to show the difference.


https://user-images.githubusercontent.com/1319853/125639667-4d551937-bd6f-48f9-a2a9-256c46273e9f.mp4


https://user-images.githubusercontent.com/1319853/125639683-e905431c-2088-431b-bd46-e9f979cdd38c.mp4

**Comment by parasharrajat** [comment]
It seems it more of a UI issue rather then performance.

**Comment by Looxor** [comment]
Hi @isagoico, 
At this point, can you please check this solution?

> It seems it more of a UI issue rather than a performance.
> Edit:
> So this suggests that the Absolute positioned element is slower than the flex equivalent, though all of this is handled by the CSS engine. Sorry, but it's hard to believe without any proof. But there is something really going on.
> **But if it makes a noticeable impact on affected users who first raised this issue then 👍**

**Comment by Looxor** [comment]
Hi @isagoico, 
At this point, can you please check this solution?

> It seems it more of a UI issue rather than a performance.
> Edit:
> So this suggests that the Absolute positioned element is slower than the flex equivalent, though all of this is handled by the CSS engine. Sorry, but it's hard to believe without any proof. But there is something really going on.
> **But if it makes a noticeable impact on affected users who first raised this issue then 👍**

**Comment by Looxor** [comment]
> It seems it more of a UI issue rather than a performance.
> 
> Edit:
> So this suggests that the Absolute positioned element is slower than the flex equivalent, though all of this is handled by the CSS engine. Sorry, but it's hard to believe without any proof. But there is something really going on.
> 
> But if it makes a noticeable impact on affected users who first raised this issue then 👍

@parasharrajat , 
Yes, that's right. The slaggy and slow transition of the search page, is due to UI issue than the performance-related issue.
So, I focused on UI issue than the performance issue.

**Comment by parasharrajat** [comment]
Sorry, @Looxor I currently don't have the bandwidth to test it.

**Comment by Looxor** [comment]
No problem. @parasharrajat , Thank you for your time.

**Comment by timszot** [comment]
@Looxor I did some more testing for you.
My performance tests were hitting `CMD +K`, once loaded type in `test` in the search field and wait for it to load the results.
Built from `main`:
image

Built from the proposed branch:
image

These proposed changes to cut down on performance costs. @marcaaron @nickmurray47 I would like your thoughts here as well.

**Comment by marcaaron** [comment]
>I don't see a noticeable improvement when using CMD+K on my production account

FWIW, it might be valuable to test locally on a production build. There is a lot of difference between dev and production JS. More info here -> https://reactjs.org/docs/optimizing-performance.html#use-the-production-build

**Comment by timszot** [comment]
>FWIW, it might be valuable to test locally on a production build.

Sorry if this wasn't clear, all these tests were done with builds from dev, pointed to production.

**Comment by marcaaron** [comment]
Interesting. That seems to suggest that we are experiencing some kind of local dev API lag, but this PR is not touching any APIs. Is the speed difference consistently reproducible?

**Comment by timszot** [comment]
> Is the speed difference consistently reproducible?

The actual time that it take to load the search and then populate the changes when you type in a value did not change from what I can tell. The only gains I saw was the rendering and scripting speeds. It was consistently faster.

**Comment by marcaaron** [comment]
Sorry I'm not following why these changes would make anything go faster. Can someone summarize?

**Comment by nickmurray47** [comment]
@timszot Thanks for the writeup and testing.

My understanding of why rendering would go faster is because instead of passing the `didScreenTransitionEnd` prop to the `FullScreenLoadingIndicator` component we only conditionally render it if true which means we no longer render a blank `FullScreenLoadingIndicator`.

**Comment by marcaaron** [comment]
>which means we no longer render a blank FullScreenLoadingIndicator

What impact does this have on performance? This is the original proposal accepted...

https://github.com/Expensify/Expensify.cash/issues/3601#issuecomment-867409116

How did we end up with this PR ?

**Comment by nickmurray47** [comment]
> How did we end up with this PR?

I asked the same thing [above](https://github.com/Expensify/Expensify.cash/pull/3980#issuecomment-879385937). The [original PR](https://github.com/Expensify/Expensify.cash/pull/3760) @Looxor submitted to address rendering caused several regressions and we ended up reverting it.

**Comment by nickmurray47** [comment]
@Looxor We are going to close this PR given the minimal performance improvement and how far off we got from the original proposal accepted.

**Comment by Looxor** [comment]
image

**Pull request closed without merging**
