### PR TITLE
[NO QA]Sign commits for @OSBotify

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
Signs commits for @OSBotify when it creates a new version

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/149007

### Tests
1. CP this PR and verify the version commit is signed correctly

### CODE REVIEW

**Review by stitesExpensify — APPROVED** [review]
LGTM

**Review by Jag96 — APPROVED** [review]

**Comment by AndrewGable** [comment]
This is working now, still some other bugs to sort out, but it's getting closer.

Screen Shot 2021-11-19 at 3 03 20 PM

**Comment by stitesExpensify** [comment]
Does that mean we can take this off hold? https://github.com/Expensify/Expensify/issues/185608

**Comment by AndrewGable** [comment]
Not quite- I will let you know when.

**Pull request merged**
