### PR TITLE
Update height of default buttons to to match the text inputs

### LINKED ISSUE #4762: [HOLD for payment] Update height of default buttons to to match the text inputs
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Upwork Link: https://www.upwork.com/jobs/~01bb2cd985b9f96a7a
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com 
2. Enter an email 
3. Compare the height of the password input and the button

## Expected Result:
Height of the button and the text input should be the same or similar. 

## Actual Result:
Height of buttons and text fields are not the same which makes it looks inconsistent. 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.0.86-2

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:**

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

___ 
From @shawnborton https://expensify.slack.com/archives/C01GTK53T8Q/p1629100009370200
> We have new text inputs, which by default use a height of 52px. I think we should update our default buttons to match this height so that our forms feel more balanced. For example, on the sign in form, the inputs are 52px but the green button is still at 40px.

### PR DESCRIPTION
**Pull request by kakajann**
### Details
Update height of default buttons to to match the text inputs

### Fixed Issues
Fixes: #4762

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screen Shot 2021-08-24 at 1 26 59 AM

#### Mobile Web
Screen Shot 2021-08-24 at 1 27 34 AM

#### Desktop
Screen Shot 2021-08-24 at 1 40 02 AM

#### iOS
Screen Shot 2021-08-24 at 1 37 56 AM

#### Android
Screenshot_20210824-014719_New Expensify

### CODE REVIEW

**Comment by shawnborton** [comment]
Now that the buttons are taller, perhaps we can update the font size on the
buttons to be 15px as well?

**Review by Jag96 — APPROVED** [review]
This LGTM, going to also tag @shawnborton for design review since he filed the initial issue

**Comment by shawnborton** [comment]
Looks good to me. Can you just quickly check other areas of the app and make sure things look good? For example, like Settings (where we have Save buttons at the bottom of a view) or the "Pay" button in an IOU, etc.

**Review by Jag96 — APPROVED** [review]
Tested around the app, looks good. Merging.

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

**Comment by kakajann** [comment]
There is no regression I think

**Pull request merged**
