### PR TITLE
[NO QA] Urgent Fix: Missed passing a parameter to NewchatOptions

### PR DESCRIPTION
**Pull request by parasharrajat**
cc: @iwiznia 

### Details

 Passed missed parameter to `getNewChatOptions`.
 
Credits: @kidroca for pointing it out.

### CODE REVIEW

**Comment by Dal-Papa** [comment]
There seem to be more occurrences of `getNewChatOptions` that aren't using the boolean, should we put a default instead ? @Julesssss

**Comment by parasharrajat** [comment]
Done

**Review by Dal-Papa — APPROVED** [review]
This looks good to me. Thanks for the changes.

**Comment by parasharrajat** [comment]
:shipit: @Dal-Papa

**Pull request merged**
