### PR TITLE
Update ini package to 1.3.8 & merge-deep to 

### PR DESCRIPTION
**Pull request by deetergp**
### Fixed Issues

Fixes https://github.com/Expensify/Expensify/issues/165493

### Tests & QA
General regression testing on the desktop app.

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by jasperhuangg** [comment]
> npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

I don't understand, how did you update the package-lock.json without updating the package.json? Or was the package.json already updated and we forgot to run npm install to update the package-lock.json?

**Comment by deetergp** [comment]
Hey @jasperhuangg, this was a WIP and I didn't see that you got assigned. The reason I was updating the package-lock.json and not the package.json is because the `ini` package is an indirect dependency of a package we use. I had to update it because of [this Snyk vulnerability issue](https://github.com/Expensify/Expensify/issues/165493), but then I realized it's a part of expensify-common and should be updated there, and then in every repo that uses the expensify-common library. So I am going to close this PR.

**Comment by deetergp** [comment]
And now that I've gone and said that, I realize that while it is in expensify-common, it is a dev dependency, so it doesn't really matter. But Expensify.cash uses it as a dependency of Electron, so I am going to re-open this PR. Test it a bit further, then remove the WIP once I'm convinced it's okay.

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by deetergp** [comment]
Alright, I've tested, removed the WIP, and calling it ready for review.

**Review by jasperhuangg — APPROVED** [review]

**Pull request merged**
