### PR TITLE
Fix: OpenWorkspaceView API call is made on pages that do not need it

### PR DESCRIPTION
**Pull request by truph01**
### Details

- This PR will make sure: the default should be that we do not call the API OpenWorkspaceView and specify the param only if we need it in WorkspacePageWithSections
### Fixed Issues

$ https://github.com/Expensify/App/issues/42900
PROPOSAL: https://github.com/Expensify/App/issues/42900#issuecomment-2141549569

### Tests

1. Sign in to any Expensify account.
2. Create a new collect workspace if itsn't
3. Go to Setting -> Workspaces, open that workspace.
4. Open the network inspector tool (can use Chrome dev tool)
5. Go to Workspace profile
6. Verify that the OpenWorkspaceView API is called
7. Go to pages: Distance rates/Workflows.
8. Verify that there is no OpenWorkspaceView API called
- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/170341821/06b81a17-3bfd-4bf7-a7c8-1834488e5c39

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/170341821/08b8cac5-ad12-4d5c-9b7b-01fca0d28894

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/170341821/9605df56-083a-42ed-9824-a2ef9479cebc

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/170341821/12052631-ce57-4b73-8586-b311b839b092

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/170341821/244eceef-0cda-420e-82d9-ee9a4680290e

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/170341821/30ab4c82-6cd5-4204-8a58-94190e19d14a

</details>

### CODE REVIEW

**Comment by mountiny** [comment]
@truph01 please get this PR ready for a review as soon as you can. Do not post new proposals on issues until this is merged. Thanks for understanding

**Comment by truph01** [comment]
@mountiny 
- I need to confirm that, should we call ```OpenWorkspaceView``` if the ```reimbursementAccount``` is available?

- Also, in ```WorkspaceProfilePage```, we need to use ```hasVBBA``` prop:
https://github.com/Expensify/App/blob/9b179ce3c63899262da82eee052eb61091880c12/src/pages/workspace/WorkspaceProfilePage.tsx#L129
so I don't think "This is being called on pages where the bank account details are not needed" like mentioned in the "Actual result" section in the bug description.

**Comment by truph01** [comment]
I just updated [comment](https://github.com/Expensify/App/pull/42979#issuecomment-2148615000)

**Comment by truph01** [comment]
@hoangzinh Based on my [comment](https://github.com/Expensify/App/pull/42979#issuecomment-2148615000), this PR is just making shouldSkipVBBACall by default true

**Comment by mountiny** [comment]
@truph01 can you make sure we do not call the API request when the `reimbursementAccount` is present?

**Comment by truph01** [comment]
@mountiny I think we can do it by updating:
https://github.com/Expensify/App/blob/a67be2f7037cab40d6fe7affd88c5f569b0afc75/src/pages/workspace/WorkspacePageWithSections.tsx#L140
to:
```
            if (reimbursementAccount) {
                return;
            }
            fetchData(policyID, shouldSkipVBBACall);
```

What do you think?

**Comment by truph01** [comment]
@hoangzinh Ah, that makes sense. So I think I need to consider my plan "do not call the API request when the reimbursementAccount is present", it can lead to the reimbursementAccount is outdated

**Comment by truph01** [comment]
@mountiny Can you confirm "if FE can receive a Pusher event regarding reimbursementAccount update" like @hoangzinh mentioned in [this](https://github.com/Expensify/App/pull/42979#issuecomment-2149521512) ? Then we can consider whether we should "do not call the API request when the reimbursementAccount is present" or not. Thanks

**Comment by truph01** [comment]
@hoangzinh Based on [it](https://github.com/Expensify/App/pull/42979#issuecomment-2150480488), you can review this PR now

**Comment by truph01** [comment]
@hoangzinh Can you help review it because it is HIGH priority task, thanks

**Comment by truph01** [comment]
@hoangzinh Yes. So that is why I said that:

> this PR is just to make sure "the default should be that we do not call the API command and specify the param only if we need it"

**Comment by mountiny** [comment]
Ok, lets continue with this, but we will need to reconsider a backend solution for this

**Comment by mountiny** [comment]
@hoangzinh the current changes in the PR are enough

**Comment by truph01** [comment]
@hoangzinh Since this PR is solely a migration and doesn't address any bugs, I'm currently quite confused about the appropriate test steps for this scenario. I added the test steps in the PR's author, if you have any feedback, let me know. Thanks

**Comment by truph01** [comment]
@hoangzinh I addressed your [comment](https://github.com/Expensify/App/pull/42979#issuecomment-2153611489)

**Comment by truph01** [comment]
> When we navigate between sibling menus, it doesn't call API to fetch the latest data.

@hoangzinh I think we need to confirm the expected behavior. Assume we are in WorkspaceProfilePage, then we go to page X, then back to WorkspaceProfilePage again:
1. Option 1: If X is one of the pages in the sibling menus, call ```OpenWorkspaceView``` else, do not call ```OpenWorkspaceView```.

2. Option2: Always do not call ```OpenWorkspaceView```

3. Option 3 (Current behavior in staging): Always call ```OpenWorkspaceView```

@mountiny  What is the expected behavior in the above 3 options?

**Comment by truph01** [comment]
@hoangzinh There are many similar pages, such as settings/workspaces/:policyID/bills, settings/workspaces/:policyID/card, settings/workspaces/:policyID/invoices, settings/workspaces/:policyID/travel, etc. In each page, we can have the same behavior as workspace profile page (navigate to other page then go back).  So we should ensure consistent handling across all these pages, not just the workspace profile page.

**Comment by truph01** [comment]
@hoangzinh It is Option 1 in [above](https://github.com/Expensify/App/pull/42979#issuecomment-2154649567), right?

**Comment by truph01** [comment]
I mean your suggestion here https://github.com/Expensify/App/pull/42979#issuecomment-2154711399 is the same as my option 1 https://github.com/Expensify/App/pull/42979#issuecomment-2154649567, do you think that is correct?

**Comment by truph01** [comment]
@hoangzinh Ok, got it.
I think now we need confirmation from @mountiny about my [question](https://github.com/Expensify/App/pull/42979#issuecomment-2154649567) before implementing the detail so there's no wasted effort.

**Comment by mountiny** [comment]
@truph01 @hoangzinh this is tricky, I think we should not call it again when the RHP modal is closed, but I can see we do that on other pages too and I think it would be out of scope for this PR, so lets do nothing now

**Comment by truph01** [comment]
@hoangzinh Based on [it](https://github.com/Expensify/App/pull/42979#issuecomment-2155547298), I remove the change which fixed your concern https://github.com/Expensify/App/pull/42979#issuecomment-2153611489. You can review PR now

**Comment by truph01** [comment]
@hoangzinh Sure, will do it today

**Comment by truph01** [comment]
@hoangzinh I agree. I just updated the test steps

**Comment by truph01** [comment]
@hoangzinh I added recording in chrome

**Comment by truph01** [comment]
@hoangzinh In mobile devices, how do we know whether the API is called or not?

**Comment by truph01** [comment]
> @hoangzinh In mobile devices, how do we know whether the API is called or not?

@hoangzinh Ah, based on your checklist, I got it

**Comment by truph01** [comment]
@hoangzinh I completed checklist

**Comment by truph01** [comment]
@hoangzinh Did you finish reviewing step?

**Review by hoangzinh — APPROVED** [review]
LGTM, congrats for the 1st PR @truph01

**Review by mountiny — APPROVED** [review]
Thanks for help here!

**Comment by truph01** [comment]
@mountiny I merged main

**Review by mountiny — APPROVED** [review]

**Pull request merged**
