### PR TITLE
remove notification Subheader

### PR DESCRIPTION
**Pull request by mateusbra**
### Details

Remove notification Subheader

### Fixed Issues

$ https://github.com/Expensify/App/issues/7670

### Tests | QA Steps

 1. Click "+"
 2. Click "New room"
 3. Add any room name, choose any workspace, choose any visibility setting - Click "Create room"
 4. Click the room header in the main chat pane to be taken to the room "Setting" pane
 5.  Verify notification Subheader was removed.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

image

#### Mobile Web

image

#### Desktop

Captura de Tela 2022-02-10 às 21 33 57
 

#### iOS

Captura de Tela 2022-02-10 às 14 14 40

#### Android

image

### CODE REVIEW

**Comment by Julesssss** [comment]
Ignore that @roryabraham, I missclicked.

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
Actually, I'm holding my review for now, as I'm unable to open the settings menu. I tried updating all repos with no luck 😕 

Screenshot 2022-02-11 at 11 57 27

**Review by parasharrajat — APPROVED** [review]
LGTM. 

cc: @Julesssss. 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by mateusbra** [comment]
@Julesssss I had this issue a few times on IOS. I tryed to reload the app and it worked for me.

**Comment by Julesssss** [comment]
God knows what the issue was, but I was finally able to verify!

**Pull request merged**
