### PR TITLE
Refactor index files for Popover. 

### LINKED ISSUE #3347: FAB menu - the menus for FAB menu slide in from the left-to-right, instead of bottom-to-top
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Upwork Job - https://www.upwork.com/jobs/~0156d103876d9e96f7

___

## Expected Result:
Menu should slide from bottom to top 

## Actual Result:
Menu slides from left-to-right

## Action Performed:
1. Open e.cash app on iOS or aOS
2. Log in and click on the FAB button. 

## Workaround:
No need, visual issue. 

## Platform:
Where is this issue occurring?

 Web
 iOS ✔️ 
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.62-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/44479856/120683074-31bdd000-c46b-11eb-939f-a0f11d39ae79.mp4

onal supporting documentation

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___
From @roryabraham https://expensify.slack.com/archives/C01GTK53T8Q/p1622681730473400
> On mobile platforms, the menus for FAB menu slide in from the left-to-right, instead of bottom-to-top

### PR DESCRIPTION
**Pull request by Luke9389**
### Details

We realized that we don't really need the .native extension file because we expect the native platforms to have small screen sizes anyway. This fixes the problem for the linked issue, while simplifying our files. 

### Fixed Issues

Fixes https://github.com/Expensify/Expensify.cash/issues/3347

### Tests / Web QA

1. Click the FAB and verify that it opens with the correct animation. For mobile, the animation should be vertical. Otherwise, it should fade horizontally. 

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

My android environment has been finicky, so I'm going to leave the android testing to QA, (unless I can get it up and running before the review process is finished here).

### CODE REVIEW

**Comment by HorusGoul** [comment]
I see you marked this as a draft. Do you want an early review, or should I wait until you mark it ready for review again?

**Comment by Luke9389** [comment]
You can wait, thanks 👍

**Comment by Luke9389** [comment]
Hey @HorusGoul, just took this off draft. Thanks for waiting!

**Review by HorusGoul — APPROVED** [review]
LGTM!

**Pull request merged**
