### PR TITLE
Fix: Using trim() for better UX

### PR DESCRIPTION
**Pull request by aman-atg**
### Details

[Comment](https://github.com/Expensify/App/issues/4155#issuecomment-884008083)

### Fixed Issues

#4155 and #4156

## Search Page
1. Search for an email
2. Add extra space
3. Search result should not disppear
 
## Profile
1. Add extra whitespace anywhere in either names
2. Save button will not be activated

## Emoji picker Menu
1. Go to any chat
2. Open emoji picker 
3. Search for an emoji
4. Adding extra whitespace won't make the result(s) disappear 

### Tested On

- [ :heavy_check_mark: ] Web
- [ :heavy_check_mark: ] Mobile Web
- [ :x: ] Desktop
- [ :x: ] iOS
- [ :heavy_check_mark: ] Android

#### Search
web
#### Profile
web2
#### Emoji Picker
web3

#### Profile
mWeb

#### Search
mWeb2

#### Profile
mobile

#### Search 
mobile2

### CODE REVIEW

**Comment by aman-atg** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Review by johnmlee101 — APPROVED** [review]
Looks good!

**Comment by kavimuru** [comment]
## Desktop -  Profile - Save button always enabled and able to save with space in name
## Expected Result: 
Save button will not be activated
## Actual Result:
Save button always enabled and able to save name with spaces
## Actions Performed:
1. Launch the app and login
2. Click on avatar and select profile
3. Add extra whitespace anywhere in either names
## Platform:
iOS 
Web ✔️
Desktop ✔️
## Build:
1.0.81-0
## Notes/Images/Video:

https://user-images.githubusercontent.com/43996225/127426928-7cbcbb47-1a33-4851-b17e-726ed80d6eea.mp4

**Comment by aman-atg** [comment]
### Web (v1.0.81-1)
image

Not observing this behaviour on staging (Web).

* Maybe it's fixed for Desktop as well on v1.0.81 , I don't have a macbook right now else I would have shown. Can you please check for build v1.0.81-1 on Desktop

**Comment by isagoico** [comment]
I'm still able to reproduce this on Web/Chrome staging 1.0.81-1 
image

**Comment by aman-atg** [comment]
@isagoico 
Can you tell me if your name was already having extra whitespace in earlier versions?
Or did you change any other field like `Preferred Pronouns` or `Timezone` etc.

 _Still trying to figure out if there's any other reason._


### New Changes
 * I found out that changing `other fields` in Profile Section will also result in saving `names` with extra whitespace so only disabling the `Button` won't completely fix this behaviour. 

https://github.com/Expensify/App/blob/f99dea6bf82ab0e411e276d400ff117e599bd2f9/src/pages/settings/Profile/ProfilePage.js#L175-L176
 * These two lines should be changed with the code below
```js
            firstName: firstName.trim(),
            lastName: lastName.trim(),
```


@johnmlee101  Please review the proposed changes

**Comment by isagoico** [comment]
I just tried again in a new account (that didn't have a name set yet) and got the same behavior. I only edited the name and last name fields with white space and text. Hope this is helpful 
image

**Comment by aman-atg** [comment]
@isagoico  Thanks for testing.

> I only edited the name and last name fields with white space and text. Hope this is helpful

I think changing the text should `enable` the Button?

**Comment by isagoico** [comment]
So, let me see if I get this. The user is allowed to save the name that contains whitespace if the user changes the text? We thought it was a bug.

**Comment by aman-atg** [comment]
> So, let me see if I get this. The user is allowed to save the name that contains whitespace if the user changes the text? We thought it was a bug.

Yes, you're right it's a bug and the new proposed changes will hopefully fix it. 

Earlier, it was thought that only disabling the **Save Button** will fix it.
But, as we can't stop user from adding a whitespace after changing the name or other fields, the best we can do is save the name after trimming it.

**Comment by isagoico** [comment]
Oh thanks a lot for the clarification 🙇‍♀️ we'll wait for the fixes so we can retest this then

**Comment by johnmlee101** [comment]
@aman-atg are you working on a fix for this?

**Comment by aman-atg** [comment]
> ### New Changes
> * I found out that changing `other fields` in Profile Section will also result in saving `names` with extra whitespace so only disabling the `Button` won't completely fix this behaviour.
> 
> https://github.com/Expensify/App/blob/f99dea6bf82ab0e411e276d400ff117e599bd2f9/src/pages/settings/Profile/ProfilePage.js#L175-L176
> 
> * These two lines should be changed with the below code
> 
> ```js
>             firstName: firstName.trim(),
>             lastName: lastName.trim(),
> ```
> 

@johnmlee101 
I think these changes will fix the issue.

**Comment by johnmlee101** [comment]
I think that makes sense! Can you spin up a PR and link both the original issue and this PR to it?

**Comment by isagoico** [comment]
Retested this and it was a pass 🎉 
image

Checking it off.

**Pull request merged**
