### PR TITLE
Fix/14972 the terms of service checkbox does not respond properly while navigating the connect bank account flow

### PR DESCRIPTION
**Pull request by tienifr**
### Fixed Issues

$ https://github.com/Expensify/App/issues/14972   
$ https://github.com/Expensify/App/issues/14972#issuecomment-1427459988

#### Connecting bank account (language: English)
1, Open workspace => connect bank account manually, enter valid information for first 3 steps
2, Go to Workspace => connect bank account manually again => Continue with setup => Go back to the first step, uncheck the check box then go back.
3, Click continue with setup again, now you are at Step 1, press "Next".
4, Verify that the checkbox remains unchecked, because you unchecked it in step 2.

#### Adding debit card (language: English)
1, Open workspace => Payments => Add payment method => Debit card, enter valid information.
2, Verify that at this step, when you press "Save":
- If you don't check the check box, an error message will appear and prevent you from saving.
- If you check the check box, you will be allowed to proceed the flow.

#### Connecting bank account (language: English)
1, Open workspace => connect bank account manually, enter valid information for first 4 steps
2, Verify that at the fourth step, when you press "Save & continue":
- If you don't check the check box, an error message will appear and prevent you from saving and moving to the next step.
- If you check the check box, you will be allowed to proceed the flow.

#### Enabling payments (language: English)
1, Open Enable Payments
2, Verify that when you press "Enable Payments":
- If you don't check the check box, an error message will appear and prevent you from moving to the next step.
- If you check the check box, you will be allowed to proceed the flow.

*To test in language: Spanish, please change language from English to Spanish then follow test steps for language: English*
- [x] Verify that no errors appear in the JS console

#### Connecting bank account (language: English)
1, Open workspace => connect bank account manually, enter valid information for first 3 steps
2, Go to Workspace => connect bank account manually again => Continue with setup => Go back to the first step, uncheck the check box then go back.
3, Click continue with setup again, now you are at Step 1, press "Next".
4, Verify that the checkbox remains unchecked, because you unchecked it in step 2.

#### Adding debit card (language: English)
1, Open workspace => Payments => Add payment method => Debit card, enter valid information.
2, Verify that at this step, when you press "Save":
- If you don't check the check box, an error message will appear and prevent you from saving.
- If you check the check box, you will be allowed to proceed the flow.

#### Connecting bank account (language: English)
1, Open workspace => connect bank account manually, enter valid information for first 4 steps
2, Verify that at the fourth step, when you press "Save & continue":
- If you don't check the check box, an error message will appear and prevent you from saving and moving to the next step.
- If you check the check box, you will be allowed to proceed the flow.

#### Enabling payments (language: English)
1, Open Enable Payments
2, Verify that when you press "Enable Payments":
- If you don't check the check box, an error message will appear and prevent you from moving to the next step.
- If you check the check box, you will be allowed to proceed the flow.

*To test in language: Spanish, please change language from English to Spanish then follow test steps for language: English*
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

#### Connecting bank account (verify checkbox value remains or not)

https://user-images.githubusercontent.com/113963320/220154981-852653dd-72d2-4bdc-985c-025ca5eb91cd.mp4

#### Connecting bank account (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220155339-4687eb58-244b-4b2c-862b-5a5dbeef1f76.mp4

#### Adding debit card (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220168747-988c4404-3c16-4df1-9647-0936e6e90117.mp4

#### Adding debit card (verify checkbox error message, language: Spanish)

https://user-images.githubusercontent.com/113963320/220161997-33587173-b84e-4c1f-a2f3-94a11ed3e754.mp4

#### Enabling payments (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220168385-58ed8fb8-7085-4dc6-9533-6ad4ed851899.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

#### Connecting bank account (verify checkbox value remains or not)

https://user-images.githubusercontent.com/113963320/220166889-6d29dd9c-2033-4456-ab2e-274cef7dd78e.mp4

#### Connecting bank account (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220166912-fa4f3afa-1199-476c-ad2d-daa13e73ea41.mp4

#### Adding debit card (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220166999-a90ba4f9-a422-4e09-bf75-5cf4d6d910f0.mp4

#### Adding debit card (verify checkbox error message, language: Spanish)

https://user-images.githubusercontent.com/113963320/220166936-d14ba748-e2a7-4c8c-95c6-7ee5502aba0a.mp4

#### Enabling payments (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220167067-9bbd39eb-ec22-4d7b-a8b4-7c8e80ae85b9.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

#### Connecting bank account (verify checkbox value remains or not)

https://user-images.githubusercontent.com/113963320/220168224-366e5b04-38c5-4a3a-8fb6-ce3794e02d94.mp4

#### Connecting bank account (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220168085-54d00ab8-69d2-4b84-bbb3-14ea8085eec7.mp4

#### Adding debit card (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220168108-09704d2d-d94e-41db-84e4-a76b0a16fbab.mp4

#### Adding debit card (verify checkbox error message, language: Spanish)

https://user-images.githubusercontent.com/113963320/220168242-68885aa1-ef4e-42bb-987c-01be0bfa8dbf.mp4

#### Enabling payments (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220168098-0ab11e1e-a180-4ab8-aec1-818faa8e2eb1.mp4

</details>

<details>
<summary>Desktop</summary>

#### Connecting bank account (verify checkbox value remains or not)

https://user-images.githubusercontent.com/113963320/220163362-30c89e97-5e0d-4da4-bf28-abbfbf314fcb.mp4

#### Connecting bank account (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220163396-4a97c621-b86e-43b6-87f4-59950c01a271.mp4

#### Adding debit card (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220163470-c443f47d-0fee-447f-ab32-63843d2b7551.mp4

#### Adding debit card (verify checkbox error message, language: Spanish)

https://user-images.githubusercontent.com/113963320/220163503-1c94bfd3-2ae6-4ec9-8e31-cffa287a2047.mp4

#### Enabling payments (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220163889-662ac823-9f97-4e8a-8be2-ee7ad9773de4.mp4

</details>

<details>
<summary>iOS</summary>

#### Connecting bank account (verify checkbox value remains or not)

https://user-images.githubusercontent.com/113963320/220167489-34685218-c1f0-4ecd-b666-dcdffdd01ec0.mp4

#### Connecting bank account (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220167645-c9797158-51c5-4b1c-be83-a0c45ac765eb.mp4

#### Adding debit card (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220167546-5cf6e6c9-22d8-4e01-a47b-ae371b33a7dd.mp4

#### Adding debit card (verify checkbox error message, language: Spanish)

https://user-images.githubusercontent.com/113963320/220167508-f70372e0-307f-4452-9cb4-8a8e6eec4c9e.mp4

#### Enabling payments (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220167567-1c2b3953-322a-4b36-a1bd-d75417739904.mp4

</details>

<details>
<summary>Android</summary>

#### Connecting bank account (verify checkbox value remains or not)

https://user-images.githubusercontent.com/113963320/220166545-894b3fe2-1fd1-4be4-bf7c-dea42b4a2296.mp4

#### Connecting bank account (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220163954-a30e6102-6761-4777-851d-38a06157f7cf.mp4

#### Adding debit card (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220163934-39374e16-1b38-4ed5-ba10-07cd9466145b.mp4

#### Adding debit card (verify checkbox error message, language: Spanish)

https://user-images.githubusercontent.com/113963320/220166432-c2aac4b5-430d-4c61-8b61-322c815f37a0.mp4

#### Enabling payments (verify checkbox error message)

https://user-images.githubusercontent.com/113963320/220166450-e65fca34-c214-4503-bbdb-fa377528489d.mp4

</details>

### CODE REVIEW

**Comment by tienifr** [comment]
Hi @NikkiWines @rushatgabhane , the PR is ready for review. Please help me check it. Thank you!

**Comment by tienifr** [comment]
Hi @NikkiWines @rushatgabhane , the PR is ready for review. Please help me check it. Thank you!

**Review by NikkiWines — COMMENTED** [review]
Code looks good and works well but missing screenshots/videos for review 

**Edit:** Eh? Maybe GH didn't load it - seems there are screenshots and videos, my bad.

**Review by rushatgabhane — COMMENTED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://user-images.githubusercontent.com/29673073/220756139-49447233-f1d1-46a2-811f-72bc9738493e.mp4



</details>


<details>
<summary>Mobile Web - Chrome</summary>


https://user-images.githubusercontent.com/29673073/220756161-af4cd6a1-8ece-48e8-b048-598c27047d2c.mp4



</details>

<details>
<summary>Mobile Web - Safari</summary>



https://user-images.githubusercontent.com/29673073/220756231-a5f500bf-1e8b-46af-a004-082c1922d462.mp4


</details>

<details>
<summary>Desktop</summary>


https://user-images.githubusercontent.com/29673073/220762151-7be373ff-d843-4e1b-b989-39ad60adfe25.mp4



</details>

<details>
<summary>iOS</summary>


https://user-images.githubusercontent.com/29673073/220756272-baa01870-164f-4ca7-ae95-68c30f912b6b.mp4



</details>

<details>
<summary>Android</summary>


https://user-images.githubusercontent.com/29673073/220761058-0628a22c-960f-41c5-976e-e16d0ffd6add.mp4


</details>

**Review by rushatgabhane — APPROVED** [review]
@NikkiWines LGTM as well

**Review by NikkiWines — APPROVED** [review]
👍

**Pull request merged**
