### PR TITLE
fix: use Navigation.navigate function to redirect user to admin workspace

### PR DESCRIPTION
**Pull request by allroundexperts**
### Details

This followup PR fixes the [regression](https://github.com/Expensify/App/issues/19440) that came up as a result of fix for [this bug](https://github.com/Expensify/App/issues/18894).

### Fixed Issues

$ https://github.com/Expensify/App/issues/18894
PROPOSAL: https://github.com/Expensify/App/issues/18894#issuecomment-1546906562

### Tests

1. Open ND on Web or Desktop and login with any account
2. Go to Settings -> WorkSpaces
3. Click on `Create new workspace` button
4. Verify that the chat report page in background changes to the workspace page
5. Verify that the composer in the background is not focused

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

1. Open ND on Web or Desktop and login with any account
2. Go to Settings -> WorkSpaces
3. Click on `Create new workspace` button
4. Verify that the chat report page in background changes to the workspace page
5. Verify that the composer in the background is not focused

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/30054992/9f50d662-64ce-4381-81a9-3ecdd413a6d5

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/30054992/4ffd272e-e241-485e-84bf-1cc7453708fd

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/30054992/ee82eb9f-beae-4429-abdd-2cc049440a87

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/30054992/1ec9c94e-5f8e-4186-9e3b-5576f3945176

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/30054992/4de1ffc5-f07c-44f2-95b6-179a62a3666b

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/30054992/1dc1af70-2f28-4cf7-b708-7839ae8e598f

</details>

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
Calling navigate twice looks really weird to me. Maybe we should discuss and decide how we want to handle this issue.

**Comment by Santhosh-Sellavel** [comment]
@NikkiWines I think the bug is with Composer here, so it should be handled separately let me know your thoughts, thanks!

**Comment by NikkiWines** [comment]
> Calling navigate twice looks really weird to me. Maybe we should discuss and decide how we want to handle this issue.
> Autofocus should be off for the composer when an RHN is OPEN

Agreed, I don't see any other place where we call `navigate` twice in a row.

> @NikkiWines I think the bug is with Composer here, so it should be handled separately let me know your thoughts, thanks!

Yep, I think you're right. I'm curious if there are any other flows that do a similar background navigation while maintaining the right side modal or some sort of popup (and focus) in the foreground.

**Comment by NikkiWines** [comment]
> @allroundexperts Still the issue occurs for me.

> @Santhosh-Sellavel Are you sure that you're on the correct branch? Please note that the branch name here is followup-fix-18894. I've tested it again and it does not seem to happen. @NikkiWines Can you check as well please?

I can't reproduce the issue on @allroundexperts's branch

**Comment by Santhosh-Sellavel** [comment]
> > @NikkiWines I think the bug is with Composer here, so it should be handled separately let me know your thoughts, thanks!
> 
> Yep, I think you're right. I'm curious if there are any other flows that do similar background navigation while maintaining the right side modal or some sort of popup (and focus) in the foreground.

We use `withNavigationFocus` for that scenarios

**Comment by Santhosh-Sellavel** [comment]
And Yes, checking out their branch changes works now.  Yesterday I just used their code changes, not sure what we wrong yesterday.

**Comment by Santhosh-Sellavel** [comment]
What can we do now @NikkiWines ?

**Comment by NikkiWines** [comment]
> Autofocus should be off for the composer when an RHN is OPEN
> @NikkiWines I think the bug is with Composer here, so it should be handled separately let me know your thoughts, thanks!

Sorry, just to clarify @Santhosh-Sellavel, are you saying we shouldn't fix this as a regression of

**Comment by NikkiWines** [comment]
My bad 😅

**Comment by Santhosh-Sellavel** [comment]
Ah Missed this comment, 

> > Autofocus should be off for the composer when an RHN is OPEN
> > @NikkiWines I think the bug is with Composer here, so it should be handled separately let me know your thoughts, thanks!
> 
> Sorry, just to clarify @Santhosh-Sellavel, are you saying we shouldn't fix this as a regression of #19224 but instead as a new separate issue?

Yes, @NikkiWines IMO it's clear the issue lies with the composer if focus when it shouldn't be. Also calling navigation twice is a really bad idea. I think we should have the fix at the Composer level. We could take it on here but the composer itself is too sensitive to components it's better to separate the issue with a normal process where we can make sure it doesn't break any.

**Comment by NikkiWines** [comment]
Ok cool, that makes sense to me. Thanks for clarifying! Let's create a new issue for this instead (or re-use https://github.com/Expensify/App/issues/19440) since it's already got steps for reproducing the error. 

cc: @danieldoglas it looks like this bug is more with composer than with the navigation code added in https://github.com/Expensify/App/pull/19224 and is better suited to being handled separately than as a regression fix. Thoughts?

**Comment by NikkiWines** [comment]
Discussed with @danieldoglas further. @allroundexperts @Santhosh-Sellavel  how would you feel about the following: 

1. No longer consider https://github.com/Expensify/App/issues/19440 a regression of https://github.com/Expensify/App/pull/19224, allowing us to close out that issue and issue payment appropriately 

2. Let @Santhosh-Sellavel act as the Contributor+ for https://github.com/Expensify/App/issues/19440, allowing @allroundexperts to propose a solution (should you want to) on that issue

3. Post an update to https://github.com/Expensify/App/issues/19440 noting that we'd like to focus the fix on Composer, and not provide a fix that involves calling `Navigation.navigate` twice in a row.

Let us know your thoughts!

**Comment by danieldoglas** [comment]
@Santhosh-Sellavel @allroundexperts how do you feel about @NikkiWines proposal above?

**Comment by Santhosh-Sellavel** [comment]
Looks good to me as well!

**Comment by danieldoglas** [comment]
Awesome, closing this!

**Pull request closed without merging**
