### PR TITLE
fixed edited flag is shown for brief moment

### LINKED ISSUE #3219: [HOLD for payment on June 15th] Edit comment - Saving an unedited comment shows the `edited` status for a brief moment
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Upwork Posting: https://www.upwork.com/jobs/~014b1b019c459a02d5
___

## Expected Result:
If the message was not changed the edited status should not appear. 

## Actual Result:
Edited status appears for a brief moment after saving a message (without changes) 

## Action Performed:
1. Navigate to a conversation in e.cash
2. Click on edit comment on a message
3. Press save without making any changes 

## Workaround:
No need, visual issue. 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS ✔️ 
 Android (another behaviour, please check notes) 
 Desktop App
 Mobile Web ✔️ 

**Version Number:** 1.0.56-0

**Logs:**

**Notes/Photos/Videos:** 
On android app, the edited status persists. 

https://user-images.githubusercontent.com/44479856/120042057-65b27480-bfd7-11eb-9f26-207c93f2ba48.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @aliabbasmalik8 https://expensify.slack.com/archives/C01GTK53T8Q/p1622188890359100
> On Edit Comment, When we clicked enter button without edit any comment then (edited) tag appear for short duration

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details
Skip edit status for the unchanged messages.

### Fixed Issues

Fixes #3219

### Tests | QA Steps
1. Navigate to a conversation in e.cash
2. Click on edit comment on a message
3. Press save without making any changes
4. No Edited tag should be shown.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/24370807/121210982-c2e0dc80-c899-11eb-806a-8982f596f6da.mp4

#### Mobile Web

https://user-images.githubusercontent.com/24370807/121211148-e146d800-c899-11eb-8f35-17ed742bd6e9.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/121211007-c6746380-c899-11eb-83ac-a0025da2ac51.mp4

#### Android

https://user-images.githubusercontent.com/24370807/121216170-48ff2200-c89e-11eb-88fb-443826f6bca3.mp4

### CODE REVIEW

**Comment by parasharrajat** [comment]
recheck

**Comment by parasharrajat** [comment]
@roryabraham It seems checks are failing.

**Comment by roryabraham** [comment]
Merge main into your branch and try again.

**Review by Jag96 — APPROVED** [review]
LGTM

**Pull request merged**
