### PR TITLE
Fix: clicking on makerbadge does not mark comments as read

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/5807

### Tests | QA Steps
1. Open two browsers.
2. Login with Account A in browser A.
3. Login with account B in browser B.
4. Close app on browser B.
5. Send message from account A from browser A to account B.
6. Copy the report URL from browser a.
7. Go to browser B.
8. Paste the URL of the Report you copied.
9. Scoll the list back to see the marker.
10. Click on the MarkerBadge. 
11. Comments should be marked as read.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/24370807/142039847-e8a797ea-ec1d-4c52-b13e-49c68a769209.mp4

#### Mobile Web

https://user-images.githubusercontent.com/24370807/142461921-0379552a-22f2-4aa4-b0a7-7bf8f9a7bbb6.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/142463289-380a6016-11bf-4547-b1cd-ee6c4ff755c4.mp4

#### Android

https://user-images.githubusercontent.com/24370807/142462003-caf5944f-b0e1-4c62-912e-0e760e983ef7.mp4

### CODE REVIEW

**Comment by Beamanator** [comment]
Where are the screenshots on mobile & desktop? :D

**Comment by parasharrajat** [comment]
on the way... :walking_man:

**Comment by parasharrajat** [comment]
Sorry to keep you waiting all set now. @Beamanator

**Comment by Beamanator** [comment]
Thanks dude - no worries about the delay :D

> Actually I was confused about this as we can't open the Url on other platforms except for M-web. But I will create clips for standard behaviour.

True, do you know if the reported issue was also occurring on other devices? Either way it's nice to know it's not breaking existing functionality so thanks for the videos :)

**Review by Beamanator — APPROVED** [review]
Looks great 👍 and tests well

**Pull request merged**
