### PR TITLE
[No QA] fix Prop types

### PR DESCRIPTION
**Pull request by parasharrajat**
@roryabraham Please review.

### Details

Just a cleanup of prop warnings.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Review by Beamanator — CHANGES_REQUESTED** [review]
I think it would be cleaner & more understandable to remove `windowDimensionsPropTypes` from `GrowlNotificationContainerPropTypes.js`, then add the `windowDimensionsPropTypes`  to `GrowlNotificationContainer/index.js` since `GrowlNotificationContainerPropTypes.js` should only contain common props.

I think this would also be nicer looking than removing specific props from a common propType file. What do you think @roryabraham & @parasharrajat ?

**Comment by roryabraham** [comment]
Agree with @Beamanator 👍

**Comment by parasharrajat** [comment]
@roryabraham Ready to move. Thanks.

**Review by Beamanator — APPROVED** [review]
Nice 👍 
I'll leave this open for @roryabraham to check out when he's back online

**Review by roryabraham — APPROVED** [review]

**Pull request merged**
