### PR TITLE
Preserve text inside code fences

### PR DESCRIPTION
**Pull request by marktoman**
### Details

Pulls in changes from updated Expensimark code on https://github.com/Expensify/expensify-common/pull/496. This makes it so that we preserve text within code fences instead of stripping out extra new lines at the bottom. This is because we feel it makes more sense to preserve what a user has entered vs trying to be "helpful" and remove text they may or may not have wanted.

### Fixed Issues

$ https://github.com/Expensify/App/issues/14694
$ https://github.com/Expensify/App/issues/14694#issuecomment-1411287892

## Steps (validation + regressions)
1. Add a comment:
````
```
text

```
````
2. Verify that it has an empty line below `text` once added.
3. Edit it and check that it looks the same as 1.
4. Repeat 1-3 for the below, but instead, make sure that it has no added line below `text`:
````
```
text
```
````

- [x] Verify that no errors appear in the JS console

## Steps (validation + regressions)
1. Add a comment:
````
```
text

```
````
2. Verify that it has an empty line below `text` once added.
3. Edit it and check that it looks the same as 1.
4. Repeat 1-3 for the below, but instead, make sure that it has no added line below `text`:
````
```
text
```
````

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/47689923/216801997-0bdfcef3-eab6-4bde-a1b7-a3a4121e34ce.mov

https://user-images.githubusercontent.com/47689923/216802005-de7d614c-c1bb-4f89-90d6-290f018a3d22.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/47689923/219436660-98b7a14f-6c5b-4d53-800d-7dc51c7512e6.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/47689923/219432945-795f5ce8-8f9e-459b-b9e0-cd6b01491344.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/47689923/216801989-3318c65a-b067-4833-bdca-b21e6727b132.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/47689923/219433027-0444d39a-096f-49b6-a61d-818bd283b0ac.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/47689923/219454270-b1a93b02-b768-4693-b369-e272efdffb21.mp4

</details>

### CODE REVIEW

**Review by bondydaa — DISMISSED** [review]
👍 Please make sure you fill out the checklist as well and test / screenshot for all devices.

**Comment by mananjadhav** [comment]
@marktoman Quick bump on @bondydaa's comment to fill out the checklist and update the screenshots for all platforms.

**Comment by marktoman** [comment]
On iOS, when entering:
````
```
Test
```
````
the converted result (`commentText` [here](https://github.com/Expensify/App/blob/0d956391215e2b467252f5e8f6d8376eefa6e0f8/src/libs/ReportUtils.js#L745)) is `<pre>Test<br /></pre>`, which is correct and the same for other platforms.

Editing works as expected:

image


But, it is rendered like this:

image

So I'm not sure if I should try to change how it is rendered somehow.

**Comment by bondydaa** [comment]
Hmm that's strange, it only happens on iOS (native or mWeb?) that it's still rendered with the extra new line?

**Comment by marktoman** [comment]
Only native, Safari works the same as desktop. I'll dig into the rendering.

**Comment by marktoman** [comment]
Apparently, the HTML standard renders the lines the way we settled on (the web/desktop videos), but this behavior is behind a flag on native:
>  Recommended value is true on non-web platforms.
https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#enableexperimentalbrcollapsing


I've tested it by adding `props.sharedProps.enableExperimentalBRCollapsing = true;` [here](https://github.com/Expensify/App/blob/13cee1cd2791f982c60c34c41b4f35f71272899b/src/components/HTMLEngineProvider/HTMLRenderers/PreRenderer/index.native.js#L7) and it solves the problem, i.e., it makes the lines consistent between web and native (both ios and android).

**Comment by bondydaa** [comment]
Hmm the other half of that recommendation is slightly concerning

> Also note that this is an experimental feature, thus subject to behavioral instability.

but I think you're right that's what we want to provide consistent behavior across all platforms. 

Go ahead and commit that change then and we can go from there.

**Review by bondydaa — DISMISSED** [review]
😬 though package*.json conflicts hopefully they're not too bad

**Comment by marktoman** [comment]
I've merged new changes and tested it everywhere, and it works as expected.

**Review by bondydaa — APPROVED** [review]

**Comment by marktoman** [comment]
Just checking if I haven't accidentally removed something in the issue description, the PR reviewer checklist will be added by a reviewer, correct?

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/3069065/219793740-0c9a4727-af57-4bb3-ac75-3961c6f81382.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/3069065/219793818-58d18bc8-88ca-4127-87b6-4e229fd36ebe.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/3069065/219793885-e35760d4-913f-46d0-a2ab-736f4de7d09b.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/3069065/219793930-a9872ed9-959f-4094-a5fe-3743cfbbc06b.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/3069065/219793957-6789ad13-2092-4d22-b749-32ed00d5f1b3.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/3069065/219793986-fad87e2e-8ad1-4763-9ae0-d01daba16a01.mov

</details>

**Comment by mananjadhav** [comment]
> Just checking if I haven't accidentally removed something in the issue description, the PR reviewer checklist will be added by a reviewer, correct?

Thanks for the PR and the thorough updates @marktoman. I've reviewed the PR and completed the checklist. All good here @bondydaa.

**Comment by marktoman** [comment]
Can somebody please explain the process? Does this wait for somebody to assign an internal engineer?

**Comment by bondydaa** [comment]
sorry was OOO on Friday, taking a look.

**Pull request merged**
