### PR TITLE
fix: Individually selected expense rows in grouped reports don't have a background color applied to them.

### PR DESCRIPTION
**Pull request by Krishna2323**
### Fixed Issues
$ https://github.com/Expensify/App/issues/45190
PROPOSAL: https://github.com/Expensify/App/issues/45190#issuecomment-2221146368

### Tests
1. Click Search in bottom navigation
2. Click "Shared" > Click check box on any one of the grouped expenses
3. Verify selected item is highlighted with a background color

- [x] Verify that no errors appear in the JS console

### Offline tests
1. Click Search in bottom navigation
2. Click "Shared" > Click check box on any one of the grouped expenses
3. Verify selected item is highlighted with a background color

### QA Steps
1. Click Search in bottom navigation
2. Click "Shared" > Click check box on any one of the grouped expenses
3. Verify selected item is highlighted with a background color

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/3d4bdea5-170a-49b2-a9ac-7cdb98868d6c

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/3b736602-0fb1-4a2f-a5bb-8bc73dc95ebb

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/58797356-ffbc-4cd5-8514-3bb10f2fb4b1

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/94e4fabe-e15a-4917-ac2f-cd533a321eed

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/dc9fd88b-1316-4f47-86ae-2f21733dfccd

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/4c4ca639-74df-4b47-861a-d5e5552b38e1

</details>

### CODE REVIEW

**Comment by shawnborton** [comment]
Looking good! 

One thing we might consider doing - the idea is that each of these rows or groups on the search page has 12px of horizontal and vertical padding, as well as 12px of vertical gap between the items. So that means when we make it so that each row can be selectable with a full bleed background color, we end up using 12px of horizontal padding and 6px of vertical padding for each row item. 

That being said, that means the first item (the group name/report title) and the last expense in the group don't quite have enough padding to make the entire card feel as though it has 12px of vertical padding, so I think we need to also add 6px of vertical padding to the entire group, to give us this effect:
CleanShot 2024-07-15 at 08 00 08@2x

Let me know if that makes sense! cc @Expensify/design

**Comment by dannymcclain** [comment]
@shawnborton that makes sense to me! The `6px` value makes me slightly sad 😂 but I'm totally down to go that route.

**Comment by dannymcclain** [comment]
Totally. I don't either so I'm down to go with what you've suggested!

**Comment by shawnborton** [comment]
Going to create a test build for easier testing.

**Comment by shawnborton** [comment]
Looks like the padding for the rows is using 8px 12px but we need it to be 6px 12px. See my comment [here](https://github.com/Expensify/App/pull/45384#issuecomment-2227753125).

CleanShot 2024-07-17 at 08 44 08@2x

**Comment by shawnborton** [comment]
And then for the top portion, it looks like it's using 12px for padding, but it needs to be 12px (top) 12px (right) 6px (bottom) 12px (left):
CleanShot 2024-07-17 at 08 45 10@2x

**Comment by shawnborton** [comment]
Actually sorry, maybe a better approach is to:

Give the whole card wrapper a vertical padding of 6px:
CleanShot 2024-07-17 at 08 49 31@2x

Then for the header, it should get a padding of 6px vertical and 12px horizontal:
CleanShot 2024-07-17 at 08 50 12@2x

And then for the inner part of the header, we should give it a min-height of 40px (just on desktop) to match the rows below:
CleanShot 2024-07-17 at 08 50 44@2x

That should make this look identical to production, but keep the correct gaps/spacing for when rows are selected. Let me know if that all makes sense!

**Comment by shawnborton** [comment]
Sounds good, thanks for your understanding and let us know when we can test again!

**Comment by shawnborton** [comment]
This part is slightly off still:
CleanShot 2024-07-18 at 11 16 39@2x

The padding should be 6px 12px, not 8px 12px.

**Comment by shawnborton** [comment]
Awesome, going to rebuild the test builds.

**Comment by shawnborton** [comment]
This definitely feels good and correct on desktop.

On mobile, given that we are using a min-height for the report title now, I think we might consider taking out some of the bottom margin from the top header area... maybe reduce it to 6px if it has a report title below it?
CleanShot 2024-07-18 at 16 17 24@2x

But if not, 12px makes sense to maintain our 12px gaps:
CleanShot 2024-07-18 at 16 18 51@2x

Let me know if that makes sense.

**Comment by shawnborton** [comment]
Nice! Looks like we have a conflict here, but I think we're ready to get this into final review. Thanks for your patience as we've been working through feedback.

**Comment by shawnborton** [comment]
Nice, this is looking good on the test builds above.

**Comment by shawnborton** [comment]
Let's try to get this one over the finish line soon, thanks!

**Review by ishpaul777 — APPROVED** [review]

**Review by marcaaron — APPROVED** [review]

**Comment by marcaaron** [comment]
@shawnborton want to take a last look here before I merge?

**Comment by shawnborton** [comment]
I think we're all good to merge!

**Review by shawnborton — APPROVED** [review]

**Pull request merged**
