### PR TITLE
[HOLD Web-Expensify#35777] Convert currency code to symbol before displaying IOU messages

### PR DESCRIPTION
**Pull request by jasperhuangg**
**_NOTE TO REVIEWER: Probably easier to review this one [without the whitespace changes](https://github.com/Expensify/App/pull/13432/files?diff=split&w=1)_**

Need changes from https://github.com/Expensify/Web-Expensify/pull/35777

### Details
- We're updating any IOU report actions to be created with the currency code (before they were created with the currency symbol) both optimistically and in PHP. So `$100.00` becomes `USD100.00`
- Once we're about to display the report action in the front-end, we'll convert the currency code for the currency symbol so it always looks the same to the user (i.e. `USD100` gets converted back to `$100`).

### Fixed Issues

$ https://github.com/Expensify/App/issues/12573

#### Request Money
1. Sign into any account and navigate to any report with a user.
2. Click the "+" icon on the report action compose and select "Request Money".
3. Request using `CAD` or `AED`.
4. Verify that the currency symbols in messages for the IOU report action messages **_don't ever change_**. (See videos below for more context).
    - make sure they don't change when the amount in the IOU Preview updates.
5. Click on the IOU report action message to open the IOU Details modal. Verify that the currency symbol displayed in the IOU report action message there is also correct.

#### Send Money
1. Sign into any account and navigate to any report with a user.
2. Click the "+" icon on the report action compose and select "Send Money".
3. Request using `CAD` or `AED`.
4. Verify that the currency symbols in messages for the created report actions **_don't ever change_**. (See videos below for more context).
    - make sure they don't change when the amount in the IOU Preview updates.
5. Click on the IOU report action message to open the IOU Details modal. Verify that the currency symbol displayed in the IOU report action message there is also correct.

#### Split Bill
1. Sign into any account and navigate to any group chat with multiple participants.
2. Click the "+" icon on the report action compose and select "Split Bill".
3. Request using `CAD` or `AED`.
4. Verify that the currency symbols in messages for the created report actions **_don't ever change_**. (See videos below for more context).
    - make sure they don't change when the amount in the IOU Preview updates.

#### Cancelling a request
1. Sign into any account and navigate to any report with a user.
2. Click the "+" icon on the report action compose and select "Request Money".
3. Request using `CAD` or `AED`.
4. Verify that the currency symbols in messages for the created report actions **_don't ever change_**. (See videos below for more context).
    - make sure they don't change when the amount in the IOU Preview updates.
5. Click on the IOU report action message to open the IOU Details modal. Verify that the currency symbol displayed in the IOU report action message there is also correct.
6. Cancel the request by clicking "Cancel". Verify that the currency symbols in messages for the created report actions are correct. (`CA$` for `CAD`, `AED ` for `AED`)

#### Declining a request
1. Sign into any account and navigate to any report with a user.
2. Click the "+" icon on the report action compose and select "Request Money".
3. Request using `CAD` or `AED`.
4. Verify that the currency symbols in messages for the created report actions **_don't ever change_**. (See videos below for more context).
    - make sure they don't change when the amount in the IOU Preview updates.
5. Click on the IOU report action message to open the IOU Details modal. Verify that the currency symbol displayed in the IOU report action message there is also correct.
6. Sign into the other user's account and navigate to the same report. Open the IOU Details modal and decline the request. Verify that the currency symbols in messages for the created report actions are correct. (`CA$` for `CAD`, `AED ` for `AED`).

#### Settling up a request (elsewhere)
1. Sign into any account and navigate to any group chat with multiple participants.
2. Click the "+" icon on the report action compose and select "Split Bill".
3. Request using `CAD` or `AED`.
4. Verify that the currency symbols in messages for the created report actions **_don't ever change_**. (See videos below for more context).
    - make sure they don't change when the amount in the IOU Preview updates.
5. Click on the IOU report action message to open the IOU Details modal. Verify that the currency symbol displayed in the IOU report action message there is also correct.
6. Sign into the other user's account and navigate to the same report. Open the IOU Details modal and select "Settle up elsewhere". Verify that the currency symbols in messages for the created report actions are correct. (`CA$` for `CAD`, `AED ` for `AED`).

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/31285285/206640844-27443c83-a3f6-4e27-92f1-60bccbf33b71.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/31285285/206386747-fd0605a0-4dc8-4f13-83b3-9e112792ef09.mov

</details>

<details>

<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/31285285/206386930-16df9952-b983-47e4-880a-50cc3062129d.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/31285285/206641039-8e71107e-dbbe-4426-93c7-4718188a0d24.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/31285285/206386984-2b32a22e-b278-4fbd-8f53-9eb26a34b5b3.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/31285285/206387035-230cca00-ba17-4df0-95a8-a7b9d92f6bfd.mov

</details>

### CODE REVIEW

**Comment by jasperhuangg** [comment]
Hey @puneetlath! Also going to request you for review on this one since you were PB'd for the associated [Web PR](https://github.com/Expensify/Web-Expensify/pull/35777), thanks!

I'll let you know when this one's fully tested and ready for review

**Comment by jasperhuangg** [comment]
@puneetlath fully tested on my end and ready to go!

**Comment by sobitneupane** [comment]
@jasperhuangg Is this PR ready for C+ review? Or Should I wait for Web-Expensify#35777?

**Comment by puneetlath** [comment]
@sobitneupane you won't be able to test it yet. Will need to wait for Web-Expensify#35777

**Comment by jasperhuangg** [comment]
@sobitneupane yes, we need to wait for https://github.com/Expensify/Web-Expensify/pull/35777 to go out on production before you can test. For now it can only be tested internally.

**Comment by jasperhuangg** [comment]
Putting this back on draft as I'm realizing there might actually be a way to simplify what I'm doing here

**Comment by jasperhuangg** [comment]
Done writing testing steps, gonna focus on screen recordings now.

**Comment by jasperhuangg** [comment]
Tested and ready for review!

**Comment by jasperhuangg** [comment]
Closing this out since the issue is solved in https://github.com/Expensify/Web-Expensify/pull/35845

**Pull request closed without merging**
