### PR TITLE
Use proper width for Cancel/Decline Button Text

### PR DESCRIPTION
**Pull request by aman-atg**
### Details
([Comment](https://github.com/Expensify/App/issues/4234#issuecomment-886983439))

### Fixed Issues

$ #4234 

### Tests || ### QA Steps
1. Login to New Expensify
2. Change language to Spanish
3. Request money from someone or Go to a chat where money is requested from you
4. Click on the amount or view details link
5. button text will not look unusual (Cancel/Decline) 

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

image

#### Mobile Web

mobile

#### Desktop
image

#### iOS
image

#### Android

mTest

### CODE REVIEW

**Review by tgolen — APPROVED** [review]
Looks great, and just like the proposal!

Can you please complete the rest of the platform testing before I merge this?

**Comment by aman-atg** [comment]
> Can you please complete the rest of the platform testing before I merge this?

@tgolen , the issue isn't happening on Android. And Sorry, I'm yet to get a macbook for other two platforms.

**Comment by tgolen** [comment]
OK, you still need to get an Android screenshot to show there are no regressions. I can test it out on iOS and the desktop app for you (I won't get to it until tomorrow).

**Comment by tgolen** [comment]
All right, I tested it on desktop, and ran into an issue. It looks like this corrupted the width of the dropdowns somehow. Here is the preferences screen on `main` and on this branch. Not only is the width different, but the text is now centered when it wasn't before (maybe this is fixed on main and you just need to merge that into your branch?).

# main
image

# this branch
image

**Comment by aman-atg** [comment]
> (maybe this is fixed on main and you just need to merge that into your branch?).

That must be the case as the removed style is not being used anywhere else.

**Comment by aman-atg** [comment]
Added a screenshot from android.

**Comment by tgolen** [comment]
Well, I was able to do it today after all! iOS looks good. I verified that when I merge `main` into this branch, it fixes that layout on the preferences page. Gonna go ahead and merge.

**Comment by tgolen** [comment]
once the tests are done

**Pull request merged**
