### PR TITLE
Ios  conversation   offline   save changes button is disabled when opened to edit the comment for the second time #11822

### PR DESCRIPTION
**Pull request by furkanuzundev**
### Details
The Save changes button is disabled when it was opened for the second time to edit the message.The screenshots in the below are includes i edit the message when i'm offline edit open the second time.

### Fixed Issues
$ https://github.com/Expensify/App/issues/11822
PROPOSAL: [11822(comment)](https://github.com/Expensify/App/issues/11822#issuecomment-1297627862)

### Tests

1. Log in an any account
2. Disable the internet connection in the main testing device
3. Click/Tap on the Pencil icon to activate the edit message box
4. Edit the message to something new and save the changes
5. Open the message editing function again
6. It's working as we expect that save button is disabled

- [x] Verify that no errors appear in the JS console

### QA Steps
1. Log in an any account
2. Disable the internet connection in the main testing device
3. Click/Tap on the Pencil icon to activate the edit message box
4. Edit the message to something new and save the changes
5. Open the message editing function again
6. It's working as we expect that save button is disabled

- [x] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

> **Mobile Web - Chrome**
> 
>  https://user-images.githubusercontent.com/30953070/199968743-82d3227f-1bd1-4176-b858-93ce40f8475a.mov

> **Mobile Web - Safari**
> 
>  https://user-images.githubusercontent.com/30953070/199968778-227dc445-0af3-4903-83f6-699b6daadceb.mov

> **Desktop**
> 
>   https://user-images.githubusercontent.com/30953070/199968861-9f479d4a-d78f-446c-bfbd-90998733841a.mov

> iOS
> 
>  https://user-images.githubusercontent.com/30953070/199968879-f821cc2d-5b20-468f-af2a-6c397efb512c.mov

> **Android**
> 
> https://user-images.githubusercontent.com/30953070/199969419-df7c837a-9a94-4e5d-8ee7-782ac56f26ac.mov

### CODE REVIEW

**Comment by furkanuzundev** [comment]
> _**I have read the CLA Document and I hereby sign the CLA**_

**Comment by dangrous** [comment]
Hey @furkanuzundev (and @eVoloshchak), quick update! I'm getting one question about this issue/PR answered internally and then will be back with a review shortly - I just wanted to check in and let you know where I was.

**Comment by furkanuzundev** [comment]
@dangrous Sure! I'm waiting.

**Comment by dangrous** [comment]
Okay I'm back! So here's the deal - given that `OfflineWithFeedback` is used in many many places, the consensus was that we shouldn't add a prop to that for this one use case.

I figured out an alternate way of dealing with this issue, though, that's much more contained. What if we edit [this line](https://github.com/Expensify/App/blob/13995adaee720fb0057e89a130bcc58af36a16c7/src/pages/home/report/ReportActionItem.js#L198) in `ReportActionItem`:

```diff
<OfflineWithFeedback
  onClose={() => {
    if (this.props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
      ReportActions.deleteOptimisticReportAction(this.props.report.reportID, this.props.action.clientID);
    } else {
      ReportActions.clearReportActionErrors(this.props.report.reportID, this.props.action.sequenceNumber);
    }
  }}
- pendingAction={this.props.action.pendingAction}
+ pendingAction={this.props.draftMessage ? null : this.props.action.pendingAction}
  errors={this.props.action.errors}
  errorRowStyles={[styles.ml10, styles.mr2]}
>
```

That should be all we need! This will remove any visual effects on the edit section when it's open, and otherwise make no changes to the rest of the app (that I'm aware of). `this.props.draftMessage` is already accessible by `ReportActionItem`, and is only passed in this particular case, so there shouldn't be any weirdness elsewhere.

Let me know what you think (and if you can test, that would be amazing too)! If you both are in agreement, @furkanuzundev you can go ahead and update the PR with this change and we can move forward from there.

**Comment by furkanuzundev** [comment]
Yes, I've tested and looked at it. It's a shorter and more efficient way.
We can work through that. If approved, I can update the PR with the current change.

**Comment by eVoloshchak** [comment]
@dangrous, your change looks good to me as well, tested it working on iOS. And imo it is more self-explanatory, than having this prop inside the condition on `OfflineWithFeedback.js`, which is great.

@furkanuzundev, you can go ahead and update the PR

**Comment by furkanuzundev** [comment]
updated

**Comment by eVoloshchak** [comment]
<details><summary><h4>Screenshots</h4></summary>

**Web**


https://user-images.githubusercontent.com/9059945/199946501-efdc074b-036f-4e42-aa0a-e3f0825c8f81.mov





**Mobile Web - Chrome**




https://user-images.githubusercontent.com/9059945/199946929-9f5fa18a-dd5c-4baf-9f6a-dd798cf33bc9.mp4






**Mobile Web - Safari**




https://user-images.githubusercontent.com/9059945/199947207-47ac55c8-54bf-4872-8793-da05dd53c094.mov




**Desktop**


https://user-images.githubusercontent.com/9059945/199947166-99703409-5d8e-4c02-b439-6f5ab0dbd127.mov






iOS


https://user-images.githubusercontent.com/9059945/199947228-3157d133-9cb1-4567-8bd4-10a703a1ed51.mov





**Android**



https://user-images.githubusercontent.com/9059945/199947256-857f2d40-f195-448f-ac4f-c006e308cf0e.mp4




</details>

<details><summary><h4>PR Reviewer Checklist</h4></summary>

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

**Comment by eVoloshchak** [comment]
@furkanuzundev, the code looks good and tests well, there are a couple of small issues with the issue description

- change the link formatting for PROPOSAL, it should look like this
Screenshot 2022-11-04 at 12 11 39

- include videos of testing tests performed on all platforms instead of screenshots (like [this](https://github.com/Expensify/App/issues/11822#issue-1408323265) or [this](https://github.com/Expensify/App/pull/12426#issuecomment-1303209663))

**Comment by furkanuzundev** [comment]
@eVoloshchak 
I updated the link formatting.
Do i need to record video again?

**Comment by eVoloshchak** [comment]
@furkanuzundev I'm talking about the [issue description](https://github.com/Expensify/App/pull/12426#issue-1434639905), 'Screenshots" section. You've uploaded screenshots, but the testing steps can be best shown with a video, so please replace the screenshots with videos

**Comment by furkanuzundev** [comment]
@eVoloshchak I have changed screenshots to video records that includes test steps.

**Review by dangrous — APPROVED** [review]
Looks good! Will merge once @eVoloshchak confirms!

**Review by eVoloshchak — APPROVED** [review]

**Comment by eVoloshchak** [comment]
@dangrous, looks good to me too!

**Comment by furkanuzundev** [comment]
This will be my first PR. We are witnessing a historical moment. :)

**Comment by dangrous** [comment]
Congrats, @furkanuzundev , I've merged it in!

Great job getting your first Expensify/App pull request over the finish line!

I know there's a lot of information in our contributing guidelines, so some points to take note of:

1. Once your PR is merged, you can be hired for another issue. Once you've completed a few issues, we may start hiring you for more than one issue at a time.
2. Once your PR is deployed to our staging servers, it will undergo quality assurance (QA) testing. If we find that this doesn't work as expected or causes a regression, you'll be responsible for fixing it. Typically we would revert this PR and give you another chance to create a similar PR without causing a regression. (I don't imagine this will happen with this PR, but it's something to be aware of)
3. Once your PR is deployed to production, we start a 7-day timer. After it has been on production for 7 days without causing any regressions, then we pay out the Upwork job.

So it might take a while before you're paid for your work, but we typically post multiple new jobs every day, so there's plenty of opportunity. I hope you've had a positive experience contributing to this repo!

**Comment by dangrous** [comment]
Not an emergency, all checks passed.

**Comment by furkanuzundev** [comment]
Got it @dangrous.Thanks!

**Pull request merged**
