### PR TITLE
Update internal dev partnerID and password

### PR DESCRIPTION
**Pull request by timszot**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
Updates the example `.env` file to use the `chat-expensify-com` partner name and password.
cc: @AndrewGable @NikkiWines 

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com/Expensify/Expensify/issues/157714

### Tests

This requires a new partner row added to your local VMs `partners` table. This can be added with the following steps:
1. run `Expensidev/scripts/sql.sh`
2. run this query: `INSERT OR IGNORE INTO partners ( created, partnerID, partnerName, partnerPassword, partnerKey ) VALUES ( '2021-03-18 00:00:00', 83, 'chat-expensify-com', 'DD1431EB9E11F0071EC05C24E9CB2FD595B1ED75', 'asdf,fdsa');`

Then edit your `.env` file using the new values from `.env.example` in the PR.
1. run `npm run web`
  1a. sign out of any existing accounts
2. sign in with a new email so a new account gets created
3. Validate the account with `Expensidev/scripts/clitools.sh validator:account`
4. Go back to e.cash and verify you can sign in with the new account and dev password
5. sign out
6. sign back in with an existing account and verify it works

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by timszot** [comment]
The Auth PR to add this partner when creating a new VM DB is [here](https://github.com/Expensify/Auth/pull/5380).

Once merged I'll send out an email detailing the change and the steps required to update everyone's VM DB with the new partner row.

**Review by AndrewGable — APPROVED** [review]

**Review by marcaaron — APPROVED** [review]
LGTM

**Comment by marcaaron** [comment]
The password here in the `.env.example` is `e21965746fd75f82bb66` but the one in the Auth PR is `DD1431EB9E11F0071EC05C24E9CB2FD595B1ED75`

Is that right?

I'm having trouble logging in on e.cash local after applying these changes.

**Comment by marcaaron** [comment]
Ok looks good and tests well for me. There is one quick caveat that my `partners` table had an entry for `greenhouse` using the the same partnerID so I had to update it to get this working.

**Comment by timszot** [comment]
> There is one quick caveat that my partners table had an entry for greenhouse using the the same partnerID so I had to update it to get this working.

I'll make sure to add a bit about this to the email I'll send out

**Comment by marcaaron** [comment]
🎉  thanks for this change!

**Comment by isagoico** [comment]
Hello @marcaaron! This one looks like it's internal QA. Can you confirm? If so, let me know when it's tested so I can check it off the deploy list.

**Comment by marcaaron** [comment]
This only affects development so I think can be checked off.

**Pull request merged**
