### PR TITLE
Make push notifications navigate to the correct chat - iOS

### PR DESCRIPTION
**Pull request by neil-marcellini**
cc @roryabraham 
### Details

When push notifications are tapped the correct chat should open. I don't have permissions to create a production build ([slack conversation](https://expensify.slack.com/archives/C03TQ48KC/p1643744168322619)) so I need one of the @Expensify/mobile-deployers  to test this change for me. A production build is needed for testing push notifications when the app is closed to accurately reflect the way the app opens without first loading JS from the metro bundler.
### Fixed Issues

$ https://github.com/Expensify/App/issues/6079

### Tests

1. Create a local production build `npm run ios-build` and run the app on your iOS device
2. Sign into the iOS app with account A
3. Run web `npm run web`
4. Sign in on web with account B
5. Put the app in the background by going to the home screen, then locking your phone
6. Send a message from account B to account A on web
7. Tap the notification that should show up on you phone
8. Ensure that the correct chat opens
9. Close the app completely by clearing it from multi-tasking
10. Repeat steps 6-8

If any of these steps don't work please let me know.

- [ ] Verify that no errors appear in the JS console

### QA Steps

Test steps 2-10
- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

#### Web

Screen Shot 2022-02-08 at 10 01 02 AM

#### Mobile Web

Simulator Screen Shot - iPhone 13 - 2022-02-08 at 10 05 29

#### Desktop

Screen Shot 2022-02-08 at 10 10 03 AM

#### iOS

Simulator Screen Shot - iPhone 13 - 2022-02-08 at 09 58 44

#### Android

Screenshot_1644344036

### CODE REVIEW

**Comment by tgolen** [comment]
Just a quick FYI that https://github.com/orgs/Expensify/teams/mobile-deployers is for our old mobile app, not this new one :D I think Pullerbear is OK

**Comment by tgolen** [comment]
Oh sorry, I did not read the description 🤦

**Review by sketchydroide — APPROVED** [review]

**Comment by sketchydroide** [comment]
I'm currently getting this error when building the app
` error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "368M544MTT" with a private key was found. (in target 'NewExpensify' from project 'NewExpensify')`
I'll talk with @AndrewGable when he gets online, so I can fix the certificate issue.

**Comment by AndrewGable** [comment]
The cert and private key should be in 1Password!

**Comment by neil-marcellini** [comment]
Thanks guys, please let me know when you get a chance to test it if it works.

**Comment by sketchydroide** [comment]
still trying to build that file, the certificate one has been acomplished, but a new hurdle appears... 😓 
```sh: line 1:  5618 Segmentation fault: 11  xcodebuild -workspace ./ios/NewExpensify.xcworkspace -scheme NewExpensify -destination 'generic/platform=iOS' -archivePath /Users/andrefonseca/Library/Developer/Xcode/Archives/2022-02-09/New\ Expensify\ 2022-02-09\ 17.13.15.xcarchive archive```
I'll try to overcome that one tomorrow, sorry

**Comment by sketchydroide** [comment]
I managed to Archive the app, but it doesn't run in my device, keep getting a `This app cannot be installed because its integrity could not be verified` 
I tried also archiving from Xcode and distributing it manually from there. But got the same result. I think the only step now is for someone else to try, or upload the build to AppStoreConnect and try installing from testflight.
We would need to let people know not to test that one, but it would probably work.

**Comment by neil-marcellini** [comment]
Ok thanks for giving it a shot. I'll request a review from another mobile deployer to see if they can get it to work. If not could you please upload it to TestFlight? Please let me know if I can help with that in any way.

**Comment by sketchydroide** [comment]
I don't think that will add anyone else, I asked in #engineering chat for help.

**Comment by neil-marcellini** [comment]
> I don't think that will add anyone else, I asked in #engineering chat for help.

Oh right because you are already assigned. Thanks for doing that.

**Comment by sketchydroide** [comment]
we haven't had any takers to help, if we don't have any until the end of the day I think I'm going to create a test flight build so we can test it.

**Comment by Julesssss** [comment]
Sorry, I have been meaning to help but not sure if I'll have time today

**Comment by sketchydroide** [comment]
No worries Jules :)

**Comment by sketchydroide** [comment]
I'm going to merge this, and then we can test it, if it does not work we can revert it or create a new PR to fix it

**Comment by alex-mechler** [comment]
I don't have an iOS device, asking for someone to test on slack https://expensify.slack.com/archives/C03TQ48KC/p1645560250530479

**Comment by kbecciv** [comment]
Hello @neil-marcellini! The issue https://github.com/Expensify/App/issues/6079  was still reproducing in our end, push notifications are not opening correct chat. 

https://user-images.githubusercontent.com/93399543/155576850-a8b5d405-cb1b-4ad5-af35-98ae6fcadbd3.MP4

**Comment by roryabraham** [comment]
Hmmm, in that case it looked like the drawer was still open, so it's hard to say if it linked to the correct chat. Regardless, I think we should probably revert this and try again. Thoughts?

**Comment by sketchydroide** [comment]
I think so @roryabraham

**Pull request merged**
