### PR TITLE
[HOLD on #33756, #34080] TS migration of `MultiGestureCanvas`, `Lightbox`, `AttachmentCarouselPager` components

### PR DESCRIPTION
**Pull request by chrispader**
@ntdiary 

### Details

Adds types for `MultiGestureCanvas`, `Lightbox` and many attachment/image related components. This PR also includes some minor code improvements in `Lightbox` for simplicity

Based on https://github.com/Expensify/App/pull/33756. Check [this](https://github.com/margelo/expensify-app-fork/compare/%40chrispader/restructure-multi-gesture-canvas...margelo:expensify-app-fork:%40chrispader/attachment-gallery-ts-migration) for actual diff

Holding on https://github.com/Expensify/App/pull/33756 as well as https://github.com/Expensify/App/pull/34080 if possible..

### Fixed Issues

$ https://github.com/Expensify/App/issues/24969
$ https://github.com/Expensify/App/issues/25152
PROPOSAL:

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

[android.webm](https://github.com/Expensify/App/assets/20173411/eba80064-fe68-4866-b578-e35ade54f20b)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/20173411/92783d3a-b534-4eb7-807b-23eefa1f6525

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by chrispader** [comment]
@blazejkustra @fabioh8010 @hayata-suenaga hey guys just a heads up, that i've already starting migrating all of the "Attachment Gallery" components to TS, since i've mostly authored the components and worked on it a lot. Some of the logic involves some tricky typings from other libraries.

Feel free to chime in here, otherwise i'm gonna finish this PR next week!

**Comment by blazejkustra** [comment]
@chrispader Attachment directory is already worked on [here](https://github.com/Expensify/App/pull/32129), let's not do the work twice 😄 cc @kubabutkiewicz 

However I'm fine with you working on it as you authored it and have the most context, just let us know once it's ready so me or @fabioh8010 can review it before making this PR `ready for review`.

**Comment by fabioh8010** [comment]
Hey @chrispader, I spoke with @kubabutkiewicz and he is okay with closing his PR and letting you do the migration here. But  could you explain us why this migration is being doing separately, e.g. are there any other reasons besides the migration itself?

We would like to reminder that, at the moment, TS migrations done outside of the TS migration team should be communicated in advanced to avoid situations just like this one.

**Comment by chrispader** [comment]
Sorry for the misunderstanding. I didn't want @kubabutkiewicz to shut down his PR, it's fine if he continues :)

Just thought that i might want to migrate at least `MultiGestureCanvas` and `Lightbox`, since i exclusively wrote it.

Also fine, if the TS team works on that too :)

**Comment by fabioh8010** [comment]
No problem @chrispader ! I think is best if you continue with this PR since you worked on in the past like you said before. And looks like `MultiGestureCanvas` and `Lightbox` are new components and therefore aren't tracked by us yet, so it's all fine for me to you continue with the work here.

**Comment by blazejkustra** [comment]
@chrispader Just keep us posted so we can review before PR is ready for C+ review 👍

**Comment by blazejkustra** [comment]
@chrispader Let us know if you have any TS related questions, always happy to help 😄 

Could you also link these issues in PR description? 
- https://github.com/Expensify/App/issues/24969
- https://github.com/Expensify/App/issues/25152

Also, are you planning to migrate whole Attachments catalog? (AttachmentCarousel and AttachmentView)

**Comment by chrispader** [comment]
> @chrispader Let us know if you have any TS related questions, always happy to help 😄
> 
> Could you also link these issues in PR description?
> 
> * [[TS migration] Migrate 'Attachments' component to TypeScript #24969](https://github.com/Expensify/App/issues/24969)
> * [[TS migration] Migrate 'AttachmentCarousel' component to TypeScript #25152](https://github.com/Expensify/App/issues/25152)
> 
> Also, are you planning to migrate whole Attachments catalog? (AttachmentCarousel and AttachmentView)

if you have somebody to do all of the attachment components, they can take that. I'd be mostly/only focussing on `MultiGestureCanvas` and `Lightbox`

**Comment by chrispader** [comment]
> @chrispader Let us know if you have any TS related questions, always happy to help 😄
> 
> Could you also link these issues in PR description?
> 
> * [[TS migration] Migrate 'Attachments' component to TypeScript #24969](https://github.com/Expensify/App/issues/24969)
> * [[TS migration] Migrate 'AttachmentCarousel' component to TypeScript #25152](https://github.com/Expensify/App/issues/25152)
> 
> Also, are you planning to migrate whole Attachments catalog? (AttachmentCarousel and AttachmentView)

@blazejkustra @fabioh8010 i'm also gonna migrate the `CarouselItem` component, if that's alright?

During the previous TS migration i found some improvements in how the attachment carousel components are structure and `CarouselItem` typings also depend heavily on the pager logic...

**Comment by chrispader** [comment]
> During the previous TS migration i found some improvements in how the attachment carousel components are structued and `CarouselItem` typings also depend heavily on the pager logic...

Actually, let's not migrate `CarouselItem` in this PR. I've created https://github.com/Expensify/App/pull/34080 which improves the pager context and a lot of code in attachment carousel components. I can add the changes to typings there after this PR is merged

**Comment by chrispader** [comment]
> > @blazejkustra @fabioh8010 i'm also gonna migrate the `CarouselItem` component, if that's alright?
> > During the previous TS migration i found some improvements in how the attachment carousel components are structurde and `CarouselItem` typings also depend heavily on the pager logic...
> 
> You can use `@ts-expect-error` if something is blocking you, from TS guidelines:
> 
> * The TS issue I'm working on is blocked by another TS issue because of type errors. What should I do?
>   In order to proceed with the migration faster, we are now allowing the use of `@ts-expect-error` annotation to temporally suppress those errors and help you unblock your issues. The only requirements is that you MUST add the annotation with a comment explaining that it must be removed when the blocking issue is migrated, e.g.:
>   ```tsx
>   return (
>       <MenuItem
>           // @ts-expect-error TODO: Remove this once MenuItem (https://github.com/Expensify/App/issues/25144) is migrated to TypeScript.
>           wrapperStyle={styles.mr3}
>           key={text}
>           icon={icon}
>           title={text}
>           onPress={onPress}
>       />
>   );
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   **You will also need to reference the blocking issue in your PR.** You can find all the TS issues [here](https://github.com/orgs/Expensify/projects/46).

OK got it, thanks! Though in this case, the reason is not any blocking issue, but the fact that inferable types will automatically get stripped out by ESLint, but if i don't define the type for `NUMBER_OF_CONCURRENT_LIGHTBOXES`, TS will throw an error.

For this reason i added the type and disable the ESLint warning for this line. Can you check if that's what we should do here?

**Comment by blazejkustra** [comment]
Looking at the code I'm not quite sure, does this PR only migrates components to TS or also you refactor these components?

>  let us know once it's ready so me or @fabioh8010 can review it before making this PR ready for review.

I see that you marked this PR as ready for review. Should me/Fabio have a look? @chrispader 

> OK got it, thanks! Though in this case, the reason is not any blocking issue, but the fact that inferable types will automatically get stripped out by ESLint, but if i don't define the type for NUMBER_OF_CONCURRENT_LIGHTBOXES, TS will throw an error.

Your solution looks good to me 😄 
```ts
const NUMBER_OF_CONCURRENT_LIGHTBOXES: number = 3;
```

**Comment by chrispader** [comment]
> Looking at the code I'm not quite sure, does this PR only migrates components to TS or does it also involve refactoring these components?

It involves some small refactorings of `Lightbox`, but let me quickly move them to the other PR i'm working on, so that we can only treat TS migration here.

**Comment by chrispader** [comment]
> > Looking at the code I'm not quite sure, does this PR only migrates components to TS or does it also involve refactoring these components?
> 
> It involves some small refactorings of `Lightbox`, but let me quickly move them to the other PR i'm working on, so that we can only treat TS migration here.

@blazejkustra @fabioh8010 just reverted the refactorings. This is ready for review, though the branch is based on another PR, so the diff also contains changes from that other PR.

There's a link to [the actual diff](https://github.com/margelo/expensify-app-fork/compare/%40chrispader/restructure-multi-gesture-canvas...margelo:expensify-app-fork:%40chrispader/attachment-gallery-ts-migration) in the PR description though

**Comment by blazejkustra** [comment]
Let's put this PR in a draft and wait for the other PR to be merged first, wdyt? @chrispader

**Comment by s77rt** [comment]
Please tag me once this becomes read to review

**Comment by chrispader** [comment]
Closing in favor of #33756. I merged TS migration changes into the other PR, so that we don't break TS checks on `main`

**Pull request closed without merging**
