### PR TITLE
Show default workspace rooms

### PR DESCRIPTION
**Pull request by neil-marcellini**
### Details

Make the default #announce and #admins rooms show up immediately after creating a new workspace. Also, when the workspace is deleted update the room names to show that they have been deleted. For more context see the design doc [here](https://docs.google.com/document/d/1xabico6VzVd_biN9qw2LFdLW6Lbr9wpN36etbHTeX8c/edit#heading=h.bsme0due1a2x). 

**Deleting workspaces currently doesn't work on IOS and Android. See the issue [here](https://github.com/Expensify/App/issues/7361).**
### Fixed Issues

$ https://github.com/Expensify/App/issues/5946

### Tests

1. Log in with a brand new account
2. Create a workspace from the green plus button at the bottom left.
3. Check for the #announce and #admins rooms in the left hand navigation.
#### For all platforms except iOS and Android:
4. Go to Settings > Workspace
5. Click the three dots in the header and select delete workspace, and confirm delete.
6. Confirm that the room names change to #announce (deleted) and #admins (deleted)

- [ ] Verify that no errors appear in the JS console

### QA Steps

Same as tests above.
- [ ] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

web

#### Mobile Web

mobile-web

#### Desktop

desktop

#### iOS

IOS

#### Android

android

### CODE REVIEW

**Review by nickmurray47 — COMMENTED** [review]
Following QA steps, seems like creating a new workspace has doubled the default workspace rooms. 

Screen Shot 2022-01-21 at 2 13 35 PM

**Comment by neil-marcellini** [comment]
> Following QA steps, seems like creating a new workspace has doubled the default workspace rooms.
> 
> Screen Shot 2022-01-21 at 2 13 35 PM
@nickmurray47
Based on the design doc I think that is the expected behavior. Each work space gets its own #announce and #admins rooms.  You can see in the subtext which workspace they belong to. I do think it's a bit clunky to have multiple default rooms especially if they both have a default workspace name, but we can always change that down the road. How do you think that should be handled?

I also edited the testing steps to clarify that a brand new account should be used and one workspace should be created with the green plus button.

**Comment by nickmurray47** [comment]
ok, thanks for the explanation @neil-marcellini! The code lgtm as far as I can tell but also going to loop in the design doc author just to confirm this is the expected behavior.

> I do think it's a bit clunky to have multiple default rooms especially if they both have a default workspace name

Yeah, so there's going to be default rooms for the user when they sign up which will have the same names as the default rooms for the first workspace that's created? It was confusing to me on first run-through.

**Comment by neil-marcellini** [comment]
> Yeah, so there's going to be default rooms for the user when they sign up which will have the same names as the default rooms for the first workspace that's created? It was confusing to me on the first run-through because I'd expect the default rooms for a user to not exist at all then, i.e. the default rooms should only be there once a workspace is created.

When I make new accounts there are no default rooms and no workspace until you press the button to create a workspace. Could you please test again?

**Comment by yuwenmemon** [comment]
Yeah @nickmurray47 I would guess those default rooms are from some other corporate policy that account has open. They're not getting created with new accounts, right?

**Review by yuwenmemon — APPROVED** [review]

**Comment by nickmurray47** [comment]
> When I make new accounts there are no default rooms and no workspace until you press the button to create a workspace. Could you please test again?

Interesting, will re-test again and see if there's any difference. This was with a brand-new account so would assume it was not under any old policies.

**Review by nickmurray47 — APPROVED** [review]
re-tested and QA worked well!

**Comment by mvtglobally** [comment]
@neil-marcellini  Should it be tested on All platforms?

**Pull request merged**
