### PR TITLE
Page do scroll to bottom when send message in public room 

### PR DESCRIPTION
**Pull request by luckydaniel1993**
@akinwale 

### Explanation of Change
I've wrapped the `scrollToBottomForCurrentUserAction` function with `InteractionManager.runAfterInteractions`.

### Fixed Issues
$ https://github.com/Expensify/App/issues/52208.
PROPOSAL: https://github.com/Expensify/App/issues/52208#issuecomment-2470540762

### Tests
1. Log in with gmail.
2. Open #expensify-roadmap public room ([https://staging.new.expensify.com/r/2091104345528462](https://staging.new.expensify.com/r/2091104345528462))
3. Scroll to the top of the page
4. Send a message
5. Verify that: Page will scroll to bottom

- [x] Verify that no errors appear in the JS console

### QA Steps
1. Log in with gmail.
2. Open #expensify-roadmap public room ([https://staging.new.expensify.com/r/2091104345528462](https://staging.new.expensify.com/r/2091104345528462))
3. Scroll to the top of the page
4. Send a message
5. Verify that: Page will scroll to bottom

- [x] Verify that no errors appear in the JS console

### PR Author Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/bbf4b3dd-74e9-4a31-bd09-350563cdd6c9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/680d5fb3-e37e-4c0a-ae14-699c799f675a

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/5f8dfed1-8654-48c5-b79b-e231f4ac53c4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/0638d51e-d95b-4760-b2d4-251509526ad4

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/f7f269a5-2bd1-41b1-adaa-482352ae433c

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/eae4fc2c-d74c-4556-bffc-50996f6d9c04

</details>

### CODE REVIEW

**Comment by akinwale** [comment]
@Anaslancer Please check all the boxes in the checklist.

**Review by akinwale — APPROVED** [review]
LGTM.

**Review by akinwale — CHANGES_REQUESTED** [review]
@Anaslancer

You need to complete the following in the initial post.
* Complete the checklist, meaning check all the boxes
* Include your testing videos / screenshots for each platform

**Comment by aldo-expensify** [comment]
@Anaslancer bump on https://github.com/Expensify/App/pull/52955#pullrequestreview-2463987825

**Comment by aldo-expensify** [comment]
Hey @Anaslancer 👋 , are planning to finish the PR here?, it was pretty closed to be ready for merging, we just need you to follow the process of including the testing videos/screenshots.

**Comment by Anaslancer** [comment]
@aldo-expensify I will add the videos in a few days. Thanks

**Comment by aldo-expensify** [comment]
> @aldo-expensify I will add the videos in a few days. Thanks

Does a "few days" mean this week? or can it be longer

**Comment by Anaslancer** [comment]
It will be this week, I am waiting my new mac.

**Comment by aldo-expensify** [comment]
> It will be this week, I am waiting my new mac.

Ah, that is great, thanks for the information!

**Comment by akinwale** [comment]
@Anaslancer Any updates here?

**Comment by Anaslancer** [comment]
I am getting this error when npm run android;
```
Could not determine the dependencies of task ':react-native:packages:react-native:ReactAndroid:hermes-engine:configureBuildForHermes'.
> Could not create task ':react-native:packages:react-native:ReactAndroid:hermes-engine:installCMake'.
   > Could not find sdkmanager executable.
```

**Comment by akinwale** [comment]
> I am getting this error when npm run android;
> 
> ```
> Could not determine the dependencies of task ':react-native:packages:react-native:ReactAndroid:hermes-engine:configureBuildForHermes'.
> > Could not create task ':react-native:packages:react-native:ReactAndroid:hermes-engine:installCMake'.
>    > Could not find sdkmanager executable.
> ```

@Anaslancer Make sure you have your ANDROID_HOME environment variable set. You would also need to install the Android SDK build tools and platform tools (if not yet installed) on Android Studio. Launch Android Studio > Settings > Languages & Framework > Android SDK, select the SDK tools tab and then choose the missing dependencies to install.

**Comment by Anaslancer** [comment]
image

**Comment by Anaslancer** [comment]
image

**Comment by akinwale** [comment]
> image

Check under the SDK Tools tab.

**Comment by Anaslancer** [comment]
image

**Comment by akinwale** [comment]
@Anaslancer You can ask for guidance on this in the #expensify-open-source Slack channel if you are unable to resolve the problem.

**Comment by Anaslancer** [comment]
But I don't have slack account for Expensify

**Comment by Anaslancer** [comment]
I requested before but they said they can't accept. Let me request again?

**Comment by Anaslancer** [comment]
Finally, I figured out we can't use Windows for android. I built it on MacOS

**Review by akinwale — APPROVED** [review]
LGTM.

**Comment by aldo-expensify** [comment]
Nice, thank you!

**Review by aldo-expensify — APPROVED** [review]

**Comment by aldo-expensify** [comment]
Could you be missing a dependency? did you try running `npm install`?

**Comment by Anaslancer** [comment]
Nope, I will try now

**Comment by Anaslancer** [comment]
I am going to have a travel, and will fix once back.

**Pull request merged**
