### PR TITLE
[No QA] Update staging from main

### PR DESCRIPTION
**Pull request by roryabraham**
cc @tgolen 

### Details
Come from [this comment](https://github.com/Expensify/Expensify.cash/issues/4060#issuecomment-881518245)

### Fixed Issues
$ https://github.com/Expensify/Expensify.cash/issues/4060

### Tests
1. Merge this PR. I don't expect a staging deploy to occur.
1. Unlock and relock the `StagingDeployCash`.
1. A staging deploy should occur.
1. Hopefully nothing breaks, because this is something outside the normal flow. 🙃 

### QA Steps
No QA.

### Tested On

n/a – GitHub only.

### CODE REVIEW

**Review by tgolen — APPROVED** [review]
OK, let's do it.

**Comment by roryabraham** [comment]
As expected, no staging deploy occurred. The above comment is not 100% accurate, but we don't need to worry about that right now.

**Comment by roryabraham** [comment]
Oof, I think this was backwards 🤦

**Comment by roryabraham** [comment]
We merged staging into main, not the other way around. That was not what I meant to do... 😓

**Comment by roryabraham** [comment]
Sorry for the inconvenience @tgolen, but I think now the best thing to do is to create a normal PR to fix the issue on main and then CP it to staging.

**Pull request merged**
