### PR TITLE
[CP Staging] Revert "Defer local updates if there are missing updates and only call `GetMissingOnyxMessages` once"

### PR DESCRIPTION
**Pull request by luacmartins**
Reverts Expensify/App#38997

Coming from [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1712264151436019). Staging is crashing on [this line](https://github.com/Expensify/App/pull/38997)

### CODE REVIEW

**Comment by aldo-expensify** [comment]
This revert is fixing https://github.com/Expensify/App/issues/39650 for me, so approving!

**Review by aldo-expensify — APPROVED** [review]

**Comment by aldo-expensify** [comment]
@jasperhuangg should we merge and CP this? or give more time to the author of https://github.com/Expensify/App/pull/38997 to fix it before reverting? I'm not sure if you are planning to deploy today or not

**Comment by jasperhuangg** [comment]
@aldo-expensify planning on deploying today, so let's get the revert up

**Review by jasperhuangg — APPROVED** [review]

**Comment by jasperhuangg** [comment]
This was a straight revert that was tested already, no need for `Emergency` label

**Comment by aldo-expensify** [comment]
> @aldo-expensify planning on deploying today, so let's get the revert up

Nice, let me know if you want me to help you testing once CP'ed to staging

**Comment by aldo-expensify** [comment]
Tested,  and confirmed that https://github.com/Expensify/App/issues/39650 is fixed in staging


https://github.com/Expensify/App/assets/87341702/6080c382-4747-4675-a7a8-83a28dd667f7

**Pull request merged**
