### PR TITLE
Web/Desktop Press Enter key to go next

### PR DESCRIPTION
**Pull request by rushatgabhane**
### Details

Convert the functional component `Button` to a class component.

Create a new prop `pressOnEnter` for `Button`.
If it's true, `onPress()` is called when `Enter` key is pressed.

This is done by adding `Enter` as a keyboard shortcut for `onPress()` using `libs/KeyboardShortcut`
```
componentDidMount() {
    return if pressOnEnter is false

      KeyboardShortcut.subscribe('Enter', () => {
          if (button not disabled or button not disabled)
              props.onPress()
      })

}
```
Unsubscribe on unmount.

For all the pages like request payment, add workspace etc.
Pass the prop `pressOnEnter` to their buttons, so that `onPress()` is called when `Enter` key is pressed.

Remove redundant event listeners for `Enter` from `BaseModal`.
And add `pressOnEnter` to replicate previous behaviour of `ConfirmModal`

### Fixed Issues

$ #3785 

### Request payment
1. Request payment to any user
2. Enter amount and press `Enter` to go next.
3. Verify that pressing `Enter` makes the payment request.

### Add PayPal.me
1. Settings -> Payments
2. Add PayPal.me
3. Enter user name
4. Verify that pressing `Enter` adds PayPal account.

### Add workspace
1. Click on + icon.
2. Add Workspace
3. Enter workspace name
4. Verify that pressing `Enter` adds workspace.

### Split bill in **group chat**
1. Go to a group chat
2. Split bill.
3. Enter amount, press `Enter` to go next.
4. Verify that pressing `Enter` confirms split.
### Workspace Invite Page
1. Go to any workspace
2. Navigate to People tab
3. Click Invite
4. Add the email or phone
5. Verify that pressing `Enter` invites the user.

### QA
Verify that mobile apps don't crash by navigating to the above mentioned pages.

### Tested On

- [x] Web
- [x] Desktop

#### Web

https://user-images.githubusercontent.com/29673073/125567862-5ef7e410-c903-42fc-9637-03aa06af9873.mp4

https://user-images.githubusercontent.com/29673073/125568641-bb6f599d-e014-486f-9f35-421225c633f8.mp4

### CODE REVIEW

**Review by luacmartins — CHANGES_REQUESTED** [review]
Looks mostly ok. The displayed amount seems to have some style issues in both iOS and android versions.

Screenshot_1626296933
Simulator Screen Shot - iPhone 12 - 2021-07-14 at 15 10 17

**Comment by rushatgabhane** [comment]
> Looks mostly ok. The displayed amount seems to have some style issues in both iOS and android versions.

@luacmartins I branced to the commit just before I made any changes `57f557cd31198a631305b617c374f2418eb5e9fa`
And the styling issue is still there.

This branch (enter-go-next) doesn't modify any styling for IOUAmountPage.
This makes me believe it's a regression from previous commits, and it's fixed in the newer commits.

I think we're safe to merge with `main` and not see this issue happening.

**Review by luacmartins — COMMENTED** [review]
I agree that it is probably a regression. LGTM, we just need to fix the conflict and we are good to go.

**Comment by luacmartins** [comment]
Thanks for the fixes! One last comment that I have: pressing `enter` selects/deselects the first recent contact on Split Bills, is that intended behavior? Should we make it so `enter` moves the user to the next step if they have other users selected?

https://user-images.githubusercontent.com/22219519/125842536-8cc115b4-7449-4da3-9706-fb1e91e32a26.mov

**Comment by rushatgabhane** [comment]
> Thanks for the fixes! One last comment that I have: pressing `enter` selects/deselects the first recent contact on Split Bills, is that intended behavior? Should we make it so `enter` moves the user to the next step if they have other users selected?
> 
>  Screen.Recording.2021-07-15.at.12.53.51.PM.mov

Yes, that's the intended behaviour. 
The page for selecting split participants doesn't really work well with keyboard. Needs to be fixed in a seperate issue.

**Review by luacmartins — APPROVED** [review]
LGTM! Thanks @rushatgabhane!

**Pull request merged**
