### PR TITLE
Fix the text style in about page

### PR DESCRIPTION
**Pull request by Dal-Papa**
@shawnborton & @bondydaa  

### Details
The text in the about page wasn't using our regular font size. 

### Fixed Issues
$ N/A

### QA Steps

1. Click on your user profile image to open the Settings menu
2. Go to "About"
3. Verify that the text is in a normal font size

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

Screen Shot 2021-08-10 at 10 47 42

#### Mobile Web

Screen Shot 2021-08-10 at 10 57 49

### CODE REVIEW

**Comment by shawnborton** [comment]
To help get rid of the dangling orphan, maybe we can change the last line to "Help us build the next generation of Expensify." - thoughts?

**Comment by Dal-Papa** [comment]
> To help get rid of the dangling orphan, maybe we can change the last line to "Help us build the next generation of Expensify." - thoughts?

It seems to work, happy to commit. 
Screen Shot 2021-08-10 at 11 41 24

**Comment by shawnborton** [comment]
Looks great!

**Review by shawnborton — DISMISSED** [review]

**Review by shawnborton — DISMISSED** [review]

**Review by bondydaa — DISMISSED** [review]

**Comment by bondydaa** [comment]
merge conflicts

**Comment by Dal-Papa** [comment]
@shawnborton : Wording was changed in [this commit](https://github.com/Expensify/App/commit/13caa50ca9529d399803f91d8db5bdcf5b027c5c) and it screwed up your nice alignment... What do you advise ?
Screen Shot 2021-08-12 at 09 26 00

**Comment by shawnborton** [comment]
If we add "Come..." back to the front of the last sentence, does that give us at least two words on the third line? Or alternatively, we could just say "Help us build the future of Expensify."

**Comment by Dal-Papa** [comment]
> If we add "Come..." back to the front of the last sentence, does that give us at least two words on the third line? Or alternatively, we could just say "Help us build the future of Expensify."

I have tried adding back the `Come` but it still leaves the Expensify alone in the last line. Let me try that last option.

**Comment by Dal-Papa** [comment]
It works ! Though now I'd say the Spanish translation is off isn't it ?
Screen Shot 2021-08-12 at 10 05 23

**Review by bondydaa — CHANGES_REQUESTED** [review]
Yeah I'm with @shawnborton I think we might need to fix this line as well https://github.com/Expensify/App/blob/dc4dd81260ce1973a62d9d9f7d9b46f5800480a1/src/languages/es.js#L218

**Comment by Dal-Papa** [comment]
Here's the About page with the updated copy in Spanish : 
Screen Shot 2021-08-16 at 16 56 19

**Review by shawnborton — DISMISSED** [review]

**Comment by bondydaa** [comment]
did you forget to push? 

I don't see any changes to the es.js file
Screen Shot 2021-08-17 at 15 43 47

**Comment by Dal-Papa** [comment]
> did you forget to push?

... No ... 🏃‍♂️

**Review by shawnborton — APPROVED** [review]

**Review by bondydaa — APPROVED** [review]

**Pull request merged**
