### PR TITLE
[NoQA] add generatePolicyID

### PR DESCRIPTION
**Pull request by marcochavezf**
cc @thienlnam 

### Details

Add `generatePolicyID()` to generate `PolicyID` on the client.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/224679

### Tests

N/A This function is going to be used for https://github.com/Expensify/Expensify/issues/224690

### QA Steps

N/A

### Screenshots

N/A

### CODE REVIEW

**Comment by marcochavezf** [comment]
Hmm it's failing because of `no-unused-vars` eslint rule, I think it will be better to move this function to [NumberUtils.js](https://github.com/Expensify/App/blob/main/src/libs/NumberUtils.js) and import it into `Policy.js` when it's used. What do you think @thienlnam? In that way, I could also add a unit test [here](https://github.com/Expensify/App/blob/98f6a1b0a67d12cada9b9b50132518f6087e2fed/tests/unit/NumberUtilsTest.js)

**Review by thienlnam — DISMISSED** [review]
Looking good! Just one nab about the comment

**Comment by thienlnam** [comment]
> Hmm it's failing because of no-unused-vars eslint rule,

You should just be able to include the variable in the export below to fix this error

**Review by thienlnam — APPROVED** [review]
looks great, thanks for the ⚡ !

**Comment by thienlnam** [comment]
Going to merge to push this forward - feel free to leave comments still if you notice something @MonilBhavsar

**Comment by thienlnam** [comment]
Tests had passed

**Pull request merged**
