### PR TITLE
Fix inverted list by applying forked version of react-native-web

### PR DESCRIPTION
**Pull request by azimgd**
I used a patched version of react-native-web with fixes for copying text into the buffer in reversed order; 

React native change: https://github.com/Expensify/react-native-web/commit/bb711d2030fce467500b11cf0a2f09b1225d7444

### Details
I have removed flatlist inversion (by inverted=true prop) which used [transform: translate] css hack and instead adding flatlist array items in reverse order [unshift instead of push]; It also reverses ScrollView event response received from browser [e.nativeEvent.configOffset *= -1];

### Fixed Issues

https://github.com/Expensify/App/issues/3381

### Tests

1. run `npm install` which will patch react-native-web package
2. `npm run web` 
3. load a chat with 200 messages
4. scrolling up and down (with debugger enabled) works fine
5. copying text into buffer preserves order

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web
https://user-images.githubusercontent.com/4882133/128644572-72213a37-820b-4465-9a2c-1eb4f3666510.mov

### CODE REVIEW

**Comment by azimgd** [comment]
outdated PR: https://github.com/Expensify/App/pull/5561

**Comment by thienlnam** [comment]
Testing but app is crashing when I scroll quickly
Screen Shot 2021-11-09 at 1 07 52 PM
Screen Shot 2021-11-09 at 1 08 02 PM

**Review by thienlnam — DISMISSED** [review]

**Comment by azimgd** [comment]
@thienlnam ready to be merged ?

**Comment by thienlnam** [comment]
Could you address the comment here ? https://github.com/Expensify/App/issues/3381#issuecomment-966369523

**Comment by azimgd** [comment]
Could you perhaps help me out with that ? @thienlnam

**Comment by thienlnam** [comment]
The change would be moving the commands you have currently in your `postinstall` into a seperate file called `/build/react-native-web.sh`, and then the `postinstall` would just be `postinstall: './build/react-native-web.sh'`

**Comment by azimgd** [comment]
Done @thienlnam

**Comment by thienlnam** [comment]
Screen Shot 2021-11-16 at 10 39 30 AM

I think you need to add execute permissions to the file https://stackoverflow.com/questions/42154912/permission-denied-for-build-sh-file

**Comment by azimgd** [comment]
@thienlnam try now

**Review by thienlnam — APPROVED** [review]
Awesome, tests well for me locally - shipping it and 🤞  we don't cause regressions

**Comment by thienlnam** [comment]
Running tests

**Pull request merged**
