### PR TITLE
Update onyx & Fix the `enable-payments` page

### LINKED ISSUE #4392: Navigating to `enable-payments` shows only the side bar content when first navigating to it. Refreshing shows an infinite spinner.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to https://staging.new.expensify.com/enable-payments
2. Refresh the page

## Expected Result:
Enable-payments sidebar should load 

## Actual Result:
An infinite loading spinner is displayed on the sidebar. 

## Workaround:
User has to log out and back in to be able to navigate succesfully to https://staging.new.expensify.com/enable-payments

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.0.82-2

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

[Upwork job](upwork.com/jobs/~018846ad70dccf9366)
___
From @Jag96 https://expensify.slack.com/archives/C01GTK53T8Q/p1627944072091400
> Navigating to https://staging.new.expensify.com/enable-payments only shows the sidebar content the first time that you navigate to it. After refreshing the page, it shows an infinite spinner until you sign out and sign back in. Same issue on main.

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ #4500
Fixes #4392

### Tests | QA Steps
1. Navigate to staging.new.expensify.com/enable-payments.
2. Refresh the page

### Tested On

- [x] Web
- [x] Mobile Web

#### Web

https://user-images.githubusercontent.com/24370807/128567424-4989d78b-be82-4165-94b3-510ff79a3fdb.mp4

### CODE REVIEW

**Comment by parasharrajat** [comment]
This is straightforward PR which simply upgrade Onyx version.

**Comment by AndrewGable** [comment]
Looks good @parasharrajat - I am ready to merge when you fix merge conflicts

**Comment by AndrewGable** [comment]
🤔 - Now there are no changes

**Comment by parasharrajat** [comment]
@AndrewGable Looks like someone already updated the version. I don't think we have to merge this PR. There is nothing to merge and you can simply mark the issues completed to just notify that those are done.

**Comment by AndrewGable** [comment]
Can we confirm the fix is live first? Either on staging or locally?

**Comment by parasharrajat** [comment]
Ok, this is the PR https://github.com/Expensify/App/pull/4610 which upgrades the Onyx. Looks like yet to be pushed to staging.

**Comment by parasharrajat** [comment]
Maybe it's better to merge so that QA can be done separately.

**Comment by AndrewGable** [comment]
Good point 👍

**Review by AndrewGable — APPROVED** [review]

**Comment by isagoico** [comment]
@marcaaron I guess the Deploy blocker label was added because of the blank page when navigating to `enable-payments `
Should I create a separate issue or is this already being addressed? 
image

**Comment by marcaaron** [comment]
I don't think there is any need for a new issue.

**Comment by marcaaron** [comment]
i.e. both issues should be resolved once we fix the new blocker.

**Comment by parasharrajat** [comment]
I don't think that I have to do something here. Revert PR will fix the original issue as well.

**Comment by isagoico** [comment]
@marcaaron This issue is still reproducible in 1.0.86-2 
image

**Comment by parasharrajat** [comment]
@isagoico the issue you are reporting now has a different cause than what we fixed.

**Comment by isagoico** [comment]
oh well I'll go ahead and create an issue for this one. Thanks Rajat!

**Comment by marcaaron** [comment]
There's no spinner anymore so it seems maybe a new issue? Not totally sure.

**Comment by isagoico** [comment]
Reported the issue here https://github.com/Expensify/App/issues/4719

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-06.  :confetti_ball:

**Comment by MitchExpensify** [comment]
No regressions mentioned here, paying in Upwork!

**Pull request merged**
