### PR TITLE
Resolve issue with focus being lost on search box after selecting a user

### PR DESCRIPTION
**Pull request by eVoloshchak**
### Details
[Expected behavior](https://github.com/Expensify/App/issues/6470#issuecomment-998120843):
1. Open the New Group page
2. Start typing the name of a user, and then select from the list of results.
3. Then if the search input was focused before the option was selected from the list, then the search input should retain focus, and the previous input value should be highlighted.
4. If the search input was not focused before the option was selected from the list, then the search input should not regain focus. Clicking on the search input should highlight the previous value, not clear it.

### Fixed Issues
https://github.com/Expensify/App/issues/6470

### Tests
1. Open the New Group page
2. Start typing the name of a user, and then select from the list of results.
3. If the search input was focused before the option was selected from the list, verify that it retains focus and the input value is highlighted.
4. If the search input was not focused before the option was selected from the list, click on it and verify that the input value is highlighted.

### QA Steps
1. Open the New Group page
2. Start typing the name of a user, and then select from the list of results.
3. If the search input was focused before the option was selected from the list, verify that it retains focus and the input value is highlighted.
4. If the search input was not focused before the option was selected from the list, click on it and verify that the input value is highlighted.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop

The problem is present on Web and Desktop, but i have no way of testing the macOS desktop app

### Screenshots
https://user-images.githubusercontent.com/9059945/147157544-0b512212-bfb7-43ed-808f-2ff3a5d3541a.mp4

### CODE REVIEW

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Please test it on Android and sign your commits.

**Comment by eVoloshchak** [comment]
> Please test it on Android and sign your commits.

The original issue states that this problem occurs only on Web and Desktop platforms. 
On Android `textInput` never loses it's focus, it stays focused even when we press on `OptionRow`.
The only difference I can see between Android and web is that, since on Android textInput never loses it's focus, `selectTextOnFocus` is useless (there's only one onFocus when the component first renders) and text is not selected when we press on `OptionRow`. Should text be selected after selecting a user on mobile platfroms too?

**Comment by parasharrajat** [comment]
> Should text be selected after selecting a user on mobile platfroms too?

Exactly. Unless Mobile platforms create some challenges for us and do not affect anything, we can keep the same behavior for all devices.

**Comment by eVoloshchak** [comment]
> Exactly. Unless Mobile platforms create some challenges for us and do not affect anything, we can keep the same behavior for all devices.

There is a challenge i bumped into.
[React-Native's textInput](https://reactnative.dev/docs/0.63/textinput#methods) does not have a `select()` method, so there's no way to select text programatically. And since input doesn't lose it's focus, `selectTextOnFocus` is irrelevant. 

We could, however, check for mobile platform in [selectRow](https://github.com/Expensify/App/blob/580c9dbb1d2cf364bdcb6d7b3c06560f35b3ac6d/src/components/OptionsSelector.js#L195) method, call `.blur()` and then immediatelly `.focus()`, that way text inside textInput will be selected.
But it results in keyboard being dismissed for a moment, which does not look good.

**Comment by parasharrajat** [comment]
Lets select the text on native instead. 
```js
this.textInput.setNativeProps({selection: {start:0 , end: content.length}});
```
Do you think this will work?

**Comment by eVoloshchak** [comment]
> Do you think this will work?
Yup, I've verified it working, thank you.
We will also need to call `this.textInput.setNativeProps({selection: null})` on` textInput's` onChangeText.

So I'm gonna close this PR, sort-out issue with my commits not being signed and will create a new pull-request, right?

**Comment by parasharrajat** [comment]
Whatever is easier for ya. You can also rebase the commits instead of creating a new PR. But I leave that part up to you.

**Pull request closed without merging**
