### PR TITLE
Block requests made without an authToken. Do not fire reconnect callbacks without an authToken.

### PR DESCRIPTION
**Pull request by marcaaron**
The full context and discussion around this solution is [here](https://expensify.slack.com/archives/C03TQ48KC/p1601579127394500)

Ultimately, we all agree that there is probably a better way to do this and discussed a few options, but this is the simplest solution to fix the problem right now. Which is... we are firing reconnect callbacks without an `authToken` so the simple solution is to... stop it !

Better solution which we can follow up with would be more of a `PubSub` or `Ion` integration where `onReconnect` callbacks are hooked into `Ion` and we just let `Ion` know that it needs to update based on an event like the app returning from background or gaining connectivity after it has been lost.
 
### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/142471

### Tests (Android specifically is very broken - apparently iOS as well)
1. Delete app and reinstall
1. Background the app
1. Open the app again
1. Attempt to login
1. Verify you are able to do so

### Screenshots
❌

### CODE REVIEW

**Review by AndrewGable — APPROVED** [review]
Confirmed this works on native platforms

**Review by alex-mechler — APPROVED** [review]
Tested all platforms 👍

**Review by cead22 — APPROVED** [review]
👍 I think  we should try to remove the code we added in `request` asap, and fix the root of the problems (eg, fetchAll being called forever)

**Review by tgolen — APPROVED** [review]
This PR makes sense as a quick protection and in the case of the reconnection callbacks 👍

**Review by stitesExpensify — APPROVED** [review]

**Pull request merged**
