### PR TITLE
Revert 'jules-updateValidatePageInVBAFlow'

### PR DESCRIPTION
**Pull request by Julesssss**
Reverts [this PR](https://github.com/Expensify/App/pull/5251), which introduced [this bug.](https://github.com/Expensify/App/issues/5290) As this is now a prod deploy blocker we need to merge this ASAP to unblock N6.

`n6-hold` is not relevant here, this revert PR resolves a deployBlocker which will delay n6.

### Fixed Issues

$ https://github.com/Expensify/App/issues/5290

### Tests | QA Steps

N/A

### CODE REVIEW

**Comment by Julesssss** [comment]
CC @roryabraham & @AndrewGable, to ensure I'm following [this guide](https://stackoverflow.com/c/expensify/questions/9870/9871#9871) correctly.

**Comment by Julesssss** [comment]
@roryabraham this is the part that isn't clear to me:

> If your PR has been deployed to staging Your PR is now a production deploy blocker. Report the issue on the PR and apply the DeployBlockerCash label.

Do I just need to mention that this is a revert PR? Don't I also need to add the cherry-pick label so this PR skips the deploy lock check?

**Comment by francoisl** [comment]
@Julesssss to confirm, we should add the `CP staging` label, right?

**Comment by roryabraham** [comment]
@Julesssss That SO is out-of-date, updating it now. We'll want to CP this.

**Comment by roryabraham** [comment]
@Julesssss That SO is out-of-date, updating it now. We'll want to CP this.

**Comment by francoisl** [comment]
I resolved the conflict, can you review again please?  + @roryabraham

**Comment by Julesssss** [comment]
HOLD for now. There's a chance this revert was unnecessary. I'm looking into the possibility that the regression [was already occurring here](https://github.com/Expensify/Expensify/issues/175776).

**Comment by Julesssss** [comment]
Okay, we're [now pretty certain](https://expensify.slack.com/archives/C020EPP9B9A/p1631839963445700) that issue did already exist. Closing this PR, thanks for the help all!

**Pull request closed without merging**
