### PR TITLE
Adjust webpack type to apple-app-site-association

### PR DESCRIPTION
**Pull request by thienlnam**
### Fixed Issues

The fiIe was getting deployed to a folder because webpack automatically tried to infer the type based on the extension but apple-app-site-association is a file not a folder

https://expensify.slack.com/archives/C03TQ48KC/p1651080349065949

### Tests

- [x] Create production build locally and ensure you don't run into errors

### PR Review Checklist
N/A

### QA Steps

- Continue testing https://github.com/Expensify/App/pull/8656

### CODE REVIEW

**Review by neil-marcellini — APPROVED** [review]
Looks good. I ran a local web build with `npm run build` and verified that this file is under `.well-known/apple-app-site-association` rather than `.well-known/apple-app-site-association/apple-app-site-association`

**Comment by neil-marcellini** [comment]
I guess we should wait to merge since https://github.com/Expensify/App/issues/8777 has the LockCashDeploys label?

**Comment by thienlnam** [comment]
I'm pretty sure the CP Staging bypasses the lock and this is needed to test a PR on the checklist so it should be fine

**Comment by thienlnam** [comment]
Nice, https://staging.new.expensify.com/.well-known/apple-app-site-association shows the new file

**Pull request merged**
