### PR TITLE
Decrease ping timeout to 2s

### PR DESCRIPTION
**Pull request by iwiznia**
### Details
See https://expensify.slack.com/archives/C03TQ48KC/p1719482824987529
https://github.com/Expensify/App/issues/44269

### Tests
None, it seems we don't call Ping in dev, not sure why.

### QA Steps
No

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by srikarparsi** [comment]
Also looking into this [here](https://github.com/Expensify/App/issues/44269). I'm going to look at this again towards the end of the day and will try to check as well if reducing the timeout fixes this. This was tested [here](https://github.com/Expensify/App/pull/43090) so I'll just try copying the testing steps.

**Comment by iwiznia** [comment]
Ah nice, did not know that existed. I think this should fix that issue, no?

**Comment by srikarparsi** [comment]
I'm not really sure because the [defaults](https://github.com/react-native-netinfo/react-native-netinfo?tab=readme-ov-file#netinfoconfiguration) have  reachabilityRequestTimeout to default to 15s so decreasing to 2s might not be recommended. And reachabilityShortTimeout is also defaulted to 5s which is shorter than 15s.

I'm thinking something like [this](https://github.com/Expensify/App/pull/44565) instead but still have to test and everything. Basically preventing another network check if one is running.

**Comment by srikarparsi** [comment]
Sorry, I'm not sure if it matters but this is what I was trying to say.

The [reasoning](https://expensify.slack.com/archives/C03TQ48KC/p1719482824987529) behind this PR is that we check for connection every 5s but each check takes 10s to timeout. So network requests are piling up when there is slow internet connection.

But I'm saying that the [default value](https://expensify.slack.com/archives/C03TQ48KC/p1719482824987529) for the check to timeout is 15s (we changed this to 10s). And if their default value for the request timeout is greater than the time between checking connections, then maybe this is fine and their code already accounts it?

I'm also not too sure what this change would do once this [PR](https://github.com/Expensify/App/pull/44565) is merged. Currently, I only see the downside of showing "You appear to be offline" when Ping takes 3s to respond on super slow connection (even though the user is connected to internet).

But I'm not too sure because I haven't looked at their code. Maybe we could try 5 seconds first and see what happens and reduce to 2? I can also merge as is if you think it's worth it to try.

**Comment by iwiznia** [comment]
> But I'm saying that the [default value](https://expensify.slack.com/archives/C03TQ48KC/p1719482824987529) for the check to timeout is 15s (we changed this to 10s). And if their default value for the request timeout is greater than the time between checking connections, then maybe this is fine and their code already accounts it?

How? Where? I am looking at the behavior in the network tab and it does not seem like it.

> I'm also not too sure what this change would do once this https://github.com/Expensify/App/pull/44565 is merged. Currently, I only see the downside of showing "You appear to be offline" when Ping takes 3s to respond on super slow connection (even though the user is connected to internet).

I don't think this is a downside really, your internet is so slow that something that normally takes a few ms is taking several seconds

> But I'm not too sure because I haven't looked at their code. Maybe we could try 5 seconds first and see what happens and reduce to 2? I can also merge as is if you think it's worth it to try.

If you want, we can try 5s... I am also fine on holding this and deploying your other PR first

**Comment by srikarparsi** [comment]
> How? Where? I am looking at the behavior in the network tab and it does not seem like it.
Yeah, you're right. I just felt like they wouldn't recommend those values as the default without properly testing it and maybe somewhere else in our implementation is wrong but who knows.

> I don't think this is a downside really, your internet is so slow that something that normally takes a few ms is taking several seconds
Yeah, maybe, I'm not too sure. On other applications, it generally shows "Your network connection seems to be slow" vs "You appear to be offline" since it's still making network request. I'm not really sure.

> If you want, we can try 5s... I am also fine on holding this and deploying your other PR first
Sounds good, I think we can merge the other PR today and test Monday/Tuesday

**Review by grgia — APPROVED** [review]

**Comment by srikarparsi** [comment]
Hey @iwiznia, I think we can close out this PR? This was fixed [here](https://github.com/Expensify/App/pull/44901)

**Comment by iwiznia** [comment]
oh ok, wish we had merged this back then.

**Pull request closed without merging**
