### PR TITLE
Route to report after creating IOU

### PR DESCRIPTION
**Pull request by Beamanator**
cc @Julesssss 

### Details

Nothing too crazy here, after creating an IOU (either a split or transaction), we should route to that report, as users would expect.

Slack convo here: https://expensify.slack.com/archives/C01GTK53T8Q/p1622502339391600

### Fixed Issues

Fixes https://github.com/Expensify/Expensify/issues/165670

### Tests
1. Click the big green `+` button
2. Click "Split Bill"
3. Enter an amount and click "Next"
3. Select multiple recipients, then "Next"
4. Confirm by clicking "Split (amount)"
5. Confirm you were routed to a chat report between everyone involved in the split. (this may be a brand new chat, or an existing one if you've previously created a group between the same group)

1. Click the big green `+` button
2. Click "Request Money"
3. Enter an amount and click "Next"
4. Select a person, then click "Request (amount)"
5. Confirm you were routed to the chat w/ that person

### QA Steps
Same as above

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

(same as desktop below)

https://user-images.githubusercontent.com/3885503/120624575-206fc600-c461-11eb-8ee1-3e89700df477.mov

#### Mobile Web

https://user-images.githubusercontent.com/3885503/120630585-45ffce00-c467-11eb-9e65-430f77367d89.mov

#### Desktop

https://user-images.githubusercontent.com/3885503/120367586-57cf5d00-c311-11eb-9f3e-6d0ac341258d.mov

#### iOS

https://user-images.githubusercontent.com/3885503/120367902-b5fc4000-c311-11eb-90a5-60bea2c72157.mov

#### Android

https://user-images.githubusercontent.com/3885503/120368466-666a4400-c312-11eb-9b23-89945c9adef5.mov

### CODE REVIEW

**Review by Julesssss — CHANGES_REQUESTED** [review]
Actions are not supposed to return data, especially outside of other Actions. Could we instead Navigate to the report from within the Action?

**Comment by Beamanator** [comment]
I see that in the Philosophy now, but I was a bit confused since there's a few functions in `/actions/IOU.js` that currently do return some things - I didn't notice those functions are only used inside that file, they're not exported! 🤦 So great catch 👍  will update now.

**Comment by Beamanator** [comment]
@Julesssss addressed your comment 👍 

@mountiny I believe when I pushed a merge commit, pullerbear got reassigned, which is how you also ended up on this issue :D If you'd like to review, please do! Otherwise feel free to remove yourself as a reviewer :D

**Comment by Beamanator** [comment]
Finally got the mweb video too 👍

**Review by Julesssss — APPROVED** [review]

**Pull request merged**
