### PR TITLE
Fixed regression Android - Chat - Message gets displayed from right to left

### PR DESCRIPTION
**Pull request by samilabud**
### Details
The root cause is that Android only converts RTL text to LTR text using Unicode controls and by default, when you start writing in a language that is written in RTL mode it converts the input text to RTL.
Here we are fixing this [regression](https://github.com/Expensify/App/issues/30584#issuecomment-1870649972), this was caused because we did not take into consideration when the composer load for the first time and the user started writing with @, we include the @ in the regular expression list to validate if the composer can be converted to LTR.

### Fixed Issues

$ https://github.com/Expensify/App/issues/30584
PROPOSAL:  https://github.com/Expensify/App/issues/30584#issuecomment-1785494092

### Tests
1. Launch App
2. Open any chat and paste an RTL text in the compose box, for example " مثال "
3. Continue typing some content

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Test 1.
1. Launch App
2. Open any chat and paste an RTL text in the compose box, for example " مثال "
3. Continue typing some content

Test 2.
1. Launch App
2. Open any chat and type @, should show a suggestion list
3. Continue typing some content
4. Delete everything, the composer should show the placeholder.

Test 3.
1. Launch App
2. Open any chat and enter line breaks (to convert the composer into multiline)
3. Type spaces and @, check if everything works.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/5216036/f74efade-7b17-4221-a7bc-d1374c8fedff

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/5216036/c7f8d66a-7cb6-4d36-baa2-c02aadb7b6c6

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/5216036/00f76d31-5a82-4002-a21b-0e5e11fb4252

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/5216036/6469cf6b-19da-416b-b591-0e9d8a3d2a64

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/5216036/9ab3ca2f-dbb4-4a75-a3f9-5d1e7d1fde29

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/5216036/d148a790-f928-43cd-8fee-24778744f7b3

</details>

### CODE REVIEW

**Comment by allroundexperts** [comment]
@samilabud Conflicts!

**Comment by samilabud** [comment]
> @samilabud Conflicts!

Done!, thank you for letting me know, I hadn't noticed 😅.

**Comment by allroundexperts** [comment]
Hi @samilabud!

This is still not working as expected. Please check below.

https://github.com/Expensify/App/assets/30054992/06cceea8-2ae9-4a04-b293-e89d3b723e05

**Comment by samilabud** [comment]
> Hi @samilabud!
> 
> This is still not working as expected. Please check below.
> 
>  Screen.Recording.2024-01-14.at.1.31.53.AM.mov

Thanks for testing!, I have fixed the -at/@- regex to take into consideration the mention/searching, please double check:

https://github.com/Expensify/App/assets/5216036/86345e10-0c23-4f59-a2fd-81cc71e35f49

**Comment by allroundexperts** [comment]
Reviewing again tomorrow.

**Comment by allroundexperts** [comment]
@samilabud I am still seeing the following two errors:

https://github.com/Expensify/App/assets/30054992/d86f82f1-73a6-474c-adef-fb20c8994f3d

https://github.com/Expensify/App/assets/30054992/c9856bda-4569-4cca-9663-d2f95f83b9e5

At this point, since we have gone back and forth across this several times now, I think its not worth spending more of our time on this.

**Comment by samilabud** [comment]
@allroundexperts I understand your point and I'm sorry for this back and forth, in my defense according to my tests of the first video bug can be reproduced in the Main branch, and the second is because the colon character was not in the list of allowed not to convert the input to RTL, if there are more characters like @ or : that trigger other events would be good to know to add them all to the list.

Result with the colon added:

https://github.com/Expensify/App/assets/5216036/1d063bc0-1c8b-4221-8934-58ec26193af8

**Comment by allroundexperts** [comment]
Another bug @samilabud:

https://github.com/Expensify/App/assets/30054992/1e7a51b0-629e-49ce-a6f5-61c071dd3bdb

**Comment by samilabud** [comment]
> Another bug @samilabud:
> 
>  Screen.Recording.2024-02-01.at.2.30.53.AM.mov

OMG 😣, it's fixed now. 

Note: This strange behavior was happening even with @ (when tagging), because the LTR conversion was being called twice because the regular expression was only being taken into account for when to start writing in the composer.

Result:

https://github.com/Expensify/App/assets/5216036/6b98efa9-350f-4033-a629-485e4385ccdb

**Comment by tgolen** [comment]
What's the status of this PR? Are there any plans to finish it?

**Comment by allroundexperts** [comment]
This can be closed given we've closed the issue as well.

**Comment by allroundexperts** [comment]
Hi @samilabud!
Can you please close this PR?

**Pull request closed without merging**
