### PR TITLE
Fixed : One of the popup modal options is highlighted by default

### PR DESCRIPTION
**Pull request by metehanozyurt**
### Details

One of the popup modal options is highlighted by default, issue fixed
### Fixed Issues

$ https://github.com/Expensify/App/issues/8133

### Tests

1-) Open Expensify App.
2-) Go to any user chat click on ➕ ,
3-) Go to any user chat click call button (up right on screen) ,
4-) When two users online request money to another one and click pay button and click arrow button like in this picture below,
5-) Go to Settings -> Profile -> Click on camera icon
6-) Go to Settings -> Workspace -> General Settings -> Click on camera icon to change picture
7-) Go to Settings -> Workspace -> Click tree dots button (up right on screen)
8-) Should not any item highlighted when open popover menu

pay button:
WhatsApp Image 2022-04-12 at 09 13 26

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps

1-) Open Expensify App.
2-) Go to any user chat click on ➕ ,
3-) Go to any user chat click call button (up right on screen) ,
4-) When two users online request money to another one and click pay button and click arrow button like in this picture below,
5-) Go to Settings -> Profile -> Click on camera icon
6-) Go to Settings -> Workspace -> General Settings -> Click on camera icon to change picture
7-) Go to Settings -> Workspace -> Click tree dots button (up right on screen)
8-) Should not any item highlighted when open popover menu

pay button:
WhatsApp Image 2022-04-12 at 09 13 26

- [x] Verify that no errors appear in the JS console

#### Web

https://user-images.githubusercontent.com/6093207/166097760-dd9e2f59-977f-4e2b-a997-b1d68bf60767.mp4

#### Mobile Web

https://user-images.githubusercontent.com/6093207/166097945-505df9ff-5dad-4ea2-bc4d-94b7bf94df01.mp4

https://user-images.githubusercontent.com/6093207/166097936-e35001e4-246c-401a-8674-c49d36eefdbf.mp4

#### Desktop

https://user-images.githubusercontent.com/6093207/166097746-6842d1ec-c2f8-4ed3-91e9-89ebd5cfa1f2.mp4

#### iOS

https://user-images.githubusercontent.com/6093207/166098098-7d404ddf-a947-4f86-9ce0-f5002c783d8d.mp4

#### Android

https://user-images.githubusercontent.com/6093207/166098097-85ab6540-0b33-4387-99ad-af485b6e4b7f.mp4

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
@metehanozyurt Please add video recordings.

**Comment by metehanozyurt** [comment]
Of course , I do it immediately . I would have a few questions. 
I added it as a test video for the web version. Would it be enough for me to shoot videos for web and desktop, would you like me to shoot for mobile versions as well? I can also do it in slow motion if you want @Santhosh-Sellavel .

**Comment by metehanozyurt** [comment]
add video records all platform and for web and desktop make slow motion records too. Thank you @Santhosh-Sellavel for guiding me with your comments 🙏.

**Comment by metehanozyurt** [comment]
I upload new videos and wrote all steps @Santhosh-Sellavel  thank you 🙏 .
I think i have one issue i validate on stage version too. I am writing here because it is an important detail that you will encounter while checking. This issue like this . 
Sometimes this button not look like this 
WhatsApp Image 2022-04-12 at 09 13 26

fullscreen versions :

when user online request money comes :
WhatsApp Image 2022-04-12 at 09 22 39

logout and login 
WhatsApp Image 2022-04-12 at 09 23 21

I would like to report this situation on the Slack channel, if you have permission. Thank you.

**Comment by metehanozyurt** [comment]
Thank you @Santhosh-Sellavel . I also tested this button, you can see it in the videos. Kind regards.

**Comment by Santhosh-Sellavel** [comment]
@metehanozyurt 
Thanks for all your efforts. Reviewing this now.

**Comment by Santhosh-Sellavel** [comment]
@metehanozyurt 
This is still broken,
https://user-images.githubusercontent.com/85645967/163045665-ff1eb420-08d8-41b5-8ebe-2e55ea9997e4.mov

**Comment by metehanozyurt** [comment]
@Santhosh-Sellavel i am so sorry . I guess my eyes couldn't distinguish because these buttons are colored. I'm looking into the cause right now.

**Comment by metehanozyurt** [comment]
this component use 
[Popover/index.js](https://github.com/Expensify/App/blob/main/src/components/Popover/index.js) can i change this file.

https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/Popover/index.js#L36-L37

to like this

```js
            animationIn={props.isSmallScreenWidth ? undefined : 'fadeIn'}
            animationOut={props.isSmallScreenWidth ? undefined : 'fadeOut'}
```

I would like to research if any other components uses it before I change it, if you see fit.

**Comment by Santhosh-Sellavel** [comment]
> I would like to research if any other components uses it before I change it, if you see fit.

Yes, please!

**Comment by metehanozyurt** [comment]
I done my research. my results is as follows. [Popover/index.js](https://github.com/Expensify/App/blob/main/src/components/Popover/index.js) used by many components.

[Popover/index.js](https://github.com/Expensify/App/blob/main/src/components/Popover/index.js) uses by this components

| animationIn | animationOut |                                                                                                                                                                    |
|-------------|--------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| no          | no           | [BasePaymentsPage.js](https://github.com/Expensify/App/blob/120e03a74eaa0da0dca7eca0320a4dbcfb97ef7d/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L301) |
| ...props         | ...props          | [BasePopoverMenu.js](https://github.com/Expensify/App/blob/fbb4674521536923ee83c6e3f093fbe6bc029f9f/src/components/PopoverMenu/BasePopoverMenu.js#L31)                 |
| yes         | yes          | [VideoChatButtonAndMenu.js](https://github.com/Expensify/App/blob/0d1ec3d7d6cdb79de62ff676dad589237185cbe2/src/components/VideoChatButtonAndMenu.js#L128)               |
| ...props    | ...props     | [PopoverWithMeasuredContent.js](https://github.com/Expensify/App/blob/58f0168373e022440a01a966a0bae772f01dda1e/src/components/PopoverWithMeasuredContent.js#L186)       |
| no          | no           | [PasswordPopover.js](https://github.com/Expensify/App/blob/d1fd5bea56dc332fa9e08b837f17c2748bac7332/src/components/PasswordPopover.js#L64)                             |
| no          | no           | [ConfirmPopover.js](https://github.com/Expensify/App/blob/9dd2a451a70b8d5107eb586ce27617d30f81aeec/src/components/ConfirmPopover.js#L58)                               |

PopoverWithMeasuredContent.js uses by this components
| animationIn | animationOut |                                                                                                                                                                                          |
|-------------|--------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| no          | no           | [EmojiPicker/index.js](https://github.com/Expensify/App/blob/e7565c1aae9ee4a8f366932d63483619d742e970/src/components/EmojiPicker/index.js#L130)                                                   |
| yes(fadeIn) | no           | [ PopoverReportActionContextMenu.js](https://github.com/Expensify/App/blob/9beba91bef9019f25d9bc256069198d290fe88ee/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L277)|

BasePopoverMenu.js uses by this components
| animationIn | animationOut |                                                                                                                                                          |
|-------------|--------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| yes(fadeIn) | yes(fadeOut) | [PopoverMenu/index.js](https://github.com/Expensify/App/blob/3a58a6ef39628f50013e80e57e76ffeda4c77c19/src/components/PopoverMenu/index.js) (on my commits)  |
| ...props    | ...props     | [PopoverMenu/index.native.js](https://github.com/Expensify/App/blob/3a58a6ef39628f50013e80e57e76ffeda4c77c19/src/components/PopoverMenu/index.native.js#L28) |

### Conclusion

I think it will increase the complexity of the [sample code ](https://github.com/Expensify/App/pull/8581#issuecomment-1097190565) I suggested above. Instead, I think we should give the fadeIn and fadeOut parameters on the [VideoChatButtonAndMenu.js](https://github.com/Expensify/App/blob/0d1ec3d7d6cdb79de62ff676dad589237185cbe2/src/components/VideoChatButtonAndMenu.js) file. 

In the code fragments below, you can see that these parameters are not set on small screens.

https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/Popover/index.js#L36-L37
And
https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/Popover/index.js#L20-L21

I had to expand the solution method that I mentioned in my proposal. Because this was an issue I encountered while shooting screen videos.

**Comment by Santhosh-Sellavel** [comment]
>I think it will increase the complexity of the https://github.com/Expensify/App/pull/8581#issuecomment-1097190565I suggested above. Instead, I think we should give the fadeIn and fadeOut parameters on the [VideoChatButtonAndMenu.js](https://github.com/Expensify/App/blob/0d1ec3d7d6cdb79de62ff676dad589237185cbe2/src/components/VideoChatButtonAndMenu.js) file.

I am fine with both the above solution or this [solution]( https://github.com/Expensify/App/pull/8581#issuecomment-1097190565)

> I think it will increase the complexity
@metehanozyurt What's the complexity here?

**Comment by metehanozyurt** [comment]
That's why I think of it as complexity. It is already ignored on small screens. We also set it for big screens. That's why I was wondering if it should be given directly on the page. I was worried that the developer who would look at the code next to me would think that it would make more sense to change it on the page.

According to the decision of you managers, I can act in that way @Santhosh-Sellavel 🙏 . I am very happy with what I have learned from you 🙏 .

**Comment by metehanozyurt** [comment]
I made a change on the page for the reason I mentioned above. If you don't see fit, I'd be happy to change it. Thank you @Santhosh-Sellavel .

Video records all platforms after this changed:
Desktop-Web:

https://user-images.githubusercontent.com/6093207/164381689-9b154810-057d-4899-a56f-35b37eb5cbfe.mp4


ios native and mWeb:

https://user-images.githubusercontent.com/6093207/164381215-45cf4c89-0518-447c-83e7-7865856183c5.mp4

android native and mWeb:

https://user-images.githubusercontent.com/6093207/164381483-2e01becd-db01-491d-809b-72e8fd3df7bc.mp4

**Comment by Santhosh-Sellavel** [comment]
@roryabraham 

What's your thought on this https://github.com/Expensify/App/pull/8581#issuecomment-1098275736

**Comment by roryabraham** [comment]
> What's your thought on this https://github.com/Expensify/App/pull/8581#issuecomment-1098275736

Well, I'm not sure the context. Why do we need to add a default animation? Can we just pass the `animationIn` and `animationOut` props in the instances where we need to?

If it makes sense to add these default animations, we should inject them as default props rather than inline in the component.

**Comment by Santhosh-Sellavel** [comment]
> If it makes sense to add these default animations, we should inject them as default props rather than inline in the component.
@metehanozyurt  Can we do this?

**Comment by metehanozyurt** [comment]
Of course i will do it like this way @Santhosh-Sellavel . I just want to make sure I understand correctly. I don't want to make angry anyone. 
I can commit immediately.

I will remove these lines:

https://github.com/Expensify/App/blob/ff3625f30b803749567b847b2b6a0f941702d0bb/src/components/ThreeDotsMenu/index.js#L97-L98

https://github.com/Expensify/App/blob/0d1ec3d7d6cdb79de62ff676dad589237185cbe2/src/components/VideoChatButtonAndMenu.js#L135-L136

https://github.com/Expensify/App/blob/2b7d6d0a4171319a9328dca14bcd5023a5352a94/src/components/AvatarWithImagePicker.js#L223-L224

https://github.com/Expensify/App/blob/6803d0091ce4bcf68ca847818ca4a76ca3778ebe/src/components/ButtonWithMenu.js#L85-L86

https://github.com/Expensify/App/blob/16b130bd0cf9fe053fb2fc8eac0f809cc8f11fc8/src/pages/home/report/ReportActionCompose.js#L452-L453

https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/Popover/index.js#L20-L21

https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/Popover/index.js#L36-L37

This one stay like this revert my change:
https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/PopoverMenu/index.js#L23

already fadeIn and fadeOut  default props in here so i did not do anything this for this file:
https://github.com/Expensify/App/blob/1814323a4c1ce7855b163527dc62f13f61bdf5a3/src/components/PopoverMenu/popoverMenuPropTypes.js#L55-L56

I will change this file like this:
https://github.com/Expensify/App/blob/3a58a6ef39628f50013e80e57e76ffeda4c77c19/src/components/Popover/popoverPropTypes.js#L17-L22

```js
const defaultProps = {
    ...(_.omit(defaultModalProps, ['type', 'popoverAnchorPosition'])),

    animationIn: 'fadeIn',
    animationOut: 'fadeOut',

    // Anchor position is optional only because it is not relevant on mobile
    anchorPosition: {},
    disableAnimation: true,
};
```

**Comment by Santhosh-Sellavel** [comment]
@metehanozyurt Looks good, please verify that it doesn’t break any existing behavior, Thanks!

**Comment by Santhosh-Sellavel** [comment]
@metehanozyurt Test's well. update the video in the PR.

**Comment by Santhosh-Sellavel** [comment]
#### PR Reviewer Checklist

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

**Comment by metehanozyurt** [comment]
Updated all platform videos on PR @Santhosh-Sellavel . Thanks.

**Review by Santhosh-Sellavel — APPROVED** [review]
LGTM Tests well!

@roryabraham

**Review by roryabraham — APPROVED** [review]

**Pull request merged**
