### PR TITLE
Update deployBlocker.yml

### PR DESCRIPTION
**Pull request by ebauger**
replace single quotes (') with backticks (`)

### Fixed Issues

$ https://github.com/Expensify/App/issues/32070
PROPOSAL: https://github.com/Expensify/App/issues/32070#issuecomment-1830169420

### Tests

1.  I created a personal SLACK_WEBHOOK URL for testing the workflow.
2. The webhook perform well in my personal slack channel.

### Screenshots/Videos
What I see in the Slack Channel from the Webhook:
Capture d’écran, le 2023-11-28 à 09 42 10

### CODE REVIEW

**Comment by ebauger** [comment]
> **CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Expensify/App/blob/main/contributingGuides/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
>    - - -
>    ***I have read the CLA Document and I hereby sign the CLA***
>    - - -
>    <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

I have read the CLA Document and I hereby sign the CLA

**Comment by ebauger** [comment]
> I think someone said they already fixed this. I spent some time debugging it last night only to find out after.

We can split the effort. Reach me in DM.

**Comment by michaelssingh** [comment]
> > I think someone said they already fixed this. I spent some time debugging it last night only to find out after.
> 
> We can split the effort. Reach me in DM.

GH has DMs TIL. ChatGPT beat us this one, it has already been [solved](https://github.com/Expensify/App/blob/4fa869c2500163c549a525a957cde18bcbbe2ab0/.github/workflows/deployBlocker.yml#L29).

**Comment by ebauger** [comment]
> > > I think someone said they already fixed this. I spent some time debugging it last night only to find out after.
> > 
> > We can split the effort. Reach me in DM.
> 
> GH has DMs TIL. I was looking forward to adding this to the my collection of easiest money I had ever made but that damn ChatGPT beat us to it, get used to saying that.
> 
> It was ["solved"](https://github.com/Expensify/App/blob/4fa869c2500163c549a525a957cde18bcbbe2ab0/.github/workflows/deployBlocker.yml#L29).  I'd hate to be next person to have to look at that file.

It's a good solution, but harder to read and maintain. Escaping should be in the actions-slack IMO.

Let's the reviewer the PR. 🌃

**Comment by cubuspl42** [comment]
Please close this PR and get familiar with the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). Thank you!

**Comment by cubuspl42** [comment]
@NicMendonca Would you please close this PR, if you have the permissions? It was posted against the guidelines and it's trashing my GitHub summaries.

**Review by jakub-trzebiatowski — CHANGES_REQUESTED** [review]
This PR should be closed

**Pull request closed without merging**
