### PR TITLE
Use new vbba 111 commands and swap order of company step and requestor steps

### PR DESCRIPTION
**Pull request by nkuoch**
### Fixed Issues
Part of https://github.com/Expensify/App/issues/30442
$ https://github.com/Expensify/App/issues/31357
Attach vbba logic to new 1:1:1 backend with new ordering + some refactoring and bug fixes.

### Tests
See comments below. More tests and review will be made in the [parent PR](https://github.com/Expensify/App/pull/31456).

https://github.com/Expensify/App/pull/33838#issuecomment-1888711616

### CODE REVIEW

**Comment by nkuoch** [comment]
Via Plaid Chase Checking
image

image

It then displayed the manual form as Plaid Chases returns substitute account numbers. Entered 011401533 and 1111222233330000

image

image

**Comment by nkuoch** [comment]
Things I noticed by that can be tackled in a follow up PR:

- When entering a beneficial owner, reaching the confirm view, reloading page forgets about it.
...

**Comment by nkuoch** [comment]
**Tested adding a PENDING business bank account.**

Clicked on Connect Manually. Entered 011401533 and 1111222233330000
Name: Alberta Charleson
SSN: 3333

Onfido got skipped because we used test data

Company name: Alberta Bobbeth Charleson
TaxID: 123456789

Made sure I reached the Validate step:
image

**Comment by nkuoch** [comment]
**Tested adding an OPEN business bank account**

Clicked on Connect with Plaid. Used TD Bank, user_good, pass_good, Plaid Saving.

Name: Alberta Charleson
SSN: 3333

Onfido got skipped because we used test data

Company name: Alberta Bobbeth Charleson
TaxID: 123456789

Made sure I reached the validated view
image

(Not sure why we always reach this view though, as my primary email address I used wasn't from a public domain. Same behaviour in prod though I believe)

**Comment by shubham1206agra** [comment]
@mountiny Can you merge this here https://github.com/Expensify/App/pull/34498?
@nkuoch Can you change the target branch to https://github.com/barttom/App-expensify/tree/vit-tieredBankAccountFlow?

**Comment by nkuoch** [comment]
I can't because it's a fork.
image
image

**Comment by shubham1206agra** [comment]
@mountiny Do I need to review this now or in the final PR?

**Comment by mountiny** [comment]
@shubham1206agra lets just merge and then let @barttom sync with the branch

**Pull request merged**
