### PR TITLE
Fix OnyxTab Navigator performance issues on web

### PR DESCRIPTION
**Pull request by kacper-mikolajczak**
### Details

This PR tries to fix performance isseus with `OnyxTabNavigator`(and underlying `MaterialTopTab`) on web by disabling animations. The root cause lies in high intensity of calculations going on on each transition between tabs and in a way `Animated` works on web.

The navigation flow is bound to be changed in near future, that's why PR aims to be as concised as it can (without performing deeper changes to the animation etc.) 

More details can be found in the original [PR](https://github.com/Expensify/App/pull/32577) and in the [quickfix](https://github.com/Expensify/App/pull/33754). 

### Fixed Issues

$ https://github.com/Expensify/App/issues/31190
PROPOSAL: https://github.com/Expensify/App/issues/31190#issuecomment-1851723261

### Tests

1. Open `FAB` -> `RequestMoney`
2. Switch to `Manual` and check if it is rendered correctly
3. Switch to `Scan` and check if it is rendered correctly
4. Switch to `Distance` and check if it is rendered correctly

### QA Steps

N/A

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/62747088/fcf2fbb9-6db1-4153-83ee-02e50d3f9168

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/62747088/cb12d6d7-768b-426c-89fe-285df0aa115a

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/62747088/124d85eb-d357-4e05-a5ff-491861bf91de

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/62747088/1fb32288-b90a-49c6-878a-b58373b0a6e5

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/62747088/c5cef007-af84-4a61-94a1-caa56dda5ae8

</details>

### CODE REVIEW

**Comment by shubham1206agra** [comment]
@kacper-mikolajczak Can you profile this PR so we can know the performance improvement here?

**Comment by kacper-mikolajczak** [comment]
> @kacper-mikolajczak Can you profile this PR so we can know the performance improvement here?

Definitely!

### Setup

As a test I went through each tab like this:

https://github.com/Expensify/App/assets/62747088/c06dbbca-9425-4db3-ade4-858392d4e584

### Results

Here are the results of profiling that on Web.

**Before** (profiled prod at `new.expensify`):

Screenshot 2024-01-03 at 11 12 37

**After** (profiled current branch):
image

As you can see, there is less high-traffic going on after disabling animations (the `rAF` callbacks tend to go way beyond frametime threshold, thus slowing down the whole app).

Hope that helps 👍

**Comment by shubham1206agra** [comment]
@mountiny Can you start an adhoc build to test this branch on physical device?

And @mananjadhav can you check this PR in physical iphone?

**Comment by mountiny** [comment]
Making the build here https://github.com/Expensify/App/actions/runs/7411340404

**Comment by kacper-mikolajczak** [comment]
Hi folks @mountiny @shubham1206agra 👋 

What is the status of the review for this one? Thanks! 👍

**Comment by shubham1206agra** [comment]
@kacper-mikolajczak You may want to also request review from @mananjadhav as he was the original reviewer.

**Comment by kacper-mikolajczak** [comment]
> @kacper-mikolajczak You may want to also request review from @mananjadhav as he was the original reviewer.

Sure thing! I cannot add reviewer myself but I guess @mananjadhav already knows as we pinged him 😄

**Comment by mountiny** [comment]
@mananjadhav whats your ETA for this review?

**Comment by mananjadhav** [comment]
I'll have them reviewed by today end of day and finish the checklist by tomorrow.

**Comment by mananjadhav** [comment]
@kacper-mikolajczak Can you please resolve the conflicts?

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/3069065/e40ccae9-038a-458e-b045-d1b808e55e24

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/3069065/5678e91c-d0f5-4bd0-ba33-b93f20ec3709

https://github.com/Expensify/App/assets/3069065/4f00a1ac-99cd-48e6-92d2-0fb1c5beebca

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/3069065/759a8baa-e2ea-46ce-85c5-81e88a145dc8

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/3069065/22f38e42-26f6-4577-8887-8e5c47720a4e

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/3069065/6eac5fdc-a6d7-4604-ad3f-529f2539df3f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/3069065/c650ca99-819a-4764-9624-b665b0493a2a

</details>

**Comment by mountiny** [comment]
iOS seems to work well for me. and yes Chelsea is loosing 😢 
https://github.com/Expensify/App/assets/36083550/01073296-d939-4beb-a2b7-4c90dc720805

**Comment by mountiny** [comment]
@kacper-mikolajczak merging main should fix the reassure test failure

**Comment by shubham1206agra** [comment]
@kacper-mikolajczak I am currently facing a problem with a real Android device.

Steps:
1. Open request money from FAB
2. Go to scan tab. Make sure camera works correctly.
3. Using manual route, go to confirmation step.
4. Click on Add reciept. Make sure camera is working correctly here too.
5. Go back to the amount step using back button.
6. Now go to scan tab again.

Expected - Camera is working
Actual - Camera is black screen.

**Comment by shubham1206agra** [comment]
NVM, this is also repro in prod. But maybe this can be fixed here.

**Comment by kacper-mikolajczak** [comment]
@mountiny @shubham1206agra Conflicts resolved ✅ 

The Blues did not win tho, let's hope they can come back in the second leg ⚽ 

> NVM, this is also repro in prod. But maybe this can be fixed here.

If the bug did not originate here, let's tackle it in separate issue 👍

**Comment by mountiny** [comment]
> The Blues did not win tho, let's hope they can come back in the second leg ⚽

hopefully 🙏 

@shubham1206agra @mananjadhav could we wrap this up?

**Comment by shubham1206agra** [comment]
> > The Blues did not win tho, let's hope they can come back in the second leg ⚽
> 
> hopefully 🙏
> 
> @shubham1206agra @mananjadhav could we wrap this up?

Its good to go from my side. Waiting for @mananjadhav to approve the request.

**Review by mananjadhav — APPROVED** [review]
Tested again, except iOS.

**Review by stitesExpensify — APPROVED** [review]

**Pull request merged**
