### PR TITLE
[CP Staging] Revert "Fix some bugs on Bank account Flow"

### PR DESCRIPTION
**Pull request by DylanDylann**
Reverts Expensify/App#51315

Fix deploy blocker:
- https://github.com/Expensify/App/issues/51823
- https://github.com/Expensify/App/issues/51854

QA Steps: 

Bug 1:

1. Tap profile icon -- workspaces-- workspace
2. Tap more features - enable workflow
3. Tap workflow in workspace settings
4. Tap connect bank account
5. Complete the flow using region bank - selecting account ending 1111
6. Note user directed to continue set up page instead of "manually add bank account page"
7. Navigate to settings and tap connect bank - continue set up
8. On tapping next on manually enter bank account page, user directed to continue set up page again
9. When we revisit the page by tapping next, user directed to personal information page
10. Verify on tapping "next" in manually enter bank account page, user must not be directed to continue set up page

Bug 2: 

1. profile icon > workspaces > enable workflow
2. Tap workflow in workspace settings > connect bank account
3. Select the Manual method to add a bank account
4. Go through the flow until "Validate account" page
5. Submit three random amounts
6. Verify that the validate code you entered is incorrect, please try again" error is shown in "Validate account" page

### CODE REVIEW

**Review by dangrous — APPROVED** [review]
Straight revert, looks good

**Review by srikarparsi — APPROVED** [review]

**Review by mountiny — APPROVED** [review]
Straight revert, thanks! Lets give it a second try

**Comment by mountiny** [comment]
Not emergency, straight revert ao checklist skipped

**Comment by Beamanator** [comment]
FYI ideally we'll still add test steps in reverts, so QA knows what to test once the revert gets to staging 🙏

**Comment by DylanDylann** [comment]
I updated the PR description to include the QA steps

**Comment by Beamanator** [comment]
Thanks very much sir 🙏  would you also be able to test in staging real quick to see if https://github.com/Expensify/App/issues/51854 was also fixed?

**Comment by DylanDylann** [comment]
@Beamanator I tried to verify [this issue](https://github.com/Expensify/App/issues/51854), but I don't know how to reproduce it based on the steps. I think @lakchote can help to verify

https://github.com/user-attachments/assets/014b3ef4-0805-4893-9a6a-f1a308d34444

**Comment by Beamanator** [comment]
Thanks for trying @DylanDylann 👍  I ping'd some QA people internally so let's see 🙏

**Pull request merged**
