### PR TITLE
Move `name` field out of `Settings` and into `ReportDetailsPage`

### PR DESCRIPTION
**Pull request by c3024**
### Details

This PR is opened because the contributor assigned for the issue #40262 has been banned and the PR #40858 can no longer be modified and merged. [Context here](https://expensify.slack.com/archives/C02NK2DQWUX/p1718239157243779).

### Fixed Issues

$ https://github.com/Expensify/App/pull/40262
PROPOSAL: https://github.com/Expensify/App/issues/40262#issuecomment-2164156184

#### Test 1

1. Go to a user created `room` in which you are a member.
2. Click on the header.
3. Verify that the RHP shows an item with `Room name` followed by editable room name followed by `in <workspace name>`.

#### Test 2

1. Go to a group chat in which you are a member.
2. Click on the header.
3. Verify that the RHP shows an item with `Group name` followed by editable group name.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as `Tests`

### QA Steps

Same as `Tests`

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/102477862/fc745980-4c9c-4de6-92f4-6acd6f71feeb

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/102477862/82dfe812-7672-43c8-b825-4461d1b22904

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/102477862/8d40835a-dc60-4980-9370-fc2214ac9695

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/102477862/143475fa-b9d6-468e-901a-7feade94a6bb

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/102477862/83e8f6ee-9fdb-4ff3-88fd-d442ffe5b994

For all the following images, admin/creator is on left and member on the right.

Group Chat

groupChat

Room

room

Policy Expense Chat

policyExpenseChatAdminAndMemberSide

Default Rooms

defaultRoom

Chat Thread

chatThread

Invoices

invoices

Money Request Report

moneyRequestReport

Money Request 

moneyRequest

Task

task

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/102477862/0bdad197-6301-427f-a145-e8d92c977376

</details>

### CODE REVIEW

**Comment by c3024** [comment]
@eVoloshchak, PR ready for your review.

@youssef-lr sorry, I made a mistake in adding the issue in `Fixed Issues` and you were assigned. Fixed it now and @marcaaron is the internal engineer for the referred issue.

**Comment by shawnborton** [comment]
Can you also share a screenshot of what the details view of a report that has an non-editable title looks like for comparison?

**Comment by c3024** [comment]
@shawnborton 

I added all the screenshots here in [this comment](https://github.com/Expensify/App/pull/43636#issue-2350325877) in the Web Chrome section of Screenshots/Videos. Please have a look.

I followed [option 1](https://github.com/Expensify/App/pull/40858#issuecomment-2102734687) specified here.

**Comment by c3024** [comment]
@eVoloshchak @marcaaron 

These are the new changes made compared to the previous PR. 
1. As per [this comment here](https://github.com/Expensify/App/pull/40858#issuecomment-2102734687), editable room/group names have the new look and aligned to left and the non-editable room/group names have the usual look with centre alignment. So, I moved the `shouldShowRoomName` logic existed in the previous PR to `shouldDisableRename` in `ReportUtils`.
2. I removed the `policy` param in the `shouldDisableRename` because it was used only to identify a public room. Additionally, the existing function looked like it was only applicable to policy rooms even though there was a `isGroupChat` check as well in it. Now, I think it is clearer than before that it is a generic function applicable for all reports.

**Comment by shawnborton** [comment]
Looks pretty good to me! Going to spin up a test build though for some local testing.

**Comment by c3024** [comment]
@eVoloshchak PR ready for review!

cc: @marcaaron

**Comment by dannymcclain** [comment]
Screenshots are looking good—I'll check out the ad hoc build once it's ready too.

**Comment by shawnborton** [comment]
Feels pretty good to me from testing the adhoc links above!

**Comment by cdOut** [comment]
Hi @c3024, just wanted to let you know that the feature you are working on in this PR is also a part of a flow that I am refactoring [over in this PR](https://github.com/Expensify/App/pull/43251), I will try to unify our code by looking into the way you've implemented it but still keep in mind the fact that we're working in parallel on this feature if my PR gets merged first.

**Comment by mallenexpensify** [comment]
Thanks for sharing @cdOut , does it make sense to put one of the issues/PRs on hold?  And/or to have a discussion _somewhere_? ( #expensify-open-source ?)

**Comment by cdOut** [comment]
> Thanks for sharing @cdOut , does it make sense to put one of the issues/PRs on hold? And/or to have a discussion _somewhere_? ( #expensify-open-source ?)

Not really, it is however something we should keep in mind when merging one of those issues after the other.

**Comment by shawnborton** [comment]
What's the latest here? Do we just close this one out since I think this is already implemented?

**Comment by cdOut** [comment]
This has been implemented in the Details Revamp flow during the refactor of ReportDetailsPage, I think this issue can be closed.

**Comment by shawnborton** [comment]
Okay cool, I'm just going to close this one out then - let me know if anyone disagrees!

**Pull request closed without merging**
