### PR TITLE
[HOLD for payment 2024-01-24] Refactor and Fix Attachment Handling in File Download and Carousel

### PR DESCRIPTION
**Pull request by kidroca**
### Pull Request Description

This pull request introduces several changes aimed at improving the handling of attachments in file download processes and the Attachment Carousel component. The key changes are as follows:

1. **Refactor `libs/FileUtils`:** The function `getAttachmentName` has been removed. It has been replaced by `getFileName`, which extracts and sanitizes filenames from URLs for filesystem usage. This new function decodes the URL segment, replaces illegal characters with underscores, and includes logging for cases where the filename cannot be determined.

2. **Fix in `libs/fileDownload`:** Modifications have been made to ensure there is a reachable fallback for filenames. This includes changes in various platform-specific files (`index.android.ts`, `index.ios.ts`, `index.ts`) to utilize `getFileName` for generating fallback filenames when necessary.

3. **Update in `AttachmentCarousel`:** The CarouselItem component now uses the source URL for fallback file names. This change is reflected in `extractAttachmentsFromReport.js`, where the source and filename are determined based on either the provided attributes or the fallback logic.

4. **PropTypes Enhancements:** In `AttachmentCarousel/CarouselItem.js` and `Attachments/propTypes.js`, the `file` property within the attachment prop types has been updated to be required, ensuring better type safety and clarity in the component's expected data structure.

**Technical Details:**
- **Files Affected:**
  - `AttachmentCarousel/CarouselItem.js`
  - `Attachments/propTypes.js`
  - `AttachmentCarousel/extractAttachmentsFromReport.js`
  - `fileDownload/FileUtils.ts`
  - `fileDownload/index.android.ts`
  - `fileDownload/index.ios.ts`
  - `fileDownload/index.ts`

The changes aim to enhance the robustness of attachment handling, ensuring filenames are correctly determined and handled across different components and platforms. Additionally, the update in PropTypes enforces stricter type checking, contributing to the overall reliability of the components.

### Fixed Issues

$ https://github.com/Expensify/App/issues/30931
PROPOSAL: https://github.com/Expensify/App/issues/30931#issuecomment-1809743645

#### Case 1 - Concierge Drag & Drop Attachments

**Objective:** Ensure attachments added by Concierge through Drag & Drop are downloadable across platforms.

**Prerequisites:** A chat session with Concierge.

##### General:

- Initiate a chat with Concierge.
- Request Concierge to send inline image attachments using the Drag & Drop method.

##### On Web / Desktop:

- Click on any of the received attachments.
- Click the Download button located in the upper right corner.
     - Note: Since the attachment is sourced directly from Amazon S3 (which is a different origin), it will not directly download but will open in a new browser tab/window.

##### On iOS / Android (a regression prevents testing this flow in the current PR):

- Tap on any of the received attachments.
- Tap the Download button located in the upper right corner.
- Observation: Unlike web platforms, native apps are unaffected by CORS. As such, the attachment should download directly to the device.

#### Case 2 - File Names Compliance

**Objective:** Verify that downloaded file names adhere to the specified naming conventions.

##### General:

- Utilize the files downloaded in `Case 1` for this test.

##### Naming Rules Verification:

1. **For files with original names**:
   - Ensure the downloaded file's name retains its original name, with the download datetime appended.
   - Example:
     - Original name: `sample.pdf`.
     - Expected download name: `sample-2023-11-29 17_42_33.461.pdf`.
   - Note: Replace colons (`:`) in datetime with underscores (`_`) as colons are not permitted in filenames.
   - Note: original file name is the name of the file on sender's device at the time they select it for upload

2. **For files without original names (e.g., Concierge Drag & Drop attachments)**:
   - Confirm that the file name is derived from its URL, with the download datetime appended.
   - Example:
     - URL: `https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads%2F1676033736079-1676033736079.png`.
     - Expected download name: `uploads_F1676033736079-1676033736079-2023-11-29 17_44_14.113.png`.

#### Case 3 - Prop-Type Warnings for Attachment Carousel

**Objective:** Ensure there are no prop-type warnings in the console related to file names when opening attachments in the attachment carousel.

##### General Procedure:

1. **Interaction with Various Attachments**:
   - Engage in different chat scenarios:
     - Chat with Concierge and open attachments that were added through drag and drop.
     - Open attachments in regular or group chats.
   - For each scenario, focus on opening a variety of attachment types.

2. **Observation in Attachment Carousel**:
   - After the attachment carousel opens, inspect the browser's console logs.
   - Look specifically for any prop-type warnings related to file names.

##### Expected Outcome:

- There should be no warnings in the console regarding missing or incorrect file names for any attachments opened in the carousel.
- Ensure that the test covers a diverse set of attachment types to verify the robustness of the implementation.

### Offline tests

N/A - attachments cannot be downloaded while offline

### QA Steps

The following tests are applicable to both staging and production

#### Case 1 - Concierge Drag & Drop Attachments

**Objective:** Ensure attachments added by Concierge through Drag & Drop are downloadable across platforms.

**Prerequisites:** A chat session with Concierge.

##### General:

- Initiate a chat with Concierge.
- Request Concierge to send inline image attachments using the Drag & Drop method.

##### On Web / Desktop:

- Click on any of the received attachments.
- Click the Download button located in the upper right corner.
     - Note: Since the attachment is sourced directly from Amazon S3 (which is a different origin), it will not directly download but will open in a new browser tab/window.

##### On iOS / Android (a regression prevents testing this flow in the current PR):

- Tap on any of the received attachments.
- Tap the Download button located in the upper right corner.
- Observation: Unlike web platforms, native apps are unaffected by CORS. As such, the attachment should download directly to the device.

#### Case 2 - File Names Compliance

**Objective:** Verify that downloaded file names adhere to the specified naming conventions.

##### General:

- Utilize the files downloaded in `Case 1` for this test.

##### Naming Rules Verification:

1. **For files with original names**:
   - Ensure the downloaded file's name retains its original name, with the download datetime appended.
   - Example:
     - Original name: `sample.pdf`.
     - Expected download name: `sample-2023-11-29 17_42_33.461.pdf`.
   - Note: Replace colons (`:`) in datetime with underscores (`_`) as colons are not permitted in filenames.
   - Note: original file name is the name of the file on sender's device at the time they select it for upload

2. **For files without original names (e.g., Concierge Drag & Drop attachments)**:
   - Confirm that the file name is derived from its URL, with the download datetime appended.
   - Example:
     - URL: `https://s3-us-west-1.amazonaws.com/concierge-responses-expensify-com/uploads%2F1676033736079-1676033736079.png`.
     - Expected download name: `uploads_F1676033736079-1676033736079-2023-11-29 17_44_14.113.png`.

#### Case 3 - Prop-Type Warnings for Attachment Carousel

**Objective:** Ensure there are no prop-type warnings in the console related to file names when opening attachments in the attachment carousel.

##### General Procedure:

1. **Interaction with Various Attachments**:
   - Engage in different chat scenarios:
     - Chat with Concierge and open attachments that were added through drag and drop.
     - Open attachments in regular or group chats.
   - For each scenario, focus on opening a variety of attachment types.

2. **Observation in Attachment Carousel**:
   - After the attachment carousel opens, inspect the browser's console logs.
   - Look specifically for any prop-type warnings related to file names.

##### Expected Outcome:

- There should be no warnings in the console regarding missing or incorrect file names for any attachments opened in the carousel.
- Ensure that the test covers a diverse set of attachment types to verify the robustness of the implementation.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

image

</details>

<details>
<summary>Android: mWeb Chrome</summary>

image

</details>

<details>
<summary>iOS: Native</summary>

Screenshot 2023-12-01 at 22 09 47

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Screenshot 2023-12-01 at 22 18 15

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Screenshot 2023-12-01 at 22 08 32

</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2023-12-01 at 16 46 37

</details>

### CODE REVIEW

**Comment by kidroca** [comment]
Update: added specific test steps

**Comment by kidroca** [comment]
> @kidroca please complete author checklist. Some platform screenshots are still missing

✔️ Done

**Review by aimane-chnaif — APPROVED** [review]
LGTM 🎉

**Comment by NikkiWines** [comment]
@kidroca you've got conflicts

**Review by NikkiWines — DISMISSED** [review]
looks good aside from conflicts!

**Comment by kidroca** [comment]
> @kidroca you've got conflicts
- ✔️ Conflicts resolved - synced with `main` 
- ✔️ Retested after syncing with main - All tests and checks have passed without any issues.

**Review by NikkiWines — APPROVED** [review]
:shipit:

**Pull request merged**
