### PR TITLE
fix(35740): don't mark as unread if I don't have a timestamp!

### PR DESCRIPTION
**Pull request by jeremy-croff**
### Fixed Issues

$ https://github.com/Expensify/App/issues/35740
PROPOSAL: https://github.com/Expensify/App/issues/35740#issuecomment-1924936555

### Tests

- [x] Verify that no errors appear in the JS console

On all devices with URL navigation (non-native/desktop apps )
1. Log out
2. Navigate to https://staging.new.expensify.com/r/8661824749067368
3. Scroll up to the task report and click it
4. Ensure the new task report you are in is not bolded in LHN

### Offline tests

Offline is not relevant to the fix.
However:
On all devices with URL navigation (non-native/desktop apps )
1. Log out
2. Navigate to https://staging.new.expensify.com/r/8661824749067368
3. -- disconnect internet -- 
4. Scroll up to the task report and click it
5. It won't load ( existing behavior )

### QA Steps

On all devices with URL navigation (non-native/desktop apps )
1. Log out
2. Navigate to https://staging.new.expensify.com/r/8661824749067368
3. Scroll up to the task report and click it
4. Ensure the new task report you are in is not bolded in LHN

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>
NOT APPLICABLE FOR ANON URL NAVIGATION

Screenshot 2024-02-15 at 9 35 09 PM

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot 2024-02-15 at 9 19 05 PM

</details>

<details>
<summary>iOS: Native</summary>
NOT APPLICABLE FOR ANON URL NAVIGATION

Screenshot 2024-02-15 at 9 19 34 PM

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/157416545/75e53fdb-71c6-48e7-aab8-ebefde68c965

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/157416545/ff90ad0c-18fb-4a0c-aa89-bc443af3ad84

</details>

<details>
<summary>MacOS: Desktop</summary>
NOT APPLICABLE FOR ANON URL NAVIGATION

Screenshot 2024-02-15 at 9 17 20 PM

</details>

### CODE REVIEW

**Comment by jeremy-croff** [comment]
@shubham1206agra Can you confirm if 'Concierge' not being bold is a regression or expected on Anon user? I am not sure what the details of the internal conversation entailed as to expected behavior for Anon read/unread.

**Comment by jeremy-croff** [comment]
> @jeremy-croff I think it shouad mark as read only on clicking on it. Otherwise, mark it as bold.



> @jeremy-croff I think it should mark as read only on clicking on it. Otherwise, mark it as bold.

Thank you for your quick response. We seem to have an additional bug in latest staging. where we are calling ReadNewestAction on concierge as an anonymous user, but when we use OpenReport, we are still receiving a null timestamp. Consequently, it does not mark the message as read, and it remains unread. 

I think within the scope of this PR we could decide to always have it read, or always unread. Or do you think I need to address the concierge timestamp issue?

**Comment by jeremy-croff** [comment]
@shubham1206agra I might require BE to handle the reading flow for this use case.

I have proposed that the absence of a timestamp should be considered as "read". However, the back end not persisting lastReadTime timestamps for anon users seems to be the root cause of the absence of the timestamp. Even after posting ReadNewestAction with a timestamp when anonymous, the subsequent OpenReport is returning a null timestamp. I don't think it is possible to solve the read/unread issue for anonymous users because of this.

As a thought for UI fix: Ignoring onyx merges on the timestamp on OpenReport seems to be the only option, but it seems hackish.

**Comment by jeremy-croff** [comment]
> @mountiny can you help us here itely leverage last visit t the timestamp?
> 
> @jeremy-croff I have another idea: switch to `lastVisitTime` for Anon users to get timestamps.

This is a super idea. I can definetely leverage lastvisitTime for anon users to determine read/unread. I was scanning the report to find a similar attribute but never noticed there was a report metadata that had this!
Thanks.

**Comment by jeremy-croff** [comment]
> @jeremy-croff Can you send me response to both API calls in the meantime?


https://dev.new.expensify.com:8082/api?command=ReadNewestAction
```
{
    "jsonCode": 200,
    "requestID": "85636214dbf20b71-DFW",
    "onyxData": [
        {
            "key": "report_6636348502217690",
            "onyxMethod": "merge",
            "value": {
                "lastReadTime": "2024-02-16 05:27:42.703"
            }
        }
    ],
    "previousUpdateID": 123781695,
    "lastUpdateID": 123782662
}```

https://dev.new.expensify.com:8082/api?command=OpenReport
```
{
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_6636348502217690",
            "value": {
                "reportID": "6636348502217690",
                "reportName": "Chat Report",
                "type": "chat",
                "chatType": "",
                "ownerAccountID": 0,
                "managerID": 0,
                "policyID": "_FAKE_",
                "participantAccountIDs": [
                    8392101
                ],
                "visibleChatMemberAccountIDs": [
                    8392101
                ],
                "isPinned": false,
                "lastReadTime": null,
                "lastMentionedTime": null,
                "lastReadSequenceNumber": 0,
                "lastVisibleActionCreated": "2024-02-16 03:47:42.611",
                "lastVisibleActionLastModified": "2024-02-16 03:47:42.611",
                "lastMessageText": "\ud83d\udc4b Hey there, I'm Concierge! I help millions of people automate their expense re\u2026",
                "lastActorAccountID": 8392101,
                "notificationPreference": "always",
                "welcomeMessage": "",
                "stateNum": 0,
                "statusNum": 0,
                "oldPolicyName": "",
                "visibility": null,
                "isOwnPolicyExpenseChat": false,
                "lastMessageHtml": "\ud83d\udc4b Hey there, I'm Concierge! I help millions of people automate their expense reporting, corporate cards, invoicing and more! I\u2019d love to help you too. If you have any questions about Expensify, you can always chat with me here 24-7 for fast and reliable support. Want me to send any more info about how we can save you time today?",
                "iouReportID": null,
                "hasOutstandingChildRequest": false,
                "policyName": null,
                "hasParentAccess": null,
                "parentReportID": null,
                "parentReportActionID": null,
                "writeCapability": "all",
                "description": "",
                "isDeletedParentAction": null,
                "reportFields": null,
                "total": 0,
                "currency": "USD",
                "submitterPayPalMeAddress": "",
                "chatReportID": null,
                "isWaitingOnBankAccount": false,
                "nonReimbursableTotal": 0,
                "isCancelledIOU": false
            }
        },
        {
            "onyxMethod": "merge",
            "key": "reportActions_6636348502217690",
            "value": {
                "5609881197705822251": {
                    "reportActionID": "5609881197705822251",
                    "previousReportActionID": "0",
                    "actionName": "CREATED",
                    "created": "2024-02-16 03:47:42.460",
                    "reportActionTimestamp": 1708055262460,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_1.png",
                    "message": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "__fake__"
                        },
                        {
                            "type": "TEXT",
                            "style": "normal",
                            "text": " created this report"
                        }
                    ],
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "__fake__"
                        }
                    ],
                    "automatic": false,
                    "sequenceNumber": 0,
                    "shouldShow": true,
                    "lastModified": "2024-02-16 03:47:42.460"
                },
                "7765280430856838045": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Expensify Concierge"
                        }
                    ],
                    "actorAccountID": 8392101,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "\ud83d\udc4b Hey there, I'm Concierge! I help millions of people automate their expense reporting, corporate cards, invoicing and more! I\u2019d love to help you too. If you have any questions about Expensify, you can always chat with me here 24-7 for fast and reliable support. Want me to send any more info about how we can save you time today?",
                            "text": "\ud83d\udc4b Hey there, I'm Concierge! I help millions of people automate their expense reporting, corporate cards, invoicing and more! I\u2019d love to help you too. If you have any questions about Expensify, you can always chat with me here 24-7 for fast and reliable support. Want me to send any more info about how we can save you time today?",
                            "isEdited": false,
                            "whisperedTo": [],
                            "isDeletedParentAction": false,
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "\ud83d\udc4b Hey there, I'm Concierge! I help millions of people automate their expense reporting, corporate cards, invoicing and more! I\u2019d love to help you too. If you have any questions about Expensify, you can always chat with me here 24-7 for fast and reliable support. Want me to send any more info about how we can save you time today?",
                        "lastModified": "2024-02-16 03:47:42.611"
                    },
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/894b50e60056c966d12216005fbcacec8ce5a2c0.png",
                    "created": "2024-02-16 03:47:42.611",
                    "timestamp": 1708055262,
                    "reportActionTimestamp": 1708055262611,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,
                    "reportActionID": "7765280430856838045",
                    "previousReportActionID": "5609881197705822251",
                    "lastModified": "2024-02-16 03:47:42.611",
                    "whisperedToAccountIDs": []
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "8392101": {
                    "accountID": 8392101,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/icons\/concierge_2022.png",
                    "firstName": "Expensify",
                    "lastName": "Concierge",
                    "status": null,
                    "displayName": "Expensify Concierge",
                    "login": "concierge@expensify.com",
                    "pronouns": "",
                    "timezone": {
                        "automatic": true,
                        "selected": "Europe\/Moscow"
                    },
                    "payPalMeAddress": "",
                    "phoneNumber": "",
                    "validated": true
                }
            }
        }
    ],
    "jsonCode": 200,
    "requestID": "85636217faed6c2b-DFW"
}
```

**Comment by jeremy-croff** [comment]
> @jeremy-croff I believe `ReadNewestAction` is called after `OpenReport`, right?

Before actually.

**Comment by jeremy-croff** [comment]
> @jeremy-croff I confirmed that the current order is reversed. Can you check why this is happening?

Reversed as compared to what?
I am giving the current behaviour of staging:
Screenshot 2024-02-15 at 11 57 14 PM

**Comment by jeremy-croff** [comment]
> > OpenReport is main API command and inside it we conditionally call ReadNewestAction

I see what you mean. I can find out why this is happening to deepen our understanding of the root cause. I do have to sign off for now and will be able to continue progress tomorrow. I'll start with continuing the RCA of the API behavior. And as a fallback can explore using lastVisitedTimestamp

**Comment by jeremy-croff** [comment]
The Read -> Open seems to only happen for Concierge. 
All Other reports whether logged in or out seem to follow
Open -> Read -> Open

**Comment by mountiny** [comment]
@shubham1206agra @rlinoz is assigned to the issue so he could help with your questions

**Comment by jeremy-croff** [comment]
Holding PR BC of https://github.com/Expensify/App/issues/35740#issuecomment-1947817642

**Comment by DylanDylann** [comment]
@mountiny Please help to re-assign @shubham1206agra to this PR. It seems the contributor adds the GH issue link after marking PR as ready and the Melvin auto assign me to this one

**Pull request closed without merging**
