### PR TITLE
[User Settings] Implement Settings Menu Selectors

### LINKED ISSUE #1493: [User Settings] Implement Settings Menu Selectors
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

We need to update the existing Settings page to include four new menu items that will link to new sub-pages. When one of the menu items is selected, a new view should appear with the title of the menu item selected.

In addition to the title, each menu item will have an icon on the left-hand side, as well as a right-facing arrow on the right-hand side (`arrow-right.svg`) The icons needed for these menu items are: 
     - Profile: `profile.svg`
     - Preferences: `gear.svg`
     - Change Password: `lock.svg`
     - Payments: `wallet.svg`
  
Icons can be found in the following zip file: [UI_Icons.zip](https://github.com/Expensify/Expensify.cash/files/5998018/UI_Icons.zip)

### Deliverables: 
- Add four clickable menu items `Profile`, `Preferences`, `Change Password`, and `Payments` to [SettingsPage.js](https://github.com/Expensify/Expensify.cash/blob/blob/src/pages/SettingsPage.js)
- When a menu item is clicked, the right-docked modal should hide the existing settings view, and display the new view with the title of the page
    -  Use `params.match.route` to determine which view to display.  
- When a sub-page is closed, the view should display the Settings page once again
- Add two new routes to [ROUTES.js](https://github.com/Expensify/Expensify.cash/blob/master/src/ROUTES.js)
     - `SUBSETTINGS: '/sttings/:route'`
     - ``getSettingsRoute: route => `/settings/${route}` ``

 
| Mobile  | Web|
| ------------- | ------------- |
|  |  |

### Sample Flow for clicking on the `Preferences` Menu Item
Screen Shot 2021-02-17 at 2 40 40 PM

### PR DESCRIPTION
**Pull request by Maftalion**
### Details
Original PR https://github.com/Expensify/Expensify.cash/pull/1630

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com//issues/1493

### Tests
- Click into Settings page from HomePage
- Click each menu item and confirm subroute renders

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

Screen Shot 2021-03-09 at 9 04 51 AM

#### Mobile Web

Screen Shot 2021-03-09 at 9 07 04 AM

#### Desktop

Screen Shot 2021-03-09 at 9 06 15 AM

#### iOS

Screen Shot 2021-03-09 at 9 12 17 AM

#### Android

Screen Shot 2021-03-09 at 9 07 58 AM

### CODE REVIEW

**Comment by Maftalion** [comment]
um not sure how i broke things 😅 , but i just cherry picked my commits over and opened a new pr.


https://user-images.githubusercontent.com/12075600/110413603-0467ae80-8043-11eb-8619-caee6a3a13f3.mov

**Comment by jasperhuangg** [comment]
Hey @Maftalion! I was randomly assigned by PullerBear and I don't think I have enough context to be reviewing this PR. 

It looks like @cead22 @shawnborton @NikkiWines and @marcaaron were reviewing the PR that this one was made from. I think they should probably be the ones reviewing this. I'll remove myself from the assignment.

As a note though it looks like you're failing the JSX style tests, but these seem to have been fixed in this PR: https://github.com/Expensify/Expensify.cash/pull/1674?expand=1.

Thanks!

**Comment by shawnborton** [comment]
The video you posted looks great to me, but I'd also love more screenshots in the original comment as well.

**Review by marcaaron — APPROVED** [review]
LGTM

**Review by NikkiWines — APPROVED** [review]
Tested and works well :shipit:

**Comment by shawnborton** [comment]
Tested and this looks great. The only slight weirdness I see is that if you navigate to a subpage of Settings (like Preferences) and then tap on the "X" in the top right corner, you see the parent Settings page flash for a split second as the rightDocked sidepane exits.

**Review by cead22 — APPROVED** [review]

**Comment by NikkiWines** [comment]
@shawnborton I think the view weirdness will probably be handled when we change the whole navigation system in marc's react-navigation PR https://github.com/Expensify/Expensify.cash/pull/1559

**Pull request merged**
