### PR TITLE
Handle 666 errors in Policy.removeMembers

### PR DESCRIPTION
**Pull request by flodnv**
cc @iwiznia @marcaaron related to an internal thread here: https://expensify.slack.com/archives/C03TQ48KC/p1642178947340500

### Details

This will give more accurate error messages instead of always the generic one.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/191023

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

1. Setup a new workspace, add a new member
2. On OldDot, make the new member's domain group restrict policy to the workspace (in Domain Settings > Members)
3. On NewDot, try to remove the member from the workspace:
Screen Shot 2022-01-14 at 4 54 20 PM

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

See above

### CODE REVIEW

**Review by marcaaron — APPROVED** [review]

**Review by iwiznia — CHANGES_REQUESTED** [review]
Based on that thread, it seems we want a better error handling than just a growl

**Review by ctkochan22 — APPROVED** [review]

**Comment by marcaaron** [comment]
>Based on that thread, it seems we want a better error handling than just a growl

Maybe we can loop in @Expensify/design to help us with this one.

We don't really have a clear guidance for how to handle server errors in non-forms. Seems like there are a couple of options:

1. Turn this into a form (I am not evil enough to ask Florent to do this 😂 )
2. Come up with a slightly different pattern...

Here's a quick attempt at `2` with the following reasoning...

A button that triggers an API request should show a loader like we do for a form



If the request doesn't not succeed we should remove the option to repeat this action (just a thought but I can see not removing it as well) and replace it with a message

**Comment by iwiznia** [comment]
That looks fine, but would that mean we would block any actions while the request is being processed? I don't quite like that.
Maybe we could instead show some kind of popup on the button that was pressed?

**Comment by marcaaron** [comment]
>Maybe we could instead show some kind of popup on the button that was pressed

Not sure if I understand the meaning of a "popup", but sounds kind of like you are suggesting an inline Growl. What makes the error popup go away? Is it time-based like the Growl? Can or should it be manually dismissed? Should we leave it there until the user does something else?

**Comment by iwiznia** [comment]
> kind of like you are suggesting an inline Growl

Yeah, like a growl with a small speech bubble pointing to the button that triggered the action. You would manually dismiss it by clicking on it or it can have a close button somewhere. I would guess that interacting again with the button would dismiss it too.

**Comment by marcaaron** [comment]
Something similar to this but pointed at the button?

a58b4d674e014a38eb764ef062430885168e85af_2_690x360

**Comment by shawnborton** [comment]
> We don't really have a clear guidance for how to handle server errors in non-forms. Seems like there are a couple of options:

How do we currently handle server errors in forms?

**Comment by iwiznia** [comment]
> Something similar to this but pointed at the button?

Yeah

**Comment by iwiznia** [comment]
> How do we currently handle server errors in forms?

That's explained in this section: https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#bookmark=id.odca5qx1yozc

**Comment by marcaaron** [comment]
We add them to the bottom of the screen above the submit button. We could do the same here, but we are exploring alternatives because this is not a form.

**Comment by shawnborton** [comment]
Well just because it's not a "form" doesn't mean we can't do something similar right? Personally I really like what you outlined in your [comment here](https://github.com/Expensify/App/pull/7229#issuecomment-1013513830).

**Comment by marcaaron** [comment]
>Well just because it's not a "form" doesn't mean we can't do something similar right?

Let's explore whether it works or not. The "form" gives the user some indication that things are loading in a button and then we show server errors above this button once the loading is done. Without the submit button the error message would just pop up at the bottom of the screen. Which does not seem much better than a Growl and also adds the question of how long the message should persist on screen.

Probably this conversation is getting a little deep for this particular issue - but if we don't want to use a Growl then it would be nice to settle on various patterns and have a bunch of common UI error handling scenarios to pull from or advise people to implement when this topic comes up.

**Comment by iwiznia** [comment]
Also this being a list which can (and probably will) be long, showing the error on the bottom is probably not the best, because it's possible it's out of the user's view...

**Comment by shawnborton** [comment]
What about the two mockups you posted in your comment above? It seems like that would be a great way to handle this? Essentially the "form" is encapsulated into the small bottom-docked modal.

**Comment by marcaaron** [comment]
I like it, but @iwiznia pointed out [here](https://github.com/Expensify/App/pull/7229#issuecomment-1013515280) that maybe this action should have an optimistic UI i.e. should the user wait to find out if it was successful and be aware of the "loading" state? Or should they simply see the change happen, then get rolled back, then see some indication that it was not successful.

**Comment by shawnborton** [comment]
Got it, I hear ya. I think most of the time I agree with wanting an optimistic UI. But I can see an argument that we don't need it when taking some kind of delete/remove action like this. Otherwise I guess we could optimistically take the action, close out the modal, and then relaunch the modal with an error message if we have one.

**Comment by flodnv** [comment]
@iwiznia Can we:
1. Merge this PR to provide instant value to users. This PR is only improving things, it is not making anything worse / different than it is today
2. Create an External issue to improve this flow further
?

**Comment by iwiznia** [comment]
Sure

**Review by iwiznia — APPROVED** [review]

**Comment by iwiznia** [comment]
Not up to me though, @AndrewGable is tagged as reviewer and did not approve

**Review by AndrewGable — APPROVED** [review]

**Comment by mvtglobally** [comment]
@flodnv  We are unable to find ""new member's domain group restrict policy to the workspace" in the OldDot. Can you please confirm where in the profile this settings should appear?

**Comment by flodnv** [comment]
This wild be in Domain Control > Groups

**Comment by mvtglobally** [comment]
@flodnv Here is what we see in the Groups. What options out of these restricts Workspace? 
Screen Shot 2022-02-12 at 1 24 50 PM
When we tried to enable "Restrict expense policy creation/removal" It blocked us from creating any workspaces

**Comment by Julesssss** [comment]
Hey @flodnv, could you confirm which switch is the correct one please

**Comment by flodnv** [comment]
Ah sorry about that, it's the last setting for "preferred policy"

**Comment by mvtglobally** [comment]
We are checking

**Comment by mvtglobally** [comment]
@flodnv  Can you please double check the issue above. We are seeing different error in PROD, but I assume its expected. Pls confirm it doesnt need to be a deploy blocker

**Comment by flodnv** [comment]
That's definitely unrelated to this PR. Thanks!

**Pull request merged**
