### PR TITLE
Revert iOS Safari auto scrollback

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
This PR reverts https://github.com/Expensify/App/pull/6413, which never really worked as expected and caused https://github.com/Expensify/App/issues/8135.

There was a lot of context and conversation behind these changes. Reverting this PR will bring back [this bug](https://github.com/Expensify/App/issues/5894), which I think is the lesser of two evils (not as bad as https://github.com/Expensify/App/issues/8135, which actually affects the usability of our app).

There was discussion of [another solution](https://github.com/Expensify/App/issues/5894#issuecomment-973563994), but I think we can reopen https://github.com/Expensify/App/issues/5894 and make it external so they can figure out how to make it work with the address bar on top or bottom (which is a configurable setting as of iOS 15).

### Fixed Issues
$ https://github.com/Expensify/App/issues/8135

### Tests / QA Steps
None, this is just a revert.

- [ ] Verify that no errors appear in the JS console

### CODE REVIEW

**Comment by parasharrajat** [comment]
@roryabraham What is the next step for this? Are we going to revert it or something else?

**Comment by roryabraham** [comment]
Hmmm ... I don't remember why I closed this. Sorry, I think we do want to revert this auto scrollback feature. Do you agree?

**Comment by parasharrajat** [comment]
Yeah, I agree to revert it.

**Review by Rpeiiihuk — COMMENTED** [review]
We

**Comment by parasharrajat** [comment]
I think we should proceed with this. It is creating more issues.

**Comment by roryabraham** [comment]
Opened up for reviews.

**Review by parasharrajat — APPROVED** [review]
LGTM

**Review by ctkochan22 — APPROVED** [review]

**Pull request merged**
