### PR TITLE
#2430 remove app.relaunch on desktop update

### PR DESCRIPTION
**Pull request by dklymenk**
### Details

Removes unnecessary from update function that breaks notifications after update.

### Fixed Issues

$ #2430

### Tests

1. Follow the instructions on how to [test electron updates](https://github.com/Expensify/App/blob/main/desktop/README.md), on the last step you should get an "update ready" notification.
2. Start update
3. After the app has restarted, open dev toools (cmd+option+i) and type `new Notification('Test notification');` in console. You see a notification.
4. (Optional) Assuming you have account A open in desktop app after update, send a message to it from account B open in browser or mobile app. You also get a notification.

### QA Steps

1. Log in to the desktop app with account A
2. Wait for the update to arrive
3. Update the desktop app
4. Right after app restart send a message from account B to account A
5. You should see a notification

### Tested On
The change only affects desktop, no need to test anything else.
- [x] Desktop

#### Desktop

https://user-images.githubusercontent.com/64093836/128174279-356ab06e-53c4-4599-af2d-299837da2e23.mp4

### CODE REVIEW

**Review by chiragsalian — APPROVED** [review]
LGTM

**Comment by roryabraham** [comment]
I am worried this caused a regression where the update app modal doesn't display after the update notification is clicked? Would love it someone could independently verify the bug. This PR seems like the most likely culprit, but I'm not sure.

**Comment by dklymenk** [comment]
I actually haven't seen any update modal during any of my tests. I don't believe there is any reason to assume this PR has caused it, because the change is to update callback only. The logic behind showing the update modal wasn't changed.

**Comment by chiragsalian** [comment]
Looks like this PR may not be the cause of the issue since we've been able to reproduce the issue on production while this code is only on staging.

**Comment by roryabraham** [comment]
Yep, my mistake this PR was not the cause.

**Comment by parasharrajat** [comment]
Coming here from the Update App modal issue. 

https://github.com/Expensify/App/blob/3ec2137f80f84fedb7fde47576d3887b5efa916a/desktop/main.js#L213-L224
was dependent on the code removed. I know that relaunching the issue but Should something be added to keep the other functionality intact. 

cc: @roryabraham @chiragsalian

**Comment by roryabraham** [comment]
Yeah, it looks like a fair amount of code related to the expected update version flag was not removed along with the flag itself.

**Comment by dklymenk** [comment]
What exactly is that code's function? Is that something I should have reimplemented in some other way?

**Comment by parasharrajat** [comment]
Yes. That code determines the Window visibility after the update. (Casually saying :whale:) But It's shocking that you removed a piece of code without tracing its usages.

**Pull request merged**
