### PR TITLE
Prevent workspace menu from dismissing when clicking on add work email

### PR DESCRIPTION
**Pull request by techievivek**
### Details

While clicking on the `add work email address` option under the workspace menu in the new dot it dismisses the workspace menu and we do not want that to happen.

Please have a look at the issue it has a video showing the unexpected behaviour.
### Fixed Issues

$ https://github.com/Expensify/App/issues/9013

### Tests

1. To test this you first need to generate(generator:account) a new account using a public mail service provider like Gmail.
2. Once you have created a verified account create a new workspace under this account by logging into new dot.
3.  Now to this workspace let's add a VBA(verified bank account)  by following the instruction to add `OPEN` state bank account from this [SO](https://stackoverflow.com/c/expensify/questions/342) in New Dot (Profiles -> workspace -> issue cards -> add bank account).
4. Once the VBA is added when we go to the same option to issue cards we can see an option to `add work email address`, clicking this will not dismiss the workspace menu like before.

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps

1. To test this make sure you have a verified account created using a public mail service provider like Gmail.
2. Once you have created a verified account create a new workspace under this account by logging into the new dot.
3.  Now to this workspace let's add a VBA(verified bank account)  by following the instruction to add an `OPEN` state bank account from this [SO](https://stackoverflow.com/c/expensify/questions/342) in New Dot (Profiles -> workspace -> issue cards -> add bank account).
4. Once the VBA is added when we go to the same option to issue cards we can see an option to `add work email address`, clicking this will not dismiss the workspace menu like before.
- [ ] Verify that no errors appear in the JS console

#### Web
https://user-images.githubusercontent.com/35863227/169164309-96a57ebe-8a7a-4ea6-932d-fff06c1e1264.mp4

#### Mobile Web

https://user-images.githubusercontent.com/35863227/169469981-d443e2ef-8044-4670-a214-5fd8d3776184.mp4

#### Desktop

https://user-images.githubusercontent.com/35863227/169276455-d33c7846-c6d7-4d27-bde3-27a03fad0307.mp4

#### iOS
https://user-images.githubusercontent.com/35863227/169164194-e6d08df9-958e-4b7b-bac5-21d583081dbf.mp4

#### Android
https://user-images.githubusercontent.com/35863227/169164200-b2c8d19e-2f2d-4857-9520-51906495108a.mp4

### CODE REVIEW

**Comment by luacmartins** [comment]
@techievivek is this still a work in progress?

**Comment by techievivek** [comment]
@luacmartins No but I am not able to test this. But the fix is to only remove the part which dismisses the sidebar.

**Review by luacmartins — CHANGES_REQUESTED** [review]
Leaving a few comments:

1. We should fix the lint error by removing the unused `Navigation` import.
2. I think we could easily test this on dev by following the steps below:
   - Create an account with a public domain (we can use `./scripts/clitools.sh generator:account` for that)
   - Login and create a new workspace
   - Add a VBA following [this SO](https://stackoverflow.com/c/expensify/questions/342)
   - Navigate to `Workspace > Issue cards`
   - Kill connection and tap `Add work email address`
   - Verify that the modal is not dismissed
3. Make sure that you go through the checklist and check off any applicable items on the list!

**Comment by techievivek** [comment]
Updated the test section thanks for the help.

**Comment by luacmartins** [comment]
Thanks for updating the test! Can we go through the rest of the checklist and add videos for all platforms?

**Comment by techievivek** [comment]
Sure I will add them today. Thanks

**Comment by techievivek** [comment]
@luacmartins I have updated the video placement and have added videos for all platforms except(Mobile web) not sure how would I access `localhost:8080` on my emulator. Any pointers on how to test this out? Thanks

**Comment by luacmartins** [comment]
I think [this SO](https://stackoverflow.com/c/expensify/questions/8291) might help

**Comment by techievivek** [comment]
@luacmartins Thanks that worked like charm, just updated the video for mWeb as well.

**Comment by luacmartins** [comment]
@techievivek Cool! thanks for the updated videos! A few more small comments:

1. Please make sure to go through the PR checklist and check any applicable checkboxes.
2. I noticed that while we have Test steps, we didn't add any QA steps. This is important because that's what Applause (our outsourced QA team), or an internal QAer will use to test the PR. The QA steps are steps that you can take in staging or production to test the PR (so that means no terminal commands, db access, etc). In this PR's case, I think the steps are the same (except for the account generator commands), but we should at least mention that under QA steps.
3. I see that you added the InternalQA label, but I think that this can be tested by Applause. At least in the past, they were able to test this flow. So I think we should remove that.

Sorry about all the back and forth, but it seems like a good learning opportunity for how our QA process works 😄

**Comment by techievivek** [comment]
@luacmartins Not an issue Carlos, I appreciate the time and effort you are taking to guide me through this it would definitely help me be a better contributor and will make things easy for others involved as well. I have updated the PR and QA. I have some small queries related to QAs which I always struggle with
1. So the QA team tests the changes only in staging and production?
2. How do we determine if the particular PR is testable by the QA team? Do they have access to Internal SO? Like in this one I thought about how would they have access to SO and the credentials used to open VBA.

Thanks for all the learnings so far. 🙌

**Review by luacmartins — APPROVED** [review]
LGTM and tests well! Thanks for the fix @techievivek!

**Comment by luacmartins** [comment]
Tests were passing...

**Comment by techievivek** [comment]
Thanks, @luacmartins for all the help and guidance, learnt a lot.

**Pull request merged**
