### PR TITLE
Add the `zip` target to fix Desktop auto updates

### PR DESCRIPTION
**Pull request by kidroca**
@roryabraham 

### Details

When `mac.target` was introduced to the electron config it overrode the default, which used to build a dmg and a zip for the current platform  
We need to specify a `zip` target, because autoupdates work with that: 

https://www.electron.build/auto-update.html#quick-setup-guide
> zip target for macOS is required for Squirrel.Mac, otherwise latest-mac.yml cannot be created, which causes autoUpdater error. Default target for macOS is dmg+zip, so there is no need to explicitly specify target.

### Fixed Issues

$ https://github.com/Expensify/App/issues/7954
$ https://github.com/Expensify/App/issues/7987

### Tests

- [ ] Verify building Desktop still works
- [ ] Verify it produces zips for each platform in `desktop-build`

#### Contributor (PR Author) Checklist
- [x] I made sure to pull `main` before submitting my PR for review
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I clearly indicated the environment tests should be run in (Staging vs Production)
- [x] I wrote testing steps that cover success & fail scenarios (if applicable)
- [ ] I ran the tests & they passed on **all platforms**
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I added comments when the code was not self explanatory
    - [ ] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [ ] I followed proper naming convention for platform-specific files (if applicable)
    - [ ] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

#### PR Reviewer Checklist
- [ ] I verified the Author pulled `main` before submitting the PR
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [x] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I verified tests pass on **all platforms** & I tested again on all platforms
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

### QA Steps

- [x] Verify Desktop auto update works. Opening the previous (staging) version should automatically update to latest
- [x] Verify `.dmg` download links work (staging): https://staging.new.expensify.com/NewExpensify.dmg and return the installer for the latest version

### Tested On

- [ ] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Desktop

Screenshot 2022-03-03 at 20 51 42

### CODE REVIEW

**Comment by kidroca** [comment]
This PR does not need to be tested on all platforms -  the desktop build config change made, could not in any way affect other platforms

**Review by neil-marcellini — COMMENTED** [review]
It sounds like you did your research and this should fix it. The desktop build worked for me and created the zips. I'll let @roryabraham approve since he is more familiar with the desktop build.

**Comment by roryabraham** [comment]
Let's see if this works – if not, could we maybe just remove `target` altogether? I don't recall why we had to add that.

**Review by roryabraham — APPROVED** [review]

**Comment by roryabraham** [comment]
Downloading from https://staging.new.expensify.com/NewExpensify.dmg seemed to work 🤞

**Pull request merged**
