### PR TITLE
submit changes via enter

### PR DESCRIPTION
**Pull request by thesahindia**
### Details
Added the functionality to save changes on profile page and secondary login page on pressing enter

### Fixed Issues

$ https://github.com/Expensify/App/issues/7093

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open app
2. Navigate to Settings > Profile
3. Make any changes in the profile and hit "Enter" key
4. Select "Add phone number"
5. Enter Password
6. Enter phone number and hit "Enter" key
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/83179295/149005480-9e0d25f5-2532-45ae-82b0-c94841a748e5.mp4

#### Desktop

https://user-images.githubusercontent.com/83179295/149007132-d4d0d8f5-2b14-4c92-a7c7-824d0b323cc6.mov

### CODE REVIEW

**Comment by thesahindia** [comment]
@rushatgabhane, done.

**Comment by rushatgabhane** [comment]
Hi @thesahindia, your QA steps don't look correct.
Please update them

**Review by rushatgabhane — APPROVED** [review]
LGTM! No side effects on mobile, tests well and fixes the issue.
cc: @puneetlath

**Comment by thesahindia** [comment]
@rushatgabhane, oops I just pasted the QA steps from the issue forgot to change that. Updated now :)

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
