### PR TITLE
LastReadActionID cleanup

### PR DESCRIPTION
**Pull request by chiragsalian**
### Details
I made the mistake to not remove this code sooner. We had migrations that should run to delete the old rNVP but the migration did not run for some reason. Maybe it does not run when signed it from chat and not expensify. shall investigate that later. For now you can see the image has the older rNVP which is incorrect so let's remove it.
image

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/145243

### Tests
1. Confirm the account has lastRead and lastReadActionID on a report.
2. Open chat report, pin it and send a message. Switch to another chat.
3. Refresh and confirm the pinned chat that you send a message on earlier does not show up as unread.

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
LGTM and passed testing. As long as e2e tests pass we're good

**Comment by chiragsalian** [comment]
Gonna go ahead and self merge since i'd like it to go out the door sooner and i don't see much reason to wait for alberto's review.

**Comment by laurenreidexpensify** [comment]
Waiting for Chirag to confirm, and then I'll action other issue and close if necessary

**Comment by chiragsalian** [comment]
Oh hey marc. So as discussed on [slack](https://expensify.slack.com/archives/C011W8BJ9L6/p1610672334117700?thread_ts=1610669619.114900&cid=C011W8BJ9L6) yesterday the change here should not be related to https://github.com/Expensify/Expensify.cash/issues/988. That's because #988 deals with pusher and this change is because I sorta broke the functionality when I did a cleanup [here](https://github.com/Expensify/Web-Expensify/pull/29918) that went live 2 days back.

Either way from my testing, receiving new chats via pusher seem to always mark them as incorrect so maybe https://github.com/Expensify/Expensify.cash/issues/988 was addressed at some point. The issue https://github.com/Expensify/Expensify.cash/issues/988 is also pretty generic and it says `are not "always" getting marked as read` and maybe if it happens in future we mention when did it not get marked as read, if there were any js console errors etc.

**Comment by chiragsalian** [comment]
So yeah I think we should close https://github.com/Expensify/Expensify.cash/issues/988 until we can get more information when the issue happens and why. 

This brings about an interesting question. What if the contributor picked up an issue but when the worked on it they said its not reproducible on their end and then we confirm its not reproducible? Do we still pay them the whole amount? I think not and this is something that should be captured somewhere, maybe in Uwork and our contribution guidelines?

**Comment by laurenreidexpensify** [comment]
@chiragsalian Let's chat in Slack about this for more visibilty, but yeah agree it's a new scenario we should get clear on

**Pull request merged**
