### PR TITLE
Fix the InternalQA checklist loosing its state

### PR DESCRIPTION
**Pull request by mountiny**
cc @yuwenmemon would you want to review, please? :) 

### Details

We were missing passing into the array of PRs those which have internalQA label, we did not parse the InternalQA section as we do for the deploy blockers.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/198446

### Tests

- [x] Verify that no errors appear in the JS console

Automated tests already exist, they were false negatives previously showing this works although it did not work. Now they are true negatives as it should actually work.

### CODE REVIEW

**Review by yuwenmemon — APPROVED** [review]
Nice find!

**Review by yuwenmemon — APPROVED** [review]

**Comment by roryabraham** [comment]
@mountiny can you add some manual testing steps please? Maybe just:

1) create a pull request
2) label it internalQA
3) Merge it with the checklist unlocked
4) check it off on the QA checklist
5) merge another PR with the checklist unlocked
6) verify that the first PR is still checked

**Comment by mountiny** [comment]
Good shout, thanks Rory!

**Comment by mountiny** [comment]
Indeed something must be wrong with the regex, tested if the state of the checkbox has been kept and it was not: https://github.com/Expensify/App/issues/9565

**Comment by mountiny** [comment]
Good, I think I found what needs to [be done](https://github.com/Expensify/Expensify/issues/198446#issuecomment-1165994310) to get this over the finish line.

**Comment by francoisl** [comment]
@mountiny @yuwenmemon to confirm, there's no QA to do for this, right?

**Comment by mountiny** [comment]
@francoisl the QA has failed unfortunately but Rory put up a fix. I am working on a follow up as the state of the checkboxes is still being lost, but this is fine for the deploy!

**Pull request merged**
