### PR TITLE
Make Terms of Service and Privacy Policy accessible

### PR DESCRIPTION
**Pull request by elemdos**
### Details
See fixed issue

### Fixed Issues
$ https://github.com/Expensify/App/issues/5082

### Tests
1. Open Settings screen
2. Click 'About'
2. Tab through About options
3. Verify footer links (Terms of Service, Privacy Policy) focus when tabbed

### QA Steps
1. Open Settings screen
2. Click 'About'
2. Tab through About options
3. Verify footer links (Terms of Service, Privacy Policy) focus when tabbed

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/39444813/133006494-164ff4ea-5873-417f-95f7-3e0eb1e6bef5.mov

#### Mobile Web
https://user-images.githubusercontent.com/39444813/133087857-dc7b5ed6-1d4d-4fe0-981d-366a834ec25c.mov

#### Desktop
https://user-images.githubusercontent.com/39444813/133006503-1a4aed52-b706-43f7-a410-1d0dce0e983b.mov

#### iOS
https://user-images.githubusercontent.com/39444813/133006505-edaaa8b5-8558-40bd-8acf-0720947fbc35.mov

#### Android
https://user-images.githubusercontent.com/39444813/146185863-313c3413-0156-46a6-b1e8-e193ae8ff3af.mov

### CODE REVIEW

**Comment by mateomorris** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by johnmlee101 — CHANGES_REQUESTED** [review]
Can you quickly demonstrate that on any mobile device that there are no regressions in terms of the links working?

**Comment by mateomorris** [comment]
@johnmlee101 sorry for the delay, still trying to get ios/android set up locally

**Comment by mateomorris** [comment]
There was a styling issue on iOS 

image

So I updated the `TextLinks`s to use `styles.textMicroSupporting` instead of `chatItemMessageHeaderTimestamp` (which was setting a static height on the link). Looks great now. This also solves the clipping (i.e. pipes) problem brought up in the [issue](https://github.com/Expensify/App/issues/5082). 

Demos have been updated accordingly.

**Comment by johnmlee101** [comment]
Amazing! It all comes together 😄 
Looking forward to the rest of the updated demos.

**Comment by mateomorris** [comment]
@johnmlee101 sorry for the delay! Getting android set up was a doozy. Last demo added.

On that note, there's a visual regression now with the links on Android. Guessing it needs its own issue?

**Comment by kadiealexander** [comment]
Hi @mateomorris, I've placed this issue on hold as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1631754482374800), as we are prioritising issues related to a feature release scheduled for 9/24. As an apology for the delay, we will add a $100 bonus as a thank you for waiting.

**Comment by johnmlee101** [comment]
Hello! This is no longer on hold. Anything left to do here other than merge with main?

**Comment by johnmlee101** [comment]
Friendly bump!

**Comment by mateomorris** [comment]
@johnmlee101 sorry, been having some issues getting Android running locally. Just need that and this should be good to merge.

**Comment by mateomorris** [comment]
@johnmlee101 okay ready to merge!

**Review by johnmlee101 — DISMISSED** [review]

**Comment by johnmlee101** [comment]
Oh no! All commits need to be signed and your last commit wasn't. You might need to rebase locally and either force push this branch if possible or create a new PR and we can quickly move on that.

**Comment by mateomorris** [comment]
@johnmlee101 not really sure I understand that, but I merged master back into this branch and it looks like that's Verified because it was done from Github. Is that what you're looking for?

**Review by johnmlee101 — APPROVED** [review]
Let me see

**Comment by johnmlee101** [comment]
image

**Comment by johnmlee101** [comment]
You'll need all of your commits to have `Verified` next to it. 
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Review by johnmlee101 — CHANGES_REQUESTED** [review]
Let me know once that is done!

**Comment by mateomorris** [comment]
Okay @johnmlee101 figured out code signing. How should I proceed?

**Comment by johnmlee101** [comment]
The best way to do this is to try a `git rebase -f main` (I think this works with forks?) and then force push to your branch with `git push -f origin mateomorris:issue-5082` 

If the second part doesn't work, create a new PR, reference and close this one, and then we'll move it to there!

**Comment by mateomorris** [comment]
Back at this after the holidays - should have it done today if everything goes smoothly 🤞

**Pull request closed without merging**
