### PR TITLE
Fix:Bank account clickable link redirect to invalid page

### PR DESCRIPTION
**Pull request by abdel-h66**
### Fixed Issues

$ https://github.com/Expensify/App/issues/27148
PROPOSAL: https://github.com/Expensify/App/issues/27148#issuecomment-1713995113

### Tests

- [x] Verify that no errors appear in the JS console
1. Open desktop app
2. Navigate to Workspaces > Workspace > Bank account
3. A link that says `Note: To connect with Chase, Wells Fargo, Capital One or Bank of America, please click here to complete this process in a browser.` should be clickable and opens up the web app. In this step make sure you are logged in to the same account. The link will take you to new.expensify.com, but for testing you should manually rewrite the link to use localhost. 
4. The bank account tab of the workspace on web should appear with no problems
5. Another step to check is to click on the back button to trigger the `backTo` part of the navigation link. 

### QA Steps

- [x] Verify that no errors appear in the JS console
1. Open desktop app
2. Navigate to Workspaces > Workspace > Bank account
3. A link that says `Note: To connect with Chase, Wells Fargo, Capital One or Bank of America, please click here to complete this process in a browser.` should be clickable and opens up the web app. In this step make sure you are logged in to the same account. The link will take you to new.expensify.com, but for testing you should manually rewrite the link to use localhost. 
4. The bank account tab of the workspace on web should appear with no problems
5. Another step to check is to click on the back button to trigger the `backTo` part of the navigation link. 

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/144037189/f570d153-4508-4e70-bffd-9a1f719cc1f2

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by abdel-h66** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mananjadhav** [comment]
@abdel-h66 I am reviewing your PR, but please note that we need signed commits to merge the PR.

**Comment by abdel-h66** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by abdel-h66** [comment]
@mananjadhav not sure how to retrigger the check again, I'm pretty sure CLA was signed in a comment above.

**Comment by mananjadhav** [comment]
@abdel-h66 what I mean is signed commits on Github. 

If you see your commits,

image

they're missing the `Verified` tag. This is because your commits are not signed. Please sign the commits and force-push otherwise we won't be able to merge this.

image

**Comment by mananjadhav** [comment]
Also the `Test steps` are empty. Can you atleast post a comment `Same as QA Steps`. Also the QA steps, why are we specifically mentioning `Desktop`?

Also the issue mentions it is reproducible on Native android as well? Can we just post videos for all the platforms?

**Comment by abdel-h66** [comment]
Thank you very much @mananjadhav I have signed the commits now ! 

It seems like the Issue mentioning Android/native is wrong, this will only happen on Desktop based on the check 
`Boolean(getPlaidDesktopMessage())` and the function only returns a translation ID on desktop and `undefined` everywhere else. 

I will include a recording from desktop

**Comment by mananjadhav** [comment]
> this will only happen on Desktop based on the check `Boolean(getPlaidDesktopMessage())`

Thanks for clarifying. The updates look good.

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

NA

</details>

<details>
<summary>Mobile Web - Chrome</summary>

NA
</details>

<details>
<summary>Mobile Web - Safari</summary>

NA

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/3069065/a03112e1-64bf-4b4e-a33d-cb5dfaf65a9a

</details>

<details>
<summary>iOS</summary>

 NA
</details>

<details>
<summary>Android</summary>

NA
</details>


-----

@pecanoro All yours.

🎀 👀 🎀 C+ Reviewed.

**Review by mananjadhav — APPROVED** [review]

**Review by pecanoro — DISMISSED** [review]

**Comment by pecanoro** [comment]
@abdel-h66 @mananjadhav We need videos in all platforms basically making sure the flow is still working on the other platforms!

**Comment by mananjadhav** [comment]
@pecanoro That was exactly my concern but as pointed out earlier, this text and link only shows up on Desktop. This flow doesn't exist on any other platform.

**Comment by pecanoro** [comment]
@mananjadhav Yeah, I understand that, but the bank flow exist in every platform and we are modifying the components that are involved in it so we should make sure it still works until the end to make we didn't break it by adding new props (or no console errors are thrown).

**Comment by abdel-h66** [comment]
Hi @pecanoro I wasn't able to run both the ios and android on my end :/ Im still debugging the issue... Could you guys take a few minutes to check the native apps ? I personally checked on desktop and web and I didnt see any issues. 
cc @mananjadhav

**Comment by abdel-h66** [comment]
Any updates here :) ? thanks

**Comment by mananjadhav** [comment]
@pecanoro I've uploaded the videos for all the platforms. All yours.

**Comment by pecanoro** [comment]
@abdel-h66 What are the problems that you are facing when building the app? Did you post in #expensify-open-source to get some help?

**Comment by abdel-h66** [comment]
Yes I posted there, didnt get any responses but I managed to build and run the ios app, now I'm trying to do the same for the android. :) 

And by the way did you get the chance to check the recording posted by [mananjadhav](https://github.com/mananjadhav) ?

**Comment by pecanoro** [comment]
Yes, but I am waiting until you are able to test it! Can you link where you posted? Maybe I can help

**Comment by abdel-h66** [comment]
I didn't post the issue for android on the slack channel as it seems very specific to my setup. and I also didn't get the chance to work on it yesterday. But for the recording I'm pretty sure they will be same, I will add one from iOS since that's the only one I can run at the moment. 

For Android I will keep digging on the issue and post on Slack if I hit a dead end.

**Comment by pecanoro** [comment]
@abdel-h66 👍 Let me know when you do. Also don't forget web!

**Comment by mananjadhav** [comment]
@abdel-h66 as discussed with @pecanoro earlier, still waiting for the pending screencasts.

**Comment by abdel-h66** [comment]
### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/144037189/1f4db323-cfb1-4b8f-8c45-42d8ccea3123




</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/144037189/8550e743-6406-4a88-a25a-1e5ad428bdbd




</details>

<details>
<summary>Mobile Web - Safari</summary>



https://github.com/Expensify/App/assets/144037189/bc107da0-8b1a-4a74-8c86-15af204b340f


</details>

<details>
<summary>Desktop</summary>



https://github.com/Expensify/App/assets/144037189/f570d153-4508-4e70-bffd-9a1f719cc1f2


</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/144037189/32fb562c-db41-4ece-866f-53d9b2ec49ba

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/144037189/9f0af8e4-a45f-4bbd-87c8-23dfa5387ff2




</details>

**Comment by abdel-h66** [comment]
Hey @pecanoro and @mananjadhav  I just uploaded recordings from all plateforms. let me know if you have any questions. Cheers !

**Comment by pecanoro** [comment]
Thank you everyone!

**Review by pecanoro — APPROVED** [review]

**Pull request merged**
