### PR TITLE
Revert "Revert "Revert "Search suffix tree implementation"""

### PR DESCRIPTION
**Pull request by jasperhuangg**
Reverts Expensify/App#51332

$ https://github.com/Expensify/App/issues/51584

### CODE REVIEW

**Comment by jasperhuangg** [comment]
Confirmed [here](https://github.com/Expensify/App/issues/51584#issuecomment-2442411318) that the revert should fix the linked deploy blocker

**Review by NikkiWines — APPROVED** [review]
👍

**Comment by jasperhuangg** [comment]
Straight revert

**Comment by hannojg** [comment]
@jasperhuangg when testing the adhoc build i can still reproduce the issue (video is a bit long but you can see that i actually test the build from this PR and can reproduce the crash):


https://github.com/user-attachments/assets/daf06634-dadb-4e04-9fb6-2cf0914464d2



The code of the search PR is never invoked in this testing flow so its not related.

**Pull request merged**
