### PR TITLE
[HOLD] Display error (and fail) when trying to pay a money request and the displayed amount does not match the actual one

### PR DESCRIPTION
**Pull request by Gonals**
cc @mountiny, @Julesssss  

### Tests
To fully test this you'll need two accounts with a [gold wallet](https://stackoverflowteams.com/c/expensify/questions/10607) (and a [verified deposit account](https://stackoverflowteams.com/c/expensify/questions/342) or debit card).

- Log into account A and request money from account B
- Log into account B and see the money request. Go offline on account B.
- Go back to account A (online) and request some more money from B. The money request should get updated to the new amount.
- Go back to B (offline). You should not see the updated amount in the money request.
- From B (still offline), click `Pay` and, on the next option, select `Pay with Expensify`. You should now see the translucent paid request. If you get stuck here, that means you have yet to go through the KYC flow. On Dev, you can skip it by removing [these lines](https://github.com/Expensify/App/blob/0bde3f839aa45245df09d9b558eef8b59c066cf1/src/components/SettlementButton.js#L90-L93). On staging, go back online and complete it once before testing this.:
Screenshot 2022-12-29 at 4 12 30 PM

-  Go back online and wait a few seconds. You should see the error:
Screenshot 2022-12-29 at 4 13 28 PM

- Click the `X` to remove the error. The request should go back to its previous state:
Screenshot 2022-12-29 at 4 13 34 PM

- Repeat the process, but choosing `I'll settle up elsewhere` instead of `Pay with expensify`. The results should be the same.

- [x] Verify that no errors appear in the JS console

### Offline tests
Included above

### QA Steps
Same as tests

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Screenshot 2022-12-29 at 4 17 21 PM

</details>

<details>
<summary>Desktop</summary>

Screenshot 2022-12-29 at 4 18 29 PM

</details>

<details>
<summary>iOS</summary>

Screenshot 2022-12-29 at 4 47 29 PM

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by Gonals** [comment]
I'm having trouble with the Android emulator today 🤷

**Comment by Gonals** [comment]
> How can a user pay with Expensify while offline?

By following the steps above. The payment won't really happen until the user goes back online

**Comment by Gonals** [comment]
> I think I can't really use `Pay with Expensify` it needs a real account with some balance(maybe internal testing accounts). Though, I never tried it. Are there any doc/steps to complete the KYC for testers/C+?
> 
> But this PR can be tested without it. We can use `I'll settle up elsewhere`.

Ah, I think you are right, as you'll need an account with a full wallet and whatnot. You can test with `I'll settle up elsewhere`. The code in the backend is different, as it goes through a different path, but the App behavior is the same, and I tested both flows, and @madmax330 or @techievivek can do another pass if they want.

**Comment by mountiny** [comment]
> Ah, I think you are right, as you'll need an account with a full wallet and whatnot. You can test with I'll settle up elsewhere. The code in the backend is different, as it goes through a different path, but the App behaviour is the same, and I tested both flows, and @madmax330 or @techievivek can do another pass if they want.

I think we can skip the testing for Pay With Wallet, it should work same as for the other commands. The user needs to be US based so only those people who have Gold wallet can technically test. @Gonals

**Comment by Gonals** [comment]
OFF HOLD!

**Comment by mountiny** [comment]
@parasharrajat Let us know if you are able to test this one, thanks!

**Comment by Gonals** [comment]
@parasharrajat Did you manage to test this?

**Comment by mountiny** [comment]
@parasharrajat I will put this on my list to do tomorrow, no problem if you are busy with other stuff!

**Comment by mountiny** [comment]
oof, quite weird, gonna have to look into this. Any ideas @Gonals ?

**Comment by Gonals** [comment]
Hmm. Weird. Is it for specific amounts or something?

**Comment by mountiny** [comment]
@parasharrajat can you test with fresh new accounts? Both the one you sending to and from.

**Comment by mountiny** [comment]
@parasharrajat How did it go?

**Comment by Gonals** [comment]
@parasharrajat, were you able to test?

**Comment by mountiny** [comment]
@parasharrajat Get better soon!

**Comment by mountiny** [comment]
@Gonals Just wanted to test this one, but maybe it would be good to ensure what wrong with IOU right now instead of adding more puzzle pieces to it.

**Comment by Gonals** [comment]
Yep. This is still wonky, but the reasons seem to have changed. I'm just going to kill this PR and tackle the issue from scratch, as it seems to be different now.

**Pull request closed without merging**
