### PR TITLE
Ensure we show upgrade flow for GL/Payroll/Tax codes for non control policy

### PR DESCRIPTION
**Pull request by rushatgabhane**
### Fixed Issues

$ https://github.com/Expensify/App/issues/45643
$ https://github.com/Expensify/App/issues/45770
PROPOSAL:

### Tests

1. Go to a non-control policy
2. Enable tags, taxes and categories
3. Go to categories, select a category
4. Click GL and verify that upgrade modal is shown
5. Click Payroll code and verify that upgrade modal is shown
6. Go to tags and select a tag
7. Click GL and verify that upgrade modal is shown
8. Go to taxes and select a tax
9. Click tax code and verify that upgrade modal is shown

### Test 2

1. Go to Workspace settings > Taxes
2. Click on any tax
3. Click Tax code
4. Without modifying the existing tax code, save the tax code
5. Verify that modal closes and no validation error is thrown

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/df45e3d5-b1ca-4fcb-8898-be0a4049c2a1

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by rushatgabhane** [comment]
@brunovjk heads up! this PR has a deadline. We want it on **production** before end of july.

**Comment by brunovjk** [comment]
> @brunovjk heads up! this PR has a deadline. We want it on **production** before end of july.

Cool, of course! I'll review it first thing in the morning. If we're in a hurry, feel free to assign another C+ :D

**Comment by rushatgabhane** [comment]
@brunovjk that would be great thank you for the urgency 😄

**Comment by brunovjk** [comment]
@rushatgabhane should we hide the default value for a non-control policy? Example the `Tax`:
<video>

Or is it intentional to work like this? Thanks. The rest looks good to me, nice work!
I'll post the checklist today, I'm testing it on Android now.

**Comment by rushatgabhane** [comment]
@brunovjk no, i think it does not add any value to hide it.

**Comment by rushatgabhane** [comment]
@brunovjk we are going to hide the taxID for non control policy. Great suggestion! 👍

**Comment by brunovjk** [comment]
Thank you @rushatgabhane.
I'm observing some strange behavior when saving a new _Tax Code_ **for a _control policy_**. Especially for a newly created workspace:

https://github.com/user-attachments/assets/e80600ca-43d6-4457-9ed5-d1bcf95a6cd2

I didn't observe the same in `staging`.

Note: I also observe another issue, but it is reproducible in `staging` and reported here https://github.com/Expensify/App/issues/45858

**Comment by rushatgabhane** [comment]
> I'm observing some strange behavior when saving a new Tax Code for a control policy

do you mean the not found page appearing briefly?

**Comment by rushatgabhane** [comment]
It happens because we go back to the page containing new tax ID, but it does not exist until the Onyx transaction has been complete.

**Comment by brunovjk** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



https://github.com/user-attachments/assets/2094249d-dd46-491c-b91f-2f1a90f47410


</details>

<details>
<summary>Android: mWeb Chrome</summary>



https://github.com/user-attachments/assets/fb27b3ab-ef81-455a-a4ab-74d7d28a59b6


</details>

<details>
<summary>iOS: Native</summary>



https://github.com/user-attachments/assets/d2e29db1-cbcd-4210-8acc-3ed0cd6c3e29


</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/e7dc202d-a4c1-46a7-a9a8-2b0bf95ff023


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/6658ac16-571f-460c-81cd-8498a414a08c


</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/d40258a3-8075-41a0-b870-0f08bd282956


</details>

**Comment by brunovjk** [comment]
@rushatgabhane you said that _We can't really do much about it._ I believe you, but I'm not happy heheh What prevents us from implementing a check to prevent the 'not found' page? Thank you.

**Comment by brunovjk** [comment]
Hello @rushatgabhane 👋, any further thoughts or updates on this? Thanks!

**Review by brunovjk — APPROVED** [review]

**Comment by brunovjk** [comment]
> We did not find an internal engineer to review this PR, trying to assign a random engineer to #45643 as well as to this PR... Please reach out for help on Slack if no one gets assigned!

Whoever is reviewing, **before merge in please check this [comment](https://github.com/Expensify/App/pull/45866#issuecomment-2243516015)**. Thank you :D

**Comment by situchan** [comment]
@brunovjk please approve PR once more to request review from engineer (@madmax330 was just assigned in [linked issue](https://github.com/Expensify/App/issues/45643))

**Review by brunovjk — APPROVED** [review]

**Comment by brunovjk** [comment]
thank you @situchan

**Review by dangrous — DISMISSED** [review]
LGTM!

**Comment by dangrous** [comment]
Before merging....

Re the weird behavior, can we delay navigating back to the page until after the onyx has been updated with the optimistic value?

**Comment by dangrous** [comment]
Bumping the above question ^

Also, conflicts now, sorry!

**Comment by rushatgabhane** [comment]
> Re the weird behavior, can we delay navigating back to the page until after the onyx has been updated with the optimistic value?

using setTimeout? yes we can but should we?

**Comment by rushatgabhane** [comment]
@brunovjk it'd be great if you could re-review web just to make sure things are working. the merge conflict was a big one

**Comment by brunovjk** [comment]
Sure :D I will review it today. @rushatgabhane can you fix the type/lint errors? Thank you.

**Comment by dangrous** [comment]
Yeah I guess we can see how annoying it is in production, I agree we shouldn't just add a timeout, probably. Is it worth bringing up in Slack to see if anyone has good ideas to minimize the flashing?

(And happy to approve this once the lint/typescript issues are fixed!)

**Comment by rushatgabhane** [comment]
We can convert the edit tax code command to `API_WITH_SIDE_EFFECTS`. This will allow us to navigate only after the promise is complete

**Comment by rushatgabhane** [comment]
Looks like someone already fixed it on `main`.

They modified the taxID in url whenever tax code changed

https://github.com/user-attachments/assets/9f7829e4-4e37-4785-bce0-ad81923e18c2

**Comment by rushatgabhane** [comment]
@brunovjk ready for a quick re-test

**Comment by brunovjk** [comment]
Nice!! Sure, give me a moment please, I'll re-test after lunch. Thanks.

**Comment by brunovjk** [comment]
Nice!! Sure, give me a moment, I'll re-test after lunch. Thanks.

**Comment by rushatgabhane** [comment]
nice nice its dinner time in bahrain : )

**Review by brunovjk — APPROVED** [review]
I re-tested it and now it all looks good to me.

**Review by dangrous — APPROVED** [review]
great! LGTM

**Pull request merged**
