### PR TITLE
[NO-QA] Commit uncommitted npm integrity diff

### PR DESCRIPTION
**Pull request by Julesssss**
### Details

`main` is out of sync. When running `npm i` there is an uncommitted diff. I am on the correct npm version and this occurs even after a full `npm run clean`.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/216678

### Tests

- Run `npm i`
- Ensure there is no local diff

### Screenshots

N/A

### CODE REVIEW

**Comment by Julesssss** [comment]
Github is refusing to show the PR diff, so here it is: 

Screenshot 2022-06-29 at 10 21 43

**Comment by Julesssss** [comment]
@MonilBhavsar @bondydaa not sure how you were both assigned, my bad. Please double check that you actually see the local diff before checking out this branch -- in case it's an error on my side. Thanks!

**Review by MonilBhavsar — COMMENTED** [review]
Let's discuss here https://expensify.slack.com/archives/C01GTK53T8Q/p1656495537023109
It looks like this is because of different hashing algorithms used and it depends upon OS.

**Comment by Julesssss** [comment]
Seems like we should just close this, as we should default to the M1 MBP diff.

**Pull request closed without merging**
