### PR TITLE
Inconsistent Android back button behavior while navigated to a modal view

### LINKED ISSUE #2066: Inconsistent Android back button behavior while navigated to a modal view
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

## Expected Result:
The Android hardware back button should work when pressed.

## Actual Result:
When you open the settings page the first back button press is ignored (as if an extra invisible page was added to the page stack), but the second and third back button press work as expected. 

## Action Performed:
1. Open the settings modal
2. Press the back button 

## Platform: 
Android

**Notes/Photos/Videos:** 

- This issue is caused by a bug in `react-navigation` and must be fixed in that repo first. 
- **See:** https://github.com/react-navigation/react-navigation/issues/9364
- Workarounds will not be accepted.

**Expensify/Expensify Issue URL:**
https://github.com/Expensify/Expensify/issues/157248
**Upwork link:** https://www.upwork.com/jobs/~016d2a711284ef2fc7

### PR DESCRIPTION
**Pull request by ahmedahtazaz**
@marcaaron Version upgrade of @react-navigation/drawer to 5.12.5

### Details
Version upgrade of @react-navigation/drawer to 5.12.5

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2066

### Tests
1. Open the settings modal by tapping on the profile image.
2. Press back button from android hardware.

### QA Steps
1. Open the settings modal by tapping on the profile image.
2. Press back button from android hardware.

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
This works perfectly fine for me. @ahmedahtazaz can you please add test and QA steps here?

**Comment by ahmedahtazaz** [comment]
Testing steps added.

**Comment by ahmedahtazaz** [comment]
@marcaaron  i have tested it on Android 6 real device and Android 11 emulator. Which Android versions have you tested on?

**Review by thienlnam — APPROVED** [review]
Approving since the package install worked fine for me and the tests worked on my device, handing it to you @marcaaron

**Comment by marcaaron** [comment]
Cool. Let's see how this goes. Worst case scenario we will look into upgrading the other dependencies if there are any issues.

**Comment by ahmedahtazaz** [comment]
Yeah okay cool. Let's hope for the best

**Pull request merged**
