### PR TITLE
Revert changes introduced by PR 2183

### LINKED ISSUE #2207: Android - Chat - Tapping plus opens chat instead of new or group chat options
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
2 options appear. One to create a new chat and one to create a group.

## Actual Result:
Opens the chat window, + button non functional

## Action Performed:
1. Launch the app and login
2. Tap the +button

## Workaround:
No workaround. 

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android ✔️ 
 Desktop App
 Mobile Web

**Version Number:** 1.0.11-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Issue not reproducible in production. 

https://user-images.githubusercontent.com/44479856/113362234-eb89aa80-931b-11eb-9f81-1b667ce59ddb.mp4

**Expensify/Expensify Issue URL:**

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
The PR is blocking the deploy.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2207

### QA Steps
Repeat steps in linked issue and retest deploy blocker

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [x] Android

#### Android
https://user-images.githubusercontent.com/32969087/113901335-775f6480-976a-11eb-834b-1a1f55fa26d2.mp4

### CODE REVIEW

**Comment by marcaaron** [comment]
Tested on Android, assuming other platforms are fine.

**Review by roryabraham — APPROVED** [review]
LGTM 👍

**Comment by roryabraham** [comment]
Merging before E2E finishes because this resolves a deploy blocker

**Comment by botify** [comment]
@roryabraham looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Pull request merged**
