### PR TITLE
pointer on top within close account page

### PR DESCRIPTION
**Pull request by mateusbra**
### Details
Style change for pointer to start on top on android on close account page

### Fixed Issues

$ https://github.com/Expensify/App/issues/7380

### Tests | QA Steps

1. login with new expensify account
2. go to settings
3. go to security page
4. go to close account page
5. verify that the pointer starts on top

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web
image

#### Desktop
Captura de Tela 2022-02-01 às 09 49 49

#### iOS
Captura de Tela 2022-02-01 às 13 02 21

#### Android
image

### CODE REVIEW

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Change looks good. But please fix the template 
image


Then test it on all platforms and add the screenshots. We are on the verge of making this mandatory for all PRs.

**Comment by mateusbra** [comment]
@parasharrajat tested on all platforms and fixed the template

**Review by parasharrajat — APPROVED** [review]
LGTM.

cc: @iwiznia 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by mateusbra** [comment]
@iwiznia do you think we have to change something, or its ok for this PR?

**Review by iwiznia — APPROVED** [review]

**Pull request merged**
