### PR TITLE
Rename Card-Rev-Share-for-Approved-Partners.md to Expensify-Card-Reve…

### PR DESCRIPTION
**Pull request by johncschuster**
### Details
No material changes. I've just updated the name of the file so that the title of the page will be updated as well. (See the Slack thread below for context)

I'm attempting to change the title to: `Expensify Card Revenue Share for ExpensifyApproved! Partners`

I added a `!` to the filename. I'm not sure if that's going to be an issue.

### Fixed Issues

https://expensify.slack.com/archives/C03TBKRSB/p1693269796992579?thread_ts=1692710155.273599&cid=C03TBKRSB

### CODE REVIEW

**Review by Julesssss — COMMENTED** [review]
Hey @johncschuster. So this change seems fine, but when I looked for the file I noticed we seem to have a duplicate file. The only difference seems to be that it's missing the `# About` header, and that it has `Expensify-` at the beginning of the file name.

Do you think we can delete that file too? 

Screenshot 2023-08-30 at 11 45 43

**Comment by johncschuster** [comment]
@Julesssss whoa, I didn't know there was a dupe. Is it in the same folder?

Also, when you say that the key difference is the `# About` header, can you show me what you mean? Is that a header in Markdown (that should be visible to the reader) or is that a header in the code?

**Comment by Julesssss** [comment]
> whoa, I didn't know there was a dupe. Is it in the same folder?

Nah, the dupe is located here: 
```
App/docs/Card-Rev-Share-for-Approved-Partners.md
```
Screenshot 2023-08-30 at 15 34 37

________________________________

And the one you edited (the good one) is located here: 
```
App/docs/articles/other/Card-Rev-Share-for-Approved-Partners.md
```
Screenshot 2023-08-30 at 15 34 41

**Comment by Julesssss** [comment]
Let's fix this and merge it next week, after the conference hold ins lifted

**Comment by Julesssss** [comment]
Hey @johncschuster, does this still need to be done? It looks like you might have completed this is a separate PR?

**Review by Julesssss — COMMENTED** [review]
There are a bunch of conflicts now. If we still need this PR i will resolve them myself

**Comment by johncschuster** [comment]
It sounds like this change was resolved in a different PR. Let's not worry about getting this one merged.

**Comment by Julesssss** [comment]
Cool. I might have been mistaken about that too. But lets close this for now

**Pull request closed without merging**
