### PR TITLE
feat: ui improvements of <code></code> 

### LINKED ISSUE #986: Blocks of `quoted` text render incorrectly on mobile
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

View the job on Upwork [here](https://www.upwork.com/jobs/~01fc428a62f97f17a2).

**Platform - version:**  

iOS and Android, build 263

**Action Performed (reproducible steps):**

1. Type a sentence with code block formatting (single ticks) in the middle, like this:

This is a test to `see how code renders in the middle` of a sentence on mobile.

2. Notice that it renders strangely by either breaking the line or overflowing.

**Expected Result:**

It should render the same way it does here on GitHub.

This is a test to `see how code renders in the middle` of a sentence on mobile.

**Actual Result:**

The line either breaks or overflows where the code formatting starts/ends

**Notes/Photos/Videos:** 

We've seen multiple results from this bug. Here are some examples:

101217023-6e804a00-3635-11eb-9bb9-2e37a0eeccbb

102281699-4c22f080-3f94-11eb-878b-345b9d978e46

### PR DESCRIPTION
**Pull request by sakul-budhathoki**
### Details
In existing code that text is rendered inside <View> so that it doesn't work as inline. So, I have replaced it with <Text>. With this changes it works as expected but some styles will not work on mobile device. (border, border radius, margin, padding) as Text inside Text in react native doesn't obey these styles. 

### Fixed Issues
Fixes #986 

### Tests
1. Sign Up
2. Navigate to chat view
3. Type message with  using ticks that will convert it into code blocks ``
4. View the formatting 

 Example message:  Hello I am testing bug `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore`. Are you a bot?

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

### Screenshots
<Add any necessary screenshots for all platforms if your change added or updated UI>

#### Web
Screen Shot 2020-12-25 at 10 34 20 AM

#### Mobile Web
Simulator Screen Shot - iPhone 11 - 2020-12-25 at 10 38 43

#### Desktop

Screen Shot 2020-12-25 at 10 43 43 AM

#### iOS
Simulator Screen Shot - iPhone 11 - 2020-12-25 at 10 15 52

#### Android
android

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by sakul-budhathoki** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by sakul-budhathoki** [comment]
recheck

**Comment by marcaaron** [comment]
>some styles will not work on mobile device

This doesn't seem like the solution we want then right? cc @shawnborton

**Comment by shawnborton** [comment]
Agree, the styles should be identical across platforms.

**Comment by sakul-budhathoki** [comment]
Hi @marcaaron @shawnborton . We can achieve below style across all platform. But it will lack border, border-radius and padding. 

Screen Shot 2020-12-30 at 10 53 00 AM

**Comment by shawnborton** [comment]
Ideally this would have the border radius/border on all platforms. Can you elaborate on why that is difficult to achieve? What roadblocks are you running into?

**Comment by sakul-budhathoki** [comment]
For web and desktop app there is no problem. But for mobile app The <code> block is rendered inside <Text> block. So, these styles are not working.

**Comment by sakul-budhathoki** [comment]
Hi @shawnborton . I am looking forward to close this PR. What will be next step to resolve this issue?

**Comment by shawnborton** [comment]
We need this style to look the same on all platforms, so any solution offered that doesn't not achieve that would be considered unacceptable.

**Comment by jboniface** [comment]
@sakul-budhathoki do you intend to complete the work on this issue?

**Comment by sakul-budhathoki** [comment]
Hi @jboniface . I have tried many things to fix this issue but couldn't fix it completely. We can only achieve below style. So, I think we can close the contract.  Thank you.

Screen Shot 2021-02-02 at 12 34 45 PM

**Pull request closed without merging**
