### PR TITLE
[WIP] Playing around with image assets

### PR DESCRIPTION
**Pull request by shawnborton**
cc @AndrewGable 

This is working great on iOS:
image

But on web, the image assets are only served up at @1x, which makes them appear low-resolution on nice retina screens:
image

### Fixed Issues
Fixes GH_LINK

### Tests
<Tests you performed on all platforms that validates your changed worked>

### Screenshots
<Add any necessary screenshots for all platforms if your change added or updated UI>

### CODE REVIEW

**Review by roryabraham — CHANGES_REQUESTED** [review]
Two questions:

1) With this approach, do we have to manage which image is actually used when we import / `require` it for use in the code? i.e: how do the scalings take effect?
2) NAB, but why do we have to use CJS `require`  instead of regular ES6 `import` statements like we do for all other imports?

**Comment by AndrewGable** [comment]
Sounds good, should we clean this PR up and submit it then additionally add SVGs? Or what is your thought on what will be easiest for design?

**Comment by shawnborton** [comment]
I think it would be beneficial for us if we had the ability to change the svg fill color via the code. So this way we would only have to supply one image asset as an .svg, and we would define fill colors as styles (:hover, inactive versus active, theming, etc).

**Comment by shawnborton** [comment]
Actually I wonder if it makes sense to make a clear P/S statement for a Upwork post? This could be a good contractor issue I think.

**Comment by roryabraham** [comment]
> I think it would be beneficial for us if we had the ability to change the svg fill color via the code

I think that's totally possible.

> This could be a good contractor issue I think.

Agreed

**Comment by shawnborton** [comment]
Going to close this for now in favor of getting this in the works: https://github.com/Expensify/Expensify/issues/149127

**Pull request closed without merging**
