### PR TITLE
Cache node_modules/gems/pods in workflows

### LINKED ISSUE #3627: [GH Actions] Set up caching for npm installs in all our workflows
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

# Problem
We do not perform any caching of node modules in our GitHub Actions, and therefore each time we run `npm ci` it can take up to 5 minutes.

# Why is this important?
This is currently one of the biggest bottlenecks across all our Expensify.cash CI/CD. Setting up caching should speed up our testing and deployment substantially. I don't have data to back this, but I would guess that we could improve the average execution time of certain workflows by more than 50%.

# Solution
Use the [actions/cache](https://github.com/actions/cache) to [cache our dependencies and speed up our workflows](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows).

[view this job on Upwork](https://www.upwork.com/jobs/~0179958076458d2f36)

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by attaradev**
### Details

Cache `node_modules` in all tasks that install npm packages to speedup workflows

### Fixed Issues

Fixes #3627 

### Tests / QA Steps
1. Merge this PR
1. Verify that tests happen as they should, but with caching.

### Tested On

n/a – GitHub only.

### CODE REVIEW

**Comment by mikeattara** [comment]
@roryabraham you can have a look, and let me know what you think.
Thanks

**Review by roryabraham — COMMENTED** [review]
Overall looks good - just the comment about using single quotes instead of double quotes for consistency

**Comment by rushatgabhane** [comment]
I know it's not related to node, but shouldn't we cache ruby gems and CocoaPods too?

Screenshot_20210627-171216

**Comment by mikeattara** [comment]
@roryabraham, should I cache the `gems` and `cocoapods`?

**Comment by roryabraham** [comment]
> should I cache the `gems` and `cocoapods`

Yes please!

**Comment by mikeattara** [comment]
@roryabraham Done

**Comment by roryabraham** [comment]
@mikeattara What about the [gems](https://github.com/Expensify/Expensify.cash/blob/a4234e9c80d5322c0eea9d35b247a07b602b56a4/.github/workflows/e2e.yml#L20) and [pods](https://github.com/Expensify/Expensify.cash/blob/a4234e9c80d5322c0eea9d35b247a07b602b56a4/.github/workflows/e2e.yml#L41) in the E2E tests?

**Comment by mikeattara** [comment]
@roryabraham, I've cached them now. Thought the [pods](https://github.com/Expensify/Expensify.cash/blob/a4234e9c80d5322c0eea9d35b247a07b602b56a4/.github/workflows/e2e.yml#L41) was updating and would not need to be cached

**Review by roryabraham — APPROVED** [review]
Okay, @mikeattara I'm approving these changes. But just FYI since we're live-testing them, my plan is to revert this PR if there are any issues. In that case, you'll have to follow-up with another PR to fix any issues.

**Comment by roryabraham** [comment]
@mikeattara I think that this _may_ have caused an error in our [last production deploy](https://github.com/Expensify/Expensify.cash/runs/3013495578?check_suite_focus=true). Can you please look into that?

**Comment by mikeattara** [comment]
@roryabraham looking into it

**Comment by mikeattara** [comment]
Can you try re-deploying?

**Comment by mikeattara** [comment]
@roryabraham, I think the issue is not with the cache but installing the pods

**Comment by roryabraham** [comment]
Okay, thanks for investigating. Will keep this on my radar during the next prod deploy.

**Pull request merged**
