### PR TITLE
Fixing duplicate Concierge chat

### PR DESCRIPTION
**Pull request by ugogiordano**
Resolving the issue of duplicate concierge chat appearing in the LHN when using deeplinks to access the concierge.

### Fixed Issues

$ https://github.com/Expensify/App/issues/44465
PROPOSAL: https://github.com/Expensify/App/issues/44465#issuecomment-2380587321

### Tests

1. Sign in at https://expensify.com/ with an email that doesn't have an account
2. Press Support from the left navigator and then select Concierge.
3. Copy the URL into a new tab and replace the hostname with https://staging.expensify.com/
4. Verify that only one Concierge chat is displayed.

[Here](https://github.com/Expensify/App/issues/44465#issuecomment-2416909187) is a video demonstrating the steps to reproduce the issue.

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Sign in at https://expensify.com/ with an email that doesn't have an account
2. Press Support from the left navigator and then select Concierge.
3. Copy the URL into a new tab and replace the hostname with https://staging.expensify.com/
4. Verify that only one Concierge chat is displayed.

[Here](https://github.com/Expensify/App/issues/44465#issuecomment-2416909187) is a video demonstrating the steps to reproduce the issue.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/3ea07133-fc00-4c1a-96d3-c780312942f0

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/02ac929c-3eeb-4bcb-b662-1da23bd3057e

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/c0df98e9-4327-424b-8e9e-97689c3ea49d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/247fc9a9-7966-40ba-9420-c63861286c9f

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/92c8771d-d084-4690-bca3-1d0564f57643

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by trjExpensify** [comment]
@getusha can you review this one today, please?

**Comment by ugogiordano** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ugogiordano** [comment]
recheck

**Comment by ugogiordano** [comment]
@getusha I was able to build the android app after pulling from the main branch. I uploaded the video.

**Review by aldo-expensify — CHANGES_REQUESTED** [review]
@ugogiordano there are some linter checks failing, can you fix them please to continue with this 🙏

**Comment by ugogiordano** [comment]
Hi @aldo-expensify,

Sorry for the late reply—I didn't notice the failing checks earlier. Thanks for pointing it out!

**Comment by aldo-expensify** [comment]
There is a check failing because of the existing `withOnyx`:

```
/home/runner/work/App/App/src/pages/ConciergePage.tsx
  73:16  error  'withOnyx' is deprecated. Use `useOnyx` instead of `withOnyx` whenever possible.
```

Can you replace that with `useOnyx`? 🙏 

@getusha friendly bump for reviewing this

**Comment by ugogiordano** [comment]
@aldo-expensify, I see that 'withOnyx' is still used on other pages. Should it be refactored everywhere? This might need to be handled in a separate issue.

**Comment by aldo-expensify** [comment]
> @aldo-expensify, I see that `withOnyx` is still used on other pages. Should it be refactored everywhere? This might need to be handled in a separate issue.

No, no need to refactor other files. I think if you just fix it in the file you touches the checks should pass.

**Comment by ugogiordano** [comment]
> > @aldo-expensify, I see that `withOnyx` is still used on other pages. Should it be refactored everywhere? This might need to be handled in a separate issue.
> 
> No, no need to refactor other files. I think if you just fix it in the file you touched the checks should pass. The check is complaining only about `ConciergePage.tsx`.

That's clear, but I'm only referring to the `ConciergePage.tsx`. Replacing `withOnyx` with `useOnyx` in the `ConciergePage.tsx` requires deleting other code as well. Here's the result:

```
import {useFocusEffect} from '@react-navigation/native';
import React, {useCallback, useEffect, useRef} from 'react';
import {View} from 'react-native';
import {useOnyx} from 'react-native-onyx';
import ReportActionsSkeletonView from '@components/ReportActionsSkeletonView';
import ReportHeaderSkeletonView from '@components/ReportHeaderSkeletonView';
import ScreenWrapper from '@components/ScreenWrapper';
import useResponsiveLayout from '@hooks/useResponsiveLayout';
import useThemeStyles from '@hooks/useThemeStyles';
import Navigation from '@libs/Navigation/Navigation';
import * as App from '@userActions/App';
import * as Report from '@userActions/Report';
import ONYXKEYS from '@src/ONYXKEYS';

/*
 * This is a "utility page", that does this:
 *     - If the user is authenticated, find their concierge chat and re-route to it
 *     - Else re-route to the login page
 */
function ConciergePage() {
    const styles = useThemeStyles();
    const isUnmounted = useRef(false);
    const {shouldUseNarrowLayout} = useResponsiveLayout();
    const [session] = useOnyx(ONYXKEYS.SESSION);
    const [isLoadingReportData] = useOnyx(ONYXKEYS.IS_LOADING_REPORT_DATA, {initialValue: true});

    useFocusEffect(
        useCallback(() => {
            if (session && 'authToken' in session) {
                App.confirmReadyToOpenApp();
                Navigation.isNavigationReady().then(() => {
                    if (isUnmounted.current || isLoadingReportData === undefined || !!isLoadingReportData) {
                        return;
                    }
                    Report.navigateToConciergeChat(true, () => !isUnmounted.current);
                });
            } else {
                Navigation.navigate();
            }
        }, [session, isLoadingReportData]),
    );

    useEffect(() => {
        isUnmounted.current = false;
        return () => {
            isUnmounted.current = true;
        };
    }, []);

    return (
        <ScreenWrapper testID={ConciergePage.displayName}>
            <View style={[styles.borderBottom, styles.appContentHeader, !shouldUseNarrowLayout && styles.headerBarDesktopHeight]}>
                <ReportHeaderSkeletonView onBackButtonPress={Navigation.goBack} />
            </View>
            <ReportActionsSkeletonView />
        </ScreenWrapper>
    );
}

ConciergePage.displayName = 'ConciergePage';

export default ConciergePage;
```

**Comment by aldo-expensify** [comment]
> I was wondering if we could take another look at the compensation for this job.

In my opinion the change is too small to consider extra compensation and having to retest isn't reason enough either. I asked for a second opinion in https://expensify.slack.com/archives/C03TQ48KC/p1732059846984899, and there was agreement on not being enough to consider extra compensation.

If you still think you should have extra compensation feel free to bring it up in `#expensify-open-source`.

Thanks for committing the update to use `useOnyx` anyway.

@getusha please review when you have some time 🙇

**Comment by ugogiordano** [comment]
> > I was wondering if we could take another look at the compensation for this job.
> 
> In my opinion the change is too small to consider extra compensation and having to retest isn't reason enough either. I asked for a second opinion in https://expensify.slack.com/archives/C03TQ48KC/p1732059846984899, and there was agreement on not being enough to consider extra compensation.
> 
> If you still think you should have extra compensation feel free to bring it up in `#expensify-open-source`.
> 
> Thanks for committing the update to use `useOnyx` anyway.
> 
> @getusha please review when you have some time 🙇

No problem. I just saw other issue asking the same small refinement, and that’s why I asked. 

Can I ask you how I can join that slack channel? I’ve submitted the required form several times with no luck.

**Comment by ugogiordano** [comment]
> @ugogiordano let's update the tests step
> 
> 1. Sign in at https://expensify.com/ with an email that doesn't have an account
> 2. Press `Support` from the left navigator and then select Concierge.
> 3. Copy the URL into a new tab and replace the hostname with https://staging.expensify.com
> 4. Verify that only one Concierge chat is displayed.

@getusha done!

**Comment by ugogiordano** [comment]
> @ugogiordano thanks! the QA steps as well and we don't need offline tests

@getusha done!

**Review by getusha — APPROVED** [review]

**Comment by aldo-expensify** [comment]
> Can I ask you how I can join that slack channel? I’ve submitted the required form several times with no luck.

Seems like we are having issues for the moment with adding new users to the slack channel:

> We have a small issue with adding users at the moment and we’re working with Slack to try and get this resolved. If you would like to join, [fill out this form](https://forms.gle/Q7hnhUJPnQCK7Fe56) with your email and Upwork profile link. Once resolved, we’ll add you.

is this the form you already filled?

**Comment by ugogiordano** [comment]
> > Can I ask you how I can join that slack channel? I’ve submitted the required form several times with no luck.
> 
> Seems like we are having issues for the moment with adding new users to the slack channel:
> 
> > We have a small issue with adding users at the moment and we’re working with Slack to try and get this resolved. If you would like to join, [fill out this form](https://forms.gle/Q7hnhUJPnQCK7Fe56) with your email and Upwork profile link. Once resolved, we’ll add you.
> 
> is this the form you already filled?

Yes that's the form I've submitted a couple of times.

**Comment by aldo-expensify** [comment]
> Yes that's the form I've submitted a couple of times.

Ahh, I think this is an ongoing issue and probably won't help to submit it more times. Sorry about that! You will just have to wait until a solution is found on our end.

**Review by aldo-expensify — APPROVED** [review]

**Pull request merged**
