### PR TITLE
fix: update highlighted emoji skin tone when the selected one changes

### PR DESCRIPTION
**Pull request by BeeMargarida**
### Details

In the emoji skin tone list, update the highlighted item when the selected skin tone changes, fixing the bug where two skin tones become selected when they are changed in another device.

### Fixed Issues

$ https://github.com/Expensify/App/issues/14644   
https://github.com/Expensify/App/issues/14644#issuecomment-1459976724

### Tests

1. Open Expensify in the browser and in iOS (or Android) using the same account
2. Go to the same chat in both the browser and the device and open the emoji popover
3. In the browser, select a skin tone and check the selected skin tone in the device
4. Verify that only the skin tone selected in the browser appears highlighted in the device 

- [X] Verify that no errors appear in the JS console

### Offline tests

This feature does not change the behaviour of offline mode.

### QA Steps

Same as above:

1. Open Expensify in the browser and in iOS (or Android) using the same account
2. Go to the same chat in both the browser and the device and open the emoji popover
3. In the browser, select a skin tone and check the selected skin tone in the device
4. Verify that only the skin tone selected in the browser appears highlighted in the device 

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/25725586/224006262-95081734-b91c-468b-a822-fcdc6a8bab97.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/25725586/224006289-14707e07-d145-4110-9360-50d07b2a4aef.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/25725586/224006313-57c10796-f8ca-4e78-b0c2-e0210f928cbe.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/25725586/224006333-dc9976f6-d2f7-47bd-912e-fab47dd292f9.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/25725586/224006357-434dca1e-3392-48db-ade4-7c53697c1824.mp4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/25725586/224006419-7a061cf3-8a9c-465d-8add-5ccd2d84bb9e.mp4

</details>

### CODE REVIEW

**Comment by BeeMargarida** [comment]
I've not tested using a High traffic account since I don't think it's needed for this fix, but please let me know if that is not the case

**Comment by BeeMargarida** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by BeeMargarida** [comment]
Updated

**Comment by BeeMargarida** [comment]
Updated

**Review by thesahindia — APPROVED** [review]
Looks good and tests well!

All yours @francoisl

**Comment by francoisl** [comment]
I was checking on [this internal convo](https://github.com/Expensify/App/issues/14644#issuecomment-1462628188), looks like we're good to move forward here 👍 

Code looks good, waiting for the automated tests to finish.

**Review by francoisl — APPROVED** [review]

**Pull request merged**
