### PR TITLE
Emoji Category Shortcuts Bar Tooltip

### PR DESCRIPTION
**Pull request by akshayasalvi**
### Fixed Issues

$ https://github.com/Expensify/App/issues/15108   
PROPOSAL: https://github.com/Expensify/App/issues/15108#issuecomment-1440483855

### Tests

**For Desktop and Web**

1. Open the app
2. Go to any chat
3. Click on the Emoji Icon
4. Hover over the category icons
5. Ensure that you are able to see the Tooltip
6. You can change the language and confirm that the tooltip shows up in the selected language.
7. Click on the Emoji Category Icon, and confirm it scrolls to the correct category
8. Attempt the steps 3-6 on a new account to see that `Frequently Used` category is not shown and still the steps work fine.

**For mWeb and Mobile Apps**

1. Open the app
2. Go to any chat
3. Click on the Emoji Icon
4. Click on the Emoji Category Icon, and confirm it scrolls to the correct category
5. Attempt the steps 2-4 on a new account to see that `Frequently Used` category is not shown and still the steps work fine.

- [x] Verify that no errors appear in the JS console

### Offline tests

NA

### QA Steps

**For Desktop and Web**

1. Open the app
2. Go to any chat
3. Click on the Emoji Icon
4. Hover over the category icons
5. Ensure that you are able to see the Tooltip
6. You can change the language and confirm that the tooltip shows up in the selected language.
7. Click on the Emoji Category Icon, and confirm it scrolls to the correct category
8. Attempt the steps 3-6 on a new account to see that `Frequently Used` category is not shown and still the steps work fine.

**For mWeb and Mobile Apps**

1. Open the app
2. Go to any chat
3. Click on the Emoji Icon
4. Click on the Emoji Category Icon, and confirm it scrolls to the correct category
5. Attempt the steps 2-4 on a new account to see that `Frequently Used` category is not shown and still the steps work fine.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Screenshot 2023-02-27 at 11 27 12 PM

**v1**
https://user-images.githubusercontent.com/57435789/221661937-ba95e97f-1c3b-48a5-a057-21796e0356f0.mp4

**v2**

https://user-images.githubusercontent.com/57435789/222346542-4f509bd4-77db-4c71-80df-21a7ae131814.mp4

**v3**

Screenshot 2023-03-02 at 12 59 02 PM

**v4 with 4px padding**

Screenshot 2023-03-02 at 7 05 31 PM

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screenshot 2023-02-28 at 12 26 11 AM

</details>

<details>
<summary>Mobile Web - Safari</summary>

Screenshot 2023-02-28 at 12 44 14 AM

</details>

<details>
<summary>Desktop</summary>

Screenshot 2023-02-27 at 11 29 44 PM

**v1**
https://user-images.githubusercontent.com/57435789/221662042-4ef1cfeb-6943-4df7-8764-2acfa55183b8.mp4

**v2**

https://user-images.githubusercontent.com/57435789/222346208-3adbf0c9-a0cd-498b-9fe6-baff5f6a6ebb.mp4

**v3**
Screenshot 2023-03-02 at 12 59 02 PM

**v4 with 4px padding**

Screenshot 2023-03-02 at 7 05 54 PM

</details>

<details>
<summary>iOS</summary>

Screenshot 2023-02-28 at 1 27 19 AM

</details>

<details>
<summary>Android</summary>

Screenshot 2023-02-27 at 11 50 04 PM

</details>

### CODE REVIEW

**Comment by akshayasalvi** [comment]
@aimane-chnaif @stitesExpensify PR is ready for review. I've had some issues with iOS pod setup. I treied working it out other branch and it worked fine, but here I had to reinstall the pods. Can you confirm if you face the same issue?

**Review by aimane-chnaif — COMMENTED** [review]
https://user-images.githubusercontent.com/96077027/221858134-6c294dad-57d0-47b6-8583-1b3d33fe93f0.mov

When hover top and bottom part of icon, tooltip not showing though highlighted

**Review by aimane-chnaif — CHANGES_REQUESTED** [review]

**Comment by akshayasalvi** [comment]
> When hover top and bottom part of icon, tooltip not showing though highlighted

@aimane-chnaif That's what I wanted to highlight in this [comment](https://github.com/Expensify/App/issues/15108#issuecomment-1446770718). Because `Tooltip` is attached to the `View` it only and hence it doesn't show up for `Pressable`. If we want to put on Pressable, then we'll have to wrap it around the View, pass the styles and update accordingly. Let me know if you that needs to be done.

cc - @stitesExpensify

**Comment by akshayasalvi** [comment]
I will be online in a few hours and I will update PR later today.

**Comment by akshayasalvi** [comment]
I requested a review again from @aimane-chnaif and it accidentally removed @stitesExpensify. PR is ready with the updates and comments addressed.

**Comment by akshayasalvi** [comment]
@aimane-chnaif thanks for the diff, I've updated as per your requirement. But I checked the other tooltip if you closely observe there's always some spacing between the element and their tooltip, that's what I was trying to achieve.

**With the current implementation**
Screenshot 2023-03-02 at 11 34 08 AM

**Other tooltips**
Screenshot 2023-03-02 at 11 34 16 AM
Screenshot 2023-03-02 at 11 34 28 AM

**Comment by akshayasalvi** [comment]
@aimane-chnaif The video that I uploaded again in the GH PR body consists of the style change as well. I uploaded v1 and v2 for Web and Desktop. Attaching the image also here for your reference.

image

**Review by aimane-chnaif — DISMISSED** [review]

**Comment by akshayasalvi** [comment]
@aimane-chnaif Based on @shawnborton's comment I've updated the spacing to 4px.

**Comment by shawnborton** [comment]
Thank you!

**Comment by akshayasalvi** [comment]
@stitesExpensify @aimane-chnaif bump on the change and tagging because @stitesExpensify was removed from the reviewer list.

**Review by aimane-chnaif — APPROVED** [review]

**Comment by akshayasalvi** [comment]
@stitesExpensify were you able to check this PR? Any action items for me?

**Comment by stitesExpensify** [comment]
Hi, I was OOO sick for most of last week. Reviewing now

**Review by stitesExpensify — APPROVED** [review]
Code LGTM! Testing now

**Comment by akshayasalvi** [comment]
Thanks for the approval @stitesExpensify. Hope you're feeling better now.

**Pull request merged**
