### PR TITLE
[A/B Testing][ESLint Clean Up] Use useOnyx cases for files in combinedTrackSubmit

### PR DESCRIPTION
**Pull request by fabioh8010**
### Details

cc @grgia 

This PR migrates the touched components from https://github.com/Expensify/App/pull/49007 to `useOnyx`:

- AccessOrNotFoundWrapper
- AttachmentPickerWithMenuItems
- FloatingActionButtonAndPopover
- IOURequestStepAmount
- IOURequestStepDistance
- IOURequestStepScan
- IOURequestStepParticipants
- ReportWelcomeText

### Fixed Issues

$ https://github.com/Expensify/App/issues/49593
PROPOSAL: https://github.com/Expensify/App/pull/49007#issuecomment-2363871566

#### AccessOrNotFoundWrapper

1. Navigate to a non-existent workspace by URL / deep link (/settings/workspaces/999999/profile).
2. Assert the Not Found page is shown.

#### AttachmentPickerWithMenuItems

1. Go to any chat.
2. Click the + button to open the meny and assert all the options shown work as expected.

#### FloatingActionButtonAndPopover

1. Click the Global Create button to open the menu.
2. Assert all the options shown work as expected.

#### IOURequestStepAmount / IOURequestStepParticipants

1. Click the Global Create button to open the menu and start submit an expense.
2. Go to the Manual tab, assert you can insert an amount and change the currency.
3. Assert there is a list of participants and choose one.
4. Assert you are able to navigate to the confirmation page and finish the flow.

#### IOURequestStepScan

1. Start submit, track or split an expense.
2. Go to the Scan tab, assert you can upload a receipt.
3. Assert you are able to navigate to the confirmation page and finish the flow.

#### IOURequestStepDistance

1. Start submit, track or split an expense.
2. Go to the Distance tab, assert you can insert a start and stop address for the map.
3. Assert you are able to navigate to the confirmation page and finish the flow.

#### ReportWelcomeText

1. Go to a chat with another user.
2. Assert the welcome text is displayed.

Screenshot 2024-10-03 at 11 00 13

- [x] Verify that no errors appear in the JS console

### Offline tests

Same.

### QA Steps

Same.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/794cb026-7fc5-4785-bc7f-ecfe2d17f52f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/ada66a35-3639-4c74-a6e0-76bea9a5c8ed

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/a13d29ce-a3a9-42ad-98d4-f42800aa1c00

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/3728b86b-2444-4177-9c20-fc56c52bc3fc

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/a3cfad82-005c-4d6f-a2c5-b2e5437340ea

https://github.com/user-attachments/assets/bfbf05a1-0efd-40f1-a372-baf6f8b2308f

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/ecb0609d-36f3-4033-9837-570a8c09bdbf

</details>

### CODE REVIEW

**Comment by grgia** [comment]
@fabioh8010 I created a separate issue for tracking [here](https://github.com/Expensify/App/issues/49593)

**Comment by grgia** [comment]
@fabioh8010 let me know when this PR is ready for review and a test build. I'd like to try and get this one merged ASAP as we need to merge the component to start testing

**Comment by fabioh8010** [comment]
@grgia I will put this on HOLD once https://github.com/Expensify/App/pull/49007 is completed.

**Comment by grgia** [comment]
@fabioh8010, could we start a review on this? I can create a test build

**Review by MonilBhavsar — DISMISSED** [review]
Looks good

**Review by grgia — DISMISSED** [review]
Nice work writing out the QA steps!

**Comment by grgia** [comment]
@shubham1206agra all yours for final review

**Comment by grgia** [comment]
@fabioh8010 could you fix conflicts?

**Comment by fabioh8010** [comment]
@grgia @shubham1206agra Done

**Comment by grgia** [comment]
@fabioh8010 looks like there's conflicts again 🙇

**Comment by fabioh8010** [comment]
> I am unable to record the video, but I am seeing blank screen on refresh of amount page.

@shubham1206agra Could you share which platform you tested and reproduction steps for this?

**Comment by fabioh8010** [comment]
@shubham1206agra I'm having consistent behavior during the refresh between `main` and this branch (tested with throttling), could you check if you have same behavior on `main`?

**main**

https://github.com/user-attachments/assets/50983e17-b74c-48eb-9d11-9a8936e4b6c6

**branch**

https://github.com/user-attachments/assets/8d14968c-59c7-4e5e-90a8-2eace47edbaa

**Comment by fabioh8010** [comment]
@shubham1206agra Fixed!

**Comment by MonilBhavsar** [comment]
@shubham1206agra over to you

**Review by shubham1206agra — APPROVED** [review]

**Review by MonilBhavsar — APPROVED** [review]
Thanks!

**Review by grgia — APPROVED** [review]

**Comment by grgia** [comment]
Hmm, all tests were passing when I merged. Looks like the test was skipped? But should be fine.

**Comment by IuliiaHerets** [comment]
This PR is failing because of issue #51247

**Comment by Julesssss** [comment]
Reverted this PR here, as it introduced a deploy blocker -- Track Expense option wasn't shown to expensifail (or all private domain) users

**Pull request merged**
