### PR TITLE
Fix: iOS autoscroll when `<input/>` is focused

### PR DESCRIPTION
**Pull request by rawalyogendra**
### Details

- Forcing mWeb(Chrome) to use "old" [Viewport resize behavior](https://developer.chrome.com/blog/viewport-resize-behavior/).
- Hiding the `input` when it is focused so that mWeb(Safari) does not scroll the whole page.
- Disabling all scroll behaviors(overscroll & touch gestures) on `body`

### Fixed Issues

$ https://github.com/Expensify/App/issues/14716
PROPOSAL: https://github.com/Expensify/App/issues/14716#issuecomment-1428241878

### Tests

1. Opened a workspace > Reimburse expenses > Connect bank account > Connect Manually
2. Entered Routing Number: 123123123
3. Entered Account Number: 1111222233331111
4. Clicked on Continue, it showed Company Information form.
5. Filled up the Company information form.
6. Verified that it did not generate black area above keyboard in iOS Safari and Chrome.

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open any workspace > Reimburse expenses > Connect bank account > Connect Manually
2. Enter Routing Number: 123123123
3. Enter Account Number: 1111222233331111
4. Click Continue, it will show Company Information form.
5. Fill up the Company information form.
6. Verify that it does not generate black area above keyboard in iOS Safari and Chrome as shown in video.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/7548730/218550374-f7be2e0a-28bf-4777-8d4f-1bf593b6b940.mov
</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/7548730/217104784-cb88d865-acf8-4a16-a135-b8974fd39d76.mp4
</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/7548730/217112698-63078519-057c-4856-8c61-364126ee375c.mov
</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/7548730/218551322-1924108d-119a-4a44-bbb3-d26927d92056.mov
</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/7548730/218553773-1d5c3851-ce2c-4dfe-b422-5bd9ef73df81.mov
</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/7548730/218551756-ef9b1f7d-2f39-4bd7-9e2e-b61f640618c8.mp4
</details>

### CODE REVIEW

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
I've reviewed the changes but I'll need more time to test. 

@rawalyogendra Can you also tag issue https://github.com/Expensify/App/issues/14815 and confirm with screencasts that this is also getting fixed with this PR.

**Comment by mananjadhav** [comment]
@rawalyogendra did you get a chance to look at my previous comment?

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/3069065/219811782-0bbba10c-8d26-41b7-9685-467e43900fe8.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/3069065/219811823-334896b9-3620-4023-a481-3ec8b7bee190.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/3069065/219811846-a2c6340b-bfb5-422f-afba-a37ee126bae8.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/3069065/219811866-8c32ea8e-28e4-43a0-aec9-0f834f11756b.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/3069065/219812162-073d5ffe-1d5a-431e-b4d9-d3db824fef5e.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/3069065/219812547-1da05410-cf07-45cc-8237-f8e638b61372.mov

</details>

**Comment by mananjadhav** [comment]
Thanks for the PR @rawalyogendra. It took a bit of time, I've checked basic screens like Form (Connect Bank Account, Company, Personal Info, Close Account) , New Chat, New Group Chat, Change Password, Chat, Sidebar, Timezone Update. I am guessing these should be enough to cover the testing for the keyboard related changes.

@puneetlath All yours.

**Comment by JmillsExpensify** [comment]
@puneetlath this would be a good one to put on your radar this week, as it's an older issue that we're trying to close the loop on. Thank you!

**Review by puneetlath — APPROVED** [review]

**Comment by rawalyogendra** [comment]
@mananjadhav I apologize for not being able to participate in the review process of this PR. I was OOO due to health issues. 

Please let me know if you want me to add anything to the PR.

**Comment by bernhardoj** [comment]
Hi, the auto scroll issue still happens on a multiline text (`textarea`). 

https://user-images.githubusercontent.com/50919443/223169848-d16ac330-96a2-42fc-9ce8-2d9232bdd5f1.mov

We should just add the opacity animation to `textarea` selector.

cc: @mananjadhav @rawalyogendra

**Comment by puneetlath** [comment]
@bernhardoj is this in relation to an issue that you're actively working on? If not, I think it makes the most sense to report the bug in #expensify-bugs. Thanks!

**Comment by bernhardoj** [comment]
@puneetlath Not really. Got it, I will report it. Thank you!

**Comment by s77rt** [comment]
This PR caused a regression https://github.com/Expensify/App/issues/16082. [Animating/Changing opacity on focus](https://github.com/rawalyogendra/App/blob/9e830eea0af2668db8306d4e8d610afa5e218fbe/web/index.html#L59) caused flickering effect.

**Comment by benomatis** [comment]
This PR appears to have introduced one of the errors in issue #30619 Sign in - Error messages in console when accessing and using sign in page

**Comment by mananjadhav** [comment]
We added `overscroll-behavior` behavior which caused the gestures to stop working on the web causing this issue https://github.com/Expensify/App/issues/51704.

**Pull request merged**
