### PR TITLE
NewChatFix

### PR DESCRIPTION
**Pull request by johndev0711**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
<Explanation of the change or anything fishy that is going on>

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes GH_LINK

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by johndev0711** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by MariaHCD — CHANGES_REQUESTED** [review]
Hi, @johndev0711! Is this ready for review? Please update the PR description with the missing sections including the link to the original issue (so that I may have context on what the PR is trying to fix) and your tests! In addition, there seem to be some JavaScript lint errors

**Comment by johndev0711** [comment]
Thanks for your effort.
I think that I've already updated the PR description with the original
issue link "https://github.com/Expensify/Expensify.cash/issues/1968", and
this was displayed as "#1968" on the description.
And the first request has the lint errors, but I've checked them and
reopened the pull requests. If there need any correction or reopening of
the PR, inform me please.
Hope to hear from you soon.
Best regards.
Thank you.
John A.

**Comment by MariaHCD** [comment]
Thanks for the information, @johndev0711. I see that you have another PR (https://github.com/Expensify/Expensify.cash/pull/2103) to fix the issue. So I believe this PR should be closed in favor of https://github.com/Expensify/Expensify.cash/pull/2103. Let me know!

**Comment by johndev0711** [comment]
I've sent a new pull request at the #2013 .
Thanks for your kindness.

**Pull request closed without merging**
