### PR TITLE
fix: categories subtitle shows undefined settings when there is sync error

### PR DESCRIPTION
**Pull request by mkzie2**
### Details

This PR:

- On workspace settings pages (categories, tags, taxes and report fields), not shows `imported from [integration] settings` text  when having integration sync error
- On workspace accounting page, shows the `Go to Expensify Classic to manage your settings.` text when synced with unsupported integration

### Fixed Issues

$ https://github.com/Expensify/App/issues/49394
PROPOSAL: https://github.com/Expensify/App/issues/49394#issuecomment-2359922547

### Tests

1. In OD, try to connect to Quickbooks Desktop but do not complete the set up to trigger error
3. In ND, open workspace settings > Categories
4. Verify `Get a better overview of where money is being spent...` message shows
-------
1. Install QuickBooks Desktop [here](https://quickbooks.intuit.com/learn-support/en-us/new-subscriptions/download-a-trial-of-quickbooks-desktop/00/185974)
2. In OD, connect to QuickBooks Desktop **successfully** following [this](https://help.expensify.com/articles/expensify-classic/connections/quickbooks-desktop/Connect-To-QuickBooks-Desktop)
3. In ND, open workspace settings > Categories
4. Verify `The categories below are imported from Quickbooks Desktop settings.` message shows
4. Press `Quickbooks Desktop settings`
5. Verify `Go to Expensify Classic to manage your settings.` message shows without any integration menu (Import, Export, Advanced...) or error message

- [x] Verify that no errors appear in the JS console

### QA Steps

See Tests

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot_1727831055
Screenshot_1727831061

-----

Screenshot_1727831164
Screenshot_1727831169

</details>

<details>
<summary>iOS: Native</summary>

Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 00 16
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 00 24
------
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 07 00

Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 06 55

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 02 24
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 02 31
-----
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 11 44
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-02 at 08 11 49

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/f0d1c233-7f7f-4087-9df5-7ba85e3c2edc

https://github.com/user-attachments/assets/35a471aa-39cd-4be3-a939-d41dc78114b9

</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2024-10-02 at 07 59 20
Screenshot 2024-10-02 at 07 59 18
Screenshot 2024-10-02 at 08 16 22
Screenshot 2024-10-02 at 08 16 20

</details>

### CODE REVIEW

**Comment by brunovjk** [comment]
@mkzie2  were we able to resolve the type error? I'll fill out the checklist after. Thank you :D

**Comment by mkzie2** [comment]
@brunovjk Done.

**Comment by brunovjk** [comment]
Great work so far @mkzie2. I have just two points before I continue with the checklist:

1 - Do we really need to create a new `CONST` `UNSUPPORTED_CONNECTIONS`? During the week I'll come back to investigate further, mayne ask for guidance, don't worry about it for now.
2 - I think we need to do the same for all the other tabs (check which ones need), do you agree?

https://github.com/user-attachments/assets/f4bd462b-3a97-4ad6-a4e0-3acd3534e0da

Thank you very much :D

**Comment by brunovjk** [comment]
Excuse @mkzie2 did you have a chance to take a look at my [last comment](https://github.com/Expensify/App/pull/49972#issuecomment-2395028592)? Thanks.

**Comment by brunovjk** [comment]
Got it, thanks a lot for the clarification. Great! I'll wait for your update so I can continue with the review. Please let me know if you need anything.

> Also note that the original issue: "... imported from your undefined settings" was fixed for QBD on `main`.

Hmm, I'll take a closer look in a bit, I wonder if it's been fixed for other tabs and connections as well? Thank you very much.

**Comment by mkzie2** [comment]
@brunovjk This is a BE issue, it was fixed from the BE so all tabs are fixed.

**Comment by brunovjk** [comment]
Great, very good :D thank you @mkzie2. Do you think we can close the issue then?

**Comment by mkzie2** [comment]
Based on https://github.com/Expensify/App/issues/49394#issuecomment-2370439560, we have 2 requirements:

> 1. Display `The categories below are imported from QuickBooks Desktop` (or the name of the connected integration, even if it's not yet supported) to make the messaging consistent.
> 2. On the policy's accounting page, show the `Go to Expensify Classic to manage your settings.` text.

The `undefined settings` bug is just 1️⃣. We still need to fix 2️⃣.

However I have one concern: Currently, when `hasSyncError`, all the workspace settings like categories, tags,... has not been imported from integration settings yet but we still show the `imported from ...` subtitle. That's confusing.

We might not want to fix issue 1️⃣ but I think we SHOULD fix the issue that I just mentioned. The solution is already implemented by [this change](https://github.com/Expensify/App/pull/49972/files#diff-c42ce6620ce9f24877cffda579d486f8c60ebb0ad577eb5dfcdcb9584208c915R291).

Wdyt?

**Comment by brunovjk** [comment]
> However I have one concern: Currently, when `hasSyncError`, all the workspace settings like categories, tags,... has not been imported from integration settings yet but we still show the `imported from ...` subtitle. That's confusing.
> 
> We might not want to fix 1️⃣ but I think we SHOULD fix the issue I just mentioned. The solution is already implemented by [this change](https://github.com/Expensify/App/pull/49972/files#diff-c42ce6620ce9f24877cffda579d486f8c60ebb0ad577eb5dfcdcb9584208c915R291).
> 
> Wdyt?

I agree 100%! Let's stick with the plan :D Maybe we need to update the test steps? Let me know when I can test it, Thank you.

**Comment by mkzie2** [comment]
@brunovjk These test steps in PR description already covered that case:

Screenshot 2024-10-10 at 18 24 29

I applied changes to other tabs, you can start testing now.

**Review by brunovjk — APPROVED** [review]
Overall the changes seem good to me, however I still wonder if do we need to specify in [`PolicyUtils.getCurrentConnectionName`](https://github.com/Expensify/App/blob/e5a9a9e88b8c24f6a14414334bc80e0c9611925f/src/libs/PolicyUtils.ts#L987-L994) that we accept `includeUnsupportedConnection`, nor create a [`CONST`](https://github.com/mkzie2/App/blob/e5a9a9e88b8c24f6a14414334bc80e0c9611925f/src/CONST.ts#L2396-L2400) for it. @mkzie2  explained why we need it [here](https://github.com/Expensify/App/pull/49972#issuecomment-2404631469), but I would like to know your opinion on this @justinpersaud. Thank you.

**Comment by mkzie2** [comment]
@justinpersaud TL;DR One of the original issues ("imported from **undefined** settings" text when integrating QBD) is fixed in BE so basically we won't need the changes that @brunovjk mentioned above.

But if we want to prevent future unsupported integrations (QBD used to be unsupported) from reintroducing the `undefined` text issue, we SHOULD keep those changes.

**Comment by justinpersaud** [comment]
I was just looking internally and it's likely because we just finished supporting Quickbooks in the backend very recently. 

Personally, I don't think we need to keep the code there for that as it was specific to this use case so I think you can go ahead and remove it.

**Comment by brunovjk** [comment]
Great! I agree 100% thank you @justinpersaud :D 

cc: @mkzie2

**Comment by mkzie2** [comment]
@brunovjk Updated.

**Comment by brunovjk** [comment]
Thank you very much for the changes @mkzie2. I retested and noticed a bug where even with _"connection error"_ `hasSyncError` is `false`, this way we never show the error message. I tested with different `policies` and [`connectionSyncProgress`](https://github.com/Expensify/App/blob/2c211a03948ebc1dfb20ee2f836d9669051acf2f/src/pages/workspace/accounting/PolicyAccountingPage.tsx#L64) it is always `undefined`:

https://github.com/user-attachments/assets/c455902b-a7f4-447f-8989-b3bdba4fbab1

I don't believe this bug is related to our PR, it seems more like an issue with the backend, but I can't confirm it. @mkzie2 did you reproduce the same bug or were you able to test everything normally? Thanks again.

**Comment by mkzie2** [comment]
@brunovjk I do not face that problem. I got `hasSyncError=true` and the error was saved in `policy.connections`. I guess it's BE bug. Could you retry on `main`?

**Comment by brunovjk** [comment]
> @brunovjk I do not face that problem. I got `hasSyncError=true` and the error was saved in `policy.connections`. I guess it's BE bug. Could you retry on `main`?

Great @mkzie2, I tested it again and this part actually works fine. However, there is one thing, even if the connection is not fully completed in OldDot we initially treat it as if it was successfully completed in NewDot, but we have not yet finished the setup. This leads to a bug where, if in OldDot you close the page before completing the setup, in NewDot we treat it as if it was completed:

https://github.com/user-attachments/assets/f31403a8-70a6-4097-a6ce-17863481af1c


Do you think we can/should fix this through FE? Thanks a lot.

cc: @justinpersaud

**Comment by justinpersaud** [comment]
Hmm that is pretty minor but I will get a second opinion

**Comment by brunovjk** [comment]
Great, besides that everything looks good here @justinpersaud, all yours :D Thanks.

**Review by justinpersaud — APPROVED** [review]

**Pull request merged**
