### PR TITLE
Reroute user trying to link to VBA steps they cannot complete

### PR DESCRIPTION
**Pull request by roryabraham**
### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/168078

### Tests / QA Steps (web/mWeb only)
1. Sign up with a new account.
1. Create a new workspace.
1. Click on `Settings` -> `Your Workspace` -> `Connect bank account`.
1. Attempt to go to the following routes: 
    - `/bank-account/company`
    - `/bank-account/personal-information`
    - `/bank-account/contract`
    - `/bank-account/validate`
    - `/bank-account/enable`

    And verify that for each you remain on this page (note that the URL will change but the UI should not:
    
    image

1. Hit `Enter Manually`
1. Enter `011401533` for the routing number and `1111222233331111` for the account number, check the box, then hit save and continue.
1. Attempt to go to the following routes:

    - `/bank-account/personal-information`
    - `/bank-account/contract`
    - `/bank-account/validate`
    - `/bank-account/enable`
    
    And verify that for each you remain on the company step.

1. Hit the back arrow.
1. Verify that you see the account and routing number you entered.
1. Attempt to go to `bank-account/personal-information` and verify that you are taken back to the company step.
1. Enter company details, then press save and continue.
1. Attempt to go to the following routes:
    - `/bank-account/contract`
    - `/bank-account/validate`
    - `/bank-account/enable`
    
    And verify that for each you remain on the requestor (personal-information) step.

1. Hit the back arrow.
1. Verify that you see the company details you entered before.
1. Attempt to go to `bank-account/contract` and verify that you are taken back to the requestor step.
1. Enter personal details, then press save and continue. (TODO: I am not able to get past this, even on `main`)

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by luacmartins — COMMENTED** [review]
Left a comment. Still need to test it.

**Review by luacmartins — COMMENTED** [review]
A couple more comments:

1. I seem to be redirected to the bank-account step when trying to complete step 7. I see the following console error `Warning: Failed prop type: Invalid prop isChecked of type string supplied to Checkbox, expected boolean.`

https://user-images.githubusercontent.com/22219519/139771889-553ae7d1-4484-4688-b382-8942a6dcd1c3.mov

2. I also noticed that when hitting the back arrow none of the fields are filled. I see the same console error above.

https://user-images.githubusercontent.com/22219519/139771996-70ad88bd-5bfe-44ad-a26f-a4e3cc3940bc.mov

I still need to do more testing. But those were my findings for now.

**Comment by luacmartins** [comment]
Did some more testing today but didn't find anything that wasn't already reported.

**Comment by luacmartins** [comment]
@roryabraham just checking if this is still being worked on?

**Comment by roryabraham** [comment]
Sorry, I dropped the ball on this one ... It is now really out-of-date so I'm just going to close it.

**Comment by roryabraham** [comment]
Reopened the linked issue

**Pull request closed without merging**
