### PR TITLE
[NO QA] Fix `tests/unit/getPullRequestsMergedBetweenTest.sh`

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
The [`-S` flag](https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt--Sltkeyidgt) was causing cherry picks to be signed, we can safely remove the flag and the tests will still be effective.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/191675

### Tests
1. Turn off signing in your git config
2. Run the script locally and verify it passes 👍 
3. Verify the tests pass in this PR

### QA Steps
N/A - Unit test, no code changes

### CODE REVIEW

**Review by roryabraham — DISMISSED** [review]

**Comment by roryabraham** [comment]
@AndrewGable While testing this you might have messed up your commit signing:

image

**Review by MariaHCD — DISMISSED** [review]
LGTM! Just need those unverified commits to be verified.

**Comment by AndrewGable** [comment]
lol nice catch, I did turn off signing! Fix incoming shortly

**Comment by AndrewGable** [comment]
Ok first time doing a signed rebase, but I think it all worked!

**Review by roryabraham — APPROVED** [review]

**Comment by roryabraham** [comment]
Thanks again for figuring this out!

**Pull request merged**
