### PR TITLE
[Form Provider Refactor] RoomNameInput fixes

### PR DESCRIPTION
**Pull request by kowczarz**
### Details

Followup to https://github.com/Expensify/App/pull/29771

### Fixed Issues

$ https://github.com/Expensify/App/issues/28877
$ https://github.com/Expensify/App/issues/31566

### Tests

IMPORTANT: User needs to have the permission to use policy rooms enabled.

Workspace new room:
1. Log in
2. Press `+` button > Press `Start chat` > Switch to `# Room`
3. Check if errors appears when incorrect data is typed in
4. Check if when spaces are replaced with `-`
5. Type correct data and create a new room

Room name:
1. Log in
2. If there are no rooms, create a new one (steps above)
3. In the chat room press its name > Press `Settings` > Press `Room name`
4. Check if the room name is propagated
5. Check if errors appears when incorrect data is typed in
6. Check if when spaces are replaced with `-`
7. Type correct data and update the name of the room

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
        - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/91068263/784ccc3d-8502-4f75-9a28-d550c324f98a

https://github.com/Expensify/App/assets/91068263/fb62271d-1dcc-4585-9721-1be843cb9e99

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/91068263/74ac5206-db49-41f2-9091-17ce6c2248fc

https://github.com/Expensify/App/assets/91068263/6878040d-0583-497e-b44a-b5e636eb440f

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/91068263/5ac9d84a-fc56-43e6-8ad6-304edef69017

https://github.com/Expensify/App/assets/91068263/b429b179-bff2-4a39-88f5-f2493cdffd6f

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/91068263/bde16033-a6ed-41a5-af46-c10b3b7347e9

https://github.com/Expensify/App/assets/91068263/7770c27a-04b6-4c03-8e13-239574c4308b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/91068263/d9a7d06d-d3ea-4214-9c56-01eb2552790e

https://github.com/Expensify/App/assets/91068263/899c7760-da85-4e98-903e-024f058a517c

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/91068263/3d69e1f0-63f3-451f-8543-a8e45379d303

https://github.com/Expensify/App/assets/91068263/023724bb-06bd-4d25-bfaa-c06f724157d1

</details>

### CODE REVIEW

**Comment by kowczarz** [comment]
Hello @luacmartins! I reverted the revert of room name input and fixed issues caused by the changes:
- https://github.com/Expensify/App/issues/30500
- https://github.com/Expensify/App/issues/30504
But I couldn't reproduce https://github.com/Expensify/App/issues/30507

**Comment by luacmartins** [comment]
Thanks for working on this! Let's retest the PR and make sure those cases are fixed!

**Review by blazejkustra — APPROVED** [review]

**Comment by kowczarz** [comment]
Hey @luacmartins I did some tests and @blazejkustra did a cross check, so now we are quite confident that there should be no more issues.

**Comment by luacmartins** [comment]
Thanks for checking. @allroundexperts do you think you'll be able to review this soon?

**Comment by luacmartins** [comment]
@kowczarz could you please fix conflicts?

**Comment by kowczarz** [comment]
@allroundexperts done. I see there are lot of changes in `src/components/RoomNameInput/index.native.js` - I had to resolve conflicts twice there, but it will be removed anyways, so if you will spot another conflict in that file, feel free to review the PR, it most likely won't affect the final version of the code.

**Comment by luacmartins** [comment]
Thanks for fixing the conflicts @kowczarz. @allroundexperts this should be ready for review

**Comment by luacmartins** [comment]
Maybe it came from this blocker? https://github.com/Expensify/App/issues/31654

**Comment by luacmartins** [comment]
@kowczarz can you merge main to fix the issue above?

**Comment by luacmartins** [comment]
bump @kowczarz

**Comment by kowczarz** [comment]
Now it's fine 

https://github.com/Expensify/App/assets/91068263/f8db8232-4552-41fd-90bc-0f799634bc8a

**Review by luacmartins — APPROVED** [review]
LGTM!

**Comment by luacmartins** [comment]
All yours @allroundexperts

**Comment by kowczarz** [comment]
@allroundexperts bump

**Review by allroundexperts — APPROVED** [review]
Looks good!

**Review by luacmartins — APPROVED** [review]

**Comment by nkuoch** [comment]
This PR caused [this regression](https://github.com/Expensify/App/issues/32398).

**Comment by luacmartins** [comment]
@kowczarz we reverted this PR because it caused the following regressions:

- https://github.com/Expensify/App/issues/32386
- https://github.com/Expensify/App/issues/32398
- https://github.com/Expensify/App/issues/32399

**Pull request merged**
