### PR TITLE
use time-analytics-webpack-plugin

### PR DESCRIPTION
**Pull request by ShuiRuTian**
### Details

Replace `speed-measure-webpack-plugin` with `time-analytics-webpack-plugin`

The output will be changed from 
Expensify_first
to
image

And the issue is fixed
image

This will improve the build speed too. 
In my machine, the first build time is reduced from 47s to 34s, and the rebuild time is reduced from 10s to 3s.

NOTE: @svgr/webpack plugin seems to take a very long time, this reason is it's async and write many files. Sadly we will record the end time only when the callback is triggered, this will make it not accurate because of how event loop works.

### Fixed Issues

$ https://github.com/Expensify/App/issues/13123
PROPOSAL: https://github.com/Expensify/App/issues/13123#issuecomment-1333215577

### Tests

1. run `npm run web` to start the webpack-dev-server
1. When the site opens, verify that there is an inline script in the `<head>` tag which contains the JS for the splash screen.
1. Compare the build time, verify the build time is reduced about 10s.
1. Open the network tab of Chrome's dev tools, and throttle your internet connection to `Slow 3G`
1. Refresh the page, and verify that the splash screen is displayed instead of a blank white screen while the main JS bundle is downloading.

- [x] Verify that no errors appear in the JS console

### Offline tests
None

### QA Steps (web only)
1. Open the chrome dev tools and throttle your internet connection to `Slow 3G`
1. Refresh the page, and verify that the splash screen is displayed instead of a blank white screen while the main JS bundle is downloading.
1. Verify that there is an inline `<script>` tag in the `<head>` tag.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

image

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Review by Santhosh-Sellavel — CHANGES_REQUESTED** [review]
@ShuiRuTian Issue is not linked properly, that's it doesn't request a Review request from us here.
Should look like
$ https://github.com/Expensify/App/issues/13123

**Comment by Santhosh-Sellavel** [comment]
@roryabraham Please add yourself as a reviewer here or @techievivek please add @roryabraham here thanks!

**Comment by Santhosh-Sellavel** [comment]
Please fill author checklist and add test steps.

@roryabraham  this one is No QA right?

**Comment by roryabraham** [comment]
@ShuiRuTian Please fill out the checklist in the PR description and provide screenshots. I think that in this case screenshots of the web and desktop platforms alone are sufficient, ideally including a successful webpack build in part of the screenshot. You can skip iOS and Android. We unfortunately will not be able to merge this PR until the checklist is filled out and screenshots are provided.

**Comment by roryabraham** [comment]
I updated test and QA steps as I saw fit, and marked this as internal QA

**Comment by roryabraham** [comment]
@ShuiRuTian You'll also need to retroactively sign commits on this branch. We are unable to merge pull requests which contain any unsigned commits.


I think that the easiest way to do that would be to follow the instructions in [this article](https://www.manthanhd.com/2021/06/18/how-to-retroactively-sign-all-commits-in-a-branch/).

You'll also need to:

1. Ensure that you're using Node 16/npm 8 (I strongly recommend using `nvm` to manage npm versions)
1. Run `npm i`
1. Commit the diff in `package-lock.json`

**Review by roryabraham — CHANGES_REQUESTED** [review]
Need to:

- Retroactively sign commits
- Commit diff in `package-lock.json`
- Fill out the author checklist
- Provide screenshots
- Test local staging webpack build with `npm run build-staging`

**Comment by ShuiRuTian** [comment]
Auh, have to say sorry, 

I do not have MacOS and I am developing on wsl2(Debian). I could only verify the build on web is fine. But when I want to run `npm run desktop`, there is something wrong happened.

So I could not provide screenshot for Desktop env, sorry for that.

-----
However, I found a strange thing.

In my personal understanding, the App wants to show a pretty icon for users when loading the "main" script(about 10M). However, I think it's not possible now.

The App is using "defer" scripts:
image

And the splash is using "DOMContentLoaded" event to run:
image

According to MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event

The event is triggered after all "defer" scripts are downloaded and executed, so, it seems that it does work as expected way, right?

**Comment by Santhosh-Sellavel** [comment]
@ShuiRuTian 
Commits are signed but yet unverified, please add your GPG key to your GitHub profile refer [this](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account) 

> Fill out the author checklist
Feels like I checked all reasonable check lists?

Check applicable/not applicable items too, by checking we confirm that it's not applicable or applicable and we did that.

**Comment by Santhosh-Sellavel** [comment]
@roryabraham Seems @ShuiRuTian has found something [here](https://github.com/Expensify/App/pull/13399#issuecomment-1342094863).

Any thoughts on this?

> Open the network tab of Chrome's dev tools, and throttle your internet connection to Slow 3G
> Refresh the page, and verify that the splash screen is displayed instead of a blank white screen while the main JS bundle is downloading.

I see a blank screen for some time and splash for a few secs and immediately app loads

**Comment by roryabraham** [comment]
Thanks for the observation @ShuiRuTian, and it seems like you're correct. This PR seems to be functioning as expected (i.e: the script tag is inlined as expected), so I'm tempted to say we should move forward with getting it approved and merged to resolve the existing problems with `SpeedMeasurePlugin`.

Regarding the issue you've described, I think what we might want is something like this:

1. Use https://github.com/architgarg/html-webpack-injector to inject the splash screen JS in the end of the body instead of in the document head
    - I've got a local branch implementing this change
1. Update https://github.com/icelam/html-inline-script-webpack-plugin so that it can prevent inline tags from having the `defer` attribute, and ensure that the inline tag for the splash screen JS does not have the `defer` attribute.
    - I've got a local branch implementing this change.


I think that should guarantee that the [splash screen JS](https://github.com/Expensify/App/blob/fcbe4c0429375fcebf9f57e800a786e049e5cb75/web/splash/splash.js):

- Runs after [the div for the splash screen](https://github.com/Expensify/App/blob/3e050bd5de58f594dc07a0b2e9f2720b3f0a9bd2/web/index.html#L77-L79) is mounted
- Does not wait for the main or vendor JS bundles to be downloaded and evaluated before executing.

Anyways, I need to do some more testing but I think that's the direction I'm likely to want to go with this.

We might be able to optimize things further from there by updating https://github.com/icelam/html-inline-script-webpack-plugin to be able to leverage "async inline tags", as described in [this article](https://www.phpied.com/asynchronous-inline-scripts-via-data-urls/).

**Comment by roryabraham** [comment]
@ShuiRuTian I still don't see the diff in package-lock.json committed in this PR

**Comment by ShuiRuTian** [comment]
@roryabraham Sorry for that, I forget to push...

@Santhosh-Sellavel I should verify the GPG now, could you please help me check again?

**Comment by Santhosh-Sellavel** [comment]
@ShuiRuTian For this issue it's fine, but please avoid force pushes in the future, thanks!

**Review by roryabraham — DISMISSED** [review]
LGTM and seems to test well, but I'll let @Santhosh-Sellavel review and test as well

**Comment by Santhosh-Sellavel** [comment]
Commits are not signed yet @ShuiRuTian

**Comment by ShuiRuTian** [comment]
Auh, sorry, I think I need to force push again to sign the commit

**Comment by ShuiRuTian** [comment]
@roryabraham Could you please approve this PR again?

**Comment by Santhosh-Sellavel** [comment]
## Build time  Comparision
### Before
#### Web
Screenshot 2022-12-11 at 10 32 05 PM

#### Desktop
Screenshot 2022-12-11 at 10 32 42 PM

### After

#### Web
Screenshot 2022-12-11 at 10 27 22 PM

#### Desktop
Screenshot 2022-12-11 at 10 27 16 PM

**Review by Santhosh-Sellavel — APPROVED** [review]
> This PR seems to be functioning as expected (i.e: the script tag is inlined as expected)

Looks good to me
Checklist: https://github.com/Expensify/App/pull/13399#issuecomment-1344627585
Build time: https://github.com/Expensify/App/pull/13399#issuecomment-1345607041

Please run workflow checks before merging @roryabraham!

**Comment by techievivek** [comment]
@roryabraham Travis seems to fail when I ran the worflow here.

**Comment by ShuiRuTian** [comment]
@techievivek Did you mean the "lint code"? But it's kind of strange, I did not change any shell.

**Comment by Santhosh-Sellavel** [comment]
@ShuiRuTian Can you merge latest main in your branch!

**Comment by Santhosh-Sellavel** [comment]
@roryabraham or @techievivek run work flow checks here please!

**Comment by techievivek** [comment]
@ShuiRuTian You will need to sign the commits, the latest one is not signed.

**Comment by ShuiRuTian** [comment]
Auh, then I need to force push again...

**Review by techievivek — APPROVED** [review]
Looks good, merging it given everyone else already approved it.

**Comment by techievivek** [comment]
NVM, I see the checklist is filled, so not sure why it applied the emergency label.

**Comment by chiragsalian** [comment]
I'm checking this off from the QA checklist but I'm not certain why this is internal. QA can check the developer tool and check code source to see if there is an inline script tag.

In my testing even on slow 3G it was too fast to see a splash screen and i see many script tags loaded in. Was there a specific one to look for? Also I do not see a white screen on refresh so i guess that's good. 

I'll be checking this off now but feel free to re-test it.

**Comment by blazejkustra** [comment]
@ShuiRuTian This plugin breaks Fast Refresh for some reason, please check the issue I reported [here](https://github.com/ShuiRuTian/time-analytics-webpack-plugin/issues/10) 🙏

**Pull request merged**
