### PR TITLE
Fix Image Attachments

### LINKED ISSUE #2844: Chat - Sent images are not displayed in chat
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
The picture I have uploaded is visible

## Actual Result:
Uploaded pictures aren't displayed

## Action Performed:
1. Go to https://staging.expensify.cash
2. Choose Chat C
3. I press plus then ADD Attachment

## Workaround:
Unknown

## Platform:
Where is this issue occurring?

 Web ✔️
 iOS
 Android
 Desktop App
 Mobile Web ✔️

**Version Number:** 1.0.43-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/118062405-de24fe80-b364-11eb-950a-dce971f90ee8.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___
From @JmillsExpensify https://expensify.slack.com/archives/C01GTK53T8Q/p1620853811137000

### PR DESCRIPTION
**Pull request by thienlnam**
### Fixed Issues

Fixes https://github.com/Expensify/Expensify.cash/issues/2844

### Tests / QA Steps

1. Upload an image, and make sure it is viewable and that you can click it to open the image modal

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

Screen Shot 2021-05-14 at 11 06 18 AM

#### Mobile Web

Screen Shot 2021-05-14 at 12 04 53 PM

#### Desktop

Screen Shot 2021-05-14 at 12 05 56 PM

#### iOS

Screen Shot 2021-05-14 at 12 03 22 PM

#### Android

Screen Shot 2021-05-14 at 12 08 05 PM

### CODE REVIEW

**Comment by roryabraham** [comment]
@thienlnam Do you want help testing this? Let's get screenshots for all platforms.

**Comment by thienlnam** [comment]
I was hoping to get localization back but still trying to figure out how to do that with this library.  I'm also thinking we can just merge this since it will fix the images and figure out localization later.  In that case, I can start testing on other platforms!

**Comment by thienlnam** [comment]
Tested on all platforms and they're working as expected, let's just get this out 👍

**Review by roryabraham — APPROVED** [review]
Agreed, let's fix this severe bug and then get localization fixed in a follow-up issue. @thienlnam Can you create an issue that describes the context behind this PR and explains why localization needs to be fixed in `RenderHTML.js`?

**Comment by roryabraham** [comment]
All yours @francoisl

**Review by francoisl — APPROVED** [review]
Works well on my side!

**Comment by thienlnam** [comment]
I chatted with Marc on how to re-add localization to the attachment title and the solution was to move the localization a layer down.  The location where localization was added in `RenderHTML.js` was just making it so that our HTML renderer package wasn't recognizing img html as an image and never went through the img handling (I'm not familiar with the react-native-render-html library so I'm not totally sure why it was doing that, but I know that removing it made it go through the img handling again).  I just went ahead and tagged my other PR https://github.com/Expensify/Expensify.cash/pull/2935 to the original issue as it just adds back Localization

**Pull request merged**
