### PR TITLE
feat: Upgrade VisionCamera to V4

### PR DESCRIPTION
**Pull request by mrousavy**
### Details

As many of you might've noticed, the upgrade to VisionCamera V3 took quite a long time already and eventually still wasn't merged because of a few blockers:

1. It required minSdk 26, or at least 23 with some minor modifications, which wasn't acceptable for Expensify. The reason was that I was using custom `SurfaceTexture` APIs for the video pipeline, and `OutputConfiguration` APIs for the Capture Session that were introduced in SDK 26 or 23 respectively. Adding backwards compatibility here was painful and required a lot of effort.
2. Up until 3.9.0, VisionCamera V3 didn't support flash on Android. This now works well on most devices, but there are a few devices where the vendor didn't implement flash or AE properly according to the Android Camera specification, which would require custom device specific workarounds from my side (`if (manufacturer == "SAMSUNG")` 🙄)
3. Up until 3.9.0, VisionCamera V3 didn't support focus on Android. This now works well on most devices, but there are a few devices where the vendor didn't implement focus metering (AF) properly according to the Android Camera specification, which would require custom device specific workarounds from my side (`if (manufacturer == "SAMSUNG")` 🙄)
4. Up until 3.9.0, VisionCamera V3 had some black-screen issues on some devices because the Camera CaptureSession could be destroyed by the Android OS, and I didn't have a good mechanism of safely restoring it. I did implement quite a good "PersistentCaptureSession" in 3.9.0, so that is theoretically fixed.

A bit of important backstory around V2 vs V3:

**In VisionCamera V2 I used CameraX**, which abstracted most of those quirks away, but back then (a year ago) was still insanely limiting and couldn't support all the features that VisionCamera had.

So **in VisionCamera V3 I switched over to Camera2**, the lower level Camera framework for Android where you have to do everything manually (e.g. capturing a photo requires an AF, AE, AWB precapture sequence, listen to status changes, manually override flash control, and only then you can capture photo metadata), and while that meant MUCH more complexity it also meant much more control and features.

Using Camera2 also gave me a great understanding of how Cameras work under the hood, and I noticed that a lot of vendors (e.g. Samsung) didn't implement the Camera HAL specification properly so I'd have to do a bunch of workarounds to avoid crashes, blackscreens or even full device reboots.
After adding workaround after workaround I decided to look into CameraX again - and to my surprise it actually did quite good over the last year. They added a ton of features, and have a bunch of those device specific quirk workarounds implemented already.

Also, they already have features like deferred surfaces and 10-bit HDR for video capture which I wanted to implement myself (those are really complex, HDR requires loading EGL OpenGL extensions).

So for VisionCamera V4 we're switching over to CameraX again. I kinda see it like this:

- VisionCamera V2 was stable but a bit feature limited
- VisionCamera V3 was a bit unstable at times, but introduced a ton of new features and exciting things
- VisionCamera V4 will be fully stable again, but with all of the features and exciting things from V3

So yea - in short; this PR upgrades to VisionCamera V4 (currently in beta).

I will do a few more breaking changes in VisionCamera V4, but none of them will affect the expensify codebase (they're mostly for the video pipeline)
Also I promise I'll fix it in Expensify if I introduce a breaking change to VisionCamera V4 😄 

### Fixed Issues

$ https://github.com/Expensify/App/issues/28341
PROPOSAL: https://github.com/Expensify/App/issues/28341#issuecomment-1748508986

### Tests

- [x] Open Scan Receipt screen
- [x] Check if Camera works and can take pictures (on iPhones as well as Android phones)
- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by allroundexperts** [comment]
Thanks! I can review when this is ready since I am reviewing the stale v3 PR as well.

**Comment by mrousavy** [comment]
Hold on we found an error on Android - marked this PR as draft, will fix it and ping you once it's ready again!

**Comment by mrousavy** [comment]
Status update: We are still encountering the error where CameraX fails to start. I am talking to Google about this, this might actually be a bug in CameraX. 😓

**Comment by Julesssss** [comment]
Let us know when you want us to generate AdHoc builds for testing

**Comment by mrousavy** [comment]
Heyo! So I think I finally fixed all the bugs now! 🚀 
 Long journey 😅 - sorry for the bunch of commits to this branch here, I had some issues with the prettier setup.

Can we create a test build for this PR now? @Julesssss

**Comment by mountiny** [comment]
@mananjadhav from the C+ thread, please can you test both platforms once the builds are ready

@allroundexperts you can test too if you want

**Review by Julesssss — DISMISSED** [review]
I noticed one small issue on Android that I can't reproduce on prod: 

- Create a non-scan money request to someone  
- Remove camera permissions
- Kill and reopen app
- Tap request money
- Try to scan receipt
- Permission prompt is shown
- Choose 'Just this time'
- **Camera view remains black**
- Close the page, then reopen it
- Camera view works as expected


https://github.com/Expensify/App/assets/10736861/c4f31173-ca78-446f-9f7f-c256fc6fd68e

**Comment by mananjadhav** [comment]
fyi, I have started the testing on iPhone.

**Comment by mrousavy** [comment]
Okay - do we consider this bug blocking?

If yes, I need `adb logcat` logs for this to see what went wrong, can you grab those for me?

**Comment by Julesssss** [comment]
> Okay - do we consider this bug blocking?

It probably shouldn't be, but I would want to make sure this does actually get fixed. I can grab logs, but won't be able to do this until Tuesday earliest.

**Comment by mrousavy** [comment]
Okay - do we want to merge this PR then already, and I'll put that bug on my list? tbh I think this was also happening in V2.

**Comment by Julesssss** [comment]
> Okay - do we want to merge this PR then already, and I'll put that bug on my list? tbh I think this was also happening in V2.

Sure. I'll try to review a test build and get a C+ review done tomorrow. If not it'll be early next week.

**Comment by Julesssss** [comment]
@mrousavy I created a seperate issue [here](https://github.com/Expensify/App/issues/38796), please comment on it so I can assign you. 

Then once the C+ review and pod/lint issues are resolved we can merge and move on.

**Comment by mananjadhav** [comment]
I’ll review once the lint issues are fixed. I’ll test in an hour or something.

**Comment by mrousavy** [comment]
sorry, fixed lint errors!

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Comment by mananjadhav** [comment]
Will test the changes once again and update the screenshots in a few hours.

**Comment by mananjadhav** [comment]
I am having some trouble with my file uploads. I just keep seeing the messages `Uploading desktop-vision-camera.mov…` with no uploads.  I'll try again in a few hours.

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
I've managed to upload the videos by cropping and compressing them, probably low network issues. As I mentioned earlier, the first time black screen still comes up on Android. But we've decided to create a new issue for that.

**Comment by mrousavy** [comment]
Cool! 👍

**Comment by Julesssss** [comment]
Created an issue for the blank camera view [here](https://github.com/Expensify/App/issues/39043). @mrousavy would you mind commenting on the issue so I can assign you? thanks

**Review by Julesssss — DISMISSED** [review]
Created a separate issue for the bug

**Comment by Julesssss** [comment]
@mananjadhav I think we're good to go now?

**Comment by mananjadhav** [comment]
Yes. I think we need to sync the latest main to get rid of the failing performance action ?

**Comment by hannojg** [comment]
Tested with beta 11, works well on all devices we have in the office!

**Comment by mananjadhav** [comment]
@Julesssss All yours.

**Review by Julesssss — APPROVED** [review]
Thanks all

**Comment by Julesssss** [comment]
There was not a failing test 😖

**Comment by johnmlee101** [comment]
I think this introduced a regression here: https://github.com/Expensify/App/issues/39241, basically the sound profile on Android isn't consistent with the settings both in OS and app-level.

**Comment by deetergp** [comment]
I suspect this may have introduced this regression as well https://github.com/Expensify/App/issues/39285. In this version of the app, the Android camera shows a black screen when attempting to SmartScan a receipt.

**Pull request merged**
