### PR TITLE
lastvisibleactioncreated fix for task, iou, expense reports

### PR DESCRIPTION
**Pull request by rojiphil**
@parasharrajat @johnmlee101 

### Details
This PR makes the following changes:
1) Set optimistic value for `lastVisibleActionCreated` in Task Report i.e. `buildOptimisticTaskReport`
2) Set optimistic value for `lastVisibleActionCreated` in IOU Report i.e. `buildOptimisticIOUReport`
3) Set optimistic value for `lastVisibleActionCreated` in Expense Report i.e. `buildOptimisticExpenseReport`

### Fixed Issues
$ https://github.com/Expensify/App/issues/30472
PROPOSAL: https://github.com/Expensify/App/issues/30472#issuecomment-1782914494

### Tests

This is an offline test scenario.

**Note**: Non-archived reports are always displayed below the Pinned/GBR/Draft reports in LHN. Further, archived reports are shown below the non-archived reports.

**Test 1: For Task Report**
1. Go Offline
2. In any chat report, create a task using FAB -> Assign Task
Expected Result: Verify that the LHN shows the created task towards the top of non-archived reports in LHN rather than at the bottom.

**Test 2: For IOU Report**
1. Go Offline
2. Click Global FAB ->Request Money
3.  Click on `Manual` tab, enter amount and click `Next`
4.  Select a new participant with whom there was no chat history before and generate money request
Expected Result: Verify that the LHN shows the IOU report with the new participant towards the top of non-archived reports in LHN rather than at the bottom.

**Test 3: For Expense Report**
**Note**: This test is ONLY applicable to large screen devices. So, smaller screen devices running native and mweb versions are not applicable.
1. Go Offline
2. Go to a workspace report (Precondition: The workspace report should not have any open money request. If it is there, settle it) 
3.  Click FAB -> Request Money -> `Manual` tab -> enter amount -> `Next` -> Generate Money Request 
4. Click on the `Report Preview` in Chat Report to launch the Expense Report.
Expected Result: Verify that the LHN shows the newly created Expense report towards the top of non-archived reports in LHN rather than at the bottom.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as the Steps for Tests Section.

### QA Steps

Same as the Steps for Tests Section.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
        - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/3004659/cea0d6aa-0c5c-4d35-a0c4-791b5d876221

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/3004659/7bdf6671-bb4f-4e5a-920d-108163abb297

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/3004659/ab65b70e-4545-4cd9-b2a3-0435509ce2d2

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/3004659/9fe466b3-4a16-4aee-85f6-7b226210c5c2

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/3004659/195d61c1-4698-4586-87e5-92c609f69fc1

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/3004659/b7f57fd4-52ba-4f0e-a02c-4edf7647c2c7

</details>

### CODE REVIEW

**Comment by rojiphil** [comment]
> I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)

A console error occurs during `Test 3: For Expense Report`. 
The error occurs in native and web versions. 
The attached screens display the error details:
Screenshot 2023-11-06 at 3 33 22 PM
Screenshot 2023-11-06 at 1 39 31 PM

**Comment by rojiphil** [comment]
@parasharrajat
PR Author checklist done. Works well too.
Over to you for review

**Review by parasharrajat — CHANGES_REQUESTED** [review]
Please update unit tests for Sidebar.

**Review by parasharrajat — CHANGES_REQUESTED** [review]
1. Please add QA steps. 
2. > Verify that the LHN shows the created task towards the top of LHN rather than at the bottom.

This is good but we should also mention in QA steps that other higher order will remain above this new item. Such as pinned items, unread reports, etc.

**Comment by rojiphil** [comment]
> 1. Please add QA steps.
> 2. > Verify that the LHN shows the created task towards the top of LHN rather than at the bottom.
> 
> This is good but we should also mention in QA steps that other higher order will remain above this new item. Such as pinned items, unread reports, etc.

I have mentioned this as a note in the `Tests` section. Also, I added a comment for QA steps.

**Comment by rojiphil** [comment]
> Please update unit tests for Sidebar.

@parasharrajat 
Sorry for missing this. The unit tests are updated for Sidebar.
Works well too. 
Kindly review

**Comment by rojiphil** [comment]
@parasharrajat 
Gentle bump for review here

**Comment by rojiphil** [comment]
@parasharrajat 
Can you prioritize the review here, please?

**Comment by rojiphil** [comment]
@parasharrajat 

The branch is, now, merged with the latest main. It works great with an additional observation here.
 
The observation is that the latest main does not show the Expense Report in LHN by default. We need to click on the Report Preview to invoke it explicitly. I'm not sure if this is intentional or is caused by some regression. 
I have added Step 4 to Test 3 Steps for testing the Expense Report to accommodate this change.

Over to you for review.

https://github.com/Expensify/App/assets/3004659/49aea1c0-fca4-4627-b2db-dfce03cae052

**Comment by rojiphil** [comment]
> I am stuck with a build error on Android.

@parasharrajat 
I just tried it on my development environment for Android build. It worked well. 
Looks like something specific in your development environment is causing this.
Is there any way I can help here? 

https://github.com/Expensify/App/assets/3004659/ccf36876-e417-40df-ab56-290e0d22810d

**Comment by rojiphil** [comment]
Maybe you could share a screenshot of the Android build error and we can take it up from there

**Comment by rojiphil** [comment]
> Sure. I face this issue from time to time. Building React-Native from the source throws an error. https://expensify.slack.com/archives/C01GTK53T8Q/p1695826372213339

I saw the slack communication but I could not open the full build log from [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1695826400384639?thread_ts=1695826372.213339&cid=C01GTK53T8Q). So, don’t know what is the latest error there.
Anyway, clearing metro cache didn’t work for you as mentioned in slack? 
When I get a build problem, I usually run `npm run clean` and reboot the system. That solves my problem.

**Review by parasharrajat — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.


:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by rojiphil** [comment]
@johnmlee101 
Gentle bump on review here

**Comment by johnmlee101** [comment]
Why was this force pushed?

**Comment by rojiphil** [comment]
> Why was this force pushed?

I had to force push this because it didn't allow me to merge changes in `reportUtils` here due to migration to typescript. Sorry if there was any other way to do it as I am unaware of it.

**Comment by rojiphil** [comment]
@johnmlee101 
Also, there is typecheck failure. Will fix this and ping you.

**Comment by rojiphil** [comment]
@johnmlee101 
I have fixed the typecheck failures after merging with the latest main.
Also, this works well across all the platforms. I have also attached the latest test videos in the PR Author checklist.
Over to you for the final review.

**Review by johnmlee101 — APPROVED** [review]

**Comment by johnmlee101** [comment]
@parasharrajat would you mind re-reviewing since it was force-pushed, just to be sure what you approved is the same. No need to re-test

**Review by parasharrajat — APPROVED** [review]
LGTM

**Comment by rojiphil** [comment]
@johnmlee101 
Gentle bump for review here

**Review by johnmlee101 — APPROVED** [review]

**Pull request merged**
