### PR TITLE
IOU Contact Preview clickable cursor issue fixed

### PR DESCRIPTION
**Pull request by Santhosh-Sellavel**
### Details
This PR is more specific, I tested everything works well on all platforms.

### Fixed Issues

$ https://github.com/Expensify/App/issues/8034

### Tests
1. Open any group chat, by pressing ➕  icon in the chat composer.
2. Click SplitBill and enter some amount process until the confirmation page.
3. On the confirmation page you should be able to
         - hover on the participant and verify the `selection` pointer is shown
         - check/uncheck participant's selection
4. Click SplitBill and enter some amount process until the confirmation page.
5. On the confirmation page, you should be able to
         - hover on the participant and verify the` disabled cursor` pointer is shown
         - not able to deselect participants
4. Perform Send Money, Request Money from FAB, or any 1:1 chat.  On the confirmation page,
        - hover on the participant and verify the` disabled cursor` pointer is shown
        
- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps
1. Open a group chat not including concierge or chronos.
1. Press ➕ icon in the chat composer.
1. Click Split Bill.
1. Enter an amount and click `Next`
1. Hover over your name or login. Verify that the cursor is disabled and that you can't deselect yourself.
1. Hover over any other participant. Verify that you see a pointer cursor, and that you can select/deselect participants.
1. Close out of the Split Bill modal.
1. Press on the big green ➕ on the home screen.
1. Select `Split Bill`.
1. Enter an amount, then click `Next`.
1. Select multiple participants, then click `Next`.
1. Hover over all of the participants. Verify that all options are disabled and cannot be selected or deselcted.
1. Close out the Split Bill Modal.
1. Open a 1:1 DM with any user other than concierge or chronos.
1. Press ➕ icon in the chat composer.
1. Click request money.
1. Enter an amount and click `Next`
1. Hover over the other participant. Verify that the cursor is disabled and that you can't deselect them.
1. Close out the Request Money modal.
1. Open a 1:1 DM with any user other than concierge or chronos.
1. Press ➕ icon in the chat composer.
1. Click send money.
1. Enter an amount and click `Next`
1. Hover over the other participant. Verify that the cursor is disabled and that you can't deselect them.
1. Close out the send money modal.
1. Press the big green ➕ on the home screen.
1. Select `Request Money`
1. Enter an amount and click `Next`
1. Choose a recipient and click `Next`
1. Hover over the other participant. Verify that the cursor is disabled and that you can't deselect them.
1. Close out the request money modal.
1. Press on the big green ➕ on the home screen.
1. Select `Send money`
1. Enter an amount and click `Next`
1. Choose a recipient and click `Next`
1. Hover over the other participant. Verify that the cursor is disabled and that you can't deselect them.
1. Close out the send money modal.

@Expensify/applauseleads – please update the existing TR regression tests that cover `Split bill`, `Request money`, and `Send money` to include the steps here. i.e:

- "Hover over yourself, verify that the cursor is disabled. Verify that you can't deselect yourself."
- "Hover over the other participants. If you are requesting money from or sending money to a single user, they should be disabled on hover/unselectable. If you are splitting a bill, they should be disabled/unselectable only if you initiated the split bill from an existing group chat."

- [x] Verify that no errors appear in the JS console

### Screenshots 
Added attachments for only desktop & web.

#### Desktop

https://user-images.githubusercontent.com/85645967/165622526-f18e712e-9783-4051-b405-9a65a23178c8.mov

https://user-images.githubusercontent.com/85645967/165622580-a3607133-9bd1-47ad-a550-fc624837a776.mov

https://user-images.githubusercontent.com/85645967/165622589-0a7001be-d054-4f63-be25-44fb357f1db7.mov

https://user-images.githubusercontent.com/85645967/165622593-25e0dc1a-f0c8-413b-afa5-b7e885749650.mov

#### Web

https://user-images.githubusercontent.com/85645967/165622466-13be190e-a068-4314-ba1b-8bb20601c65e.mov

https://user-images.githubusercontent.com/85645967/165622497-d0a42815-ed73-4af1-b99b-5f76c4de2501.mov

https://user-images.githubusercontent.com/85645967/165622503-e9bc34d2-2f9c-413d-9f66-8f5f9cf04d1e.mov

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
Pulled changes from Main.

**Review by roryabraham — APPROVED** [review]
LGTM and tests well 👍

**Review by roryabraham — CHANGES_REQUESTED** [review]
Sorry @Santhosh-Sellavel, I was updating your QA steps to make them more thorough, then I found one edge case that isn't quite right:

1. Open any group chat not including concierge or chronos.
1. Press on the ➕ icon in the message composer.
1. Enter an amount and press `Next`.
1. Hover over your own information. The cursor should appear as disabled (currently is a pointer, even though you can't deselect yourself)💥

**Comment by Santhosh-Sellavel** [comment]
That seems a new case to me, but I am sure it's well within the scope of this issue. I'll try to fix it by Monday or let's open it to contributors thanks!

**Comment by Santhosh-Sellavel** [comment]
Can we add isDisabled in here for sections,

**Comment by Santhosh-Sellavel** [comment]
@roryabraham Here is my solution for the edge case https://github.com/Expensify/App/pull/8760#issuecomment-1122695358. 

Let me know your comments.

**Comment by Santhosh-Sellavel** [comment]
bump @roryabraham

**Comment by Santhosh-Sellavel** [comment]
> Sorry @Santhosh-Sellavel, I was updating your QA steps to make them more thorough, then I found one edge case that isn't quite right:
> 
> 1. Open any group chat not including concierge or chronos.
> 2. Press on the ➕ icon in the message composer.
> 3. Enter an amount and press `Next`.
> 4. Hover over your own information. The cursor should appear as disabled (currently is a pointer, even though you can't deselect yourself)💥

Pushed the changes proposed here https://github.com/Expensify/App/pull/8760#issuecomment-1122695358


https://user-images.githubusercontent.com/85645967/168489192-044fc3ee-7636-45d2-a81f-eee8a959105e.mov

**Review by roryabraham — APPROVED** [review]
Thanks for making that adjustment, @Santhosh-Sellavel

**Pull request merged**
