### PR TITLE
update react-native-svg version

### PR DESCRIPTION
**Pull request by mateusbra**
### Details

Update version of react-native-svg to the latest.
### Fixed Issues

$ https://github.com/Expensify/App/issues/10221

### Tests

- Verify you can `npm install` normally.
- Verify svgs didn't changed and shows normally through all the app:

1. Open the app
2. Click on the + green button
3. Verify SVG Icons renders normally(New chat,New group,Send money,Request money,Split bill)
4. Click on settings button
5. Verify SVG Icons renders normally(Workspaces,Profile,Preferences,Security,Payments,About,Sign Out)
6. Open any chat
7. Click on the + button
8. Verify SVG Icons renders normally(Request money,Send Money,Add attachment)

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

### QA Steps

- Verify svgs didn't changed and shows normally through all the app:

1. Open the app
2. Click on the + green button
3. Verify SVG Icons renders normally(New chat,New group,Send money,Request money,Split bill)
4. Click on settings button
5. Verify SVG Icons renders normally(Workspaces,Profile,Preferences,Security,Payments,About,Sign Out)
6. Open any chat
7. Click on the + button
8. Verify SVG Icons renders normally(Request money,Send Money,Add attachment)

#### Web

WhatsApp Image 2022-08-10 at 15 27 23 (2)
WhatsApp Image 2022-08-10 at 15 27 23 (1)
WhatsApp Image 2022-08-10 at 15 27 23

#### Mobile Web

Android:
mweb-android-3
mweb-android-2
mweb-android-1
Ios:
mweb-ios-3
mweb-ios-2
mweb-ios-1

#### Desktop

desktop-3
desktop-2
desktop-1

#### iOS

WhatsApp Image 2022-08-11 at 21 12 12
WhatsApp Image 2022-08-11 at 21 11 24
WhatsApp Image 2022-08-11 at 21 10 52

#### Android

android-3
android-1
android-2

### CODE REVIEW

**Comment by mateusbra** [comment]
I'm having some issues to run the app on all platforms, so I'll povide the screenshots when I'm able to run it.

**Comment by mateusbra** [comment]
### CHANGELOGS SINCE VERSION 12.1
- Add onLoad method to SvgUri by @WoLewicki and @harveyconnor in https://github.com/react-native-svg/react-native-svg/pull/1817
- fix: remove tsignore in LocalSvg and provide correct types by @WoLewicki and @pratyushok in https://github.com/react-native-svg/react-native-svg/pull/1816
- add missing onLayout prop typings by @WoLewicki and @sinxwal in https://github.com/react-native-svg/react-native-svg/pull/1815
- fix: correctly export rest of the props and add onError to parsing by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1814
- fix style attribute space by @NiuGuohui in https://github.com/react-native-svg/react-native-svg/pull/1639
- fix: types from lib folder by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1813
Change enum declaration in index.d.ts to UnionType by @tainakanchu in https://github.com/react-native-svg/react-native-svg/pull/1800
- Refactor typescript code by @WoLewicki and @codebutler in https://github.com/react-native-svg/react-native-svg/pull/1806
- Fix Stop.tsx error TS2612: Property 'props' will overwrite the base property in 'Component<StopProps, {}, any>' by @DominicTobias in https://github.com/react-native-svg/react-native-svg/pull/1777
update the readme for npm by @moser-jose in https://github.com/react-native-svg/react-native-svg/pull/1523
- Fixed some vocabulary issues in Contributing file by @zidanehammouda in https://github.com/react-native-svg/react-native-svg/pull/1765
- feat: update readmes by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1716
- fix: change ci jobs to main by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1715
- Fix for SvgUri and SvgCssUri crashing on non-existing svg files by @SjaakSchilperoort in https://github.com/react-native-svg/react-native-svg/pull/1503
- Add web example by @zoontek in https://github.com/react-native-svg/react-native-svg/pull/1717
- Fix issue https://github.com/react-native-svg/react-native-svg/issues/1418 by @nitzanbueno in https://github.com/react-native-svg/react-native-svg/pull/1419
- Add support for setting an onError prop on SvgCssUri by @SjaakSchilperoort in https://github.com/react-native-svg/react-native-svg/pull/1718
- duplicate symbol '_distance' with MobileVLCKit by @notjulian in https://github.com/react-native-svg/react-native-svg/pull/1508
- feat: remove extractColor in favor of RN impl by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1726
- Fixed Typo by @sanjeeban5644 in https://github.com/react-native-svg/react-native-svg/pull/1789
- Fix many JS vulns, fix tests by @Stephen2 in https://github.com/react-native-svg/react-native-svg/pull/1775
- Do not include build artifacts in the npm package by @TikiTDO in https://github.com/react-native-svg/react-native-svg/pull/1786
- Add Windows support by @marlenecota in https://github.com/react-native-svg/react-native-svg/pull/1632
- chore: add Example to repo by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1697
- feat: add Example app build workflows by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1698
- fix: android CI by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1699
- Update to css-select to avoid security warnings by @ericanderson in https://github.com/react-native-svg/react-native-svg/pull/1692
- chore: add example with test cases by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1702
- Support PlatformColor by @oblador in https://github.com/react-native-svg/react-native-svg/pull/1561
- fix: PlatformColor crashes on iOS and Android by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1703
- feat: add empty CI job so it runs on PR then by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1705
- feat: add macos CI by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1704
- Updated README.md by @hknakn in https://github.com/react-native-svg/react-native-svg/pull/1690
- Adding mavenCentral() as jcenter() is shutting by @maheshwarimrinal in https://github.com/react-native-svg/react-native-svg/pull/1570
- Fix typo in README by @isnifer in https://github.com/react-native-svg/react-native-svg/pull/1427
- Fixed typo in README.md by @klazbaba in https://github.com/react-native-svg/react-native-svg/pull/1448
- Fix low-quality masks on iOS by @simontreny in https://github.com/react-native-svg/react-native-svg/pull/1658
- feat: move Example to TS by @WoLewicki in https://github.com/react-native-svg/react-native-svg/pull/1712
- fix#1471: every element is focusable on web by @intergalacticspacehighway in https://github.com/react-native-svg/react-native-svg/pull/1585
- Clean up expo instructions by @EvanBacon in https://github.com/react-native-svg/react-native-svg/pull/1381
- Update README.md by @umairx97 in https://github.com/react-native-svg/react-native-svg/pull/1370
- Add macOS support by @amgleitman in https://github.com/react-native-svg/react-native-svg/pull/1494
- Fix clipRule in Android https://github.com/react-native-svg/react-native-svg/issues/1409 by @magicismight in https://github.com/react-native-svg/react-native-svg/pull/1564
- Xcode 12 compatibility fix by @MoOx in https://github.com/react-native-svg/react-native-svg/pull/1604
- Exclude macos files on tvOS by @jhen0409 in https://github.com/react-native-svg/react-native-svg/pull/1584
- Fix README re: Expo usage by @brentvatne in https://github.com/react-native-svg/react-native-svg/pull/1621
- fix(🐛): Expose RN Transform API in types by @wcandillon in https://github.com/react-native-svg/react-native-svg/pull/1627
- Fix ts types by @douglowder in https://github.com/react-native-svg/react-native-svg/pull/1628

**Comment by mateusbra** [comment]
Working on it right now, I'm facing issues running `npm run android` and `npm run ios`. https://expensify.slack.com/archives/C01GTK53T8Q/p1660156287818209 it gives me this error on my macos and also on my windows. Once I'm able to run on both native platforms I'll provide the screenshots.

Also, is this Jest unit test failing because of the upgrade of RN version of the project or I'm I doing something wrong here?

**Comment by mateusbra** [comment]
About this error, I found this [link](https://itsmycode.com/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javascript-heap-out-of-memory/#:~:text=out%20of%20memory.-,How%20to%20fix%20fatal%20error%3A%20ineffective%20mark%2Dcompacts%20near%20heap,memory%20leak%20in%20the%20application) saying it could be the node version, what you think we should do here @parasharrajat ?

**Review by parasharrajat — DISMISSED** [review]
I am getting signature changes on `npm-install`. This has happened to me before but everything is working fine. 

cc: @AndrewGable Could you please run `npm-install` to see if you are getting the same? 

Also, it seems like there are some memory issues with jest tests. 
#### PR Reviewer Checklist
- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/docs/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/docs/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/docs/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/docs/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by AndrewGable** [comment]
FYI - Tests are failing and there are conflicts. But changes look good. I will do a quick review and merge once this is fixed.

**Comment by AndrewGable** [comment]
Hmm ok so we can't merge with failing tests. We are upgrading the node version here: https://github.com/Expensify/App/pull/10439 

So we could hold this PR until that one is merged if you think it will fix it.

**Comment by AndrewGable** [comment]
Bump @mateusbra

**Comment by mateusbra** [comment]
Hey guys, sorry for the delay, I was out for some days,I'll focus on this one in order to be merged ASAP...
While this PR was open a new version of react-native-svg was released.
 Do you think we should update it to the newer version(v13.1.0)? or should we keep the version we currently were testing(v12.4.3)?

**Comment by mateusbra** [comment]
There aren't any breaking change. I will test on all platforms and if it works fine I'll use this new version(v13.1.0)

**Comment by mateusbra** [comment]
It worked fine on my tests.
Also, the upgrading node/npm version PR solved the runtime memory issue on jest tests.

**Review by parasharrajat — APPROVED** [review]
LGTM. Please complete the checklist.
cc: @AndrewGable

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
