### PR TITLE
fix: input styles

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

https://github.com/Expensify/App/issues/5462#issuecomment-927869687

### Fixed Issues

$ https://github.com/Expensify/App/issues/5462

### Tests | QA Steps

Open NewDot on all the below-listed platforms one by one and follow the following procedure.
1. Open Profile Page.
2. Check the Input for FirstName and LastName is proper as per the issue description.
3. Check the Pronoun Dropdown is proper.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

image

#### Android

Screenshot 2021-10-09 20:23:03

### CODE REVIEW

**Review by pecanoro — APPROVED** [review]

**Comment by parasharrajat** [comment]
@shawnborton How about this?

**Comment by shawnborton** [comment]
I think that looks good, but to make sure, can you update the text input and the select menu to have the same exact labels and values? This will make it very easy to compare (by putting them on top of each other)

**Comment by parasharrajat** [comment]
@shawnborton Does this work?
image

**Comment by aldo-expensify** [comment]
The missing outline for `ExpensiPicker` seems to be related to this change:

https://github.com/Expensify/App/pull/5742/files#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253ebL542-R551

**Comment by parasharrajat** [comment]
This PR was never supposed to merge at this time. But I will submit another asap.

**Comment by parasharrajat** [comment]
Created a PR to fix the Border issue and other input issues. https://github.com/Expensify/App/pull/5805
cc: @marcaaron @aldo-expensify

**Pull request merged**
