### PR TITLE
Get&returnValueList=reportSummaryList

### PR DESCRIPTION
**Pull request by marcaaron**
### Details

Replaces `Get&returnValueList=reportStuff` with `reportSummaryList`.

This cuts initial fetching and re-fetching of reports from ~ 7 seconds to 1.5 seconds on a test account with many large chats and should speed things up for users.

### Fixed Issues
$ https://github.com/Expensify/Expensify.cash/issues/3875

### Tests
**Note: Pull Auth main branch and re-build before testing!**

1. Create an account with several hundred reports each having 1000+ comments (clitools can help with this)
2. Sign in and verify that you are able to do so and the LHN populates in a reasonable amount of time less than a couple of seconds and not 5-7 seconds. 
3. We are looking for the response time of the command `Get&returnValueList=reportSummaryList` which can be analyzed in the network tab

### QA Steps
For QA we'll do the same steps but ask @JmillsExpensify or someone with a large number of chats to test this out for us on staging.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
This is still on HOLD but I'm moving it into reviews

**Review by Jag96 — CHANGES_REQUESTED** [review]
Ok, after some back and forth w/ testing it looks like if the user has a pinned chat, the `getReportSummaryList` command fails in auth

Logs for user without any pinned chats (tested by navigating to https://www.expensify.com/api?command=Get&returnValueList=reportSummaryList&reportIDList=MY_REPORT_ID): [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2266e65e0b19d1fda5-LAX%22)+AND+timestamp:[2021-07-13T22:42:21.977Z+TO+2021-07-14T00:42:21.977Z]&index=logs_expensify-011518)

Logs for user with pinned chats (same URL, just pinned a chat and refreshed): [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2266e65e5f8addfda5-LAX%22)+AND+timestamp:[2021-07-13T22:42:35.490Z+TO+2021-07-14T00:42:35.490Z]&index=logs_expensify-011518)

**Review by Jag96 — APPROVED** [review]
With the latest changes in https://github.com/Expensify/Auth/pull/5769 this is working great for me!

**Comment by marcaaron** [comment]
Looks like the auth change has been deployed so I'm going to merge this guy 🤞

**Comment by isagoico** [comment]
@marcaaron @JmillsExpensify Hello! let us know when this is tested so we can check it off the list 🙇

**Comment by marcaaron** [comment]
I think we probably want to make this a blocker and wait until https://github.com/Expensify/Auth/pull/5780 has been deployed. Right, @Jag96 ?

**Comment by marcaaron** [comment]
nvm left more context on the checklist we can check this one off I think..

**Pull request merged**
