### PR TITLE
Fix inconsistent margins for reacted emojis to different sort of comments

### PR DESCRIPTION
**Pull request by rezkiy37**
### Fixed Issues

$ https://github.com/Expensify/App/issues/18681
PROPOSAL: https://github.com/Expensify/App/issues/18681#issuecomment-1607593518

### Tests

- [x] Verify that no errors appear in the JS console

1. Open the "Expensify" app on any device or platform
2. Open/create any chat 
3. Create any type of messages like test, code-blocks, quote, attachment, etc.
4. Add emojis 
5. Verify that spacings are the same between all messages and emojis

### Offline tests

Same as tests

### QA Steps

- [x] Verify that no errors appear in the JS console

Same as tests

1. Open the "Expensify" app on any device or platform
2. Open/create any chat 
3. Create any type of messages like test, code-blocks, quote, attachment, etc.
4. Add emojis 
5. Verify that spacings are the same between all messages and emojis

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

IMG_7105
IMG_7106
IMG_7107
IMG_7108

</details>

<details>
<summary>Mobile Web - Safari</summary>

IMG_7101
IMG_7102
IMG_7103
IMG_7104

</details>

<details>
<summary>Desktop</summary>

Screenshot 2023-07-02 at 13 26 08
Screenshot 2023-07-02 at 13 26 14

</details>

<details>
<summary>iOS</summary>

ios 1
ios 2
ios 3

</details>

<details>
<summary>Android</summary>

android 1
android 2
android 3

</details>

### CODE REVIEW

**Review by venture1981 — COMMENTED** [review]
@rezkiy37 
this change works on your side? possible to add video or screenshot?

**Comment by rezkiy37** [comment]
> @rezkiy37
> this change works on your side? possible to add video or screenshot?

It is still a draft PR. Once it is ready, I will open it for review 🙂

**Comment by rezkiy37** [comment]
@abdulrahuman5196 Just a friendly reminder that the PR is ready for review 🙂

**Comment by abdulrahuman5196** [comment]
Sorry for the delay @rezkiy37 Will close the review before tomorrow morning.

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>



</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by abdulrahuman5196** [comment]
NAB: @rezkiy37 Kindly mark Offline tests and QA tests as "Same as tests". This should also work offline.

**Comment by rezkiy37** [comment]
> NAB: @rezkiy37 Kindly mark Offline tests and QA tests as "Same as tests". Offline tests also should be present for this change since its expected to work offline

Done.

**Comment by rezkiy37** [comment]
@abdulrahuman5196 Just a friendly reminder 🙂

**Comment by abdulrahuman5196** [comment]
Working on this now

**Comment by abdulrahuman5196** [comment]
@rezkiy37 When we hover the message, the hover doesn't have any space top or bottom as its like attached to the message which is odd.


https://github.com/Expensify/App/assets/46707890/c5832da8-0343-4cec-abac-0af3db123647

**Comment by rezkiy37** [comment]
> @rezkiy37 When we hover the message, the hover doesn't have any space top or bottom as its like attached to the message which is odd.
> 
>  Screen.Recording.2023-07-13.at.3.03.07.PM.mov

Yes, it works this way, because the messages are separated by a separator component of FlatList, not via paddings.

**Comment by abdulrahuman5196** [comment]
@rezkiy37 I think hover should have padding as per the current working behaviour, it odd with padding for hover.


@conorpendergrast Could you kindly assign an UX person to confirm on the same? https://github.com/Expensify/App/pull/22010#issuecomment-1633900776

**Comment by rezkiy37** [comment]
> @rezkiy37 I think hover should have padding as per the current working behaviour, it odd with padding for hover.
> 
> @conorpendergrast Could you kindly tag an UX person to confirm on the same? [#22010 (comment)](https://github.com/Expensify/App/pull/22010#issuecomment-1633900776)

@abdulrahuman5196, I misunderstood. "_hover should have padding_" and "_it odd with padding for hover_". Does not it contradict?

**Comment by abdulrahuman5196** [comment]
@rezkiy37 Sorry. It was a typo, updated the comment - https://github.com/Expensify/App/pull/22010#issuecomment-1634639160

I am aligned to have some amount of padding top and bottom on hover similar to current behaviour.

Screenshot 2023-07-13 at 11 13 45 PM

**Comment by rezkiy37** [comment]
> @rezkiy37 Sorry. It was a typo, updated the comment - [#22010 (comment)](https://github.com/Expensify/App/pull/22010#issuecomment-1634639160)
> 
> I am aligned to have some amount of padding top and bottom on hover similar to current behaviour.
> 
> Screenshot 2023-07-13 at 11 13 45 PM

Well, let me add them and tweak the separator.

**Comment by abdulrahuman5196** [comment]
Thank you @rezkiy37

**Comment by rezkiy37** [comment]
@abdulrahuman5196, just to clarify the next steps:

1. Sounds like this implementation won't be merged. 
2. I am going to propose an alternative solution from the [proposal](https://github.com/Expensify/App/issues/18681#issuecomment-1607593518).
3. Should I create a new PR and close this one?

**Comment by abdulrahuman5196** [comment]
>Sounds like this implementation won't be merged.

@rezkiy37 Why would this be? Is it not possible to tweek the separator and message hover size?

Any blockers there?

**Comment by abdulrahuman5196** [comment]
I was expected to fix the hover issue alone, otherwise the implementation here seems fine AFAIK.

**Comment by rezkiy37** [comment]
@abdulrahuman5196, I've tried to add vertical paddings and minimise the separator. Basically, the distance between messages should be `8px`. The optimal solution is: `paddings = 2px`, `separator = 4px`. Visually, almost no difference between `0px` and `2px` for the hover effect. 
Also, the idea was to remove paddings. I just do not see benefits of the separator anymore. I should back paddings for messages and the separator looks like an overhead here.

**Comment by rezkiy37** [comment]
I could add pseudo-elements: ::before` and `::after`. This a way how to make hover area a little bit bigger.

**Comment by abdulrahuman5196** [comment]
@rezkiy37 

>Also, the idea was to remove paddings. I just do not see benefits of the separator anymore. I should back paddings for messages and the separator looks like an overhead here.

I agree. But why do we need a alternate proposal is something I am not sure here?. I assume we can modify this PR changes and do iteration on this.

**Comment by abdulrahuman5196** [comment]
Why do we need a different approach is my question?

**Comment by rezkiy37** [comment]
> @rezkiy37
> 
> > Also, the idea was to remove paddings. I just do not see benefits of the separator anymore. I should back paddings for messages and the separator looks like an overhead here.
> 
> I agree. But why do we need a alternate proposal is something I am not sure here?. I assume we can modify this PR changes and do iteration on this.

> Why do we need a different approach is my question?

@abdulrahuman5196, I will modify this PR. Let me apply changes and we will do one more iteration on this 🙂

**Comment by rezkiy37** [comment]
@abdulrahuman5196, I've applied the second solution. These changes align spacing between code blocks. It prevents extra bottom margins there.

<details><summary>Example</summary>
<p>

Screenshot 2023-07-17 at 14 56 25

</p>
</details>

**Comment by rezkiy37** [comment]
@abdulrahuman5196 Just a friendly reminder to take a look at the PR 🙂

**Comment by abdulrahuman5196** [comment]
Hi, Will do a another round of review today.

**Comment by abdulrahuman5196** [comment]
@rezkiy37 This was the same proposal as of here https://github.com/Expensify/App/issues/18681#issuecomment-1541555678, which we had previously considered not upto the point of solving this issue.

Where we unable to do hover fix alone on top of your previous solutions?

**Comment by abdulrahuman5196** [comment]
@rezkiy37 ping on the above

**Comment by rezkiy37** [comment]
Will check it tomorrow (on Monday).

**Comment by rezkiy37** [comment]
> @rezkiy37 This was the same proposal as of here [#18681 (comment)](https://github.com/Expensify/App/issues/18681#issuecomment-1541555678), which we had previously considered not upto the point of solving this issue.
> 
> Where we unable to do hover fix alone on top of your previous solutions?

@abdulrahuman5196, the previous proposal is similar, but not the same. AFAIK, that proposal was rejected, because it builds a dependency between messages. Basically, my alternative solution keeps messages independent.

By the way, we need the hover effect only on web and desktop. It is possible to do via CSS pseudo elements `::before` and `::after`. Let me try to play with it.

**Comment by rezkiy37** [comment]
@abdulrahuman5196, I've tried a few variants. The best one is to render 2 absolute views above and below messages. Visually, it creates a hover effect that the app has now. Also, I back initial changes.
Commit - https://github.com/Expensify/App/pull/22010/commits/37053c528cc09a9b2e1e4ee8d5ece75159fe13ad

**Comment by Beamanator** [comment]
Looks like there's conflicts

**Comment by rezkiy37** [comment]
> Looks like there's conflicts

@Beamanator, done!

**Comment by Beamanator** [comment]
Thanks @rezkiy37 - @abdulrahuman5196 can you finish your review this week please?

**Comment by rezkiy37** [comment]
I added one more [commit](https://github.com/Expensify/App/pull/22010/commits/be66de8d175546760d4f63269e091c344d0b414a), because reactions started to have top margin even when no reactions to show.

**Comment by abdulrahuman5196** [comment]
@Beamanator yes. We where actually switching the implementation midway due to hover issue. I assume its fixed now and will run a another review.

**Comment by abdulrahuman5196** [comment]
@rezkiy37 Currently whisper messages have default hover background. So the current implementation is not working smoothly with the same. 

https://github.com/Expensify/App/assets/46707890/8bee83b9-6e2c-467f-aa09-1e6c59ac2683

**Comment by rezkiy37** [comment]
> @rezkiy37 Currently whisper messages have default hover background. So the current implementation is not working smoothly with the same. I think we can only make this work without a chat separator. Correct me if wrong.
> 
>  Screen.Recording.2023-07-28.at.8.36.55.PM.mov

Looks like I forgot to remove paddings of the whisper messages. Let me try to play with it.

**Comment by rezkiy37** [comment]
@abdulrahuman5196, I figured out what happened with whisper messages. So, this kind of messages always have a "hover" effect. Actually, we just should not apply new hover logic for these messages. Also, I tweaked paddings and added bottom one. 
Commit - https://github.com/Expensify/App/pull/22010/commits/f6f4dad527432d7a5021c0fc2aaacc832826a507

<details><summary>Example</summary>
<p>

https://github.com/Expensify/App/assets/57314631/f2dc4d0e-ef7f-4f74-8809-e433fb398a0f

</p>
</details>

**Comment by rezkiy37** [comment]
@abdulrahuman5196, just a friendly reminder 🙂

**Comment by abdulrahuman5196** [comment]
Will do a another review today

**Comment by abdulrahuman5196** [comment]
@rezkiy37 Still the issue is not fixed with whisper messages. We are seeing black spaces when there are multiple whispers and hover is not matching. 

In PR

https://github.com/Expensify/App/assets/46707890/8da475a2-080c-4344-a90e-b25f49d935bc


In staging


https://github.com/Expensify/App/assets/46707890/8a738572-8c14-410c-8c6a-a4bdfd0915ed

**Comment by rezkiy37** [comment]
> @rezkiy37 Still the issue is not fixed with whisper messages. We are seeing black spaces when there are multiple whispers and hover is not matching.
> 
> In PR
> 
>  Screen.Recording.2023-08-02.at.3.06.44.PM.mov 
> 
> In staging
> 
>  Screen.Recording.2023-08-02.at.3.07.09.PM.mov

Yeah, I see. I am going to try "_By default, highlighted and leadingItem props are provided_" - https://reactnative.dev/docs/flatlist#itemseparatorcomponent.

**Comment by rezkiy37** [comment]
@abdulrahuman5196, could you say me how to invoke these messages from Concierge?

**Comment by abdulrahuman5196** [comment]
@rezkiy37  
1) account A send message to account B
2) from B Hover the message and click on flag icon
3) choose assault or harassment and the message will be flagged and hidden.

**Comment by rezkiy37** [comment]
@abdulrahuman5196, I found a way how to fix the hover effect with whisper messages. The idea is to highlight separator between the whisper messages. Also, on hover near messages, the app expands this area to avoid gaps between a message and whisper message. 
Commit - https://github.com/Expensify/App/pull/22010/commits/891ea18b227ef8ba16abf2f1869b2c8b4c09dff1

<details><summary>Example</summary>
<p>

https://github.com/Expensify/App/assets/57314631/ecefae8d-5627-46c9-b99f-581911407eb2

</p>
</details> 

Also, I fixed a spacing between parent action and other messages. However, there is a small difference on hover. Please let me know does this new effect look good? 
Because, to have the same effect, it requires a lot of changes that sounds to me like a overhead. I can expand the bottom hover area of the top message easily, but to expand the top hover area for the second message looks like too complex. 
So, I decided to keep them consistent without extra area. WDYT?

Commit - https://github.com/Expensify/App/pull/22010/commits/8fff5c6466498e8b1c0b63f49c1e26db958f6f6e

<details><summary>Example</summary>
<p>

https://github.com/Expensify/App/assets/57314631/bfeab195-6c86-4235-a003-02b0cdd1b8ce

</p>
</details>

**Comment by abdulrahuman5196** [comment]
Thanks for the update. Will re-review in my morning

**Comment by rezkiy37** [comment]
Just fixed git conflicts. Needs to be re-rested.

**Comment by rezkiy37** [comment]
Looks like everything works fine.

**Comment by abdulrahuman5196** [comment]
@rezkiy37 I am still seeing issue with whipser messages 
Screenshot 2023-08-06 at 4 58 40 PM



And moreover I am not sure on understanding what we are doing as a fix for whisper messages. Could you explain what are we trying to do specifically for whispers alone.

**Comment by rezkiy37** [comment]
> @rezkiy37 I am still seeing issue with whipser messages Screenshot 2023-08-06 at 4 58 40 PM
> 
> And moreover I am not sure on understanding what we are doing as a fix for whisper messages. Could you explain what are we trying to do specifically for whispers alone.

@abdulrahuman5196, updates:

My bad, it is one more case. I added a logic to understand what the previous action is whisper. It fixed a case when the current message is a whisper and the previous one as well, but they are not in one group.
Commit - https://github.com/Expensify/App/pull/22010/commits/51adacef71e0c240d3c3c4fbe2927fde82f643ed.

<details><summary>Example</summary>
<p>

https://github.com/Expensify/App/assets/57314631/4ed9a87a-47f3-4239-af17-42e257aede1d

</p>
</details> 

> Could you explain what are we trying to do specifically for whispers alone.

Yes, sure. The app highlights separators between whisper actions when they are in a group. It creates this solid effect. 
Also, on hover other messages near a whisper, the app should create the solid effect. It powered by extending the hover area from `4px` (_half of separator_) to `8px` (_entire separator_).

**Comment by abdulrahuman5196** [comment]
@rezkiy37 Still I am seeing issues with hover on whisper

Current issues
1) Hover on whisper is not perfect.
2) And we have a no hover point between messages where both above and below messages are not highlighted. This is not the behaviour in the main, atleast one of the messages will be highlighted at any time


https://github.com/Expensify/App/assets/46707890/34ee39cb-f68a-42ed-83d6-a55b3482d40b



@Beamanator We have been trying so much to fix the hover issue, but even after multiple iterations we are still unable to perfect the solution. Should we try for a different approach to solve the issue? Or any advice on path forward?

**Comment by abdulrahuman5196** [comment]
@Beamanator Waiting on your comments here?

**Comment by abdulrahuman5196** [comment]
@Beamanator Reference https://github.com/Expensify/App/pull/22010#issuecomment-1676405762

**Comment by Beamanator** [comment]
Sorry for the delay gents, it's been quite a busy few weeks prepping for some conferences - I will try to get back to y'all today 🙏

**Comment by Beamanator** [comment]
Hmm I can see how these types of changes (to Report action components) can run the risk of regressions since there's lots of complicated logic all over the place - I think it definitely would make sense for @rezkiy37 to take a bit of time, step back and reevaluate if there's another solution. I don't currently have time to look into what exactly would be the best way forward for this, but that's why we hire others for that work :D

One strategy I'm thinking could work well:
1. Reevaluate what exactly the problem is that we're trying to solve in the issue
    - Did we add anything to the scope after trying things in this PR?
2. Re-agree on what the solution should _look like_ (with the design team's 👀 )
3. Determine if we can break this up into multiple pieces (so far this PR isn't huge, but it seems like we can't get everything to work at once, so what if we try to just fix 1 thing at a time?)
4. Get back to coding

Thoughts?

**Comment by rezkiy37** [comment]
> Hmm I can see how these types of changes (to Report action components) can run the risk of regressions since there's lots of complicated logic all over the place - I think it definitely would make sense for @rezkiy37 to take a bit of time, step back and reevaluate if there's another solution. I don't currently have time to look into what exactly would be the best way forward for this, but that's why we hire others for that work :D
> 
> One strategy I'm thinking could work well:
> 
> 1. Reevaluate what exactly the problem is that we're trying to solve in the issue
>    
>    * Did we add anything to the scope after trying things in this PR?
> 2. Re-agree on what the solution should _look like_ (with the design team's 👀 )
> 3. Determine if we can break this up into multiple pieces (so far this PR isn't huge, but it seems like we can't get everything to work at once, so what if we try to just fix 1 thing at a time?)
> 4. Get back to coding
> 
> Thoughts?

Makes sense. I believe we should do these steps. Also, I will ask some help of my Callstack teammates.

**Comment by abdulrahuman5196** [comment]
@rezkiy37 Sorry I missed this one. I will check on the alternative solution and update sooner

**Comment by teneeto** [comment]
> @rezkiy37 Sorry I missed this one. I will check on the alternative solution and update sooner

Great work guys! 

@abdulrahuman5196 I've followed the conversation up until this point and before I look into any further proposals into this, I would also like to see how @rezkiy37 most recent proposal plays out. Perhaps I could come in at this point to see how I can assist. would also be waiting on your thoughts...

**Comment by abdulrahuman5196** [comment]
@rezkiy37 I tried this https://github.com/Expensify/App/pull/22010#issuecomment-1701303078

But for me it seems like, there isn't visible UI changes happening. I am sure if I am missing something. If possible could you kindly provide screenshots of what is previous and new change in UI?

**Comment by rezkiy37** [comment]
> @rezkiy37 I tried this [#22010 (comment)](https://github.com/Expensify/App/pull/22010#issuecomment-1701303078)
> 
> But for me it seems like, there isn't visible UI changes happening. I am sure if I am missing something. If possible could you kindly provide screenshots of what is previous and new change in UI?

Let me please provide more info here.

**Comment by rezkiy37** [comment]
> @rezkiy37 I tried this [#22010 (comment)](https://github.com/Expensify/App/pull/22010#issuecomment-1701303078)
> 
> But for me it seems like, there isn't visible UI changes happening. I am sure if I am missing something. If possible could you kindly provide screenshots of what is previous and new change in UI?

Initially, our goal here to align spacing between a message and reactions for different type of messages. Actually, there is a component with an inconsistency - **BasePreRenderer**. It happens, because it applies an additional bottom margin.
 
So, I am no the latest `main` applied `styles.mt2` (_top margin_) instead of `styles.mv2` (_vertical margins_) to `ScrollView` of **BasePreRenderer**. Result:

1. We can see that spacing between messages and their reactions are the same, even for a multi-line. There are red arrows that demonstrate a difference. 



2. We can see that spacing between messages are the same, even for a multi-line and a bare text. There are red arrows and squares, that demonstrate a difference.



3. I remember a concern - https://github.com/Expensify/App/pull/22010#issuecomment-1655890390 - about spacing between a multi-line message and text. So, prepared 2 examples where I posted the first one without an empty line between, the second one with an empty line. Even for the first case it has a minimal space. I think it is expected when you create a message it line by line. For the second example, I added an empty line explicitly. Therefore, I have a bigger space.

Screenshot 2023-09-27 at 11 35 39

cc @abdulrahuman5196 @teneeto

**Comment by abdulrahuman5196** [comment]
Thank you for the clear explanation @rezkiy37 here https://github.com/Expensify/App/pull/22010#issuecomment-1737064888

This was the alternate solution proposed during the proposal review. We have already tried other better solutions but unfortunately, due to other issues we weren't able to proceed on the same.

IMO, I think at this state this alternate is a good enough fix given the main solution(better solution) has multiple side effects preventing its implementation. 

🎀 👀 🎀
C+ Reviewed

cc: @Beamanator

**Comment by rezkiy37** [comment]
> Thank you for the clear explanation @rezkiy37 here [#22010 (comment)](https://github.com/Expensify/App/pull/22010#issuecomment-1737064888)
> 
> This was the alternate solution proposed during the proposal review. We have already tried other better solutions but unfortunately, due to other issues we weren't able to proceed on the same.
> 
> IMO, I think at this state this alternate is a good enough fix given the main solution(better solution) has multiple side effects preventing its implementation.
> 
> 🎀 👀 🎀 C+ Reviewed
> 
> cc: @Beamanator

Cool, thank you! 
I will prepare another PR, this one we will close.

**Comment by Beamanator** [comment]
Thanks @abdulrahuman5196 and @rezkiy37  for the continued effort here, looking forward to the next PR 👍

**Pull request closed without merging**
