### PR TITLE
Add Paypal option removed if Paypal already exists

### PR DESCRIPTION
**Pull request by Santhosh-Sellavel**
### Details
If the Paypal option has already been added by the user, will not show add PayPal option now.

### Fixed Issues

$ https://github.com/Expensify/App/issues/5418

### Tests & QA Steps
1. Go to Settings -> Payments
2. If PayPal username is not added already, add now.
3. Now Payments page, click `Add Payment Method` option
4. Should not see `Paypal.Me` in options.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screenshot 2021-10-28 at 12 24 23 AM

#### Mobile Web
Simulator Screen Shot - iPhone 12 - 2021-10-28 at 00 11 13

#### Desktop
Screenshot 2021-10-28 at 12 24 00 AM

#### iOS
Simulator Screen Shot - iPhone 12 - 2021-10-28 at 00 08 44

#### Android
Screenshot_1635360083

### CODE REVIEW

**Review by parasharrajat — DISMISSED** [review]

**Review by stitesExpensify — APPROVED** [review]
LGTM!

**Comment by nazam100** [comment]
Accessibility Issue: The element announced without button role. This is similar to issue #5446 
Failed WCAG: 4.1.2
Actual Result: The element is announced without a name and role of the button.
Expected Result: Since this is an interactive element, it should be announced with a name and role of the button.

Attachment:

https://user-images.githubusercontent.com/66008453/139482614-ce0c7890-76e8-487c-b9c5-d19fdd76aba8.mp4

**Comment by nazam100** [comment]
Accessibility Issue: Grey icons against white background fail contrast requirements. This issue is similar to #5506  
Failed WCAG: 1.4.11
Actual Result: The grey icons (#C6C9CA) on white background (#FFFFFF) have a color contrast ratio of 1.66:1.
Expected Result: The visual presentation of meaningful graphical objects or interactive components should have a contrast ratio of at least 3.00:1 with the surrounding background color.

Attachments:

Capture

**Comment by nazam100** [comment]
Accessibility Issue: Grey text against white background fail contrast requirements. This issue is similar to #5503
Failed WCAG: 1.4.3
Actual Result: The grey text (#AOABAE) on white background (#FFFFFF) have a color contrast ratio of 2.4:1.
Expected Result: The contrast ratio of the text against the background should be at least 4.50:1 for small text and 3.00:1 for large text (14pt bold or 18 pt+).

Attachment:

Capture

**Pull request merged**
