### PR TITLE
Adjust Padding styles to make the selected account full-Width

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7913

### Tests
1. Open the transfer account page. 
2. hover over the selected account to see that it expands to full width. 
3. Hold Press the selected account to see that design.

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I made sure to pull `main` before submitting my PR for review
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I clearly indicated the environment tests should be run in (Staging vs Production)
- [ ] I wrote testing steps that cover success & fail scenarios (if applicable)
- [x] I ran the tests & they passed on **all platforms**
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified there are no console errors related to changes in this PR
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I added comments when the code was not self explanatory
    - [ ] I put all copy / text shown in the product in all `src/languages/*` files (if applicable)
    - [ ] I followed proper naming convention for platform-specific files (if applicable)
    - [x] I followed style guidelines (in [`Styling.md`](https://github.com/Expensify/App/blob/main/STYLING.md)) for all style edits I made
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

#### PR Reviewer Checklist
- [ ] I verified the Author pulled `main` before submitting the PR
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the testing environment is mentioned in the test steps
- [ ] I verified testing steps cover success & fail scenarios (if applicable)
- [ ] I verified tests pass on **all platforms** & I tested again on all platforms
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified there are no console errors related to changes in this PR
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified comments were added when the code was not self explanatory
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files (if applicable)
    - [ ] I verified proper naming convention for platform-specific files was followed (if applicable)
    - [ ] I verified [style guidelines](https://github.com/Expensify/App/blob/main/STYLING.md) were followed
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)

### QA Steps
2. Make sure you have completed your KYC for transferring the balance.
1. Open the transfer balance page from Settings/ Payments/ Transfer Balance on all platforms.
2. Hover over the selected account (Which account) to see that it expands to full width. 
3. Hold Press the selected account to see that the highlight background color is expanding full width.

- [ ] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

image

#### Mobile Web

image

#### iOS

image

#### Android

image

### CODE REVIEW

**Review by Luke9389 — APPROVED** [review]

**Comment by mvtglobally** [comment]
@Luke9389  QA team will not be able to validate this page. Can you check it internally

**Comment by Luke9389** [comment]
Yup, checking now. 

Out of curiosity, why can't QA check this? Isn't QA added to all betas?

**Comment by mvtglobally** [comment]
@Luke9389 , 
We would love to be added to this, but due to KYC wall for Transfer Balance we are not able to setup any wallet for QA. And if Balance is $0, Transfer Balance link does not display at all after recent changes 

If you have any suggestions how to enable it for QA to test, pls add to this ticket https://github.com/Expensify/Expensify/issues/195344

**Comment by Luke9389** [comment]
I’m not seeing the Transfer Balance page on my expensifail or my real account on staging.

@parasharrajat would you be willing to explain how I can verify that my KYC is done?

**Comment by Luke9389** [comment]
QA passed.
Screen Shot 2022-03-14 at 2 00 27 PM

**Pull request merged**
