### PR TITLE
Use push to page for report settings

### PR DESCRIPTION
**Pull request by Gonals**
### Details

Here we are refactoring the report settings page to use "push to page". So instead of entering the room name directly on the report settings page, there is a menu item for the report name. When you click it you are navigated to a separate page for entering the room name. When you save it you are navigated back. I implemented the same thing for the room notification preference selection, using the same pattern as on the LanguagePage. Push to page is our preferred pattern for inputs now. 

I used functional components for the new pages, but left existing pages as class components since they should be refactored separately. The ReportSettings page is mostly unchanged, but it moved, so it will be easier to look at the diff between the new file path and the file on main.

### Fixed Issues

$ https://github.com/Expensify/App/issues/16768

### Tests
**Rename a room**
1. Create a workspace if needed
2. Create a workspace room if needed
3. Open a Room chat
4. Click on the Header
5. Go to Settings
6. Click on the room name
7. Clear the room name
8. Click save
9. Verify that you see an error on the room name input saying "Please enter a room name"
10. Enter a new room name with a capital letter
11. Verify that you see an error on the room name input saying "Room names can only include lowercase letters, numbers and hyphens"
12. Enter a valid new room name
13. Click save
14. Confirm the name has been changed and you are navigated back to the previous page

**Update room notification preference**
1. Create a workspace if needed
2. Create a workspace room if needed
3. Open a Room chat
4. Click on the Header
5. Go to Settings
6. Click on the notification preference
7. Select a different notification preference
8. Confirm that you are navigated back to the previous page and the notification preference has been updated

- [x] Verify that no errors appear in the JS console

### Offline tests
**Rename a room offline**
1. Create a workspace if needed
2. Create a workspace room if needed
3. Go offline
4. Open a Room chat
5. Click on the Header
6. Go to Settings
7. Click on the room name
1. Enter a valid new room name
1. Click save
1. Confirm the name has been changed and you are navigated back to the previous page, and the room name is grayed out
2. Go back online
3. Verify that the room name is no longer grayed out

### QA Steps
Same as tests

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.
### Screenshots/Videos
I only tested on Web since the changes are platform independent.
<details>
<summary>Web</summary>

**Rename a room**

https://user-images.githubusercontent.com/26260477/235523933-6f70f3c1-4a52-4b59-a0ba-13f4ad13d4b7.mov

**Update room notification preference**

https://user-images.githubusercontent.com/26260477/235523958-16d72a17-7aab-490d-9656-4729d1b0df9b.mov

**Rename a room offline**

https://user-images.githubusercontent.com/26260477/235523976-d3f7f727-f4ac-4f3c-8761-58bbc7f9eee1.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by Gonals** [comment]
Removing C+, as it is a very simple fix

**Review by neil-marcellini — DISMISSED** [review]
It looks like the recommendation in the [Slack conversation](https://expensify.slack.com/archives/C049HHMV9SM/p1678551138542469) was to convert this to Push to page. I think we should do that.

**Review by neil-marcellini — COMMENTED** [review]
Hmm I'm changing my mind. I think since we already "pushed" to the settings page, if we make the "Save" button navigate back then it's effectively using push to page. It would be odd to have each settings field on its own page. For example with https://staging.new.expensify.com/settings/profile/display-name the first and last name can be updated on the same page. What do you think @shawnborton?

The changes work well for updating the room name, but let's make it navigate back when you hit the "Save" button so that it works for the notification preference.

https://user-images.githubusercontent.com/26260477/229848064-46979b06-9789-42b4-b3bf-eb239dc01906.mov

**Comment by shawnborton** [comment]
I think we decided that we want both the room name and the notification frequency to be push-to-page inputs. When you tap on room name, you get pushed to a new page where you are auto-focused. Saving this new page then returns back to the overview page. 

Cc @JmillsExpensify @trjExpensify

**Comment by Gonals** [comment]
Gotcha! Refactoring this, then! WIP for now

**Comment by neil-marcellini** [comment]
Ok sounds good. It might be cool to have an illustration, animation, or branding on the "pushed" pages because they feel really empty to me.

**Comment by Gonals** [comment]
Hey @neil-marcellini! I'm going on parental leave! If you are interested, feel free to take over this one. Most of the migration is done (although I'm just now realizing I've done class components 🤦 ). Otherwise, I'll be back in a month! 😁

**Comment by neil-marcellini** [comment]
Thanks, yeah I'll take it over. Congrats @Gonals!!

**Comment by JmillsExpensify** [comment]
Super late but I wanted to confirm that yes, this is indeed the plan. 

> I think we decided that we want both the room name and the notification frequency to be push-to-page inputs. When you tap on room name, you get pushed to a new page where you are auto-focused. Saving this new page then returns back to the overview page.

**Comment by neil-marcellini** [comment]
> Does this require C+ review? Asking since I was assigned on the linked [issue](https://github.com/Expensify/App/issues/16768).

@aimane-chnaif I'm going to leave that up to the assigned internal reviewer. I'll let them know that you're available to review.

**Review by aimane-chnaif — CHANGES_REQUESTED** [review]
Reviewing as per [slack request](https://expensify.slack.com/archives/C02NK2DQWUX/p1683243104805079)

Code mostly looks good.

Some issues so far:
- style broken on invited room

bug1


- room name auto-focus doesn't work on android native. please use same solution as https://github.com/Expensify/App/pull/17953


https://user-images.githubusercontent.com/96077027/236397517-5b95de25-6aa2-4002-9ff3-0d431ce3f1b8.mov

**Comment by neil-marcellini** [comment]
Yeah thanks for your review @aimane-chnaif! I haven't had time to get to this but I will as soon as I can. I'll notify you when I'm ready for another review.

**Comment by neil-marcellini** [comment]
@aimane-chnaif I'm not able to reproduce either of the issues you described after merging main. If it's still a problem please include detailed reproduction steps.

Also, is it a new problem or does it also exist on main?

**Comment by neil-marcellini** [comment]
I thought maybe the problem was the keyboard not opening. I tried forwarding a ref to the RoomNameInput and focusing it onEntryTransitionEnd, but I couldn't get the ref to work, it was always null.

Here's the changes I tried on the RoomNamePage if you want to play around with it. Anyways, I want to make sure I understand the problem before I dig deeper.
<details>
<summary>Forward ref focus attempt</summary>

```javascript
import React, {useCallback, useRef} from 'react';
import {withOnyx} from 'react-native-onyx';
import PropTypes from 'prop-types';
import {View} from 'react-native';
import CONST from '../../../CONST';
import ScreenWrapper from '../../../components/ScreenWrapper';
import HeaderWithCloseButton from '../../../components/HeaderWithCloseButton';
import withLocalize, {withLocalizePropTypes} from '../../../components/withLocalize';
import Form from '../../../components/Form';
import ONYXKEYS from '../../../ONYXKEYS';
import styles from '../../../styles/styles';
import Navigation from '../../../libs/Navigation/Navigation';
import compose from '../../../libs/compose';
import * as ErrorUtils from '../../../libs/ErrorUtils';
import * as ValidationUtils from '../../../libs/ValidationUtils';
import withReportOrNotFound from '../../home/report/withReportOrNotFound';
import reportPropTypes from '../../reportPropTypes';
import ROUTES from '../../../ROUTES';
import * as Report from '../../../libs/actions/Report';
import RoomNameInput from '../../../components/RoomNameInput';

const propTypes = {
    ...withLocalizePropTypes,

    /** The room report for which the name is being edited */
    report: reportPropTypes.isRequired,

    /** All reports shared with the user */
    reports: PropTypes.objectOf(reportPropTypes),
};
const defaultProps = {
    reports: {},
};

const RoomNamePage = (props) => {
    const report = props.report;
    const reports = props.reports;
    const translate = props.translate;
    const nameInputRef = useRef(null);

    const validate = useCallback((values) => {
        console.log('debug validate nameInputRef =', nameInputRef);
        const errors = {};

        // We should skip validation hence we return an empty errors and we skip Form submission on the onSubmit method
        if (values.roomName === report.reportName) {
            return errors;
        }

        if (!values.roomName || values.roomName === CONST.POLICY.ROOM_PREFIX) {
            // We error if the user doesn't enter a room name or left blank
            ErrorUtils.addErrorMessage(errors, 'roomName', translate('newRoomPage.pleaseEnterRoomName'));
        } else if (!ValidationUtils.isValidRoomName(values.roomName)) {
            // We error if the room name has invalid characters
            ErrorUtils.addErrorMessage(errors, 'roomName', translate('newRoomPage.roomNameInvalidError'));
        } else if (ValidationUtils.isReservedRoomName(values.roomName)) {
            // Certain names are reserved for default rooms and should not be used for policy rooms.
            ErrorUtils.addErrorMessage(errors, 'roomName', translate('newRoomPage.roomNameReservedError', {reservedName: values.roomName}));
        } else if (ValidationUtils.isExistingRoomName(values.roomName, reports, report.policyID)) {
            // The room name can't be set to one that already exists on the policy
            ErrorUtils.addErrorMessage(errors, 'roomName', translate('newRoomPage.roomAlreadyExistsError'));
        }

        return errors;
    }, [report, reports, translate]);

    return (
        <ScreenWrapper
            includeSafeAreaPaddingBottom={false}
            onEntryTransitionEnd={() => {
                console.log('debug nameInputRef =', nameInputRef);
                if (!nameInputRef.current) {
                    return;
                }
                nameInputRef.current.focus();
            }}
        >
            <HeaderWithCloseButton
                title={translate('newRoomPage.roomName')}
                shouldShowBackButton
                onBackButtonPress={() => Navigation.drawerGoBack(ROUTES.getReportSettingsRoute(report.reportID))}
                onCloseButtonPress={() => Navigation.dismissModal(true)}
            />
            <Form
                style={[styles.flexGrow1, styles.ph5]}
                formID={ONYXKEYS.FORMS.ROOM_NAME_FORM}
                onSubmit={values => Report.updatePolicyRoomNameAndNavigate(report, values.roomName)}
                validate={validate}
                submitButtonText={translate('common.save')}
                enabledWhenOffline
            >
                <View style={styles.mb4}>
                    <RoomNameInput
                        inputID="roomName"
                        defaultValue={report.reportName}
                        ref={nameInputRef}
                    />
                </View>
            </Form>
        </ScreenWrapper>
    );
};

RoomNamePage.propTypes = propTypes;
RoomNamePage.defaultProps = defaultProps;
RoomNamePage.displayName = 'RoomNamePage';

export default compose(
    withLocalize,
    withReportOrNotFound,
    withOnyx({
        reports: {
            key: ONYXKEYS.COLLECTION.REPORT,
        },
    }),
)(RoomNamePage);

```
</details>

**Review by aimane-chnaif — CHANGES_REQUESTED** [review]
We can fix android focus issue as a follow-up.

Please fix lint.

**Comment by neil-marcellini** [comment]
> @neil-marcellini it's easily reproducible. Please check #admins room settings

Ah yes, thanks for explaining!

**Review by aimane-chnaif — DISMISSED** [review]

**Review by mountiny — COMMENTED** [review]
@neil-marcellini Great job on this one, there is one conflict though, can you please resolve it?

**Review by mountiny — APPROVED** [review]
Thanks @Gonals for staring, @aimane-chnaif for review and testing and @neil-marcellini getting it to the finish line.

**Pull request merged**
