### PR TITLE
Fix min hight constant typo

### PR DESCRIPTION
**Pull request by Julesssss**
### Details

Fixes a small issue with [this PR](https://github.com/Expensify/App/pull/8752)

### Fixed Issues

$ https://github.com/Expensify/App/issues/9128

### QA Steps

**For ipad/tablets***
- Open Expensify app on iPad/tablet (Signed out state).
- Verify that the login-form-layout is updated as per https://github.com/Expensify/App/issues/8122#issuecomment-1066971554.

**For other platforms**
- Open Expensify app
Verify that due to these changes https://github.com/Expensify/App/issues/8122#issuecomment-1066971554 is not effected for other platforms.
- Verify that no errors appear in the JS console

### Screenshots

As this was a hotfix to [this PR](https://github.com/Expensify/App/pull/8752) I only built to web and iPad (the platform which was broken)

#### Web
1) Screenshot 2022-05-23 at 17 07 12
2) Screenshot 2022-05-23 at 17 07 05

#### iOS
Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-05-23 at 17 31 07

### CODE REVIEW

**Review by amyevans — APPROVED** [review]

**Comment by Santhosh-Sellavel** [comment]
@Julesssss can we do one more correction here.

**Comment by Santhosh-Sellavel** [comment]
Oh, you got that comment too, thanks! @Julesssss

**Review by bondydaa — APPROVED** [review]

**Comment by Julesssss** [comment]
Nearly forgot theCherrypick label 😅

**Comment by Julesssss** [comment]
Morning @Expensify/applauseleads, this one is ready for retesting now. Build `1.1.65-6`

**Pull request merged**
