### PR TITLE
[Production QA] Update app description title and preview image

### PR DESCRIPTION
**Pull request by francoisl**
cc @davidcardoza 

### Details
Update the `title` property of the app's meta tags to `New Expensify`.

### Fixed Issues
$ https://github.com/Expensify/App/issues/5737#issuecomment-939192158
Follow-up of https://github.com/Expensify/App/pull/5740 that got merged too soon.

### Tests
1. Launch ngrok so you can have a public-facing URL for NewDot
2. Copy the URL in an app that does "previews", e.g. Whatsapp, Twitter, FB, etc.
3. Make sure the title of the app in the preview is `New Expensify`
3. Make sure the logo in the preview is the "E" version with a blue background - _not_ the "$" with a white background

### QA Steps
1. In WhatsApp or Twitter or FB, post a link to https://new.expensify.com
2. Make sure the title of the app in the preview is `New Expensify`, like on the screenshot
3. Make sure the logo in the preview is the "E" version with a blue background - _not_ the "$" with a white background
image

### CODE REVIEW

**Comment by shawnborton** [comment]
How about this as a replacement:
og-preview-image

[og-preview-image.png.zip](https://github.com/Expensify/App/files/7324036/og-preview-image.png.zip)

**Review by roryabraham — APPROVED** [review]
LGTM, but be aware @francoisl that Expensify/App does not have an internal or production QA checklist, so you have to personally remember to QA this on production.

**Comment by isagoico** [comment]
@francoisl I see production QA on this one. Should we check this off and then test once it hits prod?

**Comment by francoisl** [comment]
Yes please!

**Pull request merged**
