### PR TITLE
fix: Retain cursor on form submit

### PR DESCRIPTION
**Pull request by mananjadhav**
@mountiny PR for the cursor issue.

### Details

- Added `blurOnSubmit` for the `PasswordForm`

### Fixed Issues

$ https://github.com/Expensify/App/issues/5191

### Tests
1. Verified focus stays on "Return" and "Enter"
2. Verified that S.ignin button click shouldn't retain the focus

### QA Steps
1. Go to the Password form page
2. Try to enter the password
3. Press Enter and ensure that the input is still focused.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/3069065/133500036-645acd3c-c8e8-4b77-8d0e-fa8fe40fb42a.mov

#### Mobile Web

https://user-images.githubusercontent.com/3069065/133499908-fb79ef6e-2c49-4692-86c1-333214cda45e.mov

#### Desktop

https://user-images.githubusercontent.com/3069065/133499747-9c5da634-ccc7-4cb9-9161-261dd49e9094.mov

#### iOS

https://user-images.githubusercontent.com/3069065/133499857-62172868-a4d5-4a5b-a925-f2d06cb8deda.mov

#### Android
https://user-images.githubusercontent.com/3069065/133500261-7f13cdd4-c724-45da-a5cc-a43df6eb53ad.mov

### CODE REVIEW

**Comment by kadiealexander** [comment]
Hi @mananjadhav, I've placed this issue on hold as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1631754482374800), as we are prioritising issues related to a feature release scheduled for 9/24. As an apology for the delay, we will add a $100 bonus as a thank you for waiting.

**Comment by mananjadhav** [comment]
Thanks for notifying @kadiealexander. Nothing to apologise for :)

Let me know if we can help in anyway for the upcoming release

**Review by mountiny — APPROVED** [review]
LGTM! I will add HOLD into the title until we are done with the release, just in case I would accidentally want to merge this 😅

**Comment by mountiny** [comment]
Hi @mananjadhav, the `n6-hold` was lifted so we can go ahead with this one.

Although this PR is quite small and simple, I would prefer if we could always merge `main` branch to any of the `n6-hold `PRs and re-test. I doubt there will be any regression here, but better safe than sorry.

Thank you very much and I hope it won't take too long. Thank you for your patience 🙇

**Review by mountiny — COMMENTED** [review]
Approved it already before and no changes were added since.

**Pull request merged**
