### PR TITLE
Improve search functions to match multiple names

### LINKED ISSUE #1283: [Improvement] Improve E.cash search for group chats
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  All

# Problem
Search is frequently how I find a given chat. There are two main problems I currently have with it: 
1. It doesn't work well for group chats. For example I can't type in `Lauren Andrew` in order to find my group chat with Lauren and Andrew. 
2. It looks for the whole string that I type in to be a match, rather than looking at whether there is a matching user for each word. For example, when I search `Alex Revelli` nothing comes up because she she is listed as `Alexandra Revelli`. I would think that she would still show up because the second word in my search, `Revelli` is a match to her user. 
 
# Why is this important?
Easy search makes Expensify.cash an easier, lighter experience. 

# Solution
Update search to work as follows: 

- split search string on spaces
- return all exact and partial matches to each string
- order results by most recent message (meaning the most recent message posted in the chat)

Upwork Job link: https://www.upwork.com/jobs/~01ccd27d2ef43f2d7f

### PR DESCRIPTION
**Pull request by tugbadogan**
cc @NicMendonca 

### Details

- Splitted search value into the words. 
- Test regex for each word.
- Removed redundant regex patterns.
- Added `sortByLastMessageTimestamp` to search options.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1283

### Tests

- Click seach icon
- Enter "test1 test7" value to search input box
- Make sure the group with test1@example.com and test7@example.com is listed
- Verified that search results are ordered by last message timestamp

### Tested On

- [X] Web
- [ ] Mobile Web
- [ ] Desktop
- [X] iOS
- [ ] Android

#### Web
Screenshot 2021-02-14 at 17 03 59

Screenshot 2021-02-14 at 17 04 20

#### iOS
Simulator Screen Shot - iPhone X - 2021-02-14 at 17 20 47

Simulator Screen Shot - iPhone X - 2021-02-14 at 17 20 53

### CODE REVIEW

**Comment by tugbadogan** [comment]
Hi @timszot,

Can you review my pull request?

**Comment by timszot** [comment]
Reassigning as I'm still without power.

**Comment by Dal-Papa** [comment]
Code looks good but could you please resolve the conflicts and provide tests for all platforms. All checkboxes need to be completed.

**Comment by marcaaron** [comment]
@tugbadogan probably will need to create a new PR since this one was closed and the conversation is locked.

**Comment by tugbadogan** [comment]
@marcaaron I will close this PR as I created a new PR

https://github.com/Expensify/Expensify.cash/pull/1523

**Pull request closed without merging**
