### PR TITLE
Revert "Fix: back handler for Drawer"

### PR DESCRIPTION
**Pull request by marcaaron**
Reverts Expensify/App#5745

# Fixed Issues
$ https://github.com/Expensify/App/issues/6150
$ https://github.com/Expensify/App/issues/6147

### CODE REVIEW

**Comment by botify** [comment]
Hey, I noticed you changed some webpack configuration files. This can break production builds. Did you remember to run a production build locally to verify they still work?

**Comment by marcaaron** [comment]
Issues not reproducible in this branch - just doing a quick sanity test and seeing if `main` is broken again after a fresh build and cache clear then I will take off draft.

**Review by TomatoToaster — APPROVED** [review]
Cool this looks like a clean revert to me, don't block on me to merge.

**Review by Jag96 — APPROVED** [review]
Confirmed this fixes https://github.com/Expensify/App/issues/6147 as well

**Review by yuwenmemon — APPROVED** [review]

**Comment by parasharrajat** [comment]
Looks like two similar regressions poped out, I will try to find the cause and fix it.

**Pull request merged**
