### PR TITLE
3195 fix messages on password screen

### PR DESCRIPTION
**Pull request by dklymenk**
### Details

Makes the client facing offline error message more user friendly as well as adds translations to all potential errors on password form.

### Fixed Issues

$ #3195 

#### Offline error
1. Log out
2. Enter email to proceed to password form
3. Disable internet on the device or in browser devtools
4. Try to submit any password
5. Verify that the error message says: `Incorrect login or password. Please try again.`

#### Incorrect login or password
1. Log out
2. Enter email to proceed to password form
3. Submit wrong password
4. Verify that the error message says: `Looks like you're offline. Please check your connection and try again.`

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

DeepinScreenshot_select-area_20210626210058

#### Mobile Web

Screen Shot 2021-06-26 at 21 56 44

#### Desktop

DeepinScreenshot_select-area_20210626214822

#### iOS

Screen Shot 2021-06-26 at 21 53 56

#### Android

DeepinScreenshot_select-area_20210626213753

### CODE REVIEW

**Comment by dklymenk** [comment]
There is this one concern I'd like to raise.

If you put less than 4 characters in password text input and submit the form, you will get an error 402 from server which translates into a `You have 2FA enabled on this account. Please sign in using your email or phone number.` error message on FE. I think I should ask someone to validate that these error codes are still up to date: https://github.com/Expensify/Expensify.cash/blob/main/src/libs/API.js#L220-L241

**Comment by sketchydroide** [comment]
@dklymenk thanks for raising that, I think that might be an issue with our backend, and I'll investigate. Code wise your changes look good and I'm happy to aprove/merge them, And I think we can create a GH either for the internal team if it's in the backend, or for contributors if it's not, but it feels that there is at least some backend work.

**Review by sketchydroide — APPROVED** [review]
LGTM

**Comment by sketchydroide** [comment]
Ok after some investigation, this seems to make sense to have the error like that for case @dklymenk mentioned, the sense is that if the user has entered a password and a email and the account has 2FA then it needs the 2FA code as well before it tries to authenticate.

**Comment by dklymenk** [comment]
The issue I've described is for account with no 2FA. I get the 2FA error message with that account when I send less than 4 characters. Please, give it a try, if you have an account with no 2FA?

**Comment by sketchydroide** [comment]
Ohh, that is definetly interesting, still should not affect this PR.

**Comment by roryabraham** [comment]
The deploy messages are unfortunately broken right now. This was deployed to staging yesterday.

**Pull request merged**
