### PR TITLE
Don't run CLA workflow twice

### PR DESCRIPTION
**Pull request by Jag96**
### Details
This PR fixes a side effect of https://github.com/Expensify/Expensify.cash/pull/1802#issuecomment-800657505 where the CLA workflow runs on master twice. Since we already have this workflow running on `pull_request_target`, we should be able to exclude it from running on master for `pull_request` actions

### Tests
Created this PR, confirmed the CLA workflow only ran once on `pull_request_target`
image

### CODE REVIEW

**Review by roryabraham — DISMISSED** [review]
Nice, LGTM 👍

**Review by roryabraham — APPROVED** [review]
LGTM 👍

**Comment by botify** [comment]
@roryabraham looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Comment by roryabraham** [comment]
Just testing GH Actions, no need to wait for iOS E2E tests to finish.

**Pull request merged**
