### PR TITLE
IOU Requests restricted in workspace announce room chat

### PR DESCRIPTION
**Pull request by Santhosh-Sellavel**
### Details
Restricted IOU operations in announce room.

### Fixed Issues

$ https://github.com/Expensify/App/issues/5134

### Tests && QA Steps
1. Navigate to a #announce room
2. Click on the + (used to add attachments) button  in compose section button

### Fix: 
Now IOU Split/Request options will not be available for the announce room chat.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screenshot 2021-09-15 at 12 33 29 AM

#### Mobile Web
Simulator Screen Shot - iPhone 11 - 2021-09-15 at 00 20 27

#### Desktop
Screenshot 2021-09-15 at 12 24 27 AM

#### iOS
Simulator Screen Shot - iPhone 12 - 2021-09-15 at 00 18 14

#### Android
Screenshot_1631645305

### CODE REVIEW

**Comment by johnmlee101** [comment]
Can you verify in your tests that `hasMultipleParticipants` and the other parameters in the conditional are true _except_ the isDefaultRoom? (you can just do this in web)

I remember the discussion in the issue where having only 1 or 2 participants total skews this from reproducing.

**Comment by Santhosh-Sellavel** [comment]
@johnmlee101 
`hasMultipleParticipants` is used to determine IOU Split or Request option that should be shown for the chat based on participant count.

But for an announce room chat IOU operations should not be allowed. `hasMultipleParticipants` check won't be needed.

**Comment by Santhosh-Sellavel** [comment]
@johnmlee101 By the way, I checked. Refer the screenshots below
### hasMultipleParticipants false
Screenshot 2021-09-15 at 2 00 15 AM

### hasMultipleParticipants true
Screenshot 2021-09-15 at 1 59 21 AM

Note: 
For debugging purposes I added `isDefaultRoom` check as a variable `isDefaultChatRoom`

**Comment by Santhosh-Sellavel** [comment]
Since it was decided to keep it as a feature, closing this out!

**Pull request closed without merging**
