### PR TITLE
Make preDeploy workflow handle StagingDeployCash logic

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Run two new actions at the beginning of the workflow:

1) actions-ecosystem/get-merged-pull-request](https://github.com/actions-ecosystem/action-get-merged-pull-request)
    - It uses JS so should work on macOS runner.
    - Has only the one `github_token` input (note lowercase not `GITHUB_TOKEN` 😉), so should be pretty difficulty to misconfigure.
2) isStagingDeployLocked

Then if the StagingDeployCash is locked, we comment on the PR stating that it will be merged later, and skip all the rest of the workflow steps. Otherwise, continue as usual, except with one new final step. In the last step, use the `createOrUpdateStagingDeploy` action to add the newly merged PR to the StagingDeployCash.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/155208

### Tests
Testing plan:

- [x] Make sure we have a valid, open, unlocked, StagingDeployCash issue in the Expensify.cash repo.
- [x] Merge this PR, and we should expect:
    - [x] `OSBotify` _does not_ comment on the merged PR stating that it was not deployed yet.
    - [x] The version is created successfully, along with a tag and an automerge PR. The automerge PR should merge and a staging deploy should commence.
    - [x] The StagingDeployCash issue should be updated to include this PR.
- [x] Add the `🔐 LockCashDeploys 🔐` label to the `StagingDeployCash`.
- [x] Merge another dummy PR, and we should expect:
    - [x] `OSBotify` comments on the merged PR staging that is was not deployed yet.
    - [x] The rest of the workflow is skipped, but does not result in a failure. No new version is created, no new tag, no new automerge PR.
    - [x] The StagingDeployCash issue should be unmodified.

### CODE REVIEW

**Comment by roryabraham** [comment]
This is off hold and ready for review, but don't merge just yet because I want to do some testing in another repo

**Comment by roryabraham** [comment]
Okay, did some testing of the stuff I was unsure about [here](https://github.com/Andrew-Test-Org/Public-Test-Repo/actions/runs/647192334). This is updated and ready for review & merge-test.

**Comment by AndrewGable** [comment]
Is this off hold too?

**Review by AndrewGable — APPROVED** [review]

**Review by TomatoToaster — APPROVED** [review]

**Comment by AndrewGable** [comment]
Tests failed second step:

> Unable to resolve action `actions-ecosystem/get-merged-pull-request@cb1e7423b3ca9886f619a8b93874b2e72abfb87c`, repository not found

https://github.com/Expensify/Expensify.cash/actions/runs/647369887

I will make a PR to resolve this and continue testing

**Comment by AndrewGable** [comment]
PR to resolve typo 👉 https://github.com/Expensify/Expensify.cash/pull/1750

I will continue testing once this is merged!

**Comment by AndrewGable** [comment]
Got another error:

```
Run Expensify/Expensify.cash/.github/actions/createOrUpdateStagingDeploy@master
  with:
    GITHUB_TOKEN: ***
    NPM_VERSION: 1.0.2-44
    NEW_PULL_REQUESTS: https://github.com/Expensify/Expensify.cash/pull/1750
  env:
    PULL_REQUEST_NUMBER: 1751
Unexpected error occurred finding the StagingDeployCash! There may have been more than one open StagingDeployCash found, or there was some other problem with the Github API request. Error: Provided URL  is not a valid Github Issue or Pull Request!
    at Function.getIssueOrPullRequestNumberFromURL (/Users/runner/work/_actions/Expensify/Expensify.cash/master/.github/actions/createOrUpdateStagingDeploy/index.js:521:19)
Error: Error: Provided URL  is not a valid Github Issue or Pull Request!
    at /Users/runner/work/_actions/Expensify/Expensify.cash/master/.github/actions/createOrUpdateStagingDeploy/index.js:376:45
    at Function.map (/Users/runner/work/_actions/Expensify/Expensify.cash/master/.github/actions/createOrUpdateStagingDeploy/index.js:18563:24)
    at /Users/runner/work/_actions/Expensify/Expensify.cash/master/.github/actions/createOrUpdateStagingDeploy/index.js:374:50
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Failed fetching data from Github! undefined
An error occurred! Error: Failed fetching data from Github
    at /Users/runner/work/_actions/Expensify/Expensify.cash/master/.github/actions/createOrUpdateStagingDeploy/index.js:56:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Error: Failed fetching data from Github
```


https://github.com/Expensify/Expensify.cash/runs/2098738279?check_suite_focus=true

**Comment by AndrewGable** [comment]
@roryabraham fixed that error: https://github.com/Expensify/Expensify.cash/pull/1752

Back on the testing 🐴

**Comment by AndrewGable** [comment]
Verified that the first set of tests pass ✅ 

Now working on verifying the 🔒 label works

**Comment by AndrewGable** [comment]
Tested in: https://github.com/Expensify/Expensify.cash/pull/1754

Got an error: 

```
Error: HttpError: Unable to create comment because issue is locked.
Error: Unable to create comment because issue is locked.
```

We think we know the fix

**Pull request merged**
