### PR TITLE
[No QA] Fix typos in finishReleaseCycle workflow

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
(hopefully) Fixes failed workflow run: https://github.com/Expensify/Expensify.cash/actions/runs/730486034

### Tests
Merge to test 🙃

### CODE REVIEW

**Review by deetergp — CHANGES_REQUESTED** [review]
Looks good, but let's also rename the one in the test from `checkForDeployBlockers` to `checkDeployBlockers` also.

**Comment by roryabraham** [comment]
Updated 👍

**Review by deetergp — APPROVED** [review]
Looks good, thanks for cleaning up my mess!

**Comment by deetergp** [comment]
@madmax330 I'm just going to merge it since it's just fixing a name.

**Pull request merged**
