### PR TITLE
Migrate ReportActionCompose to PressableWithFeedback

### PR DESCRIPTION
**Pull request by robertKozik**
### Details

This PR replaces existing `TouchableOpacity` implementations of:
- expand button
- collapse button
- send button

to `PressableWithFeedback` implementation. For every pressable accessibilityRole and label was added (using existing translations). From the send button hitSlop is removed, because GenericPressable itself applies hitSlop based on component size

### Fixed Issues

$ https://github.com/Expensify/App/issues/17019
PROPOSAL: https://github.com/Expensify/App/issues/17019

### Tests

1. Open chat
2. Write multiline text:
        - verify that expand/collapse, add buttons works properly
3. Try to sand message and verify that send button works properly

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as Test steps

### QA Steps

Same as Test steps

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/61146594/a9bbfd8a-9563-42c0-b88a-4a573e12bf50

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/61146594/a6e0e947-70ab-4758-a529-6e46c70360bd

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/61146594/f6ee88bb-2d5b-47c7-9c05-b94caa491b27

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/61146594/520bfe41-2aed-417b-986e-753aad9f65aa

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/61146594/bd9d26a6-302f-4433-9486-92df6270e386

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/61146594/a54c4b91-aa69-4f72-abd8-75903b02af53

</details>

### CODE REVIEW

**Comment by robertKozik** [comment]
I have just an emulator on my side too, but I can encountered it on the latest main branch as well. Moreover it looks like, even after expanding the field, composer displays only one (last) line of multiline message.


https://github.com/Expensify/App/assets/61146594/603243cb-90ff-4da2-ac0a-4b5ce786c03a

**Comment by robertKozik** [comment]
> @srikarparsi When the `send` button is in disabled state, the cursor changes to disabled after applying the changes. I guess that is fine?

Yeah, It comes with the new Pressables - when it's disabled cursor is automatically handled as `disabled` too

**Comment by srikarparsi** [comment]
Thanks @robertKozik and @allroundexperts! Yeah let's wait until the crash is fixed before merging this even though it's unrelated. The code looks good so I'll just test it after the regression is fixed and this should be good to merge!

**Comment by chrispader** [comment]
The regression got fixed [here](https://github.com/Expensify/App/issues/11694#issuecomment-1568144643).

Once it's merged, you should be able to continue this issue! :)

**Comment by srikarparsi** [comment]
Awesome! @allroundexperts could you add the android screenshot to the reviewer checklist whenever you get a chance?

**Comment by srikarparsi** [comment]
ah sorry thought that the fix got merged for some reason. It looks like it will get reviewed today so hopefully we can get this out tomororw.

**Comment by roryabraham** [comment]
So should this be on HOLD for https://github.com/Expensify/App/pull/19809 ?

**Comment by srikarparsi** [comment]
Yes it should, just added it in.

**Comment by roryabraham** [comment]
Seems like this is ready to come off HOLD

**Comment by roryabraham** [comment]
@robertKozik you should probably merge main here.

**Comment by robertKozik** [comment]
I'm on it.

**Comment by robertKozik** [comment]
@roryabraham main merged

**Review by allroundexperts — APPROVED** [review]
Looks good!

**Review by srikarparsi — APPROVED** [review]
looks good to me!

**Comment by srikarparsi** [comment]
Yeah I agree @sobitneupane, might be good to address this is another issue but it's not related to this as the same happens on production. Thanks for the changes @robertKozik!

**Pull request merged**
