### PR TITLE
Revert "feat: add image loading placeholder"

### PR DESCRIPTION
**Pull request by mountiny**
Reverts Expensify/App#7723

Coming from deploy blocker https://github.com/Expensify/App/issues/7900

### CODE REVIEW

**Comment by mountiny** [comment]
@roryabraham Coming from @kidroca investigation it seems the https://github.com/Expensify/App/pull/7723 PR is causing the issues. I have created this Revert, feel free to review and merge to close the Deployblocker and @mdneyazahmad would then look into the feedback from @kidroca to fix the issue. It is not a required feature so we can revert and work on implementing it later and watch out for this problem.

**Comment by roryabraham** [comment]
Okay, after some [fiddling](https://expensify.slack.com/archives/C01GTK53T8Q/p1646077824211399) I was able to verify this fix locally.

**Review by roryabraham — APPROVED** [review]

**Comment by SumitDiyora** [comment]
**Issue 1 -**

**Title**- [Medium]: Chrome+ Jaws: Screen reader: Role is not defined for 'Send' control.
**Actual** -  'Actions (+)' control is not accessible using screen reader, while press Enter on the control focus moves to another control.
**Note-** On MAC screen reader is reading "Send Group".
**Expected** - Actions (+)' control should accessible using screen reader.
**WCAG failure** - 4.1.2
**Reproducible in staging?:** - Yes
**Version Number:** - v1.1.40-2
**Platforms** - Web (Chrome + Jaws), iOS, Mobile-web (iOS), Desktop(MAC)

Note - Due to the installation of the build not able to check on the Android

#7933_Role not defined for Send control

**Issue 2 -**

**Title**- [Medium]: Chrome+ Jaws: Screen reader: Status message is not being announced by screen reader after activating the 'Send' control.
**Actual** -  Status message is not being announced by screen reader after activating the 'Send' control. Screen reader is silent and focus lands on the Action (+) button.
**Expected** - Status message should announce by screen reader after uploading the attachment. Screen reader should read like "Image/video has been uploaded".
**WCAG failure** - 4.1.3
**Reproducible in staging?:** - Yes
**Version Number:** - v1.1.40-2
**Platforms** - Web (Chrome + Jaws), iOS, Mobile-web (iOS), Desktop(MAC)

Note - Due to the installation of the build not able to check on the Android.

https://user-images.githubusercontent.com/97600950/157387589-2e93ffe0-bd3e-4fac-85ed-be96c3832b81.mp4

**Issue 3 -**

**Title** - [Medium] Chrome: Color Contrast: Insufficient color contrast for 'Create Room' control.
**Actual** - Background/foreground color combinations with an insufficient contrast ratio was found on control. For instance, the #03D47C "Send" control text has an insufficient color contrast ratio of 2.0.1 with a #FFFFFF background.
**Expected** - The "Send" text control should have a contrast ratio against the page background of 4.5:1 or greater..
**WCAG failure** - 1.4.3
**Reproducible in staging?:** - Yes
**Version Number:** - v1.1.42-2
**Platforms** - Web (Chrome+Jaws), Desktop (MAC), Mobile-web (Safari+VoiceOver)
**Suggested Fix** - Ensure that each text/background color combination presents a contrast ratio of at least 4.5:1.

**Note** - Due to the installation of the build not able to check on the Android.

#7933_Color contrast fails for 'send' control

**Comment by SumitDiyora** [comment]
Issue 1 -

Title- [Medium]: Chrome+ Jaws : Screen reader : Name & Role is not defined for 'Actions (+)' control.
Actual - Screen reader is reading some other information on Actions(+) control.
Expected - Role = 'Button' and Name = 'Actions/Add attachments' should defined for Actions(+) control.
WCAG failure - 4.1.2
Reproducible in staging?: - Yes
Version Number : - v1.1.40-2
Platforms - Web (Chrome + Jaws), iOS, Desktop (MAC)

Note - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/157381005-478db150-6c68-4017-8b83-08a120dc5785.mp4

Issue 2 -

Title- [Medium]: Chrome+ Jaws : Keyboard : 'Actions (+)' control is not accessible using screen reader.
Actual - 'Actions (+)' control is not accessible using screen reader, while press Enter on the control focus moves to another control.
Expected - Actions (+)' control should accessible using screen reader.
WCAG failure - 2.1.1
Reproducible in staging?: - Yes
Version Number: - v1.1.40-2
Platforms - Web (Chrome + Jaws), iOS, Mobile-web(iOS)

Note - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/157382341-ae72e99d-b121-444e-bd35-56c23846fae4.mp4

Issue 3 -

Title- [Medium]: Chrome+ Jaws : Screen reader: Role is not defined for 'Send' control.
Actual - 'Actions (+)' control is not accessible using screen reader, while press Enter on the control focus moves to another control.
Note- On MAC screen reader is reading "Send Group".
Expected - Actions (+)' control should accessible using screen reader.
WCAG failure - 4.1.2
Reproducible in staging?: - Yes
Version Number: - v1.1.40-2
Platforms - Web (Chrome + Jaws), iOS, Mobile-web (iOS), Desktop(MAC)

Note - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/157382967-689c127b-42b6-4e12-974c-3256cb9c4010.mp4

Issue 4 -

Title- [Medium]: Chrome+ Jaws : Screen reader: Status message is not being announced by screen reader after activate the 'Send' control.
Actual - Status message is not being announced by screen reader after activate the 'Send' control. Screen reader is silent and focus lands on the Action(+) button.
Expected - Status message should announce by screen reader after uploading the attachment. Screen reader should read like "Image/video has been uploaded".
WCAG failure - 4.1.3
Reproducible in staging?: - Yes
Version Number: - v1.1.40-2
Platforms - Web (Chrome + Jaws), iOS, Mobile-web (iOS), Desktop(MAC)

Note - Due to installation of build not able to check on Android

https://user-images.githubusercontent.com/97600950/157387589-2e93ffe0-bd3e-4fac-85ed-be96c3832b81.mp4

**Comment by SumitDiyora** [comment]
Duplicate of PR

**Pull request merged**
