### PR TITLE
fix: Settings button appears after delay after enabling Tags

### PR DESCRIPTION
**Pull request by nkdengineer**
### Fixed Issues

$ https://github.com/Expensify/App/issues/41900
PROPOSAL: https://github.com/Expensify/App/issues/41900#issuecomment-2107148187

### Tests

1. Go to Account settings > Workspaces.
2. Go to workspace that has not enabled Tags.
3. Go to More features.
4. Enable Tags.
5. Go to Tags section.
6. Verify that: Settings button will appear immediately.

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Go to Account settings > Workspaces.
2. Go to workspace that has not enabled Tags.
3. Go to More features.
4. Enable Tags.
5. Go to Tags section.
6. Verify that: Settings button will appear immediately.
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/161821005/bd785073-a43e-42b4-b634-09a522981b21

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/161821005/0897f50b-4ac8-4a1d-9a31-35da22e0a687

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/161821005/9110323c-9a7c-4cc7-972d-6fe3a29f19d3

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/161821005/af993a7e-b2ae-4312-a7d8-5d91a636f88b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/161821005/2432314c-d7cb-4e13-8893-3ba87175b8f5

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/161821005/edb368e3-6309-489f-8489-8afa0f8bbca3

</details>

### CODE REVIEW

**Review by sobitneupane — COMMENTED** [review]
@nkdengineer I don't think we should block the page in offline if data is already available. I believe we should show offline screen only if user is offline and there is no data. I also don't think `This feature requires an active internet connection to be used.
` is correct.


https://github.com/Expensify/App/assets/25876548/e42a5cb7-e98f-4cc7-8748-ed8d7a164f70


cc: @MonilBhavsar

**Comment by MonilBhavsar** [comment]
> I don't think we should block the page in offline if data is already available.

Correct! Only if user is offline and *no* data is not available

**Comment by nkdengineer** [comment]
@sobitneupane any update here

**Comment by sobitneupane** [comment]
@nkdengineer The app crashes if I enable the Tag while offline and open the Settings.

Steps:
1. Login 
2. Go offline
3. Go to any workspace and enable the Tags feature
4. Go to Settings

https://github.com/Expensify/App/assets/25876548/f81d50b2-cfc6-4d81-b59f-c684344673ac

**Comment by nkdengineer** [comment]
@sobitneupane i can't reproduce this bug

https://github.com/Expensify/App/assets/161821005/34396c95-da8e-4b00-86d6-33b3461bda6a

**Comment by sobitneupane** [comment]
Thanks for the update @nkdengineer. I also cannot reproduce the issue any longer. We might have added default policy tags which might have solved the issue.

**Comment by sobitneupane** [comment]
Also, in that case, the issue should not be reproducible any longer. @nkdengineer Can you please verify that the change in this PR is no longer required?

**Comment by nkdengineer** [comment]
@sobitneupane I still can reproduce the bug when we open /settings/workspaces/${policyID}/tags with policyID of the workspace that we already enable tags feature but there is no policyTags_ data. Here is the step to reproduce:
1. Logout.
2. Login.
3. Open devtool, go to Application to see the Onyxkey storage. Here, we find any ```policyID``` that we already enabled tags feature but did not have ```policyTags_``` value.
4. Enter the https://dev.new.expensify.com:8082/settings/workspaces/${policyID}/tags to the url then press enter.
5. Now you can reproduce the bug.

Can you help check it?

**Comment by nkdengineer** [comment]
> @sobitneupane i can't reproduce this bug

@sobitneupane in here,  i mean I cannot reproduce [this offline bug](https://github.com/Expensify/App/pull/42623#issuecomment-2151799553)

**Comment by sobitneupane** [comment]
@nkdengineer I can still reproduce this [issue](https://github.com/Expensify/App/pull/42623#issuecomment-2151799553).

Screenshot 2024-06-12 at 14 45 12



https://github.com/Expensify/App/assets/25876548/b20eea55-7895-457b-a078-775c93ab668c

**Comment by nkdengineer** [comment]
@sobitneupane i fixed this [bug](https://github.com/Expensify/App/pull/42623#issuecomment-2162492917)

https://github.com/Expensify/App/assets/161821005/2c4de6b6-79b6-48b3-8f0b-26aa8bd03d23

**Comment by sobitneupane** [comment]
@nkdengineer I think you need to test possible flows quite extensively. I can still reproduce some issues.

https://github.com/Expensify/App/assets/25876548/c74ed2dc-88e0-4ee5-b858-c5f2f35ba115

Screenshot 2024-06-17 at 13 40 23

**Comment by nkdengineer** [comment]
I am working on it.

**Comment by nkdengineer** [comment]
> I can still reproduce some issues.

In case it is `isOffline` and `isLoading` there will be no `policyTags` so [here](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/actions/Policy/Tag.ts#L126) when creating a new tag it will create a tag with the key undefined
I think in case `policyTags = undefined` we will return early [here](https://github.com/Expensify/App/blob/75614394a2fb1e8114e35bb2d8d33bdd0c565946/src/libs/actions/Policy/Tag.ts#L119) and not be allowed to create new tags
What do you think @sobitneupane

**Comment by sobitneupane** [comment]
@nkdengineer We were allowing user to create tag before. So, we should still allow user to create tag. If user won't be able to create policy tag. We should show offline page on clicking Settings.

**Comment by nkdengineer** [comment]
>  So, we should still allow user to create tag. If user won't be able to create policy tag. We should show offline page on clicking Settings.

@MonilBhavsar what do you think?

**Comment by nkdengineer** [comment]
friendly bump @MonilBhavsar

**Comment by nkdengineer** [comment]
@MonilBhavsar friendly bump

**Comment by sobitneupane** [comment]
@nkdengineer I believe you can implement [this](https://github.com/Expensify/App/pull/42623#issuecomment-2182197415). Once I approve the PR, if @MonilBhavsar is not available I will request other engineer to review the PR.

**Comment by MonilBhavsar** [comment]
I was ooo. Apologies for delay.

>> So, we should still allow user to create tag. If user won't be able to create policy tag. We should show offline page on clicking Settings.
>
> @MonilBhavsar what do you think?

We should allow users to create tags optimistically.

**Comment by nkdengineer** [comment]
@sobitneupane i updated

https://github.com/Expensify/App/assets/161821005/d9292712-c839-45fc-9e67-93889bbe723d

**Review by sobitneupane — COMMENTED** [review]
@nkdengineer 


https://github.com/user-attachments/assets/2c8f62b4-d09b-4704-b117-33d580bf2c26

Screenshot 2024-07-18 at 13 34 55

**Comment by sobitneupane** [comment]
@nkdengineer Can you please make sure to re-run the tests to make sure no issue is reproducible any longer?

**Comment by nkdengineer** [comment]
@sobitneupane Does that mean updating the test steps?

**Comment by sobitneupane** [comment]
> Does that mean updating the test steps?

Nope. You can just update the screen recordings. And also make sure that there are no issues reproducible.

**Comment by nkdengineer** [comment]
### Screenshots/Videos
<details>
<summary>Android: Native</summary>




https://github.com/user-attachments/assets/f0e9d3d2-7a78-4440-93ec-5a0343dd0993



</details>

<details>
<summary>Android: mWeb Chrome</summary>




https://github.com/user-attachments/assets/dcc9fd00-2d5e-4d73-8ec9-2065e69e0b7c



</details>

<details>
<summary>iOS: Native</summary>





https://github.com/user-attachments/assets/d3571d20-f370-42e8-a6bb-7d1743faf449




</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/552c905c-098d-4e26-91a0-eaff02db541a


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>




https://github.com/user-attachments/assets/624e2a6b-cc4e-4f2c-830b-af66daabad9d



</details>

<details>
<summary>MacOS: Desktop</summary>




https://github.com/user-attachments/assets/418c2a55-8b37-4d38-9a7d-167408362e34



</details>

**Comment by nkdengineer** [comment]
@sobitneupane I updated new recordings.

**Review by sobitneupane — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/3f9fcb41-6825-4272-b072-1c9646faddb6

</details>


<details>
<summary>iOS: Native</summary>


https://github.com/user-attachments/assets/410aee10-9207-4908-94b9-d501587f34f5


</details>

<details>
<summary>iOS: mWeb Safari</summary>


https://github.com/user-attachments/assets/a3c026fb-1662-42d7-916b-6d74afd55dbc


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>


https://github.com/user-attachments/assets/a542b837-8807-47db-840b-7708f0f9f0c4


</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by MonilBhavsar — APPROVED** [review]
Looks good! Thank you for staying on this

**Pull request merged**
