### PR TITLE
WS plan type and upgrade common features view Pages

### PR DESCRIPTION
**Pull request by jayeshmangwani**
### Fixed Issues

$ https://github.com/Expensify/App/issues/51768
PROPOSAL:

### Test 1: Plan Type

1. Go to Workspaces -> Workspace -> Profile.
2. If the user has admin access, they will see the Plan Type tab under the Company address menu item.
3. Click on Plan Type to open a new RHP screen for Plan Type
4. Verify that the current workspace plan is preselected.

### Test 2: For Locked Plan Type
**Precondition**: The user must have an active annual Control Plan subscription and must have been billed at least once.

1. Navigate to Workspaces -> Workspace -> Profile.
2. If the user has admin access, they will see the Plan Type tab located under the Company Address menu item.
3. Click on Plan Type to open a new RHP screen for Plan Type
4. Verify that user can see the Locked Plan Type UI.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests

### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."
Same as Tests
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/670f30b6-10ec-4aa8-9073-703b02665008

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/b474a0a7-e58f-4ff2-94b1-7d2b12d8b81d

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/0a093048-18c7-458a-9590-5cabf5192b0b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/a1e67340-cd74-4d85-a307-f52c0b984a46

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/cafeda4a-427d-47ed-8a16-977254be125a

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/aa13bbc3-c7f9-4d37-82d3-e17e9f797bfc

</details>

### CODE REVIEW

**Comment by DylanDylann** [comment]
@jayeshmangwani @carlosmiceli How can we handle this PR to get it merged? Should we create a flag to hide this feature and only display these pages when all done

**Comment by jayeshmangwani** [comment]
> Should we create a flag to hide this feature and only display these pages when all done

Yes, that sounds correct to me. We can either hide this feature by hardcoding it 
OR
Do not merge this PR until our downgrade logic is implemented. In that case, you would need to create a new branch from this PR to reuse the WS plan type page.

**Comment by jayeshmangwani** [comment]
Hi @carlosmiceli , Following this discussion https://expensify.slack.com/archives/C02NK2DQWUX/p1731682677445059 , we concluded that we will display the locked plan UI only if the user has an annual control plan and their **first billing is completed**. I'll need your help to determine from the backend whether the first billing has been completed for the user.

Which parameter would be best to use to get this status? I noticed the `retry_billing_success` NVP, but I wanted to confirm if this can be used for this purpose or if there's another NVP that would be more suitable.

**Comment by carlosmiceli** [comment]
Gotcha! Let me find that for you and report back.

**Comment by DylanDylann** [comment]
@carlosmiceli we also need to confirm the next step on this [problem](https://github.com/Expensify/App/pull/53343#issuecomment-2511154299)

**Comment by DylanDylann** [comment]
> Yes, that sounds correct to me. We can either hide this feature by hardcoding it

this option looks fine to me because of simpleness

**Comment by carlosmiceli** [comment]
> this option looks fine to me because of simpleness

Sounds good, once it's all ready to be tested in dev we can change the hardcoded code. Let's make sure to add a comment where we do it.

**Comment by jayeshmangwani** [comment]
Great @carlosmiceli @DylanDylann! 
I've added a function to hide the plan type button. We'll enable it for testing, and once the downgrade API is implemented and tested, we'll remove this function altogether and display the button.

**Comment by carlosmiceli** [comment]
@jayeshmangwani it's looking like [this](https://github.com/Expensify/App/pull/53343#issuecomment-2511182459) will need a BE change, and we can send a `firstBilling` bool to show/hide the UI. Which API's response would we need to modify?

**Comment by carlosmiceli** [comment]
@jayeshmangwani bump ☝️

**Comment by jayeshmangwani** [comment]
@carlosmiceli I'm not entirely sure, but in my opinion, we may need to create a new command for this. The command would return the `firstBilling` value under the `nvp_private_subscription` key, similar to how we've implemented the `OpenSubscriptionPage`. What do you think about creating a new command, `OpenWorkspacePlanPage`, which would return the current `nvp_private_subscription` value with the new `firstBilling` key included?

**Comment by carlosmiceli** [comment]
@jayeshmangwani I like that idea, just asked in Slack for some feedback in case there's some risk I'm not seeing, will report back.

**Comment by carlosmiceli** [comment]
@jayeshmangwani a couple of questions to confirm, I'm building the new command:

- Is `firstBilling` a date, or is it a `bool` and it should be called something like "isFirstBillingComplete`?
- You don't need the placeholder values for [this](https://docs.google.com/document/d/1GDPmbvV47VVxucr-tHYjH80VylcJptP0RfGMVy3zanY/edit?tab=t.0#bookmark=id.6d8zugf9cpk6) text to come back in the response, right? How are we getting those values?

**Comment by jayeshmangwani** [comment]
@carlosmiceli 

1. Yes, it should be a boolean value, and `isFirstBillingComplete` will work.
2. Currently, we are retrieving the `endDate` value from the `nvp_private_subscription` key. This data is provided by the `ReconnectApp` and `OpenApp` APIs, and it is also updated via the `OpenSubscriptionPage` command.

I’m attaching the responses below from the `ReconnectApp` and `OpenSubscriptionPage` for the `nvp_private_subscription` key.
<details>
  <summary>ReconnectApp Response</summary>
  
  ```js
  {
    "key": "nvp_private_subscription",
    "onyxMethod": "merge",
    "value": {
        "autoRenew": true,
        "autoRenewLastChangedDate": "2024-12-04 06:41:53",
        "endDate": "2025-12-01",
        "startDate": "2024-12-01",
        "type": "yearly2018"
    }
},
```
</details>

<details>
  <summary>OpenSubscriptionPage Response</summary>
  
  ```js
  {
    "accountID": 12685249,
    "authToken": "659A2AF019C7E6EDCF97155BDBA5FD7B64C7065A4FF42E993A3DE454E16BF899E0E39ABA9D72BA0B31DC0677DE570A580C20F31F915E62F5DEE7131EAF29075741EAD2A2D3518AD76C63F30FD1B8B0AB15BD4ACABDE076DB3C9BB91EAED7A4C84AFDBA2261E80EBB663803BAC09D0B0E515C94FD4ADE2310F3752232BDA5C62B35169405D888CB15ACBB9E707B063CA69D4AC3F8558F9F9CBB2913628A59A9128E51E4E498D2A930FB0AFAECA5F5BB2E24A2DCE238AC0A9FF305D701F93BF37A0C9A0CE54E9887EAE296B65F9608012A66AABF993433A38F28EB2FC7CB74273845251C601D4EE7F16E54A28698FDF6AEAE03B14D1A972506D7DF224FF000C7D07EA6F3799373A991B6D794AD3136B43BD1ED6E1CF154B3E2AF16E4951BA0F6892A3886697C5B89684124112C3E8D5E5347AB683EF5501A9C9F3BB6626DFDE1858E4115C5F1A2349292CF6E175C920546304530AC4F0FE85E6108CF440A87F862",
    "email": "jm98289517+12@gmail.com",
    "onyxData": [
        {
            "key": "nvp_private_subscription",
            "onyxMethod": "merge",
            "value": {
                "autoRenew": true,
                "autoRenewLastChangedDate": "2024-12-04 06:41:53",
                "endDate": "2025-12-01",
                "startDate": "2024-12-01",
                "type": "yearly2018"
            }
        },
        {
            "key": "nvp_private_amountOwed",
            "onyxMethod": "merge",
            "value": 2000
        },
        {
            "key": "nvp_private_stripeCustomerID",
            "onyxMethod": "merge",
            "value": null
        },
        {
            "key": "nvp_private_billingDisputePending",
            "onyxMethod": "merge",
            "value": null
        },
        {
            "key": "nvp_private_billingStatus",
            "onyxMethod": "merge",
            "value": {
                "action": "failed",
                "periodMonth": 10,
                "periodYear": 2024
            }
        },
        {
            "key": "nvp_private_billingGracePeriodEnd",
            "onyxMethod": "merge",
            "value": 1730903003
        },
        {
            "key": "nvp_private_disableAutoRenewReasons",
            "onyxMethod": "merge",
            "value": null
        },
        {
            "key": "nvp_private_cancellationDetails",
            "onyxMethod": "merge",
            "value": null
        },
        {
            "key": "account",
            "onyxMethod": "merge",
            "value": {
                "canDowngrade": true,
                "hasPurchases": true,
                "isApprovedAccountant": false,
                "isApprovedAccountantClient": false,
                "isEligibleForRefund": false
            }
        },
        {
            "key": "fundList",
            "onyxMethod": "merge",
            "value": {}
        }
    ],
    "httpCode": 200,
    "jsonCode": 200,
    "authResponseMessage": "200 OK",
    "requestID": "8eea18b36e7f3b8b-BOM"
}
```
</details>

**Comment by carlosmiceli** [comment]
@jayeshmangwani both BE PRs are now in review, but here's how it works so you can make the changes to this and other PRs that need this command: 
- The command name is `OpenWorkspacePlanPage`.
- You'll need to send the `policyID` so we can confirm the user is admin.
- The response will include a `canDowngrade` key instead of `firstBilling`.

**Comment by jayeshmangwani** [comment]
Sounds good! I'll make the changes locally and test once OpenWorkspacePlanPage will live on staging

**Comment by carlosmiceli** [comment]
@jayeshmangwani the BE is being merged as we speak, can we confirm that we're adding proper QA steps for [this](https://github.com/Expensify/App/pull/53343#issuecomment-2530425584)? Remember that `canDowngrade` is a `bool`.

**Comment by jayeshmangwani** [comment]
> can we confirm that we're adding proper QA steps for https://github.com/Expensify/App/pull/53343#issuecomment-2530425584?

@carlosmiceli I need to update the QA steps as its not cover the locked type scenario in the existing QA steps but I'll update steps. 

Additionally, I am trying to call the `OpenWorkspacePlanPage` command on staging but am getting a 404 Not Found error. It seems like the command is not yet available on staging

**Comment by carlosmiceli** [comment]
@jayeshmangwani try now, just merged the other PR :)

**Comment by jayeshmangwani** [comment]
@carlosmiceli I have tried, but I am still getting a 404 error. I am adding the cURL command below; please let me know if there is anything wrong with the parameters I am passing

<details>

<Summary>OpenWorkspacePlanPage cURL</Summary>

```js
curl 'https://dev.new.expensify.com:8082/staging/api/OpenWorkspacePlanPage?' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryhD8BaWyWoQPtBact' \
  -H 'Origin: https://dev.new.expensify.com:8082' \
  -H 'Referer: https://dev.new.expensify.com:8082/settings/workspaces/5E6D21E477EA2384/profile/plan' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw $'------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="policyID"\r\n\r\n5E6D21E477EA2384\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="apiRequestType"\r\n\r\nread\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="authToken"\r\n\r\n004926853C82257D4E1F329BA81544374B4803204A1E59B4921163C132DE905826021CA58AC33F434E8FAB537B3BE20B9AEF13845AC9781305155EE23EBDA8ABE607FB2F37C571609020AB8B0F246B0B301EC1A107A2102EE9157D66A5D238BFB7CBF80139507672CD2D039A760BBB1863FED1243B77653274C7CC95D7281953E96D50F211A9483239B6E550A7FCA3657B8166A88A4F66451818CCC6F64FE598AE7CD4C905F8A8371F713AB95F9D6287AE7F1A44275D9987419D85F400C683B0BD7B1056C3A7879BC2BE6AFD52C55DA52803F2C845025AB2289CAEB50581EE7261AA1861EFF8B1FF1CD72232BE562A1F680F883F7FC5DB05F780DCD9DBFBF1240D29037D689FAA3816D902643EC1686C2D600BF29E247C4FEE67AA49CDA80C364C47DFEB7DAB972822CE0CA05DAE58AD0A753C50ED6AA88E8F62CB27873F53FB4DBDB3F70706BABA161CAA5EB12244C467B2C1FDA100000653A9BFF8F3DDFEBF\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="referer"\r\n\r\necash\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="platform"\r\n\r\nweb\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="api_setCookie"\r\n\r\nfalse\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="email"\r\n\r\njm98289517+44@gmail.com\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="isFromDevEnv"\r\n\r\ntrue\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="appversion"\r\n\r\n9.0.74-4\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact\r\nContent-Disposition: form-data; name="clientUpdateID"\r\n\r\n3364146410\r\n------WebKitFormBoundaryhD8BaWyWoQPtBact--\r\n'
```
</details>

**Comment by carlosmiceli** [comment]
Are you getting 404 specifically? Can you share the full response?

**Comment by carlosmiceli** [comment]
Also, not sure how this works yet between App and the BE, but isn't it supposed to be a Get method?

**Comment by carlosmiceli** [comment]
@jayeshmangwani BE fixes were merged, you were right that there was a wrong response being sent. Can you try again and let me know?

**Comment by jayeshmangwani** [comment]
Thank you @carlosmiceli for making the BE changes. I have tested them, and now I am able to get a success response that includes the `canDowngrade` value.

**Comment by DylanDylann** [comment]
@jayeshmangwani Is this ready for review?

**Comment by jayeshmangwani** [comment]
@DylanDylann , the new `OpenWorkspacePlanPage` command hasn’t been added to this PR yet, but I think I can raise a follow-up PR for that new command. For now, we can merge this PR to unblock the other issue: https://github.com/Expensify/App/issues/51515.

I’m currently resolving conflicts, and then we can merge this PR so Dylan can proceed with their PR. What do you think about this plan, @carlosmiceli ?

**Comment by jayeshmangwani** [comment]
@DylanDylann, please review this PR. It includes the following changes:

1. If the user has admin rights, they will now see a new row in the workspace profile for "Plan Type."
2. If the user is on the "Collect" plan and selects the "Control" row, they can successfully upgrade their workspace plan.

Note that we haven’t added a new command to determine the locked plan type in this PR. I plan to follow up with that in a separate PR to make it easier to review and test individually.

**Comment by jayeshmangwani** [comment]
@DylanDylann, I need your help with handling the `OpenWorkspacePlanPage` response, as it’s a bit different from common API responses.

This command returns a `canDowngrade` value, which will allow us to show two different views:

1. "Workspace Plan Type Selection" if the value is true, and
2. "Locked Type" if it’s false.

The issue is that when we call this API, we don’t get onyxData. Instead, we receive the canDowngrade value. I’m attaching the response below for reference.

<details>
<summary>OpenWorkspacePlanPage Response</summary>

```js
{
    "accountID": 14498066,
    "authToken": "0B04EE0333A9DB8FCFCDE9EC09CC5A95A19206F4735BBE6326B020D764F54B126D5AFF4E823EC91B3169917E0B8F38AEE6FB861D6B2560124080AE754377E2C23B07A3106DB2C0C641CF685636A70FA5B02DC57AECDFC30A2ACB9C0168E8D64B8BD4E9C6F070652CB3835FC8AF0D148A7B30D6C569E63280CD79C9E045D213FB4E0FF105AA0338287BA9E6AA6E2559C5DF5764DAA361849BC0E353751029F4EB7A83CCEEDBDF461D185FF9C28AFBA51C12C77C130AC130F013F194477B23B2F046B0744A8D5A19180E3F3B0E996CE04899693E995C9ACD07FAB147A36D052575FFB4E0ACE8DE0248E2B3A80A471582A4A68B69C089F4E17A04259A5861C1D260D543A04C1F4970B94FFDAF15BC3BCED911B555A74EB9556655DC325482DE9326E68487439CFD6A4492F75324D1EFF0AAA3152809E9AAAAB6D1C1B78EE5460C9D06FF1BFC03D79B9EC68C276BA8D47F8B372D0BA4AC1A0D6564A",
    "canDowngrade": true,
    "email": "jm98229517+44@gmail.com",
    "httpCode": 200,
    "jsonCode": 200,
    "authResponseMessage": "200 OK",
    "requestID": "8f142b5b4ff34907-BOM",
    "onyxData": []
}

```
</details>

Here are my questions:


1. In your opinion, how should we add this new key?
2. What view should we show if the API call fails?
3. What view should we show when the user is offline?
4. What should we display while the API is still loading?

**Comment by jayeshmangwani** [comment]
Here’s what I’m thinking about how we can handle this. Let me know your thoughts:

1. **New Onyx Key**: We can add a new Onyx key specifically for this page. It will include two properties:

- isLoading
- canDowngrade

2. **API Failure Handling**: Not completely sure about the best approach for this. Suggestions welcome!

3. **Offline Handling**: We can disable this page when offline and show a full-screen offline view, we already disabled the button on next page when offline.

4. **Loading State**: A full-screen loader while the API call is in progress.

**Comment by DylanDylann** [comment]
Should we update the BE to return?

```
    "onyxData": [
     
           {
            "key": "policy_3BA0B3668E73258D",
            "onyxMethod": "merge",
            "value": {
                    "canDowngrade": true,
           }
]

```

**Comment by DylanDylann** [comment]
> What view should we show when the user is offline?

from design doc, we apply offline pattern C for this feature so I think it is fine if the lock icon only displays when users come back online

> What should we display while the API is still loading?

I think we can display loading screen


> What view should we show if the API call fails?

I think it is fine if the lock icon only displays when the API is success

**Comment by DylanDylann** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/d506caf6-2248-44ca-aac0-a4c6212bfa34




</details>

<details>
<summary>Android: mWeb Chrome</summary>



https://github.com/user-attachments/assets/375fb0a9-a3fb-4283-8eef-a38a2352cdab



</details>

<details>
<summary>iOS: Native</summary>



https://github.com/user-attachments/assets/56c838e6-de9b-491b-a570-b19213fc428f



</details>

<details>
<summary>iOS: mWeb Safari</summary>



https://github.com/user-attachments/assets/25ace33e-f52a-48b1-9f67-1412807b9f27


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



https://github.com/user-attachments/assets/66f18a4a-fc7b-4589-b45b-6da4718fea47



</details>

<details>
<summary>MacOS: Desktop</summary>



https://github.com/user-attachments/assets/3c76fcea-5cc2-44e6-aef6-3fb585de07f5



</details>

**Review by DylanDylann — APPROVED** [review]

**Comment by jayeshmangwani** [comment]
> Should we update the BE to return?

That sounds great! @carlosmiceli, what are your thoughts on this?

**Comment by carlosmiceli** [comment]
> Should we update the BE to return?

Understood, I'll work on this and report back as soon as it's merged.

**Comment by carlosmiceli** [comment]
> The issue is that when we call this API, we don’t get onyxData. Instead, we receive the canDowngrade value.

This should not be the case, looking into it.

**Comment by carlosmiceli** [comment]
Quick update that BE PRs are in review to change the response as requested.

**Comment by carlosmiceli** [comment]
BE change is ready @jayeshmangwani!

**Comment by jayeshmangwani** [comment]
Thank you, @carlosmiceli, for updating me on this. I’ve checked the response, and we now have the response under the `onyxData` key.

One last question before applying the new command changes: I’ve added a response for the API below, and here we can see that from the BE data, we sending the `canDowngrade` key under the `account` key. Just to confirm, is it correct that we will merge the `canDowngrade` key into the account’s Onyx data?

```js
{
    "onyxData": [
        {
            "key": "account",
            "onyxMethod": "merge",
            "value": {
                "canDowngrade": true
            }
        }
    ],
    "jsonCode": 200,
    "requestID": "8f398c869f57f2c2-BOM"
}
```

**Comment by carlosmiceli** [comment]
Can you check one more time, @jayeshmangwani ? I think Auth wasn't deployed yet when I added my previous comment.

**Comment by DylanDylann** [comment]
It worked for me

Screenshot 2024-12-18 at 11 38 59

**Comment by DylanDylann** [comment]
@jayeshmangwani Currently, `canDowngrade` is saved under policy_ key

**Comment by jayeshmangwani** [comment]
@carlosmiceli @DylanDylann, yes, I now have the response under the policy_key. All good!

**Comment by jayeshmangwani** [comment]
@carlosmiceli  @DylanDylann, New command was added to the PR, but now many files are failing ESLint due to this new rule [default-value-for-inexistent-IDs](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#other-expensify-resources-on-typescript). We've already made changes to 20+ files on this PR and several of them failing ESLint. Currently, I’m working on fixing these ESLint issues.

**Comment by carlosmiceli** [comment]
Thanks for the update Jayesh! Let us know if you need more help.

**Comment by jayeshmangwani** [comment]
@DylanDylann I've resolved the ESLint errors in our PR related to the default string. Feel free to review the changes and share your feedback.

**Review by DylanDylann — APPROVED** [review]

**Comment by DylanDylann** [comment]
@jayeshmangwani All good. But we got conflict

**Comment by jayeshmangwani** [comment]
Thanks for review @DylanDylann 🙌 , I've merged the main and resolved the conflicts.

**Comment by DylanDylann** [comment]
@carlosmiceli All yours

**Review by carlosmiceli — APPROVED** [review]

**Comment by jayeshmangwani** [comment]
**Note:** QA won't be able to test this feature yet, as it's still ongoing. We need to implement the downgrade API before it's ready for testing.

**Pull request merged**
