### PR TITLE
[No QA] DRY up menu item styles

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Cleaning up and DRYing some reusable styles between the `ReportActionContextMenu` and other menu components.

### Fixed Issues
No issue, just cleanup.

### Tests
Test all the popover / create menus we have for regressions (and buttons should have different styles when hovered or pressed):

1) `ReportActionContextMenu`
2) global create menu
3) Video chat popover menu
4) Settings menu

### QA Steps
QA will be covered by regular regression testing.

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

#### Web
image

image

image

#### iOS
image

image

image

### CODE REVIEW

**Comment by shawnborton** [comment]
For this menu here:
image

I wonder if it should actually use the same styles as other bottomDocked menus, like this one?
image

I see that the styles look more compact on desktop when you right-click, and that's where the compact bottomDocked styles are coming from... but maybe we don't need to make the right-click menu look compact? Basically I love the idea of trying to eliminate an extra menu style if we can.

**Comment by roryabraham** [comment]
Yeah, so we could reuse the `MenuItem` in the `ReportActionContextMenuItem`, and this is what that would look like @shawnborton:

<table>
    <tr>
        <th>Compact</th>
        <td></td>
    </tr>
    <tr>
        <th>Same as other popovers</th>
        <td></td>
    </tr>
</table>

I personally think that the non-compact version takes up too much real estate on the screen and doesn't look as good. What do you think? The "Same as other popovers" version would simplify and DRY up the code some more too (and give us parity one the `BottomDocked` modals too, so that's good.

**Comment by shawnborton** [comment]
I think the "same as other popovers" version looks great. It is such a small difference that I don't think it's worth having to maintain two different styles for compact versus normal.

**Comment by roryabraham** [comment]
Okay, I thought it looked just a bit too intense but if you think it looks good I'll make that change!

**Review by tgolen — APPROVED** [review]

**Comment by marcaaron** [comment]
Gonna unassign myself from this one so I can focus on some other stuff and not sure it needs an extra review from me :)

**Comment by roryabraham** [comment]
Cool, going to :shipit: then

**Pull request merged**
