### PR TITLE
Add error to login input

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
Fixes how we display errors on the login form to align with other forms within the App, i.e.:

1. Separates input specific errors from server errors
2. Adds red bottom border to inputs with form validation error (server error still results in a green border)

### Fixed Issues
$ https://github.com/Expensify/App/issues/14622

### Tests
Pre-requisite: an account with 2FA enabled

**Email**
1. Navigate to the login page
3. Tap on continue without entering any value for email or phone number
4. Verify that you see the `Please enter an email or phone number` error and the input border is red
5. Enter a random text, i.e. `a`
6. Verify that the error is cleared
7. Tap `Continue`
8. Verify that you see the `The email entered is invalid. Please fix the format and try again.` error and the input border is red
9. Enter a fake phone number, i.e. `1234`
10. Verify that the error is cleared
11. Tap `Continue`
12. Verify that you see the `I couldn't validate the phone number, please try again with the country code (e.g. +15005550006).` error and that the input border is GREEN (this is a server error)
13. Enter your account email and tap `Continue`

**Password**
1. Verify that you see the password input
2. Tap `Sign in`
3. Verify that you see the `Please enter your password` error and the input border is red
4. Enter a random text, i.e. `a`
5. Verify that the error is cleared
6. Tap `Sign in`
7. Verify that you see the `Incorrect password. Please try again.` error and the input border is red
8. Enter a password that satisfies the requirements, i.e. `Password1`
9. Tap `Sign in`
10. Verify that you see the `Incorrect login or password. Please try again or reset your password.` error and that the input border is GREEN (this is a server error)
11. Enter your password
12. Tap `Sign in`

**2FA**
1. Verify that you see the 2FA input
2. Tap `Sign in`
3. Verify that you see the `Please enter your two factor code` error and the input border is red
4. Enter a random text, i.e. `1`
5. Verify that the error is cleared
6. Tap `Sign in`
7. Verify that you see the `Incorrect two factor authentication code. Please try again.` error and the input border is red
8. Enter a 2FA code that satisfies the requirements, i.e. `123456`
9. Verify that the form is automatically submitted
10. Verify that you see the `Incorrect Two Factor Authentication code. Please try again.` error and that the input border is GREEN (this is a server error)
11. Enter the correct 2FA code
12. Tap `Sign in`
13. Verify that you can sign in

- [x] Verify that no errors appear in the JS console

### Offline tests
**Email**
1. Turn off your internet connection
2. Verify that you see the `You appear to be offline.` message below the button
3. Verify that the `Continue` button is disabled
4. Turn on your internet connection and enter your email
5. Tap `Continue`

**Password & 2FA**
1. Turn off your internet connection
2. Verify that you see the `You appear to be offline.` message below the button
3. Verify that the `Sign in` button is disabled

### QA Steps
Same as test and offline steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/22219519/215895511-2c5cea53-8294-48ce-a91d-7b310cd0f140.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/22219519/215895544-f6a3aa13-a263-4bdb-acd6-f691f607825a.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/22219519/215895553-47fe48ea-5c99-4271-88c5-3145fd6e3129.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/22219519/215895572-20243798-9b77-407d-be27-a9f2fe658e54.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/22219519/215895584-78b22e21-9d82-4ebb-b6ea-5a4beb11812e.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/22219519/215895595-70624d97-50c3-4730-a929-ce8d04c2107e.mov

</details>

### CODE REVIEW

**Comment by youssef-lr** [comment]
> server error still results in a green border

@luacmartins any reason why only form validation errors should show a red border?

**Comment by luacmartins** [comment]
The API doesn't return the specific input the error is related to, so right now server errors are shown as a form level error instead of individual input. They are also not translated like other input errors. This is consistent with other forms in the App, e.g. VBA forms.

**Comment by youssef-lr** [comment]
Got it. I think we can go with the fixes in this PR, but ultimately we would want to wrap these forms in `Form` for more consistency. `Form` also takes into account server side field-specific errors so it should work nicely. What do you think?

As for testing, I'm not sure why I'm not seeing a red border when entering an invalid email format:

Screenshot 2023-02-01 at 01 03 02

**Comment by youssef-lr** [comment]
Apologies disregard my last comment about testing, there was an issue with git I didn't have all the commits pulled.

Screenshot 2023-02-01 at 01 11 19

**Comment by luacmartins** [comment]
>Got it. I think we can go with the fixes in this PR, but ultimately we would want to wrap these forms in Form for more consistency. Form also takes into account server side field-specific errors so it should work nicely. What do you think?

That was my first instinct and I tried to convert this to use Form, until I realized that this form has a couple of features that we don't support in Form:

1.  auto-submit the form when entering a 6-digit 2FA code
2. This dark magic ([here](https://github.com/Expensify/App/blob/60b9d02cab9511b21da32ab2bc9e3ccc47f2be2e/src/pages/signin/SignInPage.js#L80-L81) and [here](https://github.com/Expensify/App/blob/60b9d02cab9511b21da32ab2bc9e3ccc47f2be2e/src/pages/signin/LoginForm.js#L199-L200)) to keep both `LoginForm` and `PasswordForm` mounted, but visibly hidden

**Comment by youssef-lr** [comment]
Haha I see. I guess we can live with just a couple of forms that aren't using `Form`.

**Review by youssef-lr — DISMISSED** [review]
LGTM and tested well!

**Comment by luacmartins** [comment]
@aimane-chnaif I think those make sense for the login forms and is still the same behavior we have on staging/prod.

**Comment by luacmartins** [comment]
Sure, let me look into that

**Comment by luacmartins** [comment]
Updated!

**Review by aimane-chnaif — APPROVED** [review]

**Comment by luacmartins** [comment]
@youssef-lr could you please re-review/approve this?

**Review by youssef-lr — APPROVED** [review]

**Comment by mananjadhav** [comment]
I am tagging this PR to highlight an issue fixed [here](https://github.com/Expensify/App/issues/16683). All conditions in ternary expressions or left-hand operands on conditional renders, should be boolean. This PR is one of the PRs that uses conditional render with string operands, hence I am tagging it here for the contributors to check. 

We've also updated the item in the checklist with this [PR](https://github.com/Expensify/App/pull/18069) to avoid this issue in the future.

**Pull request merged**
