### PR TITLE
Fix Investigate App Crash MainActivity.onCreate

### PR DESCRIPTION
**Pull request by yoyumiracle**
I fixed the bug related on crash log.

### Fixed Issues

$ #35655
PROPOSAL: https://github.com/Expensify/App/issues/35655#issuecomment-1932592472

### Offline tests

N/A

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
It doesn't need any Screenshot/Videos.

### CODE REVIEW

**Comment by danieldoglas** [comment]
Assigning @akinwale as the reviewer since he was the one who approved the proposal.

**Comment by yoyumiracle** [comment]
@akinwale It pasted 4 days. Is there any problem to approve this PR?

**Comment by akinwale** [comment]
> @akinwale It pasted 4 days. Is there any problem to approve this PR?

I am trying to test the solution. I will have an update by tomorrow.

**Comment by akinwale** [comment]
I created an adhoc release build locally, and tried to test on browserstack, but a OnePlus 8 Pro running Android v11 is not available, so I tested on the closest possible configurations:
* OnePlus 8 running Android 10
* OnePlus 9 running Android 11

The app doesn't seem to be crashing on launch with the changes applied.

**Comment by akinwale** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/4160319/7ba0b32b-5247-4721-ac1e-752a69e00eef

</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by akinwale — APPROVED** [review]
LGTM.

**Comment by akinwale** [comment]
> > I created an adhoc release build locally, and tried to test on browserstack, but a OnePlus 8 Pro running Android v11 is not available, so I tested on the closest possible configurations:
> > 
> > * OnePlus 8 running Android 10
> > * OnePlus 9 running Android 11
> > 
> > The release build does not crash on launch with the changes applied.
> 
> Sorry for chiming in. Did you get crash on release build before this PR?

I don't have the exact build to test this with.

**Comment by akinwale** [comment]
For reference, here are the available OnePlus devices on browserstack for testing.

Screenshot 2024-02-18 at 17 05 29

**Comment by danieldoglas** [comment]
Not sure why the automatic flow is not working here, assigning @marcaaron since he was part of the original issue

**Comment by mountiny** [comment]
@akinwale did you also test the `main` on those devices to see if that crashes?

**Comment by akinwale** [comment]
> @akinwale did you also test the `main` on those devices to see if that crash

@mountiny I just tested building on latest `main` and the crash is not happening.

https://github.com/Expensify/App/assets/4160319/60ec20c8-46f5-4278-927a-4cff95904581

**Comment by mountiny** [comment]
@akinwale It seems like we can still see this crash happening but it seems specific to that one device 
image

**Comment by yoyumiracle** [comment]
> @akinwale It seems like we can still see this crash happening but it seems specific to that one device

If then I think we can use 'com.facebook.soloader:soloader:0.11.0+' or 'com.facebook.soloader:soloader:0.10.5+' instead of 'com.facebook.soloader:soloader:0.10.4+'.

**Comment by mountiny** [comment]
Asked QA to see if they have this device to test with https://expensify.slack.com/archives/C9YU7BX5M/p1708380774682179?thread_ts=1708378569.586009&cid=C9YU7BX5M

**Comment by mountiny** [comment]
Still no luck I believe

**Comment by yoyumiracle** [comment]
@mountiny Sorry for asking like this. Was I hired in Upwork for this issue? I can't see any order on my upwork account.
Then why I have to make pull request for it? Tell me exactly what's going on.

**Comment by mountiny** [comment]
> But some one was already hired on Upwork for this issue.
> Then why I have to make pull request for it? Tell me exactly what's going on.

It might be the C+ here who helps to test and review the PR @akinwale  who you see hired in Upwork

Do not worry you are hired too, however, we need a way to verify the crash and fix. At the moment, you did not include any videos of the app working as expected compared to main. To completely verify we have fixed this, we are looking for reproduction steps first @yoyumiracle can you also help with that?

**Comment by yoyumiracle** [comment]
> At the moment, you did not include any videos of the app working as expected compared to main. To completely verify we have fixed this, we are looking for reproduction steps first @yoyumiracle can you also help with that?

Hello @mountiny. Thanks for your kind answer. 
I regret to inform you that I won't be able to assist with this. I encountered a similar issue while developing an Android web app in the past. I resolved it using the method I suggested, but unfortunately, I don't have a real device to test for the issue now. I came across the issue on Upwork and offered my expertise based on previous experience. 
Where the crash image come from? Can't you test it on that situation? I'm sorry for not being able to provide direct assistance. I wish you the best of luck in resolving the problem.

**Comment by mvtglobally** [comment]
Can anyone suggest at least the area where the crash is happening? 
Is it on Expenses? Around Workspace creation or settings? 
Any pointers would be really helpful for QA team to repro this issue

**Comment by akinwale** [comment]
> Can anyone suggest at least the area where the crash is happening? Is it on Expenses? Around Workspace creation or settings? Any pointers would be really helpful for QA team to repro this issue

The crash log indicates that it crashes on launch, i.e. immediately a user tries to open the app from the app drawer.

**Comment by yoyumiracle** [comment]
@akinwale How is it going? Is there any probable to approve this PR? I'm tired to wait for result.

**Comment by akinwale** [comment]
@yoyumiracle Based on https://github.com/Expensify/App/pull/36465#issuecomment-1955593783, we're still waiting to be able to test on a OnePlus 8 Pro specifically.

**Comment by marcaaron** [comment]
I'm guessing this is still holding on testing? Can we do anything to move it forward? What are we blocked on? Thanks!

**Comment by yoyumiracle** [comment]
Does it move forward? I can't believe this situation.

**Comment by yoyumiracle** [comment]
@marcaaron Hello.
I understand the situation, but does anyone care for it?
If this PR is not necessary, I'll close it.
It would be good for me and you.
I feel like I'm being made fun of and even then my upwork account was closed.
Please reply to it as soon as possible.
Thanks.

**Comment by marcaaron** [comment]
@yoyumiracleI will ask QA to look into this. I can assure you that nobody is making fun of you. We are a busy company and things get lost in translation at times. Thanks for your patience.

**Comment by marcaaron** [comment]
QA results are that no crash was found. @yoyumiracle there is a `package-lock.json` change though that looks like it should not be there and the PR has conflicts. Additionally you are not using signed commits.

**Comment by yoyumiracle** [comment]
Hi @marcaaron.
Thanks for your kindness.
However, the Conflict Resolution button is disabled.
Could you please tell me how to solve this problem and the signed commit style? Or where can I find it?
I have one more problem. As I mentioned, unfortunately my Upwork account is blocked. Could I use my friend's account to receive offer?
Best Regard.

**Pull request closed without merging**
