### PR TITLE
Hide validate code form immediately when account is cleared

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

We want to hide the magic code validate form as soon as the account data is cleared.

### Fixed Issues

$ https://github.com/Expensify/App/issues/21147
PROPOSAL: https://github.com/Expensify/App/issues/21147#issuecomment-1600498246

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Requires internet connection

### QA Steps

Prerequisites: setup an authenticator
1. Sign out if you are signed in
2. Enter your email and press Continue
3. Enter the magic code from the email
4. Verify you are brought to the authenticator input page
5. Scroll to the bottom of the Footer
6. Press Login
7. Verify you are scrolled to the top and brought to the login input page
8. Verify there is no error shown below the login input

Additional tests to make sure sign-in/up functionality still works well.

- Sign up for NewDot with a new account.
- Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.
- Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.
- Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.
- Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/50919443/d7903492-c5c7-40c1-890a-ba0be1b7bcca

Sign up for NewDot with a new account.

https://github.com/Expensify/App/assets/50919443/6288499b-f9f9-4960-871a-4dc31d658784

Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/511b2f7e-ef5b-4715-9701-5540233421d2

Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.

https://github.com/Expensify/App/assets/50919443/7c9bd129-bcf4-4978-b2bf-28159d8be00b

Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/dfc5241d-90fd-46db-9f69-75d925163913

Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

https://github.com/Expensify/App/assets/50919443/1562773c-bf95-4a1e-a22a-be3e481dd576

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/50919443/3de5c84a-1cf3-4091-8384-e9e7482fd1b5

Sign up for NewDot with a new account.

https://github.com/Expensify/App/assets/50919443/9dc07985-81fd-4ab4-a58d-e704e38d6408

Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/044f01e9-811c-4bc6-993f-672cf782e065

Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.

https://github.com/Expensify/App/assets/50919443/bee68a57-d68d-4232-8ccf-69040b4271d6

Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/b621c4ff-0d7b-430c-a9c3-291e34a948d7

Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

https://github.com/Expensify/App/assets/50919443/a4d52946-c519-4dfb-9c54-09d11a2dc939

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/50919443/77ef6b2c-69c2-4b04-a989-1f7eb0e9488d

Sign up for NewDot with a new account.

https://github.com/Expensify/App/assets/50919443/7fc76f79-2fb1-43c4-9108-13f2de56f7ad

Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/2bc6e222-706d-4fa9-b512-3c5bd62c474a

Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.

https://github.com/Expensify/App/assets/50919443/2e0895ae-10d2-4d13-bb15-89243f683a95

Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/25110fa7-dac4-4e3c-adda-9063a8ac4070

Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

https://github.com/Expensify/App/assets/50919443/4737ecf4-1ea6-4303-bd9f-af743eb8f5b4

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/50919443/8077c376-9605-4ac4-a2c9-d0b97c27cbd7

Sign up for NewDot with a new account.

https://github.com/Expensify/App/assets/50919443/2295e950-d2ca-4162-b633-c25ef6184d35

Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/3433be61-5923-419f-9e04-a00882af94eb

Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.

Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/a2c5b665-91dd-49f5-8778-04d308382943

Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/50919443/8e44fb11-c7b8-4eaa-bfa0-cb7d39f341ac

Sign up for NewDot with a new account.

https://github.com/Expensify/App/assets/50919443/a1467f1f-9d86-46c4-aef9-0155d28e31d2

Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/2ba4c2d9-0e8f-461e-bccf-944bb68dd5c8

Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.

Not applicable.

Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/4524d86c-f009-4bb4-90f0-805a79f1ab5e

Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

Not applicable.

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/50919443/cb6da88c-a964-4bfd-9250-a2dbad6e1272

Sign up for NewDot with a new account.

https://github.com/Expensify/App/assets/50919443/adc2899c-230e-4185-9632-b256d1b3de29

Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/04e6d5c0-882a-4a49-997e-7839c5744815

Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.

Not applicable.

Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.

https://github.com/Expensify/App/assets/50919443/70d0a2ec-ff34-47b5-b379-249f9c0ea79d

Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

Not applicable.

</details>

### CODE REVIEW

**Review by sobitneupane — COMMENTED** [review]
@bernhardoj Can you please add followings also in QA steps.

- Sign up for NewDot with a new account.
- Sign in to NewDot with an account that does not require 2FA by copy/pasting the magic code.
- Sign in to NewDot with an account that does not require 2FA by clicking on the magic code.
- Sign in to NewDot with an account that requires 2FA by copy/pasting the magic code.
- Sign in to NewDot with an account that requires 2FA by clicking on the magic code.

We should also verify all above tests pass.

**Comment by sobitneupane** [comment]
@bernhardoj I believe we should test it on all platforms as user won't be able to use app if anything breaks. It is quite critical change.

**Comment by sobitneupane** [comment]
> The issue caused by a Desktop app is open. Closing it solves the issue.


@bernhardoj Can you please link the issue. I am not sure if I understane.

>I have a question. How do we test this by clicking on the magic code. on other platforms except web? It's not working for me (auto logging in).

@bernhardoj Can you test it in non-incognito (especially in Safari).

**Comment by sobitneupane** [comment]
@bernhardoj You need to copy the magic link and replace the initial part of url with your local host or ip. 

> The issue caused by a Desktop app is open. Closing it solves the issue.

So, is this issue reproducible on staging as well?

**Comment by sobitneupane** [comment]
>  Oh, I just realized I didn't change the domain when testing for desktop. I replaced it with localhost and it shows the abracadabra page now, but my desktop app still shows the login page (happens on main too)

When opening the link(with localhost) does it suggest to open on desktop? If it does, let's try opening it in desktop.

**Comment by sobitneupane** [comment]
> I wonder if this happens on native too because there is no way the web can communicate with the app? Haven't tested it yet because I reached max. request of magic code

We can skip the magic link part (test) because a user has no way to open the magiclink in native app.

**Comment by sobitneupane** [comment]
> Yes, it does, but I get redirected to this app instead.

bit strange

@bernhardoj Was your local desktop app open? Is it reproducible on main? Does same thing happen when you try to open other links?

**Review by sobitneupane — COMMENTED** [review]
### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/25876548/e3d0c219-4d17-4bcb-aa12-877460f403eb

https://github.com/Expensify/App/assets/25876548/920b3993-278c-4e89-b87c-83b76d880138

</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/25876548/67b8f7af-83f3-4c6b-a119-3ad987f65ed7

https://github.com/Expensify/App/assets/25876548/6da76f05-7641-4f39-bb6e-5c137b42495f

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/25876548/43559c5e-c73b-4ffc-9787-aac1abb3effd

https://github.com/Expensify/App/assets/25876548/6b87b07a-31b3-477c-826e-fb2381de19b6

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/25876548/e25b5e06-fc50-4501-96c4-62c8ff42a078

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/25876548/03f27509-8b06-4a65-8a59-e08789058030

</details>

**Review by sobitneupane — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

**Review by jasperhuangg — APPROVED** [review]

**Pull request merged**
