### PR TITLE
[InternalQA] Update the isExpensifyEmployee job

### PR DESCRIPTION
**Pull request by mountiny**
### Details

In [this PR](https://github.com/Expensify/App/pull/7672) the QA has shown the job has not worked as expected.

I have looked further into it to see what might cause a problem and I have noticed that our uses or the `get-user-teams-membership` action are wrapping the output in `fromJSON`, which the official action documentation does not, but I assume that is how we treat the variables being passed through actions/workflows.

See for example here:
https://github.com/Expensify/App/blob/fac61c6c5856340f4bbb9f7298a86eaac0411756/.github/workflows/cherryPick.yml#L18

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/194440

### Tests

- [x] Verify that no errors appear in the JS console

I am not sure how these can be easily tested locally. I will ask if there is a way that does not involve recreating the entire structure of Organization, a couple of fake accounts as members, personal repository etc.

### QA Steps

I will keep an eye on QAing this.

- [x] Verify that no errors appear in the JS console

- [ ] Make sure that first time contributors who are external still get the comment
- [ ] Make sure that internal contributors do not get this comment on merge. The easiest would be to wait for @PauloGasparSv to make his first PR to App (or just create dummy one once this PR is deployed) and see if the comment appears

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]

**Comment by botify** [comment]
@roryabraham looks like this was merged without passing tests. Please add a note explaining why this was done and remove the `Emergency` label if this is not an emergency.

**Comment by roryabraham** [comment]
Not an emergency – GHA not related to E2E tests https://github.com/Expensify/App/runs/5206066746?check_suite_focus=true

**Comment by roryabraham** [comment]
@mountiny This still did not seem to work: https://github.com/Expensify/App/runs/5206066746?check_suite_focus=true

**Comment by mountiny** [comment]
@roryabraham I am getting a bit paranoid I guess 😄 Now it is literally the same as for example this `validateActor` job:
https://github.com/Expensify/App/blob/27afd80457f4b77f59a2b118df70b99281cea8b6/.github/workflows/platformDeploy.yml#L15-L31

Could it be the same name of the output variable and the job name causing some weird problem? That seems unlikely to me.

**Review by Luke9389 — COMMENTED** [review]
This is cool. Didn't know about fromJSON

**Comment by mountiny** [comment]
@Luke9389 I have checked the QA on the deploy list off. For some reason, it did not work as expected, but it is not a blocker. I am going to try again in the coming days. It is really baffling me, why it did not work.

**Pull request merged**
