### PR TITLE
Share Code URL implementation using Environment URL

### PR DESCRIPTION
**Pull request by rojiphil**
@mananjadhav @alex-mechler @kevinksullivan @AndrewGable

### Details
The following changes can be done to incorporate the functionality in a common place:
a) Leverage the existing `WithEnvironment` component and add support for `environmentURL`. This variable will contain the environment-specific URL from `Environment`.
b) Use the `environmentURL` from `WithEnvironment` to decide on the URL for use with `Share code` functionality. Also, ensure that a trailing slash is present in the environment url.

### Fixed Issues
$ https://github.com/Expensify/App/issues/19464
PROPOSAL: https://github.com/Expensify/App/issues/19464#issuecomment-1565190797

### Tests

1. Android Native

Prerequisite: 
Find out the latest production version at https://api.github.com/repos/expensify/app/releases/latest.
Tag_name will represent the latest deployed production version
"tag_name": "1.3.27-7",
Here, the latest deployed production version is 1.3.27-7

i) Staging: 
Build an android app that uses a production environment configuration file with package version of 1.3.27-8 
"version": "1.3.27-8", (i.e. in package.json)
Follow the steps as below:
a) Verify version in Settings->About
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://staging.new.expensify.com/

ii) Production: 
Build an android app that uses production environment configuration file with package version of 1.3.27-7 
"version": "1.3.27-7", (i.e. in package.json)
Follow the steps below:
a) Verify version in Settings->About
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://new.expensify.com/

iii) Development:
Follow the steps as below:
a) Verify 'dev' label next to `Expensify` in header.
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://localhost:8080/

2. mWeb-Android-Chrome/web: 

i) Development Version:
a) Launch the expensify app at http://localhost:8080/
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://localhost:8080/

3. MacOS-Desktop:

i) Production Version:
a) Launch the electron production App 
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://new.expensify.com/

ii) Staging Version:
a) Launch the electron staging App 
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://staging.new.expensify.com/

4. iOS-Native-Simulator:

i) Production Environment:
a) Launch the production iOS Native app
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://new.expensify.com/

5. Safari-Dev
i) MacOS/iOS-Safari
a) Launch the dev version on Safari in MacOS
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://localhost:8080/

- [x] Verify that no errors appear in the JS console

### Offline tests

i) Android-Native Production Version:
a) Ensure mobile is offline (Disconnect from WiFi and Mobile Data)
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://new.expensify.com/

### QA Steps

Following additional test steps are required:
1. Web
i) Staging Deployment: 
a) Launch the expensify app at https://staging.new.expensify.com/
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://staging.new.expensify.com/

ii) Production Deployment: 
a) Launch the expensify app at https://new.expensify.com/
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://new.expensify.com/

2. iOS Native App:

i) Staging: 
a) Setup TestFlight for iOS and launch app
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://staging.new.expensify.com/

ii) Production:
a) Install production version from iOS App Store and launch app.
b) Copy URL to keyboard in Settings->Share code
c) Paste it in the compose box of one of the existing chat
d) Verify that the URL starts with https://new.expensify.com/

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android-Native-Staging (1->i)</summary>

https://github.com/Expensify/App/assets/3004659/d5041aa3-f267-413c-b1d9-ebdf37109a13

</details>

<details>
<summary>Android-Native-Production (1->ii)</summary>

https://github.com/Expensify/App/assets/3004659/c7c8b133-d8e8-49da-ae35-ce0cc25be558

</details>

<details>
<summary>mWeb-Chrome-Development Version (2->i)</summary>

https://github.com/Expensify/App/assets/3004659/56db406a-3910-4792-87cb-7095e5cad1e8

</details>

<details>
<summary>MacOS / Desktop Production </summary>

https://github.com/Expensify/App/assets/3004659/4e677be3-eacc-4b15-aed1-1963aae854e9

</details>

<details>
<summary> MacOS / Safari -Dev </summary>

https://github.com/Expensify/App/assets/3004659/b2447492-8720-48c3-b8e1-77d5fdba74f3

</details>

<details>
<summary> iOS / Native - Simulator - Production </summary>

https://github.com/Expensify/App/assets/3004659/b97673bf-aa20-46d0-84d9-c9014fb47c86

</details>

<details>
<summary>MacOS / Desktop Staging </summary>

https://github.com/Expensify/App/assets/3004659/ab8506cc-558a-4991-97ab-1a4eda3b1c20

</details>

<details>
<summary> Offline - Android Native Prod </summary>

https://github.com/Expensify/App/assets/3004659/bdbb27b5-35d9-4d92-8941-ccd3181404b8

</details>

### CODE REVIEW

**Comment by rojiphil** [comment]
@mananjadhav Were you able to review and test the changes? Let me know if this is fine to merge. Or if any changes are required, will be glad to update.

**Comment by rojiphil** [comment]
@alex-mechler. I hope you are back today. Can you please add roji+test5@owesee.com and roji@owesee.com to the high traffic account?

**Comment by rojiphil** [comment]
@mananjadhav, @alex-mechler, Friendly bump on review and next steps.

**Comment by alex-mechler** [comment]
Added [roji+test5@owesee.com](mailto:roji+test5@owesee.com) and [roji@owesee.com](mailto:roji@owesee.com) as high traffic accounts

**Review by mananjadhav — APPROVED** [review]
The code looks good, I am done testing it on 3 platforms. I'll finish this in next 10 mins.

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/3069065/86f3c2fd-8147-4103-beb8-93cce55aa2c4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/3069065/86c31221-55cb-4bae-931a-f49e7579931c

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/3069065/e86f287e-ed6b-475c-9cde-e0612b8cef23

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/3069065/69c64cd8-0bae-484c-84a6-6d02b36d04e8

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/3069065/b8942c9c-e085-493e-99ce-2fa899e9d41f

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/3069065/358e05cc-eaa4-4ace-8c28-d9f23a46b4db

</details>

**Comment by mananjadhav** [comment]
@alex-mechler all yours, I checked the URL by copying values from `.env.staging` to `.env` and it shows the correct value.

**Comment by rojiphil** [comment]
@mananjadhav @alex-mechler The lint issue due to prettier has been fixed. Also, I have done testing with the high-traffic account and have updated the checklist too with all checks. Kindly review and approve.

**Review by mananjadhav — APPROVED** [review]

**Comment by rojiphil** [comment]
> We did not find an internal engineer to review this PR, trying to assign a random engineer to #19464... Please reach out for help on Slack if no one gets assigned!

@mananjadhav  @MelvinBot  AFAIK, @alex-mechler  was supposed to review this as an internal engineer. Or is there any change?

**Review by flodnv — APPROVED** [review]

**Pull request merged**
