### PR TITLE
Added spacing between Routing & Account Number

### PR DESCRIPTION
**Pull request by Santhosh-Sellavel**
@puneetlath 

### Details
Just added a space between the` Routing Number` & `Account Number` input in Add Bank Account Step.

### Fixed Issues
$ #4834 

### Tests & QA Steps
1. Add account to free plan beta
2. Go to new.expensify.com
3. Create a workspace
4. Select Get Started in Expensify Card tab of the workspace
5. Choose the "Connect Manually" option

Fix:
Ensure space is added between `Routing Number` & `Account Number` input.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screenshot 2021-09-01 at 10 54 30 PM

#### Mobile Web

Simulator Screen Shot - iPhone 12 - 2021-09-01 at 22 55 59

#### Desktop

Screenshot 2021-09-01 at 10 54 05 PM

#### iOS

Simulator Screen Shot - iPhone 12 - 2021-09-01 at 22 57 16

#### Android

Screenshot_1630517457

### CODE REVIEW

**Comment by puneetlath** [comment]
@shawnborton would love your eyes on this form. There seems to be a mix of mb5, mt5, and mt4 in this form. It _looks_ fine to me after @Santhosh-Sellavel's changes, but would love for a second pair of eyes before merging.

**Comment by Santhosh-Sellavel** [comment]
@puneetlath
@shawnborton might be OOO until Sep 7. Can we wait until then or can we loop someone else?

**Review by puneetlath — APPROVED** [review]

**Comment by puneetlath** [comment]
Good point. It looks good to me and @michelle-thompson. So I'm going to go ahead and merge it. 

@shawnborton if you want to clean up these form styles at all when you're back, we can open a new issue.

**Comment by shawnborton** [comment]
Sounds good, but I trust you and Michelle so if it works for you all, it
works for me!

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-10.  :confetti_ball:

**Pull request merged**
