### PR TITLE
Use DOM activeElement instead of event target in composer focus logic

### PR DESCRIPTION
**Pull request by PauloGasparSv**
cc @tienifr @rushatgabhane  @getusha @situchan 

### Details
Fixes another regression caused by https://github.com/Expensify/App/issues/16098 where typing in the EmojiPicker searchbox also adds the input to the Composer.

We caught that problem early on [for the chat's main emoji picker](https://github.com/Expensify/App/pull/17138#issuecomment-1503609217) but not for the individual messages Emoji Picker.

image

### Fixed Issues
$ https://github.com/Expensify/App/issues/17413
PROPOSAL: GH_LINK_ISSUE(COMMENT)

#### For Web and Desktop:

1. Open a newDot chat that has some messages
2. Click on any of the messages
3. Press any character keys like a,b,c,d (not non-character keys like Enter, Shift)
4. Verify that the composer is focused again and the above character is entered in the composer
5. Try to Edit a message and make sure no characters are inputed to the composer
6. Open the Search in LNH and click on the search box/input (so it blurs the composer input)
7. Press any character keys like a,b,c,d (not non-character keys like Enter, Shift)
8. Verify that these characters aren't entered in the main composer
9. Go back to the chat and open the Emoji Picker
10. Press any character keys like a,b,c,d (not non-character keys like Enter, Shift)
11. Verify that these characters aren't entered in the main composer
12. Choose a message in the chat and click on "Add a Reaction"
13. Press any character keys like a,b,c,d (not non-character keys like Enter, Shift)
14. Verify that these characters aren't entered in the main composer

#### For mWeb (both), iOS and Android
1. Open a newDot chat that has some messages
2. Send some messages
3. Edit some messages and make sure no text is sent to the composer

- [ ] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
Same as tests

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/6564265/231912583-aac14438-fc67-400d-8dff-e55acb8b6524.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/6564265/231913572-49ce213c-92e0-47e5-afe6-09190d5a10c4.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/6564265/231918272-65a7d81d-b62b-49de-9d03-3f6a0b211e85.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/6564265/231913298-d9740b18-4312-4d8f-9346-c82ee9b84bde.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/6564265/231920733-fb8313c7-bd17-4a53-b411-e0819924fa2d.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/6564265/231913118-37df5f48-5387-461a-984c-1238d6dca8c5.mov

</details>

### CODE REVIEW

**Comment by PauloGasparSv** [comment]
Still adding iOS native and iOS mWeb evidences (having some simulator problems) but in the meantime this is ready for reviews

**Comment by PauloGasparSv** [comment]
Still pod installing stuff here to test iOS and iOS mWeb

I'd appreciate if someone else managed to run and test those 2 platforms.

**Comment by PauloGasparSv** [comment]
Added the final iOS native evidence! Thks for helping @rushatgabhane.

I'm clocking off here but I'll stay alert for any emails/messages if something needs my help!

**Review by rushatgabhane — APPROVED** [review]

**Comment by PauloGasparSv** [comment]
> @rushatgabhane @PauloGasparSv should we also handle this?

I think we should because Whatsapp and Slack doesn't behave like that when a message "reaction popup/popover" is opened.
Will take a look at that in a bit!

We may also have to include a fix for [this too](https://github.com/Expensify/App/issues/16098#issuecomment-1509004414).
https://user-images.githubusercontent.com/14358475/232117268-650f1c70-37e5-470b-9227-0ce1250cdf74.mov

cc @tienifr @rushatgabhane @getusha @situchan

**Comment by PauloGasparSv** [comment]
> 
> @PauloGasparSv also we should handle the space key
> 
> https://expensify.slack.com/archives/C049HHMV9SM/p1681466514310619
> 
> if the key is space we should also return early check slack.

There are some many regressions being caused by these changes, I think we should sadly close this and revert the whole P.R.

**Comment by PauloGasparSv** [comment]
Closing this in favor of https://github.com/Expensify/App/pull/17475

**Pull request closed without merging**
