### PR TITLE
Fix/37303 New message line persists if message is marked as read from LHN

### PR DESCRIPTION
**Pull request by Victor-Nyagudi**
### Details

If, on smaller devices, you marked a message as unread, navigated back to the LHN, and then marked its chat as read from the LHN, the unread marker persisted regardless of how many times you opened the chat already marked as read. 

This change adds a check for if the report is unread, which lets us access the code removing the unread marker in the scenario the chat is marked as read from the LHN.

### Fixed Issues

$ https://github.com/Expensify/App/issues/37303
$ https://github.com/Expensify/App/issues/37303#issuecomment-1974767396

### Tests

1. Open a chat report and mark a message as unread. This can be a message with just text, an attachment, or money request preview. 
2. Navigate back to the LHN and mark the same chat as read i.e. by long pressing it then selecting 'Mark as read' from the modal. 
3. Open the chat and verify there's no green unread marker. 
4. Mark another message in the chat as unread and then navigate back to the LHN. 
5. Open the same chat and verify the green unread marker is shown. 
6. Navigate back to the LHN and open the same chat again. 
7. Verify the green unread marker is not shown. 

- [x] Verify that no errors appear in the JS console

### Offline tests

Turn off your internet connection and repeat the steps in 'Tests' above. 

### QA Steps

Same as the steps in 'Tests' above. 

Repeat steps 1 to 7 in a workspace chat, task thread, reply thread, money request thread, room chat, or any other place a message can be marked unread and then accessed from the LHN. 

**Additional steps**

1. Log into another account as User B. 
2. While on the LHN as User A, send a message from User B to User A. 
3. Mark the chat with the message you just received from User B as read and then open the chat. 
4. Verify there's no green unread marker. 

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/79470910/883c54fb-e8b9-4606-9f03-300b234fd736

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/79470910/7cf70a98-be27-47b2-a6d6-4a5093fed4a3

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/79470910/11969ed0-3106-4c52-8b41-adf576f2cb68

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/79470910/556d7fba-9259-4e53-9f48-198d7ba5695a

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/79470910/7996ff5d-2d7a-4b13-a2c9-f3fe06398630

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/79470910/50d8577b-b844-4ead-afd9-52e2ee7cfa0b

</details>

### CODE REVIEW

**Comment by Victor-Nyagudi** [comment]
Reassure Performance Tests are passing locally for this branch, so I'm not sure what the issue is here.

**Comment by Victor-Nyagudi** [comment]
Bump @abdulrahuman5196 for a review so the PR doesn't get bloated with merge commits.

**Comment by abdulrahuman5196** [comment]
Hi, Where you able to check on the issues pointed out in the slack thread?

**Comment by Victor-Nyagudi** [comment]
Yes, I looked at the trhead. 

Still investigating the way forward, but [we'll first need some feedback](https://expensify.slack.com/archives/C01GTK53T8Q/p1711374411111259?thread_ts=1710863011.324649&cid=C01GTK53T8Q) from @MonilBhavsar on what the expected behavior is when someone sends you a message while the unread marker is showing. 

It currently disappears when someone sends you a message but remains when you are the one who sends a message.

**Comment by abdulrahuman5196** [comment]
@Victor-Nyagudi I checked the thread and its valid concern. The unread marker is not removed currently in staging. Even if the message was received from another user, then also we show the unread marker if we open the chat and send message in the same chat. Which is not happening in this case, where the unread marker is removed once we send a message.

Could you kindly fix the issue?


https://github.com/Expensify/App/assets/46707890/f6f267c7-5ee4-4fc2-87a1-fd07e1c38361

**Comment by Victor-Nyagudi** [comment]
@abdulrahuman5196 I'll be away for a few weeks, so I won't be able to give this issue the attention it deserves.

Kindly reassign.

**Comment by Victor-Nyagudi** [comment]
Closing this PR after getting [confirmation](https://github.com/Expensify/App/issues/37303#issuecomment-2045934785).

**Comment by Victor-Nyagudi** [comment]
Closing this PR after getting [confirmation](https://github.com/Expensify/App/issues/37303#issuecomment-2045934785).

**Pull request closed without merging**
