### PR TITLE
[No QA] Update readme for auto-update to work with latest changes

### PR DESCRIPTION
**Pull request by Jag96**
@roryabraham will you please review this?

### Details
This PR updates the steps to test auto-update on the desktop app.

### Fixed Issues
Related to https://github.com/Expensify/Expensify/issues/151959

### Tests
Run through the steps in https://github.com/Expensify/Expensify.cash/blob/joe-auto-update-readme/desktop/README.md, confirm everything works properly.

### QA
No QA

### CODE REVIEW

**Review by Beamanator — COMMENTED** [review]
Looks solid to me, but I definitely think rory (or someone with related experience) should confirm 😅

**Comment by Jag96** [comment]
Bump @roryabraham lmk if you need help testing

**Comment by roryabraham** [comment]
Okay, going to take a crack at this now

**Review by roryabraham — CHANGES_REQUESTED** [review]
We talked about some other clarifications 1:1 too

**Review by roryabraham — DISMISSED** [review]

**Comment by Jag96** [comment]
Updated!

**Review by roryabraham — APPROVED** [review]

**Pull request merged**
