### PR TITLE
[No QA] refactor close account onyx refactor frontend 2

### PR DESCRIPTION
**Pull request by srikarparsi**
### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/224886
PROPOSAL: GH_LINK_ISSUE(COMMENT)

### Tests

Adapted from https://github.com/Expensify/Web-Expensify/pull/34159

Related Web E PR for testing: https://github.com/Expensify/Web-Expensify/pull/35198

Setup:
1. Create a new account (you'll end up close it so it's probably easier if you start with a fresh account)
2. Set the NVP `private_amountOwed` to `100` (any integer is fine, really)
    - Run `./script/sql.sh` from the Expensidev directory
    - `SELECT email, accountID from accounts where email = '{The email you created to test closing an account}'`
    - `INSERT INTO nameValuePairs (accountID, name, value) VALUES (<accountID>, 'private_amountOwed', 100);`

### Dev Tests

1. In NewDot log in with the account you just created
2. Try to close the account via:
    - Profile -> Security -> Close account
    - Enter a message, then type your default contact method exactly
    - Click "Close account"
5. Verify you see the loading spinner on the "Close account" button while waiting
5. Verify you now see the "Unable to close account error modal"
    - Screen Shot 2022-06-30 at 4 21 43 PM

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Screen Shot 2022-12-26 at 9 11 16 AM

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screen Shot 2022-12-26 at 9 14 18 AM

</details>

<details>
<summary>Mobile Web - Safari</summary>

Screen Shot 2022-12-26 at 9 12 09 AM

</details>

<details>
<summary>Desktop</summary>

Screen Shot 2022-12-26 at 9 16 02 AM

</details>

<details>
<summary>iOS</summary>

I'm having some vm problems with ngrok since I'm on vacation on South Africa but when I originally tested this, it worked on all platforms.
</details>

<details>
<summary>Android</summary>

I'm having some vm problems with ngrok since I'm on vacation on South Africa but when I originally tested this, it worked on all platforms.
</details>

### CODE REVIEW

**Comment by thienlnam** [comment]
I would say this is pretty safe to merge, though let's have @Santhosh-Sellavel run through the platforms to make sure there are no console errors while closing an account

Just make sure to update your QA steps to include details on steps to close an account

**Review by neil-marcellini — COMMENTED** [review]
Let's run the tests that you listed in the Web-E PR. If you could please write them into the description here that would be great. We should test if closing an account shows the proper error message with and without the Web-E PR changes.

**Review by neil-marcellini — COMMENTED** [review]
The code looks good to me. Interestingly, when I tested with Web-E main I got a `<p>` tag in the error message. I also see that error when testing with your Web-E branch so we will need to fix that. Also, when I tested with your Web-E PR I got errors opening a report. Merging main will fix that.

https://user-images.githubusercontent.com/26260477/209212439-4d41ea49-11e3-46a3-8a15-55bfaeb0ac28.mov

**Comment by Santhosh-Sellavel** [comment]
Reviewing this now!

**Comment by Santhosh-Sellavel** [comment]
@srikarparsi or @neil-marcellini 

How to do this?

> Set the NVP private_amountOwed to 100 (any integer is fine, really)
INSERT INTO nameValuePairs (accountID, name, value) VALUES (<accountID>, 'private_amountOwed', 100);

**Comment by Santhosh-Sellavel** [comment]
> @srikarparsi or @neil-marcellini
> 
> How to do this?
> 
> > Set the NVP private_amountOwed to 100 (any integer is fine, really)
> > INSERT INTO nameValuePairs (accountID, name, value) VALUES (, 'private_amountOwed', 100);

@srikarparsi or @thienlnam or @neil-marcellini  Anyone help me with this!

**Comment by srikarparsi** [comment]
Hey @Santhosh-Sellavel, from the Expensidev directory you would run:

./script/sql.sh
SELECT email, accountID from accounts where email = '{The email you created to test closing an account}'
INSERT INTO nameValuePairs (accountID, name, value) VALUES ({The accountID you got in the previous step}, 'private_amountOwed', 100);

I'll add these steps into the description and l'm not too familiar with what C+'s have access to but let me know if you don't have access to the scripts.

**Comment by Santhosh-Sellavel** [comment]
@srikarparsi Yes I don't have access to this can anyone of you add the values for the email
`santhoshsellavel+tc0@gmail.com`

cc: @thienlnam @neil-marcellini

**Comment by neil-marcellini** [comment]
I couldn't come up with an easy test flow that will cause an error closing the account so I think it's probably best if we test this internally where we can set the NVP easily. We should also test with the backend changes. Sorry for not letting you know earlier @Santhosh-Sellavel.

**Comment by neil-marcellini** [comment]
@srikarparsi is going to get rid of the `<p>` tags sent by the backend and then I'll run through tests.

**Comment by srikarparsi** [comment]
thanks @neil-marcellini, I just added it back here: https://github.com/Expensify/Web-Expensify/pull/35198 and completed the author checklist but I took the screenshots yesterday so it still had the p tags.

**Comment by neil-marcellini** [comment]
Should we set this a [No QA] or should we try to come up with a way to QA it @srikarparsi @thienlnam?

**Review by neil-marcellini — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


With backend changes

https://user-images.githubusercontent.com/26260477/209743470-b3fbb2ea-74fc-41ae-8685-00cc80771591.mov

Without backend changes

https://user-images.githubusercontent.com/26260477/209743819-be3804a3-ba3d-4cd6-853f-2d142ef41062.mov


</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://user-images.githubusercontent.com/26260477/209743479-f5214989-0f56-4771-8916-5c272f89dd83.mov
</details>

<details>
<summary>Mobile Web - Safari</summary>



https://user-images.githubusercontent.com/26260477/209743506-3055f76c-8ca1-478c-b91e-38aeffcbe506.mp4


</details>

<details>
<summary>Desktop</summary>



https://user-images.githubusercontent.com/26260477/209743516-6d62ae84-732f-4d07-a65b-da3c2267dfd8.mov


</details>

<details>
<summary>iOS</summary>



https://user-images.githubusercontent.com/26260477/209743531-dbdb2824-b719-4d0d-84a8-8c7c4ef95ed2.mp4
</details>

<details>
<summary>Android</summary>




https://user-images.githubusercontent.com/26260477/209743563-4c4d9df9-d6c1-427f-a7d9-113d886177ab.mov


</details>

**Comment by neil-marcellini** [comment]
I looked into how we could test / QA this and I don't know of a straight forward way to set an amount owed on an account, so I made this [No QA] to get it merged. Jack is OOO so I won't wait for his review.

**Comment by Beamanator** [comment]
I'm noticing that the testing steps for this PR mention the "Unable to close account" error modal which I believe we completely removed in This PR: https://github.com/Expensify/App/pull/12534/files

FYI :D

**Pull request merged**
