### PR TITLE
Open modal to join screen share requests from GuidesPlus agents

### PR DESCRIPTION
**Pull request by francoisl**
cc @tjferriss 

### Details
- Listen to screen share invites sent by GuidesPlus agents. When joined, open OldDot in a new tab, where all the code to join screen shares already exists.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/184039

### Tests
Needs the Web-E PR https://github.com/Expensify/Web-Expensify/pull/32573. Tests steps 

### QA Steps
Regular staging QA: make sure there are no regressions in NewDot potentially introduced by this PR.

Internal QA (since it requires EW access - I can do this part myself):  follow QA steps from the Web-E PR.

### Tested On
- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### Screenshots
See the recording in https://github.com/Expensify/Web-Expensify/pull/32573 for the full flow

### CODE REVIEW

**Review by marcochavezf — CHANGES_REQUESTED** [review]

**Comment by francoisl** [comment]
Updated, thanks.

I'm seeing a warning for the propTypes in the console that makes 0 sense when I receive the push notification:

```
Failed prop type: Invalid prop `screenShareRequest.accessToken` of type `string` supplied to `Expensify`, expected `object`.
```
image

`screenShareRequest.accessToken` is expected to be a string according to the code, not an object. Also, a string is supplied. Do you happen to have any idea? Kinda stumped on this one.

**Comment by marcochavezf** [comment]
> Updated, thanks.
> 
> I'm seeing a warning for the propTypes in the console that makes 0 sense when I receive the push notification:
> 
> ```
> Failed prop type: Invalid prop `screenShareRequest.accessToken` of type `string` supplied to `Expensify`, expected `object`.
> ```
> 
> image
> 
> `screenShareRequest.accessToken` is expected to be a string according to the code, not an object. Also, a string is supplied. Do you happen to have any idea? Kinda stumped on this one.

Ah we'll need to use only `PropTypes.shape`, something like:

```jsx
    screenShareRequest: PropTypes.shape({

        /** Access token required to join a screen share room, generated by the backend */
        accessToken: PropTypes.string,

        /** Name of the screen share room to join */
        roomName: PropTypes.string,
    }),
```

because `PropTypes.objectOf` is used when we don't know the name of the properties ahead of time, but in this case we already know `screenShareRequest` has only the properties `accessToken` and `roomName`. https://stackoverflow.com/questions/45764746/react-proptypes-objectof-vs-shape

**Comment by francoisl** [comment]
Oooh got it, thanks, that makes sense. The PR is updated, but still on hold.

**Comment by francoisl** [comment]
Ok this is ready to go, the PR it depended on is on production on Web-E now. I also fixed the conflict in this PR.

**Review by marcochavezf — APPROVED** [review]

**Comment by mvtglobally** [comment]
@francoisl, @marcochavezf  Can you please validate this internally as well and check off

**Comment by francoisl** [comment]
Tested just now with @leminhphong, worked like a charm!

**Pull request merged**
