### PR TITLE
No wrap style

### PR DESCRIPTION
**Pull request by chiragsalian**
### Fixed Issues
$ https://github.com/Expensify/App/issues/7321

### Tests / QA
Tested the same steps mentioned on https://github.com/Expensify/App/issues/7321 and confirmed the image has ellipses on mWeb.
image

- [ ] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

### CODE REVIEW

**Review by roryabraham — COMMENTED** [review]
LGTM but not explicitly approving because I haven't tested.

**Review by stitesExpensify — APPROVED** [review]
LGTM

**Comment by parasharrajat** [comment]
Hey, I am here. Sorry for the delay.

If you want it to look like the old way then we should use numberOfLines={2} then it will start clipping from second line.

**Comment by stitesExpensify** [comment]
Does it look different this way? I'm not seeing it

**Comment by chiragsalian** [comment]
I think the style change alone is fine for now. Plus i feel this keeps the UI consistent with mobile and web since i see a single line on them as well.

**Comment by parasharrajat** [comment]
Previously, HeaderView was used to wrap to two lines and then clipped with an ellipsis. You can see that on PROD.

**Comment by stitesExpensify** [comment]
Gotcha. Well since we only see one line on web, I think this is fine :+1:

**Pull request merged**
