### PR TITLE
fix: Inviting a secondary login to a workspace appears as Hidden in the members table

### PR DESCRIPTION
**Pull request by truph01**
### Fixed Issues

$ https://github.com/Expensify/App/issues/52517
PROPOSAL: https://github.com/Expensify/App/issues/52517#issuecomment-2475434496

### Tests

1. Invite two users to a workspace
2. Make sure one of the users you invite is a secondary login to an existing account.
3. Verify the user with a secondary login should only appear once in the table, and their primaryLogin should be displayed.
- [x] Verify that no errors appear in the JS console

### QA Steps

Same as tests

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/5bee34fd-3fc4-4a3a-8783-b20921976ec2

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/a8c80102-c38a-4647-93d5-19b010bca070

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/c33615d9-731d-4af8-aafb-56f34cca3ce2

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/89ec0db3-ed91-4057-8715-8a63c44e9aee
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/94153798-654d-40b1-a2f0-3912ec8c7cae

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/4ae14139-e3ed-4db5-bd1e-bed527532fa0

</details>

### CODE REVIEW

**Comment by truph01** [comment]
> The secondary account appears in the members list for sometime, can't we fix that @truph01 ?

This bug occurs when a user tries to invite both the primary and secondary emails, correct? I don't think we can fix it because the frontend cannot determine if an email is a secondary contact method for another account.

**Comment by NikkiWines** [comment]
We shouldn't be displaying both - since they're same user and it's an odd UI experience to show them as two distinct options. Ideally, I think we should only show the current primary login. 

See the issue's `expected result`: 

> The user with a secondary login should only appear once in the table, and their primaryLogin should be displayed.

**Comment by truph01** [comment]
@allgandalf Can you check my thought above?

>  I don't think we can fix it in FE side because the FE cannot determine if an email is a secondary contact method for another account.

**Comment by truph01** [comment]
> Honestly the current change doesn't look great UX wise, so i think we should look for ways to fix this

Actually, the main bug and [this bug](https://github.com/Expensify/App/pull/53038#issuecomment-2497024048) are different. This PR aims to fix the main bug. We can create a separate ticket for the 2nd bug.

> can you try looking for a solution on this one?

I am still investigating a solution to fix this issue within this PR, but it requires support from the backend. The backend should return a list of secondary emails associated with any account so we can determine the relationship between two emails—in other words, whether one email is the secondary email of another. 

However, this approach still won't address the issue in offline mode. For example, if we attempt to invite two emails (one primary and one secondary) that we have no prior data for while offline, the bug will persist because we cannot determine their relationship in this scenario.

**Comment by NikkiWines** [comment]
🤔 Can we confirm if this is still a bug? Just tried reproducing it locally and on staging and I'm seeing the correct expected behavior (albiet after a short delay) 🤔 

https://github.com/user-attachments/assets/d8872e46-1b9d-4473-abef-b64264d568a7

**Comment by truph01** [comment]
@NikkiWines I tested and our main bug is not reproducible. In the [RCA](https://github.com/Expensify/App/issues/52517#issuecomment-2475434496), I mentioned:

> In personalDetailsList data, we has 0 as valid key and its data is not empty

But now, we cannot find the data for ```0``` key in ```personalDetailsList```.

**Comment by truph01** [comment]
But I think this PR still needs to be merged to make sure in the future, even there is a data for 0 key in personalDetailsList, this bug is not encountered.

**Comment by NikkiWines** [comment]
If PR introduces the visual bug from [here](https://github.com/Expensify/App/pull/53038#issuecomment-2497024048) and the main bug is no longer reproducible I don't think we should merge this as it intends to solve a problem that no longer exists.

**Comment by truph01** [comment]
> If this PR introduces the visual bug from https://github.com/Expensify/App/pull/53038#issuecomment-2497024048

@NikkiWines No, this PR does not cause the bug [here](https://github.com/Expensify/App/pull/53038#issuecomment-2497024048), that is another issue

**Comment by truph01** [comment]
@NikkiWines Could you check my [comment](https://github.com/Expensify/App/pull/53038#issuecomment-2516128012) when you have a chance, thanks.

**Comment by NikkiWines** [comment]
@truph01 sorry fro the delay. I don't think we should be merging anything to pre-emptively sovle bugs that don't currently exist. Given that I think we should close this PR.

**Pull request closed without merging**
