### PR TITLE
Added tooltip for workspace name

### PR DESCRIPTION
**Pull request by akshayasalvi**
### Details
- Added tooltip to the workspace name 

### Fixed Issues

$ https://github.com/Expensify/App/issues/5772

### Tests
1. Tested the Workspace name tooltip on all platforms
2. Ensured that nothing breaks in mobile platforms

### QA Steps

1. Go to the sidebar
2. Click on any workspacename
3. Hover over the workspace name, it should show the Tooltip

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

web-tooltip-workspace-name

#### Mobile Web

NA

#### Desktop

desktop-tooltip-workspace-name

#### iOS

NA

#### Android

NA

### CODE REVIEW

**Review by parasharrajat — APPROVED** [review]
LGTM and tests well on all platforms. Ready for merge @Beamanator

**Review by Beamanator — APPROVED** [review]
LGTM 💪

**Comment by isagoico** [comment]
This issue is failing this PR https://github.com/Expensify/App/issues/5907

**Comment by akshayasalvi** [comment]
@Beamanator @parasharrajat Can you help with the staging branch name? I checked in the main branch it is working fine. Possible that it wasn't deployed?

Screenshots here
https://github.com/Expensify/App/issues/5907#issuecomment-944894700

**Pull request merged**
