### PR TITLE
Tugbadogan display names instead of emails

### LINKED ISSUE #1446: Email addresses appearing instead of names when creating group
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  
Chrome Windows/Mac
1.0.1-221 although this has been reproduced recently

**Action Performed (reproducible steps):**

1. Go to expensify.cash and login as conor@expensify.com
2. On the search box, look for users and tap on the add button.
3. Add at least 4 users (you can access to) and click on "Go"
4. Verify the group is created, and that the email addresses are displaying. Wait 15-20 seconds and the account names should load
5. Sign in to conor+chatWithAName3@conorpendergrast.com, and you'll see the group is there but the email addresses display. Wait 15-20 seconds, and the account names should show

Created a group DM with these four users, whom I haven't chatted to before:

1. conor+chatWithName@conorpendergrast.com
2. conor+chatWithOutAName@conorpendergrast.com
3. conor+chatWithAName2@conorpendergrast.com
4. conor+chatWithAName3@conorpendergrast.com

**Expected Result:**
The names of all participants should be shown in the header of the conversation immediately. Like in [this screenshot](https://user-images.githubusercontent.com/1805746/107455565-58b86500-6b4f-11eb-8f99-b8d5798a4e79.png). 

**Actual Result:**
When first opening the conversation, whether from the creator or the receiver point of view, the email addresses appear in the header for 15-20s and then are replaced by the names. See [this screenshot](https://user-images.githubusercontent.com/1805746/107455775-a339e180-6b4f-11eb-85ad-fb4e669d9fef.png) when the conversation was created, and [this screenshot](https://user-images.githubusercontent.com/1805746/107455814-b64cb180-6b4f-11eb-9fc9-20abcd703108.png) when the conversation was first opened from one of the other participants. 

**Notes/Photos/Videos:** 
100911440-9a6cc580-34a5-11eb-803f-c521972cc481

https://www.upwork.com/jobs/~0110c4704835e8d4aa

### PR DESCRIPTION
**Pull request by tugbadogan**
@Dal-Papa 

### Details
Update reports upon PersonalDetails_GetForEmails API call.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/1446

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

#### Web

Before

https://user-images.githubusercontent.com/3853003/108427512-32708480-7235-11eb-9471-97f291a4e004.mov

After

https://user-images.githubusercontent.com/3853003/108427536-3bf9ec80-7235-11eb-9636-a2c53ce75a1c.mov

#### Mobile Web

Before

https://user-images.githubusercontent.com/3853003/108428559-a7908980-7236-11eb-80f1-b4b59cfb8839.mov

After

https://user-images.githubusercontent.com/3853003/108428587-b0815b00-7236-11eb-9895-427ad1afc339.mov

#### Desktop

After

https://user-images.githubusercontent.com/3853003/108430887-fbe93880-7239-11eb-9191-9ecf1bb7a064.mov

#### iOS

After

https://user-images.githubusercontent.com/3853003/108430538-6e0d4d80-7239-11eb-84ae-8814837eaab2.mov

#### Android

After

https://user-images.githubusercontent.com/3853003/108429642-2afeaa80-7238-11eb-8e3f-50947bf5a25d.mov

### CODE REVIEW

**Review by joelbettner — DISMISSED** [review]
LGTM. Leaving final review for @Dal-Papa

**Comment by Dal-Papa** [comment]
Hi ! The screenshots only show the LeftHandNav bar but not the conversation header like described in the issue. Could you confirm this is also fixed please ? Also, all platforms checkboxes need to be checked.

**Comment by tugbadogan** [comment]
Hi @Dal-Papa, I updated tests and screenshots to confirm that  conversation header is also fixed. And, I submit another commit to fix lint error.

**Review by Dal-Papa — APPROVED** [review]
LGTM. @marcaaron do you mind giving one last stamp just for safety please ?

**Review by marcaaron — APPROVED** [review]
LGTM 👍

**Pull request merged**
