### PR TITLE
[HOLD] Revert "[TS migration] Migrate 'PersonalDetailsUtils.js' lib to TypeScript"

### PR DESCRIPTION
**Pull request by iwiznia**
Reverts Expensify/App#30169

Context https://expensify.slack.com/archives/C03SSAQ7P/p1703183739761709

cc @thesahindia @blazejkustra @MonilBhavsar @fabioh8010 @paultsimura

### CODE REVIEW

**Comment by paultsimura** [comment]
@iwiznia could you please share a piece of context here as well?🙏🏼
I don't have access to that channel apparently, but have made changes to this TS file in my another PR that's under review currently

**Comment by muttmuure** [comment]
Performance in heavy accounts WITH lots of personal details (aka internal employee accounts) has severely degraded since this migration hit staging 3 days ago. 

Performance in heavy accounts WITHOUT lots of personal details appears to be unaffected by the performance regression.

**Comment by jasperhuangg** [comment]
@iwiznia there appear to be conflicts now, can you sort those out?

**Comment by jasperhuangg** [comment]
Heading OOO for the holidays, so it might be best to assign another engineer

**Comment by MonilBhavsar** [comment]
Conflict resolved. Let's first confirm with the build if this revert actually fixes the issue

**Comment by muttmuure** [comment]
@TMisiukiewicz please could you work with @MonilBhavsar on this today?

**Comment by fabioh8010** [comment]
@BartoszGrajdek Tagging you as you was the author of the PR.

**Comment by MonilBhavsar** [comment]
Not sure why it's not building. I'll run this against prod DB on my account and see if it fixes the issue

**Comment by mountiny** [comment]
Running the build

**Comment by situchan** [comment]
Confused which one is the exact offending PR.
To fix https://github.com/Expensify/App/issues/33326, 2 PRs were already [reverted](https://github.com/Expensify/App/pull/33496) today.
Or is this to fix any other performance regression other than #33326?

**Comment by BartoszGrajdek** [comment]
Hi, author of the PR here 😅 As you can guess I'm not really a fan of having it reverted, so I'd love to pinpoint what exactly is causing the performance issue. 

My guess is that it's most likely due to some of the underscore/lodash removals, if you could provide some reproduction steps I would love to help out 🙏🏻

**Comment by iwiznia** [comment]
I don't know the steps exactly. I think you have to have lots of people you know, so the list is large.

@muttmuure can you provide @BartoszGrajdek with steps to reproduce the issue please?

**Comment by situchan** [comment]
cc: @mountiny as you're author of [this revert](https://github.com/Expensify/App/pull/33496)

**Comment by muttmuure** [comment]
The repro steps so far are:

1. Have an account with access to lots of personal details (ex. first name, last name)
2. Open search 
3. The app (so far on web, mobile, desktop, mWeb) hangs and eventually crashes

**Comment by BartoszGrajdek** [comment]
So I guess that high-traffic account won't be enough for this, right? Since you can see only email address of the contact

**Comment by mountiny** [comment]
@iwiznia i think we might be able to close this one in case this was resolved by this revert pr https://github.com/Expensify/App/pull/33496 which was hard to confirm because people are out but from what Callstack developer suggested the new phone number methods/regexp just make the search page explode if you have thousands of personal details with phone number as primary login

**Comment by iwiznia** [comment]
Oh wow! That's nice to hear, closing then.

**Pull request closed without merging**
