### PR TITLE
Update the height of Edit profile button

### PR DESCRIPTION
**Pull request by mountiny**
### Details

This PR is adding a `small` option to Button component (styles already exist) and updates the `Edit profile` button in Profile part of Settings to be 28px tall instead of 40px.

### Fixed Issues

$ https://github.com/Expensify/Expensify.cash/issues/2434

### Tests

1. Run the app
2. Click on the profile icon
3. Click on profile
4. Make sure the `Edit profile` button is 28px tall

### QA Steps

Same as testing except of visiting staging or production version of the app.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

#### Web

image

#### Mobile Web

simulator_screenshot_C41CFD88-3CAE-4386-B082-8E4A9F9B47C3

#### Desktop

image

#### iOS

simulator_screenshot_AB719E40-ACEA-42D3-83DE-0C8A5D72C248

### CODE REVIEW

**Comment by mountiny** [comment]
@shawnborton Hi! Would you be able to double check the design here. From the issue, I was not sure if we should update the height of the button on all platforms or only website/desktop. Thank you for feedback!

**Comment by shawnborton** [comment]
Out of curiosity, what font size do small buttons use?

**Comment by shawnborton** [comment]
I agree this should be a global change and not platform specific (as are most of the things we do with E.cash!)

**Comment by mountiny** [comment]
Ok, so on the screenshots, the text is size 15px, because the styles were no applied on correct component. So for comparison, this is `font-size: 15px` as it was before with the height of button set to 40px:

image

and this is the actual buttonSmallText `font-size: 11px` as it was already defined in the codebase:

image

Let me know which one I should use :)

**Comment by shawnborton** [comment]
Perfect! Yes - the smaller button size should use the smaller font size as well.

**Comment by mountiny** [comment]
Thank you Shawn! Updated it and also the screenshots in the description. 

@HorusGoul It is good for a review 🙏

**Review by HorusGoul — APPROVED** [review]

**Comment by roryabraham** [comment]
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.

**Pull request merged**
