### PR TITLE
Change emoji highlighting type when using keyboard navigation

### PR DESCRIPTION
**Pull request by stitesExpensify**
### Details
1. Don't highlight the first emoji when opening the picker.
2. When you press the down or right arrow key on web/desktop, the first emoji should be highlighted immediately (only one keyboard press instead of 2)

### Fixed Issues

$ https://github.com/Expensify/App/issues/13417

### Tests
Web/Desktop Test:
1. Open any chat
2. Open the emoji picker
4. Make sure the emoji search bar is focused (blinking cursor)
5. Press the right arrow ONE time
6. Make sure the first emoji is now highlighted _with a blue outline_ and the search bar is not focused
7. Press enter and make sure the emoji is added to the composer
8. Re-open the emoji picker and search for "smile"
9. Make sure the first emoji is highlighted with a green background
10. Press enter and make sure it is added to the composer
11. Re-open the emoji picker and search for "smile" again
12. Press the right arrow key
13. Make sure the background of the emoji changes to a blue highlight
14. Use the arrow keys to move around the highlighted emoji, it should stay blue outlined
15. Move the mouse into the emoji picker and make sure the hovered emoji is now highlighted with a green background
16. Press and arrow key while hovering and make sure the highlight turns back to a blue outline

https://user-images.githubusercontent.com/42391420/208477492-436a349b-7cf6-495b-bab7-853bdf75b653.mp4

Mobile/MWeb Tests:
N/A

- [x] Verify that no errors appear in the JS console

### Offline tests
Same as online test

### Tests
Web/Desktop Test:
1. Open any chat
2. Open the emoji picker
4. Make sure the emoji search bar is focused (blinking cursor)
5. Press the right arrow ONE time
6. Make sure the first emoji is now highlighted _with a blue outline_ and the search bar is not focused
7. Press enter and make sure the emoji is added to the composer
8. Re-open the emoji picker and search for "smile"
9. Make sure the first emoji is highlighted with a green background
10. Press enter and make sure it is added to the composer
11. Re-open the emoji picker and search for "smile" again
12. Press the right arrow key
13. Make sure the background of the emoji changes to a blue highlight
14. Use the arrow keys to move around the highlighted emoji, it should stay blue outlined
15. Move the mouse into the emoji picker and make sure the hovered emoji is now highlighted with a green background
16. Press and arrow key while hovering and make sure the highlight turns back to a blue outline

Mobile/MWeb Test:
1. Make sure the emoji picker works as expected (these platforms should not be affected by this PR)

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>
https://user-images.githubusercontent.com/42391420/208477492-436a349b-7cf6-495b-bab7-853bdf75b653.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/42391420/208480843-b9fac5f1-26cf-441a-ad5b-af5a30f82756.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/42391420/208480508-c9f3aa43-5de1-4a61-9030-728666a8be7b.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/42391420/208705311-a91410e1-ef72-4758-9dd0-8d0314a6364b.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/42391420/208480443-2b0daede-da94-4fca-9962-1dd17c844621.mp4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/42391420/208484871-d1b53725-28a9-4430-9053-7febc59a8219.mp4

</details>

### CODE REVIEW

**Comment by stitesExpensify** [comment]
Sorry I double pullerbear'd on accident. @Luke9389 i'm going to remove you since you were second. 

@aimane-chnaif this doesn't need a C+ IMO, so I'm going to remove you as well 😄

**Review by nkuoch — DISMISSED** [review]

**Comment by stitesExpensify** [comment]
Throwing this on hold real quick to do some more of my own testing

**Comment by stitesExpensify** [comment]
I don't think this solution actually works technically. The problem is that if you search for an emoji right now, you can hit `enter` to choose the first emoji. With this change you can no longer do that which is a regression IMO.

**Comment by stitesExpensify** [comment]
Okay, this is off hold and I re-added you for review @aimane-chnaif since this is no longer just a 1 line change. 

Updating the test steps now, and then hopefully we can get this out the door!

**Review by nkuoch — APPROVED** [review]

**Comment by stitesExpensify** [comment]
Okay this is ready to go!

**Review by aimane-chnaif — APPROVED** [review]

**Comment by stitesExpensify** [comment]
Thanks @aimane-chnaif ! I updated the test videos in the OP 😄

**Pull request merged**
