### PR TITLE
fix: scroll to bottom on large paragraph text

### PR DESCRIPTION
**Pull request by mdneyazahmad**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7351

### Tests

1. Copy large paragraph text (there should be no image in between) and paste.
2. The scroll bar should move to the bottom.
- [x] Verify that no errors appear in the JS console

### QA Steps

1. Same as test step
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/77761491/150580210-ca1a98ed-3fb3-491b-8d0d-8abb4576a925.mov

#### Mobile Web

https://user-images.githubusercontent.com/77761491/151188938-adaad30f-db82-43d0-9567-600f6ef2c2d8.mov

#### Desktop

https://user-images.githubusercontent.com/77761491/151189071-931e451e-0d4b-47a2-8e14-80c82331d674.mov

#### iOS

https://user-images.githubusercontent.com/77761491/151189153-c3dffc84-af74-4e6d-8401-cf9dd5e4d287.mov

#### Android

https://user-images.githubusercontent.com/77761491/151189241-47393f20-12f0-4424-870a-ab8e1b42f93e.mp4

### CODE REVIEW

**Comment by rushatgabhane** [comment]
@mdneyazahmad could you please add video for all platforms

**Comment by rushatgabhane** [comment]
> could you please add video for all platforms


@mdneyazahmad bump :)

**Comment by mdneyazahmad** [comment]
@rushatgabhane Sorry for not updating, I got some issues with my macbook. I will upload it soon.

**Comment by mdneyazahmad** [comment]
@rushatgabhane Added screenshots

**Review by rushatgabhane — APPROVED** [review]
Tests well. LGTM!
@Beamanator

**Review by Beamanator — APPROVED** [review]

**Comment by Beamanator** [comment]
Nice work 💪

**Pull request merged**
