### PR TITLE
[Fix] Add original filename when downloading a file

### PR DESCRIPTION
**Pull request by mdneyazahmad**
### Details

Add original filename when a file is downloaded.

### Fixed Issues

$ https://github.com/Expensify/App/issues/8118

### Tests

1. Open a chat
2. Click an image to open a modal window
3. Click on download button
4. Verify that the downloaded file has same name as it was uploaded
- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. “toggleReport” and not “onIconClick”)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct english, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct english and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY
- [x] I verified any variables that can be defined as constants (ie. in CONST.js) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] Any internal methods are bound to “this” properly so there are no scoping issues
    - [x] Any internal methods bound to “this” are necessary to be bound
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose and it is
    - [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn’t already exist
    - [x] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function
(i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)

#### PR Reviewer Checklist
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. “toggleReport” and not “onIconClick”).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct english, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct english and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] Any internal methods are bound to “this” properly so there are no scoping issues
    - [ ] Any internal methods bound to “this” are necessary to be bound
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function
(i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)

### QA Steps

1. Open a chat
2. Click an image to open a modal window
3. Click on download button
4. Verify that the downloaded file has same name as it was uploaded
- [x] Verify that no errors appear in the JS console

#### Web

https://user-images.githubusercontent.com/77761491/158980044-71da7eea-4625-4735-8767-a1536bec0339.mp4

#### Mobile Web

https://user-images.githubusercontent.com/77761491/158979991-11aec668-4369-45da-acf9-f65a5eb00d73.mp4

#### Desktop

https://user-images.githubusercontent.com/77761491/158979941-987cf850-82c2-417f-abb3-cfb1d21feec3.mp4

#### iOS

https://user-images.githubusercontent.com/77761491/158979875-20da9cf2-d04c-4f0d-ad57-ad5d8dd12b0b.mp4

#### Android

https://user-images.githubusercontent.com/77761491/158979600-48c6e292-ff8b-472f-9c80-5c9179cbde85.mp4

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
#### PR Reviewer Checklist
* [ ]  I verified the correct issue is linked in the `### Fixed Issues` section above
* [ ]  I verified testing steps are clear and they cover the changes made in this PR
  
  * [ ]  I verified the steps for local testing are in the `Tests` section
  * [ ]  I verified the steps for Staging and/or Production testing are in the `QA steps` section
  * [ ]  I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
  * [ ]  I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
* [ ]  I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
* [ ]  I verified tests pass on **all platforms** & I tested again on:
  
  * [ ]  iOS / native
  * [ ]  Android / native
  * [ ]  iOS / Safari
  * [ ]  Android / Chrome
  * [ ]  MacOS / Chrome
  * [ ]  MacOS / Desktop
* [ ]  I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
* [ ]  I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
  
  * [ ]  I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. “toggleReport” and not “onIconClick”).
  * [ ]  I verified that comments were added to code that is not self explanatory
  * [ ]  I verified that any new or modified comments were clear, correct english, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
  * [ ]  I verified any copy / text shown in the product was added in all `src/languages/*` files
  * [ ]  I verified any copy / text that was added to the app is correct english and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
  * [ ]  I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
  * [ ]  I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
* [ ]  If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
* [ ]  I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
* [ ]  I verified other components are not impacted by changes in this PR (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
* [ ]  I verified all code is DRY
* [ ]  I verified any variables that can be defined as constants (ie. in CONST.js) are defined as such
* [ ]  If a new component is created I verified that:
  
  * [ ]  A similar component doesn't exist in the codebase
  * [ ]  All props are defined accurately and each prop has a `/** comment above it */`
  * [ ]  Any functional components have the `displayName` property
  * [ ]  The file is named correctly
  * [ ]  The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
  * [ ]  The only data being stored in the state is data necessary for rendering and nothing else
  * [ ]  Any internal methods are bound to “this” properly so there are no scoping issues
  * [ ]  Any internal methods bound to “this” are necessary to be bound
  * [ ]  All JSX used for rendering exists in the render method
  * [ ]  The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
* [ ]  If a new CSS style is added I verified that:
  
  * [ ]  A similar style doesn’t already exist
  * [ ]  The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function
    (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)

**Comment by Santhosh-Sellavel** [comment]
@mdneyazahmad 

Can you retest the iOS/Native app share a video here?

**Review by Santhosh-Sellavel — APPROVED** [review]
@thienlnam Verify on iOS Native alone https://github.com/Expensify/App/pull/8223#issuecomment-1075516620

Everything else tests wells. LGTM!

**Review by thienlnam — APPROVED** [review]

**Comment by thienlnam** [comment]
Waiting on IOS app but everything else looks good

**Comment by Santhosh-Sellavel** [comment]
> @mdneyazahmad
> 
> Can you retest the iOS/Native app share a video here?

Any update on this @mdneyazahmad ?

**Comment by mdneyazahmad** [comment]
@Santhosh-Sellavel I am sorry missed the notification. iOS 15.x simulator does not work for some file related thing. You can test it with ios 11.x Simulator (if you have faced any issue in testing on simulator).

**Pull request merged**
