### PR TITLE
Update app with new branding

### PR DESCRIPTION
**Pull request by shawnborton**
### Details
This updates the app with our new logo and colors.

### Fixed Issues
N/A

### Tests / QA Steps
1. Go to the Expensify.cash sign in page and make sure the screenshot, logo, and colors are updated on all platforms
2. On web, make sure the favicon is also updated to the new logo
3. Make sure the app icon is updated to use the new logo too.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

image

image

image

#### Mobile Web
image

#### Desktop
image

image

#### iOS
image

image

image

image

### CODE REVIEW

**Comment by shawnborton** [comment]
Just need to test this out on Android next, but having trouble building the app.

**Comment by roryabraham** [comment]
Tested on Android for ya, and it's looking pretty good. (splash screen also looked correct to me).

image
image

However, the default avatar images look like they come from cloudfront, and I'm not seeing those updated when testing locally...
image

Anyways, the small number of code changes look fine.

**Comment by shawnborton** [comment]
Thanks for helping out with that! I think this is ready for full review and merge then.

**Comment by roryabraham** [comment]
How did you get the screenshots locally with the updated avatars that come from cloudfront?

**Comment by shawnborton** [comment]
Ah, those new avatars are coming from Web-Static changes that we'll deploy alongside all of the app updates.

**Review by roryabraham — APPROVED** [review]
Okay, well I think this PR is working as expected 👍

**Comment by shawnborton** [comment]
@Dal-Papa all you for the final approval!

**Review by Dal-Papa — APPROVED** [review]
😍

**Comment by roryabraham** [comment]
Looks like iOS deploy failed 😕

**Comment by roryabraham** [comment]
image

@shawnborton This is now a deploy blocker, do you have a quick fix or should I revert?

**Comment by shawnborton** [comment]
Yeah, I can provide the missing icon if that helps?

**Comment by roryabraham** [comment]
Yeah, I think we need to provide the missing icon and somehow link it in the PLists. Maybe following this article:

https://medium.com/@this.shoaib/missing-required-icon-file-1893c0bedaaf

**Comment by shawnborton** [comment]
Ah, I see exactly what I did wrong. I made icons for iPad at 72x72 instead of 76x76. So should I just send a separate PR that has the three new icons with no QA, etc? Or what is the best way to proceed? Alternatively, I can just supply the new icons to you if that is easier.

**Comment by roryabraham** [comment]
Feel free to submit a new PR, this error is still a bit of a mystery to me

**Comment by roryabraham** [comment]
It looks like it wants 152x152 for iPad

**Comment by shawnborton** [comment]
Here is the follow up PR: https://github.com/Expensify/Expensify.cash/pull/2591

Let me know what I need to do for testing steps, etc.

**Comment by roryabraham** [comment]
Okay, btw @shawnborton I'm going to mark this as No QA, but really it should be `internalQA`. We just don't exactly have internal QA process for E.cash yet (we weren't sure we would ever actually need one). We'll just have to keep an eye out on staging and make sure it looks good.

**Comment by shawnborton** [comment]
Sounds good, thanks for helping me out with this one!

**Pull request merged**
