### PR TITLE
Add password to AddDebitCardPage in NewDot 

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
Adds a password requirement on the AddDebitCardPage.
We are ignoring the forgot password flow for now, as we still haven't landed on a solution.

### Fixed Issues
https://github.com/Expensify/Expensify/issues/188051 (partial)

### Tests
1. Pull the changes in [Auth](https://github.com/Expensify/Auth/pull/6271) and [Web-Secure](https://github.com/Expensify/Web-Secure/pull/2124)
2. Log into NewDot and navigate to `Settings > Payments > Add payment method > Debit card`
2. Try to submit an empty form and verify that you see an error for the password input.
3. Now fill in all the necessary information (enter 4242 4242 4242 4242 for credit card number), but use a wrong password.
4. Submit the form and verify that you see the following message: `Incorrect Expensify password entered`.
5. Now enter your correct Expensify password and submit the form again.
6. Verify that the card was added.

### QA Steps
Please note that actual password enforcement will only happen after these two PRs are merged as well: https://github.com/Expensify/Auth/pull/6271 and https://github.com/Expensify/Web-Secure/pull/2124. Before that, entering a wrong password wouldn't display an error and the card will still be added.

Follow steps above.

### Tested On

- [X] Web
- [ ] Mobile Web
- [X] Desktop
- [X] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/22219519/148591820-5ca7b892-a9bc-413c-b4b7-f7e32a8cacf1.mov

#### Desktop

https://user-images.githubusercontent.com/22219519/148591833-02f90fd7-f3d0-49d3-8623-a01e88421b1c.mov

#### iOS

https://user-images.githubusercontent.com/22219519/148593278-19b218aa-1d7b-4193-ae11-fa9a08b4b5f1.mp4

#### Android

https://user-images.githubusercontent.com/22219519/148596836-7155b605-69b5-454a-ae62-1ccdd55a45be.mov

### CODE REVIEW

**Comment by luacmartins** [comment]
This is ready for review! Since it needs to be deployed with the Auth and Web-Secure changes, I'll keep it on hold until all 3 PRs are approved!

**Comment by luacmartins** [comment]
Bumping for review!

**Review by MonilBhavsar — APPROVED** [review]
Apologies for the delay here.
Looks good to me 👍
Feel free to merge after merging backend!

**Comment by luacmartins** [comment]
Thanks for the review @MonilBhavsar! No longer on hold, merging.

**Comment by botify** [comment]
@luacmartins looks like this was merged without passing tests. Please add a note explaining why this was done and remove the `Emergency` label if this is not an emergency.

**Comment by luacmartins** [comment]
All tests passed before merging. Removing `Emergency` label.

**Pull request merged**
