### PR TITLE
Allow hitting production web-secure from staging

### PR DESCRIPTION
**Pull request by marcaaron**
### Fixed Issues
$ https://github.com/Expensify/App/issues/7371

### Tests
There's no way to test this on dev really.

### QA Steps

1. Ensure the user preference for the staging secure server toggle is off
2. Try to log in with the Chase credentials 
3. Verify it doesn't work (because we are not on staging secure)
4. Toggle to staging secure server
5. Try to log in with the Chase credentials
6. Verify we can do so now since we are in the sandbox

- [ ] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by stitesExpensify — APPROVED** [review]

**Comment by botify** [comment]
@stitesExpensify looks like this was merged without passing tests. Please add a note explaining why this was done and remove the `Emergency` label if this is not an emergency.

**Comment by stitesExpensify** [comment]
This was merged with passing tests. Issue is here https://github.com/Expensify/Expensify/issues/189984

**Comment by roryabraham** [comment]
Tried testing this and I get a CSP error on staging:

image

**Comment by danieldoglas** [comment]
I was testing just now and got the same as @roryabraham

**Comment by roryabraham** [comment]
Technically, this is QA pass because trying to log in didn't work :trollface:

**Comment by roryabraham** [comment]
I'm going to work on fixing the CSP

**Comment by roryabraham** [comment]
https://github.com/Expensify/Cloudflare-Workers/pull/29

**Comment by roryabraham** [comment]
CSP is fixed: 

image

**Comment by roryabraham** [comment]
I did the following:

1. Ensured that the `Use staging secure server` toggle was off.
1. Tried to add a Chase bank account. Was taken to production Chase OAuth, and the sandbox credentials didn't work.
1. Toggled the `Use staging secure server` on.
1. Tried to add a Chase bank account. Ended up using Plaid sandbox mode (was not taken to actual production Chase OAuth login site), and sandbox credentials worked.

Which I think means this is a QA pass ✅ 🎉

**Pull request merged**
