### PR TITLE
Allow pasting amount with comma

### PR DESCRIPTION
**Pull request by mananjadhav**
@pecanoro Can you please review this?

### Details
- Updated regex to allow pasting numbers with a comma
- Strip comma after pasting

### Fixed Issues

$ #4885 

### Tests
1. Pasted the number with a comma
2. Ensured that typing doesn't put comma

### QA Steps
1. Try any IOU feature like Split or Request money
2. Take a number with comma(s)
3. Paste and see that the number is pasted.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/3069065/131900571-4422bdab-218a-4bbe-93c1-a575e232e566.mp4

#### Mobile Web
NA - We don't allow pasting in mobile web

#### Desktop
https://user-images.githubusercontent.com/3069065/131900973-199a6808-376d-40be-8c16-efd7e41ecdf7.mp4

#### iOS

NA - We don't allow pasting in iOS

#### Android

NA - We don't allow pasting in Android

### CODE REVIEW

**Review by pecanoro — APPROVED** [review]

**Comment by mananjadhav** [comment]
@pecanoro Anything pending in this for merge?

**Comment by pecanoro** [comment]
I was waiting for @marcaaron to review it since he is also assigned as a reviewer.

**Review by marcaaron — APPROVED** [review]

**Review by marcaaron — APPROVED** [review]
LGTM

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-17.  :confetti_ball:

**Pull request merged**
