### PR TITLE
Add link to NewHelp 

### PR DESCRIPTION
**Pull request by marcochavezf**
### Details

Add link to NewHelp site from Settings page and Get assistance page.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/240970

### Tests

1. Open Settings menu
2. Click on "Help" item and verify it opens the site https://help.expensify.com/
3. Open the menu of an existing workspace.
4. Open the Get assistance page (Click on the "?" icon at the top of the page)
5. Click on "Explore help docs" item and verify it also opens the site https://help.expensify.com/

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

Same as `Test` steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/6829422/211429950-c2a4dfce-e14d-4581-afa0-9dfe806d73dc.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/6829422/211430467-0cf091f3-5913-47cb-9499-d8c00e6222c5.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/6829422/211430576-d32e7044-4b8c-4c9b-b3be-a00d0133cbfb.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/6829422/211430828-e22fed44-342c-483d-8487-44f6bc300c68.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/6829422/211431808-d79817e6-0423-4ae5-8e53-d85f201737ad.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/6829422/211431772-1e7a29ae-8b9f-4a2d-8588-aec522fa6a3f.mov

</details>

### CODE REVIEW

**Review by ctkochan22 — APPROVED** [review]

**Comment by marcochavezf** [comment]
@ctkochan22 @eVoloshchak could you complete the PR Reviewer checklist to pass the GH checks?

**Comment by ctkochan22** [comment]
@eVoloshchak you have time to do the checklist?

**Comment by eVoloshchak** [comment]
> @eVoloshchak you have time to do the checklist?

I will be able to do that in ±12 hours, would that be ok?

**Comment by eVoloshchak** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/9059945/212478490-eea78a7e-d4a3-40f0-8803-6dfa046c079b.mov




</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://user-images.githubusercontent.com/9059945/212478475-4ff83035-2255-45df-b8d2-b6b5c144c10c.mp4





</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/9059945/212478522-c545a560-87a9-4cde-bb44-54e9754e2ecb.mov




</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/9059945/212478506-5f6f5c0f-2fcb-45bd-bc0c-e9a68a33e2c7.mov




</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/9059945/212478513-eb1cfa6a-4df5-474d-94dc-65eba638df67.mov




</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/9059945/212478460-ab79c5ec-cf42-4dd6-ad9d-8aa281ae937b.mp4




</details>

**Review by eVoloshchak — APPROVED** [review]
LGTM

**Comment by marcochavezf** [comment]
Thank you guys! I'm going to merge it now

**Comment by jayeshmangwani** [comment]
@marcochavezf @eVoloshchak @ctkochan22 local app is crashing because of this PR, we are using themeColors on GetAssistance Page but we have not imported

**Comment by jayeshmangwani** [comment]
local app is crashing because of this PR, we are using themeColors on GetAssistance Page but have not imported

**Comment by eVoloshchak** [comment]
> local app is crashing because of this PR, we are using themeColors on GetAssistance Page but have not imported

Oh, true, thank you
The import was there, then it got removed in https://github.com/Expensify/App/pull/14289 since at that point this PR wasn't merged
I always thought GitHub does a lint check when merging, it should have caught that

image

Then again, even if linter would have caught it and we added the `themeColors` import back, it wouldn't crash anymore, but there would still be a bug, the icon wouldn't change the color oh hover (since this behavior was just recently added by https://github.com/Expensify/App/pull/14289)

https://user-images.githubusercontent.com/9059945/212534137-f1f9bd5d-4caf-4f83-9e86-32c9a15a62ac.mov

So to actually fix this we need to delete this line. I'm going to open a PR shortly

https://github.com/Expensify/App/blob/7ca2979f550c812171017e7b20b4ba659be17800/src/pages/GetAssistancePage.js#L62

There's also a [post for this](https://expensify.slack.com/archives/C049HHMV9SM/p1673765469647509) on Slack @jayeshmangwani created

**Comment by AndrewGable** [comment]
@marcochavezf - Can you please production QA this?

**Comment by jayeshmangwani** [comment]
was checking if am I eligible for the bonus to [reporting](https://expensify.slack.com/archives/C049HHMV9SM/p1673765469647509) a regression.

cc: @eVoloshchak @aimane-chnaif

**Comment by jayeshmangwani** [comment]
> was checking if am I eligible for the bonus to [reporting](https://expensify.slack.com/archives/C049HHMV9SM/p1673765469647509) a regression.
> 
> cc: @eVoloshchak @aimane-chnaif

@eVoloshchak @aimane-chnaif can you please confirm this, I am not able to find the original issue to comment

**Comment by eVoloshchak** [comment]
Test comment

**Comment by eVoloshchak** [comment]
@aimane-chnaif, thank you for the info!
I can't approve the PR since it was already merged, so I'm going to ask BZ members for help in Slack

**Comment by eVoloshchak** [comment]
This also had a [regression](https://github.com/Expensify/App/pull/13898#issuecomment-1383107757) that couldn't be prevented by following the checklist, not sure what're the rules on that

**Pull request merged**
