### PR TITLE
Fix bolded text for Existing Owners Error

### PR DESCRIPTION
**Pull request by jasperhuangg**
### Details
This PR fixes the text in the error message to prevent any separators (e.g. `, `, `, and`, etc.) from being bolded. It also ensures we use the localization for the word `and`.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/169896#issuecomment-884327715

### Tests
1. Paste this code block [here](https://github.com/Expensify/App/blob/3ea4b275d6fa885e631a69d6335bc80a46e4f955/src/libs/actions/BankAccounts.js#L600). This'll simulate the server returning with an existingOwners error:
    ```js
    return new Promise(resolve => resolve({existingOwners: ['patrick@expensify.com', 'spongebob@expensify.com', 'sandy@expensify.com']})).then((response) => {
        const existingOwnersList = response.existingOwners.reduce((ownersStr, owner, i, ownersArr) => {
            let separator = ',\n';
            if (i === 0) {
                separator = '\n';
            } else if (i === ownersArr.length - 1) {
                separator = ' and\n';
            }
            return `${ownersStr}${separator}${owner}`;
        }, '');
        Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {loading: false, error: CONST.BANK_ACCOUNT.ERROR.EXISTING_OWNERS, existingOwnersList});
    });
    ```
2. Navigate to the add bank account flow for a workspace. 
3. Verify that you're unable to add the account since the bank account already has an existing owner, and verify that the error step displays (see screenshots).

### QA
1. Create a new workspace and click "Get Started".
2. Add a bank account manually following the steps [here](https://stackoverflow.com/c/expensify/questions/342).
3. In a different account, follow steps 1 and 2.
4. Verify that you're unable to add the account since the bank account already has an existing owner, and verify that the error step displays (see screenshots).

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [ ] Android

#### Web
Screen Shot 2021-07-27 at 3 45 11 PM

#### Mobile Web
Screen Shot 2021-07-27 at 3 45 25 PM

#### Desktop
Screen Shot 2021-07-27 at 3 47 18 PM

#### iOS
Screen Shot 2021-07-27 at 3 45 34 PM

#### Android
Screen Shot 2021-07-28 at 11 39 34 AM

cc @michelle-thompson

### CODE REVIEW

**Review by tgolen — DISMISSED** [review]
Are you able to get it tested on Android?

**Comment by jasperhuangg** [comment]
@tgolen My android emulator is being all wonky. I have an old android device lying around somewhere, lemme see if I can find it 🧐

**Comment by jasperhuangg** [comment]
Yup, can't get my physical device to work either :/ @tgolen

**Comment by tgolen** [comment]
Ah, cool. Thanks! Sorry it gave you such fits. I know the pain

**Comment by tgolen** [comment]
I assume the removal of flex was intentional?

**Review by tgolen — APPROVED** [review]
I'll must assume you meant to remove the flex and merge this. If we need to revert that change in another PR (like if it was a mistake), then that's OK.

**Pull request merged**
