### PR TITLE
[CP Staging] Revert "Fix here is your magic code shows briefly when login with magic link"

### PR DESCRIPTION
**Pull request by MonilBhavsar**
Reverts Expensify/App#40177

Fixes a deploy blocker https://github.com/Expensify/App/issues/40742

1. Go to New dot and enter expensifail account with 2FA enabled
2. Navigate to email and locate the magic link - change to staging
3. Open an new tab and navigate to the staging link or build link
4. 2FA required page should be displayed without infinite loader

### CODE REVIEW

**Comment by MonilBhavsar** [comment]
Issue seems fixed

Screenshot 2024-04-23 at 3 30 31 PM

**Comment by MonilBhavsar** [comment]
We're probably fixing it https://github.com/Expensify/App/issues/40742#issuecomment-2071909340
We can revert if it is really blocking the deploy

**Comment by mountiny** [comment]
Thanks, straight revert so checklists are not required

**Review by mountiny — APPROVED** [review]

**Comment by mountiny** [comment]
not emergency, see above, only checklists missing

**Pull request merged**
