### PR TITLE
Make AttachmentPicker a component instead of a lib to fix Safari

### PR DESCRIPTION
**Pull request by marcaaron**
cc @Jag96 @Julesssss Seems like iOS Safari does not actually fire any change handlers for `<input type="file"/>` unless they are appended to the DOM. We should not really be creating DOM elements on the fly anyway so I came up with a more "React-y" solution which is to use a render prop component that exposes the `show()` method from `AttachmentPicker.show()` and just use that instead of importing the lib? This component will basically append a hidden file input to the DOM alongside whatever stuff it's wrapped in and this way we don't really even need `AttachmentPicker` to be cross platform.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/144167

### Tests
1. Test that files can be attached via Safari on iOS
1. Follow tests in https://github.com/Expensify/ReactNativeChat/pull/689 and make sure they still pass

### Screenshots
❌

### CODE REVIEW

**Review by Julesssss — DISMISSED** [review]

**Review by Julesssss — DISMISSED** [review]

**Review by tgolen — CHANGES_REQUESTED** [review]
I'm trying to wrap my head around this code, so hang in there with me. This is something new that I haven't really seen before and it's not very easy to follow what's happening, or why it was written this way.

The way I understand it is that iOS Safari needs to have the hidden file input appended directly to the DOM. I'm OK with that. Is there a reason why we can't just do it this way for all platforms? I think that would simplify the code and make it slightly less confusing if it's possible.

**Review by Jag96 — COMMENTED** [review]
This was definitely a bit confusing for me at first since I haven't seen this before, but I think I've got it now. I've added a couple of questions just to confirm.

**Review by Jag96 — APPROVED** [review]
LGTM

**Review by tgolen — CHANGES_REQUESTED** [review]
This looks much better 👍 thanks for those changes.

**Review by tgolen — APPROVED** [review]

**Pull request merged**
