### PR TITLE
Convert some capital letters to lowercase and capitalize months and days in Spanish.

### PR DESCRIPTION
**Pull request by ayazhussain79**
### Details
We want to convert some capital characters to lowercase and capitalization for months and days in Spanish.

### Fixed Issues
#16403 
PROPOSAL: https://github.com/Expensify/App/issues/16403#issuecomment-1481348542
### Tests

1. Go to the Personal detail -> Date of birth  verify word (Fecha de nacimiento)
2. Open date of birth picker in Spanish verify (Month name, including days)
3. Go to the Home Address and verify word 'Código postal'.
4. Go to the Profile add new profile and verify word 'Editar foto'.
5. Go to the Workspace-> Connect bank account, verify header words in both language (One moment,Un momento)

### Offline tests

Same as above

### QA Steps
Same as above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos

<details>

<summary>Web</summary>

https://user-images.githubusercontent.com/56740856/227703254-d2f00d90-396e-4dfb-99c2-7cdeda8ba35b.mp4

Screenshot_49
Screenshot_51
Screenshot_53
Screenshot_54
Screenshot_55

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Uploading Screen Recording 2023
Screenshot 2023-03-27 at 10 48 30 PM

https://user-images.githubusercontent.com/56740856/228038992-d8b155e6-ccd1-470c-8782-561219e9235d.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>
Screenshot 2023-03-27 at 10 39 46 PM
Screenshot 2023-03-27 at 10 38 28 PM

https://user-images.githubusercontent.com/56740856/228034811-5a73fedd-9cf2-405e-8512-68fcf219099a.mov

Screenshot 2023-03-27 at 10 39 01 PM

</details>

<details>
<summary>iOS</summary>

Screenshot 2023-03-27 at 10 45 45 PM
Screenshot 2023-03-27 at 10 45 56 PM
Screenshot 2023-03-27 at 10 47 17 PM

https://user-images.githubusercontent.com/56740856/228037468-b0ba84f3-51c5-4d68-a15c-23867ef08b7b.mov

</details>

<details>
<summary>Android</summary>

Screenshot 2023-03-27 at 11 01 59 PM
Screenshot 2023-03-27 at 11 02 19 PM

https://user-images.githubusercontent.com/56740856/228036776-8b29c9bc-f535-4eeb-9607-2194d4954c1f.mov

Screenshot 2023-03-27 at 11 02 44 PM

</details>

### CODE REVIEW

**Comment by ayazhussain79** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ayazhussain79** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by ayazhussain79** [comment]
Sir most of the changes are on en.js file, so it will applied on all platform I'm facing some issues on emulators sorry for that. you can verify them on any platform

**Comment by Julesssss** [comment]
Hi @ayazhussain79, can you please add screenshots/videos for all the platforms you can? And list those you cannot so we can fill in the remaining. Thanks.

**Comment by ayazhussain79** [comment]
@Julesssss  Sir, I have tested them on web chrome but not able to test them on other platforms, you can verify them it will be applied on all platforms

**Comment by Julesssss** [comment]
Also, i see failures in the CI flows. Please resolve these too.

**Review by Julesssss — CHANGES_REQUESTED** [review]
Left a note with the required changes

**Comment by ayazhussain79** [comment]
@Julesssss I have uploaded other platform videos/SS except Mobile Web - Safari and I have also used GPG keys on my github to verified commit, do I need to create a new branch and pull request?

**Comment by ayazhussain79** [comment]
@Julesssss I have created new PR with signed commits https://github.com/Expensify/App/pull/16593#issue-1642840205

**Comment by Julesssss** [comment]
Yep, Thanks!

**Pull request closed without merging**
