### PR TITLE
[No QA] Dont require accessibility checkboxes to ship a deploy checklist

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Coming from https://expensify.slack.com/archives/C07J32337/p1642722197174300

### Fixed Issues
$ n/a

### Tests
1. Close a deploy checklist with the :shipit: comment and all the QA boxes checked but a deploy blocker unchecked.
1. The issue should reopen.
1. Close a deploy checklist with the :shipit: comment and all the deploy blockers checked but a QA box unchecked.
1. The issue should reopen.
1. Close a deploy checklist with the :shipit: comment, all the QA boxes checked, all the deploy blockers checked, and at least one accessibility checkbox unchecked.
1. The issue should not reopen and the production deploy should happen.

### QA Steps
None.

### Tested On
Jest/GitHub only

### CODE REVIEW

**Review by sketchydroide — APPROVED** [review]

**Comment by sketchydroide** [comment]
is this something I can test along side the deployer for the week @roryabraham?

**Comment by roryabraham** [comment]
I think it'll be best for the current deployer to test this, because it should be tested when we're about ready to ship a prod deploy

**Comment by sketchydroide** [comment]
@chiragsalian do you mind testing then 🙏🏼

**Comment by chiragsalian** [comment]
Well the QA checklist isn't done yet and I don't plan on deploying today cause its a friday. So we've to inform the next deployer to test this on monday.

**Comment by sketchydroide** [comment]
@AndrewGable seems like you are the  deployer for the week, so you mind doing the testing as part of the deployment process for this week 🙏🏼

**Comment by AndrewGable** [comment]
Yes, I can test

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
