### PR TITLE
Fix tracking rate

### PR DESCRIPTION
**Pull request by marktoman**
### Details

Fix Rate formatting

### Fixed Issues

$ https://github.com/Expensify/App/issues/6213

##### Steps
1. In the Rate field, type any number that has less than 2 decimal places
2. Wait more than 3 seconds
##### Result
The number is formatted to 2 decimal places

##### Steps
1. In the Rate field, type any number that has more than or equal to 2 decimal places
2. Wait more than 3 seconds
##### Result
The number is preserved

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

image

#### Mobile Web

Screenshot_1644428887

### CODE REVIEW

**Comment by deetergp** [comment]
@marktoman Just a reminder that I can't review this till you've added PR details and tested on all platforms.

**Comment by marktoman** [comment]
@deetergp Updated

**Comment by deetergp** [comment]
Thanks @marktoman. 

Now I realize what's going on. You are saving the rate as `0.585` which makes perfect sense. But in order to normalize across several different kinds of currencies, we save our amounts in cents only, so we need to be saving the amount of fifty eight and a half cents as `58.5` but displaying it as `0.585` (zero dollars and fifty eight cents). 

To illustrate, this:
Screen Shot 2022-02-09 at 5 01 04 PM

Functionally ends up making expenses that pay out $0.0059 per km
Screen Shot 2022-02-09 at 5 02 16 PM

Which would very likely end up upsetting anyone that tries to get reimbursed for their mileage. Does that make ~cents~ sense?

**Review by deetergp — CHANGES_REQUESTED** [review]
We need to be storing these as as cents rather than dollars and cents.

**Review by deetergp — CHANGES_REQUESTED** [review]
With the latest changes, I am not able to type anything with a leading decimal into the form. We specifically need to be able to add `0.585` since that is the 2022 default rate for the IRS.

**Comment by marktoman** [comment]
Do you experience different behavior than what the video shows? Otherwise, can you elaborate?

https://user-images.githubusercontent.com/47689923/153510352-c156452e-fdc1-42d3-a366-6176d08786d9.mp4

**Comment by deetergp** [comment]
@marktoman What I am experiencing is the UI simply won't let me type `0.anything`

**Comment by marktoman** [comment]
@deetergp Strange, after running
```zsh
git clone https://github.com/marktoman/fix-tracking-rate fix-tracking-rate
cd fix-tracking-rate
npm install && npm run web
```

, I tested both desktop and mobile and it behaves like my video.

Can you see errors on the console?

**Comment by marktoman** [comment]
> With the latest changes, I am not able to type anything with a leading decimal into the form. We specifically need to be able to add `0.585` since that is the 2022 default rate for the IRS.

@deetergp Is this unique to the latest commit? I have tested the first commit from scratch — no difference on my end.

**Review by deetergp — APPROVED** [review]
Looks good and tests well

**Pull request merged**
