### PR TITLE
fix: remove extra space between paragraph text

### PR DESCRIPTION
**Pull request by mdneyazahmad**
### Details

Remove extra space between the two paragraphs in concierge messages.
### Fixed Issues

$ https://github.com/Expensify/App/issues/7474

### Tests

1. Open a chat with Concierge.
2. Type "I can't delete workspace". The replied messages contain multiple paragraphs.
3. There should be a normal spacing between the paragraphs.
- [x] Verify that no errors appear in the JS console

### QA Steps

1. Same as test steps
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

webb

#### Mobile Web

mwebb

#### Desktop

desktopp

#### iOS

ioss

#### Android

Screenshot_1644774448

### CODE REVIEW

**Review by parasharrajat — CHANGES_REQUESTED** [review]
@mdneyazahmad Could you please test it on Android as well? It is required effective from https://expensify.slack.com/archives/C01GTK53T8Q/p1644020126470619.

--- 
Apart from it. I think we should remove the margin Bottom as well. This is how it looks when HTML has two p tags (first 2 lines) and this is how we show two lines of text separated with a newline (last 2 lines).


image

**Comment by parasharrajat** [comment]
Any update here... Please attach screenshot for Android as well...

**Comment by mdneyazahmad** [comment]
I missed it, adding it soon. Should I change the margin bottom too?

**Comment by mdneyazahmad** [comment]
### Android Screenshot
Screenshot_1644774448

**Comment by parasharrajat** [comment]
Yes, and add the screenshot in the description at the specified location.

**Comment by mdneyazahmad** [comment]
Done

**Review by parasharrajat — APPROVED** [review]
LGTM. 

@marcochavezf 
:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by marcochavezf** [comment]
Thank you @mdneyazahmad and @parasharrajat :)

**Review by marcochavezf — APPROVED** [review]

**Pull request merged**
