### PR TITLE
Always call OpenPublicProfilePage API

### PR DESCRIPTION
**Pull request by kmbcook**
### Details

ProfilePage now calls openPublicProfilePage regardless of value of hasMinimumDetails.

### Fixed Issues

$ https://github.com/Expensify/App/issues/36610
PROPOSAL: https://github.com/Expensify/App/issues/36610#issuecomment-1949528548

### Tests

1. Go to a room chat.
2. Click on the user avatar to open profile page.
3. Check console messages or network inspector to verify that openPublicProfilePage API call has been made.

- [x] Verify that no errors appear in the JS console

### Offline tests

This issue is only relevant when online.

### QA Steps

1. User A and User B do not know each other.
2. User A goes to a public room.
3. User B goes to the same public room. (Go to the same URL as User A.)
4. User B posts a message.
5. User A notices that the message was posted.
6. User B goes to Profile and changes Display name.
7. User A clicks on avatar of User B, which shows profile page of User B.
8. Verify that User A's view of profile page of User B shows newly updated name.

 

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/14853493/8153d505-e4bc-4309-8829-7aa07a46a1d3

https://github.com/Expensify/App/assets/14853493/51d0c358-b917-4da8-bfe4-5d513a32255b

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/14853493/1dc4759b-d736-4e0e-a776-b3d0cf3ae048

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/14853493/f10c6f16-a01b-4706-b21f-a46b0578db4b

https://github.com/Expensify/App/assets/14853493/e90cc2f9-27f6-48f8-a536-e4a06e49156c

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/14853493/cb810397-ed0e-45aa-a851-4003d79a8965

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/14853493/509fcf13-896d-44ae-a2ed-bce0a3c18f9d

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/14853493/f2d96bbe-e7f8-4fa6-859f-754e8a3a0531

</details>

### CODE REVIEW

**Comment by cubuspl42** [comment]
As [commented here](https://github.com/Expensify/App/pull/37180#discussion_r1503196334), we'll be moving the review to this PR and @kmbcook will close https://github.com/Expensify/App/pull/37180.

**Comment by cubuspl42** [comment]
Please move the tests related to dev inspector to the "Tests" section. This is too technical for QA, I think.

Regarding the actual QA Steps, it would be awesome to find an actual case when this brings user-observable benefit. 

See: https://github.com/Expensify/App/issues/36610#issuecomment-1957277652

> There are scenarios where personal details don't get pushed from the back-end (e.g with public room users you don't know). So I think it makes sense to call the API when we open the page, just like we call the OpenReport API every time you open a chat.

Could you explore this lead and find reproducible, reasonably minimal QA testing steps?

**Comment by kmbcook** [comment]
I moved those test steps to Tests.

With regard to scenarios where changes to personal details don't get pushed from the back-end, what do you think of the following course of events?

We specify to QA that they test for one of those scenarios, call it scenario A. They do so for some time, with no problems. Each time they test, personal details are current because of this PR. Later, another code change ensures that in scenario A changes to personal details are indeed pushed from the back-end, making it so scenario A no longer needs this PR. Another of these scenarios, call it scenario B, still relies on this PR. Later, another code change inadvertently negates the effect of this PR. When that happens, QA tests using scenario A, and the test succeeds. However, scenario B fails because the change in this PR has been negated. In order for QA to have an effective test of this type it would need to test every possible manifestation of not calling the API, both now and in the future.

**Comment by cubuspl42** [comment]
@kmbcook 

Uh, this got a bit philosophical.

From my perspective, I just wanted to find a manual test that...

- fails on `main` (avatar gets outdated in a specific scenario, it can be a corner case)
- succeeds on this PR branch (avatar is always kept up-to-date) 

Regarding being future-proof, not all QA Steps end up being a regression test. Still, don't overthink it. It's just a good practice to find some steps that prove that the changes actually improved something.

Give it a try. **If** we find out this is too difficult, we'll move on without it. The fact that an internal engineer explicitly requested this change will be a good enough reason.

**Comment by kmbcook** [comment]
OK, I did it.

**Review by jakub-trzebiatowski — CHANGES_REQUESTED** [review]
Please merge `main`

**Comment by kmbcook** [comment]
Merged main and tested.

**Review by jakub-trzebiatowski — APPROVED** [review]

**Comment by cubuspl42** [comment]
@stitesExpensify Friendly bump

**Review by stitesExpensify — APPROVED** [review]

**Comment by stitesExpensify** [comment]
Not an emergency, all tests were passing

**Pull request merged**
