### PR TITLE
Graphical alignment issues in chat upon first sign-in

### LINKED ISSUE #1031: Graphical alignment issues in chat upon first sign-in
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/master/CONTRIBUTING.md) for onboarding!
___

**Platform - version:**  

**Action Performed (reproducible steps):**
1. Start the app on in an Incognito browser
2. Hard refresh the page
3. type in your username and password, and tap 'Log in'
4. Once you're logged in, tap the hamburger menu, type in `concierge@` in the text box, and tap on the `Concierge` user
5. Notice the off-center paperclip icon and misaligned presence indicator (green dot)

**Expected Result:**
1. The paperclip icon should remain centered on initial load and subsequent access.
2. The green dot should be correctly aligned with the profile image
3. This should be solved holistically, not as a one-off solution for each of the problems. The graphical elements are supposed to be absolute positioned, but on initial page load, this is being overruled by a position:relative. The order the styles show up in the debugger appear to change after refreshing. To see the problem occur after initial load, you must log out and refresh, then log back in. In other words, a fix will only be considered acceptable if it fixes the underlying cause of the issue, rather than masking the symptom(s). 'Band-aid' fixes are unacceptable.

**Actual Result:**
The paper clip is not centered
The green dot appears below the profile icon

**Notes/Photos/Videos:** 

off center (2)

image

View the Upwork job [here](https://www.upwork.com/jobs/~018bda224287da8095).

### PR DESCRIPTION
**Pull request by ilijaprzeski**
### Details
Removed plugin for react-native-web in babel.config.js file. So overridden issues by dynamically generated css are permanently fixed. 💯 

### Fixed Issues
Fixes [Expensify/Expensify.cash/issues/1031](https://github.com/Expensify/Expensify.cash/issues/1031)

### Tests
1. Start the app on in an Incognito browser
2. Hard refresh the page
3. type in your username and password, and tap 'Log in'
4. Once you're logged in, tap the hamburger menu, type in concierge@ in the text box, and tap on the Concierge user
5. Notice the center paperclip icon and aligned presence indicator (green dot)

### CODE REVIEW

**Review by sketchydroide — DISMISSED** [review]
LGTM

**Comment by marcaaron** [comment]
Please open **one** PR per issue. Feel free to reopen whichever single PR you are proposing as a solution.

**Comment by marcaaron** [comment]
Is there some explanation as to why removing this plugin should fix anything?

https://github.com/necolas/react-native-web/tree/master/packages/babel-plugin-react-native-web

**Comment by marcaaron** [comment]
Adding @AndrewGable to give this a second set of eyes

**Comment by marcaaron** [comment]
More conversation happening here. https://expensify.slack.com/archives/C01GTK53T8Q/p1609268462235000

We resolved that this is caused by setting the `commonjs: true` option to the babel plugin.

While this solution works and is definitely worth merging. We should follow up in `react-native-web` to see if this is a bug and to get to the real root of the problem. AFAIK we aren't using the react native commonJS modules so there should be no consequences to removing that option.

**Comment by marcaaron** [comment]
Sorry @ilijaprzeski we will need a new PR thanks.

**Review by marcaaron — APPROVED** [review]

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
