### PR TITLE
Fixed delete action on context menu

### LINKED ISSUE #3767: [HOLD for payment on July 7] Web - Chat - Message not deleted when selecting delete option from the context menu
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

Upwork link: https://www.upwork.com/jobs/~01ea79ee49be020d89
___

## Action Performed:
1. Open e.cash in Web
2. Navigate to a conversation
3. Right click on any own message
4. Choose  Delete Comment option
## Expected Result:
The comment is deleted when you click tab "Delete comment"
## Actual Result:
The delete function does not work and message not deleted.
## Workaround:
Unknown
## Platform:
Where is this issue occurring?

 Web ✔️
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.74-0
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/123493244-dd30ef00-d5e9-11eb-86c4-30ebd0eadd2a.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details
Moving the ConfrimModal up the component tree so that it does not close with the Context Menu itself.

### Fixed Issues

$ Fixes #3767

### Tests |  QA Steps
1. Open any conversation on E.cash.
2. Now send a message.
3. Wait for the Delete action to become active.
4. Try to delete the message from the Hover menu, the message should be deleted.
5. Send another message.
6. Wait for the delete action to become active.
7. Try to delete the message from the Context Menu, the message should be deleted.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/24370807/123986172-b573c980-d9e3-11eb-8879-a9a864fe5bf1.mp4

#### Mobile Web

https://user-images.githubusercontent.com/24370807/123986194-ba387d80-d9e3-11eb-8c23-b38dac415ea2.mp4

#### Desktop

https://user-images.githubusercontent.com/24370807/124058311-c43f9800-da46-11eb-92e2-90c239ae515c.mp4

#### Android

https://user-images.githubusercontent.com/24370807/123986255-c6bcd600-d9e3-11eb-8199-7d27b22f8971.mp4

### CODE REVIEW

**Review by Jag96 — COMMENTED** [review]
Left a couple comments but this is looking good to me. Requesting a review from @roryabraham as well since he reviewed the proposal

**Comment by parasharrajat** [comment]
Updated

**Review by roryabraham — APPROVED** [review]
LGTM 👍

**Comment by roryabraham** [comment]
Unfortunately the deploy comments are not working right now. This was deployed to staging yesterday.

**Pull request merged**
