### PR TITLE
Fix subtitle displayed wrong in LHN when clicking reply in thread

### PR DESCRIPTION
**Pull request by dukenv0307**
### Details

Subtitle displayed wrong briefly in LHN when clicking reply in thread
### Fixed Issues

$ https://github.com/Expensify/App/issues/19349
PROPOSAL: https://github.com/Expensify/App/issues/19349#issuecomment-1556909085

### Tests

1. Login with any account
2. If doesn't have any workspace, create a new workspace
3. Go to announce or admin chat of any workspace
4. Send any message
5. Clicking on reply in thread
6. Verify that subtitle that is displayed in LHN follows the pattern 'Workspace Name • #roomName' with correct workspace name
- [x] Verify that no errors appear in the JS console

### Offline tests

Same above
### QA Steps

1. Login with any account
2. If doesn't have any workspace, create a new workspace
3. Go to announce or admin chat of any workspace
4. Send any message
5. Clicking on reply in thread
6. Verify that subtitle that is displayed in LHN follows the pattern 'Workspace Name • #roomName' with correct workspace name
- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

[Screencast from 06-06-2023 09:50:46.webm](https://github.com/Expensify/App/assets/129500732/99fc63c1-a0fe-4411-a190-7cb604c25361)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/129500732/fe570c9b-bec4-468b-b3c2-3b9ec1c6db15

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/129500732/2557902a-260d-4d9a-84c3-6045ea28087e

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/129500732/abd3dc2a-ef2a-4272-ae7b-939b03fa8a6f

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/129500732/c24264b9-1b02-43f7-b84f-87f48eaf1b4f

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/129500732/913324b3-654c-4076-91af-3bb2380c23d5

</details>

### CODE REVIEW

**Review by amyevans — APPROVED** [review]
NBD, but looks like the videos for mWeb - Safari and Desktop are swapped

**Comment by abdulrahuman5196** [comment]
@dukenv0307 @amyevans I have raised this issue in expensify-open-source slack channel as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1686064782564449

**Comment by abdulrahuman5196** [comment]
@amyevans

>This solution seems fine, it'll enable us to fully test the fix in this PR, without becoming dependent on a fix for the unrelated issue in main

The solution is fine. But I don't think we can test it fully. Even if we remove the author's commits, we can still see the same behaviour due to the main issue. Its like with or without this fix we are seeing the same behaviour during thread creation. Since the issue of "No activity yet" will only come during the skeleton view load phase we won't be able to test if this solution fixes it.

**Comment by amyevans** [comment]
@abdulrahuman5196 Hmm I'm not sure I follow what you're saying.

I am testing with these steps:
* `git checkout 2977c04baf`
* Open an #admins chat
* Post a comment while online
* Go offline (via Chrome Devtools)
* Click `Reply in thread`
* I reproduce the bug reported in #19349: `No activity yet` displays in the LHN
before-fix

* `git cherry-pick 00f363f`
* Post a comment while online
* Go offline (via Chrome Devtools)
* Click `Reply in thread`
* The bug reported in #19349 is fixed: The subtitle in the LHN follows the pattern `Workspace Name • #roomName`
after-fix

I'm okay with _not_ pursuing the route of rebasing the fix on top of a older main commit if you have an alternate proposal (such as putting this PR on `HOLD` for `X`), but I'm just not currently understanding the need 😅

**Comment by abdulrahuman5196** [comment]
@amyevans 

You are actually checking out a older commit head and cherry picking this fix on top of that and testing. It will work that way.

In your first step `git checkout 2977c04baf`(this commit is from may 30). 

If instead of the above, if you checkout the `git checkout  main` and cherry pick this it won't work. Like the skeleton view itself is not loading on main or on latest commits. Same will happen if you checkout this PR directly.


https://github.com/Expensify/App/assets/46707890/89a2eeb1-d1f0-4de9-9610-a8a0cc3164a7




**If we want we can test the same way as your tested like checking out old commit and cherry picking fix commit on top of that(Basically that's the rebase if we want to test locally). Do we want to do that way so that we are not blocked on main fix?**

**Comment by abdulrahuman5196** [comment]
Anyways we don't have a GH issue for the skeleton view not present issue on main. So I am following to test with this way https://github.com/Expensify/App/pull/20235#issuecomment-1579058202 so that we don't have to wait.

**Comment by amyevans** [comment]
> Anyways we don't have a GH issue for the skeleton view not present issue on main. So I am following to test with this way https://github.com/Expensify/App/pull/20235#issuecomment-1579058202 so that we don't have to wait.

Yes, let's test that way. (Side note, earlier I think we were saying the same thing, just somehow not understanding one another 😄). Thanks!

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>




https://github.com/Expensify/App/assets/46707890/4ea3ed9d-4ac5-44b3-b3e2-e3d72d15796c




</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://github.com/Expensify/App/assets/46707890/f7a16c0e-12d0-467a-acc3-b02230d26a6f

</details>

<details>
<summary>Mobile Web - Safari</summary>




https://github.com/Expensify/App/assets/46707890/22d1244a-8fbb-4a1c-bd2a-a861e1e963f4





</details>

<details>
<summary>Desktop</summary>




https://github.com/Expensify/App/assets/46707890/81391045-e811-4188-a8a0-fddcb6621eca


</details>

<details>
<summary>iOS</summary>




https://github.com/Expensify/App/assets/46707890/eb30d003-3bb9-410e-a7fb-f030c7ea62ae




</details>

<details>
<summary>Android</summary>






</details>

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours now @amyevans . (I think we got derailed in the conversions a bit)

**Pull request merged**
