### PR TITLE
Only trigger deploy blocker notifications on issues

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details
We were triggering the deploy blocker notifications on PRs which could include forks, which was causing issues here: https://github.com/Expensify/App/actions/runs/1140938643

### Tests
1. Merge this PR
2. Add a `DeployBlockerCash` label to a PR, verify it does not ping in Slack
3. Add a `DeployBlockerCash` label to a issue, verify it does ping in Slack

### CODE REVIEW

**Comment by aldo-expensify** [comment]
nab: If I'm understanding correctly, we are not listening anymore events related to pull request, maybe we should comment or remove the lines handling events related to pull request:

https://github.com/Expensify/App/blob/8dc03e3d87bb11d3300e67716c2ca469c4d5b442/.github/workflows/deployBlocker.yml#L26-L31

The may confuse another developer in thinking that this is still processing pull requests.


Besides that, I don't know how to test this safely. The modified lines make sense to me, but I guess this should be also reviewed by someone else :)

**Comment by AndrewGable** [comment]
Nice find @aldo-expensify! The linked code is actually dead and I will update to remove it.

**Comment by roryabraham** [comment]
@AndrewGable I'll hold off on reviewing until you've removed the dead code. Just ping me when it's ready!

**Review by aldo-expensify — APPROVED** [review]
Looking good to me!

**Review by roryabraham — APPROVED** [review]

**Comment by roryabraham** [comment]
Going to use this PR and the linked issue to test this.

**Comment by roryabraham** [comment]
Yep, that didn't do anything, which is what we want. We could maybe remove the label and leave a comment to explain that only issues (not pull requests) can be deploy blockers. But we don't have to – that's a nice-to-have. What do y'all think?

**Comment by roryabraham** [comment]
This worked for issues: https://expensify.slack.com/archives/C01GTK53T8Q/p1630438694222000

So this is a QA-pass 🎉

**Pull request merged**
