### PR TITLE
Add manual address to debitCardPage

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
Customers have no way to enter their address if they can't find it in our Address Search component. This is a temporary fix while we are working on a better solution for it. It follows the same pattern found [here](https://github.com/Expensify/App/blob/main/src/pages/ReimbursementAccount/CompanyStep.js#L229-L282).

### Fixed Issues
$ https://github.com/Expensify/App/issues/6794

### Tests
1. Log into the app.
2. Navigate to `Profile > Payments > Add Payment method > Debit card`
3. Verify that clicking `Can't find your address? Enter it manually` displays the `City`, `State` and `Zip code` fields.
4. Do the same for `/bank-account/company`, `/bank-account/personal-information` and `/bank-account/contract`

### QA Steps
Tests above.

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

#### Web

web

#### Mobile Web

mweb

#### Desktop

desktop

#### iOS

ios

#### Android

android

### CODE REVIEW

**Comment by AndrewGable** [comment]
Was this @Expensify/design approved? The message looks a little tight in terms of spacing to my eye, so just want to make sure!

**Comment by luacmartins** [comment]
I didn't check, but I assumed so since we have been using this exact same design in the VBA flow for about a month now. That being said, I'd love their opinion here.

**Comment by megankelso** [comment]
thanks for catching Andrew! 

yes, there should be more space between the form and the hint. In Figma, it is designed to be 8 pixels between the two. Also, should that text be grey? I think blue is most appropriate for a link, but I assume this isn't one?

Screen Shot 2021-12-20 at 8 47 39 AM

**Comment by shawnborton** [comment]
I agree, let's definitely add some spacing. And I agree with Megan, the whole thing doesn't need to be blue, but how about just the "Enter it manually" part? I think that actually is a link that unfurls a larger form with more fields. 

So in summary:
- try the spacing at 4px and 8px between form and hint, we can pick which one we like best
- make just the latter part of the hint text the blue link style

Thoughts on that?

**Comment by luacmartins** [comment]
Thanks for the input @megankelso and @shawnborton! Here's how it looks with 4px (top) and 8px (bottom), both look good to me;
4px
8px

**Comment by shawnborton** [comment]
8px gap looks nice to me. What do you think Megan?

**Comment by megankelso** [comment]
agreed!

**Comment by luacmartins** [comment]
Updated!

**Comment by luacmartins** [comment]
Andrew is off for the holidays, adding somebody else for the review.

**Review by AndrewGable — APPROVED** [review]

**Comment by luacmartins** [comment]
Nvm my previous comment, Andrew just approved this. Self-merging.

**Pull request merged**
