### PR TITLE
Stop "retrying" requests that fail in the main queue

### PR DESCRIPTION
**Pull request by marcaaron**
### Details

Holding on:
- [ ] https://github.com/Expensify/Expensify/issues/208280
- [ ] https://github.com/Expensify/Expensify/issues/208185

### Fixed Issues (Related to)
https://github.com/Expensify/Expensify/issues/208281

### Tests

1. Block a the `UpdateLastRead` request that is triggered whenever a report is switched to (see tip [here](https://umaar.com/dev-tips/68-block-requests/))
1. Navigate to a report while online
1. Verify that the request is not getting retried at all and doesn't throw any errors in the JS console 

- [ ] Verify that no errors appear in the JS console

### PR Review Checklist

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps

Same as Tests

- [ ] Verify that no errors appear in the JS console

### Screenshots
❌

### CODE REVIEW

**Comment by marcaaron** [comment]
Realizing that an interesting side effect of these changes will be that all things that are currently "retryable" and optimistic will not be optimistic anymore after. 🤔 

We would be able to fix that by making those requests have a `persist: true`, but in the doc we decided this would be a gradual process. Report comments are the only thing that will work with this new system at the moment.

I think we will need to update any write requests in this PR and make sure they are retryable.

**Comment by marcaaron** [comment]
Gonna expand on this problem because on further reflection I don't think we can actually get rid of `shouldRetry` until all optimistic (but not persisted) actions are refactored over to the new API system being proposed in [this thread](https://expensify.slack.com/archives/C02HWMSMZEC/p1652736545790429). 

We can still kill the "retry counter" logic though for things outside of the Sequential Queue.

**Current behavior:**

- Write request (w/o persist: true) is made while we are offline
- It goes into the main queue because we are offline and stays there because it’s “retryable” (actually all requests are retryable unless we specify that they are _not_)
- Come back online and the main queue will process again (basically giving us the same “optimistic” behavior, but without the “persistance” that report comments have)

Gonna make those changes now so I can merge the good parts of this and wrap up the Network Improvements project as the retry logic is holding on the API changes.

**Comment by marcaaron** [comment]
Gonna expand on this problem because on further reflection I don't think we can actually get rid of `shouldRetry` until all optimistic (but not persisted) actions are refactored over to the new API system being proposed in [this thread](https://expensify.slack.com/archives/C02HWMSMZEC/p1652736545790429). 

We can still kill the "retry counter" logic though for things outside of the Sequential Queue.

**Current behavior:**

- Write request (w/o persist: true) is made while we are offline
- It goes into the main queue because we are offline and stays there because it’s “retryable” (actually all requests are retryable unless we specify that they are _not_)
- Come back online and the main queue will process again (basically giving us the same “optimistic” behavior, but without the “persistance” that report comments have)

Gonna make those changes now so I can merge the good parts of this and wrap up the Network Improvements project as the retry logic is holding on the API changes.

**Comment by marcaaron** [comment]
@roryabraham adding you here to have a second set of eyes and my rambling comments above might be interesting to you

**Comment by marcaaron** [comment]
Bump

**Review by roryabraham — APPROVED** [review]

**Comment by marcaaron** [comment]
What @roryabraham said + also want to quickly document that a consequence of this change is that some quasi-optimistic writes that kind of work offline will be broken by this change in a very minor way and only in the situation where we suddenly go offline or the site is down.

Offline features for these requests **will still mostly work while you are offline**. We just will stop handling that edge case for all commands (except `Report_AddComment` since it is in the `SequentialQueue`). Ultimately, we are going to rip this code out anyway and will be more explicit in the future about which things will be retried and which will not.

This will also free up @madmax330 to focus on the retry changes for the `SequentialQueue` without having to consider a system where both reads and writes could be retried on failure.

**Comment by Julesssss** [comment]
Please ignore these duplicated messages, we only deployed once but the message appears each the iOS deploy fails.

**Pull request merged**
