### PR TITLE
[HOLD] Create a useResponsiveLayout hook

### PR DESCRIPTION
**Pull request by rayane-d**
### Details

Related Eslint rule PR: https://github.com/Expensify/eslint-config-expensify/pull/82
### Fixed Issues

$ https://github.com/Expensify/App/issues/30528
PROPOSAL: https://github.com/Expensify/App/issues/30528#issuecomment-1783343278

### Tests

Needs to be tested on web/mweb:

1. Logout from the application.
2. Try to access any public room(eg. http://localhost:8082/r/3207869973997783).
3. Click on sign in button either from header or footer and it opens the sign page in modal and it looks proper.
4. Scroll down and verify the footer of the sign in page looks proper and items are aligned vertically.

- [x] Verify that no errors appear in the JS console

### Offline tests

N/A
### QA Steps

Same as above tests.
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

N/A (Only testable on Web and mWeb)
</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/77965000/8e2921ff-2585-48a6-8a81-b60119619074

</details>

<details>
<summary>iOS: Native</summary>

N/A (Only testable on Web and mWeb)
</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/77965000/2382dfcb-1914-40b8-a2c4-78ffb638bdec

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/77965000/a4ff39b2-11a2-49b4-8548-a67b575ba1d1

</details>

<details>
<summary>MacOS: Desktop</summary>

N/A (Only testable on Web and mWeb)
</details>

### CODE REVIEW

**Comment by getusha** [comment]
@rayane-djouah can you fix conflict and complete the checklist? additionally it would be great if you could explain why the first PR is closed.

**Comment by getusha** [comment]
@rayane-djouah i am seeing a ton of usage from `useWindowDimensions`

Screenshot 2023-12-04 at 12 54 45 PM

**Comment by getusha** [comment]
### BUG: Unable to open context menu
1. Open any chat
2. Right click on report item

https://github.com/Expensify/App/assets/75031127/2d89c7e9-a101-4cd2-a46a-354130ba66f4

**Comment by getusha** [comment]
### BUG: Emoji picker on small screen looks strange
1. Resize screen
2. Open emoji picker.

Screenshot 2023-12-04 at 1 16 15 PM

**Comment by getusha** [comment]
@rayane-djouah the progress is really slow, is there anything we should know?

**Comment by getusha** [comment]
>Bug 5: when replacing useWindowDimensions with useResponsiveLayout in [AuthScreens.tsx](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.tsx):

We should investigate why.

**Comment by getusha** [comment]
@rayane-djouah Lint is failing lets fix it.

**Comment by roryabraham** [comment]
Anything I can do to help here? If you think it would be helpful we can split this into multiple PRs so that there's fewer conflicts and a lower chance of regressions in each PR

**Comment by getusha** [comment]
@rayane-djouah i think we should also rename props named `isSmallScreenWidth`

Screenshot 2023-12-18 at 4 42 26 PM

**Comment by getusha** [comment]
>@getusha this props are coming from the withWindowDimensions HOC [here](https://github.com/Expensify/App/blob/c96a2093f20f568465b3b75c11b2c5632c80bdeb/src/components/withWindowDimensions/index.tsx#L66C1-L66C109), should we rename it?

In that case we should leave it, wdyt @roryabraham?

**Comment by roryabraham** [comment]
I think for the scope of those PR we can ignore making any changes to `withWindowDimensions` and as we migrate to functional components we can get rid of any remaining uses of `withWindowDimensions` in favor of `useResponsiveLayout`. If there are any uses of `withWindowDimensions` in a functional component, I'd say those are in-scope to be migrated to `useResponsiveLayout`.

Does that sound good?

**Comment by getusha** [comment]
I agree with @roryabraham, @rayane-djouah lets replace the usages of `withWindowDimensions` in functional components/pages.

**Comment by roryabraham** [comment]
Mentioned this above, but I'd advise that we split this up into a few smaller PRs to make it easier to get stuff over the finish line and reduce the likelihood of conflicts or regressions

**Comment by getusha** [comment]
Based on the changes in this PR, we could break it down into several PRs as follows:
1. A PR introducing useResponsiveLayout.
2. A PR to add the `inRHP` prop
3. A PR to replace usages of `isSmallScreenWidth` in components.
4. A PR to remove `inModal` prop, which i think will be redundant after `inRHP` is introduced.
5. A PR to rename parameter names in various functions (which doesn't have much effect).

However, I'm not sure if this approach would help. @roryabraham @rayane-djouah What are your thoughts on it?

**Comment by roryabraham** [comment]
yeah, maybe also a separate PR to migrate any remaining uses of `withWindowDimensions` in functional components? I'm not going to enforce any separation of PRs, so it's up to @rayane-djouah what they think is best. My advice would be to split this task up though.

**Comment by roryabraham** [comment]
Looks like we've got two new PRs that this one will HOLD on. @rayane-djouah can you please put the `[HOLD]` prefix in the title of any PRs that should be on HOLD so that the order of operations here is clear?

**Pull request closed without merging**
