### PR TITLE
resolve app crash on navigation

### PR DESCRIPTION
**Pull request by sourcecodedeveloper**
### Fixed Issues

$ https://github.com/Expensify/App/issues/27085
PROPOSAL: https://github.com/Expensify/App/issues/27085#issuecomment-1712800059

### Tests

1. Navigate to /request/new/confirmation link
2. Observe the RHP opens as expected.
3. Close RHP and paste the link /request/new/confirmation in chat window
4. Click on the link and notice RHP open without any crashes
- [x] Verify that no errors appear in the JS console

### QA Steps

mentioned in Tests
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

[web.webm](https://github.com/Expensify/App/assets/141340971/44463499-02d7-41f5-b3e0-e8ed536c4c2c)

</details>

<details>
<summary>Mobile Web - Chrome</summary>

[android-web.webm](https://github.com/Expensify/App/assets/141340971/f87ef80a-b3d6-47cd-8a50-bc621be40b60)

</details>

<details>
<summary>Mobile Web - Safari</summary>

[ios-web.webm](https://github.com/Expensify/App/assets/141340971/38e43c99-2fde-4f2e-a0e2-7ed6abc23211)

</details>

<details>
<summary>Desktop</summary>

[desktop.webm](https://github.com/Expensify/App/assets/141340971/efa89ba8-f3ca-4a59-940f-69329d29e9f8)

</details>

<details>
<summary>iOS</summary>

[ios.app.webm](https://github.com/Expensify/App/assets/141340971/ffac4dd7-9fce-468a-972b-d30f323b932d)

</details>

<details>
<summary>Android</summary>

[android.webm](https://github.com/Expensify/App/assets/141340971/3f77567a-19de-46ea-91cc-dafb99e17a8f)

</details>

### CODE REVIEW

**Comment by sobitneupane** [comment]
@sourcecodedeveloper You have not uploaded screen recordings for all platforms. Please let me know once you upload the screen recordings.

**Review by sobitneupane — COMMENTED** [review]
@sourcecodedeveloper App crashes if we click on a confirmation link with reportID
( for example: https://staging.new.expensify.com/request/new/confirmation/12)


https://github.com/Expensify/App/assets/25876548/a42e207a-95a2-4941-93c8-6221d997c8e1

**Comment by sourcecodedeveloper** [comment]
> @sourcecodedeveloper You have not uploaded screen recordings for all platforms. Please let me know once you upload the screen recordings. You need to add test steps and QA steps as well.

@sobitneupane I have added test steps and QA steps and some screenshots videos remain for mobile. In the meantime please don't hold back on uploading the screenshots videos required by the reviewer checklist as well as that would assist in testing as well.

**Comment by sourcecodedeveloper** [comment]
> @sourcecodedeveloper App crashes if we click on a confirmation link with reportID ( for example: https://staging.new.expensify.com/request/new/confirmation/12)
> Screen.Recording.2023-09-20.at.17.34.55.mov

@sobitneupane there is no mention of any reportID in the reported [issue](https://github.com/Expensify/App/issues/27085)
nor any steps mentioned by @situchan include any reportID. If there is another pull request open handling the reportId then it would be better to resolve the reportID crash in that PR. Or atleast get @situchan to update the Action Performed step of [issue](https://github.com/Expensify/App/issues/27085) to include reportID.

**Comment by sobitneupane** [comment]
@sourcecodedeveloper The issue looks very similar but it might have different root cause. If the issue is not complex, let's handle it here.

**Comment by sourcecodedeveloper** [comment]
> @sourcecodedeveloper You have not uploaded screen recordings for all platforms. Please let me know once you upload the screen recordings. You need to add test steps and QA steps as well.

@sobitneupane screen recordings have been updated. Please review.

**Comment by sourcecodedeveloper** [comment]
> @sourcecodedeveloper The issue looks very similar but it might have different root cause. If the issue is not complex, let's handle it here.
@sobitneupane yes exactly because it might have different root cause, the testing steps would need to be updated by @situchan  Agreed if the issue is not complex @situchan should be able to reproduce the crash and update the testing steps so that there are no duplicate pullrequests solving the reportid issue.

**Comment by sobitneupane** [comment]
We have decided to handle the case in another PR. So, I will review the PR shortly.

**Comment by sourcecodedeveloper** [comment]
> We have decided to handle the case in another PR. So, I will review the PR shortly.

Thanks

**Comment by sobitneupane** [comment]
@sourcecodedeveloper I am unable to replicate the issue in latest main. Looks like we won't require this PR any longer.

**Comment by situchan** [comment]
No need to tag me N times in multiple PRs.
@sourcecodedeveloper we don't need to merge PR fixing the issue which is not reproducible anymore thanks to other PR.
You're worrying about compensation but internal team will take care of that as per contributing guideline.

**Comment by sourcecodedeveloper** [comment]
> No need to tag me N times in multiple PRs. @sourcecodedeveloper we don't need to merge PR fixing the issue which is not reproducible anymore thanks to other PR. You're worrying about compensation but internal team will take care of that as per contributing guideline.

@situchan Discussions are being done and tagging is being done as needed, if being tagged is bothering you maybe just disable your notifications. The issue is still reproducible in branch 1.3.66.3. The issue should also be tested in reported branch version indicated by reporter. Because obviously there is going to be time gap when the proposal is awarded, pullrequest made and tested. If the reported is tested directly against the latest main and not the reported branch then there is a large room for bugs to resurface because the latest main would be addressing other issue not related to the PR in question.

@sobitneupane please discuss with internal team regarding testing PR against reported build version and latest main because testing the reported issue against latest main only will leave the possibility of bugs resurfacing at later time. Also there is worry about compensation regarding the PR being not merged after proposal has been awarded, time and effort was spent.

**Pull request closed without merging**
