### PR TITLE
Add a new template for requesting a library to be added in package.json

### PR DESCRIPTION
**Pull request by tgolen**
### Fixed Issues
Part of https://github.com/Expensify/Expensify/issues/334255

### Tests
None

### Offline tests
None

### QA Steps
None

### PR Author Checklist
No checklist required for this change since it's only adding a GH issue template

### CODE REVIEW

**Comment by tgolen** [comment]
cc @AndrewGable @mountiny

**Review by AndrewGable — APPROVED** [review]

**Comment by mountiny** [comment]
Copy looks good to me, @grgia all yours!

**Comment by tgolen** [comment]
The tests will fail on this PR due to not having any checklists. This is OK to bypass and merge since the changes do not change any code.

**Comment by tgolen** [comment]
bump @grgia for review please

**Review by grgia — APPROVED** [review]

**Comment by grgia** [comment]
https://github.com/Expensify/App/pull/31035#issuecomment-1804105744 ^

**Pull request merged**
