### PR TITLE
Removed border from the Picker

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details
There were two borders around the Picker. I have removed the inner border. https://github.com/Expensify/App/issues/4972#issuecomment-910075558

cc: @shawnborton 

### Fixed Issues

$ https://github.com/Expensify/App/issues/4972

### Tests | QA Steps
1. Open NewDot on the Web browser.
2. Zoom the window to enlarge the Language Picker on the Login page.
3. There should not be two borders like shown in the issue.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

image
image

#### Mobile Web

fff

#### Android

ff

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@parasharrajat we should also remove  `styles.picker`, it is unused.

**Comment by parasharrajat** [comment]
It seems you are correct. @meetmangukiya CC: @kakajann Why do we have this style if this is unused? Any reason?

**Comment by meetmangukiya** [comment]
I think it just got phased out through refactorings seeing the blame

**Review by Luke9389 — DISMISSED** [review]
Excellent. Thanks!

**Comment by Luke9389** [comment]
I'll hold off on merging until there's a commit for `styles.picker` (I agree we should poll the contributors who've touched it, but let's not wait more than a few days).

**Review by Luke9389 — APPROVED** [review]

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-15.  :confetti_ball:

**Pull request merged**
