### PR TITLE
Save preferred locale in NVP

### PR DESCRIPTION
**Pull request by luacmartins**
cc @chiragsalian 

Related Web-E PR: https://github.com/Expensify/Web-Expensify/pull/31508

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/167702

### Tests
1. Open app in two different devices, e.g. web and desktop and login with the same user.
2. On web, go to `Settings > Preferences` and change the `Language`.
3. Confirm that the language changes on Desktop too and vice-versa.

### QA Steps
Steps above.

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

#### Web

https://user-images.githubusercontent.com/22219519/126234866-a21cff2c-d4c4-451b-b67e-e1563325312a.mov

#### Mobile Web

https://user-images.githubusercontent.com/22219519/126234878-b8bb586c-506f-49de-9350-091dbd6cd735.mov

#### Desktop

https://user-images.githubusercontent.com/22219519/126234935-1f40f4c9-3bb5-48b3-a34e-12099b96f5c1.mov

#### iOS

https://user-images.githubusercontent.com/22219519/126234893-a1a0b70b-b84c-4f0b-bf01-207fcf1beab7.mov

#### Android

https://user-images.githubusercontent.com/22219519/126234954-7d9f2e7e-3e15-4952-8d2b-8da72194e6fd.mov

### CODE REVIEW

**Review by thienlnam — COMMENTED** [review]
Changes look good, going to test this tommorow

**Comment by luacmartins** [comment]
Hold removed [here](https://github.com/Expensify/Web-Expensify/pull/31508#issuecomment-882882562)

**Comment by luacmartins** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by thienlnam — CHANGES_REQUESTED** [review]
I'm testing it but the changes don't seem to be syncing between my web and desktop apps. Even if I change it Spanish on Desktop, and refresh on Web, the Web is still all in english

**Comment by luacmartins** [comment]
Are you seeing any console or network errors?

**Comment by thienlnam** [comment]
Hmm looks like I'm getting some CORS errors, might just be my development setup

Screen Shot 2021-07-20 at 10 51 53 AM

**Comment by luacmartins** [comment]
Maybe [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1626471154432800?thread_ts=1626393494.381300&cid=C01GTK53T8Q) might help? I'm not sure what solved it for me.

**Comment by thienlnam** [comment]
Hmm still not able to get it to work but since it's a cors issue and you were able to get it to work successfully, we'll have it test again during QA

**Review by thienlnam — APPROVED** [review]
Approving code changes

**Pull request merged**
