### PR TITLE
Revert "Merge pull request #4085 from Expensify/chirag-revert-3979"

### PR DESCRIPTION
**Pull request by dklymenk**
This reverts commit c2f92b63d2e8f43310162ccddea32446cbbd5753. 

@chiragsalian this a PR related to our discussion here https://github.com/Expensify/Expensify.cash/pull/3979#issuecomment-880938773

### Fixed Issues

$ #3743
$ #3293

### Tests / QA Steps
 

1. Send a message. You should see it in LHN.
2. Delete that message. The LHN should say "[Comment deleted]".
3. Refresh the page. Wait a few seconds. The LHN should still say "[Comment deleted]".
4. Send IOU. You should see "Requested €123 from A" or something like that in LHN.
5. Refresh the page. Wait a few seconds. It should still say "Requested €123 from A" and not "[Comment deleted]". (This one requires #3737 to be fixed).

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/64093836/125278225-20de6500-e31b-11eb-8a8b-712270ebf141.mp4

#### Mobile Web

https://user-images.githubusercontent.com/64093836/125286644-b9c5ae00-e324-11eb-947a-ed746b6f4369.mp4

#### Desktop

https://user-images.githubusercontent.com/64093836/125287448-97806000-e325-11eb-8dd0-05ef737ba620.mov

#### iOS

https://user-images.githubusercontent.com/64093836/125287700-eaf2ae00-e325-11eb-9ae3-db1d93a26886.mp4

#### Android

https://user-images.githubusercontent.com/64093836/125279106-343e0000-e31c-11eb-8421-efde79909afc.mp4

### CODE REVIEW

**Comment by chiragsalian** [comment]
Hmm, I don't get why we show "[Comment deleted]" when there are previous messages. If it's the first and only message then I think "[Comment deleted]" is fine but otherwise couldn't we show the previous message in the LHN @dklymenk?

I briefly checked the code and it looks like we refer `lastActionMessage` but that's something received from the backend. So I think it's nice that you have this fallback for "[Comment deleted]" but I think we should update our backend to return the lastActionMessage that actually has message content. But that will involve further testing to confirm nothing else is broken, thoughts?

**Comment by dklymenk** [comment]
> Hmm, I don't get why we show "[Comment deleted]" when there are previous messages. If it's the first and only message then I think "[Comment deleted]" is fine but otherwise couldn't we show the previous message in the LHN @dklymenk?
> 
> I briefly checked the code and it looks like we refer `lastActionMessage` but that's something received from the backend. So I think it's nice that you have this fallback for "[Comment deleted]" but I think we should update our backend to return the lastActionMessage that actually has message content. But that will involve further testing to confirm nothing else is broken, thoughts?

I don't think showing the actual last message during initial load is an issue, however updating it in real time is. I have had submitted 2 or 3 proposals in total with an implementation that works, but no matter what you do you are basically required to fetch the next last message from onyx storage every time you receive a Pusher update. It has been determined that if we cannot implement this without onyx, we shouldn't do it and instead stick to `[Comment deleted]`. See these 2 comments:  https://github.com/Expensify/App/issues/3743#issuecomment-877505727 https://github.com/Expensify/App/issues/3743#issuecomment-878138423

Also the original PR https://github.com/Expensify/App/pull/3979 has been approved and merged. The only reason it was reverted in the first place, as you probably remember, is because in combination with https://github.com/Expensify/App/issues/3737 it resulted in `[Comment deleted]` message to be shown if the last comment was an IOU. Now that #3737 is fixed and the original PR is still applicable, it means that it is still valid, right?

**Comment by chiragsalian** [comment]
Yup, i think your solution here is totally good. I guess I was thinking of another improvement that could be done on the backend to make the user experience even better which adds to the code you have here. But I guess that's for another time.

**Review by chiragsalian — DISMISSED** [review]
Looks good to me. But i cannot merge it at this time since the parent issue has N6-HOLD label. So i'll go ahead and add HOLD to this PR. Once the N6-HOLD label is removed let me know and I'll merge this PR 🙂

**Comment by mallenexpensify** [comment]
Per @parasharrajat and @NikkiWines comment above, I removed `[HOLD]` from the title. @chiragsalian can you review and/or help move this along?  Thanks

**Comment by chiragsalian** [comment]
Oh, i was waiting for an update from @dklymenk to know when it's ready for review. Can you let me know @dklymenk when it's ready for review? I see you have a travis error so at the moment I'm assuming you are working on addressing those. If not or you need any help let me know 🙂

**Comment by dklymenk** [comment]
Oh, sorry. I completely forgot that you were waiting for my signal on hold removal.

No I am not working on resolving that e2e test issue. It came up after I fixed a conflict 3 weeks ago. It looks like some package wasn't fetched properly during installation or something. My changes don't touch anything in iOS folder, so I am pretty sure that error has nothing to do with this PR.

Please let me know If you want me do anything. I just want these issues get closed already.

Once again I am sorry for not writing here about hold removal. I honestly thought you were all busy or something.

**Comment by NikkiWines** [comment]
@dklymenk you might try merging main into your branch and see if that resolves the e2e issue. This branch is 662 commits behind Expensify:main, so it's a good idea to merge it even if it doesn't end up fixing the tests.

**Comment by dklymenk** [comment]
Merged main into the branch. Tested the changes. Still looking good.

The e2e test seems to have passed the stage it failed at last time. Hopefully, it finishes successfully and we get to merge this.

**Comment by dklymenk** [comment]
@chiragsalian After merging main all tests have passed. The PR is ready for review once again.

**Review by chiragsalian — APPROVED** [review]
LGTM, i believe we have a merge freeze this week so i shouldn't merge this today and so i'll merge this next week.

**Pull request merged**
