### PR TITLE
Add Welcome Screen

### PR DESCRIPTION
**Pull request by akshayasalvi**
### Details

- Adds a Welcome Screen step for the first login of the user after setting the password
- User has an option to upload Avatar, update name and add secondary login
- User also has an option to skip the step completely

### Fixed Issues

$ https://github.com/Expensify/App/issues/5079

### Tests
1. Tested with a fresh account creation
2. Tested with skipping the step
3. Tested with an unvalidated account with validation link expired
4. Tested an existing account Forgot password flow

### QA Steps

1. Visit the app as Guest
2. Enter a new email address as a fresh signup
3. Copy the magic link received on the email and hit the URL
4. Enter the password in the form and click on Submit
5. You'll be shown the Welcome step form
6. Fill the details and verify in the Profile page that all the data is stored.

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

Screenshot 2022-01-03 at 5 04 36 AM

#### Mobile Web

image

### CODE REVIEW

**Comment by akshayasalvi** [comment]
@iwiznia One scenario is failing. Assume that I fill the `Welcome` step information and enter a phone number that is already linked to another account( or any backend error for phone number), it still redirects to the home report page.

This is because, by the time I submit the secondary login API, the user is already logged in with an auth token. 

I can fail the user to log in but that would just mean that not setting credentials in Onyx. A refresh will still cause unexpected behavior for the user. 

Do we have an API that validates if the phone number already exists or runs those validations?

**Comment by iwiznia** [comment]
> Do we have an API that validates if the phone number already exists or runs those validations?

No, we don't. Can we call the API and if it fails, show an error to the user so they can set a different phone number?

**Comment by akshayasalvi** [comment]
>  Can we call the API and if it fails, show an error to the user so they can set a different phone number?

Can do but refreshing/reloading the page will not work. Won't show the welcome page and will redirect to the home screen.

**Comment by iwiznia** [comment]
I think that's fine.

**Comment by iwiznia** [comment]
> by then the session is already set, so it skips the error goes to the Home page

Why does it skip it? Can't you make it not skip it?

> Even if I try to force the error by clearing session, etc. I get errors like Session already expired. Calling the whole sequence in the step 1, also throws the same error.

I don't understand this... if you clear the session, then no API call will succeed.

**Pull request closed without merging**
