### PR TITLE
Update the HTML entity parsing

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details
1. Now all the HTML entities are supported.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4759

### Tests | QA Steps
1. open newDot on the web.
2. Copy some text that contains whitespaces or other HTML entities from Google Docs or any other application.
3. Paste that into the composer.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### WEB | Desktop
https://user-images.githubusercontent.com/3885503/131089984-3a826df4-40bf-4b17-892d-fbe4be18f367.mov

### CODE REVIEW

**Review by Beamanator — COMMENTED** [review]
Note: The original post in slack ([here](https://expensify.slack.com/archives/C01GTK53T8Q/p1627358860323100)) noted that newlines were stripped too -> should that be fixed in this issue or did you purposefully leave it out?

> I can't record this behavior as...

Are you sure? :D What about something like this?

https://user-images.githubusercontent.com/3885503/131089984-3a826df4-40bf-4b17-892d-fbe4be18f367.mov

**Review by Beamanator — APPROVED** [review]
All you @tgolen

**Comment by Julesssss** [comment]
Whoops, we missed the notification here as the issue wasn't exported. My fault.

**Comment by Julesssss** [comment]
Will update the issue manually now.

**Pull request merged**
