### PR TITLE
Add emojis in dummy PR to retest PR #1848

### PR DESCRIPTION
**Pull request by roryabraham**
Dummy PR to retest https://github.com/Expensify/Expensify.cash/pull/1848

### CODE REVIEW

**Review by AndrewGable — APPROVED** [review]

**Comment by AndrewGable** [comment]
Merging to test deploys!

**Comment by botify** [comment]
@AndrewGable looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Comment by roryabraham** [comment]
Tags were pushed: https://github.com/Expensify/Expensify.cash/runs/2135267970?check_suite_focus=true

**Comment by roryabraham** [comment]
Staging deploys were triggered: 

image

**Pull request merged**
