### PR TITLE
[HOLD] Revert "Fix anchor renderer for links in report messages & clean up"

### PR DESCRIPTION
**Pull request by marcaaron**
Reverts Expensify/App#10144

**Fixes:** 

$ https://github.com/Expensify/App/issues/10431

### CODE REVIEW

**Comment by francoisl** [comment]
I restarted the failed tests, let's see if it helps 🤞 

Also we'd want to get that CP'ed to staging, correct?

**Comment by marcaaron** [comment]
Passing but @roryabraham [says this will break stuff](https://expensify.slack.com/archives/C03TQ48KC/p1660846939853569?thread_ts=1660759590.910429&cid=C03TQ48KC) so maybe we hold off?

**Comment by francoisl** [comment]
Yeah I'm not 100% clear on the suggested way to go either, let's wait until he's back.

**Comment by roryabraham** [comment]
Sorry, the main thing that's important is that if we CP a revert, we have to wait until the next release cycle before merging this same change back into main.

**Comment by marcaaron** [comment]
I think this revert is no longer needed as we chose to deploy the broken code to production because it wasn't blocker-y enough.

**Pull request closed without merging**
