### PR TITLE
Removed the hasText condition from getIconWidthAndHeightStyle utils

### PR DESCRIPTION
**Pull request by jayeshmangwani**
### Explanation of Change

Removed the `hasText` condition from `getIconWidthAndHeightStyle` to ensure icon-only buttons use the same icon size as regular buttons.
### Fixed Issues

$ https://github.com/Expensify/App/issues/51355
PROPOSAL: https://github.com/Expensify/App/issues/51355#issuecomment-2433011958

### Tests

1. Navigate to Settings -> Profile -> Edit Photo.
2. Select Upload Photo and choose any image.
3. Confirm that the "Rotate" icon at the bottom has the following dimensions:
- Background: 40x40
- Icon: 16x16

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests

### QA Steps

- [x] Verify that no errors appear in the JS console

Same as Tests
### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Screenshot_2024-11-01-17-56-04-90_40d2c9e2d8fb5b5aba3904834590021e

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot 2024-11-01 at 17 37 20

</details>

<details>
<summary>iOS: Native</summary>

Simulator Screenshot - iPhone SE (3rd generation) - 2024-11-01 at 17 43 53
Simulator Screenshot - iPhone SE (3rd generation) - 2024-11-01 at 17 44 07
Simulator Screenshot - iPhone SE (3rd generation) - 2024-11-01 at 17 44 11

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Simulator Screenshot - iPhone SE (3rd generation) - 2024-11-01 at 17 33 42

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>
Screenshot 2024-11-01 at 17 30 41
Screenshot 2024-11-01 at 17 31 08

</details>

<details>
<summary>MacOS: Desktop</summary>
Screenshot 2024-11-01 at 17 46 41
Screenshot 2024-11-01 at 17 46 59
Screenshot 2024-11-01 at 17 47 09

</details>

### CODE REVIEW

**Comment by shawnborton** [comment]
Screenshots look good to me from a design perspective 👍

**Comment by rojiphil** [comment]
@jayeshmangwani Thanks for the PR. Our changes adversely impact the icons in the context menu and I think we need a fix. In particular, please observe the `Reply in thread` and `Mark as unread` button icons which are smaller now. Here is a test video demonstrating the same. 


https://github.com/user-attachments/assets/a9e1529a-a51b-40c8-8b5b-ec0e66e4fcee

**Comment by jayeshmangwani** [comment]
Great catch @rojiphil ! It looks like we intentionally added the small button size here.
https://github.com/Expensify/App/blob/bef062b4caa7f665159dc107911e708031e648c4/src/components/ContextMenuItem.tsx#L123-L126

We need to remove the `small` button type from here to match the existing sizing as the staging version and instead need to pass height and width value as iconSizeSmall(16).

@shawnborton @dannymcclain What are your thoughts? Should we match the exact sizing from the staging version here, or stick with the small button size for [these two buttons](https://github.com/Expensify/App/pull/51775#issuecomment-2453519725)?

**Comment by shawnborton** [comment]
Personally I don't think we should touch the icon size in the mini menu/context menu that shows here: 
CleanShot 2024-11-04 at 08 50 44@2x

Those feel like unique and different UI elements, or at least they are for the time being. So I would just make sure to keep them exactly as-is. 

cc @Expensify/design for a gut check too.

**Comment by dannymcclain** [comment]
I agree with Shawn and Jon. (Also, those teeny tiny icons are hilarious 😂)

**Comment by jayeshmangwani** [comment]
Cool, Updated the icon size to match the current production version.

**Comment by jayeshmangwani** [comment]
@rojiphil since we're using the small button(Icon only) in several places, I'll start by comparing those icons with the prod version before moving forward.

**Comment by rojiphil** [comment]
> @rojiphil since we're using the small button(Icon only) in several places, I'll start by comparing those icons with the prod version before moving forward.

Not sure if there are any but I think we also need to check for icon only cases where `medium` or `large` are passed as that would also not turn out to be incorrect.

**Comment by jayeshmangwani** [comment]
@rojiphil , I’ve reviewed all instances where we use the small, medium, or large props for the Icon component, and they appear in about 15 files.

In my opinion, we have two options:

1. Introduce a New Prop: We could add a new prop to the Icon component (e.g., fromButton) and that will be true only if we use Icon from Button Component. If fromButton is set to true, we adjust the width and height accordingly `small = iconSizeExtraSmall, medium = iconSizeSmall and large = iconSizeNormal`. Otherwise, all icons will retain their current width and height as in the production `small = iconSizeSmall, medium = iconSizeNormal and large = iconSizeLarge`.

2. Manual Adjustments: We could manually apply the height and width in these files for Icon and remove the small, medium, or large props usage for these altogether.

Let me know what you think!

**Comment by rojiphil** [comment]
> 1. Introduce a New Prop: We could add a new prop to the Icon component (e.g., fromButton) and that will be true only if we use Icon from Button Component.

@jayeshmangwani I like the new prop idea as that would be neater. Also, `isButtonIcon` may sound better for the property name.

**Comment by jayeshmangwani** [comment]
Great, @rojiphil, I’ve pushed the change.

**Comment by rojiphil** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/a3ffa3fa-e550-4b2d-8e67-a72fa0ea8d8d

</details>

<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/4a3bef9b-4a95-49c4-bf31-a550af17b6d2

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/fc9911f9-3120-4d66-8653-aa9e79233e25

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/6482791f-a828-471c-a037-15d6d635a296

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/05711566-410f-465e-9523-f2f556ad1de5

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/e953ee9f-4945-4c73-bd89-8c4d5867ead8

</details>

**Review by rojiphil — APPROVED** [review]
@jayeshmangwani Thanks for merging with the latest main.

@mjasikowski Changes LGTM and works well too.
All yours for review. Thanks.

**Comment by shawnborton** [comment]
Screenshots look good to me.

**Comment by mjasikowski** [comment]
@jayeshmangwani @rojiphil all good, merging

**Review by mjasikowski — APPROVED** [review]

**Pull request merged**
