### PR TITLE
Fix hover issue with ButtonWithDropdownMenu

### PR DESCRIPTION
**Pull request by narefyev91**
### Details
The split button should have hover zones that line up with the two button areas that are split by a border

### Fixed Issues

$ https://github.com/Expensify/App/issues/39020
PROPOSAL:

### Tests
Pre-condition - user has add card to be able to pay with it
1. Click on fab > send money
2. enter amount and click next
3. select a user and go to confirmation page
4. Hover on right and left sides of the button - verify that hover is separated by divider

- [x] Verify that no errors appear in the JS console

### Offline tests
Pre-condition - user has add card to be able to pay with it
1. Click on fab > send money
2. enter amount and click next
3. select a user and go to confirmation page
4. Hover on right and left sides of the button - verify that hover is separated by divider

### QA Steps
Pre-condition - user has add card to be able to pay with it
1. Click on fab > send money
2. enter amount and click next
3. select a user and go to confirmation page
4. Hover on right and left sides of the button - verify that hover is separated by divider

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x]  I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x]  If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/28352309/d45b4906-9537-4a65-9efa-9c82d4653226

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/28352309/dc5f8998-01fc-41e0-8065-f724813c67bf

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/28352309/0ee8f458-644e-4f4e-85da-ff955a1e698f

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/28352309/9b7e5f00-4d13-4f4c-bc90-d687f59577b9

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/28352309/c6e0482e-a56c-469d-9f18-2e7860bfd544

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/28352309/dc778f2b-3cdf-41ba-9a77-7c55c3fad932

</details>

### CODE REVIEW

**Comment by narefyev91** [comment]
@shawnborton pushed a fix

**Comment by shawnborton** [comment]
Just to clarify, I think it is possible to have a split button that is in size large. Can you confirm that both medium (regular) and large sizes work well for this button type? cc @Expensify/design for extra eyes too.

**Comment by shawnborton** [comment]
For example, the send confirmation page uses a large size. 
CleanShot 2024-03-27 at 19 41 58@2x

**Comment by dannymcclain** [comment]
Yup—I think _ideally_ we would have all our sizes/variants for the split button (though I don't think we have any actual use cases for small split buttons or danger split buttons _yet_).

CleanShot 2024-03-27 at 14 16 25@2x

**Comment by dannymcclain** [comment]
But regarding this specific PR, the split button on a request (which I believe is medium) and in the send money confirmation (large) are both looking good. 👍

**Comment by narefyev91** [comment]
@shawnborton and @dannymcclain - based on all info above - what should we do? Just leave as we have now - for split button right side will be medium and it's looks good.
Or we integrate right button and hover state for both medium and large (seems small is not needed for now).
Just let me know - what will work for you.

**Comment by shawnborton** [comment]
I think ideally we implement the correct split button styling across small, medium, and large. 

@narefyev91 can you take a look at the split buttons [here](https://www.figma.com/file/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?type=design&node-id=1%3A2&mode=design&t=qNEmEYNtDN7gdzd7-1) and see if that is enough guidance?

**Comment by shawnborton** [comment]
Though I guess if small doesn't exist anywhere yet, maybe no need to build it now.

**Comment by narefyev91** [comment]
> I think ideally we implement the correct split button styling across small, medium, and large.
> 
> @narefyev91 can you take a look at the split buttons [here](https://www.figma.com/file/qQIIaxVUdtggrh8eg8bI5B/Brand-Guidelines-%26-Product-UI?type=design&node-id=1%3A2&mode=design&t=qNEmEYNtDN7gdzd7-1) and see if that is enough guidance?

Sure thing - will re-visit medium and large and build them based on figma

**Comment by narefyev91** [comment]
Screenshot 2024-03-28 at 15 22 07
Screenshot 2024-03-28 at 15 22 31
Screenshot 2024-03-28 at 15 22 22
Screenshot 2024-03-28 at 15 22 37
@shawnborton @dannymcclain - updated based on the design. Also fixed icon size - which was not reflecting based on large/medium sizes

**Comment by shawnborton** [comment]
Looks pretty good to me - mind showing a quick video of the hover styles too for posterity? Thanks!

**Comment by narefyev91** [comment]
> Looks pretty good to me - mind showing a quick video of the hover styles too for posterity? Thanks!

Sure!

https://github.com/Expensify/App/assets/28352309/0a7d394e-95bc-4d19-b60c-dd4108652ce3

**Comment by shawnborton** [comment]
Sorry, but can you also show the medium hover styles? I think that button can be found when going to pay for a request. 

Also, you can probably just show examples right from Storybook, right?

**Comment by narefyev91** [comment]
> Sorry, but can you also show the medium hover styles? I think that button can be found when going to pay for a request.
> 
> Also, you can probably just show examples right from Storybook, right?


https://github.com/Expensify/App/assets/28352309/a54f3da4-f957-4247-8b02-e678369cacc2

**Comment by narefyev91** [comment]
@shawnborton are we good to go here?

**Comment by shawnborton** [comment]
Nice, that looks good to me, let's get this merged.

**Comment by narefyev91** [comment]
@akinwale can you please review this one

**Comment by akinwale** [comment]
I'll review today.

**Comment by narefyev91** [comment]
> @narefyev91 Please add a verify step to the test steps. In this case, it would be to verify that the hover effect displays correctly when the user hovers the button.

updated

**Comment by akinwale** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/4160319/0dc573a7-a9b8-4a5a-9446-03bf2ec62377

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/4160319/84f13bce-b2b5-47b2-9627-f9c675118db5

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/4160319/d9e4d168-b580-4a18-95d5-672b086e7845

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/4160319/6e024a6d-546b-46bb-95e5-9979ad5c4b3b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/4160319/cf81e8a6-927f-4c72-8c71-c1d3685fb0d7

https://github.com/Expensify/App/assets/4160319/755d856b-ee7f-409c-9ff0-6ddce46e4728

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/4160319/389ba6b7-22bc-4af4-9df3-1f338792f5b3

https://github.com/Expensify/App/assets/4160319/b0ffb64e-dbee-49bd-9267-89bae21fc903

</details>

**Review by akinwale — APPROVED** [review]
LGTM.

**Review by akinwale — APPROVED** [review]

**Review by francoisl — APPROVED** [review]

**Comment by francoisl** [comment]
Tests were passing, not an emergency.

**Pull request merged**
