### PR TITLE
Update withOnyx to fix prop dependent key updates

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
See linked Onyx PR: https://github.com/Expensify/react-native-onyx/pull/98

### Fixed Issues
https://github.com/Expensify/react-native-onyx/pull/97#discussion_r689287381

### Tests
Automated tests in `react-native-onyx`

### QA Steps

No specific QA besides regressions

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
Heads up this may need to be a CP to staging depending on when this other PR hits staging -> https://github.com/Expensify/App/pull/4610

**Review by luacmartins — APPROVED** [review]
LGTM!

**Comment by luacmartins** [comment]
@marcaaron feel free to self-merge once tests are done.

**Comment by marcaaron** [comment]
Did some quick tests on web and seems like chat switching is fixed up now. Going to merge without the E2E passing so that we can avoid further confusion.

**Comment by marcaaron** [comment]
Also tested iOS and it builds fine - which is all the E2E test does.

**Pull request merged**
