### PR TITLE
[HOLD][No QA] Setup modular sass and color file for help site

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
- Sets up modular sass partials
- Creates a color module so all colors reference variables
- Removes the styles for the `code` tag because AFAICT we have no code tags currently.

### Fixed Issues
$ (partial) https://github.com/Expensify/Expensify/issues/216729

### Tests
0. (you need ruby and bundler installed to do this)
1. Run:

    ```bash
    cd help
    bundle install
    bundle exec jekyll serve
    ```
2. Make sure the site's styles load and that all the colors look correct.
3. To convince yourself that it's working, go into the colors file and change $color-blue to `#f00` and refresh the page – all the links should turn red.

### CODE REVIEW

**Comment by roryabraham** [comment]
I branched off of `marco-addNewHelpSite` so once https://github.com/Expensify/App/pull/9519 is merged and I merge main in this PR the diff will look a lot more reasonable.

**Comment by roryabraham** [comment]
This is ready for review

**Review by marcochavezf — DISMISSED** [review]
Cool, thanks for improving this @roryabraham! @aldo-expensify all yours

**Comment by roryabraham** [comment]
Putting this on hold to make sure we can make it work with the older version of jekyll that comes bundled with GH Pages (3.9.2)

**Comment by roryabraham** [comment]
Since we moved all the files, resolving conflicts here is going to be too much. I'm going to start fresh with a new PR

**Pull request closed without merging**
