### PR TITLE
Allow video files to be uploaded

### PR DESCRIPTION
**Pull request by tgolen**
### Fixed Issues
Addresses a comment from an earlier PR: https://github.com/Expensify/App/pull/10118#issuecomment-1210895657

### Tests and QA
- Upload an mov, mp3, or mp4 file under 50mb

### CODE REVIEW

**Comment by srikarparsi** [comment]
https://user-images.githubusercontent.com/48188732/184422220-fd73567a-54f9-47ab-a44b-b9954457ee9b.mov

I tried uploading this screen recording that was a .mov but I'm getting this error.

**Comment by tgolen** [comment]
Yeah, I get that error too in my local environment. When I looked at my logs, I saw an error saying that it couldn't upload it to S3, so I figured I had a local config issue. As long as it's getting to the server, I think that's OK for this PR.

**Comment by srikarparsi** [comment]
ok sounds good, thanks tim!

**Review by srikarparsi — APPROVED** [review]
lgtm!

**Pull request merged**
