### PR TITLE
[ExpensifyHelp] Dynamically create the routes file for docs

### PR DESCRIPTION
**Pull request by Prince-Mendiratta**
### Details

With this PR, we are adding a new script and a new GH action that will automatically generate the `routes.yml` file in `docs/_data/routes.yml` and ensure that if a new article was added the `routes.yml` was updated using the script, respectively.

The workflow of the script is as follows:
- All the meta data information about each hub is stored in the `docs/_data/_routes.yml` file.
- When the script is run locally, the script will read the `_routes.yml` file and add the details to it, saving the final file as `routes.yml`.
- If the number of hubs defined in `_routes.yml` is not equal to the number of hubs in the `docs/articles` folder, an error will be thrown.
- If the number of hubs are equal, then for each hub, we will check if it contains any subfolders or not.
- If they do not, then for that specific hub, we create a new key `articles` and for each file in the hub, add it to the key with `href` as the filename and `title` as the filename with the extension removed, in title case.
- If they do contain subfolder, each subfolder is treated as a `section`. A new key `sections` is added for that specific hub. For each section, we add the `href` and `title` and for each file in the subfolder, we add it to the `articles` key in the section.
- Once all the directories have been iterated, the generated YAML is saved in the `routes.yml` file, which is used by Jekyll.

This script can be executed in two ways:
- `node .github/scripts/createDocsRoutes.js`
- `npm run createDocsRoutes`

I have added a new github action `.github/workflows/validateDocsRoutes.yml`, which will trigger a new script, `verifyDocsRoutes.sh`, inspired from `verifyActions.sh`. Whenever a new Pull Request is created,
- If the `docs/` directory is not modified, the GH action will not be triggered.
- If the GH action is triggered, it will execute the `verifyDocsRoutes.sh` script, which will run the `npm run createDocsRoutes`.
- This will execute the new js script we created and based on the additions, create a new `routes.yml` file. If there is a difference between this generated file and the one on the PR branch, it is inferred that the PR author did not run the `npm run createDocsRoutes` command locally and the GH action will fail.
- If there are no difference between the files, it means that:
    - The `articles/` folder was not modified, leaving the routes same.
    - The PR author ran the `npm run createDocsRoutes` locally as required, committing the changes.

I feel that this is a better way instead of creating a GH action that will automatically generate the `routes.yml` file and commit it to the repo since this way we will have a signed commit from the PR author when the `routes.yml` needs to be modified.

### Fixed Issues

$ https://github.com/Expensify/App/issues/17241
PROPOSAL: https://github.com/Expensify/App/issues/17241#issuecomment-1502342854

### Tests

**GH action not executed**
- If the `docs/` folder was not modified, the GH action should not run.
https://github.com/Prince-Mendiratta/expensify-app/pull/10

**GH action should PASS**
- The `docs/` folder was modified but no articles were added, so the routes remain untouched.
    - https://github.com/Prince-Mendiratta/expensify-app/pull/11
- The PR author added a new article and ran the command locally, commiting the changes to `routes.yml`
    - https://github.com/Prince-Mendiratta/expensify-app/pull/12
- The PR author added a new hub and a new article, added the hub details to `_routes.yml`, ran the command locally and committed the changes to `routes.yml`.
    - https://github.com/Prince-Mendiratta/expensify-app/pull/13
- A new article was added but the command was not run locally.
    - https://github.com/Prince-Mendiratta/expensify-app/pull/15

**GH action should FAIL**
- A new hub was added but the details of the new hub was not added to `_routes.yml` and the command was not run locally successfully.
    - https://github.com/Prince-Mendiratta/expensify-app/pull/14
- [x] Verify that no errors appear in the JS console

### Offline tests

N/A

### QA Steps

N/A?

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
N/A

[Mini-Design doc](https://docs.google.com/document/d/1_r86EUWNfBO6HV1tn_eCqP1SwunLL9ndAr7aLmJX7k0/edit#)

[Custom GH pages site for testing](https://expensifyhelp.mendis.in/)

### CODE REVIEW

**Comment by marcochavezf** [comment]
Hi @Prince-Mendiratta, could you deploy your changes to a GH page just to corroborate it's deploying correctly?

**Comment by marcochavezf** [comment]
Ah I mean, since the help site is in the `docs` folder, I think the generated site can be deployed as a regular GH pages site using the fork just to verify nothing is broken in the site.

**Comment by marcochavezf** [comment]
> > GH action should FAIL
>
> A new article was added but the command was not run locally.
>
> https://github.com/Prince-Mendiratta/expensify-app/pull/14

For this test, we want to pass, because some PR authors that add articles won't be able to run the script locally (they will add the articles using the GH site), and we want to run it when the site is built and deployed. The option to run the script locally is only for developers for local development. Sorry if this wasn't clear from the beginning, but it's a requirement of the overall [solution](https://github.com/Expensify/App/issues/17241#issue-1661377832).

**Comment by marcochavezf** [comment]
Awesome! Thanks @Prince-Mendiratta! 
@rushatgabhane, when you get a chance, could you take a look and give it a review? Thanks!

**Comment by marcochavezf** [comment]
I've updated the original post to include the mini design doc and the testing site, making it easier to find them for future reference.

**Review by rushatgabhane — APPROVED** [review]

**Review by marcochavezf — APPROVED** [review]
Awesome! Sorry for the delay here guys, I tested locally and worked fine for me!

**Comment by marcochavezf** [comment]
Now let's merge it and deploy it 🤞🏽

**Comment by marcochavezf** [comment]
For some reason the script didn't run and the site doesn't contain the articles:

Screenshot 2023-04-27 at 13 17 13

Screenshot 2023-04-27 at 13 17 20

I'm going to revert the PR :(

**Pull request merged**
