### PR TITLE
fix: Message and Notification Swapping in IOU

### PR DESCRIPTION
**Pull request by nkdengineer**
### Fixed Issues

$ https://github.com/Expensify/App/issues/46393
PROPOSAL: https://github.com/Expensify/App/issues/46393#issuecomment-2255598546

### Tests

Issue 1: 
1. Navigate to Workspace Chat > Plus Sign > Submit Expense
2. Add amount and merchant, then confirm
3. Go to IOU, switch to offline mode, and generate a notification by changing the date
4. Write a message, then switch back to online mode. Notice the message and notification swap
5. Verify that: Messages and notifications should remain in place

Issue 2: 
1. Go offline
2. Go to a workspace
3. Select all categories
4. Disable categories
5. Delete categories
6. Come back online
7. Verify that: Categories should be deleted being disabled in offline mode

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/1ca77abd-1e78-440e-9483-5db39181fc1f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/8d07f39e-9b55-4521-9994-f8be04cc496c

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/bb70ab83-eb7b-4edd-bacb-3cca7b11d673

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/8d07f39e-9b55-4521-9994-f8be04cc496c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/2cac96f7-af3c-4636-a5eb-aa3668344fd6

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/3661cd91-d1e1-4106-884a-d385c5a5f11b

</details>

### CODE REVIEW

**Review by Ollyws — APPROVED** [review]
LGTM but let's test with an ad-hoc build.

**Review by tgolen — CHANGES_REQUESTED** [review]
I'll get the adhoc build going and then ping QA to start testing it.

**Comment by tgolen** [comment]
OK, I've requested the testing from QA (ref: [thread](https://expensify.slack.com/archives/C9YU7BX5M/p1723734488241679)).

**Comment by tgolen** [comment]
OK, It's building again now. QA has this on their list to do, but they have two other ad-hoc builds in front of this one that they are testing, so I don't imagine they will get to this one until the end of next week probably.

**Comment by tgolen** [comment]
Update:

QA currently has 4-5 other adhoc builds that they are testing. This PR has been moved to the end-of-the-line priority-wise. I imagine it could start being tested next week.

**Comment by tgolen** [comment]
@nkdengineer It sounds like QA is ready to test this. Could you please update your branch so it is current with `main` and then I will generate a new ad-hoc build for it?

**Comment by nkdengineer** [comment]
@tgolen I merged.

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Expense - Banner shows "transaction pending" when there is no pending Ecard transaction


**Version Number:** 9.0.24-2
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Go to https://47478.pr-testing.expensify.com/
2. Go to workspace chat
3. Submit a manual expense
4. Click on the expense preview

## Expected Result:
The banner will not show "Transaction pending. It may take a few days to post." because there is no pending Ecard transaction

## Actual Result:
The banner shows "Transaction pending. It may take a few days to post

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos


https://github.com/user-attachments/assets/cd82a72c-6fe9-476f-937d-e7744351f5e9



</details>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Task – Character limit for the task description is 1000

**Version Number:** 9.0.24-2
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Go to https://47478.pr-testing.expensify.com/
2. Log in
3. Open any chat
4. Click on + and Assign task
5. Enter task title
6. Enter a very long description

## Expected Result:
Character limit for the task description is 500

## Actual Result:
Character limit for the task description is 1000, but not 500

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f4a35636-1615-45d5-9583-26e73d1211f8

</details>

**Comment by lanitochka17** [comment]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
##  Android - room-Leaving room with public visibility app crashes

**Version Number:** 9.0.24-2
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team


## Action Performed:
1. Launch app
2. Tap fab -- start chat
3. Create a room with " Public" visibility
4. Tap header -- leave

## Expected Result:
Leaving room with public visibility app must not crash

## Actual Result:
Leaving room with public visibility app crashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/40f8beeb-33f1-4cff-9e81-5c186b9ea11a


</details>

**Comment by nkdengineer** [comment]
@ lanitochka17 I checked and these issues may not be related to this PR.

**Comment by mvtglobally** [comment]
QA is completed

**Comment by tgolen** [comment]
> @lanitochka17 I checked and these issues may not be related to this PR.

@nkdengineer Are you sure of this and the problems have been reproduced on main or staging? If so, it sounds fine to merge, but it would be nice to have certainty about what is causing those issues.

@lanitochka17 Have you tried to reproduce those on staging?

**Comment by nkdengineer** [comment]
@tgolen 

- Bug 1 maybe fixed [here](https://github.com/Expensify/App/pull/47941) and it's not related to this PR.

- Bug 2 can also reproduce on the latest main and staging

- Bug 3 is not reproducible on the latest main.

**Comment by tgolen** [comment]
OK, thank you! Sounds like this can go ahead and be merged then.

**Review by tgolen — APPROVED** [review]

**Pull request merged**
