### PR TITLE
Fix/21456 - Polish admins-only policy room - Pass arguments properly

### PR DESCRIPTION
**Pull request by rezkiy37**
### Details

This is a regression fix of https://github.com/Expensify/App/pull/21950. A new value was added to `buildOptimisticChatReport` and it was missed to pass this argument in a few places. 
I fixed arguments where other values were passed as `writeCapability`. Also, decided to use `undefined` as a default value in `buildOptimisticChatReport`, because this function generates objects for many other instances, not only a room. I pass `writeCapability` explicitly.

### Fixed Issues

$ https://github.com/Expensify/App/issues/21456, https://github.com/Expensify/App/issues/23638, https://github.com/Expensify/App/issues/23646
PROPOSAL: N/A

#### Creating a workspace
1. Click on your user avatar icon (_settings_).
2. Click on **"Workspaces"**.
3. Open the console.
4. Click on **"New workspace"**.
5. Verify that no console errors.

#### Viewing a chat reply
1. Open any chat.
2. Send a message.
3. Enable the **offline** mode.
4. Hover over the sent message and click on **"Reply in thread"** icon.
5. Verify that the thread header display the threaded message and "from" link, **Composer** should be visible.

#### Viewing a money request
1. Open any chat.
2. Click on **"+"** (_actions_) to the left of **Composer**.
3. Click on "**Request money**".
4. Enter any values.
5. Click on **"Request"**.
6. Click on **"Replies"**.
7. Open the console.
8. Click on the latest money request.
9. Verify that no console errors.

#### Creating a room when are an admin
1. Click on "**+**" (_FAB menu_).
2. Click on "**New room**".
3. Select a workspace, where you are an admin.
4. Verify that a new selector appears - "**Who can post**" with 2 values: "**All members**" and "**Amins only**".
5. Select any value for the new selector. Fill in the other selectors/inputs as you want (_up to you_).
6. Click on "**Create room**".
7. The app should redirect you to a new room chat page.
8. Open the chat settings.
9. Verify that it has the same values that you entered before.
10. Repeat one more time, but select the other value for the new selector.

#### Creating a room when are a member
1. Click on "**+**" (_FAB menu_).
2. Click on "**New room**".
3. Select a workspace, where you are a member.
4. Verify that there isn't "**Who can post**" selector.
5. Fill in the other selectors/inputs as you want (_up to you_).
6. Click on "**Create room**".
7. The app should redirect you to a new room chat page.
8. Open the chat settings 
9. Verify that "**Who can post**" selector is "**All members**" and other inputs have the same values that you entered before.

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as **Tests**

### QA Steps

Same as **Tests**

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/57314631/8dd3e172-9861-4340-acb4-0b3fda36af0f

https://github.com/Expensify/App/assets/57314631/c45b1300-50c6-4cc6-b601-3b1ae1589994

https://github.com/Expensify/App/assets/57314631/46fc0ba4-a9ca-470c-adae-804042e2e9f5

https://github.com/Expensify/App/assets/57314631/16c589a1-4093-44fd-8149-139201f31aff

https://github.com/Expensify/App/assets/57314631/d75b37f5-0b1a-48f0-ac63-f9c69cebb36a

https://github.com/Expensify/App/assets/57314631/01c402b8-8180-4439-9fbf-78c2dde1be34

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Review by amyevans — APPROVED** [review]
LGTM!

**Comment by amyevans** [comment]
@mananjadhav all yours!

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/3069065/197f6491-a124-46d1-8b98-024cfe07fe44

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/3069065/064935ed-3d2d-45b5-9426-9b74d10612aa

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/3069065/e076a256-1e78-48ea-81b4-e458600af428

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/3069065/b7717362-41d8-47b9-abf8-8265f1c60cc0

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/3069065/cfdc7d11-a77e-4381-b7ad-d565a9abaccb

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/3069065/f9665ea6-45c6-4a0f-9f77-fc1e2279c719

</details>


Thanks for the fixes @rezkiy37. I've also tested [this](https://expensify.slack.com/archives/C049HHMV9SM/p1690461910613649) in the current PR, @kavimuru.


@amyevans 🎀 👀 🎀 C+ Reviewed.

**Review by mananjadhav — APPROVED** [review]

**Review by amyevans — APPROVED** [review]

**Comment by Christinadobrzyn** [comment]
Hi! Can we confirm if this [issue](https://github.com/Expensify/App/issues/23847) and https://github.com/Expensify/App/issues/23821 will be fixed with this PR?

**Comment by rezkiy37** [comment]
> Hi! Can we confirm if this [issue](https://github.com/Expensify/App/issues/23847) and #23821 will be fixed with this PR?

@Christinadobrzyn, yes, we can confirm. This PR fixes both issues. There was a PR, which introduced these bugs - #21950. We already merge this PR, which fixes it. 
I tested on a commit (eb020063789091eb2e3086b5b54af3ead8436645) directly before this PR merge into `main`, in this case both bugs exist. Once I switch to the fix commit (024d210bc0b5a0454b62a72de60057af67cdd045), no bugs anymore.

1  Commits


<details><summary>Example for #23847 </summary>
<p>

https://github.com/Expensify/App/assets/57314631/17cd668b-0f14-4916-9fe8-9c65b034b3ac

</p>
</details> 

<details><summary>Example for #23821 </summary>
<p>

https://github.com/Expensify/App/assets/57314631/0972eb47-7cba-4752-a92f-2b2c4bae5432

</p>
</details>

**Comment by Christinadobrzyn** [comment]
Side note paying @situchan as a reporter of this regression per the discussion here https://github.com/Expensify/App/issues/23847#issuecomment-1662942237

**Pull request merged**
