### PR TITLE
Make About footer links accessible

### PR DESCRIPTION
**Pull request by elemdos**
### Details
Opened in place of a [previous PR](https://github.com/Expensify/App/pull/5173) for code-signing purposes

### Fixed Issues
$ https://github.com/Expensify/App/issues/5082

### Tests
1. Open Settings screen
2. Click 'About'
2. Tab through About options
3. Verify footer links (Terms of Service, Privacy Policy) focus when tabbed

### QA Steps
1. Open Settings screen
2. Click 'About'
2. Tab through About options
3. Verify footer links (Terms of Service, Privacy Policy) focus when tabbed

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/39444813/133006494-164ff4ea-5873-417f-95f7-3e0eb1e6bef5.mov

#### Mobile Web
https://user-images.githubusercontent.com/39444813/133087857-dc7b5ed6-1d4d-4fe0-981d-366a834ec25c.mov

#### Desktop
https://user-images.githubusercontent.com/39444813/133006503-1a4aed52-b706-43f7-a410-1d0dce0e983b.mov

#### iOS
https://user-images.githubusercontent.com/39444813/133006505-edaaa8b5-8558-40bd-8acf-0720947fbc35.mov

#### Android
https://user-images.githubusercontent.com/39444813/146185863-313c3413-0156-46a6-b1e8-e193ae8ff3af.mov

### CODE REVIEW

**Comment by marcochavezf** [comment]
Hi @mateomorris! Thank you for pushing this PR, the solution looks good but I noticed when I click on the footer links in Web the links are opened in the same tab vs in a new one (which is the default behavior). Thoughts?

**Comment by mateomorris** [comment]
@marcochavezf sounds like it would be best to have them open in a new tab, should I go ahead and do that?

**Comment by marcochavezf** [comment]
> @marcochavezf sounds like it would be best to have them open in a new tab, should I go ahead and do that?

@mateomorris yeah please, because that is what's happening currently in the production app and it's a bit jarring for the user to navigate back to the app when the ToS o privacy links are opened in the same tab 🙇🏽‍♂️

**Comment by mateomorris** [comment]
@marcochavezf okay ready - it's opening in a new tab now. I had to use accessibilityRole to make the link accessible (instead of making it an anchor tag) which isn't ideal, but the only clear way to make the link open in a new tab.

**Review by marcochavezf — APPROVED** [review]

**Comment by marcochavezf** [comment]
@mateomorris Thanks for addressing that change!

**Pull request merged**
