### PR TITLE
Update MentionUserRenderer.js Issue 26016

### PR DESCRIPTION
**Pull request by nikhildewoolkar**
### Fixed Issues
$https://github.com/Expensify/App/issues/26016

Open the app
Open any report
Write '@' to trigger mentions
Select any one mention, make any letter of mention as capital and send
Hover on mention to observe that tooltip doesn't display the right display name and avatar
For same mention as step 4 or select different mention and capitalize all letters and send
Observe that now it is not displayed as mention

$
PROPOSAL:
https://github.com/Expensify/App/issues/26016#issuecomment-1694610274

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

289936066-8a8d561f-8f41-4892-a9ac-48381e8765df

</details>

<details>
<summary>MacOS: Desktop</summary>

289936066-8a8d561f-8f41-4892-a9ac-48381e8765df

</details>

### CODE REVIEW

**Comment by nikhildewoolkar** [comment]
This is new PR for issue https://github.com/Expensify/App/issues/26016. I have filled the PR Author Checklist.
@neil-marcellini  @neil-marcellini  @adelekennedy  @rushatgabhane 
Kindly review PR.
Screenshots added below in comments. Screenshots not applicable for mobile application.
289936066-8a8d561f-8f41-4892-a9ac-48381e8765df

**Comment by youssef-lr** [comment]
This is still an issue

https://github.com/Expensify/App/assets/9680864/434a93ad-ec87-44e1-b329-cfc4a8e48b6e

**Comment by sobitneupane** [comment]
@youssef-lr I could not reproduce the issue that you mentioned.
Screenshot 2024-01-03 at 16 01 36

**Review by sobitneupane — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/25876548/4e6e08eb-990f-43d2-8b2f-543fd3a746b8

</details>

<details>
<summary>Android: mWeb Chrome</summary>


</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/25876548/8982496e-8c6b-4109-9457-d53f2c15214e


</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/25876548/d98e86f4-05e9-423d-b27c-95e57b5fb60d


</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/25876548/adea5334-e073-4a5a-a6ed-cfc591499fd4


</details>

<details>
<summary>MacOS: Desktop</summary>


https://github.com/Expensify/App/assets/25876548/85521ff8-00b9-48b5-bc66-81affab66072




</details>

**Comment by nikhildewoolkar** [comment]
Kindly review and approve ASAP @youssef-lr @sobitneupane

**Comment by youssef-lr** [comment]
on it today

**Comment by nikhildewoolkar** [comment]
Any updates? @sobitneupane @youssef-lr

**Comment by youssef-lr** [comment]
Sorry couldn't get to this, I'm on it shortly.

**Comment by nikhildewoolkar** [comment]
Kindly check and review @sobitneupane @youssef-lr

**Comment by nikhildewoolkar** [comment]
Hello ,
Kindly check the PR. Let's solve and  close this issue.

**Comment by youssef-lr** [comment]
@sobitneupane to reproduce do not select the user, press space after typing the email when it contains an uppercase then send the comment

https://github.com/Expensify/App/assets/9680864/65f9f1e7-fdbe-47be-9ce6-3f80794b2535

**Comment by youssef-lr** [comment]
Or better, copy and paste a mention with an email that contain an uppercase letter then press send.

**Comment by sobitneupane** [comment]
@nikhildewoolkar Can you please work on the issue.

**Comment by nikhildewoolkar** [comment]
@sobitneupane @youssef-lr this reproducible bug isn't related to my problem statement.  https://github.com/Expensify/App/issues/26016
Because i tested before raising PR. Please check and let me know.

**Comment by sobitneupane** [comment]
@nikhildewoolkar I don't think it is different from the original issue. We are supposed to handle all the cases related to the issue.

If there are any blockers, please let us know. We can work together to solve the issue.

**Comment by sobitneupane** [comment]
To my greatest surprise, I also could not reproduce the issue. 

https://github.com/Expensify/App/assets/25876548/2ab66fed-0b4b-4a75-924e-8aef7cbda7c5

**Comment by nikhildewoolkar** [comment]
> To my surprise, I also could not reproduce the issue.
> 
>  Screen.Recording.2024-02-08.at.21.18.59.mov

If its done lets merge this and close this issue

**Comment by youssef-lr** [comment]
This seems to have been fixed in another PR. I can't reproduce on staging.

**Comment by youssef-lr** [comment]
Check the conflicts in this file, it was fixed by this line `tnode.data = tnode.data.replace(displayNameOrLogin, getMentionDisplayText(displayNameOrLogin, htmlAttributeAccountID));`.

**Comment by nikhildewoolkar** [comment]
> This seems to have been fixed in another PR. I can't reproduce on staging.

kindly review pr

**Comment by youssef-lr** [comment]
@nikhildewoolkar I'm afraid we cannot merge this PR, we can't simply replace `getMentionDisplayText` with `toString` as it's doing a lot of things. What do you think @sobitneupane?

**Comment by nikhildewoolkar** [comment]
When we select from mentionautocomplete dropdown the it lowercases it. So why is it a problem here? @youssef-lr @sobitneupane this is what exactly decided in proposal and we should not be overthinking on this issue which has been dragging from 2 months. so i am eager to take it over to finish line. Thank you 😄

**Comment by nikhildewoolkar** [comment]
@sobitneupane @youssef-lr please review.

**Comment by sobitneupane** [comment]
@nikhildewoolkar I will kindly request your patience.

A lot has changed recently. I will update soon

**Comment by sobitneupane** [comment]
@youssef-lr We still have the issue in staging where we don't show tooltip for mentions with caps.

https://github.com/Expensify/App/assets/25876548/3e356a1d-4ae0-4aac-88b9-61bd653ed1f8

The issue is because of the wrong accountID returned in https://github.com/Expensify/App/blob/bfd272c29a968871038f200419151c43b898eb47/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L48

We need to pass lowercase letter to get the correct accountID.

So, only change required here is

https://github.com/Expensify/App/blob/bfd272c29a968871038f200419151c43b898eb47/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L46

to 

`displayNameOrLogin = tnode.data.replace(CONST.UNICODE.LTR, '').slice(1).toLowerCase()`

We are passing `displayNameOrLogin` as fallbackUserDetails. So, I think we should make `displayNameOrLogin` lowercase.

**Comment by nikhildewoolkar** [comment]
@sobitneupane fixed the merge conflict

**Comment by youssef-lr** [comment]
@sobitneupane @nikhildewoolkar indeed it seems like we need the lowercase here to fix the tool tip issue. I think we should update this check [here](https://github.com/Expensify/App/blob/39ac35ad7b57007829b8d2768ef23b3b02ffea99/src/libs/PersonalDetailsUtils.ts#L67) to turn the `login` into a lowercase for a more bulletproof solution.

```diff
diff --git a/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx b/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
index 8908350728..ad9cfb4e63 100644
--- a/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
+++ b/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx
@@ -43,7 +43,7 @@ function MentionUserRenderer({style, tnode, TDefaultRenderer, currentUserPersona
         navigationRoute = ROUTES.PROFILE.getRoute(htmlAttribAccountID);
     } else if ('data' in tnode && !isEmptyObject(tnode.data)) {
         // We need to remove the LTR unicode and leading @ from data as it is not part of the login
-        displayNameOrLogin = tnode.data.replace(CONST.UNICODE.LTR, '').slice(1).toLowerCase();
+        displayNameOrLogin = tnode.data.replace(CONST.UNICODE.LTR, '').slice(1);
 
         accountID = PersonalDetailsUtils.getAccountIDsByLogins([displayNameOrLogin])?.[0];
         navigationRoute = ROUTES.DETAILS.getRoute(displayNameOrLogin);
diff --git a/src/libs/PersonalDetailsUtils.ts b/src/libs/PersonalDetailsUtils.ts
index a881dd4112..55aee10e61 100644
--- a/src/libs/PersonalDetailsUtils.ts
+++ b/src/libs/PersonalDetailsUtils.ts
@@ -64,7 +64,7 @@ function getPersonalDetailsByIDs(accountIDs: number[], currentUserAccountID: num
  */
 function getAccountIDsByLogins(logins: string[]): number[] {
     return logins.reduce<number[]>((foundAccountIDs, login) => {
-        const currentDetail = personalDetails.find((detail) => detail?.login === login);
+        const currentDetail = personalDetails.find((detail) => detail?.login === login?.toLowerCase());
         if (!currentDetail) {
             // generate an account ID because in this case the detail is probably new, so we don't have a real accountID yet
             foundAccountIDs.push(UserUtils.generateAccountID(login));
```

**Comment by sobitneupane** [comment]
@youssef-lr Yup. We can do that. @nikhildewoolkar Can you please make the suggested changes.

**Comment by youssef-lr** [comment]
friendly bump @nikhildewoolkar!

**Comment by nikhildewoolkar** [comment]
suggested changes done. check and review once.

**Review by youssef-lr — APPROVED** [review]

**Comment by youssef-lr** [comment]
Thanks!

**Comment by nikhildewoolkar** [comment]
This issue has been resolved and still i didn't receive any upwork task link. Kindly share updates on this.

**Pull request merged**
