### PR TITLE
fix: workspace members invite page transition

### PR DESCRIPTION
**Pull request by b4s36t4**
### Details
Workspace invite member page is flickering and doesn't have the transition included in it which is caused by input focusing while rendering. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/22036
PROPOSAL: [#22036 (comment)](https://github.com/Expensify/App/issues/22036#issuecomment-1619057209)

### Tests

1. Go to Settings > Workspaces > any workspace -> Members
2. Click on the Invite button
3. Verify the Invite page is shown and slides from the right to the left

- [x] Verify that no errors appear in the JS console

### Offline tests

NA

### QA Steps

1. Go to Settings > Workspaces > any workspace -> Members
2. Click on the Invite button
3. Verify the Invite page is shown and slides from the right to the left
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/59088937/250649006-8e3bb4ff-7eca-42a9-bc56-2a82f2fee129.webm
</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/59088937/e198e487-ea69-4279-b0bc-6656cb221a48

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>
https://github.com/Expensify/App/assets/59088937/9b7084b1-26d0-4351-a70e-56858dd7b8aa

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/59088937/6775ed2d-7e98-4af4-b436-bd41119e3c01

</details>

### CODE REVIEW

**Comment by b4s36t4** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by b4s36t4** [comment]
recheck

**Comment by s77rt** [comment]
@b4s36t4 Can you please test using a high traffic account and upload the rest of the screensohts

**Comment by b4s36t4** [comment]
@s77rt sure will update.

**Comment by b4s36t4** [comment]
@s77rt With high traffic account this issue seems need an update in code. Afterwards the working can be observed below.
io

**Comment by s77rt** [comment]
@b4s36t4 Can you explain more here? Was there a problem with sections loading and if so was that related to adding the delay focus?

**Comment by b4s36t4** [comment]
@s77rt I think the issue relies on loading the contacts. When my account was just a new account adding dealy did worked, but seems delay is a setTimeOut with just 300ms of time. And if you see the old code sections were defined in render function which might be the reason. When I shifted to high traffic account I observed the issue of jitter

I think getting sections in render function is the issue so I moved getting sections (contacts) moved out that whenever the transition ends which means modal component is rendered fully then load the sections.

**Comment by b4s36t4** [comment]
No, it doesn't matter with delay. Delay is only for focusing the input not the whole component. But using `onEntryTransitionEnd` should be good since it provides grantee that transition has ended.

**Comment by b4s36t4** [comment]
@s77rt here it is -> https://user-images.githubusercontent.com/59088937/250649006-8e3bb4ff-7eca-42a9-bc56-2a82f2fee129.webm
This video is just with `shouldDelayFocus` prop.

**Comment by s77rt** [comment]
@b4s36t4 I meant for a high traffic account

**Comment by s77rt** [comment]
@b4s36t4 Isn't that video where you applied both the delay focus and moved the `sections` to a state value?

**Comment by b4s36t4** [comment]
Yes, it is. It has both the changes.

**Comment by s77rt** [comment]
@b4s36t4 Can you attach the video where only the focus delay is applied? (and using a high traffic account)

**Comment by b4s36t4** [comment]
Yes, understood now. Will share in a minute.

**Comment by b4s36t4** [comment]
@s77rt here's the video.
https://github.com/Expensify/App/assets/59088937/b1426948-156f-4ccd-839b-899b56ab9139

**Comment by s77rt** [comment]
In that last video, is there a vibration of the text?

**Comment by s77rt** [comment]
I see. In that case please revert the last commit and let's make use of `shouldShowOptions` prop similar on how it's used on `NewChatPage`.

**Comment by b4s36t4** [comment]
Ok understood. Will update the PR.

**Comment by b4s36t4** [comment]
@s77rt I don't think that approach is solving the issue. 
Please watch the video here and see the code diff. I think transition is not that upto mark.
Screenshot 2023-07-05 at 8 21 16 PM

https://github.com/Expensify/App/assets/59088937/77801916-7902-4cce-b044-c5561f24d0b6

**Comment by b4s36t4** [comment]
@s77rt also watch this video, this clearly gives the transition and make it more clear this video is the implementation of the current commit (in PR).

https://github.com/Expensify/App/assets/59088937/8aa2f8c8-a7ed-4265-b263-a23a7e4f6cc9

**Comment by s77rt** [comment]
We can't go with this PR as it's. It will cause stale data issue, the sections should be recalculated at every render (or whenever certain data change, this will become easier to handle once we migrate this page to functional component)

**Comment by s77rt** [comment]
It will not, `getSections` is called only once

**Comment by b4s36t4** [comment]
How about this? calculation sections based on the transition this way it works fine.

In the current commit when I type there's no change within the section but with this change there's transition and as well data is also getting updated.

Screenshot 2023-07-05 at 8 36 03 PM

https://github.com/Expensify/App/assets/59088937/27594fb1-afd4-40b9-bb2e-a1db49668f37

**Comment by b4s36t4** [comment]
Ok, will add that as well.

**Comment by s77rt** [comment]
@b4s36t4 Please add the missing screenshots and updates the Tests and QA to:

1. Go to Settings > Workspaces > _any_ workspace -> Members
2. Click on the Invite button
3. Verify the Invite page is shown and slides from the right to the left

**Comment by b4s36t4** [comment]
@s77rt I don't have a iOS mobile nor the space to accommodate xcode into system, any other way?

**Comment by s77rt** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [X] I verified the correct issue is linked in the `### Fixed Issues` section above
- [X] I verified testing steps are clear and they cover the changes made in this PR
    - [X] I verified the steps for local testing are in the `Tests` section
    - [X] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [X] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I verified tests pass on **all platforms** & I tested again on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [X] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



https://github.com/Expensify/App/assets/16493223/bdd33301-6d47-4d09-9a13-3cffc50818ee


</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://github.com/Expensify/App/assets/16493223/4b8955f1-1d75-49af-9e6e-99dbeab690ab


</details>

<details>
<summary>Mobile Web - Safari</summary>



https://github.com/Expensify/App/assets/16493223/f3260282-cf8a-42b1-be12-1f981570933b


</details>

<details>
<summary>Desktop</summary>



https://github.com/Expensify/App/assets/16493223/7d5b8b14-17df-446c-a8f5-12413a0dcfea


</details>

<details>
<summary>iOS</summary>



https://github.com/Expensify/App/assets/16493223/5a9759d4-9e72-4df7-b4df-b28657645a0f


</details>

<details>
<summary>Android</summary>



https://github.com/Expensify/App/assets/16493223/0c0a4669-cc1e-40bd-b13c-d7dcbfc380ab


</details>

**Comment by b4s36t4** [comment]
Thanks @s77rt.!!

**Comment by s77rt** [comment]
Please update the title to reflect the new changes, checkout the rest of unchecked boxes. You need to test on iOS it's mandatory, I see this is your first PR so I think it's okay to ignore for this one. But please next time before you submit a proposal have all the OS requirements for tests

**Comment by b4s36t4** [comment]
Thanks so much @s77rt, installing xcode now. Updated the title and checked all the boxes as well.

**Comment by s77rt** [comment]
Please check the checklist again, it does not look to have the correct format (in "I added steps for the expected offline behavior in the Offline steps section")

**Review by s77rt — APPROVED** [review]
LGTM! :rocket: 

cc @mountiny

**Comment by marcochavezf** [comment]
Reassigning @mountiny here as reviewer, since he was assigned originally in the linked issue

**Review by mountiny — APPROVED** [review]
Thanks everyone! 

@b4s36t4 congrats on your first pr!

Please going forwards always link issues with a full link in the PR body: `$ https://github.com/Expensify/App/pull/22217` for example so the automation works correctly thanks!

**Pull request merged**
