### PR TITLE
Create different files for HTML Render and fix scroll width

### PR DESCRIPTION
**Pull request by jeet-dhandha**
### Details

Follow Up Changes
- Created `MenuItemRenderHTMLTitle` for Rendering HTML based on platforms.

### Fixed Issues

$ https://github.com/Expensify/App/issues/27722
$ https://github.com/Expensify/App/issues/27777
$ https://github.com/Expensify/App/issues/27802
$ https://github.com/Expensify/App/issues/27881
PROPOSAL: https://github.com/Expensify/App/issues/27722#issuecomment-1725057516

### Tests

1. Open any chat and open assign task modal.
2. Then add a long description including a url and press next.
3. Verify that the description should be wrapped and not overflow.

- [X] Verify that no errors appear in the JS console

### Offline tests

1. Open any chat and open assign task modal.
2. Then add a long description including a url and press next.
3. Verify that the description should be wrapped and not overflow.

### QA Steps

1. Open any chat and open assign task modal.
2. Then add a long description including a url and press next.
3. Verify that the description should be wrapped and not overflow.

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Screenshot 2023-09-19 at 4 18 29 PM
Screenshot 2023-09-19 at 4 18 51 PM

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screenshot 2023-09-19 at 4 30 03 PM
Screenshot 2023-09-19 at 4 31 59 PM

</details>

<details>
<summary>Mobile Web - Safari</summary>

Screenshot 2023-09-19 at 4 22 24 PM
Screenshot 2023-09-19 at 4 23 12 PM

</details>

<details>
<summary>Desktop</summary>

Screenshot 2023-09-19 at 4 34 21 PM
Screenshot 2023-09-19 at 4 34 51 PM

</details>

<details>
<summary>iOS</summary>

Screenshot 2023-09-19 at 4 20 21 PM
Screenshot 2023-09-19 at 4 20 56 PM

</details>

<details>
<summary>Android</summary>

Screenshot 2023-09-19 at 4 26 23 PM
Screenshot 2023-09-19 at 4 28 06 PM

</details>

### CODE REVIEW

**Comment by narefyev91** [comment]
## Reviewer Checklist
- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://github.com/Expensify/App/assets/28352309/8542edb2-742a-44a5-93ae-fd1e77b6438f




</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/28352309/4cd94da4-ea2d-4c86-ab29-66ef86f40c6b




</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/28352309/5214c463-dd4d-4ba9-8eb9-0a118d4469d9




</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/assets/28352309/7ec55552-3f30-4614-acc5-6b16627aab2a




</details>

<details>
<summary>iOS</summary>


https://github.com/Expensify/App/assets/28352309/b3141a81-3d6e-413d-a715-4cc52b392499




</details>

<details>
<summary>Android</summary>


https://github.com/Expensify/App/assets/28352309/ba9598a5-4f6f-48dd-ac7a-6d8ed6df3c1d




</details>

**Review by narefyev91 — APPROVED** [review]
LGTM!
🎀 👀 🎀 C+ reviewed

**Review by narefyev91 — CHANGES_REQUESTED** [review]
One more potential blocker

**Comment by narefyev91** [comment]
@jeet-dhandha can you check this one https://github.com/Expensify/App/issues/27777

**Comment by jeet-dhandha** [comment]
Checking @narefyev91

**Comment by jeet-dhandha** [comment]
Yes @narefyev91 caused due to this as maximum 2 lines should only be rendered for Assign Task and we didn't think this one through.

**Comment by narefyev91** [comment]
> Do you have any suggestions on how we can handle trailing in `RenderHTML` ?

@jeet-dhandha https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#defaulttextprops - can be used

**Comment by jeet-dhandha** [comment]
Let me check that

**Comment by jeet-dhandha** [comment]
Fixed the overflow issue @narefyev91 @thienlnam.

**Comment by jeet-dhandha** [comment]
Handled https://github.com/Expensify/App/issues/27777.

**Comment by jeet-dhandha** [comment]
### Screenshots/Videos
<details>
<summary>Web</summary>




https://github.com/Expensify/App/assets/78416198/50828b24-9c25-415e-a9bb-e8ca6b2a8c52


</details>

<details>
<summary>Mobile Web - Chrome</summary>



https://github.com/Expensify/App/assets/78416198/41e560d1-8b22-4e60-95fa-023b6b02769c



</details>

<details>
<summary>Mobile Web - Safari</summary>




https://github.com/Expensify/App/assets/78416198/74444f2d-5d82-4e2e-87c7-5e7bc4215d37


</details>

<details>
<summary>Desktop</summary>




https://github.com/Expensify/App/assets/78416198/9d778c92-0197-4dd1-ab18-b5afe0d48147


</details>

<details>
<summary>iOS</summary>




https://github.com/Expensify/App/assets/78416198/aa591377-f497-4254-93ca-29ec24863981


</details>

<details>
<summary>Android</summary>




https://github.com/Expensify/App/assets/78416198/ddc4a44b-3230-4ceb-a8a8-724bd1ffd2ba


</details>

**Comment by jeet-dhandha** [comment]
Updated Videos for Overflow issue

**Comment by jeet-dhandha** [comment]
Yes but if we set scroll on full `task view` then user might get frustrated when user just want to change assignee.

**Comment by narefyev91** [comment]
https://github.com/Expensify/App/issues/27812 @jeet-dhandha and one regression - please take a look

**Comment by jeet-dhandha** [comment]
@narefyev91 now the issue is that the regressions are now becoming more and more of feature based requests and this should have been mentioned in the original issue. It should have been mentioned by me or by another contributor to write down the full scope but we could say it was a mistake and i think we should first clear up the full scope of the Feature Request and then continue on this PR.

**Comment by jjcoffee** [comment]
@narefyev91 @jeet-dhandha Should we add a HOLD on https://github.com/Expensify/App/issues/27812 to give you a chance to fix the regression?

**Comment by narefyev91** [comment]
@jjcoffee  i think yup - we need to fix 2 issues - and should be nice to have some time to double check everything

**Review by fedirjh — CHANGES_REQUESTED** [review]

**Comment by jeet-dhandha** [comment]
Fixed:
- https://github.com/Expensify/App/issues/27881 (Cursor Issue)
- Added ScrollView to https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskPage.js 
- Removed scrollview from `MenuItem`

**Comment by jeet-dhandha** [comment]
Nope @narefyev91 , we can take up proposals on that one. As its more of a feature request.

**Comment by narefyev91** [comment]
@jeet-dhandha button on confirm task screen now not fixed in the bottom
Staging:
Screenshot 2023-09-21 at 13 39 08
Current version:
Screenshot 2023-09-21 at 13 39 15

**Comment by jeet-dhandha** [comment]
I wrapped the submit button in scrollview thats why. 

Quick question:
- should the confirm task button visible even when there’s long description ?
- Or should it be sticked to bottom when there’s short description but when there’s long description it should be hidden and should be visible when scrolled down ?

**Comment by narefyev91** [comment]
> I wrapped the submit button in scrollview thats why.
> 
> Quick question:
> 
> * should the confirm task button visible even when there’s long description ?
> * Or should it be sticked to bottom when there’s short description, but when there’s long description it should be hidden and should be visible when scrolled down ?

It should following the same behaviour from Request money flow
Screenshot 2023-09-21 at 13 47 19
Screenshot 2023-09-21 at 13 47 51

**Comment by narefyev91** [comment]
## Reviewer Checklist
- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



https://github.com/Expensify/App/assets/28352309/b6a15308-b45f-47ae-9daa-c07463fd56b5



</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/28352309/f0edf146-1b10-4978-91a9-43776c865d4c




</details>

<details>
<summary>Mobile Web - Safari</summary>


https://github.com/Expensify/App/assets/28352309/47bcd256-9e29-4452-90ae-4ecd609ea75a




</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/assets/28352309/d9c636b2-78d1-403d-8bcb-2e1024354418




</details>

<details>
<summary>iOS</summary>


https://github.com/Expensify/App/assets/28352309/24dd0410-6e93-4d04-8f75-009ad5c9506c




</details>

<details>
<summary>Android</summary>


https://github.com/Expensify/App/assets/28352309/2974c3cf-b473-42bf-8dd0-a3ed945d79e4




</details>

**Comment by narefyev91** [comment]
All issues which we linked to this PR - fixed
Only need to make a fix for button position and we good to go

**Comment by jeet-dhandha** [comment]
### Screenshots/Videos (Confirm Task - Button Fix)
<details>
<summary>Web</summary>




https://github.com/Expensify/App/assets/78416198/8c645866-7fe9-4476-bb91-a4c5ab426f29




</details>

<details>
<summary>Mobile Web - Chrome</summary>




https://github.com/Expensify/App/assets/78416198/0304558d-ee5f-496b-a1fc-e0bcb1763599



</details>

<details>
<summary>Mobile Web - Safari</summary>





https://github.com/Expensify/App/assets/78416198/68fcd173-43e2-418c-ba3d-f7e96581a7c3



</details>

<details>
<summary>Desktop</summary>





https://github.com/Expensify/App/assets/78416198/dc8240e4-10a7-48b4-ad64-6cfea84278e9



</details>

<details>
<summary>iOS</summary>





https://github.com/Expensify/App/assets/78416198/b94de750-21f0-4033-b6ca-00411a7ef1b8



</details>

<details>
<summary>Android</summary>




https://github.com/Expensify/App/assets/78416198/d554b9b2-e929-47ec-9423-80230a866440




</details>

**Comment by jeet-dhandha** [comment]
@narefyev91 @thienlnam

**Review by narefyev91 — APPROVED** [review]
LGTM!
🎀 👀 🎀 C+ reviewed

**Review by thienlnam — APPROVED** [review]
Great, thanks for doing this!

**Comment by garrettmknight** [comment]
@burczu mentioned that [this issue](https://github.com/Expensify/App/issues/28623) and [this issue](https://github.com/Expensify/App/issues/27802) might be regressions from this PR. @jeet-dhandha can you take a look and fix?

**Pull request merged**
