### PR TITLE
Bump Airship library to resolve iOS deep link issue

### PR DESCRIPTION
**Pull request by Julesssss**
### Details

Actioning this message from Airship: 

> We found and fixed an issue with iOS open events not triggering if they contain a deep link in them. The first one will work, the next ones wont. Not sure if you use deep links, but you should update if you do

### Fixed Issues

$ https://github.com/Expensify/App/issues/18704

### Tests

- [x] Verify that no errors appear in the JS console

### Offline tests

Airship notifications not received while offline...

### QA Steps

**Test deep link notifications**
- _Notification setup for internal dev builds_ (or use the CI QR code builds)
- Sign in on web and mobile devices
- Send notification from web user to mobile user
- Notification should be recieved
- Tapping notification should open app and take user to the specific chat (there are existing bugs, but it should mostly work)

### PR Author Checklist

- [x]  I linked the correct issue in the `### Fixed Issues` section above
- [x]  I wrote clear testing steps that cover the changes made in this PR
    - [x]  I added steps for local testing in the `Tests` section
    - [x]  I added steps for the expected offline behavior in the `Offline steps` section
    - [x]  I added steps for Staging and/or Production testing in the `QA steps` section
    - [x]  I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x]  I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x]  I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x]  I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x]  I ran the tests on **all platforms** & verified they passed on:
    - [x]  Android / native
    - [x]  Android / Chrome
    - [x]  iOS / native
    - [x]  iOS / Safari
    - [x]  MacOS / Chrome / Safari
    - [x]  MacOS / Desktop
- [x]  I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x]  I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x]  I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x]  I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x]  I verified that comments were added to code that is not self explanatory
    - [x]  I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x]  I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x]  If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x]  I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x]  I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x]  I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x]  I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x]  If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x]  I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x]  I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x]  I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x]  I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x]  I verified that if a function's arguments changed that all usages have also been updated correctly
- [x]  If a new component is created I verified that:
    - [x]  A similar component doesn't exist in the codebase
    - [x]  All props are defined accurately and each prop has a `/** comment above it */`
    - [x]  The file is named correctly
    - [x]  The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x]  The only data being stored in the state is data necessary for rendering and nothing else
    - [x]  For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x]  Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x]  All JSX used for rendering exists in the render method
    - [x]  The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x]  If any new file was added I verified that:
    - [x]  The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x]  If a new CSS style is added I verified that:
    - [x]  A similar style doesn't already exist
    - [x]  The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x]  If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x]  If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x]  If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x]  If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x]  If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x]  I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos

Airship only used on native iOS/Android

**iOS**

**Android**

### CODE REVIEW

**Comment by Julesssss** [comment]
Creating QR code builds [here](https://github.com/Expensify/App/actions/runs/4936658570)

**Comment by abdulrahuman5196** [comment]
@Julesssss  I am assuming the PR is in ready state since the author checklist is almost done and PR in open state with testing builds. So going ahead with my review.
1) Seems we have only updated package-lock.json but not package.json?
2) The Lint test and unit test have failed, but it is showing unrelated change content of related to 'participants'. Could it be because of recent Prettier addition? Should we do a merge from main as suggested in #expensify-open-source.
3) I am able to successfully install and test in android from the builds, but for iOS i am getting "This app cannot be installed because its integrity could not be verified" error. Do I need to part of team or get provisioning profile to test the change in real devices? Could you let me know if any process needs to be done from my end to test on ios?

**Comment by Julesssss** [comment]
Hi @abdulrahuman5196. 

> 1) Seems we have only updated package-lock.json but not package.json?

Yeah, I don't see any local changes when running `npm i`. Is that not expected?

> 2) The Lint test and unit test have failed, but it is showing unrelated change content of related to 'participants'. Could it be because of recent Prettier addition? 

I just merged main 👍 

> 3) Do I need to part of team or get provisioning profile to test the change in real devices? Could you let me know if any process needs to be done from my end to test on ios?

Ah, perhaps. I think it's impossible for you to test iOS notifications actually. I'll do this myself now.

**Comment by abdulrahuman5196** [comment]
Hi @Julesssss, package-lock.json is the auto generated file. 
We should update `package.json` and run - `npm install` or `npm i` it will auto generate package-lock.json file. 

I assume since you had manually updated package-lock file it didn't show difference during install. But it could lead to inconsistency so we should package.json.

**Comment by abdulrahuman5196** [comment]
It seems Melvin Bot also pointed the same - https://github.com/Expensify/App/pull/18710#issuecomment-1542069761

**Comment by Julesssss** [comment]
Ohh I see my mistake now. Thanks. 

I searched for the library and didn't check the file name 🤦

**Comment by Julesssss** [comment]
Okay, holding this as iOS min version seemed to have been reverted, and that is needed for the Airship lib bump. [Internal conversation](https://expensify.slack.com/archives/C04E99DVBTP/p1683743876868229?thread_ts=1683594191.793649&cid=C04E99DVBTP).

**Comment by Julesssss** [comment]
Hey @abdulrahuman5196, the PR is actually ready for you this time 😅

We'll test iOS 👍

**Comment by abdulrahuman5196** [comment]
@Julesssss  sure thank you. Starting to look into it.

**Comment by abdulrahuman5196** [comment]
@Julesssss  sure thank you. Starting to look into it.

**Comment by abdulrahuman5196** [comment]
@Julesssss 
The changes looks good to me.

I also tested the below and all looks good to me.
1) For any regression on android, there wasn't any(there where issues in push notification but i was able to repro those in playstore builds as well)
2) Building iOS locally and there wasn't any new auto-generated code content.
3) Also checked for console errors in debug builds for ios and android for the package update.


Only action item pending is 
1) Author testing on iOS and adding author screenshots/videos in the author's checklist.

**Review by abdulrahuman5196 — APPROVED** [review]

**Comment by Julesssss** [comment]
Thanks for the review. Due to higher priority issues, I'll add the screenshots and request the internal review in about a week.

**Comment by Julesssss** [comment]
Looking at the changes I think we've bumped the lib elsewhere... nevermind

**Pull request closed without merging**
