### PR TITLE
Upgrade RN-web

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

1. Submitted a new PR to our RN-web fork https://github.com/Expensify/react-native-web/pull/5

I just found out that we were not using the latest commit from our RN-web fork. Any specific reason. 
ll

### Fixed Issues

$ https://github.com/Expensify/App/issues/7206
$ https://github.com/Expensify/App/issues/6913
### Tests | ### QA Steps
1. Test all the listed issues on the linked issue.
2. Test that ellipsis are shown correctly on LHN when chat title length exceeds the width of LHN.
3. Check the same for Search page. 
4. Check that Ellipsis are shown near the RIght edge of the screen. And does not start from the middle of the screen. 

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Web

image

### CODE REVIEW

**Comment by Beamanator** [comment]
Hmm good point, I guess previously, the changes in https://github.com/Expensify/react-native-web/commit/5548f3ab68f5dfac293e9592e0efd6ed61c3b50e were only comment changes, so no big deal that the last commit wasn't set in E/App

**Review by Beamanator — APPROVED** [review]

**Comment by Beamanator** [comment]
@parasharrajat I think you should also mention that this PR fixes https://github.com/Expensify/App/issues/6913

**Comment by parasharrajat** [comment]
Updated. Actually, this fixes many issues so I thought of only referencing the Tracking issue.

**Comment by Beamanator** [comment]
Hmm I think it's best if you can link all of the GH issues this will fix, because we have some automation that goes through merged PRs per release, finds all issues linked to PRs, and comments on them with the PR that is fixing said issue

**Pull request merged**
