### PR TITLE
Fix immediately prompt for Camera permission in scan request flow

### PR DESCRIPTION
**Pull request by dukenv0307**
### Details

Fix immediately prompt for Camera permission in scan request flow
### Fixed Issues

$ https://github.com/Expensify/App/issues/37737
PROPOSAL: https://github.com/Expensify/App/issues/37737#issuecomment-1978651716

### Tests / QA Steps

- For native Android / IOS / mWeb

1. Reset permission of the app
2. Go to FAB > Request Money > Scan
3. Verify that the camera request permission prompt doesn't appear
4. Click on the Continue button or capture icon
6. Verify that the camera request permission prompt appears
7. Accept the permission and verify that we can capture the photo

- For web/desktop

1. Go to FAB > Request Money > Scan
2. Verify that no prompt appears
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as above

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/129500732/5744c069-e915-455a-a13d-13f62dd27934

https://github.com/Expensify/App/assets/129500732/f7815ec3-118f-413e-8eaf-8deb51471977

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/129500732/ff5f1f28-371c-45c7-9b8b-25bfafd804b1

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/129500732/624a3bee-2b7d-4cb6-875f-03646c7d7fbd

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/129500732/b966ec4b-8415-4d75-8a05-af36b86a1418

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/129500732/0d376b77-3139-433b-9405-d97ed70c2e4b

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/129500732/e137f6ac-a4d2-44a6-81be-ee2fc798aa94

</details>

### CODE REVIEW

**Comment by Julesssss** [comment]
Yep, build in progress. I also want to manually test some other cases:

- User presses continue, approves our modal, enables OS permission
- User presses continue, approves our modal, rejects OS permission
- User presses continue, disapproves our modal, uploads image
- User previously rejected us 2 times, approves our modal, approves our modal and manually re-enables permission

**Comment by cubuspl42** [comment]
The code looks good

**Comment by cubuspl42** [comment]
@dukenv0307 

Would you execute these [extra testing steps](https://github.com/Expensify/App/pull/37817#issuecomment-1983136482)? I agree that we should ensure to cover all corner cases, and these are great starting points.

**Comment by cubuspl42** [comment]
@dukenv0307 This might be a dumb question, but why is the ad-hock build needed? Why is a local build not suitable?

**Comment by Julesssss** [comment]
> I'm not added to adhoc device list

We've had trouble doing this as Apple make the process very annoying, but send me your UUID and I'll try and add your device to our list.

> but why is the ad-hock build needed? Why is a local build not suitable?

Maybe there is another reason, but I use AdHoc builds for any test that requires us to background the mobile app, as I'm not convinced the dev builds behave exactly the same way.

**Comment by cubuspl42** [comment]
Please merge `main`

**Comment by cubuspl42** [comment]
My results for iOS / Web (physical iPhone):

https://github.com/Expensify/App/assets/2590174/8350fd9a-2aeb-4f09-8424-042386078818

Is this expected?

**Comment by cubuspl42** [comment]
Please update the testings steps then

**Comment by cubuspl42** [comment]
On this [video](https://github.com/Expensify/App/pull/37817#issuecomment-1994080934), I'm showing that this step fails on iOS/Web:

> Verify that the camera request permission prompt **doesn't appear**

I'm immediately prompted for the camera permission after opening the Request Money / Scan tab.

**Comment by cubuspl42** [comment]
I asked on the GH issue to confirm this: https://github.com/Expensify/App/issues/37737#issuecomment-1997104406

**Comment by Julesssss** [comment]
> Yeah, it's expected.

Wait, I don't think that's expected. The point o this issue was to prevent the permission prompt from accruing when opening the page: 

> Verify that the camera request permission prompt doesn't appear

**Comment by Julesssss** [comment]
I responded ton the issue but to confirm, mWeb should work the same way as mobile (providing we aren't restricted by OS differences).

**Review by Julesssss — COMMENTED** [review]
Could we revert the mWeb test to ensure it matched the native mobile flows please

**Comment by cubuspl42** [comment]
My primary motivation was to ensure there was consistency between our expected results and actual results. But my intuition matched yours, @Julesssss, that's why I raised the topic when @dukenv0307 updated the expected results.

@dukenv0307 Please handle this. Ping me when you're done or encounter some problems 🙂

**Comment by Julesssss** [comment]
Is there a way to prevent mounting that component so that mWeb can use our existing UI prompt?

**Comment by cubuspl42** [comment]
I'd assume it's possible

**Comment by cubuspl42** [comment]
- Would you update the Android Web video?
- Have you tested this on iOS Web?
  - Do you have access to a physical iOS device, or have verified that this is working as expected on iOS Safari?
  - It's not, you should note this

**Comment by cubuspl42** [comment]
QA Steps are outdated. Sometimes for this reason, **if** it makes sense for both to be the same, we write "Tests / Same as QA Steps".

**Comment by Julesssss** [comment]
One small change, shouldn't the web/desktop test be: 

1. Clear browser permissions
2. Go to FAB > Request Money > Scan
3. Verify that no prompt appears
4. Tap the 'Continue (and prompt me for location)' button 
5. Prompt should appear
- [x] Verify that no errors appear in the JS console

**Comment by cubuspl42** [comment]
Let's clarify something once and for all. I thought we clarified this before, but there's still some confusion. Please correct any part of my reasoning that is not correct.

This is what we call "Explainer UI":

image

I understood that we agreed to extend the scope of this issue to synchronizing the experience between the mobile Native and mobile Web, showing the Explainer UI before asking for camera permission on **both** mentioned configurations.

@dukenv0307 @Julesssss
What is your perspective?

**Comment by cubuspl42** [comment]
> What is your perspective?

When I asked this, I meant "do you also see it this way, that we _agreed_ to make the UI consistent?". From my perspective, we **did** agree and it's still on a todo list for this PR.

**Comment by cubuspl42** [comment]
Thanks! Clarified.

@dukenv0307 Please implement this so the behavior is 1:1 (or reasonably close to 1:1) on mobile Web and mobile Native, stressing that the previously mentioned "Explainer UI" should be presented to the user in both cases.

**Comment by cubuspl42** [comment]
I found this issue on iOS Web (maybe affects Android Web too?):

https://github.com/Expensify/App/assets/2590174/2cde82d7-8785-42c5-b244-bc1c38f46e8a

If I navigate from "Manual" to the "Scan" tab after opening the new money request route, I get an infinite loader. I need to re-enter the tab to make things right.

**Comment by cubuspl42** [comment]
@dukenv0307 Are you working on this? 🙂

**Comment by cubuspl42** [comment]
Please merge `main`, we're over 1000 commits behind.

I'm testing the newest changes.

**Comment by cubuspl42** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/2590174/7af796a2-004a-48b7-a098-0961820f956f

</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/2590174/2e8f7062-3094-493b-bd86-eafae8d511b9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/2590174/ab3e843a-492f-4b46-810f-a46ad48493e3

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by jakub-trzebiatowski — APPROVED** [review]

**Review by Julesssss — APPROVED** [review]
Video captures look great to me, thanks both.

**Comment by Julesssss** [comment]
What... I didn't see that button 😕

**Comment by Julesssss** [comment]
Ignoring the flakey performance check

**Comment by Julesssss** [comment]
Not an emergency, the perf test is flakey

**Pull request merged**
