### PR TITLE
Remove usages of avatarURL for policies

### PR DESCRIPTION
**Pull request by jasperhuangg**
Currently held on https://github.com/Expensify/Web-Expensify/pull/34816

### Details
This PR removes usages of `avatarURL` for policies in the front-end, since we're sending the actual avatarURL in `avatar` now from PHP in https://github.com/Expensify/Web-Expensify/pull/34740. This keeps policies more in-line with personalDetails, in that we access avatarURLs for both entities from `avatar` now.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/225573

### Tests
1. Sign into any account, open a Workspace, and go to its Settings.
2. Click on the avatar picker and upload an avatar. Verify that no loading indicator appears, and that your avatar updates immediately after you click "Save" (the "Save" button in the cropping modal). Hard refresh (`<Command><Shift><R>`) the page, and verify that the new avatar is persisted.
3. Be ready to turn off your device wifi very quickly. Repeat step 3, but IMMEDIATELY turn off your device wifi before the avatar can finish uploading. It should still show the new avatar, but it should be greyed out like so:
    Screen Shot 2022-08-26 at 9 59 10 AM

4. Turn your device wifi back on, and verify the upload completes and the avatar isn't greyed out anymore.
5. Now click on the avatar picker again and select "Remove photo". Verify that the avatar is replaced with a default avatar. Reload the page and verify that this is persisted.

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

</details>

### QA Steps

- [ ] Verify that no errors appear in the JS console

### CODE REVIEW

**Comment by Beamanator** [comment]
I'll review when this is taken off draft ok? :D

**Comment by jasperhuangg** [comment]
@Beamanator No worries! I requested for review and then realized the tests were broken on https://github.com/Expensify/Web-Expensify/pull/34740 so put it back on draft

Code changes should be good to review now, but we're going to have to hold off on testing again until that PR is on production again 🙄. I personally haven't been able to attempt those testing steps myself yet for this very reason.

**Comment by jasperhuangg** [comment]
@Beamanator I'll lyk when the Web-E PR is on prod so we can test this one out :)

https://github.com/Expensify/Web-Expensify/pull/34740

**Comment by jasperhuangg** [comment]
> @Beamanator I'll lyk when the Web-E PR is on prod so we can test this one out :)
> 
> [Expensify/Web-Expensify#34740](https://github.com/Expensify/Web-Expensify/pull/34740)

@Beamanator eeez on prod, testing rn

**Comment by jasperhuangg** [comment]
Oooof it doesn't work, investigating what's going on

**Comment by Beamanator** [comment]
Dangit lol

**Review by cristipaval — COMMENTED** [review]
Tested this on my end and seems that it fails after turning wifi back on. The avatar remains greyed out and after a hard refresh I get this
Screenshot 2022-09-12 at 11 39 16

**Review by Beamanator — APPROVED** [review]
Overall looking great! Had a few tiny comments on the Web-E PR

**Comment by Beamanator** [comment]
Web-E PR merged 👍 still waiting on it getting deployed to prod to test this thoroughly

**Comment by jasperhuangg** [comment]
@Beamanator Looks like Web-Expensify PR is on prod! Just tested after updating my `.env` file to use the production API:

```
NEW_EXPENSIFY_URL=https://new.expensify.com/
SECURE_EXPENSIFY_URL=https://secure.expensify.com/
EXPENSIFY_URL=https://www.expensify.com/
EXPENSIFY_PARTNER_NAME=chat-expensify-com
EXPENSIFY_PARTNER_PASSWORD=e21965746fd75f82bb66
PUSHER_APP_KEY=268df511a204fbb60884
USE_WEB_PROXY=true
ENVIRONMENT=development
```

and it seems to still be broken? I'm so confused, since we're clearly copying `avatarURL` into `avatar` here, but the response still shows up in `avatarURL`. I also tested Web-Expensify PR policy update with a hard-coded avatarURL just to make sure this wouldn't happen.. ughhhhh

I'm investigating right now, looks like we might need to get another Web-E PR out, sorry :/

**Comment by jasperhuangg** [comment]
https://github.com/Expensify/Web-Expensify/pull/34816 is on staging, we'll be able to test soon!

**Comment by Beamanator** [comment]
Eyyy it's finally on prod!

**Comment by Beamanator** [comment]
Still working very well for me! Note: in step 3 of the tests, we can just start with the app offline, since we're using Pattern B 

Also @jasperhuangg I thinkkk you still need to add QA tests :D

**Comment by Beamanator** [comment]
Took off hold since the Web-E PR is on Prod, and merged since tests pass 👍

**Comment by luacmartins** [comment]
@jasperhuangg This worked for me on staging. However, when we turn wifi back on the avatar momentarily reverts back to the old one. I think this happens because we call `ReconnectApp` first which still has the old avatar.

Uploading Screen Recording 2022-09-21 at 10.46.06 AM.mov…

**Comment by jasperhuangg** [comment]
> @jasperhuangg This worked for me on staging. However, when we turn wifi back on the avatar momentarily reverts back to the old one. I think this happens because we call `ReconnectApp` first which still has the old avatar. We should avoid that flicker, what do you think?
> 
>  Screen.Recording.2022-09-21.at.10.46.06.AM.mov

I agree, this flickering issue is actually an issue in a bunch of other areas of the App, I'm wondering if we should create a parent issue to deal with this. 

Basically, when we reconnect the App, we should avoid updating Onyx values that have `pendingActions`. I do something similar [here](https://github.com/Expensify/App/blob/09ff150d126765c12f783991537e55fea283eb92/src/libs/actions/App.js#L57-L70) for workspaces that are created offline. Perhaps something needs to be built into the [`SaveResponseIntoOnyx`](https://github.com/Expensify/App/blob/main/src/libs/Middleware/SaveResponseInOnyx.js) middleware?

**Comment by luacmartins** [comment]
>I agree, this flickering issue is actually an issue in a bunch of other areas of the App, I'm wondering if we should create a parent issue to deal with this.

Agreed. I'd bring this up in Slack and see where we go from there.

**Comment by jasperhuangg** [comment]
@luacmartins already on that haha message in my drafts rn

**Comment by jasperhuangg** [comment]
https://expensify.slack.com/archives/C03TQ48KC/p1663797332998359 @luacmartins

**Pull request merged**
