### PR TITLE
Handle potential CORS issues during file downloads

### PR DESCRIPTION
**Pull request by kidroca**
- Added logic to resolve URLs using `tryResolveUrlFromApiRoot`.
- For URLs not originating from the API root (3rd party), leverage the browser's built-in functionality by opening them in a new tab to avoid CORS limitations during direct downloads.

### Details

Given the security enhancements in browsers, they only permit the click() method on `<a>` elements with a 'download' attribute if invoked directly by user actions. The prior version of the function, which attempted to open it in new tab if the download failed fetched, sometimes led to a delayed user response, and the action was blocked.

### Fixed Issues

$ https://github.com/Expensify/App/issues/19965
PROPOSAL: https://github.com/Expensify/App/issues/19965#issuecomment-1648212294
Also related: https://github.com/Expensify/App/issues/23094#issuecomment-1686037864

#### **Scenario 1 - Validate Concierge Drag & Drop Attachments**

**Objective**: Ensure attachments added by Concierge through Drag & Drop are downloadable across platforms.

**Prerequisites**: A chat session with Concierge.

**Steps**:

- **General**:
    1. Initiate a chat with Concierge.
    2. Request Concierge to send inline image attachments using the Drag & Drop method.

- **On Web / Desktop**:
    1. Click on any of the received attachments.
    2. Click the Download button located in the upper right corner.
    3. Note: Since the attachment is sourced directly from Amazon S3 (which is a different origin), it will not directly download but will open in a new browser tab/window.

- ~**On iOS / Android**~ (a regression prevents testing this flow in the current PR):
    1. ~Tap on any of the received attachments.~
    2. ~Tap the Download button located in the upper right corner.~
    3. ~Observation: Unlike web platforms, native apps are unaffected by CORS. As such, the attachment should download directly to the device.~

#### **Scenario 2 - Confirm Functionality of Regular Attachments**

**Objective**: Ensure that attachments (excluding those from Concierge) are downloadable across all platforms.

**Prerequisites**: A chat session with an existing attachment (This could be any chat other than with Concierge).

**Steps**:

1. Navigate to a chat that contains an attachment. This can be an attachment sent by you or another party.
2. Open the attachment.
3. Click/Tap the Download button located in the upper right corner.
4. Observation: The attachment should initiate a direct download, saving it to your device or system.

### Offline tests

N/A - attachments cannot be downloaded while offline

#### **Scenario 1 - Validate Concierge Drag & Drop Attachments**

**Objective**: Ensure attachments added by Concierge through Drag & Drop are downloadable across platforms.

**Prerequisites**: A chat session with Concierge.

**Steps**:

- **General**:
    1. Initiate a chat with Concierge.
    2. Request Concierge to send inline image attachments using the Drag & Drop method.

- **On Web / Desktop**:
    1. Click on any of the received attachments.
    2. Click the Download button located in the upper right corner.
    3. Note: Since the attachment is sourced directly from Amazon S3 (which is a different origin), it will not directly download but will open in a new browser tab/window.

- ~**On iOS / Android**~ (a regression prevents testing this flow in the current PR):
    1. ~Tap on any of the received attachments.~
    2. ~Tap the Download button located in the upper right corner.~
    3. ~Observation: Unlike web platforms, native apps are unaffected by CORS. As such, the attachment should download directly to the device.~

#### **Scenario 2 - Confirm Functionality of Regular Attachments**

**Objective**: Ensure that attachments (excluding those from Concierge) are downloadable across all platforms.

**Prerequisites**: A chat session with an existing attachment (This could be any chat other than with Concierge).

**Steps**:

1. Navigate to a chat that contains an attachment. This can be an attachment sent by you or another party.
2. Open the attachment.
3. Click/Tap the Download button located in the upper right corner.
4. Observation: The attachment should initiate a direct download, saving it to your device or system.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
        - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/12156624/35ecb81f-ebb2-477d-9276-883e030b95ea

https://github.com/Expensify/App/assets/12156624/08d1a802-2a5c-462b-96b5-d89c3dd56a57

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/12156624/e9be29ff-59b1-436e-8585-0766f08499f0

https://github.com/Expensify/App/assets/12156624/2c18acb6-8815-4fe0-8628-124a79db7482

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/12156624/7a7cb7b7-4996-4f63-9776-2373dee5e74c

https://github.com/Expensify/App/assets/12156624/63533841-cdf0-4adc-8b4d-235f3fe21d62

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/12156624/91c5416b-035c-4b78-8418-4a3db6a9ba3d

https://github.com/Expensify/App/assets/12156624/2d1d310e-77e8-46e3-a106-ae20a939723a

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/12156624/23896882-774c-4c81-ba1a-ab21e014039e

https://github.com/Expensify/App/assets/12156624/6ac412a0-fc50-4a51-915d-4a3a8eb86308

</details>

<details>
<summary>Android</summary>

[Screen_recording_20230901_192418.webm](https://github.com/Expensify/App/assets/12156624/3b50b7ad-8479-4fca-99ad-c98cedb45467)

[Screen_recording_20230901_192618.webm](https://github.com/Expensify/App/assets/12156624/ee213d47-7989-459c-8012-c0b7bd8aa3f9)

</details>

### CODE REVIEW

**Comment by kidroca** [comment]
Updated with latest changes from `main`

**Comment by kidroca** [comment]
@aimane-chnaif 
> @kidroca please fix these console errors

I've added the following fix: da50bf4e

**Comment by kidroca** [comment]
Conflicts resolved

**Comment by kidroca** [comment]
I think we shouldn't have attempted to address the external regressions identified during testing, and that doing so caused significant delays to this PR.  
To streamline the process, I'll be revert any fixes in this PR that aren't directly related to the issue at hand.

Let's acknowledge 
- the regressions around `fileName` handling aren't a result of the changes introduced in this PR.
- We've identified and highlighted the root cause of the regression: https://github.com/Expensify/App/issues/23094#issuecomment-1686037864
- you don't expect me to fix the regressions under the scope of the current ticket
- you can hire me or anyone else to address the said regressions in a follow-up

**Review by aimane-chnaif — APPROVED** [review]

**Review by jasperhuangg — APPROVED** [review]

**Comment by kidroca** [comment]
> @kidroca I think we should not open new tab when download local image (blob). Let's fix that in new PR.

Thank you for the suggestion, @aimane-chnaif. I understand the scenario you're pointing out, but I believe it represents a very specific use case. The situation where a user tries to download an attachment they've just uploaded, before the upload process has completed is quite rare in typical user workflows.

Moreover, in the event that this does occur, it doesn't seem to cause any errors - the system handles it by re-rendering the attachment once the backend URL is ready, as in the video you've shared.

Given that this edge case neither breaks the app nor degrades the user experience significantly, adding extra logic to handle it might unnecessarily complicate handling. Complexity should only be introduced when it's clearly warranted, and in this instance, it seems like it would be for a relatively unlikely scenario.

That said, I'm open to hearing more about your concerns. If you feel there are additional factors I might not be considering, or if this is indicative of a larger issue, I'm definitely open to discussing it further.

**Pull request merged**
