### PR TITLE
Show tooltip only when cursor is present

### PR DESCRIPTION
**Pull request by aneequeahmad**
### Details

This PR will fix the tooltip showing on touchscreens without mouse/pointer. A condition for pointer is added in filed Tooltip/index.js that show Tooltip only when there is pointer present otherwise don't show the Tooltip.
### Fixed Issues

$ https://github.com/Expensify/App/issues/9737

### Tests

1. Open any report in mWeb.
2. Long press back button in report screen and see the when navigated back `back` tooltip is not shown. 

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] Any functional components have the `displayName` property
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The Contributor+ will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

### QA Steps

1.  Launch the app on mWeb.
2. Press on any report to open it.
3. Long press back button in report screen header.
4. Navigated back and `back` tooltip is not shown. 
5. Repeat the above steps multiple times to verify that tooltip doesn't appear on Touchscreens

- [x] Verify that no errors appear in the JS console

#### Web

Screenshot 2022-09-15 at 1 03 06 PM

#### Mobile Web

https://user-images.githubusercontent.com/36359331/190351463-0bdc655d-6e44-40e0-9dbf-971564714cc7.mp4

#### Desktop

https://user-images.githubusercontent.com/36359331/190360386-39cb83da-b34c-431a-b666-706f3c5050cc.mov

#### iOS

https://user-images.githubusercontent.com/36359331/190366748-2ec299ac-6d9a-4dd5-bce8-866f0b632f54.mov

#### Android

https://user-images.githubusercontent.com/36359331/190363103-8468e16c-33ae-4760-997e-adde5e39a5d2.mov

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
This is failing for me on the web resized to a small screen

https://user-images.githubusercontent.com/85645967/194640724-ab0e29c9-2293-40fd-9893-4504cdc44918.mov

**Comment by aneequeahmad** [comment]
@Santhosh-Sellavel The tooltip will always show when there is a mouse/cursor present and in this case that you mentioned there is a mouse/cursor present that's why it's showing tooltip.

**Comment by Santhosh-Sellavel** [comment]
Yeah that's fine, but should not show on chat list

**Comment by aneequeahmad** [comment]
@Santhosh-Sellavel, I debugged the case where tooltip was shown on chat list and this is what i found.

**Tooltip not hiding root cause.**

- `showTooltip` function was invoked `onHoverIn` and after navigation to back screen `hideTooltip` function is not called as mouse is still and `onHoverOut` is not triggered to run the `hideTooltip` function(console.logs can be seen in the video below to support and explain what i just said)` 

https://user-images.githubusercontent.com/36359331/195046456-156e0383-ad00-4e13-8333-f1abb530c3ff.mov

**Solution** 

- As `componentDidUpdate` lifecycle method runs and that is the place in my opinion to add a condition that if `TooltipSense.isActive() ` and `this.state.isRendered` is `true` execute the `hideTooltip` function which will handle the tooltip case itself. 

```
 componentDidUpdate(prevProps) {
        
         if(TooltipSense.isActive() &&  this.shouldStartShowAnimation) {    //Added code
            this.hideTooltip()
        }

        if (this.props.windowWidth === prevProps.windowWidth && this.props.windowHeight === prevProps.windowHeight) {
            return;
        }
        
```

**Video after fix:**


https://user-images.githubusercontent.com/36359331/195055297-8abd9b98-ba3f-4a80-8402-a38a0e509892.mov


**Note:**

-  I didn't push the code cuz i think it would be much better if someone who has worked on this tooltip can give 
   this fix a quick look so that nothing breaks or unexpected happens. Thanks
   
   cc: @parasharrajat

**Comment by parasharrajat** [comment]
Could you please explicitly state the reason for tagging and ask questions? That user may not have the full context of the issue and also not enough time to go through it all.

**Comment by Santhosh-Sellavel** [comment]
> I didn't push the code cuz i think it would be much better if someone who has worked on this tooltip can give
this fix a quick look so that nothing breaks or unexpected happens. Thanks

It doesn't matter at this point, but that's the issue we are trying to address here 

> ##Action Performed:
> Go to chat with someone
> Go back from chat using back button and open chat again and go back.
> Repeat this process sometimes and a tool tip will appear when back on chat screen
> ##Expected Result:
> No tootip should appear on chats list screen.
> 
> ##Actual Result:
> Tooltip appear on chat list screen

I'm able to still see tooltip appears on the chat list. I think we should solve this here.

**Comment by aneequeahmad** [comment]
@Santhosh-Sellavel Fixed the issue, had to add the condition to checks if tooltip is active and didn't hide. 

The reason for tagging explicitly is that i saw this `tooltip` components logic was mainly written and changed/refactored over time by you(`now I'm afraid to tag again`) and you might have the most knowledge about this component. 

Apologies if this isn't the right way to approach someone who is not assigned to the issue.

**Comment by roryabraham** [comment]
@aneequeahmad did you mean to close this PR?

**Comment by aneequeahmad** [comment]
@roryabraham no i didn't, actually there were `merge conflicts` and sync the fork option here removed the 3 commits. 

Resolved the merge conflicts just now, was testing before pushing. Pushing in a moment and reopening the the PR. Is this flow ok to resolve conflicts ?

**Comment by parasharrajat** [comment]
It seems this PR removed a bunch of commits from the history and overwrite them.

**Comment by aneequeahmad** [comment]
@parasharrajat 

 
> 😄 I have no issues with that. Sorry if I sounded rude.
> 
> I meant to say that asking direct questions while tagging can help the person easily catch up. Additionally, you can summarize the things which might be relevant to the question that you asked.

Oh i guess i didn't get it right at first, my mistake apologies.

Also, there were some merge conflicts in `package.json and package-lock.json` and the github resolved them by removing my own commits. I then just pulled and merged the latest `Expensify:main branch`in this PR. 

You're right maybe cuz i fixed the other commented issues but after the merge the fix for tooltip hot hiding bug seems not to be working.

**Comment by roryabraham** [comment]
If you get stuck, you might be able to ask for help in `#expensify-open-source`

**Comment by aneequeahmad** [comment]
@roryabraham Thank you for mentioning the issue this PR is facing. I totally agree with you that internal resources are wasted like this in these simple kind of git things. This is the first PR of all my career(`Startup career`) that is facing these kind of unexpected issues. I'll later explain in depth why these issues occurred from the very start of this PR. 

Having said that I would like to mention some points(also answers your [query](https://github.com/Expensify/App/pull/11551#:~:text=In%20order%20to%20consider%20this%20PR%20mergeable) as well) that i noticed caused the delay for merging this simple PR. Please correct me if i'm wrong. Thanks

> Only be a reasonable number of commits (somewhere between 1 and 5, probably)

- There were only 2 [commits](https://github.com/Expensify/App/pull/11551#:~:text=aneequeahmad%20requested%20a,15%20days%20ago) that fixes the `Bug: tooltip should only appear when there is mouse/cursor attached.` All tooltips(almost all of them) were appearing. 

> Only be a small number of changed files

- 3 files were changed including `package-json` but now due to merge there are more than 100 files. 

> No conflicts with the main branch

- There were no conflicts with the main when i requested review. As you know code is pushed daily and most prolly multiple people are working on the `same file`

> All commits are signed

- All commits are signed.

> Automated tests to cover your changes

- Added TooltipTest.js file that covers changes

> Screen recordings to prove that you've manually re-tested the PR on all platforms

> The PR fixes the problem described in the issue

- Will add new screen recording for these.

**Comment by aneequeahmad** [comment]
@roryabraham Thank you for mentioning the issue this PR is facing. I totally agree with you that internal resources are wasted like this in these simple kind of git things. This is the first PR of all my career(`Startup career`) that is facing these kind of unexpected issues. I'll later explain in depth why these issues occurred from the very start of this PR. 

I would like to mention some points(also answers your above [comment](https://github.com/Expensify/App/pull/11551#:~:text=In%20order%20to%20consider%20this%20PR%20mergeable) as well) that i noticed caused the delay for merging this simple PR. Please correct me if i'm wrong. Thanks

> Only be a reasonable number of commits (somewhere between 1 and 5, probably)

- There were only 2 [commits](https://github.com/Expensify/App/pull/11551#:~:text=aneequeahmad%20requested%20a,15%20days%20ago) that fixes the `Bug: tooltip should only appear when there is mouse/cursor attached.` All tooltips(almost all of them) were appearing. 

> Only be a small number of changed files

- 3 files were changed including `package-json` but now due to merge there are more than 100 files. 

> No conflicts with the main branch

- There were no conflicts with the main when i requested review. As you know code is pushed daily and most prolly multiple people are working on the `same file`

> All commits are signed

- All commits are signed.

> Automated tests to cover your changes

- Added TooltipTest.js file that covers changes

> Screen recordings to prove that you've manually re-tested the PR on all platforms

- Have to update screenshots.

> The PR fixes the problem described in the issue

- The PR fixed the issue that was 15 days ago like i mentioned here above in commit no [be11bee](https://github.com/Expensify/App/pull/11551/commits/be11bee26bcadf11c2911bcd9e927b7296bb0fea)

**Comment by aneequeahmad** [comment]
@roryabraham Thank you for mentioning the issue this PR is facing. I totally agree with you that internal resources are wasted like this in these simple kind of git things. This is the first PR of all my career(`Startup career`) that is facing these kind of unexpected issues. I'll later explain in depth why these issues occurred from the very start of this PR. 

I would like to mention some points(also answers your above [comment](https://github.com/Expensify/App/pull/11551#:~:text=In%20order%20to%20consider%20this%20PR%20mergeable) as well) that i noticed caused the delay for merging this simple PR. Please correct me if i'm wrong. Thanks

> Only be a reasonable number of commits (somewhere between 1 and 5, probably)

- There were only 2 [commits](https://github.com/Expensify/App/pull/11551#:~:text=aneequeahmad%20requested%20a,15%20days%20ago) that fixes the `Bug: tooltip should only appear when there is mouse/cursor attached.` All tooltips(almost all of them) were appearing. 

> Only be a small number of changed files

- 3 files were changed including `package-json` but now due to merge there are more than 100 files. 

> No conflicts with the main branch

- There were no conflicts with the main when i requested review. As you know code is pushed daily and most prolly multiple people are working on the `same file`

> All commits are signed

- All commits are signed.

> Automated tests to cover your changes

- Added TooltipTest.js file that covers changes

> Screen recordings to prove that you've manually re-tested the PR on all platforms

- Have to update screenshots.

> The PR fixes the problem described in the issue

- The PR fixed the issue that was 15 days ago like i mentioned here above in commit no [be11bee](https://github.com/Expensify/App/pull/11551/commits/be11bee26bcadf11c2911bcd9e927b7296bb0fea)

**Comment by roryabraham** [comment]
Looks like we moved over [here](https://github.com/Expensify/App/pull/12003) now

**Comment by aneequeahmad** [comment]
@roryabraham yes, that's correct clean PR like the requirements that you just mentioned above. Thank you for closing this one and mentioning the other

**Pull request closed without merging**
