### PR TITLE
#2806 fix selectable timezone dropdown with thuthy disabled passed

### LINKED ISSUE #2806: Timezone - Dropdown is selectable when the "Set my time zone" bottom checkbox is checked
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
Dropdown should be disabled if the bottom checkbox is checked

## Actual Result:
Dropdown is selectable when the "Set my time zone" bottom checkbox is checked

## Action Performed:
1. Go to https://staging.expensify.cash
2. Log in with any account
3. Go to Setting - Profile
4. Scroll down to Time zone field
5. Set my time zone automatically should be selected
6. Try to chose other time zone

## Workaround:
Unknown 

## Platform:
Where is this issue occurring?

 Web ✔️ 
 iOS
 Android
 Desktop App
 Mobile Web

**Version Number:** 1.0.42-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
image

https://user-images.githubusercontent.com/44479856/117885489-e9502f80-b27b-11eb-8ebd-1405afa99e69.mp4

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/163784

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by dklymenk**
### Fixed Issues
Fixes #2806

### Tests / QA Steps

1. Go to Setting - Profile
2. Scroll down to Time zone field
3. Set my time zone automatically should be selected
4. The time zone picker should be disabled (clicking on it must not bring up any options)

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
DeepinScreenshot_select-area_20210513132039

#### Mobile Web

DeepinScreenshot_select-area_20210513132049

#### Desktop

Screen Shot 2021-05-13 at 13 25 58

#### iOS

Screen Shot 2021-05-13 at 13 25 06

#### Android

DeepinScreenshot_select-area_20210513132012

### CODE REVIEW

**Comment by dklymenk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dklymenk** [comment]
Tested on all platforms and added screenshots

**Review by marcaaron — DISMISSED** [review]
This change LGTM all yours @NikkiWines

**Review by NikkiWines — DISMISSED** [review]
Aside from the CLA issue this looks good - tested and works well

**Comment by NikkiWines** [comment]
@dklymenk looks like you have some conflcits

**Comment by dklymenk** [comment]
@NikkiWines Conflict's fixed. I think the comment style got changed in the file, so I changed mine too. No other changes.

**Review by NikkiWines — APPROVED** [review]
👍

**Pull request merged**
