### PR TITLE
Remove the reviewer checklist from the PR template

### PR DESCRIPTION
**Pull request by tgolen**
### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/239867

### Tests
None. Can only be tested once merged

### Offline tests
None - this doesn't affect the app at all

### QA Steps
1. Create a new PR for any simple file change
2. Verify that the template no longer includes the reviewer checklist in the description
3. Close out the PR

### PR Author Checklist
Checklist and screenshots do not apply since this is not a change to the app code

### CODE REVIEW

**Comment by tgolen** [comment]
@parasharrajat @MonilBhavsar you can disregard that previous ping and it's OK to merge this with the reviewer checklist failing since this doesn't touch any of the app code.

**Review by MonilBhavsar — APPROVED** [review]
Looks good, Not sure why other unrelated tests are failing. Rerunning them...

**Comment by tgolen** [comment]
I'm going to self merge this since @MonilBhavsar has approved it. The failing tests are known since having the author and reviewer checklists for this PR are not necessary.

**Comment by luacmartins** [comment]
Validated that this worked [here](https://github.com/Expensify/App/pull/13241)!

**Pull request merged**
