### PR TITLE
fix-49974-attachment-infinite-loading

### PR DESCRIPTION
**Pull request by Kalydosos**
### Fixed Issues

$ https://github.com/Expensify/App/issues/49974
PROPOSAL: https://github.com/Expensify/App/issues/49974#issuecomment-2389704800

### Tests

1. Launch the app. 
2. Open a chat
3. Paste the text Alt text
4. Send the message
5. Click on the image
6. Verify that an icon and the text "No Attachment Found" are displayed

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/5725c05c-3b5b-4ebb-ae35-424fbb3aef34
</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/7425877e-2d24-469c-8ea6-2259c3124a2a
</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/98906f54-cac9-4800-b59d-53819a1a9965
</details>

<details>
<summary>iOS: mWeb Safari</summary>

ios_mweb_safari
</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/a0138782-b3c7-419f-a0be-7c3ac01a5dfc
</details>

<details>
<summary>MacOS: Desktop</summary>

macos_desktop
</details>

### CODE REVIEW

**Comment by Kalydosos** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Kalydosos** [comment]
@dubielzyk-expensify this is the PR replacing PR https://github.com/Expensify/App/pull/50511. You can refer to this comment for more context https://github.com/Expensify/App/pull/50511#issuecomment-2461793516.

**Comment by Kalydosos** [comment]
@hoangzinh yes i did some web tests.I will do some mobile tests also but i think we can keep the same screenshots and videos as it's the same, dont you think ?

**Review by hoangzinh — APPROVED** [review]
LGTM

**Comment by dubielzyk-expensify** [comment]
This looks right to me. I'll let @dannymcclain gut check as he did the design for it. cc @shawnborton too

**Comment by shawnborton** [comment]
Yup, I dig it 👍

**Review by MariaHCD — APPROVED** [review]

**Review by dannymcclain — APPROVED** [review]
Echoing Shawn and Jon, it looks good from a design perspective.

**Comment by MariaHCD** [comment]
Looks like we have some ESLint errors:

Screenshot 2024-11-12 at 1 14 41 PM

**Comment by Kalydosos** [comment]
@hoangzinh @MariaHCD sorry my computer had some issues with its network driver since this morning



> Looks like this PR hasn't touched those files. 

yes i confirm so

Also yes, merging the lastest main will fix the issue. I will do it right away.

**Review by hoangzinh — APPROVED** [review]

**Comment by Kalydosos** [comment]
@MariaHCD @hoangzinh the failure is from a file currently present on the main branch. Our PR didnt change that file. If it's there it means they bypass that ESlint check right ? If that's the case, can we do the same ? 

Capture d’écran de 2024-11-13 08-56-12

**Review by MariaHCD — APPROVED** [review]

**Comment by MariaHCD** [comment]
Ideally, it would be good to fix it in this PR. Although I do agree, this PR hasn't really touched that file so not super sure why the ESLint error is being triggered.

In any case, we can merge this and handle the migration to useOnyx in this separate issue: https://github.com/Expensify/App/issues/52459

**Comment by MariaHCD** [comment]
The migration to useOnyx will be handled in a separate issue: https://github.com/Expensify/App/issues/52459

**Comment by Kalydosos** [comment]
@MariaHCD @hoangzinh i see the deployment on staging ios and hybrid envs have failed. Is there anything i can do to help ? I use to delete the whole node-modules folder and relauch an npm install when i encounter errors like that ie related to the application of patches, i dont know if that could help

**Pull request merged**
