### PR TITLE
[HOLD] [WIP] Remove usage of `Network.post()`

### PR DESCRIPTION
**Pull request by marcaaron**
### Details

Trying to clean up remaining usages of `Network.post()` so we can fully deprecate the old API

This is touching some interesting code called the `DeeplinkWrapper`. As far as I can tell...

1. It uses `Network.post()` directly instead of `API.makeRequestWithSideEffects()` or `API.read()`
2. It seems to exist to handle opening deep links for the desktop app (on web)
3. And if we are authenticated then it will get a short lived token for the transition to log the user into desktop
4. If it can't get a short lived token (who knows why?) it does some `setTimeout()` dance (I honestly don't really get this part)

So my questions are... 

Can we avoid this usage of `makeRequestsWithSideEffects()` somehow? 

I think if we try to use Onyx to retrieve the short lived token things would become even weirder and harder to understand...

cc @tgolen to see if he has any ideas...

### Fixed Issues (Another small step towards finishing the Network migration)

https://github.com/Expensify/Expensify/issues/208281

### Tests

- [ ] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [ ] I linked the correct issue in the `### Fixed Issues` section above
- [ ] I wrote clear testing steps that cover the changes made in this PR
    - [ ] I added steps for local testing in the `Tests` section
    - [ ] I added steps for the expected offline behavior in the `Offline steps` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I ran the tests on **all platforms** & verified they passed on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [ ] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Comment by tgolen** [comment]
Hi, thanks for tagging me. It looks like all this code was just added a week ago in https://github.com/Expensify/App/pull/16043. I'm kind of disappointed that this code got merged with all the set timeouts and `Network.post()` being used directly. It seems there was little pushback or questioning about those at all which is a bit worrisome. I think it would be worth commenting on that PR about _WHY_ those `setTimeout`s are there and there should always be very clear and explicit comments in the code to explain them.

As far as trying not to use `makeRequestsWithSideEffects()` I think it might actually look much better to have it in the session key in Onyx. The way I would envision it working is:

1. Store the short-lived auth token in `ONYXKEYS.SESSION`
2. On mount, if there is a short-lived authToken in the props, then just open the desktop route (this is the easy path and doesn't require any error handling)
3. On mount, if there is no short-lived authToken in the props, then call an action method to retrieve the token
4. The action method will call the API and store the authToken in the session object OR an error (??? not totally sure about the error case, it looks like it's possible to throw an error in web-e if there was a copilot authToken used, but that shouldn't ever be the case for this flow)
5. On component did update, check to see if the short lived auth token went from `null` to `<something>` and then open the desktop route

I have so many questions about the deep link component and I've asked them in [the recent PR](https://github.com/Expensify/App/pull/16043#pullrequestreview-1383428256).

cc @ntdiary @thesahindia @hayata-suenaga @pecanoro

**Comment by marcaaron** [comment]
Thanks @tgolen I think what I'll do is...

1. Create a new command called `BeginDeepLinkRedirect`
2. That will return a response like

```
[onyxMethod: merge, key: session, value: {shortLivedAuthTokenForDeepLink: {token?, errors?}}]
```

3. In the `index.website.js` `DeeplinkWrapper` component have something like...

```js
componentDidUpdate(prevProps) {
    const didShortLivedTokenAppear = !prevProps.session.shortLivedAuthTokenForDeepLink.token && this.props.session.shortLivedAuthTokenForDeepLink.token;
    const didShortLivedTokenErrorAppear = !prevProps.session.shortLivedAuthTokenForDeepLink.error && this.props.session.shortLivedAuthTokenForDeepLink.error;
    if (didShortLivedTokenAppear) {...}
    if (didShortLivedTokenErrorAppear) {...}
}
```
4. After we navigate we can probably remove the shortLivedAuthToken from the `session` key since I don't think it can/should be used again.

And maybe we can scrap the error handling part entirely - feels like that's handling an edge case where we somehow return an empty string for the token response - and can't really see how that would happen, but can try to do some testing.

**Comment by marcaaron** [comment]
>maybe we can scrap the error handling part entirely

Ah actually I think we can't because the request could fail for some reason other than the API throwing - in that case we want to stop trying to do the deep link redirection and just render the app as normal.

**Comment by tgolen** [comment]
Ah, love this. I came to the comments a little too late though, so you can ignore some of my comments in https://github.com/Expensify/App/pull/17452

**Comment by marcaaron** [comment]
Closing for now based on the comment [here](https://github.com/Expensify/App/issues/17987#issuecomment-1523497454).

**Pull request closed without merging**
