### PR TITLE
[WIP] Enable Fabric, Turbo Modules, and New Architecture 

### PR DESCRIPTION
**Pull request by AndrewGable**
### Details

Enable Fabric, Turbo Modules, and New Architecture and fixing many bugs found while enabling it.

### Fixed Issues
$ https://github.com/Expensify/App/issues/8503

### CODE REVIEW

**Comment by hannojg** [comment]
The flashes are gone, great! Just wondering:

- Are we fine with just completely removing `Freeze`
- Or do you want us to further investigate and fix the issue with `react-freeze` and expensify?

**Comment by roryabraham** [comment]
@marcaaron Thoughts on @hannojg's last question?

**Comment by marcaaron** [comment]
It was added to prevent an issue where the previous chat would be displayed before displaying a new chat. So if we are OK with that change or if that issue does not exist with `react-freeze` disabled then I have no issues with removing it.

**Comment by marcaaron** [comment]
Not sure if react-freeze was really the best solution to the issue. It's just one I stumbled on. So, if we want to investigate that separately or other alternatives I am 👍

**Comment by AndrewGable** [comment]
One thing I've noticed in addition, it seems like the bold font is broken

`main`|`andrew-fabric`
-------|---------------
Screenshot 2022-10-28 at 12 16 35 PM | Screenshot 2022-10-28 at 11 50 13 AM

**Comment by marcaaron** [comment]
The rendering of a new-ish chat with Welcome message looks a little jumpy. Caught this series of frames:



Also if a chat has not yet been loaded then the content loader also flashes like so

https://user-images.githubusercontent.com/32969087/198706405-6fc74d9a-86e2-4ec2-b6ca-749ecf4c368d.mp4

But looks less bad on a second visit.

Some things that are weird (but not sure if introduced by the current changes):

1. The compose input is hidden when a report first opens.
2. The welcome message flashes on a new-ish chat
3. The content loader flash when we have not yet loaded a chat from the server

**Comment by marcaaron** [comment]
@AndrewGable testing on `main` with `react-freeze` disabled and confirmed that these rendering issues are new to this PR. However, I do see that the previous chat displays before the next loads (in this PR it happens so fast that we barely see it but you can look at the [first frame of the image in this comment](https://github.com/Expensify/App/pull/12167#issuecomment-1295323653) to see that it happens).

Here's an example of my tests on `main`:

https://user-images.githubusercontent.com/32969087/198714950-23404887-7e6c-4102-8109-9abc8a616c07.mp4

**Comment by marcaaron** [comment]
Not too sure but seems like the slow rendering of the compose input is dependent on other activity e.g. if we disable the `SidebarLinks` (expensive to re-render) while the drawer is open you will see the composer input does not hang as bad.
 
**With sidebar links re-rendering**

https://user-images.githubusercontent.com/32969087/198723267-bbac0641-7823-49cd-b792-e63ab81b7ca5.mp4

**With sidebar links disabled**

https://user-images.githubusercontent.com/32969087/198723340-1cb43420-62e2-4b85-b3df-1d4e93d2bffe.mp4

Now the fun part... why does it happen? 😄 Is it something about the fabric architecture? Sorry I am a n00b at understanding how it all works. It kind of looks like things are "hanging" the same amount of time (check my previous comment's video), but some things are revealed in a staggered fashion (whereas before stuff would just hang until the entire view is ready to display).

Looks like there are still some just general improvements to avoiding re-renders of the `SidebarLinks`, `LHNOptionsList`, etc. Gonna look into them as a tangent to this update and maybe it will help resolve things 🤷‍♂️

**Comment by hannojg** [comment]
I think a lot of it could be related to the concurrent rendering mode. I would suggest that we disable that mode first, and then take the time to enable it and properly update all the expensify code to work well with it?

**Comment by hannojg** [comment]
Okay, I just checked it and turned off concurrent mode for testing. Unfortunately, the named issues didn't dissolve magically 😄 

I think it will take more time/effort to enable fabric, by going through the app, identifying all issues and then providing fixes for them.
We can work on those for sure, just wondering whether its something you want us to spend time on (we'd love to get fabric working for Expensify ofc) 😊 ?

**Comment by roryabraham** [comment]
Going to close this in favor of https://github.com/Expensify/App/pull/13767

**Pull request closed without merging**
