### PR TITLE
Return a promise

### PR DESCRIPTION
**Pull request by deetergp**
This PR returns the expected promise for `reopenIssueWithComment` as well as improves some variable names in `checkDeployBlockers`.

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
Let's try this again!

**Comment by botify** [comment]
@roryabraham looks like this was merged without passing tests. Please add a note explaining why this was done or remove the `Emergency` label if this is not an emergency.

**Comment by roryabraham** [comment]
Merging to fix production deploys

**Comment by roryabraham** [comment]
It worked! 
image

Next, we need to test the various scenarios that can happen...

**Pull request merged**
