### PR TITLE
Exclude concierge from iou

### LINKED ISSUE #2698: [IOU] Users are able to send payment requests and split bills with Concierge
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Platform - version:**  

All platforms - v1.0.37-0

**How to enable the `Request Money` or `Spilt Bills` flow**
As the feature is currently behind a beta, you must perform the following change to reproduce the issue. Either navigate to Permissions.js,[ comment out this line ](https://github.com/Expensify/Expensify.cash/blob/e28b50e139c492442ea984c3d48e23be744ceb4e/src/libs/Permissions.js#L31)and return true -- or apply this [diff.txt](https://github.com/Expensify/Expensify/files/6427621/diff.txt) with ` git apply path/to/diff.txt`

**Action Performed (reproducible steps):**
0. Read the above section to ensure that the beta feature is available to you
1. Click the `+` icon on global create and select `Request Money` or `Spilt Bills`
2. Enter an amount and click `Next`
3. Search for concierge@expensify.com
4. Observe that Concierge is listed as a participant and available to send a payment request to
5. Now navigate to the Concierge DM and click the `+` icon within the DM
6. Observe that `Request Money` is an available option in the CreateMenu along with `Add Attachment`

**Expected Result:**
1. Concierge should not be an available participant to select on the IOUParticipants page via the `Request Money` or `Split Bills` flows.
2. `Request Money` should not be an available option in the CreateMenu when launched from within the Concierge DM

**Actual Result:**
1. Users can select Concierge as a participant 
2. Users can launch the `Request Money` flow from within the Concierge DM

**Notes/Photos/Videos:** 

image
image

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/162867
**Upwork Job URL:** https://www.upwork.com/jobs/~010daa7b8e343f79e4

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by tugbadogan**
@trjExpensify 

### Details
Exclude Concierge from IOU participant selection and remove IOU menu items from chat with Concierge.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify.cash/issues/2698

### Tests
Tested manually and made sure that users cannot initiate IOU request with Concierge.

### QA Steps
```
- Open 1:1 and group chat with Concierge
- Press `+` icon next to chat composer
- Observe that there is no `Request Money` or `Split Bill` option on menu
```

```
- Open 1:1 and group chat without Concierge
- Press `+` icon next to chat composer
- Observe that there is a `Request Money` or `Split Bill` option on menu
```

```
- Press big green `+` icon on the sidebar
- Select `Request Money` or `Split Bill`
- Enter a random amount and press `Next`
- Search Concierge
- Observe that Concierge doesn't appear among results
```

### Tested On

- [X] Web
- [X] Mobile Web
- [X] Desktop
- [X] iOS
- [X] Android

#### Desktop
Screenshot 2021-05-07 at 17 13 19 | Screenshot 2021-05-07 at 17 13 50
Screenshot 2021-05-07 at 17 14 23 | Screenshot 2021-05-07 at 17 14 59
Screenshot 2021-05-07 at 17 15 43 | Screenshot 2021-05-07 at 17 16 20

### CODE REVIEW

**Review by Luke9389 — CHANGES_REQUESTED** [review]
Hi @tugbadogan. Would you mind also adding this functionality to the unit [tests for getNewGroupOptions](https://github.com/Expensify/Expensify.cash/blob/7423dc02b7a5d4554e6f6536cf637afb700ce077/tests/unit/OptionsListUtilsTest.js#L175)? Otherwise lookin' great 👍

**Comment by tugbadogan** [comment]
> Hi @tugbadogan. Would you mind also adding this functionality to the unit [tests for getNewGroupOptions](https://github.com/Expensify/Expensify.cash/blob/7423dc02b7a5d4554e6f6536cf637afb700ce077/tests/unit/OptionsListUtilsTest.js#L175)? Otherwise lookin' great 👍

Hi, I added unit tests for `getNewChatOptions()` and `getNewGroupOptions()` 👍

**Review by Luke9389 — COMMENTED** [review]
Ok! This is lookin' great! 
Thanks for adding in these tests @tugbadogan. 

Just a couple of questions, and a few NABs (**N**ot **a** **B**locker).
Comment back on whether you want to address the review comments, excluding default values is not something that I'd require (since they make the code a tad more informative). Still though, I wouldn't fault you if you were to take them out. 

I do however need an answer on whether we default excludeConcierge to `true`. I see that you're using some syntactic sugar when you pass it to `getNewGroupOptions` and I just want to be sure I'm reading that right. 

Thanks!

**Comment by tugbadogan** [comment]
Thanks for the quick review @Luke9389 , I've addressed the comments and updated the PR

**Comment by tugbadogan** [comment]
> Obligatory question after review rounds: you've tested this on all 5 platforms?
> I see screenshots for Desktop but not for the others.

Yes, I tested this on all platforms. I didn't put screenshots for other platforms since there's no UI element or platform specific change here.

**Review by cead22 — APPROVED** [review]

**Review by Luke9389 — APPROVED** [review]

**Comment by Jag96** [comment]
It looks like this PR caused a regression here: https://github.com/Expensify/Expensify.cash/issues/2809

Reverting this PR in https://github.com/Expensify/Expensify.cash/pull/2834 to unblock the deploy, and reopening the associated issue

**Pull request merged**
