### PR TITLE
[E.cash - Group Chats] Added a plus sign to group avatars

### PR DESCRIPTION
**Pull request by Luke9389**
### Details
<Explanation of the change or anything fishy that is going on>

Just a simple fix to put a plus sign on the group avatar number to make it more clear what the total number of people is.

### Fixed Issues
<Please replace GH_LINK with the link to the GitHub issue this Pull Request is fixing>
Fixes https://github.com/Expensify/Expensify/issues/152360

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

Screen Shot 2021-01-26 at 3 26 43 PM

#### Mobile Web

Screen Shot 2021-01-27 at 1 46 39 PM

#### Desktop

Screen Shot 2021-01-27 at 1 49 27 PM

#### iOS

Screen Shot 2021-01-27 at 3 27 54 PM

#### Android

Screen Shot 2021-01-27 at 3 30 22 PM

### CODE REVIEW

**Comment by Luke9389** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Luke9389** [comment]
@Expensify/design One thing about this change is that it's now inconsistent with the login page image...  
Screen Shot 2021-01-27 at 2 15 14 PM

**Comment by shawnborton** [comment]
Hey Luke - was this discussed anywhere, perhaps in #expensify-cash? The current design made it through the design doc process, so any changes we would want to make to this should have at least some kind of small Problem/Solution statement proposed for discussion in #expensify-cash.

**Comment by shawnborton** [comment]
Ah, looks like there was a comment buried in a thread somewhere. I still think it's a good idea to surface this into the main room for some visibility.

**Comment by Luke9389** [comment]
Yea, that's a great point @shawnborton. I'll go ahead and spin up a lil Problem/Solution statement for this. In the event that folks are in agreement that we should move forward, I'll take this PR off HOLD 👍

**Comment by shawnborton** [comment]
Could we see this with the “+X” slightly pulled to the left? This way the
number feels a little more optically center-aligned.

I think you could do this by either adding negative margin to the left, or
padding to the right. Maybe try a couple options and we can see what feels
good?

**Comment by Luke9389** [comment]
@shawnborton I have yet to play with centering this number, but considering that we've reached a consensus on the `#expensify-cash` channel, I think we probably should change the image I linked to above after all. Should I open a design ticket for that? If so I'm happy to do it. There may be other static images related to this that need a change as well.

**Comment by shawnborton** [comment]
I don't mind either way - we could easily provide those assets for you in this PR if you'd like (I think it's just a matter of replacing two images), or you can spin up something separate.

**Comment by shawnborton** [comment]
Hey @Luke9389 - here are updated images you can use. Should be able to just simply overwrite the existing image files: [HomeScreenshots.zip](https://github.com/Expensify/Expensify.cash/files/5902955/HomeScreenshots.zip)

**Comment by Luke9389** [comment]
Ok cool! Thx @shawnborton!

**Comment by Luke9389** [comment]
@shawnborton Here's a side by side comparison of scooting the text over. The `0px` one is included for reference. I know the difference is pretty slight 😄, but lemme know what you think. 

| 0px | 1px | 2px | 3px |
|:--:|:--:|:--:|:--:|
| Screen Shot 2021-02-09 at 1 22 04 PM  | Screen Shot 2021-02-09 at 1 24 29 PM  | Screen Shot 2021-02-09 at 1 21 46 PM  | Screen Shot 2021-02-09 at 1 24 47 PM  |



_... I think my vote is for 2px._

**Comment by shawnborton** [comment]
Sweet, thanks for the comparisons - this is great! I think my vote is for 3px, this is what I was playing around with in Figma and I quite liked it:

image

**Comment by Luke9389** [comment]
Yea, now that you mention it, looking at the small versions, I think 3px is good too 👍

**Comment by Luke9389** [comment]
Updated!

**Comment by shawnborton** [comment]
Hey @Luke9389 - I just pulled this and tested and it appears to be broken:
image


It looks like that's because the whole thing just has `margin: -3px`

I think a better approach would be to wrap the the inner `+X` in a div, and give that div some `paddingRight: 3px`

The result would be this:
image

**Comment by Luke9389** [comment]
Oh my bad @shawnborton. Got my git-wires crossed. I think we can forego using another wrapper and instead just use `marginLeft` rather than `margin`.

**Review by thienlnam — COMMENTED** [review]
I'm seeing two images removed and no new ones added in the PR, is this intended?  Also I think we're okay but is `avatarInnerText` used anywhere else?

**Comment by thienlnam** [comment]
Actually, scratch that comment about the images being removed - I got confused by the red in the files changed but it just seems to be that the files are smaller in size

**Review by shawnborton — APPROVED** [review]

**Comment by Luke9389** [comment]
bumping @shawnborton and @thienlnam on merging this thang

**Pull request merged**
