### PR TITLE
Ignore unselectable text from selection

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

On the web, there is some text that is not selectable but we can still copy it when using copy shortcut CTRL+C.

### Fixed Issues

$ https://github.com/Expensify/App/issues/26694
PROPOSAL: https://github.com/Expensify/App/issues/26694#issuecomment-1706847020

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

**Web**
NOTE: if you encounter a case where the pasted text contains some random style text, it's a known issue that won't be fixed based on this [comment](https://github.com/Expensify/App/issues/24399#issuecomment-1703367417)
Emoji reaction:
1. Send any message to a chat
2. Add an emoji reaction to the message
3. Triple click the message to select it
4. Press CTRL+C and paste it to composer or any text editor
5. Verify the pasted text does not contain any emoji

Menu item:
1. Open Settings > Profile > Timezone
2. Turn on the automatic timezone
3. Select the Timezone title text and drag it to the bottom of the timezone name
4. Press CTRL+C and paste it to composer or any text editor
5. Verify the pasted text does not contain the timezone name

Multiple Avatars 1:
1. Open workspace invite page
2. Select more than 8 users to invite and press Next
3. Drag a text selection from the header to the bottom of +N text of the avatar overlay
4. Press CTRL+C and paste it to composer or any text editor
5. Verify the pasted text does not contain the +N text

Multiple Avatars 2:
1. Create a new group chat with >= 3 members and open it
2. Drag a text selection from the first user name on the chat header to the left of +N text of the avatar
3. Press CTRL+C and paste it to composer or any text editor
4. Verify the pasted text does not contain the +N text

Calendar:
1. Open Settings > Profile > Personal Details > Date of birth
2. Drag a text selection from "Date of birth" title to the bottom of the Save button text
3. Press CTRL+C and paste it to composer or any text editor
4. Verify the pasted text does not contain any text from the calendar and the Save button

Edited message:
1. Send any message to a chat
2. Edit the message
3. Select the message along with the (edited) text
4. Press CTRL+C and paste it to composer or any text editor
5. Verify the pasted message does not contain any space

Reply:
1. Send any message to a chat
2. Add a new reply to the message you sent
3. Drag a text selection from the message to the bottom of "N Reply" text
4. Press CTRL+C and paste it to composer or any text editor
5. Verify the pasted text does not contain "N Reply" text and its timestamp

List item 1:
1. Open Settings > Profile > Personal Details > Pronouns
2. Search for any pronouns
3. Drag a text selection from the Pronouns title to the pronouns list
4. Press CTRL+C and paste it to composer or any text editor
5. Verify the pasted text does not contain the pronouns list

List item 2:
1. Open workspace members page
2. Drag a text selection from Members title to the members list
3. Press CTRL+C and paste it to composer or any text editor
4. Verify the pasted text does not contain the members list and the Select all text

New message:
1. Open any chat with a few messages
2. Mark the last message as unread
3. Scroll up to show the "New message" floating view
4. Drag a text selection from the user name on the header to the end of "New message" text
5. Press CTRL+C and paste it to composer or any text editor
6. Verify the pasted text does not contain "New message"

Text input prefix
1. Press FAB and choose New room
2. Drag a text selection from the new room title to the bottom of the "#" prefix text
3. Press CTRL+C and paste it to composer or any text editor
4. Verify the pasted text does not contain the prefix ("#") text

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Emoji reaction

https://github.com/Expensify/App/assets/50919443/f55ef0c4-b927-477b-a728-3fdcf6dd5d82

List 1 (RadioListItem)

https://github.com/Expensify/App/assets/50919443/797df038-7c98-4df9-97a5-d86e2c114a23

List 2 (BaseSelectionList + UserListItem)

https://github.com/Expensify/App/assets/50919443/834f0c94-18d8-4873-be6d-f80122c033c4

MenuItem (timezone)

https://github.com/Expensify/App/assets/50919443/3064a10d-a314-4321-afe5-5daf3e0ecc9d

MultipleAvatars

https://github.com/Expensify/App/assets/50919443/af0e0911-a807-4827-9899-b9cff9d5919d

https://github.com/Expensify/App/assets/50919443/c00b158b-93c9-497d-83db-57747532e4bd

CalendarPicker + Button

https://github.com/Expensify/App/assets/50919443/69e0776a-4f05-407a-a4f7-2b5bc13cad08

Edited text

https://github.com/Expensify/App/assets/50919443/9ceafecd-4a0a-4130-9979-5b1f8137b0f5

Thread reply

https://github.com/Expensify/App/assets/50919443/d3e05a9c-c3cd-42b5-aea0-35a57baf8f38

Floating New message

https://github.com/Expensify/App/assets/50919443/9957f175-2b01-4edd-8a6b-28b8ed2b7e12

Prefix

https://github.com/Expensify/App/assets/50919443/8b9bc397-b5cd-479b-9aa3-c833187559bc

</details>

<details>
<summary>Mobile Web - Chrome</summary>

</details>

<details>
<summary>Mobile Web - Safari</summary>

</details>

<details>
<summary>Desktop</summary>

</details>

<details>
<summary>iOS</summary>

</details>

<details>
<summary>Android</summary>

</details>

### CODE REVIEW

**Review by 0xmiroslav — COMMENTED** [review]
Seems like you put dataSet code on all views where `selectable={false}` is passed.
Can we put in base component - Text, BaseGenericPressable so if `selectable={false}` is passed, add `dataSet` prop manually?

**Review by 0xmiroslav — APPROVED** [review]
LGTM!

**Review by Li357 — APPROVED** [review]
Looks good, thanks for the thorough testing here!

**Comment by getusha** [comment]
>@0xmiroslav that's actually a nice idea, but I see that [react-native-web 0.19](https://github.com/necolas/react-native-web/releases) deprecated selectable props and we are in the process of https://github.com/Expensify/App/pull/24482. I'm afraid that if we apply the dataSet in the Text/BaseGenericPressable and set the value based on selectable, it will be removed along with selectable (or may not be removed at all which makes the value always false, or undefined).


Thank you for taking this into consideration @bernhardoj @0xmiroslav

**Pull request merged**
