### PR TITLE
Handle VBA errors with red field outlines

### PR DESCRIPTION
**Pull request by jasperhuangg**
### Details
This PR adds red borders for any validation errors stemming from text inputs in the VBA flow.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/171620

### Tests/QA
1. Navigate to `<baseURL>/bank-account/company`.
2. Input invalid data for the following fields and try to submit the form. Verify that red outlines AND growl messages occur.
    - Empty password
    - Invalid address street
    - Invalid address zip code
    - Invalid website URL
    - Invalid company tax ID
    - Invalid industry code
    - Invalid incorporation date
3. Navigate to `<baseURL>/bank-account/requestor`.
4. Input invalid data for any of the fields and try to submit the form. Verify that red outlines AND growl messages occur.
    - Empty date of birth
    - Invalid address street
    - Invalid address zip code
    - Invalid last 4 digits of SSN

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screen Shot 2021-08-09 at 7 23 23 AM

#### Mobile Web
Screen Shot 2021-08-09 at 7 23 40 AM

#### Desktop
Screen Shot 2021-08-09 at 7 56 10 AM

#### iOS
Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-08-09 at 07 42 55

#### Android
Screenshot_1628531581

### CODE REVIEW

**Comment by Gonals** [comment]
Grabbing the review since I have some bandwidth [and was asked to!](https://expensify.slack.com/archives/C020EPP9B9A/p1628580779491500)

**Comment by Gonals** [comment]
Tests well, but shouldn't we change the `Incorporation Date` field to be a date input? 
Similarly, we could also enforce the format on the phone number (where I can write letters), tax ID number, zip code, and so on. Is that planned down the line? It doesn't look very professional like this

**Review by Gonals — COMMENTED** [review]
Tests well. Just one comment (and there are conflicts)

**Comment by kevinksullivan** [comment]
@Gonals I totally agree we can clean up fields for polish, but we can get a follow up issue for that.

**Comment by joelbettner** [comment]
@jasperhuangg looks good, but conflicts.

**Comment by TomatoToaster** [comment]
I'll help out with the conflicts here so ya'll can re-review.

**Comment by TomatoToaster** [comment]
Jasper is OOO, but I resolved the merge conflicts for him. Ready for a re-review @Gonals @joelbettner

**Review by joelbettner — APPROVED** [review]

**Comment by joelbettner** [comment]
@Gonals all yours.

**Review by Gonals — APPROVED** [review]
LGTM!

**Comment by jasperhuangg** [comment]
@Gonals @joelbettner Thanks so much for taking charge and resolving the merge conflicts :)

**Comment by isagoico** [comment]
Unable to check the Requestor page because of this issue https://github.com/Expensify/App/pull/4431

**Comment by isagoico** [comment]
This other issue is failing https://github.com/Expensify/App/issues/4730

**Comment by isagoico** [comment]
Retest for this was a pass! 
image

**Pull request merged**
