### PR TITLE
Add more logs to try to resolve "cb() not called" error

### PR DESCRIPTION
**Pull request by AndrewGable**
Please review @Jag96 

### Details
1. Updated to use correct node on iOS (Node 14.x)
2. Turned on "silly" debug mode, which logs the entire kitchen sink to hopefully spot the cause of the "cb error"

### Fixed Issues
Related https://github.com/Expensify/Expensify/issues/152345

### Tests
1. Run `npm install`
2. Verify it installs correctly 👍 

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by AndrewGable** [comment]
Looks like some tests are failing, I will take a look at them soon 🕵️

**Comment by AndrewGable** [comment]
Ok so I reverted all the package-lock changes because I don't think it's necessary and it ended up updating a bunch of libraries that I don't know if we need to update. This is now just adding a bunch of logs to hopefully help us track this down.

**Review by Jag96 — APPROVED** [review]
LGTM

**Pull request merged**
