### PR TITLE
Wrap the merchant text in the transaction field view

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

Currently, we only show merchant as single line in the transaction field view which will be truncated if it's very long. This PR makes it multiline.

### Fixed Issues

$ https://github.com/Expensify/App/issues/41925
PROPOSAL: https://github.com/Expensify/App/issues/41925#issuecomment-2102947901

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps
### QA Steps

1. Submit a new expense with a very long merchant
2. Open the transaction thread of the expense
3. Verify the merchant is shown as multiline instead of truncated
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Screenshot 2024-05-14 at 15 08 19

</details>

<details>
<summary>iOS: Native</summary>

Screenshot 2024-05-14 at 15 07 56

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Screenshot 2024-05-14 at 15 08 47

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Screenshot 2024-05-14 at 15 04 48

</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2024-05-14 at 15 05 19

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
The app keeps not responding when I open the transaction thread on Android, so I can't screenshot it.

**Comment by dannymcclain** [comment]
@Ollyws great catch. I think since we display the description as multi-line on the confirmation screen, it makes sense to do that with the merchant as well. I don't see why one would be treated differently than the other.

CleanShot 2024-05-15 at 08 31 23@2x

**Comment by bernhardoj** [comment]
That makes sense but I would like to confirm 1 thing. I see that we actually set the description max line to 2 on the confirmation page.
https://github.com/Expensify/App/blob/1ee5d03fc9c7530b2e1729a1a6feb8172115d1cf/src/components/MoneyRequestConfirmationList.tsx#L874

But because we render the description as HTML (markdown), the component doesn't support the max line.

Do we want to apply the max line to 2 for merchants? Or don't limit the max line?

**Comment by shawnborton** [comment]
Yeah, I kind of think the intention behind Merchant is for it to be one-line and typically as few words as possible. Is that what you think too @trjExpensify? 

So I think I'm okay with this inconsistency, just in the sense that I think these are slightly different things.

**Comment by trjExpensify** [comment]
>Yeah, I kind of think the intention behind Merchant is for it to be one-line and typically as few words as possible. Is that what you think too @trjExpensify?

Yep, agreed. A description is more of a free form field to expand on the purpose, whereas a merchant is a one-liner and typically a couple of words.

**Comment by dannymcclain** [comment]
@shawnborton @trjExpensify that makes sense to me, but this issue is specifically about making it multi-line-able. So if it shows up as two lines on the expense and the preview, should it still only show up as one line on the confirmation screen?

Or do you all think that it should _never_ be multiline? (Maybe check out https://github.com/Expensify/App/issues/41925 for more details about why there's interest in making it multiline)

**Comment by shawnborton** [comment]
Ah, I see now. Yeah, I think it's cool if we make the confirmation screen match the preview card, so we should allow two lines worth of text to display before truncating. Does that sound more in line with what you are thinking?

**Comment by dannymcclain** [comment]
>Ah, I see now. Yeah, I think it's cool if we make the confirmation screen match the preview card, so we should allow two lines worth of text to display before truncating. Does that sound more in line with what you are thinking?

Yeah that's what I was thinking!

**Comment by dubielzyk-expensify** [comment]
Ahh, I see. I'm okay with that. I was initially thinking that we should just have 1 line for merchant and 1 line for description regardless of how long it is, but I'm okay with what you're suggesting

**Comment by bernhardoj** [comment]
So, if I understand correctly, the agreement is to limit the merchant to be 2 lines on both the preview card and confirmation screen?

Or no limit for the preview card but limit for the confirmation screen to 2 lines?

**Comment by shawnborton** [comment]
> So, if I understand correctly, the agreement is to limit the merchant to be 2 lines on both the preview card and confirmation screen?

I think it's this, and I think we already have a 2 line max on the preview card? Or maybe we don't?

**Comment by dannymcclain** [comment]
>I think it's this, and I think we already have a 2 line max on the preview card? Or maybe we don't?

Yeah I'm pretty sure we already have that 2 line max on the preview card—and that's what we want.

>So, if I understand correctly, the agreement is to limit the merchant to be 2 lines on both the preview card and confirmation screen?

Yes. Two lines max on the confirmation screen & preview. (This is what description _should_ be doing anyways, but since we render as markdown/html, it doesn't obey the rules. But we don't need to dwell on that here.)

**Comment by bernhardoj** [comment]
Sorry, it's not the preview card. What I mean is this one (idk what it is called, it's in the transaction thread)

image

>  I think we already have a 2 line max on the preview card? Or maybe we don't?

We are currently not limiting it by lines but by characters.
https://github.com/Expensify/App/blob/a03fecc80e5326a24644254f682441aa50585347/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L83-L84
https://github.com/Expensify/App/blob/a03fecc80e5326a24644254f682441aa50585347/src/CONST.ts#L171-L172

**Comment by dannymcclain** [comment]
>Sorry, it's not the preview card. What I mean is this one (idk what it is called, it's in the transaction thread)

Ah gotcha. For the transaction thread, I don't know that we need to truncate at all. It looks like description has a max-character limit of 500 characters, and we don't truncate at all in the transaction thread. I don't see any problem with following that same pattern for merchant. Anyone else?

CleanShot 2024-05-16 at 09 01 53@2x

>>I think we already have a 2 line max on the preview card? Or maybe we don't?
>
>We are currently not limiting it by lines but by characters.

That works too—let's just do it the same way for both.

**Comment by dannymcclain** [comment]
>So, I vote for:
>preview card and confirmation screen: limit 2 lines
>transaction thread: no limit

I'm with you on this. I think we've run into problems in the past trying to truncate the preview with lines vs. characters, which is why it's truncated with characters. You're welcome to investigate, but my gut says it would be best to leave that alone.

>Also for description, it's possible to have many lines like below

This is insane 😂 I had no idea you could do this. Coming from [this issue](https://github.com/Expensify/App/issues/41587#issuecomment-2107397468), it seems like we'll likely be converting all those line breaks to spaces, and then truncating normally after that. So we might not need to worry about that situation here.

**Comment by bernhardoj** [comment]
Ok, I have updated the merchant max line in confirmation screen to 2.
image

For the preview card, we are limiting it by character in https://github.com/Expensify/App/pull/42243

**Review by dannymcclain — APPROVED** [review]
From a design perspective, I think this is looking good. Definitely still get a solid technical review.

**Review by Ollyws — APPROVED** [review]
LGTM.

**Review by srikarparsi — APPROVED** [review]
lgtm as well

**Pull request merged**
