### PR TITLE
Fix attachment uploads by moving stringify call

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
We added the logic to auto stringify object params but `_.isObject()` returns `true` when we have a `Blob` (`File` is a subclass)
 
### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/156388

### Tests
1. Upload an attachment and verify it works.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

### CODE REVIEW

**Comment by marcaaron** [comment]
Testing iOS and Android now. Not 100% sure if they are sending a `File`

**Comment by NikkiWines** [comment]
Testing on Android and getting the following: 
```
Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'sequenceNumber' of undefined
TypeError: Cannot read property 'sequenceNumber' of undefined
    at updateReportWithNewAction (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:160910:44)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:161218:39)
    at tryCallOne (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:26995:16)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27096:27)
    at apply (native)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30647:26)
    at _callTimer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30535:17)
    at _callImmediatesPass (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30574:17)
    at callImmediates (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:30791:33)
    at __callImmediates (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2740:35)
    at anonymous (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2526:34)
    at __guard (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2723:15)
    at flushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2525:21)
    at invokeCallbackAndReturnFlushedQueue (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:2518:33)
```

**Comment by marcaaron** [comment]
Ok just reverted this back to more or less what you had originally. I don't have a good solution for determining whether a given object parameter should be stringified or not right now.

**Comment by NikkiWines** [comment]
Confirmed attachments work on android with the new logic

**Review by NikkiWines — APPROVED** [review]
Tested and works well

**Pull request merged**
