### PR TITLE
fix: icon not set when adding bookmark to iOS home screen

### PR DESCRIPTION
**Pull request by eh2077**
### Fixed Issues

$ https://github.com/Expensify/App/issues/21064
PROPOSAL: https://github.com/Expensify/App/issues/21064#issuecomment-1597561421

### Tests
1. Navigate to https://new.expensify.com/ in iOS Safari 
2. Tap on share icon from toolbar
3. Select Add to Home Screen option
4. Tap Add on the following screen
5. Verify Expensify icon that gets added to Home Screen
6. Click the icon bookmark just added from Home Screen
7. Verify that it open https://new.expensify.com/ in iOS Safari
8. Repeat 1-7 on Android Chrome.

- [x] Verify that no errors appear in the JS console

### QA Steps
Same as test

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

N/A

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/117511920/cff9f286-4206-4c15-921f-e6374ac6a974

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/117511920/36a587ff-4374-471e-9b95-b6267fd1a572

</details>

<details>
<summary>Desktop</summary>

N/A

</details>

<details>
<summary>iOS</summary>

N/A

</details>

<details>
<summary>Android</summary>

N/A

</details>

### CODE REVIEW

**Review by shawnborton — APPROVED** [review]

**Comment by mollfpr** [comment]
@eh2077 The icon for mWeb/Chrome added to the home screen is square instead of rounded.

Screenshot 2023-06-30 at 09 47 21


[untitled.webm](https://github.com/Expensify/App/assets/25520267/d32596b0-8a03-4921-ad7e-f2e1ba0dacb6)

**Comment by eh2077** [comment]
@mollfpr Thanks for checking it on mobile Chrome. But I can't reproduce it on mobile Chrome, see below video 

https://github.com/Expensify/App/assets/117511920/13d3f354-5997-45fe-99c0-6bf8f7be5f57

From my emulator, the preview icon is round, see below screenshots
| Dev | Staging |
| ------------- | ------------- |
|   | |

Did you use the icon provided [here](https://github.com/Expensify/App/issues/21064#issuecomment-1611377241) and rebuild(Cmd + c to exit the process and run `npm run web` again) the project?

**Comment by mollfpr** [comment]
https://github.com/Expensify/App/assets/25520267/bb0d7ed7-0b1e-4c4a-93c5-0919a3279552

Here's what I commented on the `apple-touch-icon` link, and it works. I also check on the real device have the same behavior.

**Comment by eh2077** [comment]
That's so strange. I still can't reproduce it. 

Below is my emulator setting 
image

Do you test on the same branch of this PR? Or can you share the branch you're testing?

Let me setup another emulator using Pixel 5 and API 33 and try to reproduce it.

**Comment by mollfpr** [comment]
I'm checkout to this PR with GH CLI.

**Comment by eh2077** [comment]
Still can't reproduce it on emulator of Pixel 5 API 33

**Comment by mollfpr** [comment]
@marcochavezf Could you help us here to check whether the icon on adding the page to the home screen is displayed correctly like on the staging? Thanks!

**Comment by eh2077** [comment]
@mollfpr Would you mind testing with following changes on your env? 
image
```html
<link rel="icon" id="favicon" sizes="any" href="/favicon.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
```
I still can’t reproduce it but I guess it's related to the legacy usage of `rel="shortcut icon"`.

It looks like `rel="shortcut icon"` is not recommended for modern browsers and it's recommended to use `rel="icon"`, see [rel="shortcut icon" considered harmful](https://mathiasbynens.be/notes/rel-shortcut-icon) and [How to Favicon in 2023: Six files that fit most needs](https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs) FYI.

**Comment by mollfpr** [comment]
https://github.com/Expensify/App/assets/25520267/50288d6f-11ba-459e-a6ff-4f69366ebdd8

@eh2077 It's still reproducing even after I clean up the project.

**Comment by eh2077** [comment]
@mollfpr Could you update your Chrome and test with property `sizes="any"` added again? I had experienced other weird issues on outdated Chrome before. ChatGPT tells me that Chrome possibly reads icon from meta tag `<link rel="apple-touch-icon">` if it can't find the proper icon 🤔 but I think, in this case, the Chrome should be able to find the right icon?

**Comment by eh2077** [comment]
Friendly bump @mollfpr on https://github.com/Expensify/App/pull/21856#issuecomment-1617228769

**Comment by mollfpr** [comment]
Sorry for the delay! It's still resulting in the same.

> ChatGPT tells me that Chrome possibly reads icon from meta tag <link rel="apple-touch-icon"> if it can't find the proper icon

Is there any information on what the proper icon is?

Although, the result in my phone is not too noticeable, and the icon on my home screen is not round like in the simulator.

https://github.com/Expensify/App/assets/25520267/e0e09e18-e35c-4a8d-b353-70c1b7126470

@shawnborton Could you help confirm if the icon in the above video for Android is okay? Where is previously the icon that shows in Android was the favicon.

**Review by mollfpr — APPROVED** [review]
Thanks for confirming it @shawnborton ❤️

@eh2077 Let's add test for mWeb/chrome too in the test case.

**Comment by eh2077** [comment]
> @eh2077 Let's add test for mWeb/chrome too in the test case.

Added!

**Comment by eh2077** [comment]
Friendly @marcochavezf

**Review by marcochavezf — APPROVED** [review]
Thanks guys, love the "Look Gorilla To Me" 😆

**Pull request merged**
