### PR TITLE
fixed scrolling issue

### LINKED ISSUE #3768: mweb - Tapping green fab does not open the menu docking to the bottom
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open e.cash in mWeb
2. Click + button
## Expected Result:
when I tap the + fab button context menu should popup docking to the bottom

## Actual Result:
Page is greyed out and context menu does not open.

## Workaround:
Unknown

## Platform:
Where is this issue occurring?

 Web
 iOS 
 Android
 Desktop App
 Mobile Web ✔️

**Version Number:** 1.0.74-0 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:**  Issue occurs in android chrome browser SG 10 / chrome and Samsung Galaxy A50 / chrome
**Expensify/Expensify Issue URL:**

https://user-images.githubusercontent.com/43996225/123495763-fee2a400-d5f2-11eb-91d6-17487b7c570f.mp4

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### LINKED ISSUE #3781: LHN can be scrolled horizontally while closed.
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
LHN can be scroll horizontally and a scrollbar is present only when no chat is active.

## Action Performed:
1. Open E.cash Mobile web.
2. Open any chat.
3. Close the chat, go back to the home page or LHN.
4. Try to scroll the page horizontally.

## Expected Result:
Describe what you think should've happened
No scrollbar should be present and We should not be able to scroll the page and see the inactive chat page.

## Actual Result:
 Users can scroll the page and see the inactive chat in the background which is non-interactable.

## Workaround:
 Just a UI glitch.

## Platform:
Where is this issue occurring?

 Web
 iOS
 Android
 Desktop App
 Mobile Web :heavy_check_mark: 

**Version Number:** Latest
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/24370807/123708583-4e420200-d889-11eb-9225-61ddd6379bc3.mp4

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ Fixes #3768
Fixes #3781

### Tests | QA Steps

Fab button issue testing:
1. Open e.cash in mWeb
2. Click + fab button on LHN.
3. It should open properly. See issue #3768 for more info.

Horizontal scroll issue:
 1. Open E.cash Mobile web.
 2. Open any chat.
 3. Close the chat, go back to the home page or LHN.
 4. Try to scroll the page horizontally.
 5. Page should not scroll and you should click on any chat to open it. Please check the linked video on issue #3781 to see the absurd scrolling behavior.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

image

#### Mobile Web

https://user-images.githubusercontent.com/24370807/124191454-6d3ad100-dae1-11eb-93af-b1468b0941cb.mp4

#### Desktop

scroll-d

#### iOS

scroll-i

#### Android

scroll-a

### CODE REVIEW

**Comment by parasharrajat** [comment]
This is a quick one. Thanks

**Review by Beamanator — APPROVED** [review]
Tested both issues, this fixes both - nice work!

**Comment by isagoico** [comment]
@parasharrajat Anything that needs to be QAd here?

**Comment by parasharrajat** [comment]
@isagoico Somehow tests got removed. I have re-added them. Thanks.

**Pull request merged**
