### PR TITLE
Fix context-menu on native devices

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ #4200

### Tests | QA Steps
1. Open the app in iOS.
2. Navigate to a conversation.
3. Long press on a message

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

Screenshot 2021-08-23 18:06:28

#### Mobile Web

Screenshot 2021-08-23 18:08:54

#### iOS

https://user-images.githubusercontent.com/24370807/129678949-9faf5a22-1b0d-4a84-b2c9-773fdb48798a.mp4

#### Android

Screenshot 2021-08-23 18:10:36

### CODE REVIEW

**Comment by parasharrajat** [comment]
Any thought @puneetlath?

**Comment by parasharrajat** [comment]
@Beamanator Could you please review this? I will upload the screens for other platforms if needed.

**Comment by Beamanator** [comment]
@parasharrajat we'd like everyone to be in the habit of testing all PRs on **every platform** so in the future, please do add a screenshot for every platform. This is how we'll most effectively reduce regressions

**Comment by parasharrajat** [comment]
I did test it but didn't upload the images. I will update them.

**Comment by parasharrajat** [comment]
Done

**Review by Beamanator — APPROVED** [review]
LGTM! Tested on android, ios, mweb safari -> works great 👍

**Comment by botify** [comment]
This has been deployed to production and is now subject to a 7-day regression period.
If no regressions arise, payment will be issued on 2021-09-08.  :confetti_ball:

**Pull request merged**
