### PR TITLE
chore(bump-e-common): Updated expensify-common ref hash

### LINKED ISSUE #4229: Hyperlink markdown doesn't work if the ] is preceded by an (
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a conversation
2. Send this message 
` [Yo (click here to see a cool cat)](https://c8.alamy.com/compes/ha11pc/cookie-cat-con-sombrero-de-cowboy-y-sun-glass-ha11pc.jpg)`
3. Check the message in the history

## Expected Result:
The link should be hyperlinked even if there is a ) before the ].

## Actual Result:
Link is not hyperlinked. Checked on Github and it gets hyperlinked correctly so this seems like an issue. 
**Important**: Same happens for other punctuation marks. 

Example 
[Yo (click here to see a cool cat)](https://c8.alamy.com/compes/ha11pc/cookie-cat-con-sombrero-de-cowboy-y-sun-glass-ha11pc.jpg)

## Workaround:
User can send the link without the formatting

## Platform:
Where is this issue occurring?

- [x] Web
- [x] iOS
- [x] Android
- [x] Desktop App
- [x] Mobile Web

**Version Number:** 1.0.80-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

image

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

____ 
From @mallenexpensify https://expensify.slack.com/archives/C01GTK53T8Q/p1627271189249400 
> Markdown doesn't work when ] is preceded by )

### PR DESCRIPTION
**Pull request by mananjadhav**
@andreacastejon can you please review this?

### Details
- Merges hyperlink changes from expensify-common to the App

### Fixed Issues

$ Fixes [App/4229](https://github.com/Expensify/App/issues/4229)

### QA Steps

1. Type `[Yo (click here to see a cool cat)](https://c8.alamy.com/compes/ha11pc/cookie-cat-con-sombrero-de-cowboy-y-sun-glass-ha11pc.jpg)` (without `)
2. Verify it hyperlinks correctly

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/3069065/127357607-b09cc0f1-6e6c-4b0d-9d1a-6e53df0e3eec.mp4

#### Mobile Web
https://user-images.githubusercontent.com/3069065/127372250-daec48b7-855b-4965-b11b-7cffddc227cf.mp4

#### Desktop
https://user-images.githubusercontent.com/3069065/127357442-98d02450-cdf1-45d1-8cea-0bf6f136d99b.mp4

#### iOS
https://user-images.githubusercontent.com/3069065/127385748-6e297267-fa5c-47e2-8851-5b0fa654c545.mp4

#### Android
https://user-images.githubusercontent.com/3069065/127372048-5dbce2a9-172b-4252-98d2-6f0945f65ffe.mp4

### CODE REVIEW

**Comment by mananjadhav** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by timszot — DISMISSED** [review]
LGTM, leaving for @AndrewGable

**Comment by botify** [comment]
npm has a `package.json` file and a `package-lock.json` file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run `npm install`

**Comment by AndrewGable** [comment]
@mananjadhav - Screenshots look great. I updated with QA steps. Can you run `npm install` as the bot is asking?

**Comment by mananjadhav** [comment]
Just did and pushed

**Comment by mananjadhav** [comment]
@AndrewGable Some checks failed after my last commit. The lint errors are not even related to my changes.

**Comment by AndrewGable** [comment]
We will take a look into this- I agree it seems unrelated to your changes.

**Comment by mananjadhav** [comment]
Thanks. Let me know if you want my help with this.

**Comment by AndrewGable** [comment]
I updated my local `main` branch to have your hash `git://github.com/Expensify/expensify-common.git#e83c6998dac6837098745139cb2bdd4e18bf7134` in `package.json`. These are the only changes I see in my diff are this:
```diff
diff --git a/package-lock.json b/package-lock.json
index 90dd382d8..af867b63d 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -23070,8 +23070,8 @@
       }
     },
     "expensify-common": {
-      "version": "git://github.com/Expensify/expensify-common.git#7d8408c5c78792394eee8e079f115b1380221a23",
-      "from": "git://github.com/Expensify/expensify-common.git#7d8408c5c78792394eee8e079f115b1380221a23",
+      "version": "git://github.com/Expensify/expensify-common.git#e83c6998dac6837098745139cb2bdd4e18bf7134",
+      "from": "git://github.com/Expensify/expensify-common.git#e83c6998dac6837098745139cb2bdd4e18bf7134",
       "requires": {
         "classnames": "2.3.1",
         "clipboard": "2.0.4",
diff --git a/package.json b/package.json
index 2c29e02b0..377a519f9 100644
--- a/package.json
+++ b/package.json
@@ -60,7 +60,7 @@
     "electron-log": "^4.3.5",
     "electron-serve": "^1.0.0",
     "electron-updater": "^4.3.4",
-    "expensify-common": "git://github.com/Expensify/expensify-common.git#7d8408c5c78792394eee8e079f115b1380221a23",
+    "expensify-common": "git://github.com/Expensify/expensify-common.git#e83c6998dac6837098745139cb2bdd4e18bf7134",
     "expo-haptics": "^10.0.0",
     "file-loader": "^6.0.0",
     "html-entities": "^1.3.1",
```

The `package-lock.json` diff that you pushed is a lot larger. This makes me think that you might not have the same `npm` version or `node` version leading to these errors. Can you double check that you have the same versions installed and see if you see the same?

```
andrew ➜ Expensify.cash npm --version
6.14.11
andrew ➜ Expensify.cash node --version
v14.16.0
```

**Comment by mananjadhav** [comment]
Yeah, I've got different versions here:

```
npm --version ---> 6.14.5
node --version ---> v12.16.1
```

**Comment by AndrewGable** [comment]
Ok can you install the versions I've listed and see if re-running `npm install` leaves you with a similar diff? Thanks.

**Comment by mananjadhav** [comment]
@AndrewGable  I've raised a fresh PR removing my node_modules, etc. and I can match your diff. Closing this one.

https://github.com/Expensify/App/pull/4283

**Pull request closed without merging**
