### PR TITLE
Add tap to view full screen image functionality

### PR DESCRIPTION
**Pull request by thienlnam**
<Assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

<Explanation of the change or anything fishy that is going on>

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/142710 and https://github.com/Expensify/Expensify/issues/143523
### Tests
1. Upload an image and a PDF
2. Click on them and verify they open correctly

### Screenshots
<Add any necessary screenshots for all platforms if your change added or updated UI>

Screen Shot 2020-10-30 at 1 51 19 PM
Screen Shot 2020-10-30 at 1 51 07 PM

Screen Shot 2020-10-30 at 1 50 32 PM

Screen Shot 2020-10-30 at 1 50 40 PM

### CODE REVIEW

**Review by tgolen — CHANGES_REQUESTED** [review]
I know this is a WIP, so just adding a few comments. Looks like it's all on the right track 👍

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]
Looks great so far! Left a few thoughts. Biggest issue for me is that there is a lot of overlap in the web/native implementations and we should try to make things more general.

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by marcaaron — CHANGES_REQUESTED** [review]
Looking better but I think we can dry this up some more.

**Review by marcaaron — CHANGES_REQUESTED** [review]
Getting better each time! Here's another round of comments for ya

**Review by marcaaron — COMMENTED** [review]
Gonna tag in @shawnborton for some final styling thoughts...

The margins here look a little off and the `x` could be larger

Screenshot 1553

We are showing images at the max possible size which distorts them and we should really not go past their true size I think? e.g.

Screenshot 1552

For some reason when I uploaded a PDF the thumbnail preview stopped working... not sure if this is a me problem. But I'm seeing this while other non PDF images load fine

Screenshot 1554

Moving on to iOS, Android, and Desktop next...

**Review by marcaaron — CHANGES_REQUESTED** [review]
Still trying to get this working on iOS but the previews were resolved by updating `Web-PDFs` and doing a composer install

**Review by marcaaron — DISMISSED** [review]

**Review by tgolen — CHANGES_REQUESTED** [review]

**Review by tgolen — DISMISSED** [review]
Thanks for those changes. Looks good!

**Review by roryabraham — CHANGES_REQUESTED** [review]
Overall looks pretty good, just a few suggestions. Sorry for the delayed review - this was my first time fully looking through this PR

**Review by roryabraham — DISMISSED** [review]
LGTM

**Review by tgolen — DISMISSED** [review]
The different constants are getting confusing. The more explicit the constant name, the less confusing this will be. I really hate blocking the PR on this though, so I would be OK with merging this PR as-is and then doing an immediate follow-up to clean up these constants.

Here are the things that I find confusing:

- I don't know when to use ngrok or why
- If `USE_NGROK=true`, then `SITE_ROOT` and `API_ROOT` are modified with the ngrok URL. However, if you have to modify the `.env` file to set `USE_NGROK` then why not just change `SITE_ROOT` and `API_ROOT` instead?
- If `NGROCK_URL` exists, then it's not clear what happens with `EXPENSIFY_SITE_ROOT`
- `DEFAULT_SITE_ROOT` is a very ambiguous name with no meaning
- `SITE_ROOT` is also ambiguous and easily confused with the other constants
- `USE_NGROK` is not really necessary because the logic can just check if `NGROK_URL` exists

Some suggestions:
1. The readme probably needs updated instructions for using ngrok properly (why, when, how, etc.)
1. Get rid of `API_ROOT` completely. It is only used twice, and those can be switched to be  `${SITE_ROOT}api?` instead
1. Rename `DEFAULT_SITE_ROOT` to `URL_EXPENSIFY_COM`
1. Rename `CASH_SITE_ROOT` to `URL_EXPENSIFY_CASH`
1. Rename `SITE_ROOT` to something else (but I am still unclear what it is used for so I can't suggest a better name right now)
1. Maybe we can add a platform specific `.env.native` file which would be where the ngrok values are set (so you don't have to constantly be modifying `.env` when switching between platforms).

**Review by tgolen — APPROVED** [review]

**Pull request merged**
