### PR TITLE
Revert "Remove all uses of  `actorEmail` as part of personalDetails migration"

### PR DESCRIPTION
**Pull request by iwiznia**
Reverts Expensify/App#21874

Due to https://github.com/Expensify/App/issues/22286#issuecomment-1622255439

### CODE REVIEW

**Comment by iwiznia** [comment]
This is a revert, not doing the checklist really

**Review by thienlnam — APPROVED** [review]
Approving tho https://expensify.slack.com/archives/C01SKUP7QR0/p1688587045117749?thread_ts=1688585912.527219&cid=C01SKUP7QR0

**Review by luacmartins — APPROVED** [review]

**Comment by PauloGasparSv** [comment]
Feel free to merge since we got some reviews here already, removing myself!

**Comment by iwiznia** [comment]
Did not wait for travis to pass since this is a revert

**Pull request merged**
