### PR TITLE
#3102 add accessibility role and label to close button

### LINKED ISSUE #3102: Accessibility improvement: Add a role, label, and voiceover to the "close" X button
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Expected Result:
The "close" X should have a role, label, and voiceover 

## Actual Result:
There is no role, label, or voiceover to the "close" X button

## Action Performed:
1. Turn on Screen Reader or Voiceover
2. Launch the Expensify.cash app or website
3. Swipe or click into any menu that has an X "close" button. For example:
- `( + )` > `New Chat` > `X`
- `( + )` >  `Request Money` > `X`
- `( + )` >  `New Group` > `X`
- tap `avatar` icon > `X`
- tap `search` 🔍  icon > `X`

4. Notice that the X "Close" button doesn't have a role, label, or voiceover component.

## Platform:
- Windows/JAWS/Chrome
- MACOs/Voiceover/Safari
- Android/Talkback
- iOS/Voiceover
- MacWebapp/Voiceover

**Notes/Photos/Videos:** 

Video - https://user-images.githubusercontent.com/37308300/119419108-7dcc8000-bcc7-11eb-9036-bb53c6e951b7.mp4

**Upwork job link** - https://www.upwork.com/jobs/~013b962eb299963c76

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

### PR DESCRIPTION
**Pull request by dklymenk**
### Details
Simple addition off accessibility props.

### Fixed Issues

Fixes #3102 

### Tests / QA Steps

1. Turn on Screen Reader or Voiceover
2. Launch the Expensify.cash app or website
3. Swipe or click into any menu that has an X "close" button. For example:
( + ) > New Chat > X
( + ) > Request Money > X
( + ) > New Group > X
tap avatar icon > X
tap search mag icon > X
4. Make sure that the X "Close" button has a role and a label.

### Tested On

- [x] Web - Windows/JAWS/Firefox - MACOs/Voiceover/Safari
- [x] Mobile Web
- [x] Desktop - Voiceover
- [ ] iOS - iOS/Voiceover
- [x] Android - Android/Talkback

I do not own a physical iPhone and there is no Voiceover on iOS simulator, so I am unable to test accessibility features on  iOS app.

#### Web

https://user-images.githubusercontent.com/64093836/120702803-2b584400-c4bd-11eb-8f0c-d3b0ddc81355.mp4

https://user-images.githubusercontent.com/64093836/120702883-4925a900-c4bd-11eb-8f2e-587a529f8f26.mp4

#### Mobile Web

https://user-images.githubusercontent.com/64093836/120704708-9c006000-c4bf-11eb-9489-4e1254e1635f.mp4

#### Desktop

https://user-images.githubusercontent.com/64093836/120705402-732c9a80-c4c0-11eb-9543-796702a491d5.mp4

#### Android

https://user-images.githubusercontent.com/64093836/120703403-ec76be00-c4bd-11eb-84e8-3405efb04b03.mp4

### CODE REVIEW

**Review by mountiny — APPROVED** [review]
Tested on Desktop, Web and tested in ios simulator using [this](https://scottvinkle.me/blogs/work/testing-with-screen-readers#screen-reader-virtual-cursor) approach although I am not sure if it is bulletproof. Unfortunately, I do not have Android phone and I do not have certificates et up yet to test it on my phone. I have requested the certificates.

**Comment by dklymenk** [comment]
Ok, I'll submit a PR as soon as I can.

Meanwhile, you might also want to take a look at this MR - https://github.com/Expensify/Expensify.cash/pull/3285/files

It also makes accessibility changes and adds translations for EN only.

**Comment by iwiznia** [comment]
Yep, thanks for that link!

**Comment by dklymenk** [comment]
@iwiznia Please find PR with missing translation here https://github.com/Expensify/Expensify.cash/pull/3525

**Comment by iwiznia** [comment]
Thanks! I approved it already.

**Pull request merged**
