### PR TITLE
Fix comment linking bugs

### PR DESCRIPTION
**Pull request by janicduplessis**
### Details

This includes a few fixes for fixing janky or stuck scroll after comment linking. There were actually multiple different issues all with separate fixes. After all those scroll is now smooth and doesn't get stuck.

1. Fix onStartReached not called in some cases (15546b6fa2aad0e74d8822bcaecebbf9b4187287): When scrolling down after comment linking, sometimes the scroll would get stuck. This is because onStartReached was never called. This is caused by the early return in `VirtualizedList.getDerivedStateFromProps`. It compares the number of items with `renderMask.numCells()`, but for some reason sometimes this is different from the previous number of items. So to fix it we now save the previous number of items in state and also compare that. Upstream PR https://github.com/facebook/react-native/pull/46250

2. Fix maintainVisibleContentPosition on Android (0b214f7f1c59b244b4e530377bb4707140377f02): I found a few issues with the maintainVisibleContentPosition implementation on Android, which causes some jumping while scrolling. Part of it was already addressed in https://github.com/facebook/react-native/pull/43425, but we didn't have a patch for it so this adds it. There is also another issue where the first visible view is sometimes incorrectly updated so it moves the update to when the scroll view scrolls, instead of before views are updated. I also found an issue because we use z-index on list cells which cause views to be re-ordered and the wrong view ends up being selected as the first visible view. Upstream patch https://github.com/facebook/react-native/pull/46247.

3. Fix newer messages not loading (5f9aede6070436c2d80103678b4c0d4aa9a22f89): There is a check in `loadNewerChats` that would sometimes cause scrolling to be stuck because new messages are not loaded. I verified with the author of this code @perunt and also did some testing and we concluded that this code is no longer needed and can be removed.

4. Fix not found view flicker (c804881c26cf6275539c2f521c86da8cd2ceda95): Some code relies on the `isLinkingToMessage` variable to not display the not found view, but it is currently updated in a `useLayoutEffect`. On web this works fine, but on native it cannot render synchronously so there will be a flicker of the wrong UI. To fix this we can update state in render instead.

5. Fix scrollTo called when not needed on Android (13c9acb1a37667c7a2952c4a4080071992f21674): This code is supposed to call scroll to only when the screen is focused, but it was being called more because the callback depended on the scroll position value, so every time scroll ends it would call scroll to. This caused issues sometimes where scroll position would become incorrect because it would scroll to an outdated position and revert the scroll caused by maintainVisibleContentPosition. To fix this we can remove the dependency on the scroll position of the callback by using a ref.

6. Fix flickering on iOS, this is caused by the `patches/react-native+0.73.4+016+iOSCoreAnimationBorderRendering.patch` patch which adds a CATransaction around mounting phase. This transaction should also include the willMount and didMount observer calls since we use those to adjust the scroll position and we don't want iOS to update the screen before those are called. This moves the CATransaction creation around the code that calls the observers.

#### Known issues left, will address in another PR:

1. On android when comment linking twice to the same message, on the 2nd time the scroll position jumps incorrectly.

#### Before

Scrolling after comment linking with cache:

This shows janky scroll and scroll getting stuck.

https://github.com/user-attachments/assets/33b9c734-c617-4095-84c6-5a4fa7ec1619

Scrolling after comment linking no cache:

This shows the flicker of not found view as well as scroll being stuck.

https://github.com/user-attachments/assets/b64de241-402b-41ee-b9ab-b9bc74b2cfec

#### After

Scrolling after comment linking with cache:

https://github.com/user-attachments/assets/6bbd1182-f045-40ed-bdd1-f4b0e7738f6a

Scrolling after comment linking no cache:

https://github.com/user-attachments/assets/b055df6a-8f2e-4e88-955e-a87c7808c0e9

### Fixed Issues

$ https://github.com/Expensify/App/issues/46217
$ https://github.com/Expensify/App/issues/46222
PROPOSAL:

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

- [ ] Verify that no errors appear in the JS console
- [ ] Test comment linking flow with cached messages (scroll through the full chat first)
- [ ] Test comment linking flow without cached messages (use clear cache in Troubleshoot section)

Comment linking flow:

- In a chat with many messages copy the link to a message and send it
- Click on the message link from the first step
- Verify that the right message is scrolled to and that it is possible to scroll back down to the start of the chat

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/6bbd1182-f045-40ed-bdd1-f4b0e7738f6a

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/a0949770-6adc-4843-b3af-522459a22cd1

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/57c96978-5cfb-47c6-8284-7f2e126618b9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/ed08b801-3abc-4109-a5b0-76c67b28df1a

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/72d46aae-a56c-4a48-a014-dd0080313506

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/04453839-8b75-4521-8050-4f64efecff30

</details>

### CODE REVIEW

**Comment by janicduplessis** [comment]
@ishpaul777 

> I still got stuck for few seconds, while scrolling after commentlinking 🤔 (cached messages)

Do you have to scroll up / down to unblock it or just wait? The rendering of new items is just a bit slow, especially in dev mode so it would be normal if it just stays stuck for a little bit of time. It would be good to profile though to see if it can be optimized.

> I am not sure if i understand the issue itself, could you please provide a after/before video. is this part of Scrolling after comment linking with cached actions issue

It is part of `Scrolling after comment linking with cached actions issue`. Sometimes the scroll position would jump when the following occurs:

1. Scroll ends -> JS sends new scroll position to native
2. New messages are loaded
3. Native adjusts scroll position to maintain visible content position
4. Native receives outdated scroll position from JS (step 1) and scroll to old position which causes jumping

> Java code is way over my head, i'll bring in a internal engineer later to help review this. Would be helpful if you can add a before/after video

You can kind of see it in `Scrolling after comment linking with cache:` before and after videos. Basically before the patch sometimes there will be jumping of content. Would you like me to make a video with just that java change to see the before / after?

**Comment by janicduplessis** [comment]
> Is this the jump you are talking about 🤔 (this is on main branch)

Looks like it yes!

**Comment by janicduplessis** [comment]
@ishpaul777 done!

**Comment by janicduplessis** [comment]
I did notice there were some jumping issues on Safari still, but I think I can address these in a separate PR since this one is getting pretty big.

I also saw a few rarer cases of jumping on android still, but also I think can be addressed later as these fixes bring very big improvements.

**Comment by janicduplessis** [comment]
@ishpaul777 I have a few more fixes for safari, would you prefer if I make them into a separate PR or include them here?

**Comment by janicduplessis** [comment]
Will continue work on this tomorrow!

**Comment by janicduplessis** [comment]
@ishpaul777 Would you be able to confirm whether these bugs are also present on main? I think we could address them in a separate PR if so, as this one is already pretty big.

**Comment by janicduplessis** [comment]
I am only able to reproduce on real device, will debug it today.

**Comment by janicduplessis** [comment]
@ishpaul777 I am able to reproduce the issue when linking to first message on main too, I will have a quick look to see if it would be easy to fix, but I don't think it is a blocker to merge this.

**Comment by janicduplessis** [comment]
@ishpaul777 I've been trying to repro the other 2 issues on both main and my branch and wasn't able to. Can you confirm whether it still happens for you?

**Comment by janicduplessis** [comment]
Update description with the flicker fix

> Fix flickering on iOS, this is caused by the patches/react-native+0.73.4+016+iOSCoreAnimationBorderRendering.patch patch which adds a CATransaction around mounting phase. This transaction should also include the willMount and didMount observer calls since we use those to adjust the scroll position and we don't want iOS to update the screen before those are called. This moves the CATransaction creation around the code that calls the observers.

**Comment by janicduplessis** [comment]
@ishpaul777 Anything missing on my side or is everything addressed now?

**Review by ishpaul777 — APPROVED** [review]

**Comment by roryabraham** [comment]
discussing in slack [here](https://expensify.slack.com/archives/C035J5C9FAP/p1723840145399199), but let's please be sure to go back and update this PR description with links to all the upstream commits and PRs for all the added patches

**Review by roryabraham — APPROVED** [review]

**Pull request merged**
