### PR TITLE
Update about page copy

### PR DESCRIPTION
**Pull request by Beamanator**
~Holding on Spanish translation confirmation [here](https://expensify.slack.com/archives/C21FRDWCV/p1626339105092100)~ Approved!

### Details

Just updating the about page text 👍 

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/170730

### Tests
1. Go to the about page (Settings -> About)
2. Make sure new text is showing

### QA Steps
N/A

### Tested On

- [x] Web
- [x] Mobile Web
- [ ] Desktop
- [x] iOS
- [x] Android

#### Web

Screen Shot 2021-07-15 at 11 19 10 AM

#### Mobile Web (iOS)

Screen Shot 2021-07-15 at 11 18 38 AM

#### Desktop

[having a tough time since it seems there's an unrelated bug preventing me from loading anything :D]

#### iOS

Screen Shot 2021-07-15 at 11 13 35 AM

#### Android

Screen Shot 2021-07-15 at 11 03 39 AM

### CODE REVIEW

**Comment by Beamanator** [comment]
No longer on hold 👍

**Review by deetergp — CHANGES_REQUESTED** [review]
Per this convo, it should be `El nuevo Expensify` https://expensify.slack.com/archives/C21FRDWCV/p1626353964092900?thread_ts=1626339105.092100&cid=C21FRDWCV

**Comment by Beamanator** [comment]
Good catch! Fixed 👍

**Review by deetergp — APPROVED** [review]
¡Está bien, gracias!

**Review by sketchydroide — APPROVED** [review]
LGTM

**Pull request merged**
