### PR TITLE
Reduced emoji spacing and increased emoji size

### PR DESCRIPTION
**Pull request by mananjadhav**
@chiragsalian Can you please review this?

### Details
Reduced spacing between emojis and increased emoji size.

### Fixed Issues

$ #4544 

### Tests
1. Tested emoji picker on all platforms
2. Tested landscape mode. Added before and after screenshots.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
web-old-view
web-view

#### Mobile Web
**Portrait**
old-portrait
mweb

**Landscape**
old landscape
mweb landscape

#### Desktop
desktop

#### iOS
ios

#### Android
android

### CODE REVIEW

**Review by chiragsalian — CHANGES_REQUESTED** [review]
With these changes to emoji sizes i see these as unused. 
https://github.com/mananjadhav/App/blob/2a6e5b9323e2e8c6bd423a0c3d67169fe4415238/src/styles/styles.js#L1209-L1215

Could we remove them and `iconSizeLarge`?

Rest of your code looks good to me.

**Comment by mananjadhav** [comment]
@chiragsalian `iconSizeLarge` isn't used but `iconSizeNormal`, `iconSizeSmall` are used. I kept it as is just to retain the sequence. Do you still want me to remove it?

**Comment by shawnborton** [comment]
Can you help me understand why we need so many different sizes for emojis?
image

**Comment by mananjadhav** [comment]
@shawnborton We are currently using extraSmall, Normal and Large. I’ve added the small as well to ensure continuous range and if it gets used in the future. 

The above three sizes are added so that the overall container is size is not increased. We use different sizes based on device width. 

https://github.com/Expensify/App/blob/2a6e5b9323e2e8c6bd423a0c3d67169fe4415238/src/pages/home/report/EmojiPickerMenu/dynamicEmojiSize.js

**Comment by shawnborton** [comment]
So emojiSizeSmall is not used? If it's not used and we aren't sure if/when it will ever be used in the future, we can remove it. 

That being said, I am questioning why we really need 3 sizes for this. For example, we only have one main text size that we share between mobile and desktop (15px). Can you try making this work with just one standard emoji size for the picker menu?

**Comment by mananjadhav** [comment]
Okay sure. I’ll try to make a common size. That would also mean either changing the container size or number of emojis per row.  Is that something we are okay with ?

**Comment by shawnborton** [comment]
Why do you need to change the container size or number of emojis? 

If you recall from the issue you recreated... I am not sure that this is a real problem we are solving. I'd say try just adjusting the spacing first, and let's see how that looks before modifying the emoji size. Thanks!

**Comment by mananjadhav** [comment]
Okay I’ll check. 

I was following the existing structure where emojisizes are different based on device width. So are you suggesting we get rid of the current dynamicEmojiSize approach as well?

**Comment by shawnborton** [comment]
I think what I am saying is, let's just leave the emoji size alone to start (keep it how it currently is) and only modify the spacing of the buttons. Then let's review what the spacing changes do, and see if we need to make more adjustments from there.

**Comment by shawnborton** [comment]
I didn't realize we were currently using three different emoji sizes for the menu, and I personally think that's overkill.

**Comment by mananjadhav** [comment]
Yeah sorry for not being more clearer. Hence I highlighted the container size changes. So should I still go ahead and try to make the size consistent?

**Comment by shawnborton** [comment]
I would be curious to see what it looks like if we find one size that works everywhere... maybe it's something like `20`?

**Comment by mananjadhav** [comment]
Sure lets try that. We can always rollback. I'll check and update you. 🚀

**Comment by shawnborton** [comment]
Awesome, thanks for your patience on this one!

**Comment by mananjadhav** [comment]
@shawnborton This is how it looks with fixed size `20`, with less horizontal padding and desktop web container width reduced to `320` (earlier was 392). Let's take it forward from here?

**All three views**
Screenshot 2021-08-24 at 5 24 51 PM

**Web/Desktop Emoji Container Size**
Here's another comparison between  Emoji Container size `320` and `352`.

image

My take is fontSize `20` looks good on mobile landscape and portrait. Web fontSize `20` should be good with container size `352`.

**Comment by shawnborton** [comment]
I think it looks pretty good. Thoughts?

**Comment by shawnborton** [comment]
And yeah, I think it's okay if we adjust the container size on desktop to make sure things look good there too.

**Comment by mananjadhav** [comment]
@shawnborton I agree, it looks good.  For container on desktop, do prefer `320` or `352` ?

**Comment by shawnborton** [comment]
320 looks pretty good to me I think. Which do you prefer?

**Comment by mananjadhav** [comment]
Well I was included towards 352, but after checking a emoji mart, slack etc, it seems 320 might look better

**Comment by mananjadhav** [comment]
@chiragsalian I've updated the PR removing a fair amount of unused code. Can you please review it again?

**Comment by shawnborton** [comment]
Awesome, thanks again for listening to my feedback and working through our comments!

**Review by chiragsalian — APPROVED** [review]
Nice, looks clean 👍

**Pull request merged**
