### PR TITLE
Bugfix/default avatar becomes square

### PR DESCRIPTION
**Pull request by Dima-Kevanishvili**
### Details

Mask in the fallback avatar SVG file was having an Id Collision, which was causing default avatar images to be square, instead of circles. This change removed the masking method, which in return fixes the issue.

### Fixed Issues

$ https://github.com/Expensify/App/issues/12713
PROPOSAL: https://github.com/Expensify/App/issues/12713#issuecomment-1315908736

### Tests

1. Login to an account which has more than 20 chats
2. Disconnect the internet connection
3. Navigate to search page
4. Scroll and select a chat with offline default avatar
5. Press back button to close the chat
6. Observe the avatar at chat list

- [x] Verify that no errors appear in the JS console

### Offline tests

1. Login to an account which has more than 20 chats
2. Disconnect the internet connection
3. Navigate to search page
4. Scroll and select a chat with offline default avatar
5. Press back button to close the chat
6. Observe the avatar at chat list
### QA Steps

1. Login to an account which has more than 20 chats
2. Disconnect the internet connection
3. Navigate to search page
4. Scroll and select a chat with offline default avatar
5. Press back button to close the chat
6. Observe the avatar at chat list
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [ x I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).

- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

<details>
<summary><h4>PR Reviewer Checklist</h4>

The reviewer will copy/paste it into a new comment and complete it after the author checklist is completed
</summary>

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for expected offline behavior are in the `Offline steps` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [ ] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] I verified that if a function's arguments changed that all usages have also been updated correctly
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

</details>

#### Web

https://user-images.githubusercontent.com/35175081/202689892-11c81311-3e96-4b95-86bf-6794399e8069.mov

#### Mobile Web - Chrome

https://user-images.githubusercontent.com/35175081/202689954-10c7430d-19b8-4fa7-863f-a8f48698a68a.mp4

#### Mobile Web - Safari

https://user-images.githubusercontent.com/35175081/202690020-6173630b-9b66-47f2-b121-cb9fa4d9988b.mp4

#### Desktop

https://user-images.githubusercontent.com/35175081/202690045-7da965fd-4a31-4a2f-9c4b-8d867ffb68f4.mov

#### iOS

https://user-images.githubusercontent.com/35175081/202690068-a50d3e7f-b6c0-4c0b-96d5-3e441571e80a.mov

#### Android

https://user-images.githubusercontent.com/35175081/202690276-8695ff84-704d-4d32-9b8b-ab52bc1f6d32.mov

### CODE REVIEW

**Comment by Dima-Kevanishvili** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Review by aimane-chnaif — CHANGES_REQUESTED** [review]
@Dima-Kevanishvili gray background color is a bit different from old one

**Comment by Dima-Kevanishvili** [comment]
@aimane-chnaif Updated

**Comment by Dima-Kevanishvili** [comment]
> > update color transparency to better match the original color
> 
> @Dima-Kevanishvili This is kind of a workaround. Isn't there any other way to match original background exactly, not just adjusting opacity?

The original SVG file also had transparency and that's why I added it, I thought it'd be better to match the original. Otherwise no matter what I would set the color to it would have looked off on different backgrounds.

I compared the colors with a color picker on the sidebar background(unselected,unhovered) and got the RGB values of 215, 216, 217 on both old version and the new one

**Comment by Dima-Kevanishvili** [comment]
@aimane-chnaif 
I researched this problem a bit more:
The original SVG file had 2 paths (The Face and The Torso sections of the avatar image) and a single rectangle behind those paths which worked as a background.
Paths were filled with Color: #FFFFFF (White)
The rectangle was filled with Color: #C6C9CA
This can be seen here:

https://user-images.githubusercontent.com/35175081/202810854-757f858e-2ced-4345-b648-3f00a2ad7dde.mov

Additionally, the old SVG file had a mask. Inside that mask was a circle with the fill color #2ECB70.
Said mask was doing two things:
1. Because there was a circle inside the mask, it was cutting off the corners of the rectangle and making it a circle
2. It was adding transparency to the image.

The mask itself was the problem here and we needed its removal.

In my file:
Same two paths.
And a shape that first was a circle and had the shapes of the paths cut out from it with the same color as the rectangle.

The reason why the circle needed to have cutouts - After noticing the transparency, I tried to replicate it with the fill-opacity values, if the white parts(head and torso) had the gray (circle) background, then dropping the opacity of the paths, would cause the different color to show up.

What I didn't realize was that the fill color for the mask wasn't just white, or black. Therefore the color/opacity changes a bit on the old version of the file wherever you take the sample from:

https://user-images.githubusercontent.com/35175081/202812821-07673427-c773-4703-9600-316d4957242a.mov

You can see that the new version also changes the color sometimes, but the difference isn't as noticeable and it's more uncommon.

If you do the same test on the actual website, even in the older version the color difference is minimal(same as the new one on GitHub), but the problem there is that if you compare the older and new avatars on the sidebar, they do match, but if you compare them on a whiter background(report screen header for example) they do not anymore.

I could reintroduce the mask to fix the color, but then the problem would be that the transparency/color changes instead of the avatar becoming square sometimes.

So my question is: With all that information in mind, can we choose what the color/transparency should be and make it look bit different from the old version in exchange of not being randomly square or randomly different color?

**Comment by Dima-Kevanishvili** [comment]
Any updates on this?

**Comment by shawnborton** [comment]
What was the old background hex? I can switch that out

**Comment by shawnborton** [comment]
Got it. I'm not sure why that would have reduced opacity though. 

I believe we're going to be updating all of these icons soon anyways, so maybe the best path forward is just to close this one out? I'd suggest we still pay you for the issue but we're just a day or so away from merging this one: https://github.com/Expensify/App/pull/12796#issuecomment-1323933679

**Comment by Dima-Kevanishvili** [comment]
@shawnborton it would be very much appreciated if you still payed. As for closing this one out, of course I don't have anything against it.

**Comment by yuwenmemon** [comment]
Closing as per the discussion above.

**Pull request closed without merging**
