### PR TITLE
Updated placement of the user status icon

### PR DESCRIPTION
**Pull request by jayeshmangwani**
### Fixed Issues

$ https://github.com/Expensify/App/issues/34380
PROPOSAL: https://github.com/Expensify/App/issues/34380#issuecomment-1887603970

### Tests

1. Open App, Go to Settings > Profile > Status
2. Select an emoji and Press Save
3. Now go to the main chat app and observe the user icon and status placement
4. Verify that it looks same as issue description  

- [x] Verify that no errors appear in the JS console

### Offline tests

Same as Tests
### QA Steps

Same as Tests
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>
Screenshot 2024-01-29 at 9 02 48 PM
Screenshot 2024-01-29 at 9 03 14 PM

</details>

<details>
<summary>Android: mWeb Chrome</summary>
Screenshot 2024-01-29 at 8 58 56 PM
Screenshot 2024-01-29 at 8 59 15 PM

</details>

<details>
<summary>iOS: Native</summary>
dark
light

</details>

<details>
<summary>iOS: mWeb Safari</summary>

dark
light

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>
dark
light

</details>

<details>
<summary>MacOS: Desktop</summary>
dark
web

</details>

### CODE REVIEW

**Comment by jayeshmangwani** [comment]
@mollfpr Below I am attaching the screenshots for these styling

1. User profile picture height and width is 40px and 2px margins around, total height and width is 44 and backgrounnd color is componentBG(color is same as before) 
2. Height and width of the status container is 30 and background color is componentBG(color is same as before) too
3. Font size of the emoji is 22 (font size is same as before)
4. position of the emoji container is -7 from bottom and right

cc: @shawnborton @dannymcclain @dubielzyk-expensify

<details>
<summary>iOS: Native</summary>


**Dark**
Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-19 at 14 41 41

**Light**
Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-19 at 14 41 54

</details>


<details>
<summary>mWeb: Safari</summary>


**Dark**
Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-19 at 14 41 27


**Light**

Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-19 at 14 41 09


</details>


<details>
<summary>Desktop</summary>


**Dark**
Screenshot 2024-01-19 at 2 42 07 PM


**Light**
Screenshot 2024-01-19 at 2 42 21 PM


</details>


<details>
<summary>web: chrome</summary>


**Dark**
Screenshot 2024-01-19 at 2 42 30 PM


**Light**
Screenshot 2024-01-19 at 2 42 46 PM


</details>

**Comment by shawnborton** [comment]
Hmm this doesn't quite seem to line up with the mockup I remember seeing. @dubielzyk-expensify or @dannymcclain can you provide some more direction on the specifics here?

**Comment by dubielzyk-expensify** [comment]
Great progress, but a few measurements are off. Here's the detailed specs:
CleanShot 2024-01-22 at 10 23 54@2x

CleanShot 2024-01-22 at 10 24 19@2x

Also worth noting that on desktop the header background is different to on mobile which is why the border of the status circle need to change:
CleanShot 2024-01-22 at 10 25 13@2x

Hope that helps. Let me know when you got an update and I'll do another review 😄

**Comment by shawnborton** [comment]
> Also worth noting that on desktop the header background is different

Oh interesting, I did not realize that was the case. That seems like a bit of a bug... but regardless, all of this is changing with the new #ideal-nav restructuring, so I think we only need to worry about the darker `appBG` color being used here

**Comment by jayeshmangwani** [comment]
Below I am attaching a screenshots for the ios, web and desktop, please have a look and give your feedback.

For the user status icon view, height and width of the background is 16px and background color is `theme.border` and border width is 2px and border color is same as background color of the page/header (`theme.highlightBG`), and emoji is text and in the screenshots fontsize is 9 for the emojis, if we are using greater then this fontsize then emoji is overlapping with the border

> Also worth noting that on desktop the header background is different to on mobile which is why the border of the status circle need to change:
Right now desktop and all the other platform has same header background color (highlightBG), so not sure if we have to do anything extra for the desktop here
@shawnborton @dubielzyk-expensify 

<details>
  <summary>iOS</summary>
  iOS-dark

iOS-light

  
</details>

<details>
  <summary>web</summary>
 web-dark
 
web-light
 
  
</details>

<details>
  <summary>desktop</summary>
  
desktop-dark

desktop-light


  
</details>

**Comment by shawnborton** [comment]
In your screenshots, things still appear to be off. I think they are too small because the width of that area is taking into account the border size. So if we want the ellipse area to be 16px with a 2px outer stroke, we might need to make that area at say 20x20? So we get 16px + 2px stroke + 2px stroke.

**Comment by jayeshmangwani** [comment]
> So if we want the ellipse area to be 16px with a 2px outer stroke, we might need to make that area at say 20x20? So we get 16px + 2px stroke + 2px stroke.

Screenshot 2024-01-23 at 1 26 38 PM

@shawnborton in this screenshot we have used 20px height width of the main view and 2px stroke and 12px for the emoji

**Comment by shawnborton** [comment]
Nice, that seems better but let's see what @dubielzyk-expensify thinks

Also, is it just me, or is there a dark border around the user icon that shouldn't be there?
CleanShot 2024-01-23 at 09 30 30@2x

**Comment by jayeshmangwani** [comment]
> Nice, that seems better but let's see what @dubielzyk-expensify thinks
Lets wait for @dubielzyk-expensify feedback 

> Also, is it just me, or is there a dark border around the user icon that shouldn't be there? 
It is added intentionally in code, background dimensions is 44*44 and avatar’s dimensions is 40*40, if we don’t want the outer stroke then we can set background dimensions to 40*40

**Comment by shawnborton** [comment]
yeah, I don't know that we want that outer stroke there anymore.

**Comment by jayeshmangwani** [comment]
then we can remove outer stroke it in this PR

**Comment by dubielzyk-expensify** [comment]
Great work @jayeshmangwani .  Like Shawn said, let's remove the outer border on the profile picture

It looks like some emoji's overstep the barrier of the circle:
CleanShot 2024-01-24 at 16 27 50@2x

Can we get a few screenshots with different emojis that are bigger? I think we might have to shrink it down ever so slightly

**Comment by jayeshmangwani** [comment]
@dubielzyk-expensify Thanks for the review, I checked few emojis and it looks like that some large emojis goes a slight outside the view and overlap the stroke, in the attached images last one looks like that it goes outside the view, either we can hide the overflowed part or we can reduce emoji size.

In the below attached images, we have removed outer border of the profile picture

Screenshot 2024-01-24 at 1 16 59 PM
Screenshot 2024-01-24 at 1 17 17 PM
Screenshot 2024-01-24 at 1 17 44 PM
Screenshot 2024-01-24 at 1 18 05 PM

**Comment by shawnborton** [comment]
Hmm is it just me or does it feel like the ellipsis/background circle for the emoji is too small in those screenshots again?

**Comment by jayeshmangwani** [comment]
@shawnborton Yes you are right, above screenshot is of the 16*16 total dimensions, sorry I had overwritten the changes, I am attaching the new screenshots please check that, in these screenshots I have used 2px stroke and 16px background and 9px font size.
Screenshot 2024-01-24 at 2 24 57 PM
Screenshot 2024-01-24 at 2 25 38 PM
t
Screenshot 2024-01-24 at 2 26 06 PM

**Comment by shawnborton** [comment]
Cool, it might not be pulled down and to the right enough, but the sizing feels better. Will let Jon chime in with specifics though :)

**Comment by jayeshmangwani** [comment]
Thanks for the review, some emojis alignment is off because we are using the text for showing the emojis and some emojis has default spacing

**Comment by shawnborton** [comment]
I meant the entire circle area might need to be down and to the right some more, not the emoji inside of it.

**Comment by jayeshmangwani** [comment]
ohh gotcha, in the attached screenshots its -2px from bottom and right

**Comment by dubielzyk-expensify** [comment]
It should be -2px from the bottom and right to be consistent with the workspace changer we'll ship soon. Currently it doesn't look like it's positioned like that though. Is the border messing with the sizing and positioning here?

On the left is my mock and right is the screenshot:
CleanShot 2024-01-25 at 11 22 16@2x

Looks like size and font-size is correct but positioning is off

**Comment by jayeshmangwani** [comment]
Thanks for the review Jon, in this attached screenshot we have used -4 from the right and bottom (2px stroke + 2px position from bottom and right), please confirm if this looks correct
Screenshot 2024-01-25 at 1 12 45 PM

**Comment by dubielzyk-expensify** [comment]
That looks right to me. Thanks for the polish @jayeshmangwani !

**Comment by mollfpr** [comment]
@jayeshmangwani Let me know when it's ready to review!

**Comment by jayeshmangwani** [comment]
@mollfpr PR is now ready for review

**Comment by mollfpr** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [ ] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [ ] If the PR modifies the form input styles:
    - [ ] I verified that all the inputs inside a form are aligned with each other.
    - [ ] I added `Design` label so the design team can review the changes.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>



</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by mollfpr — APPROVED** [review]

**Comment by johnmlee101** [comment]
@shawnborton @dubielzyk-expensify just checking that this is fine to have both GBR and the status? 
image

**Comment by shawnborton** [comment]
> just checking that this is fine to have both GBR and the status?

Nice find! But I do think that this is okay.

**Review by johnmlee101 — APPROVED** [review]
LGTM!

**Pull request merged**
