### PR TITLE
Shows a different message when approving/paying all hold expenses

### PR DESCRIPTION
**Pull request by bernhardoj**
### Details

Currently, when we are trying to approve/pay a report that contains all hold expenses, the confirmation message isn't adjusted for all hold expenses. It still asks whether to approve what's on hold or all even though all are on hold. This PR updates the message accordingly.

### Fixed Issues

$ https://github.com/Expensify/App/issues/41613
PROPOSAL: https://github.com/Expensify/App/issues/41613#issuecomment-2094058984

### Tests

Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests

Same as QA Steps

### QA Steps

Prerequisite: approval enabled
1. As user A, submit 2 expenses to B's workspace
2. As user A, hold one of the expenses
3. As user B, open the policy expense report
4. As User B, press approve button
5. As user B, verify the confirmation modal message shows as `Approve what's not on hold, or approve the entire report.` (unchanged)
6. As user A, hold all expenses
8. As user B, press approve button
9. As user B, verify the confirmation modal message shows as `These expenses are on hold. Do you want to approve anyway?`
10. As user A, delete one of the expenses
11. As user B, press approve button
12. As user B, verify the confirmation modal message shows as `This expense is on hold. Do you want to approve anyway?`

Prerequisite: approval disabled
1. Repeat steps 1-3 above
2. As user B, press pay button
3. As user B, verify the confirmation modal message shows as `Pay what's not on hold, or pay the entire report.`
4. As user A, hold all expenses
5. As user B, press pay button
6. As user B, verify the confirmation modal message shows as `These expenses are on hold. Do you want to pay anyway?`
7. As user A, delete one of the expenses
8. As user B, press pay button
9. As user B, verify the confirmation modal message shows as `This expense is on hold. Do you want to pay anyway?`

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

approval enabled
image

image

image

approval disabled
image

image

image

</details>

<details>
<summary>Android: mWeb Chrome</summary>

approval enabled
image

image

image

approval disabled
image

image

image

</details>

<details>
<summary>iOS: Native</summary>

approval enabled
image

image

image

approval disabled
image

image

image

</details>

<details>
<summary>iOS: mWeb Safari</summary>

approval enabled
image

image

image

approval disabled
image

image

image

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

approval enabled
image

image

image

approval disabled
image

image

image

</details>

<details>
<summary>MacOS: Desktop</summary>

approval enabled
image

image

image

approval disabled
image

image

image

</details>

### CODE REVIEW

**Comment by bernhardoj** [comment]
Here is how it looks with the new confirmation message for approval,
Screenshot 2024-05-29 at 13 15 41

But we still have a case for pay, here is how it currently looks,
Screenshot 2024-05-29 at 13 20 55

what should be the message for the pay case?

_it's currently possible to hold all expenses again after approving it_

@mananjadhav @laurenreidexpensify @jasperhuangg

**Comment by jasperhuangg** [comment]
@bernhardoj @mananjadhav I just updated the QA steps in the OP with accurate ones that have been checked, please use those to test the PR, thanks!

**Comment by bernhardoj** [comment]
@jasperhuangg I have a few questions:

1. How to hold a one-expense report? I don't see an option to hold it. (the hold option is only available in the transaction thread)
image

2. Does this mean the new message is only for one-expense report? If there are multiple expenses and all of them are on hold, will we use the old message?

**Comment by jasperhuangg** [comment]
@bernhardoj Clarifying in Slack, thanks for asking. Based on my understanding you should just be able to submit multiple expenses if we're trying to test holding expenses.

**Comment by jasperhuangg** [comment]
@bernhardoj I updated the testing steps with the expected behavior, let me know if you have any trouble.

**Comment by bernhardoj** [comment]
I think the test step is a little bit confusing because both users A and B are approving the report. 

> 7. As user B, approve the report
> 8. As user A, add more expenses to the expense report, hold one and approve the rest.
> 9. As user B, press the pay button

Also, we can't add more expense to an approved/submitted report.
image

But I got the idea to hold one expense report.

> 2. Does this mean the new message is only for one-expense report? If there are multiple expenses and all of them are on hold, will we use the old message?

And do you know what we should do about this question?

I think it doesn't make sense to use the current message for a report that has all expenses on hold.
image

**Comment by jasperhuangg** [comment]
@bernhardoj That's a good point, I think we should do the following:

If approving a report that has both held/unheld expenses:
`Approve what's not on hold, or approve the entire report.`

If approving a report that has only held expenses:
`All expenses on this report are on hold. Do you want to unhold them and approve?`

**Comment by jasperhuangg** [comment]
@bernhardoj If the one-expense report is ready to paid, shouldn't the expenses on it be approved already (and not held)?

**Comment by bernhardoj** [comment]
Yes, but I can hold an approved request. I don't know if that's expected though. No error from BE when I tested it last time. If that's not expected, we can update the test step to turn off the approval setting, so the next step will be pay and not approve.

**Comment by mananjadhav** [comment]
> we can update the test step to turn off the approval setting, so the next step will be pay and not approve.

This seems good, but any specific reason why BE doesn't throw the error @jasperhuangg ?

**Comment by jasperhuangg** [comment]
I think we should still be able to hold approved requests based on what I'm seeing. I think updating the testing step to do that should be fine. Thanks for investigating. @bernhardoj

**Comment by bernhardoj** [comment]
Great! I think the last thing left is the case for more than 1 expense all on hold. I see that you previously answered it from the email, but looks like it's already been deleted.

image

@jasperhuangg Are we waiting for the team's confirmation for the wording/copy or is it an unintentional deletion?

**Comment by jasperhuangg** [comment]
@bernhardoj Ah yes, I deleted it on purpose, I'm waiting for confirmation on what the correct wording should be, thanks.

**Comment by jasperhuangg** [comment]
@bernhardoj Yeah, so we don't want any change to the existing modal copy in production when approving a report with a mix of held/unheld expenses.

We only want to update the copy for reports where all expenses are held.

**Comment by bernhardoj** [comment]
@jasperhuangg Hmm, I think I'm a bit confused here 😅. If there is held and unheld expense, the copy won't change. 

I think what we want to know is the copy for 
1. when there is only one expense and it's on hold and,
2. there are multiple expenses and all of them are on hold.

Should it be:
1. This expense is on hold. Do you want to approve anyway? (from the test step)
2. All expenses on this report are on hold. Do you want to unhold them and approve? (from https://github.com/Expensify/App/issues/41613#issuecomment-2129858660)

Or should we use copy 2 for both cases?

**Comment by jasperhuangg** [comment]
Use copy 2 for both cases!

**Comment by bernhardoj** [comment]
Great, I updated the test step to use back my test step since it's easier to test multiple expenses.

But I still need a copy for the `pay` case. From the previous test step you gave, the copy is
`This expense is on hold. Do you want to pay anyway?`

but we use this for approve
`All expenses on this report are on hold. Do you want to unhold them and approve?`.

should I just change `approve` to `pay`?

I will ask for a translation after this.

**Comment by jasperhuangg** [comment]
@bernhardoj I think that's fine. Thanks for pushing this forward!

**Comment by mananjadhav** [comment]
@bernhardoj Can you resolve the conflicts? and did you post a message about the translation?

**Comment by bernhardoj** [comment]
Conflicts solved. Asked for translation confirmation [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1718082290009629)

**Comment by mananjadhav** [comment]
@jasperhuangg Could you help with the translations here ([thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1718196783967369?thread_ts=1718082290.009629&cid=C01GTK53T8Q))?

**Comment by jasperhuangg** [comment]
@bernhardoj We realized the translations we've been talking about are incorrect.

Can you update the text to say:
This expense is on hold. Do you want to approve anyway?
 This expense is on hold. Do you want to pay anyway?

In the case where there is just 1 expense on the report? In all other cases we should use the existing copy. Sorry for the confusion, and thank you for your patience.

**Comment by bernhardoj** [comment]
Ah okay, so to confirm,

A single expense on hold: `This expense is on hold. Do you want to approve anyway?`
Some expenses are on hold, some expenses are non-hold: `Approve what's not on hold, or approve the entire report.`  unchanged
Multiple expenses all are on hold: `Approve what's not on hold, or approve the entire report.` unchanged

I still think the multi expenses all on hold doesn't looks good though (which leads to the same 2nd question [here](https://github.com/Expensify/App/pull/42736#issuecomment-2141153575) 😅), but is the above correct?

**Comment by jasperhuangg** [comment]
@bernhardoj Will ask for clarification–I'm honestly kinda confused now as to what we want 😓 Thanks for your patience

**Comment by jasperhuangg** [comment]
@bernhardoj I think you were right, the existing copy is pretty confusing. Here's what we want:

One expense
- On hold - use one of the two modals below, depending:
    - Confirm approval amount
        - This expense is on hold. Do you want to approve anyway?
    - Confirm payment amount
        - This expense is on hold. Do you want to pay anyway?
- Not on hold - skip modal

Multiple expenses
- All on hold - use one of the two modals below, depending:
    - Confirm approval amount
        - These expenses are on hold. Do you want to approve anyway?
    - Confirm payment amount
        - These expenses are on hold. Do you want to pay anyway?
- Some on hold - use modal:
    - Confirm approval amount
        - Approve what's not on hold, or approve the entire report.
    - Confirm payment amount
        - Pay what's not on hold, or pay the entire report.
- None on hold - skip modal

**Comment by bernhardoj** [comment]
@jasperhuangg Great! Updated the test step and SS. Spanish translation left.

> Confirm payment amount
> Pay what's not on hold, or pay the entire report.

Btw, do we really want to change this? The current copy is this.
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/languages/en.ts#L770

**Comment by jasperhuangg** [comment]
@bernhardoj Yeah I think we should change that since that's what the copy-check was.

**Comment by bernhardoj** [comment]
@jasperhuangg Thanks, updated!

Next, can I get the Spanish translation?

**Comment by jasperhuangg** [comment]
@bernhardoj Ah, my bad–we had some discussion on your Spanish translation thread and I think people assumed that they were already handled, I'll send an update.

In the meantime you have Typescript issues!

**Comment by jasperhuangg** [comment]
@bernhardoj 

en: This expense is on hold. Do you want to approve anyway?
es: Este gasto está bloqueado. ¿Quieres aprobar de todos modos?
en: This expense is on hold. Do you want to pay anyway?
es: Este gasto está bloqueado. ¿Quieres pagar de todos modos?

**Comment by bernhardoj** [comment]
@jasperhuangg Thanks! What about the multiple expenses:

These expenses are on hold. Do you want to approve anyway?
These expenses are on hold. Do you want to pay anyway?
Pay what's not on hold, or pay the entire report. (this one is previously "Pay what's not on hold, or pay all out-of-pocket spend.")

> In the meantime you have Typescript issues!

Yep, it's the missing translation 😅

**Comment by mananjadhav** [comment]
I've also reviewed the PR, just waiting on the final Spanish translation to test and work on the checklist.

**Comment by mananjadhav** [comment]
quick bump @jasperhuangg

**Comment by jasperhuangg** [comment]
Ah got it, still waiting on people to respond about those other translations, will get back to you as soon as I hear back. I appreciate your patience and persistence with this PR!

**Comment by jasperhuangg** [comment]
en: These expenses are on hold. Do you want to approve anyway?
es: Estos gastos están bloqueados. ¿Quieres aprobarlos de todos modos?
en: These expenses are on hold. Do you want to pay anyway?
es: Este gasto está bloqueado. ¿Quieres pagarlo de todos modos?

en: Pay what is not on hold, or or pay the entire report.
es: Paga lo que no está bloqueado, o paga el informe completo.

@bernhardoj Thank you for your patience 🙇

**Comment by bernhardoj** [comment]
@jasperhuangg Thanks! Updated. cc: @mananjadhav 

But I see that both `These expenses are on hold` and `This expense is on hold` for the pay case are translated into the same word.
en: These expenses are on hold. Do you want to pay anyway?
es: Este gasto está bloqueado. ¿Quieres pagarlo de todos modos?
en: This expense is on hold. Do you want to pay anyway?
es: Este gasto está bloqueado. ¿Quieres pagar de todos modos?

But in approve case, they are different.
en: These expenses are on hold. Do you want to approve anyway?
es: Estos gastos están bloqueados. ¿Quieres aprobarlos de todos modos?
en: This expense is on hold. Do you want to approve anyway?
es: Este gasto está bloqueado. ¿Quieres aprobar de todos modos?

Is that expected?

**Comment by mananjadhav** [comment]
Yeah looks like an oversight. @bernhardoj Can you correct and raise the fix? We can start with the review and if it's a small change we can fix it on Monday. I am hoping we should be able to finish the checklist before Monday. wdyt?

**Comment by bernhardoj** [comment]
@mananjadhav updated.

**Comment by jasperhuangg** [comment]
In the thread that I asked about the translations in they indicated that only the "Do you want to approve anyway" case should have `Estos gastos están bloqueados`. Not sure if it is an oversight. @mananjadhav are you sure about that?

**Comment by jasperhuangg** [comment]
@mananjadhav Ah okay yup we should have the plural `Estos gastos están bloqueados` for both translations, just got confirmation.

**Review by jasperhuangg — DISMISSED** [review]

**Comment by mananjadhav** [comment]
> @mananjadhav Ah okay yup we should have the plural `Estos gastos están bloqueados` for both translations, just got confirmation.

Yeah that's what @bernhardoj and I meant. Working on the checklist now.

**Comment by jasperhuangg** [comment]
@mananjadhav Any updates on that checklist?

**Comment by mananjadhav** [comment]
@jasperhuangg Left with final testing. The rest of the items of the checklist are fine, so I'll finish it once the QA is done.

**Comment by trjExpensify** [comment]
We good here?

**Comment by jasperhuangg** [comment]
@trjExpensify Still waiting on @mananjadhav to post the updated checklist.

It looks like we ran into some conflicts too @bernhardoj, sorry that happened!

**Comment by mananjadhav** [comment]
Yeah I was able to test this on Web. I'll have the checklist ready by in a few hours/tomorrow.

**Comment by bernhardoj** [comment]
Conflicts fixed

**Comment by jasperhuangg** [comment]
@mananjadhav Can we please get that checklist soon 🙇 we're running into conflicts almost every day

**Comment by mananjadhav** [comment]
Yes 😞  I am just finishing one PR and getting to this next! Sorry for the delay.

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android: Native
    - [ ] Android: mWeb Chrome
    - [ ] iOS: Native
    - [ ] iOS: mWeb Safari
    - [ ] MacOS: Chrome / Safari
    - [ ] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

android-approve-name


</details>

<details>
<summary>Android: mWeb Chrome</summary>

mweb-chrome-approve-some

</details>

<details>
<summary>iOS: Native</summary>

ios-approve-some

</details>

<details>
<summary>iOS: mWeb Safari</summary>

mweb-safari-approve-some

</details>


<details>
<summary>MacOS: Chrome / Safari</summary>

web-approve-some-es

web-approve-some

</details>

<details>
<summary>MacOS: Desktop</summary>

desktop-approve-some

</details>

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
Just finished with the checklist, took a bit longer because had to test several test cases.

**Review by mananjadhav — APPROVED** [review]

**Comment by bernhardoj** [comment]
Conflicts fixed

**Review by jasperhuangg — APPROVED** [review]
Thank you guys for your patience and perseverance with this one!

**Pull request merged**
