### PR TITLE
Add staging deploy to web and desktop

### PR DESCRIPTION
**Pull request by AndrewGable**
Please review @roryabraham 

### Details
On hold for https://github.com/Expensify/Expensify/issues/155119

Adds staging deploy environments for staging for both web and desktop. This does not yet deploy anything different to those environments, but is a first step 👣 

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/155195
Fixes https://github.com/Expensify/Expensify/issues/155196

### Tests
1. Merge this PR
2. Go to staging.expensify.cash and verify it loads 👍

### CODE REVIEW

**Review by roryabraham — CHANGES_REQUESTED** [review]
These steps will run sequentially, so I don't think we want to do both a `production` and a `staging` build every time. Instead, we should:

1) Add a step before these that determines whether we should deploy to production or staging, and [save the result in the runner's environment](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files). For now, that step would always just end in a result of "deploy to production"
2) Use that value in deployment

### Desktop
```yaml
- name: Determine environment     # We'll eventually have more logic in this step
  run: echo "SHOULD_DEPLOY_PRODUCTION=true >> $GITHUB_ENV
  
- name: Build staging desktop app
  run: SHOULD_DEPLOY_PRODUCTION=${{ env.SHOULD_DEPLOY_PRODUCTION }} npm run desktop-build -- --publish always -c.afterSign=desktop/notarize.js 
  env:
    CSC_LINK: ${{ secrets.CSC_LINK }}
    CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    APPLE_ID: ${{ secrets.APPLE_ID }}
    APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

### Web

```yaml
- name: Determine environment     # We'll eventually have more logic in this step
  run: |
      echo "SHOULD_DEPLOY_PRODUCTION=true >> $GITHUB_ENV
      if [ $SHOULD_DEPLOY_PRODUCTION ]; then S3_BUCKET="s3://expensify.cash"; else S3_BUCKET="s3://staging.expensify.cash"; fi
      echo "$S3_BUCKET" >> $GITHUB_ENV
  
- name: Deploy staging to S3
  run: aws s3 cp --recursive --acl public-read $GITHUB_WORKSPACE/dist ${{ env.S3_BUCKET }}
```

**Comment by AndrewGable** [comment]
This logic makes total sense to me, however, I was prioritizing getting staging up and running ASAP. While I agree it's not the most elegant for the long term, I thought it was fine to have staging mirror production for a while, then add this logic when we know that logic is in place. Does that make sense?

**Comment by roryabraham** [comment]
Sure, we can do that as a follow-up PR.

**Review by roryabraham — APPROVED** [review]

**Comment by roryabraham** [comment]
Once this is off hold we can test a deploy to the new S3 bucket

**Comment by AndrewGable** [comment]
Taking off hold, @rafecolton is going to merge when AWS is configured.

**Review by rafecolton — APPROVED** [review]
Everything is set up, let's see if it works!

**Pull request merged**
