### PR TITLE
Patch for WebView crash v2

### PR DESCRIPTION
**Pull request by aldo-expensify**
Patches:

- `patches/react-native+0.73.4+015+fixIOSWebViewCrash.patch`: Created from https://github.com/facebook/react-native/pull/43088. This patch won't be needed when we upgrade `react-native` to >= 0.73.5
- `patches/@rnmapbox+maps+10.1.11.patch`: Patch created by @staszekscp [here](https://github.com/Expensify/App/pull/40982), there is no PR as far as I know. To check if the patch is still needed you need to check if the renaming of the file extension is still needed or not.

### Details
Trying adding the patches from this PR again: https://github.com/Expensify/App/pull/40527, but trying to reduce the changes to a minimum

### Fixed Issues
$ https://github.com/Expensify/App/issues/40517
PROPOSAL:

### Tests

**In Web/Desktop:**

1. Create NewDot account (must be in beta `accountingOnNewExpensify`)
2. Create Workspace
3. Go to the Workspace's Settings > More Features
4. Enable "Accounting"
5. Go to Workspace's Settings > Accounting
6. Click "Set Up" in the quickbooks online menu entry
    image
8. Verify a browser tabs open with the quickbooks authentication page
9. Close the tab
10. Verify that NewDot is still working and no crash happened

**Android native / IOS native:**

1. Create NewDot account (must be in beta `accountingOnNewExpensify`)
2. Create Workspace
3. Go to the Workspace's Settings > More Features
4. Enable "Accounting"
5. Go to Workspace's Settings > Accounting
6. Click "Set Up" in the quickbooks online menu entry
    image
8. Verify that the QBO authentication page opens inside NewDot
9. Swipe back (or press back button)
11. Verify that the QBO authentication page closes, and that the App is still working and no crash happened

- [ ] Verify that no errors appear in the JS console

### QA Steps

**In Web/Desktop:**

1. Create NewDot account (must be in beta `accountingOnNewExpensify`)
2. Create Workspace
3. Go to the Workspace's Settings > More Features
4. Enable "Accounting"
5. Go to Workspace's Settings > Accounting
6. Click "Set Up" in the quickbooks online menu entry
    image
8. Verify a browser tabs open with the quickbooks authentication page
9. Close the tab
10. Verify that NewDot is still working and no crash happened

**Android native / IOS native:**

1. Create NewDot account (must be in beta `accountingOnNewExpensify`)
2. Create Workspace
3. Go to the Workspace's Settings > More Features
4. Enable "Accounting"
5. Go to Workspace's Settings > Accounting
6. Click "Set Up" in the quickbooks online menu entry
    image
8. Verify that the QBO authentication page opens inside NewDot
9. Swipe back (or press back button)
11. Verify that the QBO authentication page closes, and that the App is still working and no crash happened

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by aldo-expensify** [comment]
@rojiphil do you have an IOS device to test the AdHoc build? 🙏

**Comment by aldo-expensify** [comment]
Going to make this ready for review. Tom tested here in IOS and it didn't crash: https://expensify.slack.com/archives/C036QM0SLJK/p1714094451031619?thread_ts=1713799261.297609&cid=C036QM0SLJK

**Comment by aldo-expensify** [comment]
cc @roryabraham in case you see something wrong here 🙇

**Comment by aldo-expensify** [comment]
Oops wrong button

**Comment by rojiphil** [comment]
> do you have an IOS device to test the AdHoc build?

@aldo-expensify  I do not have an IOS device. Since we already tested on an iOS device [here](https://github.com/Expensify/App/pull/41023#issuecomment-2078464680), are you still looking for a C+ with an IOS device? If so, we will have to reassign. On the other hand, I can carry out the tests on an iOS simulator + other platforms including on an Android device. Would this work?

**Comment by rojiphil** [comment]
@aldo-expensify And a small request here. Please add roji@owesee.com and roji+test292@owesee.com accounts to the `accountingOnNewExpensify` beta. Thanks

**Comment by aldo-expensify** [comment]
> @aldo-expensify And a small request here. Please add [roji@owesee.com](https://www.expensify.com/_support/?supportEmail=roji%40owesee.com&comment=better%20supportal%20issue%20nubmer%3A%2041023&location=_support/) and [roji+test292@owesee.com](https://www.expensify.com/_support/?supportEmail=roji%2Btest292%40owesee.com&comment=better%20supportal%20issue%20nubmer%3A%2041023&location=_support/) accounts to the `accountingOnNewExpensify` beta. Thanks

Done

> > do you have an IOS device to test the AdHoc build?
> 
> @aldo-expensify I do not have an IOS device. Since we already tested on an iOS device [here](https://github.com/Expensify/App/pull/41023#issuecomment-2078464680), are you still looking for a C+ with an IOS device? If so, we will have to reassign. On the other hand, I can carry out the tests on an iOS simulator + other platforms including on an Android device. Would this work?

I think it is fine if you carry out the other platforms and IOS simulator

**Review by staszekscp — APPROVED** [review]

**Comment by staszekscp** [comment]
Nice job with the cleanup! I've also opened a [PR to `react-native-live-markdown`](https://github.com/Expensify/react-native-live-markdown/pull/331/files) so we can remove one of the patches soon 😄

**Comment by aldo-expensify** [comment]
> Nice job with the cleanup! I've also opened a [PR to `react-native-live-markdown`](https://github.com/Expensify/react-native-live-markdown/pull/331/files) so we can remove one of the patches soon 😄

Great, thanks again for all the help!

**Review by rojiphil — COMMENTED** [review]
Patch file for `react-native-live-markdown` was generated for 0.1.62 whereas the latest one in use is 0.1.64. Can we not fix this to avoid the warning? 
Here is the warning message.

Screenshot 2024-04-26 at 3 00 29 PM

**Comment by rojiphil** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [ ] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/3004659/6b446140-7978-4ef8-abb7-66134f22999f

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/3004659/e0b202d3-7595-4c38-bbd6-814b36476f3e

</details>

<details>
<summary>iOS: Native</summary>

TODO

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/3004659/c84f9f2c-6f85-4b6c-9a27-bd8704264ed9

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/3004659/294f2e33-24fd-4d2d-bd85-bc08cf70ba44

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/3004659/795ad346-91b1-46aa-b403-e9e0907d4273

</details>

**Comment by aldo-expensify** [comment]
> Patch file for `react-native-live-markdown` was generated for 0.1.62 whereas the latest one in use is 0.1.64. Can we not fix this to avoid the warning?

Updated. I confirmed that we still need the patch for 0.1.64

**Comment by aldo-expensify** [comment]
I launched another adhoc build to confirm that this still build fine after pulling from `main`

**Comment by roryabraham** [comment]
@aldo-expensify please include links to the upstream PRs / commits for each of these patches in the PR description so that we can know when we can remove it later.

**Comment by aldo-expensify** [comment]
Because it was requested [here](https://expensify.slack.com/archives/C03TQ48KC/p1714159854490759?thread_ts=1714158412.496539&cid=C03TQ48KC):

- Removed patch patches/https://github.com/Expensify+react-native-live-markdown+0.1.64.patch
- Upgraded react-native-live-markdown to 0.1.69

**Comment by aldo-expensify** [comment]
> @aldo-expensify please include links to the upstream PRs / commits for each of these patches in the PR description so that we can know when we can remove it later.

Added description for patches

**Comment by aldo-expensify** [comment]
huh Snyk failed because of `Failed to parse ios/Podfile.lock as valid YAML` ???

**Comment by rojiphil** [comment]
@aldo-expensify `ios native` build works fine for me. But `android native` build fails for me. It seems like `@fullstory/react-native` package is required but not present. It looks like some recent change introduced this. 
Here is the failure message while running `npm run android`. 

Screenshot 2024-04-27 at 5 25 26 PM

**Comment by rojiphil** [comment]
@aldo-expensify After running `npm run pod-install`, I also notice that `podfile.lock` does not include `fullstory_react-native` dependency. Could this be related to the `android native` issue? 

Screenshot 2024-04-27 at 10 00 35 AM

**Comment by trjExpensify** [comment]
Do we need to move reviewers/comments over to: https://github.com/Expensify/App/pull/41117?

**Comment by aldo-expensify** [comment]
@rojiphil can you re-approve? 🙏

**Comment by trjExpensify** [comment]
Bump @rojiphil on the re-approval, please.

**Comment by rojiphil** [comment]
Reviewing now

**Review by rojiphil — APPROVED** [review]
The App does not crash on iOS native (built using `npm run iOS` and tested on simulator).  Note: I have not tested on real device as I do not have one.
For all other platforms, the tests were performed based on the ad hoc build.
Android platform tests were carried out on real device
Works well. LGTM

Running android native build using `npm run android` still fails for me as mentioned [here](https://github.com/Expensify/App/pull/41023#issuecomment-2081052292). But this also fails on the latest main. So, have raised the issue [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1714475402105779)

**Review by Julesssss — COMMENTED** [review]
Hey @aldo-expensify. I was trying to verify iOS on a physical device, but after granting the beta flag and re-authenticating I'm still not seeing the accounting option 😕 

Any idea what I missed?

- Created public domain account 
- Created workspace
- Granted beta
- Authenticated on iOS AdHoc build
- No accounting option

Screenshot 2024-04-30 at 13 59 32

Screenshot 2024-04-30 at 13 57 40

**Comment by trjExpensify** [comment]
@Julesssss I think it can take an hour or so for the beta to be recognised. Is this build up [here](https://github.com/Expensify/App/pull/41023#issuecomment-2083580938) good to go or do we need a new one? I'm happy to give it a whirl on an iOS device. Alternatively, I can spin you up an email address on my private domain that has access and ship you the magic code to sign-in when received.

**Review by Julesssss — APPROVED** [review]
Verified physical iOS with thanks to Tom

Screenshot 2024-04-30 at 14 12 30

**Pull request merged**
