### PR TITLE
26121-remove-domain-name

### PR DESCRIPTION
**Pull request by pradeepmdk**
### Fixed Issues

$ https://github.com/Expensify/App/issues/26121
PROPOSAL: https://github.com/Expensify/App/issues/26121#issuecomment-1696726665

### Tests

For WorkSpace
1. Open https://staging.new.expensify.com/
2. Log in with any of your logins
3. Create a new workspace or open an existing one
4. Open the workspace & click on "Members"
5. Click on 'Invite' button
6. Search for an invalid phone number (+2523234211)
7. Select the user > click on "Next" > click on "Invite"
8. Select the user & click on the "Remove" button
9. Click on 'Invite' button

For Request Money
1. Open the Request money from the fab menu
2. go to offline
3. Create Request money with invalid phone number (either manual or distance)
4. Verify the displayname without the domain name 

For Split bill
1. open the Split bill from the fab menu
2. go to offline
3. Create split money with invalid phone number  
4. Verify the displayname without the domain name 

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/16595846/5a6e25f7-9d7c-44c5-b47f-c7f94da145b7

https://github.com/Expensify/App/assets/16595846/8bec82e2-9d70-4e37-b603-989f50cc8220

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/16595846/a3e640ce-5110-4a8d-9911-9cd161e9a84a

https://github.com/Expensify/App/assets/16595846/a368789d-99c4-42d3-9ad6-1ea300cfab6c

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/16595846/c90364d1-4966-4e83-a577-9027dc260d56

https://github.com/Expensify/App/assets/16595846/fb8af7e3-4fa4-44c0-a32f-8941dc4ae946

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/16595846/78024266-2c14-45eb-99dd-c5afa886a360

https://github.com/Expensify/App/assets/16595846/6a255cbb-d32c-4c43-b498-74363054befb

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/16595846/9f044751-57c3-45ed-8ae3-2964c6f519e2

https://github.com/Expensify/App/assets/16595846/5d3519ef-acc7-4c2c-9bcf-89cd5bd29000

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/16595846/9ce52e46-632f-4bf2-93ef-278ea50266c9

https://github.com/Expensify/App/assets/16595846/53719789-0aa7-4362-a4ec-53ac7e4699f2

</details>

### CODE REVIEW

**Comment by mollfpr** [comment]
@pradeepmdk Could correctly link your proposal in the description? Thanks!

**Comment by mollfpr** [comment]
@pradeepmdk I'm proposing to update the test case to 3 parts, since you have fix all the optimistic data on invite member to workspace, request money, and split bill.

- Adding members to the workspace
- Create `Request money` and `Split bill` from the FAB button with an invalid phone number while offline and verify the display name in the report doesn't have the domain
Screenshot 2023-09-05 at 19 22 22

**Comment by pradeepmdk** [comment]
@mollfpr updated

**Review by mollfpr — APPROVED** [review]
LGTM and tests well 👍

**Review by Li357 — APPROVED** [review]

**Comment by Li357** [comment]
@mollfpr Are you able to merge main and retest this to confirm everything still works after the merge freeze?

**Comment by mollfpr** [comment]
@Li357 Sure!

**Comment by mollfpr** [comment]
@Li357 Tested on all platforms. It seems still looking good!

**Comment by kavimuru** [comment]
Issue #26121 still reproduced mweb and apps

**Comment by AndrewGable** [comment]
It seems like the @expensify.sms appears in split bill scenario even after this fix, making the QA fail. I believe we should revert in this case in order to get the deploy out.

**Comment by mollfpr** [comment]
@pradeepmdk Could you check the above issue?

**Comment by pradeepmdk** [comment]
> @pradeepmdk Could you check the above issue?

checking now

**Comment by pradeepmdk** [comment]
@AndrewGable @mollfpr I am not able to reproduce this on a split bill scenario, could you share some video/steps to reproduce it?

Note: If you have old data with the domain that will still show with the domain name only. because once you log out and log in those data will removed from Onyx Those are invalid data only so not storing in the backend.

Here we are fixing only newly added data that should not be stored with the domain name.

**Comment by mollfpr** [comment]
I just tested it again with `v1.3.68-0` and could reproduce it. In every case, we haven't made it clear in the test step to use the new invalid phone number. @kavimuru Could you share a video of the failing test?

<details>
<summary>Android</summary>

[untitled.webm](https://github.com/Expensify/App/assets/25520267/a0314908-277c-4062-b0fc-23b68f23e242)

</details>

<details>
<summary>mWeb/Chrome</summary>

[untitled 2.webm](https://github.com/Expensify/App/assets/25520267/c736dfca-54b9-4560-9b36-39c472d1e2e8)

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/25520267/08d74b48-e5f1-4e05-96f0-9c93ed9bd5de

</details>

<details>
<summary>mWeb/Safari</summary>



https://github.com/Expensify/App/assets/25520267/feb810e7-255a-4cd1-8da2-be07d3ec6219

</details>

**Comment by pradeepmdk** [comment]
@kavimuru let me know which version tested the video

**Comment by kavimuru** [comment]
@pradeepmdk Tested on 1.3.68-9

**Comment by pradeepmdk** [comment]
> 🚀 [Deployed](https://github.com/Expensify/App/actions/runs/6152911708) to staging by https://github.com/Li357 in version: 1.3.68-0 🚀
> 
> platform	result
> 🤖 android 🤖	success ✅
> 🖥 desktop 🖥	success ✅
> 🍎 iOS 🍎	success ✅
> 🕸 web 🕸	success ✅

> @pradeepmdk Tested on 1.3.68-9

I am not sure if this version `1.3.68-9` has our code or not. because our code is reverted now. 

could you please try to check out this branch for testing?

**Comment by AndrewGable** [comment]
Deployed in [`1.3.68-0`](https://github.com/Expensify/App/pull/26638#issuecomment-1714782398) it was reverted in [`1.3.68-16`](https://github.com/Expensify/App/pull/27300#issuecomment-1716850424), the code was included in `1.3.68-9`.

**Comment by pradeepmdk** [comment]
@mollfpr @AndrewGable @kavimuru  I found this 
1) First we are going to create an invalid phone number on the workspace
2) Go offline
3) Then again go to request money instead of creating a new one. selecting the failed phone number one

fixed this scenario


https://github.com/Expensify/App/assets/16595846/06cb5c94-d995-4b07-94d1-952826c3fc49

**Pull request merged**
