### PR TITLE
[Refactor] Remove deprecated PersonalDetails.setPersonalDetails

### PR DESCRIPTION
**Pull request by fedirjh**
### Details

- Removed deprecated `PersonalDetails.setPersonalDetails`
- Use `PersonalDetails.updateAutomaticTimezone` to update timezone

### Fixed Issues

$ https://github.com/Expensify/App/issues/14961 
$ https://github.com/Expensify/App/issues/14961#issuecomment-1423346124

### Tests

1. Open the App in Web
2. Navigate to Settings > Profile > Timezone
3. Check  Automatically determine your location
4. Check your current Timezone is set
5. Open this file [AuthScreens.js](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.js#L56) and comment this line

https://github.com/Expensify/App/blob/49002ef6940995831ebd58cfefd3408c9ddcfc2b/src/libs/Navigation/AppNavigator/AuthScreens.js#L56

7. Set a custom timezone different than your time zone

```jsx
        // const currentTimezone = moment.tz.guess(true);
        const currentTimezone = 'Europe/London';
```

8. Navigate to Settings > Profile > Timezone
9. Confirm Timezone is updated to the custom timezone set in 7.

- [x] Verify that no errors appear in the JS console

### Offline tests

Repeat test steps

### QA Steps

Android

1. Update the timezone on the device ( Settings > General management > Date and time)
2. Select a custom timezone `Africa/Tripoli`
3. Open App
4. Navigate to Settings > Profile > Timezone
5. Confirm it's update to your current timezone.

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

Screenshot 2023-02-09 at 1 44 59 AM

</details>

<details>
<summary>Mobile Web - Chrome</summary>

Screenshot 2023-02-09 at 2 04 59 AM

</details>

<details>
<summary>Mobile Web - Safari</summary>

Screenshot 2023-02-09 at 1 49 28 AM

</details>

<details>
<summary>Desktop</summary>

Screenshot 2023-02-09 at 1 57 59 AM

</details>

<details>
<summary>iOS</summary>

Screenshot 2023-02-09 at 1 46 54 AM

</details>

<details>
<summary>Android</summary>

Screenshot_1675904769

</details>

### CODE REVIEW

**Comment by sobitneupane** [comment]
@fedirjh 

QA Steps should have steps to test on staging and production.
> [ ] I added steps for Staging and/or Production testing in the QA steps section

**Comment by sobitneupane** [comment]
@fedirjh On Android, IOS and mWeb/Chrome, When I toggle Automatic Timezone, it automatically toggles 2-3 times. Is it reproducible for you as well?

https://user-images.githubusercontent.com/25876548/217807882-3d85d34a-6ffb-480a-93e9-d6aa4ec2b11b.mov


https://user-images.githubusercontent.com/25876548/217810208-ac6ec2de-c430-400c-89f5-06e991210065.mov

**Comment by sobitneupane** [comment]
@fedirjh I cannot reproduce it on staging. I can reproduce it only in this PR.

**Comment by sobitneupane** [comment]
@fedirjh I understand your explanation. But In the [video](https://github.com/Expensify/App/pull/14979#issuecomment-1424110067), you can notice that timezones are different on web ("Asia/Kathmandu") and iPhone ("Asia/Katmandu").

I am pretty sure that [the bug](https://github.com/Expensify/App/pull/14979#issuecomment-1424110067) I reported has something to do with the current change because I can reproduce this issue constantly in this PR but not in main dev or staging.

My best guess is the difference in implementation of `PersonalDetails.updateAutomaticTimezone` and `PersonalDetails.setPersonalDetails`.

The other thing that I notice is that even when I have selected "Europe/London" as timezone (manually) and set my automatic timezone to "Europe/London". `timezone.selected` has 'Asia/Katmandu' as the value. Shouldn't it be "Europe/London" as it is the value manually selected from timezone list?

**Comment by puneetlath** [comment]
>updateAutomaticTimezone is using pusher to notify other devices about the changes, So if we have 2 devices with different timezones , then every device will trigger a change to the timezone and once other device is notified then it will trigger another change causing an infinity loop of updates to timezone.

I'm not quite sure I follow this. Specifically this part: 

>and once other device is notified then it will trigger another change causing an infinity loop of updates to timezone.

Why does getting notified trigger a change that causes more notifications to happen?

**Comment by puneetlath** [comment]
Thanks for the bump. This is the part that I'm still a little confused about: 

>Device 2 receives the new updated timezone . And since the new updated timezone is different than current timezone , Device 2 will trigger a new request to update timezone ...

Why does receiving a new timezone from pusher cause us to call the API? I would think that rather than creating an endpoint to update the timezone without pushing out to clients, the solution would be that when we receive a timezone update from pusher, we just store that new timezone in Onyx without calling the API. 

How do other inputs handle this? For example, if I update my display name, I assume that update gets pushed out to other devices. And that they don't trigger an API call when they receive the updated display name. How do those parts of the product handle it?

**Comment by sobitneupane** [comment]
@fedirjh Can you please merge the branch with main.

**Review by sobitneupane — COMMENTED** [review]
### Screenshots/Videos
<details>
<summary>Web</summary>


https://user-images.githubusercontent.com/25876548/219572542-740e5df5-e840-49bd-9ad2-38abcf6d7e6c.mov


</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/25876548/219572832-a6b2835e-f958-4363-9fa8-a383528635e2.mov



</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/25876548/219572795-e705be42-c59d-4b2f-9832-00f05fcc4fcc.mov



</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/25876548/219572565-f5b1bbcb-a375-4d14-ae4f-cbbbca6c2d9c.mov



</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/25876548/219589278-75f9eff1-1446-4726-bc6b-5f003911501b.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/25876548/219589354-a0fdd16e-f16f-4463-bc02-977900373105.mov

</details>

**Review by sobitneupane — COMMENTED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

**Comment by puneetlath** [comment]
@fedirjh for the QA steps, could they just update the timezone on their device? Would that work instead of needing to manually change the value in JS?

**Comment by puneetlath** [comment]
@sobitneupane just wanted to double-check whether you've had a chance to test on all platforms and whether your review is complete.

**Review by sobitneupane — DISMISSED** [review]
Changes test well..

cc: @puneetlath

**Review by puneetlath — APPROVED** [review]

**Review by puneetlath — CHANGES_REQUESTED** [review]

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
