### PR TITLE
Rename route so that we expect traditional query paramters

### PR DESCRIPTION
**Pull request by TomatoToaster**
@cead22, please review

All we need to do here is change the route and the query params pulled from here are expected to come after `?`.

These lines essentially work the same, it just won't look inbetween the slashes for the params:
https://github.com/Expensify/App/blob/269697b67f504243137637c72b5b8102ae01335a/src/pages/LogInWithShortLivedTokenPage.js#L51-L54

### Details
Discussion from here: https://expensify.slack.com/archives/C020EPP9B9A/p1632347607474000
related to this PR: https://github.com/Expensify/Web-Expensify/pull/31996
and this issue: https://github.com/Expensify/Expensify/issues/177739

### QA Steps
Same as here: https://github.com/Expensify/App/pull/5396, but now it should actually work.
@MitchExpensify and @kevinksullivan will be testing this so QA team can skip over this one 👍🏾 

Flow 1: Unvalidated new accounts
1. Create a new account in OldDot that has access to the freePlan beta.
2. Go to settings -> policy -> group and select the free plan here:
image

3. Verify that a new tab opens and you are logged into NewDot and you are seeing the Workspace Settings page for a newly created Workspace:
image
4. Wait a minute
5. Do any action (like add a comment)
6. Check you are not logged out

Flow 2: Existing accounts
1. Log into an account on NewDot Expensify, create a Workspace if you don't already have one using the `+` on the bottom right.
2. Log out of NewDot and then log into that same account on OldDot and go to Settings -> Policy and find your Workspace there. It should have a card icon like these:
image
3. Click on its name and verify it opens a new tab, automatically logs you in, and brings you to the workspace settings page:
image
4. Wait a minute
5. Do any action (like add a comment)
6. Check you are not logged out

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

### Screenshots
N/A

### CODE REVIEW

**Comment by cead22** [comment]
> These lines essentially work the same, it just won't look inbetween parentheses for the params:

You mean slashes?

**Comment by TomatoToaster** [comment]
Ah sorry yes I meant in between the slashes 😄

**Review by cead22 — DISMISSED** [review]

**Review by thienlnam — DISMISSED** [review]

**Comment by TomatoToaster** [comment]
Could you review again @cead22 @thienlnam, I realized I should change this log line: https://github.com/Expensify/App/pull/5430/files#diff-c3d3bf8bc4056d8f2e8ff15f6d72d7e81656cd36c30a202a084c50dda1dff582L35

since the route changed and we still don't want to be storing the authToken in the log lines.

**Review by thienlnam — APPROVED** [review]

**Review by cead22 — APPROVED** [review]

**Comment by MitchExpensify** [comment]
- [x] Flow 1 on desktop

**Pull request merged**
