### PR TITLE
fix: display all LHN options in Import state mode

### PR DESCRIPTION
**Pull request by TMisiukiewicz**
### Explanation of Change

When using Import Onyx state, for some users LHN list does not display all items comparing to the original account. This is because `session` key in Onyx is not overriden, and if the `accountID` does not exist in the `personalDetails`, it doesn't display all the items. This PR overrides session and keeps the original one in a separate key until the app is not returned into the orignal state.

### Fixed Issues

$ https://github.com/Expensify/App/issues/53060
PROPOSAL:

### Tests

1. Go to Settings -> Troubleshoot
2. Export Onyx state
3. Log out and log into another account (ideally create an entirely new account)
4. Go to Settings -> Troubleshoot
5. Press Import Onyx state and select the exported file
6. Wait until the file loads
7. Verify the LHN have all the items comparing to the original account
- [x] Verify that no errors appear in the JS console

### Offline tests

n/a
### QA Steps

// TODO: These must be filled out, or the issue title must include "[No QA]."
Same as tests
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I used [JaimeGPT](https://chatgpt.com/g/g-2dgOQl5VM-english-to-spanish-translator-aka-jaimegpt) to get English > Spanish translation. I then posted it in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.ts or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I added [unit tests](https://github.com/Expensify/App/blob/main/tests/README.md) for any new feature or bug fix in this PR to help automatically prevent regressions in this user flow.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/f339087e-3439-4f7c-9007-1f499fef4afe

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/a9cf1a54-9d2a-4d56-87c8-b9a500c30b93

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/ae59f49f-a11b-4221-8432-93e84062fca9

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/cf5990f6-dbae-43cb-b672-207cc6caccea

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/884c0021-63a1-481d-ba8f-b1ccc4e4a82d

</details>

### CODE REVIEW

**Comment by TMisiukiewicz** [comment]
Opening as a draft first as it is blocked by https://github.com/Expensify/App/pull/53370

**Comment by TMisiukiewicz** [comment]
marking as ready for review as blocking PR is now merged

**Comment by jjcoffee** [comment]
@TMisiukiewicz Would it be worth adding a unit test for this? Also, would you mind adding a screenrecording for iOS Safari for completeness? :pray:

**Comment by jjcoffee** [comment]
`BUG?:` On Android native, the original session doesn't seem to fully restore (no profile picture and the profile data seems to be endlessly loading). 

Also, not sure if this is related to this PR but the import loader also stops too soon (when I switch to the LHN you can see that the import is still pulling in reports).

https://github.com/user-attachments/assets/dbeb5c2f-e0fd-4260-8d2c-a11cd6c50b27

**Review by jjcoffee — CHANGES_REQUESTED** [review]
Just a couple of comments to address.

**Comment by TMisiukiewicz** [comment]
> Would it be worth adding a unit test for this?

I added some unit tests for transforming imported data

> Also, would you mind adding a screenrecording for iOS Safari for completeness?

after updating Xcode I have problems with Safari on iOS and it crashes each time I try to open any website, already tried everything and couldn't find a solution for that 😕 I guess I have to wait for another update...

> Also, not sure if this is related to this PR but the import loader also stops too soon (when I switch to the LHN you can see that the import is still pulling in reports).

We have an umbrella issue for Import/Export fixes #53060 so I'll tackle it in a separate PR :)

I'm taking a look on the issue with user data not appearing now.

**Comment by TMisiukiewicz** [comment]
@jjcoffee ready for review ✅

**Review by jjcoffee — APPROVED** [review]
LGTM! Thanks for the quick fixes :pray:

**Review by Gonals — APPROVED** [review]

**Comment by luacmartins** [comment]
@TMisiukiewicz @jjcoffee @Gonals we ended up reverting this PR in an attempt to fix the issue that caused [#fireroom-2024-12-17-hybridapp-crash](https://expensify.enterprise.slack.com/archives/C085GD1ET8A). This PR was NOT the cause of the issue. I'm reverting the revert [here](https://github.com/Expensify/App/pull/54267)

**Pull request merged**
