### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Christinadobrzyn**
Revised some wording under the Finding Jobs section - specific to when a contributor qualifies for a bonus and how to submit a proposal.

### Details

- Revised some wording under the Note section here 
image

- Revised some wording in this section
image

### Fixed Issues
NA - no issues fixed, just some rewording in the above sections.

### Tests
NA

--->

### QA Steps

NA
--->

### Tested On

NA

### Screenshots

See Above

#### Web

NA

#### Mobile Web
 
NA

#### Desktop

NA

#### iOS

NA

#### Android

NA

### CODE REVIEW

**Comment by mountiny** [comment]
@Christinadobrzyn Hi! You will need to sign the CLA assistant so we can merge this.

Just copy this text:

I have read the CLA Document and I hereby sign the CLA

into a new comment here and post it. That should do it 😊

**Comment by mallenexpensify** [comment]
@Christinadobrzyn can you review the changes being made here to see if they're covered? 
https://github.com/Expensify/App/pull/4996
If not, can you update that issue with the suggested edits?

**Comment by Christinadobrzyn** [comment]
Ah yikes! Thanks for catching that Matt!

Yeah I don't want to disrupt the updates that Matt proposed. Because his pull request has many more updates and mine are very minor, I'm going to close this and post a new request once Matt's updates are complete.

**Comment by Christinadobrzyn** [comment]
Proposed these changes in Matts PR.

**Pull request closed without merging**
