### PR TITLE
[No QA] Fix crash

### PR DESCRIPTION
**Pull request by parasharrajat**
### Details

Follow up #4194

### Fixed Issues

$ Crash

### CODE REVIEW

**Comment by parasharrajat** [comment]
@MonilBhavsar This PR is very urgent and should go with #4194 on staging.

**Review by MonilBhavsar — APPROVED** [review]

**Comment by marcaaron** [comment]
@MonilBhavsar next time we need to CP something to staging I _think_ we can add the `CP Staging` label. This PR must be sent to staging.

**Comment by marcaaron** [comment]
Oh yeah but that label can only be applied before the merge happens.

**Comment by marcaaron** [comment]
JK this did not need to go to staging. Please ignore me.

**Comment by marcaaron** [comment]
Sorry @MonilBhavsar you did everything right 😄

**Pull request merged**
