### PR TITLE
[NoQA] feat: enable bridgeless

### PR DESCRIPTION
**Pull request by WoLewicki**
### Details

PR enabling bridgeless mode in the App. This PR can affects the App as a whole, so should require full regression testing.

PRs for introduced patches:
- [react-native-quick-sqlite](https://github.com/margelo/react-native-quick-sqlite): https://github.com/margelo/react-native-quick-sqlite/pull/64
- [react-native-pager-view](https://github.com/callstack/react-native-pager-view): https://github.com/callstack/react-native-pager-view/pull/881
- [react-native-firebase](https://github.com/invertase/react-native-firebase): We have a dirty workaround and Meta is already working on a better solution after I reported the problem to them. We won't make a PR with it since it's better to wait for it to be fixed in core. (issue in RN repo: https://github.com/facebook/react-native/issues/46779)
- [lottie-react-native](https://github.com/lottie-react-native/lottie-react-native): The changes are already available on rc:  https://github.com/lottie-react-native/lottie-react-native/pull/1160
- [rnmapbox/maps](https://github.com/rnmapbox/maps): https://github.com/rnmapbox/maps/pull/3656
- `react-native-modal` is not maintained from what I know and there are plans for providing our own, faster implementation of the library.
- [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera): https://github.com/mrousavy/react-native-vision-camera/pull/3240

### Fixed Issues

$ https://github.com/Expensify/App/issues/48163
PROPOSAL:

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by roryabraham** [comment]
> [react-native-keyboard-controller](https://github.com/kirillzyusko/react-native-keyboard-controller): The code is already there from 1.13.0 so it just needs a bump and we can remove the patch then.

So let's do this before we merge this PR, rather than creating a patch?

**Comment by roryabraham** [comment]
Created https://github.com/Expensify/App/issues/50253

**Comment by roryabraham** [comment]
> [react-native-firebase](https://github.com/invertase/react-native-firebase): We have a dirty workaround and Meta is already working on a better solution after I reported the problem to them. We won't make a PR with it since it's better to wait for it to be fixed in core.

Can you link to an upstream issue plz? 🙇🏼

**Comment by WoLewicki** [comment]
> Can you link to an upstream issue plz? 🙇🏼

Done.

**Comment by WoLewicki** [comment]
Seems like the event system on bridgeless mode on Android is far more strict regarding the event names. I'll fix those issues one by one, thanks @fedirjh !

**Comment by hannojg** [comment]
hey @WoLewicki will you open PR for all patches in the repositories upstream? I could help with the vision camera patch if you'd like to!

**Comment by mountiny** [comment]
@WoLewicki @hannojg yeah we should definitely try to follow up with those so we can keep track of all of the patches

**Comment by WoLewicki** [comment]
Yeah, sure I'll do. Thanks @hannojg , will ping you with any problems 😅  Also, is there a reason why you didn't modify all the needed places for `onClear` callback in RN core patch? I mean this one with the changes I needed to add: https://github.com/Expensify/App/pull/48160/files#diff-6220375a6bf22d664fd3eb2f7b023728fc40b97934d8731328aca0efadaee0b9. Or was it just an overlook?

**Comment by hannojg** [comment]
> Also, is there a reason why you didn't modify all the needed places for onClear callback in RN core patch?

Is it missing in some of the view components javascript spec? i might have skipped doing that, due to the behaviour of w/o bridgeless reading it from the view manager. If so, feel free to add it everywhere, yes!

**Comment by WoLewicki** [comment]
Ok, I did extend your patch already, thanks for clarification!

**Comment by WoLewicki** [comment]
@hannojg here is the PR to `react-native-vision-camera`: https://github.com/mrousavy/react-native-vision-camera/pull/3240. It works on old arch, and I tried to test it on new arch, but the example app does not compile there 😞

**Comment by hannojg** [comment]
Nw, i will test the PR (probably going to merge it and then add anything else necessary to make new arch work, so nw, i am gonna take it from there 😊 👍 )

**Comment by mountiny** [comment]
@WoLewicki how is this looking, should I create a new build and should Fedi do another round of testing or should we wait for a bit?

**Comment by WoLewicki** [comment]
Let's do another build @mountiny, it should be ready for testing.

**Comment by mountiny** [comment]
New build running [here](https://github.com/Expensify/App/actions/runs/11324264613)

**Comment by WoLewicki** [comment]
@fedirjh hmm I don't know where it can come from. But at the same time it does not change anything in how the app is working yes?

**Review by fedirjh — APPROVED** [review]
LGTM

**Comment by mountiny** [comment]
@WoLewicki Are there some performance benefits we could already measure and expect from this PR?

**Comment by WoLewicki** [comment]
I tried to look at the output of `Reassure Performance Tests` job from this PR but I cannot find the results for the most interesting metric for us, being some kind of app TTI. Should I look somewhere else for it? I would restrain from getting those locally.

**Comment by hannojg** [comment]
@mountiny we could run the e2e tests, that gives us many interesting numbers (TTIs, FPS, Memory, CPU etc)

**Comment by WoLewicki** [comment]
I wouldn't expect enormous gains, but some at least due to Static View Configs.

**Comment by mountiny** [comment]
I can run it now. Running here https://github.com/Expensify/App/actions/runs/11438433039

**Comment by WoLewicki** [comment]
Idk why but it seems to have failed @mountiny. I just merged the newest main, maybe it will work now?

**Comment by mountiny** [comment]
https://github.com/Expensify/App/actions/runs/11452730936

**Comment by hannojg** [comment]
Hm seems like the action to run the e2e tests for a PR is broken. We'll take a look!

**Comment by hannojg** [comment]
Okay, i just learned that a fix has landed on `main` an hour ago. can we merge main and test again please? 🙏 🥺

**Comment by WoLewicki** [comment]
I merged newest main, is it ready now?

**Comment by kirillzyusko** [comment]
> I merged newest main, is it ready now?

@WoLewicki yes, tests should pass now (well, apk-manipulation stages shouldn't fail). However I see that your PR contains "merge" commits. In https://github.com/Expensify/App/pull/48251 I re-worked pipeline, where baseline is taken as last merge commit (and at this point of time I'm not sure which merge commit will be taken in your PR - will it compare with `main` or with one of merge commits in PR). I think it's just better to run e2e pipeline and check that 👀 

Additionally (just want to warn in advance) I think tests will not pass, because they are currently broken on main as well (unfortunately). I'm currently working on this PR: https://github.com/Expensify/App/pull/51248
It works, but it's draft changes and I want to improve some aspects 🙂

If your PR can wait few days, then it would be simply amazing. Alternatively I can run tests locally to check performance benefits (since e2e pipeline is not fully working at the moment).

**Comment by WoLewicki** [comment]
I think having any feedback from this PR regarding performance is valuable, so even running it locally could be enough for now.

> If your PR can wait few days, then it would be simply amazing

I'd merge this PR nonetheless since it is the way forward either way and it would help me with pushing RN 0.76 and expo update. But I don't have a strong opinion on that tbh.

**Comment by kirillzyusko** [comment]
Okay @WoLewicki , give me ~1.5hr and I'll post my results here 😊

**Comment by kirillzyusko** [comment]
Okay, I can not run tests locally, because I'm getting:

```bash
2024-10-22 17:53:35.734  3133-3375  AndroidRuntime          com.expensify.chat.e2edelta          E  FATAL EXCEPTION: mqt_native_modules (Ask Gemini)
                                                                                                    Process: com.expensify.chat.e2edelta, PID: 3133
                                                                                                    com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: Could not enqueue microtask because they are disabled in this runtime, js engine: hermes, stack:
                                                                                                    setImmediate@1:527723
                                                                                                    setDriver@1:1660584
                                                                                                    LocalForage@1:1659118
                                                                                                    anonymous@1:1640327
                                                                                                    s@1:1635136
                                                                                                    e@1:1634879
                                                                                                    anonymous@1:1634781
                                                                                                    anonymous@1:1634629
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:1634119
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:1606115
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:1603178
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:1402528
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:206788
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:206603
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193495
                                                                                                    metroRequire@1:192777
                                                                                                    anonymous@1:204066
                                                                                                    loadModuleImplementation@1:194267
                                                                                                    guardedLoadModule@1:193452
                                                                                                    metroRequire@1:192777
                                                                                                    global@1:191704
                                                                                                    
                                                                                                    	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(SourceFile:76)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

I don't know why it happens 🤷‍♂️ I think we can proceed with merging and in a meantime I will try to fix e2e pipeline to make sure we can run tests independently to a local environment 👀

**Comment by kirillzyusko** [comment]
After merging these 3 PRs we can run test against the PR:
- https://github.com/Expensify/App/pull/51338 (1)
- https://github.com/Expensify/App/pull/51351 (2)
- https://github.com/Expensify/App/pull/51248 (3)

Highly desirable to merge https://github.com/Expensify/App/pull/51182 as well, but it can be optional

**Review by mountiny — APPROVED** [review]
Lets give this one a go

**Pull request merged**
