### PR TITLE
feat: support accountid attribute in user mentions

### PR DESCRIPTION
**Pull request by samh-nl**
### Details

This PR adds support for the account ID to be provided in user mentions.
Usage examples: `<mention-user accountID=12345678>@test@test.com</mention-user>` or `<mention-user accountID=12345678></mention-user>`

### Fixed Issues

$ https://github.com/Expensify/App/issues/26306
PROPOSAL: https://github.com/Expensify/App/issues/26306#issuecomment-1699474790

### Tests

Precondition: The API does not yet support this feature. To allow testing, we can perform a modification [here](https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/home/report/ReportActionItemFragment.js#L124) to automatically add the mentions to messages:
```js
const mentionsHTML = [
	'1. <mention-user accountID=12345678>@test@test.com</mention-user> (hidden user: unknown account ID)',
	'2. <mention-user accountID=YOUR OWN ID>@test@test.com</mention-user> (current user provided via account ID)',
	'3. <mention-user accountID=ACCOUNT ID>@test@test.com</mention-user> (other user provided via account ID)',
	'4. <mention-user>@YOUR EMAIL</mention-user> (current user provided via email)',
	'5. <mention-user>@OTHER EMAIL</mention-user> (other user provided via email)',
	'6. <mention-user></mention-user> (no account ID or email)',
];

return <RenderHTML html={`<comment>${mentionsHTML.join('\n')}</comment>`} />;
```

In the above, change:
- 12345678 with a random number if you already have an account ID stored with this number. It needs to be new.
- YOUR OWN ID with your own account's ID.
- ACCOUNT ID with a known account ID (but not yourself and the login field of the account must be filled).
- YOUR EMAIL should be changed to your own email address.
- OTHER EMAIL should be changed to another account's email address.

**Verify precondition**
1. Go to any report that has a message (or post a message if none present).
2. Verify that the message is replaced with 6 mentions.

**Tests**
1. Verify that mentions 1 - 5 display the correct email address, prefixed by '@'.
2. Verify that pressing on mentions 1 - 5 opens the profile page.
3. Verify that mention 6 is not shown.
4. Verify that mention 2 is highlighted in the same color as mention 4.
5. Make the login field empty of the account of mention 3, e.g. by running (replace 123 with the account ID):
```js
window.Onyx.merge('personalDetailsList', { 123: { login: '' }});
```
6. Verify that mention 3 now correctly states the account's name prefixed with @.
7. Verify that pressing mention 3 still opens the profile page.

- [X] Verify that no errors appear in the JS console

### Offline tests

Identical to "Tests" section.

### QA Steps

Identical to "Tests" section.

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android / native
    - [X] Android / Chrome
    - [X] iOS / native
    - [X] iOS / Safari
    - [X] MacOS / Chrome / Safari
    - [X] MacOS / Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If a new component is created I verified that:
    - [X] A similar component doesn't exist in the codebase
    - [X] All props are defined accurately and each prop has a `/** comment above it */`
    - [X] The file is named correctly
    - [X] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [X] The only data being stored in the state is data necessary for rendering and nothing else
    - [X] If we are not using the full Onyx data that we loaded, I've added the proper selector in order to ensure the component only re-renders when the data it is using changes
    - [X] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [X] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [X] All JSX used for rendering exists in the render method
    - [X] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [X] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/137707942/e7344c91-983a-4845-aef8-56f23f75a08b

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://github.com/Expensify/App/assets/137707942/3d5090db-11e3-4d0e-b91a-51515934fd1b

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/137707942/df3f3d94-e06a-487f-aed2-9e0229a8cd9c

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/137707942/48af374d-8476-4194-9650-43ffc060270f

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/137707942/c85c9f52-cd8f-4ef0-b7c6-824ce4b7af6e

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/137707942/a89f0d40-c069-436a-8520-5878a473fe50

</details>

### CODE REVIEW

**Comment by puneetlath** [comment]
Oh, hm, that's interesting. So the back-end will have to return it as `<mention-user accountID=12345678></mention-user>`? That's a bit of a bummer. 

Is that specifically a restriction of the renderHTML library we're using?

**Comment by puneetlath** [comment]
Ok, got it! Thanks for the detailed explanation! Let's go with the way you have it for now. If we want to add the `recognizeSelfClosing` option later, we can always do so.

**Comment by puneetlath** [comment]
@samh-nl now that the merge freeze is over, please merge main into your branch.

**Comment by puneetlath** [comment]
Ok great. @thesahindia let us know when you'll be able to review.

**Comment by puneetlath** [comment]
@thesahindia bump.

**Comment by puneetlath** [comment]
@situchan bump!

**Comment by situchan** [comment]
Mostly looks good.

> If the accountID is not present in the personalDetailsList then we should render the mention as `@Hidden`

@puneetlath in this case, should we disable navigation to open detail page?


https://github.com/Expensify/App/assets/108292595/0339ed28-b905-4907-b19f-4e8991f8eafa

**Comment by situchan** [comment]
I am not sure if this is possible case: `<mention-user></mention-user>`


https://github.com/Expensify/App/assets/108292595/e50e0537-a85a-4b24-884e-0f3d7d170078

**Comment by puneetlath** [comment]
>If the accountID is not present in the personalDetailsList then we should render the mention as @Hidden
>@puneetlath in this case, should we disable navigation to open detail page?

Yes, if we have the accountID in the mention itself, then we can still open the profile page. Only if for some reason there isn't an accountID present, we shouldn't open the profile page. 

>I am not sure if this is possible case: <mention-user></mention-user>

Let's handle it. It _shouldn't_ happen, but let's handle it in case it does.

**Comment by situchan** [comment]
> Yes, if we have the accountID in the mention itself, then we can still open the profile page. Only if for some reason there isn't an accountID present, we shouldn't open the profile page.

So what I was asking about the case when accountID exists in mention itself but not exist in personalDetailsList.
In this case, we show @hidden so you meant still open profile page with @hidden display in email field, correct?

> Let's handle it. It shouldn't happen, but let's handle it in case it does.

So this is the case when neither accountID nor email exists in mention tag. What would be the expected behavior here?
Just render nothing?

**Comment by situchan** [comment]
@samh-nl let's address feedback above

**Comment by puneetlath** [comment]
> So this is the case when neither accountID nor email exists in mention tag. What would be the expected behavior here?
Just render nothing?

Render nothing makes sense to me for this scenario.

**Comment by puneetlath** [comment]
Good questions.

**Comment by situchan** [comment]
And we already have logic to display `Hidden` in user profile page when display name doesn't exist

https://github.com/Expensify/App/blob/926dc6ab0cb3f86541b4c1b7cd2da7131d2a3149/src/pages/ProfilePage.js#L111

**Comment by situchan** [comment]
in a few hrs

**Comment by puneetlath** [comment]
@situchan will you be able to get to this today?

**Comment by situchan** [comment]
@samh-nl 

Sometimes infinite loading

https://github.com/Expensify/App/assets/108292595/342ff69f-e089-4a6e-a657-271279d70834

Also it doesn't make sense to message Hidden


https://github.com/Expensify/App/assets/108292595/422e8dde-b35a-4495-af55-6c37ad48d4f6

**Comment by situchan** [comment]
I think they can be out of scope as not caused by this PR

**Comment by puneetlath** [comment]
I agree that both of those seem out of scope for this PR.

**Comment by situchan** [comment]
Server is down at the moment - https://expensify.slack.com/archives/C01GTK53T8Q/p1695314249132269
Will checklist once it's back

**Comment by puneetlath** [comment]
Let's try to get this across the finish line today please!

**Comment by situchan** [comment]
Long press on mention doesn't open context menu on native. Works on mWeb
Already existing bug so out of scope

**Comment by situchan** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>


https://github.com/Expensify/App/assets/108292595/e6f933a4-efc7-4862-8f03-a4f67dbc2ba7



</details>

<details>
<summary>Mobile Web - Chrome</summary>


https://github.com/Expensify/App/assets/108292595/ffea8d97-a3fb-4a9a-b8b3-8a155ca5bcd0



</details>

<details>
<summary>Mobile Web - Safari</summary>

https://github.com/Expensify/App/assets/108292595/3251db74-b90c-4928-827a-1bc2a2c5a51b




</details>

<details>
<summary>Desktop</summary>


https://github.com/Expensify/App/assets/108292595/56dc232a-b1e3-41a6-8e0b-3210783a7b01



</details>

<details>
<summary>iOS</summary>


https://github.com/Expensify/App/assets/108292595/3118cf08-dd95-4b18-a739-3dcd18d8264e



</details>

<details>
<summary>Android</summary>


https://github.com/Expensify/App/assets/108292595/6fb915f4-6b98-4ecc-9967-27b84c4e9db8



</details>

**Review by situchan — APPROVED** [review]
:shipit: 

@puneetlath all yours!

**Review by puneetlath — APPROVED** [review]
Looks good!

**Comment by kavimuru** [comment]
@situchan @thesahindia 

Are these QA steps?

1. Verify that mentions 1 - 5 display the correct email address, prefixed by '@'.
2. Verify that pressing on mentions 1 - 5 opens the profile page.
3. Verify that mention 6 is not shown.
4. Verify that mention 2 is highlighted in the same color as mention 4.
5. Make the login field empty of the account of mention 3, e.g. by running (replace 123 with the account ID):
6. window.Onyx.merge('personalDetailsList', { 123: { login: '' }});
7. Verify that mention 3 now correctly states the account's name prefixed with @.
8. Verify that pressing mention 3 still opens the profile page.

**Comment by puneetlath** [comment]
@kavimuru actually this will be basically impossible for you to QA, so you can check it off. As long as mentions are continuing to work as expected in the regression tests, we should be good.

**Comment by jasperhuangg** [comment]
Hey @puneetlath @samh-nl. Not sure if you're already aware of this, but I'm not sure if we updated the report previews to support the new accountID based mentions:
Screenshot 2023-09-26 at 3 40 57 PM

**Pull request merged**
