### PR TITLE
Updating some IOU styles

### PR DESCRIPTION
**Pull request by shawnborton**
### Details
This adds a white background to the IOU preview component and gives it a larger maxWidth so it looks nicer in the sideDocked modal. 

### Fixed Issues
N/A

### Tests / QA Steps
1. Request money from someone in order to create the IOU preview component
2. Hover over the preview component, and make sure the preview component has a white background
3. Click on the "View Details" link above the component. When the IOU detailed view launches, makes sure the preview box stretches to the full width of the detailed view. 

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
image

#### Mobile Web
Screenshot 2021-05-27 at 11 34 10

#### Desktop
image

#### iOS
Simulator Screen Shot - iPhone 11 - 2021-05-27 at 10 59 55

#### Android
image
image

### CODE REVIEW

**Comment by shawnborton** [comment]
@iwiznia or @Julesssss can you help me take this over the finish line? I am having a pretty rough time getting this set up for local testing on iOS and Android. Will keep digging into it tomorrow.

**Comment by Julesssss** [comment]
Sorry @shawnborton, I'm completely overrun and haven't been able to help with this today 😕

**Review by sketchydroide — APPROVED** [review]
code change looks good

**Comment by iwiznia** [comment]
> @iwiznia or @Julesssss can you help me take this over the finish line? 

Sure, what do you need?

**Comment by shawnborton** [comment]
I just need to test this on iOS and Android to provide screenshots. I can't get the iOS app or Android app to run locally.

**Comment by iwiznia** [comment]
ok, tested Android, I am still struggling to set up iOS.

**Comment by iwiznia** [comment]
I've been struggling to make ios work locally (follow [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1621541584068900) if you want to laugh/cry with me).

**Comment by shawnborton** [comment]
Not urgent at all but any luck @iwiznia ?

**Comment by shawnborton** [comment]
I think at this point it would be easiest if you could just pull my branch, test on Android and iOS to wrap up the screenshots above, and then we can get this merged. Hopefully for my next PR I'll have some time to troubleshoot my local apps but I probably won't get to it this week.

**Comment by iwiznia** [comment]
Sorry @shawnborton, I tested Android (and included the screenshots above), but I [could not manage to make ios work](https://expensify.slack.com/archives/C01GTK53T8Q/p1621541584068900) 😞

**Comment by Julesssss** [comment]
> Sorry @shawnborton, I tested Android (and included the screenshots above), but I [could not manage to make ios work](https://expensify.slack.com/archives/C01GTK53T8Q/p1621541584068900) 😞

Wow, just browsing that troubleshooting thread gives me a headache. 

I was luckier and was able to verify iOS/mobile web.

**Review by Julesssss — APPROVED** [review]
LGTM

**Comment by shawnborton** [comment]
Cool, everyone approved so going to merge. Thanks for the help!

**Pull request merged**
