### PR TITLE
Send platform info when making api requests

### PR DESCRIPTION
**Pull request by hayata-suenaga**
### Context
Master tracking issue [here](https://github.com/Expensify/App/issues/15342). This PR is one of three PRs necessary to send a hash along with a validation SMS message to Android device for auto-fill of magic code upon user sign in.

### Deployment schedule
[App](https://github.com/Expensify/App/pull/15973), Auth (this PR) -> [Web-E](https://github.com/Expensify/Web-Expensify/pull/36728)
This PR can be deployed independent of other PRs.

### Details
We only need to add a hash when the user is trying to sign in from an android device. To determine what device the user is using on the server side, we need to pass platform information along with the request.

### Fixed Issues

$ GH_LINK  https://github.com/Expensify/App/issues/15342

#### Development
1. In Web-Expensify, update `api.php` and add the following line somewhere in the beginning of the file (maybe line 35):
   ```php
   Log::info("Platform: ".($_REQUEST['platform'] ?? 'Idk dude'));
   ```
The WAF rule is already set for `platform` parameter in the current Web-E code. So you can test with the main code.
2. Open a chat in NewDot
3. Open your terminal and start tailing logs with `../script/tail.sh "Platform:"`
4. Sign into a NewDot (we want to send the `BeginSignIn` command as this is the command on which the new parameter is added). If you're already sign in, log out to sign in from the beginning.
5. Make sure you see a log for the Platform and it matches the platform you tested
    image
6. Make sure that you remove the log statement you added on step 1.

#### Staging
1. Go to staging.new.expensify on a laptop web browser
2. If you're already signed in, sign out
3. Open the network inspector on Chrome development console
4. Type your account email address and click "Continue"
5. Find `api?command=BeginSignIn` network request and click it
6. Go to the `payload` tab to check the `Form Data` section
7. Check there is `platform` name (the value should be set to `web`)
We want to check that the new parameter is sent in the request payload correctly. Although the purpose of the new parameter is to figure out if requests are coming from android, the existence of the `platform` payload confirms that the new parameter is at least sent without problem.
The ideal QA test is to check this on an Android native app, but since a web browser is more easy to test, I used a web in the above testing steps

### Offline tests
N/A

### QA Steps

N/A

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
N/A

### CODE REVIEW

**Comment by hayata-suenaga** [comment]
I marked this PR and other related PRs ready for review. But I cannot still confirm automatic sms validation behavior on the emulator (the magic code is not automatically extracted and passed to the input field).

Please share ideas how we can test on a real device or or what might be the reason for the behavior not being observed on the [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/36728).

**Comment by hayata-suenaga** [comment]
Please hold reviews now. I'll implement the change suggested [here](https://expensify.slack.com/archives/C03TQ48KC/p1678921525693229?thread_ts=1678835079.851749&cid=C03TQ48KC).

**Comment by hayata-suenaga** [comment]
ready for review now

**Comment by PauloGasparSv** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>



</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by PauloGasparSv** [comment]
Hey @hayata-suenaga I think we need to update the test steps right?

Maybe we can do the following for testing:

1. In Web-Expensify, update `api.php` and add the following line somewhere in the beginning of the file (maybe line 35):
   ```php
   Log::info("Platform: ".($_REQUEST['platform'] ?? 'Idk dude'));
   ```
2. Open a chat in NewDot
3. Open your terminal and start tailing logs with `../script/tail.sh "Platform:"`
4. Send a message in the chat
5. Make sure you see a log for the Platform and it matches the platform you tested
    image

I'll do that here but if those don't match the final test steps I'll re-test here : )

**Comment by hayata-suenaga** [comment]
@PauloGasparSv thank you for suggesting test steps 🙇🏻‍♂️. These steps look good to me. I just added a few details on sending `BeginSignIn` command specifically and posted the steps on the initial comment. You don't have to redo the test.

Also I updated some old comments in the initial comment.

**Comment by PauloGasparSv** [comment]
Hey @hayata-suenaga I forgot to mention: I think we may also have to change the Internal QA Steps as people won't be able to add that Log in prod and staging!

**Comment by hayata-suenaga** [comment]
@PauloGasparSv I added the step 6. thank you for pointing that out

**Comment by PauloGasparSv** [comment]
> If internal QA tests are needed, can people pull [staging](https://github.com/Expensify/app/tree/staging) and [production](https://github.com/Expensify/app/tree/production) branches?

I don't think so @hayata-suenaga!

I think both QA stages (staging and prod) are done without having the source code or running anything locally but instead it's all done either direcly in https://staging.new.expensify.com/ or https://new.expensify.com/ or the Staging/Prod builds for Desktop, Android and iOS!

BTW, here is an example of how QA is done in staging: https://github.com/Expensify/Expensify/issues/268894
And another in for prod: https://github.com/Expensify/Expensify/issues/268122

IMO sometimes it's a bit hard to come up with valid QA steps because we can't do certain things in staging or prod that we can locally (a good example is creating **and validating** a VBA, that's pretty easy in dev but requires some extra steps in staging/prod)

**Review by PauloGasparSv — APPROVED** [review]
LGTM!

@hayata-suenaga just saw the extra QA line you added! I still think those steps may not be possible to follow during QA.

If we log the platform in `logSearch` the QA steps can be to Sign In and search for the `platform` in `logSearch` (but I'm not sure if we log that).

But I think it could also be:
1) Have QA steps for Web for checking if the `platform` was sent in the request (e.g. `BeginSignIn`)  by analyzing the request in the Network Tab of the Chrome Dev Tools.

2) For all the remaining platforms, simply test if you can sign-in correctly and open a chat. That will trigger many requests that send the `platform` field and we'll make sure nothing is broken.

**Comment by hayata-suenaga** [comment]
@PauloGasparSv thank you for the info on internal QA. I checked this [SO](https://stackoverflowteams.com/c/expensify/questions/5042/5046#5046). So internal QA checklists are automatically created when the PR with the label `internalQA` is merged to staging?

**Comment by hayata-suenaga** [comment]
I made a staging section in QA testing steps in the original comment.

**Comment by hayata-suenaga** [comment]
@PauloGasparSv I just realized the production NewDot might be already sending platform info. I'll double check on this. Please don't merge this PR. I'll mark this PR as draft.

**Pull request closed without merging**
