### PR TITLE
Remove extra white space on attachment modal [iPad]

### PR DESCRIPTION
**Pull request by kakajann**
### Details
Removed extra white space from attachment modal on iPad

### Fixed Issues

$ https://github.com/Expensify/App/issues/7590

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Go to any chat
2. Open any attachment
3. Verify there's no extra white space on attachment view on iPad
- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### iPad
| Before | After |
|--------|-------|
|Screen Shot 2022-02-07 at 7 45 44 PM|Screen Shot 2022-02-07 at 7 45 51 PM|

#### Web
Screen Shot 2022-02-12 at 2 38 08 PM

#### Mobile Web
Screen Shot 2022-02-12 at 2 39 01 PM

#### iOS
Screen Shot 2022-02-12 at 2 41 02 PM

#### Android

Screen Shot 2022-02-14 at 11 13 08 AM

### CODE REVIEW

**Comment by rushatgabhane** [comment]
could you please add screenshots for all platforms? Thanks

**Comment by kakajann** [comment]
Added all screenshots, except desktop. Somehow I'm getting CORS error.
Screen Shot 2022-02-14 at 10 49 55 AM

**Comment by rushatgabhane** [comment]
@kakajann merging main into your branch should fix it.

https://expensify.slack.com/archives/C01GTK53T8Q/p1644705525718059?thread_ts=1644527403.102189&cid=C01GTK53T8Q

**Comment by kakajann** [comment]
The desktop version doesn't even run with the latest commit, it's only a blank screen.
Screen Shot 2022-02-14 at 12 06 05 PM
And there's no error in the log.

<details><summary>Show logs</summary><p>

```bash
➜  Expensify git:(fix/attachment-extra-white-space-ipad-2) npm run desktop

> new.expensify@1.1.38-3 desktop /Users/kakajann/Web/Expensify
> node desktop/start.js

[Main] Waiting for localhost:8080.ℹ ｢wds｣: Project is running at http://localhost:8080/
[Renderer] ℹ ｢wds｣: webpack output is served from /
[Renderer] ℹ ｢wds｣: Content not from webpack is served from /Users/kakajann/Web/Expensify/config/dist
[Renderer] ℹ ｢wds｣: 404s will fallback to /index.html
[Main] .
[Main] Connected!
[Main] 12:01:57.984 › (node:9854) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'USE_WEB_PROXY')
[Main]     at /Users/kakajann/Web/Expensify/desktop/main.js:186:34
[Main] (Use `Electron --trace-warnings ...` to show where the warning was created)
[Main] 12:01:57.986 › (node:9854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[Renderer] Browserslist: caniuse-lite is outdated. Please run:
[Renderer]   npx browserslist@latest --update-db
[Renderer]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[Renderer] ℹ ｢wdm｣: Hash: 2155fb27f48afb7ff7f8
[Renderer] Version: webpack 4.44.2
[Renderer] Time: 33422ms
[Renderer] Built at: 02/14/2022 12:02:30 PM
[Renderer]                                                             Asset       Size  Chunks                         Chunk Names
[Renderer] .well-known/apple-app-site-association/apple-app-site-association   1.48 KiB          [emitted]
[Renderer]                              16b4a297f6d1e62f8cc9aa8da07a2f9b.gif    228 KiB          [emitted] [immutable]
[Renderer]                              6df71f2e68421ee82534a17311f1a05f.png   17.9 KiB          [emitted] [immutable]
[Renderer]                              701ab79fefbe75d338a3c4522ae3b5d0.png   11.8 KiB          [emitted] [immutable]
[Renderer]                                app-2155fb27f48afb7ff7f8.bundle.js   40.4 MiB     app  [emitted] [immutable]  app
[Renderer]                              b200a37389bc3691eb4cbb0e800e83a7.png  116 bytes          [emitted] [immutable]
[Renderer]                              c68886dd5d370fcfa42341a1a4e21b65.png   11.3 KiB          [emitted] [immutable]
[Renderer]                              c733a880bd6d3d1f0f38ef1608fb8a32.png  207 bytes          [emitted] [immutable]
[Renderer]                                              cmaps/78-EUC-H.bcmap   2.35 KiB          [emitted]
[Renderer]                                              cmaps/78-EUC-V.bcmap  173 bytes          [emitted]
[Renderer]                                                  cmaps/78-H.bcmap   2.32 KiB          [emitted]
[Renderer]                                             cmaps/78-RKSJ-H.bcmap   2.34 KiB          [emitted]
[Renderer]                                             cmaps/78-RKSJ-V.bcmap  173 bytes          [emitted]
[Renderer]                                                  cmaps/78-V.bcmap  169 bytes          [emitted]
[Renderer]                                           cmaps/78ms-RKSJ-H.bcmap   2.59 KiB          [emitted]
[Renderer]                                           cmaps/78ms-RKSJ-V.bcmap  290 bytes          [emitted]
[Renderer]                                           cmaps/83pv-RKSJ-H.bcmap  905 bytes          [emitted]
[Renderer]                                           cmaps/90ms-RKSJ-H.bcmap  721 bytes          [emitted]
[Renderer]                                           cmaps/90ms-RKSJ-V.bcmap  290 bytes          [emitted]
[Renderer]                                          cmaps/90msp-RKSJ-H.bcmap  715 bytes          [emitted]
[Renderer]                                          cmaps/90msp-RKSJ-V.bcmap  291 bytes          [emitted]
[Renderer]                                           cmaps/90pv-RKSJ-H.bcmap  982 bytes          [emitted]
[Renderer]                                           cmaps/90pv-RKSJ-V.bcmap  260 bytes          [emitted]
[Renderer]                                                 cmaps/Add-H.bcmap   2.36 KiB          [emitted]
[Renderer]                                            cmaps/Add-RKSJ-H.bcmap   2.36 KiB          [emitted]
[Renderer]                                            cmaps/Add-RKSJ-V.bcmap  287 bytes          [emitted]
[Renderer]                                                 cmaps/Add-V.bcmap  282 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-0.bcmap  317 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-1.bcmap  371 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-2.bcmap  376 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-3.bcmap  401 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-4.bcmap  405 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-5.bcmap  406 bytes          [emitted]
[Renderer]                                          cmaps/Adobe-CNS1-6.bcmap  406 bytes          [emitted]
[Renderer]                                       cmaps/Adobe-CNS1-UCS2.bcmap   40.2 KiB          [emitted]
[Renderer]                                           cmaps/Adobe-GB1-0.bcmap  217 bytes          [emitted]
[Renderer]                                           cmaps/Adobe-GB1-1.bcmap  250 bytes          [emitted]
[Renderer]                                           cmaps/Adobe-GB1-2.bcmap  465 bytes          [emitted]
[Renderer]                                           cmaps/Adobe-GB1-3.bcmap  470 bytes          [emitted]
[Renderer]                                           cmaps/Adobe-GB1-4.bcmap  601 bytes          [emitted]
[Renderer]                                           cmaps/Adobe-GB1-5.bcmap  625 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-GB1-UCS2.bcmap   33.2 KiB          [emitted]
[Renderer]                                        cmaps/Adobe-Japan1-0.bcmap  225 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Japan1-1.bcmap  226 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Japan1-2.bcmap  233 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Japan1-3.bcmap  242 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Japan1-4.bcmap  337 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Japan1-5.bcmap  430 bytes          [emitted]
                                       cmaps/Adobe-Japan1-6.bcmap  485 bytes          [emitted]
[Renderer]                                     cmaps/Adobe-Japan1-UCS2.bcmap     40 KiB          [emitted]
[Renderer]                                        cmaps/Adobe-Korea1-0.bcmap  241 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Korea1-1.bcmap  386 bytes          [emitted]
[Renderer]                                        cmaps/Adobe-Korea1-2.bcmap  391 bytes          [emitted]
[Renderer]                                     cmaps/Adobe-Korea1-UCS2.bcmap   22.7 KiB          [emitted]
[Renderer]                                                  cmaps/B5-H.bcmap   1.06 KiB          [emitted]
[Renderer]                                                  cmaps/B5-V.bcmap  142 bytes          [emitted]
[Renderer]                                                cmaps/B5pc-H.bcmap   1.07 KiB          [emitted]
[Renderer]                                                cmaps/B5pc-V.bcmap  144 bytes          [emitted]
[Renderer]                                             cmaps/CNS-EUC-H.bcmap   1.74 KiB          [emitted]
[Renderer]                                             cmaps/CNS-EUC-V.bcmap   1.88 KiB          [emitted]
[Renderer]                                                cmaps/CNS1-H.bcmap  706 bytes          [emitted]
[Renderer]                                                cmaps/CNS1-V.bcmap  143 bytes          [emitted]
[Renderer]                                                cmaps/CNS2-H.bcmap  504 bytes          [emitted]
[Renderer]                                                cmaps/CNS2-V.bcmap   93 bytes          [emitted]
[Renderer]                                             cmaps/ETHK-B5-H.bcmap   4.32 KiB          [emitted]
[Renderer]                                             cmaps/ETHK-B5-V.bcmap  158 bytes          [emitted]
[Renderer]                                             cmaps/ETen-B5-H.bcmap    1.1 KiB          [emitted]
[Renderer]                                             cmaps/ETen-B5-V.bcmap  158 bytes          [emitted]
[Renderer]                                           cmaps/ETenms-B5-H.bcmap  101 bytes          [emitted]
[Renderer]                                           cmaps/ETenms-B5-V.bcmap  172 bytes          [emitted]
[Renderer]                                                 cmaps/EUC-H.bcmap  578 bytes          [emitted]
[Renderer]                                                 cmaps/EUC-V.bcmap  170 bytes          [emitted]
[Renderer]                                                 cmaps/Ext-H.bcmap   2.48 KiB          [emitted]
[Renderer]                                            cmaps/Ext-RKSJ-H.bcmap   2.48 KiB          [emitted]
[Renderer]                                            cmaps/Ext-RKSJ-V.bcmap  218 bytes          [emitted]
[Renderer]                                                 cmaps/Ext-V.bcmap  215 bytes          [emitted]
[Renderer]                                              cmaps/GB-EUC-H.bcmap  549 bytes          [emitted]
[Renderer]                                              cmaps/GB-EUC-V.bcmap  179 bytes          [emitted]
[Renderer]                                                  cmaps/GB-H.bcmap  528 bytes          [emitted]
[Renderer]                                                  cmaps/GB-V.bcmap  175 bytes          [emitted]
[Renderer]                                             cmaps/GBK-EUC-H.bcmap   14.3 KiB          [emitted]
[Renderer]                                             cmaps/GBK-EUC-V.bcmap  180 bytes          [emitted]
[Renderer]                                               cmaps/GBK2K-H.bcmap   19.2 KiB          [emitted]
[Renderer]                                               cmaps/GBK2K-V.bcmap  219 bytes          [emitted]
[Renderer]                                            cmaps/GBKp-EUC-H.bcmap   14.3 KiB          [emitted]
[Renderer]                                            cmaps/GBKp-EUC-V.bcmap  181 bytes          [emitted]
[Renderer]                                             cmaps/GBT-EUC-H.bcmap   7.12 KiB          [emitted]
[Renderer]                                             cmaps/GBT-EUC-V.bcmap  180 bytes          [emitted]
[Renderer]                                                 cmaps/GBT-H.bcmap    7.1 KiB          [emitted]
[Renderer]                                                 cmaps/GBT-V.bcmap  176 bytes          [emitted]
[Renderer]                                           cmaps/GBTpc-EUC-H.bcmap   7.13 KiB          [emitted]
[Renderer]                                           cmaps/GBTpc-EUC-V.bcmap  182 bytes          [emitted]
[Renderer]                                            cmaps/GBpc-EUC-H.bcmap  557 bytes          [emitted]
[Renderer]                                            cmaps/GBpc-EUC-V.bcmap  181 bytes          [emitted]
[Renderer]                                                     cmaps/H.bcmap  553 bytes          [emitted]
[Renderer]                                            cmaps/HKdla-B5-H.bcmap   2.59 KiB          [emitted]
[Renderer]                                            cmaps/HKdla-B5-V.bcmap  148 bytes          [emitted]
[Renderer]                                            cmaps/HKdlb-B5-H.bcmap   2.36 KiB          [emitted]
                                           cmaps/HKdlb-B5-V.bcmap  148 bytes          [emitted]
[Renderer]                                           cmaps/HKgccs-B5-H.bcmap   2.24 KiB          [emitted]
[Renderer]                                           cmaps/HKgccs-B5-V.bcmap  149 bytes          [emitted]
[Renderer]                                           cmaps/HKm314-B5-H.bcmap   1.73 KiB          [emitted]
[Renderer]                                           cmaps/HKm314-B5-V.bcmap  149 bytes          [emitted]
[Renderer]                                           cmaps/HKm471-B5-H.bcmap   2.12 KiB          [emitted]
[Renderer]                                           cmaps/HKm471-B5-V.bcmap  149 bytes          [emitted]
[Renderer]                                            cmaps/HKscs-B5-H.bcmap   4.33 KiB          [emitted]
[Renderer]                                            cmaps/HKscs-B5-V.bcmap  159 bytes          [emitted]
[Renderer]                                               cmaps/Hankaku.bcmap  132 bytes          [emitted]
[Renderer]                                              cmaps/Hiragana.bcmap  124 bytes          [emitted]
[Renderer]                                             cmaps/KSC-EUC-H.bcmap    1.8 KiB          [emitted]
[Renderer]                                             cmaps/KSC-EUC-V.bcmap  164 bytes          [emitted]
[Renderer]                                                 cmaps/KSC-H.bcmap   1.79 KiB          [emitted]
[Renderer]                                           cmaps/KSC-Johab-H.bcmap   16.4 KiB          [emitted]
[Renderer]                                           cmaps/KSC-Johab-V.bcmap  166 bytes          [emitted]
[Renderer]                                                 cmaps/KSC-V.bcmap  160 bytes          [emitted]
[Renderer]                                           cmaps/KSCms-UHC-H.bcmap   2.72 KiB          [emitted]
[Renderer]                                        cmaps/KSCms-UHC-HW-H.bcmap   2.72 KiB          [emitted]
[Renderer]                                        cmaps/KSCms-UHC-HW-V.bcmap  169 bytes          [emitted]
[Renderer]                                           cmaps/KSCms-UHC-V.bcmap  166 bytes          [emitted]
[Renderer]                                           cmaps/KSCpc-EUC-H.bcmap   1.98 KiB          [emitted]
[Renderer]                                           cmaps/KSCpc-EUC-V.bcmap  166 bytes          [emitted]
[Renderer]                                              cmaps/Katakana.bcmap  100 bytes          [emitted]
[Renderer]                                                     cmaps/LICENSE   2.03 KiB          [emitted]
[Renderer]                                                 cmaps/NWP-H.bcmap    2.7 KiB          [emitted]
[Renderer]                                                 cmaps/NWP-V.bcmap  252 bytes          [emitted]
[Renderer]                                                cmaps/RKSJ-H.bcmap  534 bytes          [emitted]
[Renderer]                                                cmaps/RKSJ-V.bcmap  170 bytes          [emitted]
[Renderer]                                                 cmaps/Roman.bcmap   96 bytes          [emitted]
[Renderer]                                         cmaps/UniCNS-UCS2-H.bcmap   47.1 KiB          [emitted]
[Renderer]                                         cmaps/UniCNS-UCS2-V.bcmap  156 bytes          [emitted]
[Renderer]                                        cmaps/UniCNS-UTF16-H.bcmap   49.2 KiB          [emitted]
[Renderer]                                        cmaps/UniCNS-UTF16-V.bcmap  156 bytes          [emitted]
[Renderer]                                        cmaps/UniCNS-UTF32-H.bcmap   51.4 KiB          [emitted]
[Renderer]                                        cmaps/UniCNS-UTF32-V.bcmap  160 bytes          [emitted]
[Renderer]                                         cmaps/UniCNS-UTF8-H.bcmap   52.4 KiB          [emitted]
[Renderer]                                         cmaps/UniCNS-UTF8-V.bcmap  157 bytes          [emitted]
[Renderer]                                          cmaps/UniGB-UCS2-H.bcmap   42.3 KiB          [emitted]
[Renderer]                                          cmaps/UniGB-UCS2-V.bcmap  193 bytes          [emitted]
[Renderer]                                         cmaps/UniGB-UTF16-H.bcmap   43.1 KiB          [emitted]
[Renderer]                                         cmaps/UniGB-UTF16-V.bcmap  178 bytes          [emitted]
[Renderer]                                         cmaps/UniGB-UTF32-H.bcmap   44.7 KiB          [emitted]
[Renderer]                                         cmaps/UniGB-UTF32-V.bcmap  182 bytes          [emitted]
[Renderer]                                          cmaps/UniGB-UTF8-H.bcmap   45.7 KiB          [emitted]
[Renderer]                                          cmaps/UniGB-UTF8-V.bcmap  181 bytes          [emitted]
[Renderer]                                         cmaps/UniJIS-UCS2-H.bcmap   24.8 KiB          [emitted]
[Renderer]                                      cmaps/UniJIS-UCS2-HW-H.bcmap  119 bytes          [emitted]
[Renderer]                                      cmaps/UniJIS-UCS2-HW-V.bcmap  680 bytes          [emitted]
[Renderer]                                         cmaps/UniJIS-UCS2-V.bcmap  664 bytes          [emitted]
[Renderer]                                        cmaps/UniJIS-UTF16-H.bcmap   38.5 KiB          [emitted]
                                       cmaps/UniJIS-UTF16-V.bcmap  643 bytes          [emitted]
[Renderer]                                        cmaps/UniJIS-UTF32-H.bcmap   39.6 KiB          [emitted]
[Renderer]                                        cmaps/UniJIS-UTF32-V.bcmap  677 bytes          [emitted]
[Renderer]                                         cmaps/UniJIS-UTF8-H.bcmap   40.7 KiB          [emitted]
[Renderer]                                         cmaps/UniJIS-UTF8-V.bcmap  678 bytes          [emitted]
[Renderer]                                    cmaps/UniJIS2004-UTF16-H.bcmap   38.6 KiB          [emitted]
[Renderer]                                    cmaps/UniJIS2004-UTF16-V.bcmap  647 bytes          [emitted]
[Renderer]                                    cmaps/UniJIS2004-UTF32-H.bcmap   39.7 KiB          [emitted]
[Renderer]                                    cmaps/UniJIS2004-UTF32-V.bcmap  681 bytes          [emitted]
[Renderer]                                     cmaps/UniJIS2004-UTF8-H.bcmap   40.8 KiB          [emitted]
[Renderer]                                     cmaps/UniJIS2004-UTF8-V.bcmap  682 bytes          [emitted]
[Renderer]                                   cmaps/UniJISPro-UCS2-HW-V.bcmap  705 bytes          [emitted]
[Renderer]                                      cmaps/UniJISPro-UCS2-V.bcmap  689 bytes          [emitted]
[Renderer]                                      cmaps/UniJISPro-UTF8-V.bcmap  726 bytes          [emitted]
[Renderer]                                   cmaps/UniJISX0213-UTF32-H.bcmap   39.6 KiB          [emitted]
[Renderer]                                   cmaps/UniJISX0213-UTF32-V.bcmap  684 bytes          [emitted]
[Renderer]                               cmaps/UniJISX02132004-UTF32-H.bcmap   39.7 KiB          [emitted]
[Renderer]                               cmaps/UniJISX02132004-UTF32-V.bcmap  688 bytes          [emitted]
[Renderer]                                          cmaps/UniKS-UCS2-H.bcmap   25.2 KiB          [emitted]
[Renderer]                                          cmaps/UniKS-UCS2-V.bcmap  178 bytes          [emitted]
[Renderer]                                         cmaps/UniKS-UTF16-H.bcmap   25.7 KiB          [emitted]
[Renderer]                                         cmaps/UniKS-UTF16-V.bcmap  164 bytes          [emitted]
[Renderer]                                         cmaps/UniKS-UTF32-H.bcmap   25.8 KiB          [emitted]
[Renderer]                                         cmaps/UniKS-UTF32-V.bcmap  168 bytes          [emitted]
[Renderer]                                          cmaps/UniKS-UTF8-H.bcmap   27.1 KiB          [emitted]
[Renderer]                                          cmaps/UniKS-UTF8-V.bcmap  169 bytes          [emitted]
[Renderer]                                                     cmaps/V.bcmap  166 bytes          [emitted]
[Renderer]                                             cmaps/WP-Symbol.bcmap  179 bytes          [emitted]
[Renderer]                                           css/AnnotationLayer.css   5.42 KiB          [emitted]
[Renderer]                                                     css/fonts.css   5.04 KiB          [emitted]
[Renderer]                                                       css/pdf.css  683 bytes          [emitted]
[Renderer]                              f241a554561961c8f6bbd4318a244450.png   1.53 KiB          [emitted] [immutable]
[Renderer]                              fae3c934a7353e1defbb00343509b3aa.png  913 bytes          [emitted] [immutable]
[Renderer]                                                favicon-unread.png   4.24 KiB          [emitted]
[Renderer]                                                       favicon.png   4.15 KiB          [emitted]
[Renderer]                                                 images/shadow.png  269 bytes          [emitted]
[Renderer]                                                        index.html    2.2 KiB          [emitted]
[Renderer]                                              og-preview-image.png   17.3 KiB          [emitted]
[Renderer]            pdf.worker.entry-3c5c56047f2bd6a5eb2d.bundle.worker.js   3.25 MiB          [emitted] [immutable]
[Renderer] Entrypoint app = app-2155fb27f48afb7ff7f8.bundle.js
[Renderer] [0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./index.js 52 bytes {app} [built]
[Renderer] [./index.js] 337 bytes {app} [built]
[Renderer] [./node_modules/react-native-gesture-handler/index.js] 173 bytes {app} [built]
[Renderer] [./node_modules/react-native-web/dist/exports/AppRegistry/index.js] 5.14 KiB {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} [built]
[Renderer] [./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {app} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {app} [built]
[Renderer] [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {app} [built]
[Renderer] [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[Renderer] [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {app} [built]
[Renderer]     + 3223 hidden modules
[Renderer] Child HtmlWebpackCompiler:
[Renderer]      1 asset
[Renderer]     Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
[Renderer]     [./node_modules/html-webpack-plugin/lib/loader.js!./web/index.html] 2.82 KiB {HtmlWebpackPlugin_0} [built]
[Renderer] Child worker-loader node_modules/react-pdf/dist/esm/pdf.worker.entry.js:
[Renderer]                                                      Asset      Size            Chunks                         Chunk Names
[Renderer]     pdf.worker.entry-3c5c56047f2bd6a5eb2d.bundle.worker.js  3.25 MiB  pdf.worker.entry  [emitted] [immutable]  pdf.worker.entry
[Renderer]     Entrypoint pdf.worker.entry = pdf.worker.entry-3c5c56047f2bd6a5eb2d.bundle.worker.js
[Renderer]     [./node_modules/pdfjs-dist/build/pdf.worker.js] 1.22 MiB {pdf.worker.entry} [built]
[Renderer]     [./node_modules/process/browser.js] 5.29 KiB {pdf.worker.entry} [built]
[Renderer]     [./node_modules/react-pdf/dist/esm/pdf.worker.entry.js] 460 bytes {pdf.worker.entry} [built]
[Renderer] ℹ ｢wdm｣: Compiled successfully.
```
</p></details>

**Comment by rushatgabhane** [comment]
@kakajann look for any errors in the console?

**Comment by kakajann** [comment]
View -> Toggle Developer Tools; doesn't do anything. Can't open the console.

Screen Shot 2022-02-14 at 12 23 35 PM

**Comment by rushatgabhane** [comment]
@puneetlath LGTM! 🎉
Tests well on all platforms.

I've added desktop video since @kakajann is having trouble running it.

https://user-images.githubusercontent.com/29673073/153915948-439905f8-b7ad-45b0-a654-ea7d106f336a.mov

**Comment by rushatgabhane** [comment]
P.S. @kakajann for now you could try adding a `.env` file with `USE_WEB_PROXY=true` `USE_NRGOK=false`

**Review by puneetlath — APPROVED** [review]

**Pull request merged**
