### PR TITLE
fix: Show top report skeleton when offline

### PR DESCRIPTION
**Pull request by paultsimura**
### Details

Show the top report skeleton when offline & the beginning of the history is not loaded.
Also, show the skeleton animation always regardless of the network state: https://github.com/Expensify/App/issues/31367#issuecomment-1816476601

### Fixed Issues

$ https://github.com/Expensify/App/issues/31367
$ https://github.com/Expensify/App/issues/30503
PROPOSAL: https://github.com/Expensify/App/issues/31367#issuecomment-1812714727

### Tests

Same as QA

### Offline tests

Same as QA

### QA Steps

1. Open a chat that has a long chat history.
2. Go offline.
3. Scroll to the top.
4. Return to LHN.
5. Reopen the chat in Step 1 and scroll to the top.
- [ ] Verify that a short 3-sections skeleton is displayed on top and is animated.

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/12595293/66967f85-741e-494e-8849-27e884abc2ef

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/12595293/335da8b7-689b-42d7-a2e3-09e8e9fe1177

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/12595293/6786a537-98f0-4595-afff-cd1db2f834f6

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/12595293/0628ce5c-56e4-4f3b-82ec-98f89a077653

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/12595293/1b41fe88-737e-43a9-9a1d-f7e6f0149efb

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/12595293/3cead1e6-420f-4055-9c2c-aa28e00c2e46

</details>

### CODE REVIEW

**Comment by paultsimura** [comment]
@getusha a friendly bump on this PR

**Comment by shawnborton** [comment]
Hmm yeah, a couple more skeleton messages might be nice to fill the screen a bit more. cc @Expensify/design in case they disagree :)

**Comment by shawnborton** [comment]
> Should we want to use the full-height skeleton for the initial data loading?

What does this mean exactly? 

Otherwise can we just pick a higher number, like 7? If it doesn't work perfectly everywhere, that's okay - as long as it covers most of the cases.

**Comment by paultsimura** [comment]
> What does this mean exactly?

This value is set to `true` when we first open the Report. If we're opening the report when offline, this value doesn't change to `false` until we're back online.

This is how the screen looks when we are loading the initial report actions **and** there are no pre-loaded actions:

image

Maybe we could go with the same approach and append the full-height skeleton even if we have some of the actions:

image

Otherwise, I'll go with the fixed 7:

image

@shawnborton it's up to you ☝️

**Comment by paultsimura** [comment]
Got it. @getusha your shot, please

**Comment by getusha** [comment]
I think if it's the same on the main, we can leave it as it is because it's a design choice.
what do you think? @shawnborton

**Comment by shawnborton** [comment]
That works for me

**Comment by paultsimura** [comment]
> That works for me

@getusha in this case, I think the PR can be approved if the rest LGTY?

**Comment by getusha** [comment]
@paultsimura the author PR checklist check is failing, can you make sure the PR has up-to-date checklist content?

**Comment by paultsimura** [comment]
@getusha done ✅ 

image

**Review by getusha — APPROVED** [review]
Looks good, works well.

**Comment by aldo-expensify** [comment]
Considering the conversation above, @getusha @paultsimura are we fine to proceed then?

**Review by aldo-expensify — APPROVED** [review]

**Comment by paultsimura** [comment]
> Are we fine to proceed then?

From my POV – yes

**Pull request merged**
