### PR TITLE
Fix IOU Modal styles.

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/6415

### Tests | QA Steps
1. Launch the app and login
 2. Click on green Fab button
 3. Tap Request Money
 4. Select amount and click Next

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web | Desktop

image

#### Mobile Web

Screenshot 2021-11-23 15:40:15

#### Android

Screenshot 2021-11-23 15:42:23

### CODE REVIEW

**Review by NikkiWines — APPROVED** [review]
👍 tested and works well

**Comment by parasharrajat** [comment]
This was supposed to be CP staging.

**Comment by chiragsalian** [comment]
I gotchu guys. Imma CP it to staging now.

**Comment by chiragsalian** [comment]
Manually CP'd to staging.

**Comment by mallenexpensify** [comment]
@roryabraham any idea why this was deployed to staging and production twice? cc @michaelhaxhiu @dylanexpensify , we're discussing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1638885826033800)

**Comment by roryabraham** [comment]
It's a known issue: https://github.com/Expensify/App/issues/4977

**Pull request merged**
