### PR TITLE
Remove pointer events from label, modify styling of textinput

### PR DESCRIPTION
**Pull request by AlfredoAlc**
@parasharrajat @marcaaron 
### Details

To fix the initial issue of the label being able to be selected and to loose focus when clicking on it, I set the prop `pointerEvents` to `none`. This allows to remove the `zIndex` prop, and I also removed the `selectable` prop since it has no use now.

> Pretty sure this caused a regression with labels on autofilled forms. Since they have a `z-index` of `-1` they're now hidden 
> 
> The autofill also expands beyond the edges but unsure if that was introduced in this PR.

For the issue where the autofill expands beyond the edges, I don't think it was related with the changes I made since I tested it with the same props that had before and actually the result was this:
autofill style

But I passed the `borderRadius` from the container to the `TextInput` and added a `height` since if no height is set, the blue background overlaps the border from the container. Also removed the `...spacing.pv0` because it has `paddings` props so it had no use.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4515 
$ https://github.com/Expensify/App/pull/5704

### Tested On

- [x] Web
- [ ] Mobile Web
- [x] Desktop
- [ ] iOS
- [ ] Android

#### Android
android

#### iOS
ios

#### Desktop
Desktop

#### Web
Web

### CODE REVIEW

**Review by parasharrajat — APPROVED** [review]
LGTM.

**Review by timszot — APPROVED** [review]

**Comment by parasharrajat** [comment]
Ok. No worries, I just wanted to see the autofill working. Thanks for the screens. You can attach these to the main details so that they are easier to find.

I think they look fine. Previously the autofill color was only filling in the input area but now it's covering the whole input. It does not seem a big deal to me. So :+1: .

All yours @timszot.

**Comment by anthony-hull** [comment]
> You can follow the steps for #5704. and with respect to that please test the autofill as well.
> 
> 1. When value auto-fills, a label should not be hidden and auto-filled color should not overflow the Input.
> 2. I am sure where will you get the autofill but the best guess is ComanyStep on VBA flow.

with 1Password and a card saved, on the add payment method screen you can add a debit card. letting 1password fill this in triggers the blue background

**Comment by anthony-hull** [comment]
https://user-images.githubusercontent.com/47184118/143285525-51ad5125-c100-4a39-92ef-bbeb1dc7e509.mp4

is this still broken?

**Pull request merged**
