### PR TITLE
LHN - RBR appears on the wrong workspace chat for an error occurring on another workspace

### PR DESCRIPTION
**Pull request by SIMalik**
### Fixed Issues

$ https://github.com/Expensify/App/issues/47874
PROPOSAL: https://github.com/Expensify/App/issues/47874#issuecomment-2325602648

### Tests

1. Navigate to Old Dot and sign up with a new account
2. Go to settings > Account and validate the account
3. Navigate to staging.new.expensify.com and sign in with the same account signed in on Old Dot
4. Create a workspace and name it as "Workspace 1" 
5. Go to workspace editor and enable workflows
6. Go to workflows and enable delayed submission and set it to manual and enable approvals also
7. Create another workspace and name it as "Workspace 2"
8. Navigate to Workspace 1 chat and create a manual expense
9. Click on submit but do not click on approve
10. Navigate to Old dot and refresh the page
11. Go to reports and click on the expense created on ND
12. Click on detail and change the workspace from workspace 1 to workspace 2
13. Go to New dot and wait for a few seconds for the change to take effect
14. After the changes took effect (Workspace 1 will not have GBR on the LHN and instead workspace 2 will have GBR and the expense will be moved to it)
15. Go to workspace chat 2 and create a scan expense with a normal picture so that it will throw error after it is done scanning
16. Observe the LHN of workspace chat 1 on the LHN
17. No RBR will be present on the workspace chat 1

- [x] Verify that no errors appear in the JS console

### Offline tests

NA
### QA Steps

Same as Tests above
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos

https://github.com/user-attachments/assets/078f7eeb-35ae-4069-85f3-67cd6726d572

<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

image_2024-09-26_124350675

[Video](https://drive.google.com/file/d/1mE10OUCqJQAU5_WaAgBvHa_T43lcjC6k/view?usp=sharing)
</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

47874-MAC-After-3

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

### CODE REVIEW

**Comment by SIMalik** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SIMalik** [comment]
recheck

**Comment by SIMalik** [comment]
Hi @ntdiary,

Thank you for reviewing my PR. I wanted to ask for some guidance on how to test the changes across all six platforms (Android Native, Android mWeb Chrome, iOS Native, iOS mWeb Safari, MacOS Chrome/Safari, and MacOS Desktop). Currently, I'm using Linux for development, and as this is my first PR, I'm not entirely sure how to test on all these platforms.

Could you please advise on the best approach for this? Any help or resources you can provide would be greatly appreciated.

Thank you!

**Comment by SIMalik** [comment]
> https://github.com/Expensify/App/blob/main/contributingGuides/TESTING_MACOS_AND_IOS.md Perhaps this document can help you. As for Android mWeb/native, you can use Android Studio and its emulator or your real device. Additionally, we also have a guide to help set up the local environment https://github.com/Expensify/App?tab=readme-ov-file#local-development 😄

@ntdiary Hi
Thank you for providing the resources. I’ve started working on setting up the environment and will let you know if I encounter any issues. Your assistance is much appreciated!

**Review by ntdiary — CHANGES_REQUESTED** [review]

**Comment by SIMalik** [comment]
@ntdiary 
Working well on the web. 
The Android build in Android Studio completes successfully, but after the "Build Successful" message, the app doesn't fully launch on the emulator and stops at that point. It appears to be an issue with loading Scripts.

**Comment by SIMalik** [comment]
@ntdiary 
Yes, I have executed both `npx react-native start` and `adb reverse tcp:8081 tcp:8081`, but the issue persists. Additionally, the web is running correctly on localhost:9000, while attempting to use 8081 or 8082 results in a security error.

**Comment by SIMalik** [comment]
@ntdiary 
The application is now running successfully on https://10.0.2.2:8082 within the Android emulator. I've also attached a video in the "Android: mWeb Chrome" section for your reference.

Could you please confirm if this meets the requirements?
[video](https://drive.google.com/file/d/1mE10OUCqJQAU5_WaAgBvHa_T43lcjC6k/view?usp=sharing)

**Comment by SIMalik** [comment]
> @SIMalik, LGTM! And if the video is too large, you can also upload screenshots like I did. 😄

@ntdiary 
image_2024-09-26_124142059

**Comment by SIMalik** [comment]
@ntdiary 
Yes, I am currently in the process of setting up macOS from scratch.

**Comment by SIMalik** [comment]
Hi @ntdiary,

I initially installed macOS 10.15 Catalina, but I encountered several unsupported command issues, which affected its performance. Realizing it was an outdated version, I decided to remove it.

Currently, I am in the process of installing macOS 15 Sequoia. Since this is my first time installing macOS, it’s taking some time, but I'm making progress and am not stuck.

Thank you for your understanding!

**Comment by SIMalik** [comment]
Hi @ntdiary 

MacOS: Chrome / Safari

After Code change:
47874-MAC-After-3

Before code change:
47874-MAC-Before-3


Working on other platforms.

**Comment by SIMalik** [comment]
Hi @ntdiary 

macOS: **Ventura 13.7**

**iOS Setup:** I’ve completed the following steps:

Step 1: Install Xcode 14.3.1
Step 2: Install Xcode Command Line Tools
xcode-select --install

Step 3: Set Up CocoaPods
sudo gem install bundler
bundle install

Step 4: Configure Mapbox Token
npm run configure-mapbox

Step 5: Install Project Dependencies
npm install && npm run pod-install

Step 6: Run the iOS Simulator
npm run ios

**Issue:** When I open Expensify/ios/NewExpensify.xcworkspace in Xcode, I encounter the following error message:

"The target 'NewExpensifyTests' contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets."

Could you please advise on how to proceed or correct any steps to successfully run the iOS app?

Thank you!

**Review by ntdiary — APPROVED** [review]
I'm about to approve the changes now. @SIMalik, please continue testing on the other platforms, and feel free to let me know if you encounter any problems. This will definitely help you understand and solve other issues in the future. :)

**Comment by SIMalik** [comment]
Hi @ntdiary,

Yes, I'm currently testing on the other platforms and will ensure everything is completed. If I encounter any issues, I’ll be sure to let you know.

Thank you for your support!

**Review by neil-marcellini — APPROVED** [review]
Great thanks!

**Comment by neil-marcellini** [comment]
@SIMalik looks like the automated tests found an error that will need to be fixed. We might need to re-evaluate the approach.

**Review by neil-marcellini — CHANGES_REQUESTED** [review]
Requesting changes to fix the failing tests

**Comment by SIMalik** [comment]
@neil-marcellini

You're absolutely right; I’m currently working on addressing the failing tests and will make the necessary adjustments.

**Comment by SIMalik** [comment]
@ntdiary, @neil-marcellini 

    getRBRReportAction
      ✓ returns report action that contains errors (297 ms)
      ○ skipped returns undefined when report has no RBR
      ○ skipped returns parentReportAction if it is a transaction thread, the transaction is missing smart scan fields and the report is not settled
      Report has missing fields, isn't settled and it's owner is the current user
        Report is IOU
          ○ skipped returns correct report action which has missing fields
        Report is expense
          ○ skipped returns correct report action which has missing fields
      There is a report action with smart scan errors
        ○ skipped returns correct report action which is a report preview and has an error
        ○ skipped returns correct report action which is a split bill and has an error
        ○ skipped returns undefined if there's no report action is a report preview or a split bill

Test Suites: 1 passed, 1 total
Tests:       174 skipped, 1 passed, 175 total
Snapshots:   0 total
Time:        8.196 s
Ran all test suites matching /tests\/unit\/DebugUtilsTest.ts/i with tests matching "returns report action that contains errors".

**Review by neil-marcellini — DISMISSED** [review]
Looks good thanks. The performance check is failing due to some weird merge conflict issue. I'm re-running it, but if it fails again we'll need to investigate more deeply.

**Comment by neil-marcellini** [comment]
@SIMalik I would try merging main into this PR. This merge is failing.

```
HEAD is now at a26cfb45889 Merge 38c543159587474035ee77f06f8b7b34f1202d6e into e4969b22e7dbb1f6a200cc587ced4ab665415c0e
```

**Comment by SIMalik** [comment]
> @SIMalik I would try merging main into this PR. This merge is failing.
> 
> ```
> HEAD is now at a26cfb45889 Merge 38c543159587474035ee77f06f8b7b34f1202d6e into e4969b22e7dbb1f6a200cc587ced4ab665415c0e
> ```

Hi @neil-marcellini 

I went ahead and merged the main branch into the feature branch (issue-47874). The merge completed successfully with no conflicts. I have also pushed the updated branch. The latest commit hash is 30f43f214da, and the branch is now fully up to date with main.

Please let me know if there’s anything else I should address or if any further steps are needed on this.

Thanks,

**Comment by neil-marcellini** [comment]
@SIMalik looks like there are conflicts again

**Comment by SIMalik** [comment]
@neil-marcellini @ntdiary 

Conflicts removed.

After code change:
47874-after-2

Before code change:
47874-before-2

**Comment by SIMalik** [comment]
> @SIMalik, this message?
> 
> image
> Don't worry, just click "OK" to ignore it. I see it every time I open the project in Xcode. :) Have there been any other fatal errors during compilation?

@ntdiary 
macOS: 13.7
Xcode: 14.3.1
Swift: 5
I have facing following errors during build.

build-errors1

**Review by neil-marcellini — APPROVED** [review]
Ok good to go!

**Comment by neil-marcellini** [comment]
The changed files check is failing but none of those files were changed in this PR, so they should be handled elsewhere.

**Comment by SIMalik** [comment]
@neil-marcellini @ntdiary

After deployment on staging
47874-staging-woking

**Pull request merged**
