### PR TITLE
Fix up workspace routes

### PR DESCRIPTION
**Pull request by marcaaron**
cc @parasharrajat we didn't really implement this 100% correctly as the routes need to be hooked up to the policy

### Details
- Hooks the workspace sidebar up to the chosen policy
- Enables tapping on that policy in `/settings`

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/168732

### Tests
1. Create a new workspace

2. Verify you are redirected to the `workspace/:policyID/card` route + the sidebar has the workspace name
3. Close the modal
4. Navigate to `/settings` by clicking on your avatar
5. Verify the workspace appears in `/settings`/
6. Tap on the workspace name

7. Verify you are brought back to the `workspace/:policyID/card` route

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by parasharrajat** [comment]
Sorry, didn't know about that part.

**Review by MariaHCD — COMMENTED** [review]
Looks great! Just one thing I noticed - after creating the workspace, and then dismissing the WorkspaceCardPage modal, the NewWorkspacePage is still shown:

Expensify cash

**Comment by marcaaron** [comment]
>Looks great! Just one thing I noticed - after creating the workspace, and then dismissing the WorkspaceCardPage modal, the NewWorkspacePage is still shown:

Nice, agree that seems wrong.

**Comment by marcaaron** [comment]
Updated

**Review by MariaHCD — APPROVED** [review]
🎊

**Pull request merged**
