### PR TITLE
[No QA] Use uuid to generate branch name in updateProtectedBranch

### PR DESCRIPTION
**Pull request by roryabraham**
### Details
Discussed in slack [here](https://expensify.slack.com/archives/C07J32337/p1656603628969179?thread_ts=1656578983.148269&cid=C07J32337).

### Fixed Issues
$ https://github.com/Expensify/App/issues/9638

### Tests
CP this PR and verify that it works as expected.

### CODE REVIEW

**Comment by roryabraham** [comment]
Put on HOLD because some testing shows that environment variables are not available until later steps: https://github.com/Andrew-Test-Org/Public-Test-Repo/runs/7135686588?check_suite_focus=true

**Review by luacmartins — APPROVED** [review]
LGTM! Hopefully this will stop cascading failures. Also thanks for DRYing the code :)

**Review by amyevans — APPROVED** [review]

**Review by sketchydroide — APPROVED** [review]

**Comment by roryabraham** [comment]
Going to manually CP this to test it out.

**Comment by roryabraham** [comment]
This seems to have worked fine 🎉 https://github.com/Expensify/App/pull/9644

However, the CP failed, probably again due to https://github.com/Expensify/App/issues/9640

**Pull request merged**
