### PR TITLE
Remove middle name field from Additional Details page

### PR DESCRIPTION
**Pull request by Luke9389**
### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/137514

### Tests / QA Steps

- [ ] Verify that no errors appear in the JS console

### QA Steps

1. Sign into any account on New Dot
2. Add a bank account by going to Settings > Payments > Add Payment Method > Bank Account
3. Go through the Onfido identity check with a real ID.
4. When the Additional Details page shows, _verify_ that there's no field to enter a Legal Middle Name

### CODE REVIEW

**Comment by Luke9389** [comment]
@neil-marcellini, no test steps just yet. Standby :)

**Review by neil-marcellini — APPROVED** [review]
I wasn't able to get through the Onfido flow either, but I edited [these lines](settings/payments/enable-payments) on the enable payments page and when I navigated to `settings/payments/enable-payments` I was able to verify that the middle name field is gone and everything looks good.

**Comment by Luke9389** [comment]
Awesome! Thanks. Feel free to grab that merge commit ;)

**Comment by mvtglobally** [comment]
@Luke9389 @yuwenmemon
image - 2022-03-01T112326 400

**Pull request merged**
