### PR TITLE
[P2P Distance] Rate currency doesn't match expense currency

### PR DESCRIPTION
**Pull request by nyomanjyotisa**
### Fixed Issues

$ https://github.com/Expensify/App/issues/46844
PROPOSAL: https://github.com/Expensify/App/issues/46844#issuecomment-2270164226

### Tests
Same as QA Steps
- [x] Verify that no errors appear in the JS console

### Offline tests
Same as QA Steps

### QA Steps
Pre-requisites:
Have 2 accounts with different personal currencies.
For this:

1. Log in to OD as User A
2. Go to Settings > Workspaces > Individual
3. Select your personal workspace
4. Select "Reports" from the left menu
5. Change the report currency to EUR
6. For User B, keep the default currency (e.g. USD)

Test 1:

1. Login as User A and User B to ND on different devices;
2. As User A, submit a Distance request to User B
3. As User A, navigate to the created request details
4. Verify its amount and rate are displayed in EUR
5. As User B, navigate to the same distance request details
6. Verify its amount and rate are displayed in EUR
7. As User B, submit a Distance request to User A
8. As User B, navigate to the created request details
9. Verify its amount and rate are displayed in USD
10. As User A, navigate to the same distance request details
11. Verify its amount and rate are displayed in USD

Test 2:

1. Submit a Distance request
2. Navigate to the created request details
3. Verify its rate is displayed as the selected policy currency
4. Go to the workspace setting and change the default currency to another currency (e.g. EUR)
5. Navigate to the created request details
6. Click on the "Rate" field
7. Verify that the rate shown in the "Rate" field matches the rate displayed in the "Selected Rate" modal

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Test 1

User A
Screenshot 2024-10-04 at 00 50 53

User B
Screenshot 2024-10-04 at 00 51 47

Test 2

https://github.com/user-attachments/assets/c5f40e83-2793-4ff0-8552-c62feb66623d

</details>

<details>
<summary>Android: mWeb Chrome</summary>

Test 1

User A
Screenshot 2024-10-03 at 23 32 05

User B
Screenshot 2024-10-03 at 23 34 50

Test 2

https://github.com/user-attachments/assets/81ac2f6c-588e-4f7f-8dd9-d0a62ea92a4e

</details>

<details>
<summary>iOS: Native</summary>
Test 1

User A
Screenshot 2024-10-03 at 23 42 03

User B
Screenshot 2024-10-03 at 23 41 15

Test 2

https://github.com/user-attachments/assets/67eec17c-cafa-4e15-b8c7-760514b53050

</details>

<details>
<summary>iOS: mWeb Safari</summary>

Test 1

User A
Screenshot 2024-10-03 at 23 12 21

User B
Screenshot 2024-10-03 at 23 10 55

Test 2

https://github.com/user-attachments/assets/337a5934-c0b6-4f42-9b51-b8857ebc9576

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Test 1

User A
Screenshot 2024-10-03 at 22 55 30

User B
Screenshot 2024-10-03 at 22 56 12

Test 2

https://github.com/user-attachments/assets/46b20c60-ba18-450b-b3d3-5bc9675de26e

</details>

<details>
<summary>MacOS: Desktop</summary>

Test 1

User A
Screenshot 2024-10-03 at 23 05 09

User B
Screenshot 2024-10-03 at 23 06 15

Test 2

https://github.com/user-attachments/assets/1928fc0f-a835-4cbe-bd29-4b843f7dc00a

</details>

### CODE REVIEW

**Review by paultsimura — APPROVED** [review]
LGTM ✔️

**Review by neil-marcellini — CHANGES_REQUESTED** [review]
Let's use [TransactionUtils.getCurrency](https://github.com/Expensify/App/blob/7caca60c5dc977a94d8272a871a84d0324a10b39/src/libs/TransactionUtils/index.ts#L382) instead since it accounts for modifiedCurrency.

Could we please also include a test step to click into the rate field and make sure the currencies show there properly? For example if I create a request with the policy report currency as USD and on a policy with several rates, then change the report currency to EUR, then go to edit the distance rate I think it will show the currently selected rate in EUR, when it should be USD, and all other rates should show as EUR. We need to get the rate currency for the currently selected rate from the transaction vs the policy.

You can check out [this draft PR](https://github.com/Expensify/App/pull/50001) where I'm doing something similar for the distance unit.

**Comment by neil-marcellini** [comment]
@paultsimura Yes, so in the video you showed above the problem is that the currency of the rate shows in EUR on the rate editor page, but it shows in USD on the transaction view. Let's fix that by getting the rate currency from the transaction for the currently selected rate.

I suppose it is a little confusing given that a rate in that currency doesn't exist on the policy, but I think that's less confusing than having a discrepancy between the transaction and the selected rate. The main goal is that existing distance expenses are not edited retroactively when the policy distance unit changes. If users complain or get confused then maybe we can include some informational text or re-think the pattern.

Additionally, I think we should change the prompt text on the rate editor to be unit agnostic, [like I did here](https://github.com/Expensify/App/pull/50001/files#r1790591939).

**Review by paultsimura — CHANGES_REQUESTED** [review]
Minor changes 🙏

**Review by paultsimura — CHANGES_REQUESTED** [review]

**Review by paultsimura — APPROVED** [review]

**Review by neil-marcellini — DISMISSED** [review]
I think the code looks fine and since C+ says it tests well we can go ahead and merge. We don't need to wait for the MoneyRequestConfirmationList refactor since that's a separate thing. I'll bump that one along too. 

@nyomanjyotisa we need to fix merge conflicts though. Please message me on Slack when it's updated so I can merge quickly.

**Review by neil-marcellini — APPROVED** [review]

**Pull request merged**
