### PR TITLE
Fix: integration icons next to export buttons

### PR DESCRIPTION
**Pull request by neonbhai**
### Fixed Issues
$ https://github.com/Expensify/App/issues/46981
PROPOSAL: https://github.com/Expensify/App/issues/46981#issuecomment-2273783223

### Tests

Precondition:

- Account has workspaces which are connected to QBO, NetSuite and Intacct
1. Go to Expensify
2. Go to workspace chat that is connected to QBO.
3. Submit an expense, and pay it.
4. Go to transaction thread.
5. Click on the export dropdown.
6. Note that there is QBO icon next to the buttons.
7. Click on the report header > Export.
8. Note that there is QBO icon next to the buttons.
9. Repeat Step 2 to 8 with workspaces that are connected to `Xero`, `NetSuite` and `Intacct`.

- [x] Verify that no errors appear in the JS console

### Offline tests
Same as Tests step

### QA Steps
Same as Tests step

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

Screenshot 2024-08-28 at 7 23 56 PM
Screenshot 2024-08-28 at 7 24 14 PM
Screenshot 2024-08-28 at 7 25 03 PM
Screenshot 2024-08-28 at 7 26 34 PM
Screenshot 2024-08-28 at 7 26 25 PM
Screenshot 2024-08-28 at 7 26 01 PM
Screenshot 2024-08-28 at 7 25 54 PM
Screenshot 2024-08-28 at 7 25 15 PM

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>
Screenshot 2024-08-28 at 4 48 14 PM
Screenshot 2024-08-28 at 4 48 06 PM
Screenshot 2024-08-28 at 4 46 36 PM
Screenshot 2024-08-28 at 4 46 29 PM
Screenshot 2024-08-28 at 4 44 01 PM
Screenshot 2024-08-28 at 4 43 08 PM
Screenshot 2024-08-28 at 4 43 16 PM
Screenshot 2024-08-28 at 4 43 51 PM

</details>

<details>
<summary>iOS: mWeb Safari</summary>
Screenshot 2024-08-28 at 4 44 33 PM
Screenshot 2024-08-28 at 4 48 58 PM
Screenshot 2024-08-28 at 4 48 43 PM
Screenshot 2024-08-28 at 4 44 39 PM
Screenshot 2024-08-28 at 4 46 11 PM
Screenshot 2024-08-28 at 4 46 17 PM
Screenshot 2024-08-28 at 4 41 47 PM
Screenshot 2024-08-28 at 4 42 00 PM

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

Screenshot 2024-08-27 at 11 57 26 PM
Screenshot 2024-08-27 at 11 57 17 PM
Screenshot 2024-08-27 at 11 55 56 PM
Screenshot 2024-08-27 at 11 55 28 PM
Screenshot 2024-08-27 at 11 52 03 PM
Screenshot 2024-08-27 at 11 53 34 PM
Screenshot 2024-08-27 at 11 53 46 PM
Screenshot 2024-08-27 at 11 54 22 PM

</details>

<details>
<summary>MacOS: Desktop</summary>

Screenshot 2024-08-28 at 12 08 27 AM
Screenshot 2024-08-28 at 12 08 41 AM
Screenshot 2024-08-28 at 12 46 13 AM
Screenshot 2024-08-28 at 12 46 25 AM
Screenshot 2024-08-28 at 12 49 18 AM
Screenshot 2024-08-28 at 12 49 10 AM
Screenshot 2024-08-28 at 12 48 18 AM
Screenshot 2024-08-28 at 12 48 09 AM

</details>

### CODE REVIEW

**Comment by akinwale** [comment]
@neonbhai Please fix merge conflicts.

**Comment by akinwale** [comment]
@neonbhai The Jest unit tests, lint and TypeScript Check steps are failing. Please check this.

**Comment by dubielzyk-expensify** [comment]
Can we make the icons the same size across both? I see `40x40` and `32x32`? Is that correct? 

I visually prefer the 32, though I seem to remember us choosing the 40 in some other PR. Keen to hear what @dannymcclain thinks though

**Comment by akinwale** [comment]
> @akinwale friendly bump for review

I was waiting to get Sage Intaact credentials for testing. I should be able to review today or tomorrow.

**Comment by dubielzyk-expensify** [comment]
Yeah that looks more correct to me. Let's do what @dannymcclain suggests

**Comment by akinwale** [comment]
@neonbhai Please fix merge conflicts and confirm latest design comments. Thanks.

**Comment by shawnborton** [comment]
What's the latest on this one?

**Comment by akinwale** [comment]
> What's the latest on this one?

Was waiting for @neonbhai to address the design feedback.

@neonbhai Could you please confirm that the feedback in https://github.com/Expensify/App/pull/47812#issuecomment-2377046269 has been addressed so we can move forward?

Thanks.

**Comment by dubielzyk-expensify** [comment]
I'd be keen to hear what @shawnborton and @dannymcclain thinks here, but I think the two alternatives should be:
image

And I initially thought option 1 looks better, but now I'm wondering if 2 is better. 

As for the NewSuite and Sage icons, we wouldn't wanna make any special rules for them, but we could tweak the image itself if we wanted. 

I'll let the other designers chime in

**Comment by shawnborton** [comment]
I think I lean towards option 2 (40px icon), as that is most consistent with how we handle other logo icons for things like banks.

**Comment by dannymcclain** [comment]
That works for me! We originally made them slightly smaller to help them harmonize with other menu items that use our regular icon style in case they show up together in one menu—if that's not a major concern I'm super down to go with the 40px integration icon (Option 2).

**Comment by dubielzyk-expensify** [comment]
That looks good to me 👍

**Comment by shawnborton** [comment]
Yup, looks great!

**Comment by shawnborton** [comment]
Friendly bump @akinwale

**Comment by akinwale** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>



</details>

<details>
<summary>Android: mWeb Chrome</summary>



</details>

<details>
<summary>iOS: Native</summary>



</details>

<details>
<summary>iOS: mWeb Safari</summary>



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/2cf15ad6-97a7-479e-a1f0-b303bea9959e

</details>

<details>
<summary>MacOS: Desktop</summary>



</details>

**Review by akinwale — APPROVED** [review]
LGTM.

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
