### PR TITLE
When using the Tab button on the keyboard the focus does not appear correctly

### PR DESCRIPTION
**Pull request by Justicea83**
### Fixed Issues

$https://github.com/Expensify/App/issues/8608

### Tests

- [ ] Sign In to NewDot on Web or Desktop
- [ ] Press the tab key on your keyboard
- [ ] Ensure the focus doesn't disppear after the 3rd stroke,
- [ ] Verify from the screenshots below

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps

- [ ] Sign In to NewDot on Web or Desktop
- [ ] Press the tab key on your keyboard
- [ ] Ensure the focus doesn't disppear after the 3rd stroke,
- [ ] Verify from the screenshots below

#### Web

https://user-images.githubusercontent.com/26106822/169570977-34030664-f6e1-4d20-8aba-01925b5bb7ea.mp4

#### Mobile Web

https://user-images.githubusercontent.com/26106822/169570066-82d237f2-54e0-4a05-a9aa-a94446f91e3a.mp4

#### Desktop

https://user-images.githubusercontent.com/26106822/169569858-65cc8735-a3d5-4837-83d6-211327f13d0b.mp4

### CODE REVIEW

**Review by alex-mechler — CHANGES_REQUESTED** [review]
I don't think this is how we want to fix it. We shouldn't just be removing styles (without discussion no less) to fix a tab indexing issue.

**Comment by Justicea83** [comment]
> I don't think this is how we want to fix it. We shouldn't just be removing styles (without discussion no less) to fix a tab indexing issue.

I've searched through codes and I didn't really find any convincing styles that we could remove, I'll be glad if you can throw links or resources @alex-mechler

**Comment by Justicea83** [comment]
Yes this is a tab indexing issue, but inpecting the DOM thoroughly i discovered that the tab indices are very correct, but for some strange reasons the tab focus disappears, so based on the research i did, I realized that removed styles were the issue in this case. As I said earlier, I'll be glad if you can throw some links or resources.

**Comment by Justicea83** [comment]
Am going to raise this in `#design`, because even with those styles applied it was looking great either.

**Comment by Justicea83** [comment]
@alex-mechler , i've been researching a lot about this and i can't quite figure out how to change the color of the highlighting on the desktop app, I'll be glad if you can throw some links or resources if you have any

**Comment by alex-mechler** [comment]
The `box-shadow` attribute of these styles will change the coloring or size https://github.com/Expensify/App/blob/fd29904ef9857e6c5b858da04d52c8dec0d5c369/web/index.html#L35-L42

**Comment by Justicea83** [comment]
Thanks, looking into it again

**Comment by Justicea83** [comment]
> The `box-shadow` attribute of these styles will change the coloring or size
> 
> https://github.com/Expensify/App/blob/fd29904ef9857e6c5b858da04d52c8dec0d5c369/web/index.html#L35-L42

These styles make the highlight disappear for a moment, i just can't tell why

**Comment by alex-mechler** [comment]
Is it possible that the element is losing focus? Could be tied to a rerender or similar

**Comment by Justicea83** [comment]
> Is it possible that the element is losing focus? Could be tied to a rerender or similar

Investigating into this because its so strange

**Comment by Justicea83** [comment]
Still researching on the styles to apply, as everything I've applied so far doesn't seem to work

**Comment by Justicea83** [comment]
Not overdue

**Pull request closed without merging**
