### PR TITLE
Enable haptic feedback on the NumberPad

### PR DESCRIPTION
**Pull request by parasharrajat**
### Fixed Issues

$ https://github.com/Expensify/App/issues/7128

### Tests | QA Steps
1. Open App on Android and IOS **devices**.
2. Click FAB (:heavy_plus_sign: ).
3. Open request money.
4. Add some value via the number pad. 
5. All keys should have haptic/vibration feedback on each key press and on long press.

- [x] Verify that no errors appear in the JS console

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

image

#### Mobile Web

image

#### Desktop

image

#### Android

image

### CODE REVIEW

**Review by NikkiWines — COMMENTED** [review]
I think this looks good though it's hard to tell by testing on a sim. @parasharrajat I think your QA steps should say something about being sure to test this on a physical device and ensuring that haptic feedback actually occurs.

**Comment by parasharrajat** [comment]
Oh yeah. You are correct, I forgot to add a device point.  Doing now.

**Comment by parasharrajat** [comment]
Bump @NikkiWines .

**Comment by NikkiWines** [comment]
@parasharrajat, I'm confused. Your QA steps still don't mention anything about haptic feedback

**Comment by parasharrajat** [comment]
Sorry, Just added it. @NikkiWines

**Review by NikkiWines — APPROVED** [review]
👍

**Pull request merged**
