### PR TITLE
Removing draft comments param

### PR DESCRIPTION
**Pull request by chiragsalian**
### Details
The draftComments param for getSideBarOptions was removed [here](https://github.com/Expensify/App/commit/2a591b5efb820392c22d349179bc6313cb9716d6#diff-733528d957ae6a80eb863637fa5d54278c89c6121998f3574fa8c0aba935daebL657). But at that time the usages were still passing draftComments so the method was receiving params in wrong order. The fixes here should correct that.

### Fixed Issues

$ https://github.com/Expensify/App/issues/6231

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web
1. Go to the App. Select #focus in preferences.
2. Confirm only pinned chats show.

### CODE REVIEW

**Review by thienlnam — COMMENTED** [review]
Changes look good, looks like you just need to update the method in the unit test as well

**Comment by thienlnam** [comment]
Oh lol oops 🤦  nevermind

**Comment by thienlnam** [comment]
You still need to update this right? Since it passes report_draft_comments https://github.com/Expensify/App/blob/5763378376d01ed0e019290092469b5233e5a98a/tests/unit/OptionsListUtilsTest.js#L597-L597

**Review by aldo-expensify — CHANGES_REQUESTED** [review]
I think we should remove these lines too:

https://github.com/Expensify/App/blob/13bb449d8eaf195d2184c32d436f396cc897d619/src/pages/home/sidebar/SidebarLinks.js#L277-L279

The prop `draftComments` is not used anymore.

**Comment by chiragsalian** [comment]
@thienlnam both of those codes you linked are not in main branch 😬  - [file](https://github.com/Expensify/App/blob/main/tests/unit/OptionsListUtilsTest.js#L597-L597)

**Comment by chiragsalian** [comment]
@aldo-expensify, yup good catch.

**Review by aldo-expensify — APPROVED** [review]
Looks good to me!

**Review by thienlnam — APPROVED** [review]
Oops, I guess I should start updating my local branch to main haha

**Pull request merged**
