### PR TITLE
fix/14784: Settings - Changed name is not saved under Display name page

### PR DESCRIPTION
**Pull request by tienifr**
### Fixed Issues
$ https://github.com/Expensify/App/issues/14784
PROPOSAL: [14784(COMMENT)](https://github.com/Expensify/App/issues/14784#issuecomment-1415302899)

### Tests
- Verify changed name is saved under Display name page

1. Click on >Setting>Profile > Display name
2. Change name>Click Save
3. Click the back arrow
4. Click the Display name again
5. Verify the new name matches the old name

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly
1. Go to Setting > Workspace > Connect bank account > Connect manually 
2. Fill the form and go to step 4
3. Check "Somebody else owns more than 25% of" and filling out the Identity Form part way
4. Refresh the page to ensure that the checkbox is still checked and the identify form is rendered with the values you entered

- [x] Verify that no errors appear in the JS console

### QA Steps

- Verify changed name is saved under Display name page

1. Click on >Setting>Profile > Display name
2. Change name>Click Save
3. Click the back arrow
4. Click the Display name again
6. Verify the new name matches the old name

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly
1. Go to Setting > Workspace > Connect bank account > Connect manually 
2. Fill the form and go to step 4
3. Check "Somebody else owns more than 25% of" and filling out the Identity Form part way
4. Refresh the page to ensure that the checkbox is still checked and the identify form is rendered with the values you entered
- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

- Verify changed name is saved under Display name page

https://user-images.githubusercontent.com/113963320/217036986-5073633b-fdff-4630-945d-20f613110ed1.mp4

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly

https://user-images.githubusercontent.com/113963320/217037007-c85879f7-ced3-4dd4-8eea-3648cb66cc93.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

- Verify changed name is saved under Display name page

https://user-images.githubusercontent.com/113963320/217037063-f86aac50-a06b-472b-9ce1-80373f9eef5e.mp4

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly

https://user-images.githubusercontent.com/113963320/217037105-581d6733-2429-4c85-a643-42a84f10a7bb.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

- Verify changed name is saved under Display name page

https://user-images.githubusercontent.com/113963320/217037174-e5a0cad8-c2bc-4c7d-937b-d4f1ceafb775.mp4

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly

https://user-images.githubusercontent.com/113963320/217037257-d8ad3bd9-20dc-46fa-a716-b20767601e62.mp4

</details>

<details>
<summary>Desktop</summary>

- Verify changed name is saved under Display name page

https://user-images.githubusercontent.com/113963320/217037279-a0d9e5f6-d082-453a-99d8-c9f5665d7196.mp4

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly

https://user-images.githubusercontent.com/113963320/217037321-79323951-b22e-4ff2-8840-249c46a0bbd2.mp4

</details>

<details>
<summary>iOS</summary>

- Verify changed name is saved under Display name page

https://user-images.githubusercontent.com/113963320/217037375-ed072204-84c2-4b2f-bf7c-a4142e8d87dc.mp4

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly

https://user-images.githubusercontent.com/113963320/217037415-729c6e9c-aeb7-4ed7-a9cf-c9e40ce7a3ac.mp4

</details>

<details>
<summary>Android</summary>

- Verify changed name is saved under Display name page

https://user-images.githubusercontent.com/113963320/217037594-f31ef19f-6938-42b1-a199-4e58ca6b1ed7.mp4

- Verify the form refactor for ACH Contract Step of Add Bank Account form works expectedly

https://user-images.githubusercontent.com/113963320/217037623-4a4dfdaf-787d-4114-9b8b-9fa0e141399e.mp4

</details>

### CODE REVIEW

**Comment by tienifr** [comment]
Hi @techievivek, I have completed the PR. Please help me review it. Thank you!

**Comment by Beamanator** [comment]
@sobitneupane requesting you as a reivewer since you're the C+ on the fixed issue. Do you have time to review this soon since this is quite an annoying but in many forms?

**Comment by Beamanator** [comment]
@tienifr are you up to date with `main`? I see your fork says it's 99 commits behind `Expensify:main`

**Comment by sobitneupane** [comment]
Thanks @Beamanator.

Reviewing it now.

**Review by sobitneupane — APPROVED** [review]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/25876548/217236877-e0106040-f742-46fa-a065-b2f0f97fa4f1.mov

https://user-images.githubusercontent.com/25876548/217236761-14bdc641-949a-48e9-a4d0-da03bd96891c.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/25876548/217239895-e30d08ee-1dcb-4c7a-9a76-765ed8032004.mov

https://user-images.githubusercontent.com/25876548/217240470-11c7d76c-1b4c-4821-a321-851024d9726c.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/25876548/217239536-63fcf5bd-8581-4650-b774-94082bfc71c3.mov

https://user-images.githubusercontent.com/25876548/217240179-c7ca5d5a-d075-4ced-b4e9-1783b35af1ff.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/25876548/217236790-759e56ee-181b-4319-b273-67bbe6f94729.mov

https://user-images.githubusercontent.com/25876548/217236952-6b41b863-826e-4666-84a1-d9ab24befba9.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/25876548/217238141-7ca7a19f-35a1-4ae0-95de-794f22a67920.mov

https://user-images.githubusercontent.com/25876548/217238428-4507e671-e2e9-438f-bbf3-87de83dd90fa.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/25876548/217238152-ac96492b-f001-4432-bb59-605888ead3a7.mov


https://user-images.githubusercontent.com/25876548/217239510-8f5f2f18-9192-48eb-bdcf-6b1dad8728b5.mov

</details>

**Comment by sobitneupane** [comment]
@techievivek Changes look good and tests well.

I have tested Step 4 (ACHContractStep) form in Connect bank account flow with some dummy data. I will also like to request QA team to test it thoroughly. For more details about QA Steps: https://github.com/Expensify/App/pull/13501

**Review by Beamanator — APPROVED** [review]
:shipit:

**Comment by Beamanator** [comment]
@sobitneupane thanks for the review!

I think Step 4 is covered in the QA steps in the OP, right?

**Pull request merged**
