### PR TITLE
Remove slack notifications for QA

### PR DESCRIPTION
**Pull request by iwiznia**
<If necessary, assign reviewers that know the area or changes well. Feel free to tag any additional reviewers you see fit.>

### Details
<Explanation of the change or anything fishy that is going on>

### Fixed Issues
https://github.com/Expensify/Expensify/issues/157452

### Tests
None, we can check the notifications are gone when we merge it

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
Yep, this looks right to me 👍

**Review by alex-mechler — APPROVED** [review]
LGTM, but holding off merging until we see if QA uses them

**Comment by roryabraham** [comment]
I think they said they _are_ using them, so we'll hold off until we have the new checklists in place (should be very soon, today or tomorrow).

**Comment by roryabraham** [comment]
Merging this, they shouldn't need these anymore.

**Pull request merged**
