### PR TITLE
fix workspace save btn float issue

### PR DESCRIPTION
**Pull request by thesahindia**
### Details
Fixed workspace general settings save button float issue

### Fixed Issues

$ https://github.com/Expensify/App/issues/7140

### Tests

- [x] Verify that no errors appear in the JS console

### QA Steps

1. Open app
2. Navigate to Workspace > General settings
3. Write something inside Name field (open keyboard)
4. Verify the save button floats

- [x] Verify that no errors appear in the JS console

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [x] iOS
- [ ] Android

#### iOS

Screenshot 2022-01-15 at 1 33 39 AM

### CODE REVIEW

**Comment by rushatgabhane** [comment]
@thesahindia could you please update the QA steps, and add iOS video/screenshot? Appreciate it!

**Comment by thesahindia** [comment]
Ah I didn't press the update button 🤦🏻‍♂️. Updated now.

**Review by rushatgabhane — APPROVED** [review]
Sorry this one got buried in the notifications 😅

LGTM! 🎉 @chiragsalian

**Review by chiragsalian — APPROVED** [review]
LGTM

**Pull request merged**
