### PR TITLE
[WIP] [No QA] Only deploy to staging after staging branch has been updated

### PR DESCRIPTION
**Pull request by roryabraham**
cc @deetergp Since you're digging into some GH Actions stuff right now too.

### Details
For a while now, we've been deploying the master branch to staging. This was always meant to be temporary just to get deploys working, for a number of reasons. This PR changes the deploy process such that we deploy to staging from the staging branch, and only after the staging branch has been successfully updated. _Why,_ you ask?

1. This will pave the way to allow us to build a CP process. We have been trying to get by without one for a couple weeks now, and so far have not had a single day in which all PRs pass QA and there are no open deploy blockers. Therefore we haven't run a single production deploy since we started using the new QA process. I think this alone is proof that we need some way to CP or revert changes.
1. This will simplify the process of comparing changes between releases and has the potential to lead to a number of simplifications in the deploy-related JS code. (not included in this PR because I don't want it to get too big to review)
1. Also, it conceptually makes sense that the code on staging should be from the staging branch, and the code on production should be from the production branch.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/157916

### Tests
Added unit tests for new Javascript action. To live-test these changes:

1) Make sure that the `StagingDeployCash` is _not_ locked.
2) Merge two PRs in quick succession and verify that:

- [ ] `preDeploy::version` runs for both pull requests, but due to turnstyle only one of them begins. Let's call the one that starts "run A", and the one that waits "run B"
- [ ] (run A) In `preDeploy::version`, a new `BUILD` version is created for the first PR
- [ ] (run A) An automerge PR for that version is created against the `master` branch.
- [ ] (run A) Tags are not pushed, so a staging deploy does not happen yet.
- [ ] (run B) At this point, it's expected that `runB::preDeploy` will begin, since "run A" will have finished.
- [ ] (run B) `preDeploy` should check for open automerge _PRs_, and should find that one is open! It should then _wait_ for any automerge _workflow runs_ to _begin_ (using sleep).
- [ ] (run A) `automerge` workflow should begin for the PR created in `runA::preDeploy::version`
- [ ] (run B) `runB::preDeploy` Should start waiting for any automerge workflow runs to _finish_ (wait-my-workflow).
- [ ] (run A) Meanwhile, the automerge PR created by run A should be merged.
- [ ] (run B) Run B should wait for any `deploy::stagingDeploy` jobs to start (using sleep)
- [ ] (run A) `runA::preDeploy::updateStaging` should start, and a PR should be created to merge master into staging
- [ ] (run A) The PR from the previous step should be auto-merged.
- [ ] (run A) `runA::deploy::deployStaging` should start, tag the version, and push tags. A staging deploy should begin on all platforms
- [ ] (run B) `runB::preDeploy::version` should now be free to create another new `BUILD` version. There should be no version conflict
- [ ] (run B) finishes with a staging deploy via the normal process: `preDeploy::version` -> `automerge::master` -> `preDeploy::updateStaging` -> `automerge::staging` -> `deploy::deployStaging`

WOW that's complicated. Maybe we need to step back and rethink this a bit... 😅

### CODE REVIEW

**Comment by roryabraham** [comment]
Made this a WIP because as I was reading the testing steps I found it was too damn complex

**Comment by roryabraham** [comment]
And those testing steps don't even include testing for when we lock the staging deploy

**Comment by roryabraham** [comment]
Closing this for now. @AndrewGable and I came up with a better idea

**Comment by Jag96** [comment]
Closing per last comment, feel free to reopen if we end up needing this

**Pull request closed without merging**
