### PR TITLE
Remove port to fix Flipper

### PR DESCRIPTION
**Pull request by amyevans**
### Details
Removes the use of a custom port, which was breaking Flipper.
Note: the port was originally introduced in https://github.com/Expensify/App/pull/11813 because it was believed to be the reason iOS and Android couldn't run simultaneously, but there's discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1677948615578189?thread_ts=1677165853.274999&cid=C01GTK53T8Q) and [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1680121805775169) that that's not the root cause. The test steps ensure we don't introduce a regression related to running platforms simultaneously.

cc @AndrewGable @luacmartins 

### Fixed Issues
$ https://github.com/Expensify/App/issues/21239

### Tests
1. Delete your current pods (`rm -rf ios/Pods`)
2. Reinstall them (`cd ios && pod install`)
3. Run iOS, Android, Desktop, and Web all at the same time in different terminal tabs
4. Verify any changes are hot reloaded by all four clients at once (verifying metro and webpack builds are OK to run at once)
5. Open Flipper
6. Verify you can inspect the React component tree in Flipper

- [x] Verify that no errors appear in the JS console

### Offline tests
N/A

### QA Steps
No QA, this affects dev only

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/7277067/d8a0fe41-455d-4700-ad7d-4b4038487564

</details>

<details>
<summary>Mobile Web - Chrome</summary>

N/A

</details>

<details>
<summary>Mobile Web - Safari</summary>

N/A

</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/7277067/d8a0fe41-455d-4700-ad7d-4b4038487564

</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/7277067/d8a0fe41-455d-4700-ad7d-4b4038487564

</details>

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/7277067/d8a0fe41-455d-4700-ad7d-4b4038487564

</details>

### CODE REVIEW

**Comment by amyevans** [comment]
> npm has a package.json file and a package-lock.json file. It seems you updated one without the other, which is usually a sign of a mistake. If you are updating a package make sure that you update the version in package.json then run npm install

This PR updates the scripts, not package(s), so no changes to `package-lock.json` is expected

**Comment by abdulrahuman5196** [comment]
@amyevans  Curious question. Does everyone need to reinstall the pods after we push this change?

**Comment by amyevans** [comment]
As far as I'm aware, no. To be honest I just copied the exact test steps from https://github.com/Expensify/App/pull/11813 to ensure we don't have a regression for the scenario the PR intended to fix. I think removing and reinstalling pods was just an extra precaution to ensure a fresh slate.

**Review by luacmartins — DISMISSED** [review]
LGTM

@amyevans did you also have to remove the port [here](https://github.com/Expensify/App/blob/a7b6838c0a502f6fcdae2c0f4bcc57c0ad0a72d5/ios/NewExpensify.xcodeproj/project.pbxproj#L548) to get Flipper working?

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>






</details>

<details>
<summary>Mobile Web - Chrome</summary>






</details>

<details>
<summary>Mobile Web - Safari</summary>







</details>

<details>
<summary>Desktop</summary>







</details>

<details>
<summary>iOS</summary>






</details>

<details>
<summary>Android</summary>






</details>

**Comment by abdulrahuman5196** [comment]
@amyevans  I found a issue while running this,
If i run web first(web took 8081 port) and then iOS. iOS is throwing the below error

Screenshot 2023-06-24 at 6 59 47 PM


But its working the other way. If iOS is ran first and then web, web choose 8082 port automatically and starts working.

This comment could be related - https://github.com/Expensify/App/pull/21243#issuecomment-1603008306

**Comment by luacmartins** [comment]
@amyevans did you get a chance to look into @abdulrahuman5196's comment above?

**Comment by amyevans** [comment]
> @amyevans did you get a chance to look into @abdulrahuman5196's comment above?
I haven't yet 😅. It's on my list for the next day or two but need to clear out higher priority items first

**Comment by luacmartins** [comment]
Np! Thanks for the update!

**Comment by amyevans** [comment]
> If i run web first(web took 8081 port) and then iOS. iOS is throwing the below error

I didn't hit that error, although web took 8080 for me (and pretty much always does).

I tried hardcoding `--port=8081` for iOS and android and that worked for me, but I'm wondering if it will for you (since web is selecting 8081 for you). Maybe we need to hardcode a port for every platform?

**Comment by abdulrahuman5196** [comment]
@amyevans 

> I didn't hit that error, although web took 8080 for me (and pretty much always does).

If web was started first yes, it will take 8080.
Could you kindly try this order Desktop, web, ios

Desktop would take 8080
Web would take 8081
ios would fail to take 8081.

>I tried hardcoding --port=8081 for iOS and android and that worked for me, but I'm wondering if it will for you (since web is selecting 8081 for you)

This also might not work since 8081 is already taken.

>Maybe we need to hardcode a port for every platform?

Maybe that could work. Need to test it. But will it hot reload all platforms if required? I think this also could work, but have to anyways check.

**Comment by lindboe** [comment]
Another suggestion: because adjusting ports for React Native everywhere one might build is difficult, and many tools may expect 8081, update the port-finding logic used by web and desktop to exclude 8081 from the list of options.

**What I thought we could do**
Everywhere that `portfinder.getPortPromise` exists (`config/webpack/webpack.dev.js` and `desktop/start.js`), add the `reserved` option with the value `[8081]`, which was added in this PR: https://github.com/http-party/node-portfinder/pull/18.

**The problem**
While that PR was merged at one point, I can't find any mention of it now. I think it would be a good idea to open an issue or PR to get this functionality back to that library, as it would be very useful here. We could also patch it in ourselves for now, but I'm not sure if that implementation in the original PR still applies cleanly.

**Comment by luacmartins** [comment]
What's the plan here? Are we still exploring other solutions?

**Comment by amyevans** [comment]
Yeah, still exploring solutions. 

Looking at [the docs for node-portfinder](https://github.com/http-party/node-portfinder#ports-search-scope), it says
```
By default portfinder will start searching from 8000 and scan until maximum port number (65535) is reached.

You can change this globally [...] by passing optional options object on each invocation:

portfinder.getPort({
    port: 3000,    // minimum port
    stopPort: 3333 // maximum port
}, callback);
```

And we are already utilizing this to pass `8080` as our minimum port (e.g. [here](https://github.com/Expensify/App/blob/main/desktop/start.js#L6)). So tweaking @lindboe's suggestion, I think we can:
* Change that from `8080` to `8082`, which will force web and desktop to be 8082 or higher
* Leave the rest of this PR as is (remove hardcoded ports on iOS/Android)

I'll spend some time testing that though.

**Comment by lindboe** [comment]
Yeah, I'm concerned it's very possible some tooling might expect 8080 for web/desktop when they're launched in isolation since that's been the default for a while, and is typically the port used for similar web apps. But I'm not sure.

**Comment by amyevans** [comment]
Okay I pushed that change to the PR since it's testing well for me. Confirmed that hot reloading, Flipper, Storybook, and the help docs site work... what else would be good to check? 🤔 (I definitely share the concern about there being some assumptions made somewhere that the port is `8080` 😬)

**Review by luacmartins — APPROVED** [review]
LGTM and works well. We should probably announce this to the team so they are aware of the changes, since ports can change and accessing the App would require a change in the url

**Comment by abdulrahuman5196** [comment]
Oh sorry. I was not aware of this PR being ready for review. My bad. Will check and update within a day.

**Comment by amyevans** [comment]
No worries! And thanks!

**Comment by abdulrahuman5196** [comment]
@amyevans I tested the follows and hot reload and others are working properly.
One inconsistency I noted is,

If we start, assume this order web, desktop
Now web takes port 8082, and assuming desktop takes 8083

On second time if we start in reverse order like, desktop and web
Now web takes port 8083, and assuming desktop takes 8082

Now on second time, the app is going on fresh login flow since port number is different. 
This might cause confusions, Are we ok with this change of port behaviour?

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



https://github.com/Expensify/App/assets/46707890/8b4c6f6e-69e6-46b6-b51f-7cc6a768e229




https://github.com/Expensify/App/assets/46707890/41be9191-d4dd-4958-afad-6251422b894c

</details>

<details>
<summary>Mobile Web - Chrome</summary>



Same as Web


</details>

<details>
<summary>Mobile Web - Safari</summary>



Same as Web



</details>

<details>
<summary>Desktop</summary>





Same as Web

</details>

<details>
<summary>iOS</summary>




Same as Web

</details>

<details>
<summary>Android</summary>



Same as Web





</details>

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours.

🎀 👀 🎀
C+ Reviewed

**Review by cristipaval — APPROVED** [review]

**Comment by amyevans** [comment]
Announced the change in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1690224959854549

**Comment by burczu** [comment]
@cristipaval @luacmartins @abdulrahuman5196 @amyevans It seems this PR introduced a regression fixed [here](https://github.com/Expensify/App/pull/24638) - you have missed two other places where the port should have been changed.

**Pull request merged**
