### PR TITLE
Wrapped forgot link to content

### PR DESCRIPTION
**Pull request by akshayasalvi**
@mountiny Feel free to review whenever the n6-hold is lifted :) I am keeping it in the draft right now.

### Details
- Wrap forgot link width to content instead of full width. 

### Fixed Issues

$ https://github.com/Expensify/App/issues/5355

### Tests
1. Tested the link clickability in all platforms

### QA Steps
1. Go to login and enter an existing email address
2. In the password page, try to click outside the forgot link in the same row. 
3. It shouldn't allow you to click except for the width of the `forgot?` textlink.

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/57435789/135334224-44ac30ff-1a8e-439b-874f-7d8fb4578763.mov

#### Mobile Web

https://user-images.githubusercontent.com/57435789/135334391-39bd382c-6b7a-4e4d-84a0-b9cef13d165d.mov

#### Desktop

https://user-images.githubusercontent.com/57435789/135334420-f6e434ed-9499-4999-ad42-0f2fabb97106.mov

#### iOS

https://user-images.githubusercontent.com/57435789/135335571-41b6a31e-200e-4c94-91d6-f042bca8073a.mov

#### Android

https://user-images.githubusercontent.com/57435789/135334720-a52fa9af-bc19-4043-8e21-7ed164956c64.mov

### CODE REVIEW

**Comment by mountiny** [comment]
@akshayasalvi Great Job, will look into this in coming days!

**Review by mountiny — APPROVED** [review]
Simple change, good job @akshayasalvi, thank you for this. We will wait for the hold to be lifted, sorry for extension, there should be bonus included as a compensation for the time you wait.

**Comment by mountiny** [comment]
Feel free to make this ready for a review.

**Comment by akshayasalvi** [comment]
> Feel free to make this ready for a review.

Is the `n6-hold` lifted?

**Comment by akshayasalvi** [comment]
> Simple change, good job @akshayasalvi, thank you for this. We will wait for the hold to be lifted, sorry for extension, there should be bonus included as a compensation for the time you wait.

Just read this. Thank you :) Appreciate your kind words.

**Review by mountiny — APPROVED** [review]

**Review by mountiny — APPROVED** [review]
LGTM! @akshayasalvi Great work on this one and thank you very much for your patience with the `n6-hold`.

**Pull request merged**
