### PR TITLE
36038 fix selection list footer extra padding 2

### PR DESCRIPTION
**Pull request by lukemorawski**
### Details

This PR fixes extra padding below Referral banner in Search list.
The issue was due to the fact that the safe area bottom padding was added two times - one by SelectionList and second by ScreenWrapper. After further investigation it turned out that this problem occurs in many other pages/components. In most cases it isn't as much as pronounced as on the SearchPage, as it's just an extra large space on the bottom of the list.
Every screen that uses SelectionList have been inspected and corrected if necessary.

### Fixed Issues

$ https://github.com/Expensify/App/issues/36038
PROPOSAL: no proposal

### Tests

- same as QA
- [ ] Verify that no errors appear in the JS console

### Offline tests

same as QA 

### QA Steps

- [ ] open app on IOS and tap search
- [ ] observe the referral banner at the bottom
- [ ] Other places where changes where introduced:
- [ ] Request Money Participant Selection Step
- [ ] Send Money Participant Selection Step
- [ ] Money Request Currency Selector
- [ ] Workspace Invite Page
- [ ] Room Invite Page
- [ ] Room Members Page
- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/134388952/5a459f57-c0e9-4374-9da2-1cf368d08477

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/134388952/f7219d13-ede9-4e10-bc30-21e42e93ea44

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/134388952/3ed1929d-34c0-4b02-b765-dc73063d58e8

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/134388952/a758c029-db69-467a-ae77-29b43d20f0dd

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/134388952/30d6a16c-fa25-4dbd-835e-bd6eb59debb5

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/134388952/c6d81427-3d0e-4c6c-96d2-1909f93f1c02

</details>

### CODE REVIEW

**Comment by abdulrahuman5196** [comment]
@lukemorawski Why are we updating Gemfile.lock and ios project file? If its by mistake can we remove the same?

**Comment by lukemorawski** [comment]
@abdulrahuman5196 had some problems with building the iOS app, and eventually had to update those files, but yeah I guess we can ignore them.

**Comment by abdulrahuman5196** [comment]
> @lukemorawski Why are we updating Gemfile.lock and ios project file? If its by mistake can we remove the same?

@lukemorawski We should remove them from this PR actually. Can you kindly update the PR removing them?

**Comment by lukemorawski** [comment]
> > @lukemorawski Why are we updating Gemfile.lock and ios project file? If its by mistake can we remove the same?
> 
> @lukemorawski We should remove them from this PR actually. Can you kindly update the PR removing them?

not sure if I can/should remove the ios project file. Instead I'll just merge `main` and substitute them with their latest revisions

**Comment by lukemorawski** [comment]
@abdulrahuman5196 Should be good now

**Comment by abdulrahuman5196** [comment]
Seems the changes are spread across components. Need sometime to review and test on this.
Will update here once done. I am allocating time assuming this is not high priority. Do let me know otherwise.

**Comment by lukemorawski** [comment]
@abdulrahuman5196 yeah, no high priority, but please keep in mind that:
- this padding issue occurs in many components and it's impacting UI in many places across the app
- it's hard to resolve conflicts that bundle up over time

Cheers :)

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
Missed to provide last update. The code worked fine on major checks and the approach seems good to me as well.

@lukemorawski Could you kindly merge from main? So that I can do the platform videos and take this to closure.

**Comment by luacmartins** [comment]
@abdulrahuman5196 seems like @lukemorawski merged main

**Review by luacmartins — DISMISSED** [review]

**Comment by luacmartins** [comment]
@lukemorawski we have conflicts and an outstanding comment. Let's address those to get this one merged!

**Comment by lukemorawski** [comment]
@luacmartins Should be fixed now

**Comment by luacmartins** [comment]
Thanks! @abdulrahuman5196 let's continue the review!

**Comment by abdulrahuman5196** [comment]
Hi, yes. Will start in couple of hours.

**Comment by abdulrahuman5196** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>





https://github.com/Expensify/App/assets/46707890/cd2bae78-4408-452b-95ae-f328bfe544f3


</details>

<details>
<summary>Android: mWeb Chrome</summary>





https://github.com/Expensify/App/assets/46707890/476c9664-6a58-403c-9503-24ebb5f28e16



</details>

<details>
<summary>iOS: Native</summary>






https://github.com/Expensify/App/assets/46707890/c2b6bd74-01e8-43a4-98b2-0273cc00e810


https://github.com/Expensify/App/assets/46707890/581c7f3b-aae1-4165-8477-48f980bf423e


</details>

<details>
<summary>iOS: mWeb Safari</summary>






https://github.com/Expensify/App/assets/46707890/42627ca7-5bbd-4109-a3eb-254de237f5d2



</details>

<details>
<summary>MacOS: Chrome / Safari</summary>





https://github.com/Expensify/App/assets/46707890/1279bee7-8e94-484d-8934-bc1829187be3


</details>

<details>
<summary>MacOS: Desktop</summary>





https://github.com/Expensify/App/assets/46707890/890c2457-c095-4f45-9587-42e05d87fd55


</details>

**Review by abdulrahuman5196 — APPROVED** [review]
Changes looks good and works well. Reviewers checklist is also complete.

All yours.  @luacmartins 

🎀 👀 🎀
C+ Reviewed

**Review by luacmartins — APPROVED** [review]

**Comment by pac-guerreiro** [comment]
@luacmartins @abdulrahuman5196 @lukemorawski 

This change broke submit button position on some forms, which now has no bottom padding:

Screenshot 2024-04-17 at 18 03 39
Screenshot 2024-04-17 at 18 04 27
Screenshot 2024-04-17 at 18 05 19
Screenshot 2024-04-17 at 18 05 53
Screenshot 2024-04-17 at 18 06 03
Screenshot 2024-04-17 at 18 06 13

**Comment by shawnborton** [comment]
This also broke the bottom button in other places too, like the transfer balance page. Can you please check that out as well?

**Pull request merged**
