### PR TITLE
Fix validation messages hidden behind keyboard

### PR DESCRIPTION
**Pull request by rdjuric**
### Details

Wraps our sign in steps in a `KeyboardAvoidingView`, moves the error message to stay above our `Button`.

### Fixed Issues

$ https://github.com/Expensify/App/issues/4080

### Tests

1. Open the app without being logged
2. Trigger a error message (wrong email on the first step, or wrong password in the second)
3. The error shows up above the button

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web

https://user-images.githubusercontent.com/53711423/126632093-a9e19889-79ae-4612-890c-3f08738dc698.mov

#### Mobile Web

https://user-images.githubusercontent.com/53711423/126632148-0bedcf24-100f-4707-ba98-2260fb2e264d.mp4

#### Desktop

https://user-images.githubusercontent.com/53711423/126632206-ba6ffd08-8cc3-48d4-a7d2-4a280940af33.mov

#### iOS

https://user-images.githubusercontent.com/53711423/126632228-59406fab-9026-4c39-8224-e4cf49e5139b.mp4

#### Android

https://user-images.githubusercontent.com/53711423/126632240-159f366d-4921-4027-89df-69e109f44656.mp4

### CODE REVIEW

**Review by stitesExpensify — APPROVED** [review]
Nice!

**Comment by stitesExpensify** [comment]
Code looks good, I just watched all of the videos though and I noticed on web that when the error message pops up the image on the right side scrolls down, I don't think that should be happening 😬

**Comment by rdjuric** [comment]
> Code looks great! I just watched all of the videos though and I noticed on web that when the error message pops up the image on the right side scrolls down, I don't think that should be happening 😬

The blue image on the first video? I looked HARD and couldn't see it scrolling down when the error appears 🧐

**Comment by stitesExpensify** [comment]
I'm sorry that's my fault, it was actually on desktop. The image of the phone shifts down

**Comment by rdjuric** [comment]
Ah, I can see it now! This happens on the main branch too, it doesn't look related to this PR (I also didn't change any code in the `SignInPageLayoutWide`)

Here's a vid of it happening on the main branch. You can repro it by making the window smaller than the email/password form.

https://user-images.githubusercontent.com/53711423/126851494-47ece6ae-d4de-4966-8b7c-805c4b61ff8b.mov

**Comment by stitesExpensify** [comment]
Ah, well if it's happening on main then we can just merge. Thanks!

**Pull request merged**
