### PR TITLE
fixed bug: backticks with suffix or prefix breaks. updated expensify-…

### PR DESCRIPTION
**Pull request by brianmuks**
### Details

Modified the regex to handle backticks with prefix and suffix: 
https://github.com/Expensify/expensify-common/blob/f77bb4710c13d01153716df7fb087b637ba3b8bd/lib/ExpensiMark.js#L52

### Fixed Issues

$ https://github.com/Expensify/App/issues/8288

### Tests

 1. Send the following messages & verify the displayed message.
 
 Case 1:
 
 ```
 a`b`
 ```
 
 The sent message should be - a`b`
 
 Case 2:
 
 ```
 `a`b
 ```
 
 The sent message should be - `a`b

- [x] Verify that no errors appear in the JS console

#### Contributor (PR Author) Checklist
- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [ ] I added steps for Staging and/or Production testing in the `QA steps` section
    - [ ] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [ ] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [ ] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

<details>
<summary><h4>PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

</details>

### QA Steps

- [ ] Verify that no errors appear in the JS console

#### Web

Screenshot 2022-04-13 at 7 01 34 PM

#### Mobile Web

Screenshot 2022-04-13 at 7 02 24 PM

#### Desktop

Screenshot 2022-04-13 at 7 03 08 PM

#### iOS

Screenshot 2022-04-20 at 11 53 02 AM

#### Android

screenshot (1)

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
Sorry for the delay, Review this now.

**Comment by Santhosh-Sellavel** [comment]
If message is sent using iOS, the solution doesn't work
Simulator Screen Shot - iPhone 13 - 2022-04-18 at 21 53 13

cc: @brianmuks @Beamanator

**Comment by brianmuks** [comment]
> If message is sent using iOS, the solution doesn't work Simulator Screen Shot - iPhone 13 - 2022-04-18 at 21 53 13
> 
> cc: @brianmuks @Beamanator

@Santhosh-Sellavel I have just tested this and it's working just fine on IOS too .

**Comment by Beamanator** [comment]
Hmm I'm seeing what @Santhosh-Sellavel is seeing, I just tested on iPhone 13 (15.4) simulator

Screen Shot 2022-04-20 at 1 59 31 PM

**Comment by brianmuks** [comment]
> Hmm I'm seeing what @Santhosh-Sellavel is seeing, I just tested on iPhone 13 (15.4) simulator
> 
> Screen Shot 2022-04-20 at 1 59 31 PM

Was this after ```npm install ```  to pull the latest changes from :
 ```
"expensify-common": "git+https://github.com/Expensify/expensify-common.git#428ceec578162cdd61bc156afd329987df380f9c",
```
 ?

**Comment by brianmuks** [comment]
https://user-images.githubusercontent.com/4520893/164227289-9c9fed1f-fd29-4a4f-9436-daf2e5b54401.mp4

**Comment by Beamanator** [comment]
> Was this after `npm install ` to pull the latest changes from :
> 
> ```
> "expensify-common": "git+https://github.com/Expensify/expensify-common.git#428ceec578162cdd61bc156afd329987df380f9c",
> ```

Yes I'm 99% sure I did `npm i` then `cd ios && pod install && cd ..` before running the simulator 🤔 I'll try on iPod touch 7th gen

**Comment by Beamanator** [comment]
Weird, I still don't get the back-ticks working 🤒 

Screen Shot 2022-04-20 at 2 22 28 PM

**Comment by brianmuks** [comment]
> Weird, I still don't get the back-ticks working 🤒


For debugging purposes are you able to check this line for me :
```
node_modules/expensify-common/lib/ExpensiMark.js
Line 52
```
Is it matching with : 
```
                regex: /(\B|_|)&#x60;(.*?)&#x60;(\B|_|)(?![^<]*<\/pre>)/g,

```

**Comment by Beamanator** [comment]
Yes it is 🤷 

```js
            {
                name: 'inlineCodeBlock',

                // Use the url escaped version of a backtick (`) symbol. Mobile platforms do not support lookbehinds,
                // so capture the first and third group and place them in the replacement.
                regex: /(\B|_|)&#x60;(.*?)&#x60;(\B|_|)(?![^<]*<\/pre>)/g,
                replacement: '$1<code>$2</code>$3',
            },
```

**Comment by brianmuks** [comment]
> Yes it is 🤷
> 
> ```js
>             {
>                 name: 'inlineCodeBlock',
> 
>                 // Use the url escaped version of a backtick (`) symbol. Mobile platforms do not support lookbehinds,
>                 // so capture the first and third group and place them in the replacement.
>                 regex: /(\B|_|)&#x60;(.*?)&#x60;(\B|_|)(?![^<]*<\/pre>)/g,
>                 replacement: '$1<code>$2</code>$3',
>             },
> ```

Strange 🤔 ! let me test on Ipone 12.

**Comment by brianmuks** [comment]
From  iPhone 12 Pro Max
https://user-images.githubusercontent.com/4520893/164239537-c95e2a85-d8eb-4799-9861-4fb06ff67d11.mp4

**Comment by Beamanator** [comment]
😡 well @Santhosh-Sellavel if you can test again please let me know what you find - if you see what Brian has, let's merge - otherwise let's ask for help testing in #expensify-open-source

**Comment by Santhosh-Sellavel** [comment]
I'll check again.

**Comment by Santhosh-Sellavel** [comment]
@Beamanator 😕  Weird working now.

Simulator Screen Shot - iPhone 13 - 2022-04-23 at 01 51 07

Pull latest changes from main delete `node_modules` and executed the following
`npm install && cd ios && arch -x86_64 pod install && cd .. & yarn ios`

Could be some cache issues, give it a try and let me know.

**Comment by Santhosh-Sellavel** [comment]
#### PR Reviewer Checklist</h4></summary>

- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] iOS / native
    - [ ] Android / native
    - [ ] iOS / Safari
    - [ ] Android / Chrome
    - [ ] MacOS / Chrome
    - [ ] MacOS / Desktop
- [ ] I verified there are no console errors (if there’s a console error not related to the PR, report it or open an issue for it to be fixed)
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained “why” the code was doing something instead of only explaining “what” the code was doing.
    - [ ] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by tagging the marketing team on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named “index.js”. All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/PR_REVIEW_GUIDELINES.md)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] Any functional components have the `displayName` property
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose and it is broken down into smaller components in order to separate concerns and functions
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn’t already exist
    - [ ] The style can’t be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.

**Comment by Santhosh-Sellavel** [comment]
@brianmuks 
Can you add QA Steps?

Test steps could be clearer

1. Send the following messages & verify the displayed message.

Case 1:
```
a`b`
```
The sent message should be -  a`b`

Case 2:
```
`a`b
```
The sent message should be  - `a`b

**Comment by brianmuks** [comment]
> @brianmuks Can you add QA Steps?
> 
> Test steps could be clearer
> 
> 1. Send the following messages & verify the displayed message.
> 
> Case 1:
> 
> ```
> a`b`
> ```
> 
> The sent message should be - a`b`
> 
> Case 2:
> 
> ```
> `a`b
> ```
> 
> The sent message should be - `a`b

Sure thing.

**Comment by Santhosh-Sellavel** [comment]
Add QA Steps also.

**Comment by brianmuks** [comment]
> Add QA Steps also. @brianmuks

@Santhosh-Sellavel I have used the above steps for QA steps. Is that enough ?

**Comment by Santhosh-Sellavel** [comment]
Yes

**Comment by brianmuks** [comment]
> Yes

Done

**Review by Santhosh-Sellavel — DISMISSED** [review]
LGTM Tests well!

@Beamanator

**Comment by Beamanator** [comment]
Sorry for the delay, I will test again today but now there's conflicts - @brianmuks do you mind fixing those when you have a chance? 🙏

**Comment by brianmuks** [comment]
> Sorry for the delay, I will test again today but now there's conflicts - @brianmuks do you mind fixing those when you have a chance? 🙏

I am on it. Thanks

**Comment by Beamanator** [comment]
@brianmuks conflicts are gone but so are all of your changes 😅

**Comment by brianmuks** [comment]
> @brianmuks conflicts are gone but so are all of your changes 😅

@Beamanator sorry for that. We should be good now.

**Comment by Beamanator** [comment]
Haha nice thanks 👍 I'll test tomorrow 💯 

BTW I don't think you need to do so much force-pushing 🤷

**Review by Beamanator — APPROVED** [review]
Working today! I guess it was some caching issue like @Santhosh-Sellavel suggested 😅

**Comment by Beamanator** [comment]
Hmm it looks like this PR already merged the latest expensify-common commit: https://github.com/Expensify/App/pull/8743/files

I think we can just close this PR since it looks like expensify-common commit hash is up to date here too: https://github.com/Expensify/App/blob/main/package.json

**Comment by Beamanator** [comment]
Ok closing b/c it doesn't look like there's actually any "new" changes here - since this change was merged in a PR a few days ago (link above) - I'll mention this in the issue. Well done @brianmuks thanks for sticking with us through this one 👍

**Comment by brianmuks** [comment]
> Ok closing b/c it doesn't look like there's actually any "new" changes here - since this change was merged in a PR a few days ago (link above) - I'll mention this in the issue. Well done @brianmuks thanks for sticking with us through this one 👍

I had fun working on this 😃 and  I am impressed with  your humility @Beamanator and @Santhosh-Sellavel . I can't wait to get to the next issue. I am learning a lot here 🔥

**Pull request closed without merging**
