### PR TITLE
Fix: iOS button obstructed by keyboard

### PR DESCRIPTION
**Pull request by rawalyogendra**
### Fixed Issues

$ https://github.com/Expensify/App/issues/11463
PROPOSAL: https://github.com/Expensify/App/issues/11463#issuecomment-1336473954

$ https://github.com/Expensify/App/issues/10670
PROPOSAL: https://github.com/Expensify/App/issues/11463#issuecomment-1336473954

### Tests

https://github.com/Expensify/App/issues/11463
1. Login with any account
2. Tap on FAB icon
3. Select New Group
4. Type any email, or select any existing option
5. Verify that the green "Create group" button is not hidden by the keyboard instead of anchored above it

https://github.com/Expensify/App/issues/10670
1. Login with any account
2. Tap on FAB icon
3. Select Send/Receive Money
4. Enter an amount and hit next
5. Verify Final confirmation button is not hidden by the keyboard instead of anchored above it

- [X] Verify that no errors appear in the JS console

### QA Steps

- [x] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [x] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/7548730/213496567-92b1b81a-3030-40cd-beec-7a4f745e6ae8.mov
</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/7548730/213280588-7415356a-e0d9-4b9d-bb7f-978939a97b42.mp4
</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/7548730/213281519-3a8966eb-3bc7-44b1-8c98-7b0e5339ec94.mp4
</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/7548730/213499562-ca7dc5f9-f234-475c-9e1c-eee85ecf3817.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/7548730/213282191-2c345964-c437-4ad4-800d-fe9ef243ee69.mp4
</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/7548730/213282322-966bb952-2a6c-4727-a1c9-40cd737f667c.mp4

</details>

### CODE REVIEW

**Comment by rawalyogendra** [comment]
cc: @mananjadhav @flodnv @JmillsExpensify

**Review by mananjadhav — DISMISSED** [review]

**Comment by mananjadhav** [comment]
Thanks for the update @rawalyogendra.  I think I am going to ask you to still add videos for Web and Desktop platforms for sanity.

**Comment by rawalyogendra** [comment]
> Thanks for the update @rawalyogendra. I think I am going to ask you to still add videos for Web and Desktop platforms for sanity.

@mananjadhav sure I will add the screen recordings of these platforms.



> So based on the videos attached I've got two questions:
> 
>     1. We don't have any impact on iOS and Android apps as we only updated changes for RNW?
> 
>     2. For Mobile Web Chrome, is there any difference between this PR vs our current staging/prod version.

1. As far as I can tell, it should not affect native versions as we are only adding RNW related changes.
2. The end result should be same for this change vs current version in mWeb Chrome. Even if there is a difference, it should be negligible.

**Comment by mananjadhav** [comment]
Cool. Thanks for clarifying. The changes are good and I've tested earlier when we discussed the issue. Let me test this again and complete the checklist

**Comment by mananjadhav** [comment]
@rawalyogendra I am testing this on my iPhone Simulator Safari but I can see the issue still exists.


https://user-images.githubusercontent.com/3069065/213455077-3a0effa1-6931-4afe-a5e1-0b5e32c71e41.MP4

**Comment by flodnv** [comment]
>@mananjadhav I think we have not built and published the changes of our RNW fork to NPM

Ah, is this something I should do?

**Comment by rawalyogendra** [comment]
@flodnv yes, since we are using `@expensify/react-native-web` package and the code has not been published there.

image

**Review by tgolen — DISMISSED** [review]

**Comment by mananjadhav** [comment]
Okay I thought we must have a workflow to publish the package as soon as it is merged. @flodnv @tgolen  Can you please help publishing the version and then I can test ?

**Comment by flodnv** [comment]
I tried and failed 😅 Asked for help here: https://expensify.slack.com/archives/C01GTK53T8Q/p1674225100579739

**Comment by flodnv** [comment]
I _think_ I succeeded to publish version 0.18.10 https://www.npmjs.com/package/@expensify/react-native-web?activeTab=readme. It's my first time doing this so please lmk if something is wrong 🙇

**Comment by rawalyogendra** [comment]
@flodnv @mananjadhav I can confirm that the changes has been published to npm.

Screen Shot 2023-01-24 at 10 41 23 AM

**Comment by mananjadhav** [comment]
### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/3069065/214217895-d87a1e0c-f7db-4ac3-b2a7-5aebd65654e4.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/3069065/214218037-b8ab8a7a-0ffc-483b-abdf-04d371a30cd7.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/3069065/214218068-d4dbee77-ede3-4446-a00f-662251e49a44.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/3069065/214218095-dfbd3098-8d63-407f-8155-b8c6e8d46bcb.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/3069065/214218121-f454a065-0cbb-4208-b378-f90567bd4607.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/3069065/214218182-5c418123-edac-4312-83e6-5cbb51298f83.mov

</details>

------

Thanks for the update @rawalyogendra. I was able to test and confirm it works, but I think we need to update the package.json with the correct version. So ideally we should have the `package.json` and `package-lock.json` updates as well here with `0.18.10` version.

https://github.com/Expensify/App/blob/ae66a7f019dda888390173a542b273d97042eaaa/package.json#L43-L45

**Comment by mananjadhav** [comment]
@rawalyogendra Waiting for your update on this one. Can you please update the version in package.json ?

**Comment by rawalyogendra** [comment]
@mananjadhav updated the RNW version. 

Sorry I misunderstood 😅

**Review by mananjadhav — APPROVED** [review]

**Comment by mananjadhav** [comment]
Thanks for the patience @rawalyogendra. I've tested and this works as expected.

**Comment by mananjadhav** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/3069065/215311177-3f4077cf-0cfd-4015-afc6-47455a4b3139.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/3069065/215311194-fa1160b6-ba9c-4643-bc01-1a5618973fac.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/3069065/215311214-f0ae550c-39a2-4863-be53-d33269ea009a.mov

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/3069065/215311217-847ddabc-085e-4770-912e-eb92d57e8b87.mov


</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/3069065/215311224-ee561d75-25cd-41b3-a3a4-58dae8e033b1.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/3069065/215311236-3cb55ade-abe8-4bb5-b3e6-0789faea7b44.mov

</details>


----

@flodnv All yours.

**Comment by sobitneupane** [comment]
It will also solve https://github.com/Expensify/App/issues/14161 issue. PR for [the issue](https://github.com/Expensify/App/issues/14161) was under review.

mWeb/Safari

https://user-images.githubusercontent.com/25876548/215509753-d574053d-9d2f-4b1a-88d7-f50764852d4a.MP4


mWeb/Chrome

https://user-images.githubusercontent.com/25876548/215510175-509a8a2c-7f50-4ccd-b357-fcb7cddd1407.mp4

**Comment by sobitneupane** [comment]
But for Android/Chrome (probably only those with GBoard), the composer becomes scrollable. For details: https://github.com/Expensify/App/pull/14439

https://user-images.githubusercontent.com/25876548/214786584-fb523cb3-ef52-4aa7-8c20-022d4a916331.mp4

**Comment by flodnv** [comment]
Interesting @sobitneupane, thanks a lot for connecting the dots and providing your insights!

@mananjadhav @rawalyogendra what are your thoughts on this? Should we followup on it as a separate issue, probably easier at this point?

**Comment by mananjadhav** [comment]
> @mananjadhav @rawalyogendra what are your thoughts on this? Should we followup on it as a separate issue, probably easier at this point?

@flodnv I think we should follow up this as a separate issue. 

----

Thanks @sobitneupane for the help in linking the issues.

**Comment by rawalyogendra** [comment]
@sobitneupane thank you for testing these out.

@flodnv yeah, I think a separate issue makes sense at this point.

**Review by flodnv — APPROVED** [review]

**Comment by flodnv** [comment]
@sobitneupane please feel free to create a new bug report for what you found above, thanks!

**Comment by flodnv** [comment]
Thanks, I am not surprised 😞

**Comment by redstar504** [comment]
I haven't dug into this PR very much, but is this depending on state to update the max height? We should consider using nativeProps or a ref so we can update it without depending on a re-render.

**Pull request merged**
