### PR TITLE
Add /partners/plaid/oauth_ios to apple-app-site-association

### PR DESCRIPTION
**Pull request by Gonals**
@Jag96 

cc @TomatoToaster 
### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/182955

### Tests
None, will test on staging.

### QA Steps
Go to `https://staging.new.expensify.com/partners/plaid/oauth_ios` on an iOS device, confirm the New Expensify App opens. This does not need to be QA'd on any other platform.

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Review by TomatoToaster — APPROVED** [review]

**Review by Jag96 — APPROVED** [review]
LGTM. Looks like in https://github.com/Expensify/App/pull/5077 we could QA on staging, so going to update the tests to ask QA to test there. Also, I filed https://github.com/Expensify/Expensify/issues/185770 as a separate issue to update this file's syntax to be in line w/ the new apple standard.

**Comment by Jag96** [comment]
Going to CP this to test on staging for testing

**Comment by TomatoToaster** [comment]
Just tested this BTW on iOS myself and can verify it works.

**Comment by TomatoToaster** [comment]
I did this my sending an imessage to myself with just `https://staging.new.expensify.com/partners/plaid/oauth_ios` and then clicking on the link and it opened up the NewDot app 👍🏾

**Pull request merged**
