### PR TITLE
New GH Action: CreateOrUpdateStagingDeployCash

### PR DESCRIPTION
**Pull request by roryabraham**
This issue is currently HELD on https://github.com/Expensify/Expensify/issues/157003

### Details
Implements a new Github Action to create or update the StagingDeployCash issue.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/155140

### Tests

- [x] Create a properly-formatted `StagingDeployCash` ✅ https://github.com/Expensify/Expensify.cash/issues/1712
- [x] Close the existing `StagingDeployCash` ✅
- [x] Run this action in a test workflow. It should create a new StagingDeployCash. Verify that it is created correctly, looks correct, contains the correct PRList, etc... ✅ IT'S ALIVEEE https://github.com/Expensify/Expensify.cash/issues/1732
- [x] Re-run the test workflow, and it should add the listed pull requests and deploy blockers to the StagingDeployCash that was created in the previous step.

### Tested On

- [x] Github

### CODE REVIEW

**Comment by roryabraham** [comment]
Okay, got pretty far with this. I think right now it's failing to create the action because we're listing `applausebot` as the assignee, but you can only assign a user to an issue if they have write access to that repo. So we probably just need to give `applausebot` write access to Expensify.cash.

**Comment by roryabraham** [comment]
Just for ease of record-keeping, this is how this was tested:

```yaml
- name: Create or Update StagingDeployCash
  uses: Expensify/Expensify.cash/.github/actions/createOrUpdateStagingDeploy@74b813a5ae14aa327319d49ef6d87a21ab6d75db
  with:
      NPM_VERSION: '1.0.2-25'
      GITHUB_TOKEN: ${{ secrets.OS_BOTIFY_TOKEN }}
      NEW_PULL_REQUESTS: 'https://github.com/Expensify/Expensify.cash/pull/1,https://github.com/Expensify/Expensify.cash/pull/2'
      NEW_DEPLOY_BLOCKERS: 'https://github.com/Expensify/Expensify.cash/issues/123,https://github.com/Expensify/Expensify/issues/12345'
```

And when the issue was first created, this was the result:

image

As expected, the `NEW_PULL_REQUESTS` and `NEW_DEPLOY_BLOCKERS` fields were unused (they are meant for the update use case. Now I'm going to re-run the test workflow, and I'm expecting that https://github.com/Expensify/Expensify.cash/issues/1732 should be updated to include the new PR and a new section with the deploy blocker.

**Comment by roryabraham** [comment]
Okay, had to fix a couple more bugs but now the update part is working too:

https://github.com/Expensify/Expensify.cash/issues/1732

**Comment by roryabraham** [comment]
Okay, this PR is now ready for review 👍

**Review by AndrewGable — DISMISSED** [review]

**Review by AndrewGable — APPROVED** [review]

**Review by TomatoToaster — APPROVED** [review]

**Pull request merged**
