### PR TITLE
Undo conversion of errorAttemptsCount to object

### PR DESCRIPTION
**Pull request by NikkiWines**
cc: @marcaaron 

### Details
Follow up PR to https://github.com/Expensify/Web-Secure/pull/2022 to clean out some old, no longer needed logic. 

### Fixed Issues

$ https://github.com/Expensify/App/pull/4889#issuecomment-907460540

### Tests
1. Set `isPlaidTestAccountNumbers()` and `isPlaidTestRequestor()` and ` in `lib/ACHData.php` to return `false` so that we run the some necessary checks
2. Run through the QA steps 

### QA
1. Log into an account on new.expensify.com without a bank account set up
1. Navigate to `/bank-account`
1. Click on `Connect Manually` and enter the credentials for a `PENDING` bank account from this [SO post](https://stackoverflow.com/c/expensify/questions/342/525#525)
    - image
1. Once you get to the `Requestor` step confirm that you get the `Please verify your name and date of birth. If the information is correct, click "Save & Continue` error once 
1. Resubmit your information and confirm you're routed to the next view and not looped back to the requestor step again 

### Tested On

- [x] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/16747822/131423739-606f0f69-617b-4e8a-ba76-fc6c411e5402.mov

### CODE REVIEW

**Comment by NikkiWines** [comment]
Off hold!

**Review by MonilBhavsar — APPROVED** [review]

**Comment by isagoico** [comment]
@NikkiWines Hello! I'm getting the error message in a modal instead of a Growl, I was comparing with the video you attached in the main comment but not sure if this has to do with the PR or not 
image

**Comment by marcaaron** [comment]
cc @aldo-expensify this is probably expected and related to the changes we are making?

**Comment by NikkiWines** [comment]
I believe it's fine @isagoico since I know we were moving away from growls for bank account set up, but let's wait for @aldo-expensify to confirm just in case!

**Comment by roryabraham** [comment]
Pretty confident that:

1. This is expected behavior
1. If unexpected, it's not caused by this PR.

So in lieu of input from @aldo-expensify I'm going to check this off.

**Comment by aldo-expensify** [comment]
This is expected behaviour, we changed that growl for the modal [here](https://github.com/Expensify/App/pull/4924)

**Pull request merged**
