### PR TITLE
Fix blank screen when exiting the Onfido page in IOU flow

### PR DESCRIPTION
**Pull request by luacmartins**
### Details
The `onfido.tearDown()` function causes the app to crash on Desktop. 

### Fixed Issues
$ https://github.com/Expensify/App/issues/6082

### Tests
1. Launch the Desktop app and login
2. Tap on [+] and select `Send money > enter amount > next`
3. Enter the email of a user you will send money to in the field 'Name, email or phone"
4. Tap on Continue for "Verify identity" page
5. Close 'Verify identity" modal

### QA Steps
Same as above.

### Tested On

- [X] Web
- [ ] Mobile Web
- [X] Desktop
- [ ] iOS
- [ ] Android

#### Web

https://user-images.githubusercontent.com/22219519/143292115-18d8a8fa-bae5-42e4-85f7-9c91364b13a3.mov

#### Desktop

https://user-images.githubusercontent.com/22219519/143292855-d5168d45-a75d-4f42-8572-26b069098fb8.mov

### CODE REVIEW

**Review by Luke9389 — COMMENTED** [review]
I'm a bit wary of this change (as always with platform checking). Did you ever get to the bottom of what was causing the crash? I read the issue and [this Slack thread](https://expensify.slack.com/archives/C03TQ48KC/p1637718164105600?thread_ts=1635347185.233000&cid=C03TQ48KC), and didn't see a resolution per se. Would you be willing to explain this change a bit more?

**Comment by luacmartins** [comment]
I share your concerns and wish that I had an explanation for why `onfido.tearDown()` crashes the desktop app, but I don't. Checking the [function definition](https://github.com/onfido/onfido-sdk-ui/blob/a3cd38c92b31c936145a9f902db3efc58976e327/src/index.tsx#L153-L155), I see that it just renders null. I ran some local tests and we seem to completely remove the component when we close that navigator even without `tearDown()`, so this change should be harmless.

**Comment by Luke9389** [comment]
Hmm, well I don't think this is too egregious, but I'm gonna request another pair of eyes just in case.

**Review by roryabraham — CHANGES_REQUESTED** [review]
Regarding the fix for the crash, I feel like it's safe enough. If it works, it works 🤷 

That said, I don't really want to condone the use of `getPlatform()` in this context because, even though it's less code than the alternative, it goes against our style guideline for platform-specific code. Instead, the way we would normally implement this change is using platform-specific file extensions:

1. Create a `Base` component, in this case, `BaseOnfidoWeb` or something. It would be the same as this, except without the `componentWillUnmount`
1. Create lightweight wrappers in `index.website.js` and `index.desktop.js`, and pass a ref to the `BaseOnfidoWeb` component.
1. Implement `componentWillUnmount` in `index.website.js` only.

So the resultant files would look something like this:

#### index.desktop.js

```js
import BaseOnfidoWeb from './BaseOnfidoWeb';
import onfidoPropTypes from './onfidoPropTypes';

// On desktop, we do not want to teardown onfido, because it causes a crash.
// See https://github.com/Expensify/App/issues/6082
const Onfido = BaseOnfidoWeb;

Onfido.propTypes = onfidoPropTypes;
Onfido.displayName = 'Onfido';

export default Onfido;
```

#### index.website.js

```js
import React, {Component} from 'react';
import lodashGet from 'lodash/get';
import BaseOnfidoWeb from './BaseOnfidoWeb';
import onfidoPropTypes from './onfidoPropTypes';

class Onfido extends Component {
    constructor(props) {
        super(props);
        this.baseOnfido = null;
    }
    
    componentWillUnmount() {
        const onfidoOut = lodashGet(this, 'baseOnfido.onfidoOut');
        if (!onfidoOut) {
            return;
        }
        
        onfidoOut.tearDown();
    }
    
    render() {
        return (
            <BaseOnfidoWeb
                ref={e => this.baseOnfido = e}
                
                // eslint-disable-next-line react/jsx-props-no-spreading
                {...props}
            />
        );
    }
}

Onfido.propTypes = onfidoPropTypes;

export default Onfido;
```

**Comment by luacmartins** [comment]
Thanks for the detailed explanation @roryabraham! Updated!

**Review by roryabraham — DISMISSED** [review]
NAB: I'm hesitant about calling it `BaseOnfido` because it's not used by `index.native.js`, like other `BaseXYZ` components usually would be. That's why I suggested `BaseOnfidoWeb` (because desktop is essentially a subset of web, thanks to Electron.js)

**Comment by luacmartins** [comment]
Updated!

**Review by roryabraham — APPROVED** [review]

**Review by Luke9389 — APPROVED** [review]

**Comment by Luke9389** [comment]
Thanks @roryabraham

**Pull request merged**
