### PR TITLE
RBR display in LHN, Inbox and Workspace list

### PR DESCRIPTION
**Pull request by rezkiy37**
### Details

The PR fixes a case when the Inbox and Workspace list detect RBR for one transaction thread report.

### Fixed Issues

$ https://github.com/Expensify/App/issues/46416
PROPOSAL: N/A

### Tests

1. Submit an expense of a workspace once. It should be one transaction thread report.
2. Create violations for the expense. E.g. delete the attached tag or category. 
3. Verify that there is **RBR** in the **LHN**, **Inbox** and **Workspace Switcher List**.

- [X] Verify that no errors appear in the JS console

### Offline tests

Same as **"Tests"**.

### QA Steps

Same as **"Tests"**.

- [X] Verify that no errors appear in the JS console

### PR Author Checklist

- [X] I linked the correct issue in the `### Fixed Issues` section above
- [X] I wrote clear testing steps that cover the changes made in this PR
    - [X] I added steps for local testing in the `Tests` section
    - [X] I added steps for the expected offline behavior in the `Offline steps` section
    - [X] I added steps for Staging and/or Production testing in the `QA steps` section
    - [X] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [X] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [X] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [X] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [X] I ran the tests on **all platforms** & verified they passed on:
    - [X] Android: Native
    - [X] Android: mWeb Chrome
    - [X] iOS: Native
    - [X] iOS: mWeb Safari
    - [X] MacOS: Chrome / Safari
    - [X] MacOS: Desktop
- [X] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [X] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [X] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [X] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [X] I verified that comments were added to code that is not self explanatory
    - [X] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [X] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
      - [X] If any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:
    - [X] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [X] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [X] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [X] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [X] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [X] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [X] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [X] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [X] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [X] I verified that if a function's arguments changed that all usages have also been updated correctly
- [X] If any new file was added I verified that:
    - [X] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [X] If a new CSS style is added I verified that:
    - [X] A similar style doesn't already exist
    - [X] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG)`)
- [X] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [X] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [X] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [X] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [X] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [X] I verified that all the inputs inside a form are aligned with each other.
    - [X] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [X] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [X] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/22f5be88-8f2c-4142-9f30-e22d181f7762

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/5ad35fb4-195a-467c-8ab8-c2dba831c69a

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/a9882884-db06-4874-9336-2a5f5a160848

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/e9a13a55-d17e-4e0d-abe9-631819d8979c

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/8ac0f41f-7d3b-4fb9-bac6-1fbb00bb7686

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/96fad02f-59fd-488c-a0a6-5d779c671491

</details>

### CODE REVIEW

**Comment by rezkiy37** [comment]
> But I can't reproduce the original bug. Is it fixed?

@dukenv0307 did you try the test steps of the PR? Btw, https://github.com/Expensify/App/issues/46416#issuecomment-2258567753.

**Comment by rezkiy37** [comment]
@dukenv0307 Yes, the OP is still being investigated. I found this bug related to the issue as well. 
So I will open one more PR to fix the reported bug itself as well.

**Comment by rezkiy37** [comment]
@dukenv0307, I just have a friendly question: will you review this PR?

**Comment by rezkiy37** [comment]
@dukenv0307 the initial bug of this PR or the issue? Because they are similar but not the same.

**Comment by rezkiy37** [comment]
@dukenv0307, I've synced up. Also, I tested it again and it works properly in both modes.


https://github.com/user-attachments/assets/d193b75f-5a28-4a77-8670-9946f98018bd

**Comment by rezkiy37** [comment]
> @rezkiy37 I found the following bug

@dukenv0307, I've fixed - 6d86ef9.

https://github.com/user-attachments/assets/4fb6aec3-f353-4b25-b855-7733a9d5e6ca

**Review by dukenv0307 — APPROVED** [review]

**Review by Beamanator — APPROVED** [review]
LGTM!

**Comment by Beamanator** [comment]
FYI I believe this was deployed to prod yesterday, from this checklist - https://github.com/Expensify/App/issues/47219

**Pull request merged**
