### PR TITLE
Add transition between Chats and Search views

### PR DESCRIPTION
**Pull request by marcaaron**
### Details
cc @shawnborton wondering if you are into a transition like this? 
Was cleaning some things up and thought it could use a fade.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/152779

### Tests
1. Open app
2. Touch Magnifying Glass icon
3. Verify that the sidebar view fades to the Search view
4. Touch X 
5. Verify the sidebar view fades back to the Chats view

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
https://user-images.githubusercontent.com/32969087/106338186-42e59e80-6237-11eb-9099-a2504030c141.mp4

#### Mobile Web
https://user-images.githubusercontent.com/32969087/106342485-218baf00-6245-11eb-8059-581d99b99175.mp4

#### Desktop
https://user-images.githubusercontent.com/32969087/106342562-834c1900-6245-11eb-828e-a27e2f3acf0d.mp4

#### iOS
https://user-images.githubusercontent.com/32969087/106342359-9ad6d200-6244-11eb-8785-f3aff9f0c9bc.mp4

#### Android
https://user-images.githubusercontent.com/32969087/106342521-4e3fc680-6245-11eb-9f3b-c341438ba6dc.mp4

### CODE REVIEW

**Comment by shawnborton** [comment]
Looks great to me! Curious about how the animation stuff works - can we pass easing functions into it, etc? How do we control the animation function/timing/duration/etc?

**Comment by marcaaron** [comment]
Can read about the animation options here -> https://reactnative.dev/docs/animations

**Comment by marcaaron** [comment]
Seems like `Animated.Timing` supports an easing parameter. Didn't spend too much time with it yet.

**Comment by marcaaron** [comment]
Bit lost on exactly how they are supposed to work... https://reactnative.dev/docs/easing

**Comment by marcaaron** [comment]
This might fill in some gaps - https://medium.com/oberonamsterdam/what-the-react-native-docs-forgot-to-tell-you-about-animations-c21d67abf14d

**Comment by shawnborton** [comment]
Cool, I remember Lucas doing something with animations for the FAB. Here it is for reference: https://github.com/Expensify/Expensify.cash/blob/d5d08ada8f7a7df458e553b31c5f9fb69b2eea20/src/components/FAB.js#L45-L51

Basically it would be nice to reuse easeInOut for this, that's really all I am getting at.

**Comment by marcaaron** [comment]
Care to test it out? I'm curious if you can spot any visual difference.

**Comment by marcaaron** [comment]
I tried and couldn't 🤷‍♂️

**Comment by shawnborton** [comment]
Yeah I tried and I don't think I see a difference really, though I might be doing something wrong for all I know.

**Comment by shawnborton** [comment]
Are we still planning to do this one? The spacing in the LHN is killing me, and I know this branch fixes it. 

For reference:
image

**Comment by marcaaron** [comment]
Yeah let's do it lemme fix up the conflicts here.

**Comment by shawnborton** [comment]
Just pulled, did npm install, and npm run web and I am still seeing the misalignment in the LHN header area:
image

**Comment by marcaaron** [comment]
Will take another look at this today. Didn't quite grasp what you were asking in that last comment.

**Comment by shawnborton** [comment]
Ah, basically there is this empty div with a margin top of 4px that causes the top row of the LHN to not line up with the bottom edge of the chat header:
image


So we should get rid of that empty div or whatever it is.

**Comment by shawnborton** [comment]
It also looks like the LHN header area is too tall. Currently it is 68px tall but it should be 64px tall. 
image

**Comment by shawnborton** [comment]
That being said, I can see where we can solve all of that in a separate issue.

**Comment by marcaaron** [comment]
Updated

**Review by nickmurray47 — APPROVED** [review]
LGTM, and tests well

**Pull request merged**
