### PR TITLE
Update the Apple app association file

### PR DESCRIPTION
**Pull request by mountiny**
### Details

Apple is deprecating the format of app-association-file we are currently using, therefore we need to change it. The new format is described in [this documentation](https://developer.apple.com/documentation/xcode/supporting-associated-domains) and the `applinks` property is described more specifically on [this page](https://developer.apple.com/documentation/bundleresources/applinks). 

The file also needs to be served from `.well-known/` directory as described in the docs: 
image

Check the linked issue for more details.

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/185770

### Tests

No local tests.

### QA Steps

Once deployed to staging, make sure to have the latest app version and then click [this link](https://staging.new.expensify.com/settings) and make sure the app opens instead of the browser.

Also, put `staging.new.expensify.com` into this Apple tool https://search.developer.apple.com/appsearch-validation-tool and make sure there are no errors.

### Tested On

- [ ] Web
- [ ] Mobile Web
- [ ] Desktop
- [ ] iOS
- [ ] Android

### CODE REVIEW

**Comment by mountiny** [comment]
@Dal-Papa We chatted with Joe over DM about reviewing this and he is OOO for a week so we are not in a rush on this. I guess we could even go forward with this one as we have already made these changes in Web-E.

**Review by Dal-Papa — APPROVED** [review]

**Review by Jag96 — APPROVED** [review]
@vitHoracek we were able to test https://github.com/Expensify/App/pull/6366 on staging so I think we can do the same here. Since we can test on staging I don't think we need to hold on this, I'll update the QA section

**Comment by mountiny** [comment]
@Jag96 Ah, that is true. I will test it out when it gets deployed to Staging 🙌

**Comment by Jag96** [comment]
Looks like we missed something here: https://github.com/Expensify/App/runs/4291419056?check_suite_focus=true. `ERROR in unable to locate "apple-app-site-association" at "/home/runner/work/App/App/apple-app-site-association"`

[This file](https://github.com/Expensify/App/blob/c3cee9c09ead43d31295bfd9c7d5f83cc453f87f/config/webpack/webpack.common.js#L54) has a mention that we need to update, going to make a quick PR.

**Comment by mountiny** [comment]
@Jag96 ah, good catch, waiting for the E2E to pass to merge the fix!

**Comment by mountiny** [comment]
Testing this on staging and not sure what is the issue. The validator says this:
image

But the deeplink on my phone works as expected, which makes me think it can't be broken.

**Comment by marcaaron** [comment]
Maybe related to my comment here: https://expensify.slack.com/archives/C02NQJMCQ6M/p1637684476011300?thread_ts=1637677126.010600&cid=C02NQJMCQ6M

**Comment by mountiny** [comment]
@Jag96 Ok, so the apple association validator is still showing error which is confusing to me honestly. 
image

For `expensify.com`, the validator does the same: 
image

When I made the changes there, I have left the old format as a fallback as well. At the same time, we know that on both  platforms the universal links work so the file cannot be completely wrong. The validator refers to the old archived documentation so maybe it is the validator which is not updated 😵‍💫

**Comment by marcaaron** [comment]
>At the same time, we know that on both platforms the universal links work so the file cannot be completely wrong

If Universal Links work... what are we trying to fix? What are the consequences of not passing the "validator"?

**Comment by marcaaron** [comment]
FWIW, `https://new.expensify.com/.well-known/apple-app-site-association` doesn't seem to download a file, but `https://new.expensify.com/apple-app-site-association` does. 🙃

**Comment by mountiny** [comment]
@marcaaron correct, I got confused, this PR which fixes the location just got deployed to staging https://github.com/Expensify/App/pull/6430#issuecomment-981967453

So we should try the validator in couple of minutes on staging. However, on `expensify.com` the validator also does not pass.

I guess technically, the validator should tell us the universal link are not working because the file has a wrong format, however, that is clearly not the case since the OldDot the validator also shows error, but we know the links work for us 🤷‍♂️

**Pull request merged**
