### PR TITLE
fix: hide overflow of html's body to fix scroll bug on safari ios

### PR DESCRIPTION
**Pull request by shonsirsha**
cc @Santhosh-Sellavel 

### Details
On safari (iOS), sometimes scrolling locks. This means when a user scrolls, the whole page gets scrolled, but not the actual list that the user intends to scroll - causing the scrolling to not be useful at all hence it's called "locked". Check issue below to see the bug visually.

### Fixed Issues

$ https://github.com/Expensify/App/issues/13599  
PROPOSAL: [GH_LINK_ISSUE(COMMENT)](https://github.com/Expensify/App/issues/13599#issuecomment-1367719421)

### Tests

1. Open LHN but don't scroll anywhere
2. Scroll up on the LHN list, verify that the list should be scrolling up, **and not the entire page (scroll body locking)**
3. Scroll down on the LHN list, verify that the list should be scrolling down, **and not the entire page (scroll body locking)**
4. Related to 3, if list is longer than device's screen, verify that we should still be able to see the last item on the list.

- [ ] Verify that no errors appear in the JS console

### Offline tests

Same as tests.

### QA Steps

1. Open LHN but don't scroll anywhere
2. Scroll up on the LHN list, verify that the list should be scrolling up, **and not the entire page (scroll body locking)**
3. Scroll down on the LHN list, verify that the list should be scrolling down, **and not the entire page (scroll body locking)**
4. Related to 3, if list is longer than device's screen, verify that we should still be able to see the last item on the list.

- [ ] Verify that no errors appear in the JS console

### PR Author Checklist

- [x] I linked the correct issue in the `### Fixed Issues` section above
- [x] I wrote clear testing steps that cover the changes made in this PR
    - [x] I added steps for local testing in the `Tests` section
    - [x] I added steps for the expected offline behavior in the `Offline steps` section
    - [x] I added steps for Staging and/or Production testing in the `QA steps` section
    - [x] I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
    - [x] I tested this PR with a [High Traffic account](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#high-traffic-accounts) against the staging or production API to ensure there are no regressions (e.g. long loading states that impact usability).
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I ran the tests on **all platforms** & verified they passed on:
    - [x] Android / native
    - [x] Android / Chrome
    - [x] iOS / native
    - [x] iOS / Safari
    - [x] MacOS / Chrome / Safari
    - [x] MacOS / Desktop
- [x] I verified there are no console errors (if there's a console error not related to the PR, report it or open an issue for it to be fixed)
- [x] I followed proper code patterns (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`)
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I followed the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I tested other components that can be impacted by my changes (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` are working as expected)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] I verified that if a function's arguments changed that all usages have also been updated correctly
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] I have checked off every checkbox in the PR author checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/28676406/210682323-9e9e0109-d6c0-4ad8-a957-1b43830bc265.mov

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/28676406/210684991-d9b7e9d1-b58b-4b42-825f-2f24e229b65a.mov

</details>

<details>
<summary>Mobile Web - Safari</summary>

[](https://user-images.githubusercontent.com/28676406/210682886-50ca06fb-8f2f-47d4-9445-67fdb6807485.mp4)

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/28676406/210685340-0b553385-a7f1-4af9-8012-8f0cb008aa9a.mov

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/28676406/210684964-d583ae63-4ff2-4830-877b-5162f64c1497.mov

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/28676406/210684958-8961791d-b3ce-49a2-8113-8b7c581ab9e8.mov

</details>

### CODE REVIEW

**Comment by Santhosh-Sellavel** [comment]
@danieldoglas Yes assign me & @pecanoro as reviewers.

**Comment by shonsirsha** [comment]
>>  @pecanoro , you should be assigned to this PR review since it was created from an issue you're the CME, right?


Yeah, unfortunately I can't change the reviewers (lacking permissions). I assume you could re-assign it to @pecanoro and @Santhosh-Sellavel though. 🙂

**Comment by Santhosh-Sellavel** [comment]
@shonsirsha 

The issue of not being linked properly is the problem here. 

Should be linked as follows
 `$ https://github.com/Expensify/App/issues/13599` 
 
 which would show as $ https://github.com/Expensify/App/issues/13599
 
 Please update the link, and keep a note of it. This is important as it's used for automating certain things, i.e assigning the correct reviewers, tracking PR deployment status on issues,  etc

**Review by Santhosh-Sellavel — COMMENTED** [review]
Adding my self as reviewer

**Comment by shonsirsha** [comment]
@Santhosh-Sellavel ok, done updated. Added a "#" infront of the issue's number. Haven't had this problem before (closed 2 PRs), so thanks for letting me know. Hope it could be reviewed now?

**Comment by Santhosh-Sellavel** [comment]
## Reviewer Checklist

- [ ] I have verified the author checklist is complete (all boxes are checked off).
- [ ] I verified the correct issue is linked in the `### Fixed Issues` section above
- [ ] I verified testing steps are clear and they cover the changes made in this PR
    - [ ] I verified the steps for local testing are in the `Tests` section
    - [ ] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [ ] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [ ] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [ ] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [ ] I verified tests pass on **all platforms** & I tested again on:
    - [ ] Android / native
    - [ ] Android / Chrome
    - [ ] iOS / native
    - [ ] iOS / Safari
    - [ ] MacOS / Chrome / Safari
    - [ ] MacOS / Desktop
- [ ] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [ ] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [ ] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [ ] I verified that comments were added to code that is not self explanatory
    - [ ] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [ ] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [ ] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [ ] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [ ] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [ ] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [ ] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [ ] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [ ] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [ ] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [ ] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [ ] If a new component is created I verified that:
    - [ ] A similar component doesn't exist in the codebase
    - [ ] All props are defined accurately and each prop has a `/** comment above it */`
    - [ ] The file is named correctly
    - [ ] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [ ] The only data being stored in the state is data necessary for rendering and nothing else
    - [ ] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [ ] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [ ] All JSX used for rendering exists in the render method
    - [ ] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [ ] If any new file was added I verified that:
    - [ ] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [ ] If a new CSS style is added I verified that:
    - [ ] A similar style doesn't already exist
    - [ ] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [ ] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [ ] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [ ] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [ ] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>



</details>

<details>
<summary>Mobile Web - Chrome</summary>



</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/85645967/211170495-758918d5-d93f-4962-bc9c-7b326bbca400.MP4

</details>

<details>
<summary>Desktop</summary>



</details>

<details>
<summary>iOS</summary>



</details>

<details>
<summary>Android</summary>



</details>

**Comment by shonsirsha** [comment]
Hello there 👋 

Can we get the review going? 🙂 cc @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment]
@shonsirsha Thanks for the bump, actually something is off in android, can you check?

I tried to scroll down to the end, few more empty scroll down even after reaching the end of the list. Now trying to scroll back it's not working right away

https://user-images.githubusercontent.com/85645967/211280768-5224fb3e-f0ca-4abe-9ab9-9c57e110b07e.mp4

**Comment by shonsirsha** [comment]
@Santhosh-Sellavel No worries.

Android you meant android app right? If so, the issue you mentioned also exists in `main`:


https://user-images.githubusercontent.com/28676406/211326778-9942bb2e-1858-449b-be1c-2af81b673f25.mov


Actually this issue also exists in production:


https://user-images.githubusercontent.com/28676406/211328730-ab127527-2135-486a-b680-4d8d2a7e2dcc.mp4


Tagging @pecanoro, would you be able to test it (if this issue exists in prod/main) to make sure that it's a separate issue (not related to this PR)?

Thx!

**Comment by shonsirsha** [comment]
Thanks @Santhosh-Sellavel, will wait on their final call then. Just my 2 cents, the problem that we have here on Android isn't exactly the same. Moreover, the issue was focusing on iOS scroll problem, and **Android (app)** wasn't mentioned at all in the issue,  It's an **mWeb** issue on iOS. **(iOS mWeb - Scroll behavior on some pages is inconsistent and broken)**. 

While it may look like that it's the same "scroll bug" on the surface, they aren't the same - I could try describing it this way:

1. On iOS the issue was body locking, which Ive explained in the issue & in the PR body (in short: sometimes, ios scrolls the actual html `body`, and not the list). This is on **mWeb**.
2. Here on android **(app, not mWeb!)**,  from my brief observation, the issue is user can't start scrolling up after spamming a scroll down to the list. **It already scrolls the list, not the html `body` (this is where it's different than ios').** A bit more explanation: the issue on Android here, to me it looks like a scroll down when dragged to the bottom, something (maybe an animation) will last for lets say 1s, and user should wait for 1s before they can scroll up. If the user spams their scrolling, lets say 10 times, they'd then have to wait ~10 seconds before they can scroll up without any problems. 


Frankly, these 2 sound like they're completely different issues to me.. 🤔

**Review by Santhosh-Sellavel — COMMENTED** [review]
@pecanoro 

The main issue discussed [here](https://github.com/Expensify/App/issues/13599#issuecomment-1367068970) is fixed, tests well. I run into another issue [here](https://github.com/Expensify/App/pull/14005#issuecomment-1375350420) it looks related and slightly different form the issue we are addressing here.

If you think both are different please merge this one as the main issue is solved and tests well, or do we need to wait to solve the other one too?, thanks!

**Review by pecanoro — APPROVED** [review]

**Comment by pecanoro** [comment]
I can attest the Android glitch is on prod as well, it's a bit of an edge glitch though since you have to consciously spam scrolling down. @Santhosh-Sellavel Can you post the bug on Slack? Maybe the team agrees to create an issue to fix it.

I will finish testing the PR and I will merge it if I can't find any other issues.

**Comment by Santhosh-Sellavel** [comment]
I'll report it on slack, thanks @pecanoro!

**Review by Santhosh-Sellavel — APPROVED** [review]

**Comment by pecanoro** [comment]
Unless I missed something, it seems to be working well!

**Comment by Santhosh-Sellavel** [comment]
🤦 Not sure How did I missed that, @shonsirsha can you add test steps please

**Comment by pecanoro** [comment]
Oh dammit, I remember noticing that when reviewing and forgot to post about it before merging.

**Comment by shonsirsha** [comment]
@mvtglobally @pecanoro @Santhosh-Sellavel sorry! I totally missed it as well. Added now!

**Pull request merged**
