### PR TITLE
Allow users to close their account

### PR DESCRIPTION
**Pull request by Julesssss**
### Details
Implement the 'Close account' feature under security settings. Users need to be able to close their accounts (with some exceptions) or Apple will block us from making new app updates. [Parent issue](https://github.com/Expensify/Expensify/issues/181420).

### Fixed Issues

$ https://github.com/Expensify/Expensify/issues/186628

### Tests

**1) Ensure that close account feature matches the design**
- Create a new user, validate them with the account validator tool
- Log in, navigate to Settings
- You should see a 'Security' submenu, click it
- You should see a 'Close Account' option, click it
- You should see a 'What can we do to improve' input field
- You should see a 'Type *** to confirm' input field, where *** is the users email/phone number
- The input and logic for detecting a match should NOT be case sensitive
- You should see a warning that this action cannot be undone, and it should be bold
- When you enter the users email or phone number in the bottom field, the 'Close account' button should become enabled

Screenshot_1641834168

**2) Ensure that new users can close their account**
- [You should probably do this test web to simplify the API validation step]
- Create a new user, validate them with the account validator tool
- Log in, navigate to Settings
- Enter a reason for leaving
- Enter the users' email or phone number
- Open a debugging window, to ensure you can review the API request details
- Click 'Close account'
- You should be logged out
- You should see an 'Account closed successfully' Growl
- The text entered into the reason field should have been sent via the API request

https://user-images.githubusercontent.com/10736861/148587673-aba9e67f-2d2e-44a7-9193-cda7a23ffdb1.mov

**3) Ensure that some users cannot close their account**
- Log in to an account that is awaiting reimbursement
- Navigate to Settings > Security > Close Account
- Attempt to close the account
- You should see a Modal stating that you are unable to close the account
- The Modal should contain a link to `https://community.expensify.com/discussion/4724/faq-why-cant-i-close-my-account`

https://user-images.githubusercontent.com/10736861/148587710-8b0f1e3f-39c2-402c-a754-2dbad6f8f4ef.mov

**4) Ensure that users with phone numbers have the option to close their account**
- Log in to an account which was set up with a phone number
- Navigate to Settings > Security > Close Account
- The input label should say `Type [NUMBER] to confirm`
- Enter the listed number, the 'Close Account' button should become active

https://user-images.githubusercontent.com/10736861/148807121-feec60a3-9ab6-4680-9a3d-761b35507dff.mov

### QA Steps

Run the three above tests

### Tested On

- [x] Web
- [x] Mobile Web
- [x] Desktop
- [x] iOS
- [x] Android

#### Web
Screenshot 2022-01-10 at 15 49 24

#### Mobile Web

Screenshot_1641833931

#### Desktop
Screenshot 2022-01-10 at 15 49 24

#### iOS

https://user-images.githubusercontent.com/10736861/148805980-2896d1ed-a952-4ff8-a55c-08395017ea32.mov

#### Android

Screenshot_1641834168

### CODE REVIEW

**Comment by Julesssss** [comment]
Hey @robertjchen 👋 

By the time I noticed that my original commit's parent was not from `main`, I had already rebased 😞 .

Usually I would simply rebase or cherry-pick to remove the useless commits (and I did attempt this), but because this PR has been in progress since before Christmas, and because I had already rebased onto a newer commit the conflicts were a complete nightmare.

But I'm happy to try cherry-picking tomorrow if you think it's necessary.

**Review by robertjchen — APPROVED** [review]
Perfect!!

**Comment by mvtglobally** [comment]
@robertjchen, We are unable to create a new Phone number accounts and team has a very limited number of such accounts available. Can you confirm what 1-2 environments do you want to run this QA on?

**Comment by Julesssss** [comment]
@mvtglobally ah, right. Please ignore the SMS test for now. I will retest once we re-enable the feature.

**Pull request merged**
